{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"textHintNothingDetected","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintNothingDetected"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textHintNothingDetected"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerTextConfiguration(py)textHintNothingDetected","role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when no document was detected."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintNothingDetected","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintNothingDetected"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Defaults to “Searching for document…”."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintnothingdetected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintnothingdetected"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 5.2.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration":{"title":"SBSDKUIFinderDocumentScannerTextConfiguration","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration","kind":"symbol","abstract":[{"text":"Configuration for the textual contents of the document scanning screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintNothingDetected":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthintnothingdetected","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintNothingDetected","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintNothingDetected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when no document was detected."}],"title":"textHintNothingDetected","navigatorTitle":[{"text":"textHintNothingDetected","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"textHintNothingDetected","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"textHintNothingDetected"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"textHintNothingDetected","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/title","value":"SBSDKUIFinderDocumentScannerTextConfiguration"},{"value":[{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/fragments","op":"replace"},{"value":"textHintNothingDetected","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintNothingDetected\/title"},{"value":[{"text":"textHintNothingDetected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintNothingDetected\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}