{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult\/recognitionstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult\/recognitionstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult"]]},"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"recognitionStatus","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerUIResult(py)recognitionStatus","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognitionStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckMagneticInkStripScanningStatus"}],"navigatorTitle":[{"text":"recognitionStatus","kind":"identifier"}],"role":"symbol"},"abstract":[{"text":"The status of the check recognition step.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult\/recognitionStatus","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCheckMagneticInkStripScanningStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckMagneticInkStripScanningStatus"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckMagneticInkStripScanningStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Check magnetic ink (MICR) strip scanning status."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus","title":"SBSDKCheckMagneticInkStripScanningStatus","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerUIResult":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult","abstract":[{"type":"text","text":"Configuration of the check scanner RTU UI result."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult","navigatorTitle":[{"text":"SBSDKUI2CheckScannerUIResult","kind":"identifier"}],"title":"SBSDKUI2CheckScannerUIResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerUIResult","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerUIResult/recognitionStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerUIResult\/recognitionStatus","navigatorTitle":[{"kind":"identifier","text":"recognitionStatus"}],"type":"topic","kind":"symbol","title":"recognitionStatus","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscanneruiresult\/recognitionstatus","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognitionStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCheckMagneticInkStripScanningStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckMagneticInkStripScanningStatus"}],"abstract":[{"type":"text","text":"The status of the check recognition step."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"recognitionStatus","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"recognitionStatus","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus","text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckMagneticInkStripScanningStatus"},{"text":" ","kind":"text"},{"text":"recognitionStatus","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/title","value":"SBSDKCheckMagneticInkStripScanningStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/fragments","value":[{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/navigatorTitle","value":[{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/title","value":"SBSDKUI2CheckScannerUIResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerUIResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult\/navigatorTitle","value":[{"text":"SBSDKUI2CheckScannerUIResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult~1recognitionStatus\/title","value":"recognitionStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerUIResult~1recognitionStatus\/fragments","value":[{"text":"recognitionStatus","kind":"identifier"}]}]}]}