{"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"sections":[],"kind":"symbol","abstract":[{"text":"Defines, if the confirmation dialog should be displayed or not before returning the results to the delegate.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration\/isResultWithConfirmationEnabled"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerBehaviorConfiguration(py)isResultWithConfirmationEnabled","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"isResultWithConfirmationEnabled"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isResultWithConfirmationEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","role":"symbol","title":"isResultWithConfirmationEnabled"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isResultWithConfirmationEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isresultwithconfirmationenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isresultwithconfirmationenabled"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerBehaviorConfiguration/isResultWithConfirmationEnabled":{"navigatorTitle":[{"kind":"identifier","text":"isResultWithConfirmationEnabled"}],"kind":"symbol","abstract":[{"type":"text","text":"Defines, if the confirmation dialog should be displayed or not before returning the results to the delegate."}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration\/isresultwithconfirmationenabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isResultWithConfirmationEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","title":"isResultWithConfirmationEnabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration\/isResultWithConfirmationEnabled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerBehaviorConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration","role":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerBehaviorConfiguration"}],"title":"SBSDKUIBarcodeScannerBehaviorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The configuration for the behavior of the RTU-UI barcode scanner."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"isResultWithConfirmationEnabled","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"isResultWithConfirmationEnabled"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"isResultWithConfirmationEnabled","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"isResultWithConfirmationEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration~1isResultWithConfirmationEnabled\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration~1isResultWithConfirmationEnabled\/fragments","value":[{"text":"isResultWithConfirmationEnabled","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/title","value":"SBSDKUIBarcodeScannerBehaviorConfiguration"},{"value":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/fragments"}]}]}