{"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy@SBSDKLicensePlateScannerStrategyClassic","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerStrategyClassic"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"classic"}],"role":"symbol","title":"SBSDKLicensePlateScannerStrategy.classic"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"classic","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Classic strategy using heuristic algorithms to find a license plate in an image."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy\/classic"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy\/classic"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy\/classic"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerStrategy/classic":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy\/classic","kind":"symbol","abstract":[{"text":"Classic strategy using heuristic algorithms to find a license plate in an image.","type":"text"}],"role":"symbol","title":"SBSDKLicensePlateScannerStrategy.classic","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"classic"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy\/classic","navigatorTitle":[{"text":"SBSDKLicensePlateScannerStrategyClassic","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerStrategy":{"abstract":[{"text":"The strategy being used to scan a license plate. *\/","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy","navigatorTitle":[{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"title":"SBSDKLicensePlateScannerStrategy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKLicensePlateScannerStrategyClassic","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKLicensePlateScannerStrategyClassic","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKLicensePlateScannerStrategyClassic"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy~1classic\/title","value":"SBSDKLicensePlateScannerStrategyClassic"},{"op":"replace","value":[{"text":"SBSDKLicensePlateScannerStrategyClassic","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy~1classic\/fragments"},{"op":"replace","value":"SBSDKLicensePlateScannerStrategy","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/title"},{"value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerStrategy"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerStrategy"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}