{"abstract":[{"text":"Machine learning based strategy using neural networks to find a license plate in an image.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy@SBSDKLicensePlateScannerStrategyML","title":"SBSDKLicensePlateScannerStrategy.ML","navigatorTitle":[{"text":"SBSDKLicensePlateScannerStrategyML","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ML","kind":"identifier"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy\/ml"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy\/ml"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ML","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy\/ML","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerStrategy":{"abstract":[{"text":"The strategy being used to scan a license plate. *\/","type":"text"}],"title":"SBSDKLicensePlateScannerStrategy","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerStrategy/ML":{"navigatorTitle":[{"text":"SBSDKLicensePlateScannerStrategyML","kind":"identifier"}],"title":"SBSDKLicensePlateScannerStrategy.ML","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy\/ml","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ML"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy\/ML","abstract":[{"text":"Machine learning based strategy using neural networks to find a license plate in an image.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKLicensePlateScannerStrategyML","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerStrategyML"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKLicensePlateScannerStrategyML","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/title","value":"SBSDKLicensePlateScannerStrategy","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/fragments","value":[{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKLicensePlateScannerStrategyML","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy~1ML\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy~1ML\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerStrategyML"}]}]}]}