{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSourceType\/api","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSourceType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesourcetype\/api"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesourcetype\/api"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageSourceType@SBSDKImageSourceTypeApi","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"api","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSourceTypeApi"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKImageSourceType.api","roleHeading":"Case","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"api"}]}]}],"abstract":[{"type":"text","text":"ImageRef was created by a call to an SDK feature, such as a scanner, image processor, etc."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSourceType":{"type":"topic","abstract":[{"type":"text","text":"The type of source which originated the underlying image."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSourceType","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesourcetype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageSourceType","kind":"identifier"}],"title":"SBSDKImageSourceType","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSourceType/api":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"api","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageSourceTypeApi","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSourceType\/api","title":"SBSDKImageSourceType.api","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesourcetype\/api","abstract":[{"text":"ImageRef was created by a call to an SDK feature, such as a scanner, image processor, etc.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKImageSourceTypeApi","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKImageSourceTypeApi","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKImageSourceTypeApi","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKImageSourceType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType\/navigatorTitle"},{"value":"SBSDKImageSourceTypeApi","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType~1api\/title"},{"value":[{"text":"SBSDKImageSourceTypeApi","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType~1api\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}