{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithOverallSuspiciousData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"overallSuspiciousData","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKFieldSuspiciousDataVerificationReport *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fieldDetails","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithOverallSuspiciousData:fieldDetails:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverallSuspiciousData:fieldDetails:"}],"title":"initWithOverallSuspiciousData:fieldDetails:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSuspiciousDataVerificationReport(im)initWithOverallSuspiciousData:fieldDetails:"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport\/initWithOverallSuspiciousData:fieldDetails:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/initwithoverallsuspiciousdata:fielddetails:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport":{"abstract":[{"text":"Report of the suspicious data document verification.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSuspiciousDataVerificationReport"}],"title":"SBSDKSuspiciousDataVerificationReport","navigatorTitle":[{"kind":"identifier","text":"SBSDKSuspiciousDataVerificationReport"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport/initWithOverallSuspiciousData:fieldDetails:":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithOverallSuspiciousData:fieldDetails:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverallSuspiciousData:fieldDetails:"}],"title":"initWithOverallSuspiciousData:fieldDetails:","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport\/initWithOverallSuspiciousData:fieldDetails:","url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/initwithoverallsuspiciousdata:fielddetails:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKSuspiciousDataVerificationReport","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/title"},{"op":"replace","value":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKSuspiciousDataVerificationReport"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}