{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport\/isEqual:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method","title":"isEqual:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSuspiciousDataVerificationReport(im)isEqual:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport":{"kind":"symbol","abstract":[{"type":"text","text":"Report of the suspicious data document verification."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSuspiciousDataVerificationReport"}],"title":"SBSDKSuspiciousDataVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport","navigatorTitle":[{"kind":"identifier","text":"SBSDKSuspiciousDataVerificationReport"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport/isEqual:":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport\/isEqual:","url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/isequal:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKSuspiciousDataVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/title"},{"value":[{"kind":"identifier","text":"SBSDKSuspiciousDataVerificationReport"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/fragments"},{"value":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}