{"abstract":[{"text":"The default configuration.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration(cpy)defaultConfiguration","title":"defaultConfiguration","roleHeading":"Type Property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration\/defaultConfiguration","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"typeIdentifier","text":"SBSDKVehicleIdentificationNumberScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A descriptor-like class to configure "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration","navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScanner":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"abstract":[{"text":"A class to scan video frames or still images for vehicle identification numbers and validate it.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScanner","navigatorTitle":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscanner","title":"SBSDKVehicleIdentificationNumberScanner","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerConfiguration/defaultConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerconfiguration\/defaultconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration\/defaultConfiguration","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"The default configuration.","type":"text"}],"kind":"symbol","title":"defaultConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"defaultConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"defaultConfiguration"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKVehicleIdentificationNumberScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/title","value":"SBSDKVehicleIdentificationNumberScannerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/title","value":"SBSDKVehicleIdentificationNumberScanner"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/fragments","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScanner\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScanner"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration~1defaultConfiguration\/title","value":"defaultConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerConfiguration~1defaultConfiguration\/fragments","op":"replace","value":[{"text":"defaultConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}