{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode"]]},"sections":[],"abstract":[{"type":"text","text":"Encryption\/Decryption is used when loading\/saving an image if a crypting provider is set using"},{"type":"text","text":" "},{"code":"ImageRef.setStorageCryptingProvider","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ifAvailable","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode\/ifAvailable","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"SBSDKEncryptionMode.ifAvailable","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode@SBSDKEncryptionModeIfAvailable","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeIfAvailable"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ifAvailable"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkencryptionmode\/ifavailable"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkencryptionmode\/ifavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncryptionMode":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","title":"SBSDKEncryptionMode","url":"\/documentation\/scanbotsdk\/sbsdkencryptionmode","kind":"symbol","role":"symbol","abstract":[{"text":"Encryption\/Decryption mode to be used when an image is loaded\/saved.","type":"text"}],"navigatorTitle":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncryptionMode/ifAvailable":{"abstract":[{"type":"text","text":"Encryption\/Decryption is used when loading\/saving an image if a crypting provider is set using"},{"type":"text","text":" "},{"type":"codeVoice","code":"ImageRef.setStorageCryptingProvider"},{"text":".","type":"text"}],"title":"SBSDKEncryptionMode.ifAvailable","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ifAvailable"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeIfAvailable"}],"url":"\/documentation\/scanbotsdk\/sbsdkencryptionmode\/ifavailable","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode\/ifAvailable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKEncryptionModeIfAvailable","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKEncryptionModeIfAvailable"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKEncryptionModeIfAvailable"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/title","value":"SBSDKEncryptionMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/fragments","op":"replace","value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}]},{"op":"replace","value":"SBSDKEncryptionModeIfAvailable","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode~1ifAvailable\/title"},{"value":[{"text":"SBSDKEncryptionModeIfAvailable","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode~1ifAvailable\/fragments","op":"replace"}]}]}