{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"SBSDKUI2TextPatternScannerScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenConfiguration"},{"kind":"text","text":" *) "},{"text":"fromJsonWithJson:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenConfiguration(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration\/fromjsonwithjson:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration\/fromJsonWithJson:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenConfiguration":{"role":"symbol","abstract":[{"text":"Configuration of the screen for detecting generic text data.","type":"text"}],"kind":"symbol","type":"topic","title":"SBSDKUI2TextPatternScannerScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternScannerScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenConfiguration/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration\/fromjsonwithjson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[],"title":"fromJsonWithJson:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2TextPatternScannerScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2TextPatternScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/navigatorTitle","op":"replace"}]}]}