{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler()"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Sets up the default license failure handler which is being called when the license is invalid or the trial time expired.","type":"text"},{"text":" ","type":"text"},{"text":"The default handler logs the license error to the console.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/scanbot\/setupdefaultlicensefailurehandler()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/scanbot\/setupdefaultlicensefailurehandler()"]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":"()"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)Scanbot(cm)setupDefaultLicenseFailureHandler","role":"symbol","title":"setupDefaultLicenseFailureHandler()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"}],"modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot":{"navigatorTitle":[{"kind":"identifier","text":"Scanbot"}],"url":"\/documentation\/scanbotsdk\/scanbot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scanbot"}],"role":"symbol","title":"Scanbot","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot","abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setupDefaultLicenseFailureHandler()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler()","url":"\/documentation\/scanbotsdk\/scanbot\/setupdefaultlicensefailurehandler()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"()","kind":"text"}],"title":"setupDefaultLicenseFailureHandler()","navigatorTitle":[{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Sets up the default license failure handler which is being called when the license is invalid or the trial time expired."},{"type":"text","text":" "},{"type":"text","text":"The default handler logs the license error to the console."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setupDefaultLicenseFailureHandler","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"Scanbot","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/title"},{"value":[{"text":"Scanbot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/fragments"},{"value":[{"text":"Scanbot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/navigatorTitle"},{"value":"setupDefaultLicenseFailureHandler","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setupDefaultLicenseFailureHandler()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setupDefaultLicenseFailureHandler()\/fragments"}]}]}