{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldIntValue(im)initWithValue:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithValue:"}],"title":"initWithValue:","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue\/initWithValue:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuserfieldintvalue\/initwithvalue:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldIntValue":{"title":"SBSDKUserFieldIntValue","type":"topic","abstract":[{"type":"text","text":"32-bit int value (TIFF_LONG)."}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuserfieldintvalue","navigatorTitle":[{"text":"SBSDKUserFieldIntValue","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUserFieldIntValue"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldIntValue/initWithValue:":{"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuserfieldintvalue\/initwithvalue:","kind":"symbol","title":"initWithValue:","fragments":[{"kind":"text","text":"- "},{"text":"initWithValue:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue\/initWithValue:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldIntValue\/title","op":"replace","value":"SBSDKUserFieldIntValue"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldIntValue\/fragments","value":[{"kind":"identifier","text":"SBSDKUserFieldIntValue"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldIntValue\/navigatorTitle","value":[{"text":"SBSDKUserFieldIntValue","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}