{"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTextResult:barcodeResult:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerUIResult(im)initWithTextResult:barcodeResult:","title":"initWithTextResult:barcodeResult:","navigatorTitle":[{"text":"initWithTextResult:barcodeResult:","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult\/initwithtextresult:barcoderesult:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithTextResult:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKTextPatternScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textResult"},{"kind":"text","text":" "},{"text":"barcodeResult:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult","text":"SBSDKVINBarcodeResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult"},{"text":" *) ","kind":"text"},{"text":"barcodeResult","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult\/initWithTextResult:barcodeResult:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerUIResult/initWithTextResult:barcodeResult:":{"role":"symbol","navigatorTitle":[{"text":"initWithTextResult:barcodeResult:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult\/initWithTextResult:barcodeResult:","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult\/initwithtextresult:barcoderesult:","kind":"symbol","type":"topic","title":"initWithTextResult:barcodeResult:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"initWithTextResult:barcodeResult:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","abstract":[{"text":"The result of the text line recognition.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"title":"SBSDKTextPatternScannerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerUIResult":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerUIResult"}],"abstract":[{"text":"Configuration of the generic text scanner RTU UI result.","type":"text"}],"title":"SBSDKUI2VINScannerUIResult","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeResult":{"type":"topic","title":"SBSDKVINBarcodeResult","abstract":[{"type":"text","text":"Result of the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","navigatorTitle":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult"}},"variantOverrides":[{"patch":[{"value":"SBSDKTextPatternScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}]},{"value":[{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/title","value":"SBSDKUI2VINScannerUIResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/fragments","op":"replace","value":[{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2VINScannerUIResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/navigatorTitle"},{"value":"SBSDKVINBarcodeResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/fragments","value":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}