{"abstract":[{"type":"text","text":"Pauses the delivery of frames to the delegate."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/pauseScanning()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/pausescanning()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/pausescanning()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pauseScanning","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"title":"pauseScanning()","navigatorTitle":[{"kind":"identifier","text":"pauseScanning"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraSession(im)pauseScanning","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pauseScanning","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/pauseScanning()":{"abstract":[{"type":"text","text":"Pauses the delivery of frames to the delegate."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pauseScanning"}],"kind":"symbol","title":"pauseScanning()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/pausescanning()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/pauseScanning()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pauseScanning","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession":{"role":"symbol","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraSession"}],"title":"SBSDKCameraSession","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"pauseScanning","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"pauseScanning","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"pauseScanning","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1pauseScanning()\/title","value":"pauseScanning"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pauseScanning"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1pauseScanning()\/fragments"},{"value":"SBSDKCameraSession","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"op":"replace","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/navigatorTitle"}]}]}