{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/isEqual:"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentFlowAppearanceConfiguration(im)isEqual:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"isEqual:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/isequal:"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"title":"SBSDKUI2DocumentFlowAppearanceConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the general appearance."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentFlowAppearanceConfiguration/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentFlowAppearanceConfiguration\/isEqual:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentflowappearanceconfiguration\/isequal:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/title","value":"SBSDKUI2DocumentFlowAppearanceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentFlowAppearanceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentFlowAppearanceConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentFlowAppearanceConfiguration","kind":"identifier"}]}]}]}