{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/balanced","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"balanced"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2CapturePhotoQualityPrioritization.balanced","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization@SBSDKUI2CapturePhotoQualityPrioritizationBalanced","symbolKind":"case","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/balanced"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/balanced"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/balanced":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"balanced"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/balanced","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/balanced","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced"}],"title":"SBSDKUI2CapturePhotoQualityPrioritization.balanced","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"title":"SBSDKUI2CapturePhotoQualityPrioritization","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization","type":"topic","abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1balanced\/title","value":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization~1balanced\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title","op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritization"},{"value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments"},{"value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}