{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine\/recognize(from:completion:)-5h2yb"},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngine(im)recognizeFromDocument:completion:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier","text":"SBSDKDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ()) -> "},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"recognizeFromDocument:completion:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"recognize(from:completion:)"},"abstract":[{"text":"Recognizes characters on all pages of the document and passes the result, or the error, to the completion handler.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:completion:)-5h2yb"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:completion:)-5h2yb"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":"(recognizeFromDocument:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"document","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"SBSDKOCRResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ()) -> "},{"text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The document containing the pages to run the optical character recognition on."}],"type":"paragraph"}],"name":"document"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion handler, delivering either the OCR result or an error.","type":"text"}]}],"name":"completion"}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The progress object that can be used to observe the progress or cancel the operation, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" in case of an error."}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The recognition runs asynchronously on a dedicated concurrent queue and the completion handler is called on the main thread."}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngine":{"url":"\/documentation\/scanbotsdk\/sbsdkocrengine","navigatorTitle":[{"text":"SBSDKOCREngine","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine","abstract":[{"text":"A class to perform optical character recognition (text) on an image (OCR).","type":"text"}],"type":"topic","title":"SBSDKOCREngine","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOCREngine","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngine/recognize(from:completion:)-5h2yb":{"navigatorTitle":[{"kind":"identifier","text":"recognizeFromDocument:completion:"}],"type":"topic","abstract":[{"text":"Recognizes characters on all pages of the document and passes the result, or the error, to the completion handler.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:completion:)-5h2yb","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ()) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"text":"?","kind":"text"}],"role":"symbol","title":"recognize(from:completion:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine\/recognize(from:completion:)-5h2yb"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","title":"SBSDKDocumentPage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPage","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResult":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresult","navigatorTitle":[{"text":"SBSDKOCRResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","abstract":[{"text":"The result of an optical character recognition.","type":"text"}],"type":"topic","title":"SBSDKOCRResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCRResult"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"title":"SBSDKProgress","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgress"}],"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","url":"\/documentation\/scanbotsdk\/sbsdkprogress"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"title":"SBSDKDocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocument","kind":"identifier"}],"abstract":[{"text":"A thread-safe, mutable container for scanned pages of type ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"reference"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocument","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"recognizeFromDocument:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeFromDocument:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","kind":"typeIdentifier","text":"SBSDKProgress"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"recognizeFromDocument:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"SBSDKOCRResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The document containing the pages to run the optical character recognition on.","type":"text"}],"type":"paragraph"}],"name":"document"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion handler, delivering either the OCR result or an error."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The progress object that can be used to observe the progress or cancel the operation, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" in case of an error."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"SBSDKOCREngine","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/fragments","value":[{"text":"SBSDKOCREngine","kind":"identifier"}]},{"value":[{"text":"SBSDKOCREngine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/navigatorTitle"},{"value":"recognizeFromDocument:completion:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine~1recognize(from:completion:)-5h2yb\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recognizeFromDocument:completion:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine~1recognize(from:completion:)-5h2yb\/fragments","op":"replace"},{"value":"SBSDKDocumentPage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/title","op":"replace","value":"SBSDKOCRResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKOCRResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOCRResult"}]},{"op":"replace","value":"SBSDKProgress","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments","value":[{"kind":"identifier","text":"SBSDKProgress"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title","value":"SBSDKDocument"},{"value":[{"text":"SBSDKDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}