{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Not all required fields were found or confirmed."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incomplete"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus\/incomplete","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus"]]},"metadata":{"title":"SBSDKCreditCardScanningStatus.incomplete","roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incomplete","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCreditCardScanningStatusIncomplete","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCreditCardScanningStatus@SBSDKCreditCardScanningStatusIncomplete","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus\/incomplete"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus\/incomplete"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningStatus/incomplete":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus\/incomplete","abstract":[{"type":"text","text":"Not all required fields were found or confirmed."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus\/incomplete","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incomplete","kind":"identifier"}],"type":"topic","title":"SBSDKCreditCardScanningStatus.incomplete","kind":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScanningStatusIncomplete","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningstatus","title":"SBSDKCreditCardScanningStatus","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"The status of the scanning process."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKCreditCardScanningStatusIncomplete"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKCreditCardScanningStatusIncomplete","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKCreditCardScanningStatusIncomplete"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus~1incomplete\/title","value":"SBSDKCreditCardScanningStatusIncomplete"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus~1incomplete\/fragments","value":[{"kind":"identifier","text":"SBSDKCreditCardScanningStatusIncomplete"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/title","value":"SBSDKCreditCardScanningStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/fragments","value":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningStatus\/navigatorTitle","value":[{"text":"SBSDKCreditCardScanningStatus","kind":"identifier"}]}]}]}