{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/hash","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/hash"]}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult(py)hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","title":"hash","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/hash","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/hash","abstract":[],"title":"hash","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult","title":"SBSDKDocumentQualityAnalyzerResult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"abstract":[{"text":"Result of document quality analysis. It can be used to determine, e.g., if a document is good enough to be used for OCR processing.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/title","value":"SBSDKDocumentQualityAnalyzerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/fragments","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}