{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountcapturemode\/capturedimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountcapturemode\/capturedimage"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountCaptureMode"]]},"abstract":[{"text":"Captures a still image and detects barcodes on it.","type":"text"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountCaptureModeCapturedImage","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"SBSDKBarcodeScanAndCountCaptureMode.capturedImage","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeScanAndCountCaptureMode@SBSDKBarcodeScanAndCountCaptureModeCapturedImage","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedImage"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountCaptureMode\/capturedImage"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"capturedImage"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountCaptureMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountcapturemode","type":"topic","abstract":[{"type":"text","text":"The capture mode of the barcode scan and count."}],"kind":"symbol","title":"SBSDKBarcodeScanAndCountCaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountCaptureMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountCaptureMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountCaptureMode/capturedImage":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountcapturemode\/capturedimage","title":"SBSDKBarcodeScanAndCountCaptureMode.capturedImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountCaptureMode\/capturedImage","abstract":[{"type":"text","text":"Captures a still image and detects barcodes on it."}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"capturedImage"}],"navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountCaptureModeCapturedImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeScanAndCountCaptureModeCapturedImage","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountCaptureModeCapturedImage","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKBarcodeScanAndCountCaptureModeCapturedImage","kind":"identifier"}],"languages":["occ"]}]}},{"value":"SBSDKBarcodeScanAndCountCaptureMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountCaptureMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountCaptureMode\/fragments"},{"op":"replace","value":"SBSDKBarcodeScanAndCountCaptureModeCapturedImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountCaptureMode~1capturedImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountCaptureMode~1capturedImage\/fragments","value":[{"text":"SBSDKBarcodeScanAndCountCaptureModeCapturedImage","kind":"identifier"}]}]}]}