{"abstract":[{"type":"text","text":"Uses the last frame form the camera input to detect barcodes on."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountCaptureMode"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountCaptureMode\/videoFrame","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountcapturemode\/videoframe"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountcapturemode\/videoframe"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoFrame","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame"}],"title":"SBSDKBarcodeScanAndCountCaptureMode.videoFrame","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeScanAndCountCaptureMode@SBSDKBarcodeScanAndCountCaptureModeVideoFrame","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFrame"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountCaptureMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountcapturemode","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"title":"SBSDKBarcodeScanAndCountCaptureMode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountCaptureMode","abstract":[{"text":"The capture mode of the barcode scan and count.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountCaptureMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountCaptureMode/videoFrame":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountcapturemode\/videoframe","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame","kind":"identifier"}],"title":"SBSDKBarcodeScanAndCountCaptureMode.videoFrame","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountCaptureMode\/videoFrame","abstract":[{"type":"text","text":"Uses the last frame form the camera input to detect barcodes on."}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoFrame","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountCaptureMode\/title","op":"replace","value":"SBSDKBarcodeScanAndCountCaptureMode"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountCaptureMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountCaptureMode~1videoFrame\/title","value":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountCaptureMode~1videoFrame\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}