{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatusDetected"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detected","kind":"identifier"}],"roleHeading":"Case","role":"symbol","title":"SBSDKScannerStatus.detected","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKScannerStatus@SBSDKScannerStatusDetected","symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"detected","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/detected"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/detected"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The scanner has detected something."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/detected","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus":{"abstract":[{"type":"text","text":"This enum describes the possible scanning states of any scanner."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus","title":"SBSDKScannerStatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus/detected":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/detected","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKScannerStatusDetected","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detected","kind":"identifier"}],"title":"SBSDKScannerStatus.detected","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/detected","abstract":[{"type":"text","text":"The scanner has detected something."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKScannerStatusDetected","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKScannerStatusDetected"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKScannerStatusDetected"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKScannerStatus","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"op":"replace"},{"value":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus\/navigatorTitle"},{"value":"SBSDKScannerStatusDetected","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus~1detected\/title"},{"value":[{"text":"SBSDKScannerStatusDetected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus~1detected\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}