{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/firstName"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName"]]},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerFieldName@SBSDKMachineReadableZoneRecognizerFieldNameFirstName","title":"SBSDKMachineReadableZoneRecognizerFieldName.firstName","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldNameFirstName"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstName","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The field describes the first name."}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/firstname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/firstname"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName":{"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"abstract":[{"type":"text","text":"Type classifiers for machine-readable-zone fields."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName","title":"SBSDKMachineReadableZoneRecognizerFieldName","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerFieldName","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerFieldName/firstName":{"type":"topic","title":"SBSDKMachineReadableZoneRecognizerFieldName.firstName","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerFieldName\/firstName","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerfieldname\/firstname","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameFirstName","kind":"identifier"}],"abstract":[{"type":"text","text":"The field describes the first name."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstName","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMachineReadableZoneRecognizerFieldNameFirstName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameFirstName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameFirstName","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/title","value":"SBSDKMachineReadableZoneRecognizerFieldName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerFieldName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1firstName\/title","value":"SBSDKMachineReadableZoneRecognizerFieldNameFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerFieldName~1firstName\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerFieldNameFirstName","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}