{"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldIntValue(cm)fromJsonWithJson:","symbolKind":"method","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"roleHeading":"Type Method","title":"fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuserfieldintvalue\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldIntValue","text":"SBSDKUserFieldIntValue","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue\/fromJsonWithJson:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldIntValue/fromJsonWithJson:":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkuserfieldintvalue\/fromjsonwithjson:","abstract":[],"title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldIntValue":{"type":"topic","kind":"symbol","abstract":[{"text":"32-bit int value (TIFF_LONG).","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldIntValue","navigatorTitle":[{"text":"SBSDKUserFieldIntValue","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUserFieldIntValue","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuserfieldintvalue","title":"SBSDKUserFieldIntValue"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldIntValue\/title","value":"SBSDKUserFieldIntValue","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldIntValue\/fragments","value":[{"text":"SBSDKUserFieldIntValue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldIntValue\/navigatorTitle","value":[{"text":"SBSDKUserFieldIntValue","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}