{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"capturedImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"label","content":[{"type":"paragraph","inlineContent":[{"text":"The label to describe the mock data.","type":"text"}]}]},{"name":"imageURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A web or file URL to an image file to be used to feed the video stream of simulated camera device."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A web or file URL to an image to be used on simulated camera devices when capturing a still image. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the current frame of the ","type":"text"},{"type":"codeVoice","code":"imageURL"},{"type":"text","text":" is returned when capturing a still image."}]}],"name":"capturedImageURL"},{"content":[{"inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame."}],"type":"paragraph"}],"name":"refreshOnEachFrame"}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"init","role":"symbol","title":"init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKSimulatedCameraMockData(im)initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"capturedImageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"roleHeading":"Initializer"},"abstract":[{"type":"text","text":"Initializes mock data for a simulated camera device from URLs."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData":{"title":"SBSDKSimulatedCameraMockData","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata","abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSimulatedCameraMockData/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)","navigatorTitle":[{"kind":"identifier","text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:"}],"type":"topic","title":"init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"capturedImageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"text":"Initializes mock data for a simulated camera device from URLs.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithLabel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"label","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"imageURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"imageURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"capturedImageURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"capturedImageURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"refreshOnEachFrame","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"label","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The label to describe the mock data."}]}]},{"name":"imageURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A web or file URL to an image file to be used to feed the video stream of simulated camera device."}]}]},{"name":"capturedImageURL","content":[{"inlineContent":[{"type":"text","text":"A web or file URL to an image to be used on simulated camera devices when capturing a still image. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", the current frame of the "},{"type":"codeVoice","code":"imageURL"},{"type":"text","text":" is returned when capturing a still image."}],"type":"paragraph"}]},{"name":"refreshOnEachFrame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame."}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/title","value":"SBSDKSimulatedCameraMockData","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/fragments","value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/title","value":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"op":"replace"}]}]}