{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/decryptdatafromurl(_:)-41buv"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/decryptdatafromurl(_:)-41buv"]}],"metadata":{"title":"decryptDataFromURL(_:)","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting(im)decryptDataFromURL:error:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptDataFromURL","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"decryptDataFromURL:error:","kind":"identifier"}],"required":true},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-41buv","interfaceLanguage":"swift"},"kind":"symbol","defaultImplementationsSections":[{"anchor":"SBSDKStorageCrypting-Implementations","title":"SBSDKStorageCrypting Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-2qxtm"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Decrypts the data at the given URL and returns it.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(decryptDataFromURL:error:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptDataFromURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}]}]},{"kind":"parameters","parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL that contains the data to be decrypted."}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The decrypted data.","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting/decryptDataFromURL(_:)-41buv":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptDataFromURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-41buv","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/decryptdatafromurl(_:)-41buv","navigatorTitle":[{"text":"decryptDataFromURL:error:","kind":"identifier"}],"defaultImplementations":1,"abstract":[{"type":"text","text":"Decrypts the data at the given URL and returns it."}],"title":"decryptDataFromURL(_:)","required":true,"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting/decryptDataFromURL(_:)-2qxtm":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptDataFromURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/decryptDataFromURL(_:)-2qxtm","kind":"symbol","title":"decryptDataFromURL(_:)","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/decryptdatafromurl(_:)-2qxtm","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" inherits "},{"type":"codeVoice","code":"NSObject"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"type":"topic","role":"symbol","abstract":[{"text":"Decrypts the data at the given URL and returns it.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"title":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","kind":"symbol","navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"decryptDataFromURL:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"decryptDataFromURL:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"decryptDataFromURL:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"url","content":[{"inlineContent":[{"type":"text","text":"The URL that contains the data to be decrypted."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The decrypted data."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting~1decryptDataFromURL(_:)-41buv\/title","value":"decryptDataFromURL:error:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting~1decryptDataFromURL(_:)-41buv\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decryptDataFromURL:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title","value":"SBSDKStorageCrypting"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]}]}]}