{"metadata":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoIntroImage(im)copyWithZone:","title":"copyWithZone:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage\/copyWithZone:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2nointroimage\/copywithzone:"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoIntroImage/copyWithZone:":{"kind":"symbol","title":"copyWithZone:","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2nointroimage\/copywithzone:","role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage\/copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoIntroImage":{"type":"topic","title":"SBSDKUI2NoIntroImage","abstract":[{"text":"No image for the introduction screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoIntroImage","navigatorTitle":[{"text":"SBSDKUI2NoIntroImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NoIntroImage","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2nointroimage"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage\/title","value":"SBSDKUI2NoIntroImage","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2NoIntroImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoIntroImage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2NoIntroImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}