{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage"]]},"metadata":{"title":"init(storageLocation:)","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:"}],"symbolKind":"init","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKKeyedImageStorage(im)initWithStorageLocation:","roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"text":"?)","kind":"text"}]},"sections":[],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"SBSDKKeyedImageStorage"},{"text":" at the given storage location.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"? = SBSDKStorageLocation())"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}],"type":"paragraph"}],"name":"storageLocation"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage","navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"title":"SBSDKKeyedImageStorage","kind":"symbol","abstract":[{"text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Manages images in a dictionary-like fashion."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/init(storageLocation:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:)","abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"SBSDKKeyedImageStorage"},{"type":"text","text":" at the given storage location."}],"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:"}],"role":"symbol","title":"init(storageLocation:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageLocation":{"title":"SBSDKStorageLocation","abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragelocation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageLocation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithStorageLocation:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStorageLocation:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithStorageLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"storageLocation","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"storageLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}]}]}]}},{"value":"SBSDKKeyedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/fragments","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/navigatorTitle","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"op":"replace"},{"value":"initWithStorageLocation:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithStorageLocation:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/title","value":"SBSDKStorageLocation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},{"value":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}