{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"usedDiskSpaceInBytes()","navigatorTitle":[{"kind":"identifier","text":"usedDiskSpaceInBytes"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKDeviceInformation(cm)usedDiskSpaceInBytes","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}],"roleHeading":"Type Method"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The amount of used disk space of the device in bytes."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usedDiskSpaceInBytes","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount of used disk space of the device in bytes. In case of error the return value is -1."}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceInformation/usedDiskSpaceInBytes()":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()","title":"usedDiskSpaceInBytes()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()","navigatorTitle":[{"text":"usedDiskSpaceInBytes","kind":"identifier"}],"abstract":[{"type":"text","text":"The amount of used disk space of the device in bytes."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usedDiskSpaceInBytes","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceInformation":{"title":"SBSDKDeviceInformation","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdeviceinformation","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceInformation","kind":"identifier"}],"abstract":[{"type":"text","text":"Helper class that delivers information about the used iOS device."}],"navigatorTitle":[{"text":"SBSDKDeviceInformation","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"usedDiskSpaceInBytes","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"usedDiskSpaceInBytes"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier","text":"int64_t"},{"kind":"text","text":") "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount of used disk space of the device in bytes. In case of error the return value is -1."}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"usedDiskSpaceInBytes","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation~1usedDiskSpaceInBytes()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"usedDiskSpaceInBytes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation~1usedDiskSpaceInBytes()\/fragments","op":"replace"},{"value":"SBSDKDeviceInformation","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/fragments","op":"replace"},{"value":[{"text":"SBSDKDeviceInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceInformation\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}