{"metadata":{"title":"tooDark","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"tooDark","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerGuidanceStates(py)tooDark","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tooDark","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/toodark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/toodark"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/tooDark"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tooDark","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is “?creditCardUserGuidanceTooDark”","type":"text"}]}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates"]]},"abstract":[{"text":"The user guidance text displayed when it is too dark to capture an adequate image.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"abstract":[{"text":"Configure the captions of the user guidance hints for different scanning states.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates","role":"symbol","title":"SBSDKUI2CreditCardScannerGuidanceStates","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/tooDark":{"title":"tooDark","navigatorTitle":[{"kind":"identifier","text":"tooDark"}],"abstract":[{"type":"text","text":"The user guidance text displayed when it is too dark to capture an adequate image."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooDark"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/toodark","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/tooDark","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"tooDark","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"tooDark","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tooDark"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2CreditCardScannerGuidanceStates","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/title"},{"value":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/navigatorTitle"},{"op":"replace","value":"tooDark","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1tooDark\/title"},{"op":"replace","value":[{"text":"tooDark","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1tooDark\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}