{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"supportedInterfaceOrientations","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerViewController(py)supportedInterfaceOrientations","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"supportedInterfaceOrientations"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/supportedInterfaceOrientations"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/supportedinterfaceorientations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedInterfaceOrientations"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController/supportedInterfaceOrientations":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/supportedinterfaceorientations","title":"supportedInterfaceOrientations","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/supportedInterfaceOrientations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController":{"kind":"symbol","title":"SBSDKUITextPatternScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to scan and validate a small rectangular text area in realtime.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/title","value":"SBSDKUITextPatternScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}