{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningparameters\/hash"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters\/hash","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningParameters(py)hash","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningParameters/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters\/hash","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash","role":"symbol","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningparameters\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningParameters":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningparameters","title":"SBSDKMedicalCertificateScanningParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScanningParameters"}],"type":"topic","abstract":[{"type":"text","text":"Parameters for the medical certificate scanning. The scanner supports"},{"type":"text","text":" "},{"type":"text","text":"Form 1 (Arbeitsunfähigkeitsbescheinigung) and"},{"type":"text","text":" "},{"type":"text","text":"Form 21a (Ärztliche Bescheinigung für den Bezug von Krankengeld bei Erkrankung eines Kindes)"},{"type":"text","text":" "},{"type":"text","text":"from the KBV (Kassenärztliche Bundesvereinigung) list of forms."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningParameters","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningParameters"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKMedicalCertificateScanningParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningParameters"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/fragments"},{"value":[{"text":"SBSDKMedicalCertificateScanningParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningParameters\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}