{"sections":[],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2FinderStrokedStyle(im)initWithStrokeColor:strokeWidth:cornerRadius:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithStrokeColor:strokeWidth:cornerRadius:","kind":"identifier"}],"symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"strokeColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"strokeWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"title":"init(strokeColor:strokeWidth:cornerRadius:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"strokeColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"#FFFFFFFF\", isArgb: false), "},{"kind":"externalParam","text":"strokeWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" = 3.0, "},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" = 10.0)"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStrokedStyle\/init(strokeColor:strokeWidth:cornerRadius:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStrokedStyle"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstrokedstyle\/init(strokecolor:strokewidth:cornerradius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstrokedstyle\/init(strokecolor:strokewidth:cornerradius:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"abstract":[],"title":"SBSDKUI2Color","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2FinderStrokedStyle/init(strokeColor:strokeWidth:cornerRadius:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstrokedstyle\/init(strokecolor:strokewidth:cornerradius:)","type":"topic","abstract":[],"title":"init(strokeColor:strokeWidth:cornerRadius:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"strokeColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"strokeWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithStrokeColor:strokeWidth:cornerRadius:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStrokedStyle\/init(strokeColor:strokeWidth:cornerRadius:)","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2FinderStrokedStyle":{"type":"topic","abstract":[{"type":"text","text":"A variant of the viewfinder displaying a full outline of the scanning area."}],"navigatorTitle":[{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2finderstrokedstyle","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}],"title":"SBSDKUI2FinderStrokedStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2FinderStrokedStyle","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithStrokeColor:strokeWidth:cornerRadius:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStrokeColor:strokeWidth:cornerRadius:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStrokeColor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"strokeColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"strokeWidth:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"strokeWidth"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle"},{"value":"initWithStrokeColor:strokeWidth:cornerRadius:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStrokedStyle~1init(strokeColor:strokeWidth:cornerRadius:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStrokeColor:strokeWidth:cornerRadius:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStrokedStyle~1init(strokeColor:strokeWidth:cornerRadius:)\/fragments"},{"value":"SBSDKUI2FinderStrokedStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStrokedStyle\/title"},{"value":[{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStrokedStyle\/fragments"},{"value":[{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2FinderStrokedStyle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}