{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/enableCameraTextConfiguration","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","kind":"typeIdentifier","text":"SBSDKUIEnableCameraTextConfiguration"},{"text":" * ","kind":"text"},{"text":"enableCameraTextConfiguration","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/enablecameratextconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController(py)enableCameraTextConfiguration","roleHeading":"Instance Property","title":"enableCameraTextConfiguration","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"title":"SBSDKUILicensePlateScannerViewController","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime."}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"title":"SBSDKUIEnableCameraTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of camera based view controllers."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/enableCameraTextConfiguration":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/enableCameraTextConfiguration","title":"enableCameraTextConfiguration","fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/enablecameratextconfiguration","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUILicensePlateScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}]},{"value":"SBSDKUIEnableCameraTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments"}]}]}