{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","interfaceLanguage":"swift"},"abstract":[{"text":"Informs the delegate that a license plate has been recognized successfully.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/licenseplatescannerviewcontroller(_:didrecognizelicenseplate:on:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/licenseplatescannerviewcontroller(_:didrecognizelicenseplate:on:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licensePlateScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","text":"SBSDKLicensePlateScannerViewController"},{"kind":"text","text":", "},{"text":"didRecognizeLicensePlate","kind":"externalParam"},{"kind":"text","text":" "},{"text":"licensePlateResult","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKLicensePlateScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","type":"reference"},{"type":"text","text":" instance that detected\/recognized the license plate."}]}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The result of the detection or recognition.","type":"text"}]}],"name":"licensePlateResult"},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The original image where the license plate has been detected on."}],"type":"paragraph"}]}]}],"sections":[],"metadata":{"extendedModule":"ScanbotSDK","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController(im)licensePlateScannerViewController:didRecognizeLicensePlate:on:","navigatorTitle":[{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licensePlateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRecognizeLicensePlate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKLicensePlateScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/SBSDKLicensePlateScannerViewControllerDelegate-Implementations"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)":{"role":"symbol","kind":"symbol","abstract":[{"text":"Informs the delegate that a license plate has been recognized successfully.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/licenseplatescannerviewcontroller(_:didrecognizelicenseplate:on:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","navigatorTitle":[{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"licensePlateScannerViewController"},{"text":"(","kind":"text"},{"text":"SBSDKLicensePlateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didRecognizeLicensePlate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to scan for license plates with the camera.","type":"text"}],"navigatorTitle":[{"text":"SBSDKLicensePlateScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","kind":"symbol","title":"SBSDKLicensePlateScannerViewController","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerResult":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScannerResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerresult","title":"SBSDKLicensePlateScannerResult","abstract":[{"text":"A class describing the result of a license plate scan.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/SBSDKLicensePlateScannerViewControllerDelegate-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","title":"SBSDKLicensePlateScannerViewControllerDelegate Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/SBSDKLicensePlateScannerViewControllerDelegate-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/sbsdklicenseplatescannerviewcontrollerdelegate-implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime."}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","type":"topic","title":"SBSDKUILicensePlateScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"licensePlateScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerViewController","kind":"typeIdentifier","text":"SBSDKLicensePlateScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecognizeLicensePlate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult","text":"SBSDKLicensePlateScannerResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"licensePlateResult"},{"text":" ","kind":"text"},{"kind":"identifier","text":"on:"},{"kind":"text","text":"("},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"image"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)\/title","value":"licensePlateScannerViewController:didRecognizeLicensePlate:on:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}]},{"op":"replace","value":"SBSDKLicensePlateScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerViewController\/fragments"},{"value":"SBSDKLicensePlateScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKLicensePlateScannerResult"}],"op":"replace"},{"value":"SBSDKUILicensePlateScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments","value":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}