{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/SBSDKLicensePlateScannerViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/sbsdklicenseplatescannerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/sbsdklicenseplatescannerviewcontrollerdelegate-implementations"]}],"kind":"article","metadata":{"title":"SBSDKLicensePlateScannerViewControllerDelegate Implementations","modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup","roleHeading":"API Collection"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/licensePlateScannerViewControllerShouldRecognize(_:)"],"title":"Instance Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","abstract":[{"type":"text","text":"Informs the delegate that a license plate has been recognized successfully."}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/licenseplatescannerviewcontroller(_:didrecognizelicenseplate:on:)","role":"symbol","navigatorTitle":[{"text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licensePlateScannerViewController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","text":"SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didRecognizeLicensePlate"},{"kind":"text","text":": "},{"text":"SBSDKLicensePlateScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"kind":"symbol","abstract":[{"text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","title":"SBSDKUILicensePlateScannerViewController","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/licensePlateScannerViewControllerShouldRecognize(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/licensePlateScannerViewControllerShouldRecognize(_:)","abstract":[{"text":"Asks the delegate whether the next video frame should be scanned or not.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/licenseplatescannerviewcontrollershouldrecognize(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize:"}],"kind":"symbol","type":"topic","title":"licensePlateScannerViewControllerShouldRecognize(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licensePlateScannerViewControllerShouldRecognize"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScannerViewController","text":"SBSDKLicensePlateScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/licensePlateScannerViewControllerShouldRecognize(_:)"],"generated":true}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"licensePlateScannerViewController:didRecognizeLicensePlate:on:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1licensePlateScannerViewController(_:didRecognizeLicensePlate:on:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"licensePlateScannerViewController:didRecognizeLicensePlate:on:"}],"op":"replace"},{"value":"SBSDKUILicensePlateScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1licensePlateScannerViewControllerShouldRecognize(_:)\/title","value":"licensePlateScannerViewControllerShouldRecognize:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController~1licensePlateScannerViewControllerShouldRecognize(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"licensePlateScannerViewControllerShouldRecognize:","kind":"identifier"}]}]}]}