{"metadata":{"title":"updateFlashButton","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController(im)updateFlashButton","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateFlashButton"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateFlashButton"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/updateFlashButton","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/updateflashbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/updateFlashButton":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/updateFlashButton","fragments":[{"kind":"text","text":"- "},{"text":"updateFlashButton","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}],"title":"updateFlashButton","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/updateflashbutton","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"title":"SBSDKUILicensePlateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title","value":"SBSDKUILicensePlateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}]}]}]}