{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/viewDidLoad","interfaceLanguage":"occ"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController(im)viewDidLoad","fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"viewDidLoad"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/viewdidload"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/viewDidLoad":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/viewDidLoad","fragments":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/viewdidload","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"title":"SBSDKUILicensePlateScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUILicensePlateScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}]}]}]}