{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSerializeImages:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"serializeImages"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSerializationMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKImageSerializationMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageSerializationMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageSerializationMode"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration\/initWithSerializeImages:imageSerializationMode:","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktojsonconfiguration\/initwithserializeimages:imageserializationmode:"]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration(im)initWithSerializeImages:imageSerializationMode:","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithSerializeImages:imageSerializationMode:"}],"title":"initWithSerializeImages:imageSerializationMode:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSerializeImages:imageSerializationMode:"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSerializationMode":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageSerializationMode"}],"type":"topic","title":"SBSDKImageSerializationMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode","kind":"symbol","role":"symbol","abstract":[{"text":"Image serialization mode. Applicable only when serializeImages is true.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKToJSONConfiguration/initWithSerializeImages:imageSerializationMode:":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSerializeImages:imageSerializationMode:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSerializeImages:imageSerializationMode:"}],"title":"initWithSerializeImages:imageSerializationMode:","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktojsonconfiguration\/initwithserializeimages:imageserializationmode:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration\/initWithSerializeImages:imageSerializationMode:","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKToJSONConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"type":"topic","kind":"symbol","abstract":[{"text":"Configuration used to serialize an object to json.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktojsonconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKToJSONConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"title":"SBSDKToJSONConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode\/title","value":"SBSDKImageSerializationMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode\/fragments","value":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode\/navigatorTitle","value":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/title","value":"SBSDKToJSONConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/fragments","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKToJSONConfiguration\/navigatorTitle","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}