{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"virginiaSpecificRestrictions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvarecordfieldtype\/virginiaspecificrestrictions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvarecordfieldtype\/virginiaspecificrestrictions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVARecordFieldType\/virginiaSpecificRestrictions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Virginia-specific restrictions"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"virginiaSpecificRestrictions"}],"title":"SBSDKUI2AAMVARecordFieldType.virginiaSpecificRestrictions","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AAMVARecordFieldType@SBSDKUI2AAMVARecordFieldTypeVirginiaSpecificRestrictions","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeVirginiaSpecificRestrictions"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVARecordFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AAMVARecordFieldType/virginiaSpecificRestrictions":{"role":"symbol","title":"SBSDKUI2AAMVARecordFieldType.virginiaSpecificRestrictions","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"virginiaSpecificRestrictions"}],"abstract":[{"type":"text","text":"Virginia-specific restrictions"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVARecordFieldType\/virginiaSpecificRestrictions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeVirginiaSpecificRestrictions"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvarecordfieldtype\/virginiaspecificrestrictions"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AAMVARecordFieldType":{"role":"symbol","title":"SBSDKUI2AAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}],"abstract":[{"type":"text","text":"AAMVA Record Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvarecordfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2AAMVARecordFieldTypeVirginiaSpecificRestrictions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeVirginiaSpecificRestrictions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeVirginiaSpecificRestrictions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVARecordFieldType~1virginiaSpecificRestrictions\/title","value":"SBSDKUI2AAMVARecordFieldTypeVirginiaSpecificRestrictions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVARecordFieldType~1virginiaSpecificRestrictions\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldTypeVirginiaSpecificRestrictions"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVARecordFieldType\/title","value":"SBSDKUI2AAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}