{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"4 x 6 (inches)           288 x 432 (pixels) at 72 DPI."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"us4X6"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/us4x6"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/us4x6"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKPageSize@SBSDKPageSizeUs4X6","roleHeading":"Case","title":"SBSDKPageSize.us4X6","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"us4X6","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPageSizeUs4X6","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X6"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"url":"\/documentation\/scanbotsdk\/sbsdkpagesize","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","abstract":[{"text":"Page size.","type":"text"}],"role":"symbol","title":"SBSDKPageSize","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageSize"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/us4X6":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us4X6","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeUs4X6"}],"role":"symbol","abstract":[{"type":"text","text":"4 x 6 (inches)           288 x 432 (pixels) at 72 DPI."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/us4x6","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"us4X6"}],"title":"SBSDKPageSize.us4X6"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPageSizeUs4X6"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKPageSizeUs4X6","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKPageSizeUs4X6"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title","op":"replace","value":"SBSDKPageSize"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageSize"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us4X6\/title","op":"replace","value":"SBSDKPageSizeUs4X6"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us4X6\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageSizeUs4X6"}]}]}]}