{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/iconbackground"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/iconbackground"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/iconBackground"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"]]},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconBackground","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"}],"title":"iconBackground","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"iconBackground"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen(py)iconBackground","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"The background color of the icon used in the camera permission request.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iconBackground","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is “?sbColorOutline”"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen/iconBackground":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/iconBackground","type":"topic","title":"iconBackground","role":"symbol","abstract":[{"text":"The background color of the icon used in the camera permission request.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/iconbackground","navigatorTitle":[{"kind":"identifier","text":"iconBackground"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"title":"SBSDKUI2CameraPermissionScreen","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen","abstract":[{"text":"Configuration of the camera permission request view.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"iconBackground"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"iconBackground","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" * "},{"kind":"identifier","text":"iconBackground"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen~1iconBackground\/title","value":"iconBackground"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen~1iconBackground\/fragments","value":[{"text":"iconBackground","kind":"identifier"}]},{"value":"SBSDKUI2CameraPermissionScreen","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title"},{"value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle"},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle"}]}]}