{"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKCameraDeviceType@SBSDKCameraDeviceTypeSimulated","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeSimulated","kind":"identifier"}],"title":"SBSDKCameraDeviceType.simulated","roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simulated","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/simulated","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulated"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A simulated camera that can simulate a video stream by looping a video or a single image."},{"type":"text","text":" "},{"type":"text","text":"Also used on iPhone\/iPad simulators without providing a video stream."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/simulated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/simulated"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType":{"abstract":[{"text":"An enum to describe the different types of camera lenses\/devices.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"title":"SBSDKCameraDeviceType","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/simulated":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeSimulated"}],"type":"topic","title":"SBSDKCameraDeviceType.simulated","kind":"symbol","abstract":[{"text":"A simulated camera that can simulate a video stream by looping a video or a single image.","type":"text"},{"text":" ","type":"text"},{"text":"Also used on iPhone\/iPad simulators without providing a video stream.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/simulated","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/simulated","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulated"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCameraDeviceTypeSimulated"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeSimulated"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKCameraDeviceTypeSimulated","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/title","value":"SBSDKCameraDeviceType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/fragments","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/navigatorTitle","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1simulated\/title","value":"SBSDKCameraDeviceTypeSimulated","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType~1simulated\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeSimulated"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}