{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturefeedback\/initwithcamerablinkenabled:snapfeedbackmode:"]}],"sections":[],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraBlinkEnabled:snapFeedbackMode:"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"initWithCameraBlinkEnabled:snapFeedbackMode:","navigatorTitle":[{"kind":"identifier","text":"initWithCameraBlinkEnabled:snapFeedbackMode:"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback(im)initWithCameraBlinkEnabled:snapFeedbackMode:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback\/initWithCameraBlinkEnabled:snapFeedbackMode:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraBlinkEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraBlinkEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"snapFeedbackMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode","text":"SBSDKUI2PageSnapFeedbackMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"snapFeedbackMode"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFeedbackMode":{"title":"SBSDKUI2PageSnapFeedbackMode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"kind":"symbol","abstract":[{"text":"The type of animation to display after snapping a page.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfeedbackmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFeedbackMode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CaptureFeedback/initWithCameraBlinkEnabled:snapFeedbackMode:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2capturefeedback\/initwithcamerablinkenabled:snapfeedbackmode:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback\/initWithCameraBlinkEnabled:snapFeedbackMode:","kind":"symbol","type":"topic","title":"initWithCameraBlinkEnabled:snapFeedbackMode:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraBlinkEnabled:snapFeedbackMode:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCameraBlinkEnabled:snapFeedbackMode:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CaptureFeedback":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback","abstract":[{"type":"text","text":"Configuration of the feedback shown after snapping a page."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2CaptureFeedback","url":"\/documentation\/scanbotsdk\/sbsdkui2capturefeedback"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/title","op":"replace","value":"SBSDKUI2PageSnapFeedbackMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFeedbackMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/title","op":"replace","value":"SBSDKUI2CaptureFeedback"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}]}]}]}