{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"addObserver:"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument(im)addObserver:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addObserver"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKScannedDocumentObserver","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver"},{"kind":"text","text":")"}],"title":"addObserver(_:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocumentObserver","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The observer that wants to receive the delegate calls."}]}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Observing here works very similar to delegation with the exception than an object can inform multiple delegates."},{"type":"text","text":" "},{"type":"text","text":"The observer is not retained, but stored weakly."}]},{"inlineContent":[{"text":"The observer functions are always been dispatched to the main thread,","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/addobserver(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/addobserver(_:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Adds an observer to the receiver."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/addObserver(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocumentObserver":{"title":"SBSDKScannedDocumentObserver","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocumentObserver","type":"topic","navigatorTitle":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocumentobserver","abstract":[{"type":"text","text":"A delegation-like protocol for observing changes on an instance of "},{"type":"codeVoice","code":"SBSDKScannedDocument"},{"type":"text","text":"."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument/addObserver(_:)":{"abstract":[{"type":"text","text":"Adds an observer to the receiver."}],"title":"addObserver(_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/addObserver(_:)","navigatorTitle":[{"kind":"identifier","text":"addObserver:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKScannedDocumentObserver","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument\/addobserver(_:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedDocument"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"kind":"symbol","abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"type":"topic","title":"SBSDKScannedDocument"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"addObserver:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addObserver:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"addObserver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKScannedDocumentObserver","text":"id<SBSDKScannedDocumentObserver>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"observer","content":[{"inlineContent":[{"type":"text","text":"The observer that wants to receive the delegate calls."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/title","value":"SBSDKScannedDocumentObserver"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedDocumentObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocumentObserver\/navigatorTitle","value":[{"text":"SBSDKScannedDocumentObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1addObserver(_:)\/title","value":"addObserver:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1addObserver(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addObserver:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","op":"replace","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle","op":"replace","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}