{"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"assignedToAccidentInsuranceDoctor","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeAssignedToAccidentInsuranceDoctor","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType.assignedToAccidentInsuranceDoctor","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerCheckboxType@SBSDKMedicalCertificateRecognizerCheckboxTypeAssignedToAccidentInsuranceDoctor","role":"symbol"},"abstract":[{"text":"The accident insurance doctor checkbox.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/assignedToAccidentInsuranceDoctor","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/assignedtoaccidentinsurancedoctor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/assignedtoaccidentinsurancedoctor"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"assignedToAccidentInsuranceDoctor","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType/assignedToAccidentInsuranceDoctor":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assignedToAccidentInsuranceDoctor","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/assignedtoaccidentinsurancedoctor","title":"SBSDKMedicalCertificateRecognizerCheckboxType.assignedToAccidentInsuranceDoctor","abstract":[{"text":"The accident insurance doctor checkbox.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeAssignedToAccidentInsuranceDoctor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/assignedToAccidentInsuranceDoctor","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype","kind":"symbol","role":"symbol","title":"SBSDKMedicalCertificateRecognizerCheckboxType","abstract":[{"type":"text","text":"Type classifiers for checkboxes recognized on medical certificates."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKMedicalCertificateRecognizerCheckboxTypeAssignedToAccidentInsuranceDoctor","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeAssignedToAccidentInsuranceDoctor","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeAssignedToAccidentInsuranceDoctor","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1assignedToAccidentInsuranceDoctor\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeAssignedToAccidentInsuranceDoctor"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeAssignedToAccidentInsuranceDoctor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1assignedToAccidentInsuranceDoctor\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerCheckboxType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}