{"abstract":[{"text":"The entitlement to continued payment checkbox.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"entitlementToContinuedPaymentYes"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entitlementToContinuedPaymentYes","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerCheckboxType@SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentYes","roleHeading":"Case","role":"symbol","title":"SBSDKMedicalCertificateRecognizerCheckboxType.entitlementToContinuedPaymentYes","symbolKind":"case","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/entitlementToContinuedPaymentYes"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/entitlementtocontinuedpaymentyes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/entitlementtocontinuedpaymentyes"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"type":"topic","title":"SBSDKMedicalCertificateRecognizerCheckboxType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type classifiers for checkboxes recognized on medical certificates."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType/entitlementToContinuedPaymentYes":{"abstract":[{"type":"text","text":"The entitlement to continued payment checkbox."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/entitlementtocontinuedpaymentyes","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"entitlementToContinuedPaymentYes"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/entitlementToContinuedPaymentYes","title":"SBSDKMedicalCertificateRecognizerCheckboxType.entitlementToContinuedPaymentYes"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentYes","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentYes"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerCheckboxType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1entitlementToContinuedPaymentYes\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentYes"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentYes"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1entitlementToContinuedPaymentYes\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}