{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/entitlementtocontinuedpaymentno"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/entitlementtocontinuedpaymentno"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"entitlementToContinuedPaymentNo"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerCheckboxType@SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentNo","role":"symbol","roleHeading":"Case","title":"SBSDKMedicalCertificateRecognizerCheckboxType.entitlementToContinuedPaymentNo"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"entitlementToContinuedPaymentNo"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/entitlementToContinuedPaymentNo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The entitlement to continued payment no checkbox."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype","kind":"symbol","role":"symbol","title":"SBSDKMedicalCertificateRecognizerCheckboxType","abstract":[{"type":"text","text":"Type classifiers for checkboxes recognized on medical certificates."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType/entitlementToContinuedPaymentNo":{"title":"SBSDKMedicalCertificateRecognizerCheckboxType.entitlementToContinuedPaymentNo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"entitlementToContinuedPaymentNo"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/entitlementtocontinuedpaymentno","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/entitlementToContinuedPaymentNo","abstract":[{"type":"text","text":"The entitlement to continued payment no checkbox."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentNo","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerCheckboxType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}]},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentNo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1entitlementToContinuedPaymentNo\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1entitlementToContinuedPaymentNo\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeEntitlementToContinuedPaymentNo"}]}]}]}