{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerCheckboxType@SBSDKMedicalCertificateRecognizerCheckboxTypeRequiresCareYes","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeRequiresCareYes"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType.requiresCareYes","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requiresCareYes","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/requiresCareYes","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/requirescareyes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/requirescareyes"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiresCareYes","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"The requires care checkbox."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType/requiresCareYes":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/requiresCareYes","kind":"symbol","abstract":[{"type":"text","text":"The requires care checkbox."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/requirescareyes","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeRequiresCareYes"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType.requiresCareYes","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCareYes","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType","abstract":[{"text":"Type classifiers for checkboxes recognized on medical certificates.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeRequiresCareYes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeRequiresCareYes"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeRequiresCareYes"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1requiresCareYes\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeRequiresCareYes","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1requiresCareYes\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeRequiresCareYes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxType"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/fragments"}]}]}