{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"singleParentNo","kind":"identifier"}],"platforms":["iOS"]}]}],"abstract":[{"text":"The single parent no checkbox.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","title":"SBSDKMedicalCertificateRecognizerCheckboxType.singleParentNo","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"singleParentNo"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeSingleParentNo","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerCheckboxType@SBSDKMedicalCertificateRecognizerCheckboxTypeSingleParentNo"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/singleparentno"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/singleparentno"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/singleParentNo"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"abstract":[{"text":"Type classifiers for checkboxes recognized on medical certificates.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType/singleParentNo":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/singleParentNo","title":"SBSDKMedicalCertificateRecognizerCheckboxType.singleParentNo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"singleParentNo","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/singleparentno","abstract":[{"text":"The single parent no checkbox.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeSingleParentNo","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"SBSDKMedicalCertificateRecognizerCheckboxTypeSingleParentNo","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeSingleParentNo"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeSingleParentNo"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerCheckboxType"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1singleParentNo\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeSingleParentNo"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeSingleParentNo"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1singleParentNo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}