{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/undefined"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/undefined"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"undefined"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerCheckboxType@SBSDKMedicalCertificateRecognizerCheckboxTypeUndefined","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxTypeUndefined","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType.undefined"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType"]]},"sections":[],"abstract":[{"text":"The checkbox could not be classified.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/undefined"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"type":"topic","title":"SBSDKMedicalCertificateRecognizerCheckboxType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type classifiers for checkboxes recognized on medical certificates."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerCheckboxType/undefined":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizercheckboxtype\/undefined","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeUndefined"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerCheckboxType\/undefined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"title":"SBSDKMedicalCertificateRecognizerCheckboxType.undefined","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The checkbox could not be classified."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKMedicalCertificateRecognizerCheckboxTypeUndefined","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeUndefined"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeUndefined"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerCheckboxType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1undefined\/title","value":"SBSDKMedicalCertificateRecognizerCheckboxTypeUndefined","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerCheckboxTypeUndefined"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerCheckboxType~1undefined\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}