{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/initwithcameramodule:defaultzoomfactor:autocroponmanualsnap:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:autosnappingsensitivity:autosnappingdelay:autosnappingenabled:capturewithhardwar-5f5bb"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCameraModule:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraModule"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultZoomFactor:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"defaultZoomFactor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCropOnManualSnap:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoCropOnManualSnap"},{"kind":"text","text":" "},{"text":"flashEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"flashEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minFocusDistanceLock:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"minFocusDistanceLock","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinchToZoomEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraPreviewMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureQualityPrioritization:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","text":"SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"captureQualityPrioritization","kind":"internalParam"},{"kind":"text","text":" "},{"text":"autoSnappingSensitivity:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoSnappingDelay:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"autoSnappingDelay","kind":"internalParam"},{"kind":"text","text":" "},{"text":"autoSnappingEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"autoSnappingEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureWithHardwareButtonsEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"captureWithHardwareButtonsEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"fpsLimit:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"fpsLimit","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:"}],"title":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration(im)initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration/initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:","title":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration\/initwithcameramodule:defaultzoomfactor:autocroponmanualsnap:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:autosnappingsensitivity:autosnappingdelay:autosnappingenabled:capturewithhardwar-5f5bb","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule":{"navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule","title":"SBSDKUI2CameraModule","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Determines which camera module to use on start-up.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPreviewMode":{"abstract":[{"type":"text","text":"Configuration of the camera preview mode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","title":"SBSDKUI2CameraPreviewMode","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapreviewmode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"abstract":[{"text":"Determines the prioritization of still image quality and capturing speed.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization","title":"SBSDKUI2CapturePhotoQualityPrioritization","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2CameraModule","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/fragments","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2CameraPreviewMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title","value":"SBSDKUI2CapturePhotoQualityPrioritization"},{"value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","value":"SBSDKUI2DocumentScannerCameraConfiguration"},{"value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle"}]}]}