{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detailsActionColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]}]}],"metadata":{"symbolKind":"property","role":"symbol","title":"detailsActionColor","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorUIConfiguration(py)detailsActionColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailsActionColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"detailsActionColor","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration\/detailsActionColor","interfaceLanguage":"swift"},"abstract":[{"text":"The foreground color of the top bar buttons on the details screen.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/detailsactioncolor"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/detailsactioncolor"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorUIConfiguration/detailsActionColor":{"navigatorTitle":[{"kind":"identifier","text":"detailsActionColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration\/detailsActionColor","type":"topic","abstract":[{"text":"The foreground color of the top bar buttons on the details screen.","type":"text"}],"role":"symbol","title":"detailsActionColor","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/detailsactioncolor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detailsActionColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorUIConfiguration"}],"kind":"symbol","title":"SBSDKUIDocumentDataExtractorUIConfiguration","abstract":[{"text":"The configuration for the user interface of the RTU-UI document data extractor screen.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorUIConfiguration"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"detailsActionColor","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"detailsActionColor","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"detailsActionColor"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"detailsActionColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration~1detailsActionColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration~1detailsActionColor\/fragments","value":[{"text":"detailsActionColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/title","op":"replace","value":"SBSDKUIDocumentDataExtractorUIConfiguration"},{"value":[{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}]}]}]}