{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageMetadata"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","roleHeading":"Class","title":"SBSDKImageMetadata","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageMetadata","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageMetadata"}]},"abstract":[{"text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way.","type":"text"},{"type":"text","text":" "},{"text":"Use ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor","type":"reference","isActive":true},{"type":"text","text":" to extract metadata from and inject changed metadata into image data."}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/init(with:)"],"title":"Initializers","anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/ISOValue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/altitude","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/aperture","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/digitalizationDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/exposureTime","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/focalLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/focalLength35mm","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/imageHeight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/imageWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/latitude","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/lensMaker","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/lensModel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/longitude","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/metadataDictionary","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/orientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/originalDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/title"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagemetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagemetadata"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/init(with:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"title":"init(with:)","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/init(with:)","navigatorTitle":[{"kind":"identifier","text":"initWithMetadataDictionary:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/init(with:)","abstract":[{"type":"text","text":"Creates a new  "},{"code":"SBSDKImageMetadata","type":"codeVoice"},{"text":" object or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":", if the metadata dictionary does not contain valid metadata."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/originalDate":{"title":"originalDate","navigatorTitle":[{"kind":"identifier","text":"originalDate"}],"abstract":[{"type":"text","text":"The date of when the image was captured."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/originalDate","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/originaldate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/imageWidth":{"title":"imageWidth","navigatorTitle":[{"kind":"identifier","text":"imageWidth"}],"abstract":[{"text":"The width of the image in pixels.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/imageWidth","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/imagewidth","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageWidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/focalLength":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/focalLength","title":"focalLength","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/focallength","type":"topic","abstract":[{"text":"The real focal length of the lens used to capture the image. Measured in millimeters. Readonly.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"focalLength","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"focalLength","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/metadataDictionary":{"navigatorTitle":[{"text":"metadataDictionary","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/metadataDictionary","kind":"symbol","role":"symbol","abstract":[{"text":"The raw metadata dictionary as it gets extracted from CGImageSourceCopyPropertiesAtIndex. Readonly.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/metadatadictionary","title":"metadataDictionary","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metadataDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/exposureTime":{"role":"symbol","navigatorTitle":[{"text":"exposureTime","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/exposuretime","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/exposureTime","abstract":[{"type":"text","text":"The duration the sensor was exposed during capturing the image. Equals to 1.0 \/ shutter speed. Readonly."}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exposureTime"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"exposureTime"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/init","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageMetadata"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata","title":"SBSDKImageMetadata","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata","type":"topic","abstract":[{"text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way.","type":"text"},{"text":" ","type":"text"},{"text":"Use ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor","isActive":true},{"text":" to extract metadata from and inject changed metadata into image data.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/altitude":{"abstract":[{"type":"text","text":"The altitude of the location where the image was captured."}],"navigatorTitle":[{"text":"altitude","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/altitude","title":"altitude","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/altitude","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"altitude","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/aperture":{"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/aperture","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aperture"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The f-stop number or aperture of the lens used to capture the image. Readonly."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/aperture","type":"topic","kind":"symbol","title":"aperture","navigatorTitle":[{"text":"aperture","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/ISOValue":{"navigatorTitle":[{"kind":"identifier","text":"ISOValue"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/ISOValue","kind":"symbol","role":"symbol","abstract":[{"text":"The ISO value used to capture the image. Readonly.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/isovalue","title":"ISOValue","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISOValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/latitude":{"navigatorTitle":[{"kind":"identifier","text":"latitude"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/latitude","kind":"symbol","role":"symbol","abstract":[{"text":"The latitude of the location where the image was captured.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/latitude","title":"latitude","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"latitude","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/lensMaker":{"title":"lensMaker","navigatorTitle":[{"text":"lensMaker","kind":"identifier"}],"abstract":[{"type":"text","text":"The manufacturer of the lens used to capture the image. Readonly."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/lensmaker","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/lensMaker","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lensMaker","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadataProcessor":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageMetadataProcessor","type":"topic","abstract":[{"text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadataprocessor","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/digitalizationDate":{"kind":"symbol","title":"digitalizationDate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalizationDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/digitalizationdate","navigatorTitle":[{"kind":"identifier","text":"digitalizationDate"}],"abstract":[{"text":"The date of when the image was digitized.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/digitalizationDate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/imageHeight":{"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/imageheight","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageHeight","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[{"text":"The height of the image in pixels.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/imageHeight","type":"topic","kind":"symbol","title":"imageHeight","navigatorTitle":[{"kind":"identifier","text":"imageHeight"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/lensModel":{"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/lensmodel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lensModel"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lensModel"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"text":"The model of the lens used to capture the image. Readonly.","type":"text"}],"title":"lensModel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/lensModel","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/orientation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/orientation","abstract":[{"text":"The orientation flag of the image.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"orientation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","kind":"symbol","title":"orientation","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/orientation","role":"symbol","navigatorTitle":[{"text":"orientation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/title":{"navigatorTitle":[{"text":"title","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/title","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/title","abstract":[{"type":"text","text":"The title of the image."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"title","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/longitude":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"longitude","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/longitude","title":"longitude","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/longitude","abstract":[{"type":"text","text":"The longitude of the location where the image was captured."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"longitude"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/focalLength35mm":{"abstract":[{"text":"The 35mm equivalent focal length of the lens used to capture the image. Measured in millimeters. Readonly.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"focalLength35mm","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"focalLength35mm","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/focalLength35mm","navigatorTitle":[{"text":"focalLength35mm","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/focallength35mm"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKImageMetadata","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/ISOValue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/altitude","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/aperture","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/digitalizationDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/exposureTime","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/focalLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/focalLength35mm","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/imageHeight","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/imageWidth","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/latitude","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/lensMaker","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/lensModel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/longitude","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/metadataDictionary","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/orientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/originalDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/title"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/init(with:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageMetadata","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"value":"initWithMetadataDictionary:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1init(with:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1init(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMetadataDictionary:","kind":"identifier"}]},{"value":"originalDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1originalDate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1originalDate\/fragments","op":"replace","value":[{"kind":"identifier","text":"originalDate"}]},{"value":"imageWidth","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1imageWidth\/title","op":"replace"},{"value":[{"kind":"identifier","text":"imageWidth"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1imageWidth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1focalLength\/title","value":"focalLength"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1focalLength\/fragments","value":[{"text":"focalLength","kind":"identifier"}],"op":"replace"},{"value":"metadataDictionary","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1metadataDictionary\/title"},{"value":[{"text":"metadataDictionary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1metadataDictionary\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1exposureTime\/title","value":"exposureTime","op":"replace"},{"value":[{"kind":"identifier","text":"exposureTime"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1exposureTime\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/title","value":"SBSDKImageMetadata"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"op":"replace"},{"value":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/navigatorTitle"},{"value":"altitude","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1altitude\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1altitude\/fragments","value":[{"text":"altitude","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"aperture","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1aperture\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1aperture\/fragments","value":[{"kind":"identifier","text":"aperture"}]},{"op":"replace","value":"ISOValue","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1ISOValue\/title"},{"value":[{"text":"ISOValue","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1ISOValue\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1latitude\/title","value":"latitude","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1latitude\/fragments","value":[{"text":"latitude","kind":"identifier"}]},{"op":"replace","value":"lensMaker","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1lensMaker\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1lensMaker\/fragments","op":"replace","value":[{"text":"lensMaker","kind":"identifier"}]},{"value":"SBSDKImageMetadataProcessor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/navigatorTitle","value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1digitalizationDate\/title","value":"digitalizationDate"},{"value":[{"text":"digitalizationDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1digitalizationDate\/fragments"},{"value":"imageHeight","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1imageHeight\/title"},{"value":[{"text":"imageHeight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1imageHeight\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1lensModel\/title","value":"lensModel"},{"value":[{"kind":"identifier","text":"lensModel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1lensModel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1orientation\/title","value":"orientation"},{"value":[{"text":"orientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1orientation\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1title\/title","op":"replace","value":"title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1title\/fragments","value":[{"kind":"identifier","text":"title"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1longitude\/title","value":"longitude"},{"op":"replace","value":[{"text":"longitude","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1longitude\/fragments"},{"value":"focalLength35mm","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1focalLength35mm\/title"},{"value":[{"kind":"identifier","text":"focalLength35mm"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1focalLength35mm\/fragments"}]}]}