{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord"},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/init(quad:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/quad","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/rawString","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/recognitionConfidence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/type","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/value"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKMedicalCertificateDateRecord) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"Structure to contain date record information.","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecord"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateDateRecord","title":"SBSDKMedicalCertificateDateRecord","roleHeading":"Class","symbolKind":"class"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/value":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Validated date string.","type":"text"}],"title":"value","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/value","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/type":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/type","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/type","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Date type.","type":"text"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateDateRecordType","text":"SBSDKMedicalCertificateDateRecordType","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/copyWithZone:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/copyWithZone:","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/copywithzone:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/hash":{"type":"topic","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/hash","role":"symbol","abstract":[],"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/recognitionConfidence":{"abstract":[{"type":"text","text":"Confidence in the recognized value."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/recognitionConfidence","title":"recognitionConfidence","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/recognitionconfidence","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognitionConfidence","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"recognitionConfidence"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/quad":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/quad","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/quad","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Date box."}],"navigatorTitle":[{"text":"quad","kind":"identifier"}],"title":"quad","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quad","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/initWithQuad:value:rawString:type:recognitionConfidence:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQuad:value:rawString:type:recognitionConfidence:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/initWithQuad:value:rawString:type:recognitionConfidence:","navigatorTitle":[{"text":"initWithQuad:value:rawString:type:recognitionConfidence:","kind":"identifier"}],"role":"symbol","abstract":[],"title":"initWithQuad:value:rawString:type:recognitionConfidence:","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/initwithquad:value:rawstring:type:recognitionconfidence:","kind":"symbol"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/toJson(configuration:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/tojson(configuration:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/isEqual:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","abstract":[],"title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/isequal:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord","abstract":[{"type":"text","text":"Structure to contain date record information."}],"kind":"symbol","role":"symbol","title":"SBSDKMedicalCertificateDateRecord","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecord"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/fromJsonWithJson:":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/fromjsonwithjson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/rawString":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawString","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/rawString","navigatorTitle":[{"text":"rawString","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Raw date string."}],"title":"rawString","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/rawstring","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecord/init(quad:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quad","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":"])","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecord\/init(quad:)","navigatorTitle":[{"text":"initWithQuad:","kind":"identifier"}],"title":"init(quad:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/init(quad:)"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMedicalCertificateDateRecord"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/quad","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/rawString","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/recognitionConfidence","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/type","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/value"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/init(quad:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/initWithQuad:value:rawString:type:recognitionConfidence:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecord\/fromJsonWithJson:"],"generated":true,"title":"Type Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"title":"Conforms To","kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"value","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1value\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1value\/fragments","value":[{"text":"value","kind":"identifier"}],"op":"replace"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1type\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1recognitionConfidence\/title","value":"recognitionConfidence"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1recognitionConfidence\/fragments","op":"replace","value":[{"text":"recognitionConfidence","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1quad\/title","op":"replace","value":"quad"},{"value":[{"kind":"identifier","text":"quad"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1quad\/fragments"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1toJson(configuration:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/title","value":"SBSDKMedicalCertificateDateRecord","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/fragments","value":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateDateRecord","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1rawString\/title","op":"replace","value":"rawString"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1rawString\/fragments","value":[{"kind":"identifier","text":"rawString"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1init(quad:)\/title","op":"replace","value":"initWithQuad:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQuad:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecord~1init(quad:)\/fragments"}]}]}