{"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoButtonMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/toJson(configuration:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/noButtonMode()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/pagePreviewMode()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/textButtonMode()"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKUI2PreviewButton) "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2previewbutton"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2previewbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PreviewButton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKUI2PreviewButton"},"abstract":[{"type":"text","text":"Configuration of the ‘preview’ button."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PagePreviewMode":{"type":"topic","title":"SBSDKUI2PagePreviewMode","abstract":[{"text":"Configuration of the ‘preview’ button in ‘page preview mode’.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode","navigatorTitle":[{"text":"SBSDKUI2PagePreviewMode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PagePreviewMode"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NoButtonMode":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2NoButtonMode"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoButtonMode","role":"symbol","title":"SBSDKUI2NoButtonMode","abstract":[{"type":"text","text":"Configuration of the ‘preview’ button in ‘no button mode’."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2nobuttonmode","navigatorTitle":[{"text":"SBSDKUI2NoButtonMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton/isEqual:":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/isEqual:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton\/isequal:","title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2node","navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"type":"topic","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Node"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","title":"SBSDKUI2Node"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton\/tojson(configuration:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","title":"toJson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/toJson(configuration:)"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/hash","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton\/hash","title":"hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton/fromJsonWithJson:":{"kind":"symbol","title":"fromJsonWithJson:","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}],"title":"SBSDKUI2PreviewButton","abstract":[{"text":"Configuration of the ‘preview’ button.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextButtonMode":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextButtonMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textbuttonmode","title":"SBSDKUI2TextButtonMode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextButtonMode","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Configuration of the ‘preview’ button in ‘text button mode’.","type":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton\/copywithzone:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","title":"copyWithZone:","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton/pagePreviewMode()":{"navigatorTitle":[{"kind":"identifier","text":"pagePreviewMode"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pagePreviewMode"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2PagePreviewMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PagePreviewMode"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/pagePreviewMode()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton\/pagepreviewmode()","title":"pagePreviewMode()"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton/textButtonMode()":{"navigatorTitle":[{"kind":"identifier","text":"textButtonMode"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textButtonMode"},{"kind":"text","text":"() -> "},{"text":"SBSDKUI2TextButtonMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextButtonMode","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/textButtonMode()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton\/textbuttonmode()","title":"textButtonMode()"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PreviewButton/noButtonMode()":{"title":"noButtonMode()","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"noButtonMode"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2NoButtonMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2NoButtonMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/noButtonMode()","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"noButtonMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2previewbutton\/nobuttonmode()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUI2PreviewButton","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/hash"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/toJson(configuration:)"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/noButtonMode()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/pagePreviewMode()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PreviewButton\/textButtonMode()"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"]},{"type":"inheritedBy","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NoButtonMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextButtonMode"],"title":"Inherited By","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PreviewButton"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode\/title","op":"replace","value":"SBSDKUI2PagePreviewMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode\/fragments","value":[{"text":"SBSDKUI2PagePreviewMode","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2PagePreviewMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoButtonMode\/title","value":"SBSDKUI2NoButtonMode","op":"replace"},{"value":[{"text":"SBSDKUI2NoButtonMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoButtonMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2NoButtonMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NoButtonMode\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Node","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton~1toJson(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/title","value":"SBSDKUI2PreviewButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/fragments","value":[{"text":"SBSDKUI2PreviewButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2PreviewButton"}],"op":"replace"},{"value":"SBSDKUI2TextButtonMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TextButtonMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextButtonMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TextButtonMode"}]},{"value":"pagePreviewMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton~1pagePreviewMode()\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton~1pagePreviewMode()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"pagePreviewMode"}],"op":"replace"},{"op":"replace","value":"textButtonMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton~1textButtonMode()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton~1textButtonMode()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"textButtonMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton~1noButtonMode()\/title","op":"replace","value":"noButtonMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PreviewButton~1noButtonMode()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"noButtonMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}