{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/acceptedCheckStandards","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/captureHighResolutionImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/finderAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/isFlashEnabled"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI check scanner."}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerBehaviorConfiguration"}],"title":"SBSDKUICheckScannerBehaviorConfiguration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerBehaviorConfiguration","roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"references":{"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerBehaviorConfiguration/isFlashEnabled":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFlashEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/isFlashEnabled","navigatorTitle":[{"text":"isFlashEnabled","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Whether flash is toggled on or off.","type":"text"}],"title":"isFlashEnabled","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration\/isflashenabled","kind":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerBehaviorConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration\/init","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/init","abstract":[],"title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerBehaviorConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration","role":"symbol","type":"topic","kind":"symbol","title":"SBSDKUICheckScannerBehaviorConfiguration","abstract":[{"text":"Configuration for the behavior of the RTU-UI check scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerBehaviorConfiguration/captureHighResolutionImage":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"captureHighResolutionImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration\/capturehighresolutionimage","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/captureHighResolutionImage","abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"true"},{"text":", a high-resolution photo of the check is captured to run the scanning on.","type":"text"}],"title":"captureHighResolutionImage","navigatorTitle":[{"kind":"identifier","text":"captureHighResolutionImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerBehaviorConfiguration/acceptedCheckStandards":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/acceptedCheckStandards","navigatorTitle":[{"kind":"identifier","text":"acceptedCheckStandards"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedCheckStandards"},{"text":": [","kind":"text"},{"text":"SBSDKCheckDocumentModelRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType"},{"text":"]","kind":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration\/acceptedcheckstandards","title":"acceptedCheckStandards","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An array of accepted check types."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerBehaviorConfiguration/finderAspectRatio":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier","text":"SBSDKAspectRatio"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration\/finderaspectratio","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/finderAspectRatio","abstract":[{"type":"text","text":"The aspect ratio of the view finder. Set to "},{"code":"nil","type":"codeVoice"},{"text":", if no finder should be used.","type":"text"}],"title":"finderAspectRatio","navigatorTitle":[{"text":"finderAspectRatio","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"SBSDKUICheckScannerBehaviorConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUICheckScannerBehaviorConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/acceptedCheckStandards","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/captureHighResolutionImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/finderAspectRatio","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/isFlashEnabled"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/init"],"anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"isFlashEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1isFlashEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isFlashEnabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1isFlashEnabled\/fragments"},{"value":"SBSDKUICheckScannerBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","value":"captureHighResolutionImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1captureHighResolutionImage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1captureHighResolutionImage\/fragments","value":[{"kind":"identifier","text":"captureHighResolutionImage"}],"op":"replace"},{"value":"acceptedCheckStandards","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1acceptedCheckStandards\/title","op":"replace"},{"value":[{"text":"acceptedCheckStandards","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1acceptedCheckStandards\/fragments"},{"value":"finderAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1finderAspectRatio\/title","op":"replace"},{"value":[{"kind":"identifier","text":"finderAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1finderAspectRatio\/fragments"}]}]}