{"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage"},"abstract":[{"text":"The image for the introduction screen with one side of a credit card.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroImage"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardIntroOneSideImage"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroOneSideImage","title":"SBSDKUI2CreditCardIntroOneSideImage"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(SBSDKUI2CreditCardIntroOneSideImage) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage\/hash","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/hash","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage/isEqual:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage\/isequal:","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardIntroOneSideImage"}],"title":"SBSDKUI2CreditCardIntroOneSideImage","navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"abstract":[{"type":"text","text":"The image for the introduction screen with one side of a credit card."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage/copyWithZone:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage\/copywithzone:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/copyWithZone:","type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage/toJson(configuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage\/tojson(configuration:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/toJson(configuration:)","type":"topic","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage/fromJsonWithJson:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[],"title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage\/fromjsonwithjson:","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroOneSideImage/init":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"abstract":[],"title":"init","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroonesideimage\/init","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/init","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerIntroImage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroImage","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CreditCardScannerIntroImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The image for the introduction screen of a credit card scanner screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroImage"}],"title":"SBSDKUI2CreditCardScannerIntroImage","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerintroimage"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"SBSDKUI2CreditCardIntroOneSideImage","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/hash"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/toJson(configuration:)"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroOneSideImage\/fromJsonWithJson:"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroImage"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CreditCardIntroOneSideImage"},{"kind":"text","text":" : "},{"text":"SBSDKUI2CreditCardScannerIntroImage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerIntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerIntroImage"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/title","value":"SBSDKUI2CreditCardIntroOneSideImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/fragments","value":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2CreditCardIntroOneSideImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroOneSideImage~1toJson(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2CreditCardScannerIntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroImage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerIntroImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}