{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelCnEntryAndExitPermitFront","roleHeading":"Class","navigatorTitle":[{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}],"title":"SBSDKDocumentsModelCnEntryAndExitPermitFront","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"CnEntryAndExitPermitFront"}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/business","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/destinations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/issueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/mrz","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/mrzLine","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/photo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/placeOfIssue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/portsOfExitAndEntry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/rawMRZ","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/timesOfExitAndEntry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/validFrom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/validUntil"],"generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/portsOfExitAndEntry":{"type":"topic","kind":"symbol","title":"portsOfExitAndEntry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"portsOfExitAndEntry"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"portsOfExitAndEntry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Ports where the cardholder can enter or exit"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/portsofexitandentry","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/portsOfExitAndEntry"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/business":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/business","navigatorTitle":[{"kind":"identifier","text":"business"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"business","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/business","title":"business","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Business Type"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/birthDate":{"type":"topic","kind":"symbol","title":"birthDate","role":"symbol","navigatorTitle":[{"text":"birthDate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"birthDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Date of Birth"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/birthdate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/birthDate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/timesOfExitAndEntry":{"title":"timesOfExitAndEntry","abstract":[{"text":"Number of times the cardholder has exited or entered","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"timesOfExitAndEntry","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timesOfExitAndEntry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/timesofexitandentry","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/timesOfExitAndEntry"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/validFrom":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validFrom"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/validfrom","title":"validFrom","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/validFrom","role":"symbol","abstract":[{"text":"Start date of the permit validity","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"validFrom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/gender":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gender"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/gender","title":"gender","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/gender","role":"symbol","abstract":[{"type":"text","text":"Gender"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gender"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/mrzLine":{"title":"mrzLine","abstract":[{"text":"MRZ text value","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mrzLine"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrzLine"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/mrzline","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/mrzLine"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront":{"type":"topic","abstract":[{"type":"text","text":"CnEntryAndExitPermitFront"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront","title":"SBSDKDocumentsModelCnEntryAndExitPermitFront"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Base class for strongly-typed "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"type":"text","text":" wrappers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","title":"SBSDKGenericDocumentWrapper","navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/mrz":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"mrz","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/mrz","title":"mrz","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/mrz","role":"symbol","abstract":[{"type":"text","text":"The child document of type “MRZ”."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrz"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ","text":"SBSDKDocumentsModelMRZ"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/validUntil":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validUntil"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/validuntil","title":"validUntil","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/validUntil","role":"symbol","abstract":[{"text":"End date of the permit validity","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"validUntil","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/placeOfIssue":{"abstract":[{"text":"Place where the permit was issued","type":"text"}],"type":"topic","navigatorTitle":[{"text":"placeOfIssue","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeOfIssue","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/placeofissue","kind":"symbol","title":"placeOfIssue","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/placeOfIssue"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocument","kind":"identifier"}],"title":"SBSDKGenericDocument","type":"topic","abstract":[{"type":"text","text":"Generic document."}],"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/givenNames":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"givenNames","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/givennames","title":"givenNames","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/givenNames","role":"symbol","abstract":[{"type":"text","text":"Given Names"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNames"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/id":{"title":"id","abstract":[{"type":"text","text":"Identity Document Number"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"id"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/id","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/id"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/requiredDocumentType":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/requireddocumenttype","title":"requiredDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/requiredDocumentType","role":"symbol","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredDocumentType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/initWithGenericDocument:":{"title":"initWithGenericDocument:","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/initwithgenericdocument:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/initWithGenericDocument:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/photo":{"abstract":[{"type":"text","text":"Photo"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/photo","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/photo","navigatorTitle":[{"text":"photo","kind":"identifier"}],"title":"photo","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/destinations":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"destinations","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","title":"destinations","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/destinations","navigatorTitle":[{"kind":"identifier","text":"destinations"}],"abstract":[{"type":"text","text":"Destinations"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/destinations"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/issueDate":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","title":"issueDate","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/issuedate","navigatorTitle":[{"kind":"identifier","text":"issueDate"}],"abstract":[{"type":"text","text":"Date when the permit was issued"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/issueDate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/rawMRZ":{"abstract":[{"type":"text","text":"Raw MRZ text value"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rawMRZ","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/rawMRZ","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/rawmrz","navigatorTitle":[{"kind":"identifier","text":"rawMRZ"}],"title":"rawMRZ","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentsModelCnEntryAndExitPermitFront"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelCnEntryAndExitPermitFront"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/business","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/destinations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/issueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/mrz","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/mrzLine","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/photo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/placeOfIssue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/portsOfExitAndEntry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/rawMRZ","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/timesOfExitAndEntry","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/validFrom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/validUntil"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/initWithGenericDocument:"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1portsOfExitAndEntry\/title","op":"replace","value":"portsOfExitAndEntry"},{"op":"replace","value":[{"text":"portsOfExitAndEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1portsOfExitAndEntry\/fragments"},{"op":"replace","value":"business","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1business\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1business\/fragments","op":"replace","value":[{"text":"business","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1birthDate\/title","value":"birthDate"},{"value":[{"text":"birthDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1birthDate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1timesOfExitAndEntry\/title","value":"timesOfExitAndEntry"},{"value":[{"kind":"identifier","text":"timesOfExitAndEntry"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1timesOfExitAndEntry\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1validFrom\/title","op":"replace","value":"validFrom"},{"op":"replace","value":[{"kind":"identifier","text":"validFrom"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1validFrom\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1gender\/title","value":"gender"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1gender\/fragments","value":[{"text":"gender","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1mrzLine\/title","op":"replace","value":"mrzLine"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1mrzLine\/fragments","op":"replace","value":[{"kind":"identifier","text":"mrzLine"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront\/title","op":"replace","value":"SBSDKDocumentsModelCnEntryAndExitPermitFront"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelCnEntryAndExitPermitFront"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelCnEntryAndExitPermitFront"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","value":"SBSDKGenericDocumentWrapper"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1mrz\/title","value":"mrz"},{"value":[{"text":"mrz","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1mrz\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1validUntil\/title","value":"validUntil"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1validUntil\/fragments","value":[{"kind":"identifier","text":"validUntil"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1placeOfIssue\/title","value":"placeOfIssue","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1placeOfIssue\/fragments","value":[{"kind":"identifier","text":"placeOfIssue"}],"op":"replace"},{"op":"replace","value":"SBSDKGenericDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1givenNames\/title","value":"givenNames"},{"op":"replace","value":[{"text":"givenNames","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1givenNames\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1id\/title","value":"id","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1id\/fragments","value":[{"kind":"identifier","text":"id"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1requiredDocumentType\/title","op":"replace","value":"requiredDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1requiredDocumentType\/fragments","op":"replace","value":[{"text":"requiredDocumentType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1photo\/title","value":"photo"},{"value":[{"kind":"identifier","text":"photo"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1photo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1destinations\/title","value":"destinations"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1destinations\/fragments","value":[{"text":"destinations","kind":"identifier"}],"op":"replace"},{"value":"issueDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1issueDate\/title"},{"value":[{"kind":"identifier","text":"issueDate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1issueDate\/fragments"},{"value":"rawMRZ","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1rawMRZ\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1rawMRZ\/fragments","value":[{"kind":"identifier","text":"rawMRZ"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}