{"metadata":{"navigatorTitle":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKValueSemantics","role":"symbol","title":"SBSDKValueSemantics","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKValueSemantics","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(SBSDKValueSemantics) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKValueSemantics","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/invalid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/skipped","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/valid"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","interfaceLanguage":"swift"},"abstract":[{"text":"The result of the value semantics verification.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvaluesemantics"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvaluesemantics"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/init(rawvalue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/init(rawValue:)"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/RawRepresentable-Implementations":{"kind":"article","abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/Equatable-Implementations","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/equatable-implementations"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/skipped":{"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/skipped","kind":"symbol","abstract":[{"type":"text","text":"Verification of the value semantics was skipped. For example, because the field is empty."}],"type":"topic","title":"SBSDKValueSemantics.skipped","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipped"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/skipped","navigatorTitle":[{"text":"SBSDKValueSemanticsSkipped","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics":{"type":"topic","title":"SBSDKValueSemantics","abstract":[{"type":"text","text":"The result of the value semantics verification."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","navigatorTitle":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKValueSemantics","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/valid":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKValueSemanticsValid"}],"kind":"symbol","role":"symbol","title":"SBSDKValueSemantics.valid","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/valid","type":"topic","abstract":[{"text":"No errors were detected during semantics verification. For example, the date of birth is in the past, the date","type":"text"},{"type":"text","text":" "},{"text":"of expiry is in the future.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/valid"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/invalid":{"role":"symbol","title":"SBSDKValueSemantics.invalid","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueSemanticsInvalid"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Semantically invalid value. For example, the date of birth is in the future, the date of expiry is in the past."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/invalid","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/invalid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKValueSemantics"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKValueSemantics","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKValueSemantics","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/invalid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/skipped","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/valid"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKValueSemantics"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1skipped\/title","value":"SBSDKValueSemanticsSkipped"},{"value":[{"text":"SBSDKValueSemanticsSkipped","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1skipped\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/title","value":"SBSDKValueSemantics","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/fragments","value":[{"kind":"identifier","text":"SBSDKValueSemantics"}]},{"value":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1valid\/title","value":"SBSDKValueSemanticsValid","op":"replace"},{"value":[{"text":"SBSDKValueSemanticsValid","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1valid\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1invalid\/title","value":"SBSDKValueSemanticsInvalid","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1invalid\/fragments","value":[{"kind":"identifier","text":"SBSDKValueSemanticsInvalid"}],"op":"replace"}]}]}