{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeFormatMSIPlesseyConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration"]}],"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/init()"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/checksumAlgorithms","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/maximumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/minimumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/stripCheckDigits"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatMSIPlesseyConfiguration","title":"SBSDKBarcodeFormatMSIPlesseyConfiguration","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To"}],"abstract":[{"text":"MSI Plessey barcode configuration. Add to scanner configuration to scan MSI Plessey barcodes.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:stripcheckdigits:minimumtextlength:maximumtextlength:checksumalgorithms:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","type":"topic","navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","kind":"symbol","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/copyWithZone:","kind":"symbol","title":"copyWithZone:","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/maximumTextLength":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maximumTextLength","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","abstract":[{"text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/maximumTextLength","title":"maximumTextLength","navigatorTitle":[{"text":"maximumTextLength","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/maximumtextlength"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration","abstract":[{"type":"text","text":"MSI Plessey barcode configuration. Add to scanner configuration to scan MSI Plessey barcodes."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration","type":"topic","title":"SBSDKBarcodeFormatMSIPlesseyConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/checksumAlgorithms":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/checksumalgorithms","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"checksumAlgorithms","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"checksumAlgorithms","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/checksumAlgorithms","abstract":[{"type":"text","text":"List of MSI Plessey checksum algorithms to apply during scanning."},{"text":" ","type":"text"},{"text":"A barcode is considered valid if it passes any of the checksum algorithms in the list.","type":"text"},{"type":"text","text":" "},{"text":"If the list is empty, no checksum validation is performed.","type":"text"}],"role":"symbol","title":"checksumAlgorithms"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatOneDConfigurationBase":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","abstract":[{"type":"text","text":"Base class for all linear (1D) barcode configurations."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatonedconfigurationbase","type":"topic","title":"SBSDKBarcodeFormatOneDConfigurationBase","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/new":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/new","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/new","type":"topic","navigatorTitle":[{"text":"new","kind":"identifier"}],"title":"new","kind":"symbol","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/hash":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/hash","title":"hash","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/hash","fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/init()":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/init()","title":"init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/stripCheckDigits":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripCheckDigits","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"text":"If true, the check digits are stripped from the result.","type":"text"}],"title":"stripCheckDigits","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/stripcheckdigits","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/stripCheckDigits","type":"topic","navigatorTitle":[{"text":"stripCheckDigits","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/tojson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/toJson(configuration:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"title":"toJson(configuration:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/minimumTextLength":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/minimumTextLength","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumTextLength","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"minimumTextLength"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/minimumtextlength","title":"minimumTextLength","abstract":[{"type":"text","text":"Minimum text length. Applied only to linear barcode formats that allow variable length."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/isEqual:":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/isequal:","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/isEqual:","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/fromJsonWithJson:","type":"topic","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","kind":"symbol","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"SBSDKBarcodeFormatMSIPlesseyConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/checksumAlgorithms","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/maximumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/minimumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/stripCheckDigits"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:stripCheckDigits:minimumTextLength:maximumTextLength:checksumAlgorithms:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/new"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatOneDConfigurationBase","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1maximumTextLength\/title","op":"replace","value":"maximumTextLength"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1maximumTextLength\/fragments","value":[{"kind":"identifier","text":"maximumTextLength"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/title","value":"SBSDKBarcodeFormatMSIPlesseyConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1checksumAlgorithms\/title","value":"checksumAlgorithms","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1checksumAlgorithms\/fragments","op":"replace","value":[{"kind":"identifier","text":"checksumAlgorithms"}]},{"value":"SBSDKBarcodeFormatOneDConfigurationBase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}]},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1init()\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1stripCheckDigits\/title","op":"replace","value":"stripCheckDigits"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1stripCheckDigits\/fragments","value":[{"kind":"identifier","text":"stripCheckDigits"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1toJson(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1minimumTextLength\/title","value":"minimumTextLength"},{"value":[{"text":"minimumTextLength","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration~1minimumTextLength\/fragments","op":"replace"}]}]}