{"metadata":{"externalID":"s:25ScanbotDocumentScannerSDK28SBSDKUI2PageSnapFeedbackNoneC4fromACs7Decoder_p_tKcfc","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"symbolKind":"init","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"init(from:)","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"decoder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackNone\/init(from:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackNone"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbacknone\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackNone/init(from:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackNone\/init(from:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbacknone\/init(from:)","title":"init(from:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackNone":{"abstract":[{"text":"To not use a snap animation.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbacknone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PageSnapFeedbackNone","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2PageSnapFeedbackNone","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackNone","title":"SBSDKUI2PageSnapFeedbackNone"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackNone\/title","value":"SBSDKUI2PageSnapFeedbackNone","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackNone"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackNone\/fragments"},{"value":[{"text":"SBSDKUI2PageSnapFeedbackNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackNone\/navigatorTitle"}]}]}