{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters\/binarydocumentoptimizedcompression"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters\/binarydocumentoptimizedcompression"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"binaryDocumentOptimizedCompression","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binaryDocumentOptimizedCompression","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters(cpy)binaryDocumentOptimizedCompression","roleHeading":"Type Property","symbolKind":"property","navigatorTitle":[{"text":"binaryDocumentOptimizedCompression","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"binaryDocumentOptimizedCompression"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","kind":"typeIdentifier","text":"SBSDKCompressionMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Default is CCITT_T6"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters\/binaryDocumentOptimizedCompression","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Compression mode typically producing the smallest file sizes for binary (1-bit) document images.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGeneratorParameters/binaryDocumentOptimizedCompression":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters\/binarydocumentoptimizedcompression","title":"binaryDocumentOptimizedCompression","kind":"symbol","navigatorTitle":[{"text":"binaryDocumentOptimizedCompression","kind":"identifier"}],"abstract":[{"type":"text","text":"Compression mode typically producing the smallest file sizes for binary (1-bit) document images."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters\/binaryDocumentOptimizedCompression","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binaryDocumentOptimizedCompression","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode":{"abstract":[{"text":"TIFF compression type.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode","type":"topic","navigatorTitle":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"title":"SBSDKCompressionMode","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGeneratorParameters":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters","navigatorTitle":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters","abstract":[{"type":"text","text":"TIFF generator parameters."}],"title":"SBSDKTIFFGeneratorParameters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"binaryDocumentOptimizedCompression","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"binaryDocumentOptimizedCompression","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode"},{"text":" * ","kind":"text"},{"text":"binaryDocumentOptimizedCompression","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters~1binaryDocumentOptimizedCompression\/title","value":"binaryDocumentOptimizedCompression","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters~1binaryDocumentOptimizedCompression\/fragments","value":[{"text":"binaryDocumentOptimizedCompression","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/title","value":"SBSDKCompressionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/fragments","value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/navigatorTitle","value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/title","value":"SBSDKTIFFGeneratorParameters","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace"}]}]}