{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImageVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleSelected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"titleSelected"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitleSelected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"subtitleSelected"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleDeselected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"titleDeselected"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitleDeselected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"subtitleDeselected"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundSelected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundSelected"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundDeselected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundDeselected"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration\/initwithimagevisible:titleselected:subtitleselected:titledeselected:subtitledeselected:backgroundselected:backgrounddeselected:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration(im)initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration\/initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemConfiguration":{"title":"SBSDKUI2BarcodeItemConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration","abstract":[{"type":"text","text":"Configuration of the barcode info box displayed in the camera preview."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"title":"SBSDKUI2StyledText","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemConfiguration/initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration\/initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration\/initwithimagevisible:titleselected:subtitleselected:titledeselected:subtitledeselected:backgroundselected:backgrounddeselected:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:"}],"role":"symbol","title":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PolygonStyle":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2polygonstyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PolygonStyle","title":"SBSDKUI2PolygonStyle","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"abstract":[{"type":"text","text":"Configuration of the polygon appearance."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/title","value":"SBSDKUI2BarcodeItemConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/fragments","value":[{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/fragments","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PolygonStyle\/title","value":"SBSDKUI2PolygonStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PolygonStyle\/fragments","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PolygonStyle\/navigatorTitle","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}