{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"resourceBundle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":"?","kind":"text"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/resourcebundle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/resourcebundle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"resourceBundle","symbolKind":"property","navigatorTitle":[{"text":"resourceBundle","kind":"identifier"}],"roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resourceBundle","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)Scanbot(cpy)resourceBundle","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/resourceBundle"},"abstract":[{"text":"The bundle that ScanbotSDK searches for its additional data bundles.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults is ","type":"text"},{"type":"codeVoice","code":"Bundle.main"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot":{"abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Scanbot","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot","navigatorTitle":[{"kind":"identifier","text":"Scanbot"}],"type":"topic","kind":"symbol","title":"Scanbot","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot/resourceBundle":{"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resourceBundle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbot\/resourcebundle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/resourceBundle","navigatorTitle":[{"kind":"identifier","text":"resourceBundle"}],"abstract":[{"text":"The bundle that ScanbotSDK searches for its additional data bundles.","type":"text"},{"type":"text","text":" "},{"text":"Defaults is ","type":"text"},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"title":"resourceBundle","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"resourceBundle"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"resourceBundle","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"NSBundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" * "},{"text":"resourceBundle","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/title","op":"replace","value":"Scanbot"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/fragments","value":[{"kind":"identifier","text":"Scanbot"}],"op":"replace"},{"value":"resourceBundle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1resourceBundle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1resourceBundle\/fragments","value":[{"text":"resourceBundle","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}