{"metadata":{"roleHeading":"Type Method","title":"setupDefaultLicenseFailureHandler(completion:)","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)Scanbot(cm)setupDefaultLicenseFailureHandlerWithCompletion:","navigatorTitle":[{"kind":"identifier","text":"setupDefaultLicenseFailureHandlerWithCompletion:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(setupDefaultLicenseFailureHandlerWithCompletion:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> ())?)"}],"languages":["swift"]}]},{"parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"An optional block being executed after the user pressed the OK-button in the alert."}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Sets up the default license failure handler which is being called when the license or trial time expired.","type":"text"},{"text":" ","type":"text"},{"text":"The default handler shows an alert to inform your users about the expired license or trial period.","type":"text"}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot":{"abstract":[{"text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration.","type":"text"}],"title":"Scanbot","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot","navigatorTitle":[{"text":"Scanbot","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Scanbot","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot/setupDefaultLicenseFailureHandler(completion:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)","title":"setupDefaultLicenseFailureHandler(completion:)","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)","type":"topic","abstract":[{"text":"Sets up the default license failure handler which is being called when the license or trial time expired.","type":"text"},{"text":" ","type":"text"},{"text":"The default handler shows an alert to inform your users about the expired license or trial period.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> ())?)"}],"navigatorTitle":[{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setupDefaultLicenseFailureHandlerWithCompletion:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional block being executed after the user pressed the OK-button in the alert."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/title","value":"Scanbot","op":"replace"},{"value":[{"kind":"identifier","text":"Scanbot"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/navigatorTitle","value":[{"kind":"identifier","text":"Scanbot"}],"op":"replace"},{"value":"setupDefaultLicenseFailureHandlerWithCompletion:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1setupDefaultLicenseFailureHandler(completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1setupDefaultLicenseFailureHandler(completion:)\/fragments","op":"replace"}]}]}