{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithExpectedCountry:"}],"title":"initWithExpectedCountry:","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardConfiguration(im)initWithExpectedCountry:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithExpectedCountry:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration\/initWithExpectedCountry:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithExpectedCountry:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"expectedCountry","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardconfiguration\/initwithexpectedcountry:"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardConfiguration/initWithExpectedCountry:":{"type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithExpectedCountry:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithExpectedCountry:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration\/initWithExpectedCountry:","abstract":[],"title":"initWithExpectedCountry:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardconfiguration\/initwithexpectedcountry:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardIssuingCountry":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"title":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","abstract":[{"type":"text","text":"European Health Insurance Card (EHIC) issuing country."}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardissuingcountry","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardIssuingCountry","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardConfiguration":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardConfiguration"}],"navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardConfiguration","abstract":[{"type":"text","text":"European Health Insurance Card (EHIC) configuration element. Add to extractor configuration to scan EHICs."}],"title":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry\/title"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry\/fragments","op":"replace"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardIssuingCountry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardIssuingCountry\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/title","value":"SBSDKEuropeanHealthInsuranceCardConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardConfiguration\/navigatorTitle","value":[{"text":"SBSDKEuropeanHealthInsuranceCardConfiguration","kind":"identifier"}]}]}]}