{"metadata":{"extendedModule":"SwiftUICore","title":"accessibility(activationPoint:)","role":"symbol","platforms":[{"unavailable":false,"renamed":"accessibilityActivationPoint(_:)","name":"iOS","introducedAt":"13.0","deprecated":false,"deprecatedAt":"100000.0","beta":false},{"unavailable":false,"renamed":"accessibilityActivationPoint(_:)","name":"iPadOS","introducedAt":"13.0","deprecated":false,"deprecatedAt":"100000.0","beta":false},{"unavailable":false,"renamed":"accessibilityActivationPoint(_:)","name":"Mac Catalyst","introducedAt":"13.0","deprecated":false,"deprecatedAt":"100000.0","beta":false},{"unavailable":false,"renamed":"accessibilityActivationPoint(_:)","name":"macOS","introducedAt":"10.15","deprecated":false,"deprecatedAt":"100000.0","beta":false},{"unavailable":false,"renamed":"accessibilityActivationPoint(_:)","name":"tvOS","introducedAt":"13.0","deprecated":false,"deprecatedAt":"100000.0","beta":false},{"unavailable":false,"renamed":"accessibilityActivationPoint(_:)","name":"visionOS","introducedAt":"1.0","deprecated":false,"deprecatedAt":"100000.0","beta":false},{"unavailable":false,"renamed":"accessibilityActivationPoint(_:)","name":"watchOS","introducedAt":"6.0","deprecated":false,"deprecatedAt":"100000.0","beta":false}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibility"},{"kind":"text","text":"("},{"kind":"externalParam","text":"activationPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI9UnitPointV","kind":"typeIdentifier","text":"UnitPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","kind":"typeIdentifier","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}],"symbolKind":"method","externalID":"s:7SwiftUI4ViewPAAE13accessibility15activationPointAA15ModifiedContentVyxAA31AccessibilityAttachmentModifierVGAA04UnitF0V_tF::SYNTHESIZED::s:10ScanbotSDK24SBSDKUI2CheckScannerViewV","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/accessibility(activationPoint:)-2c4kg","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/View-Implementations"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/accessibility(activationpoint:)-2c4kg"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.accessibility(activationPoint:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"activationPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnitPoint","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI9UnitPointV"},{"text":") -> ","kind":"text"},{"text":"ModifiedContent","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AccessibilityAttachmentModifier","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView":{"title":"SBSDKUI2CheckScannerView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerView","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CheckScannerView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","type":"reference"},{"text":".","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/accessibility(activationPoint:)-2c4kg":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/accessibility(activationPoint:)-2c4kg","kind":"symbol","type":"topic","title":"accessibility(activationPoint:)","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/accessibility(activationpoint:)-2c4kg","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibility"},{"kind":"text","text":"("},{"kind":"externalParam","text":"activationPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI9UnitPointV","text":"UnitPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerView/View-Implementations":{"role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerview\/view-implementations","type":"topic","title":"View Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerView\/View-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerViewController":{"navigatorTitle":[{"text":"SBSDKUI2CheckScannerViewController","kind":"identifier"}],"title":"SBSDKUI2CheckScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerViewController","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan check data."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CheckScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/title"},{"value":[{"text":"SBSDKUI2CheckScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/fragments"},{"value":[{"text":"SBSDKUI2CheckScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}