{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/crewMemberCertificate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The document is a crew member certificate."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/crewmembercertificate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/crewmembercertificate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"crewMemberCertificate"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.crewMemberCertificate","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultDocumentType@SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate","symbolKind":"case"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"crewMemberCertificate","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/crewMemberCertificate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/crewMemberCertificate","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"crewMemberCertificate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The document is a crew member certificate."}],"title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.crewMemberCertificate","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/crewmembercertificate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"abstract":[{"type":"text","text":"The type classifier for machine-readable-zone document types."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType","role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1crewMemberCertificate\/title"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeCrewMemberCertificate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1crewMemberCertificate\/fragments","op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerResultDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/title"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/fragments","op":"replace"}]}]}