{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/idCard","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/idcard"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/idcard"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.idCard","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"idCard","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultDocumentType@SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"abstract":[{"text":"The document is an ID card.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"idCard"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/idCard":{"abstract":[{"type":"text","text":"The document is an ID card."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"idCard","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.idCard","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/idCard","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/idcard"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType":{"type":"topic","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"abstract":[{"type":"text","text":"The type classifier for machine-readable-zone document types."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1idCard\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1idCard\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeIdCard"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/navigatorTitle"}]}]}