{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/passport","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The document is a passport."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/passport"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/passport"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"passport","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","symbolKind":"case","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.passport","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultDocumentType@SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passport"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/passport":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/passport","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.passport","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/passport","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passport"}],"type":"topic","abstract":[{"type":"text","text":"The document is a passport."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The type classifier for machine-readable-zone document types."}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype","role":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1passport\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1passport\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypePassport"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentType","op":"replace"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/navigatorTitle","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}