{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"swissDriverLicense"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/swissDriverLicense","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType"]]},"metadata":{"roleHeading":"Case","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.swissDriverLicense","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"swissDriverLicense","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultDocumentType@SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense","symbolKind":"case","modules":[{"name":"ScanbotSDK"}]},"sections":[],"abstract":[{"text":"The document is a Swiss driver license.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/swissdriverlicense"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/swissdriverlicense"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/swissDriverLicense":{"title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.swissDriverLicense","abstract":[{"type":"text","text":"The document is a Swiss driver license."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/swissdriverlicense","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"swissDriverLicense","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/swissDriverLicense"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType":{"abstract":[{"text":"The type classifier for machine-readable-zone document types.","type":"text"}],"title":"SBSDKMachineReadableZoneRecognizerResultDocumentType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1swissDriverLicense\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense","op":"replace"},{"op":"replace","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeSwissDriverLicense","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1swissDriverLicense\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/fragments","op":"replace","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}