{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visa"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visa"}],"title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.visa","externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultDocumentType@SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa","roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/visa","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/visa"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/visa"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType"]]},"kind":"symbol","abstract":[{"text":"The document is a visa.","type":"text"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType/visa":{"title":"SBSDKMachineReadableZoneRecognizerResultDocumentType.visa","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType\/visa","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"visa"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype\/visa","kind":"symbol","abstract":[{"text":"The document is a visa.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultDocumentType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultDocumentType","title":"SBSDKMachineReadableZoneRecognizerResultDocumentType","abstract":[{"text":"The type classifier for machine-readable-zone document types.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentType","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultdocumenttype","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1visa\/title","value":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType~1visa\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultDocumentTypeVisa","kind":"identifier"}]},{"value":"SBSDKMachineReadableZoneRecognizerResultDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultDocumentType\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultDocumentType"}]}]}]}