{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroNoImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINIntroNoImage(im)init"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroNoImage\/init","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinintronoimage\/init"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINIntroNoImage/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroNoImage\/init","title":"init","url":"\/documentation\/scanbotsdk\/sbsdkui2vinintronoimage\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINIntroNoImage":{"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"No image for the introduction screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINIntroNoImage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2VINIntroNoImage","kind":"identifier"}],"title":"SBSDKUI2VINIntroNoImage","url":"\/documentation\/scanbotsdk\/sbsdkui2vinintronoimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroNoImage"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2VINIntroNoImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroNoImage\/title"},{"op":"replace","value":[{"text":"SBSDKUI2VINIntroNoImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroNoImage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINIntroNoImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroNoImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}