{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroListEntry"]]},"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroListEntry(im)copyWithZone:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroListEntry\/copyWithZone:"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2introlistentry\/copywithzone:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroListEntry/copyWithZone:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroListEntry\/copyWithZone:","kind":"symbol","title":"copyWithZone:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2introlistentry\/copywithzone:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroListEntry":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2IntroListEntry","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroListEntry","abstract":[{"text":"An entry in the list of scanning steps of the introduction screen.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2introlistentry","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IntroListEntry","kind":"identifier"}],"title":"SBSDKUI2IntroListEntry","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroListEntry\/title","value":"SBSDKUI2IntroListEntry"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroListEntry\/fragments","value":[{"text":"SBSDKUI2IntroListEntry","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroListEntry\/navigatorTitle","value":[{"text":"SBSDKUI2IntroListEntry","kind":"identifier"}]}]}]}