{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration\/finalFrame","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"finalFrame"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentAnimationConfiguration(py)finalFrame","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finalFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"symbolKind":"property","roleHeading":"Instance Property","title":"finalFrame"},"kind":"symbol","abstract":[{"type":"text","text":"The final frame where the animated document should animate to."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finalFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"If the value is ","type":"text"},{"code":"CGRect.zero","type":"codeVoice"},{"text":", the animated document disappears after being presented.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Defaults to "},{"code":"CGRect.zero","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration\/finalframe"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration\/finalframe"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentAnimationConfiguration/finalFrame":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finalFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"title":"finalFrame","type":"topic","kind":"symbol","navigatorTitle":[{"text":"finalFrame","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The final frame where the animated document should animate to.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration\/finalFrame","url":"\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration\/finalframe"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentAnimationConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentAnimationConfiguration","title":"SBSDKDocumentAnimationConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"abstract":[{"text":"A class to configure the document animation properties.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentanimationconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"finalFrame","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"finalFrame"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"finalFrame","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"finalFrame","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration~1finalFrame\/title","op":"replace"},{"value":[{"kind":"identifier","text":"finalFrame"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration~1finalFrame\/fragments","op":"replace"},{"value":"SBSDKDocumentAnimationConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentAnimationConfiguration\/navigatorTitle","op":"replace"}]}]}