{"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"australiaPostCustomerFormat","kind":"identifier"}],"title":"australiaPostCustomerFormat","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration(py)australiaPostCustomerFormat"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/australiapostcustomerformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/australiapostcustomerformat"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration\/australiaPostCustomerFormat","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is ALPHA_NUMERIC"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"The customer format used in AUSTRALIA_POST codes. The default value is ALPHA_NUMERIC."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerConfiguration/australiaPostCustomerFormat":{"navigatorTitle":[{"text":"australiaPostCustomerFormat","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The customer format used in AUSTRALIA_POST codes. The default value is ALPHA_NUMERIC."}],"kind":"symbol","title":"australiaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration\/australiaPostCustomerFormat","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration\/australiapostcustomerformat"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeScannerConfiguration":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeScannerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodescannerconfiguration","abstract":[{"text":"Configuration of the scanning behavior.","type":"text"}],"title":"SBSDKUI2BarcodeScannerConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAustraliaPostCustomerFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"abstract":[{"text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"title":"SBSDKAustraliaPostCustomerFormat","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaustraliapostcustomerformat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAustraliaPostCustomerFormat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"australiaPostCustomerFormat","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKAustraliaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAustraliaPostCustomerFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"australiaPostCustomerFormat"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration~1australiaPostCustomerFormat\/title","value":"australiaPostCustomerFormat","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration~1australiaPostCustomerFormat\/fragments","value":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"op":"replace"},{"value":"SBSDKUI2BarcodeScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeScannerConfiguration\/navigatorTitle"},{"value":"SBSDKAustraliaPostCustomerFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAustraliaPostCustomerFormat\/title"},{"value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAustraliaPostCustomerFormat\/fragments"},{"value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAustraliaPostCustomerFormat\/navigatorTitle"}]}]}