{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/capturemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/capturemode"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountCaptureMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeScanAndCountCaptureMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode\/videoFrame","type":"reference","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"The barcode scan and count capture mode.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController\/captureMode","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController(py)captureMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeScanAndCountCaptureMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeScanAndCountCaptureMode"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"captureMode"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","title":"captureMode","symbolKind":"property"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountCaptureMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"kind":"symbol","title":"SBSDKBarcodeScanAndCountCaptureMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}],"abstract":[{"type":"text","text":"The capture mode of the barcode scan and count."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountcapturemode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountCaptureMode/videoFrame":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode\/videoFrame","abstract":[{"text":"Uses the last frame form the camera input to scan barcodes on.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountcapturemode\/videoframe","kind":"symbol","title":"SBSDKBarcodeScanAndCountCaptureMode.videoFrame","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrame","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController/captureMode":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController\/captureMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller\/capturemode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeScanAndCountCaptureMode","text":"SBSDKBarcodeScanAndCountCaptureMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"captureMode"}],"abstract":[{"text":"The barcode scan and count capture mode.","type":"text"}],"title":"captureMode","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController":{"title":"SBSDKBarcodeScanAndCountViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."},{"type":"text","text":" "},{"type":"text","text":"Screen also shows snap, scan more and reset buttons."},{"type":"text","text":" "},{"text":"The snap button starts the scanning when tapped.","type":"text"},{"text":" ","type":"text"},{"text":"The snap button resets the scanning when tapped again.","type":"text"},{"text":" ","type":"text"},{"text":"Instead it is installing itself as a child view controller onto a given parent view controller.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"captureMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"captureMode"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountCaptureMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeScanAndCountCaptureMode","text":"SBSDKBarcodeScanAndCountCaptureMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountCaptureMode\/title","op":"replace","value":"SBSDKBarcodeScanAndCountCaptureMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountCaptureMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountCaptureMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountCaptureMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountCaptureMode~1videoFrame\/title","op":"replace","value":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountCaptureMode~1videoFrame\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountCaptureModeVideoFrame"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController~1captureMode\/title","op":"replace","value":"captureMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController~1captureMode\/fragments","op":"replace","value":[{"text":"captureMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/title","op":"replace","value":"SBSDKBarcodeScanAndCountViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}]}]}]}