{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration\/statusBarMode","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"statusBarMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode","kind":"typeIdentifier","text":"SBSDKUI2StatusBarMode"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusBarMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode","text":"SBSDKUI2StatusBarMode","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration(py)statusBarMode","symbolKind":"property","role":"symbol","title":"statusBarMode","navigatorTitle":[{"text":"statusBarMode","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration"]]},"abstract":[{"text":"Visual mode used for the status bar icons.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is LIGHT"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration\/statusbarmode"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration\/statusbarmode"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarConfiguration/statusBarMode":{"type":"topic","abstract":[{"type":"text","text":"Visual mode used for the status bar icons."},{"type":"text","text":" "},{"type":"text","text":"Default is LIGHT"}],"navigatorTitle":[{"kind":"identifier","text":"statusBarMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration\/statusbarmode","role":"symbol","title":"statusBarMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration\/statusBarMode","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"statusBarMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2StatusBarMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StatusBarMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2statusbarmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"kind":"symbol","role":"symbol","title":"SBSDKUI2StatusBarMode","abstract":[{"type":"text","text":"Visual mode used for the status bar icons."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"abstract":[{"text":"Configuration of the top screen bar’s appearance.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration","kind":"symbol","title":"SBSDKUI2TopBarConfiguration","navigatorTitle":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"statusBarMode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"statusBarMode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode","kind":"typeIdentifier","text":"SBSDKUI2StatusBarMode"},{"text":" ","kind":"text"},{"text":"statusBarMode","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration~1statusBarMode\/title","op":"replace","value":"statusBarMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration~1statusBarMode\/fragments","op":"replace","value":[{"text":"statusBarMode","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2StatusBarMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/fragments","value":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}]},{"value":"SBSDKUI2TopBarConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/fragments","value":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}