{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithRegexFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"regexFilter","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumSizeScore:"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"minimumSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"addAdditionalQuietZone:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"addAdditionalQuietZone","kind":"internalParam"},{"kind":"text","text":" "},{"text":"formats:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeFormat *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"formats","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:formats:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:","fragments":[{"kind":"text","text":"- "},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonFourStateConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:"}],"modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple four-state barcode formats with a common"},{"text":" ","type":"text"},{"text":"configuration.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple four-state codes."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeFormatCommonFourStateConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:formats:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:formats:","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/title","value":"SBSDKBarcodeFormatCommonFourStateConfiguration"},{"value":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}