{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(scanFromFrame:useLiveMode:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"frame","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","kind":"typeIdentifier","text":"SBSDKBaseScannerFrame","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useLiveMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"SBSDKCheckScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]},{"parameters":[{"name":"frame","content":[{"inlineContent":[{"type":"text","text":"The frame to scan from."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Whether to use live or single shot mode."}],"type":"paragraph"}],"name":"useLiveMode"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The result of the scanning."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner\/scan(from:useLiveMode:)-4459k","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKBaseScannerFrame","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame"},{"text":", ","kind":"text"},{"text":"useLiveMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCheckScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"scanFromFrame:useLiveMode:","kind":"identifier"}],"title":"scan(from:useLiveMode:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanner(im)scanFromFrame:useLiveMode:"},"kind":"symbol","abstract":[{"type":"text","text":"Scans a bank check on the given "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","type":"reference"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanner\/scan(from:uselivemode:)-4459k"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanner\/scan(from:uselivemode:)-4459k"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanner/scan(from:useLiveMode:)-4459k":{"navigatorTitle":[{"kind":"identifier","text":"scanFromFrame:useLiveMode:"}],"type":"topic","title":"scan(from:useLiveMode:)","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanner\/scan(from:uselivemode:)-4459k","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scan"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier","text":"SBSDKBaseScannerFrame"},{"kind":"text","text":", "},{"text":"useLiveMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","text":"SBSDKCheckScanningResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner\/scan(from:useLiveMode:)-4459k","abstract":[{"type":"text","text":"Scans a bank check on the given "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","isActive":true},{"text":".","type":"text"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerFrame":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerframe","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"abstract":[{"type":"text","text":"A wrapper class for video frames."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","role":"symbol","type":"topic","title":"SBSDKBaseScannerFrame"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanner":{"type":"topic","navigatorTitle":[{"text":"SBSDKCheckScanner","kind":"identifier"}],"title":"SBSDKCheckScanner","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCheckScanner","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanner","abstract":[{"text":"A scanner to scan bank checks on various image sources.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanningResult":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"title":"SBSDKCheckScanningResult","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanningresult","abstract":[{"text":"The result of check scanning.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScanningResult"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"scanFromFrame:useLiveMode:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"scanFromFrame:useLiveMode:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult","kind":"typeIdentifier","text":"SBSDKCheckScanningResult"},{"kind":"text","text":" *) "},{"text":"scanFromFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBaseScannerFrame","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"useLiveMode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"useLiveMode"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"text":"The frame to scan from.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to use live or single shot mode."}]}],"name":"useLiveMode"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The result of the scanning.","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner~1scan(from:useLiveMode:)-4459k\/title","value":"scanFromFrame:useLiveMode:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner~1scan(from:useLiveMode:)-4459k\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scanFromFrame:useLiveMode:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/title","op":"replace","value":"SBSDKBaseScannerFrame"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/fragments","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/title","value":"SBSDKCheckScanner"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/fragments","op":"replace","value":[{"text":"SBSDKCheckScanner","kind":"identifier"}]},{"value":[{"text":"SBSDKCheckScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKCheckScanningResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckScanningResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}]}]}]}