{"kind":"symbol","metadata":{"platforms":[{"introducedAt":"13.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"13.0","name":"iPadOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.0","name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"10.15","name":"macOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.0","name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"6.0","name":"watchOS","deprecated":false,"unavailable":false}],"roleHeading":"Instance Method","externalID":"s:7SwiftUI4ViewPAAE17listRowBackgroundyQrqd__SgAaBRd__lF::SYNTHESIZED::s:10ScanbotSDK22SBSDKUI2VINScannerViewV","role":"symbol","extendedModule":"SwiftUICore","symbolKind":"method","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"title":"listRowBackground(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listRowBackground","kind":"identifier"},{"text":"<","kind":"text"},{"text":"V","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"V","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/listrowbackground(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/listRowBackground(_:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/View-Implementations"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.listRowBackground(_:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listRowBackground"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"V"},{"kind":"text","text":">("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"text":": ","kind":"text"},{"text":"V","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":" ","kind":"text"},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"V"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":"\n"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerViewController"}],"title":"SBSDKUI2VINScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan VIN (Vehicle Identification Number) data."}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerviewcontroller","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView/View-Implementations":{"type":"topic","title":"View Implementations","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/view-implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/View-Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView/listRowBackground(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/listRowBackground(_:)","kind":"symbol","title":"listRowBackground(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listRowBackground"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"V"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"V"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/listrowbackground(_:)","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView":{"title":"SBSDKUI2VINScannerView","type":"topic","abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerView"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2VINScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2VINScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/navigatorTitle"}]}]}