{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithBarcodeFormatConfigurations:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeFormatConfigurationBase *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeFormatConfigurations","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extractedDocumentFormats:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeDocumentFormat *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"extractedDocumentFormats"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyAcceptDocuments:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"onlyAcceptDocuments"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnBarcodeImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"returnBarcodeImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"engineMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerEngineMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeScannerEngineMode","kind":"typeIdentifier","text":"SBSDKBarcodeScannerEngineMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"engineMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"accumulationConfig:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeAccumulationConfiguration","kind":"typeIdentifier","text":"SBSDKBarcodeAccumulationConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accumulationConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"optimizedForOverlays:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"optimizedForOverlays"},{"kind":"text","text":" "},{"kind":"identifier","text":"processingMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKProcessingMode","kind":"typeIdentifier","text":"SBSDKProcessingMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"processingMode"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration\/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:"},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerConfiguration(im)initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration\/initwithbarcodeformatconfigurations:extracteddocumentformats:onlyacceptdocuments:returnbarcodeimage:enginemode:accumulationconfig:optimizedforoverlays:processingmode:"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration"]]},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode":{"title":"SBSDKProcessingMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingMode"}],"abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"},{"text":" ","type":"text"},{"text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results.","type":"text"},{"text":" ","type":"text"},{"text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerConfiguration/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:":{"title":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration\/initwithbarcodeformatconfigurations:extracteddocumentformats:onlyacceptdocuments:returnbarcodeimage:enginemode:accumulationconfig:optimizedforoverlays:processingmode:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration\/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:processingMode:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerEngineMode":{"type":"topic","kind":"symbol","title":"SBSDKBarcodeScannerEngineMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerEngineMode","abstract":[{"text":"The engine mode for barcode scanning.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerenginemode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeAccumulationConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeAccumulationConfiguration","abstract":[{"type":"text","text":"Configuration for how to accumulate results."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration","abstract":[{"text":"Configuration for the barcode scanner.","type":"text"}],"role":"symbol","type":"topic","title":"SBSDKBarcodeScannerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/title","value":"SBSDKProcessingMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/title","value":"SBSDKBarcodeScannerEngineMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/title","value":"SBSDKBarcodeAccumulationConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/title","value":"SBSDKBarcodeScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/fragments","value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle","op":"replace"}]}]}