{"kind":"article","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController\/healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKHealthInsuranceCardScannerViewControllerDelegate Implementations","role":"collectionGroup"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontroller\/sbsdkhealthinsurancecardscannerviewcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontroller\/sbsdkhealthinsurancecardscannerviewcontrollerdelegate-implementations"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController\/SBSDKHealthInsuranceCardScannerViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerViewController":{"title":"SBSDKUIHealthInsuranceCardScannerViewController","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewController"}],"abstract":[{"text":"A view controller for camera-based detection of health insurance cards.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerViewController/healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"healthInsuranceCardScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardScannerViewController","text":"SBSDKHealthInsuranceCardScannerViewController"},{"text":", ","kind":"text"},{"text":"didScanHealthInsuranceCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognitionResult","text":"SBSDKHealthInsuranceCardRecognitionResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController\/healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)","title":"healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscannerviewcontroller\/healthinsurancecardscannerviewcontroller(_:didscanhealthinsurancecard:)","kind":"symbol","abstract":[{"text":"Informs the delegate that a health insurance card has been scanned.","type":"text"}],"navigatorTitle":[{"text":"healthInsuranceCardScannerViewController:didScanHealthInsuranceCard:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerViewController\/healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/title","value":"SBSDKUIHealthInsuranceCardScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/fragments","value":[{"text":"SBSDKUIHealthInsuranceCardScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController~1healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)\/title","value":"healthInsuranceCardScannerViewController:didScanHealthInsuranceCard:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"healthInsuranceCardScannerViewController:didScanHealthInsuranceCard:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerViewController~1healthInsuranceCardScannerViewController(_:didScanHealthInsuranceCard:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}