{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult\/barcodeResult","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Barcode result of the VIN scanner."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVINBarcodeResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"barcodeResult"}],"modules":[{"name":"ScanbotSDK"}],"title":"barcodeResult","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerUIResult(py)barcodeResult","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKVINBarcodeResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult\/barcoderesult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult\/barcoderesult"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerUIResult/barcodeResult":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult","kind":"typeIdentifier","text":"SBSDKVINBarcodeResult"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeResult"}],"abstract":[{"text":"Barcode result of the VIN scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult\/barcodeResult","kind":"symbol","title":"barcodeResult","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult\/barcoderesult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeResult":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"title":"SBSDKVINBarcodeResult","abstract":[{"text":"Result of the barcode scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKVINBarcodeResult","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcoderesult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerUIResult":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"title":"SBSDKUI2VINScannerUIResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult","navigatorTitle":[{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"abstract":[{"text":"Configuration of the generic text scanner RTU UI result.","type":"text"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"barcodeResult","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"barcodeResult"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKVINBarcodeResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINBarcodeResult","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"barcodeResult","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult~1barcodeResult\/title","value":"barcodeResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult~1barcodeResult\/fragments","value":[{"text":"barcodeResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/title","value":"SBSDKVINBarcodeResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINBarcodeResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/title","value":"SBSDKUI2VINScannerUIResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/fragments","value":[{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerUIResult"}],"op":"replace"}]}]}