{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"topToBottom","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This is experimental and not working properly in all cases."}],"type":"paragraph"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection\/topToBottom"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection"]]},"sections":[],"kind":"symbol","abstract":[{"text":"The text (in up-orientation) is read from top to bottom (Japanese, etc.).","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkwritingdirection\/toptobottom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkwritingdirection\/toptobottom"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKWritingDirection.topToBottom","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"topToBottom","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKWritingDirectionTopToBottom","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKWritingDirection@SBSDKWritingDirectionTopToBottom"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWritingDirection":{"abstract":[{"type":"text","text":"An enum to describe the reading direction of the text independently from its orientation."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKWritingDirection","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKWritingDirection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection","url":"\/documentation\/scanbotsdk\/sbsdkwritingdirection","title":"SBSDKWritingDirection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWritingDirection/topToBottom":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"topToBottom","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The text (in up-orientation) is read from top to bottom (Japanese, etc.)."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection\/topToBottom","url":"\/documentation\/scanbotsdk\/sbsdkwritingdirection\/toptobottom","title":"SBSDKWritingDirection.topToBottom","type":"topic","navigatorTitle":[{"text":"SBSDKWritingDirectionTopToBottom","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKWritingDirectionTopToBottom"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKWritingDirectionTopToBottom"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKWritingDirectionTopToBottom","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/title","value":"SBSDKWritingDirection"},{"op":"replace","value":[{"text":"SBSDKWritingDirection","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKWritingDirection"}],"op":"replace"},{"value":"SBSDKWritingDirectionTopToBottom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection~1topToBottom\/title"},{"value":[{"text":"SBSDKWritingDirectionTopToBottom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection~1topToBottom\/fragments"}]}]}