{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","platforms":[],"title":"SBSDKImageFilterType.pureGray","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pureGray"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypePureGray","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKImageFilterTypePureGray","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/pureGray"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pureGray"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/puregray"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/puregray"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Standard grayscale filter. Creates a grayscaled 8-bit image.","type":"text"}],"sections":[],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType","abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype","kind":"symbol","role":"symbol","title":"SBSDKImageFilterType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageFilterType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFilterType/pureGray":{"role":"symbol","type":"topic","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFilterType\/pureGray","title":"SBSDKImageFilterType.pureGray","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pureGray"}],"navigatorTitle":[{"text":"SBSDKImageFilterTypePureGray","kind":"identifier"}],"abstract":[{"text":"Standard grayscale filter. Creates a grayscaled 8-bit image.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagefiltertype\/puregray"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageFilterTypePureGray"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterTypePureGray"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKImageFilterTypePureGray","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SBSDKImageFilterType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/fragments"},{"value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1pureGray\/title","value":"SBSDKImageFilterTypePureGray","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFilterType~1pureGray\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypePureGray"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}