{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"colorEnhancement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 0.5"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcolordocumentfilter\/colorenhancement"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcolordocumentfilter\/colorenhancement"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter\/colorEnhancement","interfaceLanguage":"swift"},"abstract":[{"text":"Strength of color saturation enhancement. Typical values are between 0 and 1, although higher values are possible.","type":"text"}],"kind":"symbol","metadata":{"title":"colorEnhancement","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKColorDocumentFilter(py)colorEnhancement","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"colorEnhancement","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorEnhancement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKColorDocumentFilter":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcolordocumentfilter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"abstract":[{"type":"text","text":"Color document filter. This filter is a good starting point for most use cases."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter","title":"SBSDKColorDocumentFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKColorDocumentFilter/colorEnhancement":{"navigatorTitle":[{"kind":"identifier","text":"colorEnhancement"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcolordocumentfilter\/colorenhancement","title":"colorEnhancement","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorEnhancement"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter\/colorEnhancement","kind":"symbol","abstract":[{"type":"text","text":"Strength of color saturation enhancement. Typical values are between 0 and 1, although higher values are possible."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"colorEnhancement","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"colorEnhancement"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"colorEnhancement","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKColorDocumentFilter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/title","op":"replace"},{"value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/fragments","op":"replace"},{"value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/navigatorTitle","op":"replace"},{"value":"colorEnhancement","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter~1colorEnhancement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"colorEnhancement"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter~1colorEnhancement\/fragments","op":"replace"}]}]}