{"metadata":{"navigatorTitle":[{"text":"fileStorageImageFormat","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"fileStorageImageFormat","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration(py)fileStorageImageFormat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileStorageImageFormat"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/fileStorageImageFormat","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The image format used when storing images. Defaults to ","type":"text"},{"code":".JPEG","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileStorageImageFormat"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","kind":"typeIdentifier"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestorageimageformat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestorageimageformat"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFileFormat":{"role":"symbol","kind":"symbol","title":"SBSDKImageFileFormat","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefileformat","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"identifier"}],"abstract":[{"text":"Enumeration of supported image file types.","type":"text"}],"navigatorTitle":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration/fileStorageImageFormat":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/fileStorageImageFormat","abstract":[{"type":"text","text":"The image format used when storing images. Defaults to "},{"type":"codeVoice","code":".JPEG"},{"type":"text","text":"."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fileStorageImageFormat"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"}],"navigatorTitle":[{"kind":"identifier","text":"fileStorageImageFormat"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestorageimageformat","title":"fileStorageImageFormat"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration","navigatorTitle":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"kind":"symbol","title":"ScanbotSDKConfiguration","abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"fileStorageImageFormat","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"fileStorageImageFormat"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileStorageImageFormat"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/title","value":"SBSDKImageFileFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/fragments","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1fileStorageImageFormat\/title","op":"replace","value":"fileStorageImageFormat"},{"op":"replace","value":[{"kind":"identifier","text":"fileStorageImageFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1fileStorageImageFormat\/fragments"},{"value":"ScanbotSDKConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}]}]}]}