{"abstract":[{"type":"text","text":"The bundle from which resources like image assets are loaded. Defaults to the main bundle."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/resourcebundle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/resourcebundle"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/resourceBundle","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resourceBundle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle"}],"navigatorTitle":[{"kind":"identifier","text":"resourceBundle"}],"title":"resourceBundle","roleHeading":"Instance Property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration(py)resourceBundle"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"resourceBundle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration/resourceBundle":{"abstract":[{"text":"The bundle from which resources like image assets are loaded. Defaults to the main bundle.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/resourcebundle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resourceBundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"title":"resourceBundle","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/resourceBundle","navigatorTitle":[{"kind":"identifier","text":"resourceBundle"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration","kind":"symbol","abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"type":"text","text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration","title":"ScanbotSDKConfiguration","role":"symbol","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"resourceBundle"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"resourceBundle"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"NSBundle","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"resourceBundle","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1resourceBundle\/title","op":"replace","value":"resourceBundle"},{"op":"replace","value":[{"kind":"identifier","text":"resourceBundle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1resourceBundle\/fragments"},{"op":"replace","value":"ScanbotSDKConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/title"},{"value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}]}]}]}