{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRegexFilter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"regexFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumSizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAdditionalQuietZone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"addAdditionalQuietZone"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKGS1Handling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling"},{"kind":"text","text":") "},{"kind":"internalParam","text":"gs1Handling"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatamatrixconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:gs1handling:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataMatrixConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatDataMatrixConfiguration":{"abstract":[{"type":"text","text":"DataMatrix configuration. Add to scanner configuration to scan DataMatrix and DataMatrix rectangular extensions"},{"type":"text","text":" "},{"type":"text","text":"(DMRE) codes."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatamatrixconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration","title":"SBSDKBarcodeFormatDataMatrixConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"title":"SBSDKGS1Handling","abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"type":"text","text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D"},{"type":"text","text":" "},{"type":"text","text":"barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatDataMatrixConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatamatrixconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:gs1handling:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeFormatDataMatrixConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatDataMatrixConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKGS1Handling","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments","op":"replace"},{"value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle","op":"replace"}]}]}