{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/copyWithZone:"},"sections":[],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickScanningMode(im)copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","title":"copyWithZone:","role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode","type":"topic","abstract":[{"type":"text","text":"Configuration of the Find and Pick barcode scanning mode."}],"title":"SBSDKUI2FindAndPickScanningMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickScanningMode/copyWithZone:":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickScanningMode\/copyWithZone:","abstract":[],"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickscanningmode\/copywithzone:","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/title","value":"SBSDKUI2FindAndPickScanningMode"},{"value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickScanningMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}