{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWord"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"roi:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"roi","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"glyphs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKGlyph *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"glyphs","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:confidence:roi:glyphs:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"initWithText:confidence:roi:glyphs:","navigatorTitle":[{"kind":"identifier","text":"initWithText:confidence:roi:glyphs:"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKWord(im)initWithText:confidence:roi:glyphs:","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkword\/initwithtext:confidence:roi:glyphs:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWord\/initWithText:confidence:roi:glyphs:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWord":{"title":"SBSDKWord","abstract":[{"type":"text","text":"Represents a single word. A word is made up of glyphs."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKWord","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKWord","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWord","url":"\/documentation\/scanbotsdk\/sbsdkword","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWord/initWithText:confidence:roi:glyphs:":{"role":"symbol","abstract":[],"type":"topic","title":"initWithText:confidence:roi:glyphs:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWord\/initWithText:confidence:roi:glyphs:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:confidence:roi:glyphs:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkword\/initwithtext:confidence:roi:glyphs:","navigatorTitle":[{"text":"initWithText:confidence:roi:glyphs:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKWord","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWord\/title"},{"value":[{"text":"SBSDKWord","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWord\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKWord"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWord\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}