{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllPages"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"removeAllPages()","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeAllPagesAndReturnError:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllPages","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument(im)removeAllPagesAndReturnError:"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/removeallpages()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/removeallpages()"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument\/removeAllPages()","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Removes all the pages from the receiver.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedDocument"}],"abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument","title":"SBSDKScannedDocument","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedDocument"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedDocument/removeAllPages()":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/removeallpages()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument\/removeAllPages()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllPages","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"removeAllPagesAndReturnError:","kind":"identifier"}],"title":"removeAllPages()","role":"symbol","abstract":[{"text":"Removes all the pages from the receiver.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeAllPagesAndReturnError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAllPagesAndReturnError:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeAllPagesAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/fragments","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument~1removeAllPages()\/title","value":"removeAllPagesAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument~1removeAllPages()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAllPagesAndReturnError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}