{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"The width of the image in pixels."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/imageWidth"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageWidth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageMetadata(py)imageWidth","modules":[{"name":"ScanbotSDK"}],"title":"imageWidth","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageWidth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"imageWidth","kind":"identifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagemetadata\/imagewidth"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagemetadata\/imagewidth"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata/imageWidth":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"imageWidth","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata\/imagewidth","abstract":[{"type":"text","text":"The width of the image in pixels."}],"navigatorTitle":[{"text":"imageWidth","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata\/imageWidth","type":"topic","title":"imageWidth","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadataProcessor":{"navigatorTitle":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadataprocessor","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"type":"topic","abstract":[{"text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor","title":"SBSDKImageMetadataProcessor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageMetadata":{"navigatorTitle":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagemetadata","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageMetadata"}],"type":"topic","abstract":[{"text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadataProcessor","isActive":true},{"text":" to extract metadata from and inject changed metadata into image data.","type":"text"}],"kind":"symbol","title":"SBSDKImageMetadata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageMetadata"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"imageWidth","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"imageWidth","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageWidth"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1imageWidth\/title","value":"imageWidth"},{"value":[{"kind":"identifier","text":"imageWidth"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata~1imageWidth\/fragments"},{"value":"SBSDKImageMetadataProcessor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadataProcessor\/fragments"},{"op":"replace","value":"SBSDKImageMetadata","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageMetadata\/fragments"}]}]}