{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"enableDetailedProfiling","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"enableDetailedProfiling"}],"title":"enableDetailedProfiling()","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableDetailedProfiling","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefProfiler(cm)enableDetailedProfiling","roleHeading":"Type Method","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/enabledetailedprofiling()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/enabledetailedprofiling()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/enableDetailedProfiling()","interfaceLanguage":"swift"},"abstract":[{"text":"After the function is called, ImageRefs will store additional information, such as source from which they were","type":"text"},{"type":"text","text":" "},{"type":"text","text":"created. This information may be important when trying to understand a profile. This function must be called"},{"type":"text","text":" "},{"text":"BEFORE the first ImageRef is created, otherwise details may be lost.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler":{"navigatorTitle":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler","abstract":[{"text":"ImageRef memory profiler.","type":"text"}],"title":"SBSDKImageRefProfiler","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageRefProfiler","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler/enableDetailedProfiling()":{"title":"enableDetailedProfiling()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/enableDetailedProfiling()","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/enabledetailedprofiling()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableDetailedProfiling","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"enableDetailedProfiling"}],"role":"symbol","abstract":[{"text":"After the function is called, ImageRefs will store additional information, such as source from which they were","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"created. This information may be important when trying to understand a profile. This function must be called"},{"text":" ","type":"text"},{"text":"BEFORE the first ImageRef is created, otherwise details may be lost.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"enableDetailedProfiling"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"enableDetailedProfiling"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"enableDetailedProfiling"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKImageRefProfiler","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/fragments","op":"replace","value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/navigatorTitle"},{"op":"replace","value":"enableDetailedProfiling","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1enableDetailedProfiling()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1enableDetailedProfiling()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"enableDetailedProfiling"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}