{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts"]]},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Timeouts(im)copyWithZone:","title":"copyWithZone:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts\/copyWithZone:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2timeouts\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Timeouts/copyWithZone:":{"abstract":[],"title":"copyWithZone:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2timeouts\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts\/copyWithZone:","type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Timeouts":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Timeouts","type":"topic","abstract":[{"text":"Configuration of timeouts.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2timeouts","title":"SBSDKUI2Timeouts","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Timeouts"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2Timeouts","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Timeouts\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Timeouts\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Timeouts\/navigatorTitle"}]}]}