{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/init(text:rawbytes:rawbytesencodings:structuredappendinfo:quad:quadnormalized:extendedquad:extendedquadnormalized:upceanextension:extracteddocument:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/init(text:rawbytes:rawbytesencodings:structuredappendinfo:quad:quadnormalized:extendedquad:extendedquadnormalized:upceanextension:extracteddocument:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rawBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rawBytesEncodings"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRangeEncoding","kind":"typeIdentifier","text":"SBSDKRangeEncoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"structuredAppendInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo","kind":"typeIdentifier","text":"SBSDKStructuredAppendInfo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"quad"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"quadNormalized"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"extendedQuad"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"extendedQuadNormalized"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"upcEanExtension"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extractedDocument"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/init(text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:)","interfaceLanguage":"swift"},"metadata":{"title":"init(text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:)","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem(im)initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rawBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rawBytesEncodings"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRangeEncoding","kind":"typeIdentifier","text":"SBSDKRangeEncoding"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"structuredAppendInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo","kind":"typeIdentifier","text":"SBSDKStructuredAppendInfo"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"quad"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"quadNormalized"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"extendedQuad"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"extendedQuadNormalized"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"upcEanExtension"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extractedDocument"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier","text":"SBSDKGenericDocument"},{"kind":"text","text":"?)"}],"role":"symbol","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"abstract":[{"text":"Generic document.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","title":"SBSDKGenericDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"kind":"symbol","role":"symbol","abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"text":" ","type":"text"},{"text":"considered separate barcodes.","type":"text"}],"title":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeItem"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem/init(text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:)":{"kind":"symbol","title":"init(text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/init(text:rawbytes:rawbytesencodings:structuredappendinfo:quad:quadnormalized:extendedquad:extendedquadnormalized:upceanextension:extracteddocument:)","navigatorTitle":[{"text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rawBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rawBytesEncodings","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKRangeEncoding","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRangeEncoding","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"structuredAppendInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"quad","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"quadNormalized","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"extendedQuad","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"extendedQuadNormalized","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"upcEanExtension","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"extractedDocument","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/init(text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRangeEncoding":{"navigatorTitle":[{"text":"SBSDKRangeEncoding","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding","url":"\/documentation\/scanbotsdk\/sbsdkrangeencoding","abstract":[{"text":"A character encoding for a given range of bytes.","type":"text"}],"role":"symbol","title":"SBSDKRangeEncoding","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRangeEncoding","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo":{"title":"SBSDKStructuredAppendInfo","abstract":[{"text":"The structured append mode can be used to split a message across multiple barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rawBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"rawBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rawBytesEncodings:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKRangeEncoding *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"rawBytesEncodings","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"structuredAppendInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo","text":"SBSDKStructuredAppendInfo","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo"},{"text":" *) ","kind":"text"},{"text":"structuredAppendInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"quad:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"quad","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"quadNormalized:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"quadNormalized","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extendedQuad:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"extendedQuad","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extendedQuadNormalized:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"extendedQuadNormalized","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"upcEanExtension:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"upcEanExtension","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extractedDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"text":" *) ","kind":"text"},{"text":"extractedDocument","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem~1init(text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:)\/title","value":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem~1init(text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:upcEanExtension:extractedDocument:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/title","value":"SBSDKRangeEncoding","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/fragments","value":[{"kind":"identifier","text":"SBSDKRangeEncoding"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKRangeEncoding"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/title","value":"SBSDKStructuredAppendInfo","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/fragments","value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"op":"replace"}]}]}