{"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"analyze"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SBSDKDocumentQualityAnalyzerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult"},{"text":"?","kind":"text"}],"title":"analyze(on:)","modules":[{"name":"ScanbotSDK"}],"externalID":"s:10ScanbotSDK28SBSDKDocumentQualityAnalyzerC7analyze2onAA0cdE6ResultCSgSo7UIImageC_tYaF","symbolKind":"method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzer\/analyze(on:)-7fln9"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer\/analyze(on:)-7fln9"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer"]]},"abstract":[{"text":"Asynchronously analyzes the document quality on the image and returns the result of type ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","type":"reference","isActive":true},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"analyze","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult","text":"SBSDKDocumentQualityAnalyzerResult"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"text":"The image to be analyzed.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the quality analysis."}]}],"kind":"content"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"kind":"symbol","title":"SBSDKDocumentQualityAnalyzerResult","abstract":[{"type":"text","text":"Result of document quality analysis. It can be used to determine, e.g., if a document is good enough to be used for"},{"text":" ","type":"text"},{"text":"OCR processing.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQuality":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQuality","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Result of document quality analysis.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","url":"\/documentation\/scanbotsdk\/sbsdkdocumentquality","title":"SBSDKDocumentQuality","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzer/analyze(on:)-7fln9":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzer\/analyze(on:)-7fln9","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"analyze","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult","text":"SBSDKDocumentQualityAnalyzerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"analyze(on:)","type":"topic","abstract":[{"text":"Asynchronously analyzes the document quality on the image and returns the result of type ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer\/analyze(on:)-7fln9"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzer":{"title":"SBSDKDocumentQualityAnalyzer","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzer","abstract":[{"text":"Analyzes the quality of a document on a still image.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzer"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzer"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzer"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/title","value":"SBSDKDocumentQualityAnalyzerResult","op":"replace"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/navigatorTitle","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}]},{"value":"SBSDKDocumentQuality","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentQuality"}]},{"value":[{"kind":"identifier","text":"SBSDKDocumentQuality"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/title","value":"SBSDKDocumentQualityAnalyzer"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/fragments"},{"value":[{"text":"SBSDKDocumentQualityAnalyzer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzer\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}