{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fieldType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedFieldType","text":"SBSDKTIFFImageWriterUserDefinedFieldType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterUserDefinedFieldType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/fieldtype"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/fieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The type of the field. Readonly.","type":"text"}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTIFFImageWriterUserDefinedFieldType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterUserDefinedFieldType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fieldType"}],"roleHeading":"Instance Property","title":"fieldType","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterUserDefinedField(py)fieldType"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField\/fieldType","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedField":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedField"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"type":"topic","title":"SBSDKTIFFImageWriterUserDefinedField","abstract":[{"text":"A class used to describe a user-defined TIFF field.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedField/fieldType":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/fieldtype","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fieldType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTIFFImageWriterUserDefinedFieldType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterUserDefinedFieldType"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField\/fieldType","abstract":[{"text":"The type of the field. Readonly.","type":"text"}],"navigatorTitle":[{"text":"fieldType","kind":"identifier"}],"kind":"symbol","title":"fieldType","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedFieldType":{"title":"SBSDKTIFFImageWriterUserDefinedFieldType","abstract":[{"text":"Custom TIFF field type.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedFieldType","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldType"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfieldtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fieldType","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fieldType"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedFieldType","text":"SBSDKTIFFImageWriterUserDefinedFieldType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterUserDefinedFieldType"},{"kind":"text","text":" "},{"text":"fieldType","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField\/title","op":"replace","value":"SBSDKTIFFImageWriterUserDefinedField"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField\/fragments","op":"replace"},{"op":"replace","value":"fieldType","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField~1fieldType\/title"},{"value":[{"text":"fieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField~1fieldType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/title","value":"SBSDKTIFFImageWriterUserDefinedFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldType"}]}]}]}