{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:stringvalue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:stringvalue:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"fieldName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldTag"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"stringValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fieldName","content":[{"type":"paragraph","inlineContent":[{"text":"The name of the field.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The tag of the field."}],"type":"paragraph"}],"name":"fieldTag"},{"content":[{"inlineContent":[{"text":"The string value of the field.","type":"text"}],"type":"paragraph"}],"name":"stringValue"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"init","role":"symbol","title":"init(fieldName:fieldTag:stringValue:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterUserDefinedField(im)initWithFieldName:fieldTag:stringValue:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithFieldName:fieldTag:stringValue:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"fieldTag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"stringValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField\/init(fieldName:fieldTag:stringValue:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Creates a new user-defined TIFF field with a string-type value.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedField/init(fieldName:fieldTag:stringValue:)":{"role":"symbol","title":"init(fieldName:fieldTag:stringValue:)","abstract":[{"type":"text","text":"Creates a new user-defined TIFF field with a string-type value."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:stringvalue:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFieldName:fieldTag:stringValue:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"fieldTag","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"stringValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField\/init(fieldName:fieldTag:stringValue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedField":{"role":"symbol","title":"SBSDKTIFFImageWriterUserDefinedField","abstract":[{"type":"text","text":"A class used to describe a user-defined TIFF field."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield","kind":"symbol","navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithFieldName:fieldTag:stringValue:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFieldName:fieldTag:stringValue:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFieldName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"fieldName","kind":"internalParam"},{"kind":"text","text":" "},{"text":"fieldTag:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"fieldTag","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringValue:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"stringValue"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField~1init(fieldName:fieldTag:stringValue:)\/title","value":"initWithFieldName:fieldTag:stringValue:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField~1init(fieldName:fieldTag:stringValue:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFieldName:fieldTag:stringValue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField\/title","value":"SBSDKTIFFImageWriterUserDefinedField"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField\/fragments"}]}]}