{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar\/init(retakeButton:acceptWhenOkButton:acceptWhenNotOkButton:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar(im)initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","roleHeading":"Initializer","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","kind":"identifier"}],"title":"init(retakeButton:acceptWhenOkButton:acceptWhenNotOkButton:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"retakeButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"acceptWhenOkButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"acceptWhenNotOkButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":")","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"retakeButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(text: \"?acknowledgementRetakeButtonTitle\",\n                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                      isArgb: false)),\n                                       accessibilityDescription: \"?accessibilityDescriptionAcknowledgementRetakeButton\",\n                                       background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                      isArgb: false),\n                                                                           fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                    isArgb: false),\n                                                                           strokeWidth: 0.0),\n                                       icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                    isArgb: false))), ","kind":"text"},{"text":"acceptWhenOkButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(text: \"?acknowledgementAcceptButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionAcknowledgementAcceptButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), "},{"kind":"externalParam","text":"acceptWhenNotOkButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(text: \"?acknowledgementAcceptButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionAcknowledgementAcceptButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))))","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar\/init(retakebutton:acceptwhenokbutton:acceptwhennotokbutton:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar\/init(retakebutton:acceptwhenokbutton:acceptwhennotokbutton:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementBottomBar":{"kind":"symbol","title":"SBSDKUI2AcknowledgementBottomBar","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar","navigatorTitle":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the bottom bar for the acknowledgement screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration","navigatorTitle":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Button configuration."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"title":"SBSDKUI2BarButtonConfiguration","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementBottomBar/init(retakeButton:acceptWhenOkButton:acceptWhenNotOkButton:)":{"navigatorTitle":[{"text":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar\/init(retakebutton:acceptwhenokbutton:acceptwhennotokbutton:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar\/init(retakeButton:acceptWhenOkButton:acceptWhenNotOkButton:)","title":"init(retakeButton:acceptWhenOkButton:acceptWhenNotOkButton:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"retakeButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"acceptWhenOkButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"text":"acceptWhenNotOkButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithRetakeButton:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"retakeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptWhenOkButton:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"acceptWhenOkButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptWhenNotOkButton:"},{"kind":"text","text":"("},{"text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"acceptWhenNotOkButton"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"SBSDKUI2AcknowledgementBottomBar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/fragments","value":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/title","value":"SBSDKUI2BarButtonConfiguration"},{"value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/fragments","op":"replace"},{"op":"replace","value":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar~1init(retakeButton:acceptWhenOkButton:acceptWhenNotOkButton:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar~1init(retakeButton:acceptWhenOkButton:acceptWhenNotOkButton:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:"}]}]}]}