{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withJPEGAndCompressionQuality"},{"kind":"text","text":" "},{"kind":"internalParam","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"quality","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Sets the JPEG compression quality of the stored images if the image format is JPEG."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of storage."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/init(withjpegandcompressionquality:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/init(withjpegandcompressionquality:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(withJPEGAndCompressionQuality:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a storage with JPEG image format at the default storage location."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withJPEGAndCompressionQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"title":"init(withJPEGAndCompressionQuality:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPageFileStorage(im)initWithJPEGAndCompressionQuality:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithJPEGAndCompressionQuality:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage":{"role":"symbol","title":"SBSDKDocumentPageFileStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"abstract":[{"type":"text","text":"A class to store and restore images of different types in a memory-efficient way."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileStorage/init(withJPEGAndCompressionQuality:)":{"role":"symbol","title":"init(withJPEGAndCompressionQuality:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withJPEGAndCompressionQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a storage with JPEG image format at the default storage location."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileStorage\/init(withJPEGAndCompressionQuality:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithJPEGAndCompressionQuality:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefilestorage\/init(withjpegandcompressionquality:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithJPEGAndCompressionQuality:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithJPEGAndCompressionQuality:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithJPEGAndCompressionQuality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"quality"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/title","value":"SBSDKDocumentPageFileStorage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1init(withJPEGAndCompressionQuality:)\/title","value":"initWithJPEGAndCompressionQuality:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileStorage~1init(withJPEGAndCompressionQuality:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithJPEGAndCompressionQuality:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}