{"kind":"symbol","abstract":[{"text":"The type of rotation to be applied to the receiver.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage\/rotation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage\/rotation"]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"rotation","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"rotation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage(py)rotation","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rotation","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage\/rotation","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPage/rotation":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage\/rotation","title":"rotation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage\/rotation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rotation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rotation"}],"abstract":[{"text":"The type of rotation to be applied to the receiver.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRotation":{"title":"SBSDKImageRotation","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerotation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageRotation","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKImageRotation","kind":"identifier"}],"abstract":[{"type":"text","text":"Image rotation."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPage","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage","role":"symbol","title":"SBSDKScannedPage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPage"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","abstract":[{"text":"A scanned page (","type":"text"},{"type":"codeVoice","code":"SBSDKScannedPage"},{"text":") is a representation of a scanned documents page in digital form.","type":"text"},{"type":"text","text":" "},{"text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rotation","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"rotation","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRotation"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rotation"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"rotation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage~1rotation\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage~1rotation\/fragments","value":[{"kind":"identifier","text":"rotation"}]},{"op":"replace","value":"SBSDKImageRotation","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/title"},{"value":[{"text":"SBSDKImageRotation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRotation\/navigatorTitle","value":[{"text":"SBSDKImageRotation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/title","value":"SBSDKScannedPage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/fragments","value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/navigatorTitle"}]}]}