{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2scanassistanceoverlay\/fromjsonwithjson:"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay","kind":"typeIdentifier","text":"SBSDKUI2ScanAssistanceOverlay"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay\/fromJsonWithJson:"},"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay(cm)fromJsonWithJson:","roleHeading":"Type Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanAssistanceOverlay/fromJsonWithJson:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2scanassistanceoverlay\/fromjsonwithjson:","type":"topic","kind":"symbol","title":"fromJsonWithJson:","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanAssistanceOverlay":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2ScanAssistanceOverlay","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2scanassistanceoverlay","title":"SBSDKUI2ScanAssistanceOverlay","abstract":[{"text":"Configuration of the scan assistance overlay.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2ScanAssistanceOverlay","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/navigatorTitle","value":[{"text":"SBSDKUI2ScanAssistanceOverlay","kind":"identifier"}],"op":"replace"}]}]}