{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/initWithSensitivityThreshold:","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSensitivityThreshold:"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"sensitivityThreshold"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorAutoFocusConfiguration(im)initWithSensitivityThreshold:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"initWithSensitivityThreshold:","kind":"identifier"}],"title":"initWithSensitivityThreshold:","fragments":[{"kind":"text","text":"- "},{"text":"initWithSensitivityThreshold:","kind":"identifier"}],"symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/initwithsensitivitythreshold:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration":{"abstract":[{"text":"Auto-focus configuration.","type":"text"},{"type":"text","text":" "},{"text":"The recognizer will ignore frames that are not focused. This option is enabled by default.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This configuration has no effect in SINGLE_SHOT mode."}],"type":"topic","title":"SBSDKDocumentDataExtractorAutoFocusConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorAutoFocusConfiguration/initWithSensitivityThreshold:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorautofocusconfiguration\/initwithsensitivitythreshold:","abstract":[],"navigatorTitle":[{"text":"initWithSensitivityThreshold:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorAutoFocusConfiguration\/initWithSensitivityThreshold:","title":"initWithSensitivityThreshold:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSensitivityThreshold:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/title","value":"SBSDKDocumentDataExtractorAutoFocusConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/fragments","value":[{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKDocumentDataExtractorAutoFocusConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorAutoFocusConfiguration\/navigatorTitle"}]}]}