{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRoi:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"roi","kind":"internalParam"},{"kind":"text","text":" "},{"text":"loadMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferLoadMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBufferLoadMode","text":"SBSDKBufferLoadMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"loadMode"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBufferImageLoadOptions(im)initWithRoi:loadMode:","navigatorTitle":[{"kind":"identifier","text":"initWithRoi:loadMode:"}],"title":"initWithRoi:loadMode:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"initWithRoi:loadMode:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions\/initwithroi:loadmode:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions\/initWithRoi:loadMode:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferImageLoadOptions/initWithRoi:loadMode:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions\/initwithroi:loadmode:","abstract":[],"title":"initWithRoi:loadMode:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions\/initWithRoi:loadMode:","fragments":[{"kind":"text","text":"- "},{"text":"initWithRoi:loadMode:","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRoi:loadMode:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferImageLoadOptions":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"role":"symbol","title":"SBSDKBufferImageLoadOptions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions","abstract":[{"type":"text","text":"Options for loading image from buffer."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions","navigatorTitle":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferLoadMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"role":"symbol","title":"SBSDKBufferLoadMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferLoadMode","abstract":[{"type":"text","text":"Image Ref Buffer Load Mode."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferloadmode","navigatorTitle":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/title","value":"SBSDKBufferImageLoadOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/navigatorTitle","value":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/title","value":"SBSDKBufferLoadMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/fragments","op":"replace","value":[{"text":"SBSDKBufferLoadMode","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBufferLoadMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferLoadMode\/navigatorTitle"}]}]}