{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerconfigurationoptions\/defaultoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerconfigurationoptions\/defaultoptions"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(defaultConfigurationOptions) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultOptions"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions"]]},"sections":[],"metadata":{"title":"defaultOptions","symbolKind":"property","roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions(cpy)defaultConfigurationOptions","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"defaultConfigurationOptions"}],"role":"symbol"},"abstract":[{"type":"text","text":"The default configuration."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions\/defaultOptions","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerConfigurationOptions/defaultOptions":{"abstract":[{"type":"text","text":"The default configuration."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultOptions"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions"}],"role":"symbol","navigatorTitle":[{"text":"defaultConfigurationOptions","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerconfigurationoptions\/defaultoptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions\/defaultOptions","title":"defaultOptions","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerConfigurationOptions":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerconfigurationoptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A class intended to store the configuration options for a medical certificate recognizer."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"identifier"}],"kind":"symbol","title":"SBSDKMedicalCertificateRecognizerConfigurationOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"defaultConfigurationOptions","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultConfigurationOptions"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerConfigurationOptions","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"defaultConfigurationOptions"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"defaultConfigurationOptions","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions~1defaultOptions\/title","op":"replace"},{"op":"replace","value":[{"text":"defaultConfigurationOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions~1defaultOptions\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions\/title","op":"replace","value":"SBSDKMedicalCertificateRecognizerConfigurationOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerConfigurationOptions\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerConfigurationOptions","kind":"identifier"}]}]}]}