{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling"]]},"abstract":[{"text":"Combines the validations of VALIDATE_FULL and the human-readable output format of DECODE_STRUCTURE.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeFull"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decodefull"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decodefull"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling@SBSDKGS1HandlingDecodeFull","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKGS1Handling.decodeFull","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeFull","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeFull"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeFull"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/decodeFull":{"role":"symbol","kind":"symbol","title":"SBSDKGS1Handling.decodeFull","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeFull","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeFull"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"decodeFull","kind":"identifier"}],"abstract":[{"text":"Combines the validations of VALIDATE_FULL and the human-readable output format of DECODE_STRUCTURE.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decodefull"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","abstract":[{"type":"text","text":"GS1 message handling options."},{"text":" ","type":"text"},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"barcode types."},{"type":"text","text":" "},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1Handling"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","kind":"symbol","title":"SBSDKGS1Handling"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKGS1HandlingDecodeFull","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeFull"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKGS1HandlingDecodeFull","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decodeFull\/title","value":"SBSDKGS1HandlingDecodeFull","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decodeFull\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeFull"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}