{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle\/copyWithZone:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle"]]},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle(im)copyWithZone:","symbolKind":"method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","title":"copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackedviewtextstyle\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayController":{"abstract":[{"text":"A class that represents an overlay used for visualizing scanned barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"text":"The overlay can be used to highlight and select barcodes based on user input.","type":"text"}],"title":"SBSDKBarcodeTrackingOverlayController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontroller","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackedViewTextStyle/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle\/copyWithZone:","type":"topic","title":"copyWithZone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackedviewtextstyle\/copywithzone:","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackedViewTextStyle":{"title":"SBSDKBarcodeTrackedViewTextStyle","type":"topic","abstract":[{"text":"A class that represents the style and kind of the text rendered below a barcode in ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","type":"reference","isActive":true},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle","navigatorTitle":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackedviewtextstyle","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/title","value":"SBSDKBarcodeTrackingOverlayController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/title","value":"SBSDKBarcodeTrackedViewTextStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/fragments","value":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}