{"abstract":[{"type":"text","text":"Informs the delegate that a vehicle identification number has been scanned and validated, and passes the result."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didScanVIN:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didscanvin:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didscanvin:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate"]]},"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"required":true,"title":"vinScannerViewController(_:didScanVIN:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKVINScannerViewControllerDelegate(im)vinScannerViewController:didScanValidResult:","roleHeading":"Instance Method","navigatorTitle":[{"text":"vinScannerViewController:didScanValidResult:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinScannerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","text":"SBSDKVINScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanVIN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerResult","text":"SBSDKVINScannerResult"},{"kind":"text","text":")"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(vinScannerViewController:didScanValidResult:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinScannerViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","kind":"typeIdentifier","text":"SBSDKVINScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanVIN"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult","kind":"typeIdentifier","text":"SBSDKVINScannerResult"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"reference"},{"text":" that has scanned and validated the vehicle identification number.","type":"text"}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the scan."}]}],"name":"result"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate/vinScannerViewController(_:didScanVIN:)":{"required":true,"role":"symbol","abstract":[{"type":"text","text":"Informs the delegate that a vehicle identification number has been scanned and validated, and passes the result."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinScannerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","text":"SBSDKVINScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanVIN"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerResult","text":"SBSDKVINScannerResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"vinScannerViewController:didScanValidResult:"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate\/vinscannerviewcontroller(_:didscanvin:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate\/vinScannerViewController(_:didScanVIN:)","title":"vinScannerViewController(_:didScanVIN:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","title":"SBSDKVINScannerViewController","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the vehicle identification number scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerViewControllerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewControllerDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerviewcontrollerdelegate","title":"SBSDKVINScannerViewControllerDelegate","abstract":[{"text":"The delegation protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerResult":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerresult","type":"topic","navigatorTitle":[{"text":"SBSDKVINScannerResult","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Result of the VIN scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult","title":"SBSDKVINScannerResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"vinScannerViewController:didScanValidResult:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"vinScannerViewController:didScanValidResult:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"vinScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKVINScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didScanValidResult:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKVINScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerViewController","type":"reference","isActive":true},{"type":"text","text":" that has scanned and validated the vehicle identification number."}]}]},{"name":"result","content":[{"inlineContent":[{"type":"text","text":"The result of the scan."}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewController(_:didScanVIN:)\/title","value":"vinScannerViewController:didScanValidResult:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate~1vinScannerViewController(_:didScanVIN:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"vinScannerViewController:didScanValidResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/title","value":"SBSDKVINScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/fragments","value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewController\/navigatorTitle","value":[{"text":"SBSDKVINScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/title","value":"SBSDKVINScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKVINScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/title","value":"SBSDKVINScannerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKVINScannerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerResult\/navigatorTitle","value":[{"text":"SBSDKVINScannerResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}