{"metadata":{"roleHeading":"Initializer","title":"init(orientation:writingDirection:textlineOrder:deskewAngle:)","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult(im)initWithOrientation:writingDirection:textlineOrder:deskewAngle:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKTextOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"writingDirection"},{"kind":"text","text":": "},{"text":"SBSDKWritingDirection","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKWritingDirection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textlineOrder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKTextlineOrder","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deskewAngle"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/init(orientation:writingDirection:textlineOrder:deskewAngle:)"},"abstract":[{"type":"text","text":"Designated initializer."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/init(orientation:writingdirection:textlineorder:deskewangle:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/init(orientation:writingdirection:textlineorder:deskewangle:)"]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","text":"SBSDKTextOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"writingDirection"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection","text":"SBSDKWritingDirection","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKWritingDirection","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textlineOrder"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder","text":"SBSDKTextlineOrder","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"deskewAngle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"orientation","content":[{"type":"paragraph","inlineContent":[{"text":"The general orientation of the text in the image.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The writing direction of the text lines in the image.","type":"text"}]}],"name":"writingDirection"},{"name":"textlineOrder","content":[{"type":"paragraph","inlineContent":[{"text":"The order of text lines.","type":"text"}]}]},{"name":"deskewAngle","content":[{"inlineContent":[{"type":"text","text":"The angle in radians the image needs to be rotated to achieve perfectly aligned text lines."}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextlineOrder":{"url":"\/documentation\/scanbotsdk\/sbsdktextlineorder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKTextlineOrder","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder","navigatorTitle":[{"text":"SBSDKTextlineOrder","kind":"identifier"}],"title":"SBSDKTextlineOrder","abstract":[{"text":"An enum to describes the order of columns in top-to-bottom writing direction resp. of rows in left-right and right-left direction.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult":{"title":"SBSDKTextLayoutRecognizerResult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"abstract":[{"type":"text","text":"Represents a result of the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextOrientation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","title":"SBSDKTextOrientation","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTextOrientation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextorientation","role":"symbol","abstract":[{"type":"text","text":"An enum to describes the detected orientation of text in an image."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextOrientation"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWritingDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKWritingDirection","kind":"identifier"}],"abstract":[{"type":"text","text":"An enum to describe the reading direction of the text independently from its orientation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection","kind":"symbol","title":"SBSDKWritingDirection","url":"\/documentation\/scanbotsdk\/sbsdkwritingdirection","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKWritingDirection"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult/init(orientation:writingDirection:textlineOrder:deskewAngle:)":{"url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/init(orientation:writingdirection:textlineorder:deskewangle:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/init(orientation:writingDirection:textlineOrder:deskewAngle:)","type":"topic","role":"symbol","kind":"symbol","title":"init(orientation:writingDirection:textlineOrder:deskewAngle:)","abstract":[{"text":"Designated initializer.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","text":"SBSDKTextOrientation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"writingDirection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKWritingDirection","text":"SBSDKWritingDirection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textlineOrder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","text":"SBSDKTextlineOrder","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"deskewAngle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"title":"SBSDKTextLayoutRecognizer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizer"}],"abstract":[{"type":"text","text":"Analyzes an image and returns basic text layout features."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithOrientation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","text":"SBSDKTextOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextOrientation","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"orientation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"writingDirection:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection","text":"SBSDKWritingDirection","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKWritingDirection","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"writingDirection","kind":"internalParam"},{"kind":"text","text":" "},{"text":"textlineOrder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder","text":"SBSDKTextlineOrder","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textlineOrder","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"deskewAngle:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"deskewAngle"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The general orientation of the text in the image."}]}],"name":"orientation"},{"content":[{"inlineContent":[{"text":"The writing direction of the text lines in the image.","type":"text"}],"type":"paragraph"}],"name":"writingDirection"},{"name":"textlineOrder","content":[{"type":"paragraph","inlineContent":[{"text":"The order of text lines.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The angle in radians the image needs to be rotated to achieve perfectly aligned text lines."}]}],"name":"deskewAngle"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKTextlineOrder","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/fragments","value":[{"text":"SBSDKTextlineOrder","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTextlineOrder"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/title","value":"SBSDKTextLayoutRecognizerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/navigatorTitle"},{"value":"SBSDKTextOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/title"},{"value":[{"kind":"identifier","text":"SBSDKTextOrientation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/navigatorTitle","value":[{"text":"SBSDKTextOrientation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/title","value":"SBSDKWritingDirection"},{"op":"replace","value":[{"text":"SBSDKWritingDirection","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKWritingDirection"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1init(orientation:writingDirection:textlineOrder:deskewAngle:)\/title","value":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithOrientation:writingDirection:textlineOrder:deskewAngle:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1init(orientation:writingDirection:textlineOrder:deskewAngle:)\/fragments","op":"replace"},{"value":"SBSDKTextLayoutRecognizer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments","op":"replace","value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}]}]}]}