{"abstract":[{"type":"text","text":"The order of text lines."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"textlineOrder","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTextlineOrder","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"textlineOrder","roleHeading":"Instance Property","navigatorTitle":[{"text":"textlineOrder","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textlineOrder","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","text":"SBSDKTextlineOrder"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextLayoutRecognizerResult(py)textlineOrder","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/textlineOrder"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/textlineorder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/textlineorder"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizer":{"abstract":[{"type":"text","text":"Analyzes an image and returns basic text layout features."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizer","title":"SBSDKTextLayoutRecognizer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextLayoutRecognizer"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizer"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult":{"abstract":[{"type":"text","text":"Represents a result of the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizer"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult","kind":"symbol","title":"SBSDKTextLayoutRecognizerResult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizerResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextlineOrder":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextlineOrder"}],"abstract":[{"type":"text","text":"An enum to describes the order of columns in top-to-bottom writing direction resp. of rows in left-right and right-left direction."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextlineOrder"}],"title":"SBSDKTextlineOrder","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder","url":"\/documentation\/scanbotsdk\/sbsdktextlineorder"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextLayoutRecognizerResult/textlineOrder":{"abstract":[{"text":"The order of text lines.","type":"text"}],"navigatorTitle":[{"text":"textlineOrder","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextLayoutRecognizerResult\/textlineOrder","title":"textlineOrder","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textlineOrder"},{"text":": ","kind":"text"},{"text":"SBSDKTextlineOrder","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextlayoutrecognizerresult\/textlineorder"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"textlineOrder"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"textlineOrder","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder","text":"SBSDKTextlineOrder","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder"},{"kind":"text","text":" "},{"text":"textlineOrder","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/title","op":"replace","value":"SBSDKTextLayoutRecognizer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKTextLayoutRecognizer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizer\/navigatorTitle","value":[{"text":"SBSDKTextLayoutRecognizer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/title","value":"SBSDKTextLayoutRecognizerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/fragments","op":"replace","value":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult\/navigatorTitle","value":[{"text":"SBSDKTextLayoutRecognizerResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/title","value":"SBSDKTextlineOrder"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTextlineOrder"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTextlineOrder","kind":"identifier"}]},{"value":"textlineOrder","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1textlineOrder\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextLayoutRecognizerResult~1textlineOrder\/fragments","op":"replace","value":[{"text":"textlineOrder","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}