{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clockwise180"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"SBSDKImageRotation.clockwise180","navigatorTitle":[{"text":"SBSDKImageRotationClockwise180","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageRotation@SBSDKImageRotationClockwise180","roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clockwise180","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerotation\/clockwise180"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerotation\/clockwise180"]}],"kind":"symbol","abstract":[{"text":"180 degrees rotation.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation\/clockwise180"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation/clockwise180":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotationClockwise180"}],"kind":"symbol","abstract":[{"type":"text","text":"180 degrees rotation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation\/clockwise180","title":"SBSDKImageRotation.clockwise180","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clockwise180","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagerotation\/clockwise180","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","role":"symbol","type":"topic","kind":"symbol","title":"SBSDKImageRotation","abstract":[{"text":"Image rotation.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageRotation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageRotation","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagerotation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"SBSDKImageRotationClockwise180","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKImageRotationClockwise180","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKImageRotationClockwise180","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation~1clockwise180\/title","value":"SBSDKImageRotationClockwise180"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation~1clockwise180\/fragments","op":"replace","value":[{"text":"SBSDKImageRotationClockwise180","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/title","op":"replace","value":"SBSDKImageRotation"},{"value":[{"text":"SBSDKImageRotation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/navigatorTitle"}]}]}