{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration\/confirmationDialogStyle","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/confirmationdialogstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/confirmationdialogstyle"]}],"abstract":[{"type":"text","text":"The style of the confirmation dialog."}],"metadata":{"symbolKind":"property","platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmationDialogStyle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIDialogStyle"}],"navigatorTitle":[{"kind":"identifier","text":"confirmationDialogStyle"}],"role":"symbol","title":"confirmationDialogStyle","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration(py)confirmationDialogStyle","roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration"]]},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}],"type":"paragraph"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationDialogStyle","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIDialogStyle","kind":"typeIdentifier","text":"SBSDKUIDialogStyle"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIDialogStyle":{"abstract":[{"type":"text","text":"The general style for a dialog in ScanbotSDK. Used to customize certain result dialogs in SBSDKUI components."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIDialogStyle","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUIDialogStyle","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuidialogstyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIDialogStyle","kind":"identifier"}],"title":"SBSDKUIDialogStyle"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerUIConfiguration/confirmationDialogStyle":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmationDialogStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIDialogStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"confirmationDialogStyle","kind":"identifier"}],"title":"confirmationDialogStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration\/confirmationDialogStyle","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/confirmationdialogstyle","role":"symbol","abstract":[{"text":"The style of the confirmation dialog.","type":"text"}],"kind":"symbol","type":"topic","deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerUIConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"abstract":[{"text":"The configuration for user interface of the RTU-UI barcode scanner.","type":"text"}],"title":"SBSDKUIBarcodeScannerUIConfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"confirmationDialogStyle","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"confirmationDialogStyle"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIDialogStyle","text":"SBSDKUIDialogStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIDialogStyle","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"confirmationDialogStyle"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIDialogStyle\/title","value":"SBSDKUIDialogStyle","op":"replace"},{"value":[{"text":"SBSDKUIDialogStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIDialogStyle\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIDialogStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIDialogStyle"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration~1confirmationDialogStyle\/title","op":"replace","value":"confirmationDialogStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration~1confirmationDialogStyle\/fragments","value":[{"text":"confirmationDialogStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/title","value":"SBSDKUIBarcodeScannerUIConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/navigatorTitle"}]}]}