{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderLineColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"]}]}],"metadata":{"platforms":[],"roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"finderLineColor","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderLineColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"navigatorTitle":[{"text":"finderLineColor","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration(py)finderLineColor"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration\/finderLineColor"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/finderlinecolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/finderlinecolor"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"abstract":[{"type":"text","text":"Foreground color of the detection overlay."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerUIConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration","abstract":[{"type":"text","text":"The configuration for user interface of the RTU-UI barcode scanner."}],"title":"SBSDKUIBarcodeScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"type":"topic","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerUIConfiguration/finderLineColor":{"role":"symbol","abstract":[{"type":"text","text":"Foreground color of the detection overlay."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/finderlinecolor","title":"finderLineColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderLineColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"finderLineColor","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration\/finderLineColor","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"finderLineColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"finderLineColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"finderLineColor","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/title","value":"SBSDKUIBarcodeScannerUIConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration~1finderLineColor\/title","value":"finderLineColor","op":"replace"},{"value":[{"kind":"identifier","text":"finderLineColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration~1finderLineColor\/fragments"}]}]}