{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration(py)finderAspectRatio","navigatorTitle":[{"kind":"identifier","text":"finderAspectRatio"}],"title":"finderAspectRatio","platforms":[],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderAspectRatio"},{"text":": ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderAspectRatio","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAspectRatio","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/finderaspectratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/finderaspectratio"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Aspect ratio of finder frame (width \\ height), which is used to build actual finder frame."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration\/finderAspectRatio"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerUIConfiguration/finderAspectRatio":{"deprecated":true,"type":"topic","navigatorTitle":[{"text":"finderAspectRatio","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/finderaspectratio","abstract":[{"type":"text","text":"Aspect ratio of finder frame (width \\ height), which is used to build actual finder frame."}],"role":"symbol","kind":"symbol","title":"finderAspectRatio","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration\/finderAspectRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderAspectRatio"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAspectRatio":{"title":"SBSDKAspectRatio","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaspectratio","role":"symbol","abstract":[{"type":"text","text":"A class that describes an aspect ratio for a document page."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAspectRatio"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAspectRatio","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerUIConfiguration":{"type":"topic","kind":"symbol","title":"SBSDKUIBarcodeScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"deprecated":true,"abstract":[{"text":"The configuration for user interface of the RTU-UI barcode scanner.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"finderAspectRatio","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"finderAspectRatio"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"finderAspectRatio"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration~1finderAspectRatio\/title","value":"finderAspectRatio","op":"replace"},{"value":[{"kind":"identifier","text":"finderAspectRatio"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration~1finderAspectRatio\/fragments","op":"replace"},{"op":"replace","value":"SBSDKAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAspectRatio\/title"},{"value":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAspectRatio\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAspectRatio\/navigatorTitle","value":[{"text":"SBSDKAspectRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/title","value":"SBSDKUIBarcodeScannerUIConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}]}]}]}