{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"orientationLockMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOrientationLock"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration(py)orientationLockMode","symbolKind":"property","title":"orientationLockMode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","role":"symbol","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"orientationLockMode"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration\/orientationLockMode","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}],"type":"paragraph"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock","text":"SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOrientationLock","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/orientationlockmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/orientationlockmode"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerUIConfiguration":{"title":"SBSDKUIBarcodeScannerUIConfiguration","abstract":[{"text":"The configuration for user interface of the RTU-UI barcode scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeScannerUIConfiguration/orientationLockMode":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOrientationLock","kind":"typeIdentifier","text":"SBSDKOrientationLock"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeScannerUIConfiguration\/orientationLockMode","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodescanneruiconfiguration\/orientationlockmode","abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}],"role":"symbol","navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"deprecated":true,"title":"orientationLockMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOrientationLock":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKOrientationLock","kind":"identifier"}],"abstract":[{"text":"This enum describes the available orientation lock modes for the user interface.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock","title":"SBSDKOrientationLock","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkorientationlock"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"orientationLockMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"orientationLockMode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOrientationLock","text":"SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOrientationLock","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUIBarcodeScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration~1orientationLockMode\/title","value":"orientationLockMode","op":"replace"},{"value":[{"text":"orientationLockMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeScannerUIConfiguration~1orientationLockMode\/fragments"},{"op":"replace","value":"SBSDKOrientationLock","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock\/fragments","value":[{"kind":"identifier","text":"SBSDKOrientationLock"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOrientationLock\/navigatorTitle","value":[{"text":"SBSDKOrientationLock","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}