{"abstract":[{"type":"text","text":"A string of accepted characters during text recognition. If empty or nil, all characters are accepted."}],"sections":[],"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerConfiguration(py)textRecognitionAllowedCharacters","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"textRecognitionAllowedCharacters","navigatorTitle":[{"kind":"identifier","text":"textRecognitionAllowedCharacters"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textRecognitionAllowedCharacters","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration\/textRecognitionAllowedCharacters","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/textrecognitionallowedcharacters"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/textrecognitionallowedcharacters"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textRecognitionAllowedCharacters","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerConfiguration/textRecognitionAllowedCharacters":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration\/textRecognitionAllowedCharacters","abstract":[{"text":"A string of accepted characters during text recognition. If empty or nil, all characters are accepted.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration\/textrecognitionallowedcharacters","title":"textRecognitionAllowedCharacters","navigatorTitle":[{"kind":"identifier","text":"textRecognitionAllowedCharacters"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textRecognitionAllowedCharacters","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizer":{"kind":"symbol","title":"SBSDKGenericTextLineRecognizer","role":"symbol","type":"topic","abstract":[{"text":"A class to recognize one line of text in a small area and run validation on the result.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerConfiguration"}],"title":"SBSDKGenericTextLineRecognizerConfiguration","abstract":[{"text":"A descriptor class to configure an instance of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizer","type":"reference"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"textRecognitionAllowedCharacters","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textRecognitionAllowedCharacters"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"textRecognitionAllowedCharacters"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration~1textRecognitionAllowedCharacters\/title","value":"textRecognitionAllowedCharacters","op":"replace"},{"value":[{"text":"textRecognitionAllowedCharacters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration~1textRecognitionAllowedCharacters\/fragments"},{"value":"SBSDKGenericTextLineRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/fragments","value":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizer\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericTextLineRecognizer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/title","op":"replace","value":"SBSDKGenericTextLineRecognizerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKGenericTextLineRecognizerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}