{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldConsistencyVerificationReport","kind":"typeIdentifier","text":"SBSDKFieldConsistencyVerificationReport"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldConsistencyVerificationReport(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport\/fromJsonWithJson:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport":{"url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"type":"topic","abstract":[{"text":"Report of the field consistency verification.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"title":"SBSDKFieldConsistencyVerificationReport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldConsistencyVerificationReport/fromJsonWithJson:":{"title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldConsistencyVerificationReport\/fromJsonWithJson:","type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkfieldconsistencyverificationreport\/fromjsonwithjson:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/title","value":"SBSDKFieldConsistencyVerificationReport","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKFieldConsistencyVerificationReport"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldConsistencyVerificationReport\/navigatorTitle","value":[{"text":"SBSDKFieldConsistencyVerificationReport","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}