{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"}],"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier","text":"SBSDKProgress"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPDFPagesExtractor(im)imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL.","type":"text"},{"text":" ","type":"text"},{"text":"The array of URLs is passed within the completion handler.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ([","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}]},{"name":"scaling","content":[{"inlineContent":[{"text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher.","type":"text"}],"type":"paragraph"}]},{"name":"compression","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}]}]},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"text":"The encrypter used to encrypt output image files. If ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", no encryption is used.","type":"text"}]}]},{"name":"outputDirectory","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output folder where images will be stored. If the folder does not exist, it will be created."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion handler that delivers the created array of image file URLs."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A progress object that can be used for cancellation and progress observing. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", an error occurred."}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFPagesExtractor/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)":{"navigatorTitle":[{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor\/imageurls(from:scaling:compression:encrypter:outputdirectory:completion:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL."},{"text":" ","type":"text"},{"text":"The array of URLs is passed within the completion handler.","type":"text"}],"role":"symbol","title":"imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFPagesExtractor":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFPagesExtractor","kind":"symbol","type":"topic","abstract":[{"text":"Class used to extract pages from a PDF file and returns them in various ways.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfpagesextractor","title":"SBSDKPDFPagesExtractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting":{"navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","title":"SBSDKStorageCrypting","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress":{"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","title":"SBSDKProgress","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageURLsFromPDF:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaling:"},{"kind":"text","text":"("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"scaling","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"compression:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"compression","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encrypter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SBSDKStorageCrypting>","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":") "},{"kind":"internalParam","text":"encrypter"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputDirectory:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outputDirectory"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"NSArray<NSURL *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The URL of the PDF file.","type":"text"}],"type":"paragraph"}],"name":"pdfURL"},{"content":[{"inlineContent":[{"text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher.","type":"text"}],"type":"paragraph"}],"name":"scaling"},{"content":[{"inlineContent":[{"text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used.","type":"text"}],"type":"paragraph"}],"name":"compression"},{"content":[{"inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}],"type":"paragraph"}],"name":"encrypter"},{"content":[{"inlineContent":[{"type":"text","text":"The output folder where images will be stored. If the folder does not exist, it will be created."}],"type":"paragraph"}],"name":"outputDirectory"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion handler that delivers the created array of image file URLs.","type":"text"}]}],"name":"completion"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A progress object that can be used for cancellation and progress observing. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", an error occurred."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)\/title","op":"replace","value":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:scaling:compression:encrypter:outputDirectory:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/title","op":"replace","value":"SBSDKPDFPagesExtractor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/fragments","op":"replace","value":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFPagesExtractor\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/title","op":"replace","value":"SBSDKStorageCrypting"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/navigatorTitle","op":"replace","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/title","op":"replace","value":"SBSDKProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgress"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/navigatorTitle","op":"replace","value":[{"text":"SBSDKProgress","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}