{"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration(im)initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","kind":"identifier"}],"title":"initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","symbolKind":"method","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithAllowedCountries:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKEuropeanHealthInsuranceCardIssuingCountry *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"allowedCountries","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"minBirthYear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"minBirthYear","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxBirthYear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"maxBirthYear","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minExpirationYear:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minExpirationYear"},{"kind":"text","text":" "},{"text":"maxExpirationYear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maxExpirationYear","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxCountryDetectionAttempts:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"maxCountryDetectionAttempts","kind":"internalParam"},{"kind":"text","text":" "},{"text":"minEqualFrameCount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minEqualFrameCount"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxAccumulatedFrameCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"maxAccumulatedFrameCount","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration\/initwithallowedcountries:minbirthyear:maxbirthyear:minexpirationyear:maxexpirationyear:maxcountrydetectionattempts:minequalframecount:maxaccumulatedframecount:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration/initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:":{"role":"symbol","title":"initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","fragments":[{"kind":"text","text":"- "},{"text":"initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"initWithAllowedCountries:minBirthYear:maxBirthYear:minExpirationYear:maxExpirationYear:maxCountryDetectionAttempts:minEqualFrameCount:maxAccumulatedFrameCount:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration\/initwithallowedcountries:minbirthyear:maxbirthyear:minexpirationyear:maxexpirationyear:maxcountrydetectionattempts:minequalframecount:maxaccumulatedframecount:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration for the European health insurance card (EHIC) recognizer."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/navigatorTitle","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"identifier"}]}]}]}