{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithOverallInvalidSemantics:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"overallInvalidSemantics"},{"text":" ","kind":"text"},{"text":"expiryDateSemantics:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier","text":"SBSDKCompositeFieldValueSemantics","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"expiryDateSemantics"},{"kind":"text","text":" "},{"text":"issueDateSemantics:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKCompositeFieldValueSemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics"},{"text":" *) ","kind":"text"},{"text":"issueDateSemantics","kind":"internalParam"},{"kind":"text","text":" "},{"text":"birthDateSemantics:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKCompositeFieldValueSemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics"},{"text":" *) ","kind":"text"},{"text":"birthDateSemantics","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"issueDateBeforeExpiryDate:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics","text":"SBSDKValueSemantics"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"issueDateBeforeExpiryDate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"birthDateBeforeIssueDate:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics","text":"SBSDKValueSemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"birthDateBeforeIssueDate","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"birthDateBeforeExpiryDate:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics","text":"SBSDKValueSemantics"},{"text":") ","kind":"text"},{"text":"birthDateBeforeExpiryDate","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/initwithoverallinvalidsemantics:expirydatesemantics:issuedatesemantics:birthdatesemantics:issuedatebeforeexpirydate:birthdatebeforeissuedate:birthdatebeforeexpirydate:"]}],"kind":"symbol","sections":[],"metadata":{"title":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","navigatorTitle":[{"text":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSemanticsVerificationReport(im)initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompositeFieldValueSemantics":{"role":"symbol","navigatorTitle":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"title":"SBSDKCompositeFieldValueSemantics","abstract":[{"type":"text","text":"Report of a logical field value semantics verification. If some logical field, e.g. expiry date is present in"},{"type":"text","text":" "},{"text":"multiple places in the document, it can occur that some entries are semantically correct and some are semantically","type":"text"},{"text":" ","type":"text"},{"text":"incorrect. This report shows the overall status of the logical field value semantics verification and details for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"each field that was verified."}],"url":"\/documentation\/scanbotsdk\/sbsdkcompositefieldvaluesemantics","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompositeFieldValueSemantics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCompositeFieldValueSemantics"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics":{"type":"topic","title":"SBSDKValueSemantics","abstract":[{"type":"text","text":"The result of the value semantics verification."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","navigatorTitle":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKValueSemantics","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:":{"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/initwithoverallinvalidsemantics:expirydatesemantics:issuedatesemantics:birthdatesemantics:issuedatebeforeexpirydate:birthdatebeforeissuedate:birthdatebeforeexpirydate:","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","kind":"identifier"}],"abstract":[],"title":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","navigatorTitle":[{"text":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport":{"title":"SBSDKSemanticsVerificationReport","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport","role":"symbol","navigatorTitle":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"abstract":[{"type":"text","text":"Report of the document value semantics verification."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKCompositeFieldValueSemantics","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompositeFieldValueSemantics\/navigatorTitle","value":[{"text":"SBSDKCompositeFieldValueSemantics","kind":"identifier"}],"op":"replace"},{"value":"SBSDKValueSemantics","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/fragments","op":"replace","value":[{"text":"SBSDKValueSemantics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/navigatorTitle","value":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"op":"replace"},{"value":"SBSDKSemanticsVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/title"},{"value":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/navigatorTitle"}]}]}