{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"assignedToAccidentInsuranceDoctor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/assignedtoaccidentinsurancedoctor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/assignedtoaccidentinsurancedoctor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/assignedToAccidentInsuranceDoctor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Assigned To Accident Insurance Doctor"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"assignedToAccidentInsuranceDoctor"}],"title":"SBSDKUI2MedicalCertificateDocumentFieldType.assignedToAccidentInsuranceDoctor","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MedicalCertificateDocumentFieldType@SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"abstract":[{"type":"text","text":"Medical Certificate Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/assignedToAccidentInsuranceDoctor":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.assignedToAccidentInsuranceDoctor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"assignedToAccidentInsuranceDoctor"}],"abstract":[{"type":"text","text":"Assigned To Accident Insurance Doctor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/assignedToAccidentInsuranceDoctor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/assignedtoaccidentinsurancedoctor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1assignedToAccidentInsuranceDoctor\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1assignedToAccidentInsuranceDoctor\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeAssignedToAccidentInsuranceDoctor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}