{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"renewedCertificate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/renewedcertificate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/renewedcertificate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/renewedCertificate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Renewed Certificate"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"renewedCertificate"}],"title":"SBSDKUI2MedicalCertificateDocumentFieldType.renewedCertificate","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MedicalCertificateDocumentFieldType@SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"abstract":[{"type":"text","text":"Medical Certificate Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalCertificateDocumentFieldType/renewedCertificate":{"role":"symbol","title":"SBSDKUI2MedicalCertificateDocumentFieldType.renewedCertificate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"renewedCertificate"}],"abstract":[{"type":"text","text":"Renewed Certificate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalCertificateDocumentFieldType\/renewedCertificate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalcertificatedocumentfieldtype\/renewedcertificate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1renewedCertificate\/title","value":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalCertificateDocumentFieldType~1renewedCertificate\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalCertificateDocumentFieldTypeRenewedCertificate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}