{"metadata":{"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabledWithGuidance","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabledWithGuidance"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKAutoSnappingMode@SBSDKAutoSnappingModeDisabledWithGuidance","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKAutoSnappingMode.disabledWithGuidance"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabledWithGuidance"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/disabledwithguidance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/disabledwithguidance"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode"]]},"abstract":[{"type":"text","text":"Auto-snapping is disabled while user guidance is enabled."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabledWithGuidance","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode":{"abstract":[{"type":"text","text":"The Auto-snapping mode handles different auto-snap scenarios."}],"title":"SBSDKAutoSnappingMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/disabledWithGuidance":{"title":"SBSDKAutoSnappingMode.disabledWithGuidance","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabledWithGuidance","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/disabledwithguidance","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabledWithGuidance","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAutoSnappingModeDisabledWithGuidance","kind":"identifier"}],"type":"topic","abstract":[{"text":"Auto-snapping is disabled while user guidance is enabled.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKAutoSnappingModeDisabledWithGuidance","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabledWithGuidance"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabledWithGuidance"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKAutoSnappingMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/navigatorTitle"},{"op":"replace","value":"SBSDKAutoSnappingModeDisabledWithGuidance","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1disabledWithGuidance\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabledWithGuidance"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1disabledWithGuidance\/fragments"}]}]}