{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScanAndCountPolygonStyle"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKScanAndCountPolygonStyle(im)init","role":"symbol","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScanAndCountPolygonStyle\/init","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkscanandcountpolygonstyle\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScanAndCountPolygonStyle":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"abstract":[{"text":"A class that represents the style of the polygon rendered around a barcode in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController"},{"text":".","type":"text"}],"title":"SBSDKScanAndCountPolygonStyle","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscanandcountpolygonstyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScanAndCountPolygonStyle","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScanAndCountPolygonStyle/init":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScanAndCountPolygonStyle\/init","role":"symbol","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscanandcountpolygonstyle\/init","title":"init"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller","type":"topic","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."},{"type":"text","text":" "},{"type":"text","text":"Screen also shows snap, scan more and reset buttons."},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"type":"text","text":" "},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"type":"text","text":" "},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"title":"SBSDKBarcodeScanAndCountViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKScanAndCountPolygonStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScanAndCountPolygonStyle\/title"},{"value":[{"text":"SBSDKScanAndCountPolygonStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScanAndCountPolygonStyle\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKScanAndCountPolygonStyle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScanAndCountPolygonStyle\/navigatorTitle"},{"value":"SBSDKBarcodeScanAndCountViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/title"},{"value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle"}]}]}