{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintOKManualScan","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintokmanualscan"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintokmanualscan"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintOKManualScan","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration"]]},"sections":[],"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when a document was detected with good conditions."},{"type":"text","text":" "},{"text":"Used with ","type":"text"},{"code":"autoShutterEnabled","type":"codeVoice"},{"text":" set to ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textHintOKManualScan"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"textHintOKManualScan","kind":"identifier"}],"roleHeading":"Instance Property","title":"textHintOKManualScan","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerStatusTextConfiguration(py)textHintOKManualScan","symbolKind":"property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerStatusTextConfiguration/textHintOKManualScan":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textHintOKManualScan"}],"abstract":[{"text":"The text being displayed on the user-guidance label, when a document was detected with good conditions.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Used with "},{"code":"autoShutterEnabled","type":"codeVoice"},{"text":" set to ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintOKManualScan","type":"topic","title":"textHintOKManualScan","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintokmanualscan","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintOKManualScan","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerStatusTextConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}],"abstract":[{"text":"Wraps the texts being displayed as the detection status.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration","type":"topic","title":"SBSDKDocumentScannerStatusTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"textHintOKManualScan","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"textHintOKManualScan","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"textHintOKManualScan","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintOKManualScan\/title","value":"textHintOKManualScan"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintOKManualScan\/fragments","op":"replace","value":[{"text":"textHintOKManualScan","kind":"identifier"}]},{"op":"replace","value":"SBSDKDocumentScannerStatusTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/fragments","value":[{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}]}]}]}