{"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2CroppingViewController instead.","type":"text"}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration\/polygonLineWidth","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonLineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Defaults to 2"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration\/polygonlinewidth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration\/polygonlinewidth"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonLineWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"polygonLineWidth"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration(py)polygonLineWidth","symbolKind":"property","title":"polygonLineWidth"},"abstract":[{"type":"text","text":"Defines the width of the polygon line in the cropping view."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenUIConfiguration/polygonLineWidth":{"kind":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration\/polygonlinewidth","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration\/polygonLineWidth","navigatorTitle":[{"kind":"identifier","text":"polygonLineWidth"}],"title":"polygonLineWidth","abstract":[{"type":"text","text":"Defines the width of the polygon line in the cropping view."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonLineWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenUIConfiguration":{"title":"SBSDKUICroppingScreenUIConfiguration","abstract":[{"type":"text","text":"Configuration for user interface of the page cropping screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration","role":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"polygonLineWidth"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"polygonLineWidth"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"polygonLineWidth","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration~1polygonLineWidth\/title","op":"replace","value":"polygonLineWidth"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration~1polygonLineWidth\/fragments","op":"replace","value":[{"text":"polygonLineWidth","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration\/title","op":"replace","value":"SBSDKUICroppingScreenUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}