{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseinfo\/init(status:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:nextonlinelicensecheckinms:devicederegistationerrors:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseinfo\/init(status:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:nextonlinelicensecheckinms:devicederegistationerrors:)"]}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"licenseStatusMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"expirationTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"expirationDateString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"errorMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"onlineLicenseCheckInProgress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"deviceDeregistationErrors","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"SBSDKDeviceDeregistrationError","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceDeregistrationError"},{"text":">)","kind":"text"}],"symbolKind":"init","roleHeading":"Initializer","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicenseInfo(im)initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","navigatorTitle":[{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus","text":"SBSDKLicenseStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"licenseStatusMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expirationTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expirationDateString","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"errorMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onlineLicenseCheckInProgress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"deviceDeregistationErrors","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError","text":"SBSDKDeviceDeregistrationError","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceDeregistrationError"},{"text":">)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"}],"title":"init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/init(status:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:nextonlinelicensecheckinms:devicederegistationerrors:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseStatusMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expirationTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expirationDateString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlineLicenseCheckInProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextOnlineLicenseCheckInMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceDeregistationErrors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SBSDKDeviceDeregistrationError","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceDeregistrationError"},{"kind":"text","text":">)"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo","title":"SBSDKLicenseInfo","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseInfo"}],"kind":"symbol","abstract":[{"type":"text","text":"Information about the SDK license."}],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceDeregistrationError":{"navigatorTitle":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError","url":"\/documentation\/scanbotsdk\/sbsdkdevicederegistrationerror","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Description of error that occurred during device deregistration."}],"kind":"symbol","title":"SBSDKDeviceDeregistrationError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus","type":"topic","abstract":[{"text":"Status of the license plate scanner.","type":"text"}],"title":"SBSDKLicenseStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isValid:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isValid","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"licenseStatusMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"licenseStatusMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expirationTimestamp:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"expirationTimestamp","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expirationDateString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"expirationDateString","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"errorMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"errorMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"onlineLicenseCheckInProgress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"onlineLicenseCheckInProgress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"license:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"license","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"deviceDeregistationErrors:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKDeviceDeregistrationError *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"deviceDeregistationErrors","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo~1init(status:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:)\/fragments","op":"replace"},{"value":"SBSDKLicenseInfo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseInfo"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/fragments","op":"replace"},{"value":[{"text":"SBSDKLicenseInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/navigatorTitle","op":"replace"},{"value":"SBSDKDeviceDeregistrationError","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/title","op":"replace"},{"value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/fragments","op":"replace"},{"value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/navigatorTitle","op":"replace"},{"value":"SBSDKLicenseStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments","op":"replace"},{"value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/navigatorTitle","op":"replace"}]}]}