{"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPathImageLoadOptions(im)isEqual:","title":"isEqual:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions\/isEqual:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions\/isequal:"]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathImageLoadOptions/isEqual:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions\/isequal:","type":"topic","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions\/isEqual:","fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathImageLoadOptions":{"title":"SBSDKPathImageLoadOptions","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions","navigatorTitle":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options for loading image from path."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/title","value":"SBSDKPathImageLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/fragments","value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}