{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerTextConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerConfiguration\/textConfiguration","interfaceLanguage":"swift"},"metadata":{"title":"textConfiguration","role":"symbol","platforms":[],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerTextConfiguration","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"textConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerConfiguration(py)textConfiguration","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The configuration for displayed texts."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerconfiguration\/textconfiguration"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerconfiguration\/textconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerConfiguration/textConfiguration":{"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerConfiguration\/textConfiguration","type":"topic","title":"textConfiguration","abstract":[{"text":"The configuration for displayed texts.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerconfiguration\/textconfiguration","kind":"symbol","navigatorTitle":[{"text":"textConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textConfiguration"},{"kind":"text","text":": "},{"text":"SBSDKUIBarcodesBatchScannerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerTextConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerconfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerConfiguration","kind":"identifier"}],"title":"SBSDKUIBarcodesBatchScannerConfiguration","kind":"symbol","deprecated":true,"abstract":[{"text":"This class describes the look and feel, as well as the textual contents of the RTU-UI batch barcode scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration","type":"topic","title":"SBSDKUIBarcodesBatchScannerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannertextconfiguration","abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI batch barcode scanner."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerTextConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"}],"deprecated":true}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"textConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"textConfiguration","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerTextConfiguration","text":"SBSDKUIBarcodesBatchScannerTextConfiguration"},{"text":" * ","kind":"text"},{"text":"textConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration~1textConfiguration\/title","value":"textConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"textConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration~1textConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerConfiguration"},{"op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration\/title","value":"SBSDKUIBarcodesBatchScannerTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerTextConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}