{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement\/upperRight"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/upperright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/upperright"]}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upperRight","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDisplacement@SBSDKDocumentDisplacementUpperRight","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDisplacementUpperRight"}],"symbolKind":"case","title":"SBSDKDocumentDisplacement.upperRight"},"abstract":[{"text":"The document is partially visible. Move the camera up and to the right to capture the full document.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upperRight","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDisplacement":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement","title":"SBSDKDocumentDisplacement","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDisplacement","kind":"identifier"}],"abstract":[{"type":"text","text":"The direction towards the center of the document if the document is partially visible."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDisplacement/upperRight":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDisplacement\/upperRight","title":"SBSDKDocumentDisplacement.upperRight","abstract":[{"type":"text","text":"The document is partially visible. Move the camera up and to the right to capture the full document."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdisplacement\/upperright","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDisplacementUpperRight","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upperRight","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentDisplacementUpperRight"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDisplacementUpperRight","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKDocumentDisplacementUpperRight","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/title","op":"replace","value":"SBSDKDocumentDisplacement"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDisplacement"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDisplacement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement~1upperRight\/title","op":"replace","value":"SBSDKDocumentDisplacementUpperRight"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDisplacement~1upperRight\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDisplacementUpperRight","kind":"identifier"}]}]}]}