{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumTextLength"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is 0"}],"type":"paragraph"}]}],"kind":"symbol","sections":[],"abstract":[{"text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Property","title":"maximumTextLength","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumTextLength","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"maximumTextLength"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCodabarConfiguration(py)maximumTextLength"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/maximumTextLength"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/maximumtextlength"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/maximumtextlength"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/maximumTextLength":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/maximumtextlength","kind":"symbol","type":"topic","title":"maximumTextLength","navigatorTitle":[{"text":"maximumTextLength","kind":"identifier"}],"abstract":[{"type":"text","text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/maximumTextLength","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumTextLength"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration":{"abstract":[{"type":"text","text":"Codabar barcode configuration. Add to scanner configuration to scan Codabar barcodes."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeFormatCodabarConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"maximumTextLength","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"maximumTextLength","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"maximumTextLength","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1maximumTextLength\/title","value":"maximumTextLength"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1maximumTextLength\/fragments","value":[{"text":"maximumTextLength","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/title","value":"SBSDKBarcodeFormatCodabarConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/navigatorTitle","op":"replace"}]}]}