{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner\/create()","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanner","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner","text":"SBSDKMedicalCertificateScanner"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"name":"Throws","style":"note","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","type":"reference","isActive":true},{"type":"text","text":" in case of an error."}],"type":"paragraph"}],"type":"aside"}],"kind":"content"}],"metadata":{"title":"create()","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanner","text":"SBSDKMedicalCertificateScanner","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanner(cm)createAndReturnError:","role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"createAndReturnError:"}]},"abstract":[{"type":"text","text":"Initialize the generic document recognizer."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanner\/create()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanner\/create()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanner/create()":{"title":"create()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createAndReturnError:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanner","kind":"typeIdentifier","text":"SBSDKMedicalCertificateScanner"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner\/create()","abstract":[{"type":"text","text":"Initialize the generic document recognizer."}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanner\/create()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanner":{"title":"SBSDKMedicalCertificateScanner","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanner","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateScanner","kind":"identifier"}],"abstract":[{"type":"text","text":"API for medical certificate scanning."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScanner","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKError":{"title":"SBSDKError","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerror","abstract":[{"text":"Represents errors that can occur within the Scanbot SDK.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKError","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKError","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createAndReturnError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createAndReturnError:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKMedicalCertificateScanner","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanner","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanner"},{"text":" *) ","kind":"text"},{"text":"createAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"add","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for this parameter.","type":"text"}]}],"name":"error"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"type":"text","text":". On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","value":"createAndReturnError:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner~1create()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createAndReturnError:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner~1create()\/fragments"},{"op":"replace","value":"SBSDKMedicalCertificateScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanner"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanner"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanner\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}