{"sections":[],"metadata":{"title":"encryptionMode","symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","text":"SBSDKEncryptionMode","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKKeyedImageStorage(py)encryptionMode","roleHeading":"Instance Property","navigatorTitle":[{"text":"encryptionMode","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"The encryption mode for the stored images. Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode\/disabled"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage\/encryptionMode","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier","text":"SBSDKEncryptionMode"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/encryptionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/encryptionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage/encryptionMode":{"abstract":[{"type":"text","text":"The encryption mode for the stored images. Defaults to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode\/disabled"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage\/encryptionmode","kind":"symbol","title":"encryptionMode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier","text":"SBSDKEncryptionMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage\/encryptionMode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encryptionMode"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncryptionMode/disabled":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"url":"\/documentation\/scanbotsdk\/sbsdkencryptionmode\/disabled","title":"SBSDKEncryptionMode.disabled","abstract":[{"text":"Encryption is not used when loading or saving images. Trying to load an encrypted image will fail.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode\/disabled","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncryptionMode":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","url":"\/documentation\/scanbotsdk\/sbsdkencryptionmode","abstract":[{"text":"Encryption\/Decryption mode to be used when an image is loaded\/saved.","type":"text"}],"title":"SBSDKEncryptionMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncryptionMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage","navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"title":"SBSDKKeyedImageStorage","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class."},{"type":"text","text":" "},{"type":"text","text":"Manages images in a dictionary-like fashion."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"encryptionMode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"encryptionMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"encryptionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage~1encryptionMode\/title"},{"value":[{"kind":"identifier","text":"encryptionMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage~1encryptionMode\/fragments"},{"value":"SBSDKEncryptionModeDisabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode~1disabled\/title"},{"value":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode~1disabled\/fragments"},{"value":"SBSDKEncryptionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/fragments"},{"value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/navigatorTitle"},{"value":"SBSDKKeyedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/title"},{"value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}