{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcolorconversion\/anycolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcolorconversion\/anycolor"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Load image as 3-channel BGR if the source color space is color, otherwise as single-channel grayscale. Alpha channel is discarded."}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion\/anyColor"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anyColor","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion"]]},"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKColorConversion@SBSDKColorConversionAnyColor","title":"SBSDKColorConversion.anyColor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"anyColor"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKColorConversionAnyColor"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorConversion":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKColorConversion"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcolorconversion","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKColorConversion"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion","title":"SBSDKColorConversion","kind":"symbol","abstract":[{"text":"Color conversion to apply during image loading.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorConversion/anyColor":{"title":"SBSDKColorConversion.anyColor","navigatorTitle":[{"kind":"identifier","text":"SBSDKColorConversionAnyColor"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcolorconversion\/anycolor","abstract":[{"type":"text","text":"Load image as 3-channel BGR if the source color space is color, otherwise as single-channel grayscale. Alpha channel is discarded."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"anyColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorConversion\/anyColor","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKColorConversionAnyColor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKColorConversionAnyColor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKColorConversionAnyColor","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/title","value":"SBSDKColorConversion","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/fragments","value":[{"kind":"identifier","text":"SBSDKColorConversion"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion\/navigatorTitle","value":[{"text":"SBSDKColorConversion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion~1anyColor\/title","value":"SBSDKColorConversionAnyColor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorConversion~1anyColor\/fragments","value":[{"kind":"identifier","text":"SBSDKColorConversionAnyColor"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}