{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuserfielddoublevalue\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldDoubleValue"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","title":"copyWithZone:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldDoubleValue(im)copyWithZone:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldDoubleValue\/copyWithZone:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldDoubleValue/copyWithZone:":{"title":"copyWithZone:","role":"symbol","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotsdk\/sbsdkuserfielddoublevalue\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldDoubleValue\/copyWithZone:","type":"topic","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldDoubleValue":{"title":"SBSDKUserFieldDoubleValue","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuserfielddoublevalue","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldDoubleValue","type":"topic","abstract":[{"type":"text","text":"Double value (TIFF_DOUBLE)."}],"navigatorTitle":[{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUserFieldDoubleValue","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldDoubleValue\/title"},{"value":[{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldDoubleValue\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldDoubleValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUserFieldDoubleValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}