{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/barcodewithoutvin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/barcodewithoutvin"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeWithoutVin","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeWithoutVin"},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKVINBarcodeExtractionStatus@SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKVINBarcodeExtractionStatus.barcodeWithoutVin","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeWithoutVin","kind":"identifier"}],"roleHeading":"Case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Barcode was found but it does not contain a VIN."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"title":"SBSDKVINBarcodeExtractionStatus","kind":"symbol","navigatorTitle":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status of the barcode extraction."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/barcodeWithoutVin":{"type":"topic","role":"symbol","title":"SBSDKVINBarcodeExtractionStatus.barcodeWithoutVin","abstract":[{"type":"text","text":"Barcode was found but it does not contain a VIN."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeWithoutVin"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/barcodewithoutvin","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/barcodeWithoutVin"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/title","value":"SBSDKVINBarcodeExtractionStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1barcodeWithoutVin\/title","value":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1barcodeWithoutVin\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusBarcodeWithoutVin"}]}]}]}