{"metadata":{"title":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenConfiguration(im)initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:","navigatorTitle":[{"text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:","kind":"identifier"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration\/initwithversion:screen:localization:palette:backgroundcolor:cameraconfiguration:camerapermission:topuserguidance:finderviewuserguidance:topbar:topbaropenintroscreenbutton:introscreen:actionbar:viewfinder:scannerconfiguration:shouldshowwordb-27hw1"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithVersion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"version"},{"text":" ","kind":"text"},{"kind":"identifier","text":"screen:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"screen"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localization:"},{"kind":"text","text":"("},{"text":"SBSDKUI2TextPatternScannerScreenTextLocalization","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenTextLocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"localization"},{"kind":"text","text":" "},{"text":"palette:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Palette","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","kind":"typeIdentifier","text":"SBSDKUI2Palette"},{"text":" *) ","kind":"text"},{"text":"palette","kind":"internalParam"},{"kind":"text","text":" "},{"text":"backgroundColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"text":" ","kind":"text"},{"text":"cameraConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration","text":"SBSDKUI2CameraConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraConfiguration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraPermission:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermission","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"topUserGuidance:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration"},{"text":" *) ","kind":"text"},{"text":"topUserGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderViewUserGuidance:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"text":" *) ","kind":"text"},{"text":"finderViewUserGuidance","kind":"internalParam"},{"kind":"text","text":" "},{"text":"topBar:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2TopBarConfiguration"},{"text":" *) ","kind":"text"},{"text":"topBar","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarOpenIntroScreenButton:"},{"kind":"text","text":"("},{"text":"SBSDKUI2IconButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"},{"kind":"text","text":" *) "},{"text":"topBarOpenIntroScreenButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"introScreen:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerIntroScreenConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"introScreen","kind":"internalParam"},{"kind":"text","text":" "},{"text":"actionBar:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ActionBarConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ActionBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"actionBar"},{"text":" ","kind":"text"},{"text":"viewFinder:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewFinder"},{"text":" ","kind":"text"},{"text":"scannerConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKTextPatternScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"scannerConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldShowWordBoxes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"shouldShowWordBoxes","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wordBoxesFillColor:"},{"kind":"text","text":"("},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"wordBoxesFillColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wordBoxesLineColor:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"wordBoxesLineColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationAlertDialogEnabled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"confirmationAlertDialogEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationAlertDialog:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"confirmationAlertDialog","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"successOverlay:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2ScanCompletionOverlay","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"successOverlay"},{"text":" ","kind":"text"},{"text":"sound:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","text":"SBSDKUI2Sound","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound"},{"text":" *) ","kind":"text"},{"text":"sound","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"vibration:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration","text":"SBSDKUI2Vibration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"vibration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration\/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration":{"role":"symbol","type":"topic","abstract":[{"text":"Configuration for the text pattern scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"title":"SBSDKTextPatternScannerConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanCompletionOverlay":{"title":"SBSDKUI2ScanCompletionOverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2scancompletionoverlay","abstract":[{"type":"text","text":"Configuration of the overlay to be shown after the successful scan."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Vibration":{"title":"SBSDKUI2Vibration","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Vibration"}],"abstract":[{"type":"text","text":"Configure the vibration."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","url":"\/documentation\/scanbotsdk\/sbsdkui2vibration","navigatorTitle":[{"text":"SBSDKUI2Vibration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanbotAlertDialog":{"navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"abstract":[{"text":"Configuration of the standard alert dialog.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2scanbotalertdialog","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","role":"symbol","title":"SBSDKUI2ScanbotAlertDialog","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenConfiguration":{"kind":"symbol","type":"topic","abstract":[{"text":"Configuration of the screen for detecting generic text data.","type":"text"}],"title":"SBSDKUI2TextPatternScannerScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for generic text scanner screen."}],"title":"SBSDKUI2TextPatternScannerScreenTextLocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"title":"SBSDKUI2UserGuidanceConfiguration","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the hint guiding users through the scanning process.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconButton":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2iconbutton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconButton"}],"title":"SBSDKUI2IconButton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconButton"}],"abstract":[{"text":"Configuration of the icon appearance on a button.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the camera settings to be used while scanning."}],"kind":"symbol","title":"SBSDKUI2CameraConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound":{"navigatorTitle":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"title":"SBSDKUI2Sound","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Sound","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration for the sound.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2sound"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"title":"SBSDKUI2TopBarConfiguration","type":"topic","abstract":[{"text":"Configuration of the top bar’s appearance.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","title":"SBSDKUI2CameraPermissionScreen","abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"title":"SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenConfiguration/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:":{"navigatorTitle":[{"kind":"identifier","text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreenconfiguration\/initwithversion:screen:localization:palette:backgroundcolor:cameraconfiguration:camerapermission:topuserguidance:finderviewuserguidance:topbar:topbaropenintroscreenbutton:introscreen:actionbar:viewfinder:scannerconfiguration:shouldshowwordb-27hw1","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenConfiguration\/initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:"}],"role":"symbol","title":"initWithVersion:screen:localization:palette:backgroundColor:cameraConfiguration:cameraPermission:topUserGuidance:finderViewUserGuidance:topBar:topBarOpenIntroScreenButton:introScreen:actionBar:viewFinder:scannerConfiguration:shouldShowWordBoxes:wordBoxesFillColor:wordBoxesLineColor:confirmationAlertDialogEnabled:confirmationAlertDialog:successOverlay:sound:vibration:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ActionBarConfiguration":{"abstract":[{"text":"Configuration of the buttons available in the action bar.","type":"text"}],"title":"SBSDKUI2ActionBarConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2actionbarconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ActionBarConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ActionBarConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PermanentViewFinderConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2permanentviewfinderconfiguration","title":"SBSDKUI2PermanentViewFinderConfiguration","kind":"symbol","abstract":[{"text":"Configuration of the scanning interface’s viewfinder, which is always visible to guide the user.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroScreenConfiguration":{"title":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration","abstract":[{"text":"Configuration of the introduction screen for the generic text scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Palette":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Palette","abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Palette","kind":"identifier"}],"title":"SBSDKUI2Palette","url":"\/documentation\/scanbotsdk\/sbsdkui2palette","navigatorTitle":[{"text":"SBSDKUI2Palette","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/title","value":"SBSDKTextPatternScannerConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/title","value":"SBSDKUI2ScanCompletionOverlay"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/fragments","value":[{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/title","value":"SBSDKUI2Vibration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/fragments","op":"replace","value":[{"text":"SBSDKUI2Vibration","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2Vibration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/navigatorTitle"},{"value":"SBSDKUI2ScanbotAlertDialog","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","op":"replace","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/title","value":"SBSDKUI2TextPatternScannerScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2TextPatternScannerScreenConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2TextPatternScannerScreenTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerScreenTextLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title","op":"replace","value":"SBSDKUI2UserGuidanceConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKUI2IconButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/title","value":"SBSDKUI2CameraConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/title","op":"replace","value":"SBSDKUI2Sound"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Sound"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Sound","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2TopBarConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/title"},{"value":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title","value":"SBSDKUI2CameraPermissionScreen"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"value":"SBSDKUI2ActionBarConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ActionBarConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ActionBarConfiguration","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2PermanentViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/fragments","value":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/navigatorTitle"},{"value":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/title","op":"replace","value":"SBSDKUI2Palette"},{"op":"replace","value":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Palette\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}