{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/initwithcompression:jpegquality:zipcompressionlevel:dpi:userfields:binarizationfilter:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters(im)initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","fragments":[{"kind":"text","text":"- "},{"text":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCompression:"},{"text":"(","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"compression"},{"text":" ","kind":"text"},{"text":"jpegQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"jpegQuality"},{"text":" ","kind":"text"},{"text":"zipCompressionLevel:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"zipCompressionLevel","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dpi:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"dpi","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"userFields:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKUserField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"userFields","kind":"internalParam"},{"kind":"text","text":" "},{"text":"binarizationFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter"},{"kind":"text","text":" *) "},{"text":"binarizationFilter","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompressionMode":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCompressionMode"}],"title":"SBSDKCompressionMode","abstract":[{"type":"text","text":"TIFF compression type."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCompressionMode"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcompressionmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:":{"navigatorTitle":[{"kind":"identifier","text":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:"}],"title":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/initwithcompression:jpegquality:zipcompressionlevel:dpi:userfields:binarizationfilter:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/initWithCompression:jpegQuality:zipCompressionLevel:dpi:userFields:binarizationFilter:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","title":"SBSDKTIFFGeneratorParameters","kind":"symbol","abstract":[{"type":"text","text":"TIFF generator parameters."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKParametricFilter":{"title":"SBSDKParametricFilter","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKParametricFilter","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkparametricfilter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/title","op":"replace","value":"SBSDKCompressionMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCompressionMode"}]},{"value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/navigatorTitle"},{"value":"SBSDKTIFFGeneratorParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title"},{"value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle"},{"op":"replace","value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"op":"replace"}]}]}