{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"kind":"text","text":" *) "},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFunnelAnimation\/copyWithZone:"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFunnelAnimation(im)copyWithZone:","role":"symbol","roleHeading":"Instance Method"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfunnelanimation\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFunnelAnimation"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFunnelAnimation/copyWithZone:":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFunnelAnimation\/copyWithZone:","title":"copyWithZone:","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfunnelanimation\/copywithzone:","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFunnelAnimation":{"navigatorTitle":[{"text":"SBSDKUI2PageSnapFunnelAnimation","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFunnelAnimation","title":"SBSDKUI2PageSnapFunnelAnimation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfunnelanimation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}],"abstract":[{"text":"Configuration of the funnel animation.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFunnelAnimation\/title","op":"replace","value":"SBSDKUI2PageSnapFunnelAnimation"},{"value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFunnelAnimation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFunnelAnimation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}