{"metadata":{"symbolKind":"property","roleHeading":"Type Property","title":"serialImageProcessingQueue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialImageProcessingQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier","text":"OperationQueue"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessingQueueFactory(cpy)serialImageProcessingQueue","navigatorTitle":[{"text":"serialImageProcessingQueue","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serialImageProcessingQueue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OperationQueue","preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/serialimageprocessingqueue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/serialimageprocessingqueue"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The serial image processing queue.","type":"text"},{"text":" ","type":"text"},{"text":"If you do additional image processing on large images or other tasks that consumes a lot of memory.","type":"text"},{"text":" ","type":"text"},{"text":"it is highly recommended to use this queue.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialImageProcessingQueue","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingQueueFactory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory","title":"SBSDKProcessingQueueFactory","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"abstract":[{"text":"Factory class providing different instances of","type":"text"},{"code":"NSOperationQueue","type":"codeVoice"},{"text":" to work on.","type":"text"},{"text":" ","type":"text"},{"text":"There are 2 main queues:","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingQueueFactory/serialImageProcessingQueue":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialImageProcessingQueue","type":"topic","title":"serialImageProcessingQueue","abstract":[{"type":"text","text":"The serial image processing queue."},{"type":"text","text":" "},{"type":"text","text":"If you do additional image processing on large images or other tasks that consumes a lot of memory."},{"type":"text","text":" "},{"type":"text","text":"it is highly recommended to use this queue."}],"role":"symbol","navigatorTitle":[{"text":"serialImageProcessingQueue","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serialImageProcessingQueue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OperationQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/serialimageprocessingqueue","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"serialImageProcessingQueue","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"serialImageProcessingQueue","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier","text":"NSOperationQueue"},{"kind":"text","text":" * "},{"kind":"identifier","text":"serialImageProcessingQueue"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKProcessingQueueFactory","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/title"},{"op":"replace","value":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/fragments"},{"op":"replace","value":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/navigatorTitle"},{"op":"replace","value":"serialImageProcessingQueue","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory~1serialImageProcessingQueue\/title"},{"op":"replace","value":[{"text":"serialImageProcessingQueue","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory~1serialImageProcessingQueue\/fragments"}]}]}