{"sections":[],"metadata":{"role":"symbol","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"title":"init(configuration:delegate:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","text":"SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKTextPatternScannerViewControllerDelegate","text":"SBSDKTextPatternScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:delegate:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController(im)initWithConfiguration:delegate:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller\/init(configuration:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller\/init(configuration:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithConfiguration:delegate:) "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier","text":"SBSDKTextPatternScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKTextPatternScannerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKTextPatternScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration object to configure the receiver.","type":"text"}],"type":"paragraph"}]},{"name":"delegate","content":[{"inlineContent":[{"type":"text","text":"The delegate of the receiver."}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController\/init(configuration:delegate:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"]]},"kind":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"},{"type":"text","text":"."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","title":"SBSDKTextPatternScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration","abstract":[{"text":"Configuration for the text pattern scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController/init(configuration:delegate:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:delegate:"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller\/init(configuration:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController\/init(configuration:delegate:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration","text":"SBSDKTextPatternScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKTextPatternScannerViewControllerDelegate","text":"SBSDKTextPatternScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"title":"init(configuration:delegate:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate","abstract":[{"type":"text","text":"The delegation protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewControllerDelegate"}],"title":"SBSDKTextPatternScannerViewControllerDelegate","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"navigatorTitle":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the text pattern scanner.","type":"text"}],"title":"SBSDKTextPatternScannerViewController","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithConfiguration:delegate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:delegate:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","text":"SBSDKTextPatternScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKTextPatternScannerViewControllerDelegate","text":"id<SBSDKTextPatternScannerViewControllerDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"text":"The configuration object to configure the receiver.","type":"text"}]}]},{"name":"delegate","content":[{"inlineContent":[{"type":"text","text":"The delegate of the receiver."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/title","op":"replace","value":"SBSDKTextPatternScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController~1init(configuration:delegate:)\/title","op":"replace","value":"initWithConfiguration:delegate:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController~1init(configuration:delegate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:delegate:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKTextPatternScannerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/fragments","op":"replace","value":[{"text":"SBSDKTextPatternScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTextPatternScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title","op":"replace","value":"SBSDKTextPatternScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}]}]}]}