{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/style"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/style"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/style","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2FinderStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderStyle"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"style","navigatorTitle":[{"kind":"identifier","text":"style"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseViewFinderConfiguration(py)style"},"sections":[],"abstract":[{"type":"text","text":"The visual appearance of the viewfinder."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2FinderStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderStyle"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration":{"abstract":[{"text":"Base configuration of the scanning interface’s viewfinder, serving as guidance to the user.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration","navigatorTitle":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration","title":"SBSDKUI2BaseViewFinderConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FinderStyle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2finderstyle","abstract":[{"type":"text","text":"The visual appearance of the viewfinder."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FinderStyle"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FinderStyle"}],"role":"symbol","title":"SBSDKUI2FinderStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/style":{"title":"style","navigatorTitle":[{"text":"style","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2FinderStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/style","abstract":[{"text":"The visual appearance of the viewfinder.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/style","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"style"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2FinderStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderStyle"},{"text":" * ","kind":"text"},{"text":"style","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/title","value":"SBSDKUI2BaseViewFinderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle\/title","value":"SBSDKUI2FinderStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2FinderStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2FinderStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1style\/title","value":"style"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1style\/fragments","value":[{"text":"style","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}