{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingappearanceconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"title":"hash","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration(py)hash","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration\/hash"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingAppearanceConfiguration":{"role":"symbol","type":"topic","abstract":[{"text":"Configuration of the general appearance for the cropping screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}],"title":"SBSDKUI2CroppingAppearanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingappearanceconfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingAppearanceConfiguration/hash":{"type":"topic","title":"hash","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingappearanceconfiguration\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2CroppingAppearanceConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}