{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithOverallIsInvalid:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"overallIsInvalid"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldDetails:"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKFieldInvalidDataVerificationReport *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fieldDetails","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport"]]},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"initWithOverallIsInvalid:fieldDetails:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport(im)initWithOverallIsInvalid:fieldDetails:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverallIsInvalid:fieldDetails:"}],"role":"symbol","roleHeading":"Instance Method","title":"initWithOverallIsInvalid:fieldDetails:","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/initWithOverallIsInvalid:fieldDetails:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/initwithoverallisinvalid:fielddetails:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/initWithOverallIsInvalid:fieldDetails:":{"navigatorTitle":[{"text":"initWithOverallIsInvalid:fieldDetails:","kind":"identifier"}],"title":"initWithOverallIsInvalid:fieldDetails:","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithOverallIsInvalid:fieldDetails:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/initwithoverallisinvalid:fielddetails:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/initWithOverallIsInvalid:fieldDetails:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport":{"kind":"symbol","title":"SBSDKInvalidDataVerificationReport","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"}],"url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"}],"abstract":[{"text":"Report of the field validation verification.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/title","value":"SBSDKInvalidDataVerificationReport","op":"replace"},{"value":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/fragments","op":"replace"},{"value":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}