{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/isViewFinderEnabled","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/isviewfinderenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/isviewfinderenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":" to enable and display the region of interest, to "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"False","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"isViewFinderEnabled","kind":"identifier"}],"title":"isViewFinderEnabled","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(py)isViewFinderEnabled","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isViewFinderEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration":{"title":"SBSDKBaseScannerViewFinderConfiguration","abstract":[{"text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"text":" ","type":"text"},{"text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in.","type":"text"},{"type":"text","text":" "},{"text":"It crops the video frame to that region of interest before passing it to any detector or recognizer. Usually","type":"text"},{"type":"text","text":" "},{"text":"the performance of detectors\/recognizers gain a benefit from it because less pixels must be processed.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around"},{"text":" ","type":"text"},{"text":"on the user interface.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration/isViewFinderEnabled":{"abstract":[{"text":"Set to ","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":" to enable and display the region of interest, to "},{"code":"False","type":"codeVoice"},{"text":" otherwise.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isViewFinderEnabled"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/isViewFinderEnabled","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/isviewfinderenabled","title":"isViewFinderEnabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isViewFinderEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isViewFinderEnabled"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isViewFinderEnabled"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"isViewFinderEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/title","value":"SBSDKBaseScannerViewFinderConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","value":"isViewFinderEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1isViewFinderEnabled\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1isViewFinderEnabled\/fragments","op":"replace","value":[{"text":"isViewFinderEnabled","kind":"identifier"}]}]}]}