{"sections":[],"metadata":{"role":"symbol","roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDeAddressParserConfiguration(cm)fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKDeAddressParserConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDeAddressParserConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration"},{"kind":"text","text":" *) "},{"text":"fromJsonWithJson:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration\/fromJsonWithJson:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeAddressParserConfiguration":{"type":"topic","title":"SBSDKDeAddressParserConfiguration","abstract":[{"type":"text","text":"German Address Field validation configuration."},{"text":" ","type":"text"},{"type":"text","text":"This configuration does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"text":"Add to recognizer configuration to require German Address validation checks for specific document types.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration","navigatorTitle":[{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeAddressParserConfiguration/fromJsonWithJson:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration\/fromjsonwithjson:","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/title","value":"SBSDKDeAddressParserConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}