{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","title":"hash","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDeAddressParserConfiguration(py)hash","modules":[{"name":"ScanbotSDK"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration\/hash"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration\/hash","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeAddressParserConfiguration":{"type":"topic","title":"SBSDKDeAddressParserConfiguration","abstract":[{"type":"text","text":"German Address Field validation configuration."},{"text":" ","type":"text"},{"type":"text","text":"This configuration does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"text":"Add to recognizer configuration to require German Address validation checks for specific document types.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration","navigatorTitle":[{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeAddressParserConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeAddressParserConfiguration/hash":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdeaddressparserconfiguration\/hash","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeAddressParserConfiguration\/hash","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/title","value":"SBSDKDeAddressParserConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDeAddressParserConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeAddressParserConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDeAddressParserConfiguration"}]}]}]}