{"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder@SBSDKTextlineOrderLeftToRight","role":"symbol","roleHeading":"Case","title":"SBSDKTextlineOrder.leftToRight","navigatorTitle":[{"text":"SBSDKTextlineOrderLeftToRight","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftToRight","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"Columns are read from left-to-right order in top-bottom directional languages (Japanese, etc.)."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder\/leftToRight"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlineorder\/lefttoright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlineorder\/lefttoright"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftToRight"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextlineOrder":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextlineOrder"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTextlineOrder","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder","abstract":[{"type":"text","text":"An enum to describes the order of columns in top-to-bottom writing direction resp. of rows in left-right and right-left direction."}],"url":"\/documentation\/scanbotsdk\/sbsdktextlineorder","title":"SBSDKTextlineOrder","role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextlineOrder/leftToRight":{"type":"topic","title":"SBSDKTextlineOrder.leftToRight","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftToRight"}],"url":"\/documentation\/scanbotsdk\/sbsdktextlineorder\/lefttoright","kind":"symbol","abstract":[{"text":"Columns are read from left-to-right order in top-bottom directional languages (Japanese, etc.).","type":"text"}],"navigatorTitle":[{"text":"SBSDKTextlineOrderLeftToRight","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder\/leftToRight"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKTextlineOrderLeftToRight","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKTextlineOrderLeftToRight"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKTextlineOrderLeftToRight"}],"languages":["occ"]}]}},{"value":"SBSDKTextlineOrder","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextlineOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder~1leftToRight\/title","value":"SBSDKTextlineOrderLeftToRight"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder~1leftToRight\/fragments","value":[{"text":"SBSDKTextlineOrderLeftToRight","kind":"identifier"}],"op":"replace"}]}]}