{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder@SBSDKTextlineOrderRightToLeft","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextlineOrderRightToLeft"}],"title":"SBSDKTextlineOrder.rightToLeft","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rightToLeft","kind":"identifier"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"Columns are read from right-to-left order in top-bottom directional languages."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"rightToLeft","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextlineorder\/righttoleft"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlineorder\/righttoleft"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder\/rightToLeft","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextlineOrder":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextlineOrder"}],"title":"SBSDKTextlineOrder","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder","abstract":[{"type":"text","text":"An enum to describes the order of columns in top-to-bottom writing direction resp. of rows in left-right and right-left direction."}],"url":"\/documentation\/scanbotsdk\/sbsdktextlineorder","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKTextlineOrder","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextlineOrder/rightToLeft":{"abstract":[{"type":"text","text":"Columns are read from right-to-left order in top-bottom directional languages."}],"navigatorTitle":[{"text":"SBSDKTextlineOrderRightToLeft","kind":"identifier"}],"kind":"symbol","title":"SBSDKTextlineOrder.rightToLeft","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder\/rightToLeft","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktextlineorder\/righttoleft","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightToLeft","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKTextlineOrderRightToLeft","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKTextlineOrderRightToLeft","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKTextlineOrderRightToLeft","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKTextlineOrder","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTextlineOrder"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder~1rightToLeft\/title","value":"SBSDKTextlineOrderRightToLeft","op":"replace"},{"value":[{"text":"SBSDKTextlineOrderRightToLeft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder~1rightToLeft\/fragments"}]}]}