{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Rows are read from top-to-bottom order in left-to-right or right-to-left directional languages (English, etc.)."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"topToBottom","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextlineorder\/toptobottom"]},{"paths":["\/documentation\/scanbotsdk\/sbsdktextlineorder\/toptobottom"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder\/topToBottom"},"metadata":{"roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"topToBottom","kind":"identifier"}],"title":"SBSDKTextlineOrder.topToBottom","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKTextlineOrder@SBSDKTextlineOrderTopToBottom","navigatorTitle":[{"text":"SBSDKTextlineOrderTopToBottom","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextlineOrder/topToBottom":{"abstract":[{"text":"Rows are read from top-to-bottom order in left-to-right or right-to-left directional languages (English, etc.).","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdktextlineorder\/toptobottom","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder\/topToBottom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"topToBottom"}],"kind":"symbol","title":"SBSDKTextlineOrder.topToBottom","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKTextlineOrderTopToBottom","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextlineOrder":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextlineOrder"}],"abstract":[{"type":"text","text":"An enum to describes the order of columns in top-to-bottom writing direction resp. of rows in left-right and right-left direction."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextlineOrder"}],"title":"SBSDKTextlineOrder","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextlineOrder","url":"\/documentation\/scanbotsdk\/sbsdktextlineorder"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKTextlineOrderTopToBottom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"SBSDKTextlineOrderTopToBottom","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKTextlineOrderTopToBottom","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder~1topToBottom\/title","value":"SBSDKTextlineOrderTopToBottom"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder~1topToBottom\/fragments","value":[{"text":"SBSDKTextlineOrderTopToBottom","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/title","op":"replace","value":"SBSDKTextlineOrder"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/fragments","value":[{"text":"SBSDKTextlineOrder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextlineOrder\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTextlineOrder"}],"op":"replace"}]}]}