{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"baseURL"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The URL of the folder in which the new storage should be located."},{"type":"text","text":" "},{"type":"text","text":"If the folder does not exist, it is created. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" the new location will reside in the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation\/defaultURL","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"baseURL"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragelocation\/init(baseurl:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragelocation\/init(baseurl:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation"]]},"abstract":[{"type":"text","text":"Initializes the new storage location living at the given folder."}],"metadata":{"navigatorTitle":[{"text":"initWithBaseURL:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"baseURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?)"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation(im)initWithBaseURL:","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","title":"init(baseURL:)","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation\/init(baseURL:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation/init(baseURL:)":{"type":"topic","navigatorTitle":[{"text":"initWithBaseURL:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation\/init(baseurl:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"baseURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation\/init(baseURL:)","kind":"symbol","title":"init(baseURL:)","abstract":[{"type":"text","text":"Initializes the new storage location living at the given folder."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation/defaultURL":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation\/defaulturl","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"abstract":[{"text":"The default base URL for new storage locations.","type":"text"}],"navigatorTitle":[{"text":"defaultURL","kind":"identifier"}],"title":"defaultURL","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation\/defaultURL"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStorageLocation","kind":"identifier"}],"abstract":[{"text":"Descriptor and helper class for describing and creating a directory on the file system.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"title":"SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithBaseURL:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithBaseURL:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBaseURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"text":"baseURL","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithBaseURL:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation~1init(baseURL:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation~1init(baseURL:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBaseURL:"}]},{"value":"defaultURL","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation~1defaultURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"defaultURL"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation~1defaultURL\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/title","value":"SBSDKStorageLocation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/fragments","value":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"op":"replace"}]}]}