{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocument(im)initWithType:fields:children:confidence:confidenceWeight:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:fields:children:confidence:confidenceWeight:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"initWithType:fields:children:confidence:confidenceWeight:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"initWithType:fields:children:confidence:confidenceWeight:"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocument\/initWithType:fields:children:confidence:confidenceWeight:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocument"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentType","kind":"typeIdentifier","text":"SBSDKGenericDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentType"},{"kind":"text","text":" *) "},{"text":"type","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKGenericDocumentField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"fields","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"children:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKGenericDocument *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"children"},{"text":" ","kind":"text"},{"text":"confidence:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"confidence"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confidenceWeight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"confidenceWeight"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocument\/initwithtype:fields:children:confidence:confidenceweight:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocument/initWithType:fields:children:confidence:confidenceWeight:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:fields:children:confidence:confidenceWeight:","kind":"identifier"}],"abstract":[],"role":"symbol","title":"initWithType:fields:children:confidence:confidenceWeight:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithType:fields:children:confidence:confidenceWeight:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocument\/initWithType:fields:children:confidence:confidenceWeight:","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocument\/initwithtype:fields:children:confidence:confidenceweight:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocument":{"abstract":[{"type":"text","text":"Represents a document specifically used for checking purposes, inheriting properties and methods from "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocument","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocument","title":"SBSDKCheckDocument","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocument","navigatorTitle":[{"text":"SBSDKCheckDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentType":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"abstract":[{"text":"A generic documents type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentType","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenttype","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"title":"SBSDKGenericDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"abstract":[{"text":"Represents a generic document with fields and sub-documents used for document recognition.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"title":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocument\/title","op":"replace","value":"SBSDKCheckDocument"},{"value":[{"text":"SBSDKCheckDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocument\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentType\/title","value":"SBSDKGenericDocumentType"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}