{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementModeNone","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2AcknowledgementMode@SBSDKUI2AcknowledgementModeNone","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Case","title":"SBSDKUI2AcknowledgementMode.none","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/none","interfaceLanguage":"swift"},"abstract":[{"text":"The acknowledgement screen will be disabled, in effect never shown.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/none"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"title":"SBSDKUI2AcknowledgementMode","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines, after each page is snapped, whether the acknowledgment screen should be displayed or not."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode/none":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode\/none","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeNone"}],"role":"symbol","type":"topic","abstract":[{"text":"The acknowledgement screen will be disabled, in effect never shown.","type":"text"}],"title":"SBSDKUI2AcknowledgementMode.none","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode\/none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2AcknowledgementModeNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeNone"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKUI2AcknowledgementModeNone","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/title","op":"replace","value":"SBSDKUI2AcknowledgementMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1none\/title","value":"SBSDKUI2AcknowledgementModeNone","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode~1none\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementModeNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}