{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewScreenConfiguration"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewScreenConfiguration\/init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"enabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"?reviewScreenTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)), ","kind":"text"},{"kind":"externalParam","text":"topBarMoreButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2IconButton(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\", isArgb: false),\n                                       accessibilityDescription: \"?accessibilityDescriptionReviewMoreButton\"), "},{"kind":"externalParam","text":"topBarBackButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?reviewTopBarBackButtonTitle\",\n                                                                                            accessibilityDescription: \"?accessibilityDescriptionReviewTopBarBackButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 0.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)), ","kind":"text"},{"text":"morePopup","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewMorePopupMenu","text":"SBSDKUI2ReviewMorePopupMenu","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu"},{"kind":"text","text":" = SBSDKUI2ReviewMorePopupMenu(), "},{"text":"zoomButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton"},{"kind":"text","text":" = SBSDKUI2RoundButton(accessibilityDescription: \"?accessibilityDescriptionReviewZoomButton\",\n                                        backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                       isArgb: false),\n                                        foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                       isArgb: false)), "},{"kind":"externalParam","text":"zoomOverlay"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ZoomOverlay","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ZoomOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ZoomOverlay","kind":"typeIdentifier"},{"text":" = SBSDKUI2ZoomOverlay(), ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\", isArgb: false), "},{"kind":"externalParam","text":"bottomBar"},{"kind":"text","text":": "},{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration"},{"kind":"text","text":" = SBSDKUI2ReviewBottomBarConfiguration(), "},{"kind":"externalParam","text":"switchNextPageButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton"},{"kind":"text","text":" = SBSDKUI2IconButton(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\", isArgb: false),\n                                       accessibilityDescription: \"?accessibilityDescriptionReviewNextPageButton\"), "},{"kind":"externalParam","text":"switchPreviousPageButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":" = SBSDKUI2IconButton(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\", isArgb: false),\n                                       accessibilityDescription: \"?accessibilityDescriptionReviewPreviousPageButton\"), ","kind":"text"},{"kind":"externalParam","text":"pageCounter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration"},{"text":" = SBSDKUI2UserGuidanceConfiguration(title: SBSDKUI2StyledText(text: \"?reviewScreenPageCount\",\n                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                     isArgb: false)),\n                                                      background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                   isArgb: false),\n                                                                                          strokeWidth: 0.0)), ","kind":"text"},{"text":"deleteAllPagesAlertDialog","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":" = SBSDKUI2ScanbotAlertDialog(title: SBSDKUI2StyledText(text: \"?reviewDeleteAllPagesAlertTitle\",\n                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                              isArgb: false)),\n                                               subtitle: SBSDKUI2StyledText(text: \"?reviewDeleteAllPagesAlertSubtitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                 isArgb: false)),\n                                               okButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeleteAllPagesAlertDeleteButtonTitle\",\n                                                                                     accessibilityDescription: \"?accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 0.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                              isArgb: false))),\n                                               actionButton: SBSDKUI2ButtonConfiguration(visible: false),\n                                               cancelButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeleteAllPagesAlertCancelButtonTitle\",\n                                                                                         accessibilityDescription: \"?accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton\",\n                                                                                         background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                             strokeWidth: 0.0),\n                                                                                         foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false)))), ","kind":"text"},{"text":"deletePageAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" = SBSDKUI2ScanbotAlertDialog(title: SBSDKUI2StyledText(text: \"?reviewDeletePageAlertTitle\",\n                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                              isArgb: false)),\n                                               subtitle: SBSDKUI2StyledText(text: \"?reviewDeletePageAlertSubTitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                 isArgb: false)),\n                                               okButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeletePageAlertConfirmButtonTitle\",\n                                                                                     accessibilityDescription: \"?accessibilityDescriptionReviewDeletePageAlertConfirmButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 0.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                              isArgb: false))),\n                                               actionButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeletePageAlertDeleteRetakeButtonTitle\",\n                                                                                         accessibilityDescription: \"?accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton\",\n                                                                                         background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                             strokeWidth: 0.0),\n                                                                                         foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false))),\n                                               cancelButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeletePageAlertCancelButtonTitle\",\n                                                                                         accessibilityDescription: \"?accessibilityDescriptionReviewDeletePageAlertCancelButton\",\n                                                                                         background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                             strokeWidth: 0.0),\n                                                                                         foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false)))))","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2reviewscreenconfiguration\/init(enabled:topbartitle:topbarmorebutton:topbarbackbutton:morepopup:zoombutton:zoomoverlay:backgroundcolor:bottombar:switchnextpagebutton:switchpreviouspagebutton:pagecounter:deleteallpagesalertdialog:deletepagealertdialog:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2reviewscreenconfiguration\/init(enabled:topbartitle:topbarmorebutton:topbarbackbutton:morepopup:zoombutton:zoomoverlay:backgroundcolor:bottombar:switchnextpagebutton:switchpreviouspagebutton:pagecounter:deleteallpagesalertdialog:deletepagealertdialog:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewScreenConfiguration(im)initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","modules":[{"name":"ScanbotSDK"}],"title":"init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarMoreButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarBackButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"morePopup"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu","kind":"typeIdentifier","text":"SBSDKUI2ReviewMorePopupMenu"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2RoundButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"zoomOverlay"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ZoomOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ZoomOverlay"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"bottomBar","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ReviewBottomBarConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"switchNextPageButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"switchPreviousPageButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageCounter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"},{"text":", ","kind":"text"},{"text":"deleteAllPagesAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":", "},{"text":"deletePageAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":")","kind":"text"}],"symbolKind":"init"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewMorePopupMenu":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ReviewMorePopupMenu"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ReviewMorePopupMenu"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewMorePopupMenu","url":"\/documentation\/scanbotsdk\/sbsdkui2reviewmorepopupmenu","kind":"symbol","title":"SBSDKUI2ReviewMorePopupMenu","abstract":[{"type":"text","text":"Configuration of the ‘more’ popup menu for the review screen."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","type":"topic","abstract":[],"title":"SBSDKUI2Color","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2RoundButton":{"title":"SBSDKUI2RoundButton","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the round button.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2roundbutton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2RoundButton"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanbotAlertDialog":{"navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"type":"topic","title":"SBSDKUI2ScanbotAlertDialog","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","role":"symbol","abstract":[{"type":"text","text":"Configuration of the the standard alert dialog."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2scanbotalertdialog"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewBottomBarConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the bottom bar for the review screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2reviewbottombarconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration","title":"SBSDKUI2ReviewBottomBarConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"title":"SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","abstract":[{"text":"Button configuration.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"type":"topic","title":"SBSDKUI2ButtonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"title":"SBSDKUI2UserGuidanceConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconButton":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the icon appearance.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconButton"}],"title":"SBSDKUI2IconButton","url":"\/documentation\/scanbotsdk\/sbsdkui2iconbutton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconButton"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewScreenConfiguration":{"abstract":[{"text":"Configuration of the screen for reviewing the scanned pages.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2reviewscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewScreenConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ReviewScreenConfiguration"}],"type":"topic","title":"SBSDKUI2ReviewScreenConfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2ReviewScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewScreenConfiguration/init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBarTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"text":"topBarMoreButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"},{"text":", ","kind":"text"},{"text":"topBarBackButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"text":"morePopup","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu","text":"SBSDKUI2ReviewMorePopupMenu"},{"text":", ","kind":"text"},{"text":"zoomButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ZoomOverlay","text":"SBSDKUI2ZoomOverlay"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"bottomBar","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration","text":"SBSDKUI2ReviewBottomBarConfiguration"},{"text":", ","kind":"text"},{"text":"switchNextPageButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton"},{"kind":"text","text":", "},{"text":"switchPreviousPageButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageCounter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deleteAllPagesAlertDialog"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":", "},{"text":"deletePageAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2reviewscreenconfiguration\/init(enabled:topbartitle:topbarmorebutton:topbarbackbutton:morepopup:zoombutton:zoomoverlay:backgroundcolor:bottombar:switchnextpagebutton:switchpreviouspagebutton:pagecounter:deleteallpagesalertdialog:deletepagealertdialog:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewScreenConfiguration\/init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)","type":"topic","role":"symbol","abstract":[],"title":"init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ZoomOverlay":{"title":"SBSDKUI2ZoomOverlay","url":"\/documentation\/scanbotsdk\/sbsdkui2zoomoverlay","type":"topic","abstract":[{"type":"text","text":"Configuration of the zoom overlay for the review screen."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ZoomOverlay","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ZoomOverlay"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ZoomOverlay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarTitle"},{"text":" ","kind":"text"},{"text":"topBarMoreButton:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarMoreButton"},{"text":" ","kind":"text"},{"text":"topBarBackButton:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"topBarBackButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"morePopup:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ReviewMorePopupMenu","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewMorePopupMenu","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"morePopup"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomButton:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier","text":"SBSDKUI2RoundButton"},{"kind":"text","text":" *) "},{"text":"zoomButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"zoomOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ZoomOverlay","text":"SBSDKUI2ZoomOverlay","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ZoomOverlay"},{"text":" *) ","kind":"text"},{"text":"zoomOverlay","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"backgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomBar:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ReviewBottomBarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bottomBar"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchNextPageButton:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","kind":"typeIdentifier","text":"SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"switchNextPageButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchPreviousPageButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"switchPreviousPageButton"},{"text":" ","kind":"text"},{"text":"pageCounter:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"text":"pageCounter","kind":"internalParam"},{"kind":"text","text":" "},{"text":"deleteAllPagesAlertDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deleteAllPagesAlertDialog"},{"kind":"text","text":" "},{"text":"deletePageAlertDialog:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deletePageAlertDialog"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKUI2ReviewMorePopupMenu","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewMorePopupMenu\/title"},{"op":"replace","value":[{"text":"SBSDKUI2ReviewMorePopupMenu","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewMorePopupMenu\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/title","op":"replace","value":"SBSDKUI2RoundButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/fragments","op":"replace","value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/title","value":"SBSDKUI2ScanbotAlertDialog"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","op":"replace","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]},{"value":"SBSDKUI2ReviewBottomBarConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title","value":"SBSDKUI2UserGuidanceConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","op":"replace"},{"op":"replace","value":"SBSDKUI2IconButton","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}]},{"value":"SBSDKUI2ReviewScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewScreenConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2ReviewScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewScreenConfiguration\/fragments"},{"op":"replace","value":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewScreenConfiguration~1init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewScreenConfiguration~1init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ZoomOverlay\/title","value":"SBSDKUI2ZoomOverlay"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ZoomOverlay\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ZoomOverlay"}]}]}]}