{"metadata":{"role":"symbol","title":"imageEditingViewControllerToolbarStyle(_:)","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarStyle","text":"UIBarStyle"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"}],"required":true,"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKImageEditingViewControllerDelegate(im)imageEditingViewControllerToolbarStyle:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarStyle(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbarstyle(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbarstyle(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerToolbarStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"},{"text":") -> ","kind":"text"},{"text":"UIBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarStyle"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"editingViewController","content":[{"inlineContent":[{"type":"text","text":"The calling "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"UIBarStyle","type":"codeVoice"},{"type":"text","text":" for the bottom toolbar."}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate"]]},"abstract":[{"type":"text","text":"Asks the delegate for a "},{"code":"UIBarStyle","type":"codeVoice"},{"type":"text","text":" for the bottom toolbar."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show and edit an image."}],"role":"symbol","title":"SBSDKImageEditingViewController","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate":{"navigatorTitle":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A delegate protocol to inform an object about changes in "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"title":"SBSDKImageEditingViewControllerDelegate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerToolbarStyle(_:)":{"required":true,"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollertoolbarstyle(_:)","abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarStyle"},{"type":"text","text":" for the bottom toolbar."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBarStyle","preciseIdentifier":"c:@E@UIBarStyle"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerToolbarStyle(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"}],"title":"imageEditingViewControllerToolbarStyle(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"imageEditingViewControllerToolbarStyle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIBarStyle","preciseIdentifier":"c:@E@UIBarStyle"},{"kind":"text","text":") "},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"editingViewController"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"editingViewController","content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UIBarStyle"},{"type":"text","text":" for the bottom toolbar."}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/title","value":"SBSDKImageEditingViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/fragments","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/navigatorTitle","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/title","value":"SBSDKImageEditingViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/fragments","value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarStyle(_:)\/title","value":"imageEditingViewControllerToolbarStyle:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerToolbarStyle(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerToolbarStyle:"}]}]}]}