{"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode@SBSDKCheckDocumentDetectionModeDetectAndCropDocument","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectAndCropDocument","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument","kind":"identifier"}],"role":"symbol","title":"SBSDKCheckDocumentDetectionMode.detectAndCropDocument"},"abstract":[{"text":"Document scanner will be used to locate the complete check in the input image. The documentDetectionResult","type":"text"},{"text":" ","type":"text"},{"text":"result field will contain the result of document detection. The croppedImage result field will contain a crop of","type":"text"},{"text":" ","type":"text"},{"text":"the entire check.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectAndCropDocument","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectAndCropDocument"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/detectandcropdocument"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/detectandcropdocument"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","type":"topic","abstract":[{"text":"Check document detection and extraction mode.","type":"text"}],"title":"SBSDKCheckDocumentDetectionMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode/detectAndCropDocument":{"type":"topic","title":"SBSDKCheckDocumentDetectionMode.detectAndCropDocument","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectAndCropDocument","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectAndCropDocument","abstract":[{"type":"text","text":"Document scanner will be used to locate the complete check in the input image. The documentDetectionResult"},{"type":"text","text":" "},{"type":"text","text":"result field will contain the result of document detection. The croppedImage result field will contain a crop of"},{"type":"text","text":" "},{"type":"text","text":"the entire check."}],"navigatorTitle":[{"text":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/detectandcropdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/title","value":"SBSDKCheckDocumentDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1detectAndCropDocument\/title","value":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1detectAndCropDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument"}]}]}]}