{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection\/leftToRight","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftToRight"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkwritingdirection\/lefttoright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkwritingdirection\/lefttoright"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKWritingDirection@SBSDKWritingDirectionLeftToRight","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKWritingDirectionLeftToRight","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"leftToRight","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKWritingDirection.leftToRight"},"abstract":[{"text":"The text is read from left to right (English, etc.).","type":"text"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWritingDirection/leftToRight":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection\/leftToRight","navigatorTitle":[{"text":"SBSDKWritingDirectionLeftToRight","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftToRight"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkwritingdirection\/lefttoright","role":"symbol","title":"SBSDKWritingDirection.leftToRight","abstract":[{"text":"The text is read from left to right (English, etc.).","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWritingDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKWritingDirection"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKWritingDirection"}],"title":"SBSDKWritingDirection","abstract":[{"type":"text","text":"An enum to describe the reading direction of the text independently from its orientation."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwritingdirection","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKWritingDirectionLeftToRight"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKWritingDirectionLeftToRight"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKWritingDirectionLeftToRight"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKWritingDirectionLeftToRight","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection~1leftToRight\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKWritingDirectionLeftToRight"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection~1leftToRight\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/title","value":"SBSDKWritingDirection"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/fragments","value":[{"text":"SBSDKWritingDirection","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}