{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection\/rightToLeft","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightToLeft","kind":"identifier"}],"role":"symbol","symbolKind":"case","title":"SBSDKWritingDirection.rightToLeft","navigatorTitle":[{"kind":"identifier","text":"SBSDKWritingDirectionRightToLeft"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKWritingDirection@SBSDKWritingDirectionRightToLeft","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightToLeft","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"The text is read from right to left (Arabian, Hebrew)."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkwritingdirection\/righttoleft"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkwritingdirection\/righttoleft"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWritingDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKWritingDirection"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKWritingDirection"}],"title":"SBSDKWritingDirection","abstract":[{"type":"text","text":"An enum to describe the reading direction of the text independently from its orientation."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkwritingdirection","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWritingDirection/rightToLeft":{"navigatorTitle":[{"text":"SBSDKWritingDirectionRightToLeft","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rightToLeft","kind":"identifier"}],"title":"SBSDKWritingDirection.rightToLeft","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWritingDirection\/rightToLeft","url":"\/documentation\/scanbotsdk\/sbsdkwritingdirection\/righttoleft","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The text is read from right to left (Arabian, Hebrew)."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKWritingDirectionRightToLeft","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKWritingDirectionRightToLeft","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKWritingDirectionRightToLeft","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/title","op":"replace","value":"SBSDKWritingDirection"},{"value":[{"text":"SBSDKWritingDirection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection~1rightToLeft\/title","value":"SBSDKWritingDirectionRightToLeft","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWritingDirection~1rightToLeft\/fragments","value":[{"kind":"identifier","text":"SBSDKWritingDirectionRightToLeft"}]}]}]}