{"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygonLayer(im)actionForKey:","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"actionForKey:","kind":"identifier"}],"title":"actionForKey:","navigatorTitle":[{"kind":"identifier","text":"actionForKey:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonLayer"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonLayer\/actionForKey:"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygonlayer\/actionforkey:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)CAAction","text":"id<CAAction>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"actionForKey:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygonLayer/actionForKey:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"actionForKey:"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygonlayer\/actionforkey:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonLayer\/actionForKey:","title":"actionForKey:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"actionForKey:"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygonLayer":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygonlayer","kind":"symbol","title":"SBSDKPolygonLayer","type":"topic","abstract":[{"type":"text","text":"A "},{"code":"CAShapeLayer","type":"codeVoice"},{"text":" subclass that is used to draw bezier paths with fluid animation.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonLayer","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPolygonLayer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonLayer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonLayer\/title","value":"SBSDKPolygonLayer"},{"value":[{"kind":"identifier","text":"SBSDKPolygonLayer"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonLayer\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPolygonLayer"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonLayer\/navigatorTitle"}]}]}