{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate\/barcodesbatchscannerviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate\/barcodesbatchscannerviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Informs the delegate that the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":" has been cancelled and dismissed."}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodesBatchScannerViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIBarcodesBatchScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"barcodesBatchScannerViewControllerDidCancel:","kind":"identifier"}],"roleHeading":"Instance Method","platforms":[],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodesBatchScannerViewControllerDelegate(im)barcodesBatchScannerViewControllerDidCancel:","title":"barcodesBatchScannerViewControllerDidCancel(_:)","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(barcodesBatchScannerViewControllerDidCancel:) "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodesBatchScannerViewControllerDidCancel"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"text":"SBSDKUIBarcodesBatchScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","type":"reference"},{"type":"text","text":" that did dismiss."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional."}]}]}],"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewControllerDidCancel(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewControllerDelegate":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"}],"deprecated":true,"abstract":[{"text":"Delegate protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate","title":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"abstract":[{"text":"A highly customizable camera-based view controller to detect barcodes batches.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","deprecated":true,"role":"symbol","type":"topic","kind":"symbol","title":"SBSDKUIBarcodesBatchScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewControllerDelegate/barcodesBatchScannerViewControllerDidCancel(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewControllerDidCancel(_:)","deprecated":true,"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"barcodesBatchScannerViewControllerDidCancel:"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate\/barcodesbatchscannerviewcontrollerdidcancel(_:)","abstract":[{"type":"text","text":"Informs the delegate that the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","isActive":true},{"text":" has been cancelled and dismissed.","type":"text"}],"title":"barcodesBatchScannerViewControllerDidCancel(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodesBatchScannerViewControllerDidCancel"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController","text":"SBSDKUIBarcodesBatchScannerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"barcodesBatchScannerViewControllerDidCancel:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"barcodesBatchScannerViewControllerDidCancel:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"barcodesBatchScannerViewControllerDidCancel:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIBarcodesBatchScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate~1barcodesBatchScannerViewControllerDidCancel(_:)\/title","op":"replace","value":"barcodesBatchScannerViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate~1barcodesBatchScannerViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodesBatchScannerViewControllerDidCancel:"}]}]}]}