{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/fileEncryptionMode","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileEncryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAESEncrypterMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAESEncrypterMode"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/fileencryptionmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/fileencryptionmode"]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration(py)fileEncryptionMode","title":"fileEncryptionMode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileEncryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAESEncrypterMode","text":"SBSDKAESEncrypterMode","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"fileEncryptionMode","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration"]]},"sections":[],"abstract":[{"text":"The encryption mode for stored files. Defaults to ","type":"text"},{"code":".AES128","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration":{"abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration","role":"symbol","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"title":"ScanbotSDKConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration/fileEncryptionMode":{"url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/fileencryptionmode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileEncryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAESEncrypterMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAESEncrypterMode"}],"abstract":[{"type":"text","text":"The encryption mode for stored files. Defaults to "},{"type":"codeVoice","code":".AES128"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"fileEncryptionMode","kind":"identifier"}],"title":"fileEncryptionMode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/fileEncryptionMode","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypter":{"type":"topic","title":"SBSDKAESEncrypter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter","abstract":[{"text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypterMode":{"abstract":[{"text":"An enum containing the available encryption modes for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypterMode","type":"topic","navigatorTitle":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"title":"SBSDKAESEncrypterMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencryptermode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fileEncryptionMode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"fileEncryptionMode"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypterMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAESEncrypterMode"},{"text":" ","kind":"text"},{"text":"fileEncryptionMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/title","op":"replace","value":"ScanbotSDKConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","op":"replace","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1fileEncryptionMode\/title","op":"replace","value":"fileEncryptionMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1fileEncryptionMode\/fragments","op":"replace","value":[{"text":"fileEncryptionMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/title","op":"replace","value":"SBSDKAESEncrypter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypterMode\/title","op":"replace","value":"SBSDKAESEncrypterMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypterMode\/fragments","op":"replace","value":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypterMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}]}]}]}