{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration"]]},"abstract":[{"type":"text","text":"A Boolean value that determines whether the status bar is shown on scanning screens. Defaults to "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/shouldshowstatusbaronscanningscreens"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/shouldshowstatusbaronscanningscreens"]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration(py)shouldShowStatusBarOnScanningScreens","title":"shouldShowStatusBarOnScanningScreens","navigatorTitle":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/shouldShowStatusBarOnScanningScreens"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration/shouldShowStatusBarOnScanningScreens":{"url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/shouldshowstatusbaronscanningscreens","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/shouldShowStatusBarOnScanningScreens","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"shouldShowStatusBarOnScanningScreens","navigatorTitle":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"abstract":[{"text":"A Boolean value that determines whether the status bar is shown on scanning screens. Defaults to ","type":"text"},{"code":"False","type":"codeVoice"},{"text":".","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration":{"abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration","role":"symbol","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"title":"ScanbotSDKConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shouldShowStatusBarOnScanningScreens","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldShowStatusBarOnScanningScreens"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"shouldShowStatusBarOnScanningScreens","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1shouldShowStatusBarOnScanningScreens\/title"},{"value":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1shouldShowStatusBarOnScanningScreens\/fragments"},{"value":"ScanbotSDKConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/title"},{"value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}