{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration"]]},"sections":[],"metadata":{"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setVisibility","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentFieldDisplayState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState"},{"kind":"text","text":", "},{"text":"forFieldType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotSDK"}],"title":"setVisibility(_:forFieldType:)","navigatorTitle":[{"text":"setVisibility:forFieldType:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorUIConfiguration(im)setVisibility:forFieldType:","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration\/setVisibility(_:forFieldType:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(setVisibility:forFieldType:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVisibility"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"visibility"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState","text":"SBSDKGenericDocumentFieldDisplayState","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forFieldType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fieldType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"visibility","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The visibility state for the given field type."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the field."}]}],"name":"fieldType"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/setvisibility(_:forfieldtype:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/setvisibility(_:forfieldtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A convenience method to set the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState","type":"reference","isActive":true},{"type":"text","text":" for the given field type."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorUIConfiguration/setVisibility(_:forFieldType:)":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/setvisibility(_:forfieldtype:)","role":"symbol","abstract":[{"type":"text","text":"A convenience method to set the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState","isActive":true,"type":"reference"},{"type":"text","text":" for the given field type."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVisibility","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState","text":"SBSDKGenericDocumentFieldDisplayState","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forFieldType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"setVisibility(_:forFieldType:)","navigatorTitle":[{"text":"setVisibility:forFieldType:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration\/setVisibility(_:forFieldType:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDisplayState":{"abstract":[{"text":"The generic document fields display status. Whether a field is shown or hidden in the user interface.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddisplaystate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldDisplayState"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState","title":"SBSDKGenericDocumentFieldDisplayState"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorUIConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration","role":"symbol","abstract":[{"type":"text","text":"The configuration for the user interface of the RTU-UI document data extractor screen."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}],"title":"SBSDKUIDocumentDataExtractorUIConfiguration","navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"setVisibility:forFieldType:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"setVisibility:forFieldType:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"setVisibility:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState","text":"SBSDKGenericDocumentFieldDisplayState","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState"},{"text":" *) ","kind":"text"},{"text":"visibility","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"forFieldType:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fieldType"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The visibility state for the given field type."}],"type":"paragraph"}],"name":"visibility"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The type of the field.","type":"text"}]}],"name":"fieldType"}]}},{"value":"setVisibility:forFieldType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration~1setVisibility(_:forFieldType:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setVisibility:forFieldType:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration~1setVisibility(_:forFieldType:)\/fragments","op":"replace"},{"value":"SBSDKGenericDocumentFieldDisplayState","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldDisplayState"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/title","value":"SBSDKUIDocumentDataExtractorUIConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/fragments"},{"value":[{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/navigatorTitle","op":"replace"}]}]}