{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/placeOfOperationNumber","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeOfOperationNumber"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeOfOperationNumber","kind":"identifier"}],"role":"symbol","title":"SBSDKMedicalCertificatePatientInfoFieldType.placeOfOperationNumber","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificatePatientInfoFieldType@SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber","roleHeading":"Case"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/placeofoperationnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/placeofoperationnumber"]}],"sections":[],"abstract":[{"type":"text","text":"Number of the place of operation (Betriebsstätten-Nr.)."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/placeOfOperationNumber":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber"}],"title":"SBSDKMedicalCertificatePatientInfoFieldType.placeOfOperationNumber","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeOfOperationNumber"}],"abstract":[{"type":"text","text":"Number of the place of operation (Betriebsstätten-Nr.)."}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/placeofoperationnumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/placeOfOperationNumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType","title":"SBSDKMedicalCertificatePatientInfoFieldType","abstract":[{"type":"text","text":"Type of a field in the patient info box."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1placeOfOperationNumber\/title"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypePlaceOfOperationNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1placeOfOperationNumber\/fragments"},{"op":"replace","value":"SBSDKMedicalCertificatePatientInfoFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/title"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/fragments"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/navigatorTitle"}]}]}