{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"drawTextInRect:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel\/drawTextInRect:","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","title":"drawTextInRect:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"drawTextInRect:"}],"navigatorTitle":[{"text":"drawTextInRect:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel(im)drawTextInRect:","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdetectionstatuslabel\/drawtextinrect:"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDetectionStatusLabel":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"title":"SBSDKDetectionStatusLabel","navigatorTitle":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdetectionstatuslabel","kind":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":" subclass with rounded corners and content insets to display the status of the current document detection result."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDetectionStatusLabel/drawTextInRect:":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel\/drawTextInRect:","navigatorTitle":[{"text":"drawTextInRect:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdetectionstatuslabel\/drawtextinrect:","title":"drawTextInRect:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"drawTextInRect:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDetectionStatusLabel\/title","value":"SBSDKDetectionStatusLabel"},{"value":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDetectionStatusLabel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDetectionStatusLabel\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}]}]}]}