{"metadata":{"title":"SBSDKCapturePhotoQualityPrioritization.quality","symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCapturePhotoQualityPrioritization@SBSDKCapturePhotoQualityPrioritizationQuality","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationQuality"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"}],"role":"symbol","roleHeading":"Case"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/quality"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/quality"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Captures a still image with the best possible quality in terms of noise, frozen motion and detail in low light."},{"type":"text","text":" "},{"text":"The speed of the capturing might be significantly reduced.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/quality"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/quality":{"type":"topic","title":"SBSDKCapturePhotoQualityPrioritization.quality","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritizationQuality","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/quality","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/quality","abstract":[{"type":"text","text":"Captures a still image with the best possible quality in terms of noise, frozen motion and detail in low light."},{"text":" ","type":"text"},{"text":"The speed of the capturing might be significantly reduced.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization":{"type":"topic","title":"SBSDKCapturePhotoQualityPrioritization","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization","abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCapturePhotoQualityPrioritizationQuality"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"SBSDKCapturePhotoQualityPrioritizationQuality","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKCapturePhotoQualityPrioritizationQuality","kind":"identifier"}]}],"kind":"declarations"}},{"value":"SBSDKCapturePhotoQualityPrioritizationQuality","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1quality\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKCapturePhotoQualityPrioritizationQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1quality\/fragments"},{"value":"SBSDKCapturePhotoQualityPrioritization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization\/fragments","value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}