{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(dismiss:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"text":"cancelled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"cancelled","content":[{"type":"paragraph","inlineContent":[{"text":"Whether the receiver was cancelled or finished.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"If the receiver is the ","type":"text"},{"type":"codeVoice","code":"topViewController"},{"type":"text","text":" of a "},{"type":"codeVoice","code":"UINavigationController"},{"text":" this method pops the receiver from the navigation stack. If the receiver is presented modally, it is dismissed.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller\/dismiss(cancelled:)"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller\/dismiss(cancelled:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController"]]},"abstract":[{"type":"text","text":"Dismisses the receiver if possible. Subclasses should override here and call its delegates."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","title":"dismiss(cancelled:)","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIViewController(im)dismiss:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"kind":"text","text":"("},{"text":"cancelled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"dismiss:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController\/dismiss(cancelled:)"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewController/dismiss(cancelled:)":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller\/dismiss(cancelled:)","navigatorTitle":[{"text":"dismiss:","kind":"identifier"}],"title":"dismiss(cancelled:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cancelled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController\/dismiss(cancelled:)","abstract":[{"text":"Dismisses the receiver if possible. Subclasses should override here and call its delegates.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewController"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","type":"topic","role":"symbol","title":"SBSDKUIViewController","abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"dismiss:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dismiss:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"dismiss:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cancelled"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController~1dismiss(cancelled:)\/title","value":"dismiss:"},{"value":[{"text":"- ","kind":"text"},{"text":"dismiss:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController~1dismiss(cancelled:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/title","op":"replace","value":"SBSDKUIViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}