{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode\/pageCounter","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"pageCounter","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PagePreviewMode(py)pageCounter","navigatorTitle":[{"kind":"identifier","text":"pageCounter"}],"symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageCounter","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageCounter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","kind":"typeIdentifier","text":"SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode\/pagecounter"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode\/pagecounter"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode"]]},"abstract":[{"type":"text","text":"Configuration of the page counter icon."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BadgeStyle":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the round button.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2badgestyle","role":"symbol","title":"SBSDKUI2BadgeStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PagePreviewMode":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode","title":"SBSDKUI2PagePreviewMode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PagePreviewMode","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PagePreviewMode"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the ‘preview’ button in ‘page preview mode’."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PagePreviewMode/pageCounter":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode\/pageCounter","title":"pageCounter","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageCounter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","text":"SBSDKUI2BadgeStyle","kind":"typeIdentifier"}],"abstract":[{"text":"Configuration of the page counter icon.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode\/pagecounter","navigatorTitle":[{"kind":"identifier","text":"pageCounter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"pageCounter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pageCounter"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BadgeStyle","kind":"typeIdentifier","text":"SBSDKUI2BadgeStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BadgeStyle"},{"text":" * ","kind":"text"},{"text":"pageCounter","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2BadgeStyle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BadgeStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BadgeStyle"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode\/title","value":"SBSDKUI2PagePreviewMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode\/fragments","value":[{"text":"SBSDKUI2PagePreviewMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"pageCounter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode~1pageCounter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode~1pageCounter\/fragments","value":[{"kind":"identifier","text":"pageCounter"}]}]}]}