{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode\/toJson()","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"toJson"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PagePreviewMode(im)toJson","title":"toJson()","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode"]]},"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode\/tojson()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode\/tojson()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PagePreviewMode/toJson()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode\/toJson()","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode\/tojson()","role":"symbol","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"kind":"symbol","type":"topic","title":"toJson()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PagePreviewMode":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PagePreviewMode","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2pagepreviewmode","abstract":[{"text":"Configuration of the ‘preview’ button in ‘page preview mode’.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PagePreviewMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PagePreviewMode","kind":"identifier"}],"title":"SBSDKUI2PagePreviewMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"toJson","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode~1toJson()\/title","value":"toJson"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode~1toJson()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode\/title","op":"replace","value":"SBSDKUI2PagePreviewMode"},{"value":[{"kind":"identifier","text":"SBSDKUI2PagePreviewMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PagePreviewMode\/fragments"}]}]}