{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FinderStrokedStyle(im)copyWithZone:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","title":"copyWithZone:","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderStrokedStyle\/copyWithZone:"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2finderstrokedstyle\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderStrokedStyle"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FinderStrokedStyle/copyWithZone:":{"kind":"symbol","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2finderstrokedstyle\/copywithzone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderStrokedStyle\/copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FinderStrokedStyle":{"type":"topic","title":"SBSDKUI2FinderStrokedStyle","abstract":[{"text":"A variant of the viewfinder displaying a full outline of the scanning area.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderStrokedStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FinderStrokedStyle"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2finderstrokedstyle","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FinderStrokedStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderStrokedStyle\/title","value":"SBSDKUI2FinderStrokedStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderStrokedStyle\/fragments","value":[{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderStrokedStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2FinderStrokedStyle"}]}]}]}