{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2finderstrokedstyle\/isequal:"]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","title":"isEqual:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FinderStrokedStyle(im)isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderStrokedStyle\/isEqual:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderStrokedStyle"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FinderStrokedStyle":{"type":"topic","title":"SBSDKUI2FinderStrokedStyle","abstract":[{"text":"A variant of the viewfinder displaying a full outline of the scanning area.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderStrokedStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FinderStrokedStyle"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2finderstrokedstyle","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FinderStrokedStyle"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FinderStrokedStyle/isEqual:":{"kind":"symbol","abstract":[],"role":"symbol","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderStrokedStyle\/isEqual:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2finderstrokedstyle\/isequal:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderStrokedStyle\/title","op":"replace","value":"SBSDKUI2FinderStrokedStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderStrokedStyle\/fragments","op":"replace","value":[{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderStrokedStyle\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2FinderStrokedStyle","kind":"identifier"}]}]}]}