{"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultStatusBarStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotSDKConfiguration(py)defaultStatusBarStyle","navigatorTitle":[{"text":"defaultStatusBarStyle","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"defaultStatusBarStyle","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"abstract":[{"text":"The default status bar style for scanning screens. Defaults to ","type":"text"},{"type":"codeVoice","code":".lightContent"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/defaultStatusBarStyle","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/defaultstatusbarstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/defaultstatusbarstyle"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration/defaultStatusBarStyle":{"abstract":[{"text":"The default status bar style for scanning screens. Defaults to ","type":"text"},{"type":"codeVoice","code":".lightContent"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration\/defaultstatusbarstyle","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultStatusBarStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIStatusBarStyle","kind":"typeIdentifier","text":"UIStatusBarStyle"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration\/defaultStatusBarStyle","navigatorTitle":[{"text":"defaultStatusBarStyle","kind":"identifier"}],"title":"defaultStatusBarStyle"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotSDKConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotSDKConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/scanbotsdkconfiguration","title":"ScanbotSDKConfiguration","abstract":[{"code":"ScanbotSDKConfiguration","type":"codeVoice"},{"type":"text","text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"defaultStatusBarStyle","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultStatusBarStyle"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"text":" ","kind":"text"},{"text":"defaultStatusBarStyle","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1defaultStatusBarStyle\/title","op":"replace","value":"defaultStatusBarStyle"},{"op":"replace","value":[{"kind":"identifier","text":"defaultStatusBarStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration~1defaultStatusBarStyle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/title","value":"ScanbotSDKConfiguration","op":"replace"},{"value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"op":"replace"}]}]}