{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedocumentfieldtype\/firstname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedocumentfieldtype\/firstname"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDocumentFieldType\/firstName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The first name."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"title":"SBSDKMedicalCertificateDocumentFieldType.firstName","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateDocumentFieldType@SBSDKMedicalCertificateDocumentFieldTypeFirstName","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDocumentFieldType/firstName":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType.firstName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"abstract":[{"type":"text","text":"The first name."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDocumentFieldType\/firstName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedocumentfieldtype\/firstname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDocumentFieldType":{"role":"symbol","title":"SBSDKMedicalCertificateDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}],"abstract":[{"type":"text","text":"The medical certificate document field types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedocumentfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDocumentFieldType~1firstName\/title","value":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDocumentFieldType~1firstName\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldTypeFirstName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDocumentFieldType\/title","value":"SBSDKMedicalCertificateDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}