{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2CreditCardScanningProgressConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanningProgressConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscanningprogressconfiguration\/fromjsonwithjson:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration\/fromJsonWithJson:"},"metadata":{"title":"fromJsonWithJson:","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanningProgressConfiguration(cm)fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"roleHeading":"Type Method","symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanningProgressConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanningprogressconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration"}],"abstract":[{"type":"text","text":"Configuration of visualization of the scanning progress - indeterminate progress."}],"title":"SBSDKUI2CreditCardScanningProgressConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanningProgressConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanningprogressconfiguration\/fromjsonwithjson:","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanningProgressConfiguration\/fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[],"type":"topic","title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2CreditCardScanningProgressConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2CreditCardScanningProgressConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanningProgressConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanningProgressConfiguration\/navigatorTitle","op":"replace"}]}]}