{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ExpectedBarcode\/init(barcodeValue:)"},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithBarcodeValue:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"barcodeValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ExpectedBarcode(im)initWithBarcodeValue:","role":"symbol","title":"init(barcodeValue:)","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"barcodeValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ExpectedBarcode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2expectedbarcode\/init(barcodevalue:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2expectedbarcode\/init(barcodevalue:)"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ExpectedBarcode/init(barcodeValue:)":{"navigatorTitle":[{"text":"initWithBarcodeValue:","kind":"identifier"}],"title":"init(barcodeValue:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ExpectedBarcode\/init(barcodeValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"barcodeValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2expectedbarcode\/init(barcodevalue:)","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ExpectedBarcode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2expectedbarcode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ExpectedBarcode","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2ExpectedBarcode","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ExpectedBarcode"}],"title":"SBSDKUI2ExpectedBarcode","abstract":[{"text":"Configuration of the barcode to find and scan.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithBarcodeValue:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcodeValue:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBarcodeValue:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"barcodeValue","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"initWithBarcodeValue:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ExpectedBarcode~1init(barcodeValue:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBarcodeValue:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ExpectedBarcode~1init(barcodeValue:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ExpectedBarcode\/title","value":"SBSDKUI2ExpectedBarcode"},{"value":[{"kind":"identifier","text":"SBSDKUI2ExpectedBarcode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ExpectedBarcode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ExpectedBarcode\/navigatorTitle","value":[{"text":"SBSDKUI2ExpectedBarcode","kind":"identifier"}],"op":"replace"}]}]}