{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView"]]},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"margins"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"margins","navigatorTitle":[{"kind":"identifier","text":"margins"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKZoomingImageScrollView(py)margins"},"abstract":[{"text":"The margins of the displayed image to the bounds of the receiver. Defaults to (20.0, 20.0, 20.0, 20.0).","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"margins","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","kind":"typeIdentifier","text":"UIEdgeInsets"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/margins"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/margins"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/margins","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView/margins":{"title":"margins","url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/margins","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/margins","navigatorTitle":[{"text":"margins","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"margins"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"kind":"symbol","abstract":[{"text":"The margins of the displayed image to the bounds of the receiver. Defaults to (20.0, 20.0, 20.0, 20.0).","type":"text"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"title":"SBSDKZoomingImageScrollView","url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview","abstract":[{"type":"text","text":"A scrollable and zoomable "},{"type":"codeVoice","code":"UIScrollView"},{"text":" subclass that displays images and an overlay view.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"margins"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"margins","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":" "},{"text":"margins","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView~1margins\/title","value":"margins"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView~1margins\/fragments","value":[{"kind":"identifier","text":"margins"}]},{"value":"SBSDKZoomingImageScrollView","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/fragments","op":"replace","value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}