{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:"}],"title":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(im)initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","roleHeading":"Instance Method","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithAcknowledgement:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration","text":"SBSDKUI2AcknowledgementScreenConfiguration"},{"text":" *) ","kind":"text"},{"text":"acknowledgement","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"introduction:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration","text":"SBSDKUI2IntroductionScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroductionScreenConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"introduction","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanAssistanceOverlay:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay","text":"SBSDKUI2ScanAssistanceOverlay","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"scanAssistanceOverlay"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermission:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","text":"SBSDKUI2CameraPermissionScreen"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraPermission"},{"kind":"text","text":" "},{"text":"topBarTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"topBarTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarIntroButton:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarIntroButton"},{"kind":"text","text":" "},{"text":"topBarBackButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"topBarBackButton"},{"text":" ","kind":"text"},{"text":"topUserGuidance:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"text":"topUserGuidance","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidance:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance","text":"SBSDKUI2DocumentScannerUserGuidance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance"},{"text":" *) ","kind":"text"},{"text":"userGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"backgroundColor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"autoRotateImages:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"autoRotateImages","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"openReviewAfterEachScan:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"openReviewAfterEachScan","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cameraConfiguration"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scannerParameters:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters","text":"SBSDKDocumentScannerParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"scannerParameters"},{"text":" ","kind":"text"},{"text":"polygon:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration","text":"SBSDKUI2DocumentPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"polygon"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomBar:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2CameraBottomBar","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar"},{"kind":"text","text":" *) "},{"text":"bottomBar","kind":"internalParam"},{"kind":"text","text":" "},{"text":"viewFinder:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2ViewFinderConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration"},{"text":" *) ","kind":"text"},{"text":"viewFinder","kind":"internalParam"},{"kind":"text","text":" "},{"text":"captureFeedback:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback","kind":"typeIdentifier","text":"SBSDKUI2CaptureFeedback","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"captureFeedback"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vibration:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Vibration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration"},{"text":" *) ","kind":"text"},{"text":"vibration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"timeouts:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","kind":"typeIdentifier","text":"SBSDKUI2Timeouts","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"timeouts"},{"text":" ","kind":"text"},{"kind":"identifier","text":"limitReachedAlertDialog:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"limitReachedAlertDialog"},{"kind":"text","text":" "},{"text":"cancelAlertDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cancelAlertDialog"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/initwithacknowledgement:introduction:scanassistanceoverlay:camerapermission:topbartitle:topbarintrobutton:topbarbackbutton:topuserguidance:userguidance:backgroundcolor:autorotateimages:openreviewaftereachscan:cameraconfiguration:scannerpara-9lxl1"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the introduction screen for the document scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration","title":"SBSDKUI2IntroductionScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Timeouts":{"type":"topic","title":"SBSDKUI2Timeouts","abstract":[{"text":"Configuration of timeouts.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","navigatorTitle":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2timeouts"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar":{"title":"SBSDKUI2CameraBottomBar","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"abstract":[{"text":"Configuration of the bottom bar for the camera screen.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2ButtonConfiguration","abstract":[{"type":"text","text":"Configuration of the button."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CaptureFeedback":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2capturefeedback","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback","navigatorTitle":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"abstract":[{"text":"Configuration of the feedback shown after snapping a page.","type":"text"}],"title":"SBSDKUI2CaptureFeedback"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanbotAlertDialog":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Configuration of the standard alert dialog.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","title":"SBSDKUI2ScanbotAlertDialog","url":"\/documentation\/scanbotsdk\/sbsdkui2scanbotalertdialog"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconButton":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the icon appearance on a button."}],"navigatorTitle":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconbutton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconButton"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","title":"SBSDKUI2IconButton","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"title":"SBSDKUI2StyledText","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerUserGuidance":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the hints guiding users through the scanning process."}],"title":"SBSDKUI2DocumentScannerUserGuidance","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration/initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/initwithacknowledgement:introduction:scanassistanceoverlay:camerapermission:topbartitle:topbarintrobutton:topbarbackbutton:topuserguidance:userguidance:backgroundcolor:autorotateimages:openreviewaftereachscan:cameraconfiguration:scannerpara-9lxl1","title":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:autoRotateImages:openReviewAfterEachScan:cameraConfiguration:scannerParameters:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementScreenConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration","title":"SBSDKUI2AcknowledgementScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Configuration of the acknowledgement screen.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters","title":"SBSDKDocumentScannerParameters","abstract":[{"type":"text","text":"Parameters for the document scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"title":"SBSDKUI2ViewFinderConfiguration","abstract":[{"text":"Configuration of the scanning interface’s viewfinder, allowing it to be shown or hidden as guidance to the user.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanAssistanceOverlay":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2ScanAssistanceOverlay","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2scanassistanceoverlay","title":"SBSDKUI2ScanAssistanceOverlay","abstract":[{"text":"Configuration of the scan assistance overlay.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","title":"SBSDKUI2UserGuidanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","title":"SBSDKUI2CameraPermissionScreen","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentPolygonConfiguration":{"title":"SBSDKUI2DocumentPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration","abstract":[{"type":"text","text":"Configuration of the document contour detection polygon."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration","abstract":[{"text":"Configuration of the screen for scanning the pages with the camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2CameraScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Vibration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Vibration"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configure the vibration."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Vibration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","title":"SBSDKUI2Vibration","url":"\/documentation\/scanbotsdk\/sbsdkui2vibration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2IntroductionScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/title"},{"value":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/title","value":"SBSDKUI2Timeouts","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/title","value":"SBSDKUI2CameraBottomBar"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle","value":[{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/title","op":"replace","value":"SBSDKUI2CaptureFeedback"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/navigatorTitle"},{"value":"SBSDKUI2ScanbotAlertDialog","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/title","op":"replace","value":"SBSDKUI2IconButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}]},{"op":"replace","value":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/navigatorTitle"},{"value":"SBSDKUI2StyledText","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/title","value":"SBSDKUI2DocumentScannerUserGuidance","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}]},{"op":"replace","value":"SBSDKUI2AcknowledgementScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}]},{"value":"SBSDKDocumentScannerParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}]},{"value":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/title","value":"SBSDKUI2ViewFinderConfiguration"},{"value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/title","value":"SBSDKUI2ScanAssistanceOverlay"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2ScanAssistanceOverlay","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace","value":"SBSDKUI2Color"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title","value":"SBSDKUI2UserGuidanceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title","value":"SBSDKUI2CameraPermissionScreen"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}]},{"value":"SBSDKUI2DocumentPolygonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"op":"replace"},{"value":"SBSDKUI2CameraScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","value":"SBSDKUI2DocumentScannerCameraConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}]},{"value":"SBSDKUI2Vibration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/fragments","value":[{"text":"SBSDKUI2Vibration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Vibration"}]}]}]}