{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/openreviewaftereachscan"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/openreviewaftereachscan"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"If set to true, the review screen will be shown after each added page.","type":"text"}],"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"openReviewAfterEachScan","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(py)openReviewAfterEachScan","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"openReviewAfterEachScan"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"openReviewAfterEachScan"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/openReviewAfterEachScan","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openReviewAfterEachScan","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is false","type":"text"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration","abstract":[{"text":"Configuration of the screen for scanning the pages with the camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2CameraScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration/openReviewAfterEachScan":{"abstract":[{"type":"text","text":"If set to true, the review screen will be shown after each added page."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/openreviewaftereachscan","title":"openReviewAfterEachScan","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"openReviewAfterEachScan","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openReviewAfterEachScan"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/openReviewAfterEachScan"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"openReviewAfterEachScan","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"openReviewAfterEachScan"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"openReviewAfterEachScan"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/title","value":"SBSDKUI2CameraScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}]},{"value":"openReviewAfterEachScan","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1openReviewAfterEachScan\/title","op":"replace"},{"value":[{"kind":"identifier","text":"openReviewAfterEachScan"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1openReviewAfterEachScan\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}