{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"timeouts"}],"title":"timeouts","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeouts"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Timeouts","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(py)timeouts","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/timeouts"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/timeouts"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeouts","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","text":"SBSDKUI2Timeouts","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/timeouts","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration of timeouts."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Timeouts":{"type":"topic","title":"SBSDKUI2Timeouts","abstract":[{"text":"Configuration of timeouts.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","navigatorTitle":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2timeouts"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration","abstract":[{"text":"Configuration of the screen for scanning the pages with the camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2CameraScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration/timeouts":{"abstract":[{"type":"text","text":"Configuration of timeouts."}],"navigatorTitle":[{"kind":"identifier","text":"timeouts"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/timeouts","title":"timeouts","url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/timeouts","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeouts","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2Timeouts","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"timeouts"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"timeouts"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","text":"SBSDKUI2Timeouts","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"timeouts"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2Timeouts","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/fragments","value":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/navigatorTitle"},{"value":"SBSDKUI2CameraScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"op":"replace"},{"value":"timeouts","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1timeouts\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1timeouts\/fragments","value":[{"kind":"identifier","text":"timeouts"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}