{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Accessibility description for the ‘open introduction screen’ button in top bar.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/accessibilitydescriptionopenintroscreenbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/accessibilitydescriptionopenintroscreenbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenTextLocalization(py)accessibilityDescriptionOpenIntroScreenButton","modules":[{"name":"ScanbotSDK"}],"title":"accessibilityDescriptionOpenIntroScreenButton","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionOpenIntroScreenButton"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionOpenIntroScreenButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"Default is “Open introduction screen.”","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization\/accessibilityDescriptionOpenIntroScreenButton"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization/accessibilityDescriptionOpenIntroScreenButton":{"abstract":[{"text":"Accessibility description for the ‘open introduction screen’ button in top bar.","type":"text"}],"type":"topic","title":"accessibilityDescriptionOpenIntroScreenButton","navigatorTitle":[{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization\/accessibilityDescriptionOpenIntroScreenButton","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/accessibilitydescriptionopenintroscreenbutton","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenTextLocalization"}],"title":"SBSDKUI2CreditCardScannerScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization","abstract":[{"text":"Configuration of the all strings for credit card scanner screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accessibilityDescriptionOpenIntroScreenButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accessibilityDescriptionOpenIntroScreenButton"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization~1accessibilityDescriptionOpenIntroScreenButton\/title","value":"accessibilityDescriptionOpenIntroScreenButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization~1accessibilityDescriptionOpenIntroScreenButton\/fragments","value":[{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/title","value":"SBSDKUI2CreditCardScannerScreenTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}