{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/initwithstatusbarmode:background:iconbackground:icon:enablecamerabutton:closebutton:enablecameratitle:enablecameraexplanation:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","kind":"identifier"}],"title":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen(im)initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStatusBarMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2StatusBarMode","text":"SBSDKUI2StatusBarMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode"},{"text":") ","kind":"text"},{"text":"statusBarMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"background:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"background","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"iconBackground:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"iconBackground","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"icon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2IconStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle"},{"text":" *) ","kind":"text"},{"text":"icon","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"enableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"enableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"closeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"closeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"enableCameraTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"enableCameraTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"enableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"enableCameraExplanation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"title":"SBSDKUI2StyledText","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen/initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:":{"navigatorTitle":[{"text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen\/initwithstatusbarmode:background:iconbackground:icon:enablecamerabutton:closebutton:enablecameratitle:enablecameraexplanation:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","kind":"identifier"}],"type":"topic","title":"initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen\/initWithStatusBarMode:background:iconBackground:icon:enableCameraButton:closeButton:enableCameraTitle:enableCameraExplanation:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the button."}],"title":"SBSDKUI2ButtonConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StatusBarMode":{"title":"SBSDKUI2StatusBarMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StatusBarMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"kind":"symbol","abstract":[{"type":"text","text":"The visual mode used for the status bar icons."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2statusbarmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"title":"SBSDKUI2Color","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconStyle":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2iconstyle","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"title":"SBSDKUI2IconStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","abstract":[{"type":"text","text":"Configuration of the icon appearance."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"title":"SBSDKUI2CameraPermissionScreen","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title"},{"op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2StatusBarMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StatusBarMode\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/title","value":"SBSDKUI2IconStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/fragments","value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/navigatorTitle","value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title","value":"SBSDKUI2CameraPermissionScreen"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}]}]}]}