{"abstract":[{"text":"The image quality used when storing images. Defaults to ","type":"text"},{"code":"80","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileStorageImageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","title":"fileStorageImageQuality","roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration(py)fileStorageImageQuality","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fileStorageImageQuality"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileStorageImageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"}]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/fileStorageImageQuality"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestorageimagequality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestorageimagequality"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration":{"title":"ScanbotSDKConfiguration","abstract":[{"code":"ScanbotSDKConfiguration","type":"codeVoice"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration/fileStorageImageQuality":{"abstract":[{"text":"The image quality used when storing images. Defaults to ","type":"text"},{"type":"codeVoice","code":"80"},{"text":".","type":"text"}],"title":"fileStorageImageQuality","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fileStorageImageQuality"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/fileStorageImageQuality","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/filestorageimagequality","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileStorageImageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"fileStorageImageQuality","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fileStorageImageQuality","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"uint8_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t"},{"text":" ","kind":"text"},{"text":"fileStorageImageQuality","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/title","value":"ScanbotSDKConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/fragments","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1fileStorageImageQuality\/title","value":"fileStorageImageQuality"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1fileStorageImageQuality\/fragments","value":[{"kind":"identifier","text":"fileStorageImageQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}