{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didFinish","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller\/didfinish"]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"didFinish","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"didFinish","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingViewController(im)didFinish","symbolKind":"method","title":"didFinish"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController\/didFinish","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController":{"title":"SBSDKUICroppingViewController","deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController","abstract":[{"type":"text","text":"A highly customizable view controller to edit a pages polygon or the page’s orientation."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController/didFinish":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController\/didFinish","title":"didFinish","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller\/didfinish","kind":"symbol","type":"topic","navigatorTitle":[{"text":"didFinish","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"didFinish","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/title","op":"replace","value":"SBSDKUICroppingViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/fragments","op":"replace","value":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}