{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/imageurl(withpagefileid:pagefiletype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/imageurl(withpagefileid:pagefiletype:)"]}],"abstract":[{"text":"Returns the file URL of the image with the given page file identifier and page file type.","type":"text"}],"kind":"symbol","metadata":{"title":"imageURL(withPageFileID:pageFileType:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageURLWithPageFileID:pageFileType:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage(im)imageURLWithPageFileID:pageFileType:","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageFileType"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The page file identifier of the requested image.","type":"text"}]}],"name":"pageFileID"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The page file type of the requested image.","type":"text"}]}],"name":"type"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the requested image, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the image does not exist in the storage."}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/imageURL(withPageFileID:pageFileType:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileType":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"title":"SBSDKDocumentPageFileType","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","abstract":[{"type":"text","text":"Enumeration of image type classifiers."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/imageURL(withPageFileID:pageFileType:)":{"role":"symbol","abstract":[{"text":"Returns the file URL of the image with the given page file identifier and page file type.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/imageurl(withpagefileid:pagefiletype:)","title":"imageURL(withPageFileID:pageFileType:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/imageURL(withPageFileID:pageFileType:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"imageURLWithPageFileID:pageFileType:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"abstract":[{"type":"text","text":"A class to store and restore images of different types in a memory-efficient way."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"title":"SBSDKDocumentPageFileStorage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"imageURLWithPageFileID:pageFileType:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLWithPageFileID:pageFileType:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageURLWithPageFileID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageFileID"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageFileType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"pageFileID","content":[{"inlineContent":[{"type":"text","text":"The page file identifier of the requested image."}],"type":"paragraph"}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"The page file type of the requested image.","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"The URL of the requested image, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the image does not exist in the storage.","type":"text"}],"type":"paragraph"}]}},{"value":"SBSDKDocumentPageFileType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/navigatorTitle","op":"replace"},{"value":"imageURLWithPageFileID:pageFileType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1imageURL(withPageFileID:pageFileType:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"imageURLWithPageFileID:pageFileType:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1imageURL(withPageFileID:pageFileType:)\/fragments","op":"replace"},{"value":"SBSDKDocumentPageFileStorage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle","op":"replace"}]}]}