{"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"False"},{"type":"text","text":", the finder is inset by the safe area insets. Otherwise the safe area inset is ignored."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"False"},{"type":"text","text":";"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration\/ignoresSafeAreaInsets"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoresSafeAreaInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ignoresSafeAreaInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"ignoresSafeAreaInsets","navigatorTitle":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(py)ignoresSafeAreaInsets"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/ignoressafeareainsets"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/ignoressafeareainsets"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewFinderConfiguration":{"navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"abstract":[{"text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"},{"text":" ","type":"text"},{"text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with","type":"text"},{"text":" ","type":"text"},{"text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in.","type":"text"},{"text":" ","type":"text"},{"text":"It crops the video frame to that region of interest before passing it to any scanner. Usually","type":"text"},{"text":" ","type":"text"},{"text":"the performance of scanners gain a benefit from it because less pixels must be processed.","type":"text"},{"text":" ","type":"text"},{"text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around","type":"text"},{"text":" ","type":"text"},{"text":"on the user interface.","type":"text"}],"title":"SBSDKBaseScannerViewFinderConfiguration","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewFinderConfiguration/ignoresSafeAreaInsets":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoresSafeAreaInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"If set to ","type":"text"},{"code":"False","type":"codeVoice"},{"text":", the finder is inset by the safe area insets. Otherwise the safe area inset is ignored.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"False","type":"codeVoice"},{"text":";","type":"text"}],"navigatorTitle":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}],"title":"ignoresSafeAreaInsets","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/ignoressafeareainsets","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration\/ignoresSafeAreaInsets"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ignoresSafeAreaInsets"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ignoresSafeAreaInsets"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"ignoresSafeAreaInsets","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration\/title","value":"SBSDKBaseScannerViewFinderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle","value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration~1ignoresSafeAreaInsets\/title","value":"ignoresSafeAreaInsets","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration~1ignoresSafeAreaInsets\/fragments","value":[{"text":"ignoresSafeAreaInsets","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}