{"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1\/elements","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1\/requiredDocumentType"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelGS1","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelGS1","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelGS1"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelGS1","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKBarcodeDocumentModelGS1","roleHeading":"Class"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelgs1"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelgs1"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1"},"abstract":[{"text":"GS1","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentWrapper":{"navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKGenericDocumentWrapper","abstract":[{"type":"text","text":"Base class for strongly-typed "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument"},{"type":"text","text":" wrappers."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentwrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelGS1":{"abstract":[{"type":"text","text":"GS1"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelgs1","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelGS1","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelGS1","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentModelGS1","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocument":{"type":"topic","abstract":[{"text":"Generic document.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocument","title":"SBSDKGenericDocument","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocument"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelGS1/requiredDocumentType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1\/requiredDocumentType","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelgs1\/requireddocumenttype","title":"requiredDocumentType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelGS1/elements":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1\/elements","abstract":[{"type":"text","text":"A list of all children of type “Element”."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelgs1\/elements","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"elements","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelGS1Element","text":"SBSDKBarcodeDocumentModelGS1Element"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"elements"}],"role":"symbol","title":"elements"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelGS1/initWithGenericDocument:":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1\/initWithGenericDocument:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelgs1\/initwithgenericdocument:","title":"initWithGenericDocument:","fragments":[{"kind":"text","text":"- "},{"text":"initWithGenericDocument:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeDocumentModelGS1"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKBarcodeDocumentModelGS1","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKBarcodeDocumentModelGS1","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1\/elements","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1\/requiredDocumentType"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelGS1\/initWithGenericDocument:"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelGS1","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKGenericDocumentWrapper","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentWrapper","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKGenericDocumentWrapper","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentWrapper\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentWrapper\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelGS1\/title","value":"SBSDKBarcodeDocumentModelGS1"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelGS1"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelGS1\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelGS1"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelGS1\/navigatorTitle","op":"replace"},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelGS1~1requiredDocumentType\/title","value":"requiredDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelGS1~1requiredDocumentType\/fragments","op":"replace","value":[{"text":"requiredDocumentType","kind":"identifier"}]},{"value":"elements","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelGS1~1elements\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelGS1~1elements\/fragments","value":[{"kind":"identifier","text":"elements"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}