{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoContentMode","roleHeading":"Enumeration","title":"SBSDKVideoContentMode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoContentMode"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentMode"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoContentMode"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Enumeration of video preview content mode."}],"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/fillIn","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/fitIn"],"generated":true},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideocontentmode"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideocontentmode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoContentMode/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideocontentmode\/equatable-implementations","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoContentMode/init(rawValue:)":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideocontentmode\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoContentMode/fillIn":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillIn"}],"abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"text":" ","type":"text"},{"text":"No visible borders. Video may be cropped to the visible screen area.","type":"text"}],"navigatorTitle":[{"text":"SBSDKVideoContentModeFillIn","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/fillIn","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideocontentmode\/fillin","title":"SBSDKVideoContentMode.fillIn","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoContentMode":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideocontentmode","abstract":[{"type":"text","text":"Enumeration of video preview content mode."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoContentMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentMode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode","title":"SBSDKVideoContentMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoContentMode/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideocontentmode\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoContentMode/fitIn":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideocontentmode\/fitin","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/fitIn","title":"SBSDKVideoContentMode.fitIn","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fitIn"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKVideoContentModeFitIn","kind":"identifier"}],"abstract":[{"type":"text","text":"The video layers content is fit into the video layer."},{"type":"text","text":" "},{"text":"Video may have visible borders. Video is fully visible within the screen.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKVideoContentMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"SBSDKVideoContentMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKVideoContentMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/fillIn","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoContentMode\/fitIn"],"generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKVideoContentMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoContentMode~1fillIn\/title","value":"SBSDKVideoContentModeFillIn","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoContentMode~1fillIn\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoContentMode\/title","op":"replace","value":"SBSDKVideoContentMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoContentMode\/fragments","value":[{"text":"SBSDKVideoContentMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoContentMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoContentMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoContentMode~1fitIn\/title","value":"SBSDKVideoContentModeFitIn"},{"value":[{"kind":"identifier","text":"SBSDKVideoContentModeFitIn"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoContentMode~1fitIn\/fragments"}]}]}