{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentSubfileField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AAMVADocumentSubfileField","text":"SBSDKUI2AAMVADocumentSubfileField"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentsubfile\/fields"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentsubfile\/fields"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentSubfile\/fields","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sub-file fields"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2AAMVADocumentSubfileField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AAMVADocumentSubfileField"},{"kind":"text","text":"]"}],"title":"fields","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AAMVADocumentSubfile(py)fields","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fields"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentSubfile"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVADocumentSubfile/fields":{"role":"symbol","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2AAMVADocumentSubfileField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AAMVADocumentSubfileField"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Sub-file fields"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentSubfile\/fields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fields"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentsubfile\/fields"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVADocumentSubfileField":{"role":"symbol","title":"SBSDKUI2AAMVADocumentSubfileField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfileField"}],"abstract":[{"type":"text","text":"AAMVA Document Sub-File Field"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentSubfileField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfileField"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentsubfilefield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AAMVADocumentSubfile":{"role":"symbol","title":"SBSDKUI2AAMVADocumentSubfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfile"}],"abstract":[{"type":"text","text":"AAMVA Document Sub-File"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AAMVADocumentSubfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfile"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aamvadocumentsubfile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fields"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2AAMVADocumentSubfileField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fields"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentSubfile~1fields\/title","value":"fields"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentSubfile~1fields\/fragments","value":[{"kind":"identifier","text":"fields"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentSubfileField\/title","value":"SBSDKUI2AAMVADocumentSubfileField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentSubfileField\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfileField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentSubfile\/title","value":"SBSDKUI2AAMVADocumentSubfile"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AAMVADocumentSubfile\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}