{"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKFinderView(py)secondaryAspectRatio","navigatorTitle":[{"text":"secondaryAspectRatio","kind":"identifier"}],"symbolKind":"property","title":"secondaryAspectRatio","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview\/secondaryaspectratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview\/secondaryaspectratio"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Defaults to -1.0.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/secondaryAspectRatio","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The secondary aspect ratio of the viewport (cutout), if set to -1.0, no cutout is drawn.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView/secondaryAspectRatio":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview\/secondaryaspectratio","abstract":[{"type":"text","text":"The secondary aspect ratio of the viewport (cutout), if set to -1.0, no cutout is drawn."}],"title":"secondaryAspectRatio","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"secondaryAspectRatio"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryAspectRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/secondaryAspectRatio"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderView"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView","title":"SBSDKFinderView","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"secondaryAspectRatio","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"secondaryAspectRatio"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"secondaryAspectRatio","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"secondaryAspectRatio","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView~1secondaryAspectRatio\/title"},{"value":[{"kind":"identifier","text":"secondaryAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView~1secondaryAspectRatio\/fragments"},{"value":"SBSDKFinderView","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/title"},{"value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/fragments"},{"value":[{"text":"SBSDKFinderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}