{"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatMicroPDF417Configuration","roleHeading":"Class","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKBarcodeFormatMicroPDF417Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"sections":[],"abstract":[{"text":"MicroPDF417 configuration. Add to scanner configuration to scan MicroPDF417 codes.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/init()"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/gs1Handling","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/strictMode"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/toJson(configuration:)"],"anchor":"Instance-Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeFormatMicroPDF417Configuration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatTwoDConfigurationBase":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}],"kind":"symbol","abstract":[{"type":"text","text":"Base class for all 2D barcode configurations."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformattwodconfigurationbase","title":"SBSDKBarcodeFormatTwoDConfigurationBase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/fromJsonWithJson:":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/fromJsonWithJson:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/fromjsonwithjson:","title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/hash","role":"symbol","kind":"symbol","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/hash"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:"}],"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:"}],"role":"symbol","kind":"symbol","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:gs1handling:strictmode:"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/init()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/init()","abstract":[],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/toJson(configuration:)":{"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/tojson(configuration:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/toJson(configuration:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/new":{"title":"new","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/new","navigatorTitle":[{"text":"new","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/new"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/gs1Handling":{"kind":"symbol","abstract":[{"type":"text","text":"GS1 message handling options."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/gs1handling","title":"gs1Handling","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gs1Handling","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling","text":"SBSDKGS1Handling"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"gs1Handling"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/gs1Handling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/copyWithZone:","type":"topic","kind":"symbol","abstract":[],"title":"copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration","title":"SBSDKBarcodeFormatMicroPDF417Configuration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatMicroPDF417Configuration"}],"abstract":[{"type":"text","text":"MicroPDF417 configuration. Add to scanner configuration to scan MicroPDF417 codes."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatMicroPDF417Configuration"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"Foundation.NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/isEqual:":{"title":"isEqual:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/isequal:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/isEqual:"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/strictMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/strictmode","abstract":[{"type":"text","text":"If true, the barcode scanner will only return barcodes that pass the strict validation checks according to standards to avoid false positives."}],"type":"topic","kind":"symbol","title":"strictMode","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strictMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"strictMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/strictMode"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeFormatMicroPDF417Configuration","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/gs1Handling","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/strictMode"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/toJson(configuration:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/new"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatTwoDConfigurationBase"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBarcodeFormatTwoDConfigurationBase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1toJson(configuration:)\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1toJson(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1gs1Handling\/title","op":"replace","value":"gs1Handling"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1gs1Handling\/fragments","op":"replace","value":[{"text":"gs1Handling","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/title","op":"replace","value":"SBSDKBarcodeFormatMicroPDF417Configuration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatMicroPDF417Configuration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1strictMode\/title","op":"replace","value":"strictMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration~1strictMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"strictMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}