{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardDocumentModelConstants"}]}]}],"topicSections":[{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardNumberFieldName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardholderNameFieldName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardholderNameFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardExpiryDateFieldName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardExpiryDateFieldNormalizedName"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"title":"SBSDKCreditCardDocumentModelConstants","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardDocumentModelConstants","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardDocumentModelConstants"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardExpiryDateFieldName":{"title":"creditCardExpiryDateFieldName","navigatorTitle":[{"text":"creditCardExpiryDateFieldName","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardexpirydatefieldname","abstract":[{"type":"text","text":"Name of the “ExpiryDate” field type in document type “CreditCard”."}],"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardExpiryDateFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardExpiryDateFieldName","role":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/init":{"title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/init","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/init","role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardExpiryDateFieldNormalizedName":{"navigatorTitle":[{"text":"creditCardExpiryDateFieldNormalizedName","kind":"identifier"}],"type":"topic","title":"creditCardExpiryDateFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardExpiryDateFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Normalized full name of the “ExpiryDate” field type in document type “CreditCard”."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardExpiryDateFieldNormalizedName","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardexpirydatefieldnormalizedname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardCardNumberFieldNormalizedName":{"kind":"symbol","title":"creditCardCardNumberFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardCardNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardNumberFieldNormalizedName","role":"symbol","abstract":[{"text":"Normalized full name of the “CardNumber” field type in document type “CreditCard”.","type":"text"}],"navigatorTitle":[{"text":"creditCardCardNumberFieldNormalizedName","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardcardnumberfieldnormalizedname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardCardholderNameFieldName":{"type":"topic","title":"creditCardCardholderNameFieldName","navigatorTitle":[{"text":"creditCardCardholderNameFieldName","kind":"identifier"}],"abstract":[{"text":"Name of the “CardholderName” field type in document type “CreditCard”.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardholderNameFieldName","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardCardholderNameFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardcardholdernamefieldname"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardCardNumberFieldName":{"navigatorTitle":[{"kind":"identifier","text":"creditCardCardNumberFieldName"}],"abstract":[{"text":"Name of the “CardNumber” field type in document type “CreditCard”.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardcardnumberfieldname","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardCardNumberFieldName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","kind":"symbol","title":"creditCardCardNumberFieldName","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardNumberFieldName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardDocumentType":{"abstract":[{"type":"text","text":"Document type name of the “CreditCard” document type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardDocumentType","title":"creditCardDocumentType","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"creditCardDocumentType"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcarddocumenttype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants":{"navigatorTitle":[{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}],"title":"SBSDKCreditCardDocumentModelConstants","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardCardholderNameFieldNormalizedName":{"kind":"symbol","abstract":[{"type":"text","text":"Normalized full name of the “CardholderName” field type in document type “CreditCard”."}],"title":"creditCardCardholderNameFieldNormalizedName","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardCardholderNameFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"creditCardCardholderNameFieldNormalizedName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardholderNameFieldNormalizedName","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardcardholdernamefieldnormalizedname"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKCreditCardDocumentModelConstants","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardDocumentModelConstants"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/init"],"title":"Instance Methods"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardNumberFieldName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardNumberFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardholderNameFieldName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardCardholderNameFieldNormalizedName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardExpiryDateFieldName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardExpiryDateFieldNormalizedName"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"creditCardExpiryDateFieldName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardExpiryDateFieldName\/title"},{"value":[{"text":"creditCardExpiryDateFieldName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardExpiryDateFieldName\/fragments"},{"value":"creditCardExpiryDateFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardExpiryDateFieldNormalizedName\/title"},{"value":[{"text":"creditCardExpiryDateFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardExpiryDateFieldNormalizedName\/fragments"},{"value":"creditCardCardNumberFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardNumberFieldNormalizedName\/title"},{"value":[{"kind":"identifier","text":"creditCardCardNumberFieldNormalizedName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardNumberFieldNormalizedName\/fragments"},{"value":"creditCardCardholderNameFieldName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardholderNameFieldName\/title"},{"value":[{"text":"creditCardCardholderNameFieldName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardholderNameFieldName\/fragments"},{"value":"creditCardCardNumberFieldName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardNumberFieldName\/title"},{"value":[{"kind":"identifier","text":"creditCardCardNumberFieldName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardNumberFieldName\/fragments"},{"value":"creditCardDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardDocumentType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"creditCardDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardDocumentType\/fragments"},{"op":"replace","value":"SBSDKCreditCardDocumentModelConstants","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/title"},{"op":"replace","value":[{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCreditCardDocumentModelConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/navigatorTitle"},{"op":"replace","value":"creditCardCardholderNameFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardholderNameFieldNormalizedName\/title"},{"op":"replace","value":[{"text":"creditCardCardholderNameFieldNormalizedName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardCardholderNameFieldNormalizedName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}