{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/init()"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/badPerspective","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/noDocumentFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/scanningProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/tooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/tooSmall"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/toJson(configuration:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorGuidanceStates","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"title":"SBSDKUI2DocumentDataExtractorGuidanceStates","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"roleHeading":"Class"},"abstract":[{"type":"text","text":"Configure the captions of the user guidance hints for different scanning states."}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2DocumentDataExtractorGuidanceStates) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/fromJsonWithJson:":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/fromJsonWithJson:","role":"symbol","title":"fromJsonWithJson:","abstract":[],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/tooSmall":{"role":"symbol","title":"tooSmall","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/toosmall","abstract":[{"text":"The user guidance text displayed when the detected document is too far away and appears too small.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/tooSmall","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooSmall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"tooSmall"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/isEqual:":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/isEqual:","role":"symbol","title":"isEqual:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/isequal:"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/init()":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/init()","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/noDocumentFound":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/noDocumentFound","navigatorTitle":[{"kind":"identifier","text":"noDocumentFound"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/nodocumentfound","type":"topic","title":"noDocumentFound","abstract":[{"type":"text","text":"The user guidance text displayed when no document is found. Initial state."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noDocumentFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/toJson(configuration:)":{"type":"topic","title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/tojson(configuration:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/toJson(configuration:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/tooDark":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/tooDark","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/toodark","title":"tooDark","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooDark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"The user guidance text displayed when it is too dark to capture an adequate image."}],"navigatorTitle":[{"kind":"identifier","text":"tooDark"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:":{"title":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","navigatorTitle":[{"kind":"identifier","text":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/initwithnodocumentfound:scanningprogress:toodark:toosmall:badperspective:","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Node"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2node","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Node"}],"title":"SBSDKUI2Node","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/hash","title":"hash","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/scanningProgress":{"kind":"symbol","title":"scanningProgress","navigatorTitle":[{"text":"scanningProgress","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/scanningProgress","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/scanningprogress","role":"symbol","abstract":[{"type":"text","text":"The user guidance text displayed when a document presence was detected and scanning is in progress."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanningProgress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/badPerspective":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/badPerspective","title":"badPerspective","abstract":[{"type":"text","text":"The user guidance text displayed when the detected document is not in a good perspective (device tilted)."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badPerspective"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"badPerspective"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/badperspective","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates","title":"SBSDKUI2DocumentDataExtractorGuidanceStates","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configure the captions of the user guidance hints for different scanning states."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/copyWithZone:":{"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/copywithzone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/copyWithZone:","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2DocumentDataExtractorGuidanceStates","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/badPerspective","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/noDocumentFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/scanningProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/tooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/tooSmall"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/initWithNoDocumentFound:scanningProgress:tooDark:tooSmall:badPerspective:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/fromJsonWithJson:"],"anchor":"Type-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"tooSmall","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1tooSmall\/title","op":"replace"},{"value":[{"kind":"identifier","text":"tooSmall"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1tooSmall\/fragments","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1init()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1init()\/fragments","op":"replace"},{"value":"noDocumentFound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1noDocumentFound\/title","op":"replace"},{"value":[{"text":"noDocumentFound","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1noDocumentFound\/fragments","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1toJson(configuration:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1toJson(configuration:)\/fragments","op":"replace"},{"value":"tooDark","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1tooDark\/title","op":"replace"},{"value":[{"text":"tooDark","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1tooDark\/fragments","op":"replace"},{"value":"SBSDKUI2Node","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace"},{"value":"scanningProgress","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1scanningProgress\/title","op":"replace"},{"value":[{"kind":"identifier","text":"scanningProgress"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1scanningProgress\/fragments","op":"replace"},{"value":"badPerspective","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1badPerspective\/title","op":"replace"},{"value":[{"kind":"identifier","text":"badPerspective"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates~1badPerspective\/fragments","op":"replace"},{"value":"SBSDKUI2DocumentDataExtractorGuidanceStates","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorGuidanceStates"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}