{"abstract":[{"type":"text","text":"Report of the document value semantics verification."}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateBeforeExpiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateBeforeIssueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateSemantics","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/expiryDateSemantics","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/issueDateBeforeExpiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/issueDateSemantics","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/overallInvalidSemantics"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/toJson(configuration:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKSemanticsVerificationReport) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport"]}],"metadata":{"navigatorTitle":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSemanticsVerificationReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}],"title":"SBSDKSemanticsVerificationReport"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/birthDateBeforeIssueDate":{"abstract":[{"type":"text","text":"Result of verification whether the birth date is before the issue date."}],"type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"birthDateBeforeIssueDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKValueSemantics","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateBeforeIssueDate","title":"birthDateBeforeIssueDate","navigatorTitle":[{"text":"birthDateBeforeIssueDate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/birthdatebeforeissuedate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/issueDateBeforeExpiryDate":{"kind":"symbol","navigatorTitle":[{"text":"issueDateBeforeExpiryDate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/issueDateBeforeExpiryDate","abstract":[{"type":"text","text":"Result of verification whether the issue date is before the expiry date."}],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issueDateBeforeExpiryDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKValueSemantics","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics"}],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/issuedatebeforeexpirydate","title":"issueDateBeforeExpiryDate"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/birthDateSemantics":{"navigatorTitle":[{"kind":"identifier","text":"birthDateSemantics"}],"kind":"symbol","title":"birthDateSemantics","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/birthdatesemantics","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateSemantics","abstract":[{"text":"Status of the birth date semantics verification. Shows whether the birth date in the document is in the past.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDateSemantics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier","text":"SBSDKCompositeFieldValueSemantics"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/isequal:","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/isEqual:","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/fromJsonWithJson:","role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/fromjsonwithjson:","type":"topic","kind":"symbol","title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/copyWithZone:":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/copyWithZone:","role":"symbol","title":"copyWithZone:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/toJson(configuration:)":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/tojson(configuration:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/toJson(configuration:)","role":"symbol","title":"toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/birthDateBeforeExpiryDate":{"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/birthdatebeforeexpirydate","kind":"symbol","title":"birthDateBeforeExpiryDate","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDateBeforeExpiryDate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKValueSemantics","kind":"typeIdentifier","text":"SBSDKValueSemantics"}],"abstract":[{"text":"Result of verification whether the birth date is before the expiry date.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateBeforeExpiryDate","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"birthDateBeforeExpiryDate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/expiryDateSemantics":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/expiryDateSemantics","title":"expiryDateSemantics","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiryDateSemantics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier","text":"SBSDKCompositeFieldValueSemantics"}],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/expirydatesemantics","abstract":[{"type":"text","text":"Status of the expiry date semantics verification. Shows whether the expiry date in the document is in the future."}],"navigatorTitle":[{"kind":"identifier","text":"expiryDateSemantics"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/issueDateSemantics":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/issueDateSemantics","navigatorTitle":[{"kind":"identifier","text":"issueDateSemantics"}],"abstract":[{"text":"Status of the issue date semantics verification. Shows whether the issue date in the document is in the past.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/issuedatesemantics","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issueDateSemantics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompositeFieldValueSemantics","kind":"typeIdentifier","text":"SBSDKCompositeFieldValueSemantics"}],"kind":"symbol","role":"symbol","title":"issueDateSemantics"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport":{"navigatorTitle":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport","role":"symbol","abstract":[{"type":"text","text":"Report of the document value semantics verification."}],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport","type":"topic","kind":"symbol","title":"SBSDKSemanticsVerificationReport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/hash":{"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/hash","title":"hash","fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/hash","role":"symbol","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/overallInvalidSemantics":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/overallInvalidSemantics","abstract":[{"type":"text","text":"Overall status of the value semantics verification. Corresponds to the most severe status of all fields, i.e. if at least one field is semantically incorrect, the overall status is semantically incorrect. If some verifications are skipped, they do not impact the overall status."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"overallInvalidSemantics"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"overallInvalidSemantics"}],"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/overallinvalidsemantics","title":"overallInvalidSemantics"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSemanticsVerificationReport/initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:":{"url":"\/documentation\/scanbotsdk\/sbsdksemanticsverificationreport\/initwithoverallinvalidsemantics:expirydatesemantics:issuedatesemantics:birthdatesemantics:issuedatebeforeexpirydate:birthdatebeforeissuedate:birthdatebeforeexpirydate:","title":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKSemanticsVerificationReport"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateBeforeExpiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateBeforeIssueDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/birthDateSemantics","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/expiryDateSemantics","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/issueDateBeforeExpiryDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/issueDateSemantics","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/overallInvalidSemantics"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/initWithOverallInvalidSemantics:expiryDateSemantics:issueDateSemantics:birthDateSemantics:issueDateBeforeExpiryDate:birthDateBeforeIssueDate:birthDateBeforeExpiryDate:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/toJson(configuration:)"],"title":"Instance Methods"},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSemanticsVerificationReport\/fromJsonWithJson:"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSemanticsVerificationReport"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1birthDateBeforeIssueDate\/title","op":"replace","value":"birthDateBeforeIssueDate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1birthDateBeforeIssueDate\/fragments","op":"replace","value":[{"text":"birthDateBeforeIssueDate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1issueDateBeforeExpiryDate\/title","op":"replace","value":"issueDateBeforeExpiryDate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1issueDateBeforeExpiryDate\/fragments","op":"replace","value":[{"text":"issueDateBeforeExpiryDate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1birthDateSemantics\/title","op":"replace","value":"birthDateSemantics"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1birthDateSemantics\/fragments","op":"replace","value":[{"kind":"identifier","text":"birthDateSemantics"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1toJson(configuration:)\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1toJson(configuration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1birthDateBeforeExpiryDate\/title","op":"replace","value":"birthDateBeforeExpiryDate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1birthDateBeforeExpiryDate\/fragments","op":"replace","value":[{"text":"birthDateBeforeExpiryDate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1expiryDateSemantics\/title","op":"replace","value":"expiryDateSemantics"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1expiryDateSemantics\/fragments","op":"replace","value":[{"kind":"identifier","text":"expiryDateSemantics"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1issueDateSemantics\/title","op":"replace","value":"issueDateSemantics"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1issueDateSemantics\/fragments","op":"replace","value":[{"text":"issueDateSemantics","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/title","op":"replace","value":"SBSDKSemanticsVerificationReport"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/fragments","op":"replace","value":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport\/navigatorTitle","op":"replace","value":[{"text":"SBSDKSemanticsVerificationReport","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1overallInvalidSemantics\/title","op":"replace","value":"overallInvalidSemantics"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSemanticsVerificationReport~1overallInvalidSemantics\/fragments","op":"replace","value":[{"text":"overallInvalidSemantics","kind":"identifier"}]}]}]}