{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/deviceName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/fullDeviceName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/isSimulatorDevice","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/maximumRecommendedImageSize"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/freeDiskSpace()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/freeDiskSpaceInBytes()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/totalDiskSpace()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/totalDiskSpaceInBytes()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/usedDiskSpace()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdeviceinformation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdeviceinformation"]}],"abstract":[{"type":"text","text":"Helper class that delivers information about the used iOS device."}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"SBSDKDeviceInformation","kind":"identifier"}],"role":"symbol","title":"SBSDKDeviceInformation","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceInformation","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDeviceInformation"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceInformation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/fullDeviceName":{"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullDeviceName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"fullDeviceName","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/fulldevicename","navigatorTitle":[{"text":"fullDeviceName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/fullDeviceName","abstract":[{"type":"text","text":"The full name of the device including the iOS version, e.g. “iPhone15,2 (16.0.1)”"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/isSimulatorDevice":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/isSimulatorDevice","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/issimulatordevice","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the current device is a simulator, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"title":"isSimulatorDevice","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSimulatorDevice","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isSimulatorDevice","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/freeDiskSpace()":{"navigatorTitle":[{"text":"freeDiskSpace","kind":"identifier"}],"abstract":[{"text":"The amount of unused disk space of the device as a formatted and localized string.","type":"text"}],"type":"topic","title":"freeDiskSpace()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/freeDiskSpace()","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"freeDiskSpace","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/freediskspace()"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"abstract":[{"text":"Helper class that delivers information about the used iOS device.","type":"text"}],"title":"SBSDKDeviceInformation","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDeviceInformation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/usedDiskSpace()":{"title":"usedDiskSpace()","kind":"symbol","abstract":[{"text":"The amount of used disk space of the device as a formatted and localized string.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/usedDiskSpace()","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/useddiskspace()","navigatorTitle":[{"kind":"identifier","text":"usedDiskSpace"}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedDiskSpace"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/freeDiskSpaceInBytes()":{"navigatorTitle":[{"kind":"identifier","text":"freeDiskSpaceInBytes"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/freediskspaceinbytes()","abstract":[{"text":"The amount of unused disk space of the device in bytes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/freeDiskSpaceInBytes()","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"freeDiskSpaceInBytes"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"title":"freeDiskSpaceInBytes()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/deviceName":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/devicename","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"deviceName","type":"topic","abstract":[{"text":"The name of the device, e.g. “iPhone15,2”.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"deviceName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/deviceName"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/maximumRecommendedImageSize":{"title":"maximumRecommendedImageSize","navigatorTitle":[{"kind":"identifier","text":"maximumRecommendedImageSize"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/maximumrecommendedimagesize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumRecommendedImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/maximumRecommendedImageSize","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Returns the maximum recommended image size for this device."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/totalDiskSpace()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalDiskSpace","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/totalDiskSpace()","kind":"symbol","abstract":[{"text":"The total amount of disk space of the device as a formatted and localized string.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/totaldiskspace()","type":"topic","navigatorTitle":[{"text":"totalDiskSpace","kind":"identifier"}],"title":"totalDiskSpace()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/usedDiskSpaceInBytes()":{"abstract":[{"text":"The amount of used disk space of the device in bytes.","type":"text"}],"type":"topic","title":"usedDiskSpaceInBytes()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"usedDiskSpaceInBytes"}],"url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/useddiskspaceinbytes()","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"usedDiskSpaceInBytes"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceInformation/totalDiskSpaceInBytes()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/totalDiskSpaceInBytes()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalDiskSpaceInBytes"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdeviceinformation\/totaldiskspaceinbytes()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"totalDiskSpaceInBytes"}],"abstract":[{"text":"The total amount of disk space of the device in bytes.","type":"text"}],"title":"totalDiskSpaceInBytes()"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDeviceInformation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/deviceName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/fullDeviceName","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/isSimulatorDevice","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/maximumRecommendedImageSize"],"generated":true,"anchor":"Type-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/freeDiskSpace()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/freeDiskSpaceInBytes()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/totalDiskSpace()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/totalDiskSpaceInBytes()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/usedDiskSpace()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceInformation\/usedDiskSpaceInBytes()"],"generated":true,"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceInformation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1fullDeviceName\/title","op":"replace","value":"fullDeviceName"},{"op":"replace","value":[{"kind":"identifier","text":"fullDeviceName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1fullDeviceName\/fragments"},{"op":"replace","value":"isSimulatorDevice","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1isSimulatorDevice\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isSimulatorDevice"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1isSimulatorDevice\/fragments"},{"op":"replace","value":"freeDiskSpace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1freeDiskSpace()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"freeDiskSpace","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1freeDiskSpace()\/fragments"},{"op":"replace","value":"SBSDKDeviceInformation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/title"},{"op":"replace","value":[{"text":"SBSDKDeviceInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation\/navigatorTitle"},{"op":"replace","value":"usedDiskSpace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1usedDiskSpace()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"usedDiskSpace","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1usedDiskSpace()\/fragments"},{"op":"replace","value":"freeDiskSpaceInBytes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1freeDiskSpaceInBytes()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"freeDiskSpaceInBytes"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1freeDiskSpaceInBytes()\/fragments"},{"op":"replace","value":"deviceName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1deviceName\/title"},{"op":"replace","value":[{"text":"deviceName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1deviceName\/fragments"},{"op":"replace","value":"maximumRecommendedImageSize","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1maximumRecommendedImageSize\/title"},{"op":"replace","value":[{"text":"maximumRecommendedImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1maximumRecommendedImageSize\/fragments"},{"op":"replace","value":"totalDiskSpace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1totalDiskSpace()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"totalDiskSpace","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1totalDiskSpace()\/fragments"},{"op":"replace","value":"usedDiskSpaceInBytes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1usedDiskSpaceInBytes()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"usedDiskSpaceInBytes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1usedDiskSpaceInBytes()\/fragments"},{"op":"replace","value":"totalDiskSpaceInBytes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1totalDiskSpaceInBytes()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"totalDiskSpaceInBytes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceInformation~1totalDiskSpaceInBytes()\/fragments"}]}]}