{"metadata":{"symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}],"title":"SBSDKUI2CreditCardIntroImage","roleHeading":"Class"},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/toJson(configuration:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage","interfaceLanguage":"swift"},"abstract":[{"text":"The image for the introduction screen with a credit card template.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2CreditCardIntroImage) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroImage/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/isEqual:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","title":"isEqual:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroImage":{"navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage","title":"SBSDKUI2CreditCardIntroImage","abstract":[{"text":"The image for the introduction screen with a credit card template.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2introimage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IntroImage"}],"kind":"symbol","title":"SBSDKUI2IntroImage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IntroImage"}],"abstract":[{"type":"text","text":"Determines the image for the introduction screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroImage/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/hash","abstract":[],"title":"hash","type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroImage/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage\/copywithzone:","kind":"symbol","role":"symbol","type":"topic","title":"copyWithZone:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroImage/fromJsonWithJson:":{"title":"fromJsonWithJson:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage\/fromjsonwithjson:","role":"symbol","abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroImage/init":{"title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/init","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroImage/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintroimage\/tojson(configuration:)","role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2CreditCardIntroImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardIntroImage"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/hash"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/toJson(configuration:)"],"title":"Instance Methods"},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroImage\/fromJsonWithJson:"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardIntroImage"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroImage","kind":"typeIdentifier","text":"SBSDKUI2IntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroImage"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroImage\/title","value":"SBSDKUI2CreditCardIntroImage"},{"value":[{"text":"SBSDKUI2CreditCardIntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroImage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardIntroImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroImage\/navigatorTitle"},{"value":"SBSDKUI2IntroImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/title"},{"value":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/fragments"},{"value":[{"text":"SBSDKUI2IntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroImage\/navigatorTitle"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroImage~1toJson(configuration:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroImage~1toJson(configuration:)\/fragments"}]}]}