{"metadata":{"navigatorTitle":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"role":"symbol","title":"SBSDKBasicImageLoadOptions","symbolKind":"class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBasicImageLoadOptions","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKBasicImageLoadOptions) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Basic options for loading image.","type":"text"}],"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/init()"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/canvasColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/cropRect"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/toJson(configuration:)"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"references":{"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/init()":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/init()","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/cropRect":{"navigatorTitle":[{"text":"cropRect","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cropRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/cropRect","kind":"symbol","abstract":[{"type":"text","text":"If the rect is not empty, the image will be cropped to this rect before processing."}],"url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/croprect","title":"cropRect"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/hash","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/hash","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/isEqual:","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/initWithCropRect:canvasColor:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/initWithCropRect:canvasColor:","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/initwithcroprect:canvascolor:","title":"initWithCropRect:canvasColor:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCropRect:canvasColor:","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithCropRect:canvasColor:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"abstract":[{"type":"text","text":"Basic options for loading image."}],"url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions","kind":"symbol","role":"symbol","title":"SBSDKBasicImageLoadOptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/canvasColor":{"abstract":[{"type":"text","text":"CanvasColor color to use when converting images with alpha channel to images without alpha channel."}],"title":"canvasColor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canvasColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCanvasColor","text":"SBSDKCanvasColor"}],"navigatorTitle":[{"kind":"identifier","text":"canvasColor"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/canvascolor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/canvasColor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/copyWithZone:":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/copywithzone:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/copyWithZone:","role":"symbol","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/toJson(configuration:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/tojson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/toJson(configuration:)","title":"toJson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBasicImageLoadOptions/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkbasicimageloadoptions\/fromjsonwithjson:","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKBasicImageLoadOptions","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/canvasColor","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/cropRect","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/hash"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/initWithCropRect:canvasColor:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/toJson(configuration:)"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBasicImageLoadOptions\/fromJsonWithJson:"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBasicImageLoadOptions"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1init()\/fragments"},{"value":"cropRect","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1cropRect\/title"},{"value":[{"kind":"identifier","text":"cropRect"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1cropRect\/fragments"},{"value":"SBSDKBasicImageLoadOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/title"},{"value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/fragments"},{"value":[{"text":"SBSDKBasicImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions\/navigatorTitle"},{"value":"canvasColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1canvasColor\/title"},{"value":[{"text":"canvasColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1canvasColor\/fragments"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1toJson(configuration:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBasicImageLoadOptions~1toJson(configuration:)\/fragments"}]}]}