{"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionStatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentDataExtractionStatus","symbolKind":"enum","roleHeading":"Enumeration","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus"]}],"kind":"symbol","abstract":[{"type":"text","text":"The status of the extraction process."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorBadCrop","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorNothingFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorUnacceptableDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorUnknownDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/ok","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/okButInvalidDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/okButNotConfirmed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/scanningInProgressStillFocusing"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKDocumentDataExtractionStatus) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus":{"navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus","abstract":[{"type":"text","text":"The status of the extraction process."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus","type":"topic","title":"SBSDKDocumentDataExtractionStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/okButInvalidDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/okbutinvaliddocument","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okButInvalidDocument"}],"kind":"symbol","abstract":[{"text":"The document data was extracted. Some fields in the document have failed validation, e.g. because the document is damaged, not authentic, or does not have all required fields.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/okButInvalidDocument","title":"SBSDKDocumentDataExtractionStatus.okButInvalidDocument","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusOkButInvalidDocument"}]},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/errorUnknownDocument":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A document was detected, but it does not match any supported document format."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorUnknownDocument"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorunknowndocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorUnknownDocument","title":"SBSDKDocumentDataExtractionStatus.errorUnknownDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/ok":{"type":"topic","abstract":[{"type":"text","text":"The document data was extracted."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ok","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/ok","title":"SBSDKDocumentDataExtractionStatus.ok","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusOk","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/ok"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/okButNotConfirmed":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okButNotConfirmed"}],"kind":"symbol","role":"symbol","title":"SBSDKDocumentDataExtractionStatus.okButNotConfirmed","abstract":[{"type":"text","text":"The document data was extracted. Some fields have not yet been confirmed."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/okButNotConfirmed","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/okbutnotconfirmed","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/init(rawvalue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/errorBadCrop":{"title":"SBSDKDocumentDataExtractionStatus.errorBadCrop","abstract":[{"type":"text","text":"A document was detected at an angle or distance that would result in a poor quality crop."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorbadcrop","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorBadCrop","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusErrorBadCrop","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorBadCrop"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/errorNothingFound":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errornothingfound","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusErrorNothingFound","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"No document was detected.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorNothingFound","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNothingFound","kind":"identifier"}],"title":"SBSDKDocumentDataExtractionStatus.errorNothingFound","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/RawRepresentable-Implementations","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/Equatable-Implementations":{"type":"topic","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/Equatable-Implementations","title":"Equatable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/errorUnacceptableDocument":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorUnacceptableDocument"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorUnacceptableDocument"}],"title":"SBSDKDocumentDataExtractionStatus.errorUnacceptableDocument","abstract":[{"type":"text","text":"A supported document was detected, but it is unacceptable in the current configuration."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorunacceptabledocument","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorUnacceptableDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/scanningInProgressStillFocusing":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/scanningInProgressStillFocusing","abstract":[{"type":"text","text":"Document data extraction in progress. Waiting for camera to finish focusing."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/scanninginprogressstillfocusing","title":"SBSDKDocumentDataExtractionStatus.scanningInProgressStillFocusing","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningInProgressStillFocusing"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKDocumentDataExtractionStatus","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorBadCrop","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorNothingFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorUnacceptableDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorUnknownDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/ok","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/okButInvalidDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/okButNotConfirmed","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/scanningInProgressStillFocusing"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/title","op":"replace","value":"SBSDKDocumentDataExtractionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1okButInvalidDocument\/title","op":"replace","value":"SBSDKDocumentDataExtractionStatusOkButInvalidDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1okButInvalidDocument\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractionStatusOkButInvalidDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorUnknownDocument\/title","op":"replace","value":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorUnknownDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorUnknownDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1ok\/title","op":"replace","value":"SBSDKDocumentDataExtractionStatusOk"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1ok\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusOk"}]},{"value":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1okButNotConfirmed\/title"},{"value":[{"text":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1okButNotConfirmed\/fragments"},{"value":"SBSDKDocumentDataExtractionStatusErrorBadCrop","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorBadCrop\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorBadCrop"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorBadCrop\/fragments"},{"value":"SBSDKDocumentDataExtractionStatusErrorNothingFound","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorNothingFound\/title"},{"value":[{"text":"SBSDKDocumentDataExtractionStatusErrorNothingFound","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorNothingFound\/fragments"},{"value":"SBSDKDocumentDataExtractionStatusErrorUnacceptableDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorUnacceptableDocument\/title"},{"value":[{"text":"SBSDKDocumentDataExtractionStatusErrorUnacceptableDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorUnacceptableDocument\/fragments"},{"value":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1scanningInProgressStillFocusing\/title"},{"value":[{"text":"SBSDKDocumentDataExtractionStatusScanningInProgressStillFocusing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1scanningInProgressStillFocusing\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}