{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcontentvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcontentvalidator"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKContentValidator) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidator","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKContentValidator","symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKContentValidator"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKContentValidator"}],"title":"SBSDKContentValidator","roleHeading":"Class"},"abstract":[{"type":"text","text":"Base class for content validators."}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/toJson(configuration:)"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/customContentValidator()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/defaultContentValidator()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/patternContentValidator(pattern:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/patternContentValidator(pattern:)":{"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/patternContentValidator(pattern:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"patternContentValidator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pattern","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"SBSDKPatternContentValidator","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPatternContentValidator"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/patterncontentvalidator(pattern:)","title":"patternContentValidator(pattern:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDefaultContentValidator":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator","abstract":[{"type":"text","text":"Default content validator. Accepts only non-empty strings."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDefaultContentValidator"}],"role":"symbol","title":"SBSDKDefaultContentValidator","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdefaultcontentvalidator","navigatorTitle":[{"kind":"identifier","text":"SBSDKDefaultContentValidator"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomContentValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCustomContentValidator","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Custom content validator."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator","role":"symbol","navigatorTitle":[{"text":"SBSDKCustomContentValidator","kind":"identifier"}],"kind":"symbol","title":"SBSDKCustomContentValidator","url":"\/documentation\/scanbotsdk\/sbsdkcustomcontentvalidator"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator","title":"SBSDKContentValidator","navigatorTitle":[{"text":"SBSDKContentValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Base class for content validators."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/fromJsonWithJson:":{"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/fromjsonwithjson:","abstract":[],"title":"fromJsonWithJson:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/toJson(configuration:)":{"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/tojson(configuration:)","title":"toJson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/toJson(configuration:)","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/hash","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/hash","title":"hash","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/isequal:","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/isEqual:"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/copywithzone:","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/customContentValidator()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/customContentValidator()","role":"symbol","kind":"symbol","abstract":[],"type":"topic","title":"customContentValidator()","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/customcontentvalidator()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customContentValidator","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCustomContentValidator","text":"SBSDKCustomContentValidator","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/defaultContentValidator()":{"abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultContentValidator"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDefaultContentValidator","text":"SBSDKDefaultContentValidator"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/defaultContentValidator()","title":"defaultContentValidator()","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/defaultcontentvalidator()","kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternContentValidator":{"url":"\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator","abstract":[{"text":"Pattern content validator.","type":"text"}],"title":"SBSDKPatternContentValidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPatternContentValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPatternContentValidator"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKContentValidator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKContentValidator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKContentValidator","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/hash"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/toJson(configuration:)"],"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/fromJsonWithJson:"],"title":"Type Methods","anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomContentValidator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDefaultContentValidator","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator"],"type":"inheritedBy","title":"Inherited By"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/title","value":"SBSDKDefaultContentValidator"},{"value":[{"text":"SBSDKDefaultContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDefaultContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDefaultContentValidator\/navigatorTitle","op":"replace"},{"value":"SBSDKCustomContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCustomContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/fragments","op":"replace"},{"value":[{"text":"SBSDKCustomContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomContentValidator\/navigatorTitle","op":"replace"},{"value":"SBSDKContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/navigatorTitle","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator~1toJson(configuration:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator~1toJson(configuration:)\/fragments","op":"replace"},{"value":"SBSDKPatternContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/title","op":"replace"},{"value":[{"text":"SBSDKPatternContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/fragments","op":"replace"},{"value":[{"text":"SBSDKPatternContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/navigatorTitle","op":"replace"}]}]}