{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroShippingContainer","title":"SBSDKUI2TextPatternIntroShippingContainer","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternIntroShippingContainer"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternIntroShippingContainer"}],"role":"symbol"},"abstract":[{"type":"text","text":"The image for the introduction screen showing a text on a shipping container."}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/toJson(configuration:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2TextPatternIntroShippingContainer) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternIntroShippingContainer","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroImage":{"role":"symbol","abstract":[{"type":"text","text":"The image for the introduction screen of a generic text scanner screen."}],"title":"SBSDKUI2TextPatternScannerIntroImage","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroimage","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroShippingContainer/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/fromJsonWithJson:","title":"fromJsonWithJson:","role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer\/fromjsonwithjson:","type":"topic","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroShippingContainer/toJson(configuration:)":{"kind":"symbol","type":"topic","title":"toJson(configuration:)","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer\/tojson(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroShippingContainer/init":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","abstract":[],"title":"init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroShippingContainer/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer\/isequal:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroShippingContainer/copyWithZone:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer\/copywithzone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/copyWithZone:","title":"copyWithZone:","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroShippingContainer/hash":{"role":"symbol","type":"topic","kind":"symbol","title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/hash","fragments":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer\/hash","abstract":[]},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroShippingContainer":{"type":"topic","abstract":[{"type":"text","text":"The image for the introduction screen showing a text on a shipping container."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintroshippingcontainer","title":"SBSDKUI2TextPatternIntroShippingContainer","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2TextPatternIntroShippingContainer","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternIntroShippingContainer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKUI2TextPatternIntroShippingContainer","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKUI2TextPatternIntroShippingContainer","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternIntroShippingContainer"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/hash"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/toJson(configuration:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroShippingContainer\/fromJsonWithJson:"],"generated":true,"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternIntroShippingContainer","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerIntroImage","text":"SBSDKUI2TextPatternScannerIntroImage","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2TextPatternScannerIntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/navigatorTitle"},{"op":"replace","value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroShippingContainer~1toJson(configuration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroShippingContainer~1toJson(configuration:)\/fragments"},{"op":"replace","value":"SBSDKUI2TextPatternIntroShippingContainer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroShippingContainer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternIntroShippingContainer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroShippingContainer\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2TextPatternIntroShippingContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroShippingContainer\/navigatorTitle"}]}]}