{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Royal Mail barcode configuration. Add to scanner configuration to scan Royal Mail (a.k.a. RM4SCC, CBC, BPO 4-State) barcodes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeFormatRoyalMailConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"title":"SBSDKBarcodeFormatRoyalMailConfiguration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatRoyalMailConfiguration","roleHeading":"Class","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}]},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/init()"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/stripCheckDigits"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/toJson(configuration:)"],"generated":true}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/toJson(configuration:)":{"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"title":"toJson(configuration:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/tojson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/toJson(configuration:)"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/new":{"title":"new","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/new","type":"topic","kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"navigatorTitle":[{"text":"new","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/new"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:stripCheckDigits:":{"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:stripCheckDigits:","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:stripCheckDigits:","type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:stripCheckDigits:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:stripCheckDigits:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:stripcheckdigits:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/fromjsonwithjson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/isEqual:":{"title":"isEqual:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/isequal:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/isEqual:","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/hash":{"title":"hash","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/hash","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/hash","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/copyWithZone:":{"title":"copyWithZone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/copywithzone:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/copyWithZone:","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/init()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","title":"SBSDKBarcodeFormatFourStateConfigurationBase","abstract":[{"text":"Base class for all four-state barcode configurations.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"title":"SBSDKBarcodeFormatRoyalMailConfiguration","role":"symbol","abstract":[{"type":"text","text":"Royal Mail barcode configuration. Add to scanner configuration to scan Royal Mail (a.k.a. RM4SCC, CBC, BPO 4-State) barcodes."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration/stripCheckDigits":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration\/stripcheckdigits","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/stripCheckDigits","navigatorTitle":[{"text":"stripCheckDigits","kind":"identifier"}],"abstract":[{"type":"text","text":"If true, the check digits are stripped from the result."}],"title":"stripCheckDigits","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripCheckDigits","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeFormatRoyalMailConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/stripCheckDigits"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:stripCheckDigits:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/toJson(configuration:)"],"title":"Instance Methods"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration\/new"],"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatFourStateConfigurationBase"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration~1toJson(configuration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration~1toJson(configuration:)\/fragments"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration~1init()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration~1init()\/fragments"},{"op":"replace","value":"SBSDKBarcodeFormatFourStateConfigurationBase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/navigatorTitle"},{"op":"replace","value":"SBSDKBarcodeFormatRoyalMailConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/navigatorTitle"},{"op":"replace","value":"stripCheckDigits","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration~1stripCheckDigits\/title"},{"op":"replace","value":[{"text":"stripCheckDigits","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration~1stripCheckDigits\/fragments"}]}]}