{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialImageProcessingQueue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialTextProcessingQueue"],"title":"Type Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"A serial queue for image processing."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A serial queue for text processing like optical character recognition.","type":"text"}]}]}]}],"kind":"content"}],"metadata":{"navigatorTitle":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"title":"SBSDKProcessingQueueFactory","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessingQueueFactory","symbolKind":"class","roleHeading":"Class"},"abstract":[{"type":"text","text":"Factory class providing different instances of"},{"type":"codeVoice","code":"NSOperationQueue"},{"type":"text","text":" to work on."},{"type":"text","text":" "},{"type":"text","text":"There are 2 main queues:"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingQueueFactory/serialTextProcessingQueue":{"navigatorTitle":[{"kind":"identifier","text":"serialTextProcessingQueue"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/serialtextprocessingqueue","abstract":[{"type":"text","text":"The serial text processing queue."},{"type":"text","text":" "},{"type":"text","text":"If you perform additonal tasks that consume a lot of CPU power you should consider using this queue."},{"type":"text","text":" "},{"type":"text","text":"Otherwise text processing operations can take a very long time."}],"title":"serialTextProcessingQueue","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialTextProcessingQueue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialTextProcessingQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier","text":"DispatchQueue"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingQueueFactory":{"url":"\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}],"kind":"symbol","title":"SBSDKProcessingQueueFactory","abstract":[{"type":"text","text":"Factory class providing different instances of"},{"type":"codeVoice","code":"NSOperationQueue"},{"type":"text","text":" to work on."},{"type":"text","text":" "},{"type":"text","text":"There are 2 main queues:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingQueueFactory/serialImageProcessingQueue":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"serialImageProcessingQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue"}],"type":"topic","title":"serialImageProcessingQueue","abstract":[{"type":"text","text":"The serial image processing queue."},{"type":"text","text":" "},{"type":"text","text":"If you do additional image processing on large images or other tasks that consumes a lot of memory."},{"type":"text","text":" "},{"type":"text","text":"it is highly recommended to use this queue."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/serialimageprocessingqueue","navigatorTitle":[{"kind":"identifier","text":"serialImageProcessingQueue"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialImageProcessingQueue"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingQueueFactory/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprocessingqueuefactory\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/init","kind":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKProcessingQueueFactory","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/init"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialImageProcessingQueue","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingQueueFactory\/serialTextProcessingQueue"],"anchor":"Type-Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingQueueFactory"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory~1serialTextProcessingQueue\/title","value":"serialTextProcessingQueue"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory~1serialTextProcessingQueue\/fragments","value":[{"text":"serialTextProcessingQueue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/title","value":"SBSDKProcessingQueueFactory"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingQueueFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory\/navigatorTitle","value":[{"text":"SBSDKProcessingQueueFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory~1serialImageProcessingQueue\/title","value":"serialImageProcessingQueue"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingQueueFactory~1serialImageProcessingQueue\/fragments","value":[{"kind":"identifier","text":"serialImageProcessingQueue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}