{"sections":[],"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"},"metadata":{"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"role":"symbol","title":"SBSDKPolygon"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"inlineContent":[{"text":"To convert to absolute coordinates use the methods that take a size and return absolute values.","type":"text"},{"text":" ","type":"text"},{"text":"An absolute space can be any 2-dimensional space with a size, e.g. an image.","type":"text"}],"type":"paragraph"}]}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(absolutePointA:pointB:pointC:pointD:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(from:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(metadataObject:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedDoubleValues:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedPointA:pointB:pointC:pointD:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedRect:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/detectionScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/detectionStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/heightPercentage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isConvex","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isNormalized","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isValid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/widthPercentage"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absoluteEdge(with:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePoint(with:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:)-9hkfo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:)-gke8","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:cornerRadius:with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/boundingBox(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/center()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/flipHorizontally()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/flipVertically()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isEqual(to:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isSimilar(to:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalize()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedDoubleValues()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedEdge(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedPoint(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/rotateCCW(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/rotateCW(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/setAbsolutePoint(point:with:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/setNormalizedPoint(_:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/sortClockwise()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/standardDeviation(to:)"]},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePoint(fromNormalizedPoint:with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedPoint(fromAbsolutePoint:with:)"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/isNormalized":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isNormalized","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNormalized"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isNormalized"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/isnormalized","title":"isNormalized","abstract":[{"text":"Determines if all points of the polygon are within the normalized coordinate range.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/normalize()":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalize"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/normalize()","title":"normalize()","navigatorTitle":[{"kind":"identifier","text":"normalize"}],"abstract":[{"text":"Clips the receiver the unit space {0, 0} - {1, 1}.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/absolutePoint(fromNormalizedPoint:with:)":{"title":"absolutePoint(fromNormalizedPoint:with:)","navigatorTitle":[{"kind":"identifier","text":"absolutePointFromNormalizedPoint:withSize:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"absolutePoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromNormalizedPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePoint(fromNormalizedPoint:with:)","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/absolutepoint(fromnormalizedpoint:with:)","abstract":[{"type":"text","text":"Helper method to transform an absolute point to the normalized unit coordinate system with given size."}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/debugDescription":{"fragments":[{"kind":"identifier","text":"debugDescription"}],"type":"topic","title":"debugDescription","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/debugDescription","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/debugdescription"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"role":"symbol","title":"SBSDKPolygon","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/rotateCCW(_:)":{"type":"topic","abstract":[{"text":"Performs times counter-clockwise rotations on the receiver.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"rotateCCW:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/rotateccw(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/rotateCCW(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotateCCW","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"title":"rotateCCW(_:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/bezierPath(with:for:orientation:isFrontCamera:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoPreviewLayer","preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIDeviceOrientation","kind":"typeIdentifier","text":"UIDeviceOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isFrontCamera"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)","abstract":[{"text":"Creates a UIBezierPath instance of the receiver for drawing purposes.","type":"text"}],"title":"bezierPath(with:for:orientation:isFrontCamera:)","navigatorTitle":[{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(with:for:orientation:isfrontcamera:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/isSimilar(to:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSimilar"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isSimilar(to:)","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/issimilar(to:)","navigatorTitle":[{"kind":"identifier","text":"isSimilarToPolygon:"}],"abstract":[{"type":"text","text":"Compares the receiver to another instance of SBSDKPolygon."}],"role":"symbol","title":"isSimilar(to:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/isEqual:":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isEqual:","kind":"symbol","title":"isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/isequal:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/normalizedDoubleValues()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedDoubleValues()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"normalizedDoubleValues"}],"kind":"symbol","type":"topic","title":"normalizedDoubleValues()","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/normalizeddoublevalues()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedDoubleValues"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"]"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init(metadataObject:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init(metadataobject:)","role":"symbol","title":"init(metadataObject:)","navigatorTitle":[{"text":"initWithMetadataObject:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(metadataObject:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"metadataObject","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVMetadataMachineReadableCodeObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVMetadataMachineReadableCodeObject"},{"text":")","kind":"text"}],"abstract":[{"text":"One of the designated initializer methods.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/boundingBox(with:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"boundingBox"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"navigatorTitle":[{"kind":"identifier","text":"boundingBoxWithSize:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/boundingBox(with:)","abstract":[{"type":"text","text":"Returns the axis-oriented bounding box of the receiver."}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/boundingbox(with:)","type":"topic","role":"symbol","title":"boundingBox(with:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/detectionStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/detectionStatus","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/detectionstatus","abstract":[{"text":"When polygon was detected: contains the detection status of the receiver.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus"}],"title":"detectionStatus","navigatorTitle":[{"text":"detectionStatus","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init(normalizedPointA:pointB:pointC:pointD:)":{"abstract":[{"type":"text","text":"One of the designated initializer methods."}],"title":"init(normalizedPointA:pointB:pointC:pointD:)","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizedpointa:pointb:pointc:pointd:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"normalizedPointA"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pointB"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pointC"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pointD"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedPointA:pointB:pointC:pointD:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithNormalizedPointA:pointB:pointC:pointD:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/widthPercentage":{"title":"widthPercentage","abstract":[{"type":"text","text":"When polygon was detected: contains the percentual width of the receiver in the image."}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/widthpercentage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthPercentage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/widthPercentage","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"widthPercentage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/heightPercentage":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightPercentage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/heightPercentage","kind":"symbol","type":"topic","abstract":[{"text":"When polygon was detected: contains the percentual height of the receiver in the image.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/heightpercentage","title":"heightPercentage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"heightPercentage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init(from:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(from:)","kind":"symbol","title":"init(from:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init(from:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"title":"init","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init(normalizedDoubleValues:)":{"navigatorTitle":[{"text":"initWithNormalizedDoubleValues:","kind":"identifier"}],"abstract":[{"type":"text","text":"One of the designated initializer methods."}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizeddoublevalues:)","title":"init(normalizedDoubleValues:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedDoubleValues:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"normalizedDoubleValues","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/setNormalizedPoint(_:for:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/setnormalizedpoint(_:for:)","abstract":[{"type":"text","text":"Sets the receivers point at the given index to the value of point."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNormalizedPoint"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/setNormalizedPoint(_:for:)","title":"setNormalizedPoint(_:for:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setNormalizedPoint:forIndex:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/isValid":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isValid","abstract":[{"text":"Determines if the polygon is valid.","type":"text"}],"navigatorTitle":[{"text":"isValid","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/isvalid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isValid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isValid"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/isEqual(to:)":{"title":"isEqual(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier","text":"SBSDKPolygon"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqualToPolygon:"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/isequal(to:)","abstract":[{"text":"Compares the receiver to another instance of ","type":"text"},{"code":"SBSDKPolygon","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isEqual(to:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/center()":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/center()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"}],"abstract":[{"text":"Calculates the geometric center (mass point) of the polygon in normalized unit coordinates.","type":"text"}],"navigatorTitle":[{"text":"center","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/center()","title":"center()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/normalizedPoint(with:)":{"title":"normalizedPoint(with:)","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/normalizedpoint(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedPoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"type":"text","text":"Returns the normalized point at the given index."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedPoint(with:)","navigatorTitle":[{"kind":"identifier","text":"normalizedPointWithIndex:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/normalizedPoint(fromAbsolutePoint:with:)":{"navigatorTitle":[{"kind":"identifier","text":"normalizedPointFromAbsolutePoint:withSize:"}],"abstract":[{"type":"text","text":"Helper method to transform a normalized point to an absolute coordinate system with given size."}],"role":"symbol","title":"normalizedPoint(fromAbsolutePoint:with:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedPoint(fromAbsolutePoint:with:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalizedPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAbsolutePoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/normalizedpoint(fromabsolutepoint:with:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/absolutePointsWith:":{"fragments":[{"text":"- ","kind":"text"},{"text":"absolutePointsWith:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/absolutepointswith:","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"absolutePointsWith:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePointsWith:","abstract":[],"title":"absolutePointsWith:"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/absoluteEdge(with:for:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absoluteEdge(with:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"absoluteEdge","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegment","text":"SBSDKLineSegment","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"absoluteEdgeWithIndex:forSize:"}],"abstract":[{"type":"text","text":"Returns the absolute edge at the given index."}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/absoluteedge(with:for:)","type":"topic","role":"symbol","title":"absoluteEdge(with:for:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/detectionScore":{"abstract":[{"type":"text","text":"When polygon was detected: contains the detection score of the receiver."}],"navigatorTitle":[{"kind":"identifier","text":"detectionScore"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/detectionScore","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/detectionscore","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"detectionScore"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/bezierPath(for:)-gke8":{"title":"bezierPath(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","text":"AVCaptureVideoPreviewLayer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:)-gke8","abstract":[{"text":"Creates a UIBezierPath instance of the receiver for drawing purposes.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:)-gke8","navigatorTitle":[{"text":"bezierPathForPreviewLayer:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/rotateCW(_:)":{"role":"symbol","abstract":[{"text":"Performs times clockwise rotations on the receiver.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/rotateCW(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateCW"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"rotateCW:"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/rotatecw(_:)","title":"rotateCW(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/setAbsolutePoint(point:with:for:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAbsolutePoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"point","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setAbsolutePointWithPoint:with:for:","kind":"identifier"}],"title":"setAbsolutePoint(point:with:for:)","abstract":[{"type":"text","text":"Sets the receivers point at the given index to the normalized value of point."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/setAbsolutePoint(point:with:for:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/setabsolutepoint(point:with:for:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/flipVertically()":{"type":"topic","title":"flipVertically()","role":"symbol","abstract":[{"text":"Performs a vertical flip of the polygon points.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/flipvertically()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/flipVertically()","navigatorTitle":[{"text":"flipVertically","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flipVertically","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init(normalizedRect:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"normalizedRect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithNormalizedRect:","kind":"identifier"}],"title":"init(normalizedRect:)","abstract":[{"type":"text","text":"One of the designated initializer methods."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedRect:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizedrect:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/standardDeviation(to:)":{"title":"standardDeviation(to:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardDeviation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"standardDeviationTo:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/standardDeviation(to:)","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/standarddeviation(to:)","kind":"symbol","abstract":[{"type":"text","text":"Calculates the standard deviation in the corresponding points of the receiver and the given "},{"type":"codeVoice","code":"SBSDKPolygon"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/bezierPath(for:cornerRadius:with:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezierPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGAffineTransform","kind":"typeIdentifier","text":"CGAffineTransform"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"navigatorTitle":[{"kind":"identifier","text":"bezierPathForSize:cornerRadius:withTransform:"}],"kind":"symbol","title":"bezierPath(for:cornerRadius:with:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:cornerRadius:with:)","abstract":[{"type":"text","text":"Creates a UIBezierPath instance of the receiver for drawing purposes."}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:cornerradius:with:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/bezierPath(for:)-9hkfo":{"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/bezierpath(for:)-9hkfo","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bezierPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"bezierPathForSize:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a UIBezierPath instance of the receiver for drawing purposes."}],"title":"bezierPath(for:)","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:)-9hkfo","role":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/isConvex":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isConvex"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isConvex","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/isconvex","abstract":[{"text":"Checks if the polygon is convex by verifying that all cross products have the same sign.","type":"text"}],"kind":"symbol","title":"isConvex","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConvex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/sortClockwise()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sortClockwise","kind":"identifier"},{"text":"()","kind":"text"}],"title":"sortClockwise()","abstract":[{"type":"text","text":"Orders the receivers points in clockwise order. The first point is the point right next to 12 o’clock."}],"type":"topic","navigatorTitle":[{"text":"sortClockwise","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/sortclockwise()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/sortClockwise()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeWhenApplying","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"focalLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"sensorWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"kind":"symbol","title":"sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/sizewhenapplying(to:imagescale:focallength:sensorwidth:)","navigatorTitle":[{"text":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:","kind":"identifier"}],"abstract":[{"type":"text","text":"Calculates the estimated size of the perspective-corrected and cropped image when applying the receiver to an image with given size."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/flipHorizontally()":{"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/fliphorizontally()","abstract":[{"type":"text","text":"Performs a horizontal flip of the polygon points."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/flipHorizontally()","role":"symbol","title":"flipHorizontally()","type":"topic","navigatorTitle":[{"text":"flipHorizontally","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flipHorizontally","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/normalizedEdge(with:)":{"abstract":[{"type":"text","text":"Returns the normalized edge at the given index."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedEdge(with:)","type":"topic","title":"normalizedEdge(with:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/normalizededge(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalizedEdge","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKLineSegment","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLineSegment","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"normalizedEdgeWithIndex:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/copyWithZone:":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/copywithzone:","title":"copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/absolutePoint(with:for:)":{"navigatorTitle":[{"text":"absolutePointWithIndex:forSize:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePoint(with:for:)","abstract":[{"type":"text","text":"Returns the absolute point at the given index."}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/absolutepoint(with:for:)","title":"absolutePoint(with:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"absolutePoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init(absolutePointA:pointB:pointC:pointD:for:)":{"abstract":[{"type":"text","text":"One of the designated initializer methods."}],"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"absolutePointA","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pointB","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pointC","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pointD","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(absolutePointA:pointB:pointC:pointD:for:)","url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init(absolutepointa:pointb:pointc:pointd:for:)","title":"init(absolutePointA:pointB:pointC:pointD:for:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPolygon"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/debugDescription","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/detectionScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/detectionStatus","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/heightPercentage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isConvex","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isNormalized","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isValid","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/widthPercentage"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absoluteEdge(with:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePoint(with:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePointsWith:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:)-9hkfo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:)-gke8","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(for:cornerRadius:with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/bezierPath(with:for:orientation:isFrontCamera:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/boundingBox(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/center()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/flipHorizontally()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/flipVertically()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(absolutePointA:pointB:pointC:pointD:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(metadataObject:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedDoubleValues:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedPointA:pointB:pointC:pointD:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedRect:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isEqual(to:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/isSimilar(to:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalize()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedDoubleValues()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedEdge(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedPoint(with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/rotateCCW(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/rotateCW(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/setAbsolutePoint(point:with:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/setNormalizedPoint(_:for:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/sortClockwise()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/standardDeviation(to:)"]},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/absolutePoint(fromNormalizedPoint:with:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedPoint(fromAbsolutePoint:with:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isNormalized\/title","op":"replace","value":"isNormalized"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isNormalized\/fragments","op":"replace","value":[{"text":"isNormalized","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalize()\/title","op":"replace","value":"normalize"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalize()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"normalize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1absolutePoint(fromNormalizedPoint:with:)\/title","op":"replace","value":"absolutePointFromNormalizedPoint:withSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1absolutePoint(fromNormalizedPoint:with:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"absolutePointFromNormalizedPoint:withSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","op":"replace","value":"SBSDKPolygon"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPolygon"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1rotateCCW(_:)\/title","op":"replace","value":"rotateCCW:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1rotateCCW(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rotateCCW:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(with:for:orientation:isFrontCamera:)\/title","op":"replace","value":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(with:for:orientation:isFrontCamera:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bezierPathWithCornerRadius:forPreviewLayer:orientation:isFrontCamera:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isSimilar(to:)\/title","op":"replace","value":"isSimilarToPolygon:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isSimilar(to:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isSimilarToPolygon:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedDoubleValues()\/title","op":"replace","value":"normalizedDoubleValues"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedDoubleValues()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"normalizedDoubleValues","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(metadataObject:)\/title","op":"replace","value":"initWithMetadataObject:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(metadataObject:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMetadataObject:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1boundingBox(with:)\/title","op":"replace","value":"boundingBoxWithSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1boundingBox(with:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"boundingBoxWithSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1detectionStatus\/title","op":"replace","value":"detectionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1detectionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"detectionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedPointA:pointB:pointC:pointD:)\/title","op":"replace","value":"initWithNormalizedPointA:pointB:pointC:pointD:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedPointA:pointB:pointC:pointD:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNormalizedPointA:pointB:pointC:pointD:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1widthPercentage\/title","op":"replace","value":"widthPercentage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1widthPercentage\/fragments","op":"replace","value":[{"text":"widthPercentage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1heightPercentage\/title","op":"replace","value":"heightPercentage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1heightPercentage\/fragments","op":"replace","value":[{"text":"heightPercentage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedDoubleValues:)\/title","op":"replace","value":"initWithNormalizedDoubleValues:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedDoubleValues:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNormalizedDoubleValues:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1setNormalizedPoint(_:for:)\/title","op":"replace","value":"setNormalizedPoint:forIndex:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1setNormalizedPoint(_:for:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNormalizedPoint:forIndex:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isValid\/title","op":"replace","value":"isValid"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isValid\/fragments","op":"replace","value":[{"text":"isValid","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isEqual(to:)\/title","op":"replace","value":"isEqualToPolygon:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isEqual(to:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqualToPolygon:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1center()\/title","op":"replace","value":"center"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1center()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"center"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedPoint(with:)\/title","op":"replace","value":"normalizedPointWithIndex:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedPoint(with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"normalizedPointWithIndex:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedPoint(fromAbsolutePoint:with:)\/title","op":"replace","value":"normalizedPointFromAbsolutePoint:withSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedPoint(fromAbsolutePoint:with:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"normalizedPointFromAbsolutePoint:withSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1absoluteEdge(with:for:)\/title","op":"replace","value":"absoluteEdgeWithIndex:forSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1absoluteEdge(with:for:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"absoluteEdgeWithIndex:forSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1detectionScore\/title","op":"replace","value":"detectionScore"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1detectionScore\/fragments","op":"replace","value":[{"text":"detectionScore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:)-gke8\/title","op":"replace","value":"bezierPathForPreviewLayer:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:)-gke8\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bezierPathForPreviewLayer:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1rotateCW(_:)\/title","op":"replace","value":"rotateCW:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1rotateCW(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rotateCW:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1setAbsolutePoint(point:with:for:)\/title","op":"replace","value":"setAbsolutePointWithPoint:with:for:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1setAbsolutePoint(point:with:for:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAbsolutePointWithPoint:with:for:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1flipVertically()\/title","op":"replace","value":"flipVertically"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1flipVertically()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"flipVertically","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedRect:)\/title","op":"replace","value":"initWithNormalizedRect:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedRect:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNormalizedRect:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1standardDeviation(to:)\/title","op":"replace","value":"standardDeviationTo:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1standardDeviation(to:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"standardDeviationTo:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:cornerRadius:with:)\/title","op":"replace","value":"bezierPathForSize:cornerRadius:withTransform:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:cornerRadius:with:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bezierPathForSize:cornerRadius:withTransform:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:)-9hkfo\/title","op":"replace","value":"bezierPathForSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1bezierPath(for:)-9hkfo\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"bezierPathForSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isConvex\/title","op":"replace","value":"isConvex"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1isConvex\/fragments","op":"replace","value":[{"kind":"identifier","text":"isConvex"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1sortClockwise()\/title","op":"replace","value":"sortClockwise"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1sortClockwise()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sortClockwise","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)\/title","op":"replace","value":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1sizeWhenApplying(to:imageScale:focalLength:sensorWidth:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeWhenApplyingToImageOfSize:imageScale:focalLength:sensorWidth:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1flipHorizontally()\/title","op":"replace","value":"flipHorizontally"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1flipHorizontally()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"flipHorizontally"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedEdge(with:)\/title","op":"replace","value":"normalizedEdgeWithIndex:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedEdge(with:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"normalizedEdgeWithIndex:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1absolutePoint(with:for:)\/title","op":"replace","value":"absolutePointWithIndex:forSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1absolutePoint(with:for:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"absolutePointWithIndex:forSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(absolutePointA:pointB:pointC:pointD:for:)\/title","op":"replace","value":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(absolutePointA:pointB:pointC:pointD:for:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAbsolutePointA:pointB:pointC:pointD:forSize:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}