{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeFormatCodabarConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/init()"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/enableOneDBlurScanner","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/maximumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/minimumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/returnStartEnd"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Class","title":"SBSDKBarcodeFormatCodabarConfiguration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCodabarConfiguration","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration"},"sections":[],"abstract":[{"type":"text","text":"Codabar barcode configuration. Add to scanner configuration to scan Codabar barcodes."}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/isequal:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/isEqual:","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration":{"abstract":[{"text":"Codabar barcode configuration. Add to scanner configuration to scan Codabar barcodes.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration","title":"SBSDKBarcodeFormatCodabarConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/new":{"title":"new","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"new"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/new","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/new","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/enableOneDBlurScanner":{"abstract":[{"text":"If true, the scanner will try extra-hard to scan barcodes with heavy blur or that are otherwise damaged.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableOneDBlurScanner"}],"kind":"symbol","title":"enableOneDBlurScanner","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/enableOneDBlurScanner","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableOneDBlurScanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/enableonedblurscanner"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/copywithzone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","title":"copyWithZone:","abstract":[],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/toJson(configuration:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/toJson(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/tojson(configuration:)","title":"toJson(configuration:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/returnStartEnd":{"abstract":[{"type":"text","text":"If true, return the start and end characters."}],"navigatorTitle":[{"kind":"identifier","text":"returnStartEnd"}],"kind":"symbol","title":"returnStartEnd","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnStartEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/returnStartEnd","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/returnstartend","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatOneDConfigurationBase":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatonedconfigurationbase","navigatorTitle":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","title":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"symbol","type":"topic","abstract":[{"text":"Base class for all linear (1D) barcode configurations.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/maximumTextLength":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/maximumTextLength","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"maximumTextLength"}],"role":"symbol","title":"maximumTextLength","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/maximumtextlength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTextLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[{"type":"text","text":"Maximum text length. 0 implies no maximum. Applied only to linear barcode formats that allow variable length."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:minimumTextLength:maximumTextLength:enableOneDBlurScanner:returnStartEnd:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:minimumTextLength:maximumTextLength:enableOneDBlurScanner:returnStartEnd:","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:onedconfirmationmode:minimumtextlength:maximumtextlength:enableonedblurscanner:returnstartend:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:minimumTextLength:maximumTextLength:enableOneDBlurScanner:returnStartEnd:"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:minimumTextLength:maximumTextLength:enableOneDBlurScanner:returnStartEnd:","navigatorTitle":[{"kind":"identifier","text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:minimumTextLength:maximumTextLength:enableOneDBlurScanner:returnStartEnd:"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/hash":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/hash","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/init()":{"title":"init()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/init()","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/fromJsonWithJson:":{"title":"fromJsonWithJson:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/fromJsonWithJson:","kind":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCodabarConfiguration/minimumTextLength":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcodabarconfiguration\/minimumtextlength","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"minimumTextLength","abstract":[{"text":"Minimum text length. Applied only to linear barcode formats that allow variable length.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/minimumTextLength","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minimumTextLength"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeFormatCodabarConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/enableOneDBlurScanner","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/maximumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/minimumTextLength","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/returnStartEnd"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:minimumTextLength:maximumTextLength:enableOneDBlurScanner:returnStartEnd:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/fromJsonWithJson:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCodabarConfiguration\/new"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatOneDConfigurationBase"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatCodabarConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCodabarConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCodabarConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1enableOneDBlurScanner\/title","value":"enableOneDBlurScanner","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1enableOneDBlurScanner\/fragments","value":[{"kind":"identifier","text":"enableOneDBlurScanner"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1toJson(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1returnStartEnd\/title","value":"returnStartEnd","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1returnStartEnd\/fragments","value":[{"kind":"identifier","text":"returnStartEnd"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/title","value":"SBSDKBarcodeFormatOneDConfigurationBase","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/fragments","value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1maximumTextLength\/title","value":"maximumTextLength","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1maximumTextLength\/fragments","value":[{"kind":"identifier","text":"maximumTextLength"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1minimumTextLength\/title","value":"minimumTextLength","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCodabarConfiguration~1minimumTextLength\/fragments","value":[{"text":"minimumTextLength","kind":"identifier"}],"op":"replace"}]}]}