{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAESEncrypter(py)mode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"text":"SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAESEncrypterMode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"mode","kind":"identifier"}],"symbolKind":"property","title":"mode","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter\/mode"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter\/mode"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter\/mode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The encryption mode used by the encrypter."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypterMode","kind":"typeIdentifier","text":"SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAESEncrypterMode"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypter":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","kind":"symbol","role":"symbol","title":"SBSDKAESEncrypter","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKAESEncrypter","kind":"identifier"}],"abstract":[{"text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypter/mode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter\/mode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter\/mode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAESEncrypterMode","kind":"typeIdentifier","text":"SBSDKAESEncrypterMode"}],"abstract":[{"text":"The encryption mode used by the encrypter.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"mode","kind":"identifier"}],"title":"mode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypterMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypterMode","kind":"symbol","role":"symbol","title":"SBSDKAESEncrypterMode","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencryptermode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"abstract":[{"type":"text","text":"An enum containing the available encryption modes for the "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","type":"reference","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"mode","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"mode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypterMode","kind":"typeIdentifier","text":"SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAESEncrypterMode"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKAESEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/title"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/navigatorTitle","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter~1mode\/title","value":"mode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}]},{"op":"replace","value":"SBSDKAESEncrypterMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypterMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypterMode\/fragments","value":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypterMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}