{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherAccident","kind":"identifier"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"otherAccident","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateCheckBoxType@SBSDKMedicalCertificateCheckBoxTypeOtherAccident","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMedicalCertificateCheckBoxType.otherAccident"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/otheraccident"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/otheraccident"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"text":"(Form 1) Other accident (Sonstiger Unfall, Unfallfolgen) checkbox.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/otherAccident"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/otherAccident":{"title":"SBSDKMedicalCertificateCheckBoxType.otherAccident","abstract":[{"text":"(Form 1) Other accident (Sonstiger Unfall, Unfallfolgen) checkbox.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/otheraccident","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherAccident","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/otherAccident","role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType":{"kind":"symbol","type":"topic","title":"SBSDKMedicalCertificateCheckBoxType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype","role":"symbol","abstract":[{"text":"Type of the checkbox.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1otherAccident\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeOtherAccident"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1otherAccident\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/title","value":"SBSDKMedicalCertificateCheckBoxType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/fragments","value":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}