{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingOverlayConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerconfiguration\/trackingoverlayconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerconfiguration\/trackingoverlayconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerConfiguration\/trackingOverlayConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The configuration for the tracked barcodes overlay."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"trackingOverlayConfiguration"}],"role":"symbol","title":"trackingOverlayConfiguration","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingOverlayConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration"}],"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerConfiguration(py)trackingOverlayConfiguration","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerConfiguration/trackingOverlayConfiguration":{"deprecated":true,"role":"symbol","title":"trackingOverlayConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingOverlayConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration"}],"abstract":[{"type":"text","text":"The configuration for the tracked barcodes overlay."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerConfiguration\/trackingOverlayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingOverlayConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerconfiguration\/trackingoverlayconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerConfiguration":{"deprecated":true,"role":"symbol","title":"SBSDKUIBarcodesBatchScannerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerConfiguration"}],"abstract":[{"type":"text","text":"This class describes the look and feel, as well as the textual contents of the RTU-UI batch barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeTrackingOverlayConfiguration":{"deprecated":true,"role":"symbol","title":"SBSDKUIBarcodeTrackingOverlayConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"abstract":[{"type":"text","text":"The configuration object for the RTU-UI barcode tracking overlay."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodetrackingoverlayconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"trackingOverlayConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"trackingOverlayConfiguration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"trackingOverlayConfiguration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerConfiguration~1trackingOverlayConfiguration\/title","value":"trackingOverlayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerConfiguration~1trackingOverlayConfiguration\/fragments","value":[{"kind":"identifier","text":"trackingOverlayConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerConfiguration\/title","value":"SBSDKUIBarcodesBatchScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/title","value":"SBSDKUIBarcodeTrackingOverlayConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}