{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat\/Equatable-Implementations"},"sections":[],"topicSections":[{"anchor":"Operators","title":"Operators","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat\/!=(_:_:)"]}],"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup"},"kind":"article","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDialogFormat/!=(_:_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat\/!=(_:_:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"!=(_:_:)","type":"topic","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDialogFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDialogFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat","navigatorTitle":[{"text":"SBSDKBarcodeDialogFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"The barcode dialog text format."}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKBarcodeDialogFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat\/title","op":"replace","value":"SBSDKBarcodeDialogFormat"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDialogFormat"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat\/navigatorTitle","value":[{"text":"SBSDKBarcodeDialogFormat","kind":"identifier"}]}]}]}