{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"typeAndCode","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat\/typeandcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat\/typeandcode"]}],"abstract":[{"type":"text","text":"Shows the barcode type and value."}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKBarcodeDialogFormat.typeAndCode","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"typeAndCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDialogFormatTypeAndCode"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeDialogFormat@SBSDKBarcodeDialogFormatTypeAndCode","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat\/typeAndCode"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDialogFormat/typeAndCode":{"type":"topic","abstract":[{"type":"text","text":"Shows the barcode type and value."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typeAndCode"}],"navigatorTitle":[{"text":"SBSDKBarcodeDialogFormatTypeAndCode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat\/typeAndCode","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat\/typeandcode","kind":"symbol","role":"symbol","title":"SBSDKBarcodeDialogFormat.typeAndCode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDialogFormat":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDialogFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDialogFormat","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat","title":"SBSDKBarcodeDialogFormat","type":"topic","abstract":[{"type":"text","text":"The barcode dialog text format."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKBarcodeDialogFormatTypeAndCode","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDialogFormatTypeAndCode"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKBarcodeDialogFormatTypeAndCode","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat~1typeAndCode\/title","value":"SBSDKBarcodeDialogFormatTypeAndCode"},{"value":[{"text":"SBSDKBarcodeDialogFormatTypeAndCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat~1typeAndCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat\/title","value":"SBSDKBarcodeDialogFormat"},{"op":"replace","value":[{"text":"SBSDKBarcodeDialogFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat\/fragments"}]}]}