{"abstract":[{"text":"Document type name of the “DeDriverLicenseBack.Categories.AM” document type.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"amDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/amDocumentType"},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"amDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","title":"amDocumentType","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"amDocumentType"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentConstants(cpy)amDocumentType"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/amdocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/amdocumenttype"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants/amDocumentType":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"amDocumentType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"Document type name of the “DeDriverLicenseBack.Categories.AM” document type."}],"title":"amDocumentType","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"amDocumentType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/amdocumenttype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/amDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants","navigatorTitle":[{"text":"SBSDKGenericDocumentConstants","kind":"identifier"}],"title":"SBSDKGenericDocumentConstants","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentConstants","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"amDocumentType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"amDocumentType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"amDocumentType"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1amDocumentType\/title","op":"replace","value":"amDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1amDocumentType\/fragments","value":[{"text":"amDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/title","op":"replace","value":"SBSDKGenericDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}