{"abstract":[{"type":"text","text":"Document type name of the “DeResidencePermitBack” document type."}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"deResidencePermitBackDocumentType"}],"roleHeading":"Type Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentConstants(cpy)deResidencePermitBackDocumentType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deResidencePermitBackDocumentType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"deResidencePermitBackDocumentType"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/deResidencePermitBackDocumentType"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/deresidencepermitbackdocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/deresidencepermitbackdocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deResidencePermitBackDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentConstants","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}],"kind":"symbol","title":"SBSDKGenericDocumentConstants","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants/deResidencePermitBackDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/deresidencepermitbackdocumenttype","abstract":[{"type":"text","text":"Document type name of the “DeResidencePermitBack” document type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/deResidencePermitBackDocumentType","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deResidencePermitBackDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","title":"deResidencePermitBackDocumentType","kind":"symbol","navigatorTitle":[{"text":"deResidencePermitBackDocumentType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"deResidencePermitBackDocumentType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"deResidencePermitBackDocumentType","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"deResidencePermitBackDocumentType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/title","op":"replace","value":"SBSDKGenericDocumentConstants"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/fragments"},{"op":"replace","value":"deResidencePermitBackDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1deResidencePermitBackDocumentType\/title"},{"op":"replace","value":[{"text":"deResidencePermitBackDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1deResidencePermitBackDocumentType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}