{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deResidencePermitFrontBirthDateFieldNormalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"abstract":[{"text":"Normalized full name of the “BirthDate” field type in document type “DeResidencePermitFront”.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/deresidencepermitfrontbirthdatefieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/deresidencepermitfrontbirthdatefieldnormalizedname"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/deResidencePermitFrontBirthDateFieldNormalizedName","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"deResidencePermitFrontBirthDateFieldNormalizedName"}],"symbolKind":"property","title":"deResidencePermitFrontBirthDateFieldNormalizedName","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentConstants(cpy)deResidencePermitFrontBirthDateFieldNormalizedName","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deResidencePermitFrontBirthDateFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Type Property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants":{"navigatorTitle":[{"text":"SBSDKGenericDocumentConstants","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants","title":"SBSDKGenericDocumentConstants","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants/deResidencePermitFrontBirthDateFieldNormalizedName":{"navigatorTitle":[{"kind":"identifier","text":"deResidencePermitFrontBirthDateFieldNormalizedName"}],"kind":"symbol","title":"deResidencePermitFrontBirthDateFieldNormalizedName","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/deresidencepermitfrontbirthdatefieldnormalizedname","abstract":[{"type":"text","text":"Normalized full name of the “BirthDate” field type in document type “DeResidencePermitFront”."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"deResidencePermitFrontBirthDateFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/deResidencePermitFrontBirthDateFieldNormalizedName"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"deResidencePermitFrontBirthDateFieldNormalizedName"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"deResidencePermitFrontBirthDateFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"deResidencePermitFrontBirthDateFieldNormalizedName"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/title","value":"SBSDKGenericDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/fragments","value":[{"text":"SBSDKGenericDocumentConstants","kind":"identifier"}],"op":"replace"},{"value":"deResidencePermitFrontBirthDateFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1deResidencePermitFrontBirthDateFieldNormalizedName\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1deResidencePermitFrontBirthDateFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"deResidencePermitFrontBirthDateFieldNormalizedName"}]}]}]}