{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/europeanHealthInsuranceCardCardNumberFieldNormalizedName"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants"]]},"kind":"symbol","abstract":[{"type":"text","text":"Normalized full name of the “CardNumber” field type in document type “EuropeanHealthInsuranceCard”."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/europeanhealthinsurancecardcardnumberfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/europeanhealthinsurancecardcardnumberfieldnormalizedname"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanHealthInsuranceCardCardNumberFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"europeanHealthInsuranceCardCardNumberFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"europeanHealthInsuranceCardCardNumberFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentConstants(cpy)europeanHealthInsuranceCardCardNumberFieldNormalizedName","navigatorTitle":[{"kind":"identifier","text":"europeanHealthInsuranceCardCardNumberFieldNormalizedName"}],"role":"symbol","symbolKind":"property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants/europeanHealthInsuranceCardCardNumberFieldNormalizedName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/europeanHealthInsuranceCardCardNumberFieldNormalizedName","title":"europeanHealthInsuranceCardCardNumberFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"europeanHealthInsuranceCardCardNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"Normalized full name of the “CardNumber” field type in document type “EuropeanHealthInsuranceCard”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"europeanHealthInsuranceCardCardNumberFieldNormalizedName"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/europeanhealthinsurancecardcardnumberfieldnormalizedname","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentConstants","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"SBSDKGenericDocumentConstants","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"europeanHealthInsuranceCardCardNumberFieldNormalizedName"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"europeanHealthInsuranceCardCardNumberFieldNormalizedName"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"europeanHealthInsuranceCardCardNumberFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1europeanHealthInsuranceCardCardNumberFieldNormalizedName\/title","value":"europeanHealthInsuranceCardCardNumberFieldNormalizedName","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"europeanHealthInsuranceCardCardNumberFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1europeanHealthInsuranceCardCardNumberFieldNormalizedName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/title","op":"replace","value":"SBSDKGenericDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}