{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/mDocumentType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Property","role":"symbol","title":"mDocumentType","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentConstants(cpy)mDocumentType","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"mDocumentType"}]},"abstract":[{"text":"Document type name of the “DeDriverLicenseBack.Categories.M” document type.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/mdocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/mdocumenttype"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants/mDocumentType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/mDocumentType","abstract":[{"text":"Document type name of the “DeDriverLicenseBack.Categories.M” document type.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/mdocumenttype","role":"symbol","title":"mDocumentType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mDocumentType"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"mDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants","role":"symbol","title":"SBSDKGenericDocumentConstants","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"mDocumentType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"mDocumentType"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"mDocumentType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"mDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1mDocumentType\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1mDocumentType\/fragments","value":[{"kind":"identifier","text":"mDocumentType"}]},{"op":"replace","value":"SBSDKGenericDocumentConstants","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/fragments","value":[{"text":"SBSDKGenericDocumentConstants","kind":"identifier"}]}]}]}