{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzCheckDigitDocumentNumberFieldNormalizedName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/mrzCheckDigitDocumentNumberFieldNormalizedName","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/mrzcheckdigitdocumentnumberfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/mrzcheckdigitdocumentnumberfieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Normalized full name of the “CheckDigitDocumentNumber” field type in document type “MRZ”.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants"]]},"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"mrzCheckDigitDocumentNumberFieldNormalizedName"}],"title":"mrzCheckDigitDocumentNumberFieldNormalizedName","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentConstants(cpy)mrzCheckDigitDocumentNumberFieldNormalizedName","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"mrzCheckDigitDocumentNumberFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants/mrzCheckDigitDocumentNumberFieldNormalizedName":{"navigatorTitle":[{"text":"mrzCheckDigitDocumentNumberFieldNormalizedName","kind":"identifier"}],"title":"mrzCheckDigitDocumentNumberFieldNormalizedName","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants\/mrzcheckdigitdocumentnumberfieldnormalizedname","role":"symbol","kind":"symbol","abstract":[{"text":"Normalized full name of the “CheckDigitDocumentNumber” field type in document type “MRZ”.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants\/mrzCheckDigitDocumentNumberFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrzCheckDigitDocumentNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentConstants":{"type":"topic","abstract":[],"title":"SBSDKGenericDocumentConstants","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentconstants","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentConstants","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"mrzCheckDigitDocumentNumberFieldNormalizedName","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"mrzCheckDigitDocumentNumberFieldNormalizedName","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mrzCheckDigitDocumentNumberFieldNormalizedName"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1mrzCheckDigitDocumentNumberFieldNormalizedName\/title","value":"mrzCheckDigitDocumentNumberFieldNormalizedName"},{"op":"replace","value":[{"kind":"identifier","text":"mrzCheckDigitDocumentNumberFieldNormalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants~1mrzCheckDigitDocumentNumberFieldNormalizedName\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/title","value":"SBSDKGenericDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentConstants"}],"op":"replace"}]}]}