{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration\/initwithcameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:hardwarebuttonsenabled:fpslimit:cameralivescannerresolution:"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraModule:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraModule"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomSteps:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zoomSteps"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultZoomFactor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"defaultZoomFactor"},{"kind":"text","text":" "},{"kind":"identifier","text":"flashEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"flashEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFocusDistanceLock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minFocusDistanceLock"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinchToZoomEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pinchToZoomEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKUI2OrientationLockMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2OrientationLockMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"orientationLockMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CameraPreviewMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraPreviewMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"hardwareButtonsEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hardwareButtonsEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"fpsLimit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fpsLimit"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraLiveScannerResolution:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKCameraLiveScannerResolution","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraLiveScannerResolution","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraLiveScannerResolution"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraLiveScannerResolution"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration\/initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:"},"metadata":{"navigatorTitle":[{"text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraConfiguration(im)initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","title":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:"}],"roleHeading":"Instance Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2OrientationLockMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2orientationlockmode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2OrientationLockMode","abstract":[{"text":"Configure the orientation of the interface.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2OrientationLockMode","navigatorTitle":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration/initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:":{"type":"topic","abstract":[],"title":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration\/initwithcameramodule:zoomsteps:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:orientationlockmode:camerapreviewmode:hardwarebuttonsenabled:fpslimit:cameralivescannerresolution:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration\/initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","navigatorTitle":[{"text":"initWithCameraModule:zoomSteps:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:orientationLockMode:cameraPreviewMode:hardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPreviewMode":{"kind":"symbol","title":"SBSDKUI2CameraPreviewMode","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapreviewmode","abstract":[{"type":"text","text":"Configuration of the camera preview mode."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPreviewMode","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraModule":{"navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraModule","abstract":[{"type":"text","text":"Determines which camera module to use on start-up."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameramodule","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKUI2CameraModule"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SBSDKUI2CameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraConfiguration","navigatorTitle":[{"text":"SBSDKUI2CameraConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2cameraconfiguration","abstract":[{"text":"Configuration of the camera settings to be used while scanning.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraLiveScannerResolution":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraLiveScannerResolution","url":"\/documentation\/scanbotsdk\/sbsdkcameralivescannerresolution","abstract":[{"type":"text","text":"The size of the image from camera which would be sent to the scanner for live scanning."}],"kind":"symbol","type":"topic","title":"SBSDKCameraLiveScannerResolution","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/title","value":"SBSDKUI2OrientationLockMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2OrientationLockMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2OrientationLockMode\/navigatorTitle","value":[{"text":"SBSDKUI2OrientationLockMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/title","value":"SBSDKUI2CameraPreviewMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/title","value":"SBSDKUI2CameraModule"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/fragments","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraModule\/navigatorTitle","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/title","value":"SBSDKUI2CameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraLiveScannerResolution\/title","value":"SBSDKCameraLiveScannerResolution"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraLiveScannerResolution\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}