{"abstract":[{"text":"Hide the navigation bar.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/hidden","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}],"title":"SBSDKUI2NavigationBarMode.hidden","navigatorTitle":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2NavigationBarMode@SBSDKUI2NavigationBarModeHidden","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/hidden"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/hidden"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode/hidden":{"abstract":[{"text":"Hide the navigation bar.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode\/hidden","navigatorTitle":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}],"type":"topic","title":"SBSDKUI2NavigationBarMode.hidden","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"hidden","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode\/hidden"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2NavigationBarMode":{"title":"SBSDKUI2NavigationBarMode","type":"topic","navigatorTitle":[{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2navigationbarmode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2NavigationBarMode","role":"symbol","abstract":[{"type":"text","text":"The visual mode used for the navigation bar icons. Android only."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2NavigationBarModeHidden"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2NavigationBarModeHidden"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKUI2NavigationBarModeHidden","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode~1hidden\/title"},{"value":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode~1hidden\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode\/title","value":"SBSDKUI2NavigationBarMode","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2NavigationBarMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}],"op":"replace"}]}]}