{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"new","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"title":"new","roleHeading":"Type Method","symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataMatrixConfiguration(cm)new","navigatorTitle":[{"text":"new","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatamatrixconfiguration\/new"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration\/new","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatDataMatrixConfiguration/new":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration\/new","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"title":"new","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatamatrixconfiguration\/new","navigatorTitle":[{"text":"new","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatDataMatrixConfiguration":{"title":"SBSDKBarcodeFormatDataMatrixConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatamatrixconfiguration","abstract":[{"text":"DataMatrix configuration. Add to scanner configuration to scan DataMatrix and DataMatrix rectangular extensions","type":"text"},{"text":" ","type":"text"},{"text":"(DMRE) codes.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/title","value":"SBSDKBarcodeFormatDataMatrixConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"op":"replace"}]}]}