{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/finderview(_:didchangerect:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/finderview(_:didchangerect:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/finderView(_:didChangeRect:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"]]},"metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"finderView:didChangeRect:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController(im)finderView:didChangeRect:","title":"finderView(_:didChangeRect:)","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderView","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKFinderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","text":"SBSDKFinderView","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeRect","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","title":"SBSDKFinderView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFinderView"}],"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"title":"SBSDKDocumentScannerViewController","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"type":"topic","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController/finderView(_:didChangeRect:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView"},{"text":", ","kind":"text"},{"text":"didChangeRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/finderView(_:didChangeRect:)","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"finderView:didChangeRect:"}],"kind":"symbol","title":"finderView(_:didChangeRect:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/finderview(_:didchangerect:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"finderView:didChangeRect:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"finderView:didChangeRect:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"finderView:"},{"text":"(","kind":"text"},{"text":"SBSDKFinderView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChangeRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1finderView(_:didChangeRect:)\/title","op":"replace","value":"finderView:didChangeRect:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1finderView(_:didChangeRect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finderView:didChangeRect:"}],"op":"replace"}]}]}