{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/ignoreBadAspectRatio"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/ignorebadaspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/ignorebadaspectratio"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":", the documents aspect ratio is not compared to the screens aspect ratio, the bad aspect ratio warning will never appear."}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"ignoreBadAspectRatio","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreBadAspectRatio"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController(py)ignoreBadAspectRatio","navigatorTitle":[{"text":"ignoreBadAspectRatio","kind":"identifier"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreBadAspectRatio"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"False"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"type":"topic","title":"SBSDKDocumentScannerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController/ignoreBadAspectRatio":{"navigatorTitle":[{"kind":"identifier","text":"ignoreBadAspectRatio"}],"kind":"symbol","abstract":[{"type":"text","text":"If set to "},{"code":"True","type":"codeVoice"},{"type":"text","text":", the documents aspect ratio is not compared to the screens aspect ratio, the bad aspect ratio warning will never appear."}],"title":"ignoreBadAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/ignoreBadAspectRatio","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/ignorebadaspectratio","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoreBadAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"ignoreBadAspectRatio","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"ignoreBadAspectRatio","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"ignoreBadAspectRatio","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"value":"ignoreBadAspectRatio","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1ignoreBadAspectRatio\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1ignoreBadAspectRatio\/fragments","value":[{"kind":"identifier","text":"ignoreBadAspectRatio"}]}]}]}