{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"polygonLineColorRejected","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController(py)polygonLineColorRejected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonLineColorRejected"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"polygonLineColorRejected"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/polygonLineColorRejected","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/polygonlinecolorrejected"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/polygonlinecolorrejected"]}],"abstract":[{"text":"The line color for the polygon displayed over the detected document when the document detection status is not SBSDKDocumentDetectionStatusOK.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"polygonLineColorRejected"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","kind":"symbol","title":"SBSDKDocumentScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController/polygonLineColorRejected":{"navigatorTitle":[{"text":"polygonLineColorRejected","kind":"identifier"}],"title":"polygonLineColorRejected","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/polygonLineColorRejected","abstract":[{"text":"The line color for the polygon displayed over the detected document when the document detection status is not SBSDKDocumentDetectionStatusOK.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/polygonlinecolorrejected","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonLineColorRejected","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"polygonLineColorRejected","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"polygonLineColorRejected","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"polygonLineColorRejected"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SBSDKDocumentScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1polygonLineColorRejected\/title","value":"polygonLineColorRejected"},{"value":[{"kind":"identifier","text":"polygonLineColorRejected"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1polygonLineColorRejected\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}