{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult(im)copyWithZone:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"roleHeading":"Instance Method","title":"copyWithZone:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult\/copyWithZone:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult","abstract":[{"type":"text","text":"The result of the medical certificate scanning."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScanningResult"}],"kind":"symbol","role":"symbol","title":"SBSDKMedicalCertificateScanningResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult/copyWithZone:":{"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult\/copywithzone:","title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult\/copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKMedicalCertificateScanningResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/title","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/fragments","op":"replace"},{"value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/navigatorTitle","op":"replace"}]}]}