{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/genericDocumentRecognizerViewControllerDidCancel(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"genericDocumentRecognizerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","text":"SBSDKUIGenericDocumentRecognizerViewController"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"},{"text":" that did dismiss.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Optional."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontrollerdelegate\/genericdocumentrecognizerviewcontrollerdidcancel(_:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontrollerdelegate\/genericdocumentrecognizerviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Informs the delegate that the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true,"type":"reference"},{"text":" has been cancelled and dismissed.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"required":true,"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIGenericDocumentRecognizerViewControllerDelegate(im)genericDocumentRecognizerViewControllerDidCancel:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"genericDocumentRecognizerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController"},{"kind":"text","text":")"}],"title":"genericDocumentRecognizerViewControllerDidCancel(_:)","navigatorTitle":[{"kind":"identifier","text":"genericDocumentRecognizerViewControllerDidCancel:"}],"roleHeading":"Instance Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewController"}],"role":"symbol","kind":"symbol","abstract":[{"text":"A highly customizable camera-based view controller to recognize generic documents.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontroller","type":"topic","title":"SBSDKUIGenericDocumentRecognizerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewControllerDelegate/genericDocumentRecognizerViewControllerDidCancel(_:)":{"kind":"symbol","abstract":[{"text":"Informs the delegate that the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true},{"type":"text","text":" has been cancelled and dismissed."}],"role":"symbol","title":"genericDocumentRecognizerViewControllerDidCancel(_:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/genericDocumentRecognizerViewControllerDidCancel(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"genericDocumentRecognizerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontrollerdelegate\/genericdocumentrecognizerviewcontrollerdidcancel(_:)","navigatorTitle":[{"text":"genericDocumentRecognizerViewControllerDidCancel:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerViewControllerDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"kind":"symbol","title":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewControllerDelegate","abstract":[{"text":"The delegate protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController","isActive":true},{"text":".","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"genericDocumentRecognizerViewControllerDidCancel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"genericDocumentRecognizerViewControllerDidCancel:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"genericDocumentRecognizerViewControllerDidCancel:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/title","value":"SBSDKUIGenericDocumentRecognizerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewController\/fragments","value":[{"text":"SBSDKUIGenericDocumentRecognizerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate~1genericDocumentRecognizerViewControllerDidCancel(_:)\/title","op":"replace","value":"genericDocumentRecognizerViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate~1genericDocumentRecognizerViewControllerDidCancel(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"genericDocumentRecognizerViewControllerDidCancel:"}]},{"value":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerViewControllerDelegate"}],"op":"replace"}]}]}