{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"SBSDKUI2CreditCardScannerGuidanceStates","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerGuidanceStates","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"class"},"abstract":[{"type":"text","text":"Configure the captions of the user guidance hints for different scanning states."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKUI2CreditCardScannerGuidanceStates) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}]}]}],"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/init()"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/badPerspective","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/noCardFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/scanningProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/tooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/tooSmall"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/toJson(configuration:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/noCardFound":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/noCardFound","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/nocardfound","kind":"symbol","type":"topic","title":"noCardFound","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCardFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"The user guidance text displayed when no credit card is found. Initial state."}],"navigatorTitle":[{"text":"noCardFound","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/scanningProgress":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanningProgress"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scanningProgress"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/scanningprogress","abstract":[{"type":"text","text":"The user guidance text displayed when a card presence was detected and scanning is in progress."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/scanningProgress","kind":"symbol","type":"topic","title":"scanningProgress"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/hash":{"title":"hash","kind":"symbol","type":"topic","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/hash","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates":{"navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates","type":"topic","title":"SBSDKUI2CreditCardScannerGuidanceStates","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}],"abstract":[{"text":"Configure the captions of the user guidance hints for different scanning states.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Node"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2node","abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"title":"SBSDKUI2Node","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/tooDark":{"title":"tooDark","navigatorTitle":[{"kind":"identifier","text":"tooDark"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/toodark","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The user guidance text displayed when it is too dark to capture an adequate image."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tooDark","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/tooDark"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/isEqual:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/isequal:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/isEqual:","kind":"symbol","type":"topic","title":"isEqual:"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/copyWithZone:":{"fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/copywithzone:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/copyWithZone:","kind":"symbol","type":"topic","title":"copyWithZone:"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/badPerspective":{"title":"badPerspective","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"badPerspective"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"badPerspective"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/badperspective","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/badPerspective","role":"symbol","abstract":[{"type":"text","text":"The user guidance text displayed when the detected card is not in a good perspective (device tilted)."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/init()","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/init()","kind":"symbol","type":"topic","title":"init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/fromJsonWithJson:":{"title":"fromJsonWithJson:","kind":"symbol","type":"topic","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/fromJsonWithJson:","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/toJson(configuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/tojson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/toJson(configuration:)","kind":"symbol","type":"topic","title":"toJson(configuration:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/initwithnocardfound:scanningprogress:toodark:toosmall:badperspective:","kind":"symbol","title":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerGuidanceStates/tooSmall":{"title":"tooSmall","kind":"symbol","type":"topic","navigatorTitle":[{"text":"tooSmall","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tooSmall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerguidancestates\/toosmall","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/tooSmall","role":"symbol","abstract":[{"text":"The user guidance text displayed when the detected card is too far away and appears too small.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUI2CreditCardScannerGuidanceStates","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}]},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/badPerspective","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/noCardFound","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/scanningProgress","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/tooDark","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/tooSmall"],"title":"Instance Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/initWithNoCardFound:scanningProgress:tooDark:tooSmall:badPerspective:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/toJson(configuration:)"]},{"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerGuidanceStates\/fromJsonWithJson:"],"generated":true,"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"},{"kind":"text","text":" : "},{"text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1noCardFound\/title","value":"noCardFound"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1noCardFound\/fragments","value":[{"kind":"identifier","text":"noCardFound"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1scanningProgress\/title","value":"scanningProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1scanningProgress\/fragments","value":[{"text":"scanningProgress","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2CreditCardScannerGuidanceStates","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerGuidanceStates"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerGuidanceStates","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","op":"replace","value":"SBSDKUI2Node"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1tooDark\/title","value":"tooDark"},{"op":"replace","value":[{"text":"tooDark","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1tooDark\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1badPerspective\/title","value":"badPerspective"},{"value":[{"kind":"identifier","text":"badPerspective"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1badPerspective\/fragments","op":"replace"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1init()\/fragments"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1toJson(configuration:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1toJson(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1tooSmall\/title","value":"tooSmall"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerGuidanceStates~1tooSmall\/fragments","op":"replace","value":[{"text":"tooSmall","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}