{"abstract":[{"type":"text","text":"EuropeanDriverLicenseBack.Categories.L"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategory"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/requiredDocumentType"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"class","title":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesl"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesl"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategory":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategory","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","title":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A category row from the categories table"}],"navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL":{"title":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL"}],"role":"symbol","type":"topic","abstract":[{"text":"EuropeanDriverLicenseBack.Categories.L","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesl"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL/initWithGenericDocument:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesl\/initwithgenericdocument:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/initWithGenericDocument:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"title":"initWithGenericDocument:"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL/requiredDocumentType":{"navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesl\/requireddocumenttype","title":"requiredDocumentType","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/requiredDocumentType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/requiredDocumentType"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/initWithGenericDocument:"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategory"],"type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategory"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategory\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategory\/fragments","op":"replace","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategory\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategory","kind":"identifier"}]},{"op":"replace","value":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL","kind":"identifier"}],"op":"replace"},{"value":"requiredDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL~1requiredDocumentType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesL~1requiredDocumentType\/fragments","value":[{"text":"requiredDocumentType","kind":"identifier"}],"op":"replace"}]}]}