{"kind":"symbol","topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/actionBar","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/intro","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/topBar"],"generated":true}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"abstract":[{"text":"Accessibility identifiers to be used in UI tests for the data capture scanner RTU-UI V2 (MRZ, credit card, text pattern)..","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKUI2DataCaptureAccessibility","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DataCaptureAccessibility"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/topBar":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/topBar","abstract":[],"title":"SBSDKUI2DataCaptureAccessibility.topBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"topBar","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/topbar","navigatorTitle":[{"text":"topBar","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility","type":"topic","title":"SBSDKUI2DataCaptureAccessibility","role":"symbol","abstract":[{"text":"Accessibility identifiers to be used in UI tests for the data capture scanner RTU-UI V2 (MRZ, credit card, text pattern)..","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/permission":{"navigatorTitle":[{"kind":"identifier","text":"permission"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/permission","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"permission"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/permission","title":"SBSDKUI2DataCaptureAccessibility.permission","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/actionBar":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"actionBar"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/actionBar","kind":"symbol","title":"SBSDKUI2DataCaptureAccessibility.actionBar","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/actionbar","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionBar","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/intro":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/intro","type":"topic","title":"SBSDKUI2DataCaptureAccessibility.intro","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/intro","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"intro"}],"navigatorTitle":[{"text":"intro","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKUI2DataCaptureAccessibility","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"op":"replace"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2DataCaptureAccessibility","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}]}]}]}