{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeFormatFourStateConfigurationBase) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"Base class for all four-state barcode configurations.","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"title":"SBSDKBarcodeFormatFourStateConfigurationBase","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatFourStateConfigurationBase"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalTNTPostConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","title":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodetwotrackconfiguration","abstract":[{"text":"PHARMA_CODE_TWO_TRACK barcode configuration. Add to scanner configuration to scan Laetus two-track PharmaCode","type":"text"},{"text":" ","type":"text"},{"text":"barcodes. Linear (i.e. one-track) PharmaCode scanning is configured separately through the PharmaCodeConfig class.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase","abstract":[{"text":"Base class for all four-state barcode configurations.","type":"text"}],"role":"symbol","title":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase\/tojson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"kind":"symbol","title":"toJson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase":{"title":"SBSDKBarcodeFormatConfigurationBase","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase","abstract":[{"type":"text","text":"Base class for all barcode configurations."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatAustraliaPostConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration","title":"SBSDKBarcodeFormatAustraliaPostConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatAustraliaPostConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatAustraliaPostConfiguration"}],"abstract":[{"text":"Australia Post barcode configuration. Add to scanner configuration to scan Australia Post barcodes.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformataustraliapostconfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalMailConfiguration":{"title":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Royal Mail barcode configuration. Add to scanner configuration to scan Royal Mail (a.k.a. RM4SCC, CBC, BPO 4-State)"},{"type":"text","text":" "},{"text":"barcodes.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalMailConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyalmailconfiguration"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase/isEqual:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase\/isequal:","role":"symbol","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase\/hash","role":"symbol","title":"hash","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/hash","kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatJapanPostConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatjapanpostconfiguration","kind":"symbol","title":"SBSDKBarcodeFormatJapanPostConfiguration","type":"topic","abstract":[{"text":"Japan Post barcode configuration. Add to scanner configuration to scan Japan Post barcodes.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatJapanPostConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration":{"title":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"USPS Intelligent Mail barcode configuration. Add to scanner configuration to scan USPS Intelligent Mail (a.k.a. USPS"},{"type":"text","text":" "},{"text":"OneCode, USPS-STD-11) barcodes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatuspsintelligentmailconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase/copyWithZone:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase\/copywithzone:","role":"symbol","title":"copyWithZone:","type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/copyWithZone:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatRoyalTNTPostConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Royal TNT Post barcode configuration. Add to scanner configuration to scan Royal TNT Post (a.k.a. KIX, Klant IndeX)"},{"type":"text","text":" "},{"type":"text","text":"barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalTNTPostConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration"}],"title":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatroyaltntpostconfiguration"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/fromJsonWithJson:","type":"topic","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"SBSDKBarcodeFormatFourStateConfigurationBase","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/hash"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/fromJsonWithJson:"]}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalMailConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatRoyalTNTPostConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUSPSIntelligentMailConfiguration"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatConfigurationBase","text":"SBSDKBarcodeFormatConfigurationBase"}]}],"kind":"declarations"}},{"value":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/title","value":"SBSDKBarcodeFormatFourStateConfigurationBase","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/title","value":"SBSDKBarcodeFormatConfigurationBase","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments","value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle"},{"value":"SBSDKBarcodeFormatAustraliaPostConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/title"},{"value":[{"text":"SBSDKBarcodeFormatAustraliaPostConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatAustraliaPostConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/navigatorTitle"},{"value":"SBSDKBarcodeFormatRoyalMailConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalMailConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKBarcodeFormatJapanPostConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatJapanPostConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatJapanPostConfiguration"}]},{"value":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUSPSIntelligentMailConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUSPSIntelligentMailConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUSPSIntelligentMailConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalTNTPostConfiguration\/title","value":"SBSDKBarcodeFormatRoyalTNTPostConfiguration"},{"value":[{"text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalTNTPostConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatRoyalTNTPostConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration"}],"op":"replace"}]}]}