{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration for the behavior of the machine readable zone scanner."}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/isFlashEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/isSuccessBeepEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}]}]}],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2MRZScannerViewController instead.","type":"text"}],"type":"paragraph"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"platforms":[],"symbolKind":"class","navigatorTitle":[{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}],"title":"SBSDKUIMRZScannerBehaviorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerBehaviorConfiguration","role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration","abstract":[{"text":"Configuration for the behavior of the machine readable zone scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"}],"title":"SBSDKUIMRZScannerBehaviorConfiguration","deprecated":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/isSuccessBeepEnabled":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isSuccessBeepEnabled"}],"title":"isSuccessBeepEnabled","abstract":[{"text":"Whether scanner screen should make a sound on MRZ scanning.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/issuccessbeepenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSuccessBeepEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/isSuccessBeepEnabled","role":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/maxNumberOfAccumulatedResults":{"navigatorTitle":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"role":"symbol","title":"maxNumberOfAccumulatedResults","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/maxnumberofaccumulatedresults","abstract":[{"text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxNumberOfAccumulatedResults"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"deprecated":true},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/init":{"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/init","type":"topic","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/isFlashEnabled":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFlashEnabled"}],"title":"isFlashEnabled","abstract":[{"text":"Whether flash is toggled on or off.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/isflashenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFlashEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/isFlashEnabled","role":"symbol","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerBehaviorConfiguration/requiredNumberOfEqualAccumulatedResults":{"title":"requiredNumberOfEqualAccumulatedResults","role":"symbol","deprecated":true,"abstract":[{"text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerbehaviorconfiguration\/requirednumberofequalaccumulatedresults","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults","navigatorTitle":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUIMRZScannerBehaviorConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/isFlashEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/isSuccessBeepEnabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/maxNumberOfAccumulatedResults","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/requiredNumberOfEqualAccumulatedResults"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerBehaviorConfiguration\/init"],"generated":true,"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/title","value":"SBSDKUIMRZScannerBehaviorConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerBehaviorConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIMRZScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1isSuccessBeepEnabled\/title","value":"isSuccessBeepEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1isSuccessBeepEnabled\/fragments","op":"replace","value":[{"text":"isSuccessBeepEnabled","kind":"identifier"}]},{"op":"replace","value":"maxNumberOfAccumulatedResults","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1maxNumberOfAccumulatedResults\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1maxNumberOfAccumulatedResults\/fragments","value":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}]},{"op":"replace","value":"isFlashEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1isFlashEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isFlashEnabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1isFlashEnabled\/fragments"},{"value":"requiredNumberOfEqualAccumulatedResults","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1requiredNumberOfEqualAccumulatedResults\/title"},{"op":"replace","value":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerBehaviorConfiguration~1requiredNumberOfEqualAccumulatedResults\/fragments"}]}]}