{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum","navigatorTitle":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"title":"SBSDKValueConsistency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKValueConsistency","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKValueConsistency"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"type":"text","text":"The status of the consistency verification."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKValueConsistency) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKValueConsistency"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"kind":"relationships"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency"},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/inconsistent","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/ok","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburred","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburredExtended","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okPunctuationUpperCaseCleaned","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okTruncated"],"generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/okDeburredExtended":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okDeburredExtended"}],"navigatorTitle":[{"text":"SBSDKValueConsistencyOkDeburredExtended","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okdeburredextended","abstract":[{"text":"Same as OK_DEBURRED but allows replacing diacritics not only with their base characters but also with some more","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"complex combinations. E.g., according to ICAO 9303 MRZ standard Ü can be replaced with U or UE or UXX."}],"kind":"symbol","title":"SBSDKValueConsistency.okDeburredExtended","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburredExtended","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/rawrepresentable-implementations","role":"collectionGroup","type":"topic"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/okPunctuationUpperCaseCleaned":{"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okpunctuationuppercasecleaned","role":"symbol","title":"SBSDKValueConsistency.okPunctuationUpperCaseCleaned","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okPunctuationUpperCaseCleaned","abstract":[{"text":"All values that correspond to the same logical field are equal after punctuation is removed and all characters","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"are converted to upper case."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"okPunctuationUpperCaseCleaned","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/inconsistent":{"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/inconsistent","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"inconsistent","kind":"identifier"}],"abstract":[{"type":"text","text":"The values that correspond to the same logical field are inconsistent."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistencyInconsistent"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/inconsistent","title":"SBSDKValueConsistency.inconsistent"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/okDeburred":{"abstract":[{"type":"text","text":"All values that correspond to the same logical field are equal after punctuation is removed, all characters are"},{"type":"text","text":" "},{"type":"text","text":"converted to upper case and diacritics are replaced with their base characters."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"okDeburred","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okdeburred","type":"topic","title":"SBSDKValueConsistency.okDeburred","navigatorTitle":[{"text":"SBSDKValueConsistencyOkDeburred","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburred"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/init(rawvalue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/init(rawValue:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/okTruncated":{"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/oktruncated","role":"symbol","title":"SBSDKValueConsistency.okTruncated","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okTruncated","abstract":[{"text":"In addition to OK_DEBURRED_EXTENDED, allows one string to be a prefix of another string. Correctly works with","type":"text"},{"type":"text","text":" "},{"text":"complex diacritics replacements. In particular, if one string is MUEL and another is MÜLLER, then they are","type":"text"},{"type":"text","text":" "},{"text":"considered equal up to truncation.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"okTruncated"}],"navigatorTitle":[{"text":"SBSDKValueConsistencyOkTruncated","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/Equatable-Implementations":{"kind":"article","type":"topic","title":"Equatable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/equatable-implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/Equatable-Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/ok":{"kind":"symbol","title":"SBSDKValueConsistency.ok","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/ok","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ok","kind":"identifier"}],"abstract":[{"type":"text","text":"All values that correspond to the same logical field are exactly equal."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistencyOk"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/ok","type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"title":"SBSDKValueConsistency","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"role":"symbol","type":"topic","abstract":[{"text":"The status of the consistency verification.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKValueConsistency"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","value":"SBSDKValueConsistency","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKValueConsistency","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/inconsistent","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/ok","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburred","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburredExtended","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okPunctuationUpperCaseCleaned","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okTruncated"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKValueConsistency"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKValueConsistencyOkDeburredExtended","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okDeburredExtended\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okDeburredExtended\/fragments","value":[{"text":"SBSDKValueConsistencyOkDeburredExtended","kind":"identifier"}]},{"value":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okPunctuationUpperCaseCleaned\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okPunctuationUpperCaseCleaned\/fragments","value":[{"kind":"identifier","text":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned"}],"op":"replace"},{"value":"SBSDKValueConsistencyInconsistent","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1inconsistent\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1inconsistent\/fragments","value":[{"text":"SBSDKValueConsistencyInconsistent","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okDeburred\/title","value":"SBSDKValueConsistencyOkDeburred"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okDeburred\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistencyOkDeburred"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okTruncated\/title","op":"replace","value":"SBSDKValueConsistencyOkTruncated"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okTruncated\/fragments","value":[{"text":"SBSDKValueConsistencyOkTruncated","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1ok\/title","value":"SBSDKValueConsistencyOk","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKValueConsistencyOk"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1ok\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title","value":"SBSDKValueConsistency"},{"op":"replace","value":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistency"}]}]}]}