{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKImageRefProfiler","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefProfiler","navigatorTitle":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler"},"abstract":[{"text":"ImageRef memory profiler.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(SBSDKImageRefProfiler) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"ImageRefs are reference-counted. If references aren’t correctly released for whatever reason, the image memory will","type":"text"},{"type":"text","text":" "},{"text":"leak. Leaking memory over time may cause out-of-memory crashes and must be avoided. The profiler can return basic","type":"text"},{"text":" ","type":"text"},{"text":"and detailed information about all currently alive ImageRefs, that can be useful to track leaking ImageRefs or to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"confirm that there are no leaks."}]}]}],"kind":"symbol","topicSections":[{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/enableDetailedProfiling()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/makeSnapshot()"],"title":"Type Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofiler"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofiler"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler/makeSnapshot()":{"role":"symbol","abstract":[{"text":"Returns a snapshot of all alive ImageRefs. The snapshot contains a list of ImageRefs with information such as","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in-memory size. If detailed profiling is enabled (by calling enableDetailedProfiling beforehand), the profile"},{"type":"text","text":" "},{"type":"text","text":"will contain additional information such as the source from which each ImageRef has been created."}],"navigatorTitle":[{"text":"makeSnapshot","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"makeSnapshot"},{"text":"() -> ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/makesnapshot()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/makeSnapshot()","kind":"symbol","title":"makeSnapshot()"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler/diff(firstSnapshot:secondSnapshot:)":{"kind":"symbol","type":"topic","title":"diff(firstSnapshot:secondSnapshot:)","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)","abstract":[{"type":"text","text":"Computes difference between two snapshots. To confirm that a particular operation doesn’t leak, take a snapshot"},{"text":" ","type":"text"},{"text":"before and after the operation, and check that the diff doesn’t contain any unexpected new ImageRefs.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diff","kind":"identifier"},{"text":"(","kind":"text"},{"text":"firstSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"text":", ","kind":"text"},{"text":"secondSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","text":"SBSDKImageRefPoolSnapshotsDiff"}],"navigatorTitle":[{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler/enableDetailedProfiling()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableDetailedProfiling"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/enableDetailedProfiling()","role":"symbol","type":"topic","abstract":[{"text":"After the function is called, ImageRefs will store additional information, such as source from which they were","type":"text"},{"type":"text","text":" "},{"text":"created. This information may be important when trying to understand a profile. This function must be called","type":"text"},{"type":"text","text":" "},{"text":"BEFORE the first ImageRef is created, otherwise details may be lost.","type":"text"}],"title":"enableDetailedProfiling()","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/enabledetailedprofiling()","navigatorTitle":[{"kind":"identifier","text":"enableDetailedProfiling"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler":{"title":"SBSDKImageRefProfiler","abstract":[{"text":"ImageRef memory profiler.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler/init":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/init"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageRefProfiler"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/init"]},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/enableDetailedProfiling()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/makeSnapshot()"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageRefProfiler"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"value":"makeSnapshot","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1makeSnapshot()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"makeSnapshot"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1makeSnapshot()\/fragments"},{"op":"replace","value":"diffWithFirstSnapshot:secondSnapshot:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"diffWithFirstSnapshot:secondSnapshot:"}],"op":"replace"},{"op":"replace","value":"enableDetailedProfiling","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1enableDetailedProfiling()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"enableDetailedProfiling","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1enableDetailedProfiling()\/fragments"},{"value":"SBSDKImageRefProfiler","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/fragments","value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/navigatorTitle","value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}