{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller\/applicationdidbecomeactive()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller\/applicationdidbecomeactive()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"text":"Is called when the application became active.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController\/applicationDidBecomeActive()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationDidBecomeActive","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"applicationDidBecomeActive()","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationDidBecomeActive"},{"kind":"text","text":"()"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUICameraViewController(im)applicationDidBecomeActive","navigatorTitle":[{"text":"applicationDidBecomeActive","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewController":{"title":"SBSDKUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller","abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUICameraViewController":{"title":"SBSDKUICameraViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICameraViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller","abstract":[{"type":"text","text":"A "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","type":"reference","isActive":true},{"type":"text","text":" subclass which adds support for enabled and disabled camera permission."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUICameraViewController/applicationDidBecomeActive()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController\/applicationDidBecomeActive()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"applicationDidBecomeActive","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationDidBecomeActive","kind":"identifier"},{"text":"()","kind":"text"}],"title":"applicationDidBecomeActive()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller\/applicationdidbecomeactive()","type":"topic","abstract":[{"type":"text","text":"Is called when the application became active."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"applicationDidBecomeActive","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidBecomeActive"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"applicationDidBecomeActive","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUIViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/navigatorTitle"},{"value":"SBSDKUICameraViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/title"},{"value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/fragments"},{"value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/navigatorTitle"},{"value":"applicationDidBecomeActive","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController~1applicationDidBecomeActive()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"applicationDidBecomeActive","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController~1applicationDidBecomeActive()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}