{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorBehaviorConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorBehaviorConfiguration\/excludedFieldTypes"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorbehaviorconfiguration\/excludedfieldtypes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorbehaviorconfiguration\/excludedfieldtypes"]}],"abstract":[{"text":"An array of normalized names for the document field types that should not be recognized. If ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" all the fields are going to be recognized.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"excludedFieldTypes"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","title":"excludedFieldTypes","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorBehaviorConfiguration(py)excludedFieldTypes","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"excludedFieldTypes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"excludedFieldTypes","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorBehaviorConfiguration/excludedFieldTypes":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"excludedFieldTypes","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorBehaviorConfiguration\/excludedFieldTypes","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"excludedFieldTypes"}],"title":"excludedFieldTypes","abstract":[{"text":"An array of normalized names for the document field types that should not be recognized. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" all the fields are going to be recognized.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorbehaviorconfiguration\/excludedfieldtypes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorBehaviorConfiguration":{"type":"topic","abstract":[{"text":"The configuration for the behavior of the RTU-UI document data extractor screen.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorBehaviorConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorBehaviorConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorBehaviorConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorbehaviorconfiguration","title":"SBSDKUIDocumentDataExtractorBehaviorConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"excludedFieldTypes","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"excludedFieldTypes","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"excludedFieldTypes","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration~1excludedFieldTypes\/title","op":"replace","value":"excludedFieldTypes"},{"value":[{"text":"excludedFieldTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration~1excludedFieldTypes\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIDocumentDataExtractorBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIDocumentDataExtractorBehaviorConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorBehaviorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorBehaviorConfiguration\/navigatorTitle"}]}]}