{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"SBSDKEncodingFormat.png","navigatorTitle":[{"text":"SBSDKEncodingFormatPng","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"png"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKEncodingFormat@SBSDKEncodingFormatPng","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat"]]},"abstract":[{"text":"PNG encoding.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"png"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkencodingformat\/png"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkencodingformat\/png"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat\/png","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncodingFormat/png":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormatPng"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"png"}],"kind":"symbol","abstract":[{"text":"PNG encoding.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat\/png","url":"\/documentation\/scanbotsdk\/sbsdkencodingformat\/png","type":"topic","title":"SBSDKEncodingFormat.png"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncodingFormat":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkencodingformat","abstract":[{"type":"text","text":"Image Encoding Format."}],"title":"SBSDKEncodingFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKEncodingFormat","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKEncodingFormatPng","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEncodingFormatPng"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKEncodingFormatPng"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat~1png\/title","value":"SBSDKEncodingFormatPng","op":"replace"},{"op":"replace","value":[{"text":"SBSDKEncodingFormatPng","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat~1png\/fragments"},{"value":"SBSDKEncodingFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/fragments","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}