{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/insuranceprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/insuranceprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Insurance provider (Krankenkasse bzw. Kostenträger)."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"insuranceProvider","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/insuranceProvider"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificatePatientInfoFieldType@SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insuranceProvider"}],"symbolKind":"case","navigatorTitle":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider","kind":"identifier"}],"title":"SBSDKMedicalCertificatePatientInfoFieldType.insuranceProvider","roleHeading":"Case"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType":{"role":"symbol","title":"SBSDKMedicalCertificatePatientInfoFieldType","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Type of a field in the patient info box."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoFieldType/insuranceProvider":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfofieldtype\/insuranceprovider","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider"}],"title":"SBSDKMedicalCertificatePatientInfoFieldType.insuranceProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"insuranceProvider"}],"abstract":[{"type":"text","text":"Insurance provider (Krankenkasse bzw. Kostenträger)."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoFieldType\/insuranceProvider","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/title","value":"SBSDKMedicalCertificatePatientInfoFieldType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldType"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificatePatientInfoFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType\/navigatorTitle"},{"op":"replace","value":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1insuranceProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoFieldTypeInsuranceProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoFieldType~1insuranceProvider\/fragments"}]}]}