{"abstract":[{"type":"text","text":"The drawing style of the finder view."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/viewFinderStyle"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewFinderStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO","text":"Style","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/stroke","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/viewfinderstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/viewfinderstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController(py)viewFinderStyle","title":"viewFinderStyle","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewFinderStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKFinderView","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO","kind":"typeIdentifier","text":"Style"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewFinderStyle"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum/stroke":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/stroke","abstract":[{"text":"The full line around the finder view.","type":"text"}],"title":"SBSDKFinderView.Style.stroke","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stroke"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/stroke"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"title":"SBSDKFinderView","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewStyle":{"url":"\/documentation\/scanbotsdk\/sbsdkfinderviewstyle","type":"topic","title":"SBSDKFinderViewStyle","abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewStyle","role":"symbol","fragments":[{"kind":"identifier","text":"SBSDKFinderViewStyle"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","abstract":[{"text":"A highly customizable camera view controller that delivers a basic camera functionality along with video","type":"text"},{"text":" ","type":"text"},{"text":"frame extraction and preprocessing, orientation correction and still image capturing.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"title":"SBSDKBaseScannerViewController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController/viewFinderStyle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/viewFinderStyle","role":"symbol","abstract":[{"type":"text","text":"The drawing style of the finder view."}],"navigatorTitle":[{"text":"viewFinderStyle","kind":"identifier"}],"title":"viewFinderStyle","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/viewfinderstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewFinderStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO","text":"Style","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum":{"kind":"symbol","abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}],"title":"SBSDKFinderView.Style","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"viewFinderStyle","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"viewFinderStyle","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderViewStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKFinderViewStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewStyle"},{"text":" ","kind":"text"},{"text":"viewFinderStyle","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKFinderView","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFinderView"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController~1viewFinderStyle\/title","value":"viewFinderStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController~1viewFinderStyle\/fragments","value":[{"kind":"identifier","text":"viewFinderStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}