{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"isEqual:","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration(im)isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/isEqual:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickBadgeConfiguration/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration\/isequal:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration\/isEqual:","type":"topic","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FindAndPickBadgeConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"title":"SBSDKUI2FindAndPickBadgeConfiguration","abstract":[{"text":"Configuration of the round badge on find and pick ar layer.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2findandpickbadgeconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FindAndPickBadgeConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/title","value":"SBSDKUI2FindAndPickBadgeConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/fragments","value":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}]}]}]}