{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"enableCameraButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration(py)enableCameraButtonTitle","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"enableCameraButtonTitle","navigatorTitle":[{"kind":"identifier","text":"enableCameraButtonTitle"}],"role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraTextConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraTextConfiguration\/enableCameraButtonTitle","interfaceLanguage":"swift"},"abstract":[{"text":"The string being displayed on the button to request camera access.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableCameraButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to “Enable camera”."}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuienablecameratextconfiguration\/enablecamerabuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuienablecameratextconfiguration\/enablecamerabuttontitle"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIEnableCameraTextConfiguration/enableCameraButtonTitle":{"navigatorTitle":[{"text":"enableCameraButtonTitle","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuienablecameratextconfiguration\/enablecamerabuttontitle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraTextConfiguration\/enableCameraButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableCameraButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"text":"The string being displayed on the button to request camera access.","type":"text"}],"title":"enableCameraButtonTitle"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIEnableCameraTextConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraTextConfiguration","title":"SBSDKUIEnableCameraTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration for the textual contents of camera based view controllers."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuienablecameratextconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"enableCameraButtonTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"enableCameraButtonTitle"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"enableCameraButtonTitle","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"enableCameraButtonTitle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraTextConfiguration~1enableCameraButtonTitle\/title"},{"value":[{"text":"enableCameraButtonTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraTextConfiguration~1enableCameraButtonTitle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraTextConfiguration\/title","value":"SBSDKUIEnableCameraTextConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}