{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/licensefailurehandler"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/licensefailurehandler"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"licenseFailureHandler"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)ScanbotSDKConfiguration(py)licenseFailureHandler","roleHeading":"Instance Property","title":"licenseFailureHandler","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"licenseFailureHandler","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLicenseFailureHandler","preciseIdentifier":"s:25ScanbotDocumentScannerSDK26SBSDKLicenseFailureHandlera"}]},"sections":[],"abstract":[{"type":"text","text":"A custom handler for handling license validation failures. Defaults to a built-in handler."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"licenseFailureHandler","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:25ScanbotDocumentScannerSDK26SBSDKLicenseFailureHandlera","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseFailureHandler","text":"SBSDKLicenseFailureHandler"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/licenseFailureHandler"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration","abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"type":"text","text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration","title":"ScanbotSDKConfiguration","kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus","abstract":[{"text":"The status of the ScanbotSDK license.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus","kind":"symbol","title":"SBSDKLicenseStatus","navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/ScanbotSDKConfiguration/licenseFailureHandler":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbotsdkconfiguration\/licensefailurehandler","abstract":[{"type":"text","text":"A custom handler for handling license validation failures. Defaults to a built-in handler."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"licenseFailureHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKLicenseFailureHandler","preciseIdentifier":"s:25ScanbotDocumentScannerSDK26SBSDKLicenseFailureHandlera","kind":"typeIdentifier"}],"title":"licenseFailureHandler","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/ScanbotSDKConfiguration\/licenseFailureHandler","navigatorTitle":[{"text":"licenseFailureHandler","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}],"abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFeature"}],"title":"SBSDKFeature","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseFailureHandler":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensefailurehandler","abstract":[{"type":"text","text":"Typealias for license failure handling closure."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseFailureHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseFailureHandler"}],"kind":"symbol","type":"topic","title":"SBSDKLicenseFailureHandler","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicenseFailureHandler"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"licenseFailureHandler","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"licenseFailureHandler","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"identifier","text":"licenseFailureHandler"},{"kind":"text","text":")("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus","text":"SBSDKLicenseStatus"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFeature","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKFeature","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":");"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/title","value":"ScanbotSDKConfiguration","op":"replace"},{"value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ScanbotSDKConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/title","op":"replace","value":"SBSDKLicenseStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/fragments","op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1licenseFailureHandler\/title","op":"replace","value":"licenseFailureHandler"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1ScanbotSDKConfiguration~1licenseFailureHandler\/fragments","value":[{"kind":"identifier","text":"licenseFailureHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/title","value":"SBSDKFeature"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}