{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedBarcodeTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType","text":"SBSDKBarcodeType"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumenttype\/supportedbarcodetypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumenttype\/supportedbarcodetypes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentType\/supportedBarcodeTypes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Possible barcodes for the current barcode document type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedBarcodeTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType"},{"kind":"text","text":"]"}],"title":"supportedBarcodeTypes","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentType(py)supportedBarcodeTypes","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"supportedBarcodeTypes"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeType":{"role":"symbol","title":"SBSDKBarcodeType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeType"}],"abstract":[{"type":"text","text":"Class that represents a barcode type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentType/supportedBarcodeTypes":{"role":"symbol","title":"supportedBarcodeTypes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedBarcodeTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Possible barcodes for the current barcode document type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentType\/supportedBarcodeTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"supportedBarcodeTypes"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumenttype\/supportedbarcodetypes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentType":{"role":"symbol","title":"SBSDKBarcodeDocumentType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentType"}],"abstract":[{"type":"text","text":"A helper class describing a barcode document type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumenttype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"supportedBarcodeTypes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"supportedBarcodeTypes"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeType *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"supportedBarcodeTypes"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeType\/title","value":"SBSDKBarcodeType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeType\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentType~1supportedBarcodeTypes\/title","value":"supportedBarcodeTypes"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentType~1supportedBarcodeTypes\/fragments","value":[{"kind":"identifier","text":"supportedBarcodeTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentType\/title","value":"SBSDKBarcodeDocumentType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentType\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}