{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/iso8859part9"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/iso8859part9"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding\/iso8859Part9","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"ISO\/IEC 8859 Part 9, a.k.a. Latin-5 Turkish."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding"]]},"metadata":{"navigatorTitle":[{"text":"iso8859Part9","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding(cpy)iso8859Part9","title":"iso8859Part9","symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iso8859Part9","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","text":"SBSDKCharacterEncoding","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iso8859Part9"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","text":"SBSDKCharacterEncoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding/iso8859Part9":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iso8859Part9"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","text":"SBSDKCharacterEncoding"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"iso8859Part9"}],"kind":"symbol","title":"iso8859Part9","abstract":[{"type":"text","text":"ISO\/IEC 8859 Part 9, a.k.a. Latin-5 Turkish."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding\/iso8859Part9","url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/iso8859part9"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding","kind":"symbol","title":"SBSDKCharacterEncoding","navigatorTitle":[{"text":"SBSDKCharacterEncoding","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKCharacterEncoding","kind":"identifier"}],"abstract":[{"type":"text","text":"Enumerates character encodings."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"iso8859Part9"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"iso8859Part9","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","text":"SBSDKCharacterEncoding"},{"text":" * ","kind":"text"},{"text":"iso8859Part9","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"iso8859Part9","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding~1iso8859Part9\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding~1iso8859Part9\/fragments","value":[{"kind":"identifier","text":"iso8859Part9"}]},{"value":"SBSDKCharacterEncoding","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/title"},{"value":[{"kind":"identifier","text":"SBSDKCharacterEncoding"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCharacterEncoding"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}