{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration\/new"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarexpandedconfiguration\/new"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"navigatorTitle":[{"kind":"identifier","text":"new"}],"title":"new","symbolKind":"method","roleHeading":"Type Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataBarExpandedConfiguration(cm)new"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"new","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataBarExpandedConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarexpandedconfiguration","abstract":[{"type":"text","text":"GS1 DataBar Expanded barcode configuration. Add to scanner configuration to scan GS1 DataBar Expanded and GS1 DataBar Expanded Stacked barcodes."}],"title":"SBSDKBarcodeFormatDataBarExpandedConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataBarExpandedConfiguration/new":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarExpandedConfiguration\/new","type":"topic","role":"symbol","navigatorTitle":[{"text":"new","kind":"identifier"}],"title":"new","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarexpandedconfiguration\/new","fragments":[{"kind":"text","text":"+ "},{"text":"new","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/title","value":"SBSDKBarcodeFormatDataBarExpandedConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarExpandedConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatDataBarExpandedConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}