{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizeraccumulationconfiguration\/autoclearthreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizeraccumulationconfiguration\/autoclearthreshold"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoClearThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Defaults to 4.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerAccumulationConfiguration\/autoClearThreshold","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"autoClearThreshold"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","title":"autoClearThreshold","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerAccumulationConfiguration(py)autoClearThreshold","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoClearThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The number of consecutive frames having a different document type or being empty that will automatically clear the accumulator."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerAccumulationConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"title":"SBSDKGenericDocumentRecognizer","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","abstract":[{"type":"text","text":"A class to recognize and detect the data fields from specific documents,"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerAccumulationConfiguration":{"abstract":[{"text":"The result accumulation configuration of the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","isActive":true,"type":"reference"},{"type":"text","text":" ."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizeraccumulationconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerAccumulationConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration"}],"kind":"symbol","type":"topic","title":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerAccumulationConfiguration/autoClearThreshold":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoClearThreshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"autoClearThreshold"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizeraccumulationconfiguration\/autoclearthreshold","role":"symbol","kind":"symbol","title":"autoClearThreshold","abstract":[{"type":"text","text":"The number of consecutive frames having a different document type or being empty that will automatically clear the accumulator."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerAccumulationConfiguration\/autoClearThreshold"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"autoClearThreshold","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"autoClearThreshold"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoClearThreshold"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title","op":"replace","value":"SBSDKGenericDocumentRecognizer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments","value":[{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerAccumulationConfiguration\/title","value":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerAccumulationConfiguration\/fragments","value":[{"text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerAccumulationConfiguration\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","kind":"identifier"}],"op":"replace"},{"value":"autoClearThreshold","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerAccumulationConfiguration~1autoClearThreshold\/title"},{"value":[{"kind":"identifier","text":"autoClearThreshold"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerAccumulationConfiguration~1autoClearThreshold\/fragments"}]}]}