{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"setupDefaultLicenseFailureHandler()","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":"()"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)Scanbot(cm)setupDefaultLicenseFailureHandler","navigatorTitle":[{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot\/setupDefaultLicenseFailureHandler()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Sets up the default license failure handler which is being called when the license or trial time expired.","type":"text"},{"text":" ","type":"text"},{"text":"The default handler shows an alert to inform your users about the expired license or trial period.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbot\/setupdefaultlicensefailurehandler()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbot\/setupdefaultlicensefailurehandler()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/Scanbot/setupDefaultLicenseFailureHandler()":{"abstract":[{"text":"Sets up the default license failure handler which is being called when the license or trial time expired.","type":"text"},{"text":" ","type":"text"},{"text":"The default handler shows an alert to inform your users about the expired license or trial period.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/scanbot\/setupdefaultlicensefailurehandler()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot\/setupDefaultLicenseFailureHandler()","role":"symbol","navigatorTitle":[{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}],"type":"topic","title":"setupDefaultLicenseFailureHandler()","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/Scanbot":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Scanbot"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scanbot"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/Scanbot","kind":"symbol","title":"Scanbot","url":"\/documentation\/scanbotbarcodescannersdk\/scanbot","abstract":[{"text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setupDefaultLicenseFailureHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot~1setupDefaultLicenseFailureHandler()\/title","value":"setupDefaultLicenseFailureHandler"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot~1setupDefaultLicenseFailureHandler()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/title","value":"Scanbot"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/fragments","value":[{"text":"Scanbot","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1Scanbot\/navigatorTitle","value":[{"text":"Scanbot","kind":"identifier"}]}]}]}