{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stroke"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO6strokeyA2EmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stroke","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKFinderView.Style.stroke"},"kind":"symbol","abstract":[{"text":"The full line around the finder view.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/stroke"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/stroke","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum/stroke":{"kind":"symbol","abstract":[{"type":"text","text":"The full line around the finder view."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/stroke","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stroke"}],"title":"SBSDKFinderView.Style.stroke","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/stroke"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"title":"SBSDKFinderView","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}],"title":"SBSDKFinderView.Style","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum","navigatorTitle":[{"text":"Style","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}