{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/lzw","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"For both colored and binarized images."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lzw"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterCompressionOptions@SBSDKTIFFImageWriterCompressionOptionsLzw","role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lzw"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterCompressionOptionsLzw","kind":"identifier"}],"title":"SBSDKTIFFImageWriterCompressionOptions.lzw","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/lzw"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/lzw"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions/lzw":{"abstract":[{"type":"text","text":"For both colored and binarized images."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions\/lzw","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsLzw"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions\/lzw","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lzw","kind":"identifier"}],"type":"topic","title":"SBSDKTIFFImageWriterCompressionOptions.lzw"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterCompressionOptions":{"abstract":[{"type":"text","text":"The TIFF compression algorithms."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"type":"topic","title":"SBSDKTIFFImageWriterCompressionOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewritercompressionoptions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterCompressionOptions","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKTIFFImageWriterCompressionOptionsLzw"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsLzw"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsLzw"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1lzw\/title","value":"SBSDKTIFFImageWriterCompressionOptionsLzw","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions~1lzw\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptionsLzw"}]},{"value":"SBSDKTIFFImageWriterCompressionOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/title"},{"value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterCompressionOptions\/navigatorTitle"}]}]}