{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"title":"iso8859Part7","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding(cpy)iso8859Part7","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"iso8859Part7"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","text":"SBSDKCharacterEncoding"}],"navigatorTitle":[{"kind":"identifier","text":"iso8859Part7"}],"roleHeading":"Type Property","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding\/iso8859Part7","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iso8859Part7","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCharacterEncoding","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding"]]},"abstract":[{"type":"text","text":"ISO\/IEC 8859 Part 7, a.k.a. Latin\/Greek."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/iso8859part7"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/iso8859part7"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding/iso8859Part7":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding\/iso8859Part7","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iso8859Part7","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCharacterEncoding","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding\/iso8859part7","abstract":[{"text":"ISO\/IEC 8859 Part 7, a.k.a. Latin\/Greek.","type":"text"}],"navigatorTitle":[{"text":"iso8859Part7","kind":"identifier"}],"title":"iso8859Part7"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCharacterEncoding":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding","kind":"symbol","abstract":[{"text":"Enumerates character encodings.","type":"text"}],"title":"SBSDKCharacterEncoding","navigatorTitle":[{"text":"SBSDKCharacterEncoding","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcharacterencoding","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCharacterEncoding","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"iso8859Part7"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"iso8859Part7","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKCharacterEncoding","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCharacterEncoding","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCharacterEncoding"},{"text":" * ","kind":"text"},{"text":"iso8859Part7","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"iso8859Part7","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding~1iso8859Part7\/title"},{"op":"replace","value":[{"kind":"identifier","text":"iso8859Part7"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding~1iso8859Part7\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/title","op":"replace","value":"SBSDKCharacterEncoding"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCharacterEncoding"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCharacterEncoding\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCharacterEncoding","kind":"identifier"}]}]}]}