{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition\/back","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition"]]},"abstract":[{"text":"The camera is located on the back side of the device.","type":"text"}],"metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition@SBSDKCameraDevicePositionBack","symbolKind":"case","title":"SBSDKCameraDevicePosition.back","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevicePositionBack"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradeviceposition\/back"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradeviceposition\/back"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevicePosition":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition","url":"\/documentation\/scanbotsdk\/sbsdkcameradeviceposition","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraDevicePosition"}],"navigatorTitle":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An enum to describe the physical position of a camera device."}],"title":"SBSDKCameraDevicePosition"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevicePosition/back":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDevicePositionBack"}],"title":"SBSDKCameraDevicePosition.back","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition\/back","url":"\/documentation\/scanbotsdk\/sbsdkcameradeviceposition\/back","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The camera is located on the back side of the device."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCameraDevicePositionBack"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDevicePositionBack"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKCameraDevicePositionBack"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"SBSDKCameraDevicePosition","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/title"},{"value":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraDevicePosition"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition~1back\/title","value":"SBSDKCameraDevicePositionBack"},{"value":[{"kind":"identifier","text":"SBSDKCameraDevicePositionBack"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition~1back\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}