{"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPathImageLoadOptions","navigatorTitle":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"title":"SBSDKPathImageLoadOptions","symbolKind":"class"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"kind":"symbol","abstract":[{"type":"text","text":"Options for loading image from path."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKPathImageLoadOptions) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/init()"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/canvasColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/colorConversion","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/cropRect","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/decrypter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/encryptionMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/loadMode"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/toJson(configuration:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/init()":{"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/init()","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/colorConversion":{"navigatorTitle":[{"text":"colorConversion","kind":"identifier"}],"abstract":[{"text":"Color conversion to apply during image loading.","type":"text"}],"title":"colorConversion","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/colorConversion","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/colorconversion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorConversion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKColorConversion","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKColorConversion","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/toJson(configuration:)":{"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/tojson(configuration:)","kind":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/toJson(configuration:)","role":"symbol","title":"toJson(configuration:)"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/copyWithZone:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/copywithzone:","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/copyWithZone:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/cropRect":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/croprect","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cropRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"If the rect is not empty, the image will be cropped to this rect before processing."}],"role":"symbol","navigatorTitle":[{"text":"cropRect","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/cropRect","title":"cropRect"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/encryptionMode":{"navigatorTitle":[{"text":"encryptionMode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/encryptionmode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/encryptionMode","title":"encryptionMode","abstract":[{"text":"Encryption mode.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/decrypter":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decrypter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Custom decrypter to use when loading the image if the encryptionMode implies encryption must be used."}],"navigatorTitle":[{"text":"decrypter","kind":"identifier"}],"title":"decrypter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/decrypter","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/decrypter"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions":{"role":"symbol","kind":"symbol","title":"SBSDKPathImageLoadOptions","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"abstract":[{"type":"text","text":"Options for loading image from path."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/canvasColor":{"abstract":[{"type":"text","text":"CanvasColor color to use when converting images with alpha channel to images without alpha channel."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"canvasColor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canvasColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCanvasColor","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCanvasColor","kind":"typeIdentifier"}],"type":"topic","title":"canvasColor","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/canvascolor","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/canvasColor"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/isEqual:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/isequal:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/isEqual:","role":"symbol","abstract":[],"title":"isEqual:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/loadMode":{"abstract":[{"type":"text","text":"Load mode."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPathLoadMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKPathLoadMode","kind":"typeIdentifier"}],"kind":"symbol","title":"loadMode","navigatorTitle":[{"kind":"identifier","text":"loadMode"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/loadmode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/loadMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/initwithcroprect:colorconversion:canvascolor:loadmode:encryptionmode:decrypter:","abstract":[],"type":"topic","navigatorTitle":[{"text":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","kind":"identifier"}],"role":"symbol","title":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/hash":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/hash","kind":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/hash","role":"symbol","title":"hash","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/fromJsonWithJson:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/fromjsonwithjson:","role":"symbol","title":"fromJsonWithJson:","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","title":"NSCopying"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKPathImageLoadOptions","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/canvasColor","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/colorConversion","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/cropRect","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/decrypter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/encryptionMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/hash","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/loadMode"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/copyWithZone:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/initWithCropRect:colorConversion:canvasColor:loadMode:encryptionMode:decrypter:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/toJson(configuration:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/fromJsonWithJson:"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathImageLoadOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1colorConversion\/title","value":"colorConversion"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1colorConversion\/fragments","value":[{"text":"colorConversion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1cropRect\/title","value":"cropRect"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1cropRect\/fragments","value":[{"text":"cropRect","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1encryptionMode\/title","value":"encryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1encryptionMode\/fragments","value":[{"text":"encryptionMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1decrypter\/title","value":"decrypter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1decrypter\/fragments","value":[{"kind":"identifier","text":"decrypter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/title","value":"SBSDKPathImageLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/fragments","value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/navigatorTitle","value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1canvasColor\/title","value":"canvasColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1canvasColor\/fragments","value":[{"kind":"identifier","text":"canvasColor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1loadMode\/title","value":"loadMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions~1loadMode\/fragments","value":[{"kind":"identifier","text":"loadMode"}]}]}]}