{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider"},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/init(keyGenerator:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/keyGenerator"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)"],"title":"Instance Methods","generated":true}],"abstract":[{"type":"text","text":"Protocol for loading, storing and providing encryption keys."},{"type":"text","text":" "},{"type":"text","text":"The context parameter is used to distinguish between different encryption contexts."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"SBSDKStorageCryptingKeyProvider","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyProvider"},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"For most applications in Scanbot SDK the context is derived from the URL of the file to encrypted or decrypted by calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext"},{"type":"text","text":" property on the URL."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider/keyGenerator":{"required":true,"navigatorTitle":[{"text":"keyGenerator","kind":"identifier"}],"abstract":[{"text":"The key generator that generates an encryption key for a context if no key is available yet.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/keyGenerator","type":"topic","title":"keyGenerator","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyGenerator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/keygenerator","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider","role":"symbol","navigatorTitle":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"abstract":[{"text":"A volatile key provider that generates and stores keys in memory.","type":"text"}],"title":"SBSDKVolatileKeyProvider","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider","kind":"symbol","title":"SBSDKStorageCryptingKeyProvider","role":"symbol","abstract":[{"text":"Protocol for loading, storing and providing encryption keys.","type":"text"},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Foundation/URL/sbsdk_encryptionContext":{"url":"\/documentation\/scanbotdocumentscannersdk\/foundation\/url\/sbsdk_encryptioncontext","type":"topic","title":"sbsdk_encryptionContext","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Foundation\/URL\/sbsdk_encryptionContext","abstract":[{"text":"The encryption context of the URL.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_encryptionContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider/init(keyGenerator:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithKeyGenerator:"}],"abstract":[{"text":"Initializer that takes a key generator.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyGenerator"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyGenerator"},{"kind":"text","text":")"}],"role":"symbol","required":true,"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/init(keygenerator:)","title":"init(keyGenerator:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/init(keyGenerator:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider/provideKeyForContext(_:keyLength:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider\/providekeyforcontext(_:keylength:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"provideKeyForContext"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}],"abstract":[{"type":"text","text":"Tries to load the encryption key for the given context and key length."},{"type":"text","text":" "},{"type":"text","text":"If no key is available yet, a new key is generated by the receivers key generator and stored under the given context."}],"title":"provideKeyForContext(_:keyLength:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKStorageCryptingKeyProvider","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/keyGenerator"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/init(keyGenerator:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider\/provideKeyForContext(_:keyLength:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"keyGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1keyGenerator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"keyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1keyGenerator\/fragments"},{"op":"replace","value":"SBSDKVolatileKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/navigatorTitle"},{"op":"replace","value":"SBSDKStorageCryptingKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/title"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/fragments"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle"},{"op":"replace","value":"initWithKeyGenerator:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1init(keyGenerator:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithKeyGenerator:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1init(keyGenerator:)\/fragments"},{"op":"replace","value":"provideKeyForContext:keyLength:error:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1provideKeyForContext(_:keyLength:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"provideKeyForContext:keyLength:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider~1provideKeyForContext(_:keyLength:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}