{"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/rawValue"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/adobeDeflate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittT4","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittT6","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittrle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittrlew","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/deflate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/jpeg","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/lzw","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/none","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/packbits"],"title":"Type Properties","anchor":"Type-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/enumValue(from:)"],"title":"Type Methods","anchor":"Type-Methods"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKCompressionMode) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","symbolKind":"class","role":"symbol","roleHeading":"Class","title":"SBSDKCompressionMode"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode"},"abstract":[{"text":"TIFF compression type.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/deflate":{"type":"topic","abstract":[{"text":"Deflate compression. Legacy Deflate codec identifier.","type":"text"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deflate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/deflate","role":"symbol","title":"deflate","navigatorTitle":[{"text":"deflate","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/deflate"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/none":{"title":"none","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/none","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Dump mode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/none","navigatorTitle":[{"text":"none","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode":{"abstract":[{"text":"TIFF compression type.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode","type":"topic","navigatorTitle":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"title":"SBSDKCompressionMode","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/ccittrlew":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittrlew","navigatorTitle":[{"kind":"identifier","text":"ccittrlew"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/ccittrlew","role":"symbol","abstract":[{"type":"text","text":"#1 w\/ word alignment. For binarized images only."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ccittrlew"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","text":"SBSDKCompressionMode"}],"type":"topic","title":"ccittrlew","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/rawValue":{"title":"rawValue","abstract":[{"text":"The raw value integer of the current ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode","type":"reference"},{"text":".","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"rawValue","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/rawValue","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/rawvalue"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/adobeDeflate":{"abstract":[{"type":"text","text":"Deflate compression, as recognized by Adobe. More widely supported."}],"title":"adobeDeflate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/adobeDeflate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/adobedeflate","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adobeDeflate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","text":"SBSDKCompressionMode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"adobeDeflate","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/isEqual:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/isEqual:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/isequal:","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/enumValue(from:)":{"abstract":[{"text":"Returns an instance of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode","type":"reference","isActive":true},{"text":" based on the provided raw value.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/enumValue(from:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enumValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"enumValue(from:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/enumvalue(from:)","kind":"symbol","navigatorTitle":[{"text":"enumValueFrom:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/jpeg":{"abstract":[{"text":"%JPEG DCT compression.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/jpeg","navigatorTitle":[{"text":"jpeg","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","text":"SBSDKCompressionMode","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/jpeg","title":"jpeg","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/ccittT6":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittT6","navigatorTitle":[{"text":"ccittT6","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccittT6","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/ccittt6","title":"ccittT6","abstract":[{"type":"text","text":"CCITT T.6 (CCITTFAX4, CCITT Group 4 fax encoding, TIFF 6 name). For binarized images only."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/hash":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/hash","title":"hash","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/hash","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/ccittrle":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccittrle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}],"title":"ccittrle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittrle","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/ccittrle","role":"symbol","type":"topic","abstract":[{"text":"CCITT modified Huffman RLE. For binarized images only.","type":"text"}],"navigatorTitle":[{"text":"ccittrle","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/lzw":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/lzw","abstract":[{"type":"text","text":"Lempel-Ziv and Welch."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lzw","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/lzw","kind":"symbol","title":"lzw","role":"symbol","navigatorTitle":[{"text":"lzw","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/ccittT4":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittT4","navigatorTitle":[{"text":"ccittT4","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/ccittt4","abstract":[{"type":"text","text":"CCITT T.4 (CCITTFAX3, CCITT Group 3 fax encoding, TIFF 6 name). For binarized images only."}],"title":"ccittT4","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccittT4","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCompressionMode/packbits":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcompressionmode\/packbits","kind":"symbol","abstract":[{"type":"text","text":"Macintosh RLE."}],"type":"topic","title":"packbits","navigatorTitle":[{"kind":"identifier","text":"packbits"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"packbits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCompressionMode"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/packbits"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKCompressionMode","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCompressionMode"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/hash","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/rawValue"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/isEqual:"]},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/adobeDeflate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittT4","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittT6","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittrle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/ccittrlew","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/deflate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/jpeg","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/lzw","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/none","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/packbits"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCompressionMode\/enumValue(from:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1deflate\/title","value":"deflate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1deflate\/fragments","value":[{"text":"deflate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1none\/title","value":"none"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1none\/fragments","value":[{"text":"none","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/title","value":"SBSDKCompressionMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/fragments","value":[{"kind":"identifier","text":"SBSDKCompressionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCompressionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittrlew\/title","value":"ccittrlew"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittrlew\/fragments","value":[{"kind":"identifier","text":"ccittrlew"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1rawValue\/title","value":"rawValue"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1rawValue\/fragments","value":[{"kind":"identifier","text":"rawValue"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1adobeDeflate\/title","value":"adobeDeflate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1adobeDeflate\/fragments","value":[{"kind":"identifier","text":"adobeDeflate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1enumValue(from:)\/title","value":"enumValueFrom:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1enumValue(from:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"enumValueFrom:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1jpeg\/title","value":"jpeg"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1jpeg\/fragments","value":[{"text":"jpeg","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittT6\/title","value":"ccittT6"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittT6\/fragments","value":[{"kind":"identifier","text":"ccittT6"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittrle\/title","value":"ccittrle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittrle\/fragments","value":[{"text":"ccittrle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1lzw\/title","value":"lzw"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1lzw\/fragments","value":[{"text":"lzw","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittT4\/title","value":"ccittT4"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1ccittT4\/fragments","value":[{"kind":"identifier","text":"ccittT4"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1packbits\/title","value":"packbits"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCompressionMode~1packbits\/fragments","value":[{"kind":"identifier","text":"packbits"}]}]}]}