{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKAutoSnappingMode","roleHeading":"Enumeration","role":"symbol","title":"SBSDKAutoSnappingMode","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/disabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/disabledWithGuidance","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/enabled"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/RawRepresentable-Implementations"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"The Auto-snapping mode handles different auto-snap scenarios.","type":"text"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"kind":"relationships"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode","title":"SBSDKAutoSnappingMode","role":"symbol","abstract":[{"type":"text","text":"The Auto-snapping mode handles different auto-snap scenarios."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAutoSnappingMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/equatable-implementations","title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/Equatable-Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode/enabled":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"}],"title":"SBSDKAutoSnappingMode.enabled","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/enabled","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/enabled","role":"symbol","navigatorTitle":[{"text":"SBSDKAutoSnappingModeEnabled","kind":"identifier"}],"abstract":[{"type":"text","text":"Auto-snapping and user guidance are enabled."}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode/disabledWithGuidance":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/disabledwithguidance","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/disabledWithGuidance","navigatorTitle":[{"text":"SBSDKAutoSnappingModeDisabledWithGuidance","kind":"identifier"}],"abstract":[{"type":"text","text":"Auto-snapping is disabled while user guidance is enabled."}],"title":"SBSDKAutoSnappingMode.disabledWithGuidance","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabledWithGuidance","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode/init(rawValue:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/init(rawValue:)","role":"symbol","type":"topic","kind":"symbol","title":"init(rawValue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAutoSnappingMode/disabled":{"role":"symbol","title":"SBSDKAutoSnappingMode.disabled","abstract":[{"text":"Auto-snapping and user guidance are disabled.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkautosnappingmode\/disabled","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/disabled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAutoSnappingModeDisabled","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKAutoSnappingMode","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/disabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/disabledWithGuidance","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAutoSnappingMode\/enabled"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAutoSnappingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKAutoSnappingMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode~1enabled\/title","op":"replace","value":"SBSDKAutoSnappingModeEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode~1enabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeEnabled"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode~1disabledWithGuidance\/title","op":"replace","value":"SBSDKAutoSnappingModeDisabledWithGuidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode~1disabledWithGuidance\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabledWithGuidance"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode~1disabled\/title","op":"replace","value":"SBSDKAutoSnappingModeDisabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAutoSnappingMode~1disabled\/fragments","op":"replace","value":[{"text":"SBSDKAutoSnappingModeDisabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}