{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKLineSegment","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"SBSDKLineSegment","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegment","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLineSegment","kind":"identifier"}]},"abstract":[{"text":"Helper class that encapsulates a line segment and provides geometric helper methods.","type":"text"}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(segmentFloat:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(segmentInt:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(with:and:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/boundingBox","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/center","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/end","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/length","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/orientation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/start"],"anchor":"Instance-Properties"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegment"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/start":{"navigatorTitle":[{"text":"start","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The start point of the edge","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"type":"topic","title":"start","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/start","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/start","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/init(with:and:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"and","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithPoint:andPoint:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/init(with:and:)","title":"init(with:and:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(with:and:)","abstract":[{"text":"Designated initializer.","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/center":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"The center of the edge.","type":"text"}],"navigatorTitle":[{"text":"center","kind":"identifier"}],"title":"center","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/center","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/center"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegment"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegment"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment","type":"topic","kind":"symbol","title":"SBSDKLineSegment","abstract":[{"type":"text","text":"Helper class that encapsulates a line segment and provides geometric helper methods."}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/init(segmentInt:)":{"kind":"symbol","navigatorTitle":[{"text":"initWithSegmentInt:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(segmentInt:)","title":"init(segmentInt:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"segmentInt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLineSegmentInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/init(segmentint:)","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/orientation":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The orientation of the receiver. See "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentOrientation","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"orientation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/orientation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/orientation","title":"orientation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKLineSegmentOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLineSegmentOrientation"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/debugDescription":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/debugdescription","fragments":[{"text":"debugDescription","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/debugDescription","type":"topic","kind":"symbol","title":"debugDescription","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/length":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/length","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"length","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The length of the receiver. In other words the distance between p1 and p2."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/length","navigatorTitle":[{"text":"length","kind":"identifier"}],"role":"symbol","title":"length"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegmentOrientation":{"abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentOrientation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentorientation","navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}],"title":"SBSDKLineSegmentOrientation","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/copyWithZone:":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/copywithzone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/copyWithZone:","type":"topic","role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/boundingBox":{"navigatorTitle":[{"kind":"identifier","text":"boundingBox"}],"title":"boundingBox","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/boundingBox","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/boundingbox","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"boundingBox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"kind":"symbol","abstract":[{"type":"text","text":"The axis-aligned bounding box of the receiver."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/init(segmentFloat:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(segmentFloat:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentFloat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKLineSegmentFloat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentFloat"},{"kind":"text","text":")"}],"title":"init(segmentFloat:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/init(segmentfloat:)","navigatorTitle":[{"kind":"identifier","text":"initWithSegmentFloat:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegment/end":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The end point of the edge."}],"navigatorTitle":[{"text":"end","kind":"identifier"}],"title":"end","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegment\/end","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"end","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/end"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKLineSegment","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKLineSegment","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLineSegment","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/boundingBox","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/center","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/debugDescription","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/end","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/length","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/orientation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/start"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/copyWithZone:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(segmentFloat:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(segmentInt:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegment\/init(with:and:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegment"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1start\/title","op":"replace","value":"start"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1start\/fragments","op":"replace","value":[{"kind":"identifier","text":"start"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1init(with:and:)\/title","op":"replace","value":"initWithPoint:andPoint:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1init(with:and:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPoint:andPoint:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1center\/title","op":"replace","value":"center"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1center\/fragments","op":"replace","value":[{"kind":"identifier","text":"center"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment\/title","op":"replace","value":"SBSDKLineSegment"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegment"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLineSegment","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1init(segmentInt:)\/title","op":"replace","value":"initWithSegmentInt:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1init(segmentInt:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSegmentInt:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1orientation\/title","op":"replace","value":"orientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1orientation\/fragments","op":"replace","value":[{"text":"orientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1length\/title","op":"replace","value":"length"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1length\/fragments","op":"replace","value":[{"text":"length","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentOrientation\/title","op":"replace","value":"SBSDKLineSegmentOrientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentOrientation\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegmentOrientation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentOrientation\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLineSegmentOrientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1boundingBox\/title","op":"replace","value":"boundingBox"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1boundingBox\/fragments","op":"replace","value":[{"text":"boundingBox","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1init(segmentFloat:)\/title","op":"replace","value":"initWithSegmentFloat:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1init(segmentFloat:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSegmentFloat:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1end\/title","op":"replace","value":"end"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegment~1end\/fragments","op":"replace","value":[{"text":"end","kind":"identifier"}]}]}]}