{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAdditionalFrameProcessing","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"abstract":[{"type":"text","text":"A protocol that allows to perform additional processing of frames before they are passed to the main scanner."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkadditionalframeprocessing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkadditionalframeprocessing"]}],"metadata":{"symbolKind":"protocol","title":"SBSDKAdditionalFrameProcessing","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKAdditionalFrameProcessing"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)"],"generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAdditionalFrameProcessing":{"title":"SBSDKAdditionalFrameProcessing","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAdditionalFrameProcessing","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A protocol that allows to perform additional processing of frames before they are passed to the main scanner."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkadditionalframeprocessing","navigatorTitle":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAdditionalFrameProcessing/process(frame:)":{"role":"symbol","navigatorTitle":[{"text":"processWithFrame:","kind":"identifier"}],"title":"process(frame:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkadditionalframeprocessing\/process(frame:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Performs additional processing of the frame, e.g. running other scanners on the frame.","type":"text"}],"required":true,"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKAdditionalFrameProcessing","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAdditionalFrameProcessing\/process(frame:)"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAdditionalFrameProcessing"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAdditionalFrameProcessing\/title","op":"replace","value":"SBSDKAdditionalFrameProcessing"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAdditionalFrameProcessing\/fragments","op":"replace","value":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAdditionalFrameProcessing\/navigatorTitle","op":"replace","value":[{"text":"SBSDKAdditionalFrameProcessing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAdditionalFrameProcessing~1process(frame:)\/title","op":"replace","value":"processWithFrame:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAdditionalFrameProcessing~1process(frame:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithFrame:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}