{"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSessionDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSessionObserving","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderViewDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller"]}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init(parentViewController:parentView:delegate:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoCropOnManualSnap","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnapProgressPolygonConfiguration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingDelay","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingSensitivity","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/customSnapButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/delegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/detectionStatusFontSize","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/documentImageFilters","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/hidePolygonLayer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/hideSnapButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/imageScale","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/isAnimatingCapture","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/polygonConfigurationAccepted","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/polygonConfigurationRejected","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/shouldAnimateDocument","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/snapButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/statusTextConfiguration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/suppressDetectionStatusLabel","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/suppressPolygonLayer"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/captureDocumentImage()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/copyCurrentConfiguration()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/finderView(_:didChangeRect:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/setConfiguration(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"The scanning result is visualized using a polygonal bezier path.","type":"text"},{"text":" ","type":"text"},{"text":"This class cannot be instanced from a storyboard.","type":"text"},{"text":" ","type":"text"},{"text":"Instead it is installing itself as a child view controller onto a given parent view controller.","type":"text"},{"text":" ","type":"text"},{"text":"As a subclass of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"},{"text":", it benefits from all its advantages, e.g. zooming, view finder, and energy management.","type":"text"}]}]}],"metadata":{"symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","title":"SBSDKDocumentScannerViewController"},"abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIContentContainer"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/autoSnappingDelay":{"role":"symbol","title":"autoSnappingDelay","navigatorTitle":[{"kind":"identifier","text":"autoSnappingDelay"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/autosnappingdelay","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingDelay","abstract":[{"type":"text","text":"The minimum delay in seconds between two consecutive automatic image captures."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/documentImageFilters":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/documentimagefilters","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/documentImageFilters","kind":"symbol","title":"documentImageFilters","abstract":[{"type":"text","text":"The filters to be applied to the snapped document image."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentImageFilters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"documentImageFilters"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/viewDidAppear:":{"type":"topic","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/viewdidappear:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/viewDidAppear:","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"title":"viewDidAppear:","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/statusTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/statusTextConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/statustextconfiguration","abstract":[{"text":"The configuration object for the document scanning status text.","type":"text"}],"role":"symbol","title":"statusTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"statusTextConfiguration"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusTextConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerStatusTextConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerStatusTextConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/imageScale":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/imagescale","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageScale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/imageScale","abstract":[{"text":"The scaling factor for captured images. Values are clamped to the range 0.0 - 1.0.","type":"text"}],"role":"symbol","title":"imageScale","navigatorTitle":[{"text":"imageScale","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/documentImageSizeLimit":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/documentImageSizeLimit","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/documentimagesizelimit","abstract":[{"text":"Limits the maximum size of the document image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"documentImageSizeLimit","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentImageSizeLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"title":"documentImageSizeLimit"},"doc://net.doo.ScanbotDocumentScannerSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8SendableP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"title":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/viewWillDisappear:":{"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"viewWillDisappear:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/viewWillDisappear:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/viewwilldisappear:","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/autoSnappingMode":{"type":"topic","abstract":[{"type":"text","text":"The auto-snapping mode."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"autoSnappingMode"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKAutoSnappingMode","kind":"typeIdentifier","text":"SBSDKAutoSnappingMode"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/autosnappingmode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingMode","role":"symbol","title":"autoSnappingMode"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/snapButton":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"snapButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKShutterButton","kind":"typeIdentifier","text":"SBSDKShutterButton"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/snapButton","navigatorTitle":[{"kind":"identifier","text":"snapButton"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/snapbutton","abstract":[{"text":"The default snap button.","type":"text"}],"kind":"symbol","title":"snapButton","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/init()":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init()","abstract":[{"type":"text","text":"Initializes an instance of this class with the default configuration."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/init()","title":"init()","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/setConfiguration(_:)":{"navigatorTitle":[{"text":"setConfiguration:","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"setConfiguration(_:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/setconfiguration(_:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/setConfiguration(_:)","type":"topic","abstract":[{"type":"text","text":"Sets the configuration of the receiver."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerConfiguration"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/suppressPolygonLayer":{"role":"symbol","abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" the polygon layer is always shown, if there was a document polygon scanned.","type":"text"},{"text":" ","type":"text"},{"text":"Otherwise it is hidden.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suppressPolygonLayer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/suppressPolygonLayer","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/suppresspolygonlayer","kind":"symbol","navigatorTitle":[{"text":"suppressPolygonLayer","kind":"identifier"}],"title":"suppressPolygonLayer"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/polygonConfigurationAccepted":{"kind":"symbol","abstract":[{"type":"text","text":"The configuration for the polygon displayed over the scanned document when the document detection status is "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"polygonConfigurationAccepted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygonConfigurationAccepted"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration","kind":"typeIdentifier","text":"SBSDKDocumentScannerPolygonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/polygonConfigurationAccepted","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"polygonConfigurationAccepted"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/polygonconfigurationaccepted"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/init(parentViewController:parentView:configuration:delegate:)":{"role":"symbol","abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerConfiguration","text":"SBSDKDocumentScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","kind":"symbol","type":"topic","title":"init(parentViewController:parentView:configuration:delegate:)","navigatorTitle":[{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderView":{"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderview","title":"SBSDKFinderView","type":"topic","abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSessionObserving":{"type":"topic","title":"SBSDKCameraSessionObserving","navigatorTitle":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"abstract":[{"text":"A multicast-observer protocol that informs its observers about state changes of a camera session.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasessionobserving","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSessionObserving","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/hidePolygonLayer":{"navigatorTitle":[{"text":"hidePolygonLayer","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Whether the polygon-displaying layer is hidden or not.","type":"text"}],"title":"hidePolygonLayer","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidePolygonLayer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/hidePolygonLayer","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/hidepolygonlayer","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFinderViewDelegate":{"role":"symbol","abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderView","type":"reference","isActive":true},{"text":" class.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfinderviewdelegate","navigatorTitle":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderViewDelegate","kind":"identifier"}],"title":"SBSDKFinderViewDelegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFinderViewDelegate","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/customSnapButton":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Sets a custom snapping button. If not "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", it replaces the default snapping button."}],"role":"symbol","title":"customSnapButton","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/customsnapbutton","navigatorTitle":[{"kind":"identifier","text":"customSnapButton"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/customSnapButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customSnapButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/isAnimatingCapture":{"role":"symbol","abstract":[{"text":"Whether the receiver is currently animating a captured document or not. Readonly.","type":"text"}],"navigatorTitle":[{"text":"isAnimatingCapture","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/isAnimatingCapture","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/isanimatingcapture","title":"isAnimatingCapture","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAnimatingCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus/ok":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/ok","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ok"}],"title":"SBSDKDocumentDetectionStatus.ok","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusOk"}],"abstract":[{"text":"An acceptable document was detected.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/detectionStatusFontSize":{"navigatorTitle":[{"kind":"identifier","text":"detectionStatusFontSize"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/detectionstatusfontsize","title":"detectionStatusFontSize","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/detectionStatusFontSize","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionStatusFontSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The font size of the user guidance label."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/hideSnapButton":{"abstract":[{"type":"text","text":"Whether the snap button is hidden or not."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideSnapButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"hideSnapButton","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/hidesnapbutton","title":"hideSnapButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/hideSnapButton","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/init(parentViewController:parentView:delegate:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init(parentViewController:parentView:delegate:)","navigatorTitle":[{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"abstract":[{"type":"text","text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area."}],"kind":"symbol","title":"init(parentViewController:parentView:delegate:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/init(parentviewcontroller:parentview:delegate:)","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/polygonConfigurationRejected":{"title":"polygonConfigurationRejected","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/polygonconfigurationrejected","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/polygonConfigurationRejected","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonConfigurationRejected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration","text":"SBSDKDocumentScannerPolygonConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"polygonConfigurationRejected","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The configuration for the polygon displayed over the scanned document when the document detection status is not "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/ok","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIResponderStandardEditActions"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/shouldAnimateDocument":{"abstract":[{"text":"Whether the document capturing is animated or not.","type":"text"}],"navigatorTitle":[{"text":"shouldAnimateDocument","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldAnimateDocument","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"shouldAnimateDocument","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/shouldanimatedocument","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/shouldAnimateDocument"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/viewWillAppear:":{"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/viewwillappear:","title":"viewWillAppear:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/viewWillAppear:","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/captureDocumentImage()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureDocumentImage","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Captures the currently scanned document image, as if the user would press the shutter button or the auto-snapping fires."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"captureDocumentImage","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/captureDocumentImage()","title":"captureDocumentImage()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/capturedocumentimage()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSessionDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSessionDelegate","kind":"symbol","abstract":[{"text":"The  delegate protocol for ","type":"text"},{"type":"codeVoice","code":"SBSDKCameraSession"},{"text":".","type":"text"}],"title":"SBSDKCameraSessionDelegate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasessiondelegate","role":"symbol","navigatorTitle":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/delegate":{"role":"symbol","kind":"symbol","type":"topic","title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The delegate of the receiver."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/delegate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/delegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController","kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"type":"topic","title":"SBSDKBaseScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/finderView(_:didChangeRect:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/finderView(_:didChangeRect:)","kind":"symbol","navigatorTitle":[{"text":"finderView:didChangeRect:","kind":"identifier"}],"title":"finderView(_:didChangeRect:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKFinderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKFinderView"},{"text":", ","kind":"text"},{"text":"didChangeRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/finderview(_:didchangerect:)","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/suppressDetectionStatusLabel":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"suppressDetectionStatusLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/suppressDetectionStatusLabel","abstract":[{"type":"text","text":"If set to "},{"code":"false","type":"codeVoice"},{"type":"text","text":" the scanning status label is always shown, if its text is non-empty."},{"type":"text","text":" "},{"type":"text","text":"Otherwise it is hidden."}],"navigatorTitle":[{"text":"suppressDetectionStatusLabel","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/suppressdetectionstatuslabel","title":"suppressDetectionStatusLabel","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/autoSnappingSensitivity":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/autosnappingsensitivity","title":"autoSnappingSensitivity","navigatorTitle":[{"text":"autoSnappingSensitivity","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingSensitivity","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The sensitivity of auto-snapping. Values are clamped to the range 0.0 - 1.0."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/copyCurrentConfiguration()":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/copycurrentconfiguration()","kind":"symbol","abstract":[{"type":"text","text":"Returns a copy of the receivers current configuration."}],"title":"copyCurrentConfiguration()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/copyCurrentConfiguration()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKDocumentScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerConfiguration"}],"navigatorTitle":[{"text":"copyCurrentConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)UITraitEnvironment"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/autoSnapProgressPolygonConfiguration":{"type":"topic","navigatorTitle":[{"text":"autoSnapProgressPolygonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The configuration for the progress polygon displayed over the scanned document when the document is being scanned in auto snapping mode."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/autosnapprogresspolygonconfiguration","title":"autoSnapProgressPolygonConfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoSnapProgressPolygonConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerPolygonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerPolygonConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnapProgressPolygonConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController/autoCropOnManualSnap":{"navigatorTitle":[{"text":"autoCropOnManualSnap","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller\/autocroponmanualsnap","title":"autoCropOnManualSnap","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoCropOnManualSnap","type":"topic","abstract":[{"type":"text","text":"Determines whether the document should be cropped automatically after a manual snap or not."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCropOnManualSnap","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentScannerViewController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoCropOnManualSnap","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnapProgressPolygonConfiguration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingDelay","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/autoSnappingSensitivity","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/customSnapButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/delegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/detectionStatusFontSize","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/documentImageFilters","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/hidePolygonLayer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/hideSnapButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/imageScale","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/isAnimatingCapture","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/polygonConfigurationAccepted","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/polygonConfigurationRejected","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/shouldAnimateDocument","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/snapButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/statusTextConfiguration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/suppressDetectionStatusLabel","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/suppressPolygonLayer"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/captureDocumentImage()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/copyCurrentConfiguration()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/finderView(_:didChangeRect:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/init(parentViewController:parentView:delegate:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/setConfiguration(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/viewDidAppear:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/viewWillAppear:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController\/viewWillDisappear:"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewController","text":"SBSDKBaseScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoSnappingDelay\/title","op":"replace","value":"autoSnappingDelay"},{"value":[{"text":"autoSnappingDelay","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoSnappingDelay\/fragments","op":"replace"},{"value":"documentImageFilters","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1documentImageFilters\/title","op":"replace"},{"value":[{"text":"documentImageFilters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1documentImageFilters\/fragments","op":"replace"},{"value":"statusTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1statusTextConfiguration\/title","op":"replace"},{"value":[{"text":"statusTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1statusTextConfiguration\/fragments","op":"replace"},{"value":"imageScale","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1imageScale\/title","op":"replace"},{"value":[{"kind":"identifier","text":"imageScale"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1imageScale\/fragments","op":"replace"},{"value":"documentImageSizeLimit","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1documentImageSizeLimit\/title","op":"replace"},{"value":[{"text":"documentImageSizeLimit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1documentImageSizeLimit\/fragments","op":"replace"},{"value":"SBSDKDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","op":"replace"},{"value":"autoSnappingMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoSnappingMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"autoSnappingMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoSnappingMode\/fragments","op":"replace"},{"value":"snapButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1snapButton\/title","op":"replace"},{"value":[{"kind":"identifier","text":"snapButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1snapButton\/fragments","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1init()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1init()\/fragments","op":"replace"},{"value":"setConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1setConfiguration(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1setConfiguration(_:)\/fragments","op":"replace"},{"value":"suppressPolygonLayer","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1suppressPolygonLayer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"suppressPolygonLayer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1suppressPolygonLayer\/fragments","op":"replace"},{"value":"polygonConfigurationAccepted","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1polygonConfigurationAccepted\/title","op":"replace"},{"value":[{"text":"polygonConfigurationAccepted","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1polygonConfigurationAccepted\/fragments","op":"replace"},{"value":"initWithParentViewController:parentView:configuration:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParentViewController:parentView:configuration:delegate:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/fragments","op":"replace"},{"value":"SBSDKFinderView","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/title","op":"replace"},{"value":[{"text":"SBSDKFinderView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/fragments","op":"replace"},{"value":[{"text":"SBSDKFinderView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderView\/navigatorTitle","op":"replace"},{"value":"SBSDKCameraSessionObserving","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionObserving\/title","op":"replace"},{"value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionObserving\/fragments","op":"replace"},{"value":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionObserving\/navigatorTitle","op":"replace"},{"value":"hidePolygonLayer","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1hidePolygonLayer\/title","op":"replace"},{"value":[{"text":"hidePolygonLayer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1hidePolygonLayer\/fragments","op":"replace"},{"value":"SBSDKFinderViewDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderViewDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderViewDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFinderViewDelegate\/navigatorTitle","op":"replace"},{"value":"customSnapButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1customSnapButton\/title","op":"replace"},{"value":[{"text":"customSnapButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1customSnapButton\/fragments","op":"replace"},{"value":"isAnimatingCapture","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1isAnimatingCapture\/title","op":"replace"},{"value":[{"text":"isAnimatingCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1isAnimatingCapture\/fragments","op":"replace"},{"value":"SBSDKDocumentDetectionStatusOk","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionStatusOk","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1ok\/fragments","op":"replace"},{"value":"detectionStatusFontSize","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1detectionStatusFontSize\/title","op":"replace"},{"value":[{"kind":"identifier","text":"detectionStatusFontSize"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1detectionStatusFontSize\/fragments","op":"replace"},{"value":"hideSnapButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1hideSnapButton\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hideSnapButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1hideSnapButton\/fragments","op":"replace"},{"value":"initWithParentViewController:parentView:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1init(parentViewController:parentView:delegate:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1init(parentViewController:parentView:delegate:)\/fragments","op":"replace"},{"value":"polygonConfigurationRejected","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1polygonConfigurationRejected\/title","op":"replace"},{"value":[{"kind":"identifier","text":"polygonConfigurationRejected"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1polygonConfigurationRejected\/fragments","op":"replace"},{"value":"shouldAnimateDocument","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1shouldAnimateDocument\/title","op":"replace"},{"value":[{"text":"shouldAnimateDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1shouldAnimateDocument\/fragments","op":"replace"},{"value":"captureDocumentImage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1captureDocumentImage()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureDocumentImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1captureDocumentImage()\/fragments","op":"replace"},{"value":"SBSDKCameraSessionDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionDelegate\/title","op":"replace"},{"value":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionDelegate\/fragments","op":"replace"},{"value":[{"text":"SBSDKCameraSessionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSessionDelegate\/navigatorTitle","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1delegate\/title","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1delegate\/fragments","op":"replace"},{"value":"SBSDKBaseScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle","op":"replace"},{"value":"finderView:didChangeRect:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1finderView(_:didChangeRect:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finderView:didChangeRect:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1finderView(_:didChangeRect:)\/fragments","op":"replace"},{"value":"suppressDetectionStatusLabel","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1suppressDetectionStatusLabel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"suppressDetectionStatusLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1suppressDetectionStatusLabel\/fragments","op":"replace"},{"value":"autoSnappingSensitivity","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoSnappingSensitivity\/title","op":"replace"},{"value":[{"kind":"identifier","text":"autoSnappingSensitivity"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoSnappingSensitivity\/fragments","op":"replace"},{"value":"copyCurrentConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1copyCurrentConfiguration()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyCurrentConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1copyCurrentConfiguration()\/fragments","op":"replace"},{"value":"autoSnapProgressPolygonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoSnapProgressPolygonConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"autoSnapProgressPolygonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoSnapProgressPolygonConfiguration\/fragments","op":"replace"},{"value":"autoCropOnManualSnap","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoCropOnManualSnap\/title","op":"replace"},{"value":[{"text":"autoCropOnManualSnap","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController~1autoCropOnManualSnap\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}