{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"]}],"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"title":"SBSDKVolatileKeyProvider","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKVolatileKeyProvider"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"The key storage is a simple in-memory key-value store, with the key being a hashed and salted version of the context and the key length, and the value being the encryption key.","type":"text"},{"text":" ","type":"text"},{"text":"Use this provider for temporary encryption and decryption tasks or if you are a using one constant encryption key for all encryption\/decryption tasks, that can be easily be","type":"text"},{"text":" ","type":"text"},{"text":"recreated when the app is restarted, e.g. with generators as ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPBKDF2KeyGenerator","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKHKDFKeyGenerator","isActive":true,"type":"reference"},{"text":" that have fixed input values.","type":"text"}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The stored keys are lost when the app is terminated. Any encrypted data at that time will become undecryptable.","type":"text"}]}],"style":"important","name":"Important","type":"aside"}],"kind":"content"}],"abstract":[{"type":"text","text":"A volatile key provider that generates and stores keys in memory."}],"kind":"symbol","topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/init(keyGenerator:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/keyGenerator"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/provideKeyForContext(_:keyLength:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/removeAllKeys()"]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPBKDF2KeyGenerator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"kind":"symbol","title":"SBSDKPBKDF2KeyGenerator","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpbkdf2keygenerator","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPBKDF2KeyGenerator","type":"topic","abstract":[{"text":"A key generator that uses the PBKDF2 algorithm to derive a key from a password and a salt.","type":"text"},{"text":" ","type":"text"},{"text":"See https:\/\/en.wikipedia.org\/wiki\/PBKDF2 for more information.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider/provideKeyForContext(_:keyLength:)":{"abstract":[{"text":"Loads or generates the encryption\/decryption key for the given context.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"provideKeyForContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider\/providekeyforcontext(_:keylength:)","kind":"symbol","title":"provideKeyForContext(_:keyLength:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/provideKeyForContext(_:keyLength:)","navigatorTitle":[{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider":{"title":"SBSDKVolatileKeyProvider","abstract":[{"type":"text","text":"A volatile key provider that generates and stores keys in memory."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider/init(keyGenerator:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider\/init(keygenerator:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyGenerator","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","text":"SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Designated initializer."}],"navigatorTitle":[{"text":"initWithKeyGenerator:","kind":"identifier"}],"title":"init(keyGenerator:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/init(keyGenerator:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKHKDFKeyGenerator":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkhkdfkeygenerator","role":"symbol","abstract":[{"type":"text","text":"A key generator that uses the HMAC based HKDF algorithm to generate a new encryption key. SHA512 is used as the hash function."},{"type":"text","text":" "},{"type":"text","text":"The key generation consists of two phases: extraction and expansion."},{"type":"text","text":" "},{"type":"text","text":"During the extraction a pseudo random key is generated from the input key material and an optional salt."},{"type":"text","text":" "},{"type":"text","text":"The expansion phase uses the pseudo random key and the info data block to derive the final key."}],"title":"SBSDKHKDFKeyGenerator","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKHKDFKeyGenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider/removeAllKeys()":{"navigatorTitle":[{"text":"removeAllKeys","kind":"identifier"}],"title":"removeAllKeys()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/removeAllKeys()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllKeys","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Removes all keys from the provider.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider\/removeallkeys()","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingKeyProvider":{"title":"SBSDKStorageCryptingKeyProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider","role":"symbol","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"abstract":[{"text":"Protocol for loading, storing and providing encryption keys.","type":"text"},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingkeyprovider"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider/keyGenerator":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyGenerator","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","text":"SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"keyGenerator","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The key generator that generates an encryption key for a context if no key is available yet.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider\/keygenerator","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/keyGenerator","title":"keyGenerator","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVolatileKeyProvider/deleteKeyForContext(_:keyLength:)":{"abstract":[{"text":"Deletes the key for the given context and key length.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"deleteKeyForContext:keyLength:","kind":"identifier"}],"kind":"symbol","title":"deleteKeyForContext(_:keyLength:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvolatilekeyprovider\/deletekeyforcontext(_:keylength:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteKeyForContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKVolatileKeyProvider","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/keyGenerator"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/deleteKeyForContext(_:keyLength:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/init(keyGenerator:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/provideKeyForContext(_:keyLength:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVolatileKeyProvider\/removeAllKeys()"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingKeyProvider"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKPBKDF2KeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPBKDF2KeyGenerator\/title","op":"replace"},{"value":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPBKDF2KeyGenerator\/fragments","op":"replace"},{"value":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPBKDF2KeyGenerator\/navigatorTitle","op":"replace"},{"value":"provideKeyForContext:keyLength:error:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1provideKeyForContext(_:keyLength:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"provideKeyForContext:keyLength:error:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1provideKeyForContext(_:keyLength:)\/fragments","op":"replace"},{"value":"SBSDKVolatileKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/fragments","op":"replace"},{"value":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider\/navigatorTitle","op":"replace"},{"value":"initWithKeyGenerator:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1init(keyGenerator:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyGenerator:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1init(keyGenerator:)\/fragments","op":"replace"},{"value":"SBSDKHKDFKeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKHKDFKeyGenerator\/title","op":"replace"},{"value":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKHKDFKeyGenerator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKHKDFKeyGenerator\/navigatorTitle","op":"replace"},{"value":"removeAllKeys","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1removeAllKeys()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"removeAllKeys","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1removeAllKeys()\/fragments","op":"replace"},{"value":"SBSDKStorageCryptingKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/title","op":"replace"},{"value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle","op":"replace"},{"value":"keyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1keyGenerator\/title","op":"replace"},{"value":[{"text":"keyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1keyGenerator\/fragments","op":"replace"},{"value":"deleteKeyForContext:keyLength:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1deleteKeyForContext(_:keyLength:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteKeyForContext:keyLength:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVolatileKeyProvider~1deleteKeyForContext(_:keyLength:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}