{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"title":"SBSDKCameraDeviceType","symbolKind":"enum","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDeviceType"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType"},"sections":[],"abstract":[{"text":"An enum to describe the different types of camera lenses\/devices.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/dual","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/dualWide","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/simulated","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/tele","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/triple","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/ultraWide","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/wide"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"kind":"relationships","type":"conformsTo"}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/tele":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/tele","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tele"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The telephoto lens\/device."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/tele","title":"SBSDKCameraDeviceType.tele","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeTele"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/dualWide":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeDualWide"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dualWide"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/dualWide","kind":"symbol","abstract":[{"type":"text","text":"The dual-wide lens\/device (wide + ultra-wide)."}],"role":"symbol","title":"SBSDKCameraDeviceType.dualWide","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/dualwide"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/init(rawValue:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/init(rawValue:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/rawrepresentable-implementations","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/Equatable-Implementations":{"type":"topic","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/Equatable-Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/equatable-implementations","kind":"article","title":"Equatable Implementations","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"An enum to describe the different types of camera lenses\/devices.","type":"text"}],"title":"SBSDKCameraDeviceType","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/dual":{"title":"SBSDKCameraDeviceType.dual","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dual","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraDeviceTypeDual","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The dual lens\/device (wide + tele)."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/dual","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/dual","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/simulated":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/simulated","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/simulated","abstract":[{"type":"text","text":"A simulated camera that can simulate a video stream by looping a video or a single image."},{"type":"text","text":" "},{"type":"text","text":"Also used on iPhone\/iPad simulators without providing a video stream."}],"navigatorTitle":[{"text":"SBSDKCameraDeviceTypeSimulated","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simulated","kind":"identifier"}],"title":"SBSDKCameraDeviceType.simulated","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/ultraWide":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ultraWide","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/ultrawide","title":"SBSDKCameraDeviceType.ultraWide","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeUltraWide","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The ultra-wide lens\/device.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/ultraWide"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/triple":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/triple","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/triple","abstract":[{"text":"The triple lens\/device (ultra-wide + wide + tele).","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeTriple"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"triple"}],"title":"SBSDKCameraDeviceType.triple","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/wide":{"title":"SBSDKCameraDeviceType.wide","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeWide","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/wide","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/wide","abstract":[{"text":"The wide angle lens\/device.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wide","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKCameraDeviceType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/dual","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/dualWide","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/simulated","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/tele","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/triple","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/ultraWide","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/wide"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKCameraDeviceTypeTele","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1tele\/title"},{"op":"replace","value":[{"text":"SBSDKCameraDeviceTypeTele","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1tele\/fragments"},{"op":"replace","value":"SBSDKCameraDeviceTypeDualWide","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1dualWide\/title"},{"op":"replace","value":[{"text":"SBSDKCameraDeviceTypeDualWide","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1dualWide\/fragments"},{"op":"replace","value":"SBSDKCameraDeviceType","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/title"},{"op":"replace","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/fragments"},{"op":"replace","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/navigatorTitle"},{"op":"replace","value":"SBSDKCameraDeviceTypeDual","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1dual\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeDual"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1dual\/fragments"},{"op":"replace","value":"SBSDKCameraDeviceTypeSimulated","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1simulated\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeSimulated"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1simulated\/fragments"},{"op":"replace","value":"SBSDKCameraDeviceTypeUltraWide","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1ultraWide\/title"},{"op":"replace","value":[{"text":"SBSDKCameraDeviceTypeUltraWide","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1ultraWide\/fragments"},{"op":"replace","value":"SBSDKCameraDeviceTypeTriple","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1triple\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeTriple"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1triple\/fragments"},{"op":"replace","value":"SBSDKCameraDeviceTypeWide","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1wide\/title"},{"op":"replace","value":[{"text":"SBSDKCameraDeviceTypeWide","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1wide\/fragments"}]}]}