{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/sbsdkcheckscannerviewcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/sbsdkcheckscannerviewcontrollerdelegate-implementations"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/SBSDKCheckScannerViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/checkScannerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/checkScannerViewController(_:didScanCheck:)"],"generated":true}],"metadata":{"role":"collectionGroup","modules":[{"name":"ScanbotSDK"}],"roleHeading":"API Collection","title":"SBSDKCheckScannerViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController":{"type":"topic","navigatorTitle":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController","kind":"symbol","title":"SBSDKUICheckScannerViewController","abstract":[{"type":"text","text":"A Ready-To-Use viewController to scan checks using the camera."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/checkScannerViewController(_:didChangeState:)":{"role":"symbol","navigatorTitle":[{"text":"checkScannerViewController:didChangeState:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","text":"SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeState","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckScannerState","text":"SBSDKCheckScannerState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"checkScannerViewController(_:didChangeState:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/checkScannerViewController(_:didChangeState:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has changed its scanning state. Optional."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/checkscannerviewcontroller(_:didchangestate:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerViewController/checkScannerViewController(_:didScanCheck:)":{"title":"checkScannerViewController(_:didScanCheck:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has successfully scanned a check."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerviewcontroller\/checkscannerviewcontroller(_:didscancheck:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanCheck","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCheckScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"checkScannerViewController:didScanCheck:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/checkScannerViewController(_:didScanCheck:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/checkScannerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerViewController\/checkScannerViewController(_:didScanCheck:)"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"SBSDKUICheckScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUICheckScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/fragments"},{"value":[{"text":"SBSDKUICheckScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController\/navigatorTitle"},{"value":"checkScannerViewController:didChangeState:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController~1checkScannerViewController(_:didChangeState:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkScannerViewController:didChangeState:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController~1checkScannerViewController(_:didChangeState:)\/fragments"},{"value":"checkScannerViewController:didScanCheck:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController~1checkScannerViewController(_:didScanCheck:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"checkScannerViewController:didScanCheck:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerViewController~1checkScannerViewController(_:didScanCheck:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}