{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration"]]},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUICheckRecognizerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerUIConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUICheckRecognizerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerTextConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUICheckRecognizerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","navigatorTitle":[{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerConfiguration(im)initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","roleHeading":"Initializer","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)"]}],"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration","isActive":true},{"type":"text","text":"."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerUIConfiguration"},{"kind":"text","text":", "},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration","text":"SBSDKUICheckRecognizerTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerTextConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"behaviorConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerBehaviorConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier","text":"SBSDKUICameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A configuration for the user interface. Defines colors and sizes.","type":"text"}]}],"name":"uiConfiguration"},{"content":[{"inlineContent":[{"type":"text","text":"A configuration for text being displayed in the document scanning screen."}],"type":"paragraph"}],"name":"textConfiguration"},{"name":"behaviorConfiguration","content":[{"inlineContent":[{"type":"text","text":"A configuration for defining the behavior of the document scanning screen."}],"type":"paragraph"}]},{"name":"cameraConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration object for defining the camera of the document scanning screen.","type":"text"}]}]}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"navigatorTitle":[{"text":"SBSDKUICheckRecognizerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration","title":"SBSDKUICheckRecognizerConfiguration","role":"symbol","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI check scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerUIConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckRecognizerUIConfiguration"}],"navigatorTitle":[{"text":"SBSDKUICheckRecognizerUIConfiguration","kind":"identifier"}],"title":"SBSDKUICheckRecognizerUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration for the user interface of the RTU-UI check scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerTextConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizertextconfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the  RTU-UI check scanner."}],"type":"topic","kind":"symbol","title":"SBSDKUICheckRecognizerTextConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICheckRecognizerTextConfiguration"}],"navigatorTitle":[{"text":"SBSDKUICheckRecognizerTextConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerBehaviorConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerBehaviorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerbehaviorconfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI check scanner."}],"type":"topic","kind":"symbol","title":"SBSDKUICheckRecognizerBehaviorConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerBehaviorConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUICheckRecognizerBehaviorConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:)","abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration","isActive":true},{"type":"text","text":"."}],"type":"topic","kind":"symbol","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"uiConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerUIConfiguration","text":"SBSDKUICheckRecognizerUIConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"textConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerTextConfiguration"},{"text":", ","kind":"text"},{"text":"behaviorConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerBehaviorConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier","text":"SBSDKUICameraConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"abstract":[{"text":"Configuration for the camera of all RTU-UI components.","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKUICameraConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithUiConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerUIConfiguration","text":"SBSDKUICheckRecognizerUIConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"uiConfiguration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"textConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerTextConfiguration"},{"text":" *) ","kind":"text"},{"text":"textConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"behaviorConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUICheckRecognizerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerBehaviorConfiguration"},{"text":" *) ","kind":"text"},{"text":"behaviorConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraConfiguration:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","kind":"typeIdentifier","text":"SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraConfiguration"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUICheckRecognizerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/title"},{"value":[{"text":"SBSDKUICheckRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/fragments","op":"replace"},{"op":"replace","value":"SBSDKUICheckRecognizerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration\/fragments","value":[{"text":"SBSDKUICheckRecognizerUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration\/title","value":"SBSDKUICheckRecognizerTextConfiguration","op":"replace"},{"value":[{"text":"SBSDKUICheckRecognizerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerTextConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerBehaviorConfiguration\/title","value":"SBSDKUICheckRecognizerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUICheckRecognizerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/title","op":"replace","value":"SBSDKUICameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICameraConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}