{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureNotSet"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failurenotset"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failurenotset"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus\/failureNotSet","interfaceLanguage":"swift"},"abstract":[{"text":"No license set. On platforms that support trial mode, it means that the SDK’s trial mode is over.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"SBSDKLicenseStatusFailureNotSet","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureNotSet","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusFailureNotSet","roleHeading":"Case","title":"SBSDKLicenseStatus.failureNotSet","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseStatus":{"type":"topic","title":"SBSDKLicenseStatus","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"abstract":[{"text":"Status of the license plate scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseStatus/failureNotSet":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failurenotset","navigatorTitle":[{"text":"SBSDKLicenseStatusFailureNotSet","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureNotSet","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus\/failureNotSet","abstract":[{"type":"text","text":"No license set. On platforms that support trial mode, it means that the SDK’s trial mode is over."}],"type":"topic","title":"SBSDKLicenseStatus.failureNotSet"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKLicenseStatusFailureNotSet","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureNotSet"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureNotSet"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKLicenseStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/title"},{"value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus~1failureNotSet\/title","op":"replace","value":"SBSDKLicenseStatusFailureNotSet"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus~1failureNotSet\/fragments","op":"replace","value":[{"text":"SBSDKLicenseStatusFailureNotSet","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}