{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failureinactive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failureinactive"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus\/failureInactive"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"SBSDKLicenseStatusFailureInactive","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusFailureInactive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureInactive","kind":"identifier"}],"title":"SBSDKLicenseStatus.failureInactive","role":"symbol","roleHeading":"Case"},"abstract":[{"type":"text","text":"No license active. The set license is not yet active."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureInactive"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseStatus":{"type":"topic","title":"SBSDKLicenseStatus","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"abstract":[{"text":"Status of the license plate scanner.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseStatus/failureInactive":{"title":"SBSDKLicenseStatus.failureInactive","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus\/failureInactive","abstract":[{"text":"No license active. The set license is not yet active.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatusFailureInactive","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus\/failureinactive","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureInactive","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKLicenseStatusFailureInactive","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureInactive"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKLicenseStatusFailureInactive","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKLicenseStatus","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/fragments"},{"op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/navigatorTitle"},{"op":"replace","value":"SBSDKLicenseStatusFailureInactive","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus~1failureInactive\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseStatusFailureInactive","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus~1failureInactive\/fragments"}]}]}