{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarLimitedConfiguration"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"new","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarlimitedconfiguration\/new"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarLimitedConfiguration\/new","interfaceLanguage":"occ"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"new"}],"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataBarLimitedConfiguration(cm)new","modules":[{"name":"ScanbotSDK"}],"title":"new","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataBarLimitedConfiguration":{"navigatorTitle":[{"text":"SBSDKBarcodeFormatDataBarLimitedConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatDataBarLimitedConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarlimitedconfiguration","abstract":[{"type":"text","text":"GS1 DataBar Limited barcode configuration. Add to scanner configuration to scan GS1 DataBar Limited barcodes."}],"kind":"symbol","title":"SBSDKBarcodeFormatDataBarLimitedConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarLimitedConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataBarLimitedConfiguration/new":{"navigatorTitle":[{"text":"new","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatabarlimitedconfiguration\/new","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataBarLimitedConfiguration\/new","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"role":"symbol","title":"new","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarLimitedConfiguration\/title","value":"SBSDKBarcodeFormatDataBarLimitedConfiguration"},{"value":[{"text":"SBSDKBarcodeFormatDataBarLimitedConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarLimitedConfiguration\/fragments"},{"value":[{"text":"SBSDKBarcodeFormatDataBarLimitedConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataBarLimitedConfiguration\/navigatorTitle","op":"replace"}]}]}