{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"right"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextorientation\/right"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextorientation\/right"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation\/right"},"metadata":{"title":"SBSDKTextOrientation.right","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextOrientationRight"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKTextOrientation@SBSDKTextOrientationRight"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation"]]},"abstract":[{"type":"text","text":"The text is rotated 90 degrees in clockwise direction."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextOrientation":{"url":"\/documentation\/scanbotsdk\/sbsdktextorientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextOrientation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTextOrientation","kind":"identifier"}],"abstract":[{"text":"An enum to describes the detected orientation of text in an image.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation","title":"SBSDKTextOrientation","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextOrientation/right":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"navigatorTitle":[{"text":"SBSDKTextOrientationRight","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The text is rotated 90 degrees in clockwise direction.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextOrientation\/right","title":"SBSDKTextOrientation.right","url":"\/documentation\/scanbotsdk\/sbsdktextorientation\/right"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"SBSDKTextOrientationRight","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKTextOrientationRight","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKTextOrientationRight","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/title","value":"SBSDKTextOrientation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation\/fragments","value":[{"text":"SBSDKTextOrientation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation~1right\/title","value":"SBSDKTextOrientationRight"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextOrientation~1right\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextOrientationRight"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}