{"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configureStatusDetectionLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel","text":"SBSDKDetectionStatusLabel"},{"text":", ","kind":"text"},{"text":"forDetectionResult","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":"?)","kind":"text"}],"extendedModule":"ScanbotDocumentScannerSDK","externalID":"c:@CM@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController(im)documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","navigatorTitle":[{"kind":"identifier","text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController\/SBSDKDocumentScannerViewControllerDelegate-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Optional."},{"text":" ","type":"text"},{"type":"text","text":"Lets you configure the document detections status label, depending on the document detection status."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configureStatusDetectionLabel"},{"text":" ","kind":"text"},{"text":"label","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDetectionStatusLabel","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel"},{"kind":"text","text":", "},{"text":"forDetectionResult","kind":"externalParam"},{"kind":"text","text":" "},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}],"type":"paragraph"}]},{"name":"label","content":[{"type":"paragraph","inlineContent":[{"text":"The label to be configured.","type":"text"}]}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the current document detection."}]}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can change the visibility, colors, font, and text of the label here."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 5.2.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController/SBSDKDocumentScannerViewControllerDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController\/SBSDKDocumentScannerViewControllerDelegate-Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/sbsdkdocumentscannerviewcontrollerdelegate-implementations","role":"collectionGroup","kind":"article","abstract":[],"title":"SBSDKDocumentScannerViewControllerDelegate Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"title":"SBSDKDocumentScannerViewController","type":"topic","abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document detector.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)":{"type":"topic","title":"documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","role":"symbol","abstract":[{"text":"Optional.","type":"text"},{"text":" ","type":"text"},{"text":"Lets you configure the document detections status label, depending on the document detection status.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configureStatusDetectionLabel","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel","kind":"typeIdentifier","text":"SBSDKDetectionStatusLabel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forDetectionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDetectionStatusLabel":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdetectionstatuslabel","title":"SBSDKDetectionStatusLabel","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":" subclass with rounded corners and content insets to display the status of the current document detection result."}],"navigatorTitle":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","abstract":[],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller","navigatorTitle":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SBSDKUIDocumentScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectorResult":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectorresult","title":"SBSDKDocumentDetectorResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"abstract":[{"type":"text","text":"This class represents the result of a document detection"},{"type":"text","text":" "},{"type":"text","text":"on an image."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"documentScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"configureStatusDetectionLabel:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDetectionStatusLabel","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDetectionStatusLabel","text":"SBSDKDetectionStatusLabel"},{"kind":"text","text":" *) "},{"text":"label","kind":"internalParam"},{"kind":"text","text":" "},{"text":"forDetectionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace"},{"value":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDetectionStatusLabel\/title","value":"SBSDKDetectionStatusLabel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDetectionStatusLabel\/fragments","value":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/title","value":"SBSDKUIDocumentScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/title","op":"replace","value":"SBSDKDocumentDetectorResult"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/fragments","op":"replace"}]}]}