{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKShutterButton\/buttonDetectedColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKShutterButton"]]},"abstract":[{"type":"text","text":"The main color of the receiver while the scanner status is "},{"type":"codeVoice","code":"SBSDKScannerStatusDetected"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to white.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonDetectedColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKShutterButton(py)buttonDetectedColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buttonDetectedColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"buttonDetectedColor","kind":"identifier"}],"title":"buttonDetectedColor"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkshutterbutton\/buttondetectedcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkshutterbutton\/buttondetectedcolor"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKShutterButton":{"title":"SBSDKShutterButton","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKShutterButton"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The button class used in the camera view controller to take a snapshot."},{"type":"text","text":" "},{"type":"text","text":"Animates itself depending on its status."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkshutterbutton","navigatorTitle":[{"text":"SBSDKShutterButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKShutterButton"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKShutterButton/buttonDetectedColor":{"title":"buttonDetectedColor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKShutterButton\/buttonDetectedColor","abstract":[{"type":"text","text":"The main color of the receiver while the scanner status is "},{"type":"codeVoice","code":"SBSDKScannerStatusDetected"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Defaults to white."}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkshutterbutton\/buttondetectedcolor","navigatorTitle":[{"text":"buttonDetectedColor","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"buttonDetectedColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"buttonDetectedColor"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"buttonDetectedColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"buttonDetectedColor"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKShutterButton\/title","op":"replace","value":"SBSDKShutterButton"},{"value":[{"kind":"identifier","text":"SBSDKShutterButton"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKShutterButton\/fragments"},{"value":"buttonDetectedColor","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKShutterButton~1buttonDetectedColor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"buttonDetectedColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKShutterButton~1buttonDetectedColor\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}