{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKShutterButton\/layoutSubviews"},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKShutterButton(im)layoutSubviews","title":"layoutSubviews","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"text":"layoutSubviews","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKShutterButton"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkshutterbutton\/layoutsubviews"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKShutterButton":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKShutterButton"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkshutterbutton","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKShutterButton","type":"topic","kind":"symbol","title":"SBSDKShutterButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKShutterButton"}],"abstract":[{"text":"The button class used in the camera view controller to take a snapshot.","type":"text"},{"text":" ","type":"text"},{"text":"Animates itself depending on its status.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKShutterButton/layoutSubviews":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkshutterbutton\/layoutsubviews","title":"layoutSubviews","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKShutterButton\/layoutSubviews","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKShutterButton","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKShutterButton\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKShutterButton\/fragments","op":"replace","value":[{"text":"SBSDKShutterButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKShutterButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKShutterButton"}],"op":"replace"}]}]}