{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset\/initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMrzTextLine1:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"mrzTextLine1","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mrzTextLine2:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"mrzTextLine2","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"adjustedFinderAspectRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"adjustedFinderAspectRatio","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset\/initwithmrztextline1:mrztextline2:adjustedfinderaspectratio:"]}],"sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset(im)initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","navigatorTitle":[{"text":"initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TwoLineMRZFinderLayoutPreset":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}],"title":"SBSDKUI2TwoLineMRZFinderLayoutPreset","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A ready-to-use preset 2-line text to be displayed."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TwoLineMRZFinderLayoutPreset/initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset\/initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","kind":"symbol","navigatorTitle":[{"text":"initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","kind":"identifier"}],"title":"initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithMrzTextLine1:mrzTextLine2:adjustedFinderAspectRatio:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset\/initwithmrztextline1:mrztextline2:adjustedfinderaspectratio:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/title","op":"replace","value":"SBSDKUI2TwoLineMRZFinderLayoutPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/fragments","op":"replace","value":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}]}]}]}