{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:)-8qvdo"},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","externalID":"s:10ScanbotSDK17SBSDKPDFGeneratorC8generate4from6output10Foundation3URLVSgAA20SBSDKScannedDocumentC_AJtYaKF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method","title":"generate(from:output:)"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:output:)-8qvdo"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"scannedDocument","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"? = nil) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The scanned document the PDF should be generated from.","type":"text"}],"type":"paragraph"}],"name":"scannedDocument"},{"name":"output","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output file URL. If "},{"code":"nil","type":"codeVoice"},{"text":"the default PDF location of the scanned document will be used.","type":"text"}]}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The URL the PDF file has been written to or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Asynchronously generates the PDF file from the given scanned document and saves it to the specified URL"},{"type":"text","text":" "},{"type":"text","text":"Each page is made up of one image."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","role":"symbol","navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"title":"SBSDKScannedDocument","abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator":{"navigatorTitle":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFGenerator","kind":"identifier"}],"title":"SBSDKPDFGenerator","type":"topic","abstract":[{"text":"A class to generate an ordered collection of images with or without performing HOCR.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:output:)-8qvdo":{"title":"generate(from:output:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:output:)-8qvdo","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generate","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:output:)-8qvdo","abstract":[{"text":"Asynchronously generates the PDF file from the given scanned document and saves it to the specified URL","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each page is made up of one image."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument"},{"value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/title","value":"SBSDKPDFGenerator"},{"value":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPDFGenerator"}]}]}]}