{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Field 4: given names","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardFieldType@SBSDKHealthInsuranceCardFieldTypeGivenName","symbolKind":"case","title":"SBSDKHealthInsuranceCardFieldType.givenName","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"givenName"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeGivenName","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/givenName","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"givenName","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/givenname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/givenname"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldType"}],"abstract":[{"type":"text","text":"Health insurance card field type."}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType","title":"SBSDKHealthInsuranceCardFieldType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/givenName":{"title":"SBSDKHealthInsuranceCardFieldType.givenName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"givenName","kind":"identifier"}],"abstract":[{"text":"Field 4: given names","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/givenname","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeGivenName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/givenName","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKHealthInsuranceCardFieldTypeGivenName","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKHealthInsuranceCardFieldTypeGivenName","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKHealthInsuranceCardFieldTypeGivenName","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKHealthInsuranceCardFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/title"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1givenName\/title","value":"SBSDKHealthInsuranceCardFieldTypeGivenName","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeGivenName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1givenName\/fragments","op":"replace"}]}]}