{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionNumber"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/institutionnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/institutionnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"institutionNumber","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardFieldType@SBSDKHealthInsuranceCardFieldTypeInstitutionNumber","symbolKind":"case","title":"SBSDKHealthInsuranceCardFieldType.institutionNumber","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber"}],"role":"symbol","roleHeading":"Case"},"abstract":[{"type":"text","text":"Field 7 (part before dash): institution number"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"institutionNumber"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/institutionNumber":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"institutionNumber","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionNumber","abstract":[{"text":"Field 7 (part before dash): institution number","type":"text"}],"title":"SBSDKHealthInsuranceCardFieldType.institutionNumber","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/institutionnumber","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType":{"title":"SBSDKHealthInsuranceCardFieldType","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"abstract":[{"type":"text","text":"Health insurance card field type."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1institutionNumber\/title","value":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1institutionNumber\/fragments","value":[{"text":"SBSDKHealthInsuranceCardFieldTypeInstitutionNumber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/title","value":"SBSDKHealthInsuranceCardFieldType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/fragments","value":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}