{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionName","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/institutionname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/institutionname"]}],"abstract":[{"text":"Field 7 (part after dash): institution name or abbreviation","type":"text"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeInstitutionName"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardFieldType@SBSDKHealthInsuranceCardFieldTypeInstitutionName","title":"SBSDKHealthInsuranceCardFieldType.institutionName","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"institutionName","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"institutionName","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType":{"abstract":[{"type":"text","text":"Health insurance card field type."}],"title":"SBSDKHealthInsuranceCardFieldType","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldType"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/institutionName":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"institutionName"}],"abstract":[{"type":"text","text":"Field 7 (part after dash): institution name or abbreviation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeInstitutionName"}],"title":"SBSDKHealthInsuranceCardFieldType.institutionName","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/institutionname","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/institutionName","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKHealthInsuranceCardFieldTypeInstitutionName"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldTypeInstitutionName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeInstitutionName"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/title","value":"SBSDKHealthInsuranceCardFieldType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1institutionName\/title","value":"SBSDKHealthInsuranceCardFieldTypeInstitutionName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1institutionName\/fragments","value":[{"text":"SBSDKHealthInsuranceCardFieldTypeInstitutionName","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}