{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate\/barcodesbatchscannerviewcontroller(_:didfinishwith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate\/barcodesbatchscannerviewcontroller(_:didfinishwith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"modules":[{"name":"ScanbotSDK"}],"title":"barcodesBatchScannerViewController(_:didFinishWith:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodesBatchScannerViewControllerDelegate(im)barcodesBatchScannerViewController:didFinishWithResults:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"barcodesBatchScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController","kind":"typeIdentifier","text":"SBSDKUIBarcodesBatchScannerViewController"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKUIBarcodeMappedResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedResult","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"barcodesBatchScannerViewController:didFinishWithResults:"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewController(_:didFinishWith:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(barcodesBatchScannerViewController:didFinishWithResults:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodesBatchScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","text":"SBSDKUIBarcodesBatchScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"barcodeResults"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedResult","text":"SBSDKUIBarcodeMappedResult"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"text":"The scanner view controller that scanned barcode(s).","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"An array of SBSDKBarcodeScannerResult objects containing scanned barcodes."}],"type":"paragraph"}],"name":"barcodeResults"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Informs the delegate that one or more barcodes have been scanned and the view controller has dismissed."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewControllerDelegate/barcodesBatchScannerViewController(_:didFinishWith:)":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate\/barcodesbatchscannerviewcontroller(_:didfinishwith:)","title":"barcodesBatchScannerViewController(_:didFinishWith:)","navigatorTitle":[{"text":"barcodesBatchScannerViewController:didFinishWithResults:","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewController(_:didFinishWith:)","abstract":[{"type":"text","text":"Informs the delegate that one or more barcodes have been scanned and the view controller has dismissed."}],"required":true,"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodesBatchScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeMappedResult","kind":"typeIdentifier","text":"SBSDKUIBarcodeMappedResult"},{"kind":"text","text":"])"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeMappedResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeMappedResult"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodemappedresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeMappedResult","title":"SBSDKUIBarcodeMappedResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeMappedResult"}],"deprecated":true,"abstract":[{"type":"text","text":"Class that contains barcode result and mapped data."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewController":{"type":"topic","abstract":[{"text":"A highly customizable camera-based view controller to scan barcodes batches.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"deprecated":true,"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontroller","kind":"symbol","role":"symbol","title":"SBSDKUIBarcodesBatchScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerViewControllerDelegate":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate","abstract":[{"type":"text","text":"Delegate protocol for "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"}],"deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"barcodesBatchScannerViewController:didFinishWithResults:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodesBatchScannerViewController:didFinishWithResults:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"barcodesBatchScannerViewController:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerViewController","kind":"typeIdentifier","text":"SBSDKUIBarcodesBatchScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishWithResults:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKUIBarcodeMappedResult *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeResults","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scanner view controller that scanned barcode(s)."}]}],"name":"viewController"},{"content":[{"inlineContent":[{"type":"text","text":"An array of SBSDKBarcodeScannerResult objects containing scanned barcodes."}],"type":"paragraph"}],"name":"barcodeResults"}],"kind":"parameters"}},{"value":"barcodesBatchScannerViewController:didFinishWithResults:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate~1barcodesBatchScannerViewController(_:didFinishWith:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"barcodesBatchScannerViewController:didFinishWithResults:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate~1barcodesBatchScannerViewController(_:didFinishWith:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult\/title","value":"SBSDKUIBarcodeMappedResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult\/fragments","value":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIBarcodeMappedResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeMappedResult\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}