{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/initwithformat:text:rawbytes:rawbytesencodings:structuredappendinfo:quad:quadnormalized:extendedquad:extendedquadnormalized:isupsidedown:sourceimage:upceanextension:isgs1message:isgs1compositepart:databarstacksize:sizescore:extracteddocumen-81ru7"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem(im)initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat"},{"text":" *) ","kind":"text"},{"text":"format","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"text:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rawBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawBytes"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBytesEncodings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKRangeEncoding *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawBytesEncodings"},{"kind":"text","text":" "},{"kind":"identifier","text":"structuredAppendInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKStructuredAppendInfo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"structuredAppendInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"quad:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quad"},{"kind":"text","text":" "},{"kind":"identifier","text":"quadNormalized:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quadNormalized"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendedQuad:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"extendedQuad"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendedQuadNormalized:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"extendedQuadNormalized"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUpsideDown:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isUpsideDown"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sourceImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"upcEanExtension:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"upcEanExtension"},{"kind":"text","text":" "},{"kind":"identifier","text":"isGS1Message:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isGS1Message"},{"kind":"text","text":" "},{"kind":"identifier","text":"isGS1CompositePart:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isGS1CompositePart"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataBarStackSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dataBarStackSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractedDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"extractedDocument"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"globalIndex"},{"kind":"text","text":";"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem/initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/initwithformat:text:rawbytes:rawbytesencodings:structuredappendinfo:quad:quadnormalized:extendedquad:extendedquadnormalized:isupsidedown:sourceimage:upceanextension:isgs1message:isgs1compositepart:databarstacksize:sizescore:extracteddocumen-81ru7","title":"initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFormat:text:rawBytes:rawBytesEncodings:structuredAppendInfo:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","abstract":[{"type":"text","text":"Generic document."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"type":"topic","title":"SBSDKGenericDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo":{"title":"SBSDKStructuredAppendInfo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo","navigatorTitle":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"The structured append mode can be used to split a message across multiple barcodes."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormat":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","abstract":[{"type":"text","text":"Enumerates barcode formats."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"title":"SBSDKBarcodeFormat","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormat"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","title":"SBSDKBarcodeItem","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","type":"topic","abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are considered separate barcodes.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"abstract":[{"text":"Image ref class.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}],"type":"topic","title":"SBSDKImageRef","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","url":"\/documentation\/scanbotsdk\/sbsdkimageref","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","op":"replace","value":"SBSDKGenericDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/title","op":"replace","value":"SBSDKStructuredAppendInfo"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/title","op":"replace","value":"SBSDKBarcodeFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","op":"replace","value":"SBSDKBarcodeItem"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","op":"replace","value":"SBSDKImageRef"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRef"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}