{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraModule"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"defaultZoomFactor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"flashEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minFocusDistanceLock"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pinchToZoomEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewMode"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"captureQualityPrioritization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","text":"SBSDKUI2CapturePhotoQualityPrioritization"},{"text":", ","kind":"text"},{"text":"acceptedAngleScore","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"acceptedSizeScore"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoSnappingSensitivity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoSnappingDelay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoSnappingEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"requiredAspectRatios","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKUI2AspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AspectRatio","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"ignoreBadAspectRatio","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"captureWithHardwareButtonsEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration(im)initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","role":"symbol","symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraModule"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule","kind":"typeIdentifier","text":"SBSDKUI2CameraModule"},{"kind":"text","text":" = SBSDKUI2CameraModule.back, "},{"kind":"externalParam","text":"defaultZoomFactor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = 1.0, "},{"text":"flashEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"minFocusDistanceLock","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"text":"cameraPreviewMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","text":"SBSDKUI2CameraPreviewMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode"},{"kind":"text","text":" = SBSDKUI2CameraPreviewMode.fillIn, "},{"text":"captureQualityPrioritization","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","text":"SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization"},{"kind":"text","text":" = SBSDKUI2CapturePhotoQualityPrioritization.balanced, "},{"text":"acceptedAngleScore","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = 0.75, "},{"text":"acceptedSizeScore","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" = 0.75, ","kind":"text"},{"kind":"externalParam","text":"autoSnappingSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":" = 0.66, ","kind":"text"},{"kind":"externalParam","text":"autoSnappingDelay"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 200, "},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 50, ","kind":"text"},{"text":"autoSnappingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"requiredAspectRatios"},{"kind":"text","text":": ["},{"text":"SBSDKUI2AspectRatio","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AspectRatio"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"ignoreBadAspectRatio"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"captureWithHardwareButtonsEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = true)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-buha"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-buha"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization","title":"SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerCameraConfiguration/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cameraModule"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule"},{"kind":"text","text":", "},{"kind":"externalParam","text":"defaultZoomFactor"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"flashEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minFocusDistanceLock"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cameraPreviewMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captureQualityPrioritization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","text":"SBSDKUI2CapturePhotoQualityPrioritization"},{"kind":"text","text":", "},{"kind":"externalParam","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"acceptedSizeScore","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"autoSnappingSensitivity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoSnappingDelay"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoSnappingEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"requiredAspectRatios","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKUI2AspectRatio","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AspectRatio","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"ignoreBadAspectRatio"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captureWithHardwareButtonsEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration\/init(cameramodule:defaultzoomfactor:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:acceptedanglescore:acceptedsizescore:autosnappingsensitivity:autosnappingdelay:acceptedbrightnessthresho-buha","abstract":[],"title":"init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)","role":"symbol","navigatorTitle":[{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode":{"title":"SBSDKUI2CameraPreviewMode","abstract":[{"text":"Configuration of the camera preview mode.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AspectRatio":{"abstract":[{"type":"text","text":"Configuration of the finder’s aspect ratio."}],"type":"topic","title":"SBSDKUI2AspectRatio","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AspectRatio","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2aspectratio","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraModule":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraModule","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2cameramodule","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"title":"SBSDKUI2CameraModule","role":"symbol","abstract":[{"text":"Determine which camera module to use on start-up.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerCameraConfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCameraModule:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule","text":"SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraModule","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraModule","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"defaultZoomFactor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"text":"defaultZoomFactor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"flashEnabled:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"flashEnabled"},{"text":" ","kind":"text"},{"text":"minFocusDistanceLock:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minFocusDistanceLock"},{"kind":"text","text":" "},{"text":"pinchToZoomEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"pinchToZoomEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewMode:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureQualityPrioritization:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization"},{"kind":"text","text":") "},{"text":"captureQualityPrioritization","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedAngleScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"acceptedAngleScore","kind":"internalParam"},{"kind":"text","text":" "},{"text":"acceptedSizeScore:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"acceptedSizeScore"},{"text":" ","kind":"text"},{"text":"autoSnappingSensitivity:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoSnappingSensitivity"},{"kind":"text","text":" "},{"text":"autoSnappingDelay:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"autoSnappingDelay","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedBrightnessThreshold:"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"acceptedBrightnessThreshold"},{"text":" ","kind":"text"},{"text":"autoSnappingEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"autoSnappingEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredAspectRatios:"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKUI2AspectRatio *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"requiredAspectRatios","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreBadAspectRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"ignoreBadAspectRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureWithHardwareButtonsEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"captureWithHardwareButtonsEnabled","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2CapturePhotoQualityPrioritization","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)\/title","value":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration~1init(cameraModule:defaultZoomFactor:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:acceptedAngleScore:acceptedSizeScore:autoSnappingSensitivity:autoSnappingDelay:acceptedBrightnessThreshold:autoSnappingEnabled:requiredAspectRatios:ignoreBadAspectRatio:captureWithHardwareButtonsEnabled:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/title","value":"SBSDKUI2CameraPreviewMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/fragments","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AspectRatio\/title","value":"SBSDKUI2AspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AspectRatio\/fragments","op":"replace","value":[{"text":"SBSDKUI2AspectRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AspectRatio\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2AspectRatio","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2CameraModule","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/fragments","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","value":"SBSDKUI2DocumentScannerCameraConfiguration"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}