{"kind":"symbol","abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when no document was detected because of image noise."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textHintTooNoisy","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Defaults to “Background too noisy!\\nSearching for document…”."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthinttoonoisy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthinttoonoisy"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerTextConfiguration"]]},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"textHintTooNoisy","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textHintTooNoisy"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"textHintTooNoisy","kind":"identifier"}],"platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerTextConfiguration(py)textHintTooNoisy"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooNoisy","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerTextConfiguration/textHintTooNoisy":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannertextconfiguration\/texthinttoonoisy","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintTooNoisy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"textHintTooNoisy","kind":"identifier"}],"title":"textHintTooNoisy","deprecated":true,"abstract":[{"text":"The text being displayed on the user-guidance label, when no document was detected because of image noise.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerTextConfiguration\/textHintTooNoisy","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerTextConfiguration":{"title":"SBSDKUIFinderDocumentScannerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannertextconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerTextConfiguration","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of the document scanning screen."}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textHintTooNoisy"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"textHintTooNoisy"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"textHintTooNoisy","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintTooNoisy\/title","value":"textHintTooNoisy"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerTextConfiguration~1textHintTooNoisy\/fragments","op":"replace","value":[{"kind":"identifier","text":"textHintTooNoisy"}]},{"op":"replace","value":"SBSDKUIFinderDocumentScannerTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerTextConfiguration"}]},{"value":[{"text":"SBSDKUIFinderDocumentScannerTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerTextConfiguration\/navigatorTitle","op":"replace"}]}]}