{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/recognizing","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The medical certificate scanner is recognizing a medical certificate."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/recognizing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/recognizing"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateScannerState@SBSDKMedicalCertificateScannerStateRecognizing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"recognizing","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStateRecognizing","kind":"identifier"}],"role":"symbol","title":"SBSDKMedicalCertificateScannerState.recognizing","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"recognizing","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate","title":"SBSDKMedicalCertificateScannerState","abstract":[{"type":"text","text":"The live recognition state of the medical certificate scanner."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerState","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerState/recognizing":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"recognizing","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerstate\/recognizing","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerState\/recognizing","abstract":[{"type":"text","text":"The medical certificate scanner is recognizing a medical certificate."}],"role":"symbol","type":"topic","title":"SBSDKMedicalCertificateScannerState.recognizing","navigatorTitle":[{"text":"SBSDKMedicalCertificateScannerStateRecognizing","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKMedicalCertificateScannerStateRecognizing","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateRecognizing"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerStateRecognizing"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/title","value":"SBSDKMedicalCertificateScannerState","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerState"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState\/fragments"},{"value":"SBSDKMedicalCertificateScannerStateRecognizing","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1recognizing\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerState~1recognizing\/fragments","value":[{"text":"SBSDKMedicalCertificateScannerStateRecognizing","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}