{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/barcodeScannerViewController(_:shouldHighlightResult:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(barcodeScannerViewController:shouldHighlightResult:) "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeScannerViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerViewController"},{"text":", ","kind":"text"},{"text":"shouldHighlightResult","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"code"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","isActive":true},{"type":"text","text":"."}]}],"name":"viewController"},{"name":"code","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The barcode scanner result that may be highlighted or not."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":", if the provided barcode result should be highlighted on the selection overlay. "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"It is optional and only called when the selection overlay is enabled.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/barcodescannerviewcontroller(_:shouldhighlightresult:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/barcodescannerviewcontroller(_:shouldhighlightresult:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate"]]},"metadata":{"required":true,"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodeScannerViewControllerDelegate(im)barcodeScannerViewController:shouldHighlightResult:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController"},{"text":", ","kind":"text"},{"text":"shouldHighlightResult","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"barcodeScannerViewController:shouldHighlightResult:","kind":"identifier"}],"role":"symbol","platforms":[],"symbolKind":"method","title":"barcodeScannerViewController(_:shouldHighlightResult:)"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"sections":[],"abstract":[{"type":"text","text":"Asks the delegate whether to highlight a barcode on the selection overlay or not."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate":{"role":"symbol","deprecated":true,"abstract":[{"text":"Delegate protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate","type":"topic","title":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","title":"SBSDKUIBarcodeScannerViewController","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes.","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate/barcodeScannerViewController(_:shouldHighlightResult:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeScannerViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController","text":"SBSDKUIBarcodeScannerViewController"},{"text":", ","kind":"text"},{"text":"shouldHighlightResult","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"barcodeScannerViewController:shouldHighlightResult:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/barcodescannerviewcontroller(_:shouldhighlightresult:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/barcodeScannerViewController(_:shouldHighlightResult:)","abstract":[{"type":"text","text":"Asks the delegate whether to highlight a barcode on the selection overlay or not."}],"kind":"symbol","required":true,"deprecated":true,"title":"barcodeScannerViewController(_:shouldHighlightResult:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"title":"SBSDKBarcodeItem","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","type":"topic","abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"considered separate barcodes."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeItem","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","navigatorTitle":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"barcodeScannerViewController:shouldHighlightResult:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"barcodeScannerViewController:shouldHighlightResult:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"barcodeScannerViewController:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldHighlightResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"kind":"text","text":" *) "},{"text":"code","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calling "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","isActive":true},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The barcode scanner result that may be highlighted or not."}]}],"name":"code"}],"kind":"parameters"}},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"type":"text","text":", if the provided barcode result should be highlighted on the selection overlay. "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/title","value":"SBSDKUIBarcodeScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","value":"SBSDKUIBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle"},{"value":"barcodeScannerViewController:shouldHighlightResult:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1barcodeScannerViewController(_:shouldHighlightResult:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1barcodeScannerViewController(_:shouldHighlightResult:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScannerViewController:shouldHighlightResult:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]}]}]}