{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScannerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIBarcodeScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"},{"text":" that did dismiss.","type":"text"}],"type":"paragraph"}],"name":"viewController"}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Optional.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Informs the delegate that the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","isActive":true},{"type":"text","text":" has been cancelled and dismissed."}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/barcodescannerviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/barcodescannerviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/barcodeScannerViewControllerDidCancel(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIBarcodeScannerViewControllerDelegate(im)barcodeScannerViewControllerDidCancel:","symbolKind":"method","platforms":[],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScannerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController","text":"SBSDKUIBarcodeScannerViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"barcodeScannerViewControllerDidCancel:","kind":"identifier"}],"role":"symbol","title":"barcodeScannerViewControllerDidCancel(_:)","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"title":"SBSDKUIBarcodeScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","role":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","type":"topic","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate/barcodeScannerViewControllerDidCancel(_:)":{"kind":"symbol","type":"topic","title":"barcodeScannerViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeScannerViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate\/barcodescannerviewcontrollerdidcancel(_:)","abstract":[{"type":"text","text":"Informs the delegate that the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","type":"reference","isActive":true},{"type":"text","text":" has been cancelled and dismissed."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate\/barcodeScannerViewControllerDidCancel(_:)","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"barcodeScannerViewControllerDidCancel:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewControllerDelegate"}],"kind":"symbol","abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"},{"text":".","type":"text"}],"type":"topic","title":"SBSDKUIBarcodeScannerViewControllerDelegate","role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"barcodeScannerViewControllerDidCancel:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"barcodeScannerViewControllerDidCancel:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"barcodeScannerViewControllerDidCancel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController","text":"SBSDKUIBarcodeScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","isActive":true},{"type":"text","text":" that did dismiss."}]}],"name":"viewController"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKUIBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle"},{"value":"barcodeScannerViewControllerDidCancel:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1barcodeScannerViewControllerDidCancel(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"barcodeScannerViewControllerDidCancel:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate~1barcodeScannerViewControllerDidCancel(_:)\/fragments"},{"value":"SBSDKUIBarcodeScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/fragments"},{"value":[{"text":"SBSDKUIBarcodeScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewControllerDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}