{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmoidentitycardfront\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmoidentitycardfront\/id"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMoIdentityCardFront(py)id","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"id","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMoIdentityCardFront"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMoIdentityCardFront\/id"},"sections":[],"abstract":[{"type":"text","text":"Identity Document Number"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMoIdentityCardFront":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmoidentitycardfront","navigatorTitle":[{"text":"SBSDKDocumentsModelMoIdentityCardFront","kind":"identifier"}],"title":"SBSDKDocumentsModelMoIdentityCardFront","kind":"symbol","abstract":[{"type":"text","text":"MoIdentityCardFront"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMoIdentityCardFront","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelMoIdentityCardFront","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMoIdentityCardFront/id":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmoidentitycardfront\/id","navigatorTitle":[{"text":"id","kind":"identifier"}],"title":"id","kind":"symbol","abstract":[{"type":"text","text":"Identity Document Number"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMoIdentityCardFront\/id","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"type":"topic","title":"SBSDKGenericDocumentField","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic document field."}],"navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"id"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"id"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardFront\/title","value":"SBSDKDocumentsModelMoIdentityCardFront"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardFront\/fragments","value":[{"text":"SBSDKDocumentsModelMoIdentityCardFront","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardFront\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelMoIdentityCardFront","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardFront~1id\/title","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMoIdentityCardFront~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]}]}]}