{"sections":[],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"abstract":[{"text":"Creates a new instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","isActive":true},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createNewWithDocument:configuration:andDelegate:) "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier","text":"SBSDKDocument"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerConfiguration","kind":"typeIdentifier","text":"SBSDKUIDocumentScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController","kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewController"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document to which the scanned pages will be added. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" the receiver creates a new document."}]}],"name":"document"},{"content":[{"inlineContent":[{"text":"The configuration to define look and feel of the new scanning view controller.","type":"text"}],"type":"paragraph"}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate of the new scanning view controller."}]}],"name":"delegate"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A new instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController"},{"text":".","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController\/create(document:configuration:delegate:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"createNewWithDocument:configuration:andDelegate:"}],"roleHeading":"Type Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"create(document:configuration:delegate:)","platforms":[],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController(cm)createNewWithDocument:configuration:andDelegate:","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIDocumentScannerConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/create(document:configuration:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/create(document:configuration:delegate:)"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"abstract":[],"kind":"symbol","title":"SBSDKUIDocumentScannerViewController","type":"topic","deprecated":true,"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewControllerDelegate":{"deprecated":true,"abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate","type":"topic","role":"symbol","title":"SBSDKUIDocumentScannerViewControllerDelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocument":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocument","title":"SBSDKDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocument"}],"abstract":[{"type":"text","text":"A thread-safe, mutable container for scanned pages of type "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage","isActive":true},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocument"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController/create(document:configuration:delegate:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerConfiguration","text":"SBSDKUIDocumentScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate","text":"SBSDKUIDocumentScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController","text":"SBSDKUIDocumentScannerViewController"}],"title":"create(document:configuration:delegate:)","abstract":[{"text":"Creates a new instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","isActive":true},{"text":".","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createNewWithDocument:configuration:andDelegate:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/create(document:configuration:delegate:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController\/create(document:configuration:delegate:)","deprecated":true,"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage","abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"type":"topic","title":"SBSDKDocumentPage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerConfiguration":{"title":"SBSDKUIDocumentScannerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerConfiguration","role":"symbol","kind":"symbol","deprecated":true,"abstract":[{"type":"text","text":"This class describes the look and feel, the behavior, as well as the textual contents of the detection screen for documents."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"createNewWithDocument:configuration:andDelegate:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createNewWithDocument:configuration:andDelegate:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController"},{"text":" *) ","kind":"text"},{"text":"createNewWithDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"configuration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIDocumentScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"andDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKUIDocumentScannerViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"document","content":[{"type":"paragraph","inlineContent":[{"text":"The document to which the scanned pages will be added. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" the receiver creates a new document.","type":"text"}]}]},{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to define look and feel of the new scanning view controller.","type":"text"}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate of the new scanning view controller.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController"},{"type":"text","text":"."}]}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"SBSDKUIDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/navigatorTitle","op":"replace"},{"value":"SBSDKUIDocumentScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/fragments","op":"replace"},{"value":[{"text":"SBSDKUIDocumentScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/navigatorTitle","op":"replace"},{"value":"SBSDKDocument","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocument\/title","op":"replace"},{"value":[{"text":"SBSDKDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocument\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocument\/navigatorTitle","op":"replace"},{"value":"createNewWithDocument:configuration:andDelegate:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController~1create(document:configuration:delegate:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createNewWithDocument:configuration:andDelegate:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController~1create(document:configuration:delegate:)\/fragments","op":"replace"},{"value":"SBSDKDocumentPage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/navigatorTitle","op":"replace"},{"value":"SBSDKUIDocumentScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUIDocumentScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerConfiguration\/navigatorTitle","op":"replace"}]}]}