{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quad","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":">","kind":"text"}],"title":"quad","navigatorTitle":[{"text":"quad","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateCheckBox(py)quad"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox\/quad"},"sections":[],"abstract":[{"type":"text","text":"Points of the box."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckbox\/quad"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckbox\/quad"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBox/quad":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox\/quad","title":"quad","type":"topic","abstract":[{"type":"text","text":"Points of the box."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckbox\/quad","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quad","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"quad","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBox":{"navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBox","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}],"abstract":[{"text":"Structure to contain full information about found box.","type":"text"}],"title":"SBSDKMedicalCertificateCheckBox","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckbox"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"quad"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"quad","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"quad","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox~1quad\/title","value":"quad"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox~1quad\/fragments","value":[{"text":"quad","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/title","value":"SBSDKMedicalCertificateCheckBox"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBox"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBox\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateCheckBox","kind":"identifier"}]}]}]}