{"kind":"symbol","abstract":[{"text":"All pages will be in landscape orientation.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation\/landscape"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation\/landscape"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation\/landscape","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscape"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"landscape"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageOrientationLandscape","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation@SBSDKPDFRendererPageOrientationLandscape","roleHeading":"Case","title":"SBSDKPDFRendererPageOrientation.landscape"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageOrientation":{"abstract":[{"text":"An enum describing the orientation of the pages when rendering a PDF document.","type":"text"}],"title":"SBSDKPDFRendererPageOrientation","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageOrientation/landscape":{"role":"symbol","abstract":[{"type":"text","text":"All pages will be in landscape orientation."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"landscape"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientationLandscape"}],"title":"SBSDKPDFRendererPageOrientation.landscape","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation\/landscape","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation\/landscape"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPDFRendererPageOrientationLandscape"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKPDFRendererPageOrientationLandscape","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKPDFRendererPageOrientationLandscape","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKPDFRendererPageOrientation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/navigatorTitle"},{"value":"SBSDKPDFRendererPageOrientationLandscape","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation~1landscape\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientationLandscape"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation~1landscape\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}