{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"portrait","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientationPortrait"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation@SBSDKPDFRendererPageOrientationPortrait","title":"SBSDKPDFRendererPageOrientation.portrait","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"All pages will be in portrait orientation."}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation\/portrait"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation\/portrait"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation\/portrait"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageOrientation/portrait":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"portrait"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation\/portrait","abstract":[{"text":"All pages will be in portrait orientation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientationPortrait"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation\/portrait","type":"topic","title":"SBSDKPDFRendererPageOrientation.portrait","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageOrientation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation","kind":"symbol","title":"SBSDKPDFRendererPageOrientation","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageOrientation","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of the pages when rendering a PDF document."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKPDFRendererPageOrientationPortrait"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKPDFRendererPageOrientationPortrait","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKPDFRendererPageOrientationPortrait","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation~1portrait\/title","value":"SBSDKPDFRendererPageOrientationPortrait"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation~1portrait\/fragments","value":[{"text":"SBSDKPDFRendererPageOrientationPortrait","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/title","value":"SBSDKPDFRendererPageOrientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/fragments","value":[{"text":"SBSDKPDFRendererPageOrientation","kind":"identifier"}],"op":"replace"}]}]}