{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformats\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormats\/hash"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormats(py)hash","modules":[{"name":"ScanbotSDK"}],"title":"hash","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormats"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormats/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormats\/hash","type":"topic","fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformats\/hash","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormats":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormats","kind":"identifier"}],"title":"SBSDKBarcodeFormats","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformats","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormats","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeFormats","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Lists of barcode formats to decode."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormats\/title","value":"SBSDKBarcodeFormats","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormats\/fragments","value":[{"text":"SBSDKBarcodeFormats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormats\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormats","kind":"identifier"}],"op":"replace"}]}]}