{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet\/collapsedvisibleheight"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet\/collapsedvisibleheight"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"collapsedVisibleHeight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collapsedVisibleHeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CollapsedVisibleHeight","text":"SBSDKUI2CollapsedVisibleHeight","kind":"typeIdentifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet(py)collapsedVisibleHeight","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"collapsedVisibleHeight","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collapsedVisibleHeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CollapsedVisibleHeight","text":"SBSDKUI2CollapsedVisibleHeight","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"text":"Default is SMALL","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Height of the collapsed result sheet."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet\/collapsedVisibleHeight","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sheet":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"role":"symbol","title":"SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sheet"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sheet/collapsedVisibleHeight":{"abstract":[{"text":"Height of the collapsed result sheet.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet\/collapsedVisibleHeight","title":"collapsedVisibleHeight","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet\/collapsedvisibleheight","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"collapsedVisibleHeight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CollapsedVisibleHeight","kind":"typeIdentifier","text":"SBSDKUI2CollapsedVisibleHeight"}],"navigatorTitle":[{"kind":"identifier","text":"collapsedVisibleHeight"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CollapsedVisibleHeight":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2collapsedvisibleheight","title":"SBSDKUI2CollapsedVisibleHeight","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}],"abstract":[{"type":"text","text":"Configuration of the barcodes result sheet’s height while collapsed."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"collapsedVisibleHeight","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"collapsedVisibleHeight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CollapsedVisibleHeight","kind":"typeIdentifier","text":"SBSDKUI2CollapsedVisibleHeight"},{"kind":"text","text":" "},{"kind":"identifier","text":"collapsedVisibleHeight"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2Sheet","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/title"},{"value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/navigatorTitle","op":"replace"},{"value":"collapsedVisibleHeight","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet~1collapsedVisibleHeight\/title","op":"replace"},{"value":[{"text":"collapsedVisibleHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet~1collapsedVisibleHeight\/fragments","op":"replace"},{"value":"SBSDKUI2CollapsedVisibleHeight","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/title","op":"replace"},{"value":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}