{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCreditCardScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"setConfiguration(_:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanner(im)setConfiguration:","navigatorTitle":[{"text":"setConfiguration:","kind":"identifier"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/setconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/setconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Sets the configuration of the receiver.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner\/setConfiguration(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","text":"SBSDKCreditCardScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The new configuration."}],"type":"paragraph"}]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanner/setConfiguration(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner\/setConfiguration(_:)","type":"topic","title":"setConfiguration(_:)","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/setconfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfiguration"},{"kind":"text","text":"("},{"text":"SBSDKCreditCardScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setConfiguration:"}],"abstract":[{"type":"text","text":"Sets the configuration of the receiver."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration":{"navigatorTitle":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration for the credit card scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration","title":"SBSDKCreditCardScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanner":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner","abstract":[{"type":"text","text":"A class to scan credit cards on various image sources."}],"navigatorTitle":[{"text":"SBSDKCreditCardScanner","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScanner","kind":"identifier"}],"type":"topic","title":"SBSDKCreditCardScanner","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanner","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setConfiguration:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setConfiguration:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCreditCardScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The new configuration.","type":"text"}]}],"name":"configuration"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner~1setConfiguration(_:)\/title","value":"setConfiguration:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner~1setConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConfiguration:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/title","op":"replace","value":"SBSDKCreditCardScannerConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}]},{"op":"replace","value":"SBSDKCreditCardScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/title"},{"op":"replace","value":[{"text":"SBSDKCreditCardScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/fragments"},{"op":"replace","value":[{"text":"SBSDKCreditCardScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}