{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/intro"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/intro\/done"],"anchor":"Type-Properties","generated":true}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"class","title":"SBSDKUI2DataCaptureAccessibility.intro","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"s:10ScanbotSDK32SBSDKUI2DataCaptureAccessibilityC5introC","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"intro"}],"navigatorTitle":[{"kind":"identifier","text":"intro"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"intro"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/intro"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility","navigatorTitle":[{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}],"title":"SBSDKUI2DataCaptureAccessibility","abstract":[{"type":"text","text":"Accessibility identifiers to be used in UI tests for the data capture scanner RTU-UI V2 (MRZ, credit card, text pattern).."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DataCaptureAccessibility","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/intro/done":{"type":"topic","kind":"symbol","title":"done","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"done","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/intro\/done","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/intro\/done","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DataCaptureAccessibility/intro":{"type":"topic","kind":"symbol","title":"SBSDKUI2DataCaptureAccessibility.intro","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"intro"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2datacaptureaccessibility\/intro","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"intro"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DataCaptureAccessibility\/intro","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/title","value":"SBSDKUI2DataCaptureAccessibility","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DataCaptureAccessibility\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DataCaptureAccessibility"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}