{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSymbol:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"symbol","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"boundingRect:"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"boundingRect","kind":"internalParam"},{"kind":"text","text":" "},{"text":"recognitionConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"recognitionConfidence","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdksymbolbox\/initwithsymbol:boundingrect:recognitionconfidence:"]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox(im)initWithSymbol:boundingRect:recognitionConfidence:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSymbol:boundingRect:recognitionConfidence:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSymbol:boundingRect:recognitionConfidence:","kind":"identifier"}],"title":"initWithSymbol:boundingRect:recognitionConfidence:","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox\/initWithSymbol:boundingRect:recognitionConfidence:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSymbolBox/initWithSymbol:boundingRect:recognitionConfidence:":{"role":"symbol","title":"initWithSymbol:boundingRect:recognitionConfidence:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksymbolbox\/initwithsymbol:boundingrect:recognitionconfidence:","fragments":[{"kind":"text","text":"- "},{"text":"initWithSymbol:boundingRect:recognitionConfidence:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSymbol:boundingRect:recognitionConfidence:"}],"abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox\/initWithSymbol:boundingRect:recognitionConfidence:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSymbolBox":{"abstract":[{"text":"Structure containing recognized symbol text and bounds.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSymbolBox"}],"url":"\/documentation\/scanbotsdk\/sbsdksymbolbox","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKSymbolBox"}],"title":"SBSDKSymbolBox"}},"variantOverrides":[{"patch":[{"value":"SBSDKSymbolBox","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/title"},{"value":[{"kind":"identifier","text":"SBSDKSymbolBox"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/fragments"},{"value":[{"text":"SBSDKSymbolBox","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}