{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMaxiCodeConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"new","kind":"identifier"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatMaxiCodeConfiguration(cm)new","title":"new","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"new"}],"roleHeading":"Type Method","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMaxiCodeConfiguration\/new","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatmaxicodeconfiguration\/new"]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMaxiCodeConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatMaxiCodeConfiguration"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatMaxiCodeConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMaxiCodeConfiguration","title":"SBSDKBarcodeFormatMaxiCodeConfiguration","abstract":[{"text":"MaxiCode configuration. Add to scanner configuration to scan MaxiCode codes.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmaxicodeconfiguration","role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMaxiCodeConfiguration/new":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmaxicodeconfiguration\/new","abstract":[],"title":"new","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMaxiCodeConfiguration\/new","navigatorTitle":[{"kind":"identifier","text":"new"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMaxiCodeConfiguration\/title","value":"SBSDKBarcodeFormatMaxiCodeConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMaxiCodeConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatMaxiCodeConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMaxiCodeConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatMaxiCodeConfiguration"}]}]}]}