{"kind":"symbol","abstract":[{"type":"text","text":"(Form 1) Incapable of work since (arbeitsunfähig seit) date."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/incapableOfWorkSince"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"incapableOfWorkSince"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkSince","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateDateRecordType@SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkSince","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKMedicalCertificateDateRecordType.incapableOfWorkSince","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incapableOfWorkSince","kind":"identifier"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/incapableofworksince"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/incapableofworksince"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType","abstract":[{"type":"text","text":"Type of a date record."}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype","type":"topic","title":"SBSDKMedicalCertificateDateRecordType","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType/incapableOfWorkSince":{"title":"SBSDKMedicalCertificateDateRecordType.incapableOfWorkSince","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incapableOfWorkSince","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"(Form 1) Incapable of work since (arbeitsunfähig seit) date."}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkSince","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/incapableofworksince","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/incapableOfWorkSince"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkSince","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkSince","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkSince","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKMedicalCertificateDateRecordType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/fragments"},{"value":[{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/navigatorTitle"},{"value":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkSince","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1incapableOfWorkSince\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeIncapableOfWorkSince"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1incapableOfWorkSince\/fragments"}]}]}