{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration\/minimum1dquietzonesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration\/minimum1dquietzonesize"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/minimum1DQuietZoneSize"},"metadata":{"title":"minimum1DQuietZoneSize","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration(py)minimum1DQuietZoneSize","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","navigatorTitle":[{"text":"minimum1DQuietZoneSize","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimum1DQuietZoneSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"Minimum quiet zone size on the left and right sides of a 1D barcode, measured in number of modules."},{"type":"text","text":" "},{"type":"text","text":"The quiet zone is only for 1D barcodes with weak start\/stop patterns, i.e. Iata2Of5, Industrial2Of5, Code25,"},{"type":"text","text":" "},{"type":"text","text":"Itf, Codabar, MsiPlessey and Code11."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DQuietZoneSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is 6","type":"text"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatGS1CompositeConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","title":"SBSDKBarcodeFormatGS1CompositeConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"GS1 Composite configuration. Add to scanner configuration to scan GS1 Composite barcodes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatGS1CompositeConfiguration/minimum1DQuietZoneSize":{"role":"symbol","navigatorTitle":[{"text":"minimum1DQuietZoneSize","kind":"identifier"}],"abstract":[{"text":"Minimum quiet zone size on the left and right sides of a 1D barcode, measured in number of modules.","type":"text"},{"text":" ","type":"text"},{"text":"The quiet zone is only for 1D barcodes with weak start\/stop patterns, i.e. Iata2Of5, Industrial2Of5, Code25,","type":"text"},{"text":" ","type":"text"},{"text":"Itf, Codabar, MsiPlessey and Code11.","type":"text"}],"title":"minimum1DQuietZoneSize","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration\/minimum1DQuietZoneSize","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimum1DQuietZoneSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatgs1compositeconfiguration\/minimum1dquietzonesize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"minimum1DQuietZoneSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"minimum1DQuietZoneSize","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DQuietZoneSize"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatGS1CompositeConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration~1minimum1DQuietZoneSize\/title","op":"replace","value":"minimum1DQuietZoneSize"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration~1minimum1DQuietZoneSize\/fragments","op":"replace","value":[{"text":"minimum1DQuietZoneSize","kind":"identifier"}]}]}]}