{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2textwithbadgebuttonmode\/isequal:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"title":"isEqual:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2TextWithBadgeButtonMode(im)isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TextWithBadgeButtonMode\/isEqual:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TextWithBadgeButtonMode"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TextWithBadgeButtonMode":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the ‘preview’ button in ‘text with badge button mode’."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TextWithBadgeButtonMode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}],"title":"SBSDKUI2TextWithBadgeButtonMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2textwithbadgebuttonmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TextWithBadgeButtonMode/isEqual:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2textwithbadgebuttonmode\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TextWithBadgeButtonMode\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TextWithBadgeButtonMode\/title","value":"SBSDKUI2TextWithBadgeButtonMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TextWithBadgeButtonMode\/fragments","value":[{"text":"SBSDKUI2TextWithBadgeButtonMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TextWithBadgeButtonMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TextWithBadgeButtonMode"}]}]}]}