{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BackgroundStyle(im)init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"init()"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2backgroundstyle\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2backgroundstyle\/init()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle\/init()"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BackgroundStyle/init()":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"title":"init()","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle\/init()","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2backgroundstyle\/init()","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BackgroundStyle":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2backgroundstyle","title":"SBSDKUI2BackgroundStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BackgroundStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}],"kind":"symbol","abstract":[{"type":"text","text":"Appearance of the polygon used for buttons and hint backgrounds."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"init","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace"},{"value":"SBSDKUI2BackgroundStyle","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/fragments","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BackgroundStyle\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}