{"metadata":{"role":"collectionGroup","title":"SBSDKTextPatternScannerViewControllerDelegate Implementations","modules":[{"name":"ScanbotSDK"}],"roleHeading":"API Collection"},"kind":"article","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/SBSDKTextPatternScannerViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewController(_:didValidate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewControllerShouldScan(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/sbsdktextpatternscannerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/sbsdktextpatternscannerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller","role":"symbol","deprecated":true,"abstract":[{"text":"A highly customizable camera-based view controller to scan and validate a small rectangular text area in realtime.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}],"title":"SBSDKUITextPatternScannerViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController/textPatternScannerViewController(_:didValidate:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewController(_:didValidate:)","kind":"symbol","type":"topic","title":"textPatternScannerViewController(_:didValidate:)","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/textpatternscannerviewcontroller(_:didvalidate:)","abstract":[{"type":"text","text":"Informs the delegate that text pattern has been scanned and validated and passes the result."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textPatternScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didValidate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"textLineScannerViewController:didValidateResult:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController/textPatternScannerViewControllerShouldScan(_:)":{"abstract":[{"text":"Asks the delegate whether the next video frame should be scanned or not.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textPatternScannerViewControllerShouldScan"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","kind":"typeIdentifier","text":"SBSDKTextPatternScannerViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewControllerShouldScan(_:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/textpatternscannerviewcontrollershouldscan(_:)","type":"topic","navigatorTitle":[{"text":"textPatternScannerViewControllerShouldScan:","kind":"identifier"}],"title":"textPatternScannerViewControllerShouldScan(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewController(_:didValidate:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewControllerShouldScan(_:)"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"SBSDKUITextPatternScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/fragments","value":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController~1textPatternScannerViewController(_:didValidate:)\/title","value":"textLineScannerViewController:didValidateResult:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController~1textPatternScannerViewController(_:didValidate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textLineScannerViewController:didValidateResult:"}],"op":"replace"},{"value":"textPatternScannerViewControllerShouldScan:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController~1textPatternScannerViewControllerShouldScan(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController~1textPatternScannerViewControllerShouldScan(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"textPatternScannerViewControllerShouldScan:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}