{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsManager\/unsubscribe(_:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsManager"]]},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"unsubscribe:","kind":"identifier"}],"title":"unsubscribe(_:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAnalyticsManager(im)unsubscribe:","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticsmanager\/unsubscribe(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticsmanager\/unsubscribe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Unsubscribes a subscriber from receiving analytics events."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKAnalyticsSubscriber"},{"text":")","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsManager/unsubscribe(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKAnalyticsSubscriber","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKAnalyticsSubscriber"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticsmanager\/unsubscribe(_:)","navigatorTitle":[{"kind":"identifier","text":"unsubscribe:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsManager\/unsubscribe(_:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Unsubscribes a subscriber from receiving analytics events."}],"title":"unsubscribe(_:)","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsManager":{"role":"symbol","abstract":[{"type":"codeVoice","code":"SBSDKAnalyticsManager"},{"type":"text","text":" is a singleton class that manages analytics events within the Scanbot SDK."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticsmanager","type":"topic","title":"SBSDKAnalyticsManager","navigatorTitle":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsManager","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAnalyticsSubscriber":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"title":"SBSDKAnalyticsSubscriber","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAnalyticsSubscriber","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkanalyticssubscriber","abstract":[{"type":"text","text":"The subscriber that is being tracked."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unsubscribe:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unsubscribe:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"unsubscribe:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"id<SBSDKAnalyticsSubscriber>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsManager~1unsubscribe(_:)\/title","value":"unsubscribe:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsManager~1unsubscribe(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unsubscribe:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsManager\/title","value":"SBSDKAnalyticsManager"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsManager\/fragments","value":[{"kind":"identifier","text":"SBSDKAnalyticsManager"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsManager\/navigatorTitle","value":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/title","value":"SBSDKAnalyticsSubscriber"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/fragments","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAnalyticsSubscriber\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}