{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"patternContentValidator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pattern","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPatternContentValidator","text":"SBSDKPatternContentValidator","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/patternContentValidator(pattern:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"patternContentValidator"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pattern"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKPatternContentValidator","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPatternContentValidator"}],"roleHeading":"Type Method","title":"patternContentValidator(pattern:)","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"s:10ScanbotSDK21SBSDKContentValidatorC014patternContentD00E0AA012SBSDKPatternfD0CSS_tFZ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/patterncontentvalidator(pattern:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator/patternContentValidator(pattern:)":{"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"patternContentValidator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pattern","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKPatternContentValidator","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPatternContentValidator","kind":"typeIdentifier"}],"role":"symbol","title":"patternContentValidator(pattern:)","url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator\/patterncontentvalidator(pattern:)","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator\/patternContentValidator(pattern:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternContentValidator":{"type":"topic","title":"SBSDKPatternContentValidator","navigatorTitle":[{"kind":"identifier","text":"SBSDKPatternContentValidator"}],"abstract":[{"text":"Pattern content validator.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPatternContentValidator"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator":{"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKContentValidator","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","type":"topic","abstract":[{"type":"text","text":"Base class for content validators."}],"kind":"symbol","title":"SBSDKContentValidator","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKPatternContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/title"},{"op":"replace","value":[{"text":"SBSDKPatternContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/fragments"},{"op":"replace","value":[{"text":"SBSDKPatternContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/navigatorTitle"},{"op":"replace","value":"SBSDKContentValidator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/title"},{"op":"replace","value":[{"text":"SBSDKContentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKContentValidator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}