{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization\/checkUserGuidanceBadPerspective","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/checkuserguidancebadperspective"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/checkuserguidancebadperspective"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The user guidance text displayed when the detected check is not in a good perspective (device tilted)."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkUserGuidanceBadPerspective"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is “Please hold your device straight over the check.”","type":"text"}]}]}],"metadata":{"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkUserGuidanceBadPerspective","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"checkUserGuidanceBadPerspective","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenTextLocalization(py)checkUserGuidanceBadPerspective","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"checkUserGuidanceBadPerspective","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenTextLocalization":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization","role":"symbol","kind":"symbol","title":"SBSDKUI2CheckScannerScreenTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerScreenTextLocalization"}],"abstract":[{"type":"text","text":"Configuration of the all strings for check scanner screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerScreenTextLocalization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenTextLocalization/checkUserGuidanceBadPerspective":{"abstract":[{"type":"text","text":"The user guidance text displayed when the detected check is not in a good perspective (device tilted)."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenTextLocalization\/checkUserGuidanceBadPerspective","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreentextlocalization\/checkuserguidancebadperspective","type":"topic","kind":"symbol","title":"checkUserGuidanceBadPerspective","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkUserGuidanceBadPerspective"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"checkUserGuidanceBadPerspective"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"checkUserGuidanceBadPerspective","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"checkUserGuidanceBadPerspective","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"checkUserGuidanceBadPerspective","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/title","value":"SBSDKUI2CheckScannerScreenTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CheckScannerScreenTextLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization~1checkUserGuidanceBadPerspective\/title","op":"replace","value":"checkUserGuidanceBadPerspective"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenTextLocalization~1checkUserGuidanceBadPerspective\/fragments","op":"replace","value":[{"kind":"identifier","text":"checkUserGuidanceBadPerspective"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}