{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFilter"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFilter"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter@SBSDKUI2BarcodesExtensionFilterNoFilter","title":"SBSDKUI2BarcodesExtensionFilter.noFilter","symbolKind":"case","navigatorTitle":[{"text":"SBSDKUI2BarcodesExtensionFilterNoFilter","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter\/noFilter","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter\/nofilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter\/nofilter"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"EAN and UPC codes are not filtered. Both are returned regardless if they have an extension or not.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodesExtensionFilter":{"title":"SBSDKUI2BarcodesExtensionFilter","navigatorTitle":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodesExtensionFilter/noFilter":{"title":"SBSDKUI2BarcodesExtensionFilter.noFilter","abstract":[{"type":"text","text":"EAN and UPC codes are not filtered. Both are returned regardless if they have an extension or not."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noFilter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodesExtensionFilterNoFilter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter\/nofilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter\/noFilter","kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUI2BarcodesExtensionFilterNoFilter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilterNoFilter"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilterNoFilter"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/title","value":"SBSDKUI2BarcodesExtensionFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter~1noFilter\/title","value":"SBSDKUI2BarcodesExtensionFilterNoFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter~1noFilter\/fragments","value":[{"text":"SBSDKUI2BarcodesExtensionFilterNoFilter","kind":"identifier"}],"op":"replace"}]}]}