{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"SBSDKUI2BarcodesExtensionFilter.onlyWithExtensions","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter@SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onlyWithExtensions","kind":"identifier"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter\/onlywithextensions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter\/onlywithextensions"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter\/onlyWithExtensions"},"abstract":[{"text":"Only EAN and UPC codes with extensions are returned.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"onlyWithExtensions","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodesExtensionFilter/onlyWithExtensions":{"title":"SBSDKUI2BarcodesExtensionFilter.onlyWithExtensions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter\/onlyWithExtensions","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter\/onlywithextensions","abstract":[{"text":"Only EAN and UPC codes with extensions are returned.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlyWithExtensions"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodesExtensionFilter":{"kind":"symbol","title":"SBSDKUI2BarcodesExtensionFilter","role":"symbol","type":"topic","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter~1onlyWithExtensions\/title","value":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter~1onlyWithExtensions\/fragments"},{"value":"SBSDKUI2BarcodesExtensionFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/fragments","value":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}