{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksymbolbox\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox(im)copyWithZone:","role":"symbol","title":"copyWithZone:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox\/copyWithZone:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSymbolBox":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKSymbolBox"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox","url":"\/documentation\/scanbotsdk\/sbsdksymbolbox","navigatorTitle":[{"text":"SBSDKSymbolBox","kind":"identifier"}],"title":"SBSDKSymbolBox","abstract":[{"text":"Structure containing recognized symbol text and bounds.","type":"text"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSymbolBox/copyWithZone:":{"abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox\/copyWithZone:","type":"topic","title":"copyWithZone:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksymbolbox\/copywithzone:","role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKSymbolBox","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKSymbolBox"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/navigatorTitle","value":[{"text":"SBSDKSymbolBox","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}