{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Computes difference between two snapshots. To confirm that a particular operation doesn’t leak, take a snapshot"},{"type":"text","text":" "},{"type":"text","text":"before and after the operation, and check that the diff doesn’t contain any unexpected new ImageRefs."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfiler"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"diffWithFirstSnapshot:secondSnapshot:"}],"title":"diff(firstSnapshot:secondSnapshot:)","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefProfiler(cm)diffWithFirstSnapshot:secondSnapshot:","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diff","kind":"identifier"},{"text":"(","kind":"text"},{"text":"firstSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secondSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","kind":"typeIdentifier"}],"symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"diff"},{"kind":"text","text":"("},{"kind":"externalParam","text":"firstSnapshot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secondSnapshot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshotsDiff","text":"SBSDKImageRefPoolSnapshotsDiff"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"firstSnapshot","content":[{"inlineContent":[{"text":"Snapshot that was taken earlier","type":"text"}],"type":"paragraph"}]},{"name":"secondSnapshot","content":[{"inlineContent":[{"type":"text","text":"Snapshot that was taken later"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Difference between two snapshots"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefProfiler":{"kind":"symbol","title":"SBSDKImageRefProfiler","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofiler","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfiler","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"abstract":[{"type":"text","text":"ImageRef memory profiler."}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefProfiler/diff(firstSnapshot:secondSnapshot:)":{"title":"diff(firstSnapshot:secondSnapshot:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"diff"},{"kind":"text","text":"("},{"kind":"externalParam","text":"firstSnapshot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secondSnapshot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshotsDiff","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","abstract":[{"type":"text","text":"Computes difference between two snapshots. To confirm that a particular operation doesn’t leak, take a snapshot"},{"type":"text","text":" "},{"type":"text","text":"before and after the operation, and check that the diff doesn’t contain any unexpected new ImageRefs."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)","navigatorTitle":[{"kind":"identifier","text":"diffWithFirstSnapshot:secondSnapshot:"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefPoolSnapshot":{"title":"SBSDKImageRefPoolSnapshot","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot","abstract":[{"text":"Snapshot of all alive ImageRefs.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefPoolSnapshotsDiff":{"abstract":[{"text":"difference between two snapshots.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"title":"SBSDKImageRefPoolSnapshotsDiff","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshotsdiff","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshotsDiff","navigatorTitle":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"diffWithFirstSnapshot:secondSnapshot:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshotsDiff","text":"SBSDKImageRefPoolSnapshotsDiff"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"diffWithFirstSnapshot:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"firstSnapshot"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondSnapshot:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"secondSnapshot"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Snapshot that was taken earlier","type":"text"}],"type":"paragraph"}],"name":"firstSnapshot"},{"content":[{"inlineContent":[{"text":"Snapshot that was taken later","type":"text"}],"type":"paragraph"}],"name":"secondSnapshot"}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"Difference between two snapshots","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler\/title","value":"SBSDKImageRefProfiler","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/title","op":"replace","value":"diffWithFirstSnapshot:secondSnapshot:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/title","op":"replace","value":"SBSDKImageRefPoolSnapshot"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/title","op":"replace","value":"SBSDKImageRefPoolSnapshotsDiff"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/fragments","op":"replace","value":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}]}]}]}