{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"recognizerParameters","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","platforms":[],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:recognizerParameters:delegate:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardScannerViewController(im)initWithParentViewController:parentView:recognizerParameters:delegate:","title":"init(parentViewController:parentView:recognizerParameters:delegate:)","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewController"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controller’s view using its entire bounds area.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewController\/init(parentViewController:parentView:recognizerParameters:delegate:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithParentViewController:parentView:recognizerParameters:delegate:) "},{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"recognizerParameters","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardScannerViewControllerDelegate","text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"parentViewController","content":[{"inlineContent":[{"type":"text","text":"The view controller the newly created instance is embedded into."}],"type":"paragraph"}]},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view the newly created instance is embedded into."}]}]},{"name":"recognizerParameters","content":[{"inlineContent":[{"type":"text","text":"The live detection configuration parameters."}],"type":"paragraph"}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate of the receiver."}]}]}],"kind":"parameters"}],"deprecationSummary":[{"inlineContent":[{"text":"Please consider using SBSDKGenericDocumentRecognizerViewController.","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontroller\/init(parentviewcontroller:parentview:recognizerparameters:delegate:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontroller\/init(parentviewcontroller:parentview:recognizerparameters:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardScannerViewController/init(parentViewController:parentView:recognizerParameters:delegate:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"recognizerParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerParameters"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardScannerViewControllerDelegate"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:recognizerParameters:delegate:"}],"title":"init(parentViewController:parentView:recognizerParameters:delegate:)","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontroller\/init(parentviewcontroller:parentview:recognizerparameters:delegate:)","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewController\/init(parentViewController:parentView:recognizerParameters:delegate:)","abstract":[{"type":"text","text":"Installs the receiver as child view controller onto the parent view controller’s view using its entire bounds area."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","title":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters","type":"topic","abstract":[{"text":"The health insurance card recognizer configuration.","type":"text"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardScannerViewController":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to scan health insurance cards with the camera."}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewController","title":"SBSDKHealthInsuranceCardScannerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardScannerViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardScannerViewController","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardScannerViewControllerDelegate":{"title":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardscannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewControllerDelegate","abstract":[{"text":"The delegation protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardScannerViewController","type":"reference","isActive":true},{"type":"text","text":" class."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithParentViewController:parentView:recognizerParameters:delegate:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:recognizerParameters:delegate:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParentViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"parentViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"parentView:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":" *) "},{"text":"parentView","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognizerParameters:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerParameters","text":"SBSDKHealthInsuranceCardRecognizerParameters"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"recognizerParameters"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardScannerViewControllerDelegate","text":"id<SBSDKHealthInsuranceCardScannerViewControllerDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithParentViewController:parentView:recognizerParameters:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewController~1init(parentViewController:parentView:recognizerParameters:delegate:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithParentViewController:parentView:recognizerParameters:delegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewController~1init(parentViewController:parentView:recognizerParameters:delegate:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title","value":"SBSDKHealthInsuranceCardRecognizerParameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewController\/title","value":"SBSDKHealthInsuranceCardScannerViewController"},{"op":"replace","value":[{"text":"SBSDKHealthInsuranceCardScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewController\/fragments"},{"value":"SBSDKHealthInsuranceCardScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewControllerDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardScannerViewControllerDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}