{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem\/initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithText:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawBytes:"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"rawBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rawBytesEncodings:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKRangeEncoding *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"rawBytesEncodings","kind":"internalParam"},{"kind":"text","text":" "},{"text":"structuredAppendInfo:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKStructuredAppendInfo","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStructuredAppendInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"structuredAppendInfo"},{"kind":"text","text":" "},{"text":"format:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormat","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"format"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quad:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quad"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quadNormalized:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"quadNormalized"},{"text":" ","kind":"text"},{"text":"extendedQuad:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"extendedQuad"},{"kind":"text","text":" "},{"text":"extendedQuadNormalized:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSValue *>"},{"kind":"text","text":" *) "},{"text":"extendedQuadNormalized","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isUpsideDown:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isUpsideDown","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceImage:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"},{"text":" *) ","kind":"text"},{"text":"sourceImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"upcEanExtension:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"upcEanExtension"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isGS1Message:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isGS1Message"},{"kind":"text","text":" "},{"kind":"identifier","text":"isGS1CompositePart:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isGS1CompositePart","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataBarStackSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"dataBarStackSize","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeScore:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"sizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extractedDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"extractedDocument"},{"text":" ","kind":"text"},{"text":"globalIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"globalIndex","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeItem(im)initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","role":"symbol","title":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","navigatorTitle":[{"text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeitem\/initwithtext:rawbytes:rawbytesencodings:structuredappendinfo:format:quad:quadnormalized:extendedquad:extendedquadnormalized:isupsidedown:sourceimage:upceanextension:isgs1message:isgs1compositepart:databarstacksize:sizescore:extracteddocumen-7jnoz"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRef":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageref","title":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageRef"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}],"abstract":[{"type":"text","text":"Image ref class."}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeItem":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeItem"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"considered separate barcodes."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeitem","title":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStructuredAppendInfo":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo","abstract":[{"type":"text","text":"The structured append mode can be used to split a message across multiple barcodes."}],"kind":"symbol","title":"SBSDKStructuredAppendInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstructuredappendinfo","navigatorTitle":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeItem/initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeitem\/initwithtext:rawbytes:rawbytesencodings:structuredappendinfo:format:quad:quadnormalized:extendedquad:extendedquadnormalized:isupsidedown:sourceimage:upceanextension:isgs1message:isgs1compositepart:databarstacksize:sizescore:extracteddocumen-7jnoz","kind":"symbol","title":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","navigatorTitle":[{"kind":"identifier","text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeItem\/initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormat":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormat","title":"SBSDKBarcodeFormat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformat","abstract":[{"text":"Enumerates barcode formats.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocument":{"abstract":[{"text":"Generic document.","type":"text"}],"title":"SBSDKGenericDocument","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocument"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKImageRef","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRef\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRef\/fragments","op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRef\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}]},{"value":"SBSDKBarcodeItem","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/title","value":"SBSDKStructuredAppendInfo","op":"replace"},{"value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/fragments"},{"value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormat\/title","value":"SBSDKBarcodeFormat"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}]},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/title"},{"op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}