{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewscreenconfiguration\/init(enabled:topbartitle:topbarmorebutton:topbarbackbutton:morepopup:zoombutton:zoomoverlay:backgroundcolor:bottombar:switchnextpagebutton:switchpreviouspagebutton:pagecounter:deleteallpagesalertdialog:deletepagealertdialog:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewscreenconfiguration\/init(enabled:topbartitle:topbarmorebutton:topbarbackbutton:morepopup:zoombutton:zoomoverlay:backgroundcolor:bottombar:switchnextpagebutton:switchpreviouspagebutton:pagecounter:deleteallpagesalertdialog:deletepagealertdialog:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewScreenConfiguration\/init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" = SBSDKUI2StyledText(text: \"?reviewScreenTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)), ","kind":"text"},{"text":"topBarMoreButton","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton"},{"kind":"text","text":" = SBSDKUI2IconButton(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\", isArgb: false),\n                                       accessibilityDescription: \"?accessibilityDescriptionReviewMoreButton\"), "},{"kind":"externalParam","text":"topBarBackButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?reviewTopBarBackButtonTitle\",\n                                                                                            accessibilityDescription: \"?accessibilityDescriptionReviewTopBarBackButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 0.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)), "},{"kind":"externalParam","text":"morePopup"},{"kind":"text","text":": "},{"text":"SBSDKUI2ReviewMorePopupMenu","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewMorePopupMenu","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu","kind":"typeIdentifier"},{"text":" = SBSDKUI2ReviewMorePopupMenu(), ","kind":"text"},{"text":"zoomButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2RoundButton"},{"text":" = SBSDKUI2RoundButton(accessibilityDescription: \"?accessibilityDescriptionReviewZoomButton\",\n                                        backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                       isArgb: false),\n                                        foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                       isArgb: false)), ","kind":"text"},{"kind":"externalParam","text":"zoomOverlay"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ZoomOverlay","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ZoomOverlay","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ZoomOverlay","kind":"typeIdentifier"},{"text":" = SBSDKUI2ZoomOverlay(), ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\", isArgb: false), "},{"kind":"externalParam","text":"bottomBar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ReviewBottomBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration"},{"kind":"text","text":" = SBSDKUI2ReviewBottomBarConfiguration(), "},{"kind":"externalParam","text":"switchNextPageButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2IconButton(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\", isArgb: false),\n                                       accessibilityDescription: \"?accessibilityDescriptionReviewNextPageButton\"), "},{"text":"switchPreviousPageButton","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton"},{"kind":"text","text":" = SBSDKUI2IconButton(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\", isArgb: false),\n                                       accessibilityDescription: \"?accessibilityDescriptionReviewPreviousPageButton\"), "},{"text":"pageCounter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"text":" = SBSDKUI2UserGuidanceConfiguration(title: SBSDKUI2StyledText(text: \"?reviewScreenPageCount\",\n                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                     isArgb: false)),\n                                                      background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                   isArgb: false),\n                                                                                          strokeWidth: 0.0)), ","kind":"text"},{"text":"deleteAllPagesAlertDialog","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" = SBSDKUI2ScanbotAlertDialog(title: SBSDKUI2StyledText(text: \"?reviewDeleteAllPagesAlertTitle\",\n                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                              isArgb: false)),\n                                               subtitle: SBSDKUI2StyledText(text: \"?reviewDeleteAllPagesAlertSubtitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                 isArgb: false)),\n                                               okButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeleteAllPagesAlertDeleteButtonTitle\",\n                                                                                     accessibilityDescription: \"?accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 0.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                              isArgb: false))),\n                                               actionButton: SBSDKUI2ButtonConfiguration(visible: false),\n                                               cancelButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeleteAllPagesAlertCancelButtonTitle\",\n                                                                                         accessibilityDescription: \"?accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton\",\n                                                                                         background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                             strokeWidth: 0.0),\n                                                                                         foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false)))), ","kind":"text"},{"kind":"externalParam","text":"deletePageAlertDialog"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog"},{"text":" = SBSDKUI2ScanbotAlertDialog(title: SBSDKUI2StyledText(text: \"?reviewDeletePageAlertTitle\",\n                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                              isArgb: false)),\n                                               subtitle: SBSDKUI2StyledText(text: \"?reviewDeletePageAlertSubTitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                 isArgb: false)),\n                                               okButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeletePageAlertConfirmButtonTitle\",\n                                                                                     accessibilityDescription: \"?accessibilityDescriptionReviewDeletePageAlertConfirmButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 0.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                              isArgb: false))),\n                                               actionButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeletePageAlertDeleteRetakeButtonTitle\",\n                                                                                         accessibilityDescription: \"?accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton\",\n                                                                                         background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                             strokeWidth: 0.0),\n                                                                                         foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false))),\n                                               cancelButton: SBSDKUI2ButtonConfiguration(text: \"?reviewDeletePageAlertCancelButtonTitle\",\n                                                                                         accessibilityDescription: \"?accessibilityDescriptionReviewDeletePageAlertCancelButton\",\n                                                                                         background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                             strokeWidth: 0.0),\n                                                                                         foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false)))))","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewScreenConfiguration"]]},"sections":[],"metadata":{"role":"symbol","title":"init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)","roleHeading":"Initializer","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewScreenConfiguration(im)initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","navigatorTitle":[{"kind":"identifier","text":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"topBarTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBarMoreButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"topBarBackButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"text":"morePopup","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu","kind":"typeIdentifier","text":"SBSDKUI2ReviewMorePopupMenu"},{"text":", ","kind":"text"},{"text":"zoomButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"zoomOverlay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2ZoomOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ZoomOverlay"},{"text":", ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"bottomBar","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ReviewBottomBarConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"switchNextPageButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"switchPreviousPageButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton"},{"text":", ","kind":"text"},{"text":"pageCounter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deleteAllPagesAlertDialog"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":", ","kind":"text"},{"text":"deletePageAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":")"}],"symbolKind":"init"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanbotAlertDialog":{"abstract":[{"type":"text","text":"Configuration of the the standard alert dialog."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"title":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanbotalertdialog"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ZoomOverlay":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the zoom overlay for the review screen."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ZoomOverlay","title":"SBSDKUI2ZoomOverlay","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2zoomoverlay","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ZoomOverlay"}],"navigatorTitle":[{"text":"SBSDKUI2ZoomOverlay","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ButtonConfiguration":{"abstract":[{"type":"text","text":"Button configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"title":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2buttonconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"role":"symbol","title":"SBSDKUI2StyledText","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the bottom bar for the review screen."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration","title":"SBSDKUI2ReviewBottomBarConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewScreenConfiguration/init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewScreenConfiguration\/init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)","navigatorTitle":[{"text":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarMoreButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarBackButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"morePopup"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu","kind":"typeIdentifier","text":"SBSDKUI2ReviewMorePopupMenu"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"zoomButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2RoundButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2RoundButton","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"zoomOverlay"},{"kind":"text","text":": "},{"text":"SBSDKUI2ZoomOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ZoomOverlay"},{"kind":"text","text":", "},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomBar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration","text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"switchNextPageButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"switchPreviousPageButton","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2IconButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageCounter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deleteAllPagesAlertDialog"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deletePageAlertDialog"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewscreenconfiguration\/init(enabled:topbartitle:topbarmorebutton:topbarbackbutton:morepopup:zoombutton:zoomoverlay:backgroundcolor:bottombar:switchnextpagebutton:switchpreviouspagebutton:pagecounter:deleteallpagesalertdialog:deletepagealertdialog:)","abstract":[],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2RoundButton":{"abstract":[{"type":"text","text":"Configuration of the round button."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"title":"SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2RoundButton","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2roundbutton","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration","title":"SBSDKUI2UserGuidanceConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidanceconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewMorePopupMenu":{"type":"topic","title":"SBSDKUI2ReviewMorePopupMenu","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewMorePopupMenu","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewmorepopupmenu","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReviewMorePopupMenu","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ReviewMorePopupMenu"}],"abstract":[{"text":"Configuration of the ‘more’ popup menu for the review screen.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Color"}],"title":"SBSDKUI2Color","type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IconButton":{"navigatorTitle":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","type":"topic","title":"SBSDKUI2IconButton","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2iconbutton","abstract":[{"type":"text","text":"Configuration of the icon appearance."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2IconButton","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewScreenConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the screen for reviewing the scanned pages."}],"type":"topic","title":"SBSDKUI2ReviewScreenConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewscreenconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ReviewScreenConfiguration"}],"navigatorTitle":[{"text":"SBSDKUI2ReviewScreenConfiguration","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithEnabled:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"enabled"},{"text":" ","kind":"text"},{"text":"topBarTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarMoreButton:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"topBarMoreButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"topBarBackButton:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"topBarBackButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"morePopup:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewMorePopupMenu","kind":"typeIdentifier","text":"SBSDKUI2ReviewMorePopupMenu","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewMorePopupMenu"},{"kind":"text","text":" *) "},{"text":"morePopup","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"zoomButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2RoundButton","text":"SBSDKUI2RoundButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2RoundButton","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zoomButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"zoomOverlay:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ZoomOverlay","kind":"typeIdentifier","text":"SBSDKUI2ZoomOverlay","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ZoomOverlay"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zoomOverlay"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"backgroundColor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"bottomBar:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2ReviewBottomBarConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bottomBar","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"switchNextPageButton:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"switchNextPageButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchPreviousPageButton:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconButton","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"switchPreviousPageButton"},{"kind":"text","text":" "},{"text":"pageCounter:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"},{"text":" *) ","kind":"text"},{"text":"pageCounter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"deleteAllPagesAlertDialog:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deleteAllPagesAlertDialog"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletePageAlertDialog:"},{"kind":"text","text":"("},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog"},{"text":" *) ","kind":"text"},{"text":"deletePageAlertDialog","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog\/title","op":"replace","value":"SBSDKUI2ScanbotAlertDialog"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ZoomOverlay\/title","value":"SBSDKUI2ZoomOverlay","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ZoomOverlay\/fragments","value":[{"text":"SBSDKUI2ZoomOverlay","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments","op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"value":"SBSDKUI2ReviewBottomBarConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/title"},{"value":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration~1init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)\/title","value":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration~1init(enabled:topBarTitle:topBarMoreButton:topBarBackButton:morePopup:zoomButton:zoomOverlay:backgroundColor:bottomBar:switchNextPageButton:switchPreviousPageButton:pageCounter:deleteAllPagesAlertDialog:deletePageAlertDialog:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2RoundButton\/title","value":"SBSDKUI2RoundButton"},{"value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2RoundButton\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/title","op":"replace","value":"SBSDKUI2UserGuidanceConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewMorePopupMenu\/title","value":"SBSDKUI2ReviewMorePopupMenu","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ReviewMorePopupMenu"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewMorePopupMenu\/fragments"},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments"},{"value":"SBSDKUI2IconButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconButton\/fragments","value":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration\/title","value":"SBSDKUI2ReviewScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2ReviewScreenConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}