{"abstract":[{"type":"text","text":"The title of the confirmation dialog retry button."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration\/confirmationDialogRetryButtonTitle","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerTextConfiguration(py)confirmationDialogRetryButtonTitle","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationDialogRetryButtonTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"confirmationDialogRetryButtonTitle"}],"title":"confirmationDialogRetryButtonTitle","symbolKind":"property","platforms":[]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration\/confirmationdialogretrybuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration\/confirmationdialogretrybuttontitle"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"confirmationDialogRetryButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerTextConfiguration":{"kind":"symbol","title":"SBSDKUIBarcodeScannerTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI barcode scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerTextConfiguration/confirmationDialogRetryButtonTitle":{"deprecated":true,"abstract":[{"type":"text","text":"The title of the confirmation dialog retry button."}],"title":"confirmationDialogRetryButtonTitle","navigatorTitle":[{"kind":"identifier","text":"confirmationDialogRetryButtonTitle"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration\/confirmationdialogretrybuttontitle","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration\/confirmationDialogRetryButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmationDialogRetryButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"confirmationDialogRetryButtonTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"confirmationDialogRetryButtonTitle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"confirmationDialogRetryButtonTitle","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/title","value":"SBSDKUIBarcodeScannerTextConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerTextConfiguration"}],"op":"replace"},{"value":"confirmationDialogRetryButtonTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration~1confirmationDialogRetryButtonTitle\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration~1confirmationDialogRetryButtonTitle\/fragments","value":[{"text":"confirmationDialogRetryButtonTitle","kind":"identifier"}]}]}]}