{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"]}],"metadata":{"navigatorTitle":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentAnimationConfiguration","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"title":"SBSDKDocumentAnimationConfiguration","roleHeading":"Class","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration"},"abstract":[{"type":"text","text":"A class to configure the document animation properties."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/appearanceDuration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/disappearanceDuration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/displayDuration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/finalFrame","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/imageContentMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/overlayColor"],"generated":true}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/disappearanceDuration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"disappearanceDuration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/disappearanceduration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/disappearanceDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"disappearanceDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The amount of time the document takes to disappear or animate to the final frame."}],"title":"disappearanceDuration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)":{"navigatorTitle":[{"text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","kind":"identifier"}],"type":"topic","title":"init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appearanceDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"displayDuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"disappearanceDuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"overlayColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageContentMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ContentMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewContentMode"},{"text":", ","kind":"text"},{"text":"finalFrame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/init(appearanceduration:displayduration:disappearanceduration:overlaycolor:imagecontentmode:finalframe:)","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/overlayColor":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"overlayColor"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/overlaycolor","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/overlayColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"overlayColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The color used to overlay the camera screen during the animation."}],"title":"overlayColor","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/imageContentMode":{"type":"topic","abstract":[{"text":"The content mode for the document’s image view being animated.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/imageContentMode","navigatorTitle":[{"text":"imageContentMode","kind":"identifier"}],"role":"symbol","title":"imageContentMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/imagecontentmode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageContentMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIViewContentMode","text":"ContentMode","kind":"typeIdentifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration","title":"SBSDKDocumentAnimationConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}],"abstract":[{"text":"A class to configure the document animation properties.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/init()":{"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/init()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"abstract":[],"title":"init()","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/displayDuration":{"navigatorTitle":[{"kind":"identifier","text":"displayDuration"}],"type":"topic","title":"displayDuration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/displayDuration","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The display time for the document, before it animates to the provided valid final frame or disappear otherwise."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/displayduration","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/appearanceDuration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"appearanceDuration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/appearanceduration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/appearanceDuration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appearanceDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"abstract":[{"type":"text","text":"The amount of time the document takes to appear."}],"title":"appearanceDuration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentAnimationConfiguration/finalFrame":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"finalFrame"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentanimationconfiguration\/finalframe","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/finalFrame","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finalFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The final frame where the animated document should animate to."}],"title":"finalFrame","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentAnimationConfiguration"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/appearanceDuration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/disappearanceDuration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/displayDuration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/finalFrame","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/imageContentMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/overlayColor"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentAnimationConfiguration\/init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1disappearanceDuration\/title","value":"disappearanceDuration","op":"replace"},{"value":[{"text":"disappearanceDuration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1disappearanceDuration\/fragments","op":"replace"},{"value":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAppearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1init(appearanceDuration:displayDuration:disappearanceDuration:overlayColor:imageContentMode:finalFrame:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1overlayColor\/title","value":"overlayColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1overlayColor\/fragments","value":[{"text":"overlayColor","kind":"identifier"}],"op":"replace"},{"value":"imageContentMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1imageContentMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1imageContentMode\/fragments","value":[{"kind":"identifier","text":"imageContentMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration\/title","value":"SBSDKDocumentAnimationConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentAnimationConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration\/navigatorTitle","value":[{"text":"SBSDKDocumentAnimationConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1init()\/title","value":"init"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1init()\/fragments"},{"value":"displayDuration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1displayDuration\/title"},{"value":[{"text":"displayDuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1displayDuration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1appearanceDuration\/title","op":"replace","value":"appearanceDuration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1appearanceDuration\/fragments","value":[{"kind":"identifier","text":"appearanceDuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1finalFrame\/title","op":"replace","value":"finalFrame"},{"value":[{"kind":"identifier","text":"finalFrame"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentAnimationConfiguration~1finalFrame\/fragments"}]}]}