{"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init(from:)"],"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingDetectButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingResetButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingRotateButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingTopBarCancelButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingTopBarConfirmButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/cameraProgressOverlayTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingDetectButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingResetButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingRotateButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingScreenTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingTopBarCancelButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingTopBarConfirmButtonTitle"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/toJson()"],"title":"Instance Methods"}],"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"class","roleHeading":"Class","title":"SBSDKUI2CroppingTextLocalization","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingTextLocalization","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2CroppingTextLocalization) ","kind":"text"},{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/accessibilityDescriptionCroppingTopBarCancelButton":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingtopbarcancelbutton","kind":"symbol","title":"accessibilityDescriptionCroppingTopBarCancelButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The accessibility hint for the ‘cancel’ button, located in the top bar of the cropping screen."},{"type":"text","text":" "},{"type":"text","text":"Default is “Tap to close screen without applying changes”"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingTopBarCancelButton","navigatorTitle":[{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/init(from:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/init(from:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init(from:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(from:)","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/accessibilityDescriptionCroppingDetectButton":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingdetectbutton","kind":"symbol","title":"accessibilityDescriptionCroppingDetectButton","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCroppingDetectButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[{"text":"The accessibility hint for the ‘detect document’ button, located in the bottom bar of the cropping screen.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Tap to detect document on the image”","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingDetectButton","navigatorTitle":[{"text":"accessibilityDescriptionCroppingDetectButton","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/isEqual:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/isequal:","kind":"symbol","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/croppingRotateButtonTitle":{"abstract":[{"text":"The ‘rotate page’ button title, located in the bottom bar of the cropping screen.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “Rotate”"}],"navigatorTitle":[{"text":"croppingRotateButtonTitle","kind":"identifier"}],"type":"topic","title":"croppingRotateButtonTitle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingRotateButtonTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"croppingRotateButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/croppingrotatebuttontitle"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/cameraProgressOverlayTitle":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/cameraprogressoverlaytitle","abstract":[{"type":"text","text":"The cropping progress overlay title."},{"text":" ","type":"text"},{"type":"text","text":"Default is “Please wait…”"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/cameraProgressOverlayTitle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraProgressOverlayTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"cameraProgressOverlayTitle"}],"title":"cameraProgressOverlayTitle","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/croppingDetectButtonTitle":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/croppingdetectbuttontitle","kind":"symbol","title":"croppingDetectButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"croppingDetectButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The ‘detect document’ button title, located in the bottom bar of the cropping screen."},{"type":"text","text":" "},{"type":"text","text":"Default is “Detect”"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingDetectButtonTitle","navigatorTitle":[{"text":"croppingDetectButtonTitle","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/croppingTopBarConfirmButtonTitle":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/croppingtopbarconfirmbuttontitle","abstract":[{"type":"text","text":"The ‘confirm’ button title, located in the top bar of the cropping screen."},{"type":"text","text":" "},{"type":"text","text":"Default is “Done”"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingTopBarConfirmButtonTitle","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"croppingTopBarConfirmButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"croppingTopBarConfirmButtonTitle","kind":"identifier"}],"title":"croppingTopBarConfirmButtonTitle","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/accessibilityDescriptionCroppingTopBarConfirmButton":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingtopbarconfirmbutton","kind":"symbol","title":"accessibilityDescriptionCroppingTopBarConfirmButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarConfirmButton"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The accessibility hint for the ‘confirm’ button, located in the top bar of the cropping screen."},{"text":" ","type":"text"},{"text":"Default is “Tap to apply changes”","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingTopBarConfirmButton","navigatorTitle":[{"text":"accessibilityDescriptionCroppingTopBarConfirmButton","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/fromJsonWithJson:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/fromjsonwithjson:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/fromJsonWithJson:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/toJson()":{"kind":"symbol","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/tojson()","title":"toJson()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/toJson()","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/accessibilityDescriptionCroppingRotateButton":{"abstract":[{"text":"The accessibility hint for the ‘rotate page’ button, located in the bottom bar of the cropping screen.","type":"text"},{"type":"text","text":" "},{"text":"Default is “Tap to rotate document”","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingrotatebutton","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","title":"accessibilityDescriptionCroppingRotateButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingRotateButton","type":"topic","navigatorTitle":[{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/init(cameraprogressoverlaytitle:croppingtopbarcancelbuttontitle:croppingtopbarconfirmbuttontitle:croppingdetectbuttontitle:croppingrotatebuttontitle:croppingresetbuttontitle:croppingscreentitle:accessibilitydescriptioncroppingtopbarconfirmb-23die","title":"init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraProgressOverlayTitle"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"croppingTopBarCancelButtonTitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"croppingTopBarConfirmButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"croppingDetectButtonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"croppingRotateButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"croppingResetButtonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"croppingScreenTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"accessibilityDescriptionCroppingTopBarConfirmButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionCroppingDetectButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"accessibilityDescriptionCroppingRotateButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"accessibilityDescriptionCroppingResetButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)","navigatorTitle":[{"kind":"identifier","text":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/accessibilityDescriptionCroppingResetButton":{"abstract":[{"type":"text","text":"The accessibility hint for the ‘reset detection’ button, located in the bottom bar of the cropping screen."},{"type":"text","text":" "},{"text":"Default is “Tap to reset document contour to whole image”","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/accessibilitydescriptioncroppingresetbutton","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityDescriptionCroppingResetButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","title":"accessibilityDescriptionCroppingResetButton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingResetButton","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCroppingResetButton"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization","kind":"symbol","title":"SBSDKUI2CroppingTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of all the strings for the standalone cropping screen."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/croppingTopBarCancelButtonTitle":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"croppingTopBarCancelButtonTitle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingTopBarCancelButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"croppingTopBarCancelButtonTitle"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/croppingtopbarcancelbuttontitle","type":"topic","abstract":[{"type":"text","text":"The ‘cancel’ button title, located in the top bar of the cropping screen."},{"type":"text","text":" "},{"type":"text","text":"Default is “Cancel”"}],"title":"croppingTopBarCancelButtonTitle"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/hash":{"title":"hash","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/hash","fragments":[{"text":"hash","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Node":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2node","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Node","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"title":"SBSDKUI2Node","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/init()":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/init()","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/croppingScreenTitle":{"abstract":[{"type":"text","text":"The cropping screen title, located in the top bar."},{"type":"text","text":" "},{"type":"text","text":"Default is “Crop”"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/croppingscreentitle","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"croppingScreenTitle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"croppingScreenTitle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingScreenTitle","type":"topic","navigatorTitle":[{"kind":"identifier","text":"croppingScreenTitle"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingTextLocalization/croppingResetButtonTitle":{"abstract":[{"type":"text","text":"The ‘reset detection’ button title, located in the bottom bar of the cropping screen."},{"text":" ","type":"text"},{"type":"text","text":"Default is “Reset”"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingtextlocalization\/croppingresetbuttontitle","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"croppingResetButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","title":"croppingResetButtonTitle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingResetButtonTitle","type":"topic","navigatorTitle":[{"text":"croppingResetButtonTitle","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SBSDKUI2CroppingTextLocalization","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingDetectButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingResetButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingRotateButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingTopBarCancelButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/accessibilityDescriptionCroppingTopBarConfirmButton","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/cameraProgressOverlayTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingDetectButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingResetButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingRotateButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingScreenTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingTopBarCancelButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/croppingTopBarConfirmButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/hash"]},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/toJson()"],"generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingTextLocalization\/fromJsonWithJson:"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Node","kind":"typeIdentifier","text":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"accessibilityDescriptionCroppingTopBarCancelButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingTopBarCancelButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingTopBarCancelButton\/fragments","value":[{"text":"accessibilityDescriptionCroppingTopBarCancelButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingDetectButton\/title","value":"accessibilityDescriptionCroppingDetectButton","op":"replace"},{"value":[{"text":"accessibilityDescriptionCroppingDetectButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingDetectButton\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingRotateButtonTitle\/title","value":"croppingRotateButtonTitle","op":"replace"},{"op":"replace","value":[{"text":"croppingRotateButtonTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingRotateButtonTitle\/fragments"},{"op":"replace","value":"cameraProgressOverlayTitle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1cameraProgressOverlayTitle\/title"},{"op":"replace","value":[{"text":"cameraProgressOverlayTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1cameraProgressOverlayTitle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingDetectButtonTitle\/title","value":"croppingDetectButtonTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingDetectButtonTitle\/fragments","op":"replace","value":[{"text":"croppingDetectButtonTitle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingTopBarConfirmButtonTitle\/title","value":"croppingTopBarConfirmButtonTitle"},{"op":"replace","value":[{"text":"croppingTopBarConfirmButtonTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingTopBarConfirmButtonTitle\/fragments"},{"value":"accessibilityDescriptionCroppingTopBarConfirmButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingTopBarConfirmButton\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarConfirmButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingTopBarConfirmButton\/fragments"},{"value":"toJson","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1toJson()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1toJson()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingRotateButton\/title","value":"accessibilityDescriptionCroppingRotateButton","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingRotateButton\/fragments","value":[{"text":"accessibilityDescriptionCroppingRotateButton","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)\/title","value":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1init(cameraProgressOverlayTitle:croppingTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:)\/fragments"},{"value":"accessibilityDescriptionCroppingResetButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingResetButton\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1accessibilityDescriptionCroppingResetButton\/fragments","value":[{"text":"accessibilityDescriptionCroppingResetButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/title","op":"replace","value":"SBSDKUI2CroppingTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/fragments","value":[{"text":"SBSDKUI2CroppingTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CroppingTextLocalization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingTopBarCancelButtonTitle\/title","value":"croppingTopBarCancelButtonTitle"},{"op":"replace","value":[{"text":"croppingTopBarCancelButtonTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingTopBarCancelButtonTitle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/fragments"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/navigatorTitle"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingScreenTitle\/title","value":"croppingScreenTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingScreenTitle\/fragments","value":[{"kind":"identifier","text":"croppingScreenTitle"}]},{"op":"replace","value":"croppingResetButtonTitle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingResetButtonTitle\/title"},{"value":[{"kind":"identifier","text":"croppingResetButtonTitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingTextLocalization~1croppingResetButtonTitle\/fragments"}]}]}