{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2DocumentScannerOutputSettings) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]}]}],"metadata":{"title":"SBSDKUI2DocumentScannerOutputSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings","symbolKind":"class","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}]},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(from:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/defaultFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/pagesScanLimit"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/toJson()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings"},"sections":[],"abstract":[{"type":"text","text":"Configuration of the output settings."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/defaultFilter":{"navigatorTitle":[{"kind":"identifier","text":"defaultFilter"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultFilter","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/defaultfilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/defaultFilter","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Determines the image filter to apply by default."}],"title":"defaultFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Node":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2node","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Node","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"title":"SBSDKUI2Node","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/documentAnalysisMode":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/documentanalysismode","title":"documentAnalysisMode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered"},{"text":" ","type":"text"},{"type":"text","text":"image."},{"type":"text","text":" "},{"text":"Default is UNFILTERED_DOCUMENT","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAnalysisMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"documentAnalysisMode","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/isEqual:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/isequal:","title":"isEqual:","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/init()":{"abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/init()","title":"init()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/init()","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings","abstract":[{"text":"Configuration of the output settings.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"role":"symbol","type":"topic","title":"SBSDKUI2DocumentScannerOutputSettings"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)","role":"symbol","abstract":[],"title":"init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/init(pagesscanlimit:documentimagesizelimit:documentanalysismode:defaultfilter:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"pagesScanLimit","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentImageSizeLimit"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"documentAnalysisMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"defaultFilter"},{"text":": ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/toJson()":{"role":"symbol","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","title":"toJson()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/toJson()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/tojson()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/hash","type":"topic","role":"symbol","title":"hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/hash","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/init(from:)":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/init(from:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(from:)","title":"init(from:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/fromJsonWithJson:","role":"symbol","abstract":[],"title":"fromJsonWithJson:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/fromjsonwithjson:","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/pagesScanLimit":{"role":"symbol","navigatorTitle":[{"text":"pagesScanLimit","kind":"identifier"}],"abstract":[{"text":"The limit of the number of pages that can be scanned. Default is 0 (no limit).","type":"text"},{"text":" ","type":"text"},{"text":"Default is 0","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pagesScanLimit"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","title":"pagesScanLimit","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/pagesScanLimit","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/pagesscanlimit"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/documentImageSizeLimit":{"role":"symbol","title":"documentImageSizeLimit","abstract":[{"text":"The limit of the size of the cropped document images. If one of the dimensions of the cropped image is larger","type":"text"},{"type":"text","text":" "},{"type":"text","text":"than the limit, the image is downscaled so that its longer dimension matches the limit. The default is 0 (no"},{"type":"text","text":" "},{"text":"limit).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is 0"}],"navigatorTitle":[{"kind":"identifier","text":"documentImageSizeLimit"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentImageSizeLimit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/documentimagesizelimit","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentImageSizeLimit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SBSDKUI2DocumentScannerOutputSettings","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/defaultFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/hash","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/pagesScanLimit"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/toJson()"],"generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/fromJsonWithJson:"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Node","text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Node","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"defaultFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1defaultFilter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1defaultFilter\/fragments","value":[{"kind":"identifier","text":"defaultFilter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/fragments","op":"replace","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"value":"documentAnalysisMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentAnalysisMode\/title"},{"op":"replace","value":[{"text":"documentAnalysisMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentAnalysisMode\/fragments"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1init()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1init()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/title","op":"replace","value":"SBSDKUI2DocumentScannerOutputSettings"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)\/title","value":"initWithPagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1init(pagesScanLimit:documentImageSizeLimit:documentAnalysisMode:defaultFilter:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1toJson()\/title","value":"toJson","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1toJson()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJson","kind":"identifier"}]},{"value":"pagesScanLimit","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1pagesScanLimit\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1pagesScanLimit\/fragments","op":"replace","value":[{"kind":"identifier","text":"pagesScanLimit"}]},{"value":"documentImageSizeLimit","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentImageSizeLimit\/title"},{"value":[{"kind":"identifier","text":"documentImageSizeLimit"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentImageSizeLimit\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}