{"kind":"symbol","metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration","platforms":[],"roleHeading":"Class","role":"symbol","title":"SBSDKUICroppingScreenTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/accessibilityConfiguration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/detectButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/doneButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/hintTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/resetButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/rotateButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/topBarTitle"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"title":"Conforms To"}],"abstract":[{"text":"Configuration for the textual content of the page cropping screen.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2CroppingViewController instead."}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/cancelButtonTitle":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/cancelbuttontitle","abstract":[{"text":"String being displayed on the cancel button.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/cancelButtonTitle","kind":"symbol","role":"symbol","title":"cancelButtonTitle","navigatorTitle":[{"text":"cancelButtonTitle","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/accessibilityConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/accessibilityconfiguration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityConfiguration"},{"kind":"text","text":": "},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/accessibilityConfiguration","kind":"symbol","navigatorTitle":[{"text":"accessibilityConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A configuration with accessibility texts settings."}],"title":"accessibilityConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/topBarTitle":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/topbartitle","abstract":[{"text":"String being displayed as the title on the top bar.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/topBarTitle","kind":"symbol","role":"symbol","title":"topBarTitle","navigatorTitle":[{"text":"topBarTitle","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/hintTitle":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hintTitle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/hinttitle","abstract":[{"type":"text","text":"String being displayed as a hint. Empty by default."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/hintTitle","kind":"symbol","role":"symbol","title":"hintTitle","navigatorTitle":[{"text":"hintTitle","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration":{"title":"SBSDKUICroppingScreenTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"abstract":[{"text":"Configuration for the textual content of the page cropping screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration","deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/detectButtonTitle":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/detectButtonTitle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/detectbuttontitle","kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"detectButtonTitle","kind":"identifier"}],"role":"symbol","abstract":[{"text":"String being displayed on the detect button.","type":"text"}],"title":"detectButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectButtonTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/init","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/init","kind":"symbol","role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/doneButtonTitle":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/doneButtonTitle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/donebuttontitle","kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"doneButtonTitle","kind":"identifier"}],"role":"symbol","abstract":[{"text":"String being displayed on the done button.","type":"text"}],"title":"doneButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doneButtonTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/resetButtonTitle":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetButtonTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/resetbuttontitle","abstract":[{"text":"String being displayed on the reset button","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/resetButtonTitle","kind":"symbol","role":"symbol","title":"resetButtonTitle","navigatorTitle":[{"text":"resetButtonTitle","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/rotateButtonTitle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/rotateButtonTitle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/rotatebuttontitle","type":"topic","deprecated":true,"navigatorTitle":[{"text":"rotateButtonTitle","kind":"identifier"}],"role":"symbol","abstract":[{"text":"String being displayed on the rotate button.","type":"text"}],"title":"rotateButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rotateButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUICroppingScreenTextConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/accessibilityConfiguration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/cancelButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/detectButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/doneButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/hintTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/resetButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/rotateButtonTitle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/topBarTitle"],"title":"Instance Properties","anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/init"],"generated":true}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1cancelButtonTitle\/title","value":"cancelButtonTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1cancelButtonTitle\/fragments","value":[{"text":"cancelButtonTitle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1accessibilityConfiguration\/title","op":"replace","value":"accessibilityConfiguration"},{"value":[{"text":"accessibilityConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1accessibilityConfiguration\/fragments"},{"op":"replace","value":"topBarTitle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1topBarTitle\/title"},{"value":[{"text":"topBarTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1topBarTitle\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1hintTitle\/title","value":"hintTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1hintTitle\/fragments","value":[{"kind":"identifier","text":"hintTitle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration\/title","value":"SBSDKUICroppingScreenTextConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"op":"replace"},{"value":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration\/navigatorTitle"},{"op":"replace","value":"detectButtonTitle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1detectButtonTitle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1detectButtonTitle\/fragments","value":[{"kind":"identifier","text":"detectButtonTitle"}],"op":"replace"},{"op":"replace","value":"doneButtonTitle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1doneButtonTitle\/title"},{"value":[{"kind":"identifier","text":"doneButtonTitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1doneButtonTitle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1resetButtonTitle\/title","value":"resetButtonTitle","op":"replace"},{"value":[{"kind":"identifier","text":"resetButtonTitle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1resetButtonTitle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1rotateButtonTitle\/title","value":"rotateButtonTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1rotateButtonTitle\/fragments","value":[{"text":"rotateButtonTitle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}