{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/area","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKResamplingMethod.area","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"area","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKResamplingMethodArea","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod@SBSDKResamplingMethodArea","symbolKind":"case"},"sections":[],"kind":"symbol","abstract":[{"text":"Accurate, produces moire-free results, but tends to produce blurrier images. When","type":"text"},{"type":"text","text":" "},{"text":"upsampling, it is similar to nearest-neighbor.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/area"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/area"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"area","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/area":{"title":"SBSDKResamplingMethod.area","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/area","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/area","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"area","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKResamplingMethodArea","kind":"identifier"}],"abstract":[{"type":"text","text":"Accurate, produces moire-free results, but tends to produce blurrier images. When"},{"type":"text","text":" "},{"type":"text","text":"upsampling, it is similar to nearest-neighbor."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"navigatorTitle":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"title":"SBSDKResamplingMethod","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKResamplingMethod"}],"role":"symbol","abstract":[{"type":"text","text":"Resampling method."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKResamplingMethodArea","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKResamplingMethodArea"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKResamplingMethodArea"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1area\/title","value":"SBSDKResamplingMethodArea","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1area\/fragments","value":[{"text":"SBSDKResamplingMethodArea","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title","value":"SBSDKResamplingMethod","op":"replace"},{"value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments"},{"value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}