{"metadata":{"navigatorTitle":[{"text":"SBSDKDocumentDetectorModeMachineLearning","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode@SBSDKDocumentDetectorModeMachineLearning","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineLearning"}],"title":"SBSDKDocumentDetectorMode.machineLearning","role":"symbol","symbolKind":"case","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"The new machine-learning based detection mode."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode\/machinelearning"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode\/machinelearning"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineLearning","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/machineLearning"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode/machineLearning":{"type":"topic","title":"SBSDKDocumentDetectorMode.machineLearning","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/machineLearning","abstract":[{"text":"The new machine-learning based detection mode.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"machineLearning","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode\/machinelearning","navigatorTitle":[{"text":"SBSDKDocumentDetectorModeMachineLearning","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode":{"title":"SBSDKDocumentDetectorMode","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"abstract":[{"text":"The mode of the document detector: standard or machine-learning-based.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectorMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDetectorModeMachineLearning"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentDetectorModeMachineLearning","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentDetectorModeMachineLearning"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"SBSDKDocumentDetectorModeMachineLearning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1machineLearning\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1machineLearning\/fragments","value":[{"text":"SBSDKDocumentDetectorModeMachineLearning","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/title","value":"SBSDKDocumentDetectorMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/navigatorTitle"}]}]}