{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultLicenseFailureHandler","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:25ScanbotDocumentScannerSDK26SBSDKLicenseFailureHandlera","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseFailureHandler","text":"SBSDKLicenseFailureHandler"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The default license failure handler.","type":"text"}]}]}],"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"defaultLicenseFailureHandler","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)Scanbot(cm)defaultLicenseFailureHandler","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"SBSDKLicenseFailureHandler","kind":"typeIdentifier","preciseIdentifier":"s:25ScanbotDocumentScannerSDK26SBSDKLicenseFailureHandlera"}],"symbolKind":"method","title":"defaultLicenseFailureHandler()","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/defaultLicenseFailureHandler()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/defaultlicensefailurehandler()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/scanbot\/defaultlicensefailurehandler()"]}],"abstract":[{"type":"text","text":"The default license failure handler."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseFailureHandler":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensefailurehandler","abstract":[{"type":"text","text":"Typealias for license failure handling closure."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseFailureHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseFailureHandler"}],"kind":"symbol","type":"topic","title":"SBSDKLicenseFailureHandler","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicenseFailureHandler"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot/defaultLicenseFailureHandler()":{"abstract":[{"type":"text","text":"The default license failure handler."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultLicenseFailureHandler"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/defaultLicenseFailureHandler()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultLicenseFailureHandler","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKLicenseFailureHandler","preciseIdentifier":"s:25ScanbotDocumentScannerSDK26SBSDKLicenseFailureHandlera","kind":"typeIdentifier"}],"title":"defaultLicenseFailureHandler()","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot\/defaultlicensefailurehandler()","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Scanbot"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot","navigatorTitle":[{"text":"Scanbot","kind":"identifier"}],"abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}],"kind":"symbol","role":"symbol","title":"Scanbot"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"defaultLicenseFailureHandler","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"defaultLicenseFailureHandler","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#$@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus#$@M@ScanbotDocumentScannerSDK@E@SBSDKFeature#*$objc(cs)NSString)","text":"void (^)(enum SBSDKLicenseStatus, enum SBSDKFeature, NSString *)"},{"text":") ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The default license failure handler."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"defaultLicenseFailureHandler","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1defaultLicenseFailureHandler()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1defaultLicenseFailureHandler()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/title","value":"Scanbot","op":"replace"},{"op":"replace","value":[{"text":"Scanbot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Scanbot"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot\/navigatorTitle"}]}]}