{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configureStatusDetectionLabel"},{"kind":"text","text":" "},{"kind":"internalParam","text":"label"},{"text":": ","kind":"text"},{"text":"SBSDKDetectionStatusLabel","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDetectionStatusLabel","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forDetectionResult"},{"kind":"text","text":" "},{"text":"result","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The label to be configured.","type":"text"}]}],"name":"label"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the current document detection."}]}],"name":"result"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"You can change the visibility, colors, font, and text of the label here."}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerViewController(im)documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","title":"documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","extendedModule":"ScanbotSDK","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configureStatusDetectionLabel"},{"text":": ","kind":"text"},{"text":"SBSDKDetectionStatusLabel","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDetectionStatusLabel","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"forDetectionResult","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":"?)"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)"},"abstract":[{"type":"text","text":"Optional."},{"type":"text","text":" "},{"text":"Lets you configure the document detections status label, depending on the document detection status.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/SBSDKDocumentScannerViewControllerDelegate-Implementations"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/SBSDKDocumentScannerViewControllerDelegate-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/SBSDKDocumentScannerViewControllerDelegate-Implementations","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/sbsdkdocumentscannerviewcontrollerdelegate-implementations","type":"topic","title":"SBSDKDocumentScannerViewControllerDelegate Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController":{"kind":"symbol","title":"SBSDKUIDocumentScannerViewController","deprecated":true,"navigatorTitle":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDetectionStatusLabel":{"url":"\/documentation\/scanbotsdk\/sbsdkdetectionstatuslabel","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel","role":"symbol","kind":"symbol","title":"SBSDKDetectionStatusLabel","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UILabel"},{"text":" subclass with rounded corners and content insets to display the status of the current document detection result.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"navigatorTitle":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorResult":{"abstract":[{"text":"This class represents the result of a document detection","type":"text"},{"type":"text","text":" "},{"type":"text","text":"on an image."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"kind":"symbol","title":"SBSDKDocumentDetectorResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)":{"title":"documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","navigatorTitle":[{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)","abstract":[{"type":"text","text":"Optional."},{"type":"text","text":" "},{"text":"Lets you configure the document detections status label, depending on the document detection status.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:configurestatusdetectionlabel:fordetectionresult:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configureStatusDetectionLabel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDetectionStatusLabel","kind":"typeIdentifier","text":"SBSDKDetectionStatusLabel"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forDetectionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":"?)","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"documentScannerViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"text":"configureStatusDetectionLabel:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDetectionStatusLabel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel","kind":"typeIdentifier","text":"SBSDKDetectionStatusLabel"},{"kind":"text","text":" *) "},{"text":"label","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forDetectionResult:"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/title","value":"SBSDKUIDocumentScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/fragments","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/title","value":"SBSDKDetectionStatusLabel"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/fragments","value":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKDocumentDetectorResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/navigatorTitle"},{"value":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:configureStatusDetectionLabel:forDetectionResult:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:configureStatusDetectionLabel:forDetectionResult:","kind":"identifier"}]},{"op":"replace","value":"SBSDKDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}