{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation\/init(overlayColor:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"overlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorModalOverlay\", isArgb: false))"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfunnelanimation\/init(overlaycolor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2pagesnapfunnelanimation\/init(overlaycolor:)"]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"init(overlayColor:)","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PageSnapFunnelAnimation(im)initWithOverlayColor:","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"overlayColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOverlayColor:"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFunnelAnimation/init(overlayColor:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfunnelanimation\/init(overlaycolor:)","abstract":[],"title":"init(overlayColor:)","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation\/init(overlayColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"overlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithOverlayColor:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PageSnapFunnelAnimation":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2PageSnapFunnelAnimation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PageSnapFunnelAnimation","abstract":[{"text":"Configuration of the funnel animation.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2pagesnapfunnelanimation","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}],"title":"SBSDKUI2PageSnapFunnelAnimation","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","type":"topic","abstract":[],"title":"SBSDKUI2Color","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithOverlayColor:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOverlayColor:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithOverlayColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"overlayColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation~1init(overlayColor:)\/title","value":"initWithOverlayColor:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation~1init(overlayColor:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOverlayColor:"}]},{"value":"SBSDKUI2PageSnapFunnelAnimation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFunnelAnimation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PageSnapFunnelAnimation\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace","value":"SBSDKUI2Color"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]}]}]}