{"abstract":[{"type":"text","text":"Creates a new instance of the VIN scanner and returns it to be presented modally."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerviewcontroller\/create(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerviewcontroller\/create(with:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenConfiguration","kind":"typeIdentifier","text":"SBSDKUI2VINScannerScreenConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerUIResult","kind":"typeIdentifier","text":"SBSDKUI2VINScannerUIResult"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerViewController","kind":"typeIdentifier","text":"SBSDKUI2VINScannerViewController"}],"title":"create(with:completion:)","navigatorTitle":[{"kind":"identifier","text":"createWith:completion:"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerViewController(cm)createWith:completion:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController\/create(with:completion:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration","text":"SBSDKUI2VINScannerScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult","text":"SBSDKUI2VINScannerUIResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerUIResult"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController","text":"SBSDKUI2VINScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerViewController"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration object for the VIN scanner screen."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion closure that is called when the VIN scanner has finished."}],"type":"paragraph"}]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerviewcontroller","navigatorTitle":[{"text":"SBSDKUI2VINScannerViewController","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKUI2VINScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan VIN (Vehicle Identification Number) data.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenConfiguration":{"abstract":[{"type":"text","text":"Configuration of the screen for detecting VIN data."}],"title":"SBSDKUI2VINScannerScreenConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerViewController/create(with:completion:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController\/create(with:completion:)","navigatorTitle":[{"text":"createWith:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a new instance of the VIN scanner and returns it to be presented modally."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerviewcontroller\/create(with:completion:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenConfiguration","text":"SBSDKUI2VINScannerScreenConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerUIResult","text":"SBSDKUI2VINScannerUIResult","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerViewController","text":"SBSDKUI2VINScannerViewController","kind":"typeIdentifier"}],"title":"create(with:completion:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerUIResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscanneruiresult","abstract":[{"type":"text","text":"Configuration of the generic text scanner RTU UI result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult","kind":"symbol","title":"SBSDKUI2VINScannerUIResult","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWith:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWith:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2VINScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerViewController"},{"text":" *) ","kind":"text"},{"text":"createWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2VINScannerScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"SBSDKUI2VINScannerUIResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerUIResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerUIResult"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The configuration object for the VIN scanner screen."}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion closure that is called when the VIN scanner has finished."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/title","value":"SBSDKUI2VINScannerViewController"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2VINScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2VINScannerScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2VINScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2VINScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenConfiguration\/navigatorTitle"},{"op":"replace","value":"createWith:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController~1create(with:completion:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWith:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController~1create(with:completion:)\/fragments"},{"op":"replace","value":"SBSDKUI2VINScannerUIResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerUIResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2VINScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerUIResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}