{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProcessByTileConfiguration(im)isEqual:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration\/isEqual:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration\/isequal:"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessByTileConfiguration/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration\/isEqual:","title":"isEqual:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration\/isequal:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessByTileConfiguration":{"title":"SBSDKProcessByTileConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"abstract":[{"text":"Configuration for processing image by tiles.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,","type":"text"},{"text":" ","type":"text"},{"text":"but prediction can be less accurate.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/title","value":"SBSDKProcessByTileConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle","value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"op":"replace"}]}]}