{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(checkScannerViewController:didFailScanningWithError:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","text":"SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The check scanner viewController that failed scanning.","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"The error that occurred during scanning.","type":"text"}]}]}],"kind":"parameters"}],"abstract":[{"text":"Informs the delegate, that the check scanner has failed scanning a check with an error.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didFailScanning:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontroller(_:didfailscanning:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontroller(_:didfailscanning:)"]}],"metadata":{"navigatorTitle":[{"text":"checkScannerViewController:didFailScanningWithError:","kind":"identifier"}],"title":"checkScannerViewController(_:didFailScanning:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckScannerViewControllerDelegate(im)checkScannerViewController:didFailScanningWithError:","roleHeading":"Instance Method","symbolKind":"method","required":true,"role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate/checkScannerViewController(_:didFailScanning:)":{"title":"checkScannerViewController(_:didFailScanning:)","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontroller(_:didfailscanning:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkScannerViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","kind":"typeIdentifier","text":"SBSDKCheckScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailScanning"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkScannerViewController:didFailScanningWithError:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewController(_:didFailScanning:)","abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has failed scanning a check with an error."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"kind":"symbol","title":"SBSDKCheckScannerViewController","navigatorTitle":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan bank checks."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate","navigatorTitle":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The delegation protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","type":"reference","isActive":true},{"type":"text","text":" class."}],"title":"SBSDKCheckScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"checkScannerViewController:didFailScanningWithError:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkScannerViewController:didFailScanningWithError:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"checkScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","text":"SBSDKCheckScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFailScanningWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The check scanner viewController that failed scanning."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"The error that occurred during scanning.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewController(_:didFailScanning:)\/title","value":"checkScannerViewController:didFailScanningWithError:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkScannerViewController:didFailScanningWithError:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewController(_:didFailScanning:)\/fragments"},{"value":"SBSDKCheckScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments"},{"value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle"},{"value":"SBSDKCheckScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}]}]}]}