{"sections":[],"kind":"symbol","abstract":[{"text":"Whether flash is toggled on or off.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFlashEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFlashEnabled"}],"title":"isFlashEnabled","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerBehaviorConfiguration(py)isFlashEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFlashEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration\/isflashenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration\/isflashenabled"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/isFlashEnabled"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration/isFlashEnabled":{"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration\/isflashenabled","kind":"symbol","abstract":[{"text":"Whether flash is toggled on or off.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFlashEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isFlashEnabled"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/isFlashEnabled","title":"isFlashEnabled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerBehaviorConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescannerbehaviorconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI medical certificates scanner."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerBehaviorConfiguration","title":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"isFlashEnabled","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"isFlashEnabled"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFlashEnabled"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1isFlashEnabled\/title","op":"replace","value":"isFlashEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration~1isFlashEnabled\/fragments","value":[{"text":"isFlashEnabled","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration"},{"value":[{"text":"SBSDKUIMedicalCertificateScannerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerBehaviorConfiguration\/fragments","op":"replace"}]}]}