{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile\/imageInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Image-specific information, e.g. memory consumption."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile"]]},"metadata":{"navigatorTitle":[{"text":"imageInfo","kind":"identifier"}],"symbolKind":"property","title":"imageInfo","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefProfile(py)imageInfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProfile","text":"SBSDKImageProfile","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/imageinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/imageinfo"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageInfo","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProfile","text":"SBSDKImageProfile","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfile":{"url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofile","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfile"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"ImageRef profile which provides detailed information about stored object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"title":"SBSDKImageRefProfile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfile/imageInfo":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/imageinfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageProfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProfile","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Image-specific information, e.g. memory consumption."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile\/imageInfo","title":"imageInfo"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProfile":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageProfile"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprofile","abstract":[{"text":"ImageRef profile part specific to image information.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile","kind":"symbol","title":"SBSDKImageProfile","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProfile"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"imageInfo","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"imageInfo","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKImageProfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProfile","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageInfo"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/title","op":"replace","value":"SBSDKImageRefProfile"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile~1imageInfo\/title","op":"replace","value":"imageInfo"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile~1imageInfo\/fragments","op":"replace","value":[{"text":"imageInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/title","op":"replace","value":"SBSDKImageProfile"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/fragments","op":"replace","value":[{"text":"SBSDKImageProfile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageProfile","kind":"identifier"}]}]}]}