{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageSource","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageSource"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"metadata":{"title":"imageSource","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageSource","text":"SBSDKImageSource","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefProfile(py)imageSource","role":"symbol","navigatorTitle":[{"text":"imageSource","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/imagesource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/imagesource"]}],"abstract":[{"type":"text","text":"Description of source from which the ImageRef was created. Non-null only if detailed profiling has been previously enabled by a call to enableDetailedProfiling."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile\/imageSource"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfile":{"url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofile","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfile"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"ImageRef profile which provides detailed information about stored object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"title":"SBSDKImageRefProfile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfile/imageSource":{"title":"imageSource","navigatorTitle":[{"text":"imageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Description of source from which the ImageRef was created. Non-null only if detailed profiling has been previously enabled by a call to enableDetailedProfiling."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKImageSource","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageSource","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/imagesource","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile\/imageSource"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSource":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageSource"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagesource","title":"SBSDKImageSource","type":"topic","abstract":[{"text":"Description of source from which the ImageRef was created.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSource"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"imageSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"imageSource","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKImageSource","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageSource"},{"text":" * ","kind":"text"},{"text":"imageSource","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/title","value":"SBSDKImageRefProfile"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/fragments","value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/navigatorTitle","value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile~1imageSource\/title","value":"imageSource"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile~1imageSource\/fragments","value":[{"text":"imageSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/title","value":"SBSDKImageSource"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/fragments","value":[{"kind":"identifier","text":"SBSDKImageSource"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}