{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/View-Implementations"]]},"metadata":{"platforms":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"13.0","deprecated":false,"renamed":"accessibilityLabel(_:)","deprecatedAt":"100000.0"},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"13.0","deprecated":false,"renamed":"accessibilityLabel(_:)","deprecatedAt":"100000.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.0","deprecated":false,"renamed":"accessibilityLabel(_:)","deprecatedAt":"100000.0"},{"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.15","deprecated":false,"renamed":"accessibilityLabel(_:)","deprecatedAt":"100000.0"},{"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"13.0","deprecated":false,"renamed":"accessibilityLabel(_:)","deprecatedAt":"100000.0"},{"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"renamed":"accessibilityLabel(_:)","deprecatedAt":"100000.0"},{"beta":false,"name":"watchOS","unavailable":false,"introducedAt":"6.0","deprecated":false,"renamed":"accessibilityLabel(_:)","deprecatedAt":"100000.0"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibility"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Text","preciseIdentifier":"s:7SwiftUI4TextV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ModifiedContent","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AccessibilityAttachmentModifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"kind":"text","text":">"}],"extendedModule":"SwiftUICore","symbolKind":"method","externalID":"s:7SwiftUI4ViewPAAE13accessibility5labelAA15ModifiedContentVyxAA31AccessibilityAttachmentModifierVGAA4TextV_tF::SYNTHESIZED::s:10ScanbotSDK29SBSDKUI2CreditCardScannerViewV","title":"accessibility(label:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibility"},{"kind":"text","text":"("},{"kind":"externalParam","text":"label"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV","text":"Text"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/accessibility(label:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/accessibility(label:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.accessibility(label:)"},{"type":"text","text":"."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView/accessibility(label:)":{"title":"accessibility(label:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Text","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV"},{"text":") -> ","kind":"text"},{"text":"ModifiedContent","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AccessibilityAttachmentModifier","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"text":">","kind":"text"}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/accessibility(label:)","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/accessibility(label:)","abstract":[],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView/View-Implementations":{"role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/View-Implementations","abstract":[],"title":"View Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerViewController"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan credit card data.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerViewController","title":"SBSDKUI2CreditCardScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView":{"title":"SBSDKUI2CreditCardScannerView","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerView"}],"abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerView"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/title","value":"SBSDKUI2CreditCardScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/fragments","value":[{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}