{"abstract":[{"text":"Designated initializer. Creates a new instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration","isActive":true},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:)","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:trackingoverlayconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:trackingoverlayconfiguration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"uiConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerTextConfiguration","text":"SBSDKUIBarcodeScannerTextConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerBehaviorConfiguration"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackingOverlayConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:"}],"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerConfiguration(im)initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:","platforms":[],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Initializer","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"uiConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration"},{"text":", ","kind":"text"},{"text":"textConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerTextConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration","text":"SBSDKUIBarcodeScannerTextConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"behaviorConfiguration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration","text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerBehaviorConfiguration"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","kind":"typeIdentifier","text":"SBSDKUICameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackingOverlayConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for the user interface. Defines colors and sizes."}]}],"name":"uiConfiguration"},{"name":"textConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration for text being displayed in the barcode scanner screen.","type":"text"}]}]},{"name":"behaviorConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for barcode scanner behavior."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"A configuration for the barcode scanners camera."}],"type":"paragraph"}],"name":"cameraConfiguration"},{"content":[{"inlineContent":[{"text":"A configuration for the barcode scanners tracking overlay.","type":"text"}],"type":"paragraph"}],"name":"trackingOverlayConfiguration"}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerTextConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannertextconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerTextConfiguration"}],"title":"SBSDKUIBarcodeScannerTextConfiguration","deprecated":true,"role":"symbol","navigatorTitle":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerConfiguration/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"uiConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration","text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerTextConfiguration","text":"SBSDKUIBarcodeScannerTextConfiguration"},{"kind":"text","text":", "},{"text":"behaviorConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cameraConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration","text":"SBSDKUICameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"trackingOverlayConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:","kind":"identifier"}],"type":"topic","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration\/init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:)","title":"init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerconfiguration\/init(uiconfiguration:textconfiguration:behaviorconfiguration:cameraconfiguration:trackingoverlayconfiguration:)","abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration","isActive":true,"type":"reference"},{"text":".","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration","role":"symbol","type":"topic","kind":"symbol","title":"SBSDKUIBarcodeScannerConfiguration","abstract":[{"type":"text","text":"This class describes the look and feel, as well as the textual contents of the RTU-UI barcode scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerConfiguration","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraConfiguration":{"type":"topic","title":"SBSDKUICameraConfiguration","abstract":[{"text":"Configuration for the camera of all RTU-UI components.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","navigatorTitle":[{"text":"SBSDKUICameraConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICameraConfiguration"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicameraconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeTrackingOverlayConfiguration":{"title":"SBSDKUIBarcodeTrackingOverlayConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","abstract":[{"text":"The configuration object for the RTU-UI barcode tracking overlay.","type":"text"}],"kind":"symbol","deprecated":true,"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodetrackingoverlayconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerBehaviorConfiguration":{"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerbehaviorconfiguration","title":"SBSDKUIBarcodeScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"text":"The configuration for the behavior of the RTU-UI barcode scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerUIConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration","abstract":[{"type":"text","text":"The configuration for user interface of the RTU-UI barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration","title":"SBSDKUIBarcodeScannerUIConfiguration","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithUiConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIBarcodeScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"uiConfiguration"},{"kind":"text","text":" "},{"text":"textConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerTextConfiguration","kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerTextConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"behaviorConfiguration:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerBehaviorConfiguration","text":"SBSDKUIBarcodeScannerBehaviorConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"behaviorConfiguration"},{"text":" ","kind":"text"},{"text":"cameraConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUICameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraConfiguration"},{"text":" *) ","kind":"text"},{"text":"cameraConfiguration","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingOverlayConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeTrackingOverlayConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeTrackingOverlayConfiguration","text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"trackingOverlayConfiguration","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"uiConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for the user interface. Defines colors and sizes."}]}]},{"name":"textConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration for text being displayed in the barcode scanner screen.","type":"text"}]}]},{"name":"behaviorConfiguration","content":[{"inlineContent":[{"text":"A configuration for barcode scanner behavior.","type":"text"}],"type":"paragraph"}]},{"name":"cameraConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"A configuration for the barcode scanners camera.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A configuration for the barcode scanners tracking overlay."}]}],"name":"trackingOverlayConfiguration"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/title","value":"SBSDKUIBarcodeScannerTextConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerTextConfiguration"}]},{"value":[{"text":"SBSDKUIBarcodeScannerTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerTextConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:)\/title","value":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration~1init(uiConfiguration:textConfiguration:behaviorConfiguration:cameraConfiguration:trackingOverlayConfiguration:)\/fragments","op":"replace"},{"value":"SBSDKUIBarcodeScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration\/title"},{"value":[{"text":"SBSDKUIBarcodeScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration\/navigatorTitle"},{"value":"SBSDKUICameraConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUICameraConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICameraConfiguration","kind":"identifier"}]},{"value":"SBSDKUIBarcodeTrackingOverlayConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/title"},{"value":[{"text":"SBSDKUIBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeTrackingOverlayConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeTrackingOverlayConfiguration"}]},{"value":"SBSDKUIBarcodeScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/title"},{"value":[{"text":"SBSDKUIBarcodeScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerBehaviorConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerBehaviorConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/title","value":"SBSDKUIBarcodeScannerUIConfiguration"},{"op":"replace","value":[{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}