{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"textLineScannerViewController:didFailScanningWithError:"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textPatternScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKTextPatternScannerViewControllerDelegate(im)textLineScannerViewController:didFailScanningWithError:","title":"textPatternScannerViewController(_:didFailScanning:)","required":true,"role":"symbol","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(textLineScannerViewController:didFailScanningWithError:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textPatternScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailScanning"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The scanner controller where scanning has failed."}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred during scanning."}]}],"name":"error"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate\/textPatternScannerViewController(_:didFailScanning:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate that scanning has failed with an error."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate\/textpatternscannerviewcontroller(_:didfailscanning:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate\/textpatternscannerviewcontroller(_:didfailscanning:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate"]]},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show a camera screen with the text pattern scanner.","type":"text"}],"title":"SBSDKTextPatternScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate","role":"symbol","type":"topic","title":"SBSDKTextPatternScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The delegation protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKTextPatternScannerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewControllerDelegate/textPatternScannerViewController(_:didFailScanning:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewControllerDelegate\/textPatternScannerViewController(_:didFailScanning:)","abstract":[{"type":"text","text":"Informs the delegate that scanning has failed with an error."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontrollerdelegate\/textpatternscannerviewcontroller(_:didfailscanning:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textPatternScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController"},{"text":", ","kind":"text"},{"text":"didFailScanning","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"required":true,"type":"topic","navigatorTitle":[{"text":"textLineScannerViewController:didFailScanningWithError:","kind":"identifier"}],"kind":"symbol","title":"textPatternScannerViewController(_:didFailScanning:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"textLineScannerViewController:didFailScanningWithError:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textLineScannerViewController:didFailScanningWithError:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"textLineScannerViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","kind":"typeIdentifier","text":"SBSDKTextPatternScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailScanningWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The scanner controller where scanning has failed."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"The error that occurred during scanning.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKTextPatternScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title"},{"value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments"},{"value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle"},{"value":"SBSDKTextPatternScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKTextPatternScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate\/navigatorTitle"},{"value":"textLineScannerViewController:didFailScanningWithError:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate~1textPatternScannerViewController(_:didFailScanning:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textLineScannerViewController:didFailScanningWithError:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewControllerDelegate~1textPatternScannerViewController(_:didFailScanning:)\/fragments"}]}]}