{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"standard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2GS1SystemElementValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2GS1SystemElementValidationStatus","text":"SBSDKUI2GS1SystemElementValidationStatus"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1documentfield\/init(rawvalue:applicationidentifier:datatitle:fielddescription:standard:validationstatus:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1documentfield\/init(rawvalue:applicationidentifier:datatitle:fielddescription:standard:validationstatus:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2GS1DocumentField\/init(rawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"standard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2GS1SystemElementValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2GS1SystemElementValidationStatus"},{"kind":"text","text":")"}],"title":"init(rawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2GS1DocumentField(im)initWithRawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2GS1DocumentField"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2GS1DocumentField":{"role":"symbol","title":"SBSDKUI2GS1DocumentField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2GS1DocumentField"}],"abstract":[{"type":"text","text":"GS1 Document Field"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2GS1DocumentField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2GS1DocumentField"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1documentfield"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2GS1DocumentField/init(rawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:)":{"role":"symbol","title":"init(rawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dataTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"standard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2GS1SystemElementValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2GS1SystemElementValidationStatus"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Designated initializer."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2GS1DocumentField\/init(rawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1documentfield\/init(rawvalue:applicationidentifier:datatitle:fielddescription:standard:validationstatus:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2GS1SystemElementValidationStatus":{"role":"symbol","title":"SBSDKUI2GS1SystemElementValidationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatus"}],"abstract":[{"type":"text","text":"GS1 Element Validation Status"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2GS1SystemElementValidationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatus"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1systemelementvalidationstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithRawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRawValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawValue"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"applicationIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldDescription:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fieldDescription"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"standard"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2GS1SystemElementValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2GS1SystemElementValidationStatus","text":"SBSDKUI2GS1SystemElementValidationStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"validationStatus"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2GS1DocumentField\/title","value":"SBSDKUI2GS1DocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2GS1DocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2GS1DocumentField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2GS1DocumentField~1init(rawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:)\/title","value":"initWithRawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2GS1DocumentField~1init(rawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRawValue:applicationIdentifier:dataTitle:fieldDescription:standard:validationStatus:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2GS1SystemElementValidationStatus\/title","value":"SBSDKUI2GS1SystemElementValidationStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2GS1SystemElementValidationStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2GS1SystemElementValidationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}