{"abstract":[{"text":"The default configuration.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2CroppingViewController instead.","type":"text"}],"type":"paragraph"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenconfiguration\/defaultconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration\/defaultConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUICroppingScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenConfiguration"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"platforms":[],"navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenConfiguration(cpy)defaultConfiguration","role":"symbol","roleHeading":"Type Property","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUICroppingScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenConfiguration"}],"title":"defaultConfiguration"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenConfiguration/defaultConfiguration":{"title":"defaultConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenconfiguration\/defaultconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenConfiguration","text":"SBSDKUICroppingScreenConfiguration","kind":"typeIdentifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration\/defaultConfiguration","abstract":[{"type":"text","text":"The default configuration."}],"navigatorTitle":[{"text":"defaultConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenConfiguration","kind":"identifier"}],"title":"SBSDKUICroppingScreenConfiguration","abstract":[{"type":"text","text":"This class describes the look and feel, as well as the textual contents of the page cropping screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration","type":"topic","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenConfiguration"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"defaultConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"defaultConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenConfiguration","text":"SBSDKUICroppingScreenConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"defaultConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration~1defaultConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"defaultConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration~1defaultConfiguration\/fragments"},{"op":"replace","value":"SBSDKUICroppingScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}