{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualitythreshold\/initwithsymbolquality:symbolratio:"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSymbolQuality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"symbolQuality"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbolRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"symbolRatio"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithSymbolQuality:symbolRatio:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"initWithSymbolQuality:symbolRatio:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSymbolQuality:symbolRatio:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityThreshold(im)initWithSymbolQuality:symbolRatio:","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityThreshold"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityThreshold\/initWithSymbolQuality:symbolRatio:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityThreshold/initWithSymbolQuality:symbolRatio:":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualitythreshold\/initwithsymbolquality:symbolratio:","kind":"symbol","title":"initWithSymbolQuality:symbolRatio:","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityThreshold\/initWithSymbolQuality:symbolRatio:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSymbolQuality:symbolRatio:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSymbolQuality:symbolRatio:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityThreshold":{"role":"symbol","abstract":[{"text":"Point in the quality-number of symbols space to separate quality levels.","type":"text"}],"type":"topic","title":"SBSDKDocumentQualityThreshold","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityThreshold","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualitythreshold","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityThreshold"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityThreshold"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKDocumentQualityThreshold","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityThreshold\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityThreshold\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityThreshold\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}