{"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateCheckBoxType@SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKMedicalCertificateCheckBoxType.entitlementToContinuedPaymentNo","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"entitlementToContinuedPaymentNo"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/entitlementtocontinuedpaymentno"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/entitlementtocontinuedpaymentno"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"entitlementToContinuedPaymentNo","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"(Form 21a) Entitlement to continued payment no (keinen Anspruch auf Entgeltfortzahlung) checkbox.","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentNo","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/entitlementToContinuedPaymentNo":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/entitlementtocontinuedpaymentno","title":"SBSDKMedicalCertificateCheckBoxType.entitlementToContinuedPaymentNo","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"entitlementToContinuedPaymentNo"}],"abstract":[{"text":"(Form 21a) Entitlement to continued payment no (keinen Anspruch auf Entgeltfortzahlung) checkbox.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentNo"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType","abstract":[{"type":"text","text":"Type of the checkbox."}],"kind":"symbol","title":"SBSDKMedicalCertificateCheckBoxType","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1entitlementToContinuedPaymentNo\/title","value":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1entitlementToContinuedPaymentNo\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentNo"}]},{"value":"SBSDKMedicalCertificateCheckBoxType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/fragments"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/navigatorTitle"}]}]}