{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/init(rawvalue:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/init(rawValue:)"},"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"externalID":"s:10ScanbotSDK32SBSDKAustraliaPostCustomerFormatO8rawValueACSgSi_tcfc","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"title":"init(rawValue:)","role":"symbol"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat/init(rawValue:)":{"url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/init(rawValue:)","abstract":[],"kind":"symbol","type":"topic","title":"init(rawValue:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat":{"title":"SBSDKAustraliaPostCustomerFormat","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","abstract":[{"type":"text","text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62."}],"navigatorTitle":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/title","op":"replace","value":"SBSDKAustraliaPostCustomerFormat"},{"op":"replace","value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/navigatorTitle","value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}