{"metadata":{"roleHeading":"Instance Property","title":"keyProvider","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting(py)keyProvider","required":true,"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider"}],"navigatorTitle":[{"kind":"identifier","text":"keyProvider"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting"]]},"abstract":[{"type":"text","text":"The key provider that provides\/generates the encryption keys."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"keyProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyProvider","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/keyprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/keyprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/keyProvider","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting/keyProvider":{"type":"topic","navigatorTitle":[{"text":"keyProvider","kind":"identifier"}],"kind":"symbol","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"keyProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","text":"SBSDKStorageCryptingKeyProvider"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting\/keyProvider","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting\/keyprovider","abstract":[{"type":"text","text":"The key provider that provides\/generates the encryption keys."}],"title":"keyProvider"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCrypting"}],"title":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","type":"topic","navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol for loading, storing and providing encryption keys."},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","title":"SBSDKStorageCryptingKeyProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"keyProvider","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"keyProvider","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"id<SBSDKStorageCryptingKeyProvider>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider"},{"kind":"text","text":" "},{"text":"keyProvider","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting~1keyProvider\/title","op":"replace","value":"keyProvider"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting~1keyProvider\/fragments","value":[{"kind":"identifier","text":"keyProvider"}]},{"op":"replace","value":"SBSDKStorageCrypting","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments"},{"op":"replace","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/title","value":"SBSDKStorageCryptingKeyProvider","op":"replace"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle"}]}]}