{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"detectButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(text: \"?croppingDetectButtonTitle\",\n                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                      isArgb: false)),\n                                       accessibilityDescription: \"?accessibilityDescriptionCroppingDetectButton\",\n                                       background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                      isArgb: false),\n                                                                           fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                    isArgb: false),\n                                                                           strokeWidth: 0.0),\n                                       icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                    isArgb: false))), ","kind":"text"},{"kind":"externalParam","text":"rotateButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(text: \"?croppingRotateButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCroppingRotateButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))), ","kind":"text"},{"kind":"externalParam","text":"resetButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" = SBSDKUI2BarButtonConfiguration(title: SBSDKUI2StyledText(text: \"?croppingResetButtonTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)),\n                                           accessibilityDescription: \"?accessibilityDescriptionCroppingResetButton\",\n                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                          isArgb: false),\n                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                        isArgb: false),\n                                                                               strokeWidth: 0.0),\n                                           icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                        isArgb: false))))"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"detectButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"rotateButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"resetButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":")"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithDetectButton:rotateButton:resetButton:"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CroppingBottomBar(im)initWithDetectButton:rotateButton:resetButton:","title":"init(detectButton:rotateButton:resetButton:)","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingbottombar\/init(detectbutton:rotatebutton:resetbutton:)"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingbottombar\/init(detectbutton:rotatebutton:resetbutton:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar\/init(detectButton:rotateButton:resetButton:)"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingBottomBar/init(detectButton:rotateButton:resetButton:)":{"role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"detectButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"text":"rotateButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resetButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithDetectButton:rotateButton:resetButton:","kind":"identifier"}],"title":"init(detectButton:rotateButton:resetButton:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar\/init(detectButton:rotateButton:resetButton:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingbottombar\/init(detectbutton:rotatebutton:resetbutton:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CroppingBottomBar":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CroppingBottomBar","title":"SBSDKUI2CroppingBottomBar","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2croppingbottombar","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingBottomBar","kind":"identifier"}],"abstract":[{"text":"Configuration of the bottom bar for the cropping screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingBottomBar"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BarButtonConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2barbuttonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","kind":"symbol","title":"SBSDKUI2BarButtonConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the button located on a bar."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithDetectButton:rotateButton:resetButton:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectButton:rotateButton:resetButton:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithDetectButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" *) "},{"text":"detectButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rotateButton:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rotateButton"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"resetButton"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":"initWithDetectButton:rotateButton:resetButton:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar~1init(detectButton:rotateButton:resetButton:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar~1init(detectButton:rotateButton:resetButton:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDetectButton:rotateButton:resetButton:"}],"op":"replace"},{"value":"SBSDKUI2CroppingBottomBar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/fragments","value":[{"text":"SBSDKUI2CroppingBottomBar","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CroppingBottomBar\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingBottomBar","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/title","op":"replace","value":"SBSDKUI2BarButtonConfiguration"},{"value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle"}]}]}