{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoLocation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvcarddocumentfieldtype\/geolocation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvcarddocumentfieldtype\/geolocation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFieldType\/geoLocation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The geolocation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoLocation"}],"title":"SBSDKVCardDocumentFieldType.geoLocation","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKVCardDocumentFieldType@SBSDKVCardDocumentFieldTypeGeoLocation","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeGeoLocation"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVCardDocumentFieldType/geoLocation":{"role":"symbol","title":"SBSDKVCardDocumentFieldType.geoLocation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"geoLocation"}],"abstract":[{"type":"text","text":"The geolocation."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFieldType\/geoLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeGeoLocation"}],"url":"\/documentation\/scanbotsdk\/sbsdkvcarddocumentfieldtype\/geolocation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVCardDocumentFieldType":{"role":"symbol","title":"SBSDKVCardDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVCardDocumentFieldType"}],"abstract":[{"type":"text","text":"The vCard document field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkvcarddocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVCardDocumentFieldTypeGeoLocation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeGeoLocation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeGeoLocation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVCardDocumentFieldType~1geoLocation\/title","value":"SBSDKVCardDocumentFieldTypeGeoLocation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVCardDocumentFieldType~1geoLocation\/fragments","value":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeGeoLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVCardDocumentFieldType\/title","value":"SBSDKVCardDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVCardDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}