{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvcarddocumentfieldtype\/title"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvcarddocumentfieldtype\/title"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFieldType\/title","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The title."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"}],"title":"SBSDKVCardDocumentFieldType.title","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKVCardDocumentFieldType@SBSDKVCardDocumentFieldTypeTitle","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeTitle"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVCardDocumentFieldType/title":{"role":"symbol","title":"SBSDKVCardDocumentFieldType.title","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"}],"abstract":[{"type":"text","text":"The title."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFieldType\/title","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeTitle"}],"url":"\/documentation\/scanbotsdk\/sbsdkvcarddocumentfieldtype\/title"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVCardDocumentFieldType":{"role":"symbol","title":"SBSDKVCardDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVCardDocumentFieldType"}],"abstract":[{"type":"text","text":"The vCard document field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVCardDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkvcarddocumentfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVCardDocumentFieldTypeTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeTitle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeTitle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVCardDocumentFieldType~1title\/title","value":"SBSDKVCardDocumentFieldTypeTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVCardDocumentFieldType~1title\/fragments","value":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldTypeTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVCardDocumentFieldType\/title","value":"SBSDKVCardDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVCardDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKVCardDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}