{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraOverlayColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraOverlayColor"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorUIConfiguration(py)cameraOverlayColor","title":"cameraOverlayColor","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraOverlayColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/cameraoverlaycolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/cameraoverlaycolor"]}],"abstract":[{"type":"text","text":"The background color of the detection overlay."}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration\/cameraOverlayColor","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorUIConfiguration/cameraOverlayColor":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration\/cameraoverlaycolor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cameraOverlayColor"}],"type":"topic","title":"cameraOverlayColor","kind":"symbol","abstract":[{"type":"text","text":"The background color of the detection overlay."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration\/cameraOverlayColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraOverlayColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorUIConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorUIConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorUIConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractoruiconfiguration","kind":"symbol","title":"SBSDKUIDocumentDataExtractorUIConfiguration","role":"symbol","abstract":[{"type":"text","text":"The configuration for the user interface of the RTU-UI document data extractor screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"cameraOverlayColor","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cameraOverlayColor"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"cameraOverlayColor","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration~1cameraOverlayColor\/title","value":"cameraOverlayColor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration~1cameraOverlayColor\/fragments","value":[{"text":"cameraOverlayColor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/title","value":"SBSDKUIDocumentDataExtractorUIConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUIDocumentDataExtractorUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorUIConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}