{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"textRectForBounds:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bounds","kind":"internalParam"},{"kind":"text","text":" "},{"text":"limitedToNumberOfLines:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"numberOfLines"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel\/textRectForBounds:limitedToNumberOfLines:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdetectionstatuslabel\/textrectforbounds:limitedtonumberoflines:"]}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDetectionStatusLabel(im)textRectForBounds:limitedToNumberOfLines:","title":"textRectForBounds:limitedToNumberOfLines:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textRectForBounds:limitedToNumberOfLines:"}],"symbolKind":"method","navigatorTitle":[{"text":"textRectForBounds:limitedToNumberOfLines:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDetectionStatusLabel/textRectForBounds:limitedToNumberOfLines:":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"textRectForBounds:limitedToNumberOfLines:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel\/textRectForBounds:limitedToNumberOfLines:","navigatorTitle":[{"text":"textRectForBounds:limitedToNumberOfLines:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdetectionstatuslabel\/textrectforbounds:limitedtonumberoflines:","abstract":[],"title":"textRectForBounds:limitedToNumberOfLines:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDetectionStatusLabel":{"navigatorTitle":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"kind":"symbol","title":"SBSDKDetectionStatusLabel","abstract":[{"type":"text","text":"A "},{"code":"UILabel","type":"codeVoice"},{"type":"text","text":" subclass with rounded corners and content insets to display the status of the current document scanning result."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"url":"\/documentation\/scanbotsdk\/sbsdkdetectionstatuslabel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/title","value":"SBSDKDetectionStatusLabel"},{"value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/navigatorTitle","value":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"op":"replace"}]}]}