{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorUnacceptableDocument","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorunacceptabledocument"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorunacceptabledocument"]}],"abstract":[{"text":"A document was detected as a supported document, but it was not part of the accepted","type":"text"},{"type":"text","text":" "},{"type":"text","text":"documents."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnacceptableDocument"},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentRecognitionStatus@SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument","symbolKind":"case","title":"SBSDKGenericDocumentRecognitionStatus.errorUnacceptableDocument","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorUnacceptableDocument","kind":"identifier"}],"roleHeading":"Case"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/errorUnacceptableDocument":{"type":"topic","title":"SBSDKGenericDocumentRecognitionStatus.errorUnacceptableDocument","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorunacceptabledocument","abstract":[{"type":"text","text":"A document was detected as a supported document, but it was not part of the accepted"},{"text":" ","type":"text"},{"text":"documents.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnacceptableDocument","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorUnacceptableDocument"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus":{"title":"SBSDKGenericDocumentRecognitionStatus","abstract":[{"text":"The status of the generic document recognition.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorUnacceptableDocument\/title"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnacceptableDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorUnacceptableDocument\/fragments"},{"value":"SBSDKGenericDocumentRecognitionStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/fragments"}]}]}