{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorUnknownDocument","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnknownDocument"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorunknowndocument"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorunknowndocument"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus"]]},"metadata":{"title":"SBSDKGenericDocumentRecognitionStatus.errorUnknownDocument","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentRecognitionStatus@SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorUnknownDocument"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"A document was detected, but it was not recognized as a supported document.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus":{"title":"SBSDKGenericDocumentRecognitionStatus","kind":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"The status of the generic document recognition."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/errorUnknownDocument":{"title":"SBSDKGenericDocumentRecognitionStatus.errorUnknownDocument","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","kind":"identifier"}],"abstract":[{"text":"A document was detected, but it was not recognized as a supported document.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/errorunknowndocument","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorUnknownDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/errorUnknownDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"SBSDKGenericDocumentRecognitionStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}]},{"op":"replace","value":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorUnknownDocument\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1errorUnknownDocument\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionStatusErrorUnknownDocument","kind":"identifier"}]}]}]}