{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"incompleteValidation","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/incompletevalidation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/incompletevalidation"]}],"metadata":{"roleHeading":"Case","title":"SBSDKGenericDocumentRecognitionStatus.incompleteValidation","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentRecognitionStatus@SBSDKGenericDocumentRecognitionStatusIncompleteValidation","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"incompleteValidation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation"}],"modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/incompleteValidation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"All fields were recognized, but some of them failed validation."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/incompleteValidation":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/incompletevalidation","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"incompleteValidation","kind":"identifier"}],"abstract":[{"type":"text","text":"All fields were recognized, but some of them failed validation."}],"title":"SBSDKGenericDocumentRecognitionStatus.incompleteValidation","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/incompleteValidation","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus","type":"topic","abstract":[{"type":"text","text":"The status of the generic document recognition."}],"kind":"symbol","role":"symbol","title":"SBSDKGenericDocumentRecognitionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1incompleteValidation\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1incompleteValidation\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusIncompleteValidation"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/title","value":"SBSDKGenericDocumentRecognitionStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}