{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"successFound","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus"]]},"abstract":[{"type":"text","text":"A document was found and can be processed further."}],"metadata":{"roleHeading":"Case","title":"SBSDKGenericDocumentRecognitionStatus.successFound","externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentRecognitionStatus@SBSDKGenericDocumentRecognitionStatusSuccessFound","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"successFound"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusSuccessFound","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/successfound"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/successfound"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/successFound","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The status of the generic document recognition."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}],"title":"SBSDKGenericDocumentRecognitionStatus","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/successFound":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/successfound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"successFound","kind":"identifier"}],"abstract":[{"text":"A document was found and can be processed further.","type":"text"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusSuccessFound","kind":"identifier"}],"type":"topic","title":"SBSDKGenericDocumentRecognitionStatus.successFound","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/successFound"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"SBSDKGenericDocumentRecognitionStatusSuccessFound","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusSuccessFound"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKGenericDocumentRecognitionStatusSuccessFound","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/title","value":"SBSDKGenericDocumentRecognitionStatus","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"op":"replace"},{"value":"SBSDKGenericDocumentRecognitionStatusSuccessFound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1successFound\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentRecognitionStatusSuccessFound","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1successFound\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}