{"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentRecognitionStatus@SBSDKGenericDocumentRecognitionStatusSuccess","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatusSuccess","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","title":"SBSDKGenericDocumentRecognitionStatus.success"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/success"},"abstract":[{"type":"text","text":"A document was found, cropped and it’s fields have been recognized."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/success"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/success"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus/success":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus\/success","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"abstract":[{"type":"text","text":"A document was found, cropped and it’s fields have been recognized."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusSuccess"}],"type":"topic","title":"SBSDKGenericDocumentRecognitionStatus.success","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus\/success"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionStatus":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionStatus","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The status of the generic document recognition."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatus"}],"title":"SBSDKGenericDocumentRecognitionStatus","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionstatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGenericDocumentRecognitionStatusSuccess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusSuccess"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusSuccess"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKGenericDocumentRecognitionStatusSuccess","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1success\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionStatusSuccess"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus~1success\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/title","value":"SBSDKGenericDocumentRecognitionStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionStatus\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}