{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CustomImage"]]},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"initWithUri:","fragments":[{"kind":"text","text":"- "},{"text":"initWithUri:","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithUri:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2CustomImage(im)initWithUri:","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2customimage\/initwithuri:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CustomImage\/initWithUri:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithUri:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uri"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CustomImage":{"title":"SBSDKUI2CustomImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CustomImage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CustomImage","kind":"identifier"}],"abstract":[{"type":"text","text":"A custom image for the introduction screen."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2customimage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CustomImage","kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CustomImage/initWithUri:":{"title":"initWithUri:","navigatorTitle":[{"text":"initWithUri:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2customimage\/initwithuri:","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUri:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CustomImage\/initWithUri:","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CustomImage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CustomImage\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CustomImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CustomImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CustomImage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CustomImage"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}