{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","externalID":"s:10ScanbotSDK21SBSDKApplicationStateO8rawValueACSgSi_tcfc","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","role":"symbol","symbolKind":"init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkapplicationstate\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/init(rawValue:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate\/init(rawvalue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState\/init(rawValue:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKApplicationState":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKApplicationState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKApplicationState","kind":"identifier"}],"title":"SBSDKApplicationState","url":"\/documentation\/scanbotsdk\/sbsdkapplicationstate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKApplicationState","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An enum describing the current state of the app."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/title","op":"replace","value":"SBSDKApplicationState"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKApplicationState"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKApplicationState\/navigatorTitle","op":"replace","value":[{"text":"SBSDKApplicationState","kind":"identifier"}]}]}]}