{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController\/create(image:polygon:)"},"kind":"symbol","metadata":{"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"createWithImage:polygon:"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController(cm)createWithImage:polygon:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"create(image:polygon:)","role":"symbol"},"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","isActive":true},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(createWithImage:polygon:) "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier","text":"SBSDKImageEditingViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The uncropped original image that is being edited."}]}]},{"name":"polygon","content":[{"type":"paragraph","inlineContent":[{"text":"The polygon used to crop the input image. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" the polygon is being auto-detected.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"reference","isActive":true},{"text":".","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/create(image:polygon:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/create(image:polygon:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"title":"SBSDKImageEditingViewController","type":"topic","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show and edit an image.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController/create(image:polygon:)":{"title":"create(image:polygon:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier","text":"SBSDKPolygon"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/create(image:polygon:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithImage:polygon:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController\/create(image:polygon:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","title":"SBSDKPolygon","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPolygon"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygon"}],"abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"createWithImage:polygon:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:polygon:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"image"},{"text":" ","kind":"text"},{"text":"polygon:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier","text":"SBSDKPolygon"},{"kind":"text","text":" *) "},{"text":"polygon","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SBSDKImageEditingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},{"value":"createWithImage:polygon:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController~1create(image:polygon:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController~1create(image:polygon:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:polygon:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPolygon"}]}]}]}