{"kind":"symbol","abstract":[{"type":"text","text":"Asks the controller to rotate input image"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"rotateInputImageClockwise(_:animated:)","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController(im)rotateInputImageClockwise:animated:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rotateInputImageClockwise","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"rotateInputImageClockwise:animated:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateInputImageClockwise"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"clockwise"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rotation direction. If set "},{"type":"codeVoice","code":"True"},{"type":"text","text":", rotates clockwise, counterclockwise otherwise."}]}],"name":"clockwise"},{"name":"animated","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"text":", animates the rotation.","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController\/rotateInputImageClockwise(_:animated:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/rotateinputimageclockwise(_:animated:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/rotateinputimageclockwise(_:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show and edit an image."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController","type":"topic","title":"SBSDKImageEditingViewController","navigatorTitle":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageEditingViewController/rotateInputImageClockwise(_:animated:)":{"kind":"symbol","navigatorTitle":[{"text":"rotateInputImageClockwise:animated:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Asks the controller to rotate input image"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageeditingviewcontroller\/rotateinputimageclockwise(_:animated:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageEditingViewController\/rotateInputImageClockwise(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rotateInputImageClockwise","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"rotateInputImageClockwise(_:animated:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"rotateInputImageClockwise:animated:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rotateInputImageClockwise:animated:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rotateInputImageClockwise:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"clockwise","kind":"internalParam"},{"kind":"text","text":" "},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rotation direction. If set "},{"type":"codeVoice","code":"True"},{"type":"text","text":", rotates clockwise, counterclockwise otherwise."}]}],"name":"clockwise"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":", animates the rotation."}]}],"name":"animated"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/title","value":"SBSDKImageEditingViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/fragments","value":[{"text":"SBSDKImageEditingViewController","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController\/navigatorTitle"},{"value":"rotateInputImageClockwise:animated:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController~1rotateInputImageClockwise(_:animated:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageEditingViewController~1rotateInputImageClockwise(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rotateInputImageClockwise:animated:"}],"op":"replace"}]}]}