{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldValue\/userFieldStringValue(value:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userFieldStringValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKUserFieldStringValue","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldStringValue","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldStringValue"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldValue"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","externalID":"s:10ScanbotSDK19SBSDKUserFieldValueC04userd6StringE05valueAA0cdgE0CSS_tFZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userFieldStringValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKUserFieldStringValue","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldStringValue"}],"title":"userFieldStringValue(value:)","role":"symbol","roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuserfieldvalue\/userfieldstringvalue(value:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldValue/userFieldStringValue(value:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldValue\/userFieldStringValue(value:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userFieldStringValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKUserFieldStringValue","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUserFieldStringValue","kind":"typeIdentifier"}],"title":"userFieldStringValue(value:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuserfieldvalue\/userfieldstringvalue(value:)","type":"topic","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldStringValue":{"url":"\/documentation\/scanbotsdk\/sbsdkuserfieldstringvalue","abstract":[{"text":"ASCII string value (TIFF_ASCII).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUserFieldStringValue"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUserFieldStringValue"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldStringValue","title":"SBSDKUserFieldStringValue","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUserFieldValue":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUserFieldValue","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUserFieldValue","abstract":[{"text":"User-defined TIFF field value.","type":"text"}],"kind":"symbol","type":"topic","title":"SBSDKUserFieldValue","url":"\/documentation\/scanbotsdk\/sbsdkuserfieldvalue","role":"symbol","navigatorTitle":[{"text":"SBSDKUserFieldValue","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUserFieldStringValue","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldStringValue\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUserFieldStringValue"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldStringValue\/fragments","op":"replace"},{"value":[{"text":"SBSDKUserFieldStringValue","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldStringValue\/navigatorTitle","op":"replace"},{"value":"SBSDKUserFieldValue","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldValue\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUserFieldValue"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldValue\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUserFieldValue"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUserFieldValue\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}