{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDetectionResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDetectionResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult(py)documentDetectionResult","title":"documentDetectionResult","navigatorTitle":[{"text":"documentDetectionResult","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult\/documentdetectionresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult\/documentdetectionresult"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Result of the document detection in the input image."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult\/documentDetectionResult"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionResult":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult","type":"topic","title":"SBSDKDocumentDataExtractionResult","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"role":"symbol","abstract":[{"type":"text","text":"Contains the result of running the document data extractor."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","kind":"symbol","abstract":[{"type":"text","text":"Result of the document contour detection."}],"role":"symbol","title":"SBSDKDocumentDetectionResult","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionResult/documentDetectionResult":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDetectionResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"documentDetectionResult","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult\/documentDetectionResult","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult\/documentdetectionresult","title":"documentDetectionResult","abstract":[{"text":"Result of the document detection in the input image.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"documentDetectionResult","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"documentDetectionResult"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"},{"text":" * ","kind":"text"},{"text":"documentDetectionResult","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKDocumentDataExtractionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","op":"replace"},{"value":"documentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult~1documentDetectionResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"documentDetectionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult~1documentDetectionResult\/fragments","op":"replace"}]}]}