{"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKPageFit.none","symbolKind":"case","navigatorTitle":[{"text":"SBSDKPageFitNone","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKPageFit@SBSDKPageFitNone","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]},"abstract":[{"text":"No resizing, centers the image on the page. The physical size of the image","type":"text"},{"text":" ","type":"text"},{"text":"will be determined by the ","type":"text"},{"code":"dpi","type":"codeVoice"},{"text":" parameter.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/none","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpagefit\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpagefit\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit":{"abstract":[{"type":"text","text":"Page fit."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageFit","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagefit","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","navigatorTitle":[{"text":"SBSDKPageFit","kind":"identifier"}],"title":"SBSDKPageFit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit/none":{"title":"SBSDKPageFit.none","abstract":[{"type":"text","text":"No resizing, centers the image on the page. The physical size of the image"},{"type":"text","text":" "},{"type":"text","text":"will be determined by the "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" parameter."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPageFitNone","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagefit\/none","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/none","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKPageFitNone","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKPageFitNone","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKPageFitNone","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKPageFit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/title"},{"op":"replace","value":[{"text":"SBSDKPageFit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/fragments"},{"op":"replace","value":[{"text":"SBSDKPageFit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/navigatorTitle"},{"op":"replace","value":"SBSDKPageFitNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit~1none\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPageFitNone"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit~1none\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}