{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"SBSDKPageFitStretch","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKPageFit@SBSDKPageFitStretch","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stretch","kind":"identifier"}],"symbolKind":"case","title":"SBSDKPageFit.stretch","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stretch","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/stretch","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagefit\/stretch"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagefit\/stretch"]}],"sections":[],"abstract":[{"text":"Stretch image to fill the entire page. The image will never be cropped","type":"text"},{"text":" ","type":"text"},{"text":"and there will never be any white borders left, but the image aspect ratio","type":"text"},{"text":" ","type":"text"},{"text":"will be made to match the page aspect ratio.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit":{"abstract":[{"type":"text","text":"Page fit."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageFit","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagefit","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","navigatorTitle":[{"text":"SBSDKPageFit","kind":"identifier"}],"title":"SBSDKPageFit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit/stretch":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/stretch","abstract":[{"type":"text","text":"Stretch image to fill the entire page. The image will never be cropped"},{"type":"text","text":" "},{"type":"text","text":"and there will never be any white borders left, but the image aspect ratio"},{"type":"text","text":" "},{"type":"text","text":"will be made to match the page aspect ratio."}],"url":"\/documentation\/scanbotsdk\/sbsdkpagefit\/stretch","role":"symbol","navigatorTitle":[{"text":"SBSDKPageFitStretch","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stretch","kind":"identifier"}],"title":"SBSDKPageFit.stretch"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKPageFitStretch","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKPageFitStretch","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKPageFitStretch","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKPageFit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/title","op":"replace"},{"value":[{"text":"SBSDKPageFit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPageFit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit~1stretch\/title","op":"replace","value":"SBSDKPageFitStretch"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit~1stretch\/fragments","op":"replace","value":[{"text":"SBSDKPageFitStretch","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}