{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration\/init(imagevisible:titleselected:subtitleselected:titledeselected:subtitledeselected:backgroundselected:backgrounddeselected:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration\/init(imagevisible:titleselected:subtitleselected:titledeselected:subtitledeselected:backgroundselected:backgrounddeselected:)"]}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Initializer","title":"init(imageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:)","symbolKind":"init","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration(im)initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"titleSelected","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"text":"subtitleSelected","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"text":"titleDeselected","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subtitleDeselected"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"backgroundSelected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle"},{"text":", ","kind":"text"},{"text":"backgroundDeselected","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2PolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration\/init(imageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"imageVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"titleSelected"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" = SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                            isArgb: false)), "},{"kind":"externalParam","text":"subtitleSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                          color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                               isArgb: false)), ","kind":"text"},{"text":"titleDeselected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                              isArgb: false)), "},{"text":"subtitleDeselected","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2StyledText(text: \"BARCODE_SUBTITLE\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                 isArgb: false)), "},{"text":"backgroundSelected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle"},{"kind":"text","text":" = SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\", isArgb: false),\n                                         fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                  isArgb: false),\n                                         strokeWidth: 0.0, cornerRadius: 10.0), "},{"text":"backgroundDeselected","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle"},{"text":" = SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                         fillColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                  isArgb: false),\n                                         strokeWidth: 0.0, cornerRadius: 10.0))","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration","abstract":[{"text":"Configuration of the barcode info box displayed in the camera preview.","type":"text"}],"type":"topic","title":"SBSDKUI2BarcodeItemConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"title":"SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemConfiguration/init(imageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemconfiguration\/init(imagevisible:titleselected:subtitleselected:titledeselected:subtitledeselected:backgroundselected:backgrounddeselected:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"titleSelected","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"text":"subtitleSelected","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"titleDeselected"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"text":"subtitleDeselected","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"backgroundSelected"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"backgroundDeselected","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemConfiguration\/init(imageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:)","title":"init(imageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:)","navigatorTitle":[{"text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PolygonStyle":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"abstract":[{"text":"Configuration of the polygon appearance.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2polygonstyle","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PolygonStyle","title":"SBSDKUI2PolygonStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithImageVisible:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleSelected:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"titleSelected","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtitleSelected:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"subtitleSelected","kind":"internalParam"},{"kind":"text","text":" "},{"text":"titleDeselected:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"titleDeselected","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"subtitleDeselected:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"subtitleDeselected","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundSelected:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PolygonStyle","kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundSelected"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundDeselected:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"backgroundDeselected","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/title","value":"SBSDKUI2BarcodeItemConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration~1init(imageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:)\/title","value":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemConfiguration~1init(imageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:"}]},{"value":"SBSDKUI2PolygonStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PolygonStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PolygonStyle\/fragments","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PolygonStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"op":"replace"}]}]}