{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"devicePrefersUltraWideCamera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdeviceinformation\/deviceprefersultrawidecamera"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdeviceinformation\/deviceprefersultrawidecamera"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceInformation\/devicePrefersUltraWideCamera","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"type":"text","text":" if the device works better with the ultra-wide camera instead of the standard camera."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"devicePrefersUltraWideCamera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"devicePrefersUltraWideCamera","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDeviceInformation(cpy)devicePrefersUltraWideCamera","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"devicePrefersUltraWideCamera"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceInformation"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDeviceInformation":{"role":"symbol","title":"SBSDKDeviceInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDeviceInformation"}],"abstract":[{"type":"text","text":"Helper class that delivers information about the used iOS device."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDeviceInformation"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdeviceinformation"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDeviceInformation/devicePrefersUltraWideCamera":{"role":"symbol","title":"devicePrefersUltraWideCamera","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"devicePrefersUltraWideCamera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"True"},{"type":"text","text":" if the device works better with the ultra-wide camera instead of the standard camera."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDeviceInformation\/devicePrefersUltraWideCamera","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"devicePrefersUltraWideCamera"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdeviceinformation\/deviceprefersultrawidecamera"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"devicePrefersUltraWideCamera"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"devicePrefersUltraWideCamera"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"devicePrefersUltraWideCamera"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation\/title","value":"SBSDKDeviceInformation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation\/fragments","value":[{"kind":"identifier","text":"SBSDKDeviceInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation~1devicePrefersUltraWideCamera\/title","value":"devicePrefersUltraWideCamera"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDeviceInformation~1devicePrefersUltraWideCamera\/fragments","value":[{"kind":"identifier","text":"devicePrefersUltraWideCamera"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}