{"abstract":[{"type":"text","text":"Text, that is used as an accessibility label for the page-amount button."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pageCounterButtonAccessibilityLabel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to “%d photos”, to voice the amount of scans taken.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration"]]},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/pagecounterbuttonaccessibilitylabel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/pagecounterbuttonaccessibilitylabel"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerAccessibilityConfiguration(py)pageCounterButtonAccessibilityLabel","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageCounterButtonAccessibilityLabel"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"pageCounterButtonAccessibilityLabel","symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"pageCounterButtonAccessibilityLabel"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/pageCounterButtonAccessibilityLabel"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerAccessibilityConfiguration/pageCounterButtonAccessibilityLabel":{"type":"topic","title":"pageCounterButtonAccessibilityLabel","kind":"symbol","deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageCounterButtonAccessibilityLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/pagecounterbuttonaccessibilitylabel","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/pageCounterButtonAccessibilityLabel","navigatorTitle":[{"text":"pageCounterButtonAccessibilityLabel","kind":"identifier"}],"abstract":[{"type":"text","text":"Text, that is used as an accessibility label for the page-amount button."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerAccessibilityConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerAccessibilityConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"kind":"symbol","title":"SBSDKUIDocumentScannerAccessibilityConfiguration","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration","deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pageCounterButtonAccessibilityLabel","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"pageCounterButtonAccessibilityLabel","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"pageCounterButtonAccessibilityLabel"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1pageCounterButtonAccessibilityLabel\/title","value":"pageCounterButtonAccessibilityLabel","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"pageCounterButtonAccessibilityLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1pageCounterButtonAccessibilityLabel\/fragments"},{"op":"replace","value":"SBSDKUIDocumentScannerAccessibilityConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/title"},{"value":[{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/navigatorTitle"}]}]}