{"kind":"symbol","abstract":[{"type":"text","text":"The drawing style of the finder view."}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration\/style","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/style"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/style"]}],"metadata":{"title":"style","navigatorTitle":[{"kind":"identifier","text":"style"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(py)style","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView"},{"text":".","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum","kind":"typeIdentifier","text":"Style"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/stroke","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"title":"SBSDKFinderView","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewStyle":{"abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}],"url":"\/documentation\/scanbotsdk\/sbsdkfinderviewstyle","title":"SBSDKFinderViewStyle","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"SBSDKFinderViewStyle"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewFinderConfiguration/style":{"title":"style","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKFinderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO","text":"Style","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"style","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration\/style","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration\/style","kind":"symbol","abstract":[{"type":"text","text":"The drawing style of the finder view."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}],"title":"SBSDKFinderView.Style","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum","navigatorTitle":[{"text":"Style","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum/stroke":{"kind":"symbol","abstract":[{"type":"text","text":"The full line around the finder view."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/stroke","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stroke"}],"title":"SBSDKFinderView.Style.stroke","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/stroke"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewFinderConfiguration":{"title":"SBSDKBaseScannerViewFinderConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewFinderConfiguration","abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"text":" ","type":"text"},{"text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in."},{"type":"text","text":" "},{"type":"text","text":"It crops the video frame to that region of interest before passing it to any scanner. Usually"},{"type":"text","text":" "},{"text":"the performance of scanners gain a benefit from it because less pixels must be processed.","type":"text"},{"text":" ","type":"text"},{"text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around","type":"text"},{"text":" ","type":"text"},{"text":"on the user interface.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewfinderconfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"style"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"style","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewStyle","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKFinderViewStyle","text":"SBSDKFinderViewStyle","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","value":[{"text":"SBSDKFinderView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration~1style\/title","value":"style"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration~1style\/fragments","value":[{"text":"style","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration\/title","value":"SBSDKBaseScannerViewFinderConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}]},{"op":"replace","value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle"}]}]}