{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeFull"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingDecodeFull","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUI2Gs1Handling.decodeFull","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeFull"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling@SBSDKUI2Gs1HandlingDecodeFull"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/decodefull"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/decodefull"]}],"abstract":[{"type":"text","text":"Same as DECODE_STRUCTURE, but with full validation."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeFull","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/decodeFull":{"title":"SBSDKUI2Gs1Handling.decodeFull","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/decodeFull","abstract":[{"text":"Same as DECODE_STRUCTURE, but with full validation.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/decodefull","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFull"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingDecodeFull","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling","navigatorTitle":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"title":"SBSDKUI2Gs1Handling","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUI2Gs1HandlingDecodeFull","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2Gs1HandlingDecodeFull","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeFull"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SBSDKUI2Gs1HandlingDecodeFull","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1decodeFull\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingDecodeFull"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1decodeFull\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/title","value":"SBSDKUI2Gs1Handling"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/navigatorTitle","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}