{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/none"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","title":"SBSDKUI2Gs1Handling.none","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingNone"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling@SBSDKUI2Gs1HandlingNone"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling"]]},"sections":[],"abstract":[{"type":"text","text":"The (FNC1) character is simply stripped from the result in barcodes that implement this mode. Do not use. Will"},{"type":"text","text":" "},{"type":"text","text":"be removed in a future release."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/none"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","type":"topic","abstract":[{"text":"GS1_COMPOSITE barcode type handling","type":"text"}],"title":"SBSDKUI2Gs1Handling","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/none":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingNone","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/none","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/none","title":"SBSDKUI2Gs1Handling.none","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The (FNC1) character is simply stripped from the result in barcodes that implement this mode. Do not use. Will"},{"type":"text","text":" "},{"type":"text","text":"be removed in a future release."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKUI2Gs1HandlingNone","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2Gs1HandlingNone","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingNone"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/title","value":"SBSDKUI2Gs1Handling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/fragments","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},{"value":"SBSDKUI2Gs1HandlingNone","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1none\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingNone"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1none\/fragments","op":"replace"}]}]}