{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/validate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/validate"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validate"},"abstract":[{"text":"GS1 messages are converted to machine-readable format per the GS1 spec (the special character is converted to","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"ASCII \\x1D) and validated. The implied 01 AI key is prepended to DataBar results. Invalid messages are not"},{"type":"text","text":" "},{"type":"text","text":"returned."}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKUI2Gs1Handling.validate","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling@SBSDKUI2Gs1HandlingValidate","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidate"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling/validate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling\/validate","title":"SBSDKUI2Gs1Handling.validate","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling\/validate","abstract":[{"text":"GS1 messages are converted to machine-readable format per the GS1 spec (the special character is converted to","type":"text"},{"type":"text","text":" "},{"text":"ASCII \\x1D) and validated. The implied 01 AI key is prepended to DataBar results. Invalid messages are not","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"returned."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"title":"SBSDKUI2Gs1Handling","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","navigatorTitle":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKUI2Gs1HandlingValidate","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingValidate"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKUI2Gs1HandlingValidate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1validate\/title","value":"SBSDKUI2Gs1HandlingValidate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling~1validate\/fragments","value":[{"text":"SBSDKUI2Gs1HandlingValidate","kind":"identifier"}]},{"value":"SBSDKUI2Gs1Handling","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}]}]}]}