{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonEdgeOrientation"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonEdgeOrientation\/vertical","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"vertical","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The edge is oriented vertically."}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"vertical","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientationVertical","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKPolygonEdgeOrientation@SBSDKPolygonEdgeOrientationVertical","symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","roleHeading":"Case","title":"SBSDKPolygonEdgeOrientation.vertical"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygonedgeorientation\/vertical"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygonedgeorientation\/vertical"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygonEdgeOrientation":{"navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"kind":"symbol","title":"SBSDKPolygonEdgeOrientation","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygonedgeorientation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonEdgeOrientation"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygonEdgeOrientation/vertical":{"navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientationVertical","kind":"identifier"}],"title":"SBSDKPolygonEdgeOrientation.vertical","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"vertical","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygonedgeorientation\/vertical","abstract":[{"type":"text","text":"The edge is oriented vertically."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygonEdgeOrientation\/vertical"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"SBSDKPolygonEdgeOrientationVertical","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKPolygonEdgeOrientationVertical","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKPolygonEdgeOrientationVertical","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonEdgeOrientation\/title","value":"SBSDKPolygonEdgeOrientation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonEdgeOrientation\/fragments","value":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientation"}],"op":"replace"},{"value":"SBSDKPolygonEdgeOrientationVertical","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonEdgeOrientation~1vertical\/title"},{"op":"replace","value":[{"text":"SBSDKPolygonEdgeOrientationVertical","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygonEdgeOrientation~1vertical\/fragments"}]}]}