{"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"role":"symbol","symbolKind":"case","title":"SBSDKOrientationLock.none","externalID":"c:@M@ScanbotSDK@E@SBSDKOrientationLock@SBSDKOrientationLockNone","navigatorTitle":[{"kind":"identifier","text":"SBSDKOrientationLockNone"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The orientation is not locked. The captured image is orientated so that the upper area of the image is directed towards the status bar."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkorientationlock\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkorientationlock\/none"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock\/none","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The image either has a landscape or portrait aspect ratio."}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOrientationLock":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOrientationLock","kind":"identifier"}],"title":"SBSDKOrientationLock","abstract":[{"type":"text","text":"This enum describes the available orientation lock modes for the user interface."}],"url":"\/documentation\/scanbotsdk\/sbsdkorientationlock","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","type":"topic","navigatorTitle":[{"text":"SBSDKOrientationLock","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOrientationLock/none":{"kind":"symbol","abstract":[{"type":"text","text":"The orientation is not locked. The captured image is orientated so that the upper area of the image is directed towards the status bar."}],"title":"SBSDKOrientationLock.none","navigatorTitle":[{"kind":"identifier","text":"SBSDKOrientationLockNone"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock\/none","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkorientationlock\/none"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKOrientationLockNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKOrientationLockNone"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKOrientationLockNone","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/title","value":"SBSDKOrientationLock","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/fragments","value":[{"kind":"identifier","text":"SBSDKOrientationLock"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKOrientationLock"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock~1none\/title","value":"SBSDKOrientationLockNone"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock~1none\/fragments","value":[{"kind":"identifier","text":"SBSDKOrientationLockNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}