{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"roleHeading":"Enumeration","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKVideoOrientation","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoOrientation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"role":"symbol","symbolKind":"enum"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/landscapeLeft","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/landscapeRight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/portrait","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/portraitUpsideDown"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/angle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/isLandscape","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/isPortrait"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"An enum describing the orientation of a video frame.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/portraitUpsideDown":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/portraitupsidedown","type":"topic","navigatorTitle":[{"text":"SBSDKVideoOrientationPortraitUpsideDown","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/portraitUpsideDown","kind":"symbol","title":"SBSDKVideoOrientation.portraitUpsideDown","abstract":[{"text":"Portrait upside down orientation.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"portraitUpsideDown","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/landscapeLeft":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/landscapeLeft","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscapeLeft","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVideoOrientationLandscapeLeft","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/landscapeleft","abstract":[{"text":"Landscape left orientation.","type":"text"}],"title":"SBSDKVideoOrientation.landscapeLeft"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/landscapeRight":{"title":"SBSDKVideoOrientation.landscapeRight","abstract":[{"text":"Landscape right orientation.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/landscaperight","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeRight"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/landscapeRight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeRight"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","kind":"article","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/RawRepresentable-Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/rawrepresentable-implementations","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/isLandscape":{"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the receiver is either landscape left or landscape right, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/islandscape","role":"symbol","type":"topic","title":"isLandscape","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLandscape"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/isLandscape"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/portrait":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/portrait","abstract":[{"type":"text","text":"Portrait orientation."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"portrait"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/portrait","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationPortrait"}],"title":"SBSDKVideoOrientation.portrait"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/isPortrait":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPortrait"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/isPortrait","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/isportrait","type":"topic","abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the receiver is either portrait or portrait upside down, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"title":"isPortrait"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation":{"title":"SBSDKVideoOrientation","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}],"navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/init(rawvalue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/init(rawValue:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/angle":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/angle","kind":"symbol","title":"angle","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/angle","abstract":[{"text":"Returns the counter-clockwise angle of the orientation in degrees, with portrait equaling 90 degrees.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"angle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVideoOrientation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/landscapeLeft","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/landscapeRight","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/portrait","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/portraitUpsideDown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1portraitUpsideDown\/title","value":"SBSDKVideoOrientationPortraitUpsideDown"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1portraitUpsideDown\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoOrientationPortraitUpsideDown"}]},{"value":"SBSDKVideoOrientationLandscapeLeft","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1landscapeLeft\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1landscapeLeft\/fragments","value":[{"text":"SBSDKVideoOrientationLandscapeLeft","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1landscapeRight\/title","value":"SBSDKVideoOrientationLandscapeRight"},{"value":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeRight"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1landscapeRight\/fragments","op":"replace"},{"value":"SBSDKVideoOrientationPortrait","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1portrait\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKVideoOrientationPortrait","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1portrait\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/title","value":"SBSDKVideoOrientation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}