{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/componentUnavailable","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/illegalState","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidArgument","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidData","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidImageRef","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidLicense","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/ioError","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/nullPointer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/operationCanceled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/outOfMemory","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/timeout","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/unknownError"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKErrorType","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorType","kind":"identifier"}],"role":"symbol","title":"SBSDKErrorType"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKErrorType","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK.","type":"text"},{"text":" ","type":"text"},{"text":"Each case corresponds to a specific error code.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/init(rawValue:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/init(rawvalue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/invalidArgument":{"title":"SBSDKErrorType.invalidArgument","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/invalidargument","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidArgument"}],"abstract":[{"text":"An invalid argument was passed to an SDK function or method.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidArgument","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidArgument"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/componentUnavailable":{"type":"topic","kind":"symbol","abstract":[{"text":"A required SDK component is unavailable or not properly initialized.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/componentunavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"componentUnavailable"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/componentUnavailable","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeComponentUnavailable"}],"role":"symbol","title":"SBSDKErrorType.componentUnavailable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}],"abstract":[{"type":"text","text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK."},{"type":"text","text":" "},{"type":"text","text":"Each case corresponds to a specific error code."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"title":"SBSDKErrorType","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/invalidLicense":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidLicense"}],"abstract":[{"type":"text","text":"The SDK license is invalid or license requirements are not satisfied."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidLicense"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/invalidlicense","title":"SBSDKErrorType.invalidLicense","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidLicense","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/illegalState":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/illegalState","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeIllegalState"}],"abstract":[{"text":"The SDK is in an illegal or inconsistent state for the requested operation.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"illegalState"}],"title":"SBSDKErrorType.illegalState","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/illegalstate","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/nullPointer":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nullPointer"}],"abstract":[{"text":"A null pointer was encountered where a valid reference was expected.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeNullPointer"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/nullpointer","title":"SBSDKErrorType.nullPointer","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/nullPointer","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/unknownError":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"abstract":[{"type":"text","text":"An unknown or unexpected error occurred."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeUnknownError"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/unknownerror","title":"SBSDKErrorType.unknownError","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/unknownError","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/outOfMemory":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outOfMemory"}],"abstract":[{"type":"text","text":"The system ran out of memory during the operation."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeOutOfMemory"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/outofmemory","title":"SBSDKErrorType.outOfMemory","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/outOfMemory","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/ioError":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/ioerror","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/ioError","abstract":[{"text":"An input\/output error occurred during file or data operations.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ioError"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeIoError"}],"title":"SBSDKErrorType.ioError","role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/timeout":{"type":"topic","abstract":[{"type":"text","text":"The operation timed out before completion."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/timeout","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/timeout","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeTimeout"}],"title":"SBSDKErrorType.timeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/invalidData":{"type":"topic","abstract":[{"text":"The provided data is invalid, corrupted, or in an unexpected format.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/invaliddata","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidData"}],"title":"SBSDKErrorType.invalidData","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidData"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/Equatable-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/equatable-implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/operationCanceled":{"abstract":[{"type":"text","text":"The operation was canceled before completion or by user."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/operationCanceled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeOperationCanceled"}],"title":"SBSDKErrorType.operationCanceled","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/operationcanceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operationCanceled"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/invalidImageRef":{"title":"SBSDKErrorType.invalidImageRef","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/invalidimageref","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeInvalidImageRef"}],"abstract":[{"type":"text","text":"An invalid image reference was provided or the image data is corrupted."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidImageRef","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidImageRef"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorType/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrortype\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/RawRepresentable-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKErrorType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKErrorType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKErrorType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/componentUnavailable","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/illegalState","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidArgument","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidData","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidImageRef","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/invalidLicense","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/ioError","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/nullPointer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/operationCanceled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/outOfMemory","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/timeout","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorType\/unknownError"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKErrorTypeInvalidArgument","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1invalidArgument\/title"},{"op":"replace","value":[{"text":"SBSDKErrorTypeInvalidArgument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1invalidArgument\/fragments"},{"op":"replace","value":"SBSDKErrorTypeComponentUnavailable","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1componentUnavailable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorTypeComponentUnavailable"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1componentUnavailable\/fragments"},{"op":"replace","value":"SBSDKErrorType","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType\/title"},{"op":"replace","value":[{"text":"SBSDKErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType\/fragments"},{"op":"replace","value":[{"text":"SBSDKErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType\/navigatorTitle"},{"op":"replace","value":"SBSDKErrorTypeInvalidLicense","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1invalidLicense\/title"},{"op":"replace","value":[{"text":"SBSDKErrorTypeInvalidLicense","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1invalidLicense\/fragments"},{"op":"replace","value":"SBSDKErrorTypeIllegalState","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1illegalState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorTypeIllegalState"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1illegalState\/fragments"},{"op":"replace","value":"SBSDKErrorTypeNullPointer","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1nullPointer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorTypeNullPointer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1nullPointer\/fragments"},{"op":"replace","value":"SBSDKErrorTypeUnknownError","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1unknownError\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorTypeUnknownError"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1unknownError\/fragments"},{"op":"replace","value":"SBSDKErrorTypeOutOfMemory","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1outOfMemory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorTypeOutOfMemory"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1outOfMemory\/fragments"},{"op":"replace","value":"SBSDKErrorTypeIoError","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1ioError\/title"},{"op":"replace","value":[{"text":"SBSDKErrorTypeIoError","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1ioError\/fragments"},{"op":"replace","value":"SBSDKErrorTypeTimeout","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1timeout\/title"},{"op":"replace","value":[{"text":"SBSDKErrorTypeTimeout","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1timeout\/fragments"},{"op":"replace","value":"SBSDKErrorTypeInvalidData","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1invalidData\/title"},{"op":"replace","value":[{"text":"SBSDKErrorTypeInvalidData","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1invalidData\/fragments"},{"op":"replace","value":"SBSDKErrorTypeOperationCanceled","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1operationCanceled\/title"},{"op":"replace","value":[{"text":"SBSDKErrorTypeOperationCanceled","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1operationCanceled\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1invalidImageRef\/title","op":"replace","value":"SBSDKErrorTypeInvalidImageRef"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorType~1invalidImageRef\/fragments","op":"replace","value":[{"text":"SBSDKErrorTypeInvalidImageRef","kind":"identifier"}]}]}]}