{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/init()"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/accumulationDuration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/allowPartiallyVisibleDocuments","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/minimumBrightness","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/retentionTime"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/toJson(configuration:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKPartiallyVisibleDocumentConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration","title":"SBSDKPartiallyVisibleDocumentConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"role":"symbol","symbolKind":"class","roleHeading":"Class"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"]}],"abstract":[{"text":"Configuration for handling partially visible documents.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration","title":"SBSDKPartiallyVisibleDocumentConfiguration","abstract":[{"type":"text","text":"Configuration for handling partially visible documents."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/init()":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/init()","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"title":"NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/isEqual:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/isequal:","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/isEqual:","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/hash":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/hash","role":"symbol","title":"hash","kind":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/hash","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/accumulationDuration":{"abstract":[{"type":"text","text":"Duration in milliseconds over which the document has to be detected as partially visible. If on any frame the"},{"type":"text","text":" "},{"type":"text","text":"document is not detected as partially visible, or detected as having a completely different Displacement, the"},{"type":"text","text":" "},{"type":"text","text":"accumulation will be reset. During the accumulation, the document scanner will return a status of"},{"type":"text","text":" "},{"type":"text","text":"ERROR_NOTHING_DETECTED instead of one of the partially visible statuses. Set to 0 to disable this behavior."}],"title":"accumulationDuration","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accumulationDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"accumulationDuration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/accumulationDuration","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/accumulationduration"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/minimumBrightness":{"abstract":[{"type":"text","text":"Minimum brightness of a partially visible potential document. Increasing this value can reduce the number"},{"type":"text","text":" "},{"type":"text","text":"of spurious detections."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumBrightness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minimumBrightness","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/minimumbrightness","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/minimumBrightness","role":"symbol","title":"minimumBrightness","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/retentionTime":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/retentionTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retentionTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/retentiontime","navigatorTitle":[{"kind":"identifier","text":"retentionTime"}],"abstract":[{"text":"Time in milliseconds during which the detection status ERROR_NOTHING_DETECTED is changed to","type":"text"},{"text":" ","type":"text"},{"text":"ERROR_PARTIALLY_VISIBLE_TOO_CLOSE if no document was detected following the detection of a partially visible","type":"text"},{"text":" ","type":"text"},{"text":"document. Set to 0 to disable this behavior.","type":"text"}],"title":"retentionTime","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/toJson(configuration:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/toJson(configuration:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/tojson(configuration:)","title":"toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","title":"fromJsonWithJson:","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/fromJsonWithJson:"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/allowPartiallyVisibleDocuments":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/allowpartiallyvisibledocuments","type":"topic","role":"symbol","abstract":[{"type":"text","text":"If true, the document scanner will return a status of ERROR_PARTIALLY_VISIBLE or ERROR_PARTIALLY_VISIBLE_TOO_CLOSE"},{"type":"text","text":" "},{"type":"text","text":"if a document-like shape is detected, but not all four corners of the document are visible."},{"type":"text","text":" "},{"type":"text","text":"If false, a status of ERROR_NOTHING_DETECTED will be returned instead."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/allowPartiallyVisibleDocuments","navigatorTitle":[{"kind":"identifier","text":"allowPartiallyVisibleDocuments"}],"kind":"symbol","title":"allowPartiallyVisibleDocuments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPartiallyVisibleDocuments"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/copyWithZone:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/copywithzone:","kind":"symbol","title":"copyWithZone:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/copyWithZone:","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","role":"symbol","navigatorTitle":[{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/initwithallowpartiallyvisibledocuments:accumulationduration:retentiontime:minimumbrightness:","title":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPartiallyVisibleDocumentConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/accumulationDuration","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/allowPartiallyVisibleDocuments","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/hash","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/minimumBrightness","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/retentionTime"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/init()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/toJson(configuration:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/fromJsonWithJson:"],"title":"Type Methods","anchor":"Type-Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title","op":"replace","value":"SBSDKPartiallyVisibleDocumentConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1accumulationDuration\/title","value":"accumulationDuration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1accumulationDuration\/fragments","value":[{"kind":"identifier","text":"accumulationDuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1minimumBrightness\/title","value":"minimumBrightness","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1minimumBrightness\/fragments","value":[{"kind":"identifier","text":"minimumBrightness"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1retentionTime\/title","value":"retentionTime","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1retentionTime\/fragments","value":[{"text":"retentionTime","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1toJson(configuration:)\/fragments"},{"value":"allowPartiallyVisibleDocuments","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1allowPartiallyVisibleDocuments\/title"},{"value":[{"text":"allowPartiallyVisibleDocuments","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1allowPartiallyVisibleDocuments\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}