{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"symbolKind":"enum","title":"SBSDKImageSerializationMode","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageSerializationMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}]},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/buffer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/reference"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKImageSerializationMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Image serialization mode. Applicable only when serializeImages is true."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode"]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"kind":"relationships"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSerializationMode/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/Equatable-Implementations","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode\/equatable-implementations","title":"Equatable Implementations","kind":"article","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSerializationMode/reference":{"navigatorTitle":[{"text":"SBSDKImageSerializationModeReference","kind":"identifier"}],"abstract":[{"type":"text","text":"Images are serialized as references to native resources."}],"role":"symbol","title":"SBSDKImageSerializationMode.reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/reference","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode\/reference","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reference","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSerializationMode/init(rawValue:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSerializationMode/buffer":{"abstract":[{"type":"text","text":"Images are serialized as base64 encoded buffers."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"buffer"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/buffer","title":"SBSDKImageSerializationMode.buffer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationModeBuffer"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode\/buffer"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSerializationMode/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSerializationMode":{"role":"symbol","abstract":[{"text":"Image serialization mode. Applicable only when serializeImages is true.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode","type":"topic","title":"SBSDKImageSerializationMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageserializationmode","navigatorTitle":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s12CaseIterableP","title":"Swift.CaseIterable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageSerializationMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/buffer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSerializationMode\/reference"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSerializationMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode~1reference\/title","value":"SBSDKImageSerializationModeReference"},{"value":[{"text":"SBSDKImageSerializationModeReference","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode~1reference\/fragments"},{"value":"SBSDKImageSerializationModeBuffer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode~1buffer\/title"},{"value":[{"text":"SBSDKImageSerializationModeBuffer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode~1buffer\/fragments"},{"value":"SBSDKImageSerializationMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSerializationMode\/navigatorTitle"}]}]}