{"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/init(feature:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/init(feature:device:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureSession","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/device","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/exposureSettings","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isCameraAdjusting","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isCapturingStillImage","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isFocusLockEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isFrontCameraUsed","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isMirrored","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isScanningPaused","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isSessionRunning","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isTorchLightAvailable","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isTorchLightEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isZoomAvailable","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isZooming","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/keepAliveTimeout","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/maxOpticalZoom","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/maxZoom","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/minZoom","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/photoQualityPrioritization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/previewLayer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/updateTorchlightBlock","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/updateZoomBlock","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoContentMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoFrameResolution","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoOrientation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoResolution","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/zoomValue"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/addSessionObserver(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/beginFocusLock(at:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureStillImage(completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/endFocusLock()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/freezeSession()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/observeValue(forKeyPath:of:change:context:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/pauseScanning()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/removeSessionObserver(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/resetZoom(animated:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/resumeScanning()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/setPreviewLayerVisible(_:animated:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/setZoom(_:animated:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/start()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/stop(keepAlive:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/unfreezeSession()"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8CopyableP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo"}],"abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"SBSDKCameraSession","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"roleHeading":"Class"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/init(feature:)":{"kind":"symbol","abstract":[{"type":"text","text":"The designated initializer of the class. Does not start the capture session."}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKFeature","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKFeature","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/init(feature:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/init(feature:)","title":"init(feature:)","navigatorTitle":[{"text":"initWithFeature:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/setZoom(_:animated:)":{"kind":"symbol","type":"topic","title":"setZoom(_:animated:)","abstract":[{"type":"text","text":"Sets the camera devices current zoom factor."},{"type":"text","text":" "},{"type":"text","text":"If the new value exceeds the minimum or maximum value for zooming it is clamped."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/setzoom(_:animated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setZoom","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setZoomValue:animated:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/setZoom(_:animated:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/init(feature:device:)":{"type":"topic","title":"init(feature:device:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/init(feature:device:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/init(feature:device:)","abstract":[{"text":"Convenience initializer of the class. Does not start the capture session.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKFeature","kind":"typeIdentifier","text":"SBSDKFeature"},{"kind":"text","text":", "},{"kind":"externalParam","text":"device"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraDevice","kind":"typeIdentifier","text":"SBSDKCameraDevice"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFeature:device:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/updateZoomBlock":{"kind":"symbol","navigatorTitle":[{"text":"updateZoomBlock","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/updateZoomBlock","role":"symbol","abstract":[{"type":"text","text":"A block being executed when the zoom factor has changed. The new zoom factor is provided as parameter."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/updatezoomblock","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateZoomBlock","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ())?","kind":"text"}],"title":"updateZoomBlock"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isTorchLightAvailable":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchLightAvailable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/istorchlightavailable","kind":"symbol","title":"isTorchLightAvailable","navigatorTitle":[{"text":"isTorchLightAvailable","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isTorchLightAvailable","role":"symbol","type":"topic","abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the camera device has a torch light and the torch light is available, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/keepAliveTimeout":{"navigatorTitle":[{"kind":"identifier","text":"keepAliveTimeout"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keepAliveTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/keepalivetimeout","type":"topic","abstract":[{"type":"text","text":"The time the session is kept alive after stopping it."},{"text":" ","type":"text"},{"text":"If the session is stopped and then re-started while it is still alive it will be much faster ready than when being completely restarted.","type":"text"},{"text":" ","type":"text"},{"text":"The default value is 1 second.","type":"text"},{"text":" ","type":"text"},{"text":"Negative values will result in a fatal error. Values close to 0 may lead to issues when starting and stopping the session multiple times quickly.","type":"text"}],"title":"keepAliveTimeout","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/keepAliveTimeout"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/resumeScanning()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"resumeScanning"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/resumescanning()","abstract":[{"type":"text","text":"Resumes the delivery of frames to the delegate."}],"title":"resumeScanning()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/resumeScanning()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resumeScanning"},{"kind":"text","text":"()"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","title":"AVCaptureVideoDataOutputSampleBufferDelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/endFocusLock()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"endFocusLock"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/endfocuslock()","title":"endFocusLock()","kind":"symbol","abstract":[{"type":"text","text":"Ends the focus lock and returns to standard continous auto-focus."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/endFocusLock()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endFocusLock"},{"kind":"text","text":"()"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isZooming":{"title":"isZooming","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isZooming","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isZooming","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isZooming","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/iszooming","type":"topic","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":", if the camera currently is zooming, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise. Readonly."}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isFocusLockEnabled":{"abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", if the cameras focus is locked, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise. Readonly.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isFocusLockEnabled","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/isfocuslockenabled","type":"topic","role":"symbol","title":"isFocusLockEnabled","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFocusLockEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFocusLockEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/device":{"title":"device","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/device","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The camera device to be used."}],"navigatorTitle":[{"kind":"identifier","text":"device"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraDevice"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/device"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/start()":{"abstract":[{"text":"Starts the camera capture session asynchronously.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/start()","title":"start()","navigatorTitle":[{"text":"startSession","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/start()","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/pauseScanning()":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/pausescanning()","type":"topic","navigatorTitle":[{"text":"pauseScanning","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseScanning","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/pauseScanning()","abstract":[{"text":"Pauses the delivery of frames to the delegate.","type":"text"}],"title":"pauseScanning()","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/photoQualityPrioritization":{"abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/photoQualityPrioritization","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"photoQualityPrioritization"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoQualityPrioritization"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCapturePhotoQualityPrioritization","kind":"typeIdentifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"title":"photoQualityPrioritization","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/photoqualityprioritization","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s8CopyableP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isFrontCameraUsed":{"title":"isFrontCameraUsed","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/isfrontcameraused","kind":"symbol","navigatorTitle":[{"text":"isFrontCameraUsed","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":", if the front side camera is used, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise. Readonly."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isFrontCameraUsed","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFrontCameraUsed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/videoFrameResolution":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Sets or gets the current video frame resolution."}],"title":"videoFrameResolution","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoFrameResolution","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoFrameResolution","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoFrameResolution"}],"kind":"symbol","navigatorTitle":[{"text":"videoFrameResolution","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/videoframeresolution"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/videoOrientation":{"title":"videoOrientation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoOrientation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/videoorientation","type":"topic","abstract":[{"text":"Sets or gets the current video orientation.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoOrientation","text":"SBSDKVideoOrientation","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"videoOrientation","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/videoContentMode":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/videocontentmode","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoContentMode","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoContentMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoContentMode","kind":"typeIdentifier","text":"SBSDKVideoContentMode"}],"title":"videoContentMode","abstract":[{"type":"text","text":"The content mode of the video preview layer: fit-in or fill-in. Defaults to "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoContentMode\/fillIn","type":"reference"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"videoContentMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/addSessionObserver(_:)":{"abstract":[{"text":"Adds a new observer to the list of observers.","type":"text"}],"title":"addSessionObserver(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/addsessionobserver(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addSessionObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCameraSessionObserving","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKCameraSessionObserving"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"addSessionObserver:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/addSessionObserver(_:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession","title":"SBSDKCameraSession","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/captureStillImage(completion:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureStillImage(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureStillImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier","text":"SBSDKBaseScannerFrame"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> ())"}],"navigatorTitle":[{"kind":"identifier","text":"captureStillImageWithCompletionHandler:"}],"title":"captureStillImage(completion:)","role":"symbol","abstract":[{"type":"text","text":"Captures a still image asynchronously and passes the image data or an error to the completion handler."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/capturestillimage(completion:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations":{"abstract":[],"title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/avcapturevideodataoutputsamplebufferdelegate-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isTorchLightEnabled":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isTorchLightEnabled","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchLightEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isTorchLightEnabled","kind":"identifier"}],"title":"isTorchLightEnabled","role":"symbol","abstract":[{"text":"Turns the torch light on or off.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/istorchlightenabled"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/maxZoom":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/maxzoom","title":"maxZoom","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/maxZoom","abstract":[{"type":"text","text":"The camera devices maximum zoom factor. Readonly."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"kind":"identifier","text":"maxZoom"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/unfreezeSession()":{"type":"topic","title":"unfreezeSession()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/unfreezeSession()","role":"symbol","abstract":[{"text":"Unfreezes the camera session.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/unfreezesession()","navigatorTitle":[{"kind":"identifier","text":"unfreezeSession"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unfreezeSession"},{"kind":"text","text":"()"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/exposureSettings":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"exposureSettings"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraExposureSettings","kind":"typeIdentifier","text":"SBSDKCameraExposureSettings"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"exposureSettings"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/exposureSettings","title":"exposureSettings","abstract":[{"type":"text","text":"Returns the current cameras exposure settings."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/exposuresettings","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isZoomAvailable":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/iszoomavailable","abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", if the camera zoom is available, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise. Readonly.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isZoomAvailable","title":"isZoomAvailable","navigatorTitle":[{"kind":"identifier","text":"isZoomAvailable"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isZoomAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/previewLayer":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/previewlayer","abstract":[{"type":"text","text":"The preview layer that the camera device uses to output the current video frames."},{"type":"text","text":" "},{"type":"text","text":"Can be added to any superlayer."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/previewLayer","type":"topic","title":"previewLayer","navigatorTitle":[{"kind":"identifier","text":"previewLayer"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewLayer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureVideoPreviewLayer","kind":"typeIdentifier","text":"AVCaptureVideoPreviewLayer"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/minZoom":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/minzoom","title":"minZoom","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minZoom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/minZoom","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minZoom"}],"abstract":[{"type":"text","text":"The camera devices minimum zoom factor. Readonly."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isCapturingStillImage":{"navigatorTitle":[{"kind":"identifier","text":"isCapturingStillImage"}],"title":"isCapturingStillImage","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/iscapturingstillimage","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCapturingStillImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Returns ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the camera is currently in the process of taking a still image, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isCapturingStillImage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/zoomValue":{"abstract":[{"text":"Sets or gets the camera devices current zoom factor. Zooming is done without animation.","type":"text"},{"text":" ","type":"text"},{"text":"If the new value exceeds the minimum or maximum value for zooming it is clamped.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoomValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/zoomValue","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/zoomvalue","title":"zoomValue","role":"symbol","navigatorTitle":[{"text":"zoomValue","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/resetZoom(animated:)":{"navigatorTitle":[{"kind":"identifier","text":"resetZoomAnimated:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/resetZoom(animated:)","type":"topic","title":"resetZoom(animated:)","abstract":[{"type":"text","text":"Resets the zoom factor to the minimum zoom value."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/resetzoom(animated:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetZoom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/loggingContext":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/loggingcontext","fragments":[{"kind":"identifier","text":"loggingContext"}],"type":"topic","title":"loggingContext","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/loggingContext","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/removeSessionObserver(_:)":{"kind":"symbol","abstract":[{"text":"Removes an observer from the list of observers.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeSessionObserver","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKCameraSessionObserving","text":"SBSDKCameraSessionObserving","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/removesessionobserver(_:)","navigatorTitle":[{"kind":"identifier","text":"removeSessionObserver:"}],"title":"removeSessionObserver(_:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/removeSessionObserver(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/videoDelegate":{"navigatorTitle":[{"kind":"identifier","text":"videoDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoDelegate","type":"topic","title":"videoDelegate","abstract":[{"type":"text","text":"The delegate object for camera output."},{"type":"text","text":" "},{"type":"text","text":"Its receives the video frames and does still image captures."},{"type":"text","text":" "},{"type":"text","text":"Delegates can implement all functions from "},{"type":"codeVoice","code":"AVCaptureVideoDataOutputSampleBufferDelegate"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/videodelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKCameraSessionDelegate","text":"SBSDKCameraSessionDelegate"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isSessionRunning":{"title":"isSessionRunning","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isSessionRunning","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSessionRunning"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the camera session is running, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise. Readonly."}],"navigatorTitle":[{"kind":"identifier","text":"isSessionRunning"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/issessionrunning"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isCameraAdjusting":{"title":"isCameraAdjusting","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCameraAdjusting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isCameraAdjusting"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":", if the camera is currently adjusting autofocus, exposure or white balance,"},{"type":"text","text":" "},{"type":"text","text":"false otherwise. Readonly."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isCameraAdjusting","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/iscameraadjusting","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/captureSession":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureSession","text":"AVCaptureSession"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"captureSession"}],"abstract":[{"type":"text","text":"The AVCaptureSession object."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureSession","title":"captureSession","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/capturesession"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/videoResolution":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"abstract":[{"type":"text","text":"Returns the video resolution of the current video output. Orientation is taken into account."},{"type":"text","text":" "},{"type":"text","text":"Returns CGSizeZero, if the capture session is not running."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/videoresolution","navigatorTitle":[{"kind":"identifier","text":"videoResolution"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoResolution","title":"videoResolution"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/updateTorchlightBlock":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTorchlightBlock"},{"kind":"text","text":": (() -> ())?"}],"navigatorTitle":[{"kind":"identifier","text":"updateTorchlightBlock"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/updatetorchlightblock","type":"topic","abstract":[{"type":"text","text":"A block being executed when the torch light status changes (mode or availability)."}],"title":"updateTorchlightBlock","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/updateTorchlightBlock","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/stop(keepAlive:)":{"title":"stop(keepAlive:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/stop(keepAlive:)","role":"symbol","abstract":[{"type":"text","text":"Stops the camera capture session. Does nothing if the session is already stopped."}],"navigatorTitle":[{"kind":"identifier","text":"stopSession:"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keepAlive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/stop(keepalive:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/observeValue(forKeyPath:of:change:context:)":{"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/observevalue(forkeypath:of:change:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSKeyValueChangeKey","text":"NSKeyValueChangeKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/observeValue(forKeyPath:of:change:context:)","navigatorTitle":[{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"role":"symbol","kind":"symbol","title":"observeValue(forKeyPath:of:change:context:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isScanningPaused":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isScanningPaused"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/isscanningpaused","type":"topic","kind":"symbol","title":"isScanningPaused","role":"symbol","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":", if the live scanning is paused, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise. Readonly."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isScanningPaused","navigatorTitle":[{"kind":"identifier","text":"isScanningPaused"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/maxOpticalZoom":{"kind":"symbol","title":"maxOpticalZoom","navigatorTitle":[{"kind":"identifier","text":"maxOpticalZoom"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/maxopticalzoom","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/maxOpticalZoom","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxOpticalZoom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"type":"text","text":"The camera devices maximum optical zoom factor. Readonly."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCapturePhotoQualityPrioritization/balanced":{"type":"topic","title":"SBSDKCapturePhotoQualityPrioritization.balanced","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcapturephotoqualityprioritization\/balanced","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"balanced"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationBalanced"}],"abstract":[{"type":"text","text":"Balances capturing speed and image quality equally. This is the default value."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/isMirrored":{"role":"symbol","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the camera session mirrors its video, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMirrored"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isMirrored","title":"isMirrored","navigatorTitle":[{"kind":"identifier","text":"isMirrored"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/ismirrored","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/freezeSession()":{"abstract":[{"type":"text","text":"Freezes the camera session."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"freezeSession"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/freezeSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeSession"},{"kind":"text","text":"()"}],"kind":"symbol","title":"freezeSession()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/freezesession()","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/setPreviewLayerVisible(_:animated:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreviewLayerVisible"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/setpreviewlayervisible(_:animated:)","navigatorTitle":[{"kind":"identifier","text":"setPreviewLayerVisible:animated:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/setPreviewLayerVisible(_:animated:)","abstract":[{"type":"text","text":"Toggles the visibility of the camera preview."}],"title":"setPreviewLayerVisible(_:animated:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession/beginFocusLock(at:)":{"kind":"symbol","title":"beginFocusLock(at:)","navigatorTitle":[{"kind":"identifier","text":"beginFocusLockAtLensPosition:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/beginFocusLock(at:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Disables auto-focus and locks the lens at the specified lens position."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beginFocusLock"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession\/beginfocuslock(at:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoContentMode/fillIn":{"abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"text":" ","type":"text"},{"text":"No visible borders. Video may be cropped to the visible screen area.","type":"text"}],"type":"topic","title":"SBSDKVideoContentMode.fillIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillIn"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideocontentmode\/fillin","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoContentMode\/fillIn"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKCameraSession","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureSession","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/device","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/exposureSettings","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isCameraAdjusting","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isCapturingStillImage","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isFocusLockEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isFrontCameraUsed","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isMirrored","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isScanningPaused","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isSessionRunning","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isTorchLightAvailable","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isTorchLightEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isZoomAvailable","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/isZooming","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/keepAliveTimeout","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/loggingContext","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/maxOpticalZoom","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/maxZoom","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/minZoom","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/photoQualityPrioritization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/previewLayer","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/updateTorchlightBlock","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/updateZoomBlock","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoContentMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoDelegate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoFrameResolution","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoOrientation","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/videoResolution","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/zoomValue"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/addSessionObserver(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/beginFocusLock(at:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/captureStillImage(completion:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/endFocusLock()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/freezeSession()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/init(feature:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/init(feature:device:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/observeValue(forKeyPath:of:change:context:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/pauseScanning()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/removeSessionObserver(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/resetZoom(animated:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/resumeScanning()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/setPreviewLayerVisible(_:animated:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/setZoom(_:animated:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/start()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/stop(keepAlive:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/unfreezeSession()"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithFeature:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1init(feature:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFeature:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1init(feature:)\/fragments"},{"value":"setZoomValue:animated:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1setZoom(_:animated:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setZoomValue:animated:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1setZoom(_:animated:)\/fragments"},{"value":"initWithFeature:device:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1init(feature:device:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFeature:device:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1init(feature:device:)\/fragments"},{"value":"updateZoomBlock","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1updateZoomBlock\/title"},{"value":[{"kind":"identifier","text":"updateZoomBlock"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1updateZoomBlock\/fragments"},{"value":"isTorchLightAvailable","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isTorchLightAvailable\/title"},{"value":[{"kind":"identifier","text":"isTorchLightAvailable"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isTorchLightAvailable\/fragments"},{"value":"keepAliveTimeout","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1keepAliveTimeout\/title"},{"value":[{"kind":"identifier","text":"keepAliveTimeout"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1keepAliveTimeout\/fragments"},{"value":"resumeScanning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1resumeScanning()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resumeScanning"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1resumeScanning()\/fragments"},{"value":"endFocusLock","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1endFocusLock()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"endFocusLock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1endFocusLock()\/fragments"},{"value":"isZooming","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isZooming\/title"},{"value":[{"text":"isZooming","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isZooming\/fragments"},{"value":"isFocusLockEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isFocusLockEnabled\/title"},{"value":[{"kind":"identifier","text":"isFocusLockEnabled"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isFocusLockEnabled\/fragments"},{"value":"device","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1device\/title"},{"value":[{"kind":"identifier","text":"device"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1device\/fragments"},{"value":"startSession","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1start()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startSession"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1start()\/fragments"},{"value":"pauseScanning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1pauseScanning()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"pauseScanning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1pauseScanning()\/fragments"},{"value":"photoQualityPrioritization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1photoQualityPrioritization\/title"},{"value":[{"kind":"identifier","text":"photoQualityPrioritization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1photoQualityPrioritization\/fragments"},{"value":"isFrontCameraUsed","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isFrontCameraUsed\/title"},{"value":[{"text":"isFrontCameraUsed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isFrontCameraUsed\/fragments"},{"value":"videoFrameResolution","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoFrameResolution\/title"},{"value":[{"text":"videoFrameResolution","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoFrameResolution\/fragments"},{"value":"videoOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoOrientation\/title"},{"value":[{"text":"videoOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoOrientation\/fragments"},{"value":"videoContentMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoContentMode\/title"},{"value":[{"kind":"identifier","text":"videoContentMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoContentMode\/fragments"},{"value":"addSessionObserver:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1addSessionObserver(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"addSessionObserver:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1addSessionObserver(_:)\/fragments"},{"value":"SBSDKCameraSession","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/title"},{"value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/navigatorTitle"},{"value":"captureStillImageWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1captureStillImage(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"captureStillImageWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1captureStillImage(completion:)\/fragments"},{"value":"isTorchLightEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isTorchLightEnabled\/title"},{"value":[{"text":"isTorchLightEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isTorchLightEnabled\/fragments"},{"value":"maxZoom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1maxZoom\/title"},{"value":[{"kind":"identifier","text":"maxZoom"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1maxZoom\/fragments"},{"value":"unfreezeSession","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1unfreezeSession()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"unfreezeSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1unfreezeSession()\/fragments"},{"value":"exposureSettings","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1exposureSettings\/title"},{"value":[{"text":"exposureSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1exposureSettings\/fragments"},{"value":"isZoomAvailable","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isZoomAvailable\/title"},{"value":[{"text":"isZoomAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isZoomAvailable\/fragments"},{"value":"previewLayer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1previewLayer\/title"},{"value":[{"kind":"identifier","text":"previewLayer"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1previewLayer\/fragments"},{"value":"minZoom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1minZoom\/title"},{"value":[{"text":"minZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1minZoom\/fragments"},{"value":"isCapturingStillImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isCapturingStillImage\/title"},{"value":[{"text":"isCapturingStillImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isCapturingStillImage\/fragments"},{"value":"zoomValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1zoomValue\/title"},{"value":[{"kind":"identifier","text":"zoomValue"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1zoomValue\/fragments"},{"value":"resetZoomAnimated:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1resetZoom(animated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"resetZoomAnimated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1resetZoom(animated:)\/fragments"},{"value":"removeSessionObserver:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1removeSessionObserver(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeSessionObserver:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1removeSessionObserver(_:)\/fragments"},{"value":"videoDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoDelegate\/title"},{"value":[{"kind":"identifier","text":"videoDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoDelegate\/fragments"},{"value":"isSessionRunning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isSessionRunning\/title"},{"value":[{"kind":"identifier","text":"isSessionRunning"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isSessionRunning\/fragments"},{"value":"isCameraAdjusting","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isCameraAdjusting\/title"},{"value":[{"kind":"identifier","text":"isCameraAdjusting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isCameraAdjusting\/fragments"},{"value":"captureSession","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1captureSession\/title"},{"value":[{"kind":"identifier","text":"captureSession"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1captureSession\/fragments"},{"value":"videoResolution","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoResolution\/title"},{"value":[{"kind":"identifier","text":"videoResolution"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1videoResolution\/fragments"},{"value":"updateTorchlightBlock","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1updateTorchlightBlock\/title"},{"value":[{"kind":"identifier","text":"updateTorchlightBlock"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1updateTorchlightBlock\/fragments"},{"value":"stopSession:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1stop(keepAlive:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopSession:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1stop(keepAlive:)\/fragments"},{"value":"observeValueForKeyPath:ofObject:change:context:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1observeValue(forKeyPath:of:change:context:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"observeValueForKeyPath:ofObject:change:context:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1observeValue(forKeyPath:of:change:context:)\/fragments"},{"value":"isScanningPaused","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isScanningPaused\/title"},{"value":[{"kind":"identifier","text":"isScanningPaused"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isScanningPaused\/fragments"},{"value":"maxOpticalZoom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1maxOpticalZoom\/title"},{"value":[{"text":"maxOpticalZoom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1maxOpticalZoom\/fragments"},{"value":"SBSDKCapturePhotoQualityPrioritizationBalanced","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/title"},{"value":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/fragments"},{"value":"isMirrored","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isMirrored\/title"},{"value":[{"kind":"identifier","text":"isMirrored"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1isMirrored\/fragments"},{"value":"freezeSession","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1freezeSession()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"freezeSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1freezeSession()\/fragments"},{"value":"setPreviewLayerVisible:animated:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1setPreviewLayerVisible(_:animated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setPreviewLayerVisible:animated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1setPreviewLayerVisible(_:animated:)\/fragments"},{"value":"beginFocusLockAtLensPosition:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1beginFocusLock(at:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"beginFocusLockAtLensPosition:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession~1beginFocusLock(at:)\/fragments"},{"value":"SBSDKVideoContentModeFillIn","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoContentMode~1fillIn\/title"},{"value":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoContentMode~1fillIn\/fragments"}]}]}