{"sections":[],"abstract":[{"text":"This enum describes the possible scanning states of any scanner.","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/idle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanned","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanning"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"identifier"}],"title":"SBSDKScannerStatus","navigatorTitle":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKScannerStatus","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannerStatus"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus/idle":{"navigatorTitle":[{"text":"SBSDKScannerStatusIdle","kind":"identifier"}],"title":"SBSDKScannerStatus.idle","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idle","kind":"identifier"}],"abstract":[{"type":"text","text":"The scanner is paused or has not yet been started."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus\/idle","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/idle"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus/scanning":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanning","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanning","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKScannerStatusScanning","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus\/scanning","abstract":[{"text":"The scanner is active.","type":"text"}],"title":"SBSDKScannerStatus.scanning"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus\/equatable-implementations","abstract":[],"role":"collectionGroup","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus/init(rawValue:)":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","title":"init(rawValue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus":{"navigatorTitle":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"title":"SBSDKScannerStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"This enum describes the possible scanning states of any scanner."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/RawRepresentable-Implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus\/rawrepresentable-implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannerStatus/scanned":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanned","kind":"identifier"}],"title":"SBSDKScannerStatus.scanned","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannerstatus\/scanned","kind":"symbol","abstract":[{"type":"text","text":"The scanner has scanned something."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanned","navigatorTitle":[{"text":"SBSDKScannerStatusScanned","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKScannerStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKScannerStatus","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKScannerStatus","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/idle","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanned","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannerStatus\/scanning"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannerStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1idle\/title","value":"SBSDKScannerStatusIdle"},{"value":[{"kind":"identifier","text":"SBSDKScannerStatusIdle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1idle\/fragments"},{"value":"SBSDKScannerStatusScanning","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1scanning\/title"},{"value":[{"text":"SBSDKScannerStatusScanning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1scanning\/fragments"},{"value":"SBSDKScannerStatus","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus\/title"},{"value":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus\/navigatorTitle"},{"value":"SBSDKScannerStatusScanned","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1scanned\/title"},{"value":[{"kind":"identifier","text":"SBSDKScannerStatusScanned"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannerStatus~1scanned\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}