{"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription(py)prescriptionFreeText","title":"prescriptionFreeText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"prescriptionFreeText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"prescriptionFreeText"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription"]]},"abstract":[{"type":"text","text":"Prescription Free Text."}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription\/prescriptionFreeText","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prescriptionFreeText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingprescription\/prescriptionfreetext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingprescription\/prescriptionfreetext"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription/prescriptionFreeText":{"abstract":[{"text":"Prescription Free Text.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingprescription\/prescriptionfreetext","title":"prescriptionFreeText","role":"symbol","navigatorTitle":[{"text":"prescriptionFreeText","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription\/prescriptionFreeText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"prescriptionFreeText","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription":{"title":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingprescription","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","kind":"identifier"}],"abstract":[{"text":"Prescription.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentField":{"title":"SBSDKGenericDocumentField","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentfield","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"type":"topic","abstract":[{"type":"text","text":"A generic document field."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"prescriptionFreeText","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"prescriptionFreeText"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"text":" * ","kind":"text"},{"text":"prescriptionFreeText","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription~1prescriptionFreeText\/title","value":"prescriptionFreeText","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription~1prescriptionFreeText\/fragments","op":"replace","value":[{"kind":"identifier","text":"prescriptionFreeText"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription\/title","value":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingPrescription\/fragments"},{"value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/title","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}