{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabledInAutoSnappingMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2shutterbutton\/enabledinautosnappingmode"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2shutterbutton\/enabledinautosnappingmode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"enabledInAutoSnappingMode","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ShutterButton(py)enabledInAutoSnappingMode","title":"enabledInAutoSnappingMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabledInAutoSnappingMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton\/enabledInAutoSnappingMode","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Determines if the ‘shutter’ button can be tapped to manually snap a document when ‘auto snapping mode’ is"},{"type":"text","text":" "},{"text":"active.","type":"text"},{"text":" ","type":"text"},{"text":"Default is true","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ShutterButton":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2shutterbutton","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ShutterButton"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton","title":"SBSDKUI2ShutterButton","abstract":[{"text":"Configuration of the ‘shutter’ button.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ShutterButton/enabledInAutoSnappingMode":{"url":"\/documentation\/scanbotsdk\/sbsdkui2shutterbutton\/enabledinautosnappingmode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ShutterButton\/enabledInAutoSnappingMode","abstract":[{"text":"Determines if the ‘shutter’ button can be tapped to manually snap a document when ‘auto snapping mode’ is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"active."},{"type":"text","text":" "},{"text":"Default is true","type":"text"}],"kind":"symbol","title":"enabledInAutoSnappingMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabledInAutoSnappingMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"enabledInAutoSnappingMode","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"enabledInAutoSnappingMode","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"enabledInAutoSnappingMode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enabledInAutoSnappingMode"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/title","value":"SBSDKUI2ShutterButton"},{"op":"replace","value":[{"text":"SBSDKUI2ShutterButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton\/fragments"},{"value":"enabledInAutoSnappingMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton~1enabledInAutoSnappingMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ShutterButton~1enabledInAutoSnappingMode\/fragments","value":[{"kind":"identifier","text":"enabledInAutoSnappingMode"}]}]}]}