{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration\/init(topbartitle:minimumquality:acknowledgementmode:badimagehint:backgroundcolor:bottombar:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration\/init(topbartitle:minimumquality:acknowledgementmode:badimagehint:backgroundcolor:bottombar:)"]}],"kind":"symbol","metadata":{"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"title":"init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)","navigatorTitle":[{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}],"role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration(im)initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentQuality","kind":"typeIdentifier","text":"SBSDKDocumentQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"acknowledgementMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AcknowledgementMode","kind":"typeIdentifier","text":"SBSDKUI2AcknowledgementMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"badImageHint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration","kind":"typeIdentifier","text":"SBSDKUI2IconUserGuidanceConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomBar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier","text":"SBSDKUI2AcknowledgementBottomBar"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"kind":"text","text":" = SBSDKUI2StyledText(visible: false, text: \"?acknowledgementTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)), "},{"kind":"externalParam","text":"minimumQuality"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentQuality","kind":"typeIdentifier","text":"SBSDKDocumentQuality"},{"kind":"text","text":" = SBSDKDocumentQuality.poor, "},{"kind":"externalParam","text":"acknowledgementMode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode","text":"SBSDKUI2AcknowledgementMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AcknowledgementMode"},{"text":" = SBSDKUI2AcknowledgementMode.always, ","kind":"text"},{"text":"badImageHint","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconUserGuidanceConfiguration","text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration"},{"text":" = SBSDKUI2IconUserGuidanceConfiguration(visible: true,\n                                                          icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                       isArgb: false)),\n                                                          title: SBSDKUI2StyledText(text: \"?acknowledgementScreenBadDocumentHint\",\n                                                                                    color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                         isArgb: false)),\n                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorNegative\",\n                                                                                                                         isArgb: false),\n                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorNegative\",\n                                                                                                                       isArgb: false),\n                                                                                              strokeWidth: 0.0)), ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), ","kind":"text"},{"text":"bottomBar","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","text":"SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar"},{"text":" = SBSDKUI2AcknowledgementBottomBar())","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"title":"SBSDKUI2StyledText","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration","role":"symbol","kind":"symbol","title":"SBSDKUI2AcknowledgementScreenConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration of the acknowledgement screen."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQuality":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentquality","title":"SBSDKDocumentQuality","abstract":[{"type":"text","text":"The result of the document quality check."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQuality","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementBottomBar":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"title":"SBSDKUI2AcknowledgementBottomBar","navigatorTitle":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the bottom bar for the acknowledgement screen."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementScreenConfiguration/init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration\/init(topbartitle:minimumquality:acknowledgementmode:badimagehint:backgroundcolor:bottombar:)","navigatorTitle":[{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}],"role":"symbol","title":"init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topBarTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minimumQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"acknowledgementMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2AcknowledgementMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AcknowledgementMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"badImageHint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2IconUserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomBar","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2AcknowledgementBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconUserGuidanceConfiguration":{"abstract":[{"type":"text","text":"Configuration of the hint (containing an icon) guiding users through the scanning process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconUserGuidanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2iconuserguidanceconfiguration","role":"symbol","title":"SBSDKUI2IconUserGuidanceConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2color","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"title":"SBSDKUI2Color"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementmode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"abstract":[{"text":"Determines, after each page is snapped, whether the acknowledgment screen should be displayed or not.","type":"text"}],"title":"SBSDKUI2AcknowledgementMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTopBarTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumQuality:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentQuality","text":"SBSDKDocumentQuality"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumQuality"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgementMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AcknowledgementMode","text":"SBSDKUI2AcknowledgementMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"acknowledgementMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"badImageHint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconUserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration","text":"SBSDKUI2IconUserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"badImageHint"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","text":"SBSDKUI2AcknowledgementBottomBar"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bottomBar"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2AcknowledgementScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentQuality","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQuality"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQuality"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2AcknowledgementBottomBar","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/title"},{"op":"replace","value":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/navigatorTitle"},{"op":"replace","value":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration~1init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration~1init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)\/fragments"},{"op":"replace","value":"SBSDKUI2IconUserGuidanceConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconUserGuidanceConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconUserGuidanceConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconUserGuidanceConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2AcknowledgementMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/title"},{"op":"replace","value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}