{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidanceTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/userguidancetextcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/userguidancetextcolor"]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"userGuidanceTextColor"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentScannerUIConfiguration(py)userGuidanceTextColor","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"userGuidanceTextColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"userGuidanceTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"platforms":[],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/userGuidanceTextColor","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Foreground\/text color of the user guidance label.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration":{"abstract":[{"text":"Configuration for the user interface of the document scanning screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"title":"SBSDKUIDocumentScannerUIConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"deprecated":true,"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerUIConfiguration/userGuidanceTextColor":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userGuidanceTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerUIConfiguration\/userGuidanceTextColor","title":"userGuidanceTextColor","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscanneruiconfiguration\/userguidancetextcolor","deprecated":true,"navigatorTitle":[{"text":"userGuidanceTextColor","kind":"identifier"}],"type":"topic","abstract":[{"text":"Foreground\/text color of the user guidance label.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"userGuidanceTextColor","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"userGuidanceTextColor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" * "},{"text":"userGuidanceTextColor","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/title","op":"replace","value":"SBSDKUIDocumentScannerUIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUIDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1userGuidanceTextColor\/title","op":"replace","value":"userGuidanceTextColor"},{"value":[{"kind":"identifier","text":"userGuidanceTextColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerUIConfiguration~1userGuidanceTextColor\/fragments","op":"replace"}]}]}