{"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)twEntryAndExitPermitIDFieldNormalizedName","symbolKind":"property","navigatorTitle":[{"text":"twEntryAndExitPermitIDFieldNormalizedName","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"twEntryAndExitPermitIDFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Type Property","title":"twEntryAndExitPermitIDFieldNormalizedName","role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/twEntryAndExitPermitIDFieldNormalizedName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Normalized full name of the “ID” field type in document type “TwEntryAndExitPermit”."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"twEntryAndExitPermitIDFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/twentryandexitpermitidfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/twentryandexitpermitidfieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","title":"SBSDKDocumentsModelConstants","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/twEntryAndExitPermitIDFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/twentryandexitpermitidfieldnormalizedname","kind":"symbol","role":"symbol","title":"twEntryAndExitPermitIDFieldNormalizedName","abstract":[{"text":"Normalized full name of the “ID” field type in document type “TwEntryAndExitPermit”.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/twEntryAndExitPermitIDFieldNormalizedName","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"twEntryAndExitPermitIDFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"twEntryAndExitPermitIDFieldNormalizedName","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"twEntryAndExitPermitIDFieldNormalizedName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"twEntryAndExitPermitIDFieldNormalizedName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"twEntryAndExitPermitIDFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title","value":"SBSDKDocumentsModelConstants"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}]},{"op":"replace","value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle"},{"op":"replace","value":"twEntryAndExitPermitIDFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1twEntryAndExitPermitIDFieldNormalizedName\/title"},{"op":"replace","value":[{"text":"twEntryAndExitPermitIDFieldNormalizedName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1twEntryAndExitPermitIDFieldNormalizedName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}