{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidanceTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/userguidancetextcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/userguidancetextcolor"]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userGuidanceTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"userGuidanceTextColor","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerUIConfiguration(py)userGuidanceTextColor","title":"userGuidanceTextColor"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration\/userGuidanceTextColor"},"sections":[],"abstract":[{"text":"The text color of the user guidance label.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerUIConfiguration/userGuidanceTextColor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration\/userGuidanceTextColor","title":"userGuidanceTextColor","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userGuidanceTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"type":"text","text":"The text color of the user guidance label."}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/userguidancetextcolor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userGuidanceTextColor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration","navigatorTitle":[{"text":"SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"identifier"}],"title":"SBSDKUIMedicalCertificateScannerUIConfiguration","abstract":[{"type":"text","text":"Configuration for the user interface of the RTU-UI medical certificate scanner."}],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"userGuidanceTextColor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"userGuidanceTextColor"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"userGuidanceTextColor","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration~1userGuidanceTextColor\/title","value":"userGuidanceTextColor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration~1userGuidanceTextColor\/fragments","value":[{"kind":"identifier","text":"userGuidanceTextColor"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerUIConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}