{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile\/copyWithZone:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"copyWithZone:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageProfile(im)copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprofile\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProfile":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile","kind":"symbol","title":"SBSDKImageProfile","type":"topic","navigatorTitle":[{"text":"SBSDKImageProfile","kind":"identifier"}],"abstract":[{"type":"text","text":"ImageRef profile part specific to image information."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProfile","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprofile","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProfile/copyWithZone:":{"title":"copyWithZone:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProfile\/copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprofile\/copywithzone:","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKImageProfile","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/title"},{"op":"replace","value":[{"text":"SBSDKImageProfile","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageProfile"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProfile\/navigatorTitle"}]}]}