{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityThreshold(py)hash","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"hash","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualitythreshold\/hash"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityThreshold"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityThreshold\/hash","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityThreshold/hash":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityThreshold\/hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualitythreshold\/hash","role":"symbol","kind":"symbol","abstract":[],"title":"hash","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityThreshold":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityThreshold","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityThreshold"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualitythreshold","title":"SBSDKDocumentQualityThreshold","abstract":[{"type":"text","text":"Point in the quality-number of symbols space to separate quality levels."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityThreshold","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityThreshold\/title","value":"SBSDKDocumentQualityThreshold"},{"value":[{"text":"SBSDKDocumentQualityThreshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityThreshold\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentQualityThreshold"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityThreshold\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}