{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSymbolQuality:symbolRatio:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"initWithSymbolQuality:symbolRatio:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSymbolQuality:symbolRatio:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityThreshold(im)initWithSymbolQuality:symbolRatio:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityThreshold\/initWithSymbolQuality:symbolRatio:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityThreshold"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSymbolQuality:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"symbolQuality","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"symbolRatio:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"symbolRatio","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualitythreshold\/initwithsymbolquality:symbolratio:"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityThreshold/initWithSymbolQuality:symbolRatio:":{"navigatorTitle":[{"kind":"identifier","text":"initWithSymbolQuality:symbolRatio:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityThreshold\/initWithSymbolQuality:symbolRatio:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualitythreshold\/initwithsymbolquality:symbolratio:","type":"topic","abstract":[],"kind":"symbol","title":"initWithSymbolQuality:symbolRatio:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSymbolQuality:symbolRatio:"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityThreshold":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityThreshold","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityThreshold"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualitythreshold","title":"SBSDKDocumentQualityThreshold","abstract":[{"type":"text","text":"Point in the quality-number of symbols space to separate quality levels."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityThreshold","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKDocumentQualityThreshold","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityThreshold\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentQualityThreshold"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityThreshold\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityThreshold\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}