{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fitIn"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode"]]},"abstract":[{"text":"The video layers content is fit into the video layer.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Video may have visible borders. Video is fully visible within the screen."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKVideoContentMode.fitIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fitIn","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentModeFitIn"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode@SBSDKVideoContentModeFitIn","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fitIn"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fitin"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fitin"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode/fitIn":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fitin","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fitIn","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentModeFitIn"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fitIn"}],"title":"SBSDKVideoContentMode.fitIn","abstract":[{"type":"text","text":"The video layers content is fit into the video layer."},{"text":" ","type":"text"},{"type":"text","text":"Video may have visible borders. Video is fully visible within the screen."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode":{"navigatorTitle":[{"text":"SBSDKVideoContentMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode","abstract":[{"type":"text","text":"Enumeration of video preview content mode."}],"title":"SBSDKVideoContentMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVideoContentMode"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKVideoContentModeFitIn","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoContentModeFitIn"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKVideoContentModeFitIn","kind":"identifier"}]}]}},{"value":"SBSDKVideoContentModeFitIn","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fitIn\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVideoContentModeFitIn"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fitIn\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/title","value":"SBSDKVideoContentMode","op":"replace"},{"value":[{"text":"SBSDKVideoContentMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/fragments","op":"replace"}]}]}