{"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultCheckDigitType@SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth","roleHeading":"Case","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.dateOfBirth","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType"]]},"abstract":[{"text":"Date of birth validation check-digit.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/dateOfBirth"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/dateofbirth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/dateofbirth"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/dateOfBirth":{"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/dateofbirth","abstract":[{"type":"text","text":"Date of birth validation check-digit."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/dateOfBirth","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfBirth"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth"}],"title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.dateOfBirth","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"abstract":[{"type":"text","text":"MRZ check-digit types."}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1dateOfBirth\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeDateOfBirth"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1dateOfBirth\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"op":"replace"}]}]}