{"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultCheckDigitType@SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral"}],"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.general","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"general","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/general","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/general"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/general"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"general"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"General document validation check-digit.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType":{"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype","abstract":[{"type":"text","text":"MRZ check-digit types."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/general":{"title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.general","abstract":[{"text":"General document validation check-digit.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/general","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/general","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"general"}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1general\/title","op":"replace","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypeGeneral"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1general\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}