{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalNumber","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultCheckDigitType@SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"personalNumber","kind":"identifier"}],"role":"symbol","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.personalNumber"},"abstract":[{"text":"Personal number validation check-digit.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/personalNumber"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/personalnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/personalnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"abstract":[{"type":"text","text":"MRZ check-digit types."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType/personalNumber":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/personalNumber","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType.personalNumber","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"personalNumber","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber","kind":"identifier"}],"abstract":[{"text":"Personal number validation check-digit.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype\/personalnumber","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/title"},{"op":"replace","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1personalNumber\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitTypePersonalNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType~1personalNumber\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}