{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topUserGuidance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","title":"topUserGuidance","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenTextLocalization(py)topUserGuidance","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"topUserGuidance"}],"modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization\/topUserGuidance","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization\/topuserguidance"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization\/topuserguidance"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topUserGuidance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is “Locate the text you are looking for”","type":"text"}]}]}],"abstract":[{"type":"text","text":"Text for the top user guidance caption."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenTextLocalization":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternScannerScreenTextLocalization","kind":"identifier"}],"title":"SBSDKUI2TextPatternScannerScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization","abstract":[{"text":"Configuration of the all strings for generic text scanner screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenTextLocalization/topUserGuidance":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization\/topUserGuidance","abstract":[{"text":"Text for the top user guidance caption.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topUserGuidance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization\/topuserguidance","type":"topic","role":"symbol","title":"topUserGuidance","navigatorTitle":[{"text":"topUserGuidance","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"topUserGuidance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"topUserGuidance","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topUserGuidance"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"SBSDKUI2TextPatternScannerScreenTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/title"},{"value":[{"text":"SBSDKUI2TextPatternScannerScreenTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization~1topUserGuidance\/title","value":"topUserGuidance"},{"op":"replace","value":[{"text":"topUserGuidance","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization~1topUserGuidance\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}