{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration(py)hash","title":"hash","roleHeading":"Instance Property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration\/hash","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":";","kind":"text"}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration/hash":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/hash","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","title":"SBSDKCreditCardScannerConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration","abstract":[{"type":"text","text":"Configuration for the credit card scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKCreditCardScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/fragments","value":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/navigatorTitle"}]}]}