{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithUseDocumentDetector:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"useDocumentDetector","kind":"internalParam"},{"kind":"text","text":" "},{"text":"scanningMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCreditCardScanningMode","text":"SBSDKCreditCardScanningMode"},{"kind":"text","text":") "},{"text":"scanningMode","kind":"internalParam"},{"kind":"text","text":" "},{"text":"requireExpiryDate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"requireExpiryDate"},{"text":" ","kind":"text"},{"text":"requireCardholderName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"requireCardholderName"},{"text":" ","kind":"text"},{"text":"resultAccumulationConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKResultAccumulationConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration"},{"text":" *) ","kind":"text"},{"text":"resultAccumulationConfig","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnCreditCardImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"returnCreditCardImage"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerConfiguration(im)initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:","fragments":[{"kind":"text","text":"- "},{"text":"initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:"}],"title":"initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration\/initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/initwithusedocumentdetector:scanningmode:requireexpirydate:requirecardholdername:resultaccumulationconfig:returncreditcardimage:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration","title":"SBSDKCreditCardScannerConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration","abstract":[{"type":"text","text":"Configuration for the credit card scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerConfiguration/initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:":{"role":"symbol","abstract":[],"title":"initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:","fragments":[{"kind":"text","text":"- "},{"text":"initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerconfiguration\/initwithusedocumentdetector:scanningmode:requireexpirydate:requirecardholdername:resultaccumulationconfig:returncreditcardimage:","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerConfiguration\/initWithUseDocumentDetector:scanningMode:requireExpiryDate:requireCardholderName:resultAccumulationConfig:returnCreditCardImage:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode","kind":"symbol","role":"symbol","abstract":[{"text":"The scanning mode.","type":"text"}],"type":"topic","title":"SBSDKCreditCardScanningMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScanningMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration":{"navigatorTitle":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration","abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"kind":"symbol","type":"topic","title":"SBSDKResultAccumulationConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKCreditCardScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCreditCardScannerConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/title","op":"replace","value":"SBSDKCreditCardScanningMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/fragments","op":"replace","value":[{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/navigatorTitle","value":[{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}],"op":"replace"},{"value":"SBSDKResultAccumulationConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/title"},{"value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/navigatorTitle"}]}]}