{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"quality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"encryptionMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"encryptionMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"encrypter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKStorageCryptingProvider>","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"encrypter","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSaveImageOptions"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"initWithQuality:encryptionMode:encrypter:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKSaveImageOptions(im)initWithQuality:encryptionMode:encrypter:","symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"initWithQuality:encryptionMode:encrypter:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQuality:encryptionMode:encrypter:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdksaveimageoptions\/initwithquality:encryptionmode:encrypter:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSaveImageOptions\/initWithQuality:encryptionMode:encrypter:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSaveImageOptions":{"abstract":[{"text":"Options for saving image to a path.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksaveimageoptions","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSaveImageOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"title":"SBSDKSaveImageOptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncryptionMode":{"title":"SBSDKEncryptionMode","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode","role":"symbol","abstract":[{"text":"Encryption\/Decryption mode to be used when an image is loaded\/saved.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKSaveImageOptions/initWithQuality:encryptionMode:encrypter:":{"abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdksaveimageoptions\/initwithquality:encryptionmode:encrypter:","kind":"symbol","role":"symbol","title":"initWithQuality:encryptionMode:encrypter:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKSaveImageOptions\/initWithQuality:encryptionMode:encrypter:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithQuality:encryptionMode:encrypter:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQuality:encryptionMode:encrypter:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSaveImageOptions\/title","value":"SBSDKSaveImageOptions","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSaveImageOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKSaveImageOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/title","value":"SBSDKEncryptionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/fragments","value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace"}]}]}