{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(setupDefaultLicenseFailureHandlerWithCompletion:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional block being executed after the user pressed the OK-button in the alert."}]}],"name":"completion"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Sets up the default license failure handler which is being called when the license or trial time expired."},{"type":"text","text":" "},{"type":"text","text":"The default handler shows an alert to inform your users about the expired license or trial period."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setupDefaultLicenseFailureHandlerWithCompletion:"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupDefaultLicenseFailureHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ())?)","kind":"text"}],"symbolKind":"method","title":"setupDefaultLicenseFailureHandler(completion:)","externalID":"c:@M@ScanbotSDK@objc(cs)Scanbot(cm)setupDefaultLicenseFailureHandlerWithCompletion:","roleHeading":"Type Method"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setupDefaultLicenseFailureHandler(completion:)":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/scanbot\/setupdefaultlicensefailurehandler(completion:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setupDefaultLicenseFailureHandlerWithCompletion:"}],"abstract":[{"type":"text","text":"Sets up the default license failure handler which is being called when the license or trial time expired."},{"type":"text","text":" "},{"type":"text","text":"The default handler shows an alert to inform your users about the expired license or trial period."}],"title":"setupDefaultLicenseFailureHandler(completion:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setupDefaultLicenseFailureHandler(completion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> ())?)"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot":{"url":"\/documentation\/scanbotsdk\/scanbot","abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scanbot"}],"navigatorTitle":[{"kind":"identifier","text":"Scanbot"}],"title":"Scanbot","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setupDefaultLicenseFailureHandlerWithCompletion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setupDefaultLicenseFailureHandlerWithCompletion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"An optional block being executed after the user pressed the OK-button in the alert.","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"setupDefaultLicenseFailureHandlerWithCompletion:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setupDefaultLicenseFailureHandler(completion:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setupDefaultLicenseFailureHandlerWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setupDefaultLicenseFailureHandler(completion:)\/fragments"},{"op":"replace","value":"Scanbot","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/title"},{"op":"replace","value":[{"text":"Scanbot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/fragments"},{"op":"replace","value":[{"text":"Scanbot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/navigatorTitle"}]}]}