{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"processingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","text":"SBSDKProcessingMode"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results.","type":"text"},{"text":" ","type":"text"},{"text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Default is AUTO","type":"text"}],"type":"paragraph"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processingMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"processingMode","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"processingMode","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerConfiguration(py)processingMode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/processingmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/processingmode"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/processingMode"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"title":"SBSDKBarcodeScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration for the barcode scanner."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode":{"title":"SBSDKProcessingMode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"},{"text":" ","type":"text"},{"text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results.","type":"text"},{"text":" ","type":"text"},{"text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerConfiguration/processingMode":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processingMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","text":"SBSDKProcessingMode","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it."}],"navigatorTitle":[{"text":"processingMode","kind":"identifier"}],"role":"symbol","title":"processingMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerConfiguration\/processingMode","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerconfiguration\/processingmode","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"processingMode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"processingMode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","text":"SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"processingMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle"},{"value":"SBSDKProcessingMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/title"},{"value":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/fragments"},{"value":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/navigatorTitle"},{"value":"processingMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1processingMode\/title"},{"value":[{"text":"processingMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerConfiguration~1processingMode\/fragments"}]}]}