{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocument\/initwithtype:fields:children:quad:quadinroot:crop:confidence:confidenceweight:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentType","text":"SBSDKGenericDocumentType"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKGenericDocumentField *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fields"},{"kind":"text","text":" "},{"kind":"identifier","text":"children:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKGenericDocument *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"children"},{"kind":"text","text":" "},{"kind":"identifier","text":"quad:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quad"},{"kind":"text","text":" "},{"kind":"identifier","text":"quadInRoot:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quadInRoot"},{"kind":"text","text":" "},{"kind":"identifier","text":"crop:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"crop"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"confidence"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceWeight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"confidenceWeight"},{"kind":"text","text":";"}]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocument(im)initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:","title":"initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocument\/initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocument"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocument/initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocument\/initwithtype:fields:children:quad:quadinroot:crop:confidence:confidenceweight:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:","kind":"identifier"}],"title":"initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocument\/initWithType:fields:children:quad:quadInRoot:crop:confidence:confidenceWeight:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocument":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocument","title":"SBSDKCheckDocument","abstract":[{"text":"Represents a document specifically used for checking purposes, inheriting properties and methods from ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKCheckDocument","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentType":{"kind":"symbol","title":"SBSDKGenericDocumentType","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentType","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumenttype","abstract":[{"text":"Generic Document Type.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"title":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}],"type":"topic","abstract":[{"type":"text","text":"Image ref class."}],"url":"\/documentation\/scanbotsdk\/sbsdkimageref","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Generic document."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","title":"SBSDKGenericDocument"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocument\/title","op":"replace","value":"SBSDKCheckDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentType\/title","op":"replace","value":"SBSDKGenericDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentType\/fragments","value":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentType\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","value":"SBSDKImageRef","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRef"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}