{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage\/sbsdk_imageFiltered(by:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(sbsdk_imageFilteredWithFilters:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sbsdk_imageFiltered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"kind":"text","text":" "},{"text":"filters","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"]) -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The types of the filters to be applied."}]}],"name":"filters"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The filtered ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage\/sbsdk_imagefiltered(by:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK","relatedModules":["UIKit"]}],"symbolKind":"method","externalID":"c:@CM@ScanbotDocumentScannerSDK@@objc(cs)UIImage(im)sbsdk_imageFilteredWithFilters:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sbsdk_imageFiltered","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"title":"sbsdk_imageFiltered(by:)","roleHeading":"Instance Method","extendedModule":"UIKit"},"abstract":[{"type":"text","text":"Applies a filter to the receiver and returns the filtered image."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit/UIImage":{"navigatorTitle":[{"kind":"identifier","text":"UIImage"}],"title":"UIImage","abstract":[{"type":"text","text":"An "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" class extension to perform basic image processing operations."},{"type":"text","text":" "},{"type":"text","text":"Direct usage is not recommended for large images."},{"type":"text","text":" "},{"type":"text","text":"queues and proper memory management."}],"url":"\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"Base class for all parametric filters."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","type":"topic","role":"symbol","title":"SBSDKParametricFilter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","kind":"symbol","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit/UIImage/sbsdk_imageFiltered(by:)":{"role":"symbol","title":"sbsdk_imageFiltered(by:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageFiltered","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"kind":"text","text":": ["},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit\/UIImage\/sbsdk_imageFiltered(by:)","abstract":[{"text":"Applies a filter to the receiver and returns the filtered image.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/uikit\/uiimage\/sbsdk_imagefiltered(by:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/UIKit":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/UIKit","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/uikit","title":"UIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]}]}]}