{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFImageExtractor"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Asynchronously extracts images from a PDF, converts them to JPEGs and writes them to a specified URL."},{"type":"text","text":" "},{"type":"text","text":"The array of URLs is passed within the completion handler."}],"metadata":{"title":"extract(from:compression:encrypter:outputDirectory:completion:)","symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPDFImageExtractor(im)extractImageURLsFromPDF:compression:encrypter:outputDirectory:completion:","roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","navigatorTitle":[{"text":"extractImageURLsFromPDF:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfimageextractor\/extract(from:compression:encrypter:outputdirectory:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfimageextractor\/extract(from:compression:encrypter:outputdirectory:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFImageExtractor\/extract(from:compression:encrypter:outputDirectory:completion:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(extractImageURLsFromPDF:compression:encrypter:outputDirectory:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pdfURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ([","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"pdfURL","content":[{"inlineContent":[{"text":"The URL of the PDF file.","type":"text"}],"type":"paragraph"}]},{"name":"compression","content":[{"inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}],"type":"paragraph"}]},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}]}]},{"name":"outputDirectory","content":[{"inlineContent":[{"type":"text","text":"The output folder where images will be stored. If the folder does not exist, it will be created."}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"The completion handler that delivers the created array of image file URLs.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A progress object that can be used for cancellation and progress observing. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", an error occurred."}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","title":"SBSDKProgress"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFImageExtractor/extract(from:compression:encrypter:outputDirectory:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFImageExtractor\/extract(from:compression:encrypter:outputDirectory:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Asynchronously extracts images from a PDF, converts them to JPEGs and writes them to a specified URL."},{"type":"text","text":" "},{"type":"text","text":"The array of URLs is passed within the completion handler."}],"navigatorTitle":[{"text":"extractImageURLsFromPDF:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"title":"extract(from:compression:encrypter:outputDirectory:completion:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfimageextractor\/extract(from:compression:encrypter:outputdirectory:completion:)","role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCrypting"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"kind":"symbol","title":"SBSDKStorageCrypting","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFImageExtractor":{"navigatorTitle":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"title":"SBSDKPDFImageExtractor","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfimageextractor","abstract":[{"type":"text","text":"Class used to extract images from a PDF file and returns them in various ways."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFImageExtractor","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFImageExtractor","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"extractImageURLsFromPDF:compression:encrypter:outputDirectory:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extractImageURLsFromPDF:compression:encrypter:outputDirectory:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","kind":"typeIdentifier","text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"extractImageURLsFromPDF:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"compression:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"compression"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"id<SBSDKStorageCrypting>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"encrypter"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputDirectory:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outputDirectory"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSURL *>"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"pdfURL","content":[{"inlineContent":[{"type":"text","text":"The URL of the PDF file."}],"type":"paragraph"}]},{"name":"compression","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}]}]},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"text":"The encrypter used to encrypt output image files. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", no encryption is used.","type":"text"}]}]},{"name":"outputDirectory","content":[{"type":"paragraph","inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler that delivers the created array of image file URLs."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"text":"A progress object that can be used for cancellation and progress observing. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", an error occurred.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/title","value":"SBSDKProgress"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/fragments","value":[{"kind":"identifier","text":"SBSDKProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/navigatorTitle","value":[{"text":"SBSDKProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor~1extract(from:compression:encrypter:outputDirectory:completion:)\/title","value":"extractImageURLsFromPDF:compression:encrypter:outputDirectory:completion:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor~1extract(from:compression:encrypter:outputDirectory:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"extractImageURLsFromPDF:compression:encrypter:outputDirectory:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/title","value":"SBSDKStorageCrypting"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/navigatorTitle","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor\/title","value":"SBSDKPDFImageExtractor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor\/fragments","value":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor\/navigatorTitle","value":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}