{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/create(configuration:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/create(configuration:delegate:)"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/create(configuration:delegate:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"createWithConfiguration:delegate:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController(cm)createWithConfiguration:delegate:","title":"create(configuration:delegate:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerConfiguration"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUICheckRecognizerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUICheckRecognizerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController","text":"SBSDKUICheckRecognizerViewController","kind":"typeIdentifier"}],"roleHeading":"Type Method","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(createWithConfiguration:delegate:) "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerConfiguration"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate","text":"SBSDKUICheckRecognizerViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUICheckRecognizerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"text":"SBSDKUICheckRecognizerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The configuration to define look and feel of the new detection view controller.","type":"text"}],"type":"paragraph"}],"name":"configuration"},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate of the new detection view controller.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A new instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","isActive":true},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"]]},"kind":"symbol","abstract":[{"text":"Creates a new instance of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"},{"type":"text","text":"."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController/create(configuration:delegate:)":{"navigatorTitle":[{"text":"createWithConfiguration:delegate:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/create(configuration:delegate:)","kind":"symbol","type":"topic","title":"create(configuration:delegate:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/create(configuration:delegate:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUICheckRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerConfiguration"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUICheckRecognizerViewControllerDelegate","text":"SBSDKUICheckRecognizerViewControllerDelegate"},{"text":"?) -> ","kind":"text"},{"text":"SBSDKUICheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to recognize checks using the camera."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","type":"topic","title":"SBSDKUICheckRecognizerViewController","navigatorTitle":[{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}],"navigatorTitle":[{"text":"SBSDKUICheckRecognizerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerconfiguration","title":"SBSDKUICheckRecognizerConfiguration","role":"symbol","abstract":[{"type":"text","text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI check scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckRecognizerViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewControllerDelegate","title":"SBSDKUICheckRecognizerViewControllerDelegate","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontrollerdelegate","abstract":[{"text":"The delegation protocol for ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewControllerDelegate"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"createWithConfiguration:delegate:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithConfiguration:delegate:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","kind":"typeIdentifier","text":"SBSDKUICheckRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController"},{"kind":"text","text":" *) "},{"text":"createWithConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUICheckRecognizerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUICheckRecognizerViewControllerDelegate","text":"id<SBSDKUICheckRecognizerViewControllerDelegate>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController~1create(configuration:delegate:)\/title","op":"replace","value":"createWithConfiguration:delegate:"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithConfiguration:delegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController~1create(configuration:delegate:)\/fragments"},{"value":"SBSDKUICheckRecognizerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/title"},{"value":[{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/title","value":"SBSDKUICheckRecognizerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewControllerDelegate\/title","value":"SBSDKUICheckRecognizerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}