{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/enablecameratextconfiguration"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIEnableCameraTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration"},{"text":" * ","kind":"text"},{"text":"enableCameraTextConfiguration","kind":"identifier"},{"kind":"text","text":";"}]}]}],"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"enableCameraTextConfiguration","navigatorTitle":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"enableCameraTextConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController(py)enableCameraTextConfiguration","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/enableCameraTextConfiguration","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"title":"SBSDKUIEnableCameraTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of camera based view controllers."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController/enableCameraTextConfiguration":{"title":"enableCameraTextConfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/enableCameraTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/enablecameratextconfiguration","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"enableCameraTextConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to recognize checks using the camera."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","type":"topic","title":"SBSDKUICheckRecognizerViewController","navigatorTitle":[{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title","value":"SBSDKUIEnableCameraTextConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/title","value":"SBSDKUICheckRecognizerViewController"},{"value":[{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/fragments","op":"replace"}]}]}