{"metadata":{"role":"collectionGroup","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKCheckRecognizerViewControllerDelegate Implementations","roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/SBSDKCheckRecognizerViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"]]},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/checkRecognizerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/checkRecognizerViewController(_:didRecognizeCheck:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/sbsdkcheckrecognizerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/sbsdkcheckrecognizerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController":{"title":"SBSDKUICheckRecognizerViewController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}],"abstract":[{"type":"text","text":"A Ready-To-Use viewController to recognize checks using the camera."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController/checkRecognizerViewController(_:didRecognizeCheck:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/checkRecognizerViewController(_:didRecognizeCheck:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkRecognizerViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","text":"SBSDKCheckRecognizerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRecognizeCheck"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","kind":"typeIdentifier","text":"SBSDKCheckRecognizerResult"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Informs the delegate, that the check scanner has successfully detected and recognized a check."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/checkrecognizerviewcontroller(_:didrecognizecheck:)","navigatorTitle":[{"text":"checkRecognizerViewController:didRecognizeCheck:","kind":"identifier"}],"title":"checkRecognizerViewController(_:didRecognizeCheck:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController/checkRecognizerViewController(_:didChangeState:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/checkRecognizerViewController(_:didChangeState:)","navigatorTitle":[{"text":"checkRecognizerViewController:didChangeState:","kind":"identifier"}],"type":"topic","role":"symbol","title":"checkRecognizerViewController(_:didChangeState:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkRecognizerViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerViewController","kind":"typeIdentifier","text":"SBSDKCheckRecognizerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeState"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckRecognizerState","text":"SBSDKCheckRecognizerState"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/checkrecognizerviewcontroller(_:didchangestate:)","abstract":[{"text":"Informs the delegate, that the check scanner has changed its detection\/recognition state. Optional.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/checkRecognizerViewController(_:didChangeState:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/checkRecognizerViewController(_:didRecognizeCheck:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"SBSDKUICheckRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}]},{"value":"checkRecognizerViewController:didRecognizeCheck:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController~1checkRecognizerViewController(_:didRecognizeCheck:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController~1checkRecognizerViewController(_:didRecognizeCheck:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"checkRecognizerViewController:didRecognizeCheck:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController~1checkRecognizerViewController(_:didChangeState:)\/title","value":"checkRecognizerViewController:didChangeState:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController~1checkRecognizerViewController(_:didChangeState:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkRecognizerViewController:didChangeState:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}