{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"updateLayout","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/updatelayout"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/updateLayout"},"metadata":{"symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"updateLayout","kind":"identifier"}],"navigatorTitle":[{"text":"updateLayout","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerViewController(im)updateLayout","roleHeading":"Instance Method","title":"updateLayout"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICheckRecognizerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller","abstract":[{"type":"text","text":"A Ready-To-Use viewController to recognize checks using the camera."}],"type":"topic","title":"SBSDKUICheckRecognizerViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerViewController/updateLayout":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerViewController\/updateLayout","kind":"symbol","abstract":[],"type":"topic","title":"updateLayout","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"updateLayout","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"updateLayout"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizerviewcontroller\/updatelayout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/title","value":"SBSDKUICheckRecognizerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}