{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper\/init(document:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper\/init(document:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper\/init(document:)","interfaceLanguage":"swift"},"metadata":{"title":"init(document:)","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper(im)initWithGenericDocument:","role":"symbol","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithGenericDocument:) "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The wrapped document."}],"type":"paragraph"}],"name":"document"}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper\/requiredDocumentType","type":"reference","isActive":true},{"type":"text","text":" is not "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" and is not equal to the document’s type name."}]}],"type":"aside"}],"kind":"content"}],"abstract":[{"text":"Initializes a new wrapper of the given document.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"abstract":[{"type":"text","text":"Base class for strongly-typed "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"type":"text","text":" wrappers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","type":"topic","title":"SBSDKGenericDocumentWrapper"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","abstract":[{"type":"text","text":"Generic document."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}],"type":"topic","title":"SBSDKGenericDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper/requiredDocumentType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper\/requiredDocumentType","navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"abstract":[{"text":"The required type of the wrapped document. ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if this wrapper can wrap more than one type of document.","type":"text"}],"kind":"symbol","type":"topic","title":"requiredDocumentType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper\/requireddocumenttype","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper/init(document:)":{"title":"init(document:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper\/init(document:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"abstract":[{"type":"text","text":"Initializes a new wrapper of the given document."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper\/init(document:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument"},{"kind":"text","text":"?)"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithGenericDocument:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"document","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The wrapped document."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title","op":"replace","value":"SBSDKGenericDocumentWrapper"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper~1requiredDocumentType\/title","value":"requiredDocumentType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper~1requiredDocumentType\/fragments","value":[{"text":"requiredDocumentType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper~1init(document:)\/title","value":"initWithGenericDocument:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper~1init(document:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}