{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:minprocessedfraction:maxprocessedfraction:earlystopifnsymbolsfound:tilesize:returnqualityheatmap:"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration"]]},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration(im)initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","fragments":[{"kind":"text","text":"- "},{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithQualityThresholds:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKDocumentQualityThreshold *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"qualityThresholds"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityIndices:"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKDocumentQuality *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"qualityIndices"},{"text":" ","kind":"text"},{"text":"detectOrientation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"detectOrientation","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inspectSmallText:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"inspectSmallText"},{"text":" ","kind":"text"},{"text":"maxImageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"maxImageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minEstimatedNumberOfSymbolsForDocument:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minEstimatedNumberOfSymbolsForDocument","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"minProcessedFraction:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minProcessedFraction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxProcessedFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"maxProcessedFraction"},{"kind":"text","text":" "},{"text":"earlyStopIfNSymbolsFound:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"earlyStopIfNSymbolsFound","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tileSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tileSize"},{"text":" ","kind":"text"},{"text":"returnQualityHeatmap:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"returnQualityHeatmap","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:":{"type":"topic","title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:minprocessedfraction:maxprocessedfraction:earlystopifnsymbolsfound:tilesize:returnqualityheatmap:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration","role":"symbol","kind":"symbol","title":"SBSDKDocumentQualityAnalyzerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration","type":"topic","abstract":[{"type":"text","text":"Document Quality Analyzer configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKDocumentQualityAnalyzerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle","value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}