{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/tilesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/tilesize"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 300"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/tileSize"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"tileSize"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration(py)tileSize","modules":[{"name":"ScanbotSDK"}],"title":"tileSize"},"abstract":[{"type":"text","text":"Image will be processed in tiles of this size; will be ignored if image is small."}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration/tileSize":{"navigatorTitle":[{"text":"tileSize","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration\/tilesize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/tileSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tileSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Image will be processed in tiles of this size; will be ignored if image is small."}],"kind":"symbol","title":"tileSize","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"title":"SBSDKDocumentQualityAnalyzerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerconfiguration","role":"symbol","abstract":[{"text":"Document Quality Analyzer configuration.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"tileSize","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"tileSize","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"tileSize","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"tileSize","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1tileSize\/title"},{"op":"replace","value":[{"text":"tileSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1tileSize\/fragments"},{"op":"replace","value":"SBSDKDocumentQualityAnalyzerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}