{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot\/initWithImageRefProfiles:totalMemoryConsumption:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshot\/initwithimagerefprofiles:totalmemoryconsumption:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot(im)initWithImageRefProfiles:totalMemoryConsumption:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageRefProfiles:totalMemoryConsumption:"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImageRefProfiles:totalMemoryConsumption:"}],"title":"initWithImageRefProfiles:totalMemoryConsumption:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithImageRefProfiles:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKImageRefProfile *>"},{"text":" *) ","kind":"text"},{"text":"imageRefProfiles","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"totalMemoryConsumption:","kind":"identifier"},{"kind":"text","text":"("},{"text":"int64_t","preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"totalMemoryConsumption","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefPoolSnapshot/initWithImageRefProfiles:totalMemoryConsumption:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageRefProfiles:totalMemoryConsumption:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot\/initWithImageRefProfiles:totalMemoryConsumption:","url":"\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshot\/initwithimagerefprofiles:totalmemoryconsumption:","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithImageRefProfiles:totalMemoryConsumption:","kind":"identifier"}],"title":"initWithImageRefProfiles:totalMemoryConsumption:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefPoolSnapshot":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshot","abstract":[{"type":"text","text":"Snapshot of all alive ImageRefs."}],"type":"topic","title":"SBSDKImageRefPoolSnapshot","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/title","op":"replace","value":"SBSDKImageRefPoolSnapshot"},{"op":"replace","value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle"}]}]}