{"sections":[],"abstract":[{"type":"text","text":"Initializes a new "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","isActive":true,"type":"reference"},{"type":"text","text":" at the given storage location with given image file format."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"storageLocation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"text":"fileFormat","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}]}],"name":"storageLocation"},{"name":"fileFormat","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file format that should be used to store the images."}]}]},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"text":"The encrypter used to encrypt\/decrypt image data.If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", no encryption is used.","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"init","title":"init(storageLocation:fileFormat:encrypter:)","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKIndexedImageStorage(im)initWithStorageLocation:fileFormat:encrypter:","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fileFormat"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?)","kind":"text"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"title":"SBSDKStorageCrypting"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/init(storageLocation:fileFormat:encrypter:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"text":"fileFormat","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"text":"?)","kind":"text"}],"title":"init(storageLocation:fileFormat:encrypter:)","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:"}],"abstract":[{"text":"Initializes a new ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","isActive":true},{"type":"text","text":" at the given storage location with given image file format."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageFileFormat":{"role":"symbol","navigatorTitle":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageFileFormat"}],"type":"topic","title":"SBSDKImageFileFormat","url":"\/documentation\/scanbotsdk\/sbsdkimagefileformat","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","abstract":[{"text":"Enumeration of supported image file types.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage":{"kind":"symbol","title":"SBSDKIndexedImageStorage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Manages images in an array-like fashion."}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageLocation":{"abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragelocation","title":"SBSDKStorageLocation","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithStorageLocation:fileFormat:encrypter:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithStorageLocation:fileFormat:encrypter:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithStorageLocation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageLocation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"storageLocation"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileFormat:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageFileFormat","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageFileFormat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"fileFormat"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encrypter:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<SBSDKStorageCrypting>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"encrypter"},{"text":";","kind":"text"}]}]}},{"value":{"parameters":[{"name":"storageLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The file format that should be used to store the images."}],"type":"paragraph"}],"name":"fileFormat"},{"content":[{"inlineContent":[{"type":"text","text":"The encrypter used to encrypt\/decrypt image data.If "},{"type":"codeVoice","code":"nil"},{"text":", no encryption is used.","type":"text"}],"type":"paragraph"}],"name":"encrypter"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKStorageCrypting","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/title","value":"initWithStorageLocation:fileFormat:encrypter:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:fileFormat:encrypter:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/title","value":"SBSDKImageFileFormat","op":"replace"},{"value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageFileFormat\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/title","value":"SBSDKIndexedImageStorage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/navigatorTitle","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/title","value":"SBSDKStorageLocation","op":"replace"},{"op":"replace","value":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageLocation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}]}]}]}