{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkrawimageloadoptions\/initwithroi:orientation:"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithRoi:orientation:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithRoi:orientation:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithRoi:orientation:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRawImageLoadOptions(im)initWithRoi:orientation:","symbolKind":"method"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions\/initWithRoi:orientation:","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRoi:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"roi"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageRotation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"orientation"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRawImageLoadOptions/initWithRoi:orientation:":{"type":"topic","abstract":[],"title":"initWithRoi:orientation:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions\/initWithRoi:orientation:","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrawimageloadoptions\/initwithroi:orientation:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRoi:orientation:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRoi:orientation:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRawImageLoadOptions":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"abstract":[{"type":"text","text":"Options for loading images that come from sensor."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"url":"\/documentation\/scanbotsdk\/sbsdkrawimageloadoptions","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRawImageLoadOptions","title":"SBSDKRawImageLoadOptions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRotation":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRotation","url":"\/documentation\/scanbotsdk\/sbsdkimagerotation","title":"SBSDKImageRotation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRotation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotation"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image rotation."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/title","value":"SBSDKRawImageLoadOptions","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRawImageLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKRawImageLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/title","value":"SBSDKImageRotation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/fragments","value":[{"text":"SBSDKImageRotation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRotation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"op":"replace"}]}]}