{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"relevantInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplanmedicinefieldtype\/relevantinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplanmedicinefieldtype\/relevantinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanMedicineFieldType\/relevantInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The relevant info."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"relevantInfo"}],"title":"SBSDKMedicalPlanMedicineFieldType.relevantInfo","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanMedicineFieldType@SBSDKMedicalPlanMedicineFieldTypeRelevantInfo","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineFieldTypeRelevantInfo"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanMedicineFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanMedicineFieldType/relevantInfo":{"role":"symbol","title":"SBSDKMedicalPlanMedicineFieldType.relevantInfo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"relevantInfo"}],"abstract":[{"type":"text","text":"The relevant info."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanMedicineFieldType\/relevantInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineFieldTypeRelevantInfo"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanmedicinefieldtype\/relevantinfo"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanMedicineFieldType":{"role":"symbol","title":"SBSDKMedicalPlanMedicineFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanMedicineFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document medicine information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanMedicineFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanmedicinefieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalPlanMedicineFieldTypeRelevantInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineFieldTypeRelevantInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineFieldTypeRelevantInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanMedicineFieldType~1relevantInfo\/title","value":"SBSDKMedicalPlanMedicineFieldTypeRelevantInfo"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanMedicineFieldType~1relevantInfo\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineFieldTypeRelevantInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanMedicineFieldType\/title","value":"SBSDKMedicalPlanMedicineFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanMedicineFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanMedicineFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}