{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration(py)processingMode","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processingMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKProcessingMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode"}],"title":"processingMode","navigatorTitle":[{"text":"processingMode","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"]]},"kind":"symbol","abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/processingmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/processingmode"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"processingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results."},{"type":"text","text":" "},{"type":"text","text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Default is AUTO"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/processingMode","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","navigatorTitle":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the check scanner.","type":"text"}],"title":"SBSDKCheckScannerConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it."},{"type":"text","text":" "},{"type":"text","text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results."},{"type":"text","text":" "},{"type":"text","text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject."}],"navigatorTitle":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingMode","kind":"identifier"}],"title":"SBSDKProcessingMode","url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration/processingMode":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/processingmode","navigatorTitle":[{"text":"processingMode","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processingMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/processingMode","title":"processingMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"processingMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"processingMode"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode","kind":"typeIdentifier","text":"SBSDKProcessingMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode"},{"text":" ","kind":"text"},{"text":"processingMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/title","op":"replace","value":"SBSDKCheckScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/fragments","value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/title","value":"SBSDKProcessingMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration~1processingMode\/title","value":"processingMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration~1processingMode\/fragments","value":[{"text":"processingMode","kind":"identifier"}]}]}]}