{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration\/errorDialogStyle"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration"]]},"abstract":[{"text":"The style of the dialog\/alert in case of error.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerUIConfiguration(py)errorDialogStyle","title":"errorDialogStyle","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDialogStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"errorDialogStyle"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDialogStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUIDialogStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration\/errordialogstyle"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration\/errordialogstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerUIConfiguration":{"abstract":[{"text":"Configuration for the user interface of the RTU-UI check scanner.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerUIConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICheckRecognizerUIConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration","title":"SBSDKUICheckRecognizerUIConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogStyle":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUIDialogStyle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidialogstyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIDialogStyle"}],"title":"SBSDKUIDialogStyle","abstract":[{"text":"The general style for a dialog in ScanbotSDK. Used to customize certain result dialogs in SBSDKUI components.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerUIConfiguration/errorDialogStyle":{"abstract":[{"type":"text","text":"The style of the dialog\/alert in case of error."}],"title":"errorDialogStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration\/errorDialogStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDialogStyle"},{"text":": ","kind":"text"},{"text":"SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration\/errordialogstyle","navigatorTitle":[{"kind":"identifier","text":"errorDialogStyle"}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"errorDialogStyle","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"errorDialogStyle"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKUIDialogStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"errorDialogStyle"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKUICheckRecognizerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerUIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration\/fragments"},{"op":"replace","value":"SBSDKUIDialogStyle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogStyle\/title"},{"op":"replace","value":[{"text":"SBSDKUIDialogStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration~1errorDialogStyle\/title","value":"errorDialogStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration~1errorDialogStyle\/fragments","op":"replace","value":[{"text":"errorDialogStyle","kind":"identifier"}]}]}]}