{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"orientationLockMode"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckRecognizerUIConfiguration(py)orientationLockMode","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"}],"roleHeading":"Instance Property","title":"orientationLockMode"},"abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration\/orientationLockMode"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","text":"SBSDKOrientationLock"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration\/orientationlockmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration\/orientationlockmode"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerUIConfiguration/orientationLockMode":{"abstract":[{"text":"Allowed orientations for automatic interface rotations.","type":"text"}],"navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration\/orientationLockMode","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","text":"SBSDKOrientationLock"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration\/orientationlockmode","type":"topic","title":"orientationLockMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckRecognizerUIConfiguration":{"abstract":[{"text":"Configuration for the user interface of the RTU-UI check scanner.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckRecognizerUIConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckRecognizerUIConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICheckRecognizerUIConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckrecognizeruiconfiguration","title":"SBSDKUICheckRecognizerUIConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOrientationLock":{"abstract":[{"text":"This enum describes the available orientation lock modes for the user interface.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOrientationLock"}],"url":"\/documentation\/scanbotsdk\/sbsdkorientationlock","type":"topic","title":"SBSDKOrientationLock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"orientationLockMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"orientationLockMode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","text":"SBSDKOrientationLock","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration~1orientationLockMode\/title","value":"orientationLockMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration~1orientationLockMode\/fragments","value":[{"text":"orientationLockMode","kind":"identifier"}]},{"value":"SBSDKUICheckRecognizerUIConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckRecognizerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckRecognizerUIConfiguration"}]},{"op":"replace","value":"SBSDKOrientationLock","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/title"},{"value":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}