{"metadata":{"roleHeading":"Type Method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scanbotOCR","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration(cm)scanbotOCR","navigatorTitle":[{"text":"scanbotOCR","kind":"identifier"}],"title":"scanbotOCR()","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/scanbotocr()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/scanbotocr()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/scanbotOCR()"},"abstract":[{"type":"text","text":"Creates an OCR configuration using the mode "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/scanbotOCR","isActive":true},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanbotOCR","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration"}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The new OCR configuration object.","type":"text"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode/scanbotOCR":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineModeScanbotOCR"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanbotOCR"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode\/scanbotocr","abstract":[{"type":"text","text":"The new machine-learning based mode made by Scanbot SDK GmbH. Faster, less errors, but currently only"},{"type":"text","text":" "},{"type":"text","text":"supports languages with latin letters."}],"title":"SBSDKOCREngineMode.scanbotOCR","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/scanbotOCR"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/scanbotOCR()":{"navigatorTitle":[{"kind":"identifier","text":"scanbotOCR"}],"role":"symbol","title":"scanbotOCR()","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/scanbotocr()","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/scanbotOCR()","abstract":[{"text":"Creates an OCR configuration using the mode ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/scanbotOCR","type":"reference"},{"text":".","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanbotOCR","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration":{"abstract":[{"type":"text","text":"A class describing the configuration of the optical character recognizer (OCR) engine."}],"url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKOCREngineConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"scanbotOCR","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"scanbotOCR"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","kind":"typeIdentifier","text":"SBSDKOCREngineConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration"},{"kind":"text","text":" *) "},{"text":"scanbotOCR","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The new OCR configuration object."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","value":"SBSDKOCREngineModeScanbotOCR","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1scanbotOCR\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1scanbotOCR\/fragments","value":[{"kind":"identifier","text":"SBSDKOCREngineModeScanbotOCR"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1scanbotOCR()\/title","value":"scanbotOCR"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1scanbotOCR()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"scanbotOCR"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/title","value":"SBSDKOCREngineConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}