{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"toJson(configuration:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerConfiguration(im)toJsonWithConfiguration:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration\/tojson(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration\/tojson(configuration:)"]}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKToJSONConfiguration()) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration\/toJson(configuration:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKToJSONConfiguration":{"kind":"symbol","title":"SBSDKToJSONConfiguration","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktojsonconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration used to serialize an object to json."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration","navigatorTitle":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerConfiguration/toJson(configuration:)":{"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration\/tojson(configuration:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration\/toJson(configuration:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerConfiguration":{"title":"SBSDKBarcodeScannerConfiguration","abstract":[{"type":"text","text":"Configuration for the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"toJsonWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKToJSONConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/fragments"},{"value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/navigatorTitle"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration~1toJson(configuration:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration~1toJson(configuration:)\/fragments"},{"value":"SBSDKBarcodeScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle"}]}]}