{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile\/fromjsonwithjson:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile\/fromJsonWithJson:"},"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefProfile(cm)fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"fromJsonWithJson:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefProfile","text":"SBSDKImageRefProfile","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfile":{"role":"symbol","title":"SBSDKImageRefProfile","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfile"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"kind":"symbol","abstract":[{"type":"text","text":"ImageRef profile which provides detailed information about stored object."}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfile/fromJsonWithJson:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofile\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfile\/fromJsonWithJson:","abstract":[],"title":"fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKImageRefProfile","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfile\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}