{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A check has been recognized and validated successfully.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus\/success","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKCheckRecognitionResultStatus@SBSDKCheckRecognitionResultStatusSuccess","roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKCheckRecognitionResultStatusSuccess","kind":"identifier"}],"title":"SBSDKCheckRecognitionResultStatus.success","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus\/success"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus\/success"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognitionResultStatus":{"navigatorTitle":[{"text":"SBSDKCheckRecognitionResultStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus","type":"topic","kind":"symbol","abstract":[{"text":"An enum describing the status of a check recognition.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognitionResultStatus","kind":"identifier"}],"title":"SBSDKCheckRecognitionResultStatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognitionResultStatus/success":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognitionResultStatusSuccess"}],"abstract":[{"text":"A check has been recognized and validated successfully.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus\/success","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus\/success","title":"SBSDKCheckRecognitionResultStatus.success","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKCheckRecognitionResultStatusSuccess","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckRecognitionResultStatusSuccess"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SBSDKCheckRecognitionResultStatusSuccess","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus\/title","value":"SBSDKCheckRecognitionResultStatus"},{"op":"replace","value":[{"text":"SBSDKCheckRecognitionResultStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus~1success\/title","value":"SBSDKCheckRecognitionResultStatusSuccess"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckRecognitionResultStatusSuccess"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus~1success\/fragments"}]}]}