{"sections":[],"abstract":[{"text":"A check has been recognized but the validation of its content has been failed.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus\/validationFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationFailed"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"case","title":"SBSDKCheckRecognitionResultStatus.validationFailed","externalID":"c:@M@ScanbotSDK@E@SBSDKCheckRecognitionResultStatus@SBSDKCheckRecognitionResultStatusValidationFailed","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKCheckRecognitionResultStatusValidationFailed","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationFailed"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus\/validationfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus\/validationfailed"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognitionResultStatus/validationFailed":{"abstract":[{"type":"text","text":"A check has been recognized but the validation of its content has been failed."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus\/validationFailed","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKCheckRecognitionResultStatusValidationFailed","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationFailed"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus\/validationfailed","role":"symbol","title":"SBSDKCheckRecognitionResultStatus.validationFailed"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognitionResultStatus":{"abstract":[{"text":"An enum describing the status of a check recognition.","type":"text"}],"title":"SBSDKCheckRecognitionResultStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognitionResultStatus","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKCheckRecognitionResultStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognitionResultStatus","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognitionresultstatus","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCheckRecognitionResultStatusValidationFailed"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKCheckRecognitionResultStatusValidationFailed","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKCheckRecognitionResultStatusValidationFailed","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus~1validationFailed\/title","value":"SBSDKCheckRecognitionResultStatusValidationFailed","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus~1validationFailed\/fragments","value":[{"text":"SBSDKCheckRecognitionResultStatusValidationFailed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus\/title","value":"SBSDKCheckRecognitionResultStatus","op":"replace"},{"value":[{"text":"SBSDKCheckRecognitionResultStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognitionResultStatus\/fragments","op":"replace"}]}]}