{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanMedicine","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanMedicine","text":"SBSDKUI2MedicalPlanMedicine"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalplanstandardsubheading\/medicines"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalplanstandardsubheading\/medicines"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanStandardSubheading\/medicines","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Medicines"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalPlanMedicine","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanMedicine"},{"kind":"text","text":"]"}],"title":"medicines","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanStandardSubheading(py)medicines","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"medicines"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanStandardSubheading"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanStandardSubheading/medicines":{"role":"symbol","title":"medicines","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalPlanMedicine","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanMedicine"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Medicines"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanStandardSubheading\/medicines","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"medicines"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplanstandardsubheading\/medicines"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanStandardSubheading":{"role":"symbol","title":"SBSDKUI2MedicalPlanStandardSubheading","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheading"}],"abstract":[{"type":"text","text":"Medical Plan Standard Subheading"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanStandardSubheading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheading"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplanstandardsubheading"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanMedicine":{"role":"symbol","title":"SBSDKUI2MedicalPlanMedicine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicine"}],"abstract":[{"type":"text","text":"Medical Plan Medicine"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanMedicine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicine"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplanmedicine"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"medicines"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"medicines"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2MedicalPlanMedicine *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"medicines"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanStandardSubheading~1medicines\/title","value":"medicines"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanStandardSubheading~1medicines\/fragments","value":[{"kind":"identifier","text":"medicines"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanStandardSubheading\/title","value":"SBSDKUI2MedicalPlanStandardSubheading"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanStandardSubheading\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheading"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanMedicine\/title","value":"SBSDKUI2MedicalPlanMedicine"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanMedicine\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicine"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}