{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanSubheadingPrescription","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanSubheadingPrescription","text":"SBSDKUI2MedicalPlanSubheadingPrescription"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalplanstandardsubheading\/prescriptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalplanstandardsubheading\/prescriptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanStandardSubheading\/prescriptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Prescriptions"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalPlanSubheadingPrescription","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanSubheadingPrescription"},{"kind":"text","text":"]"}],"title":"prescriptions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanStandardSubheading(py)prescriptions","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"prescriptions"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanStandardSubheading"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanStandardSubheading":{"role":"symbol","title":"SBSDKUI2MedicalPlanStandardSubheading","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheading"}],"abstract":[{"type":"text","text":"Medical Plan Standard Subheading"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanStandardSubheading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheading"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplanstandardsubheading"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanSubheadingPrescription":{"role":"symbol","title":"SBSDKUI2MedicalPlanSubheadingPrescription","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescription"}],"abstract":[{"type":"text","text":"Medical Plan Subheading Prescription."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanSubheadingPrescription","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescription"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplansubheadingprescription"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanStandardSubheading/prescriptions":{"role":"symbol","title":"prescriptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2MedicalPlanSubheadingPrescription","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MedicalPlanSubheadingPrescription"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Prescriptions"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanStandardSubheading\/prescriptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prescriptions"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplanstandardsubheading\/prescriptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"prescriptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"prescriptions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2MedicalPlanSubheadingPrescription *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"prescriptions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanStandardSubheading\/title","value":"SBSDKUI2MedicalPlanStandardSubheading"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanStandardSubheading\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheading"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanSubheadingPrescription\/title","value":"SBSDKUI2MedicalPlanSubheadingPrescription"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanSubheadingPrescription\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescription"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanStandardSubheading~1prescriptions\/title","value":"prescriptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanStandardSubheading~1prescriptions\/fragments","value":[{"kind":"identifier","text":"prescriptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}