{"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration\/isPinchToZoomEnabled","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"isPinchToZoomEnabled","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"isPinchToZoomEnabled","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(py)isPinchToZoomEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPinchToZoomEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"When this property is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the camera zoom can be controlled by a pinch gesture anywhere in the base scannner view controllers view."},{"type":"text","text":" "},{"type":"text","text":"If set to "},{"code":"false","type":"codeVoice"},{"type":"text","text":", zooming by pinching will be disabled."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPinchToZoomEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerZoomConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"kind":"symbol","title":"SBSDKBaseScannerZoomConfiguration","abstract":[{"type":"text","text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera."},{"type":"text","text":" "},{"type":"text","text":"This class lets you customize the zooming user experience."}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerZoomConfiguration/isPinchToZoomEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPinchToZoomEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerZoomConfiguration\/isPinchToZoomEnabled","kind":"symbol","navigatorTitle":[{"text":"isPinchToZoomEnabled","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerzoomconfiguration\/ispinchtozoomenabled","role":"symbol","type":"topic","abstract":[{"text":"When this property is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", the camera zoom can be controlled by a pinch gesture anywhere in the base scannner view controllers view.","type":"text"},{"text":" ","type":"text"},{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"false"},{"text":", zooming by pinching will be disabled.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"title":"isPinchToZoomEnabled"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isPinchToZoomEnabled","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isPinchToZoomEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isPinchToZoomEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBaseScannerZoomConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerZoomConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration\/navigatorTitle"},{"value":"isPinchToZoomEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration~1isPinchToZoomEnabled\/title"},{"value":[{"kind":"identifier","text":"isPinchToZoomEnabled"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerZoomConfiguration~1isPinchToZoomEnabled\/fragments"}]}]}