{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lazyWithCopy","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKPathLoadMode@SBSDKPathLoadModeLazyWithCopy","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadModeLazyWithCopy"}],"roleHeading":"Case","symbolKind":"case","title":"SBSDKPathLoadMode.lazyWithCopy","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lazyWithCopy"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/lazyWithCopy","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/lazywithcopy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/lazywithcopy"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode"]]},"sections":[],"abstract":[{"text":"Image is loaded into memory the first time it’s requested. Specified path is copied into internal directory and","type":"text"},{"text":" ","type":"text"},{"text":"so isn’t required to exist at the time of loading.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode","type":"topic","role":"symbol","abstract":[{"text":"Image Ref Path Load Mode.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPathLoadMode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadMode"}],"title":"SBSDKPathLoadMode","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathLoadMode/lazyWithCopy":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadModeLazyWithCopy"}],"title":"SBSDKPathLoadMode.lazyWithCopy","abstract":[{"type":"text","text":"Image is loaded into memory the first time it’s requested. Specified path is copied into internal directory and"},{"text":" ","type":"text"},{"text":"so isn’t required to exist at the time of loading.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathloadmode\/lazywithcopy","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lazyWithCopy","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathLoadMode\/lazyWithCopy","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"SBSDKPathLoadModeLazyWithCopy","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKPathLoadModeLazyWithCopy"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKPathLoadModeLazyWithCopy","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/title","value":"SBSDKPathLoadMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPathLoadMode"}]},{"value":[{"text":"SBSDKPathLoadMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode~1lazyWithCopy\/title","value":"SBSDKPathLoadModeLazyWithCopy","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathLoadMode~1lazyWithCopy\/fragments","op":"replace","value":[{"text":"SBSDKPathLoadModeLazyWithCopy","kind":"identifier"}]}]}]}