{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/isEqual:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatQRCodeConfiguration(im)isEqual:","symbolKind":"method","title":"isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/isEqual:":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/isEqual:","title":"isEqual:","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration","title":"SBSDKBarcodeFormatQRCodeConfiguration","abstract":[{"type":"text","text":"QR Code configuration. Add to scanner configuration to scan QR codes, Micro QR codes and rectangular Micro QR (rMQR)"},{"type":"text","text":" "},{"type":"text","text":"codes."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/title","value":"SBSDKBarcodeFormatQRCodeConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}]}]}]}