{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/UIViewControllerTransitioningDelegate-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"interactionControllerForDismissal","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"using"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animator"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewControllerInteractiveTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerInteractiveTransitioning"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/interactioncontrollerfordismissal(using:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/interactioncontrollerfordismissal(using:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"interactionControllerForDismissal:"}],"title":"interactionControllerForDismissal(using:)","role":"symbol","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorViewController(im)interactionControllerForDismissal:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interactionControllerForDismissal"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerInteractiveTransitioning","text":"UIViewControllerInteractiveTransitioning"},{"kind":"text","text":"?"}],"extendedModule":"ScanbotSDK"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIViewControllerTransitioningDelegate.interactionControllerForDismissal(using:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/interactionControllerForDismissal(using:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController/UIViewControllerTransitioningDelegate-Implementations":{"kind":"article","title":"UIViewControllerTransitioningDelegate Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/UIViewControllerTransitioningDelegate-Implementations","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/uiviewcontrollertransitioningdelegate-implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController/interactionControllerForDismissal(using:)":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller\/interactioncontrollerfordismissal(using:)","title":"interactionControllerForDismissal(using:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController\/interactionControllerForDismissal(using:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"interactionControllerForDismissal","kind":"identifier"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":") -> "},{"text":"UIViewControllerInteractiveTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerInteractiveTransitioning"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"interactionControllerForDismissal:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorViewController":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorviewcontroller","abstract":[{"text":"A highly customizable camera-based view controller to extract generic documents data.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorViewController","kind":"symbol","title":"SBSDKUIDocumentDataExtractorViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"interactionControllerForDismissal:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"interactionControllerForDismissal:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qoobjc(pl)UIViewControllerInteractiveTransitioning","text":"id<UIViewControllerInteractiveTransitioning>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"interactionControllerForDismissal:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIViewControllerAnimatedTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":") "},{"text":"animator","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController~1interactionControllerForDismissal(using:)\/title","value":"interactionControllerForDismissal:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController~1interactionControllerForDismissal(using:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"interactionControllerForDismissal:","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUIDocumentDataExtractorViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/fragments","value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorViewController\/navigatorTitle","value":[{"text":"SBSDKUIDocumentDataExtractorViewController","kind":"identifier"}]}]}]}