{"abstract":[{"text":"Document type name of the “UnknownCheck” document type.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants\/unknownCheckDocumentType"},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelConstants(cpy)unknownCheckDocumentType","title":"unknownCheckDocumentType","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownCheckDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"text":"unknownCheckDocumentType","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownCheckDocumentType"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/unknowncheckdocumenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/unknowncheckdocumenttype"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelConstants/unknownCheckDocumentType":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownCheckDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants\/unknownCheckDocumentType","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/unknowncheckdocumenttype","abstract":[{"text":"Document type name of the “UnknownCheck” document type.","type":"text"}],"title":"unknownCheckDocumentType","type":"topic","navigatorTitle":[{"text":"unknownCheckDocumentType","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelConstants":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelConstants","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants","abstract":[],"role":"symbol","navigatorTitle":[{"text":"SBSDKCheckDocumentModelConstants","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants","type":"topic","title":"SBSDKCheckDocumentModelConstants"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"unknownCheckDocumentType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"unknownCheckDocumentType"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"unknownCheckDocumentType"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants~1unknownCheckDocumentType\/title","op":"replace","value":"unknownCheckDocumentType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants~1unknownCheckDocumentType\/fragments","op":"replace","value":[{"text":"unknownCheckDocumentType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/title","value":"SBSDKCheckDocumentModelConstants","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelConstants"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/navigatorTitle","value":[{"text":"SBSDKCheckDocumentModelConstants","kind":"identifier"}],"op":"replace"}]}]}