{"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","title":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","interfaceLanguage":"swift"},"abstract":[{"text":"Name of the “TimesOfExitAndEntry” field type in document type “CnEntryAndExitPermitFront”.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitfronttimesofexitandentryfieldname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitfronttimesofexitandentryfieldname"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName":{"navigatorTitle":[{"text":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","title":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitfronttimesofexitandentryfieldname","abstract":[{"text":"Name of the “TimesOfExitAndEntry” field type in document type “CnEntryAndExitPermitFront”.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"navigatorTitle":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"title":"SBSDKDocumentsModelConstants","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName\/title"},{"op":"replace","value":[{"text":"cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1cnEntryAndExitPermitFrontTimesOfExitAndEntryFieldName\/fragments"},{"op":"replace","value":"SBSDKDocumentsModelConstants","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}