{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"parentViewController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate"},{"text":"?)","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerViewController(im)initWithParentViewController:parentView:delegate:","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"platforms":[],"role":"symbol","title":"init(parentViewController:parentView:delegate:)","symbolKind":"init"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController\/init(parentViewController:parentView:delegate:)","interfaceLanguage":"swift"},"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controller’s view using its entire bounds area.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithParentViewController:parentView:delegate:) "},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"parentViewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"parentViewController","content":[{"type":"paragraph","inlineContent":[{"text":"The view controller the newly created instance is embedded into.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The view the newly created instance is embedded into.","type":"text"}]}],"name":"parentView"},{"name":"delegate","content":[{"inlineContent":[{"text":"The delegate of the receiver.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController"]]},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please consider using SBSDKDocumentDataExtractorViewController."}],"type":"paragraph"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller\/init(parentviewcontroller:parentview:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller\/init(parentviewcontroller:parentview:delegate:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewController":{"role":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"title":"SBSDKHealthInsuranceCardRecognizerViewController","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to scan health insurance cards with the camera.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate":{"type":"topic","title":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","abstract":[{"type":"text","text":"The delegation protocol for the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController","type":"reference","isActive":true},{"type":"text","text":" class."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","deprecated":true,"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerViewController/init(parentViewController:parentView:delegate:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerViewController\/init(parentViewController:parentView:delegate:)","abstract":[{"type":"text","text":"Installs the receiver as child view controller onto the parent view controller’s view using its entire bounds area."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"deprecated":true,"type":"topic","navigatorTitle":[{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerviewcontroller\/init(parentviewcontroller:parentview:delegate:)","title":"init(parentViewController:parentView:delegate:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithParentViewController:parentView:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParentViewController:parentView:delegate:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithParentViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"parentViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"parentView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parentView"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate:"},{"text":"(","kind":"text"},{"text":"id<SBSDKHealthInsuranceCardRecognizerViewControllerDelegate>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller the newly created instance is embedded into."}]}],"name":"parentViewController"},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view the newly created instance is embedded into."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The delegate of the receiver."}],"type":"paragraph"}],"name":"delegate"}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/title","op":"replace","value":"SBSDKHealthInsuranceCardRecognizerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"identifier"}]},{"op":"replace","value":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewControllerDelegate\/title"},{"value":[{"text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithParentViewController:parentView:delegate:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController~1init(parentViewController:parentView:delegate:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithParentViewController:parentView:delegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerViewController~1init(parentViewController:parentView:delegate:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}