{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"captureOutput(_:didOutput:from:)","extendedModule":"ScanbotBarcodeScannerSDK","role":"symbol","externalID":"c:@CM@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession(im)captureOutput:didOutputSampleBuffer:fromConnection:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureOutput","text":"AVCaptureOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureConnection","preciseIdentifier":"c:objc(cs)AVCaptureConnection"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/captureoutput(_:didoutput:from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/captureoutput(_:didoutput:from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"output","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureOutput","text":"AVCaptureOutput","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didOutput","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"connection","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureConnection","text":"AVCaptureConnection","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AVCaptureVideoDataOutputSampleBufferDelegate.captureOutput(_:didOutput:from:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/captureOutput(_:didOutput:from:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraSession"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraSession"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"title":"SBSDKCameraSession","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession/captureOutput(_:didOutput:from:)":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/captureoutput(_:didoutput:from:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/captureOutput(_:didOutput:from:)","title":"captureOutput(_:didOutput:from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureOutput","preciseIdentifier":"c:objc(cs)AVCaptureOutput","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didOutput","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureConnection","preciseIdentifier":"c:objc(cs)AVCaptureConnection","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/avcapturevideodataoutputsamplebufferdelegate-implementations","abstract":[],"role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations","kind":"article","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"captureOutput:didOutputSampleBuffer:fromConnection:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"captureOutput:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureOutput","preciseIdentifier":"c:objc(cs)AVCaptureOutput","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"output","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didOutputSampleBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fromConnection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureConnection","preciseIdentifier":"c:objc(cs)AVCaptureConnection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"connection","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1captureOutput(_:didOutput:from:)\/title","value":"captureOutput:didOutputSampleBuffer:fromConnection:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1captureOutput(_:didOutput:from:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}],"op":"replace"}]}]}