{"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"isEqual:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration(im)isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration\/isequal:"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration\/isEqual:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentPolygonConfiguration/isEqual:":{"kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","abstract":[],"title":"isEqual:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentPolygonConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration","abstract":[{"text":"Configuration of the document contour detection polygon.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}],"title":"SBSDKUI2DocumentPolygonConfiguration","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2DocumentPolygonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/navigatorTitle"}]}]}