{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode"]]},"abstract":[{"text":"AES128 mode with a key length of 16 bytes. Secure and fast.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AES128","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode@SBSDKAESEncrypterModeAES128","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AES128","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKAESEncrypterModeAES128","kind":"identifier"}],"symbolKind":"case","title":"SBSDKAESEncrypterMode.AES128","modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode\/AES128","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaesencryptermode\/aes128"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaesencryptermode\/aes128"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter":{"role":"symbol","abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."},{"type":"text","text":" "},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"text":"The context being passed to the encrypt\/decrypt methods is ignored.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAESEncrypter"}],"navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"type":"topic","title":"SBSDKAESEncrypter","url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypterMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"title":"SBSDKAESEncrypterMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"abstract":[{"type":"text","text":"An enum containing the available encryption modes for the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","url":"\/documentation\/scanbotsdk\/sbsdkaesencryptermode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypterMode/AES128":{"type":"topic","navigatorTitle":[{"text":"SBSDKAESEncrypterModeAES128","kind":"identifier"}],"title":"SBSDKAESEncrypterMode.AES128","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"AES128","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode\/AES128","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesencryptermode\/aes128","abstract":[{"type":"text","text":"AES128 mode with a key length of 16 bytes. Secure and fast."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKAESEncrypterModeAES128"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKAESEncrypterModeAES128","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKAESEncrypterModeAES128","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/title","value":"SBSDKAESEncrypter"},{"op":"replace","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/title","value":"SBSDKAESEncrypterMode"},{"value":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode~1AES128\/title","value":"SBSDKAESEncrypterModeAES128"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode~1AES128\/fragments","value":[{"kind":"identifier","text":"SBSDKAESEncrypterModeAES128"}]}]}]}