{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAMotorCarrierData"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentAAMVAMotorCarrierData(py)jurisdiction","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jurisdiction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"jurisdiction","kind":"identifier"}],"title":"jurisdiction","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jurisdiction","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"abstract":[{"type":"text","text":"Data element ID “MAI”. This is the jurisdiction of the residential address of the individual carrier. This information is utilized by the base jurisdiction to send information to the carrier that purchased the IRP credentials."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAMotorCarrierData\/jurisdiction","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvamotorcarrierdata\/jurisdiction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvamotorcarrierdata\/jurisdiction"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAMotorCarrierData":{"abstract":[{"type":"text","text":"Motor Carrier Data. File type “MC”."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAMotorCarrierData"}],"kind":"symbol","title":"SBSDKBarcodeDocumentAAMVAMotorCarrierData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVAMotorCarrierData","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvamotorcarrierdata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAMotorCarrierData","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentAAMVAMotorCarrierData/jurisdiction":{"kind":"symbol","title":"jurisdiction","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jurisdiction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentaamvamotorcarrierdata\/jurisdiction","abstract":[{"type":"text","text":"Data element ID “MAI”. This is the jurisdiction of the residential address of the individual carrier. This information is utilized by the base jurisdiction to send information to the carrier that purchased the IRP credentials."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentAAMVAMotorCarrierData\/jurisdiction","navigatorTitle":[{"kind":"identifier","text":"jurisdiction"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"title":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","abstract":[{"type":"text","text":"A generic document field."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"jurisdiction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"jurisdiction","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"jurisdiction"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeDocumentAAMVAMotorCarrierData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAMotorCarrierData\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAMotorCarrierData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAMotorCarrierData\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVAMotorCarrierData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAMotorCarrierData\/navigatorTitle"},{"value":"jurisdiction","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAMotorCarrierData~1jurisdiction\/title"},{"value":[{"kind":"identifier","text":"jurisdiction"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentAAMVAMotorCarrierData~1jurisdiction\/fragments"},{"value":"SBSDKGenericDocumentField","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title"},{"value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}