{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock"]]},"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResultBlock(py)polygon","role":"symbol","navigatorTitle":[{"text":"polygon","kind":"identifier"}],"title":"polygon","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"polygon","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock\/polygon","interfaceLanguage":"swift"},"abstract":[{"text":"The bounding polygon of the receiver in normalized unit coordinate space.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblock\/polygon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblock\/polygon"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock","title":"SBSDKOCRResultBlock","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock","abstract":[{"text":"The partial result of an optical character recognition.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOCRResultBlock"}],"navigatorTitle":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPolygon","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon","title":"SBSDKPolygon","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlock/polygon":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlock\/polygon","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The bounding polygon of the receiver in normalized unit coordinate space."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygon"},{"kind":"text","text":": "},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"}],"navigatorTitle":[{"text":"polygon","kind":"identifier"}],"title":"polygon","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblock\/polygon"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"polygon"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"polygon","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"polygon"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SBSDKOCRResultBlock","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock\/fragments","value":[{"text":"SBSDKOCRResultBlock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon"},{"value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock~1polygon\/title","value":"polygon"},{"value":[{"text":"polygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlock~1polygon\/fragments"}]}]}