{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/acceptedanglescore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/acceptedanglescore"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"acceptedAngleScore","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Defaults to 75.0. Set lower values to accept more perspective distortion."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Lower values result in more blurred document images."}]}],"name":"Warning","type":"aside","style":"warning"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedAngleScore","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The minimum score in percent (0 - 100) of the perspective distortion to accept a detected document.","type":"text"}],"metadata":{"role":"symbol","title":"acceptedAngleScore","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetector(py)acceptedAngleScore","navigatorTitle":[{"text":"acceptedAngleScore","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"type":"topic","abstract":[{"text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef.","type":"text"}],"title":"SBSDKDocumentDetector","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/acceptedAngleScore":{"title":"acceptedAngleScore","abstract":[{"type":"text","text":"The minimum score in percent (0 - 100) of the perspective distortion to accept a detected document."}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/acceptedanglescore","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/acceptedAngleScore","navigatorTitle":[{"text":"acceptedAngleScore","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"acceptedAngleScore","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"acceptedAngleScore"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"acceptedAngleScore","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":" ","kind":"text"},{"text":"acceptedAngleScore","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1acceptedAngleScore\/title","value":"acceptedAngleScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1acceptedAngleScore\/fragments","value":[{"text":"acceptedAngleScore","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}