{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc"},"metadata":{"roleHeading":"Instance Method","title":"detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detectDocumentPolygon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"smoothingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"useLiveDetectionParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetector(im)detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"abstract":[{"text":"Executes an edge detection algorithm on the given image and returns","type":"text"},{"type":"text","text":" "},{"text":"a polygon describing the extends of the detected documents box.","type":"text"},{"type":"text","text":" "},{"text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectDocumentPolygon"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"text":"visibleImageRect","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"smoothingEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useLiveDetectionParameters"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"image","content":[{"inlineContent":[{"text":"The image to analyze.","type":"text"}],"type":"paragraph"}]},{"name":"visibleImageRect","content":[{"type":"paragraph","inlineContent":[{"text":"The unified image rectangle that should be analyzed.","type":"text"},{"type":"text","text":" "},{"text":"(0, 0)-(1, 1) or an empty rect means the whole image is being analyzed.","type":"text"}]}]},{"name":"smoothingEnabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set to YES if you want the polygon output to be smoothed with latest frames. If you choose to use smoothing"},{"type":"text","text":" "},{"type":"text","text":"you should call resetSmoothingData regularly."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set YES if you want to use faster live detection. Live detection is less reliable than normal detection."}]}],"name":"useLiveDetectionParameters"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The detection result containing the status and a polygon.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-101hc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-101hc"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"type":"topic","abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector","title":"SBSDKDocumentDetector","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc","navigatorTitle":[{"kind":"identifier","text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Executes an edge detection algorithm on the given image and returns","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a polygon describing the extends of the detected documents box."},{"text":" ","type":"text"},{"type":"text","text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention."}],"title":"detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectdocumentpolygon(on:visibleimagerect:smoothingenabled:uselivedetectionparameters:)-101hc","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detectDocumentPolygon","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"visibleImageRect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"smoothingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useLiveDetectionParameters"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorResult":{"abstract":[{"type":"text","text":"This class represents the result of a document detection"},{"text":" ","type":"text"},{"type":"text","text":"on an image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult","type":"topic","kind":"symbol","title":"SBSDKDocumentDetectorResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"kind":"text","text":" *) "},{"text":"detectDocumentPolygonOnImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"text":"visibleImageRect:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"text":"visibleImageRect","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smoothingEnabled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"smoothingEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLiveDetectionParameters:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"useLiveDetectionParameters","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image to analyze.","type":"text"}]}]},{"name":"visibleImageRect","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unified image rectangle that should be analyzed."},{"text":" ","type":"text"},{"text":"(0, 0)-(1, 1) or an empty rect means the whole image is being analyzed.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set to YES if you want the polygon output to be smoothed with latest frames. If you choose to use smoothing"},{"text":" ","type":"text"},{"type":"text","text":"you should call resetSmoothingData regularly."}]}],"name":"smoothingEnabled"},{"name":"useLiveDetectionParameters","content":[{"type":"paragraph","inlineContent":[{"text":"Set YES if you want to use faster live detection. Live detection is less reliable than normal detection.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The detection result containing the status and a polygon.","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"op":"replace","value":"SBSDKDocumentDetector","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/navigatorTitle","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc\/title","value":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectDocumentPolygonOnImage:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectDocumentPolygon(on:visibleImageRect:smoothingEnabled:useLiveDetectionParameters:)-101hc\/fragments","op":"replace"},{"value":"SBSDKDocumentDetectorResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/title"},{"value":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}