{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectPhotoPolygon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"visibleImageRect","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"text":"smoothingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to analyze."}]}],"name":"image"},{"name":"visibleImageRect","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unified image rectangle that should be analyzed."},{"type":"text","text":" "},{"type":"text","text":"(0, 0)-(1, 1) or an empty rect means the whole image is being analyzed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set to YES if you want the polygon output to be smoothed with latest frames. If you choose to use smoothing"},{"type":"text","text":" "},{"type":"text","text":"you should call resetSmoothingData regularly."}]}],"name":"smoothingEnabled"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection result containing the status and a polygon."}]}]}],"metadata":{"title":"detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetector(im)detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","navigatorTitle":[{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}],"symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detectPhotoPolygon","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"visibleImageRect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"smoothingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"kind":"text","text":"?"}],"roleHeading":"Instance Method"},"sections":[],"abstract":[{"type":"text","text":"Executes an edge detection algorithm on the given image and returns"},{"text":" ","type":"text"},{"type":"text","text":"a polygon describing the extends of the detected photos box."},{"text":" ","type":"text"},{"type":"text","text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectphotopolygon(on:visibleimagerect:smoothingenabled:)-10171"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectphotopolygon(on:visibleimagerect:smoothingenabled:)-10171"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"title":"SBSDKDocumentDetector","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171","type":"topic","kind":"symbol","navigatorTitle":[{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}],"abstract":[{"text":"Executes an edge detection algorithm on the given image and returns","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a polygon describing the extends of the detected photos box."},{"type":"text","text":" "},{"type":"text","text":"For a short period of time the uncompressed image data is hold twice in memory. Use with attention."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectphotopolygon(on:visibleimagerect:smoothingenabled:)-10171","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detectPhotoPolygon","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"visibleImageRect"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"smoothingEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","abstract":[{"type":"text","text":"This class represents the result of a document detection"},{"text":" ","type":"text"},{"text":"on an image.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult","navigatorTitle":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"title":"SBSDKDocumentDetectorResult"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"detectPhotoPolygonOnImage:"},{"kind":"text","text":"("},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":" "},{"text":"visibleImageRect:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"visibleImageRect"},{"text":" ","kind":"text"},{"text":"smoothingEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"smoothingEnabled","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title","op":"replace","value":"SBSDKDocumentDetector"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171\/title","value":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:"},{"value":[{"text":"- ","kind":"text"},{"text":"detectPhotoPolygonOnImage:visibleImageRect:smoothingEnabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectPhotoPolygon(on:visibleImageRect:smoothingEnabled:)-10171\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/title","value":"SBSDKDocumentDetectorResult"},{"value":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}