{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectorMode","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectorMode"},{"kind":"text","text":": "},{"text":"SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"detectorMode","navigatorTitle":[{"text":"detectorMode","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetector(py)detectorMode","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectormode"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectormode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"detectorMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/machineLearning","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"The current mode of the detector: "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/standard","isActive":true},{"text":" or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/machineLearning"},{"type":"text","text":" based."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode/machineLearning":{"abstract":[{"type":"text","text":"The new machine-learning based detection mode."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/machineLearning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineLearning","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode\/machinelearning","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorModeMachineLearning"}],"title":"SBSDKDocumentDetectorMode.machineLearning"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"type":"topic","title":"SBSDKDocumentDetector","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector","role":"symbol","abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode":{"abstract":[{"type":"text","text":"The mode of the document detector: standard or machine-learning-based."}],"title":"SBSDKDocumentDetectorMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode/standard":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectorModeStandard","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/standard","kind":"symbol","title":"SBSDKDocumentDetectorMode.standard","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode\/standard","type":"topic","abstract":[{"type":"text","text":"The standard detection mode."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/detectorMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/detectorMode","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectorMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"}],"title":"detectorMode","navigatorTitle":[{"text":"detectorMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/detectormode","kind":"symbol","abstract":[{"type":"text","text":"The current mode of the detector: "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/standard"},{"text":" or ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode\/machineLearning","isActive":true},{"type":"text","text":" based."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"detectorMode"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"detectorMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectorMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"},{"text":" ","kind":"text"},{"text":"detectorMode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1machineLearning\/title","value":"SBSDKDocumentDetectorModeMachineLearning"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectorModeMachineLearning"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1machineLearning\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/title","op":"replace","value":"SBSDKDocumentDetectorMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}]},{"value":"SBSDKDocumentDetectorModeStandard","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1standard\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorModeStandard"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode~1standard\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectorMode\/title","value":"detectorMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1detectorMode\/fragments","value":[{"kind":"identifier","text":"detectorMode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}