{"metadata":{"navigatorTitle":[{"text":"setDefaultDetectorMode:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetector(cm)setDefaultDetectorMode:","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultDetectorMode"},{"kind":"text","text":"("},{"text":"SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Type Method","role":"symbol","title":"setDefaultDetectorMode(_:)","symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"Set default detector mode. Unless the new instance of detector is initialized with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init(mode:)"},{"text":" initializer, this new instance will have this mode set.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDefaultDetectorMode"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"newDefaultDetectorMode","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"newDefaultDetectorMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The desired detector mode."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/setdefaultdetectormode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/setdefaultdetectormode(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/setDefaultDetectorMode(_:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/init(mode:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init(mode:)","navigatorTitle":[{"text":"initWithMode:","kind":"identifier"}],"abstract":[{"type":"text","text":"Designated initialiizer."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/init(mode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"},{"text":")","kind":"text"}],"role":"symbol","title":"init(mode:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"title":"SBSDKDocumentDetector","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorMode":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectormode","abstract":[{"text":"The mode of the document detector: standard or machine-learning-based.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectorMode","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKDocumentDetectorMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/setDefaultDetectorMode(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/setDefaultDetectorMode(_:)","navigatorTitle":[{"kind":"identifier","text":"setDefaultDetectorMode:"}],"abstract":[{"text":"Set default detector mode. Unless the new instance of detector is initialized with ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/init(mode:)"},{"type":"text","text":" initializer, this new instance will have this mode set."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/setdefaultdetectormode(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setDefaultDetectorMode","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKDocumentDetectorMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"},{"text":")","kind":"text"}],"role":"symbol","title":"setDefaultDetectorMode(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"setDefaultDetectorMode:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDefaultDetectorMode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setDefaultDetectorMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectorMode"},{"kind":"text","text":") "},{"text":"newDefaultDetectorMode","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1init(mode:)\/title","value":"initWithMode:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1init(mode:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector","op":"replace"},{"value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments"},{"value":"SBSDKDocumentDetectorMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectorMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1setDefaultDetectorMode(_:)\/title","value":"setDefaultDetectorMode:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1setDefaultDetectorMode(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDefaultDetectorMode:"}]}]}]}