{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"barcodeItemMapper"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper","text":"SBSDKUI2BarcodeItemMapper"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"sheetColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dividerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"modalOverlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"loadingMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"errorState"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemErrorState","text":"SBSDKUI2BarcodeItemErrorState","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithBarcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:","kind":"identifier"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping(im)initWithBarcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:","symbolKind":"init","title":"init(barcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcodeItemMapper"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemMapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper","text":"SBSDKUI2BarcodeItemMapper"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"sheetColor"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false), "},{"kind":"externalParam","text":"dividerColor"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), "},{"kind":"externalParam","text":"modalOverlayColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorModalOverlay\", isArgb: false), "},{"kind":"externalParam","text":"loadingMessage"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" = SBSDKUI2StyledText(text: \"Loading message for barcode info mapping.\",\n                                       color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                            isArgb: false)), "},{"text":"errorState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeItemErrorState","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemErrorState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemErrorState"},{"kind":"text","text":" = SBSDKUI2BarcodeItemErrorState())"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping\/init(barcodeitemmapper:sheetcolor:dividercolor:modaloverlaycolor:loadingmessage:errorstate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping\/init(barcodeitemmapper:sheetcolor:dividercolor:modaloverlaycolor:loadingmessage:errorstate:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping\/init(barcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","role":"symbol","title":"SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemErrorState":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemerrorstate","role":"symbol","title":"SBSDKUI2BarcodeItemErrorState","abstract":[{"type":"text","text":"Configuration of the the mapper’s error dialog."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemErrorState","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeItemErrorState"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeItemErrorState","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"title":"SBSDKUI2BarcodeInfoMapping","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the barcode data mapping."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemMapper":{"abstract":[{"text":"Maps a barcode’s data to the data of the corresponding product.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemmapper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemMapper","type":"topic","title":"SBSDKUI2BarcodeItemMapper"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping/init(barcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:)":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping\/init(barcodeitemmapper:sheetcolor:dividercolor:modaloverlaycolor:loadingmessage:errorstate:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcodeItemMapper"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeItemMapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper"},{"text":"?, ","kind":"text"},{"text":"sheetColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dividerColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"modalOverlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loadingMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"text":"errorState","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeItemErrorState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemErrorState"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithBarcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping\/init(barcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:)","type":"topic","title":"init(barcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithBarcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBarcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithBarcodeItemMapper:"},{"kind":"text","text":"("},{"text":"id<SBSDKUI2BarcodeItemMapper>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKUI2BarcodeItemMapper"},{"kind":"text","text":") "},{"text":"barcodeItemMapper","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheetColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheetColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"dividerColor:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"dividerColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalOverlayColor:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"modalOverlayColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"loadingMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"text":"loadingMessage","kind":"internalParam"},{"kind":"text","text":" "},{"text":"errorState:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2BarcodeItemErrorState","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemErrorState","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemErrorState","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"errorState","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemErrorState\/title","value":"SBSDKUI2BarcodeItemErrorState","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemErrorState\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemErrorState"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/title","value":"SBSDKUI2BarcodeInfoMapping","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}]},{"value":"SBSDKUI2BarcodeItemMapper","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemMapper\/fragments","value":[{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping~1init(barcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:)\/title","value":"initWithBarcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping~1init(barcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBarcodeItemMapper:sheetColor:dividerColor:modalOverlayColor:loadingMessage:errorState:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]}]}]}