{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"sections":[],"abstract":[{"text":"Normalized full name of the “DriverPermitRestrictionCode” field type in document type “AAMVA.DLID”.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","role":"symbol","navigatorTitle":[{"text":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","kind":"identifier"}],"roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverpermitrestrictioncodefieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverpermitrestrictioncodefieldnormalizedname"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName":{"abstract":[{"type":"text","text":"Normalized full name of the “DriverPermitRestrictionCode” field type in document type “AAMVA.DLID”."}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","navigatorTitle":[{"kind":"identifier","text":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvadliddriverpermitrestrictioncodefieldnormalizedname","type":"topic","title":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelConstants","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName\/title","value":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"aamvaDLIDDriverPermitRestrictionCodeFieldNormalizedName"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}