{"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","role":"symbol","navigatorTitle":[{"text":"aamvaVehicleDataNumberOfAxlesFieldName","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleDataNumberOfAxlesFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaVehicleDataNumberOfAxlesFieldName","title":"aamvaVehicleDataNumberOfAxlesFieldName"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Name of the “NumberOfAxles” field type in document type “AAMVA.VehicleData”.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaVehicleDataNumberOfAxlesFieldName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicledatanumberofaxlesfieldname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicledatanumberofaxlesfieldname"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelConstants","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/aamvaVehicleDataNumberOfAxlesFieldName":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaVehicleDataNumberOfAxlesFieldName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/aamvavehicledatanumberofaxlesfieldname","navigatorTitle":[{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldName"}],"kind":"symbol","title":"aamvaVehicleDataNumberOfAxlesFieldName","role":"symbol","abstract":[{"type":"text","text":"Name of the “NumberOfAxles” field type in document type “AAMVA.VehicleData”."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"aamvaVehicleDataNumberOfAxlesFieldName","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldName"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldName"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaVehicleDataNumberOfAxlesFieldName\/title","value":"aamvaVehicleDataNumberOfAxlesFieldName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaVehicleDataNumberOfAxlesFieldName\/fragments","value":[{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}