{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/swissqrpaymentreferencetypefieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/swissqrpaymentreferencetypefieldnormalizedname"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"swissQRPaymentReferenceTypeFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]}],"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swissQRPaymentReferenceTypeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)swissQRPaymentReferenceTypeFieldNormalizedName","navigatorTitle":[{"text":"swissQRPaymentReferenceTypeFieldNormalizedName","kind":"identifier"}],"title":"swissQRPaymentReferenceTypeFieldNormalizedName","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/swissQRPaymentReferenceTypeFieldNormalizedName","interfaceLanguage":"swift"},"abstract":[{"text":"Normalized full name of the “PaymentReferenceType” field type in document type “SwissQR”.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"title":"SBSDKBarcodeDocumentModelConstants","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/swissQRPaymentReferenceTypeFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/swissqrpaymentreferencetypefieldnormalizedname","abstract":[{"text":"Normalized full name of the “PaymentReferenceType” field type in document type “SwissQR”.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/swissQRPaymentReferenceTypeFieldNormalizedName","title":"swissQRPaymentReferenceTypeFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"swissQRPaymentReferenceTypeFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"swissQRPaymentReferenceTypeFieldNormalizedName","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"swissQRPaymentReferenceTypeFieldNormalizedName","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"swissQRPaymentReferenceTypeFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"swissQRPaymentReferenceTypeFieldNormalizedName"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1swissQRPaymentReferenceTypeFieldNormalizedName\/title","value":"swissQRPaymentReferenceTypeFieldNormalizedName","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1swissQRPaymentReferenceTypeFieldNormalizedName\/fragments","value":[{"text":"swissQRPaymentReferenceTypeFieldNormalizedName","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}