{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer\/init(lineColor:)","interfaceLanguage":"swift"},"metadata":{"title":"init(lineColor:)","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLineColor:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygonLayer(im)initWithLineColor:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lineColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"abstract":[{"type":"text","text":"Designated initializer."}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygonlayer\/init(linecolor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygonlayer\/init(linecolor:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithLineColor:) ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lineColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"lineColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The initial color for the path drawing color."}]}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonLayer":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"CAShapeLayer"},{"type":"text","text":" subclass that is used to draw bezier paths with fluid animation."}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpolygonlayer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonLayer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer","navigatorTitle":[{"text":"SBSDKPolygonLayer","kind":"identifier"}],"title":"SBSDKPolygonLayer","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonLayer/init(lineColor:)":{"title":"init(lineColor:)","url":"\/documentation\/scanbotsdk\/sbsdkpolygonlayer\/init(linecolor:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer\/init(lineColor:)","abstract":[{"type":"text","text":"Designated initializer."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLineColor:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"lineColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithLineColor:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLineColor:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithLineColor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"lineColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer\/title","value":"SBSDKPolygonLayer","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer\/fragments","value":[{"text":"SBSDKPolygonLayer","kind":"identifier"}],"op":"replace"},{"value":"initWithLineColor:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer~1init(lineColor:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithLineColor:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer~1init(lineColor:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}