{"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DBarcodesQuietZone"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","navigatorTitle":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"minimum1DBarcodesQuietZone","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerConfiguration(py)minimum1DBarcodesQuietZone"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/minimum1dbarcodesquietzone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/minimum1dbarcodesquietzone"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minimum1DBarcodesQuietZone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Default is 10","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration\/minimum1DBarcodesQuietZone"},"sections":[],"abstract":[{"text":"Optional minimum required quiet zone on the barcode. Measured in modules (the smallest bar size on a barcode).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The default is 10. NOTE - This feature works on ITF barcodes only."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration/minimum1DBarcodesQuietZone":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minimum1DBarcodesQuietZone","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minimum1DBarcodesQuietZone"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration\/minimum1dbarcodesquietzone","abstract":[{"type":"text","text":"Optional minimum required quiet zone on the barcode. Measured in modules (the smallest bar size on a barcode)."},{"type":"text","text":" "},{"text":"The default is 10. NOTE - This feature works on ITF barcodes only.","type":"text"}],"title":"minimum1DBarcodesQuietZone","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration\/minimum1DBarcodesQuietZone","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerConfiguration":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerConfiguration","title":"SBSDKUI2BarcodeScannerConfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"minimum1DBarcodesQuietZone","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minimum1DBarcodesQuietZone"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"text":"minimum1DBarcodesQuietZone","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration~1minimum1DBarcodesQuietZone\/title","value":"minimum1DBarcodesQuietZone"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration~1minimum1DBarcodesQuietZone\/fragments","value":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/title","value":"SBSDKUI2BarcodeScannerConfiguration"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeScannerConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}