{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"generateKey","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keyLength"},{"kind":"text","text":": "},{"text":"SBSDKStorageCryptingKeyLength","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"keyLength","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The length of the generated key."}]}]}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The newly generated encryption key.","type":"text"}]}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"Generates a new encryption key."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRandomKeyGenerator\/generateKey(keyLength:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRandomKeyGenerator"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateKey"},{"text":"(","kind":"text"},{"text":"keyLength","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKStorageCryptingKeyLength","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"roleHeading":"Instance Method","title":"generateKey(keyLength:)","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKRandomKeyGenerator(im)generateKeyWithLength:WithError:","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"generateKeyWithLength:WithError:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkrandomkeygenerator\/generatekey(keylength:)"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkrandomkeygenerator\/generatekey(keylength:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKRandomKeyGenerator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that generates secure, random keys for storage encryption."},{"type":"text","text":" "},{"text":"They keys are generated using the ","type":"text"},{"type":"codeVoice","code":"SecRandomCopyBytes"},{"text":" function.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkrandomkeygenerator","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRandomKeyGenerator","title":"SBSDKRandomKeyGenerator","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingKeyLength":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingkeylength","title":"SBSDKStorageCryptingKeyLength","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"abstract":[{"type":"text","text":"The length of the encryption key."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKRandomKeyGenerator/generateKey(keyLength:)":{"kind":"symbol","abstract":[{"text":"Generates a new encryption key.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKRandomKeyGenerator\/generateKey(keyLength:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkrandomkeygenerator\/generatekey(keylength:)","title":"generateKey(keyLength:)","navigatorTitle":[{"kind":"identifier","text":"generateKeyWithLength:WithError:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generateKey","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keyLength"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"generateKeyWithLength:WithError:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateKeyWithLength:WithError:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"generateKeyWithLength:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingKeyLength","text":"SBSDKStorageCryptingKeyLength","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKStorageCryptingKeyLength"},{"kind":"text","text":") "},{"kind":"internalParam","text":"keyLength"},{"text":" ","kind":"text"},{"text":"WithError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"keyLength","content":[{"inlineContent":[{"type":"text","text":"The length of the generated key."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}],"name":"error"}]}},{"path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"The newly generated encryption key."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"op":"replace","value":"SBSDKRandomKeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRandomKeyGenerator\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRandomKeyGenerator\/fragments","value":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRandomKeyGenerator\/navigatorTitle","op":"replace","value":[{"text":"SBSDKRandomKeyGenerator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/title","value":"SBSDKStorageCryptingKeyLength"},{"value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]},{"op":"replace","value":"generateKeyWithLength:WithError:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRandomKeyGenerator~1generateKey(keyLength:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKRandomKeyGenerator~1generateKey(keyLength:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"generateKeyWithLength:WithError:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}