{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions\/initWithRoi:loadMode:encryptionMode:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRoi:loadMode:encryptionMode:"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithRoi:loadMode:encryptionMode:","kind":"identifier"}],"title":"initWithRoi:loadMode:encryptionMode:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPathImageLoadOptions(im)initWithRoi:loadMode:encryptionMode:","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRoi:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"roi"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPathLoadMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode","kind":"typeIdentifier","text":"SBSDKPathLoadMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"loadMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","kind":"typeIdentifier","text":"SBSDKEncryptionMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"encryptionMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions\/initwithroi:loadmode:encryptionmode:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathImageLoadOptions/initWithRoi:loadMode:encryptionMode:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions\/initwithroi:loadmode:encryptionmode:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRoi:loadMode:encryptionMode:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions\/initWithRoi:loadMode:encryptionMode:","abstract":[],"type":"topic","title":"initWithRoi:loadMode:encryptionMode:","navigatorTitle":[{"text":"initWithRoi:loadMode:encryptionMode:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathLoadMode":{"role":"symbol","type":"topic","kind":"symbol","title":"SBSDKPathLoadMode","abstract":[{"type":"text","text":"Image Ref Path Load Mode."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathLoadMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPathLoadMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkpathloadmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathLoadMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncryptionMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncryptionMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkencryptionmode","abstract":[{"text":"Encryption\/Decryption mode to be used when an image is loaded\/saved.","type":"text"}],"navigatorTitle":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}],"kind":"symbol","title":"SBSDKEncryptionMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathImageLoadOptions":{"url":"\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions","role":"symbol","type":"topic","title":"SBSDKPathImageLoadOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"abstract":[{"text":"Options for loading image from path.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKPathLoadMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKPathLoadMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPathLoadMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathLoadMode\/navigatorTitle"},{"value":"SBSDKEncryptionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncryptionMode\/navigatorTitle"},{"value":"SBSDKPathImageLoadOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/title"},{"value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/navigatorTitle"}]}]}