{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroCustomImage\/copyWithZone:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinintrocustomimage\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"copyWithZone:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINIntroCustomImage(im)copyWithZone:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroCustomImage"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINIntroCustomImage":{"abstract":[{"text":"A custom image for the introduction screen.","type":"text"}],"title":"SBSDKUI2VINIntroCustomImage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINIntroCustomImage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINIntroCustomImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroCustomImage","url":"\/documentation\/scanbotsdk\/sbsdkui2vinintrocustomimage","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINIntroCustomImage/copyWithZone:":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","title":"copyWithZone:","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINIntroCustomImage\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2vinintrocustomimage\/copywithzone:","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroCustomImage\/title","value":"SBSDKUI2VINIntroCustomImage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroCustomImage\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2VINIntroCustomImage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINIntroCustomImage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2VINIntroCustomImage"}]}]}]}