{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/acceptedmrztypes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/acceptedmrztypes"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/acceptedMRZTypes"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration(py)acceptedMRZTypes","navigatorTitle":[{"text":"acceptedMRZTypes","kind":"identifier"}],"title":"acceptedMRZTypes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedMRZTypes"},{"kind":"text","text":": ["},{"text":"SBSDKMRZDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType"},{"kind":"text","text":"]"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property"},"abstract":[{"text":"List of MRZ document types for which MRZ fallback is enabled.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptedMRZTypes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","text":"SBSDKMRZDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZDocumentType":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzdocumenttype","navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZDocumentType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZDocumentType","kind":"symbol","role":"symbol","abstract":[{"text":"Type of document containing the MRZ.","type":"text"}],"title":"SBSDKMRZDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/acceptedMRZTypes":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/acceptedmrztypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedMRZTypes"},{"text":": [","kind":"text"},{"text":"SBSDKMRZDocumentType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"abstract":[{"text":"List of MRZ document types for which MRZ fallback is enabled.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/acceptedMRZTypes","role":"symbol","type":"topic","title":"acceptedMRZTypes","navigatorTitle":[{"text":"acceptedMRZTypes","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"MRZ fallback configuration element."},{"type":"text","text":" "},{"type":"text","text":"This configuration element does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"text":"Add to extractor configuration to enable recognizing the MRZ only, specifically for documents that are otherwise not","type":"text"},{"type":"text","text":" "},{"type":"text","text":"supported."},{"type":"text","text":" "},{"type":"text","text":"Note that this may enable scanning of documents that were not enabled through the accepted document types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration","role":"symbol","type":"topic","title":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"acceptedMRZTypes"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"acceptedMRZTypes","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKMRZDocumentType *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"acceptedMRZTypes"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/title","value":"SBSDKMRZDocumentType","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZDocumentType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1acceptedMRZTypes\/title","value":"acceptedMRZTypes"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1acceptedMRZTypes\/fragments","op":"replace","value":[{"kind":"identifier","text":"acceptedMRZTypes"}]},{"value":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fragments","value":[{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/navigatorTitle"}]}]}