{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode\/fillin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode\/fillin"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","abstract":[{"text":"In this mode, the camera preview frames fill the entire layout view - the preview frames may contain additional content at the edges that are not visible in the preview layout.","type":"text"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"symbolKind":"case","title":"SBSDKUI2CameraPreviewMode.fillIn","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewModeFillIn","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CameraPreviewMode@SBSDKUI2CameraPreviewModeFillIn"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode\/fillIn","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraPreviewMode/fillIn":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode\/fillin","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode\/fillIn","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewModeFillIn","kind":"identifier"}],"title":"SBSDKUI2CameraPreviewMode.fillIn","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"In this mode, the camera preview frames fill the entire layout view - the preview frames may contain additional content at the edges that are not visible in the preview layout."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraPreviewMode":{"abstract":[{"text":"Configuration of the camera preview mode.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraPreviewMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2camerapreviewmode","kind":"symbol","title":"SBSDKUI2CameraPreviewMode","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2CameraPreviewModeFillIn","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewModeFillIn"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewModeFillIn"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2CameraPreviewModeFillIn","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode~1fillIn\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewModeFillIn"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode~1fillIn\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/title","op":"replace","value":"SBSDKUI2CameraPreviewMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}