{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration\/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerIntroScreenConfiguration(im)initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:"}],"role":"symbol","title":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","symbolKind":"method","navigatorTitle":[{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage","text":"SBSDKUI2TextPatternScannerIntroImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerIntroImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"backgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dividerColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"dividerColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handlerColor:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"handlerColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAutomatically:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"showAutomatically"},{"kind":"text","text":" "},{"kind":"identifier","text":"title:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"title"},{"kind":"text","text":" "},{"kind":"identifier","text":"explanation:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"explanation"},{"kind":"text","text":" "},{"kind":"identifier","text":"doneButton:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"doneButton"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration\/initwithimage:backgroundcolor:dividercolor:handlercolor:showautomatically:title:explanation:donebutton:"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroScreenConfiguration/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration\/initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"symbol","title":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","navigatorTitle":[{"text":"initWithImage:backgroundColor:dividerColor:handlerColor:showAutomatically:title:explanation:doneButton:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration\/initwithimage:backgroundcolor:dividercolor:handlercolor:showautomatically:title:explanation:donebutton:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroImage":{"abstract":[{"text":"The image for the introduction screen of a generic text scanner screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroimage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TextPatternScannerIntroImage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2TextPatternScannerIntroImage","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroImage","title":"SBSDKUI2TextPatternScannerIntroImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","abstract":[{"type":"text","text":"Configuration of the button."}],"type":"topic","kind":"symbol","title":"SBSDKUI2ButtonConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerIntroScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerintroscreenconfiguration","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}],"abstract":[{"text":"Configuration of the introduction screen for the generic text scanner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerIntroScreenConfiguration","title":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"kind":"symbol","type":"topic","title":"SBSDKUI2StyledText"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2TextPatternScannerIntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/title","op":"replace"},{"value":[{"text":"SBSDKUI2TextPatternScannerIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroImage\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2TextPatternScannerIntroScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerIntroScreenConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}