{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customLanguagesFolderURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"To use other than the default languages, download them ","type":"text"},{"identifier":"https:\/\/github.com\/tesseract-ocr\/tessdata_fast","type":"reference","isActive":true},{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"and bundle them with your app.","type":"text"},{"text":" ","type":"text"},{"text":"When your app starts, copy the files to this folder and call ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installLanguages()","type":"reference","isActive":true},{"text":" to install.","type":"text"}]},{"style":"note","type":"aside","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installCustomLanguagesFrom(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/customlanguagesfolderurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/customlanguagesfolderurl"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/customLanguagesFolderURL"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRLanguagesManager(cpy)customLanguagesFolderURL","title":"customLanguagesFolderURL","navigatorTitle":[{"kind":"identifier","text":"customLanguagesFolderURL"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customLanguagesFolderURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}]},"abstract":[{"type":"text","text":"The URL of the folder for custom language trained data files."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/customLanguagesFolderURL":{"abstract":[{"type":"text","text":"The URL of the folder for custom language trained data files."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/customLanguagesFolderURL","navigatorTitle":[{"text":"customLanguagesFolderURL","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/customlanguagesfolderurl","title":"customLanguagesFolderURL","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customLanguagesFolderURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installCustomLanguagesFrom(_:)":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installCustomLanguagesFrom(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"installCustomLanguagesFrom","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"installCustomLanguagesFrom:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installcustomlanguagesfrom(_:)","title":"installCustomLanguagesFrom(_:)","abstract":[{"type":"text","text":"A helper function to easily install custom OCR languages."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager":{"role":"symbol","abstract":[{"type":"text","text":"Helper class to manage trained data files for the Tesseract OCR engine."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager","title":"SBSDKOCRLanguagesManager"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installLanguages()":{"abstract":[{"type":"text","text":"Installs the default and custom OCR language files and prepares them for usage."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installLanguages()","navigatorTitle":[{"text":"installLanguages","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"installLanguages","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installlanguages()","title":"installLanguages()","role":"symbol","kind":"symbol","type":"topic"},"https://github.com/tesseract-ocr/tessdata_fast":{"title":"here","url":"https:\/\/github.com\/tesseract-ocr\/tessdata_fast","identifier":"https:\/\/github.com\/tesseract-ocr\/tessdata_fast","type":"link","titleInlineContent":[{"type":"text","text":"here"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"customLanguagesFolderURL","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"customLanguagesFolderURL","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"customLanguagesFolderURL","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1customLanguagesFolderURL\/title","value":"customLanguagesFolderURL","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1customLanguagesFolderURL\/fragments","value":[{"text":"customLanguagesFolderURL","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installCustomLanguagesFrom(_:)\/title","value":"installCustomLanguagesFrom:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installCustomLanguagesFrom(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"installCustomLanguagesFrom:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/title","value":"SBSDKOCRLanguagesManager","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/fragments","value":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/navigatorTitle","value":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installLanguages()\/title","value":"installLanguages","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installLanguages()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"installLanguages","kind":"identifier"}],"op":"replace"}]}]}