{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NavigationBarMode"]]},"abstract":[{"type":"text","text":"Hide the navigation bar."}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"hidden","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2NavigationBarMode@SBSDKUI2NavigationBarModeHidden","symbolKind":"case","roleHeading":"Case","title":"SBSDKUI2NavigationBarMode.hidden","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2NavigationBarModeHidden"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2navigationbarmode\/hidden"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2navigationbarmode\/hidden"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NavigationBarMode\/hidden","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NavigationBarMode":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NavigationBarMode","navigatorTitle":[{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}],"title":"SBSDKUI2NavigationBarMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2NavigationBarMode","kind":"identifier"}],"type":"topic","abstract":[{"text":"The visual mode used for the navigation bar icons. Android only.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2navigationbarmode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2NavigationBarMode/hidden":{"abstract":[{"type":"text","text":"Hide the navigation bar."}],"kind":"symbol","title":"SBSDKUI2NavigationBarMode.hidden","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2NavigationBarMode\/hidden","url":"\/documentation\/scanbotsdk\/sbsdkui2navigationbarmode\/hidden","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"hidden","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SBSDKUI2NavigationBarModeHidden","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2NavigationBarModeHidden"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKUI2NavigationBarMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NavigationBarMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NavigationBarMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2NavigationBarMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NavigationBarMode\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2NavigationBarModeHidden","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NavigationBarMode~1hidden\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2NavigationBarMode~1hidden\/fragments","value":[{"text":"SBSDKUI2NavigationBarModeHidden","kind":"identifier"}]}]}]}