{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeandriverlicensefrontbirthdatefieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeandriverlicensefrontbirthdatefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"europeanDriverLicenseFrontBirthDateFieldNormalizedName"}],"title":"europeanDriverLicenseFrontBirthDateFieldNormalizedName","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)europeanDriverLicenseFrontBirthDateFieldNormalizedName","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanDriverLicenseFrontBirthDateFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/europeanDriverLicenseFrontBirthDateFieldNormalizedName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"abstract":[{"type":"text","text":"Normalized full name of the “BirthDate” field type in document type “EuropeanDriverLicenseFront”."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"europeanDriverLicenseFrontBirthDateFieldNormalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/europeanDriverLicenseFrontBirthDateFieldNormalizedName":{"abstract":[{"type":"text","text":"Normalized full name of the “BirthDate” field type in document type “EuropeanDriverLicenseFront”."}],"title":"europeanDriverLicenseFrontBirthDateFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanDriverLicenseFrontBirthDateFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeandriverlicensefrontbirthdatefieldnormalizedname","kind":"symbol","navigatorTitle":[{"text":"europeanDriverLicenseFrontBirthDateFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/europeanDriverLicenseFrontBirthDateFieldNormalizedName","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","title":"SBSDKDocumentsModelConstants","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"europeanDriverLicenseFrontBirthDateFieldNormalizedName","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"europeanDriverLicenseFrontBirthDateFieldNormalizedName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"europeanDriverLicenseFrontBirthDateFieldNormalizedName"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1europeanDriverLicenseFrontBirthDateFieldNormalizedName\/title","op":"replace","value":"europeanDriverLicenseFrontBirthDateFieldNormalizedName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1europeanDriverLicenseFrontBirthDateFieldNormalizedName\/fragments","op":"replace","value":[{"text":"europeanDriverLicenseFrontBirthDateFieldNormalizedName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title","op":"replace","value":"SBSDKDocumentsModelConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}