{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/moIdentityCardFrontValidUntilFieldName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"abstract":[{"text":"Name of the “ValidUntil” field type in document type “MoIdentityCardFront”.","type":"text"}],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"moIdentityCardFrontValidUntilFieldName","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moIdentityCardFrontValidUntilFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)moIdentityCardFrontValidUntilFieldName","roleHeading":"Type Property","title":"moIdentityCardFrontValidUntilFieldName","modules":[{"name":"ScanbotSDK"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/moidentitycardfrontvaliduntilfieldname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/moidentitycardfrontvaliduntilfieldname"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"moIdentityCardFrontValidUntilFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","title":"SBSDKDocumentsModelConstants","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/moIdentityCardFrontValidUntilFieldName":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"moIdentityCardFrontValidUntilFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/moidentitycardfrontvaliduntilfieldname","navigatorTitle":[{"kind":"identifier","text":"moIdentityCardFrontValidUntilFieldName"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/moIdentityCardFrontValidUntilFieldName","title":"moIdentityCardFrontValidUntilFieldName","kind":"symbol","abstract":[{"type":"text","text":"Name of the “ValidUntil” field type in document type “MoIdentityCardFront”."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"moIdentityCardFrontValidUntilFieldName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"moIdentityCardFrontValidUntilFieldName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"moIdentityCardFrontValidUntilFieldName"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title","value":"SBSDKDocumentsModelConstants"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments","value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1moIdentityCardFrontValidUntilFieldName\/title","value":"moIdentityCardFrontValidUntilFieldName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1moIdentityCardFrontValidUntilFieldName\/fragments","value":[{"kind":"identifier","text":"moIdentityCardFrontValidUntilFieldName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}