{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAdditionalParameters(py)australiaPostCustomerFormat","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat"}],"role":"symbol","roleHeading":"Instance Property","title":"australiaPostCustomerFormat","modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters\/australiaPostCustomerFormat"},"abstract":[{"type":"text","text":"The australia post customer format."}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/australiapostcustomerformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/australiapostcustomerformat"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/alphanumeric"},{"text":".","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAdditionalParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAdditionalParameters","kind":"identifier"}],"title":"SBSDKBarcodeAdditionalParameters","role":"symbol","abstract":[{"text":"A class that contains additional parameters for barcodes detection and filtering.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat":{"title":"SBSDKAustraliaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"The format of the australia post code. Can be "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/numeric","type":"reference"},{"type":"text","text":" or "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/alphanumeric","isActive":true,"type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Only relevant for format codes 59 and 62."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat/numeric":{"title":"SBSDKAustraliaPostCustomerFormat.numeric","url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/numeric","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numeric"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/numeric","navigatorTitle":[{"text":"SBSDKAustraliaPostCustomerFormatNumeric","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The numeric format."}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAdditionalParameters/australiaPostCustomerFormat":{"abstract":[{"type":"text","text":"The australia post customer format."}],"type":"topic","title":"australiaPostCustomerFormat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier","text":"SBSDKAustraliaPostCustomerFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters\/australiaPostCustomerFormat","navigatorTitle":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/australiapostcustomerformat","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat/alphanumeric":{"abstract":[{"type":"text","text":"The alphanumeric format."}],"title":"SBSDKAustraliaPostCustomerFormat.alphanumeric","url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/alphanumeric","navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatAlphanumeric"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/alphanumeric","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"alphanumeric","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"australiaPostCustomerFormat","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/title","value":"SBSDKBarcodeAdditionalParameters","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/fragments","value":[{"text":"SBSDKBarcodeAdditionalParameters","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKBarcodeAdditionalParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/title","value":"SBSDKAustraliaPostCustomerFormat","op":"replace"},{"op":"replace","value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1numeric\/title","value":"SBSDKAustraliaPostCustomerFormatNumeric","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatNumeric"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1numeric\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters~1australiaPostCustomerFormat\/title","value":"australiaPostCustomerFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters~1australiaPostCustomerFormat\/fragments","value":[{"kind":"identifier","text":"australiaPostCustomerFormat"}]},{"value":"SBSDKAustraliaPostCustomerFormatAlphanumeric","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1alphanumeric\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1alphanumeric\/fragments","value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatAlphanumeric"}],"op":"replace"}]}]}