{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters\/minimumTextLength"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters"]]},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"minimumTextLength","symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAdditionalParameters(py)minimumTextLength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minimumTextLength","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"text":"minimumTextLength","kind":"identifier"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Minimum required text length of the detected barcode."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/minimumtextlength"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/minimumtextlength"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Defaults to 0."}],"type":"paragraph"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently works for ITF and MSI Plessey barcodes only!"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAdditionalParameters/minimumTextLength":{"kind":"symbol","title":"minimumTextLength","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters\/minimumTextLength","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimumTextLength","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"abstract":[{"text":"Minimum required text length of the detected barcode.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"minimumTextLength"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/minimumtextlength"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAdditionalParameters":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"role":"symbol","abstract":[{"type":"text","text":"A class that contains additional parameters for barcodes detection and filtering."}],"kind":"symbol","title":"SBSDKBarcodeAdditionalParameters","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"minimumTextLength","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"minimumTextLength","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"minimumTextLength","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters~1minimumTextLength\/title","value":"minimumTextLength","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters~1minimumTextLength\/fragments","value":[{"text":"minimumTextLength","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/title","value":"SBSDKBarcodeAdditionalParameters"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/fragments"}]}]}