{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters"]]},"abstract":[{"text":"The checksum algorithm for MSI Plessey barcodes.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters\/msiPlesseyChecksumAlgorithm","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"kind":"content"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeAdditionalParameters(py)msiPlesseyChecksumAlgorithm","title":"msiPlesseyChecksumAlgorithm","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/msiplesseychecksumalgorithm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/msiplesseychecksumalgorithm"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod10":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod10","kind":"identifier"}],"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod10","role":"symbol","abstract":[{"type":"text","text":"Mod10."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod10","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAdditionalParameters/msiPlesseyChecksumAlgorithm":{"navigatorTitle":[{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters\/msiplesseychecksumalgorithm","abstract":[{"text":"The checksum algorithm for MSI Plessey barcodes.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters\/msiPlesseyChecksumAlgorithm","type":"topic","title":"msiPlesseyChecksumAlgorithm","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAdditionalParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAdditionalParameters","kind":"identifier"}],"title":"SBSDKBarcodeAdditionalParameters","role":"symbol","abstract":[{"text":"A class that contains additional parameters for barcodes detection and filtering.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAdditionalParameters","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeadditionalparameters","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","type":"topic","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","url":"\/documentation\/scanbotsdk\/sbsdkbarcodemsiplesseychecksumalgorithm","kind":"symbol","abstract":[{"type":"text","text":"The checksum algorithm for MSI-Plessey type barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"msiPlesseyChecksumAlgorithm","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod10\/title","op":"replace","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod10\/fragments","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters~1msiPlesseyChecksumAlgorithm\/title","value":"msiPlesseyChecksumAlgorithm"},{"value":[{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters~1msiPlesseyChecksumAlgorithm\/fragments"},{"value":"SBSDKBarcodeAdditionalParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAdditionalParameters"}]},{"value":[{"text":"SBSDKBarcodeAdditionalParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAdditionalParameters\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"op":"replace"}]}]}