{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airlineDesignatorOfBoardingPassIssuer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/airlinedesignatorofboardingpassissuer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/airlinedesignatorofboardingpassissuer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType\/airlineDesignatorOfBoardingPassIssuer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Airline designator of boarding pass issuer"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airlineDesignatorOfBoardingPassIssuer"}],"title":"SBSDKUI2BoardingPassDocumentFieldType.airlineDesignatorOfBoardingPassIssuer","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2BoardingPassDocumentFieldType@SBSDKUI2BoardingPassDocumentFieldTypeAirlineDesignatorOfBoardingPassIssuer","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineDesignatorOfBoardingPassIssuer"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"Boarding Pass Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BoardingPassDocumentFieldType/airlineDesignatorOfBoardingPassIssuer":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType.airlineDesignatorOfBoardingPassIssuer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airlineDesignatorOfBoardingPassIssuer"}],"abstract":[{"type":"text","text":"Airline designator of boarding pass issuer"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType\/airlineDesignatorOfBoardingPassIssuer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineDesignatorOfBoardingPassIssuer"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/airlinedesignatorofboardingpassissuer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineDesignatorOfBoardingPassIssuer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineDesignatorOfBoardingPassIssuer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineDesignatorOfBoardingPassIssuer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType\/title","value":"SBSDKUI2BoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType~1airlineDesignatorOfBoardingPassIssuer\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineDesignatorOfBoardingPassIssuer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType~1airlineDesignatorOfBoardingPassIssuer\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineDesignatorOfBoardingPassIssuer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}