{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airlineNumericCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/airlinenumericcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/airlinenumericcode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType\/airlineNumericCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Airline numeric code"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airlineNumericCode"}],"title":"SBSDKUI2BoardingPassDocumentFieldType.airlineNumericCode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2BoardingPassDocumentFieldType@SBSDKUI2BoardingPassDocumentFieldTypeAirlineNumericCode","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineNumericCode"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BoardingPassDocumentFieldType/airlineNumericCode":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType.airlineNumericCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airlineNumericCode"}],"abstract":[{"type":"text","text":"Airline numeric code"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType\/airlineNumericCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineNumericCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/airlinenumericcode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"Boarding Pass Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineNumericCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineNumericCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineNumericCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType~1airlineNumericCode\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineNumericCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType~1airlineNumericCode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeAirlineNumericCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType\/title","value":"SBSDKUI2BoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}