{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"baggageTagLicensePlateNumbers"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/baggagetaglicenseplatenumbers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/baggagetaglicenseplatenumbers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType\/baggageTagLicensePlateNumbers","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Baggage tag license plate numbers"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"baggageTagLicensePlateNumbers"}],"title":"SBSDKUI2BoardingPassDocumentFieldType.baggageTagLicensePlateNumbers","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2BoardingPassDocumentFieldType@SBSDKUI2BoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BoardingPassDocumentFieldType/baggageTagLicensePlateNumbers":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType.baggageTagLicensePlateNumbers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"baggageTagLicensePlateNumbers"}],"abstract":[{"type":"text","text":"Baggage tag license plate numbers"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType\/baggageTagLicensePlateNumbers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype\/baggagetaglicenseplatenumbers"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"Boarding Pass Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2boardingpassdocumentfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType~1baggageTagLicensePlateNumbers\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType~1baggageTagLicensePlateNumbers\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeBaggageTagLicensePlateNumbers"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType\/title","value":"SBSDKUI2BoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}