{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration\/australiaPostCustomerFormat","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformataustraliapostconfiguration\/australiapostcustomerformat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformataustraliapostconfiguration\/australiapostcustomerformat"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"australiaPostCustomerFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is ALPHA_NUMERIC","type":"text"}]}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"australiaPostCustomerFormat","kind":"identifier"}],"title":"australiaPostCustomerFormat","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatAustraliaPostConfiguration(py)australiaPostCustomerFormat"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat":{"role":"symbol","navigatorTitle":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","title":"SBSDKAustraliaPostCustomerFormat","url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat","type":"topic","abstract":[{"type":"text","text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatAustraliaPostConfiguration/australiaPostCustomerFormat":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"role":"symbol","abstract":[{"type":"text","text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62."}],"title":"australiaPostCustomerFormat","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformataustraliapostconfiguration\/australiapostcustomerformat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration\/australiaPostCustomerFormat","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatAustraliaPostConfiguration":{"abstract":[{"text":"Australia Post barcode configuration. Add to scanner configuration to scan Australia Post barcodes.","type":"text"}],"type":"topic","title":"SBSDKBarcodeFormatAustraliaPostConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatAustraliaPostConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatAustraliaPostConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformataustraliapostconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"australiaPostCustomerFormat"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"australiaPostCustomerFormat","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/title","op":"replace","value":"SBSDKAustraliaPostCustomerFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration~1australiaPostCustomerFormat\/title","value":"australiaPostCustomerFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration~1australiaPostCustomerFormat\/fragments","value":[{"kind":"identifier","text":"australiaPostCustomerFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/title","value":"SBSDKBarcodeFormatAustraliaPostConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatAustraliaPostConfiguration"}]},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatAustraliaPostConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/navigatorTitle"}]}]}