{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport\/overallSuspiciousData"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport"]]},"metadata":{"title":"overallSuspiciousData","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"overallSuspiciousData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"property","navigatorTitle":[{"text":"overallSuspiciousData","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSuspiciousDataVerificationReport(py)overallSuspiciousData"},"abstract":[{"type":"text","text":"Overall status of the suspicious data verification. Corresponds to the most severe status of all fields, i.e. if at least one field is suspicious, the overall status is suspicious."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"overallSuspiciousData"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/overallsuspiciousdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/overallsuspiciousdata"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"abstract":[{"text":"Report of the suspicious data document verification.","type":"text"}],"navigatorTitle":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport","title":"SBSDKSuspiciousDataVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSuspiciousDataVerificationReport/overallSuspiciousData":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSuspiciousDataVerificationReport\/overallSuspiciousData","kind":"symbol","title":"overallSuspiciousData","navigatorTitle":[{"text":"overallSuspiciousData","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdksuspiciousdataverificationreport\/overallsuspiciousdata","type":"topic","abstract":[{"type":"text","text":"Overall status of the suspicious data verification. Corresponds to the most severe status of all fields, i.e. if at least one field is suspicious, the overall status is suspicious."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overallSuspiciousData","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"overallSuspiciousData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"overallSuspiciousData","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"overallSuspiciousData"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/title","value":"SBSDKSuspiciousDataVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/fragments","value":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport\/navigatorTitle","value":[{"text":"SBSDKSuspiciousDataVerificationReport","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport~1overallSuspiciousData\/title","value":"overallSuspiciousData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSuspiciousDataVerificationReport~1overallSuspiciousData\/fragments","value":[{"text":"overallSuspiciousData","kind":"identifier"}]}]}]}