{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView(py)finderSafeArea","roleHeading":"Instance Property","navigatorTitle":[{"text":"finderSafeArea","kind":"identifier"}],"title":"finderSafeArea","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderSafeArea","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/findersafearea"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/findersafearea"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderSafeArea","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The area where the finder should be placed in the coordinate system of the receiver."},{"type":"text","text":" "},{"type":"text","text":"Is ignored if finder safe area is empty (zero height or width)."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderSafeArea","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"code":"CGRect.zero","type":"codeVoice"},{"type":"text","text":"."}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfinderview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"title":"SBSDKFinderView","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/finderSafeArea":{"abstract":[{"text":"The area where the finder should be placed in the coordinate system of the receiver.","type":"text"},{"text":" ","type":"text"},{"text":"Is ignored if finder safe area is empty (zero height or width).","type":"text"}],"title":"finderSafeArea","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderSafeArea","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/findersafearea","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/finderSafeArea","navigatorTitle":[{"text":"finderSafeArea","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"finderSafeArea"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"finderSafeArea","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"finderSafeArea","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","op":"replace","value":"SBSDKFinderView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderView"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderSafeArea\/title","op":"replace","value":"finderSafeArea"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView~1finderSafeArea\/fragments","op":"replace","value":[{"kind":"identifier","text":"finderSafeArea"}]}]}]}