{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(recognizeFromImage:completion:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to run the optical character recognition on."}]}],"name":"image"},{"name":"completion","content":[{"inlineContent":[{"text":"The completion handler, delivering either the OCR result or an error.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"text":"The recognition runs asynchronously on a dedicated concurrent queue and the completion handler is called on the main thread.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognize"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ())"}],"navigatorTitle":[{"kind":"identifier","text":"recognizeFromImage:completion:"}],"role":"symbol","roleHeading":"Instance Method","title":"recognize(from:completion:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngine(im)recognizeFromImage:completion:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine\/recognize(from:completion:)-1piuv","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Recognizes characters on the given image and passes the result, or the error, to the completion handler."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:completion:)-1piuv"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:completion:)-1piuv"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResult":{"abstract":[{"type":"text","text":"The result of an optical character recognition."}],"type":"topic","title":"SBSDKOCRResult","url":"\/documentation\/scanbotsdk\/sbsdkocrresult","navigatorTitle":[{"text":"SBSDKOCRResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResult","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngine":{"type":"topic","navigatorTitle":[{"text":"SBSDKOCREngine","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrengine","title":"SBSDKOCREngine","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOCREngine"}],"abstract":[{"type":"text","text":"A class to perform optical character recognition (text) on an image (OCR)."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngine/recognize(from:completion:)-1piuv":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKOCRResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> ())"}],"navigatorTitle":[{"text":"recognizeFromImage:completion:","kind":"identifier"}],"kind":"symbol","title":"recognize(from:completion:)","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkocrengine\/recognize(from:completion:)-1piuv","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngine\/recognize(from:completion:)-1piuv","abstract":[{"text":"Recognizes characters on the given image and passes the result, or the error, to the completion handler.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"recognizeFromImage:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeFromImage:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"recognizeFromImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRResult","text":"SBSDKOCRResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResult"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image to run the optical character recognition on.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler, delivering either the OCR result or an error."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/title","value":"SBSDKOCRResult"},{"value":[{"text":"SBSDKOCRResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKOCRResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/title","value":"SBSDKOCREngine","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngine"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/fragments"},{"value":[{"text":"SBSDKOCREngine","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine~1recognize(from:completion:)-1piuv\/title","value":"recognizeFromImage:completion:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngine~1recognize(from:completion:)-1piuv\/fragments","value":[{"text":"- ","kind":"text"},{"text":"recognizeFromImage:completion:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}