{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategories\/l"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategories\/l"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategories"]]},"abstract":[{"text":"L.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategory"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategories(py)l","navigatorTitle":[{"text":"l","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","title":"l","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategories\/l"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeDriverLicenseBackCategories":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategories","abstract":[{"type":"text","text":"Categories table row container."}],"title":"SBSDKGenericDocumentDeDriverLicenseBackCategories","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategories","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategories","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategories","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeDriverLicenseBackCategories/l":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategories\/l","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategories\/l","navigatorTitle":[{"text":"l","kind":"identifier"}],"title":"l","kind":"symbol","abstract":[{"type":"text","text":"L."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeDriverLicenseBackCategory":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategory","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdedriverlicensebackcategory","title":"SBSDKGenericDocumentDeDriverLicenseBackCategory","abstract":[{"type":"text","text":"A category row from the categories table."}],"navigatorTitle":[{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"l","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"l","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeDriverLicenseBackCategory","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeDriverLicenseBackCategory"},{"kind":"text","text":" * "},{"kind":"identifier","text":"l"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKGenericDocumentDeDriverLicenseBackCategories","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories\/title"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategories","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentDeDriverLicenseBackCategories"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories\/navigatorTitle"},{"op":"replace","value":"l","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories~1l\/title"},{"op":"replace","value":[{"kind":"identifier","text":"l"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategories~1l\/fragments"},{"op":"replace","value":"SBSDKGenericDocumentDeDriverLicenseBackCategory","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategory\/title"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategory\/fragments"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentDeDriverLicenseBackCategory","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeDriverLicenseBackCategory\/navigatorTitle"}]}]}