{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHD","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullHD","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionFullHD","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"case","title":"SBSDKVideoFrameResolution.fullHD","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionFullHD"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/fullHD","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Select a full HD (1920x1080) video resolution."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution\/fullhd"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution\/fullhd"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoFrameResolution/fullHD":{"abstract":[{"type":"text","text":"Select a full HD (1920x1080) video resolution."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullHD"}],"navigatorTitle":[{"text":"SBSDKVideoFrameResolutionFullHD","kind":"identifier"}],"title":"SBSDKVideoFrameResolution.fullHD","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution\/fullhd","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/fullHD"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoFrameResolution":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution","role":"symbol","title":"SBSDKVideoFrameResolution","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVideoFrameResolutionFullHD"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKVideoFrameResolutionFullHD","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution~1fullHD\/title","value":"SBSDKVideoFrameResolutionFullHD"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution~1fullHD\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}]},{"value":"SBSDKVideoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/navigatorTitle","op":"replace"}]}]}