{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Select the photo preset for best quality when capturing images.","type":"text"}],"kind":"symbol","sections":[],"metadata":{"title":"SBSDKVideoFrameResolution.photo","symbolKind":"case","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"photo","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionPhoto","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/photo"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution\/photo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution\/photo"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoFrameResolution/photo":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution\/photo","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution\/photo","type":"topic","abstract":[{"text":"Select the photo preset for best quality when capturing images.","type":"text"}],"role":"symbol","title":"SBSDKVideoFrameResolution.photo","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"photo","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoFrameResolution":{"type":"topic","title":"SBSDKVideoFrameResolution","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoFrameResolution","kind":"symbol","role":"symbol","abstract":[{"text":"An enum describing the resolution of a video or camera stream.","type":"text"}],"navigatorTitle":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoframeresolution"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKVideoFrameResolutionPhoto","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionPhoto"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionPhoto"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution~1photo\/title","value":"SBSDKVideoFrameResolutionPhoto","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution~1photo\/fragments","value":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/title","value":"SBSDKVideoFrameResolution","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoFrameResolution\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}