{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVADLID\/addressCity","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVADLID"]]},"abstract":[{"text":"Data element ID “DAI”. City portion of the cardholder address.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelAAMVADLID(py)addressCity","roleHeading":"Instance Property","navigatorTitle":[{"text":"addressCity","kind":"identifier"}],"title":"addressCity","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressCity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressCity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamvadlid\/addresscity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamvadlid\/addresscity"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelAAMVADLID":{"kind":"symbol","type":"topic","title":"SBSDKBarcodeDocumentModelAAMVADLID","abstract":[{"type":"text","text":"Driver License Or ID Document"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamvadlid","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVADLID","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelAAMVADLID","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelAAMVADLID","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","abstract":[{"type":"text","text":"Generic document field."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","title":"SBSDKGenericDocumentField"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelAAMVADLID/addressCity":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelaamvadlid\/addresscity","title":"addressCity","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelAAMVADLID\/addressCity","abstract":[{"text":"Data element ID “DAI”. City portion of the cardholder address.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressCity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"addressCity","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"addressCity","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"addressCity","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":" * ","kind":"text"},{"text":"addressCity","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeDocumentModelAAMVADLID","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVADLID\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVADLID"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVADLID\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVADLID\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelAAMVADLID"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","op":"replace","value":"SBSDKGenericDocumentField"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVADLID~1addressCity\/title","value":"addressCity","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelAAMVADLID~1addressCity\/fragments","value":[{"kind":"identifier","text":"addressCity"}],"op":"replace"}]}]}