{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/nofilter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/nofilter"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter\/noFilter"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noFilter"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKUIBarcodesExtensionFilter@SBSDKUIBarcodesExtensionFilterNoFilter","title":"SBSDKUIBarcodesExtensionFilter.noFilter","navigatorTitle":[{"text":"SBSDKUIBarcodesExtensionFilterNoFilter","kind":"identifier"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noFilter"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"EAN and UPC barcoded with or without extensions will be returned."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesExtensionFilter":{"abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter","type":"topic","kind":"symbol","role":"symbol","title":"SBSDKUIBarcodesExtensionFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesExtensionFilter/noFilter":{"navigatorTitle":[{"text":"SBSDKUIBarcodesExtensionFilterNoFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"EAN and UPC barcoded with or without extensions will be returned."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noFilter","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter\/noFilter","title":"SBSDKUIBarcodesExtensionFilter.noFilter","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/nofilter","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUIBarcodesExtensionFilterNoFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUIBarcodesExtensionFilterNoFilter","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKUIBarcodesExtensionFilterNoFilter","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SBSDKUIBarcodesExtensionFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/fragments","value":[{"text":"SBSDKUIBarcodesExtensionFilter","kind":"identifier"}]},{"value":[{"text":"SBSDKUIBarcodesExtensionFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter~1noFilter\/title","value":"SBSDKUIBarcodesExtensionFilterNoFilter"},{"op":"replace","value":[{"text":"SBSDKUIBarcodesExtensionFilterNoFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter~1noFilter\/fragments"}]}]}