{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/onlywithextensions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/onlywithextensions"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter\/onlyWithExtensions"},"abstract":[{"text":"Only EAN and UPC barcoded with extensions will be returned.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter"]]},"kind":"symbol","metadata":{"roleHeading":"Case","title":"SBSDKUIBarcodesExtensionFilter.onlyWithExtensions","externalID":"c:@M@ScanbotSDK@E@SBSDKUIBarcodesExtensionFilter@SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlyWithExtensions"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyWithExtensions"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesExtensionFilter":{"abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter","type":"topic","kind":"symbol","role":"symbol","title":"SBSDKUIBarcodesExtensionFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesExtensionFilter/onlyWithExtensions":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onlyWithExtensions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesExtensionFilter\/onlyWithExtensions","abstract":[{"type":"text","text":"Only EAN and UPC barcoded with extensions will be returned."}],"title":"SBSDKUIBarcodesExtensionFilter.onlyWithExtensions","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesextensionfilter\/onlywithextensions","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}]}]}},{"value":"SBSDKUIBarcodesExtensionFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"op":"replace"},{"op":"replace","value":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter~1onlyWithExtensions\/title"},{"op":"replace","value":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesExtensionFilter~1onlyWithExtensions\/fragments"}]}]}