{"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"large"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2CollapsedVisibleHeight@SBSDKUI2CollapsedVisibleHeightLarge","title":"SBSDKUI2CollapsedVisibleHeight.large","roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"SBSDKUI2CollapsedVisibleHeightLarge","kind":"identifier"}]},"abstract":[{"type":"text","text":"Result sheet is not completely collapsed, revealing more information."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"large"}]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2collapsedvisibleheight\/large"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2collapsedvisibleheight\/large"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight\/large"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CollapsedVisibleHeight":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2collapsedvisibleheight","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the barcodes result sheet’s height while collapsed."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight","title":"SBSDKUI2CollapsedVisibleHeight"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CollapsedVisibleHeight/large":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"large","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CollapsedVisibleHeight\/large","type":"topic","kind":"symbol","abstract":[{"text":"Result sheet is not completely collapsed, revealing more information.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2collapsedvisibleheight\/large","navigatorTitle":[{"text":"SBSDKUI2CollapsedVisibleHeightLarge","kind":"identifier"}],"title":"SBSDKUI2CollapsedVisibleHeight.large"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKUI2CollapsedVisibleHeightLarge","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2CollapsedVisibleHeightLarge","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKUI2CollapsedVisibleHeightLarge","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/title","value":"SBSDKUI2CollapsedVisibleHeight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}]},{"value":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight\/navigatorTitle"},{"value":"SBSDKUI2CollapsedVisibleHeightLarge","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight~1large\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeightLarge"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CollapsedVisibleHeight~1large\/fragments"}]}]}