{"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"imageDecrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGenerator(im)generateFromImageURLs:imageDecrypter:toFileURL:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"generate(from:imageDecrypter:to:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"generateFromImageURLs:imageDecrypter:toFileURL:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:imageDecrypter:to:)-2kxqv"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Synchronously converts the images at the given image URLs to a multipage-TIFF file and saves it to the specified URL."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:imagedecrypter:to:)-2kxqv"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:imagedecrypter:to:)-2kxqv"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(generateFromImageURLs:imageDecrypter:toFileURL:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"imageDecrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The array of image URLs to generate the multipage-TIFF from."}],"type":"paragraph"}],"name":"imageURLs"},{"content":[{"inlineContent":[{"text":"The decrypter to use for the images. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" the images are assumed to be unencrypted.","type":"text"}],"type":"paragraph"}],"name":"imageDecrypter"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}],"name":"fileURL"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the operation was successful, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator","title":"SBSDKTIFFGenerator","abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"type":"text","text":" "},{"type":"text","text":"When passing an encrypter the generated TIFF images will be encrypted."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"title":"SBSDKStorageCrypting","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","role":"symbol","navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator/generate(from:imageDecrypter:to:)-2kxqv":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:imagedecrypter:to:)-2kxqv","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:imageDecrypter:to:)-2kxqv","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"imageDecrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"generate(from:imageDecrypter:to:)","abstract":[{"type":"text","text":"Synchronously converts the images at the given image URLs to a multipage-TIFF file and saves it to the specified URL."}],"navigatorTitle":[{"text":"generateFromImageURLs:imageDecrypter:toFileURL:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"generateFromImageURLs:imageDecrypter:toFileURL:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateFromImageURLs:imageDecrypter:toFileURL:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"generateFromImageURLs:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSURL *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageURLs"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageDecrypter:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"id<SBSDKStorageCrypting>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageDecrypter"},{"kind":"text","text":" "},{"kind":"identifier","text":"toFileURL:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The array of image URLs to generate the multipage-TIFF from.","type":"text"}],"type":"paragraph"}],"name":"imageURLs"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The decrypter to use for the images. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" the images are assumed to be unencrypted.","type":"text"}]}],"name":"imageDecrypter"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}],"name":"fileURL"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the operation was successful, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}]}],"kind":"content"}},{"op":"replace","value":"SBSDKTIFFGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/fragments"},{"op":"replace","value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/navigatorTitle"},{"op":"replace","value":"SBSDKStorageCrypting","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments"},{"op":"replace","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle"},{"op":"replace","value":"generateFromImageURLs:imageDecrypter:toFileURL:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1generate(from:imageDecrypter:to:)-2kxqv\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateFromImageURLs:imageDecrypter:toFileURL:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1generate(from:imageDecrypter:to:)-2kxqv\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}