{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio","text":"SBSDKUI2AspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aspectratio\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AspectRatio(cm)fromJsonWithJson:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio\/fromJsonWithJson:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AspectRatio/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aspectratio\/fromjsonwithjson:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio\/fromJsonWithJson:","kind":"symbol","title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AspectRatio":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aspectratio","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AspectRatio"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AspectRatio","abstract":[{"text":"Configuration of the finder’s aspect ratio.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKUI2AspectRatio"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2AspectRatio","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/fragments","op":"replace","value":[{"text":"SBSDKUI2AspectRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AspectRatio\/navigatorTitle","value":[{"text":"SBSDKUI2AspectRatio","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}