{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/valid","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"SBSDKValueSemanticsValid","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKValueSemantics@SBSDKValueSemanticsValid","roleHeading":"Case","title":"SBSDKValueSemantics.valid","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}],"role":"symbol","symbolKind":"case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/valid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/valid"]}],"abstract":[{"type":"text","text":"No errors were detected during semantics verification. For example, the date of birth is in the past, the date"},{"type":"text","text":" "},{"text":"of expiry is in the future.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics":{"type":"topic","title":"SBSDKValueSemantics","abstract":[{"type":"text","text":"The result of the value semantics verification."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","navigatorTitle":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKValueSemantics","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/valid":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKValueSemanticsValid"}],"kind":"symbol","role":"symbol","title":"SBSDKValueSemantics.valid","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/valid","type":"topic","abstract":[{"text":"No errors were detected during semantics verification. For example, the date of birth is in the past, the date","type":"text"},{"type":"text","text":" "},{"text":"of expiry is in the future.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/valid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKValueSemanticsValid"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKValueSemanticsValid","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKValueSemanticsValid","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/title","op":"replace","value":"SBSDKValueSemantics"},{"value":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKValueSemantics"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1valid\/title","value":"SBSDKValueSemanticsValid"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1valid\/fragments","value":[{"text":"SBSDKValueSemanticsValid","kind":"identifier"}],"op":"replace"}]}]}