{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"vehicleData","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeDocumentAAMVAVehicleData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleData","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleData"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"VehicleData."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVA\/vehicleData"},"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"vehicleData","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVA(py)vehicleData","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"vehicleData"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vehicleData"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVAVehicleData","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleData"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVA"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamva\/vehicledata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamva\/vehicledata"]}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVA/vehicleData":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVA\/vehicleData","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamva\/vehicledata","abstract":[{"text":"VehicleData.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"vehicleData","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleData","text":"SBSDKBarcodeDocumentAAMVAVehicleData"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"vehicleData","kind":"identifier"}],"title":"vehicleData"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVAVehicleData":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvavehicledata","title":"SBSDKBarcodeDocumentAAMVAVehicleData","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleData","kind":"identifier"}],"abstract":[{"text":"Vehicle Data. File type “VH”.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentAAMVAVehicleData","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVA":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVA","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamva","type":"topic","abstract":[{"text":"AAMVA.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVA","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVA","kind":"identifier"}],"title":"SBSDKBarcodeDocumentAAMVA"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.1"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"vehicleData"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"vehicleData"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVAVehicleData","text":"SBSDKBarcodeDocumentAAMVAVehicleData","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVAVehicleData"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"vehicleData"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVA~1vehicleData\/title","op":"replace","value":"vehicleData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVA~1vehicleData\/fragments","value":[{"text":"vehicleData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleData\/title","value":"SBSDKBarcodeDocumentAAMVAVehicleData"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleData\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVAVehicleData\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVAVehicleData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVA\/title","op":"replace","value":"SBSDKBarcodeDocumentAAMVA"},{"value":[{"text":"SBSDKBarcodeDocumentAAMVA","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVA\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVA\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVA","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}