{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/initWithUniqueId:timestampCreated:strongReferences:serializedReferences:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUniqueId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uniqueId"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestampCreated:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"timestampCreated"},{"kind":"text","text":" "},{"kind":"identifier","text":"strongReferences:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"strongReferences"},{"kind":"text","text":" "},{"kind":"identifier","text":"serializedReferences:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"serializedReferences"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRefCountedObjectProfile(im)initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","symbolKind":"method","title":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/initwithuniqueid:timestampcreated:strongreferences:serializedreferences:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile/initWithUniqueId:timestampCreated:strongReferences:serializedReferences:":{"role":"symbol","navigatorTitle":[{"text":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","kind":"identifier"}],"title":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/initwithuniqueid:timestampcreated:strongreferences:serializedreferences:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile":{"abstract":[{"type":"text","text":"Profile info of a reference-counted stored object."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile","title":"SBSDKRefCountedObjectProfile","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/title","value":"SBSDKRefCountedObjectProfile","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/fragments","value":[{"kind":"identifier","text":"SBSDKRefCountedObjectProfile"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"op":"replace"}]}]}