{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installlanguages()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installlanguages()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Installs the default and custom OCR language files and prepares them for usage.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"installLanguages","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"text":" if all languages have been installed successfully, ","type":"text"},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"Language files that are already in place are not being overwritten.","type":"text"},{"text":" ","type":"text"},{"text":"If you want to force a new set of language files you must call ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/resetInstalledLanguages()","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default languages are being installed from the "},{"code":"SBSDKOCRData.bundle","type":"codeVoice"},{"type":"text","text":" that your app should ship."},{"type":"text","text":" "},{"type":"text","text":"Custom languages are installed from the custom languages folder: "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/customLanguagesFolderURL"},{"text":".","type":"text"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installLanguages()","interfaceLanguage":"swift"},"metadata":{"title":"installLanguages()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installLanguages"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"installLanguages"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRLanguagesManager(cm)installLanguages","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Type Method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager","title":"SBSDKOCRLanguagesManager","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKOCRLanguagesManager","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Helper class to manage trained data files for the Tesseract OCR engine."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/resetInstalledLanguages()":{"kind":"symbol","navigatorTitle":[{"text":"resetInstalledLanguages","kind":"identifier"}],"type":"topic","abstract":[{"text":"Removes all installed OCR languages and reinstalls them.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/resetInstalledLanguages()","title":"resetInstalledLanguages()","url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/resetinstalledlanguages()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"resetInstalledLanguages","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/installLanguages()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"installLanguages","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/installlanguages()","title":"installLanguages()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"installLanguages","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Installs the default and custom OCR language files and prepares them for usage."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/installLanguages()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRLanguagesManager/customLanguagesFolderURL":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customLanguagesFolderURL","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrlanguagesmanager\/customlanguagesfolderurl","title":"customLanguagesFolderURL","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"customLanguagesFolderURL","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The URL of the folder for custom language trained data files."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRLanguagesManager\/customLanguagesFolderURL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"installLanguages","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"installLanguages","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"installLanguages"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/title","value":"SBSDKOCRLanguagesManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager\/fragments","value":[{"kind":"identifier","text":"SBSDKOCRLanguagesManager"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1resetInstalledLanguages()\/title","value":"resetInstalledLanguages"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1resetInstalledLanguages()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"resetInstalledLanguages"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installLanguages()\/title","value":"installLanguages"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1installLanguages()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"installLanguages"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1customLanguagesFolderURL\/title","value":"customLanguagesFolderURL"},{"op":"replace","value":[{"kind":"identifier","text":"customLanguagesFolderURL"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRLanguagesManager~1customLanguagesFolderURL\/fragments"}]}]}