{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/RawRepresentable-Implementations"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/hashValue","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"extendedModule":"Swift","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@ScanbotSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","roleHeading":"Instance Property","modules":[{"relatedModules":["Swift"],"name":"ScanbotSDK"}],"role":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"hashValue","symbolKind":"property"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/RawRepresentable-Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}],"title":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization","url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CapturePhotoQualityPrioritization/hashValue":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CapturePhotoQualityPrioritization\/hashValue","title":"hashValue","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2capturephotoqualityprioritization\/hashvalue","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title","op":"replace","value":"SBSDKUI2CapturePhotoQualityPrioritization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments","op":"replace","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}