{"sections":[],"kind":"symbol","metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"both","kind":"identifier"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"SBSDKVideoFlipModeBoth","kind":"identifier"}],"title":"SBSDKVideoFlipMode.both","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVideoFlipMode@SBSDKVideoFlipModeBoth"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode\/both","interfaceLanguage":"swift"},"abstract":[{"text":"Flip the image both, horizontally and vertically.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/both"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/both"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"both","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFlipMode/both":{"title":"SBSDKVideoFlipMode.both","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode\/both","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvideoflipmode\/both","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFlipModeBoth"}],"abstract":[{"type":"text","text":"Flip the image both, horizontally and vertically."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"both"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFlipMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFlipMode","title":"SBSDKVideoFlipMode","navigatorTitle":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoflipmode","type":"topic","role":"symbol","abstract":[{"text":"An enum describing how images can be flipped.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVideoFlipMode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKVideoFlipModeBoth","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKVideoFlipModeBoth","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKVideoFlipModeBoth","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode~1both\/title","value":"SBSDKVideoFlipModeBoth"},{"value":[{"text":"SBSDKVideoFlipModeBoth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode~1both\/fragments"},{"op":"replace","value":"SBSDKVideoFlipMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/fragments","op":"replace","value":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFlipMode\/navigatorTitle","value":[{"text":"SBSDKVideoFlipMode","kind":"identifier"}]}]}]}