{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode","text":"SBSDKCheckDocumentDetectionMode"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"By default only the machine-readable data is extracted during check scanning. Optionally, the coordinates and a crop of the entire check document can be returned, in addition to the check data."},{"type":"text","text":" "},{"type":"text","text":"A check scan result may still be successful even if the whole document is not visible in the input image and the complete document could not be located."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If cropping is enabled, check recognition will be performed on the cropped image of the check, which may improve recognition results."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is DISABLED"}]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"documentDetectionMode","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode","text":"SBSDKCheckDocumentDetectionMode"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration(py)documentDetectionMode","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"documentDetectionMode"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Document detection to be performed in addition to scanning the machine-readable data in the check."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/documentdetectionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/documentdetectionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/documentDetectionMode","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration/documentDetectionMode":{"abstract":[{"type":"text","text":"Document detection to be performed in addition to scanning the machine-readable data in the check."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode","text":"SBSDKCheckDocumentDetectionMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/documentDetectionMode","navigatorTitle":[{"kind":"identifier","text":"documentDetectionMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/documentdetectionmode","title":"documentDetectionMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","abstract":[{"type":"text","text":"Configuration of the check scanner."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"title":"SBSDKCheckScannerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode":{"abstract":[{"type":"text","text":"Check document detection and extraction mode."}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","role":"symbol","type":"topic","title":"SBSDKCheckDocumentDetectionMode","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"documentDetectionMode","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"documentDetectionMode"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode","kind":"typeIdentifier","text":"SBSDKCheckDocumentDetectionMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDetectionMode"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"documentDetectionMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration~1documentDetectionMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentDetectionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration~1documentDetectionMode\/fragments"},{"op":"replace","value":"SBSDKCheckScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKCheckDocumentDetectionMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/title"},{"op":"replace","value":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}