{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine"]]},"sections":[],"abstract":[{"type":"text","text":"A list of all children of type “Substance”."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"substances","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"substances","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine(py)substances","title":"substances","navigatorTitle":[{"kind":"identifier","text":"substances"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine\/substances","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodeldemedicalplansubheadingmedicine\/substances"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodeldemedicalplansubheadingmedicine\/substances"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodeldemedicalplansubheadingmedicinesubstance","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","abstract":[{"type":"text","text":"Substance"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance"}],"title":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine/substances":{"abstract":[{"text":"A list of all children of type “Substance”.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine\/substances","kind":"symbol","title":"substances","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"substances","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"substances","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodeldemedicalplansubheadingmedicine\/substances"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine","title":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodeldemedicalplansubheadingmedicine","abstract":[{"text":"Medicine","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"substances","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"substances","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"substances","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance\/title","value":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicineSubstance"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine~1substances\/title","value":"substances"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine~1substances\/fragments","value":[{"text":"substances","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine\/title","value":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelDEMedicalPlanSubheadingMedicine","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}