{"metadata":{"role":"symbol","title":"close()","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanningResult(im)close","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"close","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"close","kind":"identifier"},{"text":"()","kind":"text"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"close","kind":"identifier"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult\/close()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanningresult\/close()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanningresult\/close()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanningResult":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult","title":"SBSDKCheckScanningResult","navigatorTitle":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The result of check scanning."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscanningresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanningResult/close()":{"role":"symbol","title":"close()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanningResult\/close()","url":"\/documentation\/scanbotsdk\/sbsdkcheckscanningresult\/close()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"close","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"close","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"close","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"close"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"close"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/title","value":"SBSDKCheckScanningResult"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckScanningResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/fragments"},{"value":[{"text":"SBSDKCheckScanningResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult~1close()\/title","value":"close","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanningResult~1close()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"close"}],"op":"replace"}]}]}