{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/skipped","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"SBSDKValueSemantics.skipped","roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skipped","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKValueSemanticsSkipped","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKValueSemantics@SBSDKValueSemanticsSkipped"},"abstract":[{"text":"Verification of the value semantics was skipped. For example, because the field is empty.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipped"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/skipped"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/skipped"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","abstract":[{"text":"The result of the value semantics verification.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics","role":"symbol","title":"SBSDKValueSemantics","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKValueSemantics","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKValueSemantics","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/skipped":{"role":"symbol","title":"SBSDKValueSemantics.skipped","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/skipped","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"skipped","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKValueSemanticsSkipped","kind":"identifier"}],"abstract":[{"type":"text","text":"Verification of the value semantics was skipped. For example, because the field is empty."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/skipped"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SBSDKValueSemanticsSkipped","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKValueSemanticsSkipped"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKValueSemanticsSkipped","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKValueSemantics","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/title"},{"value":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKValueSemantics"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1skipped\/title","value":"SBSDKValueSemanticsSkipped"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1skipped\/fragments","value":[{"kind":"identifier","text":"SBSDKValueSemanticsSkipped"}],"op":"replace"}]}]}