{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRegexFilter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"regexFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumSizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAdditionalQuietZone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"addAdditionalQuietZone"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKGS1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGS1Handling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling"},{"kind":"text","text":") "},{"kind":"internalParam","text":"gs1Handling"},{"kind":"text","text":" "},{"kind":"identifier","text":"strictMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"strictMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"qr:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"qr"},{"kind":"text","text":" "},{"kind":"identifier","text":"microQr:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"microQr"},{"kind":"text","text":" "},{"kind":"identifier","text":"rmqr:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rmqr"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatQRCodeConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","symbolKind":"method"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:gs1handling:strictmode:qr:microqr:rmqr:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling":{"role":"symbol","title":"SBSDKGS1Handling","url":"\/documentation\/scanbotsdk\/sbsdkgs1handling","navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"abstract":[{"text":"GS1 message handling options.","type":"text"},{"text":" ","type":"text"},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D barcode types.","type":"text"},{"text":" ","type":"text"},{"text":"https:\/\/ref.gs1.org\/standards\/genspecs\/","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1Handling"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration":{"abstract":[{"type":"text","text":"QR Code configuration. Add to scanner configuration to scan QR codes, Micro QR codes and rectangular Micro QR (rMQR) codes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"title":"SBSDKBarcodeFormatQRCodeConfiguration","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:gs1handling:strictmode:qr:microqr:rmqr:","type":"topic","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:","kind":"identifier"}],"title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:gs1Handling:strictMode:qr:microQr:rmqr:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/title","op":"replace","value":"SBSDKGS1Handling"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/fragments","op":"replace","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatQRCodeConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}