{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatQRCodeConfiguration(py)qr","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qr","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","title":"qr","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"qr","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/qr","interfaceLanguage":"swift"},"abstract":[{"text":"If true, scan and return QR codes.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qr","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is true"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/qr"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/qr"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration/qr":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration\/qr","abstract":[{"type":"text","text":"If true, scan and return QR codes."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"qr"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration\/qr","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"qr"}],"type":"topic","kind":"symbol","title":"qr"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatQRCodeConfiguration":{"abstract":[{"type":"text","text":"QR Code configuration. Add to scanner configuration to scan QR codes, Micro QR codes and rectangular Micro QR (rMQR) codes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatQRCodeConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatqrcodeconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"title":"SBSDKBarcodeFormatQRCodeConfiguration","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"qr"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"qr"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"qr"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1qr\/title","value":"qr"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration~1qr\/fragments","value":[{"kind":"identifier","text":"qr"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/title","value":"SBSDKBarcodeFormatQRCodeConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatQRCodeConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatQRCodeConfiguration","kind":"identifier"}]}]}]}