{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"SBSDKEncodingFormatPng","kind":"identifier"}],"title":"SBSDKEncodingFormat.png","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncodingFormat@SBSDKEncodingFormatPng","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"png"}]},"abstract":[{"type":"text","text":"PNG encoding."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"png","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencodingformat\/png"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencodingformat\/png"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodingFormat"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodingFormat\/png","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodingFormat":{"abstract":[{"type":"text","text":"Image Encoding Format."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodingformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"title":"SBSDKEncodingFormat","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKEncodingFormat"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodingFormat"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodingFormat/png":{"abstract":[{"type":"text","text":"PNG encoding."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodingformat\/png","navigatorTitle":[{"text":"SBSDKEncodingFormatPng","kind":"identifier"}],"title":"SBSDKEncodingFormat.png","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodingFormat\/png","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"png"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKEncodingFormatPng"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKEncodingFormatPng","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKEncodingFormatPng"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SBSDKEncodingFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodingFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodingFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodingFormat\/navigatorTitle","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]},{"op":"replace","value":"SBSDKEncodingFormatPng","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodingFormat~1png\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodingFormat~1png\/fragments","op":"replace","value":[{"text":"SBSDKEncodingFormatPng","kind":"identifier"}]}]}]}