{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Updates the frame of the tracking view to match the position and size of the associated barcode.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcodeFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"isHighlighted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"textStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle"},{"text":", ","kind":"text"},{"text":"polygonStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKTrackedBarcodeInfoViewable(im)updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:","required":true,"title":"update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)","role":"symbol","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable\/update(barcodeframe:ishighlighted:textstyle:polygonstyle:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable\/update(barcodeframe:ishighlighted:textstyle:polygonstyle:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable\/update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcodeFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"isHighlighted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"textStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle"},{"text":", ","kind":"text"},{"text":"polygonStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewPolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The frame of the scanned barcode within the coordinate system of the tracking view’s superview.","type":"text"}],"type":"paragraph"}],"name":"barcodeFrame"},{"content":[{"inlineContent":[{"text":"A boolean value that indicates whether the associated barcode is highlighted.","type":"text"}],"type":"paragraph"}],"name":"isHighlighted"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The text style of the receiver.","type":"text"}]}],"name":"textStyle"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon style of the receiver."}]}],"name":"polygonStyle"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"name":"Note","content":[{"inlineContent":[{"text":"Implement this method to update the position and size of the tracking view based on the scanned barcode’s frame.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayController":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontroller","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"title":"SBSDKBarcodeTrackingOverlayController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","type":"topic","abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing scanned barcodes."},{"type":"text","text":" "},{"type":"text","text":"It provides a customizable user interface for displaying barcodes and supports interaction with them."},{"type":"text","text":" "},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayConfiguration":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlayconfiguration","abstract":[{"type":"text","text":"A class that represents the configuration options for a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This overlay is used to visualize the scanned barcodes on the screen."},{"type":"text","text":" "},{"type":"text","text":"The class provides various customization options for the appearance and behavior of the overlay."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration","title":"SBSDKBarcodeTrackingOverlayConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackedViewTextStyle":{"abstract":[{"type":"text","text":"A class that represents the style and kind of the text rendered below a barcode in "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackedviewtextstyle","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}],"title":"SBSDKBarcodeTrackedViewTextStyle","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackedViewPolygonStyle":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackedviewpolygonstyle","role":"symbol","title":"SBSDKBarcodeTrackedViewPolygonStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewPolygonStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewPolygonStyle"}],"kind":"symbol","abstract":[{"type":"text","text":"A class that represents the style of the polygon rendered around a barcode in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKTrackedBarcodeInfoViewable/update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable\/update(barcodeframe:ishighlighted:textstyle:polygonstyle:)","navigatorTitle":[{"text":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:","kind":"identifier"}],"title":"update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable\/update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)","required":true,"type":"topic","abstract":[{"text":"Updates the frame of the tracking view to match the position and size of the associated barcode.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"update","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcodeFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"isHighlighted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"textStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle"},{"text":", ","kind":"text"},{"text":"polygonStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKTrackedBarcodeInfoViewable":{"navigatorTitle":[{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"abstract":[{"text":"A protocol that defines the methods and properties required for a custom tracking view to be displayed over scanned barcodes using the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration","type":"reference"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The custom view must conform to this protocol in order to be used as an overlay on top of the scanned barcodes.","type":"text"}],"title":"SBSDKTrackedBarcodeInfoViewable","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable","type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateWithBarcodeFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"barcodeFrame"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isHighlighted","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","text":"SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"textStyle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"polygonStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackedViewPolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle","text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"polygonStyle","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The frame of the scanned barcode within the coordinate system of the tracking view’s superview."}],"type":"paragraph"}],"name":"barcodeFrame"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A boolean value that indicates whether the associated barcode is highlighted."}]}],"name":"isHighlighted"},{"content":[{"inlineContent":[{"text":"The text style of the receiver.","type":"text"}],"type":"paragraph"}],"name":"textStyle"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The polygon style of the receiver.","type":"text"}]}],"name":"polygonStyle"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKBarcodeTrackingOverlayController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/title","value":"SBSDKBarcodeTrackingOverlayConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/fragments","value":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/title","value":"SBSDKBarcodeTrackedViewTextStyle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewTextStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/title","value":"SBSDKBarcodeTrackedViewPolygonStyle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/fragments","value":[{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackedViewPolygonStyle\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackedViewPolygonStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable~1update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)\/title","value":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable~1update(barcodeFrame:isHighlighted:textStyle:polygonStyle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateWithBarcodeFrame:isHighlighted:textStyle:polygonStyle:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable\/title","value":"SBSDKTrackedBarcodeInfoViewable","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable\/fragments","value":[{"text":"SBSDKTrackedBarcodeInfoViewable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"op":"replace"}]}]}