{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorEnhancement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is 0.5"}]}],"kind":"content"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/colorenhancement"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/colorenhancement"]}],"abstract":[{"text":"Strength of color saturation enhancement. Typical values are between 0 and 1, although higher values are possible.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorEnhancement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"colorEnhancement"}],"role":"symbol","roleHeading":"Instance Property","title":"colorEnhancement","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKColorDocumentFilter(py)colorEnhancement"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/colorEnhancement"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/colorEnhancement":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorEnhancement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"colorEnhancement","kind":"identifier"}],"title":"colorEnhancement","abstract":[{"type":"text","text":"Strength of color saturation enhancement. Typical values are between 0 and 1, although higher values are possible."}],"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/colorenhancement","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/colorEnhancement","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter":{"url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter","title":"SBSDKColorDocumentFilter","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter","navigatorTitle":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Color document filter. This filter is a good starting point for most use cases."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"colorEnhancement","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"colorEnhancement","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorEnhancement"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"colorEnhancement","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter~1colorEnhancement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"colorEnhancement"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter~1colorEnhancement\/fragments","op":"replace"},{"value":"SBSDKColorDocumentFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/title","op":"replace"},{"value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/fragments","op":"replace"},{"value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/navigatorTitle","op":"replace"}]}]}