{"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKColorDocumentFilter(im)initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","navigatorTitle":[{"text":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/initwithcontrastenhancement:colorenhancement:paperwhitening:paperwhiteningbias:"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithContrastEnhancement:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"contrastEnhancement","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"colorEnhancement:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"colorEnhancement","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"paperWhitening:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"paperWhitening","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"paperWhiteningBias:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"paperWhiteningBias","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter/initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter\/initwithcontrastenhancement:colorenhancement:paperwhitening:paperwhiteningbias:","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter\/initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:","kind":"identifier"}],"title":"initWithContrastEnhancement:colorEnhancement:paperWhitening:paperWhiteningBias:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKColorDocumentFilter":{"title":"SBSDKColorDocumentFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKColorDocumentFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcolordocumentfilter","navigatorTitle":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"Color document filter. This filter is a good starting point for most use cases."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/title","value":"SBSDKColorDocumentFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/fragments","value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKColorDocumentFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKColorDocumentFilter"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}