{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapCheckMarkAnimation\/copyWithZone:","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapCheckMarkAnimation(im)copyWithZone:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapCheckMarkAnimation"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapcheckmarkanimation\/copywithzone:"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapCheckMarkAnimation":{"navigatorTitle":[{"text":"SBSDKUI2PageSnapCheckMarkAnimation","kind":"identifier"}],"title":"SBSDKUI2PageSnapCheckMarkAnimation","abstract":[{"type":"text","text":"Configuration of the check mark animation."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapcheckmarkanimation","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapCheckMarkAnimation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PageSnapCheckMarkAnimation","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapCheckMarkAnimation/copyWithZone:":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","title":"copyWithZone:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapcheckmarkanimation\/copywithzone:","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapCheckMarkAnimation\/copyWithZone:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2PageSnapCheckMarkAnimation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapCheckMarkAnimation\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2PageSnapCheckMarkAnimation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapCheckMarkAnimation\/fragments"},{"value":[{"text":"SBSDKUI2PageSnapCheckMarkAnimation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapCheckMarkAnimation\/navigatorTitle"}]}]}