{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithSbColorPrimary:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorPrimary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorPrimaryDisabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorPrimaryDisabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorNegative:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorNegative","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorPositive:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorPositive","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorWarning:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorWarning","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSecondary:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorSecondary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSecondaryDisabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorSecondaryDisabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOnPrimary:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorOnPrimary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOnSecondary:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorOnSecondary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSurface:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorSurface","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOutline:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorOutline","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOnSurfaceVariant:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorOnSurfaceVariant","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorOnSurface:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorOnSurface","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSurfaceLow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorSurfaceLow","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorSurfaceHigh:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorSurfaceHigh","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sbColorModalOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"sbColorModalOverlay","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2palette\/initwithsbcolorprimary:sbcolorprimarydisabled:sbcolornegative:sbcolorpositive:sbcolorwarning:sbcolorsecondary:sbcolorsecondarydisabled:sbcoloronprimary:sbcoloronsecondary:sbcolorsurface:sbcoloroutline:sbcoloronsurfacevariant:sbcoloronsurfac-8ll73"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette\/initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"}],"role":"symbol","title":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Palette(im)initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","roleHeading":"Instance Method"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"title":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Palette":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette","title":"SBSDKUI2Palette","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Palette"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2palette"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Palette/initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2palette\/initwithsbcolorprimary:sbcolorprimarydisabled:sbcolornegative:sbcolorpositive:sbcolorwarning:sbcolorsecondary:sbcolorsecondarydisabled:sbcoloronprimary:sbcoloronsecondary:sbcolorsurface:sbcoloroutline:sbcoloronsurfacevariant:sbcoloronsurfac-8ll73","kind":"symbol","title":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Palette\/initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2Palette","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Palette\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}