{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/mod1110Ncr","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Modulo 1110 NCR."}],"sections":[],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Type Property","title":"mod1110Ncr","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm(cpy)mod1110Ncr","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"mod1110Ncr","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm"}],"navigatorTitle":[{"kind":"identifier","text":"mod1110Ncr"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"mod1110Ncr","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm\/mod1110ncr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm\/mod1110ncr"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMSIPlesseyChecksumAlgorithm":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm","abstract":[{"text":"Checksum algorithm for MSI_PLESSEY.","type":"text"}],"title":"SBSDKMSIPlesseyChecksumAlgorithm","navigatorTitle":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMSIPlesseyChecksumAlgorithm/mod1110Ncr":{"navigatorTitle":[{"kind":"identifier","text":"mod1110Ncr"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/mod1110Ncr","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm\/mod1110ncr","role":"symbol","abstract":[{"type":"text","text":"Modulo 1110 NCR."}],"title":"mod1110Ncr","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod1110Ncr","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mod1110Ncr","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"mod1110Ncr","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"mod1110Ncr"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKMSIPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/fragments","op":"replace","value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1mod1110Ncr\/title","value":"mod1110Ncr"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1mod1110Ncr\/fragments","op":"replace","value":[{"kind":"identifier","text":"mod1110Ncr"}]}]}]}