{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile\/initWithRefInfo:imageInfo:imageSource:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"initWithRefInfo:imageInfo:imageSource:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRefInfo:imageInfo:imageSource:"}],"title":"initWithRefInfo:imageInfo:imageSource:","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefProfile(im)initWithRefInfo:imageInfo:imageSource:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRefInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRefCountedObjectProfile","text":"SBSDKRefCountedObjectProfile","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"refInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"imageInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProfile","text":"SBSDKImageProfile","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"imageSource:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageSource","text":"SBSDKImageSource","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageSource","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/initwithrefinfo:imageinfo:imagesource:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSource":{"navigatorTitle":[{"text":"SBSDKImageSource","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagesource","type":"topic","abstract":[{"text":"Description of source from which the ImageRef was created.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSource","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageSource"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfile/initWithRefInfo:imageInfo:imageSource:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithRefInfo:imageInfo:imageSource:","kind":"identifier"}],"title":"initWithRefInfo:imageInfo:imageSource:","navigatorTitle":[{"text":"initWithRefInfo:imageInfo:imageSource:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofile\/initwithrefinfo:imageinfo:imagesource:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile\/initWithRefInfo:imageInfo:imageSource:","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProfile":{"type":"topic","abstract":[{"type":"text","text":"ImageRef profile part specific to image information."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProfile","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageProfile"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProfile"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprofile","title":"SBSDKImageProfile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfile":{"abstract":[{"type":"text","text":"ImageRef profile which provides detailed information about stored object."}],"navigatorTitle":[{"text":"SBSDKImageRefProfile","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfile","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefProfile","kind":"identifier"}],"title":"SBSDKImageRefProfile","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"title":"SBSDKRefCountedObjectProfile","navigatorTitle":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"abstract":[{"type":"text","text":"Profile info of a reference-counted stored object."}],"url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/title","op":"replace","value":"SBSDKImageSource"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/fragments","op":"replace","value":[{"text":"SBSDKImageSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageSource"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/title","op":"replace","value":"SBSDKImageProfile"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageProfile"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProfile\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageProfile"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/title","op":"replace","value":"SBSDKImageRefProfile"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/fragments","op":"replace","value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfile\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageRefProfile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/title","op":"replace","value":"SBSDKRefCountedObjectProfile"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/fragments","op":"replace","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle","op":"replace","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}]}]}]}