{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","title":"detectionRate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionRate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration(py)detectionRate","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"detectionRate"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"The rate of detections\/recognitions per second in normal performance mode."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 20, meaning that 20 frames per second are detected\/recognized, equally distributed over one second."},{"type":"text","text":" "},{"type":"text","text":"When the video frame rate is 30, 10 frames will be skipped and 20 frames will be detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,"},{"type":"text","text":" "},{"type":"text","text":"the actual detection rate is limited by the video frame rate."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/detectionRate"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/detectionrate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/detectionrate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration/detectionRate":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration\/detectionRate","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration\/detectionrate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"detectionRate","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The rate of detections\/recognitions per second in normal performance mode.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 20, meaning that 20 frames per second are detected\/recognized, equally distributed over one second.","type":"text"},{"text":" ","type":"text"},{"text":"When the video frame rate is 30, 10 frames will be skipped and 20 frames will be detected\/recognized.","type":"text"},{"text":" ","type":"text"},{"text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,","type":"text"},{"text":" ","type":"text"},{"text":"the actual detection rate is limited by the video frame rate.","type":"text"}],"role":"symbol","title":"detectionRate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerEnergyConfiguration":{"abstract":[{"type":"text","text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"type":"text","text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"type":"text","text":" "},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"type":"text","text":" "},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"type":"text","text":"well as in energy saving mode."},{"text":" ","type":"text"},{"text":"In performance mode the scanners will be fed with a higher, configurable rate of","type":"text"},{"text":" ","type":"text"},{"text":"video frames per second.","type":"text"},{"text":" ","type":"text"},{"text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate","type":"text"},{"text":" ","type":"text"},{"text":"of scans will be reduced to a lower (configurable) rate.","type":"text"},{"text":" ","type":"text"},{"text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode.","type":"text"},{"text":" ","type":"text"},{"text":"Inactivity here means that both of the following conditions are met:","type":"text"}],"title":"SBSDKBaseScannerEnergyConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerenergyconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerEnergyConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"detectionRate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"detectionRate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionRate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1detectionRate\/title","value":"detectionRate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration~1detectionRate\/fragments","value":[{"kind":"identifier","text":"detectionRate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/title","value":"SBSDKBaseScannerEnergyConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}