{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsManager\/subscribe(_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticsmanager\/subscribe(_:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticsmanager\/subscribe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"subscribe","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"subscriber"},{"kind":"text","text":": "},{"text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsManager"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"subscribe:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subscribe"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"subscribe(_:)","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsManager(im)subscribe:"},"abstract":[{"type":"text","text":"Subscribes a subscriber to receive analytics events."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsManager":{"kind":"symbol","title":"SBSDKAnalyticsManager","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsManager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAnalyticsManager"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"SBSDKAnalyticsManager"},{"type":"text","text":" is a singleton class that manages analytics events within the Scanbot SDK."}],"url":"\/documentation\/scanbotsdk\/sbsdkanalyticsmanager"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsSubscriber":{"title":"SBSDKAnalyticsSubscriber","kind":"symbol","navigatorTitle":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The subscriber that is being tracked."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber","url":"\/documentation\/scanbotsdk\/sbsdkanalyticssubscriber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsManager/subscribe(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsManager\/subscribe(_:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkanalyticsmanager\/subscribe(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subscribe:"}],"abstract":[{"type":"text","text":"Subscribes a subscriber to receive analytics events."}],"title":"subscribe(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"subscribe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"subscribe:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"subscribe:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"subscribe:"},{"kind":"text","text":"("},{"text":"id<SBSDKAnalyticsSubscriber>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager\/title","value":"SBSDKAnalyticsManager"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager\/fragments","value":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}]},{"value":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/title","value":"SBSDKAnalyticsSubscriber"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}]},{"value":"subscribe:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager~1subscribe(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsManager~1subscribe(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"subscribe:","kind":"identifier"}],"op":"replace"}]}]}