{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration"]]},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAccumulatedResultsVerifierConfiguration(im)initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMaximumNumberOfAccumulatedFrames:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/initwithmaximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration\/initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration":{"role":"symbol","title":"SBSDKAccumulatedResultsVerifierConfiguration","navigatorTitle":[{"text":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration","kind":"symbol","abstract":[{"text":"Configure the frame accumulation process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration/initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:":{"url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/initwithmaximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:","navigatorTitle":[{"text":"initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","kind":"identifier"}],"title":"initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:","kind":"symbol","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration\/initWithMaximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/title","value":"SBSDKAccumulatedResultsVerifierConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/fragments","value":[{"text":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}