{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/compression","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","role":"symbol","title":"compression","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters(py)compression","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"compression","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compression","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode","text":"SBSDKCompressionMode","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/compression"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/compression"]}],"abstract":[{"type":"text","text":"Compression."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"compression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode","text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is LZW","type":"text"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/compression":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"compression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode"}],"abstract":[{"text":"Compression.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"compression"}],"title":"compression","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/compression","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/compression","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"type":"topic","abstract":[{"type":"text","text":"TIFF generator parameters."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"title":"SBSDKTIFFGeneratorParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCompressionMode":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCompressionMode","kind":"identifier"}],"abstract":[{"type":"text","text":"TIFF compression type."}],"type":"topic","navigatorTitle":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"title":"SBSDKCompressionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcompressionmode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"compression","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"compression","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKCompressionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCompressionMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCompressionMode"},{"kind":"text","text":" * "},{"kind":"identifier","text":"compression"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"compression","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1compression\/title"},{"op":"replace","value":[{"kind":"identifier","text":"compression"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters~1compression\/fragments"},{"op":"replace","value":"SBSDKTIFFGeneratorParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title"},{"op":"replace","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments"},{"op":"replace","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle"},{"op":"replace","value":"SBSDKCompressionMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/title"},{"op":"replace","value":[{"text":"SBSDKCompressionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCompressionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCompressionMode"}],"op":"replace"}]}]}