{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetector(py)currentHeightScore","role":"symbol","title":"currentHeightScore","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentHeightScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"currentHeightScore","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentHeightScore"},"abstract":[{"text":"The height score of the latest detected polygon (0 - 100). Part of the size score.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentHeightScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currentheightscore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currentheightscore"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector","navigatorTitle":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"role":"symbol","title":"SBSDKDocumentDetector"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetector/currentHeightScore":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetector\/currentheightscore","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetector\/currentHeightScore","title":"currentHeightScore","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentHeightScore","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The height score of the latest detected polygon (0 - 100). Part of the size score."}],"role":"symbol","navigatorTitle":[{"text":"currentHeightScore","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"currentHeightScore","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"currentHeightScore","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentHeightScore"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/title","value":"SBSDKDocumentDetector","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector\/navigatorTitle","value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentHeightScore\/title","value":"currentHeightScore","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetector~1currentHeightScore\/fragments","value":[{"text":"currentHeightScore","kind":"identifier"}],"op":"replace"}]}]}