{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerFrame"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerframe\/toimageref(rotation:roi:origin:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerframe\/toimageref(rotation:roi:origin:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerFrame\/toImageRef(rotation:roi:origin:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"toImageRefWithRotation:roi:origin:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toImageRef","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRotation","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRotation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"roi","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageOrigin"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRef"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerFrame(im)toImageRefWithRotation:roi:origin:","roleHeading":"Instance Method","title":"toImageRef(rotation:roi:origin:)"},"sections":[],"abstract":[{"text":"Converts the wrapped image to an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef"},{"text":" with the specified parameters.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toImageRef","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRotation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"},{"text":" = .none, ","kind":"text"},{"text":"roi","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":" = .zero, "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageOrigin","text":"SBSDKImageOrigin"},{"kind":"text","text":" = .topLeft) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The rotation to be applied to the image. Defaults to ","type":"text"},{"type":"codeVoice","code":".none"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"rotation"},{"content":[{"inlineContent":[{"text":"The region of interest to be applied to the image. Defaults to ","type":"text"},{"type":"codeVoice","code":".zero"},{"text":", which means the whole image.","type":"text"}],"type":"paragraph"}],"name":"roi"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The origin of the image. Defaults to ","type":"text"},{"code":".topLeft","type":"codeVoice"},{"text":". Use this flag to flip the image vertically, horizontally or in both directions.","type":"text"}]}],"name":"origin"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"An "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef","isActive":true},{"type":"text","text":" representation of the wrapped image."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRef":{"type":"topic","title":"SBSDKImageRef","abstract":[{"type":"text","text":"Image ref class."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRef"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageref","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageOrigin":{"title":"SBSDKImageOrigin","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageorigin","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageOrigin","abstract":[{"type":"text","text":"Location of the image origin in the image coordinate system."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageOrigin"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageOrigin"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerFrame":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerFrame","title":"SBSDKBaseScannerFrame","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerframe","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"abstract":[{"type":"text","text":"A wrapper for a video frame. Can be used with "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" and "},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRotation":{"kind":"symbol","abstract":[{"text":"Image rotation.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRotation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageRotation","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerotation","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation","title":"SBSDKImageRotation"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerFrame/toImageRef(rotation:roi:origin:)":{"abstract":[{"text":"Converts the wrapped image to an ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef","isActive":true},{"text":" with the specified parameters.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerFrame\/toImageRef(rotation:roi:origin:)","type":"topic","title":"toImageRef(rotation:roi:origin:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toImageRef","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rotation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRotation","text":"SBSDKImageRotation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"roi","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"origin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageOrigin","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageOrigin"},{"text":") -> ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRef"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerframe\/toimageref(rotation:roi:origin:)","navigatorTitle":[{"text":"toImageRefWithRotation:roi:origin:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"toImageRefWithRotation:roi:origin:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toImageRefWithRotation:roi:origin:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"toImageRefWithRotation:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRotation","text":"SBSDKImageRotation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rotation"},{"kind":"text","text":" "},{"kind":"identifier","text":"roi:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"roi"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageOrigin","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageOrigin","text":"SBSDKImageOrigin"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"origin"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The rotation to be applied to the image. Defaults to "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"rotation"},{"content":[{"inlineContent":[{"type":"text","text":"The region of interest to be applied to the image. Defaults to "},{"type":"codeVoice","code":".zero"},{"type":"text","text":", which means the whole image."}],"type":"paragraph"}],"name":"roi"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The origin of the image. Defaults to "},{"type":"codeVoice","code":".topLeft"},{"type":"text","text":". Use this flag to flip the image vertically, horizontally or in both directions."}]}],"name":"origin"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRef","type":"reference","isActive":true},{"type":"text","text":" representation of the wrapped image."}]}]}},{"op":"replace","value":"SBSDKImageRef","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRef\/title"},{"op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRef\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRef\/navigatorTitle"},{"op":"replace","value":"SBSDKImageOrigin","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageOrigin\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageOrigin"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageOrigin\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageOrigin"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageOrigin\/navigatorTitle"},{"op":"replace","value":"SBSDKBaseScannerFrame","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerFrame\/title"},{"op":"replace","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerFrame\/fragments"},{"op":"replace","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerFrame\/navigatorTitle"},{"op":"replace","value":"SBSDKImageRotation","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageRotation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/navigatorTitle"},{"op":"replace","value":"toImageRefWithRotation:roi:origin:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerFrame~1toImageRef(rotation:roi:origin:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toImageRefWithRotation:roi:origin:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerFrame~1toImageRef(rotation:roi:origin:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}