{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheetContent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/sheetcontent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/sheetcontent"]}],"abstract":[{"type":"text","text":"Configuration of the list containing the barcodes that have already been scanned."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheetContent"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode(py)sheetContent","role":"symbol","title":"sheetContent","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetContent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","kind":"typeIdentifier","text":"SBSDKUI2SheetContent"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"sheetContent","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/sheetContent":{"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheetContent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent"}],"navigatorTitle":[{"text":"sheetContent","kind":"identifier"}],"title":"sheetContent","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/sheetcontent","role":"symbol","abstract":[{"type":"text","text":"Configuration of the list containing the barcodes that have already been scanned."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/sheetContent"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","title":"SBSDKUI2SheetContent","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"type":"topic","abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode":{"abstract":[{"text":"Configuration of the mode for scanning multiple barcodes.","type":"text"}],"title":"SBSDKUI2MultipleScanningMode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sheetContent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sheetContent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent","kind":"typeIdentifier","text":"SBSDKUI2SheetContent","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sheetContent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1sheetContent\/title","value":"sheetContent"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode~1sheetContent\/fragments","value":[{"text":"sheetContent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/title","value":"SBSDKUI2SheetContent"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/fragments","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/title","value":"SBSDKUI2MultipleScanningMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/fragments","value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}