{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormTypeForm1B"}],"title":"SBSDKMedicalCertificateFormType.form1B","roleHeading":"Case","role":"symbol","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"form1B"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateFormType@SBSDKMedicalCertificateFormTypeForm1B"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1b"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1b"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Form 1B."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"form1B","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType\/form1B"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateFormType":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype","kind":"symbol","title":"SBSDKMedicalCertificateFormType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormType"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateFormType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of the medical certificate form."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateFormType/form1B":{"kind":"symbol","abstract":[{"text":"Form 1B.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateFormTypeForm1B","kind":"identifier"}],"title":"SBSDKMedicalCertificateFormType.form1B","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType\/form1B","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"form1B","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1b"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKMedicalCertificateFormTypeForm1B","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateFormTypeForm1B","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormTypeForm1B"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/title","value":"SBSDKMedicalCertificateFormType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType~1form1B\/title","value":"SBSDKMedicalCertificateFormTypeForm1B","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType~1form1B\/fragments","value":[{"text":"SBSDKMedicalCertificateFormTypeForm1B","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}