{"schemaVersion":{"minor":3,"patch":0,"major":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/polygonBackgroundColor"},"metadata":{"title":"polygonBackgroundColor","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerUIConfiguration(py)polygonBackgroundColor","platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"polygonBackgroundColor","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Background color of the detected documents polygon, when the polygons quality is not acceptable."}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneruiconfiguration\/polygonbackgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneruiconfiguration\/polygonbackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Defaults to clear color."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerUIConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerUIConfiguration","role":"symbol","title":"SBSDKUIFinderDocumentScannerUIConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerUIConfiguration"}],"abstract":[{"text":"Configuration for the user interface of the document scanning screen.","type":"text"}],"deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneruiconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerUIConfiguration/polygonBackgroundColor":{"role":"symbol","abstract":[{"type":"text","text":"Background color of the detected documents polygon, when the polygons quality is not acceptable."}],"deprecated":true,"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerUIConfiguration\/polygonBackgroundColor","navigatorTitle":[{"text":"polygonBackgroundColor","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscanneruiconfiguration\/polygonbackgroundcolor","title":"polygonBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygonBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"polygonBackgroundColor","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"polygonBackgroundColor"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"polygonBackgroundColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/title","value":"SBSDKUIFinderDocumentScannerUIConfiguration"},{"value":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerUIConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration~1polygonBackgroundColor\/title","value":"polygonBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerUIConfiguration~1polygonBackgroundColor\/fragments","value":[{"text":"polygonBackgroundColor","kind":"identifier"}]}]}]}