{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate\/finderScanningViewController(_:didFinishWith:)"},"sections":[],"kind":"symbol","abstract":[{"text":"Informs the delegate that the document scanning view controller has scanned document pages and the view controller has dismissed.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate"]]},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"metadata":{"title":"finderScanningViewController(_:didFinishWith:)","modules":[{"name":"ScanbotSDK"}],"platforms":[],"required":true,"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIFinderDocumentScannerViewControllerDelegate(im)finderScanningViewController:didFinishWith:","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderScanningViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"finderScanningViewController:didFinishWith:","kind":"identifier"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderScanningViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","isActive":true},{"type":"text","text":" which generated the scanned pages and dismissed."}]}]},{"name":"document","content":[{"type":"paragraph","inlineContent":[{"text":"The document containing the scanned pages.","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontrollerdelegate\/finderscanningviewcontroller(_:didfinishwith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontrollerdelegate\/finderscanningviewcontroller(_:didfinishwith:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewControllerDelegate":{"title":"SBSDKUIFinderDocumentScannerViewControllerDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewControllerDelegate"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"symbol","abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController"},{"text":".","type":"text"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController":{"abstract":[{"text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"title":"SBSDKUIFinderDocumentScannerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewControllerDelegate/finderScanningViewController(_:didFinishWith:)":{"title":"finderScanningViewController(_:didFinishWith:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderScanningViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"finderScanningViewController:didFinishWith:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewControllerDelegate\/finderScanningViewController(_:didFinishWith:)","abstract":[{"type":"text","text":"Informs the delegate that the document scanning view controller has scanned document pages and the view controller has dismissed."}],"kind":"symbol","required":true,"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontrollerdelegate\/finderscanningviewcontroller(_:didfinishwith:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","title":"SBSDKDocumentPage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"navigatorTitle":[{"text":"SBSDKDocument","kind":"identifier"}],"type":"topic","abstract":[{"text":"A thread-safe, mutable container for scanned pages of type ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","url":"\/documentation\/scanbotsdk\/sbsdkdocument","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocument","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"finderScanningViewController:didFinishWith:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"finderScanningViewController:didFinishWith:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"finderScanningViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","text":"SBSDKUIFinderDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFinishWith:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"viewController","content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","type":"reference","isActive":true},{"type":"text","text":" which generated the scanned pages and dismissed."}],"type":"paragraph"}]},{"name":"document","content":[{"inlineContent":[{"type":"text","text":"The document containing the scanned pages."}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKUIFinderDocumentScannerViewControllerDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIFinderDocumentScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/title","op":"replace","value":"SBSDKUIFinderDocumentScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIFinderDocumentScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate~1finderScanningViewController(_:didFinishWith:)\/title","op":"replace","value":"finderScanningViewController:didFinishWith:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewControllerDelegate~1finderScanningViewController(_:didFinishWith:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finderScanningViewController:didFinishWith:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","op":"replace","value":"SBSDKDocumentPage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title","op":"replace","value":"SBSDKDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}