{"abstract":[{"text":"Notifies that properties have changed by incrementing the update counter.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/notifypropertieschange()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/notifypropertieschange()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/notifyPropertiesChange()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyPropertiesChange"},{"kind":"text","text":"()"}]}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"notifyPropertiesChange","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(im)notifyPropertiesChange","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"notifyPropertiesChange()","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration/notifyPropertiesChange()":{"navigatorTitle":[{"kind":"identifier","text":"notifyPropertiesChange"}],"kind":"symbol","type":"topic","title":"notifyPropertiesChange()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyPropertiesChange"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/notifypropertieschange()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/notifyPropertiesChange()","abstract":[{"type":"text","text":"Notifies that properties have changed by incrementing the update counter."}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","title":"SBSDKBaseScannerViewFinderConfiguration","abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"type":"text","text":" "},{"type":"text","text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in."},{"type":"text","text":" "},{"type":"text","text":"It crops the video frame to that region of interest before passing it to any scanner. Usually"},{"type":"text","text":" "},{"type":"text","text":"the performance of scanners gain a benefit from it because less pixels must be processed."},{"type":"text","text":" "},{"type":"text","text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around"},{"type":"text","text":" "},{"type":"text","text":"on the user interface."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"notifyPropertiesChange"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"notifyPropertiesChange"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1notifyPropertiesChange()\/title","op":"replace","value":"notifyPropertiesChange"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1notifyPropertiesChange()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyPropertiesChange"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/title","op":"replace","value":"SBSDKBaseScannerViewFinderConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}]}]}]}