{"sections":[],"abstract":[{"text":"List of accepted barcode document formats.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/accepteddocumentformats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/accepteddocumentformats"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"acceptedDocumentFormats","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptedDocumentFormats","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat"},{"text":"]","kind":"text"}],"symbolKind":"property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(py)acceptedDocumentFormats","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"acceptedDocumentFormats"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/acceptedDocumentFormats","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedDocumentFormats"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeDocumentFormat","text":"SBSDKUI2BarcodeDocumentFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration/acceptedDocumentFormats":{"navigatorTitle":[{"kind":"identifier","text":"acceptedDocumentFormats"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/acceptedDocumentFormats","kind":"symbol","abstract":[{"type":"text","text":"List of accepted barcode document formats."}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/accepteddocumentformats","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedDocumentFormats"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat","text":"SBSDKUI2BarcodeDocumentFormat","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"title":"acceptedDocumentFormats","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"title":"SBSDKUI2BarcodeRecognizerConfiguration","abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration","navigatorTitle":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeDocumentFormat":{"title":"SBSDKUI2BarcodeDocumentFormat","navigatorTitle":[{"text":"SBSDKUI2BarcodeDocumentFormat","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeDocumentFormat","abstract":[{"type":"text","text":"Type of barcode document format used."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodedocumentformat","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeDocumentFormat"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"acceptedDocumentFormats"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"acceptedDocumentFormats","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKUI2BarcodeDocumentFormat *>"},{"text":" * ","kind":"text"},{"text":"acceptedDocumentFormats","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1acceptedDocumentFormats\/title","value":"acceptedDocumentFormats"},{"op":"replace","value":[{"text":"acceptedDocumentFormats","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1acceptedDocumentFormats\/fragments"},{"value":"SBSDKUI2BarcodeRecognizerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title"},{"value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKUI2BarcodeDocumentFormat","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeDocumentFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeDocumentFormat\/fragments","op":"replace","value":[{"text":"SBSDKUI2BarcodeDocumentFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeDocumentFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeDocumentFormat"}]}]}]}