{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiplesseychecksumalgorithm:austra-872c0"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiplesseychecksumalgorithm:austra-872c0"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"acceptedDocumentFormats"},{"kind":"text","text":": ["},{"text":"SBSDKUI2BarcodeDocumentFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat"},{"text":"] = [], ","kind":"text"},{"text":"barcodesExtensionFilter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter","kind":"typeIdentifier"},{"text":" = SBSDKUI2BarcodesExtensionFilter.noFilter, ","kind":"text"},{"text":"barcodesRegexFilter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"\", "},{"text":"minimumTextLength","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" = 0, ","kind":"text"},{"text":"maximumTextLength","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 0, ","kind":"text"},{"kind":"externalParam","text":"minimum1DBarcodesQuietZone"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 10, "},{"text":"stripCheckDigits","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"useIATA2OF5Checksum"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"useCode11Checksum"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"barcodeFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat"},{"text":"] = [], ","kind":"text"},{"text":"msiPlesseyChecksumAlgorithm","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"text":" = SBSDKUI2MSIPlesseyChecksumAlgorithm\n                    .mod10, ","kind":"text"},{"kind":"externalParam","text":"australiaPostCustomerFormat"},{"kind":"text","text":": "},{"text":"SBSDKUI2AustraliaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AustraliaPostCustomerFormat"},{"text":" = SBSDKUI2AustraliaPostCustomerFormat\n                    .alphaNumeric, ","kind":"text"},{"text":"gs1Handling","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2Gs1Handling","text":"SBSDKUI2Gs1Handling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling","kind":"typeIdentifier"},{"text":" = SBSDKUI2Gs1Handling.parse)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","roleHeading":"Initializer","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(im)initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"acceptedDocumentFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat","kind":"typeIdentifier","text":"SBSDKUI2BarcodeDocumentFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"barcodesExtensionFilter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodesRegexFilter"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minimumTextLength","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"maximumTextLength","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minimum1DBarcodesQuietZone"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stripCheckDigits"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"useIATA2OF5Checksum","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useCode11Checksum"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeFormats","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"msiPlesseyChecksumAlgorithm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"text":", ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AustraliaPostCustomerFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"gs1Handling"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2Gs1Handling","text":"SBSDKUI2Gs1Handling","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AustraliaPostCustomerFormat":{"title":"SBSDKUI2AustraliaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}],"abstract":[{"text":"The customer format used in AUSTRALIA_POST codes. Only relevant for format codes 59 and 62.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2australiapostcustomerformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"abstract":[{"text":"Configuration of the scanning behavior.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration","title":"SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"acceptedDocumentFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat","text":"SBSDKUI2BarcodeDocumentFormat"},{"kind":"text","text":"], "},{"text":"barcodesExtensionFilter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter"},{"kind":"text","text":", "},{"text":"barcodesRegexFilter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"minimumTextLength","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maximumTextLength"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"minimum1DBarcodesQuietZone","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stripCheckDigits"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useIATA2OF5Checksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"useCode11Checksum","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeFormats"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"msiPlesseyChecksumAlgorithm"},{"text":": ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"australiaPostCustomerFormat"},{"text":": ","kind":"text"},{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AustraliaPostCustomerFormat"},{"kind":"text","text":", "},{"text":"gs1Handling","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2Gs1Handling","text":"SBSDKUI2Gs1Handling","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","kind":"symbol","role":"symbol","title":"init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","type":"topic","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiplesseychecksumalgorithm:austra-872c0","navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodesExtensionFilter":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodesextensionfilter","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"kind":"symbol","title":"SBSDKUI2BarcodesExtensionFilter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeFormat":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeformat","role":"symbol","title":"SBSDKUI2BarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeFormat","abstract":[{"type":"text","text":"Barcode symbology used."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Gs1Handling":{"role":"symbol","abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling","title":"SBSDKUI2Gs1Handling","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeDocumentFormat":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodedocumentformat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeDocumentFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Type of barcode document format used."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeDocumentFormat"}],"title":"SBSDKUI2BarcodeDocumentFormat","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2msiplesseychecksumalgorithm","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"abstract":[{"text":"Type of MSI plessey checksum algorithm used.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAcceptedDocumentFormats:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKUI2BarcodeDocumentFormat *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"acceptedDocumentFormats","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodesExtensionFilter:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter"},{"text":") ","kind":"text"},{"text":"barcodesExtensionFilter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodesRegexFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodesRegexFilter"},{"kind":"text","text":" "},{"text":"minimumTextLength:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"minimumTextLength","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maximumTextLength:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"maximumTextLength"},{"text":" ","kind":"text"},{"text":"minimum1DBarcodesQuietZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"minimum1DBarcodesQuietZone","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stripCheckDigits:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stripCheckDigits","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useIATA2OF5Checksum:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"useIATA2OF5Checksum","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useCode11Checksum:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"useCode11Checksum","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeFormats:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKUI2BarcodeFormat *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodeFormats"},{"kind":"text","text":" "},{"text":"msiPlesseyChecksumAlgorithm:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"msiPlesseyChecksumAlgorithm"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","text":"SBSDKUI2AustraliaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AustraliaPostCustomerFormat"},{"kind":"text","text":") "},{"text":"australiaPostCustomerFormat","kind":"internalParam"},{"kind":"text","text":" "},{"text":"gs1Handling:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2Gs1Handling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2Gs1Handling","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"gs1Handling","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2AustraliaPostCustomerFormat","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AustraliaPostCustomerFormat\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)\/title","value":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter\/title","value":"SBSDKUI2BarcodesExtensionFilter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter\/fragments","value":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2BarcodeFormat","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeFormat\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeFormat\/fragments"},{"op":"replace","value":"SBSDKUI2Gs1Handling","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeDocumentFormat\/title","value":"SBSDKUI2BarcodeDocumentFormat"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeDocumentFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeDocumentFormat\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithm","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}