{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Optional minimum required quiet zone on the barcode. Measured in modules (the smallest bar size on a barcode)."},{"type":"text","text":" "},{"text":"The default is 10. NOTE - This feature works on ITF barcodes only.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is 10"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DBarcodesQuietZone"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimum1DBarcodesQuietZone"},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimum1DBarcodesQuietZone","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}],"title":"minimum1DBarcodesQuietZone","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(py)minimum1DBarcodesQuietZone","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/minimum1dbarcodesquietzone"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/minimum1dbarcodesquietzone"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration/minimum1DBarcodesQuietZone":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimum1DBarcodesQuietZone","abstract":[{"type":"text","text":"Optional minimum required quiet zone on the barcode. Measured in modules (the smallest bar size on a barcode)."},{"type":"text","text":" "},{"text":"The default is 10. NOTE - This feature works on ITF barcodes only.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is 10"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimum1DBarcodesQuietZone","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","title":"minimum1DBarcodesQuietZone","navigatorTitle":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration\/minimum1dbarcodesquietzone","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"abstract":[{"text":"Configuration of the scanning behavior.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcoderecognizerconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"title":"SBSDKUI2BarcodeRecognizerConfiguration","navigatorTitle":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"minimum1DBarcodesQuietZone","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimum1DBarcodesQuietZone"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1minimum1DBarcodesQuietZone\/title","value":"minimum1DBarcodesQuietZone","op":"replace"},{"value":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1minimum1DBarcodesQuietZone\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments","value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}