{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype\/outofmemory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype\/outofmemory"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The system ran out of memory during the operation.","type":"text"}],"metadata":{"title":"SBSDKErrorType.outOfMemory","role":"symbol","navigatorTitle":[{"text":"SBSDKErrorTypeOutOfMemory","kind":"identifier"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outOfMemory"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKErrorType@SBSDKErrorTypeOutOfMemory","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outOfMemory"}]}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/outOfMemory"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/outOfMemory":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/outofmemory","role":"symbol","kind":"symbol","title":"SBSDKErrorType.outOfMemory","abstract":[{"type":"text","text":"The system ran out of memory during the operation."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outOfMemory","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorTypeOutOfMemory","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/outOfMemory"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType","abstract":[{"type":"text","text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK."},{"type":"text","text":" "},{"type":"text","text":"Each case corresponds to a specific error code."}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"type":"topic","title":"SBSDKErrorType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKErrorTypeOutOfMemory","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKErrorTypeOutOfMemory","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKErrorTypeOutOfMemory"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1outOfMemory\/title","value":"SBSDKErrorTypeOutOfMemory","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1outOfMemory\/fragments","value":[{"kind":"identifier","text":"SBSDKErrorTypeOutOfMemory"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/title","value":"SBSDKErrorType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/fragments","value":[{"text":"SBSDKErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKErrorType"}],"op":"replace"}]}]}