{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"polygon"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","text":"SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"parametricFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"},{"text":"]?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"pageFileID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the images in the default page file storage."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon of the area where the document is located within the pages image."}]}],"name":"polygon"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of parametric filters to be applied to the page or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"parametricFilters"}],"kind":"parameters"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithPageFileID:polygon:parametricFilters:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageFileID","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"parametricFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"text":"]?)","kind":"text"}],"title":"init(pageFileID:polygon:parametricFilters:)","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPage(im)initWithPageFileID:polygon:parametricFilters:","role":"symbol","roleHeading":"Initializer"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/init(pagefileid:polygon:parametricfilters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/init(pagefileid:polygon:parametricfilters:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"abstract":[{"text":"Designated initializer. Creates a new page object.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","abstract":[{"type":"text","text":"Base class for all parametric filters."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"title":"SBSDKParametricFilter","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage/init(pageFileID:polygon:parametricFilters:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/init(pagefileid:polygon:parametricfilters:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"pageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"kind":"text","text":", "},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"parametricFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"]?)"}],"abstract":[{"text":"Designated initializer. Creates a new page object.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:)","type":"topic","title":"init(pageFileID:polygon:parametricFilters:)","navigatorTitle":[{"text":"initWithPageFileID:polygon:parametricFilters:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage","title":"SBSDKDocumentPage","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPage","kind":"identifier"}],"abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPolygon":{"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygon"}],"navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpolygon","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","role":"symbol","title":"SBSDKPolygon"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithPageFileID:polygon:parametricFilters:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithPageFileID:polygon:parametricFilters:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithPageFileID:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSUUID","preciseIdentifier":"c:objc(cs)NSUUID"},{"text":" *) ","kind":"text"},{"text":"pageFileID","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"polygon:"},{"text":"(","kind":"text"},{"text":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"polygon","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"parametricFilters:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKParametricFilter *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"parametricFilters","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"pageFileID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the images in the default page file storage."}]}]},{"name":"polygon","content":[{"inlineContent":[{"type":"text","text":"The polygon of the area where the document is located within the pages image."}],"type":"paragraph"}]},{"name":"parametricFilters","content":[{"inlineContent":[{"text":"The array of parametric filters to be applied to the page or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","value":"SBSDKParametricFilter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title"},{"op":"replace","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:parametricFilters:)\/title","value":"initWithPageFileID:polygon:parametricFilters:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPageFileID:polygon:parametricFilters:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:parametricFilters:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/title","op":"replace","value":"SBSDKDocumentPage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"value":"SBSDKPolygon","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/title"},{"value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPolygon\/navigatorTitle","value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace"}]}]}