{"kind":"symbol","abstract":[{"type":"text","text":"An "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" of the original image including any applied rotations."}],"sections":[],"metadata":{"navigatorTitle":[{"text":"originalImage","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentPage(py)originalImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"originalImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"role":"symbol","title":"originalImage","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"originalImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/originalimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/originalimage"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage\/originalImage","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage/originalImage":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage\/originalimage","abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" of the original image including any applied rotations."}],"navigatorTitle":[{"text":"originalImage","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalImage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","title":"originalImage","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage\/originalImage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage","title":"SBSDKDocumentPage","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPage","kind":"identifier"}],"abstract":[{"text":"This class represents a scanned documents page.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"originalImage","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"originalImage","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":" * "},{"text":"originalImage","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"originalImage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage~1originalImage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage~1originalImage\/fragments","value":[{"kind":"identifier","text":"originalImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/fragments","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}