{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerUIResult\/init(rawText:wordBoxes:symbolBoxes:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscanneruiresult\/init(rawtext:wordboxes:symbolboxes:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscanneruiresult\/init(rawtext:wordboxes:symbolboxes:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithRawText:wordBoxes:symbolBoxes:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wordBoxes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKWordBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"symbolBoxes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKSymbolBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox"},{"kind":"text","text":"])"}],"roleHeading":"Initializer","title":"init(rawText:wordBoxes:symbolBoxes:)","symbolKind":"init","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerUIResult(im)initWithRawText:wordBoxes:symbolBoxes:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerUIResult"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wordBoxes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox","kind":"typeIdentifier","text":"SBSDKWordBox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"symbolBoxes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox","kind":"typeIdentifier","text":"SBSDKSymbolBox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox"},{"kind":"text","text":"])"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKWordBox":{"abstract":[{"type":"text","text":"Structure containing recognized word text and bounds."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKWordBox","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkwordbox","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKWordBox","role":"symbol","title":"SBSDKWordBox","navigatorTitle":[{"text":"SBSDKWordBox","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerUIResult/init(rawText:wordBoxes:symbolBoxes:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"wordBoxes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKWordBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKWordBox","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"symbolBoxes","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKSymbolBox","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKSymbolBox"},{"kind":"text","text":"])"}],"abstract":[],"title":"init(rawText:wordBoxes:symbolBoxes:)","navigatorTitle":[{"kind":"identifier","text":"initWithRawText:wordBoxes:symbolBoxes:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscanneruiresult\/init(rawtext:wordboxes:symbolboxes:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerUIResult\/init(rawText:wordBoxes:symbolBoxes:)","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerUIResult":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of the generic text scanner RTU UI result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerUIResult","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscanneruiresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerUIResult"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerUIResult"}],"title":"SBSDKUI2TextPatternScannerUIResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSymbolBox":{"navigatorTitle":[{"text":"SBSDKSymbolBox","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Structure containing recognized symbol text and bounds.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSymbolBox","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSymbolBox","title":"SBSDKSymbolBox","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdksymbolbox"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithRawText:wordBoxes:symbolBoxes:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRawText:wordBoxes:symbolBoxes:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRawText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rawText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"wordBoxes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKWordBox *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"wordBoxes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"symbolBoxes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKSymbolBox *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"symbolBoxes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/title","op":"replace","value":"SBSDKWordBox"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/fragments","op":"replace","value":[{"text":"SBSDKWordBox","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKWordBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKWordBox\/navigatorTitle"},{"op":"replace","value":"initWithRawText:wordBoxes:symbolBoxes:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerUIResult~1init(rawText:wordBoxes:symbolBoxes:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithRawText:wordBoxes:symbolBoxes:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerUIResult~1init(rawText:wordBoxes:symbolBoxes:)\/fragments"},{"op":"replace","value":"SBSDKUI2TextPatternScannerUIResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerUIResult\/title"},{"op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerUIResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2TextPatternScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerUIResult\/navigatorTitle"},{"op":"replace","value":"SBSDKSymbolBox","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKSymbolBox"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/fragments"},{"op":"replace","value":[{"text":"SBSDKSymbolBox","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSymbolBox\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}