{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/initWithName:fullName:normalizedName:listIndex:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fullName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fullName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"normalizedName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"normalizedName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"listIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"listIndex","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/initwithname:fullname:normalizedname:listindex:"]}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithName:fullName:normalizedName:listIndex:"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"initWithName:fullName:normalizedName:listIndex:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:fullName:normalizedName:listIndex:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType(im)initWithName:fullName:normalizedName:listIndex:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType/initWithName:fullName:normalizedName:listIndex:":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:fullName:normalizedName:listIndex:"}],"title":"initWithName:fullName:normalizedName:listIndex:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/initwithname:fullname:normalizedname:listindex:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:fullName:normalizedName:listIndex:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/initWithName:fullName:normalizedName:listIndex:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelRootType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelRootType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype","title":"SBSDKDocumentsModelRootType","abstract":[{"type":"text","text":"Root document type."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/title","op":"replace","value":"SBSDKDocumentsModelRootType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/fragments","value":[{"text":"SBSDKDocumentsModelRootType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelRootType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}