{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewController:configureScanningStatusLabel:forScanningResult:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontroller:configurescanningstatuslabel:forscanningresult:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"documentScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"configureScanningStatusLabel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDetectionStatusLabel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDetectionStatusLabel","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"label","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forScanningResult:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentDetectionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"metadata":{"navigatorTitle":[{"text":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerViewController(im)documentScannerViewController:configureScanningStatusLabel:forScanningResult:","role":"symbol","title":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan a single documents of a certain aspect ratio."}],"kind":"symbol","type":"topic","deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController","title":"SBSDKUIFinderDocumentScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerViewController/documentScannerViewController:configureScanningStatusLabel:forScanningResult:":{"fragments":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerViewController\/documentScannerViewController:configureScanningStatusLabel:forScanningResult:","title":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:","role":"symbol","navigatorTitle":[{"text":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscannerviewcontroller\/documentscannerviewcontroller:configurescanningstatuslabel:forscanningresult:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","abstract":[{"text":"Result of the document contour detection.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","role":"symbol","title":"SBSDKDocumentDetectionResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","title":"SBSDKDocumentScannerViewController","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document scanner."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDetectionStatusLabel":{"url":"\/documentation\/scanbotsdk\/sbsdkdetectionstatuslabel","abstract":[{"type":"text","text":"A "},{"code":"UILabel","type":"codeVoice"},{"type":"text","text":" subclass with rounded corners and content insets to display the status of the current document scanning result."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDetectionStatusLabel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"title":"SBSDKDetectionStatusLabel"}},"variantOverrides":[{"patch":[{"value":"SBSDKUIFinderDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerViewController\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","op":"replace"},{"value":"SBSDKDetectionStatusLabel","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDetectionStatusLabel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}