{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot\/initwithimagerefprofiles:totalmemoryconsumption:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImageRefProfiles:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKImageRefProfile *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageRefProfiles"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalMemoryConsumption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"totalMemoryConsumption"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot(im)initWithImageRefProfiles:totalMemoryConsumption:","navigatorTitle":[{"kind":"identifier","text":"initWithImageRefProfiles:totalMemoryConsumption:"}],"role":"symbol","title":"initWithImageRefProfiles:totalMemoryConsumption:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithImageRefProfiles:totalMemoryConsumption:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot\/initWithImageRefProfiles:totalMemoryConsumption:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot"]]},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefPoolSnapshot/initWithImageRefProfiles:totalMemoryConsumption:":{"kind":"symbol","navigatorTitle":[{"text":"initWithImageRefProfiles:totalMemoryConsumption:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot\/initwithimagerefprofiles:totalmemoryconsumption:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImageRefProfiles:totalMemoryConsumption:","kind":"identifier"}],"type":"topic","title":"initWithImageRefProfiles:totalMemoryConsumption:","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot\/initWithImageRefProfiles:totalMemoryConsumption:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefPoolSnapshot":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","title":"SBSDKImageRefPoolSnapshot","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot","abstract":[{"text":"Snapshot of all alive ImageRefs.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKImageRefPoolSnapshot","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/title"},{"value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/fragments"},{"value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}