{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot"]]},"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageRefProfiles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"SBSDKImageRefProfile","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefProfile","kind":"typeIdentifier"},{"text":">)","kind":"text"}],"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithImageRefProfiles:","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot(im)initWithImageRefProfiles:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"init(imageRefProfiles:)"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot\/init(imageRefProfiles:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageRefProfiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefProfile","text":"SBSDKImageRefProfile","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfile"},{"kind":"text","text":">)"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot\/init(imagerefprofiles:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot\/init(imagerefprofiles:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefPoolSnapshot":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot","title":"SBSDKImageRefPoolSnapshot","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot","abstract":[{"text":"Snapshot of all alive ImageRefs.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefProfile":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefProfile","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefprofile","title":"SBSDKImageRefProfile","type":"topic","role":"symbol","abstract":[{"type":"text","text":"ImageRef profile which provides detailed information about stored object."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKImageRefProfile","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefProfile"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRefPoolSnapshot/init(imageRefProfiles:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImageRefProfiles:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRefPoolSnapshot\/init(imageRefProfiles:)","kind":"symbol","title":"init(imageRefProfiles:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerefpoolsnapshot\/init(imagerefprofiles:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageRefProfiles"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageRefProfile","kind":"typeIdentifier","text":"SBSDKImageRefProfile"},{"kind":"text","text":">)"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithImageRefProfiles:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithImageRefProfiles:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImageRefProfiles:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKImageRefProfile *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageRefProfiles","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKImageRefPoolSnapshot","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/title"},{"value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle"},{"value":"SBSDKImageRefProfile","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfile\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfile\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageRefProfile"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefProfile\/navigatorTitle"},{"value":"initWithImageRefProfiles:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot~1init(imageRefProfiles:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithImageRefProfiles:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRefPoolSnapshot~1init(imageRefProfiles:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}