{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedDocumentTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType","text":"SBSDKGenericDocumentRootType"},{"text":"]","kind":"text"}],"role":"symbol","symbolKind":"property","title":"acceptedDocumentTypes","navigatorTitle":[{"kind":"identifier","text":"acceptedDocumentTypes"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizer(py)acceptedDocumentTypes"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/acceptedDocumentTypes"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/accepteddocumenttypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/accepteddocumenttypes"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedDocumentTypes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType","text":"SBSDKGenericDocumentRootType"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Please specify at least one document type you want to scan for.","type":"text"}]}],"kind":"content"}],"abstract":[{"text":"An array of recognizable document types.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer/acceptedDocumentTypes":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptedDocumentTypes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType","kind":"typeIdentifier","text":"SBSDKGenericDocumentRootType"},{"kind":"text","text":"]"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/accepteddocumenttypes","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"acceptedDocumentTypes","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/acceptedDocumentTypes","abstract":[{"type":"text","text":"An array of recognizable document types."}],"title":"acceptedDocumentTypes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRootType":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype","navigatorTitle":[{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","title":"SBSDKGenericDocumentRootType","role":"symbol","abstract":[{"text":"Root document type.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"abstract":[{"text":"A class to recognize and detect the data fields from specific documents,","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","title":"SBSDKGenericDocumentRecognizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"acceptedDocumentTypes"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"acceptedDocumentTypes"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKGenericDocumentRootType *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"acceptedDocumentTypes","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1acceptedDocumentTypes\/title","value":"acceptedDocumentTypes"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1acceptedDocumentTypes\/fragments","value":[{"kind":"identifier","text":"acceptedDocumentTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/title","value":"SBSDKGenericDocumentRootType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}]},{"value":"SBSDKGenericDocumentRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}]}]}]}