{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/isaccumulatingdocuments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/isaccumulatingdocuments"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/isAccumulatingDocuments","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAccumulatingDocuments","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Set to ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":", if recognition should happen on a single image."},{"type":"text","text":" "},{"text":"Set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":", if consecutive frames should be used to refine the recognized documents."}]},{"style":"important","content":[{"inlineContent":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"text":", you need to call ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/resetDocumentAccumulation()","type":"reference"},{"type":"text","text":" before trying to recognize a different document."}],"type":"paragraph"}],"type":"aside","name":"Important"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isAccumulatingDocuments"}],"symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"isAccumulatingDocuments","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizer(py)isAccumulatingDocuments","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAccumulatingDocuments"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"Defines whether recognition should happen on a single image or on a consecutive frames."}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"title":"SBSDKGenericDocumentRecognizer","abstract":[{"type":"text","text":"A class to recognize and detect the data fields from specific documents,"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer/isAccumulatingDocuments":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAccumulatingDocuments","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/isAccumulatingDocuments","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/isaccumulatingdocuments","navigatorTitle":[{"kind":"identifier","text":"isAccumulatingDocuments"}],"title":"isAccumulatingDocuments","role":"symbol","kind":"symbol","abstract":[{"text":"Defines whether recognition should happen on a single image or on a consecutive frames.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer/resetDocumentAccumulation()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"resetDocumentAccumulation","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/resetDocumentAccumulation()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/resetdocumentaccumulation()","navigatorTitle":[{"text":"resetDocumentAccumulation","kind":"identifier"}],"title":"resetDocumentAccumulation()","role":"symbol","kind":"symbol","abstract":[{"text":"Resets the recognized-documents-accumulator.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isAccumulatingDocuments"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"isAccumulatingDocuments"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAccumulatingDocuments"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKGenericDocumentRecognizer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}]},{"value":"isAccumulatingDocuments","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1isAccumulatingDocuments\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isAccumulatingDocuments"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1isAccumulatingDocuments\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1resetDocumentAccumulation()\/title","value":"resetDocumentAccumulation"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetDocumentAccumulation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1resetDocumentAccumulation()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}