{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"]]},"abstract":[{"text":"Recognizes a document on a video frame and extracts the documents fields.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(recognizeDocumentOnBuffer:orientation:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"videoOrientation"},{"text":": ","kind":"text"},{"text":"AVCaptureVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":") -> "},{"text":"SBSDKGenericDocumentRecognitionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"CMSampleBuffer","type":"codeVoice"},{"text":" instance to recognize a document on.","type":"text"}],"type":"paragraph"}],"name":"sampleBuffer"},{"name":"videoOrientation","content":[{"type":"paragraph","inlineContent":[{"text":"The orientation of the sample buffer.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"The recognition result or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no document has been recognized."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/recognize(on:videoorientation:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/recognize(on:videoorientation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/recognize(on:videoOrientation:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"recognizeDocumentOnBuffer:orientation:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"recognize(on:videoOrientation:)","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"text":"videoOrientation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier","text":"AVCaptureVideoOrientation"},{"kind":"text","text":") -> "},{"text":"SBSDKGenericDocumentRecognitionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizer(im)recognizeDocumentOnBuffer:orientation:"},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"title":"SBSDKGenericDocumentRecognizer","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to recognize and detect the data fields from specific documents,"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionresult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognitionResult","kind":"identifier"}],"title":"SBSDKGenericDocumentRecognitionResult","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The recognition result of the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","type":"reference","isActive":true},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer/recognize(on:videoOrientation:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoOrientation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult","kind":"typeIdentifier","text":"SBSDKGenericDocumentRecognitionResult"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"recognizeDocumentOnBuffer:orientation:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/recognize(on:videoOrientation:)","abstract":[{"text":"Recognizes a document on a video frame and extracts the documents fields.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/recognize(on:videoorientation:)","type":"topic","title":"recognize(on:videoOrientation:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"recognizeDocumentOnBuffer:orientation:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"recognizeDocumentOnBuffer:orientation:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"SBSDKGenericDocumentRecognitionResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult"},{"kind":"text","text":" *) "},{"text":"recognizeDocumentOnBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@opaqueCMSampleBuffer","kind":"typeIdentifier","text":"opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"text":"sampleBuffer","kind":"internalParam"},{"kind":"text","text":" "},{"text":"orientation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"videoOrientation"},{"kind":"text","text":";"}]}]}},{"value":"SBSDKGenericDocumentRecognizer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionResult\/title","value":"SBSDKGenericDocumentRecognitionResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionResult\/fragments","value":[{"text":"SBSDKGenericDocumentRecognitionResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1recognize(on:videoOrientation:)\/title","value":"recognizeDocumentOnBuffer:orientation:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1recognize(on:videoOrientation:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeDocumentOnBuffer:orientation:"}]}]}]}