{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/resultAccumulatorConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"resultAccumulatorConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerAccumulationConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerAccumulationConfiguration","text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/resultaccumulatorconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/resultaccumulatorconfiguration"]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"resultAccumulatorConfiguration"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizer(py)resultAccumulatorConfiguration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"resultAccumulatorConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerAccumulationConfiguration","text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration"},{"kind":"text","text":"?"}],"title":"resultAccumulatorConfiguration"},"kind":"symbol","abstract":[{"type":"text","text":"The configuration of the receivers result accumulation."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerAccumulationConfiguration":{"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The result accumulation configuration of the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","isActive":true,"type":"reference"},{"text":" .","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizeraccumulationconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerAccumulationConfiguration","title":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer/resultAccumulatorConfiguration":{"title":"resultAccumulatorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/resultAccumulatorConfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resultAccumulatorConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerAccumulationConfiguration","text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/resultaccumulatorconfiguration","type":"topic","abstract":[{"type":"text","text":"The configuration of the receivers result accumulation."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resultAccumulatorConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"abstract":[{"text":"A class to recognize and detect the data fields from specific documents,","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","title":"SBSDKGenericDocumentRecognizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"resultAccumulatorConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"resultAccumulatorConfiguration"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerAccumulationConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerAccumulationConfiguration","text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration"},{"kind":"text","text":" * "},{"text":"resultAccumulatorConfiguration","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerAccumulationConfiguration\/title","op":"replace","value":"SBSDKGenericDocumentRecognizerAccumulationConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerAccumulationConfiguration\/fragments","value":[{"text":"SBSDKGenericDocumentRecognizerAccumulationConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1resultAccumulatorConfiguration\/title","value":"resultAccumulatorConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1resultAccumulatorConfiguration\/fragments","value":[{"text":"resultAccumulatorConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKGenericDocumentRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}