{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharpnessAcceptanceFactor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"0 - any image will be accepted."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"80 - a good compromise; the recommended setting."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"100 - only very sharp images will be accepted."}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"Defaults to 80.","type":"text"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/sharpnessAcceptanceFactor","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/sharpnessacceptancefactor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/sharpnessacceptancefactor"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizer(py)sharpnessAcceptanceFactor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sharpnessAcceptanceFactor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"kind":"identifier","text":"sharpnessAcceptanceFactor"}],"role":"symbol","title":"sharpnessAcceptanceFactor","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"The accepted minimal sharpness score. Images with a score less than that will be rejected with blurry status.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer/sharpnessAcceptanceFactor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sharpnessAcceptanceFactor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/sharpnessAcceptanceFactor","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/sharpnessacceptancefactor","navigatorTitle":[{"kind":"identifier","text":"sharpnessAcceptanceFactor"}],"title":"sharpnessAcceptanceFactor","role":"symbol","kind":"symbol","abstract":[{"text":"The accepted minimal sharpness score. Images with a score less than that will be rejected with blurry status.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"title":"SBSDKGenericDocumentRecognizer","abstract":[{"type":"text","text":"A class to recognize and detect the data fields from specific documents,"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"sharpnessAcceptanceFactor","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"sharpnessAcceptanceFactor"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"text":"sharpnessAcceptanceFactor","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1sharpnessAcceptanceFactor\/title","value":"sharpnessAcceptanceFactor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1sharpnessAcceptanceFactor\/fragments","value":[{"text":"sharpnessAcceptanceFactor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title","value":"SBSDKGenericDocumentRecognizer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}]}]}]}