{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation"},{"text":"? = SBSDKStorageLocation())","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}],"type":"paragraph"}],"name":"storageLocation"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:)"]}],"metadata":{"title":"init(storageLocation:)","symbolKind":"init","role":"symbol","roleHeading":"Initializer","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKKeyedImageStorage(im)initWithStorageLocation:","navigatorTitle":[{"text":"initWithStorageLocation:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKKeyedImageStorage"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Initializes a new ","type":"text"},{"code":"SBSDKKeyedImageStorage","type":"codeVoice"},{"text":" at the given storage location.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKKeyedImageStorage/init(storageLocation:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation"},{"text":"?)","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:)","abstract":[{"text":"Initializes a new ","type":"text"},{"code":"SBSDKKeyedImageStorage","type":"codeVoice"},{"text":" at the given storage location.","type":"text"}],"type":"topic","title":"init(storageLocation:)","navigatorTitle":[{"text":"initWithStorageLocation:","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageLocation":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragelocation","navigatorTitle":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"identifier"}],"kind":"symbol","title":"SBSDKStorageLocation","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKKeyedImageStorage":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkkeyedimagestorage","title":"SBSDKKeyedImageStorage","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKKeyedImageStorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in a dictionary-like fashion.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithStorageLocation:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStorageLocation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"storageLocation"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"storageLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The storage location at which the new storage should reside.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"initWithStorageLocation:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:)\/fragments"},{"op":"replace","value":"SBSDKStorageLocation","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/fragments"},{"op":"replace","value":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/navigatorTitle"},{"op":"replace","value":"SBSDKKeyedImageStorage","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage\/title"},{"op":"replace","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage\/fragments"},{"op":"replace","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage\/navigatorTitle"}]}]}