{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration(im)initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","navigatorTitle":[{"text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","kind":"identifier"}],"title":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCameraModule:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraModule","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraModule","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraModule","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"defaultZoomFactor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"defaultZoomFactor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoCropOnManualSnap:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"autoCropOnManualSnap","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"flashEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"flashEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minFocusDistanceLock:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minFocusDistanceLock","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pinchToZoomEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pinchToZoomEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CameraPreviewMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode","text":"SBSDKUI2CameraPreviewMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraPreviewMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"captureQualityPrioritization:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2CapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"captureQualityPrioritization","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoSnappingSensitivity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"autoSnappingSensitivity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoSnappingDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"autoSnappingDelay","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoSnappingEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoSnappingEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureWithHardwareButtonsEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"captureWithHardwareButtonsEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"fpsLimit:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fpsLimit"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraLiveScannerResolution:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraLiveScannerResolution","kind":"typeIdentifier","text":"SBSDKCameraLiveScannerResolution"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraLiveScannerResolution"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration\/initwithcameramodule:defaultzoomfactor:autocroponmanualsnap:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:autosnappingsensitivity:autosnappingdelay:autosnappingenabled:capturewithhardwar-1ll9w"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerCameraConfiguration/initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration\/initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration\/initwithcameramodule:defaultzoomfactor:autocroponmanualsnap:flashenabled:minfocusdistancelock:pinchtozoomenabled:camerapreviewmode:capturequalityprioritization:autosnappingsensitivity:autosnappingdelay:autosnappingenabled:capturewithhardwar-1ll9w","navigatorTitle":[{"text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","kind":"identifier"}],"role":"symbol","abstract":[],"title":"initWithCameraModule:defaultZoomFactor:autoCropOnManualSnap:flashEnabled:minFocusDistanceLock:pinchToZoomEnabled:cameraPreviewMode:captureQualityPrioritization:autoSnappingSensitivity:autoSnappingDelay:autoSnappingEnabled:captureWithHardwareButtonsEnabled:fpsLimit:cameraLiveScannerResolution:","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"title":"SBSDKUI2DocumentScannerCameraConfiguration","abstract":[{"type":"text","text":"Configuration of the camera behavior."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerCameraConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercameraconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraModule":{"title":"SBSDKUI2CameraModule","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"abstract":[{"type":"text","text":"Determines which camera module to use on start-up."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2cameramodule","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraModule","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CapturePhotoQualityPrioritization":{"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKUI2CapturePhotoQualityPrioritization","abstract":[{"type":"text","text":"Determines the prioritization of still image quality and capturing speed."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CapturePhotoQualityPrioritization","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2capturephotoqualityprioritization"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraLiveScannerResolution":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"type":"topic","title":"SBSDKCameraLiveScannerResolution","abstract":[{"type":"text","text":"The size of the image from camera which would be sent to the scanner for live scanning."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameralivescannerresolution","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraLiveScannerResolution","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2CameraPreviewMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2CameraPreviewMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPreviewMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the camera preview mode."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2camerapreviewmode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2CameraPreviewMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","value":"SBSDKUI2DocumentScannerCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/title","value":"SBSDKUI2CameraModule","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/fragments","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraModule\/navigatorTitle","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/title","value":"SBSDKUI2CapturePhotoQualityPrioritization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CapturePhotoQualityPrioritization"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CapturePhotoQualityPrioritization\/navigatorTitle","value":[{"text":"SBSDKUI2CapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/title","value":"SBSDKCameraLiveScannerResolution","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/title","value":"SBSDKUI2CameraPreviewMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2CameraPreviewMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraPreviewMode"}],"op":"replace"}]}]}