{"kind":"symbol","abstract":[{"text":"Driver license recognition is enabled in the licence.","type":"text"}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature@SBSDKFeatureDriverLicenseRecognition","symbolKind":"case","title":"SBSDKFeature.driverLicenseRecognition","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureDriverLicenseRecognition"}],"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"driverLicenseRecognition"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/driverlicenserecognition"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/driverlicenserecognition"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/driverLicenseRecognition"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"driverLicenseRecognition","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}],"title":"SBSDKFeature","kind":"symbol","abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/driverLicenseRecognition":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"driverLicenseRecognition","kind":"identifier"}],"title":"SBSDKFeature.driverLicenseRecognition","kind":"symbol","abstract":[{"type":"text","text":"Driver license recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/driverLicenseRecognition","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/driverlicenserecognition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureDriverLicenseRecognition"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFeatureDriverLicenseRecognition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKFeatureDriverLicenseRecognition","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKFeatureDriverLicenseRecognition","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/title","value":"SBSDKFeature"},{"value":[{"text":"SBSDKFeature","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/navigatorTitle","value":[{"text":"SBSDKFeature","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1driverLicenseRecognition\/title","value":"SBSDKFeatureDriverLicenseRecognition"},{"value":[{"text":"SBSDKFeatureDriverLicenseRecognition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1driverLicenseRecognition\/fragments"}]}]}