{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okPunctuationUpperCaseCleaned"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okPunctuationUpperCaseCleaned"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okpunctuationuppercasecleaned"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okpunctuationuppercasecleaned"]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okPunctuationUpperCaseCleaned","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKValueConsistency@SBSDKValueConsistencyOkPunctuationUpperCaseCleaned","role":"symbol","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","title":"SBSDKValueConsistency.okPunctuationUpperCaseCleaned","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned"}]},"sections":[],"abstract":[{"type":"text","text":"All values that correspond to the same logical field are equal after punctuation is removed and all characters are converted to upper case."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/okPunctuationUpperCaseCleaned":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okPunctuationUpperCaseCleaned","type":"topic","abstract":[{"type":"text","text":"All values that correspond to the same logical field are equal after punctuation is removed and all characters are converted to upper case."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okpunctuationuppercasecleaned","navigatorTitle":[{"text":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okPunctuationUpperCaseCleaned","kind":"identifier"}],"title":"SBSDKValueConsistency.okPunctuationUpperCaseCleaned"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"abstract":[{"type":"text","text":"The status of the consistency verification."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKValueConsistency","kind":"identifier"}],"title":"SBSDKValueConsistency","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","navigatorTitle":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okPunctuationUpperCaseCleaned\/title","op":"replace"},{"value":[{"text":"SBSDKValueConsistencyOkPunctuationUpperCaseCleaned","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okPunctuationUpperCaseCleaned\/fragments","op":"replace"},{"value":"SBSDKValueConsistency","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments","op":"replace"},{"value":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}