{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionFlipCameraButton","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton"}],"modules":[{"name":"ScanbotSDK"}],"title":"accessibilityDescriptionFlipCameraButton","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenTextLocalization(py)accessibilityDescriptionFlipCameraButton"},"abstract":[{"type":"text","text":"Accessibility description for the flip camera button."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Default is “Flip camera”"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionflipcamerabutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionflipcamerabutton"]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/accessibilityDescriptionFlipCameraButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/accessibilitydescriptionflipcamerabutton","navigatorTitle":[{"text":"accessibilityDescriptionFlipCameraButton","kind":"identifier"}],"abstract":[{"text":"Accessibility description for the flip camera button.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/accessibilityDescriptionFlipCameraButton","title":"accessibilityDescriptionFlipCameraButton","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization","title":"SBSDKUI2VINScannerScreenTextLocalization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for generic text scanner screen."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accessibilityDescriptionFlipCameraButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"accessibilityDescriptionFlipCameraButton","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionFlipCameraButton\/title","value":"accessibilityDescriptionFlipCameraButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1accessibilityDescriptionFlipCameraButton\/fragments","value":[{"text":"accessibilityDescriptionFlipCameraButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/title","value":"SBSDKUI2VINScannerScreenTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}]}]}]}