{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topUserGuidance"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Default is “Point the camera at the VIN”","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization"]]},"sections":[],"abstract":[{"type":"text","text":"Text for the top user guidance caption."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/topuserguidance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/topuserguidance"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topUserGuidance"},"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"topUserGuidance","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","title":"topUserGuidance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topUserGuidance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2VINScannerScreenTextLocalization(py)topUserGuidance"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization","title":"SBSDKUI2VINScannerScreenTextLocalization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for generic text scanner screen."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerScreenTextLocalization/topUserGuidance":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerScreenTextLocalization\/topUserGuidance","role":"symbol","title":"topUserGuidance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topUserGuidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerscreentextlocalization\/topuserguidance","abstract":[{"text":"Text for the top user guidance caption.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"topUserGuidance"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"topUserGuidance"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"topUserGuidance"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topUserGuidance"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/title","op":"replace","value":"SBSDKUI2VINScannerScreenTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerScreenTextLocalization"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2VINScannerScreenTextLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1topUserGuidance\/title","op":"replace","value":"topUserGuidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerScreenTextLocalization~1topUserGuidance\/fragments","op":"replace","value":[{"text":"topUserGuidance","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}