{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","title":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult(im)initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","text":"SBSDKDocumentDetectionStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detectionScores:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentDetectionScores","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionScores","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores"},{"text":" *) ","kind":"text"},{"text":"detectionScores","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"points:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"points","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"horizontalLines:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKLineSegmentInt *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"horizontalLines"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalLines:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentInt *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"verticalLines"},{"kind":"text","text":" "},{"kind":"identifier","text":"pointsNormalized:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSValue *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pointsNormalized"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalLinesNormalized:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentFloat *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"horizontalLinesNormalized"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalLinesNormalized:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKLineSegmentFloat *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"verticalLinesNormalized"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatio:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aspectRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"averageBrightness:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"averageBrightness"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/initwithstatus:detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:averagebrightness:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"abstract":[{"text":"Result of the document contour detection.","type":"text"}],"title":"SBSDKDocumentDetectionResult","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionStatus":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionstatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionStatus","abstract":[{"type":"text","text":"Status of the document detection."}],"title":"SBSDKDocumentDetectionStatus","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionResult/initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:":{"title":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionresult\/initwithstatus:detectionscores:points:horizontallines:verticallines:pointsnormalized:horizontallinesnormalized:verticallinesnormalized:aspectratio:averagebrightness:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionResult\/initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithStatus:detectionScores:points:horizontalLines:verticalLines:pointsNormalized:horizontalLinesNormalized:verticalLinesNormalized:aspectRatio:averageBrightness:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionScores":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionscores","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"abstract":[{"type":"text","text":"The total and partial scores for the detected document contour."}],"type":"topic","title":"SBSDKDocumentDetectionScores","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/title","op":"replace","value":"SBSDKDocumentDetectionResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/title","op":"replace","value":"SBSDKDocumentDetectionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/title","op":"replace","value":"SBSDKDocumentDetectionScores"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}]}]}]}