{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDetectionStatusLabel\/initWithFrame:","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKDetectionStatusLabel(im)initWithFrame:","role":"symbol","title":"initWithFrame:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"frame"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdetectionstatuslabel\/initwithframe:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDetectionStatusLabel"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDetectionStatusLabel/initWithFrame:":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdetectionstatuslabel\/initwithframe:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"title":"initWithFrame:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDetectionStatusLabel\/initWithFrame:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDetectionStatusLabel":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDetectionStatusLabel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdetectionstatuslabel","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":" subclass with rounded corners and content insets to display the status of the current document scanning result."}],"kind":"symbol","title":"SBSDKDetectionStatusLabel","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKDetectionStatusLabel","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDetectionStatusLabel\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDetectionStatusLabel\/fragments","value":[{"text":"SBSDKDetectionStatusLabel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDetectionStatusLabel"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDetectionStatusLabel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}