{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Asynchronously generates the PDF file from the images at the specified indices from the image storage and saves it to the specified URL."},{"text":" ","type":"text"},{"text":"Each page is made up of one image.","type":"text"}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"externalID":"s:10ScanbotSDK17SBSDKPDFGeneratorC8generate4from8indexSet6output10Foundation3URLVSgAA17SBSDKImageStoring_p_AH05IndexG0VSgAJtYaKF","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generate"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring"},{"text":", ","kind":"text"},{"text":"indexSet","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"text":"?, ","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"symbolKind":"method","title":"generate(from:indexSet:output:)"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@nonobjc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageStorage"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","kind":"typeIdentifier","text":"SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"text":", ","kind":"text"},{"text":"indexSet","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"? = nil, "},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"imageStorage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image store to take the images from."}]}]},{"name":"indexSet","content":[{"inlineContent":[{"type":"text","text":"The indices of images in the image store the PDF should be generated from. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if all images must be used."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output file URL."}]}],"name":"output"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The URL the PDF file has been written to or "},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:indexset:output:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:indexSet:output:)":{"abstract":[{"type":"text","text":"Asynchronously generates the PDF file from the images at the specified indices from the image storage and saves it to the specified URL."},{"text":" ","type":"text"},{"type":"text","text":"Each page is made up of one image."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:indexset:output:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generate"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring"},{"text":", ","kind":"text"},{"text":"indexSet","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"kind":"text","text":"?, "},{"text":"output","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"title":"generate(from:indexSet:output:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator":{"navigatorTitle":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator","type":"topic","title":"SBSDKPDFGenerator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator","abstract":[{"type":"text","text":"A class to generate an ordered collection of images with or without performing HOCR."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFGenerator"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","kind":"symbol","title":"SBSDKImageStoring","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageStoring"}],"abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKPDFGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/title"},{"value":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFGenerator"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","value":"SBSDKImageStoring","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments"},{"value":[{"text":"SBSDKImageStoring","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}