{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult"]]},"abstract":[{"type":"codeVoice","code":"True"},{"type":"text","text":", if the validation was successful. "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationSuccessful"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"validationSuccessful","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult(py)validationSuccessful","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"validationSuccessful","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"validationSuccessful","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresult\/validationsuccessful"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresult\/validationsuccessful"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult\/validationSuccessful","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResult/validationSuccessful":{"navigatorTitle":[{"kind":"identifier","text":"validationSuccessful"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult\/validationSuccessful","type":"topic","abstract":[{"type":"codeVoice","code":"True"},{"text":", if the validation was successful. ","type":"text"},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresult\/validationsuccessful","title":"validationSuccessful","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationSuccessful","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult","abstract":[{"text":"A class describing the result of the generic text line recognizer.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResult"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresult","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResult"}],"title":"SBSDKGenericTextLineRecognizerResult","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"validationSuccessful"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"validationSuccessful","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationSuccessful"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"validationSuccessful","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult~1validationSuccessful\/title"},{"value":[{"kind":"identifier","text":"validationSuccessful"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult~1validationSuccessful\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult\/title","value":"SBSDKGenericTextLineRecognizerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult\/fragments","op":"replace","value":[{"text":"SBSDKGenericTextLineRecognizerResult","kind":"identifier"}]}]}]}