{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProcessor\/init(sampleBuffer:videoOrientation:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Initializes a new image processor with the given "},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":" and video orientation."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithSampleBuffer:videoOrientation:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"videoOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"sampleBuffer","content":[{"inlineContent":[{"type":"text","text":"The input image of the new image processor."}],"type":"paragraph"}]},{"name":"videoOrientation","content":[{"inlineContent":[{"type":"text","text":"The original orientation of the video the sample buffer was extracted from."}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageProcessor(im)initWithSampleBuffer:videoOrientation:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(sampleBuffer:videoOrientation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"videoOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSampleBuffer:videoOrientation:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProcessor"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprocessor\/init(samplebuffer:videoorientation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprocessor\/init(samplebuffer:videoorientation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProcessor/init(sampleBuffer:videoOrientation:)":{"abstract":[{"text":"Initializes a new image processor with the given ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"},{"text":" and video orientation.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprocessor\/init(samplebuffer:videoorientation:)","kind":"symbol","role":"symbol","title":"init(sampleBuffer:videoOrientation:)","navigatorTitle":[{"kind":"identifier","text":"initWithSampleBuffer:videoOrientation:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProcessor\/init(sampleBuffer:videoOrientation:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageProcessor":{"navigatorTitle":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"role":"symbol","title":"SBSDKImageProcessor","abstract":[{"text":"A class to process images.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProcessor","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageprocessor","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageProcessor"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithSampleBuffer:videoOrientation:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSampleBuffer:videoOrientation:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithSampleBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"opaqueCMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"text":" *) ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"videoOrientation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"videoOrientation","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"sampleBuffer","content":[{"inlineContent":[{"text":"The input image of the new image processor.","type":"text"}],"type":"paragraph"}]},{"name":"videoOrientation","content":[{"inlineContent":[{"type":"text","text":"The original orientation of the video the sample buffer was extracted from."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor~1init(sampleBuffer:videoOrientation:)\/title","value":"initWithSampleBuffer:videoOrientation:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSampleBuffer:videoOrientation:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor~1init(sampleBuffer:videoOrientation:)\/fragments"},{"op":"replace","value":"SBSDKImageProcessor","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor\/fragments"},{"op":"replace","value":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageProcessor\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}