{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdetectionscores\/initwithtotalscore:distancescore:anglescore:sizescore:aspectratioscore:linecoveragescore:widthscore:heightscore:"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithTotalScore:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"totalScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"distanceScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":") ","kind":"text"},{"text":"distanceScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"angleScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"angleScore","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"sizeScore","kind":"internalParam"},{"kind":"text","text":" "},{"text":"aspectRatioScore:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aspectRatioScore"},{"text":" ","kind":"text"},{"text":"lineCoverageScore:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"lineCoverageScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"widthScore:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"widthScore"},{"text":" ","kind":"text"},{"text":"heightScore:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"heightScore","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionScores(im)initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores\/initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionScores/initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionscores\/initwithtotalscore:distancescore:anglescore:sizescore:aspectratioscore:linecoveragescore:widthscore:heightscore:","fragments":[{"kind":"text","text":"- "},{"text":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","kind":"identifier"}],"title":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores\/initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectionScores":{"type":"topic","abstract":[{"text":"The total and partial scores for the detected document contour.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectionScores","title":"SBSDKDocumentDetectionScores","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectionscores"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKDocumentDetectionScores","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectionScores\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}