{"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPage","kind":"identifier"}]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"type":"text","text":"A scanned document page basically consists of an original image, a polygon that describes the location of a"},{"type":"text","text":" "},{"type":"text","text":"paper document in the image and an image filter. Cropping and perspective-correcting the original image generates"},{"type":"text","text":" "},{"type":"text","text":"the unfiltered document image. Adding the filter generates the final document image, which is an"},{"type":"text","text":" "},{"type":"text","text":"optimized digital representation of the scanned paper document."}],"type":"paragraph"},{"inlineContent":[{"text":"This class encapsulates image processing, storing, persisting and preview creation in a very efficient way.","type":"text"},{"text":" ","type":"text"},{"text":"You can rotate the image, change the polygon and filter, limit the image size and more in a non-destructive way.","type":"text"},{"text":" ","type":"text"},{"text":"Document and preview images are lazily recreated after performing such changes.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"All images are persisted and cached on disk.","type":"text"},{"text":" ","type":"text"},{"text":"At any time you can request either an ","type":"text"},{"code":"SBSDKImageRef","type":"codeVoice"},{"text":" or the file URL to any of the images.","type":"text"}],"type":"paragraph"}]}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage","symbolKind":"class","role":"symbol","title":"SBSDKDocumentPage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}]},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(image:polygon:parametricFilters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(page:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:documentImageSizeLimit:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalPreviewImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalPreviewImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/pageFileUUID","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/pageImageSource","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/parametricFilters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/polygon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/status","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentPreviewImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentPreviewImageURL"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/applyDocumentDetection()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/applyDocumentDetection(engineMode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:engineMode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImage(usingParametricFilters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/rotateClockwise(_:)"],"generated":true}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentPreviewImage":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimage","navigatorTitle":[{"kind":"identifier","text":"documentPreviewImage"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"SBSDKImageRef"},{"type":"text","text":" of the document image including applied rotations,"},{"type":"text","text":" "},{"type":"text","text":"filter and polygon in a resolution matching the devices screen."}],"title":"documentPreviewImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPreviewImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/pageImageSource":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/pageImageSource","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/pageimagesource","navigatorTitle":[{"text":"pageImageSource","kind":"identifier"}],"title":"pageImageSource","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageImageSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPageImageSource","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageImageSource","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The source the image was received from."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentImage":{"abstract":[{"text":"An ","type":"text"},{"code":"SBSDKImageRef","type":"codeVoice"},{"text":" of the document image including applied rotations, filter and polygon.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImage","navigatorTitle":[{"text":"documentImage","kind":"identifier"}],"title":"documentImage","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentimage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/unfilteredDocumentPreviewImage":{"title":"unfilteredDocumentPreviewImage","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentPreviewImage","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unfilteredDocumentPreviewImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier","text":"SBSDKImageRef"},{"kind":"text","text":"?"}],"abstract":[{"text":"An ","type":"text"},{"code":"SBSDKImageRef","type":"codeVoice"},{"text":" of the unfiltered document image including applied rotations and polygon in a resolution matching the devices screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/unfiltereddocumentpreviewimage","navigatorTitle":[{"kind":"identifier","text":"unfilteredDocumentPreviewImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","title":"SBSDKDocumentPage","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class represents a scanned documents page."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/originalImage":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/originalimage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"originalImage"}],"kind":"symbol","type":"topic","title":"originalImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalImage","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"SBSDKImageRef"},{"type":"text","text":" of the original image including any applied rotations."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/init(page:)":{"type":"topic","navigatorTitle":[{"text":"initWithPage:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Copy initializer. Creates a deep copy of the receiver."}],"title":"init(page:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(page:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(page:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"page","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage","text":"SBSDKDocumentPage","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/init(pageFileID:polygon:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:)","navigatorTitle":[{"text":"initWithPageFileID:polygon:","kind":"identifier"}],"title":"init(pageFileID:polygon:)","abstract":[{"text":"Designated initializer. Creates a new page object.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/unfilteredDocumentPreviewImageURL":{"type":"topic","navigatorTitle":[{"text":"unfilteredDocumentPreviewImageURL","kind":"identifier"}],"role":"symbol","title":"unfilteredDocumentPreviewImageURL","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" of the unfiltered document image including applied rotations and polygon in a resolution matching the devices screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentPreviewImageURL","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/unfiltereddocumentpreviewimageurl","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unfilteredDocumentPreviewImageURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/originalImageURL":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalImageURL","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/originalimageurl","role":"symbol","title":"originalImageURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalImageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"originalImageURL"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"code":"URL","type":"codeVoice"},{"type":"text","text":" of the original image including any applied rotations."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/parametricFilters":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parametricFilters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"text":"]?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/parametricFilters","abstract":[{"text":"The parametric filters of the receiver.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/parametricfilters","title":"parametricFilters","type":"topic","navigatorTitle":[{"text":"parametricFilters","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/copyWithZone:":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/copywithzone:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/copyWithZone:","kind":"symbol","abstract":[],"title":"copyWithZone:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/originalPreviewImage":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalPreviewImage","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"SBSDKImageRef"},{"type":"text","text":" of the original image including any applied rotations in a resolution matching the devices screen."}],"role":"symbol","kind":"symbol","title":"originalPreviewImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalPreviewImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"originalPreviewImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/originalpreviewimage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/init(pageFileID:polygon:parametricFilters:)":{"abstract":[{"type":"text","text":"Designated initializer. Creates a new page object."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPageFileID:polygon:parametricFilters:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"parametricFilters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"]?)"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:)","type":"topic","title":"init(pageFileID:polygon:parametricFilters:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:parametricfilters:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/applyDocumentDetection()":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyDocumentDetection","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Detects the documents polygon on the original image of the receiver and applies it, regardless of the detection status.","type":"text"}],"title":"applyDocumentDetection()","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/applydocumentdetection()","navigatorTitle":[{"text":"applyDocumentDetection","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/applyDocumentDetection()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/unfilteredDocumentImageURL":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/unfiltereddocumentimageurl","title":"unfilteredDocumentImageURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unfilteredDocumentImageURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"unfilteredDocumentImageURL"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentImageURL","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"URL"},{"text":" of the unfiltered document image including applied rotations and polygon.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentImageSizeLimit":{"abstract":[{"type":"text","text":"Limits the maximum size of the document image. If width or height are zero, this property is effectively ignored."}],"role":"symbol","type":"topic","title":"documentImageSizeLimit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImageSizeLimit","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentimagesizelimit","navigatorTitle":[{"kind":"identifier","text":"documentImageSizeLimit"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentImageSizeLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/polygon":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"polygon","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/polygon","navigatorTitle":[{"text":"polygon","kind":"identifier"}],"title":"polygon","abstract":[{"type":"text","text":"The polygon of the area where the document is located within the pages image."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/polygon"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentImageURL":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImageURL","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"URL"},{"text":" of the document image including applied rotations, filter and polygon.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"documentImageURL","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentImageURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"title":"documentImageURL","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentimageurl"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"title":"SBSDKDocumentPageFileStorage","abstract":[{"type":"text","text":"A class to store and restore images of different types in a memory-efficient way."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentPreviewImage(usingParametricFilters:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"documentPreviewImageUsingParametricFilters:","kind":"identifier"}],"abstract":[{"type":"text","text":"A preview "},{"type":"codeVoice","code":"SBSDKImageRef"},{"type":"text","text":" of the document image including applied rotations, polygon and thbe given filter in a resolution matching the devices screen."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImage(usingParametricFilters:)","title":"documentPreviewImage(usingParametricFilters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreviewImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"usingParametricFilters","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimage(usingparametricfilters:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/unfilteredDocumentImage":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unfilteredDocumentImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier","text":"SBSDKImageRef"},{"kind":"text","text":"?"}],"title":"unfilteredDocumentImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentImage","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"SBSDKImageRef"},{"type":"text","text":" of the unfiltered document image including applied rotations and polygon."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/unfiltereddocumentimage","navigatorTitle":[{"kind":"identifier","text":"unfilteredDocumentImage"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/pageFileUUID":{"navigatorTitle":[{"kind":"identifier","text":"pageFileUUID"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/pageFileUUID","type":"topic","abstract":[{"type":"text","text":"The ID of the images in the default "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","isActive":true},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageFileUUID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/pagefileuuid","title":"pageFileUUID"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/detectDocument(applyPolygonIfOkay:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applyPolygonIfOkay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"detectDocumentAndApplyPolygonIfOkay:"}],"role":"symbol","abstract":[{"type":"text","text":"Detects the documents polygon on the original image of the receiver."}],"title":"detectDocument(applyPolygonIfOkay:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/detectdocument(applypolygonifokay:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/init(image:polygon:parametricFilters:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithImage:polygon:parametricFilters:"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(image:polygon:parametricfilters:)","title":"init(image:polygon:parametricFilters:)","abstract":[{"text":"Designated initializer. Creates a new page object.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"parametricFilters","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?)"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(image:polygon:parametricFilters:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentPreviewImageURL":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" of the document image including applied rotations,"},{"type":"text","text":" "},{"type":"text","text":"filter and polygon in a resolution matching the devices screen."}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimageurl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPreviewImageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentPreviewImageURL"}],"title":"documentPreviewImageURL","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageURL"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/applyDocumentDetection(engineMode:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/applydocumentdetection(enginemode:)","abstract":[{"type":"text","text":"Detects the documents polygon on the original image of the receiver and applies it, regardless of the detection status."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/applyDocumentDetection(engineMode:)","title":"applyDocumentDetection(engineMode:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyDocumentDetection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"engineMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","text":"SBSDKDocumentScannerEngineMode"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"applyDocumentDetectionWithEngineMode:"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/rotateClockwise(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/rotateclockwise(_:)","abstract":[{"type":"text","text":"Rotates the receiver clockwise."}],"navigatorTitle":[{"kind":"identifier","text":"rotateClockwise:"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/rotateClockwise(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateClockwise"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"rotateClockwise(_:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/originalPreviewImageURL":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalPreviewImageURL","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" of the original image including any applied rotations in a resolution matching the devices screen."}],"navigatorTitle":[{"kind":"identifier","text":"originalPreviewImageURL"}],"title":"originalPreviewImageURL","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/originalpreviewimageurl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalPreviewImageURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/detectDocument(applyPolygonIfOkay:engineMode:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:engineMode:)","navigatorTitle":[{"kind":"identifier","text":"detectDocumentAndApplyPolygonIfOkay:engineMode:"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/detectdocument(applypolygonifokay:enginemode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applyPolygonIfOkay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"engineMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode","text":"SBSDKDocumentScannerEngineMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult","text":"SBSDKDocumentDetectionResult"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Detects the documents polygon on the original image of the receiver."}],"title":"detectDocument(applyPolygonIfOkay:engineMode:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/status":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/status","type":"topic","abstract":[{"type":"text","text":"The status of the documents polygon that was detected on the original image."}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"title":"status","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentDetectionStatus","kind":"typeIdentifier","text":"SBSDKDocumentDetectionStatus"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/keyPathsForValuesAffectingValueForKey:":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/keypathsforvaluesaffectingvalueforkey:","title":"keyPathsForValuesAffectingValueForKey:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/keyPathsForValuesAffectingValueForKey:","navigatorTitle":[{"kind":"identifier","text":"keyPathsForValuesAffectingValueForKey:"}],"type":"topic","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"keyPathsForValuesAffectingValueForKey:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/init(pageFileID:polygon:parametricFilters:documentImageSizeLimit:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithPageFileID:polygon:parametricFilters:documentImageSizeLimit:"}],"abstract":[{"type":"text","text":"Designated initializer. Creates a new page object."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:documentImageSizeLimit:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/init(pagefileid:polygon:parametricfilters:documentimagesizelimit:)","title":"init(pageFileID:polygon:parametricFilters:documentImageSizeLimit:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageFileID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier","text":"SBSDKPolygon"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"parametricFilters"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier","text":"SBSDKParametricFilter"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"documentImageSizeLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}]},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKDocumentPage","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalPreviewImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/originalPreviewImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/pageFileUUID","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/pageImageSource","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/parametricFilters","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/polygon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/status","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentImageURL","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentPreviewImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/unfilteredDocumentPreviewImageURL"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/applyDocumentDetection()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/applyDocumentDetection(engineMode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/detectDocument(applyPolygonIfOkay:engineMode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImage(usingParametricFilters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(image:polygon:parametricFilters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(page:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/init(pageFileID:polygon:parametricFilters:documentImageSizeLimit:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/rotateClockwise(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/keyPathsForValuesAffectingValueForKey:"],"anchor":"Type-Methods","title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"documentPreviewImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImage\/title"},{"op":"replace","value":[{"text":"documentPreviewImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImage\/fragments"},{"op":"replace","value":"pageImageSource","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1pageImageSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"pageImageSource"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1pageImageSource\/fragments"},{"op":"replace","value":"documentImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentImage\/title"},{"op":"replace","value":[{"text":"documentImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentImage\/fragments"},{"op":"replace","value":"unfilteredDocumentPreviewImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentPreviewImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"unfilteredDocumentPreviewImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentPreviewImage\/fragments"},{"op":"replace","value":"SBSDKDocumentPage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle"},{"op":"replace","value":"originalImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1originalImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"originalImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1originalImage\/fragments"},{"op":"replace","value":"initWithPage:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(page:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPage:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(page:)\/fragments"},{"op":"replace","value":"initWithPageFileID:polygon:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPageFileID:polygon:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:)\/fragments"},{"op":"replace","value":"unfilteredDocumentPreviewImageURL","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentPreviewImageURL\/title"},{"op":"replace","value":[{"text":"unfilteredDocumentPreviewImageURL","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentPreviewImageURL\/fragments"},{"op":"replace","value":"originalImageURL","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1originalImageURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"originalImageURL"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1originalImageURL\/fragments"},{"op":"replace","value":"parametricFilters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1parametricFilters\/title"},{"op":"replace","value":[{"text":"parametricFilters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1parametricFilters\/fragments"},{"op":"replace","value":"originalPreviewImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1originalPreviewImage\/title"},{"op":"replace","value":[{"text":"originalPreviewImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1originalPreviewImage\/fragments"},{"op":"replace","value":"initWithPageFileID:polygon:parametricFilters:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:parametricFilters:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPageFileID:polygon:parametricFilters:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:parametricFilters:)\/fragments"},{"op":"replace","value":"applyDocumentDetection","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1applyDocumentDetection()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applyDocumentDetection"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1applyDocumentDetection()\/fragments"},{"op":"replace","value":"unfilteredDocumentImageURL","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentImageURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"unfilteredDocumentImageURL"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentImageURL\/fragments"},{"op":"replace","value":"documentImageSizeLimit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentImageSizeLimit\/title"},{"op":"replace","value":[{"text":"documentImageSizeLimit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentImageSizeLimit\/fragments"},{"op":"replace","value":"polygon","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1polygon\/title"},{"op":"replace","value":[{"text":"polygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1polygon\/fragments"},{"op":"replace","value":"documentImageURL","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentImageURL\/title"},{"op":"replace","value":[{"text":"documentImageURL","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentImageURL\/fragments"},{"op":"replace","value":"SBSDKDocumentPageFileStorage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle"},{"op":"replace","value":"documentPreviewImageUsingParametricFilters:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImage(usingParametricFilters:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentPreviewImageUsingParametricFilters:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImage(usingParametricFilters:)\/fragments"},{"op":"replace","value":"unfilteredDocumentImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentImage\/title"},{"op":"replace","value":[{"text":"unfilteredDocumentImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1unfilteredDocumentImage\/fragments"},{"op":"replace","value":"pageFileUUID","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1pageFileUUID\/title"},{"op":"replace","value":[{"text":"pageFileUUID","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1pageFileUUID\/fragments"},{"op":"replace","value":"detectDocumentAndApplyPolygonIfOkay:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1detectDocument(applyPolygonIfOkay:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"detectDocumentAndApplyPolygonIfOkay:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1detectDocument(applyPolygonIfOkay:)\/fragments"},{"op":"replace","value":"initWithImage:polygon:parametricFilters:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(image:polygon:parametricFilters:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:polygon:parametricFilters:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(image:polygon:parametricFilters:)\/fragments"},{"op":"replace","value":"documentPreviewImageURL","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImageURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentPreviewImageURL"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImageURL\/fragments"},{"op":"replace","value":"applyDocumentDetectionWithEngineMode:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1applyDocumentDetection(engineMode:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"applyDocumentDetectionWithEngineMode:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1applyDocumentDetection(engineMode:)\/fragments"},{"op":"replace","value":"rotateClockwise:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1rotateClockwise(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rotateClockwise:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1rotateClockwise(_:)\/fragments"},{"op":"replace","value":"originalPreviewImageURL","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1originalPreviewImageURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"originalPreviewImageURL"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1originalPreviewImageURL\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1detectDocument(applyPolygonIfOkay:engineMode:)\/title","value":"detectDocumentAndApplyPolygonIfOkay:engineMode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1detectDocument(applyPolygonIfOkay:engineMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectDocumentAndApplyPolygonIfOkay:engineMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1status\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:parametricFilters:documentImageSizeLimit:)\/title","value":"initWithPageFileID:polygon:parametricFilters:documentImageSizeLimit:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1init(pageFileID:polygon:parametricFilters:documentImageSizeLimit:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageFileID:polygon:parametricFilters:documentImageSizeLimit:"}]}]}]}