{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/init()"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/acceptedCountries","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/acceptedMRZTypes"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKDocumentDataExtractorMRZFallbackConfiguration) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration"]}],"metadata":{"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"symbolKind":"class","role":"symbol","title":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"abstract":[{"text":"MRZ fallback configuration element.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration element does not enable the scanning of any document types by itself.","type":"text"},{"text":" ","type":"text"},{"text":"Add to extractor configuration to enable recognizing the MRZ only, specifically for documents that are otherwise not supported.","type":"text"},{"text":" ","type":"text"},{"text":"Note that this may enable scanning of documents that were not enabled through the accepted document types.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement","role":"symbol","abstract":[{"text":"Base class for all document data extraction configuration elements.","type":"text"}],"title":"SBSDKDocumentDataExtractorConfigurationElement","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/fromJsonWithJson:":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fromJsonWithJson:","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/acceptedCountries":{"abstract":[{"text":"List of ISO 3166-1 alpha-3 country codes for which the MRZ fallback is enabled. (e.g. “DEU” for Germany).","type":"text"}],"navigatorTitle":[{"text":"acceptedCountries","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/acceptedCountries","type":"topic","title":"acceptedCountries","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptedCountries","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/acceptedcountries","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration":{"abstract":[{"text":"MRZ fallback configuration element.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration element does not enable the scanning of any document types by itself.","type":"text"},{"text":" ","type":"text"},{"text":"Add to extractor configuration to enable recognizing the MRZ only, specifically for documents that are otherwise not supported.","type":"text"},{"text":" ","type":"text"},{"text":"Note that this may enable scanning of documents that were not enabled through the accepted document types.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration","role":"symbol","type":"topic","title":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/initWithAcceptedCountries:acceptedMRZTypes:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/initWithAcceptedCountries:acceptedMRZTypes:","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAcceptedCountries:acceptedMRZTypes:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"initWithAcceptedCountries:acceptedMRZTypes:","kind":"identifier"}],"title":"initWithAcceptedCountries:acceptedMRZTypes:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/initwithacceptedcountries:acceptedmrztypes:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/hash":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/acceptedMRZTypes":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/acceptedmrztypes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/acceptedMRZTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedMRZTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZDocumentType","text":"SBSDKMRZDocumentType"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"acceptedMRZTypes"}],"title":"acceptedMRZTypes","kind":"symbol","abstract":[{"text":"List of MRZ document types for which MRZ fallback is enabled.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/toJson(configuration:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/toJson(configuration:)","type":"topic","title":"toJson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/tojson(configuration:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/init()":{"kind":"symbol","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/init()","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/init()","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"Foundation.NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/isEqual:":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/isequal:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration/copyWithZone:":{"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration\/copywithzone:","abstract":[],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/copyWithZone:","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/acceptedCountries","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/acceptedMRZTypes","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/hash"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/initWithAcceptedCountries:acceptedMRZTypes:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/toJson(configuration:)"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fromJsonWithJson:"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationElement","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationElement","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/title","value":"SBSDKDocumentDataExtractorConfigurationElement"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/fragments","value":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1acceptedCountries\/title","value":"acceptedCountries"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1acceptedCountries\/fragments","value":[{"text":"acceptedCountries","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/title","value":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1acceptedMRZTypes\/title","value":"acceptedMRZTypes"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1acceptedMRZTypes\/fragments","value":[{"text":"acceptedMRZTypes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1toJson(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}