{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSProgress"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/s8SendableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"},"sections":[],"metadata":{"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgress"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKProgress","symbolKind":"class"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/init(totalUnitCount:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/updateHandler"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindCreatePages","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindProcessImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindTextRecognition"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprogress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprogress"]}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/updateHandler":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/updateHandler","kind":"symbol","title":"updateHandler","role":"symbol","abstract":[{"text":"The standard process for observing a ","type":"text"},{"type":"codeVoice","code":"Progress"},{"text":" progressing is to use KVO on the ","type":"text"},{"type":"codeVoice","code":"Progress"},{"text":" instance.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"SBSDKProgressUpdateHandler"},{"text":" simplifies observing the progress largely.","type":"text"},{"text":" ","type":"text"},{"text":"It is called on main thread whenever the progress changes. Usually here you update your UI, e.g. ","type":"text"},{"type":"codeVoice","code":"UIProgressView"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKProgessUpdateHandler","preciseIdentifier":"s:10ScanbotSDK25SBSDKProgessUpdateHandlera","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"updateHandler","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkprogress\/updatehandler"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/SBSDKProgressKindTextRecognition":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindTextRecognition","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgressKindTextRecognition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotsdk\/sbsdkprogress\/sbsdkprogresskindtextrecognition","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgressKindTextRecognition"}],"kind":"symbol","type":"topic","abstract":[{"text":"The progress describes a text recognition operation.","type":"text"}],"title":"SBSDKProgressKindTextRecognition","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/localizedAdditionalDescription":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"localizedAdditionalDescription","kind":"identifier"}],"title":"localizedAdditionalDescription","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/localizedAdditionalDescription","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/localizedadditionaldescription","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/localizedDescription":{"fragments":[{"text":"localizedDescription","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/localizeddescription","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/localizedDescription","abstract":[],"title":"localizedDescription"},"doc://net.doo.ScanbotSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s8SendableP","title":"Swift.Sendable"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"url":"\/documentation\/scanbotsdk\/sbsdkprogress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","type":"topic","abstract":[],"title":"SBSDKProgress","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/SBSDKProgressKindProcessImage":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindProcessImage","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/sbsdkprogresskindprocessimage","abstract":[{"type":"text","text":"The progress describes an image processing operation."}],"type":"topic","role":"symbol","title":"SBSDKProgressKindProcessImage","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgressKindProcessImage"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgressKindProcessImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSProgress":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSProgress","title":"NSProgress"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/initWithParent:userInfo:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithParent:userInfo:","kind":"identifier"}],"type":"topic","title":"initWithParent:userInfo:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/initwithparent:userinfo:","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithParent:userInfo:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/initWithParent:userInfo:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/observeValueForKeyPath:ofObject:change:context:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/observeValueForKeyPath:ofObject:change:context:","fragments":[{"text":"- ","kind":"text"},{"text":"observeValueForKeyPath:ofObject:change:context:","kind":"identifier"}],"navigatorTitle":[{"text":"observeValueForKeyPath:ofObject:change:context:","kind":"identifier"}],"abstract":[],"type":"topic","title":"observeValueForKeyPath:ofObject:change:context:","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/observevalueforkeypath:ofobject:change:context:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/cancelled":{"title":"cancelled","fragments":[{"kind":"identifier","text":"cancelled"}],"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/cancelled","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/cancelled"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/init(totalUnitCount:)":{"type":"topic","title":"init(totalUnitCount:)","navigatorTitle":[{"text":"initWithTotalUnitCount:","kind":"identifier"}],"abstract":[{"type":"text","text":"A convenience initializer mimicking the behavior of "},{"code":"Progress","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"totalUnitCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/init(totalUnitCount:)","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/init(totalunitcount:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/SBSDKProgressKindCreatePages":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/sbsdkprogresskindcreatepages","role":"symbol","navigatorTitle":[{"text":"SBSDKProgressKindCreatePages","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindCreatePages","title":"SBSDKProgressKindCreatePages","abstract":[{"text":"The progress describes a document\/PDF creation operation.","type":"text"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgressKindCreatePages","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/cancel":{"abstract":[],"title":"cancel","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/cancel","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/cancel","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"cancel","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"cancel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKProgress"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgress"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKProgress","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/cancelled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/localizedAdditionalDescription","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/localizedDescription","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/updateHandler"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/cancel","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/init(totalUnitCount:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/initWithParent:userInfo:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/observeValueForKeyPath:ofObject:change:context:"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindCreatePages","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindProcessImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/SBSDKProgressKindTextRecognition"],"anchor":"Type-Properties","title":"Type Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSProgress"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSProgress","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1updateHandler\/title","op":"replace","value":"updateHandler"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1updateHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"updateHandler"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1SBSDKProgressKindTextRecognition\/title","op":"replace","value":"SBSDKProgressKindTextRecognition"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1SBSDKProgressKindTextRecognition\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgressKindTextRecognition"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title","op":"replace","value":"SBSDKProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgress"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgress"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1SBSDKProgressKindProcessImage\/title","op":"replace","value":"SBSDKProgressKindProcessImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1SBSDKProgressKindProcessImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgressKindProcessImage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1init(totalUnitCount:)\/title","op":"replace","value":"initWithTotalUnitCount:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1init(totalUnitCount:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTotalUnitCount:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1SBSDKProgressKindCreatePages\/title","op":"replace","value":"SBSDKProgressKindCreatePages"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1SBSDKProgressKindCreatePages\/fragments","op":"replace","value":[{"text":"SBSDKProgressKindCreatePages","kind":"identifier"}]}]}]}