{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroCustomImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroDefaultImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroNoImage"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"abstract":[{"text":"The image for the introduction screen of a document data extractor screen.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroCustomImage(uri:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroDefaultImage()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroNoImage()"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2DocumentDataExtractorIntroImage) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorIntroImage","title":"SBSDKUI2DocumentDataExtractorIntroImage","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"symbolKind":"class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage"]}],"references":{"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage":{"abstract":[{"type":"text","text":"The image for the introduction screen of a document data extractor screen."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage","title":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"title":"SBSDKUI2Node","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2node","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/isEqual:":{"title":"isEqual:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/isEqual:","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/isequal:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataIntroDefaultImage":{"title":"SBSDKUI2DocumentDataIntroDefaultImage","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroDefaultImage","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroDefaultImage"}],"abstract":[{"type":"text","text":"The image for the introduction screen featuring a document."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataintrodefaultimage","navigatorTitle":[{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/hash":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/hash","title":"hash","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/hash","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/documentDataIntroDefaultImage()":{"abstract":[],"kind":"symbol","title":"documentDataIntroDefaultImage()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroDefaultImage()","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintrodefaultimage()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentDataIntroDefaultImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroDefaultImage"}],"navigatorTitle":[{"text":"documentDataIntroDefaultImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/toJson(configuration:)":{"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"title":"toJson(configuration:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/tojson(configuration:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/toJson(configuration:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/fromJsonWithJson:":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","role":"symbol","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataIntroNoImage":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"No image for the introduction screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroNoImage"}],"title":"SBSDKUI2DocumentDataIntroNoImage","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroNoImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroNoImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataintronoimage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/documentDataIntroCustomImage(uri:)":{"title":"documentDataIntroCustomImage(uri:)","type":"topic","navigatorTitle":[{"text":"documentDataIntroCustomImageWithUri:","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintrocustomimage(uri:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroCustomImage(uri:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataIntroCustomImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"uri"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroCustomImage","kind":"typeIdentifier","text":"SBSDKUI2DocumentDataIntroCustomImage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/documentDataIntroNoImage()":{"kind":"symbol","role":"symbol","title":"documentDataIntroNoImage()","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/documentdataintronoimage()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataIntroNoImage"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataIntroNoImage","kind":"typeIdentifier","text":"SBSDKUI2DocumentDataIntroNoImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroNoImage()","navigatorTitle":[{"kind":"identifier","text":"documentDataIntroNoImage"}],"type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataIntroCustomImage":{"abstract":[{"type":"text","text":"A custom image for the introduction screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataintrocustomimage","role":"symbol","title":"SBSDKUI2DocumentDataIntroCustomImage","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroCustomImage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroCustomImage","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroCustomImage"}]},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorIntroImage/copyWithZone:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/copyWithZone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorintroimage\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKUI2DocumentDataExtractorIntroImage","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/hash"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroCustomImage(uri:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroDefaultImage()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/documentDataIntroNoImage()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorIntroImage\/fromJsonWithJson:"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroCustomImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroDefaultImage","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataIntroNoImage"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","text":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2DocumentDataExtractorIntroImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/title","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorIntroImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorIntroImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2Node","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2DocumentDataIntroDefaultImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroDefaultImage\/title","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroDefaultImage\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentDataIntroDefaultImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroDefaultImage\/navigatorTitle","op":"replace"},{"value":"documentDataIntroDefaultImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroDefaultImage()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"documentDataIntroDefaultImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroDefaultImage()\/fragments","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1toJson(configuration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1toJson(configuration:)\/fragments","op":"replace"},{"value":"SBSDKUI2DocumentDataIntroNoImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroNoImage\/title","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentDataIntroNoImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroNoImage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroNoImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroNoImage\/navigatorTitle","op":"replace"},{"value":"documentDataIntroCustomImageWithUri:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroCustomImage(uri:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"documentDataIntroCustomImageWithUri:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroCustomImage(uri:)\/fragments","op":"replace"},{"value":"documentDataIntroNoImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroNoImage()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"documentDataIntroNoImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorIntroImage~1documentDataIntroNoImage()\/fragments","op":"replace"},{"value":"SBSDKUI2DocumentDataIntroCustomImage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroCustomImage\/title","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentDataIntroCustomImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroCustomImage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataIntroCustomImage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataIntroCustomImage\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}