{"sections":[],"abstract":[{"text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKUI2ArOverlayPolygonConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/init()"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/deselected","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/selected","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/visible"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/toJson(configuration:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration","navigatorTitle":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"title":"SBSDKUI2ArOverlayPolygonConfiguration","symbolKind":"class"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/toJson(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/tojson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/deselected":{"navigatorTitle":[{"text":"deselected","kind":"identifier"}],"abstract":[{"type":"text","text":"Appearance of the overlay polygon when a barcode is not selected."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deselected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/deselected","title":"deselected","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/deselected"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/init()":{"title":"init()","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/init()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/init()","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Node":{"title":"SBSDKUI2Node","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2node","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/isEqual:","type":"topic","role":"symbol","kind":"symbol","title":"isEqual:","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/copyWithZone:":{"abstract":[],"kind":"symbol","role":"symbol","title":"copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/copywithzone:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/visible":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/visible","type":"topic","title":"visible","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/visible","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"visible"}],"abstract":[{"text":"Control the visibility of the overlay polygon.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/selected":{"title":"selected","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Appearance of the overlay polygon after a barcode has been selected."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/selected","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/selected","navigatorTitle":[{"text":"selected","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}],"title":"SBSDKUI2ArOverlayPolygonConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration","abstract":[{"type":"text","text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}]},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/fromJsonWithJson:":{"kind":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/fromjsonwithjson:","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/hash":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/hash","fragments":[{"kind":"identifier","text":"hash"}],"abstract":[],"role":"symbol","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/hash","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/initWithVisible:deselected:selected:":{"navigatorTitle":[{"text":"initWithVisible:deselected:selected:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/initwithvisible:deselected:selected:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/initWithVisible:deselected:selected:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisible:deselected:selected:","kind":"identifier"}],"abstract":[],"role":"symbol","title":"initWithVisible:deselected:selected:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2ArOverlayPolygonConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/deselected","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/selected","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/visible"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/initWithVisible:deselected:selected:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/fromJsonWithJson:"],"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Node","text":"SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Node","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1toJson(configuration:)\/fragments"},{"value":"deselected","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1deselected\/title"},{"value":[{"kind":"identifier","text":"deselected"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1deselected\/fragments"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1init()\/fragments"},{"value":"SBSDKUI2Node","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/title"},{"value":[{"text":"SBSDKUI2Node","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Node\/navigatorTitle"},{"value":"visible","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1visible\/title"},{"value":[{"text":"visible","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1visible\/fragments"},{"value":"selected","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1selected\/title"},{"value":[{"kind":"identifier","text":"selected"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1selected\/fragments"},{"value":"SBSDKUI2ArOverlayPolygonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/title"},{"value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/navigatorTitle"}]}]}