{"abstract":[{"text":"The Auto-snapping mode handles different auto-snap scenarios.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabledWithGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/enabled"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkautosnappingmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkautosnappingmode"]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"title":"SBSDKAutoSnappingMode","roleHeading":"Enumeration","externalID":"c:@M@ScanbotSDK@E@SBSDKAutoSnappingMode","symbolKind":"enum","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/init(rawValue:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/init(rawvalue:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/equatable-implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/Equatable-Implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/enabled":{"url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/enabled","kind":"symbol","title":"SBSDKAutoSnappingMode.enabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/enabled","abstract":[{"text":"Auto-snapping and user guidance are enabled.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAutoSnappingModeEnabled","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/disabledWithGuidance":{"abstract":[{"text":"Auto-snapping is disabled while user guidance is enabled.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabledWithGuidance","kind":"symbol","role":"symbol","title":"SBSDKAutoSnappingMode.disabledWithGuidance","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabledWithGuidance","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/disabledwithguidance","navigatorTitle":[{"text":"SBSDKAutoSnappingModeDisabledWithGuidance","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"title":"SBSDKAutoSnappingMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode","abstract":[{"type":"text","text":"The Auto-snapping mode handles different auto-snap scenarios."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAutoSnappingMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/rawrepresentable-implementations","role":"collectionGroup","kind":"article"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAutoSnappingMode/disabled":{"abstract":[{"text":"Auto-snapping and user guidance are disabled.","type":"text"}],"title":"SBSDKAutoSnappingMode.disabled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabled","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKAutoSnappingModeDisabled","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkautosnappingmode\/disabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"SBSDKAutoSnappingMode","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabled","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/disabledWithGuidance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAutoSnappingMode\/enabled"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAutoSnappingMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1enabled\/title","op":"replace","value":"SBSDKAutoSnappingModeEnabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1enabled\/fragments","op":"replace","value":[{"text":"SBSDKAutoSnappingModeEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1disabledWithGuidance\/title","op":"replace","value":"SBSDKAutoSnappingModeDisabledWithGuidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1disabledWithGuidance\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAutoSnappingModeDisabledWithGuidance"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/title","op":"replace","value":"SBSDKAutoSnappingMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/fragments","op":"replace","value":[{"text":"SBSDKAutoSnappingMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKAutoSnappingMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode\/navigatorTitle"},{"value":"SBSDKAutoSnappingModeDisabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1disabled\/title"},{"value":[{"text":"SBSDKAutoSnappingModeDisabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAutoSnappingMode~1disabled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}