{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The structured append mode can be used to split a message across multiple barcodes."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKStructuredAppendInfo) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/count","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/index"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/toJson(configuration:)"],"title":"Instance Methods"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"roleHeading":"Class","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKStructuredAppendInfo","symbolKind":"class","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/hash","abstract":[],"title":"hash","fragments":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/hash","kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/index":{"abstract":[{"text":"The index of the barcode in the structured append set.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","title":"index","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/index","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/index","navigatorTitle":[{"text":"index","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/fromjsonwithjson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/copyWithZone:":{"abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/copywithzone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/isequal:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/isEqual:","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/count":{"navigatorTitle":[{"kind":"identifier","text":"count"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/count","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/count","title":"count","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[{"type":"text","text":"The number of barcodes in the structured append set."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/id":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/id","abstract":[{"text":"The ID of the structured append set.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/id","title":"id","type":"topic"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/toJson(configuration:)":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/tojson(configuration:)","title":"toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/toJson(configuration:)","role":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo/initWithCount:index:id:":{"url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo\/initwithcount:index:id:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCount:index:id:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCount:index:id:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/initWithCount:index:id:","kind":"symbol","type":"topic","title":"initWithCount:index:id:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo":{"title":"SBSDKStructuredAppendInfo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo","navigatorTitle":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"The structured append mode can be used to split a message across multiple barcodes."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKStructuredAppendInfo","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/count","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/index"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/initWithCount:index:id:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/toJson(configuration:)"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo\/fromJsonWithJson:"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"index","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo~1index\/title"},{"value":[{"text":"index","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo~1index\/fragments"},{"value":"count","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo~1count\/title"},{"value":[{"text":"count","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo~1count\/fragments"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo~1id\/title"},{"value":[{"kind":"identifier","text":"id"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo~1id\/fragments"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo~1toJson(configuration:)\/fragments"},{"value":"SBSDKStructuredAppendInfo","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/title"},{"value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}