{"sections":[],"kind":"symbol","metadata":{"title":"SBSDKCheckDocumentDetectionMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode","roleHeading":"Enumeration"},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectAndCropDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/disabled"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Check document detection and extraction mode.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKCheckDocumentDetectionMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/RawRepresentable-Implementations","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"abstract":[{"text":"Check document detection and extraction mode.","type":"text"}],"type":"topic","title":"SBSDKCheckDocumentDetectionMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/init(rawValue:)","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/init(rawvalue:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode/disabled":{"type":"topic","title":"SBSDKCheckDocumentDetectionMode.disabled","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCheckDocumentDetectionModeDisabled","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/disabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/disabled","abstract":[{"type":"text","text":"Document detection is not performed. Successful check scans will only contain the machine-readable check data without a full crop of the check."}]},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode/detectDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Document scanner will be used to locate the complete check in the input image. The documentDetectionResult result field will contain the result of document detection."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectDocument","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/detectdocument","title":"SBSDKCheckDocumentDetectionMode.detectDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionModeDetectDocument"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/Equatable-Implementations","role":"collectionGroup","kind":"article","title":"Equatable Implementations","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/equatable-implementations","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode/detectAndCropDocument":{"title":"SBSDKCheckDocumentDetectionMode.detectAndCropDocument","navigatorTitle":[{"text":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode\/detectandcropdocument","role":"symbol","type":"topic","abstract":[{"text":"Document scanner will be used to locate the complete check in the input image. The documentDetectionResult result field will contain the result of document detection. The croppedImage result field will contain a crop of the entire check.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectAndCropDocument","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectAndCropDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKCheckDocumentDetectionMode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectAndCropDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/detectDocument","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode\/disabled"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/title","value":"SBSDKCheckDocumentDetectionMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1disabled\/title","value":"SBSDKCheckDocumentDetectionModeDisabled","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1disabled\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionModeDisabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1detectDocument\/title","value":"SBSDKCheckDocumentDetectionModeDetectDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1detectDocument\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionModeDetectDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1detectAndCropDocument\/title","value":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode~1detectAndCropDocument\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionModeDetectAndCropDocument","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}