{"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration(im)toJsonWithConfiguration:","title":"toJson(configuration:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration"},{"kind":"text","text":" = SBSDKToJSONConfiguration()) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlayfindandpickconfiguration\/tojson(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlayfindandpickconfiguration\/tojson(configuration:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration\/toJson(configuration:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayFindAndPickConfiguration/toJson(configuration:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"toJson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlayfindandpickconfiguration\/tojson(configuration:)","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration\/toJson(configuration:)","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKToJSONConfiguration":{"title":"SBSDKToJSONConfiguration","navigatorTitle":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration used to serialize an object to json.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktojsonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayFindAndPickConfiguration":{"type":"topic","title":"SBSDKUI2ArOverlayFindAndPickConfiguration","navigatorTitle":[{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration of the AR overlay.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlayfindandpickconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"toJsonWithConfiguration:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"toJsonWithConfiguration:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration~1toJson(configuration:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration~1toJson(configuration:)\/fragments"},{"value":"SBSDKToJSONConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/title","value":"SBSDKUI2ArOverlayFindAndPickConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/navigatorTitle"}]}]}