{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType"]]},"abstract":[{"text":"Field 8: card number","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/cardnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/cardnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardNumber"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardNumber"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKHealthInsuranceCardFieldType@SBSDKHealthInsuranceCardFieldTypeCardNumber","role":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeCardNumber","kind":"identifier"}],"roleHeading":"Case","title":"SBSDKHealthInsuranceCardFieldType.cardNumber","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardNumber","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType":{"title":"SBSDKHealthInsuranceCardFieldType","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"abstract":[{"type":"text","text":"Health insurance card field type."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardFieldType/cardNumber":{"kind":"symbol","abstract":[{"text":"Field 8: card number","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardNumber","kind":"identifier"}],"role":"symbol","title":"SBSDKHealthInsuranceCardFieldType.cardNumber","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardfieldtype\/cardnumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardFieldType\/cardNumber","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardFieldTypeCardNumber","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKHealthInsuranceCardFieldTypeCardNumber","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldTypeCardNumber","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeCardNumber"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKHealthInsuranceCardFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/title","op":"replace"},{"value":[{"text":"SBSDKHealthInsuranceCardFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType\/navigatorTitle","op":"replace"},{"value":"SBSDKHealthInsuranceCardFieldTypeCardNumber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1cardNumber\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardFieldTypeCardNumber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardFieldType~1cardNumber\/fragments","op":"replace"}]}]}