{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgessUpdateHandler","interfaceLanguage":"swift"},"abstract":[{"text":"A closure typealias used on informing observers about progress updating.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgessUpdateHandler","kind":"identifier"},{"text":" = (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier"},{"text":") -> ()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"progress","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The progress object that called the update handler."}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprogessupdatehandler"]}],"metadata":{"roleHeading":"Type Alias","role":"symbol","title":"SBSDKProgessUpdateHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgessUpdateHandler","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"SBSDKProgessUpdateHandler","kind":"identifier"}],"symbolKind":"typealias","externalID":"s:25ScanbotDocumentScannerSDK25SBSDKProgessUpdateHandlera"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress":{"type":"topic","title":"SBSDKProgress","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgessUpdateHandler":{"title":"SBSDKProgessUpdateHandler","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgessUpdateHandler","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogessupdatehandler","navigatorTitle":[{"text":"SBSDKProgessUpdateHandler","kind":"identifier"}],"abstract":[{"text":"A closure typealias used on informing observers about progress updating.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgessUpdateHandler","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/title","op":"replace","value":"SBSDKProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/fragments","op":"replace","value":[{"text":"SBSDKProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}