{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer\/recognize(from:orientation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer\/recognize(from:orientation:)"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizer(im)recognizeFromSampleBuffer:orientation:","symbolKind":"method","navigatorTitle":[{"text":"recognizeFromSampleBuffer:orientation:","kind":"identifier"}],"platforms":[],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"title":"recognize(from:orientation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKVideoOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer\/recognize(from:orientation:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(recognizeFromSampleBuffer:orientation:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sampleBuffer"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier","text":"CMSampleBuffer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","text":"SBSDKVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"sampleBuffer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sample buffer to recognize from."}]}]},{"name":"orientation","content":[{"inlineContent":[{"type":"text","text":"The orientation of the sample buffer."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The recognition result."}]}],"kind":"content"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using SBSDKDocumentDataExtractor."}]}],"abstract":[{"type":"text","text":"Recognizes european health insurance cards on a "},{"type":"codeVoice","code":"CMSampleBuffer"},{"text":".","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation":{"type":"topic","title":"SBSDKVideoOrientation","abstract":[{"text":"An enum describing the orientation of a video frame.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizer/recognize(from:orientation:)":{"deprecated":true,"abstract":[{"type":"text","text":"Recognizes european health insurance cards on a "},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer\/recognize(from:orientation:)","type":"topic","title":"recognize(from:orientation:)","navigatorTitle":[{"kind":"identifier","text":"recognizeFromSampleBuffer:orientation:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation"},{"kind":"text","text":") -> "},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer\/recognize(from:orientation:)","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResult":{"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresult","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"}],"abstract":[{"type":"text","text":"The result of the health insurance card recognition."}],"type":"topic","role":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizer":{"title":"SBSDKHealthInsuranceCardRecognizer","kind":"symbol","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizer","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"A class to recognize health insurance cards, a.k.a. elektronische Gesundheitskarten (eGK) on various image sources.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizer"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"recognizeFromSampleBuffer:orientation:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"recognizeFromSampleBuffer:orientation:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"text":" *) ","kind":"text"},{"text":"recognizeFromSampleBuffer:","kind":"identifier"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sampleBuffer"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","kind":"typeIdentifier","text":"SBSDKVideoOrientation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"orientation"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"sampleBuffer","content":[{"type":"paragraph","inlineContent":[{"text":"The sample buffer to recognize from.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The orientation of the sample buffer."}],"type":"paragraph"}],"name":"orientation"}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The recognition result."}]}]},"op":"replace"},{"value":"SBSDKVideoOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/navigatorTitle"},{"op":"replace","value":"recognizeFromSampleBuffer:orientation:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer~1recognize(from:orientation:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer~1recognize(from:orientation:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeFromSampleBuffer:orientation:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/title","op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/fragments","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/title","value":"SBSDKHealthInsuranceCardRecognizer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardRecognizer","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKHealthInsuranceCardRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/navigatorTitle"}]}]}