{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/speed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/speed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/speed","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritizationSpeed","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization@SBSDKCapturePhotoQualityPrioritizationSpeed","role":"symbol","title":"SBSDKCapturePhotoQualityPrioritization.speed","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"speed"}]},"abstract":[{"text":"Captures a still image at the highest possible speed. The quality of the image may be degraded.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speed"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/speed":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speed"}],"abstract":[{"text":"Captures a still image at the highest possible speed. The quality of the image may be degraded.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationSpeed"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/speed","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/speed","title":"SBSDKCapturePhotoQualityPrioritization.speed"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization","abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."}],"kind":"symbol","role":"symbol","title":"SBSDKCapturePhotoQualityPrioritization","navigatorTitle":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKCapturePhotoQualityPrioritizationSpeed","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationSpeed"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKCapturePhotoQualityPrioritizationSpeed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKCapturePhotoQualityPrioritizationSpeed","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1speed\/title"},{"value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritizationSpeed"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1speed\/fragments"},{"value":"SBSDKCapturePhotoQualityPrioritization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/title"},{"value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCapturePhotoQualityPrioritization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/navigatorTitle"}]}]}