{"metadata":{"platforms":[],"navigatorTitle":[{"text":"copyCurrentConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizer(im)copyCurrentConfiguration","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"symbolKind":"method","title":"copyCurrentConfiguration()","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"Returns a copy of the receivers current configuration.","type":"text"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Please consider using SBSDKDocumentDataExtractor.","type":"text"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer\/copyCurrentConfiguration()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyCurrentConfiguration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The current configuration."}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer\/copycurrentconfiguration()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer\/copycurrentconfiguration()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizer/copyCurrentConfiguration()":{"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer\/copycurrentconfiguration()","navigatorTitle":[{"text":"copyCurrentConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","title":"copyCurrentConfiguration()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer\/copyCurrentConfiguration()","kind":"symbol","abstract":[{"text":"Returns a copy of the receivers current configuration.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizer":{"type":"topic","title":"SBSDKHealthInsuranceCardRecognizer","role":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizer","navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizer","kind":"identifier"}],"abstract":[{"text":"A class to recognize health insurance cards, a.k.a. elektronische Gesundheitskarten (eGK) on various image sources.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for the European health insurance card (EHIC) recognizer."}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"role":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"copyCurrentConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyCurrentConfiguration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The current configuration.","type":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer~1copyCurrentConfiguration()\/title","value":"copyCurrentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer~1copyCurrentConfiguration()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyCurrentConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/title","op":"replace","value":"SBSDKHealthInsuranceCardRecognizer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/fragments","op":"replace","value":[{"text":"SBSDKHealthInsuranceCardRecognizer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardRecognizer"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/title","op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}]}]}]}