{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/sbsdkdocumentscannerviewcontrollerdelegate-implementations"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/sbsdkdocumentscannerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/SBSDKDocumentScannerViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"title":"SBSDKDocumentScannerViewControllerDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}]},"kind":"article","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:configureScanningStatusLabel:forScanningResult:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewControllerDidFailSnappingImage(_:withError:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewControllerWillSnapImage(_:)"],"generated":true,"anchor":"Instance-Methods"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/documentScannerViewController(_:configureScanningStatusLabel:forScanningResult:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"text":"configureScanningStatusLabel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDetectionStatusLabel","text":"SBSDKDetectionStatusLabel"},{"kind":"text","text":", "},{"text":"forScanningResult","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:configureScanningStatusLabel:forScanningResult:)","title":"documentScannerViewController(_:configureScanningStatusLabel:forScanningResult:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:configurescanningstatuslabel:forscanningresult:)","navigatorTitle":[{"text":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:","kind":"identifier"}],"abstract":[{"text":"Optional.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Lets you configure the document scanning status label, depending on the document detection status."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)":{"role":"symbol","navigatorTitle":[{"text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSnapDocumentImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectionResult"},{"kind":"text","text":"?, "},{"text":"autoSnapped","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Informs the delegate that the document scanner scanned and captured a document and provides the original image, the cropped document image"},{"type":"text","text":" "},{"type":"text","text":"and the result of the scanning."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","title":"documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontroller(_:didsnapdocumentimage:on:with:autosnapped:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/documentScannerViewControllerWillSnapImage(_:)":{"title":"documentScannerViewControllerWillSnapImage(_:)","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontrollerwillsnapimage(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewControllerWillSnapImage(_:)","kind":"symbol","abstract":[{"type":"text","text":"Optional."},{"type":"text","text":" "},{"type":"text","text":"Informs the delegate that the document scanner controller is going to capture an image."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentScannerViewControllerWillSnapImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentScannerViewControllerWillSnapImage:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller","deprecated":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"kind":"symbol","title":"SBSDKUIDocumentScannerViewController","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentScannerViewController/documentScannerViewControllerDidFailSnappingImage(_:withError:)":{"abstract":[{"type":"text","text":"Optional."},{"type":"text","text":" "},{"text":"Informs the delegate that snapping an image failed.","type":"text"}],"title":"documentScannerViewControllerDidFailSnappingImage(_:withError:)","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentscannerviewcontroller\/documentscannerviewcontrollerdidfailsnappingimage(_:witherror:)","navigatorTitle":[{"kind":"identifier","text":"documentScannerViewControllerDidFailSnappingImage:withError:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentScannerViewControllerDidFailSnappingImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"withError","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewControllerDidFailSnappingImage(_:withError:)","type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:configureScanningStatusLabel:forScanningResult:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewControllerDidFailSnappingImage(_:withError:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentScannerViewController\/documentScannerViewControllerWillSnapImage(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:configureScanningStatusLabel:forScanningResult:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:configureScanningStatusLabel:forScanningResult:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:configureScanningStatusLabel:forScanningResult:","kind":"identifier"}]},{"value":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentScannerViewController:didSnapDocumentImage:onImage:withResult:autoSnapped:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewController(_:didSnapDocumentImage:on:with:autoSnapped:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewControllerWillSnapImage(_:)\/title","value":"documentScannerViewControllerWillSnapImage:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewControllerWillSnapImage(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentScannerViewControllerWillSnapImage:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/title","value":"SBSDKUIDocumentScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewControllerDidFailSnappingImage(_:withError:)\/title","value":"documentScannerViewControllerDidFailSnappingImage:withError:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentScannerViewController~1documentScannerViewControllerDidFailSnappingImage(_:withError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewControllerDidFailSnappingImage:withError:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}