{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanner\/copycurrentconfiguration()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscanner\/copycurrentconfiguration()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScanner(im)copyCurrentConfiguration","title":"copyCurrentConfiguration()","navigatorTitle":[{"text":"copyCurrentConfiguration","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKCheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","text":"SBSDKCheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"A copy of configuration that was used to create this instance."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner\/copyCurrentConfiguration()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a copy of the current configuration value. Changes to the copy will not affect the original instance."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration","abstract":[{"text":"Configuration of the check scanner.","type":"text"}],"title":"SBSDKCheckScannerConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanner":{"navigatorTitle":[{"text":"SBSDKCheckScanner","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscanner","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner","role":"symbol","title":"SBSDKCheckScanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCheckScanner","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"API for check scanning.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScanner/copyCurrentConfiguration()":{"navigatorTitle":[{"kind":"identifier","text":"copyCurrentConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscanner\/copycurrentconfiguration()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScanner\/copyCurrentConfiguration()","role":"symbol","title":"copyCurrentConfiguration()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyCurrentConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","text":"SBSDKCheckScannerConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a copy of the current configuration value. Changes to the copy will not affect the original instance."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"copyCurrentConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration","text":"SBSDKCheckScannerConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A copy of configuration that was used to create this instance."}],"type":"paragraph"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKCheckScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKCheckScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/title"},{"op":"replace","value":[{"text":"SBSDKCheckScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner\/navigatorTitle"},{"op":"replace","value":"copyCurrentConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner~1copyCurrentConfiguration()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"copyCurrentConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScanner~1copyCurrentConfiguration()\/fragments"}]}]}