{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/init(feature:device:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/init(feature:device:)"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/init(feature:device:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature"},{"kind":"text","text":", "},{"text":"device","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraDevice"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The feature you want to use the camera for.","type":"text"}]}],"name":"feature"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The camera device to be used."}]}],"name":"device"}],"kind":"parameters"}],"abstract":[{"text":"Convenience initializer of the class. Does not start the capture session.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession(im)initWithFeature:device:","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature","text":"SBSDKFeature","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"device","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraDevice","text":"SBSDKCameraDevice","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithFeature:device:","kind":"identifier"}],"symbolKind":"init","title":"init(feature:device:)","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Initializer"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession":{"navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"type":"topic","title":"SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCameraSession","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession/init(feature:device:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession\/init(feature:device:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession\/init(feature:device:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"feature","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKFeature","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature"},{"kind":"text","text":", "},{"text":"device","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKCameraDevice","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraDevice"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithFeature:device:","kind":"identifier"}],"type":"topic","title":"init(feature:device:)","abstract":[{"text":"Convenience initializer of the class. Does not start the capture session.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFeature"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}],"abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature","kind":"symbol","title":"SBSDKFeature","role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraDevice":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraDevice"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcameradevice","abstract":[{"type":"text","text":"The camera device to be used with a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraDevice","kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraDevice","kind":"identifier"}],"title":"SBSDKCameraDevice","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithFeature:device:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFeature:device:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithFeature:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature","kind":"typeIdentifier","text":"SBSDKFeature","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature"},{"kind":"text","text":") "},{"kind":"internalParam","text":"feature"},{"text":" ","kind":"text"},{"text":"device:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraDevice","text":"SBSDKCameraDevice","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"device"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The feature you want to use the camera for."}],"type":"paragraph"}],"name":"feature"},{"name":"device","content":[{"inlineContent":[{"type":"text","text":"The camera device to be used."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":"SBSDKCameraSession","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/fragments","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/navigatorTitle"},{"value":"initWithFeature:device:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1init(feature:device:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession~1init(feature:device:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFeature:device:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/title","value":"SBSDKFeature","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/fragments","value":[{"text":"SBSDKFeature","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraDevice\/title","value":"SBSDKCameraDevice"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraDevice\/fragments","op":"replace","value":[{"text":"SBSDKCameraDevice","kind":"identifier"}]},{"value":[{"text":"SBSDKCameraDevice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraDevice\/navigatorTitle"}]}]}