{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformataustraliapostconfiguration\/australiapostcustomerformat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformataustraliapostconfiguration\/australiapostcustomerformat"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat"}],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is ALPHA_NUMERIC"}]}],"kind":"content"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration"]]},"metadata":{"title":"australiaPostCustomerFormat","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatAustraliaPostConfiguration(py)australiaPostCustomerFormat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAustraliaPostCustomerFormat","text":"SBSDKAustraliaPostCustomerFormat"}],"role":"symbol"},"abstract":[{"text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration\/australiaPostCustomerFormat"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatAustraliaPostConfiguration/australiaPostCustomerFormat":{"title":"australiaPostCustomerFormat","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformataustraliapostconfiguration\/australiapostcustomerformat","navigatorTitle":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration\/australiaPostCustomerFormat","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKAustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAustraliaPostCustomerFormat"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatAustraliaPostConfiguration":{"title":"SBSDKBarcodeFormatAustraliaPostConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformataustraliapostconfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatAustraliaPostConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatAustraliaPostConfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Australia Post barcode configuration. Add to scanner configuration to scan Australia Post barcodes."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatAustraliaPostConfiguration"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAustraliaPostCustomerFormat":{"abstract":[{"text":"Can be either numeric or alphanumeric and is only relevant for Format Codes 59 and 62.","type":"text"}],"kind":"symbol","title":"SBSDKAustraliaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAustraliaPostCustomerFormat","navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaustraliapostcustomerformat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"australiaPostCustomerFormat","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"australiaPostCustomerFormat"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKAustraliaPostCustomerFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKAustraliaPostCustomerFormat","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"australiaPostCustomerFormat","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration~1australiaPostCustomerFormat\/title","value":"australiaPostCustomerFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration~1australiaPostCustomerFormat\/fragments","value":[{"text":"australiaPostCustomerFormat","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/title","value":"SBSDKBarcodeFormatAustraliaPostConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatAustraliaPostConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatAustraliaPostConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatAustraliaPostConfiguration"}]},{"op":"replace","value":"SBSDKAustraliaPostCustomerFormat","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAustraliaPostCustomerFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAustraliaPostCustomerFormat\/fragments","value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAustraliaPostCustomerFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}