{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inspectSmallText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is false"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/inspectsmalltext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/inspectsmalltext"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Inspect small text (typically less than 12 pixels height) when analyzing the document quality."},{"type":"text","text":" "},{"type":"text","text":"If true, processing will be slower, but when the quality issue with a document is the low resolution of the"},{"type":"text","text":" "},{"type":"text","text":"text,"},{"type":"text","text":" "},{"type":"text","text":"then the issue will be caught."}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inspectSmallText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"inspectSmallText"}],"role":"symbol","title":"inspectSmallText","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration(py)inspectSmallText"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/inspectSmallText","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Document Quality Analyzer configuration."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"title":"SBSDKDocumentQualityAnalyzerConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/inspectSmallText":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inspectSmallText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/inspectSmallText","kind":"symbol","role":"symbol","abstract":[{"text":"Inspect small text (typically less than 12 pixels height) when analyzing the document quality.","type":"text"},{"text":" ","type":"text"},{"text":"If true, processing will be slower, but when the quality issue with a document is the low resolution of the","type":"text"},{"text":" ","type":"text"},{"text":"text,","type":"text"},{"text":" ","type":"text"},{"text":"then the issue will be caught.","type":"text"}],"navigatorTitle":[{"text":"inspectSmallText","kind":"identifier"}],"title":"inspectSmallText","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/inspectsmalltext"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"inspectSmallText","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"inspectSmallText","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"inspectSmallText","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKDocumentQualityAnalyzerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle","op":"replace"},{"value":"inspectSmallText","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1inspectSmallText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"inspectSmallText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration~1inspectSmallText\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}