{"sections":[],"metadata":{"title":"removeObserver(_:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeObserver"},{"kind":"text","text":"("},{"text":"SBSDKScannedPageObserver","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedPageObserver","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage(im)removeObserver:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol"},"abstract":[{"text":"Removes an observer from the receiver.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeObserver"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageObserver","kind":"typeIdentifier","text":"SBSDKScannedPageObserver","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedPageObserver"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The observer that wants to stop receiving delegate calls."}]}],"name":"observer"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpage\/removeobserver(_:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpage\/removeobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/removeObserver(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPage","kind":"identifier"}],"title":"SBSDKScannedPage","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A scanned page ("},{"code":"SBSDKScannedPage","type":"codeVoice"},{"type":"text","text":") is a representation of a scanned documents page in digital form."},{"type":"text","text":" "},{"type":"text","text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageObserver":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPageObserver","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpageobserver","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A delegation-like protocol for observing changes on an instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","isActive":true},{"text":".","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKScannedPageObserver","kind":"identifier"}],"title":"SBSDKScannedPageObserver","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageObserver"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage/removeObserver(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Removes an observer from the receiver."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeObserver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedPageObserver","text":"SBSDKScannedPageObserver"},{"text":")","kind":"text"}],"title":"removeObserver(_:)","navigatorTitle":[{"text":"removeObserver:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage\/removeObserver(_:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage\/removeobserver(_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"removeObserver:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeObserver:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"removeObserver:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<SBSDKScannedPageObserver>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKScannedPageObserver","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"observer","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The observer that wants to stop receiving delegate calls.","type":"text"}],"type":"paragraph"}],"name":"observer"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SBSDKScannedPage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/title"},{"value":[{"kind":"identifier","text":"SBSDKScannedPage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKScannedPage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/navigatorTitle"},{"op":"replace","value":"SBSDKScannedPageObserver","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageObserver\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageObserver\/fragments","value":[{"text":"SBSDKScannedPageObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageObserver\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKScannedPageObserver"}],"op":"replace"},{"value":"removeObserver:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1removeObserver(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage~1removeObserver(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeObserver:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}