{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/document"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/document"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","abstract":[{"text":"The fully processed, rotated, cropped and filtered image.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType"]]},"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKScannedPageImageType@SBSDKScannedPageImageTypeDocument","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKScannedPageImageTypeDocument","kind":"identifier"}],"title":"SBSDKScannedPageImageType.document","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType","title":"SBSDKScannedPageImageType","url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"role":"symbol","abstract":[{"type":"text","text":"An enum representing the different types of images a scanned page has."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType/document":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/document","title":"SBSDKScannedPageImageType.document","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKScannedPageImageTypeDocument","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/document","abstract":[{"text":"The fully processed, rotated, cropped and filtered image.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKScannedPageImageTypeDocument","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKScannedPageImageTypeDocument","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKScannedPageImageTypeDocument","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKScannedPageImageType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/title","op":"replace"},{"value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/fragments","op":"replace"},{"value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/navigatorTitle","op":"replace"},{"value":"SBSDKScannedPageImageTypeDocument","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType~1document\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKScannedPageImageTypeDocument"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType~1document\/fragments","op":"replace"}]}]}