{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/equatable-implementations"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/!=(_:_:)"],"anchor":"Operators","generated":true,"title":"Operators"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType","title":"SBSDKScannedPageImageType","url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"role":"symbol","abstract":[{"type":"text","text":"An enum representing the different types of images a scanned page has."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType/!=(_:_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype\/!=(_:_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKScannedPageImageType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/title"},{"value":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/fragments"},{"value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/navigatorTitle"}]}]}