{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization\/disabled","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}]}]}],"metadata":{"symbolKind":"case","title":"SBSDKBinarization.disabled","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKBinarization@SBSDKBinarizationDisabled","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationDisabled"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"Do not binarize the image. Image will be stored as a grayscale or color TIFF.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbinarization\/disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbinarization\/disabled"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarization":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBinarization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarization"}],"title":"SBSDKBinarization","abstract":[{"text":"Binarization behavior to apply when adding pages to a TIFF.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbinarization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarization/disabled":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarization\/disabled","kind":"symbol","abstract":[{"text":"Do not binarize the image. Image will be stored as a grayscale or color TIFF.","type":"text"}],"title":"SBSDKBinarization.disabled","url":"\/documentation\/scanbotsdk\/sbsdkbinarization\/disabled","role":"symbol","navigatorTitle":[{"text":"SBSDKBinarizationDisabled","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"SBSDKBinarizationDisabled","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKBinarizationDisabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKBinarizationDisabled","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/title","value":"SBSDKBinarization"},{"value":[{"text":"SBSDKBinarization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBinarization"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization~1disabled\/title","op":"replace","value":"SBSDKBinarizationDisabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarization~1disabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBinarizationDisabled"}]}]}]}