{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:processbytileconfiguration:minrequiredorientationconfidence:returnqualityheatmap:"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithQualityThresholds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKDocumentQualityThreshold *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"qualityThresholds"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityIndices:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKDocumentQuality *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"qualityIndices","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detectOrientation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"detectOrientation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inspectSmallText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"inspectSmallText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maxImageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"maxImageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minEstimatedNumberOfSymbolsForDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minEstimatedNumberOfSymbolsForDocument","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"processByTileConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKProcessByTileConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProcessByTileConfiguration"},{"text":" *) ","kind":"text"},{"text":"processByTileConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minRequiredOrientationConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minRequiredOrientationConfidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnQualityHeatmap:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"returnQualityHeatmap","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","interfaceLanguage":"occ"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration(im)initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessByTileConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessbytileconfiguration","title":"SBSDKProcessByTileConfiguration","abstract":[{"text":"Configuration for processing image by tiles.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,","type":"text"},{"text":" ","type":"text"},{"text":"but prediction can be less accurate.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessByTileConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:":{"kind":"symbol","role":"symbol","type":"topic","title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:processByTileConfiguration:minRequiredOrientationConfidence:returnQualityHeatmap:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:processbytileconfiguration:minrequiredorientationconfidence:returnqualityheatmap:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration","navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration","title":"SBSDKDocumentQualityAnalyzerConfiguration","abstract":[{"text":"Document Quality Analyzer configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKProcessByTileConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentQualityAnalyzerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle"}]}]}