{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResultWordBox"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithWord:boundingRect:confidenceValue:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResultWordBox(im)initWithWord:boundingRect:confidenceValue:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithWord:boundingRect:confidenceValue:"}],"roleHeading":"Instance Method","role":"symbol","title":"initWithWord:boundingRect:confidenceValue:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithWord:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"word","kind":"internalParam"},{"kind":"text","text":" "},{"text":"boundingRect:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"boundingRect"},{"text":" ","kind":"text"},{"text":"confidenceValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"confidenceValue"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresultwordbox\/initwithword:boundingrect:confidencevalue:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResultWordBox\/initWithWord:boundingRect:confidenceValue:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResultWordBox/initWithWord:boundingRect:confidenceValue:":{"role":"symbol","navigatorTitle":[{"text":"initWithWord:boundingRect:confidenceValue:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithWord:boundingRect:confidenceValue:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresultwordbox\/initwithword:boundingrect:confidencevalue:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResultWordBox\/initWithWord:boundingRect:confidenceValue:","title":"initWithWord:boundingRect:confidenceValue:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResultWordBox":{"type":"topic","abstract":[{"text":"A class describing a recognized word, its bounding box and its text recognition confidence.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResultWordBox"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResultWordBox","title":"SBSDKGenericTextLineRecognizerResultWordBox","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresultwordbox","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerResultWordBox","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResultWordBox\/title","value":"SBSDKGenericTextLineRecognizerResultWordBox"},{"value":[{"text":"SBSDKGenericTextLineRecognizerResultWordBox","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResultWordBox\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResultWordBox\/navigatorTitle","value":[{"text":"SBSDKGenericTextLineRecognizerResultWordBox","kind":"identifier"}]}]}]}