{"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageSource(im)toJsonWithConfiguration:","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","roleHeading":"Instance Method","title":"toJson(configuration:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration"},{"kind":"text","text":" = SBSDKToJSONConfiguration()) -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagesource\/tojson(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagesource\/tojson(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSource\/toJson(configuration:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSource"]]},"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKToJSONConfiguration":{"title":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktojsonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration used to serialize an object to json."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageSource":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagesource","kind":"symbol","navigatorTitle":[{"text":"SBSDKImageSource","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Description of source from which the ImageRef was created."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSource","title":"SBSDKImageSource","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageSource/toJson(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSource\/toJson(configuration:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"title":"toJson(configuration:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagesource\/tojson(configuration:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"toJsonWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKToJSONConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKImageSource","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSource\/title"},{"value":[{"text":"SBSDKImageSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSource\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageSource"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSource\/navigatorTitle"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSource~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSource~1toJson(configuration:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}