{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/accessibilityinputlabels(_:)-17d6w"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"externalID":"s:7SwiftUI4ViewPAAE24accessibilityInputLabelsyAA15ModifiedContentVyxAA31AccessibilityAttachmentModifierVGSayAA4TextVGF::SYNTHESIZED::s:10ScanbotSDK33SBSDKUI2DocumentDataExtractorViewV","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"symbolKind":"method","roleHeading":"Instance Method","extendedModule":"SwiftUICore","title":"accessibilityInputLabels(_:)","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"14.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"14.0","name":"iPadOS"},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"11.0"},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"watchOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"7.0"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityInputLabels"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV","text":"Text"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/View-Implementations"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/accessibilityInputLabels(_:)-17d6w","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"View.accessibilityInputLabels(_:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityInputLabels"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inputLabels"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:7SwiftUI4TextV","kind":"typeIdentifier","text":"Text"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","kind":"typeIdentifier","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorViewController":{"title":"SBSDKUI2DocumentDataExtractorViewController","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to extract data from various documents."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorviewcontroller","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView":{"title":"SBSDKUI2DocumentDataExtractorView","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorViewController","type":"reference"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorView","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView/View-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/View-Implementations","abstract":[],"kind":"article","role":"collectionGroup","title":"View Implementations","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorView/accessibilityInputLabels(_:)-17d6w":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorview\/accessibilityinputlabels(_:)-17d6w","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityInputLabels","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4TextV","text":"Text","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"ModifiedContent","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AccessibilityAttachmentModifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"kind":"text","text":">"}],"title":"accessibilityInputLabels(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorView\/accessibilityInputLabels(_:)-17d6w","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/title","value":"SBSDKUI2DocumentDataExtractorViewController"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorViewController\/navigatorTitle","op":"replace"}]}]}