{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizer\/acceptedCheckTypes"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizer"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"acceptedCheckTypes"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptedCheckTypes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType","text":"SBSDKCheckDocumentRootType"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"acceptedCheckTypes","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizer(py)acceptedCheckTypes"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizer\/acceptedchecktypes"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizer\/acceptedchecktypes"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptedCheckTypes","kind":"identifier"},{"kind":"text","text":": ["},{"text":"SBSDKCheckDocumentRootType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"An array of accepted check types. By default all check types are allowed."}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizer":{"navigatorTitle":[{"text":"SBSDKCheckRecognizer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizer","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizer","type":"topic","abstract":[{"type":"text","text":"A realtime detector and recognizer for bank checks."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckRecognizer"}],"kind":"symbol","title":"SBSDKCheckRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizer/acceptedCheckTypes":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptedCheckTypes","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCheckDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentRootType"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizer\/acceptedCheckTypes","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizer\/acceptedchecktypes","navigatorTitle":[{"kind":"identifier","text":"acceptedCheckTypes"}],"title":"acceptedCheckTypes","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An array of accepted check types. By default all check types are allowed."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentRootType":{"kind":"symbol","title":"SBSDKCheckDocumentRootType","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentRootType","abstract":[{"type":"text","text":"Root document type."}],"navigatorTitle":[{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentroottype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"acceptedCheckTypes"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"acceptedCheckTypes"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKCheckDocumentRootType *>"},{"kind":"text","text":" * "},{"text":"acceptedCheckTypes","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKCheckRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizer\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizer\/fragments","value":[{"text":"SBSDKCheckRecognizer","kind":"identifier"}],"op":"replace"},{"value":"acceptedCheckTypes","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizer~1acceptedCheckTypes\/title","op":"replace"},{"value":[{"text":"acceptedCheckTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizer~1acceptedCheckTypes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType\/title","value":"SBSDKCheckDocumentRootType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentRootType\/fragments","value":[{"text":"SBSDKCheckDocumentRootType","kind":"identifier"}],"op":"replace"}]}]}