{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(recognizeOnImage:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recognize"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":") -> "},{"text":"SBSDKCheckRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The input image."}],"type":"paragraph"}],"name":"image"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"An "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult"},{"text":" object containing the field data or nil if detection or recognition failed.","type":"text"}],"type":"paragraph"}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"This function is intended to use for detection on static images.","type":"text"}]}],"style":"important","name":"Important"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizer\/recognize(on:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckrecognizer\/recognize(on:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizer"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizer\/recognize(on:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"recognizeOnImage:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizer(im)recognizeOnImage:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"recognize(on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCheckRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult"},{"text":"?","kind":"text"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Recognizes a check in the given image."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizer/recognize(on:)":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizer\/recognize(on:)","kind":"symbol","abstract":[{"type":"text","text":"Recognizes a check in the given image."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizer\/recognize(on:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"recognize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"SBSDKCheckRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"recognizeOnImage:","kind":"identifier"}],"title":"recognize(on:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizer":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizer","kind":"symbol","abstract":[{"text":"A realtime detector and recognizer for bank checks.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizer","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckRecognizer"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizer"}],"title":"SBSDKCheckRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckRecognizerResult":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckrecognizerresult","kind":"symbol","abstract":[{"type":"text","text":"The result object of a check recognition."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckRecognizerResult","kind":"identifier"}],"type":"topic","title":"SBSDKCheckRecognizerResult","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckRecognizerResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"recognizeOnImage:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeOnImage:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckRecognizerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckRecognizerResult","kind":"typeIdentifier","text":"SBSDKCheckRecognizerResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"recognizeOnImage:"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"recognizeOnImage:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizer~1recognize(on:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recognizeOnImage:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizer~1recognize(on:)\/fragments","op":"replace"},{"value":"SBSDKCheckRecognizer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizer\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizer\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizer"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerResult\/title","value":"SBSDKCheckRecognizerResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckRecognizerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckRecognizerResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}