{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","role":"symbol","title":"autoSnapProgress","navigatorTitle":[{"kind":"identifier","text":"autoSnapProgress"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnapProgress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PolygonStyle","kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration(py)autoSnapProgress"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentpolygonconfiguration\/autosnapprogress"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentpolygonconfiguration\/autosnapprogress"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoSnapProgress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PolygonStyle","kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentPolygonConfiguration"]]},"abstract":[{"type":"text","text":"Configuration of the animated polygon when the document is being scanned for capturing in ‘auto snapping mode’."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentPolygonConfiguration\/autoSnapProgress","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentPolygonConfiguration/autoSnapProgress":{"title":"autoSnapProgress","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentpolygonconfiguration\/autosnapprogress","type":"topic","abstract":[{"type":"text","text":"Configuration of the animated polygon when the document is being scanned for capturing in ‘auto snapping mode’."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoSnapProgress"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PolygonStyle"}],"navigatorTitle":[{"text":"autoSnapProgress","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentPolygonConfiguration\/autoSnapProgress"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentPolygonConfiguration":{"abstract":[{"type":"text","text":"Configuration of the document contour detection polygon."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentpolygonconfiguration","navigatorTitle":[{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}],"title":"SBSDKUI2DocumentPolygonConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentPolygonConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PolygonStyle":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2polygonstyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PolygonStyle","abstract":[{"text":"Configuration of the polygon appearance.","type":"text"}],"type":"topic","title":"SBSDKUI2PolygonStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"autoSnapProgress","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"autoSnapProgress"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PolygonStyle","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PolygonStyle","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"autoSnapProgress"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"autoSnapProgress","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentPolygonConfiguration~1autoSnapProgress\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentPolygonConfiguration~1autoSnapProgress\/fragments","value":[{"kind":"identifier","text":"autoSnapProgress"}],"op":"replace"},{"value":"SBSDKUI2DocumentPolygonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentPolygonConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentPolygonConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentPolygonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentPolygonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PolygonStyle\/title","op":"replace","value":"SBSDKUI2PolygonStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PolygonStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"op":"replace"},{"value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PolygonStyle\/navigatorTitle"}]}]}