{"kind":"symbol","metadata":{"title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatJapanPostConfiguration(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatJapanPostConfiguration"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatjapanpostconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration\/fromJsonWithJson:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatJapanPostConfiguration":{"title":"SBSDKBarcodeFormatJapanPostConfiguration","abstract":[{"text":"Japan Post barcode configuration. Add to scanner configuration to scan Japan Post barcodes.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatjapanpostconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatJapanPostConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatJapanPostConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatJapanPostConfiguration/fromJsonWithJson:":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatjapanpostconfiguration\/fromjsonwithjson:","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration\/fromJsonWithJson:","role":"symbol","title":"fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/title","value":"SBSDKBarcodeFormatJapanPostConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}