{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroductionScreenConfiguration(im)init","role":"symbol","title":"init()","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/init()"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration","abstract":[{"text":"Configuration of the introduction screen for the document scanner.","type":"text"}],"title":"SBSDKUI2IntroductionScreenConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration/init()":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"title":"init()","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration\/init()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/title","value":"SBSDKUI2IntroductionScreenConfiguration"},{"op":"replace","value":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}]},{"value":"init","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1init()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"}]}]}