{"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage(im)imageWithPageFileID:pageFileType:","modules":[{"name":"ScanbotSDK"}],"title":"image(withPageFileID:pageFileType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentPageFileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"imageWithPageFileID:pageFileType:"}],"role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/image(withPageFileID:pageFileType:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"text":"(","kind":"text"},{"text":"withPageFileID","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageFileType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The page file identifier of the requested image."}],"type":"paragraph"}],"name":"pageFileID"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page file type of the requested image."}]}],"name":"type"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"The requested image, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the image does not exist in the storage."}],"type":"paragraph"}]}],"abstract":[{"text":"Returns the image with the given page file identifier and page file type.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/image(withpagefileid:pagefiletype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/image(withpagefileid:pagefiletype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","kind":"symbol","title":"SBSDKDocumentPageFileType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype","role":"symbol","abstract":[{"text":"Enumeration of image type classifiers.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/image(withPageFileID:pageFileType:)":{"abstract":[{"type":"text","text":"Returns the image with the given page file identifier and page file type."}],"role":"symbol","title":"image(withPageFileID:pageFileType:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/image(withPageFileID:pageFileType:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"text":": ","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":", "},{"text":"pageFileType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"imageWithPageFileID:pageFileType:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/image(withpagefileid:pagefiletype:)","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"role":"symbol","title":"SBSDKDocumentPageFileStorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","abstract":[{"text":"A class to store and restore images of different types in a memory-efficient way.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"imageWithPageFileID:pageFileType:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"imageWithPageFileID:pageFileType:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"imageWithPageFileID:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSUUID","kind":"typeIdentifier","text":"NSUUID"},{"text":" *) ","kind":"text"},{"text":"pageFileID","kind":"internalParam"},{"kind":"text","text":" "},{"text":"pageFileType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The page file identifier of the requested image.","type":"text"}],"type":"paragraph"}],"name":"pageFileID"},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page file type of the requested image."}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The requested image, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the image does not exist in the storage."}]}],"kind":"content"}},{"op":"replace","value":"SBSDKDocumentPageFileType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/navigatorTitle","value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1image(withPageFileID:pageFileType:)\/title","value":"imageWithPageFileID:pageFileType:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageWithPageFileID:pageFileType:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1image(withPageFileID:pageFileType:)\/fragments"},{"op":"replace","value":"SBSDKDocumentPageFileStorage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}]},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}