{"sections":[],"abstract":[{"type":"text","text":"Returns the file URL of a screen-size preview of the image with the given page file identifier and page file type."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPageFileID","kind":"externalParam"},{"kind":"text","text":" "},{"text":"pageFileID","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentPageFileType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"pageFileID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page file identifier of the requested image."}]}]},{"content":[{"inlineContent":[{"text":"The page file type of the requested image.","type":"text"}],"type":"paragraph"}],"name":"type"}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the requested preview image, or "},{"type":"codeVoice","code":"nil"},{"text":" if the image does not exist in the storage.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/previewImageURL(withPageFileID:pageFileType:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/previewimageurl(withpagefileid:pagefiletype:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/previewimageurl(withpagefileid:pagefiletype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage"]]},"metadata":{"title":"previewImageURL(withPageFileID:pageFileType:)","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPageFileStorage(im)previewImageURLWithPageFileID:pageFileType:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPageFileID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"previewImageURLWithPageFileID:pageFileType:"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","kind":"symbol","title":"SBSDKDocumentPageFileType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefiletype","role":"symbol","abstract":[{"text":"Enumeration of image type classifiers.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage":{"role":"symbol","title":"SBSDKDocumentPageFileStorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileStorage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage","abstract":[{"text":"A class to store and restore images of different types in a memory-efficient way.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageFileStorage/previewImageURL(withPageFileID:pageFileType:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileStorage\/previewImageURL(withPageFileID:pageFileType:)","kind":"symbol","title":"previewImageURL(withPageFileID:pageFileType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewImageURL","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPageFileID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"text":", ","kind":"text"},{"text":"pageFileType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentPageFileType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"previewImageURLWithPageFileID:pageFileType:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpagefilestorage\/previewimageurl(withpagefileid:pagefiletype:)","role":"symbol","abstract":[{"text":"Returns the file URL of a screen-size preview of the image with the given page file identifier and page file type.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"previewImageURLWithPageFileID:pageFileType:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"previewImageURLWithPageFileID:pageFileType:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"previewImageURLWithPageFileID:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pageFileID"},{"text":" ","kind":"text"},{"text":"pageFileType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageFileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentPageFileType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"pageFileID","content":[{"type":"paragraph","inlineContent":[{"text":"The page file identifier of the requested image.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The page file type of the requested image."}],"type":"paragraph"}],"name":"type"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the requested preview image, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the image does not exist in the storage."}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/title","op":"replace","value":"SBSDKDocumentPageFileType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/fragments","value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/title","value":"SBSDKDocumentPageFileStorage","op":"replace"},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/fragments"},{"value":[{"text":"SBSDKDocumentPageFileStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1previewImageURL(withPageFileID:pageFileType:)\/title","op":"replace","value":"previewImageURLWithPageFileID:pageFileType:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"previewImageURLWithPageFileID:pageFileType:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageFileStorage~1previewImageURL(withPageFileID:pageFileType:)\/fragments"}]}]}