{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"Barcode containing a VIN was successfully extracted.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus"]]},"metadata":{"roleHeading":"Case","title":"SBSDKVINBarcodeExtractionStatus.success","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKVINBarcodeExtractionStatusSuccess","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKVINBarcodeExtractionStatus@SBSDKVINBarcodeExtractionStatusSuccess"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/success","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/success"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/success"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus/success":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus\/success","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusSuccess"}],"type":"topic","abstract":[{"type":"text","text":"Barcode containing a VIN was successfully extracted."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus\/success","title":"SBSDKVINBarcodeExtractionStatus.success"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINBarcodeExtractionStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINBarcodeExtractionStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvinbarcodeextractionstatus","navigatorTitle":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status of the barcode extraction."}],"type":"topic","role":"symbol","title":"SBSDKVINBarcodeExtractionStatus","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKVINBarcodeExtractionStatusSuccess","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVINBarcodeExtractionStatusSuccess"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKVINBarcodeExtractionStatusSuccess","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1success\/title","op":"replace","value":"SBSDKVINBarcodeExtractionStatusSuccess"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus~1success\/fragments","op":"replace","value":[{"text":"SBSDKVINBarcodeExtractionStatusSuccess","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/title","op":"replace","value":"SBSDKVINBarcodeExtractionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/fragments","op":"replace","value":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINBarcodeExtractionStatus\/navigatorTitle","op":"replace","value":[{"text":"SBSDKVINBarcodeExtractionStatus","kind":"identifier"}]}]}]}