{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarizationFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters\/binarizationFilter","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters(py)binarizationFilter","navigatorTitle":[{"text":"binarizationFilter","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binarizationFilter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"binarizationFilter"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters"]]},"sections":[],"abstract":[{"text":"Filter to apply to the input image when adding pages with binarization.","type":"text"},{"text":" ","type":"text"},{"text":"If set, the filter is applied to the input image and the resulting image is stored as a 1-bit TIFF.","type":"text"},{"text":" ","type":"text"},{"text":"When storing documents it’s typically best to use the BINARY_DOCUMENT_OPTIMIZED_COMPRESSION compression mode","type":"text"},{"text":" ","type":"text"},{"text":"(CCITT_T6)","type":"text"},{"text":" ","type":"text"},{"text":"instead of the default, as it tends to produce the smallest file sizes.","type":"text"},{"text":" ","type":"text"},{"text":"If not set, simple thresholding is applied to the image, instead.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters\/binarizationfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters\/binarizationfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGeneratorParameters/binarizationFilter":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters\/binarizationfilter","title":"binarizationFilter","navigatorTitle":[{"kind":"identifier","text":"binarizationFilter"}],"abstract":[{"text":"Filter to apply to the input image when adding pages with binarization.","type":"text"},{"text":" ","type":"text"},{"text":"If set, the filter is applied to the input image and the resulting image is stored as a 1-bit TIFF.","type":"text"},{"text":" ","type":"text"},{"text":"When storing documents it’s typically best to use the BINARY_DOCUMENT_OPTIMIZED_COMPRESSION compression mode","type":"text"},{"text":" ","type":"text"},{"text":"(CCITT_T6)","type":"text"},{"text":" ","type":"text"},{"text":"instead of the default, as it tends to produce the smallest file sizes.","type":"text"},{"text":" ","type":"text"},{"text":"If not set, simple thresholding is applied to the image, instead.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"binarizationFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","text":"SBSDKParametricFilter"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters\/binarizationFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"title":"SBSDKParametricFilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGeneratorParameters":{"title":"SBSDKTIFFGeneratorParameters","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters","role":"symbol","navigatorTitle":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"TIFF generator parameters.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"binarizationFilter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"binarizationFilter"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"text":" * ","kind":"text"},{"text":"binarizationFilter","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters~1binarizationFilter\/title","op":"replace","value":"binarizationFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters~1binarizationFilter\/fragments","op":"replace","value":[{"text":"binarizationFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/title","value":"SBSDKTIFFGeneratorParameters"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/fragments","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}]}]}]}