{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset","text":"SBSDKBinarizationFilterPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"denoise"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/init(preset:outputmode:denoise:radius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/init(preset:outputmode:denoise:radius:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/init(preset:outputMode:denoise:radius:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBinarizationFilterPreset","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"denoise"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(preset:outputMode:denoise:radius:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCustomBinarizationFilter(im)initWithPreset:outputMode:denoise:radius:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPreset:outputMode:denoise:radius:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOutputMode":{"role":"symbol","title":"SBSDKOutputMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOutputMode"}],"abstract":[{"type":"text","text":"Output mode of binarization filter."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKOutputMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkoutputmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBinarizationFilterPreset":{"role":"symbol","title":"SBSDKBinarizationFilterPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"abstract":[{"type":"text","text":"Preset of parameters for custom binarization filter."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"url":"\/documentation\/scanbotsdk\/sbsdkbinarizationfilterpreset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter/init(preset:outputMode:denoise:radius:)":{"role":"symbol","title":"init(preset:outputMode:denoise:radius:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBinarizationFilterPreset","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"denoise"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/init(preset:outputMode:denoise:radius:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPreset:outputMode:denoise:radius:"}],"url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/init(preset:outputmode:denoise:radius:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter":{"role":"symbol","title":"SBSDKCustomBinarizationFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPreset:outputMode:denoise:radius:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreset:outputMode:denoise:radius:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPreset:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBinarizationFilterPreset","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBinarizationFilterPreset","text":"SBSDKBinarizationFilterPreset"},{"kind":"text","text":") "},{"kind":"internalParam","text":"preset"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"outputMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"denoise:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"denoise"},{"kind":"text","text":" "},{"kind":"identifier","text":"radius:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"radius"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/title","value":"SBSDKOutputMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/fragments","value":[{"kind":"identifier","text":"SBSDKOutputMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/title","value":"SBSDKBinarizationFilterPreset"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBinarizationFilterPreset\/fragments","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter~1init(preset:outputMode:denoise:radius:)\/title","value":"initWithPreset:outputMode:denoise:radius:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter~1init(preset:outputMode:denoise:radius:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreset:outputMode:denoise:radius:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/title","value":"SBSDKCustomBinarizationFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}