{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputMode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/outputMode"},"abstract":[{"type":"text","text":"Output mode of the filter. BINARY will return a black and white image, GRAYSCALE will return an antialiased"},{"text":" ","type":"text"},{"type":"text","text":"grayscale image."},{"type":"text","text":" "},{"text":"Default is BINARY","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/outputmode"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/outputmode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outputMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode"}],"modules":[{"name":"ScanbotSDK"}],"title":"outputMode","roleHeading":"Instance Property","navigatorTitle":[{"text":"outputMode","kind":"identifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCustomBinarizationFilter(py)outputMode"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"type":"topic","title":"SBSDKCustomBinarizationFilter","abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCustomBinarizationFilter/outputMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCustomBinarizationFilter\/outputMode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"outputMode","kind":"identifier"}],"type":"topic","title":"outputMode","abstract":[{"type":"text","text":"Output mode of the filter. BINARY will return a black and white image, GRAYSCALE will return an antialiased"},{"type":"text","text":" "},{"type":"text","text":"grayscale image."},{"text":" ","type":"text"},{"type":"text","text":"Default is BINARY"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"outputMode"},{"text":": ","kind":"text"},{"text":"SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcustombinarizationfilter\/outputmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOutputMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","type":"topic","role":"symbol","title":"SBSDKOutputMode","url":"\/documentation\/scanbotsdk\/sbsdkoutputmode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOutputMode"}],"navigatorTitle":[{"text":"SBSDKOutputMode","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Output mode of binarization filter."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"outputMode","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"outputMode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOutputMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode"},{"kind":"text","text":" "},{"text":"outputMode","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/title","value":"SBSDKCustomBinarizationFilter","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter~1outputMode\/title","op":"replace","value":"outputMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCustomBinarizationFilter~1outputMode\/fragments","value":[{"text":"outputMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKOutputMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOutputMode\/fragments","value":[{"kind":"identifier","text":"SBSDKOutputMode"}]}]}]}