{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay","text":"SBSDKUI2ScanCompletionOverlay"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2scancompletionoverlay\/fromjsonwithjson:"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:","roleHeading":"Type Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanCompletionOverlay(cm)fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay\/fromJsonWithJson:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanCompletionOverlay/fromJsonWithJson:":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay\/fromJsonWithJson:","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2scancompletionoverlay\/fromjsonwithjson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanCompletionOverlay":{"abstract":[{"text":"Configuration of the overlay to be shown after the successful scan.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2scancompletionoverlay","title":"SBSDKUI2ScanCompletionOverlay","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanCompletionOverlay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/title","value":"SBSDKUI2ScanCompletionOverlay","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ScanCompletionOverlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanCompletionOverlay\/navigatorTitle","value":[{"text":"SBSDKUI2ScanCompletionOverlay","kind":"identifier"}],"op":"replace"}]}]}