{"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageref\/fromencodedbuffer(encodedbuffer:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageref\/fromencodedbuffer(encodedbuffer:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromEncodedBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"encodedBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBufferImageLoadOptions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions","text":"SBSDKBufferImageLoadOptions"},{"kind":"text","text":" = SBSDKBufferImageLoadOptions()) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef","text":"SBSDKImageRef"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Creates ImageRef from encoded buffer, e.g. from jpeg."}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"fromEncodedBufferWithEncodedBuffer:options:"}],"title":"fromEncodedBuffer(encodedBuffer:options:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromEncodedBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"encodedBuffer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBufferImageLoadOptions","kind":"typeIdentifier","text":"SBSDKBufferImageLoadOptions"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier","text":"SBSDKImageRef"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef(cm)fromEncodedBufferWithEncodedBuffer:options:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef\/fromEncodedBuffer(encodedBuffer:options:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRef":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef","title":"SBSDKImageRef","type":"topic","abstract":[{"type":"text","text":"Image ref class."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageref","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRef/fromEncodedBuffer(encodedBuffer:options:)":{"title":"fromEncodedBuffer(encodedBuffer:options:)","navigatorTitle":[{"text":"fromEncodedBufferWithEncodedBuffer:options:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Creates ImageRef from encoded buffer, e.g. from jpeg."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef\/fromEncodedBuffer(encodedBuffer:options:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageref\/fromencodedbuffer(encodedbuffer:options:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromEncodedBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"encodedBuffer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBufferImageLoadOptions","kind":"typeIdentifier","text":"SBSDKBufferImageLoadOptions"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef","kind":"typeIdentifier","text":"SBSDKImageRef"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBufferImageLoadOptions":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbufferimageloadoptions","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions","kind":"symbol","abstract":[{"text":"Options for loading image from buffer.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBufferImageLoadOptions","kind":"identifier"}],"title":"SBSDKBufferImageLoadOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"fromEncodedBufferWithEncodedBuffer:options:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"fromEncodedBufferWithEncodedBuffer:options:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef"},{"text":" *) ","kind":"text"},{"text":"fromEncodedBufferWithEncodedBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"encodedBuffer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBufferImageLoadOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBufferImageLoadOptions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBufferImageLoadOptions"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKImageRef","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageRef"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/navigatorTitle","op":"replace"},{"value":"fromEncodedBufferWithEncodedBuffer:options:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef~1fromEncodedBuffer(encodedBuffer:options:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"fromEncodedBufferWithEncodedBuffer:options:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef~1fromEncodedBuffer(encodedBuffer:options:)\/fragments","op":"replace"},{"value":"SBSDKBufferImageLoadOptions","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBufferImageLoadOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBufferImageLoadOptions\/navigatorTitle","op":"replace"}]}]}