{"sections":[],"metadata":{"navigatorTitle":[{"text":"releaseStrongReferenceWithUniqueId:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"releaseStrongReferenceWithUniqueId:","roleHeading":"Type Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRef(cm)releaseStrongReferenceWithUniqueId:","role":"symbol","symbolKind":"method","fragments":[{"text":"+ ","kind":"text"},{"text":"releaseStrongReferenceWithUniqueId:","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"releaseStrongReferenceWithUniqueId:"},{"kind":"text","text":"("},{"text":"NSUUID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUUID"},{"text":" *) ","kind":"text"},{"text":"uniqueId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageref\/releasestrongreferencewithuniqueid:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef\/releaseStrongReferenceWithUniqueId:","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRef/releaseStrongReferenceWithUniqueId:":{"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"releaseStrongReferenceWithUniqueId:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef\/releaseStrongReferenceWithUniqueId:","abstract":[],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageref\/releasestrongreferencewithuniqueid:","navigatorTitle":[{"text":"releaseStrongReferenceWithUniqueId:","kind":"identifier"}],"kind":"symbol","title":"releaseStrongReferenceWithUniqueId:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRef":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRef","title":"SBSDKImageRef","type":"topic","abstract":[{"type":"text","text":"Image ref class."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageref","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKImageRef","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageRef"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageRef"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRef\/navigatorTitle","op":"replace"}]}]}