{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignored","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentFieldValidationStatus"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentFieldValidationStatus\/ignored","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentFieldValidationStatus"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"ignored","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus(cpy)ignored","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignored"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus","text":"SBSDKGenericDocumentFieldValidationStatus"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"ignored"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"abstract":[{"type":"text","text":"The document contains a field of this type, but recognition for this field is disabled."},{"type":"text","text":" "},{"type":"text","text":"The value of this field is always empty, although the field may be non-empty in the document."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentfieldvalidationstatus\/ignored"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentfieldvalidationstatus\/ignored"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentFieldValidationStatus":{"abstract":[{"text":"Field validation status.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentfieldvalidationstatus","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentFieldValidationStatus","title":"SBSDKGenericDocumentFieldValidationStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentFieldValidationStatus/ignored":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignored","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentfieldvalidationstatus\/ignored","abstract":[{"text":"The document contains a field of this type, but recognition for this field is disabled.","type":"text"},{"text":" ","type":"text"},{"text":"The value of this field is always empty, although the field may be non-empty in the document.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentFieldValidationStatus\/ignored","navigatorTitle":[{"text":"ignored","kind":"identifier"}],"kind":"symbol","title":"ignored"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"ignored"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ignored"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKGenericDocumentFieldValidationStatus","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentFieldValidationStatus","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentFieldValidationStatus"},{"text":" * ","kind":"text"},{"text":"ignored","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentFieldValidationStatus\/title","value":"SBSDKGenericDocumentFieldValidationStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentFieldValidationStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentFieldValidationStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentFieldValidationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentFieldValidationStatus~1ignored\/title","value":"ignored"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentFieldValidationStatus~1ignored\/fragments","value":[{"text":"ignored","kind":"identifier"}]}]}]}