{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseinfo\/initwithstatus:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:devices:nextonlinelicensecheckinms:devicederegistationerrors:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicenseInfo(im)initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isValid:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isValid","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"licenseStatusMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"licenseStatusMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expirationTimestamp:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"expirationTimestamp","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expirationDateString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"expirationDateString","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"errorMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"errorMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"onlineLicenseCheckInProgress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onlineLicenseCheckInProgress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"license:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"license","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"devices:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"devices","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nextOnlineLicenseCheckInMs:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"nextOnlineLicenseCheckInMs"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceDeregistationErrors:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKDeviceDeregistrationError *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceDeregistationErrors"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Information about the SDK license."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKLicenseInfo","kind":"identifier"}],"title":"SBSDKLicenseInfo","url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseInfo/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdklicenseinfo\/initwithstatus:isvalid:licensestatusmessage:expirationtimestamp:expirationdatestring:errormessage:onlinelicensecheckinprogress:license:devices:nextonlinelicensecheckinms:devicederegistationerrors:","title":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseInfo\/initWithStatus:isValid:licenseStatusMessage:expirationTimestamp:expirationDateString:errorMessage:onlineLicenseCheckInProgress:license:devices:nextOnlineLicenseCheckInMs:deviceDeregistationErrors:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Status of the license plate scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"title":"SBSDKLicenseStatus","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/title","value":"SBSDKLicenseInfo"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/fragments","value":[{"kind":"identifier","text":"SBSDKLicenseInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseInfo\/navigatorTitle","value":[{"text":"SBSDKLicenseInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title","value":"SBSDKLicenseStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/navigatorTitle","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}]}]}]}