{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/supportedInterfaceOrientations"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask","text":"UIInterfaceOrientationMask"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportedInterfaceOrientations"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/supportedinterfaceorientations"]}],"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerViewController(py)supportedInterfaceOrientations","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"title":"supportedInterfaceOrientations","roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController":{"navigatorTitle":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based view controller to scan vehicle license plates in realtime.","type":"text"}],"role":"symbol","title":"SBSDKUILicensePlateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerViewController/supportedInterfaceOrientations":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerViewController\/supportedInterfaceOrientations","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerviewcontroller\/supportedinterfaceorientations","role":"symbol","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"type":"topic","title":"supportedInterfaceOrientations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/title","value":"SBSDKUILicensePlateScannerViewController","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/fragments"},{"value":[{"text":"SBSDKUILicensePlateScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerViewController\/navigatorTitle","op":"replace"}]}]}