{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:finderviewuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintro-2e7e7"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}],"symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenTextLocalization(im)initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithTopBarTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"topBarTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"topBarCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"topBarCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"topUserGuidance:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"topUserGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"finderViewUserGuidance:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"finderViewUserGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"introScreenTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"introScreenTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"introScreenDoneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"introScreenDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"introScreenText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"introScreenText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionOverlaySuccessMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"completionOverlaySuccessMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlashButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlashButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionZoomButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionZoomButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenTextLocalization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization","navigatorTitle":[{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the all strings for MRZ scanner screen.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization","title":"SBSDKUI2MRZScannerScreenTextLocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenTextLocalization/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:finderviewuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintro-2e7e7","kind":"symbol","title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","abstract":[],"navigatorTitle":[{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/title","value":"SBSDKUI2MRZScannerScreenTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2MRZScannerScreenTextLocalization","kind":"identifier"}],"op":"replace"}]}]}