{"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration(cm)tesseractWithLanguageString:","title":"tesseract(withLanguageString:)","role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tesseract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLanguageString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","kind":"typeIdentifier"}],"symbolKind":"method","navigatorTitle":[{"text":"tesseractWithLanguageString:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/tesseract(withLanguageString:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/tesseract(withlanguagestring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/tesseract(withlanguagestring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Creates an OCR configuration using the mode ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/tesseract","isActive":true,"type":"reference"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLanguageString"},{"kind":"text","text":" "},{"kind":"internalParam","text":"languageString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","text":"SBSDKOCREngineConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"A string with two-character-language strings, separated by a plus or comma sign, for example “de+en”.","type":"text"}],"type":"paragraph"}],"name":"languageString"}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The new OCR configuration object."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","kind":"symbol","title":"SBSDKOCREngineConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"A class describing the configuration of the optical character recognizer (OCR) engine."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineConfiguration/tesseract(withLanguageString:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration\/tesseract(withLanguageString:)","abstract":[{"text":"Creates an OCR configuration using the mode ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/tesseract","type":"reference","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrengineconfiguration\/tesseract(withlanguagestring:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tesseractWithLanguageString:"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLanguageString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","text":"SBSDKOCREngineConfiguration"}],"title":"tesseract(withLanguageString:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode/tesseract":{"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode\/tesseract","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineModeTesseract"}],"abstract":[{"text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages.","type":"text"}],"title":"SBSDKOCREngineMode.tesseract","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/tesseract","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"tesseractWithLanguageString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"tesseractWithLanguageString:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineConfiguration","text":"SBSDKOCREngineConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOCREngineConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tesseractWithLanguageString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"languageString","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"A string with two-character-language strings, separated by a plus or comma sign, for example “de+en”.","type":"text"}],"type":"paragraph"}],"name":"languageString"}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The new OCR configuration object."}]}],"kind":"content"}},{"op":"replace","value":"SBSDKOCREngineConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOCREngineConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKOCREngineConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration\/navigatorTitle"},{"op":"replace","value":"tesseractWithLanguageString:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1tesseract(withLanguageString:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"tesseractWithLanguageString:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineConfiguration~1tesseract(withLanguageString:)\/fragments"},{"op":"replace","value":"SBSDKOCREngineModeTesseract","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1tesseract\/title"},{"op":"replace","value":[{"text":"SBSDKOCREngineModeTesseract","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1tesseract\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}