{"abstract":[{"type":"text","text":"Configuration of the dialog for requesting camera permissions."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/camerapermission"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/camerapermission"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"cameraPermission","roleHeading":"Instance Property","navigatorTitle":[{"text":"cameraPermission","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenConfiguration(py)cameraPermission","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cameraPermission","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier"}]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/cameraPermission","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraPermission","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","navigatorTitle":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"type":"topic","title":"SBSDKUI2CameraPermissionScreen","kind":"symbol","abstract":[{"text":"Configuration of the camera permission request view.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration":{"title":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the screen for extracting data from ID documents."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration/cameraPermission":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/camerapermission","navigatorTitle":[{"kind":"identifier","text":"cameraPermission"}],"abstract":[{"text":"Configuration of the dialog for requesting camera permissions.","type":"text"}],"title":"cameraPermission","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/cameraPermission","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPermission"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"cameraPermission"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cameraPermission","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cameraPermission"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2CameraPermissionScreen","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/title","value":"SBSDKUI2DocumentDataExtractorScreenConfiguration"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/navigatorTitle"},{"op":"replace","value":"cameraPermission","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1cameraPermission\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1cameraPermission\/fragments","op":"replace","value":[{"text":"cameraPermission","kind":"identifier"}]}]}]}