{"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"viewWillTransitionToSize:withTransitionCoordinator:","fragments":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerViewController(im)viewWillTransitionToSize:withTransitionCoordinator:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller\/viewwilltransitiontosize:withtransitioncoordinator:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController\/viewWillTransitionToSize:withTransitionCoordinator:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewWillTransitionToSize:"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withTransitionCoordinator:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UIViewControllerTransitionCoordinator>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"coordinator"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewController/viewWillTransitionToSize:withTransitionCoordinator:":{"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller\/viewwilltransitiontosize:withtransitioncoordinator:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController\/viewWillTransitionToSize:withTransitionCoordinator:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"type":"topic","title":"viewWillTransitionToSize:withTransitionCoordinator:","navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewController":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController","abstract":[{"text":"A view controller for camera-based detection of health insurance cards.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"type":"topic","role":"symbol","deprecated":true,"title":"SBSDKUIHealthInsuranceCardRecognizerViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/title","op":"replace","value":"SBSDKUIHealthInsuranceCardRecognizerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/navigatorTitle","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"op":"replace"}]}]}