{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizerShouldBegin(_:)"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController\/UIGestureRecognizerDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"extendedModule":"ScanbotDocumentScannerSDK","title":"gestureRecognizerShouldBegin(_:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizerShouldBegin:"}],"externalID":"c:@CM@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerController(im)gestureRecognizerShouldBegin:","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController\/gestureRecognizerShouldBegin(_:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercontroller\/gesturerecognizershouldbegin(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercontroller\/gesturerecognizershouldbegin(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController","title":"SBSDKUI2DocumentScannerController","abstract":[{"text":"A highly customizable camera-based RTU-UI controller to scan documents.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerController/UIGestureRecognizerDelegate-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController\/UIGestureRecognizerDelegate-Implementations","type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercontroller\/uigesturerecognizerdelegate-implementations","title":"UIGestureRecognizerDelegate Implementations","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerController/gestureRecognizerShouldBegin(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gestureRecognizerShouldBegin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercontroller\/gesturerecognizershouldbegin(_:)","kind":"symbol","title":"gestureRecognizerShouldBegin(_:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController\/gestureRecognizerShouldBegin(_:)","navigatorTitle":[{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"gestureRecognizerShouldBegin:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"gestureRecognizerShouldBegin:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/title","value":"SBSDKUI2DocumentScannerController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/fragments","value":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController~1gestureRecognizerShouldBegin(_:)\/title","value":"gestureRecognizerShouldBegin:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController~1gestureRecognizerShouldBegin(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}]}]}]}