{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdevicederegistrationerror\/hash"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError\/hash","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDeviceDeregistrationError(py)hash","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceDeregistrationError/hash":{"url":"\/documentation\/scanbotsdk\/sbsdkdevicederegistrationerror\/hash","title":"hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError\/hash","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDeviceDeregistrationError":{"role":"symbol","title":"SBSDKDeviceDeregistrationError","type":"topic","abstract":[{"text":"Description of error that occurred during device deregistration.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}],"url":"\/documentation\/scanbotsdk\/sbsdkdevicederegistrationerror","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDeviceDeregistrationError"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKDeviceDeregistrationError","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/fragments"},{"op":"replace","value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDeviceDeregistrationError\/navigatorTitle"}]}]}