{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentBoardingPassLeg(im)initWithGenericDocument:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","text":"SBSDKGenericDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/initwithgenericdocument:"]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/initWithGenericDocument:","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","title":"SBSDKGenericDocument","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg":{"abstract":[{"text":"Leg of the journey.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg","title":"SBSDKBarcodeDocumentBoardingPassLeg","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/initWithGenericDocument:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/initWithGenericDocument:","title":"initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/initwithgenericdocument:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace"},{"value":"SBSDKBarcodeDocumentBoardingPassLeg","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg\/fragments","value":[{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}]}]}]}