{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/secondNonConsecutiveBaggageTagLicensePlateNumber"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Second Non Consecutive Baggage Tag License Plate Number."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"secondNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentBoardingPassLeg(py)secondNonConsecutiveBaggageTagLicensePlateNumber","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"secondNonConsecutiveBaggageTagLicensePlateNumber"}],"roleHeading":"Instance Property","title":"secondNonConsecutiveBaggageTagLicensePlateNumber","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"secondNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/secondnonconsecutivebaggagetaglicenseplatenumber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/secondnonconsecutivebaggagetaglicenseplatenumber"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"title":"SBSDKGenericDocumentField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","abstract":[{"text":"A generic document field.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg/secondNonConsecutiveBaggageTagLicensePlateNumber":{"role":"symbol","navigatorTitle":[{"text":"secondNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg\/secondnonconsecutivebaggagetaglicenseplatenumber","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg\/secondNonConsecutiveBaggageTagLicensePlateNumber","abstract":[{"text":"Second Non Consecutive Baggage Tag License Plate Number.","type":"text"}],"title":"secondNonConsecutiveBaggageTagLicensePlateNumber","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"secondNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentBoardingPassLeg":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentBoardingPassLeg"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentboardingpassleg","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentBoardingPassLeg","abstract":[{"type":"text","text":"Leg of the journey."}],"title":"SBSDKBarcodeDocumentBoardingPassLeg","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentBoardingPassLeg","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"secondNonConsecutiveBaggageTagLicensePlateNumber"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"secondNonConsecutiveBaggageTagLicensePlateNumber"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":" * ","kind":"text"},{"text":"secondNonConsecutiveBaggageTagLicensePlateNumber","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1secondNonConsecutiveBaggageTagLicensePlateNumber\/title","value":"secondNonConsecutiveBaggageTagLicensePlateNumber","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"secondNonConsecutiveBaggageTagLicensePlateNumber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg~1secondNonConsecutiveBaggageTagLicensePlateNumber\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg\/title","op":"replace","value":"SBSDKBarcodeDocumentBoardingPassLeg"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentBoardingPassLeg\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentBoardingPassLeg"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}