{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/isEqual:"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration"]]},"metadata":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessByTileConfiguration(im)isEqual:","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration/isEqual:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/isEqual:","type":"topic","kind":"symbol","title":"isEqual:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/isequal:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"title":"SBSDKProcessByTileConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration","kind":"symbol","type":"topic","abstract":[{"text":"Configuration for processing image by tiles.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,"},{"type":"text","text":" "},{"type":"text","text":"but prediction can be less accurate."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKProcessByTileConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle"}]}]}