{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxProcessedFraction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"maxProcessedFraction"}],"role":"symbol","symbolKind":"property","title":"maxProcessedFraction","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessByTileConfiguration(py)maxProcessedFraction"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration"]]},"abstract":[{"type":"text","text":"At most this fraction of the image will be processed, range is from 0 to 1."},{"type":"text","text":" "},{"type":"text","text":"Decreasing this value below 1.0 can lead to faster processing but may result in"},{"type":"text","text":" "},{"type":"text","text":"less accurate prediction, as only a subset of the image tiles will be analyzed."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/maxprocessedfraction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/maxprocessedfraction"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxProcessedFraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is 1","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/maxProcessedFraction"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration/maxProcessedFraction":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxProcessedFraction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"abstract":[{"text":"At most this fraction of the image will be processed, range is from 0 to 1.","type":"text"},{"text":" ","type":"text"},{"text":"Decreasing this value below 1.0 can lead to faster processing but may result in","type":"text"},{"text":" ","type":"text"},{"text":"less accurate prediction, as only a subset of the image tiles will be analyzed.","type":"text"}],"title":"maxProcessedFraction","url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/maxprocessedfraction","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/maxProcessedFraction","navigatorTitle":[{"text":"maxProcessedFraction","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration":{"title":"SBSDKProcessByTileConfiguration","navigatorTitle":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for processing image by tiles.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,","type":"text"},{"text":" ","type":"text"},{"text":"but prediction can be less accurate.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"maxProcessedFraction"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"maxProcessedFraction","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxProcessedFraction"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration~1maxProcessedFraction\/title","op":"replace","value":"maxProcessedFraction"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration~1maxProcessedFraction\/fragments","op":"replace","value":[{"kind":"identifier","text":"maxProcessedFraction"}]},{"value":"SBSDKProcessByTileConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/fragments"},{"value":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle"}]}]}