{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"SBSDKFeature.PDFCreation","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKFeature@SBSDKFeaturePDFCreation","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFCreation","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/PDFCreation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/pdfcreation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfeature\/pdfcreation"]}],"sections":[],"abstract":[{"type":"text","text":"PDF creation is enabled in the license."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDFCreation"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"role":"symbol","kind":"symbol","title":"SBSDKFeature","url":"\/documentation\/scanbotsdk\/sbsdkfeature","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature/PDFCreation":{"navigatorTitle":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}],"title":"SBSDKFeature.PDFCreation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature\/PDFCreation","abstract":[{"text":"PDF creation is enabled in the license.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfeature\/pdfcreation","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFCreation","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFeaturePDFCreation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","value":"SBSDKFeature"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFeature"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1PDFCreation\/title","value":"SBSDKFeaturePDFCreation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature~1PDFCreation\/fragments","value":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}