{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allow5","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/allow5"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/allow5"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allow5"},"abstract":[{"type":"text","text":"Return detected 5-digit extension if present, but do not require it. Ignore the 2-digit extension."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior"]]},"metadata":{"title":"SBSDKUpcEanExtensionBehavior.allow5","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorAllow5"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allow5"}],"symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUpcEanExtensionBehavior@SBSDKUpcEanExtensionBehaviorAllow5"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"title":"SBSDKUpcEanExtensionBehavior"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUpcEanExtensionBehavior/allow5":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkupceanextensionbehavior\/allow5","role":"symbol","abstract":[{"type":"text","text":"Return detected 5-digit extension if present, but do not require it. Ignore the 2-digit extension."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUpcEanExtensionBehavior\/allow5","title":"SBSDKUpcEanExtensionBehavior.allow5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allow5"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorAllow5"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUpcEanExtensionBehaviorAllow5"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorAllow5","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKUpcEanExtensionBehaviorAllow5","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/title","value":"SBSDKUpcEanExtensionBehavior"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/fragments","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1allow5\/title","value":"SBSDKUpcEanExtensionBehaviorAllow5","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUpcEanExtensionBehavior~1allow5\/fragments","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorAllow5"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}