{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscapeRight","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoorientation\/landscaperight"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoorientation\/landscaperight"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeRight","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Landscape right orientation."}],"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation@SBSDKVideoOrientationLandscapeRight","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeRight"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeRight"}],"title":"SBSDKVideoOrientation.landscapeRight","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation","role":"symbol","title":"SBSDKVideoOrientation","type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/landscapeRight":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/landscaperight","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeRight"}],"abstract":[{"type":"text","text":"Landscape right orientation."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeRight"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeRight","kind":"symbol","type":"topic","title":"SBSDKVideoOrientation.landscapeRight"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKVideoOrientationLandscapeRight","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKVideoOrientationLandscapeRight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKVideoOrientationLandscapeRight","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKVideoOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/title"},{"value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/navigatorTitle"},{"value":"SBSDKVideoOrientationLandscapeRight","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1landscapeRight\/title"},{"value":[{"text":"SBSDKVideoOrientationLandscapeRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1landscapeRight\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}