{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTopBarTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topBarTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"topBarCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topBarCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"topUserGuidance:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topUserGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"finderViewUserGuidance:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"finderViewUserGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"introScreenTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"introScreenTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"introScreenDoneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"introScreenDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"introScreenText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"introScreenText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionOverlaySuccessMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"completionOverlaySuccessMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionOpenIntroScreenButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionIntroScreenDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textPatternConfirmationAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"textPatternConfirmationAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textPatternConfirmationAlertCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"textPatternConfirmationAlertCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textPatternConfirmationAlertSubmitButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"textPatternConfirmationAlertSubmitButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionConfirmationCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionConfirmationCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionConfirmationSubmitButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionConfirmationSubmitButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlashButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlashButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionZoomButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionZoomButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlipCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization"]]},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenTextLocalization(im)initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","navigatorTitle":[{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:finderviewuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintro-49ith"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenTextLocalization/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:":{"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:finderviewuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintro-49ith","navigatorTitle":[{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:finderViewUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:textPatternConfirmationAlertTitle:textPatternConfirmationAlertCancelButton:textPatternConfirmationAlertSubmitButton:accessibilityDescriptionConfirmationCancelButton:accessibilityDescriptionConfirmationSubmitButton:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenTextLocalization":{"title":"SBSDKUI2TextPatternScannerScreenTextLocalization","abstract":[{"text":"Configuration of the all strings for generic text scanner screen.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/title","value":"SBSDKUI2TextPatternScannerScreenTextLocalization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2TextPatternScannerScreenTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}],"op":"replace"}]}]}