{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/autoSnap","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnap"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"If the source image was captured automatically. For example, by auto snapping functions."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource"]]},"metadata":{"title":"SBSDKDocumentPageImageSource.autoSnap","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"autoSnap","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceAutoSnap"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentPageImageSource@SBSDKDocumentPageImageSourceAutoSnap","role":"symbol","symbolKind":"case"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/autosnap"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/autosnap"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/autoSnap":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/autoSnap","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"autoSnap","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource.autoSnap","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/autosnap","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceAutoSnap","kind":"identifier"}],"abstract":[{"type":"text","text":"If the source image was captured automatically. For example, by auto snapping functions."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"abstract":[{"text":"The source from where the image of the page originated from.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKDocumentPageImageSourceAutoSnap","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentPageImageSourceAutoSnap","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceAutoSnap"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKDocumentPageImageSourceAutoSnap","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1autoSnap\/title"},{"value":[{"text":"SBSDKDocumentPageImageSourceAutoSnap","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1autoSnap\/fragments"},{"value":"SBSDKDocumentPageImageSource","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSource"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/fragments"}]}]}