{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imported"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceImported"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentPageImageSource@SBSDKDocumentPageImageSourceImported","title":"SBSDKDocumentPageImageSource.imported","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"text":"If the source image was imported from external source.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"imported","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/imported"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/imported"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/imported"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/imported":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/imported","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imported"}],"title":"SBSDKDocumentPageImageSource.imported","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/imported","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceImported","kind":"identifier"}],"abstract":[{"type":"text","text":"If the source image was imported from external source."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"abstract":[{"text":"The source from where the image of the page originated from.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"SBSDKDocumentPageImageSourceImported","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceImported"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceImported"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKDocumentPageImageSourceImported","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1imported\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceImported"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1imported\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/title","op":"replace","value":"SBSDKDocumentPageImageSource"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSource"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}