{"abstract":[{"text":"If the source image was captured manually. For example, when the user pressed a snap button.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource"]]},"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKDocumentPageImageSource.manualSnap","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"manualSnap","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentPageImageSource@SBSDKDocumentPageImageSourceManualSnap","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceManualSnap","kind":"identifier"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/manualSnap","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/manualsnap"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/manualsnap"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"manualSnap","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"abstract":[{"text":"The source from where the image of the page originated from.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/manualSnap":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/manualSnap","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"manualSnap","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource.manualSnap","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/manualsnap","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceManualSnap","kind":"identifier"}],"abstract":[{"type":"text","text":"If the source image was captured manually. For example, when the user pressed a snap button."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentPageImageSourceManualSnap"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceManualSnap"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKDocumentPageImageSourceManualSnap","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKDocumentPageImageSource","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1manualSnap\/title","value":"SBSDKDocumentPageImageSourceManualSnap"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1manualSnap\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceManualSnap"}],"op":"replace"}]}]}