{"sections":[],"metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentPageImageSource@SBSDKDocumentPageImageSourceUndefined","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"undefined","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKDocumentPageImageSource.undefined","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceUndefined"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/undefined"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/undefined"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Used by default. If the source is not defined."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/undefined","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"title":"SBSDKDocumentPageImageSource","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"abstract":[{"text":"The source from where the image of the page originated from.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/undefined":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/undefined","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"undefined"}],"title":"SBSDKDocumentPageImageSource.undefined","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/undefined","type":"topic","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceUndefined","kind":"identifier"}],"abstract":[{"type":"text","text":"Used by default. If the source is not defined."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentPageImageSourceUndefined"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SBSDKDocumentPageImageSourceUndefined","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentPageImageSourceUndefined"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKDocumentPageImageSource","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageImageSource"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/fragments"},{"op":"replace","value":"SBSDKDocumentPageImageSourceUndefined","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1undefined\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1undefined\/fragments","value":[{"text":"SBSDKDocumentPageImageSourceUndefined","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}