{"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFrame"}],"role":"symbol","title":"SBSDKDocumentPageImageSource.videoFrame","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentPageImageSource@SBSDKDocumentPageImageSourceVideoFrame","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoFrame","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"If the source image was taken from the video frame.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/videoFrame"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/videoframe"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/videoframe"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource/videoFrame":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource\/videoFrame","navigatorTitle":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKDocumentPageImageSource.videoFrame","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"videoFrame","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource\/videoframe","abstract":[{"type":"text","text":"If the source image was taken from the video frame."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPageImageSource":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPageImageSource","abstract":[{"type":"text","text":"The source from where the image of the page originated from."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpageimagesource","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"SBSDKDocumentPageImageSource"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SBSDKDocumentPageImageSourceVideoFrame","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}]}]}},{"value":"SBSDKDocumentPageImageSourceVideoFrame","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1videoFrame\/title"},{"value":[{"text":"SBSDKDocumentPageImageSourceVideoFrame","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource~1videoFrame\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/title","value":"SBSDKDocumentPageImageSource","op":"replace"},{"value":[{"text":"SBSDKDocumentPageImageSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPageImageSource\/fragments"}]}]}