{"kind":"symbol","abstract":[{"type":"text","text":"Simple pattern matching where # stands for any digit and ? stands for any character."},{"type":"text","text":" "},{"type":"text","text":"All other characters represent themselves."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wildcard","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKPatternGrammar@SBSDKPatternGrammarWildcard","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKPatternGrammarWildcard","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"SBSDKPatternGrammar.wildcard"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpatterngrammar\/wildcard"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpatterngrammar\/wildcard"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar\/wildcard","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wildcard"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternGrammar/wildcard":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPatternGrammarWildcard"}],"kind":"symbol","role":"symbol","title":"SBSDKPatternGrammar.wildcard","abstract":[{"type":"text","text":"Simple pattern matching where # stands for any digit and ? stands for any character."},{"type":"text","text":" "},{"type":"text","text":"All other characters represent themselves."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wildcard"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar\/wildcard","url":"\/documentation\/scanbotsdk\/sbsdkpatterngrammar\/wildcard"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternGrammar":{"type":"topic","title":"SBSDKPatternGrammar","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpatterngrammar","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPatternGrammar"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternGrammar","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPatternGrammar"}],"abstract":[{"text":"Grammar of pattern matching.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKPatternGrammarWildcard","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKPatternGrammarWildcard","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKPatternGrammarWildcard","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKPatternGrammarWildcard","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar~1wildcard\/title"},{"value":[{"text":"SBSDKPatternGrammarWildcard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar~1wildcard\/fragments"},{"value":"SBSDKPatternGrammar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/title"},{"value":[{"kind":"identifier","text":"SBSDKPatternGrammar"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/fragments"},{"value":[{"text":"SBSDKPatternGrammar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternGrammar\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}