{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"strokeColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" = SBSDKUI2Color(colorString: \"#FFFFFFFF\", isArgb: false), ","kind":"text"},{"text":"fillColor","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"#FFFFFF30\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"strokeWidth"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" = 2.0)","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle\/init(strokeColor:fillColor:strokeWidth:)"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle(im)initWithStrokeColor:fillColor:strokeWidth:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"strokeColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"fillColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"strokeWidth","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithStrokeColor:fillColor:strokeWidth:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"init(strokeColor:fillColor:strokeWidth:)","roleHeading":"Initializer"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2backgroundstyle\/init(strokecolor:fillcolor:strokewidth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2backgroundstyle\/init(strokecolor:fillcolor:strokewidth:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BackgroundStyle":{"url":"\/documentation\/scanbotsdk\/sbsdkui2backgroundstyle","role":"symbol","abstract":[{"text":"Appearance of the polygon used for buttons and hint backgrounds.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"title":"SBSDKUI2BackgroundStyle","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BackgroundStyle/init(strokeColor:fillColor:strokeWidth:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithStrokeColor:fillColor:strokeWidth:"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"strokeColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"fillColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"strokeWidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":")","kind":"text"}],"title":"init(strokeColor:fillColor:strokeWidth:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle\/init(strokeColor:fillColor:strokeWidth:)","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2backgroundstyle\/init(strokecolor:fillcolor:strokewidth:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithStrokeColor:fillColor:strokeWidth:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStrokeColor:fillColor:strokeWidth:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStrokeColor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"strokeColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fillColor:"},{"kind":"text","text":"("},{"text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"fillColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"strokeWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"strokeWidth"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/title","value":"SBSDKUI2BackgroundStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/fragments","op":"replace","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}]},{"value":"initWithStrokeColor:fillColor:strokeWidth:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle~1init(strokeColor:fillColor:strokeWidth:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStrokeColor:fillColor:strokeWidth:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle~1init(strokeColor:fillColor:strokeWidth:)\/fragments"},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]}]}]}