{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserGuidanceHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/isuserguidancehidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/isuserguidancehidden"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration\/isUserGuidanceHidden","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether the user guidance label is hidden or not."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserGuidanceHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isUserGuidanceHidden","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMedicalCertificateScannerUIConfiguration(py)isUserGuidanceHidden","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isUserGuidanceHidden"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerUIConfiguration/isUserGuidanceHidden":{"role":"symbol","title":"isUserGuidanceHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserGuidanceHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the user guidance label is hidden or not."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration\/isUserGuidanceHidden","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isUserGuidanceHidden"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration\/isuserguidancehidden"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMedicalCertificateScannerUIConfiguration":{"role":"symbol","title":"SBSDKUIMedicalCertificateScannerUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the user interface of the RTU-UI medical certificate scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMedicalCertificateScannerUIConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuimedicalcertificatescanneruiconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isUserGuidanceHidden"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isUserGuidanceHidden"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserGuidanceHidden"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration~1isUserGuidanceHidden\/title","value":"isUserGuidanceHidden"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration~1isUserGuidanceHidden\/fragments","value":[{"kind":"identifier","text":"isUserGuidanceHidden"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/title","value":"SBSDKUIMedicalCertificateScannerUIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMedicalCertificateScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMedicalCertificateScannerUIConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}