{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration\/new","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatjapanpostconfiguration\/new"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatJapanPostConfiguration(cm)new","role":"symbol","roleHeading":"Type Method","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"new"}],"modules":[{"name":"ScanbotSDK"}],"title":"new"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"new"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatJapanPostConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Japan Post barcode configuration. Add to scanner configuration to scan Japan Post barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatjapanpostconfiguration","title":"SBSDKBarcodeFormatJapanPostConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatJapanPostConfiguration/new":{"role":"symbol","navigatorTitle":[{"text":"new","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatJapanPostConfiguration\/new","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatjapanpostconfiguration\/new","kind":"symbol","title":"new"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/title","value":"SBSDKBarcodeFormatJapanPostConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatJapanPostConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}