{"metadata":{"title":"onDrop(of:delegate:)","extendedModule":"SwiftUICore","roleHeading":"Instance Method","platforms":[{"name":"iOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false},{"name":"macOS","beta":false,"introducedAt":"11.0","deprecated":false,"unavailable":false}],"symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"externalID":"s:7SwiftUI4ViewPAAE6onDrop2of8delegateQrSay22UniformTypeIdentifiers6UTTypeVG_AA0E8Delegate_ptF::SYNTHESIZED::s:10ScanbotSDK22SBSDKUI2VINScannerViewV","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDrop"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"of"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:22UniformTypeIdentifiers6UTTypeV","kind":"typeIdentifier","text":"UTType"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI12DropDelegateP","text":"DropDelegate"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.onDrop(of:delegate:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/View-Implementations"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/onDrop(of:delegate:)-8pfpz","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDrop"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"supportedContentTypes"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:22UniformTypeIdentifiers6UTTypeV","text":"UTType","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"DropDelegate","preciseIdentifier":"s:7SwiftUI12DropDelegateP"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":"\n","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/ondrop(of:delegate:)-8pfpz"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerViewController":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController","title":"SBSDKUI2VINScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2VINScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2VINScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan VIN (Vehicle Identification Number) data."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2VINScannerView","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SBSDKUI2VINScannerView","kind":"identifier"}],"title":"SBSDKUI2VINScannerView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController","isActive":true},{"text":".","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView/View-Implementations":{"type":"topic","role":"collectionGroup","kind":"article","title":"View Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/View-Implementations","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/view-implementations","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView/onDrop(of:delegate:)-8pfpz":{"title":"onDrop(of:delegate:)","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/ondrop(of:delegate:)-8pfpz","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDrop"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"of"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:22UniformTypeIdentifiers6UTTypeV","text":"UTType"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"DropDelegate","preciseIdentifier":"s:7SwiftUI12DropDelegateP"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/onDrop(of:delegate:)-8pfpz"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/title","value":"SBSDKUI2VINScannerViewController","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2VINScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2VINScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/navigatorTitle"}]}]}