{"metadata":{"role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotSDK"}],"title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle(cm)fromJsonWithJson:","symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2iconstyle\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle\/fromJsonWithJson:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","text":"SBSDKUI2IconStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconStyle/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconstyle\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle\/fromJsonWithJson:","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","title":"fromJsonWithJson:","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconStyle":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconstyle","title":"SBSDKUI2IconStyle","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the icon appearance.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2IconStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/title"},{"value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/navigatorTitle","value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"op":"replace"}]}]}