{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsupportedDocumentAlertDialog","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/unsupportedDocumentAlertDialog","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration"]]},"abstract":[{"type":"text","text":"Configuration of the alert dialog that will be presented when document is not detected as one that is supported"},{"text":" ","type":"text"},{"type":"text","text":"by the SDK."}],"sections":[],"metadata":{"title":"unsupportedDocumentAlertDialog","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsupportedDocumentAlertDialog"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenConfiguration(py)unsupportedDocumentAlertDialog","navigatorTitle":[{"text":"unsupportedDocumentAlertDialog","kind":"identifier"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/unsupporteddocumentalertdialog"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/unsupporteddocumentalertdialog"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration","title":"SBSDKUI2DocumentDataExtractorScreenConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration of the screen for extracting data from ID documents."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenConfiguration"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanbotAlertDialog":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Configuration of the standard alert dialog.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","title":"SBSDKUI2ScanbotAlertDialog","url":"\/documentation\/scanbotsdk\/sbsdkui2scanbotalertdialog"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration/unsupportedDocumentAlertDialog":{"role":"symbol","title":"unsupportedDocumentAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/unsupportedDocumentAlertDialog","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/unsupporteddocumentalertdialog","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedDocumentAlertDialog"},{"kind":"text","text":": "},{"text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"unsupportedDocumentAlertDialog","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the alert dialog that will be presented when document is not detected as one that is supported"},{"text":" ","type":"text"},{"type":"text","text":"by the SDK."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"unsupportedDocumentAlertDialog","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"unsupportedDocumentAlertDialog"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"unsupportedDocumentAlertDialog"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/title","op":"replace","value":"SBSDKUI2DocumentDataExtractorScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenConfiguration"}],"op":"replace"},{"value":"SBSDKUI2ScanbotAlertDialog","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1unsupportedDocumentAlertDialog\/title","op":"replace","value":"unsupportedDocumentAlertDialog"},{"value":[{"text":"unsupportedDocumentAlertDialog","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1unsupportedDocumentAlertDialog\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}