{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannedPageDidChangeData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"page","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedPage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page that changed it properties."}]}],"name":"page"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageobserver\/scannedpagedidchangedata(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageobserver\/scannedpagedidchangedata(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scannedPageDidChangeData:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"scannedPageDidChangeData(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannedPageDidChangeData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage","text":"SBSDKScannedPage"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKScannedPageObserver(im)scannedPageDidChangeData:","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Informs the observers that one or more of a scanned pages properties have been changed."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageObserver\/scannedPageDidChangeData(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageObserver"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPage":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","type":"topic","title":"SBSDKScannedPage","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKScannedPage","kind":"identifier"}],"abstract":[{"text":"A scanned page (","type":"text"},{"code":"SBSDKScannedPage","type":"codeVoice"},{"text":") is a representation of a scanned documents page in digital form.","type":"text"},{"text":" ","type":"text"},{"text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPageObserver/scannedPageDidChangeData(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scannedPageDidChangeData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKScannedPage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage"},{"text":")","kind":"text"}],"title":"scannedPageDidChangeData(_:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageObserver\/scannedPageDidChangeData(_:)","navigatorTitle":[{"text":"scannedPageDidChangeData:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Informs the observers that one or more of a scanned pages properties have been changed."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageobserver\/scannedpagedidchangedata(_:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPageObserver":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPageObserver","title":"SBSDKScannedPageObserver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPageObserver","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A delegation-like protocol for observing changes on an instance of "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","type":"reference","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpageobserver","navigatorTitle":[{"text":"SBSDKScannedPageObserver","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"scannedPageDidChangeData:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scannedPageDidChangeData:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"scannedPageDidChangeData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage","text":"SBSDKScannedPage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"page"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"page","content":[{"inlineContent":[{"text":"The page that changed it properties.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/title","value":"SBSDKScannedPage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/fragments","value":[{"text":"SBSDKScannedPage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/navigatorTitle","value":[{"text":"SBSDKScannedPage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageObserver~1scannedPageDidChangeData(_:)\/title","value":"scannedPageDidChangeData:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageObserver~1scannedPageDidChangeData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scannedPageDidChangeData:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageObserver\/title","value":"SBSDKScannedPageObserver"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageObserver\/fragments","value":[{"text":"SBSDKScannedPageObserver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPageObserver\/navigatorTitle","value":[{"text":"SBSDKScannedPageObserver","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}