{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRegexFilter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"regexFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumSizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAdditionalQuietZone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"addAdditionalQuietZone"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DQuietZoneSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimum1DQuietZoneSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripCheckDigits:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"stripCheckDigits"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTextLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maximumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"code32:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"code32"},{"kind":"text","text":" "},{"kind":"identifier","text":"code39:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"code39"},{"kind":"text","text":" "},{"kind":"identifier","text":"pzn7:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pzn7"},{"kind":"text","text":" "},{"kind":"identifier","text":"pzn8:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pzn8"},{"kind":"text","text":" "},{"kind":"identifier","text":"tryCode39ExtendedMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tryCode39ExtendedMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"useCode39CheckDigit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"useCode39CheckDigit"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:minimumtextlength:maximumtextlength:code32:code39:pzn7:pzn8:trycode39extendedmode:us-kdfg"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode39Configuration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:":{"abstract":[],"role":"symbol","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:stripcheckdigits:minimumtextlength:maximumtextlength:code32:code39:pzn7:pzn8:trycode39extendedmode:us-kdfg","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:stripCheckDigits:minimumTextLength:maximumTextLength:code32:code39:pzn7:pzn8:tryCode39ExtendedMode:useCode39CheckDigit:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode39Configuration":{"type":"topic","abstract":[{"text":"Code 39 barcode and derivatives configuration. Add to scanner configuration to scan Code 39, Code 32 (Italian","type":"text"},{"text":" ","type":"text"},{"text":"Pharmacode), PZN7 and PZN8 (Pharmazentralnummer) barcodes.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode39configuration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}],"title":"SBSDKBarcodeFormatCode39Configuration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode39Configuration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeFormatCode39Configuration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode39Configuration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}],"op":"replace"}]}]}