{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerControllerShouldScanBarcodes(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontrollershouldscanbarcodes(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontrollershouldscanbarcodes(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Asks the delegate if the receiver should scan barcodes on the next video frame.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScannerControllerShouldScanBarcodes","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","text":"SBSDKBarcodeScannerViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The calling ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"name":"controller"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"True","type":"codeVoice"},{"text":", if barcodes should be scanned on the next video frame. ","type":"text"},{"code":"False","type":"codeVoice"},{"text":" otherwise.","type":"text"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Optional."}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScannerControllerShouldScanBarcodes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate(im)barcodeScannerControllerShouldScanBarcodes:","title":"barcodeScannerControllerShouldScanBarcodes(_:)","required":true,"symbolKind":"method","navigatorTitle":[{"text":"barcodeScannerControllerShouldScanBarcodes:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewControllerDelegate":{"navigatorTitle":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate","title":"SBSDKBarcodeScannerViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The delegate protocol of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"},{"type":"text","text":" that provides methods for"},{"type":"text","text":" "},{"type":"text","text":"enabling\/disabling scanning and managing scanned barcodes."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewControllerDelegate/barcodeScannerControllerShouldScanBarcodes(_:)":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontrollershouldscanbarcodes(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeScannerControllerShouldScanBarcodes","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController","text":"SBSDKBarcodeScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"barcodeScannerControllerShouldScanBarcodes(_:)","kind":"symbol","required":true,"role":"symbol","abstract":[{"type":"text","text":"Asks the delegate if the receiver should scan barcodes on the next video frame."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerControllerShouldScanBarcodes(_:)","navigatorTitle":[{"text":"barcodeScannerControllerShouldScanBarcodes:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"title":"SBSDKBarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"barcodeScannerControllerShouldScanBarcodes:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","text":"SBSDKBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calling "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"},{"type":"text","text":"."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"type":"text","text":", if barcodes should be scanned on the next video frame. "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","value":"SBSDKBarcodeScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/navigatorTitle"},{"op":"replace","value":"barcodeScannerControllerShouldScanBarcodes:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerControllerShouldScanBarcodes(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerControllerShouldScanBarcodes(_:)\/fragments"},{"op":"replace","value":"SBSDKBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}