{"sections":[],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pageSnapFeedbackNone","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2PageSnapFeedbackNone","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackNone"}],"roleHeading":"Type Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackMode(cm)pageSnapFeedbackNone","navigatorTitle":[{"kind":"identifier","text":"pageSnapFeedbackNone"}],"title":"pageSnapFeedbackNone()","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSnapFeedbackNone"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackNone","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackNone","kind":"typeIdentifier","text":"SBSDKUI2PageSnapFeedbackNone"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfeedbacknone()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfeedbacknone()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode\/pageSnapFeedbackNone()","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackNone":{"abstract":[{"text":"To not use a snap animation.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackNone","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbacknone","title":"SBSDKUI2PageSnapFeedbackNone","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2PageSnapFeedbackNone","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PageSnapFeedbackNone","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackMode/pageSnapFeedbackNone()":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pageSnapFeedbackNone","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackNone","kind":"typeIdentifier","text":"SBSDKUI2PageSnapFeedbackNone"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode\/pageSnapFeedbackNone()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pageSnapFeedbackNone"}],"title":"pageSnapFeedbackNone()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode\/pagesnapfeedbacknone()","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PageSnapFeedbackMode":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackMode","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The type of animation to display after snapping a page."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2pagesnapfeedbackmode","title":"SBSDKUI2PageSnapFeedbackMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"pageSnapFeedbackNone"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"pageSnapFeedbackNone","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PageSnapFeedbackNone","text":"SBSDKUI2PageSnapFeedbackNone","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PageSnapFeedbackNone","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"pageSnapFeedbackNone","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKUI2PageSnapFeedbackNone","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackNone\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackNone\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackNone"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackNone\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackNone"}]},{"value":"pageSnapFeedbackNone","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode~1pageSnapFeedbackNone()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pageSnapFeedbackNone"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode~1pageSnapFeedbackNone()\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/title","value":"SBSDKUI2PageSnapFeedbackMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2PageSnapFeedbackMode"}],"op":"replace"},{"value":[{"text":"SBSDKUI2PageSnapFeedbackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PageSnapFeedbackMode\/navigatorTitle","op":"replace"}]}]}