{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/copyWithZone:"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration(im)copyWithZone:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","title":"copyWithZone:","role":"symbol","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/copyWithZone:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/copywithzone:","abstract":[],"title":"copyWithZone:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration":{"title":"SBSDKUI2ReviewBottomBarConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration","abstract":[{"type":"text","text":"Configuration of the bottom bar for the review screen."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/title","value":"SBSDKUI2ReviewBottomBarConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}