{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotateButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/rotateButton"},"abstract":[{"text":"Configuration of the ‘rotate’ button, located in the bottom bar.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration(py)rotateButton","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rotateButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"rotateButton","role":"symbol","navigatorTitle":[{"text":"rotateButton","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/rotatebutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/rotatebutton"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BarButtonConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2barbuttonconfiguration","title":"SBSDKUI2BarButtonConfiguration","navigatorTitle":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the button located on a bar."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration":{"title":"SBSDKUI2ReviewBottomBarConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration","abstract":[{"type":"text","text":"Configuration of the bottom bar for the review screen."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ReviewBottomBarConfiguration/rotateButton":{"navigatorTitle":[{"kind":"identifier","text":"rotateButton"}],"abstract":[{"type":"text","text":"Configuration of the ‘rotate’ button, located in the bottom bar."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rotateButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration"}],"title":"rotateButton","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2reviewbottombarconfiguration\/rotatebutton","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ReviewBottomBarConfiguration\/rotateButton","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rotateButton","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"rotateButton","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rotateButton"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2BarButtonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/title"},{"value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/fragments"},{"value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle"},{"value":"SBSDKUI2ReviewBottomBarConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/title"},{"value":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration\/navigatorTitle"},{"value":"rotateButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1rotateButton\/title"},{"value":[{"text":"rotateButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ReviewBottomBarConfiguration~1rotateButton\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}