{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardintrotwosidesimage\/isequal:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroTwoSidesImage"]]},"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"isEqual:","roleHeading":"Instance Method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardIntroTwoSidesImage(im)isEqual:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroTwoSidesImage\/isEqual:","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroTwoSidesImage":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintrotwosidesimage","kind":"symbol","type":"topic","title":"SBSDKUI2CreditCardIntroTwoSidesImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroTwoSidesImage","abstract":[{"text":"The image for the introduction screen with two sides of a credit card.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardIntroTwoSidesImage","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2CreditCardIntroTwoSidesImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardIntroTwoSidesImage/isEqual:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardIntroTwoSidesImage\/isEqual:","type":"topic","kind":"symbol","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardintrotwosidesimage\/isequal:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroTwoSidesImage\/title","op":"replace","value":"SBSDKUI2CreditCardIntroTwoSidesImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroTwoSidesImage\/fragments","op":"replace","value":[{"text":"SBSDKUI2CreditCardIntroTwoSidesImage","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardIntroTwoSidesImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardIntroTwoSidesImage\/navigatorTitle"}]}]}