{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerbehaviorconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"init","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerBehaviorConfiguration(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerBehaviorConfiguration":{"navigatorTitle":[{"text":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Configuration for the behavior of RTU-UI text pattern scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"identifier"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerbehaviorconfiguration","title":"SBSDKUITextPatternScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerBehaviorConfiguration/init":{"title":"init","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerbehaviorconfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerBehaviorConfiguration\/init","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/title","value":"SBSDKUITextPatternScannerBehaviorConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUITextPatternScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerBehaviorConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}