{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton\/hash","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2roundbutton\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2RoundButton(py)hash","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2RoundButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2roundbutton","type":"topic","abstract":[{"type":"text","text":"Configuration of the round button."}],"kind":"symbol","title":"SBSDKUI2RoundButton","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2RoundButton"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2RoundButton/hash":{"type":"topic","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2RoundButton\/hash","kind":"symbol","title":"hash","url":"\/documentation\/scanbotsdk\/sbsdkui2roundbutton\/hash"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/title","value":"SBSDKUI2RoundButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}]},{"op":"replace","value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2RoundButton\/navigatorTitle"}]}]}