{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accessibility","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV","text":"Text"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier"},{"text":">","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/View-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/accessibility(value:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"View.accessibility(value:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/accessibility(value:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"title":"accessibility(value:)","extendedModule":"SwiftUICore","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","platforms":[{"deprecatedAt":"100000.0","deprecated":false,"beta":false,"renamed":"accessibilityValue(_:)","unavailable":false,"introducedAt":"13.0","name":"iOS"},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"renamed":"accessibilityValue(_:)","introducedAt":"13.0","deprecatedAt":"100000.0"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"Mac Catalyst","renamed":"accessibilityValue(_:)","deprecatedAt":"100000.0"},{"unavailable":false,"deprecated":false,"name":"macOS","renamed":"accessibilityValue(_:)","beta":false,"deprecatedAt":"100000.0","introducedAt":"10.15"},{"name":"tvOS","introducedAt":"13.0","renamed":"accessibilityValue(_:)","deprecatedAt":"100000.0","deprecated":false,"unavailable":false,"beta":false},{"renamed":"accessibilityValue(_:)","deprecated":false,"unavailable":false,"name":"visionOS","deprecatedAt":"100000.0","introducedAt":"1.0","beta":false},{"deprecatedAt":"100000.0","unavailable":false,"beta":false,"deprecated":false,"renamed":"accessibilityValue(_:)","introducedAt":"6.0","name":"watchOS"}],"externalID":"s:7SwiftUI4ViewPAAE13accessibility5valueAA15ModifiedContentVyxAA31AccessibilityAttachmentModifierVGAA4TextV_tF::SYNTHESIZED::s:10ScanbotSDK22SBSDKUI2MRZScannerViewV","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Text","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ModifiedContent","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier"},{"text":">","kind":"text"}]},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerViewController":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"title":"SBSDKUI2MRZScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerviewcontroller","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan MRZ (Machine-readable zones) of various documents.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView/accessibility(value:)":{"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/accessibility(value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibility"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"Text","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV"},{"text":") -> ","kind":"text"},{"text":"ModifiedContent","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[],"role":"symbol","type":"topic","title":"accessibility(value:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/accessibility(value:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MRZScannerView"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview","navigatorTitle":[{"text":"SBSDKUI2MRZScannerView","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController"},{"text":".","type":"text"}],"type":"topic","role":"symbol","title":"SBSDKUI2MRZScannerView"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerView/View-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerview\/view-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerView\/View-Implementations","type":"topic","title":"View Implementations","kind":"article","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2MRZScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerViewController"}],"op":"replace"}]}]}