{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodeImageOptions"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkencodeimageoptions\/initwithquality:format:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"quality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"format:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncodingFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKEncodingFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat"},{"text":") ","kind":"text"},{"text":"format","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"initWithQuality:format:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKEncodeImageOptions(im)initWithQuality:format:","title":"initWithQuality:format:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithQuality:format:","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodeImageOptions\/initWithQuality:format:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncodeImageOptions":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"type":"topic","abstract":[{"type":"text","text":"Options for encoding image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodeImageOptions","title":"SBSDKEncodeImageOptions","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkencodeimageoptions","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncodeImageOptions/initWithQuality:format:":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithQuality:format:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodeImageOptions\/initWithQuality:format:","title":"initWithQuality:format:","type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithQuality:format:"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkencodeimageoptions\/initwithquality:format:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEncodingFormat":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncodingFormat"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEncodingFormat","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkencodingformat","kind":"symbol","abstract":[{"type":"text","text":"Image Encoding Format."}],"title":"SBSDKEncodingFormat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodeImageOptions\/title","value":"SBSDKEncodeImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodeImageOptions\/fragments","value":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodeImageOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/title","value":"SBSDKEncodingFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/fragments","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEncodingFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEncodingFormat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}