{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Magnetic ink strip was not found.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus"]]},"kind":"symbol","metadata":{"title":"SBSDKCheckMagneticInkStripScanningStatus.errorNothingFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNothingFound"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKCheckMagneticInkStripScanningStatus@SBSDKCheckMagneticInkStripScanningStatusErrorNothingFound","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatusErrorNothingFound"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorNothingFound"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus\/errorNothingFound","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus\/errornothingfound"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus\/errornothingfound"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckMagneticInkStripScanningStatus/errorNothingFound":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKCheckMagneticInkStripScanningStatusErrorNothingFound","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus\/errornothingfound","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus\/errorNothingFound","abstract":[{"text":"Magnetic ink strip was not found.","type":"text"}],"title":"SBSDKCheckMagneticInkStripScanningStatus.errorNothingFound","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorNothingFound","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckMagneticInkStripScanningStatus":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckmagneticinkstripscanningstatus","abstract":[{"text":"Check magnetic ink (MICR) strip scanning status.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckMagneticInkStripScanningStatus","title":"SBSDKCheckMagneticInkStripScanningStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckMagneticInkStripScanningStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKCheckMagneticInkStripScanningStatusErrorNothingFound","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKCheckMagneticInkStripScanningStatusErrorNothingFound","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatusErrorNothingFound"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKCheckMagneticInkStripScanningStatusErrorNothingFound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus~1errorNothingFound\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatusErrorNothingFound"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus~1errorNothingFound\/fragments"},{"op":"replace","value":"SBSDKCheckMagneticInkStripScanningStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckMagneticInkStripScanningStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckMagneticInkStripScanningStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}