{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subFileRawHeaderString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvadocumentsubfile\/subfilerawheaderstring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaamvadocumentsubfile\/subfilerawheaderstring"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentSubfile\/subFileRawHeaderString","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Subfile raw header string."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subFileRawHeaderString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"subFileRawHeaderString","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAAMVADocumentSubfile(py)subFileRawHeaderString","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"subFileRawHeaderString"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentSubfile"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVADocumentSubfile":{"role":"symbol","title":"SBSDKAAMVADocumentSubfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAAMVADocumentSubfile"}],"abstract":[{"type":"text","text":"The AAMVA document subfile information."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentSubfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAAMVADocumentSubfile"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvadocumentsubfile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAAMVADocumentSubfile/subFileRawHeaderString":{"role":"symbol","title":"subFileRawHeaderString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subFileRawHeaderString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Subfile raw header string."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAAMVADocumentSubfile\/subFileRawHeaderString","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subFileRawHeaderString"}],"url":"\/documentation\/scanbotsdk\/sbsdkaamvadocumentsubfile\/subfilerawheaderstring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"subFileRawHeaderString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"subFileRawHeaderString"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"subFileRawHeaderString"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVADocumentSubfile\/title","value":"SBSDKAAMVADocumentSubfile"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVADocumentSubfile\/fragments","value":[{"kind":"identifier","text":"SBSDKAAMVADocumentSubfile"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVADocumentSubfile~1subFileRawHeaderString\/title","value":"subFileRawHeaderString"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAAMVADocumentSubfile~1subFileRawHeaderString\/fragments","value":[{"kind":"identifier","text":"subFileRawHeaderString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}