{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBorderWidthFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"borderWidthFraction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"blackOutliersFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"blackOutliersFraction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"whiteOutliersFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"whiteOutliersFraction"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter\/initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter"]]},"metadata":{"navigatorTitle":[{"text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","kind":"identifier"}],"title":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKGrayscaleFilter(im)initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/initwithborderwidthfraction:blackoutliersfraction:whiteoutliersfraction:"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter/initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter\/initwithborderwidthfraction:blackoutliersfraction:whiteoutliersfraction:","navigatorTitle":[{"kind":"identifier","text":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter\/initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","title":"initWithBorderWidthFraction:blackOutliersFraction:whiteOutliersFraction:","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter","title":"SBSDKGrayscaleFilter","kind":"symbol","type":"topic","abstract":[{"text":"Converts color images to grayscale and applies autocontrast.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter"}},"variantOverrides":[{"patch":[{"value":"SBSDKGrayscaleFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/title"},{"value":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/fragments"},{"value":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}