{"abstract":[{"type":"text","text":"Configuration of the all strings for document data extractor screen."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"localization","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenConfiguration(py)localization","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localization","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"navigatorTitle":[{"kind":"identifier","text":"localization"}],"title":"localization","roleHeading":"Instance Property"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/localization"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/localization"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/localization","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration/localization":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration\/localization","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"abstract":[{"text":"Configuration of the all strings for document data extractor screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration\/localization","navigatorTitle":[{"text":"localization","kind":"identifier"}],"title":"localization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenConfiguration":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreenconfiguration","abstract":[{"text":"Configuration of the screen for extracting data from ID documents.","type":"text"}],"kind":"symbol","title":"SBSDKUI2DocumentDataExtractorScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","title":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","abstract":[{"type":"text","text":"Configuration of the all strings for document data extractor screen."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"localization","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"localization","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization"},{"text":" * ","kind":"text"},{"text":"localization","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1localization\/title","op":"replace","value":"localization"},{"value":[{"kind":"identifier","text":"localization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration~1localization\/fragments"},{"value":"SBSDKUI2DocumentDataExtractorScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenConfiguration"}]},{"value":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}