{"metadata":{"title":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","symbolKind":"method","navigatorTitle":[{"text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerConfiguration(im)initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration\/initwithbarcodeformatconfigurations:extracteddocumentformats:onlyacceptdocuments:returnbarcodeimage:enginemode:accumulationconfig:optimizedforoverlays:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBarcodeFormatConfigurations:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeFormatConfigurationBase *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeFormatConfigurations"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractedDocumentFormats:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeDocumentFormat *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"extractedDocumentFormats"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyAcceptDocuments:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"onlyAcceptDocuments"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnBarcodeImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"returnBarcodeImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"engineMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeScannerEngineMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerEngineMode","kind":"typeIdentifier","text":"SBSDKBarcodeScannerEngineMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"engineMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"accumulationConfig:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeAccumulationConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationConfiguration","kind":"typeIdentifier","text":"SBSDKBarcodeAccumulationConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accumulationConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"optimizedForOverlays:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"optimizedForOverlays"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration\/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerEngineMode":{"title":"SBSDKBarcodeScannerEngineMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerenginemode","type":"topic","abstract":[{"type":"text","text":"The engine mode for barcode scanning."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerEngineMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerConfiguration/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:":{"role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration\/initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","title":"initWithBarcodeFormatConfigurations:extractedDocumentFormats:onlyAcceptDocuments:returnBarcodeImage:engineMode:accumulationConfig:optimizedForOverlays:","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration\/initwithbarcodeformatconfigurations:extracteddocumentformats:onlyacceptdocuments:returnbarcodeimage:enginemode:accumulationconfig:optimizedforoverlays:","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerConfiguration","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerconfiguration","role":"symbol","title":"SBSDKBarcodeScannerConfiguration","abstract":[{"type":"text","text":"Configuration for the barcode scanner."}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeAccumulationConfiguration":{"abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeAccumulationConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeaccumulationconfiguration","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeAccumulationConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeScannerEngineMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/fragments","value":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/title","value":"SBSDKBarcodeScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/fragments","value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/title","value":"SBSDKBarcodeAccumulationConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/fragments","value":[{"text":"SBSDKBarcodeAccumulationConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeAccumulationConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationConfiguration"}]}]}]}