{"metadata":{"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCryptingProvider(im)initWithBlock:","modules":[{"name":"ScanbotSDK"}],"title":"init(block:)","navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": () -> ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"SBSDKStorageCrypting"},{"kind":"text","text":"))"}],"role":"symbol","roleHeading":"Initializer"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcryptingprovider\/init(block:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcryptingprovider\/init(block:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCryptingProvider"]]},"abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"codeVoice","code":"SBSDKCryptingProvider"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> ("},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting"},{"kind":"text","text":"))"}]}]},{"kind":"parameters","parameters":[{"name":"block","content":[{"inlineContent":[{"text":"A block that creates and returns a storage crypter instance conforming to ","type":"text"},{"code":"SBSDKStorageCrypting","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"The block will be called each time the "},{"type":"codeVoice","code":"storageCrypting()"},{"type":"text","text":" method is invoked. Make sure that the block returns a valid AND new instance. Do not reuse instances, always return a new one."}],"type":"paragraph"}]}],"kind":"content"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCryptingProvider\/init(block:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCryptingProvider":{"abstract":[{"type":"text","text":"A block-based storage crypting provider."},{"type":"text","text":" "},{"type":"text","text":"Create an instance of this class with a block that returns the desired crypting implementation."}],"title":"SBSDKCryptingProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCryptingProvider"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCryptingProvider","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCryptingProvider"}],"url":"\/documentation\/scanbotsdk\/sbsdkcryptingprovider"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCrypting"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","title":"SBSDKStorageCrypting"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCryptingProvider/init(block:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": () -> ("},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":"))"}],"kind":"symbol","abstract":[{"type":"text","text":"Designated initializer. Creates a new instance of "},{"type":"codeVoice","code":"SBSDKCryptingProvider"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCryptingProvider\/init(block:)","navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}],"url":"\/documentation\/scanbotsdk\/sbsdkcryptingprovider\/init(block:)","title":"init(block:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithBlock:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBlock:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SBSDKStorageCrypting>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"kind":"text","text":" (^"},{"kind":"text","text":")()) "},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A block that creates and returns a storage crypter instance conforming to ","type":"text"},{"type":"codeVoice","code":"SBSDKStorageCrypting"},{"text":".","type":"text"}]}],"name":"block"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKCryptingProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCryptingProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCryptingProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCryptingProvider\/fragments"},{"op":"replace","value":[{"text":"SBSDKCryptingProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCryptingProvider\/navigatorTitle"},{"op":"replace","value":"SBSDKStorageCrypting","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments"},{"op":"replace","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle"},{"value":"initWithBlock:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCryptingProvider~1init(block:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlock:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCryptingProvider~1init(block:)\/fragments","op":"replace"}]}]}