{"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okButNotConfirmed","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed","kind":"identifier"}],"title":"SBSDKDocumentDataExtractionStatus.okButNotConfirmed","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionStatus@SBSDKDocumentDataExtractionStatusOkButNotConfirmed","role":"symbol","symbolKind":"case"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/okButNotConfirmed","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/okbutnotconfirmed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/okbutnotconfirmed"]}],"abstract":[{"type":"text","text":"The document data was extracted. Some fields have not yet been confirmed."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okButNotConfirmed","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/okButNotConfirmed":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"okButNotConfirmed","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/okButNotConfirmed","title":"SBSDKDocumentDataExtractionStatus.okButNotConfirmed","abstract":[{"text":"The document data was extracted. Some fields have not yet been confirmed.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/okbutnotconfirmed"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus":{"navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"abstract":[{"text":"The status of the extraction process.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKDocumentDataExtractionStatus","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1okButNotConfirmed\/title","op":"replace","value":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1okButNotConfirmed\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusOkButNotConfirmed"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/title","op":"replace","value":"SBSDKDocumentDataExtractionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}