{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paragraph","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"SBSDKOCRResultBlockTypeParagraph","kind":"identifier"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"paragraph","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"SBSDKOCRResultBlockType.paragraph","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKOCRResultBlockType@SBSDKOCRResultBlockTypeParagraph"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/paragraph"},"abstract":[{"type":"text","text":"The result block represents a text paragraph."}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/paragraph"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/paragraph"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType/paragraph":{"url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/paragraph","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKOCRResultBlockTypeParagraph","kind":"identifier"}],"title":"SBSDKOCRResultBlockType.paragraph","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/paragraph","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"paragraph","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The result block represents a text paragraph."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType","title":"SBSDKOCRResultBlockType","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype","abstract":[{"type":"text","text":"The block type of an OCR fragment."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKOCRResultBlockTypeParagraph"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SBSDKOCRResultBlockTypeParagraph","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKOCRResultBlockTypeParagraph"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1paragraph\/title","op":"replace","value":"SBSDKOCRResultBlockTypeParagraph"},{"value":[{"text":"SBSDKOCRResultBlockTypeParagraph","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1paragraph\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/title","value":"SBSDKOCRResultBlockType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/fragments","value":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}