{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithIsValidationSuccessful:text:confidenceValue:"}],"title":"initWithIsValidationSuccessful:text:confidenceValue:","navigatorTitle":[{"text":"initWithIsValidationSuccessful:text:confidenceValue:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVehicleIdentificationNumberScannerResult(im)initWithIsValidationSuccessful:text:confidenceValue:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/initWithIsValidationSuccessful:text:confidenceValue:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithIsValidationSuccessful:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isValidationSuccessful","kind":"internalParam"},{"kind":"text","text":" "},{"text":"text:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"kind":"text","text":" "},{"text":"confidenceValue:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"confidenceValue"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult\/initwithisvalidationsuccessful:text:confidencevalue:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult/initWithIsValidationSuccessful:text:confidenceValue:":{"role":"symbol","kind":"symbol","title":"initWithIsValidationSuccessful:text:confidenceValue:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult\/initWithIsValidationSuccessful:text:confidenceValue:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithIsValidationSuccessful:text:confidenceValue:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult\/initwithisvalidationsuccessful:text:confidencevalue:","navigatorTitle":[{"text":"initWithIsValidationSuccessful:text:confidenceValue:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVehicleIdentificationNumberScannerResult":{"navigatorTitle":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"title":"SBSDKVehicleIdentificationNumberScannerResult","abstract":[{"text":"A class describing the result of the vehicle identification number scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvehicleidentificationnumberscannerresult","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVehicleIdentificationNumberScannerResult","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/title","op":"replace","value":"SBSDKVehicleIdentificationNumberScannerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKVehicleIdentificationNumberScannerResult"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKVehicleIdentificationNumberScannerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVehicleIdentificationNumberScannerResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}