{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"There is no CPU usage while the receiver is not on screen.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"False will NOT stop the camera session, but pause the delivery of video frames and QR codes."}]},{"inlineContent":[{"text":"There is some very low CPU activity while the receiver is not on screen, but there is also no","type":"text"},{"type":"text","text":" "},{"text":"lag when the receiver returns to the screen.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"platforms":[],"navigatorTitle":[{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"}],"title":"stopsCameraSessionWhenDisappeared","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerBehaviorConfiguration(py)stopsCameraSessionWhenDisappeared","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/stopscamerasessionwhendisappeared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/stopscamerasessionwhendisappeared"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":", the default, the camera session will be stopped entirely,"},{"text":" ","type":"text"},{"type":"text","text":"when the receiver disappears and restarts when the receiver reappears."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/stopsCameraSessionWhenDisappeared","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerBehaviorConfiguration":{"title":"SBSDKUIDocumentScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"navigatorTitle":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerBehaviorConfiguration/stopsCameraSessionWhenDisappeared":{"kind":"symbol","abstract":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"type":"text","text":", the default, the camera session will be stopped entirely,"},{"text":" ","type":"text"},{"type":"text","text":"when the receiver disappears and restarts when the receiver reappears."}],"deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerbehaviorconfiguration\/stopscamerasessionwhendisappeared","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}],"title":"stopsCameraSessionWhenDisappeared","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerBehaviorConfiguration\/stopsCameraSessionWhenDisappeared","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"stopsCameraSessionWhenDisappeared","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIDocumentScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerBehaviorConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace"},{"value":"stopsCameraSessionWhenDisappeared","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1stopsCameraSessionWhenDisappeared\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerBehaviorConfiguration~1stopsCameraSessionWhenDisappeared\/fragments","value":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}]}]}]}