{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"focalLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"Returns -1.0, if the value is not present in the metadata."}],"type":"paragraph"}]}],"kind":"content"}],"abstract":[{"text":"The real focal length of the lens used to capture the image. Measured in millimeters. Readonly.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/focalLength","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"focalLength","kind":"identifier"}],"role":"symbol","symbolKind":"property","title":"focalLength","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageMetadata(py)focalLength","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"focalLength","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/focallength"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/focallength"]}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadataProcessor":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadataProcessor"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadataprocessor","abstract":[{"text":"Helper class to extract or inject image metadata, e.g. EXIF, TIFF, JFIF from  image data.","type":"text"}],"title":"SBSDKImageMetadataProcessor"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata/focalLength":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"focalLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata\/focallength","title":"focalLength","kind":"symbol","abstract":[{"type":"text","text":"The real focal length of the lens used to capture the image. Measured in millimeters. Readonly."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata\/focalLength","navigatorTitle":[{"kind":"identifier","text":"focalLength"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageMetadata":{"type":"topic","title":"SBSDKImageMetadata","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagemetadata","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageMetadata"}],"abstract":[{"type":"text","text":"Encapsulates image metadata, e.g. EXIF, TIFF, JFIF in a convenient way."},{"type":"text","text":" "},{"text":"Use ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadataProcessor","type":"reference","isActive":true},{"type":"text","text":" to extract metadata from and inject changed metadata into image data."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageMetadata"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageMetadata"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"focalLength","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"focalLength"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"focalLength","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/title","value":"SBSDKImageMetadataProcessor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/fragments","op":"replace","value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadataProcessor\/navigatorTitle","value":[{"text":"SBSDKImageMetadataProcessor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1focalLength\/title","op":"replace","value":"focalLength"},{"op":"replace","value":[{"kind":"identifier","text":"focalLength"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata~1focalLength\/fragments"},{"value":"SBSDKImageMetadata","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/title"},{"value":[{"text":"SBSDKImageMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageMetadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageMetadata","kind":"identifier"}]}]}]}