{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(scanningViewController:didFinishWithDocument:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController","text":"SBSDKUIDocumentScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController"},{"type":"text","text":" which generated the scanned pages and dismissed."}]}]},{"name":"document","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document containing the scanned pages."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontrollerdelegate\/scanningviewcontroller(_:didfinishwith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontrollerdelegate\/scanningviewcontroller(_:didfinishwith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate\/scanningViewController(_:didFinishWith:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate that the document scanning view controller has scanned document pages"},{"type":"text","text":" "},{"type":"text","text":"and the view controller has dismissed."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"scanningViewController:didFinishWithDocument:"}],"role":"symbol","title":"scanningViewController(_:didFinishWith:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUIDocumentScannerViewControllerDelegate(im)scanningViewController:didFinishWithDocument:","required":true,"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController":{"role":"symbol","title":"SBSDKUIDocumentScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewControllerDelegate":{"role":"symbol","title":"SBSDKUIDocumentScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontrollerdelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewControllerDelegate/scanningViewController(_:didFinishWith:)":{"navigatorTitle":[{"kind":"identifier","text":"scanningViewController:didFinishWithDocument:"}],"role":"symbol","title":"scanningViewController(_:didFinishWith:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanningViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Informs the delegate that the document scanning view controller has scanned document pages"},{"type":"text","text":" "},{"type":"text","text":"and the view controller has dismissed."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewControllerDelegate\/scanningViewController(_:didFinishWith:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontrollerdelegate\/scanningviewcontroller(_:didfinishwith:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPage":{"role":"symbol","title":"SBSDKDocumentPage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpage"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocument":{"role":"symbol","title":"SBSDKDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocument"}],"abstract":[{"type":"text","text":"A thread-safe, mutable container for scanned pages of type "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPage"},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocument"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scanningViewController:didFinishWithDocument:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanningViewController:didFinishWithDocument:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scanningViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController","text":"SBSDKUIDocumentScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishWithDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocument","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocument","text":"SBSDKDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/title","value":"SBSDKUIDocumentScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/title","value":"SBSDKUIDocumentScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate~1scanningViewController(_:didFinishWith:)\/title","value":"scanningViewController:didFinishWithDocument:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewControllerDelegate~1scanningViewController(_:didFinishWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanningViewController:didFinishWithDocument:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPage\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentPage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocument\/title","value":"SBSDKDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}