{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate\/medicalCertificateScannerViewController(_:didScanMedicalCertificate:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(medicalCertificateScannerViewController:didScanMedicalCertificate:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"medicalCertificateScannerViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier","text":"SBSDKMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanMedicalCertificate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier","text":"SBSDKMedicalCertificateScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The medical certificate scanner view controller which scanned the medical certificate."}],"type":"paragraph"}],"name":"controller"},{"content":[{"inlineContent":[{"type":"text","text":"The medical certificate scanner result that have been scanned."}],"type":"paragraph"}],"name":"result"}]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"required":true,"navigatorTitle":[{"text":"medicalCertificateScannerViewController:didScanMedicalCertificate:","kind":"identifier"}],"title":"medicalCertificateScannerViewController(_:didScanMedicalCertificate:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKMedicalCertificateScannerViewControllerDelegate(im)medicalCertificateScannerViewController:didScanMedicalCertificate:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"medicalCertificateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanMedicalCertificate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"abstract":[{"text":"Informs the delegate, that the medical certificate scanner has successfully detected and scanned a medical certificate.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate\/medicalcertificatescannerviewcontroller(_:didscanmedicalcertificate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate\/medicalcertificatescannerviewcontroller(_:didscanmedicalcertificate:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScanningResult":{"kind":"symbol","type":"topic","abstract":[{"text":"The result of the medical certificate scanning.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescanningresult","title":"SBSDKMedicalCertificateScanningResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}],"title":"SBSDKMedicalCertificateScannerViewController","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController","kind":"symbol","abstract":[{"type":"text","text":"The classic UI view controller that can be used to detect and scan medical certificates. Can be configured to scan on video frames or,"},{"type":"text","text":" "},{"type":"text","text":"for better accuracy, on high-res photos that are automatically captured."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewControllerDelegate/medicalCertificateScannerViewController(_:didScanMedicalCertificate:)":{"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate\/medicalcertificatescannerviewcontroller(_:didscanmedicalcertificate:)","kind":"symbol","required":true,"role":"symbol","abstract":[{"type":"text","text":"Informs the delegate, that the medical certificate scanner has successfully detected and scanned a medical certificate."}],"navigatorTitle":[{"text":"medicalCertificateScannerViewController:didScanMedicalCertificate:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"medicalCertificateScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMedicalCertificateScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController"},{"text":", ","kind":"text"},{"text":"didScanMedicalCertificate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMedicalCertificateScanningResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate\/medicalCertificateScannerViewController(_:didScanMedicalCertificate:)","type":"topic","title":"medicalCertificateScannerViewController(_:didScanMedicalCertificate:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateScannerViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatescannerviewcontrollerdelegate","abstract":[{"type":"text","text":"The delegation protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},{"type":"text","text":" class."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewControllerDelegate"}],"type":"topic","title":"SBSDKMedicalCertificateScannerViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewControllerDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"medicalCertificateScannerViewController:didScanMedicalCertificate:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"medicalCertificateScannerViewController:didScanMedicalCertificate:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"medicalCertificateScannerViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScannerViewController","text":"SBSDKMedicalCertificateScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didScanMedicalCertificate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificateScanningResult","text":"SBSDKMedicalCertificateScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateScanningResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The medical certificate scanner view controller which scanned the medical certificate.","type":"text"}]}],"name":"controller"},{"content":[{"inlineContent":[{"type":"text","text":"The medical certificate scanner result that have been scanned."}],"type":"paragraph"}],"name":"result"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/title","value":"SBSDKMedicalCertificateScanningResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/fragments","value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScanningResult\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateScanningResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/title","value":"SBSDKMedicalCertificateScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/fragments","value":[{"text":"SBSDKMedicalCertificateScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate~1medicalCertificateScannerViewController(_:didScanMedicalCertificate:)\/title","value":"medicalCertificateScannerViewController:didScanMedicalCertificate:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate~1medicalCertificateScannerViewController(_:didScanMedicalCertificate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"medicalCertificateScannerViewController:didScanMedicalCertificate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate\/title","value":"SBSDKMedicalCertificateScannerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateScannerViewControllerDelegate","kind":"identifier"}]}]}]}