{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/fixedSize()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedSize"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":"\n"}],"platforms":["iOS"]}]}],"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"13.0","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"13.0","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.0","beta":false},{"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.15","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","introducedAt":"13.0","beta":false},{"unavailable":false,"deprecated":false,"name":"watchOS","introducedAt":"6.0","beta":false}],"externalID":"s:7SwiftUI4ViewPAAE9fixedSizeQryF::SYNTHESIZED::s:10ScanbotSDK22SBSDKUI2VINScannerViewV","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fixedSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"method","title":"fixedSize()","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotSDK"}],"roleHeading":"Instance Method","extendedModule":"SwiftUICore"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/View-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.fixedSize()"},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/fixedsize()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView/View-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/View-Implementations","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/view-implementations","role":"collectionGroup","title":"View Implementations","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView/fixedSize()":{"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview\/fixedsize()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView\/fixedSize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixedSize"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"type":"topic","title":"fixedSize()","kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerViewController":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerviewcontroller","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan VIN (Vehicle Identification Number) data.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerViewController"}],"title":"SBSDKUI2VINScannerViewController","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2VINScannerView":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2VINScannerView"}],"role":"symbol","abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerViewController","isActive":true},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2VINScannerView","type":"topic","title":"SBSDKUI2VINScannerView","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2VINScannerView"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2vinscannerview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/title","value":"SBSDKUI2VINScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUI2VINScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2VINScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2VINScannerViewController"}]}]}]}