{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode39Configuration"]]},"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"text":"minimumTextLength","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode39Configuration(py)minimumTextLength","title":"minimumTextLength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"roleHeading":"Instance Property","role":"symbol"},"abstract":[{"text":"Minimum text length. Applied only to linear barcode formats that allow variable length.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode39Configuration\/minimumTextLength"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Default is 1","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode39configuration\/minimumtextlength"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode39configuration\/minimumtextlength"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode39Configuration/minimumTextLength":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumTextLength","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","abstract":[{"text":"Minimum text length. Applied only to linear barcode formats that allow variable length.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode39configuration\/minimumtextlength","type":"topic","navigatorTitle":[{"text":"minimumTextLength","kind":"identifier"}],"title":"minimumTextLength","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode39Configuration\/minimumTextLength"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode39Configuration":{"title":"SBSDKBarcodeFormatCode39Configuration","abstract":[{"type":"text","text":"Code 39 barcode and derivatives configuration. Add to scanner configuration to scan Code 39, Code 32 (Italian Pharmacode), PZN7 and PZN8 (Pharmazentralnummer) barcodes."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode39Configuration","navigatorTitle":[{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode39configuration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"minimumTextLength"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"minimumTextLength","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode39Configuration~1minimumTextLength\/title","op":"replace","value":"minimumTextLength"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode39Configuration~1minimumTextLength\/fragments","op":"replace","value":[{"text":"minimumTextLength","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode39Configuration\/title","op":"replace","value":"SBSDKBarcodeFormatCode39Configuration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode39Configuration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode39Configuration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}]}]}]}