{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAnalysisMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is UNFILTERED_DOCUMENT"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/documentanalysismode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/documentanalysismode"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings"]]},"abstract":[{"text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"documentAnalysisMode","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings(py)documentAnalysisMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAnalysisMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode"}],"roleHeading":"Instance Property","title":"documentAnalysisMode","symbolKind":"property","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings","kind":"symbol","title":"SBSDKUI2DocumentScannerOutputSettings","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}],"abstract":[{"type":"text","text":"Configuration of the output settings."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerOutputSettings/documentAnalysisMode":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneroutputsettings\/documentanalysismode","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image."}],"title":"documentAnalysisMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAnalysisMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentAnalysisMode"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentAnalysisMode":{"abstract":[{"type":"text","text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentAnalysisMode","title":"SBSDKUI2DocumentAnalysisMode","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentanalysismode","navigatorTitle":[{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"documentAnalysisMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"documentAnalysisMode","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentAnalysisMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"documentAnalysisMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/title","op":"replace","value":"SBSDKUI2DocumentScannerOutputSettings"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentAnalysisMode\/title","op":"replace","value":"documentAnalysisMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentAnalysisMode\/fragments","op":"replace","value":[{"text":"documentAnalysisMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/title","op":"replace","value":"SBSDKUI2DocumentAnalysisMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/fragments","op":"replace","value":[{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentAnalysisMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentAnalysisMode"}]}]}]}