{"kind":"symbol","metadata":{"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProcessByTileConfiguration(im)initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","navigatorTitle":[{"text":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","kind":"identifier"}],"role":"symbol","symbolKind":"method","title":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"minProcessedFraction:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minProcessedFraction"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxProcessedFraction:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxProcessedFraction"},{"kind":"text","text":" "},{"kind":"identifier","text":"minNumberOfRequiredSymbols:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minNumberOfRequiredSymbols"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tileSize"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/initwithenabled:minprocessedfraction:maxprocessedfraction:minnumberofrequiredsymbols:tilesize:"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration","title":"SBSDKProcessByTileConfiguration","navigatorTitle":[{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessByTileConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration for processing image by tiles.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to make the document quality analyzer processing faster with lower memory consumption,","type":"text"},{"text":" ","type":"text"},{"text":"but prediction can be less accurate.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessByTileConfiguration/initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:":{"abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessByTileConfiguration\/initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","type":"topic","role":"symbol","title":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprocessbytileconfiguration\/initwithenabled:minprocessedfraction:maxprocessedfraction:minnumberofrequiredsymbols:tilesize:","navigatorTitle":[{"kind":"identifier","text":"initWithEnabled:minProcessedFraction:maxProcessedFraction:minNumberOfRequiredSymbols:tileSize:"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKProcessByTileConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKProcessByTileConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessByTileConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}