{"sections":[],"abstract":[{"text":"Configuration of the screen for cropping the scanned pages.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerScreens\/cropping"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cropping","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration","text":"SBSDKUI2CroppingScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannerscreens\/cropping"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannerscreens\/cropping"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerScreens"]]},"metadata":{"roleHeading":"Instance Property","title":"cropping","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cropping","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration"}],"navigatorTitle":[{"text":"cropping","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerScreens(py)cropping","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerScreens/cropping":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerScreens\/cropping","navigatorTitle":[{"kind":"identifier","text":"cropping"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cropping","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the screen for cropping the scanned pages."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerscreens\/cropping","title":"cropping","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the screen for cropping the scanned pages."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingscreenconfiguration","type":"topic","title":"SBSDKUI2CroppingScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingScreenConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerScreens":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerScreens","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the document scanner sub-screens."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerscreens","type":"topic","title":"SBSDKUI2DocumentScannerScreens","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerScreens","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerScreens","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"cropping"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"cropping","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2CroppingScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingScreenConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cropping"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"cropping","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerScreens~1cropping\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerScreens~1cropping\/fragments","value":[{"kind":"identifier","text":"cropping"}]},{"value":"SBSDKUI2CroppingScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2CroppingScreenConfiguration","kind":"identifier"}]},{"value":"SBSDKUI2DocumentScannerScreens","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerScreens\/title"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerScreens","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerScreens\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}