{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"b1","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","kind":"typeIdentifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategories"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategories\/b1"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategories\/b1"]}],"abstract":[{"type":"text","text":"The child document of type “B1”."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategories\/b1"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"b1"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1"},{"kind":"text","text":"?"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategories(py)b1","title":"b1","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"b1","kind":"identifier"}],"role":"symbol"},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1":{"abstract":[{"type":"text","text":"DeDriverLicenseBack.Categories.B1"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesb1","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","navigatorTitle":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","kind":"identifier"}],"title":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategories/b1":{"abstract":[{"type":"text","text":"The child document of type “B1”."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategories\/b1","title":"b1","type":"topic","navigatorTitle":[{"text":"b1","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"b1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategories\/b1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategories":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategories","abstract":[{"type":"text","text":"Categories table row container"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategories","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategories"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategories"}],"title":"SBSDKDocumentsModelDeDriverLicenseBackCategories","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"b1","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"b1","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1"},{"kind":"text","text":" * "},{"kind":"identifier","text":"b1"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1\/title","value":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1"},{"value":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesB1"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories~1b1\/title","value":"b1"},{"value":[{"text":"b1","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories~1b1\/fragments"},{"op":"replace","value":"SBSDKDocumentsModelDeDriverLicenseBackCategories","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategories"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategories\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategories","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}