{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenLowPowerFarDistance","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenlowpowerfardistance"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenlowpowerfardistance"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode"]]},"abstract":[{"text":"Similar to NEXT_GEN_LOW_POWER, but optimized for scanning from far distances.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextGenLowPowerFarDistance"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeScannerEngineMode@SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","roleHeading":"Case","title":"SBSDKBarcodeScannerEngineMode.nextGenLowPowerFarDistance","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nextGenLowPowerFarDistance","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/nextGenLowPowerFarDistance":{"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SBSDKBarcodeScannerEngineMode.nextGenLowPowerFarDistance","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenlowpowerfardistance","abstract":[{"text":"Similar to NEXT_GEN_LOW_POWER, but optimized for scanning from far distances.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenLowPowerFarDistance","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nextGenLowPowerFarDistance","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The engine mode for barcode scanning."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"title":"SBSDKBarcodeScannerEngineMode","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenLowPowerFarDistance\/title","value":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenLowPowerFarDistance\/fragments","value":[{"text":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","kind":"identifier"}],"op":"replace"},{"value":"SBSDKBarcodeScannerEngineMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle"}]}]}