{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cryptingProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/cryptingProvider"},"abstract":[{"text":"If non-nil, overrides the default image encryption provider.","type":"text"}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cryptingProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"cryptingProvider","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"cryptingProvider","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKKeyedImageStorage(py)cryptingProvider"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/cryptingprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/cryptingprovider"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/cryptingProvider":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cryptingProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"If non-nil, overrides the default image encryption provider.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/cryptingProvider","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/cryptingprovider","type":"topic","navigatorTitle":[{"text":"cryptingProvider","kind":"identifier"}],"title":"cryptingProvider","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingProvider":{"title":"SBSDKStorageCryptingProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","abstract":[{"type":"text","text":"Protocol for providing a storage crypting object."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingprovider"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage":{"role":"symbol","kind":"symbol","title":"SBSDKKeyedImageStorage","type":"topic","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class."},{"type":"text","text":" "},{"type":"text","text":"Manages images in a dictionary-like fashion."}],"navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"cryptingProvider","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"cryptingProvider","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SBSDKStorageCryptingProvider>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":" ","kind":"text"},{"text":"cryptingProvider","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"cryptingProvider","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1cryptingProvider\/title","op":"replace"},{"value":[{"text":"cryptingProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1cryptingProvider\/fragments"},{"value":"SBSDKStorageCryptingProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/title"},{"value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/navigatorTitle"},{"value":"SBSDKKeyedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/title"},{"value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}