{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/required"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/required"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/required"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","abstract":[{"text":"Encryption\/Decryption is used when loading\/saving an image. A crypting provider must first be set using ","type":"text"},{"type":"codeVoice","code":"ImageRef.setStorageCryptingProvider"},{"text":". If no provider is set, the loading\/saving operation will fail.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"SBSDKEncryptionModeRequired","kind":"identifier"}],"title":"SBSDKEncryptionMode.required","symbolKind":"case","roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode@SBSDKEncryptionModeRequired","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/required":{"abstract":[{"text":"Encryption\/Decryption is used when loading\/saving an image. A crypting provider must first be set using ","type":"text"},{"code":"ImageRef.setStorageCryptingProvider","type":"codeVoice"},{"text":". If no provider is set, the loading\/saving operation will fail.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/required","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/required","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeRequired"}],"title":"SBSDKEncryptionMode.required","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"identifier"}],"title":"SBSDKEncryptionMode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode","abstract":[{"type":"text","text":"Encryption\/Decryption mode to be used when an image is loaded\/saved."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKEncryptionMode","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKEncryptionModeRequired","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKEncryptionModeRequired","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKEncryptionModeRequired"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKEncryptionModeRequired","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1required\/title"},{"value":[{"text":"SBSDKEncryptionModeRequired","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1required\/fragments"},{"value":"SBSDKEncryptionMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/title"},{"value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/navigatorTitle"}]}]}