{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor\/scaleFactor"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleFactor"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"scaleFactor","kind":"identifier"}],"title":"scaleFactor","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPDFImageExtractor(py)scaleFactor","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/scalefactor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/scalefactor"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor"]]},"abstract":[{"text":"The scale factor applied to the PDF media box frame while extracting images. Defaults to 1.0.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaleFactor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFImageExtractor":{"type":"topic","abstract":[{"type":"text","text":"Class used to extract images from a PDF file and returns them in various ways."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor","role":"symbol","title":"SBSDKPDFImageExtractor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor","navigatorTitle":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPDFImageExtractor/scaleFactor":{"abstract":[{"type":"text","text":"The scale factor applied to the PDF media box frame while extracting images. Defaults to 1.0."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaleFactor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"scaleFactor","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpdfimageextractor\/scalefactor","type":"topic","title":"scaleFactor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPDFImageExtractor\/scaleFactor"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"scaleFactor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"scaleFactor"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":" "},{"text":"scaleFactor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/title","op":"replace","value":"SBSDKPDFImageExtractor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/fragments","op":"replace","value":[{"text":"SBSDKPDFImageExtractor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor~1scaleFactor\/title","op":"replace","value":"scaleFactor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPDFImageExtractor~1scaleFactor\/fragments","op":"replace","value":[{"kind":"identifier","text":"scaleFactor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}