{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardScannerViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","text":"SBSDKCreditCardScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanCreditCard"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","text":"SBSDKCreditCardScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"result","content":[{"inlineContent":[{"type":"text","text":"The scanned credit card result."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate\/creditcardscannerviewcontroller(_:didscancreditcard:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate\/creditcardscannerviewcontroller(_:didscancreditcard:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate"]]},"sections":[],"abstract":[{"text":"Informs the delegate that the scanner has scanned a credit card.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewController(_:didScanCreditCard:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCreditCardScannerViewControllerDelegate(im)creditCardScannerViewController:didScanCreditCard:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardScannerViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","text":"SBSDKCreditCardScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanCreditCard"},{"kind":"text","text":": "},{"text":"SBSDKCreditCardScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"creditCardScannerViewController:didScanCreditCard:","kind":"identifier"}],"title":"creditCardScannerViewController(_:didScanCreditCard:)","required":true},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewControllerDelegate/creditCardScannerViewController(_:didScanCreditCard:)":{"title":"creditCardScannerViewController(_:didScanCreditCard:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate\/creditCardScannerViewController(_:didScanCreditCard:)","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate\/creditcardscannerviewcontroller(_:didscancreditcard:)","type":"topic","abstract":[{"type":"text","text":"Informs the delegate that the scanner has scanned a credit card."}],"required":true,"navigatorTitle":[{"text":"creditCardScannerViewController:didScanCreditCard:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCreditCardScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanCreditCard","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCreditCardScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewController":{"type":"topic","title":"SBSDKCreditCardScannerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScannerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan credit cards."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult":{"role":"symbol","title":"SBSDKCreditCardScanningResult","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult","navigatorTitle":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult","abstract":[{"type":"text","text":"Contains the result of running the credit card scanner."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScannerViewControllerDelegate":{"type":"topic","title":"SBSDKCreditCardScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewControllerDelegate","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscannerviewcontrollerdelegate","navigatorTitle":[{"text":"SBSDKCreditCardScannerViewControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegate protocol for the "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","type":"reference"},{"text":".","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"creditCardScannerViewController:didScanCreditCard:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"creditCardScannerViewController:didScanCreditCard:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"creditCardScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScannerViewController","text":"SBSDKCreditCardScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didScanCreditCard:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","text":"SBSDKCreditCardScanningResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calling "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}]}]},{"name":"result","content":[{"inlineContent":[{"text":"The scanned credit card result.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"creditCardScannerViewController:didScanCreditCard:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate~1creditCardScannerViewController(_:didScanCreditCard:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"creditCardScannerViewController:didScanCreditCard:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate~1creditCardScannerViewController(_:didScanCreditCard:)\/fragments","op":"replace"},{"value":"SBSDKCreditCardScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/title","op":"replace"},{"value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKCreditCardScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewController\/navigatorTitle","op":"replace"},{"value":"SBSDKCreditCardScanningResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScanningResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScanningResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/navigatorTitle","op":"replace"},{"value":"SBSDKCreditCardScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"SBSDKCreditCardScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/fragments","op":"replace"},{"value":[{"text":"SBSDKCreditCardScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScannerViewControllerDelegate\/navigatorTitle","op":"replace"}]}]}