{"sections":[],"metadata":{"role":"symbol","title":"beginStreamingEncryptWithContext:error:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAESEncrypter(im)beginStreamingEncryptWithContext:error:","navigatorTitle":[{"text":"beginStreamingEncryptWithContext:error:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"beginStreamingEncryptWithContext:error:","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter\/beginstreamingencryptwithcontext:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter\/beginStreamingEncryptWithContext:error:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"beginStreamingEncryptWithContext:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"context","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypter":{"title":"SBSDKAESEncrypter","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter","abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."},{"text":" ","type":"text"},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAESEncrypter/beginStreamingEncryptWithContext:error:":{"abstract":[],"title":"beginStreamingEncryptWithContext:error:","fragments":[{"text":"- ","kind":"text"},{"text":"beginStreamingEncryptWithContext:error:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"beginStreamingEncryptWithContext:error:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkaesencrypter\/beginstreamingencryptwithcontext:error:","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAESEncrypter\/beginStreamingEncryptWithContext:error:","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/title","op":"replace","value":"SBSDKAESEncrypter"},{"op":"replace","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/fragments"},{"value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAESEncrypter\/navigatorTitle"}]}]}