{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/photo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/photo"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Select the photo preset for best quality when capturing images.","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionPhoto","symbolKind":"case","title":"SBSDKVideoFrameResolution.photo"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/photo","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution/photo":{"title":"SBSDKVideoFrameResolution.photo","abstract":[{"type":"text","text":"Select the photo preset for best quality when capturing images."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionPhoto"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/photo","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/photo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"photo"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution":{"title":"SBSDKVideoFrameResolution","url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKVideoFrameResolutionPhoto","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKVideoFrameResolutionPhoto","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1photo\/title"},{"op":"replace","value":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1photo\/fragments"},{"op":"replace","value":"SBSDKVideoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/title"},{"op":"replace","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/navigatorTitle"}]}]}