{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/removepage(_:onerror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/removepage(_:onerror:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removePage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"page"},{"kind":"text","text":": "},{"text":"SBSDKScannedPage","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onError"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","kind":"typeIdentifier","text":"SBSDKScannedPage"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":") -> ())? = nil)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"page","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page to be removed."}]}]},{"name":"onError","content":[{"inlineContent":[{"type":"text","text":"A block being executed in case the deletion of the page failed."}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument\/removePage(_:onError:)"},"abstract":[{"text":"Removes a page from the receiver.","type":"text"}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removePage"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage","kind":"typeIdentifier","text":"SBSDKScannedPage"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKScannedPage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":") -> ())?)","kind":"text"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedDocument(im)removePage:onError:","navigatorTitle":[{"text":"removePage:onError:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"removePage(_:onError:)"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedDocument":{"title":"SBSDKScannedDocument","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKScannedDocument","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument","abstract":[{"text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedDocument/removePage(_:onError:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedDocument\/removePage(_:onError:)","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanneddocument\/removepage(_:onerror:)","abstract":[{"type":"text","text":"Removes a page from the receiver."}],"title":"removePage(_:onError:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removePage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage","text":"SBSDKScannedPage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onError"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage","text":"SBSDKScannedPage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> ())?)"}],"navigatorTitle":[{"kind":"identifier","text":"removePage:onError:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScannedPage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPage","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscannedpage","role":"symbol","title":"SBSDKScannedPage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPage"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","abstract":[{"text":"A scanned page (","type":"text"},{"type":"codeVoice","code":"SBSDKScannedPage"},{"text":") is a representation of a scanned documents page in digital form.","type":"text"},{"type":"text","text":" "},{"text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"removePage:onError:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removePage:onError:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"removePage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","kind":"typeIdentifier","text":"SBSDKScannedPage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"page"},{"text":" ","kind":"text"},{"text":"onError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKScannedPage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScannedPage","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScannedPage"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"onError","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"page","content":[{"inlineContent":[{"text":"The page to be removed.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A block being executed in case the deletion of the page failed.","type":"text"}]}],"name":"onError"}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument"},{"value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/fragments"},{"value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument\/navigatorTitle"},{"op":"replace","value":"removePage:onError:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument~1removePage(_:onError:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedDocument~1removePage(_:onError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removePage:onError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/title","value":"SBSDKScannedPage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/fragments","op":"replace","value":[{"text":"SBSDKScannedPage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScannedPage\/navigatorTitle","value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}