{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator\/isEqual:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPatternContentValidator(im)isEqual:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternContentValidator":{"url":"\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Pattern content validator."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPatternContentValidator","kind":"identifier"}],"title":"SBSDKPatternContentValidator","navigatorTitle":[{"kind":"identifier","text":"SBSDKPatternContentValidator"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPatternContentValidator/isEqual:":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpatterncontentvalidator\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPatternContentValidator\/isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/title","value":"SBSDKPatternContentValidator"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPatternContentValidator"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPatternContentValidator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPatternContentValidator"}]}]}]}