{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration\/init(visible:title:accessibilitydescription:background:icon:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration\/init(visible:title:accessibilitydescription:background:icon:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"]]},"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration(im)initWithVisible:title:accessibilityDescription:background:icon:","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"visible","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"background","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle"},{"kind":"text","text":", "},{"text":"icon","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","kind":"typeIdentifier","text":"SBSDKUI2IconStyle"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"text":"initWithVisible:title:accessibilityDescription:background:icon:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"init(visible:title:accessibilityDescription:background:icon:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration\/init(visible:title:accessibilityDescription:background:icon:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"visible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(), ","kind":"text"},{"text":"accessibilityDescription","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" = \"\", ","kind":"text"},{"text":"background","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","text":"SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2BackgroundStyle(), "},{"text":"icon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2IconStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle"},{"kind":"text","text":" = SBSDKUI2IconStyle())"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration/init(visible:title:accessibilityDescription:background:icon:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration\/init(visible:title:accessibilityDescription:background:icon:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"visible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"text":"accessibilityDescription","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"background","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2BackgroundStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle"},{"kind":"text","text":", "},{"text":"icon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2IconStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle"},{"text":")","kind":"text"}],"title":"init(visible:title:accessibilityDescription:background:icon:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithVisible:title:accessibilityDescription:background:icon:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration\/init(visible:title:accessibilitydescription:background:icon:)","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration":{"abstract":[{"type":"text","text":"Button configuration."}],"title":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","role":"symbol","type":"topic","title":"SBSDKUI2StyledText","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconStyle":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configuration of the icon appearance.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconstyle","role":"symbol","title":"SBSDKUI2IconStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BackgroundStyle":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"title":"SBSDKUI2BackgroundStyle","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2backgroundstyle","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","abstract":[{"type":"text","text":"Appearance of the polygon used for buttons and hint backgrounds."}],"navigatorTitle":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithVisible:title:accessibilityDescription:background:icon:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithVisible:title:accessibilityDescription:background:icon:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVisible:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"visible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"title:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescription:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescription"},{"text":" ","kind":"text"},{"text":"background:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"background"},{"text":" ","kind":"text"},{"text":"icon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2IconStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"icon","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration~1init(visible:title:accessibilityDescription:background:icon:)\/title","op":"replace","value":"initWithVisible:title:accessibilityDescription:background:icon:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration~1init(visible:title:accessibilityDescription:background:icon:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithVisible:title:accessibilityDescription:background:icon:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/title","op":"replace","value":"SBSDKUI2BarButtonConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/fragments","value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"value":"SBSDKUI2IconStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/fragments","op":"replace","value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/title","value":"SBSDKUI2BackgroundStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/fragments","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}