{"sections":[],"abstract":[{"type":"text","text":"Select the photo preset for best quality when capturing images."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/photo"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/photo"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/photo","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"photo","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"title":"SBSDKVideoFrameResolution.photo","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionPhoto","symbolKind":"case","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"photo","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution/photo":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"photo","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution\/photo","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution\/photo","title":"SBSDKVideoFrameResolution.photo","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionPhoto"}],"abstract":[{"text":"Select the photo preset for best quality when capturing images.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKVideoFrameResolution":{"type":"topic","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"title":"SBSDKVideoFrameResolution","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkvideoframeresolution","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKVideoFrameResolution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVideoFrameResolutionPhoto"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionPhoto"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionPhoto"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKVideoFrameResolutionPhoto","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1photo\/title","op":"replace"},{"value":[{"text":"SBSDKVideoFrameResolutionPhoto","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution~1photo\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/title","op":"replace","value":"SBSDKVideoFrameResolution"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}]},{"value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKVideoFrameResolution\/navigatorTitle","op":"replace"}]}]}