{"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar(im)initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","navigatorTitle":[{"text":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRetakeButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"retakeButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acceptWhenOkButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"acceptWhenOkButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acceptWhenNotOkButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"text":" *) ","kind":"text"},{"text":"acceptWhenNotOkButton","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar\/initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar\/initwithretakebutton:acceptwhenokbutton:acceptwhennotokbutton:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementBottomBar":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","abstract":[{"type":"text","text":"Configuration of the bottom bar for the acknowledgement screen."}],"title":"SBSDKUI2AcknowledgementBottomBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementBottomBar/initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar\/initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","title":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithRetakeButton:acceptWhenOkButton:acceptWhenNotOkButton:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar\/initwithretakebutton:acceptwhenokbutton:acceptwhennotokbutton:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration":{"title":"SBSDKUI2BarButtonConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration","abstract":[{"type":"text","text":"Configuration of the button located on a bar."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/title","op":"replace","value":"SBSDKUI2AcknowledgementBottomBar"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/title","op":"replace","value":"SBSDKUI2BarButtonConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}