{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/threeLineMrzFinderLayoutPreset()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset(cm)threeLineMrzFinderLayoutPreset","title":"threeLineMrzFinderLayoutPreset()","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"threeLineMrzFinderLayoutPreset","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ThreeLineMRZFinderLayoutPreset"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ThreeLineMRZFinderLayoutPreset","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/threelinemrzfinderlayoutpreset()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/threelinemrzfinderlayoutpreset()"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","title":"SBSDKUI2MRZFinderLayoutPreset","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"abstract":[{"text":"Source of the text for the MRZ finder example overlay.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ThreeLineMRZFinderLayoutPreset":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2threelinemrzfinderlayoutpreset","title":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"abstract":[{"text":"A ready-to-use preset 3-line text to be displayed.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/threeLineMrzFinderLayoutPreset()":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"}],"title":"threeLineMrzFinderLayoutPreset()","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ThreeLineMRZFinderLayoutPreset","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/threelinemrzfinderlayoutpreset()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/threeLineMrzFinderLayoutPreset()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"threeLineMrzFinderLayoutPreset"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"threeLineMrzFinderLayoutPreset","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ThreeLineMRZFinderLayoutPreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ThreeLineMRZFinderLayoutPreset"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/title","op":"replace","value":"SBSDKUI2MRZFinderLayoutPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/fragments","op":"replace","value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2MRZFinderLayoutPreset","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/title","op":"replace","value":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ThreeLineMRZFinderLayoutPreset\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ThreeLineMRZFinderLayoutPreset"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1threeLineMrzFinderLayoutPreset()\/title","op":"replace","value":"threeLineMrzFinderLayoutPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1threeLineMrzFinderLayoutPreset()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"threeLineMrzFinderLayoutPreset"}]}]}]}