{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"abstract":[{"text":"Disables auto-focus and locks the lens at the specified focus lens position. The default value is ","type":"text"},{"type":"codeVoice","code":"False"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannergeneralconfiguration\/isfocuslockenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannergeneralconfiguration\/isfocuslockenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerGeneralConfiguration\/isFocusLockEnabled"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFocusLockEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFocusLockEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isFocusLockEnabled","role":"symbol","navigatorTitle":[{"text":"isFocusLockEnabled","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)isFocusLockEnabled","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerGeneralConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerGeneralConfiguration","role":"symbol","abstract":[{"type":"text","text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."}],"kind":"symbol","title":"SBSDKBaseScannerGeneralConfiguration","navigatorTitle":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannergeneralconfiguration","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerGeneralConfiguration/isFocusLockEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFocusLockEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerGeneralConfiguration\/isFocusLockEnabled","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannergeneralconfiguration\/isfocuslockenabled","title":"isFocusLockEnabled","navigatorTitle":[{"text":"isFocusLockEnabled","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Disables auto-focus and locks the lens at the specified focus lens position. The default value is ","type":"text"},{"code":"False","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isFocusLockEnabled","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isFocusLockEnabled","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isFocusLockEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/title","value":"SBSDKBaseScannerGeneralConfiguration","op":"replace"},{"value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration~1isFocusLockEnabled\/title","value":"isFocusLockEnabled","op":"replace"},{"value":[{"text":"isFocusLockEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerGeneralConfiguration~1isFocusLockEnabled\/fragments"}]}]}