{"sections":[],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerBehaviorConfiguration(py)shouldAnimateZooming","title":"shouldAnimateZooming","roleHeading":"Instance Property","navigatorTitle":[{"text":"shouldAnimateZooming","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldAnimateZooming","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","platforms":[]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/shouldAnimateZooming","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldAnimateZooming"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"abstract":[{"type":"text","text":"Defines, if zooming in or out should be animated."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/shouldanimatezooming"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/shouldanimatezooming"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration/shouldAnimateZooming":{"deprecated":true,"title":"shouldAnimateZooming","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/shouldAnimateZooming","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration\/shouldanimatezooming","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldAnimateZooming","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Defines, if zooming in or out should be animated."}],"role":"symbol","navigatorTitle":[{"text":"shouldAnimateZooming","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerBehaviorConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscannerbehaviorconfiguration","deprecated":true,"title":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerBehaviorConfiguration","role":"symbol","abstract":[{"type":"text","text":"The configuration for the behavior of RTU-UI detector screens for barcodes."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"shouldAnimateZooming","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"shouldAnimateZooming","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"shouldAnimateZooming","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"shouldAnimateZooming","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1shouldAnimateZooming\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration~1shouldAnimateZooming\/fragments","op":"replace","value":[{"kind":"identifier","text":"shouldAnimateZooming"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration"},{"value":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerBehaviorConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}