{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"points","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"on"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"points","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon to be applied, described as array of 4 points."}]}]},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image to bre cropped.","type":"text"}]}]}],"kind":"parameters"}],"metadata":{"role":"symbol","title":"applyCrop(points:on:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"kind":"text","text":"("},{"text":"points","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProcessor(cm)applyCropWithPoints:on:","navigatorTitle":[{"text":"applyCropWithPoints:on:","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(points:on:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(points:on:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:on:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Crops an image by the given polygon and performs perspective correction."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyCrop(points:on:)":{"title":"applyCrop(points:on:)","navigatorTitle":[{"kind":"identifier","text":"applyCropWithPoints:on:"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(points:on:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:on:)","abstract":[{"type":"text","text":"Crops an image by the given polygon and performs perspective correction."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","title":"SBSDKImageRef","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref","type":"topic","abstract":[{"type":"text","text":"Image ref class."}],"navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKImageProcessor","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to process images."}],"type":"topic","title":"SBSDKImageProcessor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"applyCropWithPoints:on:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"applyCropWithPoints:on:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"applyCropWithPoints:"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"points","kind":"internalParam"},{"kind":"text","text":" "},{"text":"on:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"points","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon to be applied, described as array of 4 points."}]}]},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image to bre cropped.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"applyCropWithPoints:on:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(points:on:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(points:on:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"applyCropWithPoints:on:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","op":"replace","value":"SBSDKImageRef"},{"op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/title","op":"replace","value":"SBSDKImageProcessor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/fragments","value":[{"text":"SBSDKImageProcessor","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}