{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(points:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(points:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Crops the input image by the given polygon and performs perspective correction.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"method","title":"applyCrop(points:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"points"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"applyCropWithPoints:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageProcessor(im)applyCropWithPoints:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"text":"points","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"points","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon to be applied, described as array of 4 unit-coordinate points (x: 0.0…1.0, y: 0.0…1.0)."}]}]}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor/applyCrop(points:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor\/applyCrop(points:)","title":"applyCrop(points:)","kind":"symbol","abstract":[{"text":"Crops the input image by the given polygon and performs perspective correction.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"applyCropWithPoints:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"applyCrop","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"points"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor\/applycrop(points:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageProcessor":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageProcessor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKImageProcessor","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to process images."}],"type":"topic","title":"SBSDKImageProcessor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageProcessor","url":"\/documentation\/scanbotsdk\/sbsdkimageprocessor","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"applyCropWithPoints:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"applyCropWithPoints:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"applyCropWithPoints:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSValue *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"points"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"points","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The polygon to be applied, described as array of 4 unit-coordinate points (x: 0.0…1.0, y: 0.0…1.0)."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"applyCropWithPoints:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(points:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"applyCropWithPoints:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor~1applyCrop(points:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/title","value":"SBSDKImageProcessor","op":"replace"},{"value":[{"text":"SBSDKImageProcessor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageProcessor\/navigatorTitle","value":[{"text":"SBSDKImageProcessor","kind":"identifier"}]}]}]}