{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelRootType"],"type":"inheritedBy","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKGenericDocumentType) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/init(name:fullName:normalizedName:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/displayText","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/fullName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/listIndex","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/name","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/normalizedName"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/toJson(configuration:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/defaultDocumentTypeDisplayTexts","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/userDocumentTypeDisplayTexts"],"anchor":"Type-Properties","generated":true}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"roleHeading":"Class","title":"SBSDKGenericDocumentType","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentType"}],"role":"symbol","symbolKind":"class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"abstract":[{"text":"Generic Document Type.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/toJson(configuration:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"title":"toJson(configuration:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/tojson(configuration:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelRootType":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelroottype","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelRootType"}],"title":"SBSDKBarcodeDocumentModelRootType","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelRootType"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelRootType","abstract":[{"text":"Root document type.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/normalizedName":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"text":"Normalized global document type name. Common document types appearing as child documents in different places","type":"text"},{"text":" ","type":"text"},{"text":"will often have the same normalized type name.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/normalizedName","title":"normalizedName","navigatorTitle":[{"kind":"identifier","text":"normalizedName"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/normalizedname"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/initWithName:fullName:normalizedName:listIndex:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/initwithname:fullname:normalizedname:listindex:","title":"initWithName:fullName:normalizedName:listIndex:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:fullName:normalizedName:listIndex:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithName:fullName:normalizedName:listIndex:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/initWithName:fullName:normalizedName:listIndex:","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/fullName":{"title":"fullName","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/fullName","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/fullname","navigatorTitle":[{"text":"fullName","kind":"identifier"}],"abstract":[{"type":"text","text":"Unique global document type name prefixed with the document types of all containing documents."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/name":{"navigatorTitle":[{"kind":"identifier","text":"name"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/name","title":"name","abstract":[{"text":"Local document type name.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/name","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/hash":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/hash","fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol","title":"hash","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/hash","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType":{"abstract":[{"type":"text","text":"Generic Document Type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"kind":"symbol","title":"SBSDKGenericDocumentType","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/fromjsonwithjson:","title":"fromJsonWithJson:","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/fromJsonWithJson:","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/isEqual:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/isEqual:","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/isequal:","role":"symbol","title":"isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/copyWithZone:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/copywithzone:","role":"symbol","abstract":[],"kind":"symbol","title":"copyWithZone:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/displayText":{"title":"displayText","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayText","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/displayText","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/displaytext","kind":"symbol","abstract":[{"text":"The friendly, human-readable display name of this document type in English.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/listIndex":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/listindex","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/listIndex","navigatorTitle":[{"text":"listIndex","kind":"identifier"}],"kind":"symbol","title":"listIndex","abstract":[{"text":"A document can contain multiple fields of the same name, the property serves for storing natural order of such","type":"text"},{"text":" ","type":"text"},{"text":"fields, null if multiple entries aren’t allowed for this field.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/defaultDocumentTypeDisplayTexts":{"abstract":[{"text":"A dictionary of the default display strings for generic document types.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultDocumentTypeDisplayTexts","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/defaultDocumentTypeDisplayTexts","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/defaultdocumenttypedisplaytexts","title":"defaultDocumentTypeDisplayTexts"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/init(name:fullName:normalizedName:)":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/init(name:fullName:normalizedName:)","title":"init(name:fullName:normalizedName:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fullName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"normalizedName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithName:fullName:normalizedName:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/init(name:fullname:normalizedname:)","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentType/userDocumentTypeDisplayTexts":{"role":"symbol","title":"userDocumentTypeDisplayTexts","abstract":[{"text":"A dictionary of the default display strings for generic document types.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDocumentTypeDisplayTexts"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumenttype\/userdocumenttypedisplaytexts","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/userDocumentTypeDisplayTexts"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGenericDocumentType"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/fullName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/hash","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/listIndex","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/name","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/normalizedName"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/copyWithZone:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/init(name:fullName:normalizedName:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/initWithName:fullName:normalizedName:listIndex:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/isEqual:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/toJson(configuration:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentType\/fromJsonWithJson:"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Inherited By","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelRootType"],"type":"inheritedBy","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1toJson(configuration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1toJson(configuration:)\/fragments","op":"replace"},{"value":"SBSDKBarcodeDocumentModelRootType","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelRootType\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentModelRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelRootType\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentModelRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelRootType\/navigatorTitle","op":"replace"},{"value":"normalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1normalizedName\/title","op":"replace"},{"value":[{"kind":"identifier","text":"normalizedName"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1normalizedName\/fragments","op":"replace"},{"value":"fullName","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1fullName\/title","op":"replace"},{"value":[{"text":"fullName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1fullName\/fragments","op":"replace"},{"value":"name","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1name\/title","op":"replace"},{"value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1name\/fragments","op":"replace"},{"value":"SBSDKGenericDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType\/fragments","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType\/navigatorTitle","op":"replace"},{"value":"listIndex","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1listIndex\/title","op":"replace"},{"value":[{"kind":"identifier","text":"listIndex"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1listIndex\/fragments","op":"replace"},{"value":"initWithName:fullName:normalizedName:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1init(name:fullName:normalizedName:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:fullName:normalizedName:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentType~1init(name:fullName:normalizedName:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}