{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI"},"metadata":{"navigatorTitle":[{"text":"ScanbotUI","kind":"identifier"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)ScanbotUI","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"ScanbotUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanbotUI"}],"roleHeading":"Class"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanbotUI","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Helper class to configure the properties of the ScanbotSDK RTU-UI (SBSDKUI) components.","type":"text"}],"topicSections":[{"anchor":"Type-Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultImageStoreEncrypter","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultPDFEncrypter","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultStatusBarStyle","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/shouldShowStatusBarOnScanningScreens"],"generated":true,"title":"Type Properties"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotui"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/scanbotui"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotUI/init":{"title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotui\/init"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotUI/defaultPDFEncrypter":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultPDFEncrypter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"defaultPDFEncrypter","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The SBSDKUI-component-wide encrypter for storing PDF files to disk. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"defaultPDFEncrypter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultPDFEncrypter","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotui\/defaultpdfencrypter"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotUI/defaultStatusBarStyle":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultStatusBarStyle","kind":"symbol","title":"defaultStatusBarStyle","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotui\/defaultstatusbarstyle","abstract":[{"type":"text","text":"The default status bar style of all ScanbotSDK RTU-UI components upon their initialization. Defaults to "},{"type":"codeVoice","code":".lightContent"},{"type":"text","text":"."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"defaultStatusBarStyle","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotUI/defaultImageStoreEncrypter":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultImageStoreEncrypter","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/scanbotui\/defaultimagestoreencrypter","navigatorTitle":[{"kind":"identifier","text":"defaultImageStoreEncrypter"}],"title":"defaultImageStoreEncrypter","abstract":[{"type":"text","text":"The SBSDKUI-component-wide encrypter for storing image data to disk. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImageStoreEncrypter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"SBSDKStorageCrypting"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotUI/shouldShowStatusBarOnScanningScreens":{"url":"\/documentation\/scanbotbarcodescannersdk\/scanbotui\/shouldshowstatusbaronscanningscreens","role":"symbol","navigatorTitle":[{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/shouldShowStatusBarOnScanningScreens","title":"shouldShowStatusBarOnScanningScreens","abstract":[{"type":"text","text":"A Boolean value that determines whether the status bar is shown on scanning screens. Defaults to "},{"type":"codeVoice","code":"False"},{"type":"text","text":"."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldShowStatusBarOnScanningScreens","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/ScanbotUI":{"kind":"symbol","abstract":[{"type":"text","text":"Helper class to configure the properties of the ScanbotSDK RTU-UI (SBSDKUI) components."}],"url":"\/documentation\/scanbotbarcodescannersdk\/scanbotui","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanbotUI","kind":"identifier"}],"type":"topic","title":"ScanbotUI","navigatorTitle":[{"text":"ScanbotUI","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ScanbotUI","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ScanbotUI","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ScanbotUI"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/init"]},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultImageStoreEncrypter","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultPDFEncrypter","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/defaultStatusBarStyle","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/ScanbotUI\/shouldShowStatusBarOnScanningScreens"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanbotUI"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI~1defaultPDFEncrypter\/title","value":"defaultPDFEncrypter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI~1defaultPDFEncrypter\/fragments","value":[{"text":"defaultPDFEncrypter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI~1defaultStatusBarStyle\/title","value":"defaultStatusBarStyle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI~1defaultStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"defaultStatusBarStyle"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI~1defaultImageStoreEncrypter\/title","value":"defaultImageStoreEncrypter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI~1defaultImageStoreEncrypter\/fragments","value":[{"text":"defaultImageStoreEncrypter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI~1shouldShowStatusBarOnScanningScreens\/title","value":"shouldShowStatusBarOnScanningScreens","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI~1shouldShowStatusBarOnScanningScreens\/fragments","value":[{"kind":"identifier","text":"shouldShowStatusBarOnScanningScreens"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI\/title","value":"ScanbotUI","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI\/fragments","value":[{"kind":"identifier","text":"ScanbotUI"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1ScanbotUI\/navigatorTitle","value":[{"text":"ScanbotUI","kind":"identifier"}],"op":"replace"}]}]}