{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayText"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"displayText(forDocumentType:)","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerTextConfiguration(im)displayTextForDocumentType:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"displayTextForDocumentType:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(displayTextForDocumentType:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayText"},{"kind":"text","text":"("},{"text":"forDocumentType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"documentType","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"documentType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the document."}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The text displayed for the given document type.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"A convenience method to get the text displayed for the given document type."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/displaytext(fordocumenttype:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/displaytext(fordocumenttype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration\/displayText(forDocumentType:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration/displayText(forDocumentType:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration\/displayText(forDocumentType:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"displayText","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forDocumentType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/displaytext(fordocumenttype:)","title":"displayText(forDocumentType:)","abstract":[{"text":"A convenience method to get the text displayed for the given document type.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"displayTextForDocumentType:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration","title":"SBSDKUIGenericDocumentRecognizerTextConfiguration","abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI generic document recognizer screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"displayTextForDocumentType:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"displayTextForDocumentType:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"displayTextForDocumentType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"documentType"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"documentType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the document."}]}]}],"kind":"parameters"}},{"value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The text displayed for the given document type.","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"displayTextForDocumentType:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration~1displayText(forDocumentType:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration~1displayText(forDocumentType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayTextForDocumentType:"}],"op":"replace"},{"value":"SBSDKUIGenericDocumentRecognizerTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/title"},{"value":[{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}