{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerTextConfiguration(im)init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","title":"init"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/init"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration\/init","abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration":{"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"symbol","role":"symbol","title":"SBSDKUIGenericDocumentRecognizerTextConfiguration","abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI generic document recognizer screen."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}]}]}]}