{"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","title":"availableDevices(for:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition","text":"SBSDKCameraDevicePosition"},{"text":") -> [","kind":"text"},{"text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"availableDevicesForPosition:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice(cm)availableDevicesForPosition:"},"abstract":[{"text":"Returns a list of all available and supported cameras of the device at the given position.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(availableDevicesForPosition:) ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableDevices"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"position","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition","text":"SBSDKCameraDevicePosition","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition"},{"text":") -> [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","kind":"typeIdentifier","text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The position of the requested cameras: front or back.","type":"text"}]}],"name":"position"}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of the supported available cameras of the current device for the given position."}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:)-9q6l6"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:)-9q6l6"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-9q6l6","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice/availableDevices(for:)-9q6l6":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"availableDevicesForPosition:"}],"abstract":[{"text":"Returns a list of all available and supported cameras of the device at the given position.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition","kind":"typeIdentifier","text":"SBSDKCameraDevicePosition"},{"kind":"text","text":") -> ["},{"text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraDevice","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevice\/availabledevices(for:)-9q6l6","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice\/availableDevices(for:)-9q6l6","title":"availableDevices(for:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCameraSession","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"title":"SBSDKCameraSession","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevicePosition":{"title":"SBSDKCameraDevicePosition","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition","url":"\/documentation\/scanbotsdk\/sbsdkcameradeviceposition","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraDevicePosition"}],"abstract":[{"type":"text","text":"An enum to describe the physical position of a camera device."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDevice":{"abstract":[{"type":"text","text":"The camera device to be used with a "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","type":"reference"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevice","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraDevice"}],"title":"SBSDKCameraDevice","navigatorTitle":[{"text":"SBSDKCameraDevice","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcameradevice"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"availableDevicesForPosition:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"availableDevicesForPosition:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<SBSDKCameraDevice *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"availableDevicesForPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCameraDevicePosition","text":"SBSDKCameraDevicePosition","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDevicePosition"},{"text":") ","kind":"text"},{"text":"position","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"position","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The position of the requested cameras: front or back."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of the supported available cameras of the current device for the given position."}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:)-9q6l6\/title","value":"availableDevicesForPosition:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"availableDevicesForPosition:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice~1availableDevices(for:)-9q6l6\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title","op":"replace","value":"SBSDKCameraSession"},{"value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"op":"replace"},{"value":"SBSDKCameraDevicePosition","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/fragments","value":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevicePosition\/navigatorTitle","value":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}],"op":"replace"},{"value":"SBSDKCameraDevice","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCameraDevice"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDevice\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}