{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemSubtitle"},"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent(py)barcodeItemSubtitle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemSubtitle"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeItemSubtitle"}],"modules":[{"name":"ScanbotSDK"}],"title":"barcodeItemSubtitle","symbolKind":"property"},"abstract":[{"text":"Configuration of the subtitle of a barcode list entry (displaying the barcode’s symbology).","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeItemSubtitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/barcodeitemsubtitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/barcodeitemsubtitle"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2StyledText"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","title":"SBSDKUI2SheetContent","navigatorTitle":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent/barcodeItemSubtitle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent\/barcodeItemSubtitle","abstract":[{"type":"text","text":"Configuration of the subtitle of a barcode list entry (displaying the barcode’s symbology)."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent\/barcodeitemsubtitle","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"barcodeItemSubtitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeItemSubtitle"}],"title":"barcodeItemSubtitle","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"barcodeItemSubtitle","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"barcodeItemSubtitle"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" * ","kind":"text"},{"text":"barcodeItemSubtitle","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2SheetContent","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1barcodeItemSubtitle\/title","value":"barcodeItemSubtitle","op":"replace"},{"value":[{"text":"barcodeItemSubtitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent~1barcodeItemSubtitle\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}