{"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please consider using the new class-based SBSDKParametricFilters."}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/blackandwhite"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/blackandwhite"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/blackAndWhite","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"blackAndWhite","kind":"identifier"}],"platforms":[],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeBlackAndWhite","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBlackAndWhite"}],"title":"SBSDKImageFilterType.blackAndWhite","roleHeading":"Case","symbolKind":"case"},"abstract":[{"type":"text","text":"Black and white filter with background cleaning. Creates a grayscaled 8-bit image with mostly black or white pixels."},{"text":" ","type":"text"},{"type":"text","text":"Usecase: Textual documents or documents with black and white illustrations."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"blackAndWhite"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/blackAndWhite":{"role":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"blackAndWhite","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/blackAndWhite","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/blackandwhite","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeBlackAndWhite"}],"title":"SBSDKImageFilterType.blackAndWhite","abstract":[{"type":"text","text":"Black and white filter with background cleaning. Creates a grayscaled 8-bit image with mostly black or white pixels."},{"type":"text","text":" "},{"type":"text","text":"Usecase: Textual documents or documents with black and white illustrations."}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"abstract":[{"text":"The ScanbotSDK image filter types.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageFilterType","kind":"identifier"}],"title":"SBSDKImageFilterType","kind":"symbol","deprecated":true,"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageFilterTypeBlackAndWhite"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterTypeBlackAndWhite"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKImageFilterTypeBlackAndWhite"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1blackAndWhite\/title","value":"SBSDKImageFilterTypeBlackAndWhite"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1blackAndWhite\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeBlackAndWhite"}]},{"value":"SBSDKImageFilterType","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageFilterType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}