{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Please consider using the new class-based SBSDKParametricFilters.","type":"text"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otsuBinarization","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/otsubinarization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/otsubinarization"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/otsuBinarization"},"kind":"symbol","abstract":[{"text":"A filter for black and white conversion using OTSU binarization.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeOtsuBinarization"}],"platforms":[],"title":"SBSDKImageFilterType.otsuBinarization","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"otsuBinarization"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeOtsuBinarization","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Case","symbolKind":"case","role":"symbol"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/otsuBinarization":{"navigatorTitle":[{"text":"SBSDKImageFilterTypeOtsuBinarization","kind":"identifier"}],"deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"otsuBinarization","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/otsubinarization","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/otsuBinarization","title":"SBSDKImageFilterType.otsuBinarization","kind":"symbol","type":"topic","abstract":[{"text":"A filter for black and white conversion using OTSU binarization.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType":{"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype","deprecated":true,"navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"title":"SBSDKImageFilterType","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.1.1","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKImageFilterTypeOtsuBinarization","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeOtsuBinarization"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKImageFilterTypeOtsuBinarization","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKImageFilterTypeOtsuBinarization","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1otsuBinarization\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1otsuBinarization\/fragments","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeOtsuBinarization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/title","value":"SBSDKImageFilterType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/fragments","value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}