{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerConfiguration(im)initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","kind":"identifier"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithQualityThresholds:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKDocumentQualityThreshold *>"},{"text":" *) ","kind":"text"},{"text":"qualityThresholds","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityIndices:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKDocumentQuality *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"qualityIndices"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectOrientation:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"detectOrientation","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"inspectSmallText:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"inspectSmallText"},{"kind":"text","text":" "},{"text":"maxImageSize:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"maxImageSize","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEstimatedNumberOfSymbolsForDocument:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"minEstimatedNumberOfSymbolsForDocument","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minProcessedFraction:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minProcessedFraction"},{"kind":"text","text":" "},{"text":"maxProcessedFraction:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"maxProcessedFraction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"earlyStopIfNSymbolsFound:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"earlyStopIfNSymbolsFound","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"tileSize:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"tileSize","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"returnQualityHeatmap:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"returnQualityHeatmap","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:minprocessedfraction:maxprocessedfraction:earlystopifnsymbolsfound:tilesize:returnqualityheatmap:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration":{"title":"SBSDKDocumentQualityAnalyzerConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration","abstract":[{"type":"text","text":"Document Quality Analyzer configuration."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerConfiguration/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerConfiguration\/initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerconfiguration\/initwithqualitythresholds:qualityindices:detectorientation:inspectsmalltext:maximagesize:minestimatednumberofsymbolsfordocument:minprocessedfraction:maxprocessedfraction:earlystopifnsymbolsfound:tilesize:returnqualityheatmap:","type":"topic","title":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","navigatorTitle":[{"text":"initWithQualityThresholds:qualityIndices:detectOrientation:inspectSmallText:maxImageSize:minEstimatedNumberOfSymbolsForDocument:minProcessedFraction:maxProcessedFraction:earlyStopIfNSymbolsFound:tileSize:returnQualityHeatmap:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKDocumentQualityAnalyzerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerConfiguration\/navigatorTitle","op":"replace"}]}]}