{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/init(totalUnitCount:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress(im)initWithTotalUnitCount:","navigatorTitle":[{"text":"initWithTotalUnitCount:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(totalUnitCount:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"totalUnitCount"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"symbolKind":"init"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprogress\/init(totalunitcount:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkprogress\/init(totalunitcount:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A convenience initializer mimicking the behavior of "},{"type":"codeVoice","code":"Progress"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"totalUnitCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The number of total work units the progress. See ","type":"text"},{"code":"Progress","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"totalUnitCount"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"url":"\/documentation\/scanbotsdk\/sbsdkprogress","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKProgress","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","abstract":[],"role":"symbol","title":"SBSDKProgress","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgress"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/init(totalUnitCount:)":{"title":"init(totalUnitCount:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/init(totalUnitCount:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"totalUnitCount"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"A convenience initializer mimicking the behavior of "},{"type":"codeVoice","code":"Progress"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkprogress\/init(totalunitcount:)","role":"symbol","navigatorTitle":[{"text":"initWithTotalUnitCount:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithTotalUnitCount:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTotalUnitCount:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTotalUnitCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"kind":"text","text":") "},{"text":"totalUnitCount","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title","value":"SBSDKProgress"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKProgress"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments"},{"op":"replace","value":"initWithTotalUnitCount:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1init(totalUnitCount:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTotalUnitCount:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1init(totalUnitCount:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}