{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"localizedAdditionalDescription","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"symbolKind":"property","role":"symbol","fragments":[{"kind":"identifier","text":"localizedAdditionalDescription"}],"modules":[{"name":"ScanbotSDK"}],"title":"localizedAdditionalDescription","roleHeading":"Instance Property","navigatorTitle":[{"text":"localizedAdditionalDescription","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress(py)localizedAdditionalDescription"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/localizedAdditionalDescription","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprogress\/localizedadditionaldescription"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","url":"\/documentation\/scanbotsdk\/sbsdkprogress","title":"SBSDKProgress","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKProgress"}],"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgress"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/localizedAdditionalDescription":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/localizedAdditionalDescription","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprogress\/localizedadditionaldescription","type":"topic","kind":"symbol","fragments":[{"text":"localizedAdditionalDescription","kind":"identifier"}],"title":"localizedAdditionalDescription"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title","op":"replace","value":"SBSDKProgress"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments","value":[{"text":"SBSDKProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProgress"}]}]}]}