{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/updateHandler","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"The standard process for observing a ","type":"text"},{"type":"codeVoice","code":"Progress"},{"type":"text","text":" progressing is to use KVO on the "},{"type":"codeVoice","code":"Progress"},{"type":"text","text":" instance."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"SBSDKProgressUpdateHandler"},{"type":"text","text":" simplifies observing the progress largely."},{"type":"text","text":" "},{"type":"text","text":"It is called on main thread whenever the progress changes. Usually here you update your UI, e.g. "},{"code":"UIProgressView","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"updateHandler","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKProgessUpdateHandler","preciseIdentifier":"s:10ScanbotSDK25SBSDKProgessUpdateHandlera","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgessUpdateHandler","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"updateHandler","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateHandler"},{"kind":"text","text":": "},{"text":"SBSDKProgessUpdateHandler","kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK25SBSDKProgessUpdateHandlera"},{"text":"?","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress(py)updateHandler","navigatorTitle":[{"kind":"identifier","text":"updateHandler"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprogress\/updatehandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkprogress\/updatehandler"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"title":"SBSDKProgress","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKProgress","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgress"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkprogress","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress/updateHandler":{"navigatorTitle":[{"text":"updateHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"The standard process for observing a "},{"code":"Progress","type":"codeVoice"},{"type":"text","text":" progressing is to use KVO on the "},{"type":"codeVoice","code":"Progress"},{"text":" instance.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"SBSDKProgressUpdateHandler"},{"text":" simplifies observing the progress largely.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It is called on main thread whenever the progress changes. Usually here you update your UI, e.g. "},{"code":"UIProgressView","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkprogress\/updatehandler","kind":"symbol","title":"updateHandler","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress\/updateHandler","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKProgessUpdateHandler","preciseIdentifier":"s:10ScanbotSDK25SBSDKProgessUpdateHandlera"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgessUpdateHandler":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKProgessUpdateHandler"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgessUpdateHandler","title":"SBSDKProgessUpdateHandler","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprogessupdatehandler","abstract":[{"type":"text","text":"A closure typealias used on informing observers about progress updating."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKProgessUpdateHandler"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"updateHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"updateHandler"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"identifier","text":"updateHandler"},{"text":")(","kind":"text"},{"text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title","op":"replace","value":"SBSDKProgress"},{"value":[{"text":"SBSDKProgress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1updateHandler\/title","value":"updateHandler"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress~1updateHandler\/fragments","value":[{"text":"updateHandler","kind":"identifier"}]}]}]}