{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"timestampCreated","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"timestampCreated"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRefCountedObjectProfile(py)timestampCreated","role":"symbol","title":"timestampCreated"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"timestampCreated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/timestampCreated"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile"]]},"abstract":[{"type":"text","text":"Timestamp (milliseconds since the UNIX epoch), at which the object was first created."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/timestampcreated"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/timestampcreated"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile":{"abstract":[{"type":"text","text":"Profile info of a reference-counted stored object."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"title":"SBSDKRefCountedObjectProfile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile/timestampCreated":{"kind":"symbol","abstract":[{"text":"Timestamp (milliseconds since the UNIX epoch), at which the object was first created.","type":"text"}],"title":"timestampCreated","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/timestampCreated","url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/timestampcreated","role":"symbol","type":"topic","navigatorTitle":[{"text":"timestampCreated","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"timestampCreated","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"timestampCreated","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"timestampCreated","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier","text":"int64_t"},{"text":" ","kind":"text"},{"text":"timestampCreated","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/title","op":"replace","value":"SBSDKRefCountedObjectProfile"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/fragments","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile~1timestampCreated\/title","value":"timestampCreated","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile~1timestampCreated\/fragments","op":"replace","value":[{"kind":"identifier","text":"timestampCreated"}]}]}]}