{"abstract":[{"text":"Subtitle for the alert when document cannot be processed.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization"]]},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization(py)documentDataExtractorCantProcessDocumentAlertSubtitle","title":"documentDataExtractorCantProcessDocumentAlertSubtitle","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"documentDataExtractorCantProcessDocumentAlertSubtitle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorCantProcessDocumentAlertSubtitle"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentDataExtractorCantProcessDocumentAlertSubtitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Default is “This document doesn’t meet the processing requirements. Please check accepted document types and try"},{"type":"text","text":" "},{"type":"text","text":"again.”"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorcantprocessdocumentalertsubtitle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorcantprocessdocumentalertsubtitle"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorCantProcessDocumentAlertSubtitle"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/documentDataExtractorCantProcessDocumentAlertSubtitle":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorCantProcessDocumentAlertSubtitle"}],"title":"documentDataExtractorCantProcessDocumentAlertSubtitle","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/documentdataextractorcantprocessdocumentalertsubtitle","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/documentDataExtractorCantProcessDocumentAlertSubtitle","abstract":[{"type":"text","text":"Subtitle for the alert when document cannot be processed."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentDataExtractorCantProcessDocumentAlertSubtitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization","abstract":[{"type":"text","text":"Configuration of the all strings for document data extractor screen."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"symbol","title":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"documentDataExtractorCantProcessDocumentAlertSubtitle"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"documentDataExtractorCantProcessDocumentAlertSubtitle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"documentDataExtractorCantProcessDocumentAlertSubtitle","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"documentDataExtractorCantProcessDocumentAlertSubtitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorCantProcessDocumentAlertSubtitle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"documentDataExtractorCantProcessDocumentAlertSubtitle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1documentDataExtractorCantProcessDocumentAlertSubtitle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/title","value":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/navigatorTitle"}]}]}