{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration\/configurations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration\/configurations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfiguration(py)configurations","title":"configurations","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurations"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationElement","kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorConfigurationElement"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"configurations"}]},"abstract":[{"type":"text","text":"List of configuration elements for the document data extractor."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurations","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationElement","text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement"},{"text":">","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration\/configurations","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationElement":{"abstract":[{"type":"text","text":"Base class for all document data extraction configuration elements."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationelement","title":"SBSDKDocumentDataExtractorConfigurationElement","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationElement","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfiguration/configurations":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorConfigurationElement","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationElement"},{"kind":"text","text":">"}],"type":"topic","abstract":[{"text":"List of configuration elements for the document data extractor.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"configurations"}],"title":"configurations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration\/configurations","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration\/configurations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfiguration","abstract":[{"type":"text","text":"Configuration for the document data extractor."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfiguration","kind":"identifier"}],"title":"SBSDKDocumentDataExtractorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"configurations","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"configurations","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKDocumentDataExtractorConfigurationElement *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"configurations","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKDocumentDataExtractorConfigurationElement","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentDataExtractorConfigurationElement","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationElement"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationElement\/navigatorTitle","op":"replace"},{"value":"configurations","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration~1configurations\/title","op":"replace"},{"value":[{"text":"configurations","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration~1configurations\/fragments","op":"replace"},{"value":"SBSDKDocumentDataExtractorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfiguration\/navigatorTitle","op":"replace"}]}]}