{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/hash"},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatMicroPDF417Configuration(py)hash","symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"MicroPDF417 configuration. Add to scanner configuration to scan MicroPDF417 codes."}],"title":"SBSDKBarcodeFormatMicroPDF417Configuration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatMicroPDF417Configuration/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatMicroPDF417Configuration\/hash","title":"hash","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatmicropdf417configuration\/hash","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/title","value":"SBSDKBarcodeFormatMicroPDF417Configuration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatMicroPDF417Configuration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatMicroPDF417Configuration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}