{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewController(im)beginFocusLockAtLensPosition:","navigatorTitle":[{"text":"beginFocusLockAtLensPosition:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginFocusLockAt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lensPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"beginFocusLockAt(lensPosition:)","symbolKind":"method","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":"(beginFocusLockAtLensPosition:) ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginFocusLockAt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lensPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"name":"lensPosition","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The position of the lens. Values can be between 0.0f (minimum focusing distance) and"},{"type":"text","text":" "},{"type":"text","text":"1.0f (maximum focusing distance). The value will be clamped to [0.0f, 1.0f]."}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":", if the attempt to lock the focus was successful, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" if the attempt failed or if focus lock is"},{"type":"text","text":" "},{"type":"text","text":"not available."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/beginFocusLockAt(lensPosition:)"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/beginfocuslockat(lensposition:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/beginfocuslockat(lensposition:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"]]},"abstract":[{"text":"Disables auto-focus and locks the lens at the specified lens position.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController/beginFocusLockAt(lensPosition:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Disables auto-focus and locks the lens at the specified lens position.","type":"text"}],"title":"beginFocusLockAt(lensPosition:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/beginFocusLockAt(lensPosition:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/beginfocuslockat(lensposition:)","navigatorTitle":[{"text":"beginFocusLockAtLensPosition:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beginFocusLockAt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lensPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller","role":"symbol","title":"SBSDKBaseScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"text":"A highly customizable camera view controller that delivers a basic camera functionality along with video","type":"text"},{"text":" ","type":"text"},{"text":"frame extraction and preprocessing, orientation correction and still image capturing.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"beginFocusLockAtLensPosition:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"beginFocusLockAtLensPosition:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"beginFocusLockAtLensPosition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"lensPosition"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"lensPosition","content":[{"inlineContent":[{"text":"The position of the lens. Values can be between 0.0f (minimum focusing distance) and","type":"text"},{"text":" ","type":"text"},{"text":"1.0f (maximum focusing distance). The value will be clamped to [0.0f, 1.0f].","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":", if the attempt to lock the focus was successful, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" if the attempt failed or if focus lock is"},{"type":"text","text":" "},{"type":"text","text":"not available."}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1beginFocusLockAt(lensPosition:)\/title","op":"replace","value":"beginFocusLockAtLensPosition:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1beginFocusLockAt(lensPosition:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"beginFocusLockAtLensPosition:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/title","op":"replace","value":"SBSDKBaseScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]}]}]}