{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPathImageLoadOptions","text":"SBSDKPathImageLoadOptions"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPathImageLoadOptions(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"roleHeading":"Type Method"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions\/fromJsonWithJson:","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathImageLoadOptions":{"kind":"symbol","abstract":[{"type":"text","text":"Options for loading image from path."}],"title":"SBSDKPathImageLoadOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions","url":"\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathImageLoadOptions/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"kind":"symbol","title":"fromJsonWithJson:","abstract":[],"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions\/fromjsonwithjson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions\/fromJsonWithJson:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/title","value":"SBSDKPathImageLoadOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/fragments","value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/navigatorTitle"}]}]}