{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox\/initwithquad:fields:hascontents:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox"]]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox\/initWithQuad:fields:hasContents:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"initWithQuad:fields:hasContents:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalCertificatePatientInfoBox(im)initWithQuad:fields:hasContents:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithQuad:fields:hasContents:"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQuad:fields:hasContents:"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithQuad:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quad"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKMedicalCertificatePatientInfoField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fields"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasContents:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hasContents"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoBox":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoBox"}],"title":"SBSDKMedicalCertificatePatientInfoBox","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoBox"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox","abstract":[{"type":"text","text":"Patient information box."}],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificatePatientInfoBox/initWithQuad:fields:hasContents:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificatePatientInfoBox\/initWithQuad:fields:hasContents:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithQuad:fields:hasContents:","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatepatientinfobox\/initwithquad:fields:hascontents:","navigatorTitle":[{"text":"initWithQuad:fields:hasContents:","kind":"identifier"}],"title":"initWithQuad:fields:hasContents:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/title","value":"SBSDKMedicalCertificatePatientInfoBox","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificatePatientInfoBox"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificatePatientInfoBox\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificatePatientInfoBox","kind":"identifier"}],"op":"replace"}]}]}