{"abstract":[{"type":"text","text":"Initializes a new "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage"},{"text":" at the given storage location with given image file format.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","kind":"identifier"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKIndexedImageStorage(im)initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":", "},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"text":"encryptedImagesURLs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation","text":"SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageFileFormat","kind":"typeIdentifier","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"encryptedImagesURLs","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"storageLocation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}]}]},{"name":"fileFormat","content":[{"type":"paragraph","inlineContent":[{"text":"The file format that should be used to store the images.","type":"text"}]}]},{"name":"encrypter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt\/decrypt image data.If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", no encryption is used."}]}]},{"name":"encryptedImagesURLs","content":[{"type":"paragraph","inlineContent":[{"text":"Array of URLs containing encrypted images. The images at these URLs must be encrypted with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the given encrypter (if not "},{"code":"nil","type":"codeVoice"},{"text":") and must have the same file format as specified in the fileFormat parameter.","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:encryptedimagesurls:)"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:encryptedimagesurls:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting":{"abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCrypting"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting","role":"symbol","title":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageLocation":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageLocation"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragelocation","abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"title":"SBSDKStorageLocation","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage","navigatorTitle":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Manages images in an array-like fashion."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"type":"topic","title":"SBSDKIndexedImageStorage","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageFileFormat":{"title":"SBSDKImageFileFormat","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagefileformat","abstract":[{"type":"text","text":"Enumeration of supported image file types."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageFileFormat","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageFileFormat"}],"navigatorTitle":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKIndexedImageStorage/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)":{"abstract":[{"text":"Initializes a new ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage","isActive":true},{"type":"text","text":" at the given storage location with given image file format."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"text":"fileFormat","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"text":"encryptedImagesURLs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"])","kind":"text"}],"kind":"symbol","title":"init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encrypter:encryptedimagesurls:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStorageLocation:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStorageLocation","kind":"typeIdentifier","text":"SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageLocation"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"storageLocation"},{"text":" ","kind":"text"},{"text":"fileFormat:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageFileFormat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"fileFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter:"},{"text":"(","kind":"text"},{"text":"id<SBSDKStorageCrypting>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"encrypter"},{"text":" ","kind":"text"},{"text":"encryptedImagesURLs:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSURL *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"encryptedImagesURLs"},{"text":";","kind":"text"}]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}],"type":"paragraph"}],"name":"storageLocation"},{"name":"fileFormat","content":[{"inlineContent":[{"text":"The file format that should be used to store the images.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The encrypter used to encrypt\/decrypt image data.If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}],"type":"paragraph"}],"name":"encrypter"},{"name":"encryptedImagesURLs","content":[{"type":"paragraph","inlineContent":[{"text":"Array of URLs containing encrypted images. The images at these URLs must be encrypted with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the given encrypter (if not "},{"type":"codeVoice","code":"nil"},{"type":"text","text":") and must have the same file format as specified in the fileFormat parameter."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/title","op":"replace","value":"SBSDKStorageCrypting"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"op":"replace","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/title","op":"replace","value":"SBSDKStorageLocation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},{"value":[{"kind":"identifier","text":"SBSDKStorageLocation"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageLocation\/navigatorTitle"},{"value":"SBSDKIndexedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},{"value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle"},{"value":"SBSDKImageFileFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageFileFormat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageFileFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageFileFormat\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageFileFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)\/title","value":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:fileFormat:encrypter:encryptedImagesURLs:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encrypter:encryptedImagesURLs:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}