{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/shutterbuttonaccessibilityhint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/shutterbuttonaccessibilityhint"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/shutterButtonAccessibilityHint"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shutterButtonAccessibilityHint"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to “Makes a scan”.","type":"text"}]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration(py)shutterButtonAccessibilityHint","title":"shutterButtonAccessibilityHint","platforms":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shutterButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"shutterButtonAccessibilityHint","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"abstract":[{"text":"Text, that is used as an accessibility hint for the shutter button.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"deprecated":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"title":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/shutterButtonAccessibilityHint":{"abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the shutter button."}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/shutterButtonAccessibilityHint","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shutterButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"shutterButtonAccessibilityHint","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/shutterbuttonaccessibilityhint","navigatorTitle":[{"text":"shutterButtonAccessibilityHint","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shutterButtonAccessibilityHint","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"shutterButtonAccessibilityHint","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"shutterButtonAccessibilityHint","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/title","value":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1shutterButtonAccessibilityHint\/title","value":"shutterButtonAccessibilityHint"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration~1shutterButtonAccessibilityHint\/fragments","value":[{"text":"shutterButtonAccessibilityHint","kind":"identifier"}]}]}]}