{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The scanner will only use the current frame and will spend additional time to ensure the best possible result.","type":"text"},{"text":" ","type":"text"},{"text":"Use this mode when scanning single images, e.g. imported from the gallery.","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKCreditCardScanningMode@SBSDKCreditCardScanningModeSingleShot","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"singleShot","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScanningModeSingleShot"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","title":"SBSDKCreditCardScanningMode.singleShot"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"singleShot","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode\/singleshot"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode\/singleshot"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode\/singleShot","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningMode":{"title":"SBSDKCreditCardScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"The scanning mode.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScanningMode"}],"navigatorTitle":[{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningMode/singleShot":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningMode\/singleShot","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningmode\/singleshot","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScanningModeSingleShot"}],"title":"SBSDKCreditCardScanningMode.singleShot","abstract":[{"type":"text","text":"The scanner will only use the current frame and will spend additional time to ensure the best possible result."},{"type":"text","text":" "},{"text":"Use this mode when scanning single images, e.g. imported from the gallery.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"singleShot"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKCreditCardScanningModeSingleShot","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKCreditCardScanningModeSingleShot","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKCreditCardScanningModeSingleShot","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKCreditCardScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/title"},{"op":"replace","value":[{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCreditCardScanningMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode~1singleShot\/title","value":"SBSDKCreditCardScanningModeSingleShot"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningMode~1singleShot\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCreditCardScanningModeSingleShot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}