{"metadata":{"role":"symbol","title":"streamingCryptChunk:error:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAESGCMEncrypter(im)streamingCryptChunk:error:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"streamingCryptChunk:error:","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"streamingCryptChunk:error:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"streamingCryptChunk:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/streamingCryptChunk:error:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/streamingcryptchunk:error:"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter/streamingCryptChunk:error:":{"abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"streamingCryptChunk:error:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/streamingCryptChunk:error:","navigatorTitle":[{"kind":"identifier","text":"streamingCryptChunk:error:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/streamingcryptchunk:error:","title":"streamingCryptChunk:error:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter":{"abstract":[{"type":"text","text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider."},{"type":"text","text":" "},{"type":"text","text":"Supports encryption and decryption of single data blocks as well as streaming data."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter","role":"symbol","title":"SBSDKAESGCMEncrypter","navigatorTitle":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKAESGCMEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/title"},{"op":"replace","value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}