{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2RoundButton\/isEqual:"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2RoundButton"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2roundbutton\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2RoundButton(im)isEqual:","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2RoundButton":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2roundbutton","title":"SBSDKUI2RoundButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"abstract":[{"text":"Configuration of the round button.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2RoundButton"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2RoundButton/isEqual:":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2RoundButton\/isEqual:","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2roundbutton\/isequal:","abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2RoundButton","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2RoundButton\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2RoundButton\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2RoundButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2RoundButton"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}