{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions"]]},"metadata":{"title":"hash","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKEncodeImageOptions(py)hash","symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions\/hash","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions\/hash"]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodeImageOptions":{"navigatorTitle":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions","type":"topic","title":"SBSDKEncodeImageOptions","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Options for encoding image."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKEncodeImageOptions","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodeImageOptions/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions\/hash","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions\/hash","kind":"symbol","role":"symbol","title":"hash","type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKEncodeImageOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/fragments"},{"op":"replace","value":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}