{"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/!=(_:_:)"],"title":"Operators","anchor":"Operators"}],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"article","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype\/!=(_:_:)","abstract":[],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraDeviceType":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraDeviceType","kind":"symbol","title":"SBSDKCameraDeviceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An enum to describe the different types of camera lenses\/devices."}],"url":"\/documentation\/scanbotsdk\/sbsdkcameradevicetype"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/title","op":"replace","value":"SBSDKCameraDeviceType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraDeviceType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}