{"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerBehaviorConfiguration(py)wordBoxHighlightEnabled","role":"symbol","roleHeading":"Instance Property","title":"wordBoxHighlightEnabled","navigatorTitle":[{"kind":"identifier","text":"wordBoxHighlightEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wordBoxHighlightEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"Whether the word boxes should be shown."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/wordBoxHighlightEnabled"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/wordboxhighlightenabled"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/wordboxhighlightenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"wordBoxHighlightEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration/wordBoxHighlightEnabled":{"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"wordBoxHighlightEnabled"}],"title":"wordBoxHighlightEnabled","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration\/wordboxhighlightenabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"wordBoxHighlightEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration\/wordBoxHighlightEnabled","abstract":[{"text":"Whether the word boxes should be shown.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerBehaviorConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUITextDataScannerBehaviorConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerBehaviorConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerBehaviorConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerbehaviorconfiguration","type":"topic","abstract":[{"text":"Configuration for the behavior of RTU-UI text data scanner.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKUITextDataScannerBehaviorConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"wordBoxHighlightEnabled","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"wordBoxHighlightEnabled"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wordBoxHighlightEnabled"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1wordBoxHighlightEnabled\/title","value":"wordBoxHighlightEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration~1wordBoxHighlightEnabled\/fragments","value":[{"text":"wordBoxHighlightEnabled","kind":"identifier"}]},{"value":"SBSDKUITextDataScannerBehaviorConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration\/title"},{"value":[{"text":"SBSDKUITextDataScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerBehaviorConfiguration\/fragments"}]}]}