{"kind":"symbol","abstract":[{"text":"Applies a polygon to the receiver and returns the cropped and perspective corrected image.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(sbsdk_imageWarpedByPolygon:lensCameraProperties:imageScale:sizeLimit:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageWarped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"polygon","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","text":"SBSDKPolygon","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"lensCameraProperties","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sizeLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":" = .zero) -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The polygon used to crop and perspective correct the image.","type":"text"}],"type":"paragraph"}],"name":"polygon"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Properties of the camera which captured the image or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"lensCameraProperties"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the image has been scaled, compared to how it was captured from the camera, you must set the scaling factor here for proper cropping. Otherwise the resulting aspect ratio will be wrong. Set to 1.0 if the image must retain its original size."}]}],"name":"imageScale"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The maximum size of the resulting image. If the image exceeds this size, it will be scaled down to fit within the specified dimensions. Default is ","type":"text"},{"type":"codeVoice","code":".zero"},{"text":", which means no size limit.","type":"text"}]}],"name":"sizeLimit"}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The cropped and perspective corrected "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":"or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation failed."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagewarped(by:lenscameraproperties:imagescale:sizelimit:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:lensCameraProperties:imageScale:sizeLimit:)","interfaceLanguage":"swift"},"metadata":{"extendedModule":"UIKit","modules":[{"name":"ScanbotSDK","relatedModules":["UIKit"]}],"role":"symbol","title":"sbsdk_imageWarped(by:lensCameraProperties:imageScale:sizeLimit:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageWarped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"lensCameraProperties","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLensCameraProperties","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties"},{"text":"?, ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"sizeLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"externalID":"c:@CM@ScanbotSDK@@objc(cs)UIImage(im)sbsdk_imageWarpedByPolygon:lensCameraProperties:imageScale:sizeLimit:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit":{"kind":"symbol","type":"topic","title":"UIKit","url":"\/documentation\/scanbotsdk\/uikit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","abstract":[],"role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"title":"SBSDKPolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"identifier","text":"UIImage"}],"role":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" class extension to perform basic image processing operations.","type":"text"},{"text":" ","type":"text"},{"text":"Direct usage is not recommended for large images.","type":"text"},{"text":" ","type":"text"},{"text":"queues and proper memory management.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage","navigatorTitle":[{"kind":"identifier","text":"UIImage"}],"title":"UIImage","url":"\/documentation\/scanbotsdk\/uikit\/uiimage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLensCameraProperties":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"kind":"symbol","title":"SBSDKLensCameraProperties","url":"\/documentation\/scanbotsdk\/sbsdklenscameraproperties","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Encapsulates lens and camera properties. Can be used with polygonal image cropping to achieve a very accurate aspect ratio of the resulting image."},{"type":"text","text":" "},{"type":"text","text":"If created from image image metadata, uses a dictionary of some known devices to lookup the values."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage/sbsdk_imageWarped(by:lensCameraProperties:imageScale:sizeLimit:)":{"title":"sbsdk_imageWarped(by:lensCameraProperties:imageScale:sizeLimit:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_imageWarped(by:lensCameraProperties:imageScale:sizeLimit:)","abstract":[{"text":"Applies a polygon to the receiver and returns the cropped and perspective corrected image.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_imagewarped(by:lenscameraproperties:imagescale:sizelimit:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_imageWarped","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPolygon","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon"},{"text":"?, ","kind":"text"},{"text":"lensCameraProperties","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKLensCameraProperties","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties"},{"text":"?, ","kind":"text"},{"text":"imageScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"sizeLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"kind":"identifier","text":"SBSDKPolygon"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","value":[{"text":"SBSDKPolygon","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/title","value":"SBSDKLensCameraProperties"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/fragments","value":[{"text":"SBSDKLensCameraProperties","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKLensCameraProperties"}]}]}]}