{"metadata":{"roleHeading":"Case","title":"SBSDKUIBarcodesExtensionFilter.onlyWithExtensions","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUIBarcodesExtensionFilter@SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"onlyWithExtensions","kind":"identifier"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Only EAN and UPC barcoded with extensions will be returned."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesExtensionFilter"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesExtensionFilter\/onlyWithExtensions","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyWithExtensions"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesextensionfilter\/onlywithextensions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesextensionfilter\/onlywithextensions"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesExtensionFilter/onlyWithExtensions":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesExtensionFilter\/onlyWithExtensions","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"onlyWithExtensions","kind":"identifier"}],"abstract":[{"text":"Only EAN and UPC barcoded with extensions will be returned.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKUIBarcodesExtensionFilter.onlyWithExtensions","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesextensionfilter\/onlywithextensions","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesExtensionFilter":{"role":"symbol","type":"topic","title":"SBSDKUIBarcodesExtensionFilter","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesextensionfilter","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesExtensionFilter","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter~1onlyWithExtensions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilterOnlyWithExtensions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter~1onlyWithExtensions\/fragments"},{"value":"SBSDKUIBarcodesExtensionFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesExtensionFilter"}],"op":"replace"},{"value":[{"text":"SBSDKUIBarcodesExtensionFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesExtensionFilter\/navigatorTitle"}]}]}