{"metadata":{"roleHeading":"Type Property","title":"defaultStatusBarStyle","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"defaultStatusBarStyle"}],"externalID":"c:@M@ScanbotSDK@objc(cs)ScanbotUI(cpy)defaultStatusBarStyle"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI"]]},"abstract":[{"type":"text","text":"The default status bar style of all ScanbotSDK RTU-UI components upon their initialization. Defaults to "},{"code":".lightContent","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/scanbotui\/defaultstatusbarstyle"]},{"paths":["\/documentation\/scanbotsdk\/scanbotui\/defaultstatusbarstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI\/defaultStatusBarStyle"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultStatusBarStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle","kind":"typeIdentifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotUI/defaultStatusBarStyle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI\/defaultStatusBarStyle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultStatusBarStyle"},{"kind":"text","text":": "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"navigatorTitle":[{"text":"defaultStatusBarStyle","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/scanbotui\/defaultstatusbarstyle","type":"topic","title":"defaultStatusBarStyle","abstract":[{"text":"The default status bar style of all ScanbotSDK RTU-UI components upon their initialization. Defaults to ","type":"text"},{"code":".lightContent","type":"codeVoice"},{"text":".","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotUI":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI","title":"ScanbotUI","type":"topic","abstract":[{"type":"text","text":"Helper class to configure the properties of the ScanbotSDK RTU-UI (SBSDKUI) components."}],"url":"\/documentation\/scanbotsdk\/scanbotui","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ScanbotUI","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ScanbotUI","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"defaultStatusBarStyle","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultStatusBarStyle"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultStatusBarStyle"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI~1defaultStatusBarStyle\/title","op":"replace","value":"defaultStatusBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI~1defaultStatusBarStyle\/fragments","value":[{"text":"defaultStatusBarStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI\/title","value":"ScanbotUI"},{"op":"replace","value":[{"text":"ScanbotUI","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI\/navigatorTitle","value":[{"kind":"identifier","text":"ScanbotUI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}