{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardPhoto"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardPhoto\/initWithGenericDocument:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithGenericDocument:"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocument","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"symbolKind":"method","title":"initWithGenericDocument:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardPhoto(im)initWithGenericDocument:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardphoto\/initwithgenericdocument:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","abstract":[{"text":"Generic document.","type":"text"}],"title":"SBSDKGenericDocument","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocument"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardPhoto":{"title":"SBSDKBarcodeDocumentModelVCardPhoto","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardPhoto"}],"abstract":[{"text":"Photo","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardphoto","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardPhoto","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardPhoto"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardPhoto/initWithGenericDocument:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardPhoto\/initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardphoto\/initwithgenericdocument:","title":"initWithGenericDocument:","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithGenericDocument:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardPhoto\/title","value":"SBSDKBarcodeDocumentModelVCardPhoto","op":"replace"},{"value":[{"text":"SBSDKBarcodeDocumentModelVCardPhoto","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardPhoto\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelVCardPhoto","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardPhoto\/navigatorTitle"}]}]}