{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(documentDataExtractorViewController:didExtractResult:onImage:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataExtractorViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","text":"SBSDKDocumentDataExtractorViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didExtract"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","kind":"typeIdentifier","text":"SBSDKDocumentDataExtractionResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","isActive":true,"type":"reference"},{"text":" instance that extracted the document.","type":"text"}]}],"name":"viewController"},{"content":[{"inlineContent":[{"text":"The extraction result.","type":"text"}],"type":"paragraph"}],"name":"result"},{"content":[{"inlineContent":[{"text":"The original image where the document has been extracted from.","type":"text"}],"type":"paragraph"}],"name":"image"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontroller(_:didextract:on:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontroller(_:didextract:on:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewController(_:didExtract:on:)"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"documentDataExtractorViewController:didExtractResult:onImage:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKDocumentDataExtractorViewControllerDelegate(im)documentDataExtractorViewController:didExtractResult:onImage:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataExtractorViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorViewController","kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didExtract"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","kind":"typeIdentifier","text":"SBSDKDocumentDataExtractionResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":")"}],"title":"documentDataExtractorViewController(_:didExtract:on:)","modules":[{"name":"ScanbotSDK"}],"role":"symbol","required":true},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Informs the delegate that a document has been extracted successfully.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"title":"SBSDKDocumentDataExtractionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"abstract":[{"type":"text","text":"Contains the result of running the document data extractor."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewControllerDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate","title":"SBSDKDocumentDataExtractorViewControllerDelegate","abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewControllerDelegate/documentDataExtractorViewController(_:didExtract:on:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewControllerDelegate\/documentDataExtractorViewController(_:didExtract:on:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontrollerdelegate\/documentdataextractorviewcontroller(_:didextract:on:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDataExtractorViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorViewController","text":"SBSDKDocumentDataExtractorViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didExtract"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","text":"SBSDKDocumentDataExtractionResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"documentDataExtractorViewController:didExtractResult:onImage:"}],"title":"documentDataExtractorViewController(_:didExtract:on:)","role":"symbol","abstract":[{"type":"text","text":"Informs the delegate that a document has been extracted successfully."}],"required":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorViewController":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorviewcontroller","title":"SBSDKDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to extract documents data, e.g. German passports, ID cards and driver’s licenses on video frames."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"documentDataExtractorViewController:didExtractResult:onImage:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentDataExtractorViewController:didExtractResult:onImage:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"documentDataExtractorViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didExtractResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKDocumentDataExtractionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"kind":"text","text":" "},{"kind":"identifier","text":"onImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorViewController","isActive":true,"type":"reference"},{"type":"text","text":" instance that extracted the document."}]}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The extraction result."}]}]},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The original image where the document has been extracted from."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKDocumentDataExtractionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate\/title","value":"SBSDKDocumentDataExtractorViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate\/fragments","value":[{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractorViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewController(_:didExtract:on:)\/title","value":"documentDataExtractorViewController:didExtractResult:onImage:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewControllerDelegate~1documentDataExtractorViewController(_:didExtract:on:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentDataExtractorViewController:didExtractResult:onImage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/title","value":"SBSDKDocumentDataExtractorViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/fragments","value":[{"text":"SBSDKDocumentDataExtractorViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorViewController"}],"op":"replace"}]}]}