{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/none"},"metadata":{"navigatorTitle":[{"text":"SBSDKResamplingMethodNone","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKResamplingMethod@SBSDKResamplingMethodNone","role":"symbol","title":"SBSDKResamplingMethod.none","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod"]]},"abstract":[{"type":"text","text":"Always geometrically rescale the image to fit the page if necessary. Fast."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Otherwise, downscale the bitmap to match the "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" setting via the selected method before"},{"type":"text","text":" "},{"type":"text","text":"adding it to the PDF if the calculated image DPI after stretching is greater than "},{"type":"codeVoice","code":"dpi"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Slower.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/none"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod/none":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod\/none","navigatorTitle":[{"text":"SBSDKResamplingMethodNone","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Always geometrically rescale the image to fit the page if necessary. Fast."}],"title":"SBSDKResamplingMethod.none","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod\/none","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResamplingMethod":{"title":"SBSDKResamplingMethod","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkresamplingmethod","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKResamplingMethod"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKResamplingMethod","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResamplingMethod","kind":"symbol","abstract":[{"type":"text","text":"Resampling method."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKResamplingMethodNone","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKResamplingMethodNone","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKResamplingMethodNone","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKResamplingMethodNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1none\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod~1none\/fragments","value":[{"kind":"identifier","text":"SBSDKResamplingMethodNone"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/title","value":"SBSDKResamplingMethod"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/fragments","value":[{"text":"SBSDKResamplingMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResamplingMethod\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKResamplingMethod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}