{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/orientationConfidence","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Confidence that the reported orientation of the document is correct. Returned if orientation detection is enabled.","type":"text"},{"text":" ","type":"text"},{"text":"The value is in the range of [0, 1].","type":"text"},{"text":" ","type":"text"},{"text":"Possible reasons for low confidence are:","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult(py)orientationConfidence","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientationConfidence","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"orientationConfidence","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"orientationConfidence","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/orientationconfidence"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/orientationconfidence"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientationConfidence","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Document contains text with multiple orientations."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Text on the document is poorly readable."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Text on the document is on the edge of detectable text range (text is too small or too big)."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Insufficient statistics because only part of the image was processed. See ProcessByTileConfiguration options in the DocumentQualityAnalyzerConfiguration."}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult"]]},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult/orientationConfidence":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/orientationConfidence","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/orientationconfidence","title":"orientationConfidence","kind":"symbol","abstract":[{"type":"text","text":"Confidence that the reported orientation of the document is correct. Returned if orientation detection is enabled."},{"type":"text","text":" "},{"type":"text","text":"The value is in the range of [0, 1]."},{"type":"text","text":" "},{"type":"text","text":"Possible reasons for low confidence are:"}],"navigatorTitle":[{"kind":"identifier","text":"orientationConfidence"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Result of document quality analysis. It can be used to determine, e.g., if a document is good enough to be used for OCR processing."}],"kind":"symbol","title":"SBSDKDocumentQualityAnalyzerResult","navigatorTitle":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"orientationConfidence"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"orientationConfidence"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"orientationConfidence"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult~1orientationConfidence\/title","op":"replace","value":"orientationConfidence"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult~1orientationConfidence\/fragments","op":"replace","value":[{"kind":"identifier","text":"orientationConfidence"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/title","op":"replace","value":"SBSDKDocumentQualityAnalyzerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}