{"abstract":[{"text":"Only draw the corners of the finder view.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"corners"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview\/style-swift.enum\/corners"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/Style-swift.enum"]]},"sections":[],"metadata":{"role":"symbol","title":"SBSDKFinderView.Style.corners","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"corners"}],"symbolKind":"case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"s:24ScanbotBarcodeScannerSDK15SBSDKFinderViewC5StyleO7cornersyA2EmF","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/Style-swift.enum\/corners"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView/Style-swift.enum/corners":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview\/style-swift.enum\/corners","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/Style-swift.enum\/corners","title":"SBSDKFinderView.Style.corners","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"corners","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Only draw the corners of the finder view."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView/Style-swift.enum":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview\/style-swift.enum","navigatorTitle":[{"text":"Style","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"title":"SBSDKFinderView.Style","abstract":[{"type":"text","text":"The enum that defines the drawing styles of the finder view."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/Style-swift.enum"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"title":"SBSDKFinderView","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKFinderView","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/title","op":"replace","value":"SBSDKFinderView"},{"op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/fragments"},{"value":[{"text":"SBSDKFinderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}