{"abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1\/requiredDocumentType"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesa1\/requireddocumenttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesa1\/requireddocumenttype"]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"requiredDocumentType","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1(py)requiredDocumentType","symbolKind":"property","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"DeDriverLicenseBack.Categories.A1"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesa1","title":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1/requiredDocumentType":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"requiredDocumentType","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeldedriverlicensebackcategoriesa1\/requireddocumenttype","navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1\/requiredDocumentType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"requiredDocumentType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"requiredDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1\/title","value":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1\/fragments","value":[{"text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1~1requiredDocumentType\/title","value":"requiredDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelDeDriverLicenseBackCategoriesA1~1requiredDocumentType\/fragments","value":[{"kind":"identifier","text":"requiredDocumentType"}],"op":"replace"}]}]}