{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/accessibilitydragpoint(_:description:isenabled:)-3l621"]}],"metadata":{"platforms":[{"name":"iOS","unavailable":false,"introducedAt":"18.0","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"18.0","beta":false,"name":"iPadOS","deprecated":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"18.0"},{"introducedAt":"15.0","unavailable":false,"name":"macOS","deprecated":false,"beta":false},{"deprecated":false,"name":"visionOS","introducedAt":"2.0","unavailable":false,"beta":false}],"extendedModule":"SwiftUICore","externalID":"s:7SwiftUI4ViewPAAE22accessibilityDragPoint_11description9isEnabledAA15ModifiedContentVyxAA31AccessibilityAttachmentModifierVGAA04UnitF0V_AA18LocalizedStringKeyVSbtF::SYNTHESIZED::s:10ScanbotSDK29SBSDKUI2CreditCardScannerViewV","symbolKind":"method","title":"accessibilityDragPoint(_:description:isEnabled:)","role":"symbol","modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"accessibilityDragPoint","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnitPoint","preciseIdentifier":"s:7SwiftUI9UnitPointV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV","text":"LocalizedStringKey","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier","text":"ModifiedContent"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/View-Implementations"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.accessibilityDragPoint(_:description:isEnabled:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"accessibilityDragPoint","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"point"},{"text":": ","kind":"text"},{"text":"UnitPoint","preciseIdentifier":"s:7SwiftUI9UnitPointV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV","text":"LocalizedStringKey"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"text":"ModifiedContent","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AccessibilityAttachmentModifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/accessibilityDragPoint(_:description:isEnabled:)-3l621","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView/accessibilityDragPoint(_:description:isEnabled:)-3l621":{"kind":"symbol","title":"accessibilityDragPoint(_:description:isEnabled:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/accessibilityDragPoint(_:description:isEnabled:)-3l621","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/accessibilitydragpoint(_:description:isenabled:)-3l621","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accessibilityDragPoint","kind":"identifier"},{"kind":"text","text":"("},{"text":"UnitPoint","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI9UnitPointV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocalizedStringKey","preciseIdentifier":"s:7SwiftUI18LocalizedStringKeyV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ModifiedContent","preciseIdentifier":"s:7SwiftUI15ModifiedContentV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"AccessibilityAttachmentModifier","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"kind":"text","text":">"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView":{"abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerViewController"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerView"}],"title":"SBSDKUI2CreditCardScannerView","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerView/View-Implementations":{"type":"topic","role":"collectionGroup","title":"View Implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerView\/View-Implementations","kind":"article","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerview\/view-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerViewController":{"type":"topic","role":"symbol","title":"SBSDKUI2CreditCardScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2CreditCardScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to scan credit card data."}],"navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/title","value":"SBSDKUI2CreditCardScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CreditCardScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}