{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metadata","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata","text":"SBSDKDocumentsModelMetadata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMetadata","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/metadata","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront"]]},"abstract":[{"type":"text","text":"The child document of type “Metadata”."}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metadata","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata","text":"SBSDKDocumentsModelMetadata","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"metadata","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelCnEntryAndExitPermitFront(py)metadata","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"metadata","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/metadata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/metadata"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront/metadata":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata","kind":"typeIdentifier","text":"SBSDKDocumentsModelMetadata"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront\/metadata","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront\/metadata","kind":"symbol","abstract":[{"type":"text","text":"The child document of type “Metadata”."}],"navigatorTitle":[{"kind":"identifier","text":"metadata"}],"role":"symbol","title":"metadata"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMetadata":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMetadata","kind":"symbol","abstract":[{"text":"Metadata for the document","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelMetadata","kind":"identifier"}],"title":"SBSDKDocumentsModelMetadata","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmetadata","navigatorTitle":[{"text":"SBSDKDocumentsModelMetadata","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnEntryAndExitPermitFront":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnentryandexitpermitfront","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnEntryAndExitPermitFront","abstract":[{"text":"CnEntryAndExitPermitFront","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}],"title":"SBSDKDocumentsModelCnEntryAndExitPermitFront","navigatorTitle":[{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"metadata","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"metadata"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMetadata","kind":"typeIdentifier","text":"SBSDKDocumentsModelMetadata"},{"kind":"text","text":" * "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"metadata","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1metadata\/title","op":"replace"},{"value":[{"text":"metadata","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront~1metadata\/fragments","op":"replace"},{"value":"SBSDKDocumentsModelMetadata","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMetadata\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelMetadata"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMetadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelMetadata"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMetadata\/navigatorTitle","op":"replace"},{"value":"SBSDKDocumentsModelCnEntryAndExitPermitFront","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentsModelCnEntryAndExitPermitFront","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelCnEntryAndExitPermitFront"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnEntryAndExitPermitFront\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}