{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatroyaltntpostconfiguration()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatRoyalTntPostConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatRoyalTNTPostConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatRoyalTNTPostConfiguration"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Type Method","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"barcodeFormatRoyalTntPostConfiguration()","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatRoyalTntPostConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatRoyalTNTPostConfiguration"}],"externalID":"s:24ScanbotBarcodeScannerSDK35SBSDKBarcodeFormatConfigurationBaseC07barcodef12RoyalTntPostG0AA0efj7TNTPostG0CyFZ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalTntPostConfiguration()"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase":{"abstract":[{"text":"Base class for all barcode configurations.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"title":"SBSDKBarcodeFormatConfigurationBase","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatRoyalTNTPostConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Royal TNT Post barcode configuration. Add to scanner configuration to scan Royal TNT Post (a.k.a. KIX, Klant IndeX) barcodes."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatroyaltntpostconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatRoyalTNTPostConfiguration","title":"SBSDKBarcodeFormatRoyalTNTPostConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatRoyalTntPostConfiguration()":{"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatRoyalTntPostConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatRoyalTNTPostConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatroyaltntpostconfiguration()","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalTntPostConfiguration()","type":"topic","title":"barcodeFormatRoyalTntPostConfiguration()","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeFormatConfigurationBase","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments"},{"value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle"},{"value":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatRoyalTNTPostConfiguration\/title"},{"value":[{"text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatRoyalTNTPostConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatRoyalTNTPostConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}