{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatamatrixconfiguration()"]}],"metadata":{"roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatDataMatrixConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataMatrixConfiguration","kind":"typeIdentifier"}],"title":"barcodeFormatDataMatrixConfiguration()","role":"symbol","externalID":"s:24ScanbotBarcodeScannerSDK35SBSDKBarcodeFormatConfigurationBaseC07barcodef10DataMatrixG0AA0efjkG0CyFZ","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataMatrixConfiguration()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatDataMatrixConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataMatrixConfiguration","text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase":{"abstract":[{"text":"Base class for all barcode configurations.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"title":"SBSDKBarcodeFormatConfigurationBase","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatDataMatrixConfiguration":{"title":"SBSDKBarcodeFormatDataMatrixConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatDataMatrixConfiguration","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatdatamatrixconfiguration","abstract":[{"type":"text","text":"DataMatrix configuration. Add to scanner configuration to scan DataMatrix and DataMatrix rectangular extensions (DMRE) codes."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataMatrixConfiguration()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataMatrixConfiguration()","abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"barcodeFormatDataMatrixConfiguration()","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatamatrixconfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatDataMatrixConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatDataMatrixConfiguration","text":"SBSDKBarcodeFormatDataMatrixConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKBarcodeFormatConfigurationBase","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments"},{"value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle"},{"value":"SBSDKBarcodeFormatDataMatrixConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/title"},{"value":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatDataMatrixConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/navigatorTitle"}]}]}