{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"new","kind":"identifier"},{"text":";","kind":"text"}]}]}],"metadata":{"fragments":[{"kind":"text","text":"+ "},{"text":"new","kind":"identifier"}],"roleHeading":"Type Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"new","kind":"identifier"}],"title":"new","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration(cm)new"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PermanentViewFinderConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2permanentviewfinderconfiguration\/new"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PermanentViewFinderConfiguration\/new","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PermanentViewFinderConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2permanentviewfinderconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PermanentViewFinderConfiguration","title":"SBSDKUI2PermanentViewFinderConfiguration","abstract":[{"text":"Configuration of the scanning interface’s viewfinder, which is always visible to guide the user.","type":"text"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PermanentViewFinderConfiguration/new":{"abstract":[],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2permanentviewfinderconfiguration\/new","role":"symbol","title":"new","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"navigatorTitle":[{"kind":"identifier","text":"new"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PermanentViewFinderConfiguration\/new"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2PermanentViewFinderConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PermanentViewFinderConfiguration\/title"},{"value":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PermanentViewFinderConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PermanentViewFinderConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}