{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroImage\/fromJsonWithJson:","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckIntroImage(cm)fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroImage","text":"SBSDKUI2CheckIntroImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckIntroImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromJsonWithJson:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"json"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroImage"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkintroimage\/fromjsonwithjson:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckIntroImage/fromJsonWithJson:":{"role":"symbol","type":"topic","title":"fromJsonWithJson:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkintroimage\/fromjsonwithjson:","kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroImage\/fromJsonWithJson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckIntroImage":{"kind":"symbol","title":"SBSDKUI2CheckIntroImage","url":"\/documentation\/scanbotsdk\/sbsdkui2checkintroimage","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CheckIntroImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckIntroImage","kind":"identifier"}],"abstract":[{"type":"text","text":"The image for the introduction screen with a check template."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroImage\/title","op":"replace","value":"SBSDKUI2CheckIntroImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CheckIntroImage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroImage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CheckIntroImage"}]}]}]}