{"kind":"symbol","metadata":{"title":"hash","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration(py)hash","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration\/hash"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconuserguidanceconfiguration\/hash"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconUserGuidanceConfiguration/hash":{"role":"symbol","kind":"symbol","title":"hash","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration\/hash","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconuserguidanceconfiguration\/hash","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"hash"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconUserGuidanceConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"title":"SBSDKUI2IconUserGuidanceConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconuserguidanceconfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2IconUserGuidanceConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}