{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency"]]},"kind":"symbol","metadata":{"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKValueConsistency.okDeburredExtended","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistencyOkDeburredExtended"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKValueConsistency@SBSDKValueConsistencyOkDeburredExtended","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"okDeburredExtended","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"okDeburredExtended","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburredExtended","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Same as OK_DEBURRED but allows replacing diacritics not only with their base characters but also with some more"},{"type":"text","text":" "},{"type":"text","text":"complex combinations. E.g., according to ICAO 9303 MRZ standard Ü can be replaced with U or UE or UXX."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okdeburredextended"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okdeburredextended"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/okDeburredExtended":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okDeburredExtended"}],"navigatorTitle":[{"text":"SBSDKValueConsistencyOkDeburredExtended","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/okdeburredextended","abstract":[{"text":"Same as OK_DEBURRED but allows replacing diacritics not only with their base characters but also with some more","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"complex combinations. E.g., according to ICAO 9303 MRZ standard Ü can be replaced with U or UE or UXX."}],"kind":"symbol","title":"SBSDKValueConsistency.okDeburredExtended","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okDeburredExtended","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"title":"SBSDKValueConsistency","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"role":"symbol","type":"topic","abstract":[{"text":"The status of the consistency verification.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKValueConsistency"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKValueConsistencyOkDeburredExtended"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKValueConsistencyOkDeburredExtended"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKValueConsistencyOkDeburredExtended","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKValueConsistencyOkDeburredExtended","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okDeburredExtended\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistencyOkDeburredExtended"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okDeburredExtended\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title","value":"SBSDKValueConsistency"},{"op":"replace","value":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}