{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset1"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarizationFilterPreset@SBSDKBinarizationFilterPresetPreset1","symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preset1","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"SBSDKBinarizationFilterPreset.preset1"},"abstract":[{"text":"Very fast, performs well if there are no shadows.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset1"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preset1","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset\/preset1"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset":{"title":"SBSDKBinarizationFilterPreset","navigatorTitle":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"abstract":[{"type":"text","text":"Preset of parameters for custom binarization filter."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset/preset1":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preset1"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset1","type":"topic","abstract":[{"type":"text","text":"Very fast, performs well if there are no shadows."}],"title":"SBSDKBinarizationFilterPreset.preset1","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset\/preset1","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBinarizationFilterPresetPreset1","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset1"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset1"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBinarizationFilterPreset","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/title"},{"op":"replace","value":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/navigatorTitle"},{"op":"replace","value":"SBSDKBinarizationFilterPresetPreset1","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset~1preset1\/title"},{"op":"replace","value":[{"text":"SBSDKBinarizationFilterPresetPreset1","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset~1preset1\/fragments"}]}]}