{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/Equatable-Implementations"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpagefit\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Operators","anchor":"Operators","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/!=(_:_:)"]}],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"ScanbotSDK"}],"role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit":{"abstract":[{"text":"Page fit.","type":"text"}],"title":"SBSDKPageFit","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagefit","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageFit"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPageFit","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagefit\/!=(_:_:)","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/title","op":"replace","value":"SBSDKPageFit"},{"value":[{"kind":"identifier","text":"SBSDKPageFit"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/navigatorTitle","value":[{"text":"SBSDKPageFit","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}