{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/init(visible:deselected:selected:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/init(visible:deselected:selected:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"visible","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"deselected"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle"},{"text":" = SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                  isArgb: false),\n                                         strokeWidth: 2.0, cornerRadius: 2.0), ","kind":"text"},{"kind":"externalParam","text":"selected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle"},{"kind":"text","text":" = SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\", isArgb: false),\n                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                  isArgb: false),\n                                         strokeWidth: 2.0, cornerRadius: 2.0))"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration(im)initWithVisible:deselected:selected:","symbolKind":"init","roleHeading":"Initializer","title":"init(visible:deselected:selected:)","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithVisible:deselected:selected:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"visible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deselected"},{"text":": ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selected"},{"kind":"text","text":": "},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle"},{"kind":"text","text":")"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/init(visible:deselected:selected:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"title":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"symbol","abstract":[{"text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PolygonStyle":{"title":"SBSDKUI2PolygonStyle","abstract":[{"type":"text","text":"Configuration of the polygon appearance."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2polygonstyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/init(visible:deselected:selected:)":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"visible","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"deselected","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selected"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","kind":"typeIdentifier","text":"SBSDKUI2PolygonStyle"},{"text":")","kind":"text"}],"title":"init(visible:deselected:selected:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/init(visible:deselected:selected:)","navigatorTitle":[{"text":"initWithVisible:deselected:selected:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/init(visible:deselected:selected:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithVisible:deselected:selected:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithVisible:deselected:selected:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"visible"},{"kind":"text","text":" "},{"kind":"identifier","text":"deselected:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deselected"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected:"},{"kind":"text","text":"("},{"text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle"},{"text":" *) ","kind":"text"},{"text":"selected","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"SBSDKUI2ArOverlayPolygonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}]},{"value":"SBSDKUI2PolygonStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1init(visible:deselected:selected:)\/title","value":"initWithVisible:deselected:selected:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration~1init(visible:deselected:selected:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithVisible:deselected:selected:","kind":"identifier"}]}]}]}