{"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatITFConfiguration(im)isEqual:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"isEqual:","symbolKind":"method","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatitfconfiguration\/isequal:"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatITFConfiguration"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatITFConfiguration\/isEqual:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatITFConfiguration/isEqual:":{"type":"topic","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatITFConfiguration\/isEqual:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatitfconfiguration\/isequal:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatITFConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatITFConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatITFConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatITFConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeFormatITFConfiguration","abstract":[{"text":"ITF (Interleaved 2-of-5) barcode configuration. Add to scanner configuration to scan Interleaved 2-of-5 (ITF)","type":"text"},{"text":" ","type":"text"},{"text":"barcodes.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatitfconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKBarcodeFormatITFConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatITFConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatITFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatITFConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatITFConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatITFConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}