{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/layoutsubviews"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/layoutSubviews"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKZoomingImageScrollView(im)layoutSubviews","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"layoutSubviews","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView/layoutSubviews":{"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"kind":"symbol","title":"layoutSubviews","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView\/layoutSubviews","url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview\/layoutsubviews","fragments":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKZoomingImageScrollView":{"navigatorTitle":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkzoomingimagescrollview","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKZoomingImageScrollView","type":"topic","title":"SBSDKZoomingImageScrollView","abstract":[{"text":"A scrollable and zoomable ","type":"text"},{"code":"UIScrollView","type":"codeVoice"},{"text":" subclass that displays images and an overlay view.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/title","value":"SBSDKZoomingImageScrollView"},{"value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/fragments","op":"replace"},{"value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKZoomingImageScrollView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}