{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The values that correspond to the same logical field are inconsistent."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/inconsistent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/inconsistent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/inconsistent"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inconsistent"}]}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKValueConsistency@SBSDKValueConsistencyInconsistent","role":"symbol","title":"SBSDKValueConsistency.inconsistent","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistencyInconsistent"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inconsistent"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/inconsistent":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inconsistent","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/inconsistent","title":"SBSDKValueConsistency.inconsistent","kind":"symbol","navigatorTitle":[{"text":"SBSDKValueConsistencyInconsistent","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/inconsistent","abstract":[{"text":"The values that correspond to the same logical field are inconsistent.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"role":"symbol","abstract":[{"text":"The status of the consistency verification.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency","navigatorTitle":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"type":"topic","title":"SBSDKValueConsistency","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKValueConsistency","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"SBSDKValueConsistencyInconsistent","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistencyInconsistent"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKValueConsistencyInconsistent","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKValueConsistencyInconsistent","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1inconsistent\/title"},{"op":"replace","value":[{"text":"SBSDKValueConsistencyInconsistent","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1inconsistent\/fragments"},{"op":"replace","value":"SBSDKValueConsistency","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments"},{"op":"replace","value":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle"}]}]}