{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency"]]},"abstract":[{"type":"text","text":"In addition to OK_DEBURRED_EXTENDED, allows one string to be a prefix of another string. Correctly works with"},{"type":"text","text":" "},{"type":"text","text":"complex diacritics replacements. In particular, if one string is MUEL and another is MÜLLER, then they are"},{"type":"text","text":" "},{"type":"text","text":"considered equal up to truncation."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okTruncated","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okTruncated"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/oktruncated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/oktruncated"]}],"metadata":{"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKValueConsistency.okTruncated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okTruncated"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKValueConsistency@SBSDKValueConsistencyOkTruncated","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistencyOkTruncated"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency":{"role":"symbol","abstract":[{"text":"The status of the consistency verification.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency","url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency","navigatorTitle":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"type":"topic","title":"SBSDKValueConsistency","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKValueConsistency","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueConsistency/okTruncated":{"type":"topic","title":"SBSDKValueConsistency.okTruncated","abstract":[{"type":"text","text":"In addition to OK_DEBURRED_EXTENDED, allows one string to be a prefix of another string. Correctly works with"},{"type":"text","text":" "},{"type":"text","text":"complex diacritics replacements. In particular, if one string is MUEL and another is MÜLLER, then they are"},{"type":"text","text":" "},{"type":"text","text":"considered equal up to truncation."}],"url":"\/documentation\/scanbotsdk\/sbsdkvalueconsistency\/oktruncated","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueConsistency\/okTruncated","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okTruncated"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKValueConsistencyOkTruncated"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKValueConsistencyOkTruncated","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKValueConsistencyOkTruncated"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKValueConsistencyOkTruncated","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKValueConsistency","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKValueConsistency"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/fragments","op":"replace"},{"value":[{"text":"SBSDKValueConsistency","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency\/navigatorTitle","op":"replace"},{"value":"SBSDKValueConsistencyOkTruncated","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okTruncated\/title","op":"replace"},{"value":[{"text":"SBSDKValueConsistencyOkTruncated","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueConsistency~1okTruncated\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}