{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingProvider"]]},"abstract":[{"type":"text","text":"Returns a storage crypting object"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"storageCrypting","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"items":[{"content":[{"inlineContent":[{"text":"Returns SBSDKStorageCrypting object to be used for encrypting or decrypting file","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingprovider\/storagecrypting()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingprovider\/storagecrypting()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","title":"storageCrypting()","navigatorTitle":[{"kind":"identifier","text":"storageCrypting"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"required":true,"role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingProvider(im)storageCrypting","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storageCrypting"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"SBSDKStorageCrypting"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingProvider\/storageCrypting()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCrypting":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCrypting","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"title":"SBSDKStorageCrypting","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecrypting","abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingProvider":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingprovider","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"title":"SBSDKStorageCryptingProvider","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingProvider","abstract":[{"type":"text","text":"Protocol for providing a storage crypting object."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingProvider/storageCrypting()":{"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"storageCrypting"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingProvider\/storageCrypting()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storageCrypting"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier","text":"SBSDKStorageCrypting"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingprovider\/storagecrypting()","type":"topic","abstract":[{"text":"Returns a storage crypting object","type":"text"}],"title":"storageCrypting()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"storageCrypting"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"storageCrypting","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id<SBSDKStorageCrypting>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCrypting"},{"text":") ","kind":"text"},{"text":"storageCrypting","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/title","op":"replace","value":"SBSDKStorageCrypting"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCrypting\/navigatorTitle","op":"replace","value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingProvider\/title","op":"replace","value":"SBSDKStorageCryptingProvider"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingProvider\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingProvider~1storageCrypting()\/title","op":"replace","value":"storageCrypting"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingProvider~1storageCrypting()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"storageCrypting"}]}]}]}