{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"Warning: Any operation on the receiver after a call to this function may lead to unpredictable behaviour and corrupted data.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/delete()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/delete()"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"delete()","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument(im)deleteAndReturnError:","roleHeading":"Instance Method","navigatorTitle":[{"text":"deleteAndReturnError:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/delete()","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Removes the receiver and its pages from the disk and clears the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/pages","isActive":true},{"type":"text","text":" array."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument/pages":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/pages","title":"pages","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pages"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument\/pages","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pages"},{"text":": [","kind":"text"},{"text":"SBSDKScannedPage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The array of scanned pages. Readonly."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument/delete()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"delete","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Removes the receiver and its pages from the disk and clears the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/pages","isActive":true},{"type":"text","text":" array."}],"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument\/delete()","title":"delete()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/delete()","role":"symbol","type":"topic","navigatorTitle":[{"text":"deleteAndReturnError:","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"title":"SBSDKScannedDocument","type":"topic","abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"deleteAndReturnError:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"deleteAndReturnError:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"deleteAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"add","value":{"parameters":[{"name":"error","content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"code":"YES","type":"codeVoice"},{"type":"text","text":" if the method succeeded, otherwise "},{"type":"codeVoice","code":"NO"},{"text":".","type":"text"}]}]},"op":"add"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1pages\/title","value":"pages","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1pages\/fragments","op":"replace","value":[{"text":"pages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1delete()\/title","value":"deleteAndReturnError:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1delete()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deleteAndReturnError:"}],"op":"replace"},{"value":"SBSDKScannedDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}