{"abstract":[{"type":"text","text":"A document was detected, but it was at an angle\/distance that was too large."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorBadCrop","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorBadCrop"}],"roleHeading":"Case","title":"SBSDKDocumentDataExtractionStatus.errorBadCrop","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKDocumentDataExtractionStatus@SBSDKDocumentDataExtractionStatusErrorBadCrop","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusErrorBadCrop","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorbadcrop"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorbadcrop"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorBadCrop","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus/errorBadCrop":{"role":"symbol","type":"topic","abstract":[{"text":"A document was detected, but it was at an angle\/distance that was too large.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorBadCrop","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus\/errorbadcrop","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus\/errorBadCrop","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatusErrorBadCrop","kind":"identifier"}],"title":"SBSDKDocumentDataExtractionStatus.errorBadCrop"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionStatus","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"abstract":[{"text":"The status of the extraction process.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"title":"SBSDKDocumentDataExtractionStatus","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKDocumentDataExtractionStatusErrorBadCrop","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorBadCrop"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKDocumentDataExtractionStatusErrorBadCrop","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorBadCrop\/title","value":"SBSDKDocumentDataExtractionStatusErrorBadCrop"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatusErrorBadCrop"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus~1errorBadCrop\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/title","value":"SBSDKDocumentDataExtractionStatus"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionStatus"}]},{"value":[{"text":"SBSDKDocumentDataExtractionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}