{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topBarTitle"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" = SBSDKUI2StyledText(visible: false, text: \"?acknowledgementTitle\",\n                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                          isArgb: false)), "},{"text":"minimumQuality","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKDocumentQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentQuality","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQuality"},{"text":" = SBSDKDocumentQuality.poor, ","kind":"text"},{"text":"acknowledgementMode","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementMode","text":"SBSDKUI2AcknowledgementMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2AcknowledgementMode","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2AcknowledgementMode.always, "},{"kind":"externalParam","text":"badImageHint"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration","text":"SBSDKUI2IconUserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKUI2IconUserGuidanceConfiguration(visible: true,\n                                                          icon: SBSDKUI2IconStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                       isArgb: false)),\n                                                          title: SBSDKUI2StyledText(text: \"?acknowledgementScreenBadDocumentHint\",\n                                                                                    color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                         isArgb: false)),\n                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorNegative\",\n                                                                                                                         isArgb: false),\n                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorNegative\",\n                                                                                                                       isArgb: false),\n                                                                                              strokeWidth: 0.0)), ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), "},{"text":"bottomBar","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementBottomBar"},{"text":" = SBSDKUI2AcknowledgementBottomBar())","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"init","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentQuality","text":"SBSDKDocumentQuality"},{"text":", ","kind":"text"},{"text":"acknowledgementMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2AcknowledgementMode","kind":"typeIdentifier","text":"SBSDKUI2AcknowledgementMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"badImageHint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration","text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"bottomBar","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","text":"SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration(im)initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","navigatorTitle":[{"kind":"identifier","text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration\/init(topbartitle:minimumquality:acknowledgementmode:badimagehint:backgroundcolor:bottombar:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration\/init(topbartitle:minimumquality:acknowledgementmode:badimagehint:backgroundcolor:bottombar:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"title":"SBSDKUI2Color"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementBottomBar":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementbottombar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementBottomBar","kind":"symbol","title":"SBSDKUI2AcknowledgementBottomBar","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"abstract":[{"type":"text","text":"Configuration of the bottom bar for the acknowledgement screen."}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQuality":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQuality","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentquality","title":"SBSDKDocumentQuality","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKDocumentQuality","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQuality"}],"role":"symbol","abstract":[{"type":"text","text":"The result of the document quality check."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext","kind":"symbol","title":"SBSDKUI2StyledText","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementMode":{"title":"SBSDKUI2AcknowledgementMode","abstract":[{"type":"text","text":"Determines, after each page is snapped, whether the acknowledgment screen should be displayed or not."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementmode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementMode"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IconUserGuidanceConfiguration":{"kind":"symbol","role":"symbol","title":"SBSDKUI2IconUserGuidanceConfiguration","type":"topic","abstract":[{"text":"Configuration of the hint (containing an icon) guiding users through the scanning process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2iconuserguidanceconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementScreenConfiguration":{"title":"SBSDKUI2AcknowledgementScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the acknowledgement screen."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementScreenConfiguration/init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)":{"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration\/init(topbartitle:minimumquality:acknowledgementmode:badimagehint:backgroundcolor:bottombar:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)","type":"topic","title":"init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"text":"minimumQuality","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentQuality"},{"kind":"text","text":", "},{"text":"acknowledgementMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2AcknowledgementMode","text":"SBSDKUI2AcknowledgementMode"},{"text":", ","kind":"text"},{"text":"badImageHint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration","text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomBar","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2AcknowledgementBottomBar","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTopBarTitle:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"text":"topBarTitle","kind":"internalParam"},{"kind":"text","text":" "},{"text":"minimumQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentQuality","text":"SBSDKDocumentQuality"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumQuality"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgementMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2AcknowledgementMode","text":"SBSDKUI2AcknowledgementMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"acknowledgementMode"},{"text":" ","kind":"text"},{"text":"badImageHint:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration","text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"badImageHint"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2AcknowledgementBottomBar","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bottomBar"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/title","value":"SBSDKUI2AcknowledgementBottomBar","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}]},{"value":"SBSDKDocumentQuality","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQuality\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQuality\/fragments","op":"replace","value":[{"text":"SBSDKDocumentQuality","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKDocumentQuality"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQuality\/navigatorTitle"},{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementMode\/title","op":"replace","value":"SBSDKUI2AcknowledgementMode"},{"op":"replace","value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/title","op":"replace","value":"SBSDKUI2IconUserGuidanceConfiguration"},{"value":[{"text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"op":"replace"},{"value":"SBSDKUI2AcknowledgementScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration~1init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)\/title","value":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration~1init(topBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}]}]}]}