{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVARecordFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AAMVARecordFieldType","text":"SBSDKUI2AAMVARecordFieldType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"typeString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvadocumentsubfilefield\/init(type:typestring:value:rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvadocumentsubfilefield\/init(type:typestring:value:rawvalue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVADocumentSubfileField\/init(type:typeString:value:rawValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2AAMVARecordFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AAMVARecordFieldType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"typeString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(type:typeString:value:rawValue:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2AAMVADocumentSubfileField(im)initWithType:typeString:value:rawValue:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithType:typeString:value:rawValue:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVADocumentSubfileField"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AAMVADocumentSubfileField/init(type:typeString:value:rawValue:)":{"role":"symbol","title":"init(type:typeString:value:rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2AAMVARecordFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AAMVARecordFieldType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"typeString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Designated initializer."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVADocumentSubfileField\/init(type:typeString:value:rawValue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithType:typeString:value:rawValue:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvadocumentsubfilefield\/init(type:typestring:value:rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AAMVARecordFieldType":{"role":"symbol","title":"SBSDKUI2AAMVARecordFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}],"abstract":[{"type":"text","text":"AAMVA Record Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVARecordFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvarecordfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2AAMVADocumentSubfileField":{"role":"symbol","title":"SBSDKUI2AAMVADocumentSubfileField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfileField"}],"abstract":[{"type":"text","text":"AAMVA Document Sub-File Field"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVADocumentSubfileField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfileField"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aamvadocumentsubfilefield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithType:typeString:value:rawValue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:typeString:value:rawValue:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2AAMVARecordFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2AAMVARecordFieldType","text":"SBSDKUI2AAMVARecordFieldType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"typeString"},{"kind":"text","text":" "},{"kind":"identifier","text":"value:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawValue"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVADocumentSubfileField~1init(type:typeString:value:rawValue:)\/title","value":"initWithType:typeString:value:rawValue:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVADocumentSubfileField~1init(type:typeString:value:rawValue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:typeString:value:rawValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVARecordFieldType\/title","value":"SBSDKUI2AAMVARecordFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVARecordFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVARecordFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVADocumentSubfileField\/title","value":"SBSDKUI2AAMVADocumentSubfileField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2AAMVADocumentSubfileField\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AAMVADocumentSubfileField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}