{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration\/licenseFailureHandler","interfaceLanguage":"swift"},"abstract":[{"text":"A custom handler for handling license validation failures. Defaults to a built-in handler.","type":"text"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"licenseFailureHandler","kind":"identifier"}],"title":"licenseFailureHandler","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)ScanbotSDKConfiguration(py)licenseFailureHandler","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseFailureHandler","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKLicenseFailureHandler","kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK26SBSDKLicenseFailureHandlera"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/licensefailurehandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/licensefailurehandler"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseFailureHandler","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseFailureHandler","text":"SBSDKLicenseFailureHandler","kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK26SBSDKLicenseFailureHandlera"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFeature":{"title":"SBSDKFeature","url":"\/documentation\/scanbotsdk\/sbsdkfeature","role":"symbol","navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}],"abstract":[{"text":"License features.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotSDKConfiguration":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/scanbotsdkconfiguration","abstract":[{"type":"codeVoice","code":"ScanbotSDKConfiguration"},{"text":" is a configuration class that allows you to customize various settings and behavior of the Scanbot SDK.","type":"text"}],"title":"ScanbotSDKConfiguration","navigatorTitle":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScanbotSDKConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus","type":"topic","abstract":[{"text":"Status of the license plate scanner.","type":"text"}],"title":"SBSDKLicenseStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotSDKConfiguration/licenseFailureHandler":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotSDKConfiguration\/licenseFailureHandler","url":"\/documentation\/scanbotsdk\/scanbotsdkconfiguration\/licensefailurehandler","type":"topic","abstract":[{"text":"A custom handler for handling license validation failures. Defaults to a built-in handler.","type":"text"}],"title":"licenseFailureHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseFailureHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ScanbotSDK26SBSDKLicenseFailureHandlera","text":"SBSDKLicenseFailureHandler"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"licenseFailureHandler"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseFailureHandler":{"title":"SBSDKLicenseFailureHandler","role":"symbol","navigatorTitle":[{"text":"SBSDKLicenseFailureHandler","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensefailurehandler","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseFailureHandler","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseFailureHandler","abstract":[{"type":"text","text":"Typealias for license failure handling closure."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"licenseFailureHandler","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"licenseFailureHandler"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":"licenseFailureHandler","kind":"identifier"},{"text":")(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKFeature","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFeature","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/title","value":"SBSDKFeature","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFeature\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/title","value":"ScanbotSDKConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/fragments","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration\/navigatorTitle","value":[{"text":"ScanbotSDKConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title","value":"SBSDKLicenseStatus","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration~1licenseFailureHandler\/title","value":"licenseFailureHandler","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotSDKConfiguration~1licenseFailureHandler\/fragments","value":[{"text":"licenseFailureHandler","kind":"identifier"}],"op":"replace"}]}]}