{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannerstatus\/detected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannerstatus\/detected"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus\/detected"},"sections":[],"abstract":[{"type":"text","text":"The scanner has detected something."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detected","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKScannerStatus@SBSDKScannerStatusDetected","navigatorTitle":[{"text":"SBSDKScannerStatusDetected","kind":"identifier"}],"role":"symbol","title":"SBSDKScannerStatus.detected","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detected","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannerStatus":{"navigatorTitle":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"abstract":[{"text":"This enum describes the possible scanning states of any scanner.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"identifier"}],"role":"symbol","title":"SBSDKScannerStatus","url":"\/documentation\/scanbotsdk\/sbsdkscannerstatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannerStatus/detected":{"type":"topic","abstract":[{"text":"The scanner has detected something.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannerStatus\/detected","title":"SBSDKScannerStatus.detected","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatusDetected"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannerstatus\/detected","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detected","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKScannerStatusDetected"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKScannerStatusDetected"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKScannerStatusDetected"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus\/title","value":"SBSDKScannerStatus"},{"value":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus~1detected\/title","value":"SBSDKScannerStatusDetected"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannerStatus~1detected\/fragments","value":[{"kind":"identifier","text":"SBSDKScannerStatusDetected"}],"op":"replace"}]}]}