{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithSheetColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sheetColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dividerColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dividerColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountChangeEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"manualCountChangeEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountOutlineColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manualCountOutlineColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountChangeColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manualCountChangeColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"title:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"clearAllButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"clearAllButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeItemTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeItemTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeItemSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeItemSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeItemImageVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"barcodeItemImageVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"submitButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"submitButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"startScanningButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"startScanningButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeholderTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeholderTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeholderSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeholderSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeholderIconBackground:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeholderIconBackground","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeholderIcon:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2IconStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconStyle","text":"SBSDKUI2IconStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeholderIcon","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"swipeToDelete:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SwipeToDelete","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwipeToDelete","text":"SBSDKUI2SwipeToDelete","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"swipeToDelete","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent\/initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent"]]},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent(im)initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:"}],"title":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent\/initwithsheetcolor:dividercolor:manualcountchangeenabled:manualcountoutlinecolor:manualcountchangecolor:title:clearallbutton:barcodeitemtitle:barcodeitemsubtitle:barcodeitemimagevisible:submitbutton:startscanningbutton:placeholdertitle:plac-40t2r"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","title":"SBSDKUI2ButtonConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration of the button."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2buttonconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetContent":{"role":"symbol","kind":"symbol","title":"SBSDKUI2SheetContent","abstract":[{"type":"text","text":"Configuration of the list containing the barcodes that have already been scanned."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","title":"SBSDKUI2Color","abstract":[],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconStyle":{"title":"SBSDKUI2IconStyle","abstract":[{"text":"Configuration of the icon appearance.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconStyle","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconstyle","role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetContent/initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent\/initwithsheetcolor:dividercolor:manualcountchangeenabled:manualcountoutlinecolor:manualcountchangecolor:title:clearallbutton:barcodeitemtitle:barcodeitemsubtitle:barcodeitemimagevisible:submitbutton:startscanningbutton:placeholdertitle:plac-40t2r","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent\/initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:","kind":"symbol","navigatorTitle":[{"text":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:","kind":"identifier"}],"title":"initWithSheetColor:dividerColor:manualCountChangeEnabled:manualCountOutlineColor:manualCountChangeColor:title:clearAllButton:barcodeItemTitle:barcodeItemSubtitle:barcodeItemImageVisible:submitButton:startScanningButton:placeholderTitle:placeholderSubtitle:placeholderIconBackground:placeholderIcon:swipeToDelete:","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SwipeToDelete":{"title":"SBSDKUI2SwipeToDelete","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SwipeToDelete","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2swipetodelete","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the swipe-to-delete button."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SwipeToDelete","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2SwipeToDelete","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText":{"abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"title":"SBSDKUI2StyledText","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2SheetContent","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title","op":"replace"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2IconStyle","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/title","op":"replace"},{"value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2SwipeToDelete","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwipeToDelete\/title","op":"replace"},{"value":[{"text":"SBSDKUI2SwipeToDelete","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwipeToDelete\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2SwipeToDelete","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SwipeToDelete\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}