{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(sampleBuffer:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Initializes a frame from a sample buffer as it is typically aquired from the camera.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"sampleBuffer","content":[{"inlineContent":[{"text":"The sample buffer to initialize the receiver from.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe\/init(samplebuffer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe\/init(samplebuffer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame"]]},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithSampleBuffer:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerFrame(im)initWithSampleBuffer:","title":"init(sampleBuffer:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame/init(sampleBuffer:)":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe\/init(samplebuffer:)","abstract":[{"type":"text","text":"Initializes a frame from a sample buffer as it is typically aquired from the camera."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSampleBuffer:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(sampleBuffer:)","title":"init(sampleBuffer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":")"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame":{"title":"SBSDKBaseScannerFrame","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame","kind":"symbol","navigatorTitle":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"abstract":[{"type":"text","text":"A wrapper class for video frames."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithSampleBuffer:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSampleBuffer:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithSampleBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@opaqueCMSampleBuffer","text":"opaqueCMSampleBuffer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"sampleBuffer","content":[{"type":"paragraph","inlineContent":[{"text":"The sample buffer to initialize the receiver from.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"initWithSampleBuffer:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1init(sampleBuffer:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1init(sampleBuffer:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSampleBuffer:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/title","value":"SBSDKBaseScannerFrame","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"op":"replace"}]}]}