{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep\/shouldmatchsubstring"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep\/shouldmatchsubstring"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldMatchSubstring","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"code":"False","type":"codeVoice"},{"type":"text","text":"."}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep"]]},"abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"text":" the pattern validation also validates successfully if only a part of the whole recognized text matches","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the the validation pattern."},{"type":"text","text":" "},{"type":"text","text":"If set to "},{"type":"codeVoice","code":"False"},{"type":"text","text":", the whole text must match the validation pattern."},{"type":"text","text":" "},{"type":"text","text":"Applies to pattern validation only."}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldMatchSubstring","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"shouldMatchSubstring"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"shouldMatchSubstring","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextDataScannerStep(py)shouldMatchSubstring","roleHeading":"Instance Property"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep\/shouldMatchSubstring","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStep/shouldMatchSubstring":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep\/shouldMatchSubstring","kind":"symbol","abstract":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":" the pattern validation also validates successfully if only a part of the whole recognized text matches","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the the validation pattern."},{"text":" ","type":"text"},{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"False"},{"text":", the whole text must match the validation pattern.","type":"text"},{"text":" ","type":"text"},{"text":"Applies to pattern validation only.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep\/shouldmatchsubstring","navigatorTitle":[{"text":"shouldMatchSubstring","kind":"identifier"}],"title":"shouldMatchSubstring","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldMatchSubstring","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerStep":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerStep","role":"symbol","abstract":[{"type":"text","text":"Defines a single workflow step of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","isActive":true},{"type":"text","text":" flow."}],"title":"SBSDKUITextDataScannerStep","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextDataScannerStep"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerstep","navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextDataScannerStep"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextDataScannerViewController":{"abstract":[{"text":"A highly customizable camera-based view controller to recognize and validate a small rectangular text area in realtime.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextDataScannerViewController","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextdatascannerviewcontroller","role":"symbol","title":"SBSDKUITextDataScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUITextDataScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"shouldMatchSubstring"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"shouldMatchSubstring","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldMatchSubstring"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep~1shouldMatchSubstring\/title","value":"shouldMatchSubstring"},{"value":[{"text":"shouldMatchSubstring","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep~1shouldMatchSubstring\/fragments"},{"value":"SBSDKUITextDataScannerStep","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerStep\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerStep"}]},{"value":"SBSDKUITextDataScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextDataScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextDataScannerViewController\/fragments"}]}]}