{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaVehicleDataEngineSizeFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Type Property","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvaVehicleDataEngineSizeFieldNormalizedName","symbolKind":"property","title":"aamvaVehicleDataEngineSizeFieldNormalizedName","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"aamvaVehicleDataEngineSizeFieldNormalizedName"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleDataEngineSizeFieldNormalizedName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants"]]},"abstract":[{"type":"text","text":"Normalized full name of the “EngineSize” field type in document type “AAMVA.VehicleData”."}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicledataenginesizefieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicledataenginesizefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleDataEngineSizeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants","abstract":[],"title":"SBSDKBarcodeDocumentConstants","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants","type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants/aamvaVehicleDataEngineSizeFieldNormalizedName":{"navigatorTitle":[{"text":"aamvaVehicleDataEngineSizeFieldNormalizedName","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/aamvavehicledataenginesizefieldnormalizedname","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleDataEngineSizeFieldNormalizedName","role":"symbol","title":"aamvaVehicleDataEngineSizeFieldNormalizedName","abstract":[{"type":"text","text":"Normalized full name of the “EngineSize” field type in document type “AAMVA.VehicleData”."}],"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleDataEngineSizeFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"aamvaVehicleDataEngineSizeFieldNormalizedName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"aamvaVehicleDataEngineSizeFieldNormalizedName"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"aamvaVehicleDataEngineSizeFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/title","op":"replace","value":"SBSDKBarcodeDocumentConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleDataEngineSizeFieldNormalizedName\/title","op":"replace","value":"aamvaVehicleDataEngineSizeFieldNormalizedName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleDataEngineSizeFieldNormalizedName\/fragments","op":"replace","value":[{"kind":"identifier","text":"aamvaVehicleDataEngineSizeFieldNormalizedName"}]}]}]}