{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/customDocumentType"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/customdocumenttype"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/customdocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Document type name of the “VCard.Custom” document type."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"customDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","roleHeading":"Type Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)customDocumentType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","navigatorTitle":[{"text":"customDocumentType","kind":"identifier"}],"title":"customDocumentType"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants/customDocumentType":{"navigatorTitle":[{"kind":"identifier","text":"customDocumentType"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"customDocumentType","abstract":[{"type":"text","text":"Document type name of the “VCard.Custom” document type."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants\/customdocumenttype","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants\/customDocumentType"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentConstants":{"title":"SBSDKBarcodeDocumentConstants","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentConstants","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentconstants","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"customDocumentType","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"customDocumentType","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"customDocumentType"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"customDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1customDocumentType\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants~1customDocumentType\/fragments","value":[{"kind":"identifier","text":"customDocumentType"}]},{"value":"SBSDKBarcodeDocumentConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"op":"replace"}]}]}