{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine\/dosingUnit","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","title":"dosingUnit","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine(py)dosingUnit","navigatorTitle":[{"kind":"identifier","text":"dosingUnit"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dosingUnit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"abstract":[{"type":"text","text":"Dosing Unit."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dosingUnit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingmedicine\/dosingunit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingmedicine\/dosingunit"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentField":{"abstract":[{"text":"A generic document field.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentfield","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","kind":"symbol","title":"SBSDKGenericDocumentField","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine":{"title":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine","abstract":[{"type":"text","text":"Medicine."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingmedicine","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine/dosingUnit":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine\/dosingUnit","title":"dosingUnit","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"dosingUnit","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dosingUnit"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Dosing Unit."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentdemedicalplansubheadingmedicine\/dosingunit"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dosingUnit","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dosingUnit"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"text":"dosingUnit","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"value":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine\/navigatorTitle"},{"value":"dosingUnit","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine~1dosingUnit\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentDEMedicalPlanSubheadingMedicine~1dosingUnit\/fragments","value":[{"kind":"identifier","text":"dosingUnit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}