{"abstract":[{"text":"If non-nil, overrides the default image encryption provider.","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKIndexedImageStorage(py)cryptingProvider","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"cryptingProvider","kind":"identifier"}],"title":"cryptingProvider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cryptingProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/cryptingProvider"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cryptingProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/cryptingprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/cryptingprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingProvider":{"abstract":[{"text":"Protocol for providing a storage crypting object.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"title":"SBSDKStorageCryptingProvider","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingprovider","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage":{"title":"SBSDKIndexedImageStorage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage/cryptingProvider":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cryptingProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"cryptingProvider"}],"title":"cryptingProvider","kind":"symbol","abstract":[{"type":"text","text":"If non-nil, overrides the default image encryption provider."}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/cryptingprovider","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/cryptingProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"cryptingProvider","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cryptingProvider"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"id<SBSDKStorageCryptingProvider>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"cryptingProvider","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/title","value":"SBSDKStorageCryptingProvider","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/fragments","value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/title","value":"SBSDKIndexedImageStorage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1cryptingProvider\/title","value":"cryptingProvider","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1cryptingProvider\/fragments","value":[{"kind":"identifier","text":"cryptingProvider"}],"op":"replace"}]}]}