{"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefProfiler(cm)diffWithFirstSnapshot:secondSnapshot:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"diff"},{"kind":"text","text":"("},{"kind":"externalParam","text":"firstSnapshot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secondSnapshot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshotsDiff","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","title":"diff(firstSnapshot:secondSnapshot:)","navigatorTitle":[{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)"},"abstract":[{"type":"text","text":"Computes difference between two snapshots. To confirm that a particular operation doesn’t leak, take a snapshot"},{"type":"text","text":" "},{"type":"text","text":"before and after the operation, and check that the diff doesn’t contain any unexpected new ImageRefs."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"diff"},{"kind":"text","text":"("},{"kind":"externalParam","text":"firstSnapshot"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secondSnapshot"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshotsDiff","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshotsDiff"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"firstSnapshot","content":[{"type":"paragraph","inlineContent":[{"text":"Snapshot that was taken earlier","type":"text"}]}]},{"name":"secondSnapshot","content":[{"inlineContent":[{"text":"Snapshot that was taken later","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"Difference between two snapshots"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefPoolSnapshot":{"abstract":[{"type":"text","text":"Snapshot of all alive ImageRefs."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot","url":"\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshot","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"title":"SBSDKImageRefPoolSnapshot","role":"symbol","navigatorTitle":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler","url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler","title":"SBSDKImageRefProfiler","kind":"symbol","abstract":[{"text":"ImageRef memory profiler.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefPoolSnapshotsDiff":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshotsDiff","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagerefpoolsnapshotsdiff","title":"SBSDKImageRefPoolSnapshotsDiff","navigatorTitle":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"abstract":[{"type":"text","text":"difference between two snapshots."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRefProfiler/diff(firstSnapshot:secondSnapshot:)":{"abstract":[{"text":"Computes difference between two snapshots. To confirm that a particular operation doesn’t leak, take a snapshot","type":"text"},{"text":" ","type":"text"},{"text":"before and after the operation, and check that the diff doesn’t contain any unexpected new ImageRefs.","type":"text"}],"title":"diff(firstSnapshot:secondSnapshot:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"diff"},{"kind":"text","text":"("},{"kind":"externalParam","text":"firstSnapshot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secondSnapshot"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SBSDKImageRefPoolSnapshotsDiff","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","navigatorTitle":[{"kind":"identifier","text":"diffWithFirstSnapshot:secondSnapshot:"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"diffWithFirstSnapshot:secondSnapshot:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshotsDiff","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff"},{"text":" *) ","kind":"text"},{"text":"diffWithFirstSnapshot:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"text":" *) ","kind":"text"},{"text":"firstSnapshot","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"secondSnapshot:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRefPoolSnapshot","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRefPoolSnapshot"},{"text":" *) ","kind":"text"},{"text":"secondSnapshot","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Snapshot that was taken earlier"}]}],"name":"firstSnapshot"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Snapshot that was taken later","type":"text"}]}],"name":"secondSnapshot"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Difference between two snapshots","type":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/title","value":"SBSDKImageRefPoolSnapshot"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshot"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/title","value":"SBSDKImageRefProfiler"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}]},{"value":"SBSDKImageRefPoolSnapshotsDiff","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshotsDiff\/title"},{"value":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshotsDiff\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageRefPoolSnapshotsDiff"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefPoolSnapshotsDiff\/navigatorTitle"},{"value":"diffWithFirstSnapshot:secondSnapshot:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/fragments"}]}]}