{"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerController(_:didScanMRZ:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerControllerShouldScanMRZ(_:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/sbsdkmrzscannerviewcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/sbsdkmrzscannerviewcontrollerdelegate-implementations"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/SBSDKMRZScannerViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMRZScannerViewControllerDelegate Implementations"},"sections":[],"kind":"article","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to detect machine readable zones.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"title":"SBSDKUIMRZScannerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"deprecated":true,"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController/mrzScannerControllerShouldScanMRZ(_:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerControllerShouldScanMRZ(_:)","title":"mrzScannerControllerShouldScanMRZ(_:)","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/mrzscannercontrollershouldscanmrz(_:)","abstract":[{"text":"Asks the delegate if the scanner should detect machine-readable zones on the next video frame.","type":"text"},{"text":" ","type":"text"},{"text":"Optional.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScannerControllerShouldScanMRZ"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","text":"SBSDKMRZScannerViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mrzScannerControllerShouldScanMRZ:"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController/mrzScannerController(_:didScanMRZ:)":{"title":"mrzScannerController(_:didScanMRZ:)","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/mrzscannercontroller(_:didscanmrz:)","role":"symbol","navigatorTitle":[{"text":"mrzScannerController:didScanMRZ:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerController(_:didScanMRZ:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","text":"SBSDKMRZScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didScanMRZ","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult","text":"SBSDKMRZScannerResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Informs the delegate that the scanner has scanned a machine-readable zone.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerController(_:didScanMRZ:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/mrzScannerControllerShouldScanMRZ(_:)"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/title","value":"SBSDKUIMRZScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1mrzScannerControllerShouldScanMRZ(_:)\/title","value":"mrzScannerControllerShouldScanMRZ:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1mrzScannerControllerShouldScanMRZ(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScannerControllerShouldScanMRZ:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1mrzScannerController(_:didScanMRZ:)\/title","value":"mrzScannerController:didScanMRZ:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController~1mrzScannerController(_:didScanMRZ:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mrzScannerController:didScanMRZ:","kind":"identifier"}]}]}]}