{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/supportedInterfaceOrientations"},"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIMRZScannerViewController(py)supportedInterfaceOrientations","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"modules":[{"name":"ScanbotSDK"}],"title":"supportedInterfaceOrientations"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/supportedinterfaceorientations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIInterfaceOrientationMask","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientationMask"},{"text":" ","kind":"text"},{"text":"supportedInterfaceOrientations","kind":"identifier"},{"text":";","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController","abstract":[{"text":"A highly customizable camera-based view controller to detect machine readable zones.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"title":"SBSDKUIMRZScannerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"deprecated":true,"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIMRZScannerViewController/supportedInterfaceOrientations":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"supportedInterfaceOrientations","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIMRZScannerViewController\/supportedInterfaceOrientations","url":"\/documentation\/scanbotsdk\/sbsdkuimrzscannerviewcontroller\/supportedinterfaceorientations","title":"supportedInterfaceOrientations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUIMRZScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIMRZScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKUIMRZScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIMRZScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}