{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"keyProvider"}],"symbolKind":"property","title":"keyProvider","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAESGCMEncrypter(py)keyProvider","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyProvider"},{"kind":"text","text":": "},{"text":"SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyProvider"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyProvider"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"The key provider that provides\/generates the encryption keys.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/keyprovider"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/keyprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/keyProvider"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter/keyProvider":{"navigatorTitle":[{"text":"keyProvider","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The key provider that provides\/generates the encryption keys."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter\/keyProvider","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyProvider"}],"url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter\/keyprovider","title":"keyProvider"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESGCMEncrypter":{"navigatorTitle":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesgcmencrypter","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"type":"topic","abstract":[{"text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider.","type":"text"},{"type":"text","text":" "},{"text":"Supports encryption and decryption of single data blocks as well as streaming data.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESGCMEncrypter","title":"SBSDKAESGCMEncrypter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol for loading, storing and providing encryption keys."},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","title":"SBSDKStorageCryptingKeyProvider"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"keyProvider"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"keyProvider","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<SBSDKStorageCryptingKeyProvider>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider"},{"kind":"text","text":" "},{"text":"keyProvider","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter~1keyProvider\/title","op":"replace","value":"keyProvider"},{"op":"replace","value":[{"kind":"identifier","text":"keyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter~1keyProvider\/fragments"},{"value":"SBSDKAESGCMEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/fragments","value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESGCMEncrypter\/navigatorTitle","op":"replace","value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/title","op":"replace","value":"SBSDKStorageCryptingKeyProvider"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}