{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeIdCardBack\/initWithGenericDocument:"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"initWithGenericDocument:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentDeIdCardBack(im)initWithGenericDocument:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeIdCardBack"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithGenericDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"text":"document","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentdeidcardback\/initwithgenericdocument:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"abstract":[{"text":"Represents a generic document with fields and sub-documents used for document recognition.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","title":"SBSDKGenericDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeIdCardBack/initWithGenericDocument:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeIdCardBack\/initWithGenericDocument:","kind":"symbol","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdeidcardback\/initwithgenericdocument:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentDeIdCardBack":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentDeIdCardBack"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentDeIdCardBack","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentDeIdCardBack"}],"title":"SBSDKGenericDocumentDeIdCardBack","abstract":[{"text":"German ID card, back side.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentdeidcardback"}},"variantOverrides":[{"patch":[{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeIdCardBack\/title","value":"SBSDKGenericDocumentDeIdCardBack","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentDeIdCardBack\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentDeIdCardBack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}