{"metadata":{"navigatorTitle":[{"text":"initWithKeyProvider:mode:perFileEncryption:","kind":"identifier"}],"role":"symbol","title":"init(keyProvider:mode:perfileEncryption:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAESEncrypter(im)initWithKeyProvider:mode:perFileEncryption:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKAESEncrypterMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode"},{"text":", ","kind":"text"},{"text":"perfileEncryption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"symbolKind":"init"},"kind":"symbol","abstract":[{"text":"Extended initializer.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithKeyProvider:mode:perFileEncryption:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingKeyProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKAESEncrypterMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode"},{"text":", ","kind":"text"},{"text":"perfileEncryption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"keyProvider","content":[{"inlineContent":[{"text":"The key provider used to generate, store, and retrieve encryption keys.","type":"text"}],"type":"paragraph"}]},{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"text":"The value of  ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","isActive":true},{"text":" that specifies the AES encryption mode to be used.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaesencrypter\/init(keyprovider:mode:perfileencryption:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaesencrypter\/init(keyprovider:mode:perfileencryption:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter\/init(keyProvider:mode:perfileEncryption:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyProvider":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyProvider","abstract":[{"text":"Protocol for loading, storing and providing encryption keys.","type":"text"},{"text":" ","type":"text"},{"text":"The context parameter is used to distinguish between different encryption contexts.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyProvider"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeyprovider","title":"SBSDKStorageCryptingKeyProvider","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypterMode":{"abstract":[{"text":"An enum containing the available encryption modes for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","title":"SBSDKAESEncrypterMode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesencryptermode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter","navigatorTitle":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"title":"SBSDKAESEncrypter","abstract":[{"type":"text","text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data."},{"type":"text","text":" "},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESEncrypter"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter/init(keyProvider:mode:perfileEncryption:)":{"kind":"symbol","abstract":[{"text":"Extended initializer.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithKeyProvider:mode:perFileEncryption:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter\/init(keyProvider:mode:perfileEncryption:)","url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter\/init(keyprovider:mode:perfileencryption:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider","text":"SBSDKStorageCryptingKeyProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode","text":"SBSDKAESEncrypterMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"perfileEncryption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"type":"topic","title":"init(keyProvider:mode:perfileEncryption:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithKeyProvider:mode:perFileEncryption:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithKeyProvider:mode:perFileEncryption:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithKeyProvider:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKStorageCryptingKeyProvider>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyProvider"},{"text":") ","kind":"text"},{"text":"keyProvider","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESEncrypterMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKAESEncrypterMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode"},{"text":") ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"perFileEncryption:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"perfileEncryption","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"keyProvider","content":[{"inlineContent":[{"text":"The key provider used to generate, store, and retrieve encryption keys.","type":"text"}],"type":"paragraph"}]},{"name":"mode","content":[{"inlineContent":[{"text":"The value of  ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypterMode","type":"reference"},{"text":" that specifies the AES encryption mode to be used.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKStorageCryptingKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/title"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/fragments"},{"op":"replace","value":[{"text":"SBSDKStorageCryptingKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyProvider\/navigatorTitle"},{"op":"replace","value":"SBSDKAESEncrypterMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/title"},{"op":"replace","value":[{"text":"SBSDKAESEncrypterMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAESEncrypterMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypterMode\/navigatorTitle"},{"op":"replace","value":"SBSDKAESEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/title"},{"op":"replace","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/navigatorTitle"},{"op":"replace","value":"initWithKeyProvider:mode:perFileEncryption:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter~1init(keyProvider:mode:perfileEncryption:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithKeyProvider:mode:perFileEncryption:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter~1init(keyProvider:mode:perfileEncryption:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}