{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult\/copyWithZone:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult(im)copyWithZone:","roleHeading":"Instance Method","role":"symbol","title":"copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionResult":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","title":"SBSDKDocumentDataExtractionResult","abstract":[{"text":"Contains the result of running the generic document extractor.","type":"text"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionResult/copyWithZone:":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult\/copywithzone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult\/copyWithZone:","title":"copyWithZone:","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/title","op":"replace","value":"SBSDKDocumentDataExtractionResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/fragments","op":"replace","value":[{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}]}]}]}