{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageObserver"]]},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scannedPageDidChangeImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKScannedPage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKScannedPageImageType","text":"SBSDKScannedPageImageType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"scannedPageDidChangeImage:of:image:"}],"title":"scannedPageDidChangeImage(_:of:image:)","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKScannedPageObserver(im)scannedPageDidChangeImage:of:image:","role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageObserver\/scannedPageDidChangeImage(_:of:image:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scannedPageDidChangeImage"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"page","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage","text":"SBSDKScannedPage"},{"kind":"text","text":", "},{"text":"of","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKScannedPageImageType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType","kind":"typeIdentifier","text":"SBSDKScannedPageImageType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"page","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page that changed its image."}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the image that has been changed."}]}]},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The new image or nil, if the image has been invalidated."}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageobserver\/scannedpagedidchangeimage(_:of:image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscannedpageobserver\/scannedpagedidchangeimage(_:of:image:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Informs the observers that one of the images of a scanned page has been changed.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedPage"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpage","abstract":[{"text":"A scanned page (","type":"text"},{"type":"codeVoice","code":"SBSDKScannedPage"},{"type":"text","text":") is a representation of a scanned documents page in digital form."},{"type":"text","text":" "},{"text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","title":"SBSDKScannedPage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageObserver/scannedPageDidChangeImage(_:of:image:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageObserver\/scannedPageDidChangeImage(_:of:image:)","abstract":[{"text":"Informs the observers that one of the images of a scanned page has been changed.","type":"text"}],"title":"scannedPageDidChangeImage(_:of:image:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scannedPageDidChangeImage:of:image:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkscannedpageobserver\/scannedpagedidchangeimage(_:of:image:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scannedPageDidChangeImage"},{"kind":"text","text":"("},{"text":"SBSDKScannedPage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"of","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKScannedPageImageType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKScannedPageImageType"},{"kind":"text","text":", "},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?)","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageImageType":{"abstract":[{"text":"An enum representing the different types of images a scanned page has.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscannedpageimagetype","type":"topic","kind":"symbol","title":"SBSDKScannedPageImageType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageImageType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPageObserver":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKScannedPageObserver"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedPageObserver"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageObserver","url":"\/documentation\/scanbotsdk\/sbsdkscannedpageobserver","role":"symbol","abstract":[{"text":"A delegation-like protocol for observing changes on an instance of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","isActive":true},{"type":"text","text":"."}],"title":"SBSDKScannedPageObserver"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"scannedPageDidChangeImage:of:image:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scannedPageDidChangeImage:of:image:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"scannedPageDidChangeImage:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage","text":"SBSDKScannedPage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"page"},{"kind":"text","text":" "},{"kind":"identifier","text":"of:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKScannedPageImageType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPageImageType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKScannedPageImageType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"image:"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"page","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The page that changed its image."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The type of the image that has been changed.","type":"text"}]}],"name":"type"},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The new image or nil, if the image has been invalidated."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKScannedPage","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedPage"}],"op":"replace"},{"value":[{"text":"SBSDKScannedPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageObserver~1scannedPageDidChangeImage(_:of:image:)\/title","value":"scannedPageDidChangeImage:of:image:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scannedPageDidChangeImage:of:image:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageObserver~1scannedPageDidChangeImage(_:of:image:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/title","value":"SBSDKScannedPageImageType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/fragments","value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}]},{"value":[{"text":"SBSDKScannedPageImageType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageImageType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageObserver\/title","value":"SBSDKScannedPageObserver"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageObserver\/fragments","value":[{"kind":"identifier","text":"SBSDKScannedPageObserver"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKScannedPageObserver"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPageObserver\/navigatorTitle","op":"replace"}]}]}