{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/equatable-implementations"]}],"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/!=(_:_:)"],"title":"Operators","generated":true}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/!=(_:_:)":{"title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/!=(_:_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/!=(_:_:)","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"abstract":[{"type":"text","text":"Type of MSI plessey checksum algorithm used."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title","op":"replace","value":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/navigatorTitle","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}