{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mod11Ibm","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod11Ibm","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm@SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm","role":"symbol","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod11Ibm","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod11Ibm"}]},"abstract":[{"type":"text","text":"Mod11IBM checksum algorithm"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/mod11ibm"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/mod11ibm"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/mod11Ibm":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mod11Ibm","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/mod11ibm","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.mod11Ibm","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/mod11Ibm","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm","kind":"identifier"}],"abstract":[{"type":"text","text":"Mod11IBM checksum algorithm"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"abstract":[{"text":"Type of MSI plessey checksum algorithm used.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod11Ibm\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1mod11Ibm\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmMod11Ibm"}]},{"value":"SBSDKUI2MSIPlesseyChecksumAlgorithm","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}]}]}]}