{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/none"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"No checksum algorithm used."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/none","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm@SBSDKUI2MSIPlesseyChecksumAlgorithmNone","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"role":"symbol","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.none"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm/none":{"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm\/none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm.none","abstract":[{"type":"text","text":"No checksum algorithm used."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm\/none"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","type":"topic","abstract":[{"text":"Type of MSI plessey checksum algorithm used.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1none\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone"},{"op":"replace","value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithmNone","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm~1none\/fragments"},{"op":"replace","value":"SBSDKUI2MSIPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title"},{"value":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments"}]}]}