{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"type":"text","text":" "},{"type":"text","text":"No visible borders. Video may be cropped to the visible screen area."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}],"title":"SBSDKVideoContentMode.fillIn","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKVideoContentMode@SBSDKVideoContentModeFillIn","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fillin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fillin"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode/fillIn":{"url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode\/fillin","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode\/fillIn","abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"type":"text","text":" "},{"type":"text","text":"No visible borders. Video may be cropped to the visible screen area."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillIn"}],"title":"SBSDKVideoContentMode.fillIn","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoContentMode":{"title":"SBSDKVideoContentMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoContentMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkvideocontentmode","navigatorTitle":[{"text":"SBSDKVideoContentMode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoContentMode","type":"topic","abstract":[{"type":"text","text":"Enumeration of video preview content mode."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVideoContentModeFillIn"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKVideoContentModeFillIn","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fillIn\/title","value":"SBSDKVideoContentModeFillIn"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode~1fillIn\/fragments","value":[{"text":"SBSDKVideoContentModeFillIn","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/title","value":"SBSDKVideoContentMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoContentMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoContentMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoContentMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}