{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"partiallyVisibleDocumentConfiguration"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerConfiguration(py)partiallyVisibleDocumentConfiguration","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"partiallyVisibleDocumentConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partiallyVisibleDocumentConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration","text":"SBSDKPartiallyVisibleDocumentConfiguration"}]},"abstract":[{"type":"text","text":"Configuration for handling partially visible documents."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerconfiguration\/partiallyvisibledocumentconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerconfiguration\/partiallyvisibledocumentconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerConfiguration\/partiallyVisibleDocumentConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partiallyVisibleDocumentConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration","kind":"typeIdentifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerConfiguration/partiallyVisibleDocumentConfiguration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"partiallyVisibleDocumentConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPartiallyVisibleDocumentConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerconfiguration\/partiallyvisibledocumentconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerConfiguration\/partiallyVisibleDocumentConfiguration","title":"partiallyVisibleDocumentConfiguration","role":"symbol","abstract":[{"text":"Configuration for handling partially visible documents.","type":"text"}],"navigatorTitle":[{"text":"partiallyVisibleDocumentConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerConfiguration":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerconfiguration","abstract":[{"type":"text","text":"Configuration for the document scanner."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerConfiguration"}],"title":"SBSDKDocumentScannerConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"title":"SBSDKPartiallyVisibleDocumentConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for handling partially visible documents."}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration","navigatorTitle":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"partiallyVisibleDocumentConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"partiallyVisibleDocumentConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration"},{"text":" * ","kind":"text"},{"text":"partiallyVisibleDocumentConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"partiallyVisibleDocumentConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerConfiguration~1partiallyVisibleDocumentConfiguration\/title"},{"op":"replace","value":[{"text":"partiallyVisibleDocumentConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerConfiguration~1partiallyVisibleDocumentConfiguration\/fragments"},{"op":"replace","value":"SBSDKDocumentScannerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKPartiallyVisibleDocumentConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}