{"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeStructure"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case","roleHeading":"Case","title":"SBSDKGS1Handling.decodeStructure","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling@SBSDKGS1HandlingDecodeStructure","navigatorTitle":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decodestructure"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decodestructure"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"decodeStructure","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeStructure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Same as VALIDATE_STRUCTURE. Additionally, GS1 strings are converted to the human-readable format,"},{"type":"text","text":" "},{"type":"text","text":"instead (with parentheses used to wrap AI keys, e.g. “(01)123456789”). The \\x1D character is"},{"type":"text","text":" "},{"type":"text","text":"never used in this representation."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","type":"topic","title":"SBSDKGS1Handling","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGS1Handling"}],"navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"text":"The GS1 standard defines a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"type":"text","text":" "},{"type":"text","text":"barcode types."},{"text":" ","type":"text"},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","kind":"symbol","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/decodeStructure":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeStructure","navigatorTitle":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decodestructure","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodeStructure","kind":"identifier"}],"title":"SBSDKGS1Handling.decodeStructure","type":"topic","abstract":[{"type":"text","text":"Same as VALIDATE_STRUCTURE. Additionally, GS1 strings are converted to the human-readable format,"},{"type":"text","text":" "},{"type":"text","text":"instead (with parentheses used to wrap AI keys, e.g. “(01)123456789”). The \\x1D character is"},{"type":"text","text":" "},{"type":"text","text":"never used in this representation."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKGS1HandlingDecodeStructure"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","op":"replace","value":"SBSDKGS1Handling"},{"value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decodeStructure\/title","value":"SBSDKGS1HandlingDecodeStructure"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decodeStructure\/fragments","value":[{"text":"SBSDKGS1HandlingDecodeStructure","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}