{"abstract":[{"text":"Accessibility description for the ‘close scanner’ button in the alerts.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionclosescannerbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionclosescannerbutton"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCloseScannerButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is “Close the scanner”"}]}],"kind":"content"}],"metadata":{"symbolKind":"property","title":"accessibilityDescriptionCloseScannerButton","roleHeading":"Instance Property","navigatorTitle":[{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization(py)accessibilityDescriptionCloseScannerButton"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCloseScannerButton"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/accessibilityDescriptionCloseScannerButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/accessibilitydescriptionclosescannerbutton","navigatorTitle":[{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/accessibilityDescriptionCloseScannerButton","kind":"symbol","type":"topic","abstract":[{"text":"Accessibility description for the ‘close scanner’ button in the alerts.","type":"text"}],"title":"accessibilityDescriptionCloseScannerButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"kind":"symbol","abstract":[{"text":"Configuration of the all strings for document data extractor screen.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}],"role":"symbol","type":"topic","title":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accessibilityDescriptionCloseScannerButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionCloseScannerButton","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCloseScannerButton\/title","value":"accessibilityDescriptionCloseScannerButton"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1accessibilityDescriptionCloseScannerButton\/fragments","value":[{"kind":"identifier","text":"accessibilityDescriptionCloseScannerButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/title","value":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}