{"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldValueSemantics(im)initWithFieldFullName:invalidSemantics:","title":"initWithFieldFullName:invalidSemantics:","fragments":[{"kind":"text","text":"- "},{"text":"initWithFieldFullName:invalidSemantics:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithFieldFullName:invalidSemantics:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldValueSemantics\/initWithFieldFullName:invalidSemantics:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkfieldvaluesemantics\/initwithfieldfullname:invalidsemantics:"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFieldFullName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"fieldFullName","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidSemantics:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"invalidSemantics"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldValueSemantics"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldValueSemantics":{"url":"\/documentation\/scanbotsdk\/sbsdkfieldvaluesemantics","type":"topic","title":"SBSDKFieldValueSemantics","kind":"symbol","abstract":[{"text":"Report of the field value semantics verification.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKFieldValueSemantics","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFieldValueSemantics"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldValueSemantics"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldValueSemantics/initWithFieldFullName:invalidSemantics:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldValueSemantics\/initWithFieldFullName:invalidSemantics:","url":"\/documentation\/scanbotsdk\/sbsdkfieldvaluesemantics\/initwithfieldfullname:invalidsemantics:","title":"initWithFieldFullName:invalidSemantics:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFieldFullName:invalidSemantics:"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFieldFullName:invalidSemantics:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldValueSemantics\/title","value":"SBSDKFieldValueSemantics"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldValueSemantics\/fragments","op":"replace","value":[{"text":"SBSDKFieldValueSemantics","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldValueSemantics\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFieldValueSemantics"}]}]}]}