{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/guidance"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration\/guidance"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration\/guidance"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReorderPagesScreenConfiguration(py)guidance","title":"guidance","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"guidance"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"guidance","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration"]]},"abstract":[{"type":"text","text":"Configuration of the static user guidance, located just below the top bar."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"guidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"abstract":[{"text":"Configuration of the hint guiding users through the scanning process.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"title":"SBSDKUI2UserGuidanceConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReorderPagesScreenConfiguration/guidance":{"title":"guidance","url":"\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration\/guidance","navigatorTitle":[{"text":"guidance","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the static user guidance, located just below the top bar."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/guidance","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"guidance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReorderPagesScreenConfiguration":{"type":"topic","title":"SBSDKUI2ReorderPagesScreenConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the screen for reordering the scanned pages."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration","navigatorTitle":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"guidance","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"guidance"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"guidance"},{"text":";","kind":"text"}]}]}},{"value":"SBSDKUI2UserGuidanceConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration~1guidance\/title","op":"replace","value":"guidance"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration~1guidance\/fragments","value":[{"kind":"identifier","text":"guidance"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/title","op":"replace","value":"SBSDKUI2ReorderPagesScreenConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}]}]}]}