{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"platforms":[],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration(py)accessibilityConfiguration","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityConfiguration"}],"title":"accessibilityConfiguration","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"accessibilityConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration"},{"text":"?","kind":"text"}]},"sections":[],"abstract":[{"type":"text","text":"A configuration with accessibility texts settings."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration\/accessibilityconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration\/accessibilityconfiguration"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration\/accessibilityConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration","text":"SBSDKUICroppingScreenAccessibilityConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2CroppingViewController instead."}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"navigatorTitle":[{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration","title":"SBSDKUICroppingScreenAccessibilityConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenTextConfiguration":{"abstract":[{"type":"text","text":"Configuration for the textual content of the page cropping screen."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration","title":"SBSDKUICroppingScreenTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenTextConfiguration/accessibilityConfiguration":{"title":"accessibilityConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityConfiguration"},{"kind":"text","text":": "},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"A configuration with accessibility texts settings.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenTextConfiguration\/accessibilityConfiguration","type":"topic","kind":"symbol","navigatorTitle":[{"text":"accessibilityConfiguration","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreentextconfiguration\/accessibilityconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"accessibilityConfiguration"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"accessibilityConfiguration","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","kind":"typeIdentifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accessibilityConfiguration"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/title","op":"replace","value":"SBSDKUICroppingScreenAccessibilityConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/title","value":"SBSDKUICroppingScreenTextConfiguration"},{"op":"replace","value":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}]},{"value":"accessibilityConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration~1accessibilityConfiguration\/title"},{"op":"replace","value":[{"text":"accessibilityConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenTextConfiguration~1accessibilityConfiguration\/fragments"}]}]}