{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)Scanbot(cpy)licenseExpirationDate","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseExpirationDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"roleHeading":"Type Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"licenseExpirationDate","kind":"identifier"}],"title":"licenseExpirationDate","modules":[{"name":"ScanbotSDK"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbot\/licenseexpirationdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/scanbot\/licenseexpirationdate"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The expiration date for license.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"licenseExpirationDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"text":"Date of license expiration.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", if there is no expiration date - for example if the license is invalid or not set."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/licenseExpirationDate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/licenseExpirationDate":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/licenseExpirationDate","navigatorTitle":[{"text":"licenseExpirationDate","kind":"identifier"}],"title":"licenseExpirationDate","url":"\/documentation\/scanbotsdk\/scanbot\/licenseexpirationdate","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseExpirationDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The expiration date for license."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Scanbot","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/scanbot","navigatorTitle":[{"text":"Scanbot","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}],"title":"Scanbot","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"licenseExpirationDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"licenseExpirationDate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" * ","kind":"text"},{"text":"licenseExpirationDate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1licenseExpirationDate\/title","value":"licenseExpirationDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1licenseExpirationDate\/fragments","value":[{"kind":"identifier","text":"licenseExpirationDate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/title","value":"Scanbot"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/fragments","value":[{"kind":"identifier","text":"Scanbot"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/navigatorTitle","value":[{"text":"Scanbot","kind":"identifier"}]}]}]}