{"kind":"symbol","abstract":[{"text":"Detects and scans credit card on the  given ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner\/scan(from:)-78jam"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/scan(from:)-78jam"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/scan(from:)-78jam"]}],"metadata":{"title":"scan(from:)","navigatorTitle":[{"kind":"identifier","text":"scanFromFrame:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanner(im)scanFromFrame:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scan","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier","text":"SBSDKBaseScannerFrame"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","text":"SBSDKCreditCardScanningResult"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(scanFromFrame:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"frame","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier","text":"SBSDKBaseScannerFrame"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult","kind":"typeIdentifier","text":"SBSDKCreditCardScanningResult"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The frame to scan from."}]}]}]},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The credit card scanning result containing the scanned credit card.","type":"text"}]}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerFrame":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerframe","title":"SBSDKBaseScannerFrame","abstract":[{"text":"A wrapper class for video frames.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerFrame"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanner":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardScanner"}],"abstract":[{"type":"text","text":"A class to scan credit cards on various image sources."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner","title":"SBSDKCreditCardScanner","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardScanner"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanner"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanner/scan(from:)-78jam":{"navigatorTitle":[{"text":"scanFromFrame:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanner\/scan(from:)-78jam","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanner\/scan(from:)-78jam","type":"topic","title":"scan(from:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scan","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","kind":"typeIdentifier","text":"SBSDKBaseScannerFrame"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","text":"SBSDKCreditCardScanningResult"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Detects and scans credit card on the  given ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardScanningResult":{"role":"symbol","navigatorTitle":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Contains the result of running the credit card scanner.","type":"text"}],"title":"SBSDKCreditCardScanningResult","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcreditcardscanningresult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"scanFromFrame:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scanFromFrame:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardScanningResult","text":"SBSDKCreditCardScanningResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardScanningResult","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"scanFromFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","kind":"typeIdentifier","text":"SBSDKBaseScannerFrame"},{"kind":"text","text":" *) "},{"text":"frame","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The frame to scan from.","type":"text"}],"type":"paragraph"}],"name":"frame"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The credit card scanning result containing the scanned credit card."}]}]}},{"op":"replace","value":"SBSDKBaseScannerFrame","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/fragments","value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"op":"replace"},{"value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/navigatorTitle","op":"replace"},{"value":"SBSDKCreditCardScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKCreditCardScanner"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCreditCardScanner"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner~1scan(from:)-78jam\/title","value":"scanFromFrame:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scanFromFrame:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanner~1scan(from:)-78jam\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/title","op":"replace","value":"SBSDKCreditCardScanningResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/fragments","value":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardScanningResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCreditCardScanningResult","kind":"identifier"}]}]}]}