{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeylength\/bits128"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeylength\/bits128"]}],"sections":[],"abstract":[{"type":"text","text":"A key length of 128 bits (16 bytes) ."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength\/bits128"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bits128"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKStorageCryptingKeyLength@SBSDKStorageCryptingKeyLengthBits128","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"symbolKind":"case","title":"SBSDKStorageCryptingKeyLength.bits128"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bits128"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyLength/bits128":{"url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeylength\/bits128","abstract":[{"type":"text","text":"A key length of 128 bits (16 bytes) ."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength\/bits128","title":"SBSDKStorageCryptingKeyLength.bits128","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bits128","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyLengthBits128","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyLength":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeylength","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyLength","title":"SBSDKStorageCryptingKeyLength","abstract":[{"type":"text","text":"The length of the encryption key."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKStorageCryptingKeyLengthBits128","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKStorageCryptingKeyLengthBits128","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength~1bits128\/title"},{"value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLengthBits128"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength~1bits128\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/title","op":"replace","value":"SBSDKStorageCryptingKeyLength"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyLength"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyLength\/navigatorTitle","op":"replace","value":[{"text":"SBSDKStorageCryptingKeyLength","kind":"identifier"}]}]}]}