{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scannedPageDidChangeData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedPage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","text":"SBSDKScannedPage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"page","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/scannedPageDidChangeData:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKScannedDocument(im)scannedPageDidChangeData:","fragments":[{"text":"- ","kind":"text"},{"text":"scannedPageDidChangeData:","kind":"identifier"}],"title":"scannedPageDidChangeData:","navigatorTitle":[{"text":"scannedPageDidChangeData:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/scannedpagedidchangedata:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedDocument"}],"title":"SBSDKScannedDocument","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","type":"topic","abstract":[{"text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedPage":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscannedpage","abstract":[{"type":"text","text":"A scanned page ("},{"type":"codeVoice","code":"SBSDKScannedPage"},{"type":"text","text":") is a representation of a scanned documents page in digital form."},{"type":"text","text":" "},{"type":"text","text":"Each page consists of an original image of the scan, various editing properties like cropping polygon, rotation and filters, some metadata properties like the document detection status and the document quality analyzer result and a number of processed images in different stages."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedPage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedPage","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKScannedPage","kind":"identifier"}],"kind":"symbol","title":"SBSDKScannedPage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument/scannedPageDidChangeData:":{"fragments":[{"text":"- ","kind":"text"},{"text":"scannedPageDidChangeData:","kind":"identifier"}],"kind":"symbol","title":"scannedPageDidChangeData:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/scannedPageDidChangeData:","type":"topic","role":"symbol","navigatorTitle":[{"text":"scannedPageDidChangeData:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument\/scannedpagedidchangedata:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title","op":"replace","value":"SBSDKScannedDocument"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","op":"replace","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKScannedDocument"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/title","op":"replace","value":"SBSDKScannedPage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKScannedPage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedPage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKScannedPage","kind":"identifier"}]}]}]}