{"metadata":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerViewController(im)initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController\/initWithCoder:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController":{"type":"topic","kind":"symbol","title":"SBSDKUIDocumentScannerViewController","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIDocumentScannerViewController"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerViewController/initWithCoder:":{"title":"initWithCoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscannerviewcontroller\/initwithcoder:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerViewController\/initWithCoder:","role":"symbol","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/title","value":"SBSDKUIDocumentScannerViewController","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUIDocumentScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}