{"metadata":{"navigatorTitle":[{"text":"SBSDKImageSourceTypePlatformImage","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"SBSDKImageSourceType.platformImage","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageSourceType@SBSDKImageSourceTypePlatformImage","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"platformImage","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"ImageRef was created from a platform image, e.g. Bitmap on Android, UIImage on iOS."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSourceType\/platformImage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSourceType"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesourcetype\/platformimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesourcetype\/platformimage"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"platformImage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSourceType/platformImage":{"title":"SBSDKImageSourceType.platformImage","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"platformImage","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesourcetype\/platformimage","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSourceTypePlatformImage"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSourceType\/platformImage","kind":"symbol","abstract":[{"type":"text","text":"ImageRef was created from a platform image, e.g. Bitmap on Android, UIImage on iOS."}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageSourceType":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagesourcetype","type":"topic","title":"SBSDKImageSourceType","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageSourceType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"abstract":[{"text":"The type of source which originated the underlying image.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKImageSourceType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SBSDKImageSourceTypePlatformImage","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageSourceTypePlatformImage"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKImageSourceTypePlatformImage","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKImageSourceTypePlatformImage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType~1platformImage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType~1platformImage\/fragments","value":[{"text":"SBSDKImageSourceTypePlatformImage","kind":"identifier"}]},{"value":"SBSDKImageSourceType","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageSourceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}