{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/hash","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/hash"]}],"sections":[],"kind":"symbol","metadata":{"title":"hash","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVINScannerConfiguration(py)hash","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"hash"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVINScannerConfiguration"}],"type":"topic","kind":"symbol","abstract":[{"text":"Configuration for the VIN scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"title":"SBSDKVINScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVINScannerConfiguration/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVINScannerConfiguration\/hash","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkvinscannerconfiguration\/hash","kind":"symbol","title":"hash","fragments":[{"kind":"identifier","text":"hash"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/title","value":"SBSDKVINScannerConfiguration","op":"replace"},{"value":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVINScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKVINScannerConfiguration","kind":"identifier"}]}]}]}