{"kind":"symbol","metadata":{"symbolKind":"init","title":"init(sheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:)","navigatorTitle":[{"kind":"identifier","text":"initWithSheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sheetColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dividerColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"modalOverlayColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updateButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"text":"cancelButton","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearTextButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2IconStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle"},{"kind":"text","text":")"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog(im)initWithSheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2manualcounteditdialog\/init(sheetcolor:dividercolor:modaloverlaycolor:title:info:updatebutton:cancelbutton:cleartextbutton:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2manualcounteditdialog\/init(sheetcolor:dividercolor:modaloverlaycolor:title:info:updatebutton:cancelbutton:cleartextbutton:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog\/init(sheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"sheetColor","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false), "},{"kind":"externalParam","text":"dividerColor"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), "},{"text":"modalOverlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorModalOverlay\", isArgb: false), ","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2StyledText(text: \"Update count\",\n                                                               color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                    isArgb: false)), "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"Adjust the number of items you scanned.\",\n                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                   isArgb: false)), ","kind":"text"},{"kind":"externalParam","text":"updateButton"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                        text: \"Update\",\n                                                                                        background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                            fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                            strokeWidth: 1.0),\n                                                                                        foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                 isArgb: false),\n                                                                                                                            useShadow: false)), ","kind":"text"},{"kind":"externalParam","text":"cancelButton"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                        text: \"Cancel\",\n                                                                                        background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                            fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                            strokeWidth: 1.0),\n                                                                                        foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                            color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                 isArgb: false),\n                                                                                                                            useShadow: false)), "},{"text":"clearTextButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2IconStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle"},{"text":" = SBSDKUI2IconStyle(visible: true,\n                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                            isArgb: false)))","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2StyledText"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Button configuration."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","title":"SBSDKUI2ButtonConfiguration","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"url":"\/documentation\/scanbotsdk\/sbsdkui2color","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","title":"SBSDKUI2Color"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ManualCountEditDialog":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","title":"SBSDKUI2ManualCountEditDialog","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2manualcounteditdialog","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"kind":"symbol","abstract":[{"text":"Configuration of the dialog to manually edit the barcode count.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ManualCountEditDialog/init(sheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog\/init(sheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sheetColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"dividerColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"modalOverlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"updateButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clearTextButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2IconStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle"},{"kind":"text","text":")"}],"title":"init(sheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:)","type":"topic","navigatorTitle":[{"text":"initWithSheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2manualcounteditdialog\/init(sheetcolor:dividercolor:modaloverlaycolor:title:info:updatebutton:cancelbutton:cleartextbutton:)","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconStyle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2iconstyle","title":"SBSDKUI2IconStyle","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"abstract":[{"text":"Configuration of the icon appearance.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2IconStyle","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithSheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSheetColor:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"sheetColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dividerColor:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dividerColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalOverlayColor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"modalOverlayColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"title:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"info"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateButton:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"updateButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButton:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"text":"cancelButton","kind":"internalParam"},{"kind":"text","text":" "},{"text":"clearTextButton:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","kind":"typeIdentifier","text":"SBSDKUI2IconStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"clearTextButton"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration","op":"replace"},{"value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments","op":"replace"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"value":"SBSDKUI2ManualCountEditDialog","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}]},{"op":"replace","value":"initWithSheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog~1init(sheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog~1init(sheetColor:dividerColor:modalOverlayColor:title:info:updateButton:cancelButton:clearTextButton:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/title","value":"SBSDKUI2IconStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}]}]}]}