{"abstract":[{"type":"text","text":"Designated initializer."}],"metadata":{"platforms":[{"deprecated":false,"beta":false,"introducedAt":"14.0","unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"introducedAt":"14.0","unavailable":false,"name":"iPadOS"},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"beta":false}],"role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputKeyMaterial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"salt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHKDFKeyGenerator(im)initWithInputKeyMaterial:info:salt:","navigatorTitle":[{"kind":"identifier","text":"initWithInputKeyMaterial:info:salt:"}],"modules":[{"name":"ScanbotSDK"}],"title":"init(inputKeyMaterial:info:salt:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"inputKeyMaterial","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"salt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The input key material used to create the pseudo random key used during the extraction phase."}],"type":"paragraph"}],"name":"inputKeyMaterial"},{"content":[{"inlineContent":[{"text":"The info data block that may be used during the expansion phase. Optional. Default is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"info"},{"content":[{"inlineContent":[{"type":"text","text":"The salt data block that may be used during  the extraction phase. Optional. Default is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"salt"}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator\/init(inputkeymaterial:info:salt:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator\/init(inputkeymaterial:info:salt:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator\/init(inputKeyMaterial:info:salt:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHKDFKeyGenerator":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator","abstract":[{"text":"A key generator that uses the HMAC based HKDF algorithm to generate a new encryption key. SHA512 is used as the hash function.","type":"text"},{"text":" ","type":"text"},{"text":"The key generation consists of two phases: extraction and expansion.","type":"text"},{"text":" ","type":"text"},{"text":"During the extraction a pseudo random key is generated from the input key material and an optional salt.","type":"text"},{"text":" ","type":"text"},{"text":"The expansion phase uses the pseudo random key and the info data block to derive the final key.","type":"text"}],"type":"topic","title":"SBSDKHKDFKeyGenerator","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHKDFKeyGenerator/init(inputKeyMaterial:info:salt:)":{"url":"\/documentation\/scanbotsdk\/sbsdkhkdfkeygenerator\/init(inputkeymaterial:info:salt:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHKDFKeyGenerator\/init(inputKeyMaterial:info:salt:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inputKeyMaterial","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"salt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Designated initializer.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithInputKeyMaterial:info:salt:"}],"title":"init(inputKeyMaterial:info:salt:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithInputKeyMaterial:info:salt:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithInputKeyMaterial:info:salt:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithInputKeyMaterial:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"inputKeyMaterial","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"info:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"salt:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"salt","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"inputKeyMaterial","content":[{"inlineContent":[{"text":"The input key material used to create the pseudo random key used during the extraction phase.","type":"text"}],"type":"paragraph"}]},{"name":"info","content":[{"inlineContent":[{"type":"text","text":"The info data block that may be used during the expansion phase. Optional. Default is "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"salt","content":[{"type":"paragraph","inlineContent":[{"text":"The salt data block that may be used during  the extraction phase. Optional. Default is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKHKDFKeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/fragments"},{"op":"replace","value":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator\/navigatorTitle"},{"op":"replace","value":"initWithInputKeyMaterial:info:salt:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator~1init(inputKeyMaterial:info:salt:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithInputKeyMaterial:info:salt:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHKDFKeyGenerator~1init(inputKeyMaterial:info:salt:)\/fragments"}]}]}