{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/textLineRecognition"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textLineRecognition","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/textlinerecognition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/textlinerecognition"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureTextLineRecognition"}],"title":"SBSDKFeature.textLineRecognition","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"textLineRecognition"}],"symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKFeature@SBSDKFeatureTextLineRecognition","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","roleHeading":"Case"},"kind":"symbol","abstract":[{"type":"text","text":"Text line recognition is enabled in the licence."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature/textLineRecognition":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature\/textlinerecognition","abstract":[{"type":"text","text":"Text line recognition is enabled in the licence."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature\/textLineRecognition","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureTextLineRecognition"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"textLineRecognition"}],"type":"topic","title":"SBSDKFeature.textLineRecognition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKFeature":{"navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKFeature","role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkfeature","title":"SBSDKFeature","abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKFeatureTextLineRecognition","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFeatureTextLineRecognition"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKFeatureTextLineRecognition","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1textLineRecognition\/title","value":"SBSDKFeatureTextLineRecognition","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature~1textLineRecognition\/fragments","value":[{"text":"SBSDKFeatureTextLineRecognition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/title","value":"SBSDKFeature","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/fragments","value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKFeature\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}