{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter\/beginStreamingEncryptWithContext:error:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"beginStreamingEncryptWithContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter\/beginstreamingencryptwithcontext:error:"]}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"beginStreamingEncryptWithContext:error:"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"beginStreamingEncryptWithContext:error:"}],"title":"beginStreamingEncryptWithContext:error:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAESGCMEncrypter(im)beginStreamingEncryptWithContext:error:"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESGCMEncrypter/beginStreamingEncryptWithContext:error:":{"navigatorTitle":[{"text":"beginStreamingEncryptWithContext:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"beginStreamingEncryptWithContext:error:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter\/beginstreamingencryptwithcontext:error:","kind":"symbol","type":"topic","title":"beginStreamingEncryptWithContext:error:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter\/beginStreamingEncryptWithContext:error:","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESGCMEncrypter":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter","title":"SBSDKAESGCMEncrypter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"kind":"symbol","abstract":[{"type":"text","text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider."},{"type":"text","text":" "},{"type":"text","text":"Supports encryption and decryption of single data blocks as well as streaming data."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/title","value":"SBSDKAESGCMEncrypter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/fragments","value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/navigatorTitle"}]}]}