{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"provideContextFor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter\/provideContextFor:","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAESGCMEncrypter(im)provideContextFor:","navigatorTitle":[{"kind":"identifier","text":"provideContextFor:"}],"title":"provideContextFor:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"provideContextFor:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter\/providecontextfor:"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESGCMEncrypter":{"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKAESGCMEncrypter","abstract":[{"type":"text","text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider."},{"type":"text","text":" "},{"type":"text","text":"Supports encryption and decryption of single data blocks as well as streaming data."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter","navigatorTitle":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESGCMEncrypter/provideContextFor:":{"navigatorTitle":[{"text":"provideContextFor:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter\/provideContextFor:","title":"provideContextFor:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"provideContextFor:","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter\/providecontextfor:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKAESGCMEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/title","op":"replace"},{"value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/navigatorTitle","op":"replace"}]}]}