{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBitmapMemoryConsumption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"bitmapMemoryConsumption"},{"kind":"text","text":" "},{"kind":"identifier","text":"hibernationMemoryConsumption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hibernationMemoryConsumption"},{"kind":"text","text":";"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimageprofile\/initwithbitmapmemoryconsumption:hibernationmemoryconsumption:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageProfile"]]},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKImageProfile(im)initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","navigatorTitle":[{"kind":"identifier","text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageProfile\/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageProfile":{"title":"SBSDKImageProfile","abstract":[{"type":"text","text":"ImageRef profile part specific to image information."}],"type":"topic","navigatorTitle":[{"text":"SBSDKImageProfile","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageProfile","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageprofile","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageProfile","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageProfile/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageprofile\/initwithbitmapmemoryconsumption:hibernationmemoryconsumption:","abstract":[],"navigatorTitle":[{"text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageProfile\/initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","fragments":[{"kind":"text","text":"- "},{"text":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:","kind":"identifier"}],"title":"initWithBitmapMemoryConsumption:hibernationMemoryConsumption:"}},"variantOverrides":[{"patch":[{"value":"SBSDKImageProfile","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageProfile\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageProfile"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageProfile\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageProfile\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}