{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorthrower\/throwerror(code:description:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorthrower\/throwerror(code:description:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Throws an ","type":"text"},{"type":"codeVoice","code":"SBSDKError"},{"text":" based on a given error code and description.","type":"text"},{"text":" ","type":"text"},{"text":"This is used to propagate errors from the underlying C++ core to Swift\/Objective-C.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorThrower\/throwError(code:description:)"},"sections":[],"metadata":{"symbolKind":"method","title":"throwError(code:description:)","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"throwErrorWithCode:description:error:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throwError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKErrorThrower(cm)throwErrorWithCode:description:error:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorThrower"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"throwError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"code","content":[{"inlineContent":[{"type":"text","text":"The integer error code corresponding to an "},{"type":"codeVoice","code":"SBSDKError"},{"type":"text","text":" case."}],"type":"paragraph"}]},{"name":"description","content":[{"type":"paragraph","inlineContent":[{"text":"A string describing the error.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"code":"SBSDKError","type":"codeVoice"},{"text":" corresponding to the provided code.","type":"text"}]}],"type":"aside","name":"Throws","style":"note"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorThrower":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorThrower"}],"title":"SBSDKErrorThrower","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorThrower","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorthrower","abstract":[{"text":"A helper class for Objective-C to throw ","type":"text"},{"code":"SBSDKError","type":"codeVoice"},{"text":"s.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorThrower"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKErrorThrower/throwError(code:description:)":{"title":"throwError(code:description:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throwError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Throws an "},{"code":"SBSDKError","type":"codeVoice"},{"type":"text","text":" based on a given error code and description."},{"type":"text","text":" "},{"type":"text","text":"This is used to propagate errors from the underlying C++ core to Swift\/Objective-C."}],"navigatorTitle":[{"kind":"identifier","text":"throwErrorWithCode:description:error:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkerrorthrower\/throwerror(code:description:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKErrorThrower\/throwError(code:description:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"throwErrorWithCode:description:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"throwErrorWithCode:description:error:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"throwErrorWithCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"code"},{"kind":"text","text":" "},{"kind":"identifier","text":"description:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"description","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"code","content":[{"type":"paragraph","inlineContent":[{"text":"The integer error code corresponding to an ","type":"text"},{"code":"SBSDKError","type":"codeVoice"},{"text":" case.","type":"text"}]}]},{"name":"description","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string describing the error."}]}]},{"name":"error","content":[{"inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"code":"YES","type":"codeVoice"},{"type":"text","text":" if the method succeeded, otherwise "},{"code":"NO","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"},"op":"add"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorThrower\/title","value":"SBSDKErrorThrower","op":"replace"},{"op":"replace","value":[{"text":"SBSDKErrorThrower","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorThrower\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorThrower"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorThrower\/navigatorTitle"},{"op":"replace","value":"throwErrorWithCode:description:error:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorThrower~1throwError(code:description:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"throwErrorWithCode:description:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKErrorThrower~1throwError(code:description:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}