{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"]]},"abstract":[{"text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"parentView"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","text":"SBSDKMRZScannerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","text":"SBSDKMRZScannerViewControllerDelegate"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"name":"parentViewController","content":[{"type":"paragraph","inlineContent":[{"text":"The view controller the newly created instance is embedded into.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The view the newly created instance is embedded into.","type":"text"}],"type":"paragraph"}],"name":"parentView"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The recognizers configuration."}]}],"name":"configuration"},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate of the receiver. if ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" and the "},{"code":"parentViewController","type":"codeVoice"},{"text":" conforms to the","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","type":"reference","isActive":true},{"text":" protocol, the ","type":"text"},{"type":"codeVoice","code":"parentViewController"},{"text":" is automatically set as delegate.","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)"]}],"metadata":{"symbolKind":"init","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController(im)initWithParentViewController:parentView:configuration:delegate:","modules":[{"name":"ScanbotSDK"}],"title":"init(parentViewController:parentView:configuration:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"parentViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"text":"parentView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","text":"SBSDKMRZScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMRZScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithParentViewController:parentView:configuration:delegate:"}]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate":{"type":"topic","title":"SBSDKMRZScannerViewControllerDelegate","abstract":[{"text":"The delegation protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","type":"reference","isActive":true},{"type":"text","text":" class."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController/init(parentViewController:parentView:configuration:delegate:)":{"navigatorTitle":[{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController\/init(parentViewController:parentView:configuration:delegate:)","title":"init(parentViewController:parentView:configuration:delegate:)","abstract":[{"type":"text","text":"Installs the receiver as child view controller onto the parent view controllers view using its entire bounds area."}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller\/init(parentviewcontroller:parentview:configuration:delegate:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"parentViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"parentView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKMRZScannerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMRZScannerViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate"},{"kind":"text","text":"?)"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"title":"SBSDKMRZScannerViewController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan machine-readable zones."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration","navigatorTitle":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for MRZ scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerConfiguration"}],"title":"SBSDKMRZScannerConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerconfiguration","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithParentViewController:parentView:configuration:delegate:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParentViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":" *) "},{"text":"parentViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"parentView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"text":"parentView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"configuration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerConfiguration","kind":"typeIdentifier","text":"SBSDKMRZScannerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"text":"delegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKMRZScannerViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"parentViewController","content":[{"inlineContent":[{"text":"The view controller the newly created instance is embedded into.","type":"text"}],"type":"paragraph"}]},{"name":"parentView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view the newly created instance is embedded into."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The recognizers configuration.","type":"text"}]}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate of the receiver. if "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" and the "},{"code":"parentViewController","type":"codeVoice"},{"text":" conforms to the","type":"text"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","isActive":true},{"text":" protocol, the ","type":"text"},{"type":"codeVoice","code":"parentViewController"},{"type":"text","text":" is automatically set as delegate."}]}],"name":"delegate"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKMRZScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/title","op":"replace","value":"initWithParentViewController:parentView:configuration:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController~1init(parentViewController:parentView:configuration:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithParentViewController:parentView:configuration:delegate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","value":"SBSDKMRZScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/title","value":"SBSDKMRZScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKMRZScannerConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMRZScannerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}