{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/invalid","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Semantically invalid value. For example, the date of birth is in the future, the date of expiry is in the past."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKValueSemantics@SBSDKValueSemanticsInvalid","title":"SBSDKValueSemantics.invalid","navigatorTitle":[{"text":"SBSDKValueSemanticsInvalid","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/invalid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/invalid"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics/invalid":{"navigatorTitle":[{"text":"SBSDKValueSemanticsInvalid","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics\/invalid","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics\/invalid","abstract":[{"text":"Semantically invalid value. For example, the date of birth is in the future, the date of expiry is in the past.","type":"text"}],"role":"symbol","title":"SBSDKValueSemantics.invalid","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKValueSemantics":{"abstract":[{"text":"The result of the value semantics verification.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkvaluesemantics","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKValueSemantics","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKValueSemantics"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKValueSemantics"}],"title":"SBSDKValueSemantics"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKValueSemanticsInvalid","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKValueSemanticsInvalid","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKValueSemanticsInvalid"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKValueSemanticsInvalid","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1invalid\/title"},{"value":[{"kind":"identifier","text":"SBSDKValueSemanticsInvalid"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics~1invalid\/fragments"},{"value":"SBSDKValueSemantics","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/title"},{"value":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/fragments"},{"value":[{"text":"SBSDKValueSemantics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKValueSemantics\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}