{"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKDocumentDetectionStatus.errorPartiallyVisibleTooClose","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentDetectionStatus@SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorPartiallyVisibleTooClose"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/errorPartiallyVisibleTooClose","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"A document was detected, but not all of its corners are visible and the document is too close to the camera."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorPartiallyVisibleTooClose","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/errorpartiallyvisibletooclose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/errorpartiallyvisibletooclose"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus/errorPartiallyVisibleTooClose":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorPartiallyVisibleTooClose"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/errorPartiallyVisibleTooClose","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/errorpartiallyvisibletooclose","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose"}],"title":"SBSDKDocumentDetectionStatus.errorPartiallyVisibleTooClose","abstract":[{"text":"A document was detected, but not all of its corners are visible and the document is too close to the camera.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus","abstract":[{"type":"text","text":"Status of the document detection."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus","type":"topic","kind":"symbol","title":"SBSDKDocumentDetectionStatus"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1errorPartiallyVisibleTooClose\/title"},{"value":[{"text":"SBSDKDocumentDetectionStatusErrorPartiallyVisibleTooClose","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1errorPartiallyVisibleTooClose\/fragments"},{"value":"SBSDKDocumentDetectionStatus","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentDetectionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus\/navigatorTitle","op":"replace"}]}]}