{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentMedicalCertificate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmedicalcertificate\/incapableofworkuntil"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmedicalcertificate\/incapableofworkuntil"]}],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentMedicalCertificate(py)incapableOfWorkUntil","navigatorTitle":[{"kind":"identifier","text":"incapableOfWorkUntil"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incapableOfWorkUntil"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"incapableOfWorkUntil","roleHeading":"Instance Property","role":"symbol"},"abstract":[{"type":"text","text":"Incapable Of Work Until. The format is ISO8601 with delimiters."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"incapableOfWorkUntil","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentMedicalCertificate\/incapableOfWorkUntil","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentMedicalCertificate/incapableOfWorkUntil":{"kind":"symbol","abstract":[{"text":"Incapable Of Work Until. The format is ISO8601 with delimiters.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incapableOfWorkUntil"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"incapableOfWorkUntil"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmedicalcertificate\/incapableofworkuntil","type":"topic","title":"incapableOfWorkUntil","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentMedicalCertificate\/incapableOfWorkUntil"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentMedicalCertificate":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentMedicalCertificate","kind":"identifier"}],"abstract":[{"text":"Medical Certificate.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmedicalcertificate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentMedicalCertificate","kind":"symbol","title":"SBSDKBarcodeDocumentMedicalCertificate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentMedicalCertificate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"abstract":[{"type":"text","text":"A generic document field."}],"title":"SBSDKGenericDocumentField","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"incapableOfWorkUntil","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"incapableOfWorkUntil","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":" * "},{"text":"incapableOfWorkUntil","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"incapableOfWorkUntil","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentMedicalCertificate~1incapableOfWorkUntil\/title"},{"value":[{"text":"incapableOfWorkUntil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentMedicalCertificate~1incapableOfWorkUntil\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentMedicalCertificate\/title","op":"replace","value":"SBSDKBarcodeDocumentMedicalCertificate"},{"value":[{"text":"SBSDKBarcodeDocumentMedicalCertificate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentMedicalCertificate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentMedicalCertificate\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentMedicalCertificate","kind":"identifier"}]},{"op":"replace","value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}]},{"value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","op":"replace"}]}]}