{"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTop:left:bottom:right:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTop:left:bottom:right:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2EdgeInsets(im)initWithTop:left:bottom:right:","role":"symbol","title":"initWithTop:left:bottom:right:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2EdgeInsets"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2edgeinsets\/initwithtop:left:bottom:right:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2EdgeInsets\/initWithTop:left:bottom:right:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithTop:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"top","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"left:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"left","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bottom:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"bottom","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"right:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"right","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2EdgeInsets":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}],"type":"topic","title":"SBSDKUI2EdgeInsets","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2EdgeInsets","abstract":[{"type":"text","text":"Represents the insets of a rectangle."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2edgeinsets","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2EdgeInsets"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2EdgeInsets/initWithTop:left:bottom:right:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2EdgeInsets\/initWithTop:left:bottom:right:","abstract":[],"title":"initWithTop:left:bottom:right:","url":"\/documentation\/scanbotsdk\/sbsdkui2edgeinsets\/initwithtop:left:bottom:right:","navigatorTitle":[{"text":"initWithTop:left:bottom:right:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTop:left:bottom:right:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2EdgeInsets","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2EdgeInsets\/title"},{"op":"replace","value":[{"text":"SBSDKUI2EdgeInsets","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2EdgeInsets\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2EdgeInsets","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2EdgeInsets\/navigatorTitle"}]}]}