{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureVersion","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"No license active. The set license does not cover the current SDK version.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureVersion"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/failureversion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/failureversion"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"SBSDKLicenseStatus.failureVersion","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"SBSDKLicenseStatusFailureVersion","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureVersion","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusFailureVersion","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"title":"SBSDKLicenseStatus","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","role":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"abstract":[{"text":"Status of the license plate scanner.","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureVersion":{"kind":"symbol","abstract":[{"text":"No license active. The set license does not cover the current SDK version.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failureversion","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureVersion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureVersion"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureVersion"}],"title":"SBSDKLicenseStatus.failureVersion","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKLicenseStatusFailureVersion","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKLicenseStatusFailureVersion","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKLicenseStatusFailureVersion","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKLicenseStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/navigatorTitle"},{"op":"replace","value":"SBSDKLicenseStatusFailureVersion","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureVersion\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureVersion"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureVersion\/fragments"}]}]}