{"sections":[],"metadata":{"title":"SBSDKOCRResultBlockType.line","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRResultBlockTypeLine"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"line","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKOCRResultBlockType@SBSDKOCRResultBlockTypeLine","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"line","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/line"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/line"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/line","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The result block represents a text line.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"title":"SBSDKOCRResultBlockType","url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype","abstract":[{"type":"text","text":"The block type of an OCR fragment."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRResultBlockType"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRResultBlockType/line":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKOCRResultBlockTypeLine"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrresultblocktype\/line","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRResultBlockType\/line","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"line","kind":"identifier"}],"type":"topic","title":"SBSDKOCRResultBlockType.line","abstract":[{"type":"text","text":"The result block represents a text line."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKOCRResultBlockTypeLine"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKOCRResultBlockTypeLine"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKOCRResultBlockTypeLine"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/title","value":"SBSDKOCRResultBlockType"},{"value":[{"text":"SBSDKOCRResultBlockType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOCRResultBlockType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1line\/title","value":"SBSDKOCRResultBlockTypeLine"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRResultBlockType~1line\/fragments","value":[{"text":"SBSDKOCRResultBlockTypeLine","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}