{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is “Close screen without granting permission”","type":"text"}]}]}],"abstract":[{"type":"text","text":"The accessibility hint for the ‘close’ button of the camera permission dialog."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/accessibilitydescriptioncamerapermissionclosebutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/accessibilitydescriptioncamerapermissionclosebutton"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton"},"metadata":{"roleHeading":"Instance Property","title":"accessibilityDescriptionCameraPermissionCloseButton","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenTextLocalization(py)accessibilityDescriptionCameraPermissionCloseButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization/accessibilityDescriptionCameraPermissionCloseButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/accessibilitydescriptioncamerapermissionclosebutton","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The accessibility hint for the ‘close’ button of the camera permission dialog."}],"title":"accessibilityDescriptionCameraPermissionCloseButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization":{"type":"topic","title":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the all strings for credit card scanner screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization","navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"accessibilityDescriptionCameraPermissionCloseButton"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/title","op":"replace","value":"accessibilityDescriptionCameraPermissionCloseButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/title","op":"replace","value":"SBSDKUI2CreditCardScannerScreenTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/fragments","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}]}]}]}