{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization\/creditCardUserGuidanceScanningProgress","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"creditCardUserGuidanceScanningProgress","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"creditCardUserGuidanceScanningProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardUserGuidanceScanningProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScannerScreenTextLocalization(py)creditCardUserGuidanceScanningProgress","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/creditcarduserguidancescanningprogress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/creditcarduserguidancescanningprogress"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardUserGuidanceScanningProgress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"inlineContent":[{"text":"Default is “Scanning the credit card…”","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"The user guidance text displayed when a card presence was detected.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization/creditCardUserGuidanceScanningProgress":{"title":"creditCardUserGuidanceScanningProgress","abstract":[{"type":"text","text":"The user guidance text displayed when a card presence was detected."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"creditCardUserGuidanceScanningProgress","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization\/creditCardUserGuidanceScanningProgress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardUserGuidanceScanningProgress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization\/creditcarduserguidancescanningprogress"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScannerScreenTextLocalization":{"kind":"symbol","type":"topic","abstract":[{"text":"Configuration of the all strings for credit card scanner screen.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"title":"SBSDKUI2CreditCardScannerScreenTextLocalization","navigatorTitle":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscannerscreentextlocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScannerScreenTextLocalization","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"creditCardUserGuidanceScanningProgress","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"creditCardUserGuidanceScanningProgress","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"creditCardUserGuidanceScanningProgress"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"creditCardUserGuidanceScanningProgress","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization~1creditCardUserGuidanceScanningProgress\/title","op":"replace"},{"value":[{"kind":"identifier","text":"creditCardUserGuidanceScanningProgress"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization~1creditCardUserGuidanceScanningProgress\/fragments","op":"replace"},{"value":"SBSDKUI2CreditCardScannerScreenTextLocalization","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScannerScreenTextLocalization"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CreditCardScannerScreenTextLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScannerScreenTextLocalization\/navigatorTitle","op":"replace"}]}]}