{"abstract":[{"type":"text","text":"Only EAN and UPC codes with extensions are returned."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"onlyWithExtensions","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter\/onlyWithExtensions","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodesExtensionFilter@SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","title":"SBSDKUI2BarcodesExtensionFilter.onlyWithExtensions","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlyWithExtensions"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodesextensionfilter\/onlywithextensions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodesextensionfilter\/onlywithextensions"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodesExtensionFilter":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodesextensionfilter","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"kind":"symbol","title":"SBSDKUI2BarcodesExtensionFilter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodesExtensionFilter/onlyWithExtensions":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodesextensionfilter\/onlywithextensions","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onlyWithExtensions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Only EAN and UPC codes with extensions are returned."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodesExtensionFilter\/onlyWithExtensions","title":"SBSDKUI2BarcodesExtensionFilter.onlyWithExtensions","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2BarcodesExtensionFilter","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter\/fragments","op":"replace"},{"value":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter~1onlyWithExtensions\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilterOnlyWithExtensions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodesExtensionFilter~1onlyWithExtensions\/fragments","op":"replace"}]}]}