{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset5"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset5"]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKBinarizationFilterPresetPreset5","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarizationFilterPreset@SBSDKBinarizationFilterPresetPreset5","title":"SBSDKBinarizationFilterPreset.preset5","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preset5","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"abstract":[{"text":"Performs well even if there are shadows.","type":"text"},{"text":" ","type":"text"},{"text":"The preset is an upgrade to PRESET_4 that adds special treatment for high contrast objects such as barcodes.","type":"text"},{"text":" ","type":"text"},{"text":"Binarized barcodes typically remain readable.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preset5"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset\/preset5","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset/preset5":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset\/preset5","abstract":[{"type":"text","text":"Performs well even if there are shadows."},{"type":"text","text":" "},{"type":"text","text":"The preset is an upgrade to PRESET_4 that adds special treatment for high contrast objects such as barcodes."},{"type":"text","text":" "},{"type":"text","text":"Binarized barcodes typically remain readable."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset5"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset\/preset5","title":"SBSDKBinarizationFilterPreset.preset5","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preset5"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset":{"role":"symbol","abstract":[{"type":"text","text":"Preset of parameters for custom binarization filter."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset","title":"SBSDKBinarizationFilterPreset"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKBinarizationFilterPresetPreset5","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset5"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKBinarizationFilterPresetPreset5","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset~1preset5\/title","value":"SBSDKBinarizationFilterPresetPreset5","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset~1preset5\/fragments","value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPresetPreset5"}]},{"value":"SBSDKBinarizationFilterPreset","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/title"},{"value":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}