{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/close()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/close()"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField(im)close","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"close()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"close"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"close","kind":"identifier"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/close()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"close","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/close()":{"navigatorTitle":[{"text":"close","kind":"identifier"}],"type":"topic","title":"close()","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/close()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"close","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/close()","abstract":[],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"title":"SBSDKGenericDocumentField","abstract":[{"text":"Generic document field.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"close","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"close","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"close","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField~1close()\/title","value":"close"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField~1close()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"close","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}]}]}]}