{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"]]},"abstract":[{"text":"Crop of the field.","type":"text"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"image","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField(py)image","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/image","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRef"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","title":"SBSDKImageRef","navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref","abstract":[{"type":"text","text":"Image ref class."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"title":"SBSDKGenericDocumentField","abstract":[{"text":"Generic document field.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField/image":{"navigatorTitle":[{"text":"image","kind":"identifier"}],"type":"topic","title":"image","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield\/image","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField\/image","abstract":[{"type":"text","text":"Crop of the field."}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"image","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"image","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef","text":"SBSDKImageRef","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"image"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title","value":"SBSDKImageRef","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments","value":[{"text":"SBSDKImageRef","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField~1image\/title","value":"image","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField~1image\/fragments","value":[{"text":"image","kind":"identifier"}],"op":"replace"}]}]}