{"metadata":{"title":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode(im)initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCountingRepeatDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"countingRepeatDelay","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowEmptySubmission:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowEmptySubmission"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","text":"SBSDKUI2MultipleBarcodesScanningMode"},{"kind":"text","text":") "},{"text":"mode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheet:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sheet"},{"text":" *) ","kind":"text"},{"text":"sheet","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheetContent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2SheetContent"},{"text":" *) ","kind":"text"},{"text":"sheetContent","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountEditDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ManualCountEditDialog"},{"text":" *) ","kind":"text"},{"text":"manualCountEditDialog","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeInfoMapping:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"},{"text":" *) ","kind":"text"},{"text":"barcodeInfoMapping","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"arOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration"},{"text":" *) ","kind":"text"},{"text":"arOverlay","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/initwithcountingrepeatdelay:allowemptysubmission:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sheet":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Sheet","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheet","title":"SBSDKUI2Sheet","type":"topic","navigatorTitle":[{"text":"SBSDKUI2Sheet","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sheet"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleBarcodesScanningMode":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the mode used for scanning multiple barcodes."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleBarcodesScanningMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"type":"topic","title":"SBSDKUI2MultipleBarcodesScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplebarcodesscanningmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode/initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:":{"type":"topic","kind":"symbol","title":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode\/initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","navigatorTitle":[{"kind":"identifier","text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode\/initwithcountingrepeatdelay:allowemptysubmission:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:","role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the mode for scanning multiple barcodes."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode","url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode","title":"SBSDKUI2MultipleScanningMode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ManualCountEditDialog":{"kind":"symbol","abstract":[{"text":"Configuration of the dialog to manually edit the barcode count.","type":"text"}],"title":"SBSDKUI2ManualCountEditDialog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ManualCountEditDialog","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2manualcounteditdialog"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeInfoMapping":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeinfomapping","title":"SBSDKUI2BarcodeInfoMapping","abstract":[{"text":"Configuration of the barcode data mapping.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeInfoMapping","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"title":"SBSDKUI2ArOverlayGeneralConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetContent":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetcontent","abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetContent","title":"SBSDKUI2SheetContent","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/title","value":"SBSDKUI2Sheet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/fragments","value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sheet\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title","value":"SBSDKUI2MultipleBarcodesScanningMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleBarcodesScanningMode\/navigatorTitle","value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/title","op":"replace","value":"SBSDKUI2MultipleScanningMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/title","op":"replace","value":"SBSDKUI2ManualCountEditDialog"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/fragments","op":"replace","value":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ManualCountEditDialog\/navigatorTitle"},{"value":"SBSDKUI2BarcodeInfoMapping","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeInfoMapping\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title","value":"SBSDKUI2ArOverlayGeneralConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/title","value":"SBSDKUI2SheetContent","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/fragments","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetContent\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}