{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/cancelAlertDialog","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration of the alert dialog displayed when the ‘cancel’ button is pressed."}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"cancelAlertDialog","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(py)cancelAlertDialog","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelAlertDialog","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"cancelAlertDialog","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelAlertDialog"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/cancelalertdialog"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/cancelalertdialog"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration/cancelAlertDialog":{"title":"cancelAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/cancelAlertDialog","abstract":[{"text":"Configuration of the alert dialog displayed when the ‘cancel’ button is pressed.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/cancelalertdialog","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelAlertDialog"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelAlertDialog"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanbotAlertDialog":{"title":"SBSDKUI2ScanbotAlertDialog","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2scanbotalertdialog","navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"abstract":[{"type":"text","text":"Configuration of the the standard alert dialog."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration":{"type":"topic","kind":"symbol","title":"SBSDKUI2CameraScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the screen for scanning the pages with the camera."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cancelAlertDialog"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cancelAlertDialog"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":" * ","kind":"text"},{"text":"cancelAlertDialog","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1cancelAlertDialog\/title","value":"cancelAlertDialog","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"cancelAlertDialog"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1cancelAlertDialog\/fragments"},{"value":"SBSDKUI2ScanbotAlertDialog","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/title"},{"value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/title","value":"SBSDKUI2CameraScreenConfiguration","op":"replace"},{"value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}