{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/init(acknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"acknowledgement","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2AcknowledgementScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration"},{"kind":"text","text":" = SBSDKUI2AcknowledgementScreenConfiguration(), "},{"kind":"externalParam","text":"introduction"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration","text":"SBSDKUI2IntroductionScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroductionScreenConfiguration"},{"kind":"text","text":" = SBSDKUI2IntroductionScreenConfiguration(), "},{"text":"scanAssistanceOverlay","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay","text":"SBSDKUI2ScanAssistanceOverlay","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay"},{"text":" = SBSDKUI2ScanAssistanceOverlay(), ","kind":"text"},{"kind":"externalParam","text":"cameraPermission"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier"},{"text":" = SBSDKUI2CameraPermissionScreen(statusBarMode: SBSDKUI2StatusBarMode.dark,\n                                           background: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                     isArgb: false),\n                                           iconBackground: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                         isArgb: false),\n                                           icon: SBSDKUI2IconStyle(visible: true,\n                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                        isArgb: false)),\n                                           enableCameraButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                           text: \"?cameraPermissionEnableCameraButton\",\n                                                                                           accessibilityDescription: \"?accessibilityDescriptionCameraPermissionEnableCameraButton\",\n                                                                                           background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                          isArgb: false),\n                                                                                                                               fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                        isArgb: false),\n                                                                                                                               strokeWidth: 0.0),\n                                                                                           foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                               color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                    isArgb: false),\n                                                                                                                               useShadow: false)),\n                                           closeButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                    text: \"?cameraPermissionCloseButton\",\n                                                                                    accessibilityDescription: \"?accessibilityDescriptionCameraPermissionCloseButton\",\n                                                                                    background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                   isArgb: false),\n                                                                                                                        fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                 isArgb: false),\n                                                                                                                        strokeWidth: 0.0),\n                                                                                    foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                        color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                             isArgb: false),\n                                                                                                                        useShadow: false)),\n                                           enableCameraTitle: SBSDKUI2StyledText(text: \"?cameraPermissionEnableCameraTitle\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                      isArgb: false)),\n                                           enableCameraExplanation: SBSDKUI2StyledText(text: \"?cameraPermissionEnableCameraExplanation\",\n                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                            isArgb: false))), ","kind":"text"},{"text":"topBarTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":" = SBSDKUI2StyledText(text: \"?cameraTopBarTitle\",\n                                                             color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                  isArgb: false)), ","kind":"text"},{"kind":"externalParam","text":"topBarIntroButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton"},{"kind":"text","text":" = SBSDKUI2IconButton(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\", isArgb: false),\n                               accessibilityDescription: \"?accessibilityDescriptionCameraTopBarIntroButton\"), "},{"text":"topBarBackButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"text":" = SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                    text: \"?cameraTopBarCancelButtonTitle\",\n                                                                                    accessibilityDescription: \"?accessibilityDescriptionCameraTopBarCancelButton\",\n                                                                                    background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                   isArgb: false),\n                                                                                                                        fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                 isArgb: false),\n                                                                                                                        strokeWidth: 0.0),\n                                                                                    foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                        color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                             isArgb: false),\n                                                                                                                        useShadow: false)), ","kind":"text"},{"text":"topUserGuidance","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":" = SBSDKUI2UserGuidanceConfiguration(title: SBSDKUI2StyledText(text: \"?cameraTopGuidance\",\n                                                                        color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                             isArgb: false))), "},{"text":"userGuidance","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance","kind":"typeIdentifier","text":"SBSDKUI2DocumentScannerUserGuidance","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance"},{"text":" = SBSDKUI2DocumentScannerUserGuidance(), ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"#000000FF\", isArgb: false), ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration"},{"kind":"text","text":" = SBSDKUI2DocumentScannerCameraConfiguration(), "},{"kind":"externalParam","text":"polygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration","text":"SBSDKUI2DocumentPolygonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration"},{"kind":"text","text":" = SBSDKUI2DocumentPolygonConfiguration(), "},{"kind":"externalParam","text":"bottomBar"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","kind":"typeIdentifier"},{"text":" = SBSDKUI2CameraBottomBar(), ","kind":"text"},{"text":"viewFinder","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration"},{"text":" = SBSDKUI2ViewFinderConfiguration(visible: false,\n                                                                                      aspectRatio: SBSDKUI2AspectRatio(width: 21.0,\n                                                                                                                       height: 29.0)), ","kind":"text"},{"kind":"externalParam","text":"captureFeedback"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback","text":"SBSDKUI2CaptureFeedback","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2CaptureFeedback(), "},{"text":"vibration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2Vibration(enabled: true), "},{"text":"timeouts","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","text":"SBSDKUI2Timeouts","kind":"typeIdentifier"},{"kind":"text","text":" = SBSDKUI2Timeouts(autoCancelTimeout: 0, initialScanDelay: 0), "},{"text":"limitReachedAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":" = SBSDKUI2ScanbotAlertDialog(title: SBSDKUI2StyledText(text: \"?cameraLimitReachedAlertTitle\",\n                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                      isArgb: false)),\n                                       subtitle: SBSDKUI2StyledText(text: \"?cameraLimitReachedAlertSubtitle\",\n                                                                    color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                         isArgb: false)),\n                                       okButton: SBSDKUI2ButtonConfiguration(text: \"?cameraLimitReachedOkButtonTitle\",\n                                                                             accessibilityDescription: \"?accessibilityDescriptionCameraLimitReachedOkButton\",\n                                                                             background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                          isArgb: false),\n                                                                                                                 strokeWidth: 0.0),\n                                                                             foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                      isArgb: false))),\n                                       cancelButton: SBSDKUI2ButtonConfiguration(visible: false)), "},{"kind":"externalParam","text":"cancelAlertDialog"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":" = SBSDKUI2ScanbotAlertDialog(title: SBSDKUI2StyledText(text: \"?cameraCancelAlertTitle\",\n                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                      isArgb: false)),\n                                       subtitle: SBSDKUI2StyledText(text: \"?cameraCancelAlertSubtitle\",\n                                                                    color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                         isArgb: false)),\n                                       okButton: SBSDKUI2ButtonConfiguration(text: \"?cameraCancelYesButtonTitle\",\n                                                                             accessibilityDescription: \"?accessibilityDescriptionCameraCancelYesButton\",\n                                                                             background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                          isArgb: false),\n                                                                                                                 strokeWidth: 0.0),\n                                                                             foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                      isArgb: false))),\n                                       cancelButton: SBSDKUI2ButtonConfiguration(text: \"?cameraCancelNoButtonTitle\",\n                                                                                 accessibilityDescription: \"?accessibilityDescriptionCameraCancelNoButton\",\n                                                                                 background: SBSDKUI2BackgroundStyle(fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                              isArgb: false),\n                                                                                                                     strokeWidth: 0.0),\n                                                                                 foreground: SBSDKUI2ForegroundStyle(color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                          isArgb: false)))))"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"title":"init(acknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:)","navigatorTitle":[{"text":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(im)initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"acknowledgement"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration","kind":"typeIdentifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"introduction"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroductionScreenConfiguration","text":"SBSDKUI2IntroductionScreenConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanAssistanceOverlay"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ScanAssistanceOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPermission","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topBarIntroButton"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","kind":"typeIdentifier","text":"SBSDKUI2IconButton"},{"text":", ","kind":"text"},{"text":"topBarBackButton","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topUserGuidance"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","text":"SBSDKUI2UserGuidanceConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userGuidance"},{"kind":"text","text":": "},{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance"},{"kind":"text","text":", "},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration","kind":"typeIdentifier","text":"SBSDKUI2DocumentScannerCameraConfiguration"},{"kind":"text","text":", "},{"text":"polygon","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration"},{"kind":"text","text":", "},{"text":"bottomBar","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2CameraBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar"},{"kind":"text","text":", "},{"text":"viewFinder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","text":"SBSDKUI2ViewFinderConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captureFeedback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CaptureFeedback","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback"},{"kind":"text","text":", "},{"text":"vibration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration"},{"text":", ","kind":"text"},{"text":"timeouts","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","text":"SBSDKUI2Timeouts","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limitReachedAlertDialog"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cancelAlertDialog","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/init(acknowledgement:introduction:scanassistanceoverlay:camerapermission:topbartitle:topbarintrobutton:topbarbackbutton:topuserguidance:userguidance:backgroundcolor:cameraconfiguration:polygon:bottombar:viewfinder:capturefeedback:vibration:-7d6t1"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/init(acknowledgement:introduction:scanassistanceoverlay:camerapermission:topbartitle:topbarintrobutton:topbarbackbutton:topuserguidance:userguidance:backgroundcolor:cameraconfiguration:polygon:bottombar:viewfinder:capturefeedback:vibration:-7d6t1"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration/init(acknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"acknowledgement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration","text":"SBSDKUI2AcknowledgementScreenConfiguration"},{"kind":"text","text":", "},{"text":"introduction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroductionScreenConfiguration","kind":"typeIdentifier","text":"SBSDKUI2IntroductionScreenConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanAssistanceOverlay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay","text":"SBSDKUI2ScanAssistanceOverlay","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPermission"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","text":"SBSDKUI2CameraPermissionScreen"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topBarTitle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"topBarIntroButton","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"topBarBackButton","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"text":"topUserGuidance","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"},{"text":", ","kind":"text"},{"text":"userGuidance","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"backgroundColor"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"cameraConfiguration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration","text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygon","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration","text":"SBSDKUI2DocumentPolygonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomBar"},{"kind":"text","text":": "},{"text":"SBSDKUI2CameraBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar"},{"text":", ","kind":"text"},{"text":"viewFinder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration"},{"text":", ","kind":"text"},{"text":"captureFeedback","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2CaptureFeedback","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback"},{"text":", ","kind":"text"},{"text":"vibration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration","text":"SBSDKUI2Vibration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timeouts"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","text":"SBSDKUI2Timeouts"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limitReachedAlertDialog"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancelAlertDialog"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/init(acknowledgement:introduction:scanassistanceoverlay:camerapermission:topbartitle:topbarintrobutton:topbarbackbutton:topuserguidance:userguidance:backgroundcolor:cameraconfiguration:polygon:bottombar:viewfinder:capturefeedback:vibration:-7d6t1","title":"init(acknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/init(acknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanAssistanceOverlay":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the scan assistance overlay."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2scanassistanceoverlay","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay","title":"SBSDKUI2ScanAssistanceOverlay"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Timeouts":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2timeouts","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"title":"SBSDKUI2Timeouts","abstract":[{"text":"Configuration of timeouts.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementScreenConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration","title":"SBSDKUI2AcknowledgementScreenConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the acknowledgement screen.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerUserGuidance":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the hints guiding users through the scanning process."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneruserguidance","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance","title":"SBSDKUI2DocumentScannerUserGuidance","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ScanbotAlertDialog":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2scanbotalertdialog","title":"SBSDKUI2ScanbotAlertDialog","navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","kind":"symbol","abstract":[{"text":"Configuration of the the standard alert dialog.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraPermissionScreen":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2camerapermissionscreen","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the camera permission request view."}],"title":"SBSDKUI2CameraPermissionScreen","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconButton":{"url":"\/documentation\/scanbotsdk\/sbsdkui2iconbutton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconButton"}],"abstract":[{"type":"text","text":"Configuration of the icon appearance."}],"title":"SBSDKUI2IconButton","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Button configuration."}],"title":"SBSDKUI2ButtonConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"title":"SBSDKUI2UserGuidanceConfiguration","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"title":"SBSDKUI2StyledText","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraBottomBar":{"abstract":[{"text":"Configuration of the bottom bar for the camera screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","url":"\/documentation\/scanbotsdk\/sbsdkui2camerabottombar","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraBottomBar","kind":"identifier"}],"title":"SBSDKUI2CameraBottomBar"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IntroductionScreenConfiguration":{"title":"SBSDKUI2IntroductionScreenConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}],"navigatorTitle":[{"text":"SBSDKUI2IntroductionScreenConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2introductionscreenconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the introduction screen for the document scanner."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerCameraConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercameraconfiguration","title":"SBSDKUI2DocumentScannerCameraConfiguration","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration","abstract":[{"text":"Configuration of the camera behavior.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration":{"role":"symbol","kind":"symbol","title":"SBSDKUI2CameraScreenConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration of the screen for scanning the pages with the camera."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentPolygonConfiguration":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2documentpolygonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the document contour detection polygon."}],"title":"SBSDKUI2DocumentPolygonConfiguration","navigatorTitle":[{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ViewFinderConfiguration":{"abstract":[{"text":"Configuration of the scanning interface’s viewfinder, serving as guidance to the user.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}],"type":"topic","title":"SBSDKUI2ViewFinderConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2viewfinderconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CaptureFeedback":{"abstract":[{"type":"text","text":"Configuration of the feedback shown after snapping a page."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2capturefeedback","title":"SBSDKUI2CaptureFeedback","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Vibration":{"kind":"symbol","abstract":[{"text":"Vibration configuration.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2vibration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Vibration","kind":"identifier"}],"title":"SBSDKUI2Vibration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Vibration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithAcknowledgement:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration","kind":"typeIdentifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"},{"text":" *) ","kind":"text"},{"text":"acknowledgement","kind":"internalParam"},{"kind":"text","text":" "},{"text":"introduction:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IntroductionScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IntroductionScreenConfiguration","text":"SBSDKUI2IntroductionScreenConfiguration"},{"text":" *) ","kind":"text"},{"text":"introduction","kind":"internalParam"},{"kind":"text","text":" "},{"text":"scanAssistanceOverlay:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2ScanAssistanceOverlay","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanAssistanceOverlay","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay"},{"text":" *) ","kind":"text"},{"text":"scanAssistanceOverlay","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermission:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2CameraPermissionScreen","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraPermissionScreen","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraPermissionScreen","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"cameraPermission","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"topBarTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarIntroButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","text":"SBSDKUI2IconButton"},{"text":" *) ","kind":"text"},{"text":"topBarIntroButton","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarBackButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"text":"topBarBackButton","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topUserGuidance:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topUserGuidance"},{"text":" ","kind":"text"},{"text":"userGuidance:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2DocumentScannerUserGuidance","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerUserGuidance"},{"text":" *) ","kind":"text"},{"text":"userGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"backgroundColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerCameraConfiguration","kind":"typeIdentifier","text":"SBSDKUI2DocumentScannerCameraConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerCameraConfiguration"},{"kind":"text","text":" *) "},{"text":"cameraConfiguration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"polygon:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentPolygonConfiguration","text":"SBSDKUI2DocumentPolygonConfiguration"},{"kind":"text","text":" *) "},{"text":"polygon","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CameraBottomBar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraBottomBar"},{"kind":"text","text":" *) "},{"text":"bottomBar","kind":"internalParam"},{"kind":"text","text":" "},{"text":"viewFinder:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKUI2ViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ViewFinderConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ViewFinderConfiguration"},{"text":" *) ","kind":"text"},{"text":"viewFinder","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureFeedback:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback","text":"SBSDKUI2CaptureFeedback","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"captureFeedback"},{"kind":"text","text":" "},{"text":"vibration:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Vibration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Vibration","kind":"typeIdentifier","text":"SBSDKUI2Vibration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"vibration"},{"text":" ","kind":"text"},{"text":"timeouts:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Timeouts","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Timeouts","text":"SBSDKUI2Timeouts"},{"text":" *) ","kind":"text"},{"text":"timeouts","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"limitReachedAlertDialog:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"limitReachedAlertDialog"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelAlertDialog:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"cancelAlertDialog","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1init(acknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1init(acknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAcknowledgement:introduction:scanAssistanceOverlay:cameraPermission:topBarTitle:topBarIntroButton:topBarBackButton:topUserGuidance:userGuidance:backgroundColor:cameraConfiguration:polygon:bottomBar:viewFinder:captureFeedback:vibration:timeouts:limitReachedAlertDialog:cancelAlertDialog:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/title","value":"SBSDKUI2ScanAssistanceOverlay"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanAssistanceOverlay\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}]},{"value":"SBSDKUI2Timeouts","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/title"},{"value":[{"text":"SBSDKUI2Timeouts","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Timeouts\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Timeouts"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2AcknowledgementScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/title","op":"replace","value":"SBSDKUI2DocumentScannerUserGuidance"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerUserGuidance\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2ScanbotAlertDialog","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2CameraPermissionScreen","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CameraPermissionScreen","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraPermissionScreen\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraPermissionScreen"}],"op":"replace"},{"value":"SBSDKUI2IconButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IconButton"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title","value":"SBSDKUI2ButtonConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title","value":"SBSDKUI2UserGuidanceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/title","value":"SBSDKUI2CameraBottomBar"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraBottomBar\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CameraBottomBar"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/title","value":"SBSDKUI2IntroductionScreenConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IntroductionScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IntroductionScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/title","value":"SBSDKUI2DocumentScannerCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2DocumentScannerCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerCameraConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/title","op":"replace","value":"SBSDKUI2CameraScreenConfiguration"},{"op":"replace","value":[{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/title","value":"SBSDKUI2DocumentPolygonConfiguration"},{"value":[{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentPolygonConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentPolygonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/title","value":"SBSDKUI2ViewFinderConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/fragments","value":[{"text":"SBSDKUI2ViewFinderConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ViewFinderConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ViewFinderConfiguration"}]},{"op":"replace","value":"SBSDKUI2CaptureFeedback","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/fragments","value":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}]},{"value":"SBSDKUI2Vibration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Vibration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Vibration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Vibration","kind":"identifier"}]}]}]}