{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topBarIntroButton","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/topBarIntroButton"},"sections":[],"abstract":[{"type":"text","text":"Configuration of the ‘introduction’ button, located in the top bar."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/topbarintrobutton"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/topbarintrobutton"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarIntroButton"},{"kind":"text","text":": "},{"text":"SBSDKUI2IconButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"}],"navigatorTitle":[{"kind":"identifier","text":"topBarIntroButton"}],"role":"symbol","title":"topBarIntroButton","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CameraScreenConfiguration(py)topBarIntroButton","symbolKind":"property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration/topBarIntroButton":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarIntroButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2IconButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the ‘introduction’ button, located in the top bar."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration\/topBarIntroButton","title":"topBarIntroButton","role":"symbol","navigatorTitle":[{"text":"topBarIntroButton","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration\/topbarintrobutton","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CameraScreenConfiguration":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CameraScreenConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CameraScreenConfiguration","type":"topic","role":"symbol","abstract":[{"text":"Configuration of the screen for scanning the pages with the camera.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2camerascreenconfiguration","title":"SBSDKUI2CameraScreenConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconButton":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Configuration of the icon appearance.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2IconButton"}],"title":"SBSDKUI2IconButton","url":"\/documentation\/scanbotsdk\/sbsdkui2iconbutton","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconButton"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"topBarIntroButton","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"topBarIntroButton","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconButton","text":"SBSDKUI2IconButton","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconButton","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"topBarIntroButton","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1topBarIntroButton\/title","value":"topBarIntroButton"},{"value":[{"text":"topBarIntroButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration~1topBarIntroButton\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/title","value":"SBSDKUI2CameraScreenConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CameraScreenConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraScreenConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/title","op":"replace","value":"SBSDKUI2IconButton"},{"value":[{"text":"SBSDKUI2IconButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconButton\/fragments"}]}]}