{"abstract":[{"text":"Órgão Expedidor - Issuing Authority","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingAuthority","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelBrIdCardFront(py)issuingAuthority","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"issuingAuthority","navigatorTitle":[{"text":"issuingAuthority","kind":"identifier"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelbridcardfront\/issuingauthority"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelbridcardfront\/issuingauthority"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelBrIdCardFront"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelBrIdCardFront\/issuingAuthority","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelBrIdCardFront/issuingAuthority":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelBrIdCardFront\/issuingAuthority","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"issuingAuthority","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"issuingAuthority"}],"role":"symbol","title":"issuingAuthority","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelbridcardfront\/issuingauthority","type":"topic","abstract":[{"type":"text","text":"Órgão Expedidor - Issuing Authority"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Generic document field.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","type":"topic","kind":"symbol","title":"SBSDKGenericDocumentField"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelBrIdCardFront":{"title":"SBSDKDocumentsModelBrIdCardFront","abstract":[{"text":"Brazilian National Identity Card (Registro Geral)","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelbridcardfront","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentsModelBrIdCardFront","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelBrIdCardFront"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelBrIdCardFront","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"issuingAuthority","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"issuingAuthority","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":" * ","kind":"text"},{"text":"issuingAuthority","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelBrIdCardFront~1issuingAuthority\/title","value":"issuingAuthority","op":"replace"},{"value":[{"kind":"identifier","text":"issuingAuthority"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelBrIdCardFront~1issuingAuthority\/fragments","op":"replace"},{"value":"SBSDKGenericDocumentField","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentsModelBrIdCardFront","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelBrIdCardFront\/title"},{"value":[{"text":"SBSDKDocumentsModelBrIdCardFront","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelBrIdCardFront\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelBrIdCardFront"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelBrIdCardFront\/navigatorTitle","op":"replace"}]}]}