{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Creates an instance of the recognizer which recognizes any of the given accepted document types."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/init(accepteddocumenttypes:excludedfieldtypes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/init(accepteddocumenttypes:excludedfieldtypes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithAcceptedDocumentTypes:excludedFieldTypes:) "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"acceptedDocumentTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","text":"SBSDKGenericDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType"},{"kind":"text","text":"], "},{"text":"excludedFieldTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"acceptedDocumentTypes","content":[{"inlineContent":[{"text":"An array of document types that should be recognized. Must not be ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" or empty."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"An array of normalized names for the document field types that should not be recognized. If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" all the fields are going to be recognized."}],"type":"paragraph"}],"name":"excludedFieldTypes"}]}],"sections":[],"metadata":{"title":"init(acceptedDocumentTypes:excludedFieldTypes:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"acceptedDocumentTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType","kind":"typeIdentifier","text":"SBSDKGenericDocumentRootType"},{"text":"], ","kind":"text"},{"text":"excludedFieldTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?)"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentTypes:excludedFieldTypes:"}],"symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizer(im)initWithAcceptedDocumentTypes:excludedFieldTypes:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/init(acceptedDocumentTypes:excludedFieldTypes:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"abstract":[{"type":"text","text":"A class to recognize and detect the data fields from specific documents,"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","title":"SBSDKGenericDocumentRecognizer","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer/init(acceptedDocumentTypes:excludedFieldTypes:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"acceptedDocumentTypes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKGenericDocumentRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRootType","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"excludedFieldTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer\/init(acceptedDocumentTypes:excludedFieldTypes:)","abstract":[{"text":"Creates an instance of the recognizer which recognizes any of the given accepted document types.","type":"text"}],"title":"init(acceptedDocumentTypes:excludedFieldTypes:)","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer\/init(accepteddocumenttypes:excludedfieldtypes:)","kind":"symbol","navigatorTitle":[{"text":"initWithAcceptedDocumentTypes:excludedFieldTypes:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRootType":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentroottype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRootType","abstract":[{"type":"text","text":"Root document type."}],"title":"SBSDKGenericDocumentRootType","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithAcceptedDocumentTypes:excludedFieldTypes:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAcceptedDocumentTypes:excludedFieldTypes:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAcceptedDocumentTypes:"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKGenericDocumentRootType *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"acceptedDocumentTypes","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"excludedFieldTypes:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"excludedFieldTypes"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"acceptedDocumentTypes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of document types that should be recognized. Must not be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" or empty."}]}]},{"name":"excludedFieldTypes","content":[{"type":"paragraph","inlineContent":[{"text":"An array of normalized names for the document field types that should not be recognized. If ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" all the fields are going to be recognized."}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title","value":"SBSDKGenericDocumentRecognizer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/navigatorTitle"},{"value":"initWithAcceptedDocumentTypes:excludedFieldTypes:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1init(acceptedDocumentTypes:excludedFieldTypes:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcceptedDocumentTypes:excludedFieldTypes:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer~1init(acceptedDocumentTypes:excludedFieldTypes:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/title","value":"SBSDKGenericDocumentRootType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/fragments","value":[{"text":"SBSDKGenericDocumentRootType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentRootType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRootType\/navigatorTitle"}]}]}