{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/camerasession:didchangezoom:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraSession:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCameraSession","text":"SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didChangeZoom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"zoomValue","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/cameraSession:didChangeZoom:"},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"cameraSession:didChangeZoom:","kind":"identifier"}],"title":"cameraSession:didChangeZoom:","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController(im)cameraSession:didChangeZoom:","navigatorTitle":[{"text":"cameraSession:didChangeZoom:","kind":"identifier"}]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraSession":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraSession","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcamerasession","type":"topic","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}],"title":"SBSDKCameraSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","type":"topic","abstract":[{"text":"A highly customizable camera view controller that delivers a basic camera functionality along with video","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"frame extraction and preprocessing, orientation correction and still image capturing."}],"title":"SBSDKBaseScannerViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController/cameraSession:didChangeZoom:":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cameraSession:didChangeZoom:"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/cameraSession:didChangeZoom:","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/camerasession:didchangezoom:","title":"cameraSession:didChangeZoom:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraSession:didChangeZoom:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKCameraSession","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/title"},{"op":"replace","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSession"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraSession\/navigatorTitle"},{"op":"replace","value":"SBSDKBaseScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle"}]}]}