{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The image storage was invalid or nil."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/imageStorageCopyingFailed"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/imagestoragecopyingfailed"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/imagestoragecopyingfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SBSDKErrorCode.imageStorageCopyingFailed","externalID":"c:@M@ScanbotSDK@E@SBSDKErrorCode@SBSDKErrorCodeImageStorageCopyingFailed","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeImageStorageCopyingFailed"}],"symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageStorageCopyingFailed","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageStorageCopyingFailed"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/imageStorageCopyingFailed":{"abstract":[{"type":"text","text":"The image storage was invalid or nil."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeImageStorageCopyingFailed"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/imageStorageCopyingFailed","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/imagestoragecopyingfailed","kind":"symbol","type":"topic","role":"symbol","title":"SBSDKErrorCode.imageStorageCopyingFailed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"imageStorageCopyingFailed","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKErrorCode"}],"abstract":[{"text":"The error codes in the SBSDKErrorDomain.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCode"}],"title":"SBSDKErrorCode","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKErrorCodeImageStorageCopyingFailed"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKErrorCodeImageStorageCopyingFailed","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKErrorCodeImageStorageCopyingFailed","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKErrorCodeImageStorageCopyingFailed","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1imageStorageCopyingFailed\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1imageStorageCopyingFailed\/fragments","op":"replace","value":[{"text":"SBSDKErrorCodeImageStorageCopyingFailed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/title","value":"SBSDKErrorCode","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKErrorCode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/fragments","op":"replace"}]}]}