{"metadata":{"title":"SBSDKErrorCode.invalidFileURL","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidFileURL"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKErrorCode@SBSDKErrorCodeInvalidFileURL","roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFileURL"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidFileURL","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidfileurl"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidfileurl"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode"]]},"abstract":[{"type":"text","text":"The file does not exist."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFileURL"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode":{"abstract":[{"type":"text","text":"The error codes in the SBSDKErrorDomain."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode","navigatorTitle":[{"text":"SBSDKErrorCode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode","type":"topic","kind":"symbol","title":"SBSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKErrorCode","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/invalidFileURL":{"abstract":[{"text":"The file does not exist.","type":"text"}],"title":"SBSDKErrorCode.invalidFileURL","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidFileURL"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/invalidFileURL","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/invalidfileurl","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidFileURL","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKErrorCodeInvalidFileURL"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SBSDKErrorCodeInvalidFileURL","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKErrorCodeInvalidFileURL"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/title","value":"SBSDKErrorCode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKErrorCode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidFileURL\/title","value":"SBSDKErrorCodeInvalidFileURL"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1invalidFileURL\/fragments","op":"replace","value":[{"text":"SBSDKErrorCodeInvalidFileURL","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}