{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/pageanalysis"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/pageanalysis"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode"]]},"abstract":[{"type":"text","text":"Page analysis failed."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageAnalysis"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/pageAnalysis"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageAnalysis"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKErrorCode@SBSDKErrorCodePageAnalysis","role":"symbol","title":"SBSDKErrorCode.pageAnalysis","roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKErrorCodePageAnalysis","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode","type":"topic","title":"SBSDKErrorCode","abstract":[{"type":"text","text":"The error codes in the SBSDKErrorDomain."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKErrorCode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/pageAnalysis":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageAnalysis"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/pageanalysis","title":"SBSDKErrorCode.pageAnalysis","role":"symbol","navigatorTitle":[{"text":"SBSDKErrorCodePageAnalysis","kind":"identifier"}],"abstract":[{"text":"Page analysis failed.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/pageAnalysis","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKErrorCodePageAnalysis"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKErrorCodePageAnalysis"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKErrorCodePageAnalysis","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SBSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/fragments","value":[{"text":"SBSDKErrorCode","kind":"identifier"}]},{"value":"SBSDKErrorCodePageAnalysis","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1pageAnalysis\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorCodePageAnalysis"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1pageAnalysis\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}