{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/textRecognition"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode"]]},"abstract":[{"type":"text","text":"Optical text recognition failed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"textRecognition","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/textrecognition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrorcode\/textrecognition"]}],"metadata":{"title":"SBSDKErrorCode.textRecognition","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKErrorCode@SBSDKErrorCodeTextRecognition","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textRecognition","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKErrorCodeTextRecognition","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode/textRecognition":{"title":"SBSDKErrorCode.textRecognition","role":"symbol","navigatorTitle":[{"text":"SBSDKErrorCodeTextRecognition","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textRecognition","kind":"identifier"}],"abstract":[{"type":"text","text":"Optical text recognition failed."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode\/textRecognition","url":"\/documentation\/scanbotsdk\/sbsdkerrorcode\/textrecognition","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorCode":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorCode","title":"SBSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorCode"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrorcode","type":"topic","abstract":[{"type":"text","text":"The error codes in the SBSDKErrorDomain."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKErrorCode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKErrorCodeTextRecognition"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKErrorCodeTextRecognition"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKErrorCodeTextRecognition"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1textRecognition\/title","value":"SBSDKErrorCodeTextRecognition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode~1textRecognition\/fragments","value":[{"text":"SBSDKErrorCodeTextRecognition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/title","op":"replace","value":"SBSDKErrorCode"},{"value":[{"text":"SBSDKErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorCode\/fragments"}]}]}