{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/fromjsonwithjson:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/fromJsonWithJson:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions"]]},"metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPathImageLoadOptions(cm)fromJsonWithJson:","role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKPathImageLoadOptions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPathImageLoadOptions","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/fromJsonWithJson:":{"title":"fromJsonWithJson:","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/fromjsonwithjson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions","title":"SBSDKPathImageLoadOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"abstract":[{"text":"Options for loading image from path.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/title","op":"replace","value":"SBSDKPathImageLoadOptions"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/fragments","op":"replace","value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}]}]}]}