{"metadata":{"roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroGeneralField(cm)fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2TextPatternIntroGeneralField","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroGeneralField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternIntroGeneralField"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternintrogeneralfield\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroGeneralField\/fromJsonWithJson:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroGeneralField"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroGeneralField/fromJsonWithJson:":{"role":"symbol","type":"topic","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroGeneralField\/fromJsonWithJson:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintrogeneralfield\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternIntroGeneralField":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternIntroGeneralField","abstract":[{"type":"text","text":"The image for the introduction screen featuring a general text field."}],"title":"SBSDKUI2TextPatternIntroGeneralField","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternIntroGeneralField"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternIntroGeneralField"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternintrogeneralfield","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroGeneralField\/title","value":"SBSDKUI2TextPatternIntroGeneralField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroGeneralField\/fragments","value":[{"text":"SBSDKUI2TextPatternIntroGeneralField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternIntroGeneralField\/navigatorTitle","value":[{"text":"SBSDKUI2TextPatternIntroGeneralField","kind":"identifier"}]}]}]}