{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/isSuspicious","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Shows whether the data in the field is suspicious, e.g. contains word “Sample” in the name."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuspicious"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/issuspicious"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/issuspicious"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldSuspiciousDataVerificationReport(py)isSuspicious","title":"isSuspicious","navigatorTitle":[{"text":"isSuspicious","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSuspicious","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport":{"abstract":[{"type":"text","text":"Report of the suspicious data field verification."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport","navigatorTitle":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}],"kind":"symbol","title":"SBSDKFieldSuspiciousDataVerificationReport"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFieldSuspiciousDataVerificationReport/isSuspicious":{"title":"isSuspicious","url":"\/documentation\/scanbotsdk\/sbsdkfieldsuspiciousdataverificationreport\/issuspicious","abstract":[{"text":"Shows whether the data in the field is suspicious, e.g. contains word “Sample” in the name.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isSuspicious"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuspicious"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFieldSuspiciousDataVerificationReport\/isSuspicious"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isSuspicious"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isSuspicious","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isSuspicious","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/title","value":"SBSDKFieldSuspiciousDataVerificationReport"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/fragments","value":[{"kind":"identifier","text":"SBSDKFieldSuspiciousDataVerificationReport"}]},{"value":[{"text":"SBSDKFieldSuspiciousDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport\/navigatorTitle"},{"value":"isSuspicious","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport~1isSuspicious\/title"},{"value":[{"kind":"identifier","text":"isSuspicious"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFieldSuspiciousDataVerificationReport~1isSuspicious\/fragments"}]}]}