{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","roleHeading":"Instance Method","title":"generate(from:to:)","symbolKind":"method","externalID":"s:25ScanbotDocumentScannerSDK18SBSDKTIFFGeneratorC8generate4from2to10Foundation3URLVSgSayAIG_AItYaKF"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"imageURLs","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"], ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"fileURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"imageURLs","content":[{"inlineContent":[{"text":"The array of image URLs to generate the multipage-TIFF from.","type":"text"}],"type":"paragraph"}]},{"name":"fileURL","content":[{"type":"paragraph","inlineContent":[{"text":"The file URL to save the TIFF file at.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The URL the TIFF file has been written to or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" and an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" if the operation failed."}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGenerator\/generate(from:to:)-4ea4l"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGenerator"]]},"sections":[],"abstract":[{"text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and saves it to the specified URL.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgenerator\/generate(from:to:)-4ea4l"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGenerator":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgenerator","abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/defaultCryptingProvider","isActive":true,"type":"reference"},{"text":" is set, the generated TIFF files will be encrypted using the specified crypting provider.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGenerator","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"title":"SBSDKTIFFGenerator","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot/defaultCryptingProvider":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/defaultCryptingProvider","abstract":[{"type":"text","text":"The SDK-wide encryption provider for storing image data to disk. Defaults to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", no encryption used."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultCryptingProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/scanbot\/defaultcryptingprovider","navigatorTitle":[{"kind":"identifier","text":"defaultCryptingProvider"}],"type":"topic","title":"defaultCryptingProvider","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGenerator/generate(from:to:)-4ea4l":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgenerator\/generate(from:to:)-4ea4l","kind":"symbol","title":"generate(from:to:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGenerator\/generate(from:to:)-4ea4l","abstract":[{"text":"Asynchronously converts the images at the given image URLs to a multipage-TIFF file and saves it to the specified URL.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGenerator\/title","value":"SBSDKTIFFGenerator","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGenerator\/fragments","value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGenerator\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1defaultCryptingProvider\/title","value":"defaultCryptingProvider","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1defaultCryptingProvider\/fragments","value":[{"kind":"identifier","text":"defaultCryptingProvider"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}