{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"visible","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"background:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BackgroundStyle","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BackgroundStyle"},{"text":" *) ","kind":"text"},{"text":"background","kind":"internalParam"},{"kind":"text","text":" "},{"text":"foregroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"foregroundColor"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2badgestyle\/initwithvisible:background:foregroundcolor:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BadgeStyle\/initWithVisible:background:foregroundColor:","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"initWithVisible:background:foregroundColor:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithVisible:background:foregroundColor:","kind":"identifier"}],"title":"initWithVisible:background:foregroundColor:","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2BadgeStyle(im)initWithVisible:background:foregroundColor:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BadgeStyle"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BadgeStyle":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2badgestyle","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BadgeStyle","title":"SBSDKUI2BadgeStyle","navigatorTitle":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration of the badge.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BadgeStyle/initWithVisible:background:foregroundColor:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BadgeStyle\/initWithVisible:background:foregroundColor:","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2badgestyle\/initwithvisible:background:foregroundcolor:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisible:background:foregroundColor:","kind":"identifier"}],"title":"initWithVisible:background:foregroundColor:","navigatorTitle":[{"text":"initWithVisible:background:foregroundColor:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2BackgroundStyle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2BackgroundStyle","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration of the background appearance for buttons and hints."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}],"title":"SBSDKUI2BackgroundStyle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2backgroundstyle"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","type":"topic","title":"SBSDKUI2Color","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2BadgeStyle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BadgeStyle\/title","op":"replace"},{"value":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BadgeStyle\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BadgeStyle\/navigatorTitle","value":[{"text":"SBSDKUI2BadgeStyle","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2BackgroundStyle","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BackgroundStyle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BackgroundStyle\/fragments","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2BackgroundStyle\/navigatorTitle"},{"value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle"}]}]}