{"metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKBarcodeEngineModeLegacy","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeEngineMode@SBSDKBarcodeEngineModeLegacy","title":"SBSDKBarcodeEngineMode.legacy","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"legacy","kind":"identifier"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode\/legacy","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeenginemode\/legacy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeenginemode\/legacy"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode"]]},"abstract":[{"text":"Legacy mode.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"legacy"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeEngineMode/legacy":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode\/legacy","abstract":[{"text":"Legacy mode.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeenginemode\/legacy","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeEngineModeLegacy"}],"kind":"symbol","title":"SBSDKBarcodeEngineMode.legacy","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"legacy","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeEngineMode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeEngineMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeenginemode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode","navigatorTitle":[{"text":"SBSDKBarcodeEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The engine mode of the barcode recognizer."}],"kind":"symbol","title":"SBSDKBarcodeEngineMode","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeEngineModeLegacy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeEngineModeLegacy"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKBarcodeEngineModeLegacy","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode~1legacy\/title","value":"SBSDKBarcodeEngineModeLegacy"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode~1legacy\/fragments","value":[{"text":"SBSDKBarcodeEngineModeLegacy","kind":"identifier"}]},{"op":"replace","value":"SBSDKBarcodeEngineMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeEngineMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKBarcodeEngineMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode\/navigatorTitle"}]}]}