{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"title":"SBSDKUI2UserGuidanceVisibility.disabled","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2UserGuidanceVisibility@SBSDKUI2UserGuidanceVisibilityDisabled","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibilityDisabled","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case"},"sections":[],"abstract":[{"type":"text","text":"Disabled for both ‘auto snapping’ and ‘manual snapping’ modes."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/disabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/disabled"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility\/disabled","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceVisibility":{"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"abstract":[{"text":"Determines the visibility mode for the document capturing user guidance labels.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility","title":"SBSDKUI2UserGuidanceVisibility","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceVisibility/disabled":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibilityDisabled","kind":"identifier"}],"title":"SBSDKUI2UserGuidanceVisibility.disabled","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceVisibility\/disabled","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancevisibility\/disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"disabled","kind":"identifier"}],"abstract":[{"text":"Disabled for both ‘auto snapping’ and ‘manual snapping’ modes.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKUI2UserGuidanceVisibilityDisabled","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibilityDisabled"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKUI2UserGuidanceVisibilityDisabled","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/title","value":"SBSDKUI2UserGuidanceVisibility"},{"value":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}],"op":"replace"},{"value":"SBSDKUI2UserGuidanceVisibilityDisabled","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility~1disabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceVisibility~1disabled\/fragments","value":[{"text":"SBSDKUI2UserGuidanceVisibilityDisabled","kind":"identifier"}],"op":"replace"}]}]}