{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller\/acceptedchecktypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller\/acceptedchecktypes"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedCheckTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKCheckDocumentModelRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType"},{"text":"]","kind":"text"}],"role":"symbol","title":"acceptedCheckTypes","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController(py)acceptedCheckTypes","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"acceptedCheckTypes","kind":"identifier"}],"symbolKind":"property"},"abstract":[{"text":"An array of accepted check types. By default all check types are allowed.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedCheckTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKCheckDocumentModelRootType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController\/acceptedCheckTypes","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController/acceptedCheckTypes":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController\/acceptedCheckTypes","abstract":[{"type":"text","text":"An array of accepted check types. By default all check types are allowed."}],"role":"symbol","title":"acceptedCheckTypes","kind":"symbol","navigatorTitle":[{"text":"acceptedCheckTypes","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller\/acceptedchecktypes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedCheckTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKCheckDocumentModelRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerViewController"}],"type":"topic","title":"SBSDKCheckScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","abstract":[{"text":"Classic UI view controller that can be used to scan bank checks.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelRootType":{"role":"symbol","abstract":[{"text":"Root document type.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelroottype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelRootType","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckDocumentModelRootType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKCheckDocumentModelRootType","kind":"identifier"}],"title":"SBSDKCheckDocumentModelRootType","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"acceptedCheckTypes","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"acceptedCheckTypes"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKCheckDocumentModelRootType *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"acceptedCheckTypes"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"acceptedCheckTypes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController~1acceptedCheckTypes\/title"},{"value":[{"text":"acceptedCheckTypes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController~1acceptedCheckTypes\/fragments"},{"op":"replace","value":"SBSDKCheckScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle"},{"op":"replace","value":"SBSDKCheckDocumentModelRootType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/title"},{"op":"replace","value":[{"text":"SBSDKCheckDocumentModelRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelRootType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/navigatorTitle"}]}]}