{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"]]},"abstract":[{"text":"Specifies the way of barcode images generation or disables this generation at all.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeImageGenerationType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeImageGenerationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeImageGenerationType","text":"SBSDKBarcodeImageGenerationType"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use, if you want to receive a full sized image with barcodes."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeImageGenerationType\/none","isActive":true},{"text":".","type":"text"}]},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property has no effect if "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/isTrackingOverlayEnabled","isActive":true,"type":"reference"},{"type":"text","text":" is set to "},{"code":"True","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"With the tracking overlay enabled, barcode images cannot be generated."}]}],"style":"note","type":"aside"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/barcodeImageGenerationType"},"metadata":{"navigatorTitle":[{"text":"barcodeImageGenerationType","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"barcodeImageGenerationType","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController(py)barcodeImageGenerationType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"barcodeImageGenerationType","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeImageGenerationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeImageGenerationType"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/barcodeimagegenerationtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/barcodeimagegenerationtype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController/isTrackingOverlayEnabled":{"abstract":[{"type":"text","text":"Displays an augmented reality view that draws the frames, content and type text of the found barcodes when it finds them."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/isTrackingOverlayEnabled","title":"isTrackingOverlayEnabled","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTrackingOverlayEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/istrackingoverlayenabled","navigatorTitle":[{"text":"isTrackingOverlayEnabled","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"title":"SBSDKBarcodeScannerViewController","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeImageGenerationType":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeimagegenerationtype","type":"topic","kind":"symbol","title":"SBSDKBarcodeImageGenerationType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeImageGenerationType","role":"symbol","abstract":[{"type":"text","text":"The type of the barcode image generation."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeImageGenerationType/none":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"abstract":[{"text":"No barcode image generation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationTypeNone"}],"title":"SBSDKBarcodeImageGenerationType.none","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeImageGenerationType\/none","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeimagegenerationtype\/none","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController/barcodeImageGenerationType":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/barcodeimagegenerationtype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeImageGenerationType"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeImageGenerationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeImageGenerationType"}],"navigatorTitle":[{"text":"barcodeImageGenerationType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/barcodeImageGenerationType","role":"symbol","type":"topic","abstract":[{"text":"Specifies the way of barcode images generation or disables this generation at all.","type":"text"}],"title":"barcodeImageGenerationType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"barcodeImageGenerationType","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"barcodeImageGenerationType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeImageGenerationType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeImageGenerationType","text":"SBSDKBarcodeImageGenerationType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeImageGenerationType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"isTrackingOverlayEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController~1isTrackingOverlayEnabled\/title"},{"value":[{"kind":"identifier","text":"isTrackingOverlayEnabled"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController~1isTrackingOverlayEnabled\/fragments"},{"value":"SBSDKBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKBarcodeImageGenerationType","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeImageGenerationType\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeImageGenerationType\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeImageGenerationType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeImageGenerationType\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeImageGenerationType~1none\/title","value":"SBSDKBarcodeImageGenerationTypeNone","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeImageGenerationTypeNone"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeImageGenerationType~1none\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController~1barcodeImageGenerationType\/title","value":"barcodeImageGenerationType","op":"replace"},{"value":[{"text":"barcodeImageGenerationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController~1barcodeImageGenerationType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}