{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController(py)isRecognitionEnabled","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"isRecognitionEnabled","kind":"identifier"}],"navigatorTitle":[{"text":"isRecognitionEnabled","kind":"identifier"}],"role":"symbol","title":"isRecognitionEnabled"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/isrecognitionenabled"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/isRecognitionEnabled","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRecognitionEnabled"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 6.1.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","title":"SBSDKBarcodeScannerViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController/isRecognitionEnabled":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/isRecognitionEnabled","type":"topic","kind":"symbol","title":"isRecognitionEnabled","role":"symbol","abstract":[],"fragments":[{"text":"isRecognitionEnabled","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/isrecognitionenabled"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}