{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetAccumulation"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/resetaccumulation()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/resetaccumulation()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/resetAccumulation()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Resets the barcode results accumulator that is used for smoother results."},{"type":"text","text":" "},{"type":"text","text":"It is recommended to explicitly reset it, when there is the intention to scan for another barcode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetAccumulation"},{"kind":"text","text":"()"}],"title":"resetAccumulation()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController(im)resetAccumulation","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"resetAccumulation"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.1.3"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"role":"symbol","title":"SBSDKBarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController/resetAccumulation()":{"role":"symbol","title":"resetAccumulation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetAccumulation"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resets the barcode results accumulator that is used for smoother results."},{"type":"text","text":" "},{"type":"text","text":"It is recommended to explicitly reset it, when there is the intention to scan for another barcode."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/resetAccumulation()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetAccumulation"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/resetaccumulation()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"resetAccumulation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetAccumulation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"resetAccumulation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title","value":"SBSDKBarcodeScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController~1resetAccumulation()\/title","value":"resetAccumulation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController~1resetAccumulation()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetAccumulation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}