{"sections":[],"abstract":[{"type":"text","text":"Cleans the video frame accumulator."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScanner\/clearFrameAccumulator()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScanner"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescanner\/clearframeaccumulator()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdklicenseplatescanner\/clearframeaccumulator()"]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKLicensePlateScanner(im)clearFrameAccumulator","navigatorTitle":[{"text":"clearFrameAccumulator","kind":"identifier"}],"title":"clearFrameAccumulator()","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"clearFrameAccumulator","kind":"identifier"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearFrameAccumulator"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This basically resets the scanner to start a new scan."}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScanner/clearFrameAccumulator()":{"url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescanner\/clearframeaccumulator()","abstract":[{"text":"Cleans the video frame accumulator.","type":"text"}],"navigatorTitle":[{"text":"clearFrameAccumulator","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScanner\/clearFrameAccumulator()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearFrameAccumulator"},{"kind":"text","text":"()"}],"role":"symbol","title":"clearFrameAccumulator()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScanner":{"kind":"symbol","title":"SBSDKLicensePlateScanner","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A class to scan a vehicle’s license plate in a "},{"type":"codeVoice","code":"UIImage"},{"text":" or ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":" and run a validation on the result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScanner","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescanner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicensePlateScanner","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLicensePlateScanner","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"clearFrameAccumulator","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearFrameAccumulator"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"clearFrameAccumulator"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"clearFrameAccumulator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner~1clearFrameAccumulator()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner~1clearFrameAccumulator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearFrameAccumulator"}],"op":"replace"},{"op":"replace","value":"SBSDKLicensePlateScanner","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicensePlateScanner"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScanner\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKLicensePlateScanner"}]}]}]}