{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraLiveScannerResolution"]]},"kind":"symbol","abstract":[{"type":"text","text":"The image is in UHD resolution. 3840x2160 pixels or close to it."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameralivescannerresolution\/uhd"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcameralivescannerresolution\/uhd"]}],"metadata":{"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKCameraLiveScannerResolution@SBSDKCameraLiveScannerResolutionUhd","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uhd","kind":"identifier"}],"roleHeading":"Case","title":"SBSDKCameraLiveScannerResolution.uhd","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraLiveScannerResolution\/uhd","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uhd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraLiveScannerResolution":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"title":"SBSDKCameraLiveScannerResolution","abstract":[{"text":"The size of the image from camera which would be sent to the scanner for live scanning.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameralivescannerresolution","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraLiveScannerResolution"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCameraLiveScannerResolution/uhd":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uhd","kind":"identifier"}],"kind":"symbol","title":"SBSDKCameraLiveScannerResolution.uhd","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCameraLiveScannerResolution\/uhd","navigatorTitle":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}],"type":"topic","abstract":[{"text":"The image is in UHD resolution. 3840x2160 pixels or close to it.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcameralivescannerresolution\/uhd"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKCameraLiveScannerResolutionUhd","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKCameraLiveScannerResolutionUhd","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraLiveScannerResolution\/title","value":"SBSDKCameraLiveScannerResolution","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraLiveScannerResolution\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolution"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraLiveScannerResolution\/navigatorTitle","value":[{"text":"SBSDKCameraLiveScannerResolution","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraLiveScannerResolution~1uhd\/title","value":"SBSDKCameraLiveScannerResolutionUhd"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCameraLiveScannerResolution~1uhd\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraLiveScannerResolutionUhd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}