{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Defaults to “Cancel”.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/cancelButtonTitle","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"cancelButtonTitle"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerTextConfiguration(py)cancelButtonTitle","role":"symbol","title":"cancelButtonTitle"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"String being displayed on the cancel button."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/cancelbuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/cancelbuttontitle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration/cancelButtonTitle":{"abstract":[{"type":"text","text":"String being displayed on the cancel button."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration\/cancelbuttontitle","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"cancelButtonTitle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration\/cancelButtonTitle","title":"cancelButtonTitle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerTextConfiguration":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerTextConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICheckScannerTextConfiguration"}],"title":"SBSDKUICheckScannerTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannertextconfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the  RTU-UI check scanner."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerTextConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"cancelButtonTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cancelButtonTitle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cancelButtonTitle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1cancelButtonTitle\/title","value":"cancelButtonTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration~1cancelButtonTitle\/fragments","value":[{"text":"cancelButtonTitle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/title","value":"SBSDKUICheckScannerTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerTextConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICheckScannerTextConfiguration","kind":"identifier"}]}]}]}