{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingMode"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"live","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"In live mode input images are expected to come from a video source like a camera.","type":"text"},{"text":" ","type":"text"},{"text":"Scanners in live mode typically spend little time on each image and are able to quickly analyze multiple images and combine the individual image results into a final result.","type":"text"},{"text":" ","type":"text"},{"text":"Individual results from a particular image may be less accurate than running the scanner in single-shot mode on that frame, but after aggregating a few images of the same subject, the final result becomes much more accurate.","type":"text"}],"metadata":{"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingModeLive"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKProcessingMode.live","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKProcessingMode@SBSDKProcessingModeLive","symbolKind":"case"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingmode\/live"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingmode\/live"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingMode\/live"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessingMode":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingmode","role":"symbol","abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"},{"text":" ","type":"text"},{"text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results.","type":"text"},{"text":" ","type":"text"},{"text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject.","type":"text"}],"title":"SBSDKProcessingMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingMode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProcessingMode/live":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProcessingMode\/live","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"live","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprocessingmode\/live","title":"SBSDKProcessingMode.live","abstract":[{"type":"text","text":"In live mode input images are expected to come from a video source like a camera."},{"type":"text","text":" "},{"type":"text","text":"Scanners in live mode typically spend little time on each image and are able to quickly analyze multiple images and combine the individual image results into a final result."},{"type":"text","text":" "},{"type":"text","text":"Individual results from a particular image may be less accurate than running the scanner in single-shot mode on that frame, but after aggregating a few images of the same subject, the final result becomes much more accurate."}],"navigatorTitle":[{"text":"SBSDKProcessingModeLive","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKProcessingModeLive","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKProcessingModeLive","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKProcessingModeLive","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKProcessingMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingMode~1live\/title","value":"SBSDKProcessingModeLive","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProcessingMode~1live\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingModeLive"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}