{"abstract":[{"type":"text","text":"Check-digit type."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultCheckDigitType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"type","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizerResultCheckDigit(py)type","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigit\/type","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigit\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigit\/type"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigit":{"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigit","title":"SBSDKMachineReadableZoneRecognizerResultCheckDigit","abstract":[{"type":"text","text":"Contains information about a single check-digit."}],"navigatorTitle":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigit"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigit/type":{"role":"symbol","abstract":[{"type":"text","text":"Check-digit type."}],"type":"topic","title":"type","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigit\/type","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigit\/type","navigatorTitle":[{"text":"type","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizerResultCheckDigitType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizerresultcheckdigittype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"identifier"}],"abstract":[{"type":"text","text":"MRZ check-digit types."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}],"title":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMachineReadableZoneRecognizerResultCheckDigitType","kind":"typeIdentifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizerResultCheckDigitType"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigit","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigit\/title"},{"op":"replace","value":[{"text":"SBSDKMachineReadableZoneRecognizerResultCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigit\/fragments"},{"value":"type","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigit~1type\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigit~1type\/fragments","op":"replace","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/title","value":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizerResultCheckDigitType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizerResultCheckDigitType"}]}]}]}