{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront\/initialregistrationdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront\/initialregistrationdate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront\/initialRegistrationDate"},"abstract":[{"text":"Date when the cardholder was initially registered","type":"text"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"initialRegistrationDate","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelHkIdentityCardFront(py)initialRegistrationDate","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"initialRegistrationDate","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialRegistrationDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialRegistrationDate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"abstract":[{"type":"text","text":"Generic document field."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"identifier"}],"type":"topic","title":"SBSDKGenericDocumentField","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelHkIdentityCardFront":{"abstract":[{"type":"text","text":"HkIdentityCardFront"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelHkIdentityCardFront"}],"role":"symbol","type":"topic","title":"SBSDKDocumentsModelHkIdentityCardFront","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelHkIdentityCardFront"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelHkIdentityCardFront/initialRegistrationDate":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelhkidentitycardfront\/initialregistrationdate","title":"initialRegistrationDate","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelHkIdentityCardFront\/initialRegistrationDate","type":"topic","navigatorTitle":[{"text":"initialRegistrationDate","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialRegistrationDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Date when the cardholder was initially registered"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"initialRegistrationDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"initialRegistrationDate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField"},{"text":" * ","kind":"text"},{"text":"initialRegistrationDate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","value":"SBSDKGenericDocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentsModelHkIdentityCardFront","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentsModelHkIdentityCardFront","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentsModelHkIdentityCardFront"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront\/navigatorTitle"},{"op":"replace","value":"initialRegistrationDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront~1initialRegistrationDate\/title"},{"op":"replace","value":[{"text":"initialRegistrationDate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelHkIdentityCardFront~1initialRegistrationDate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}