{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevice\/availabledevices(for:position:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevice\/availabledevices(for:position:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraDevice(cm)availableDevicesForType:andPosition:","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"availableDevicesForType:andPosition:"}],"title":"availableDevices(for:position:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKCameraDeviceType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDeviceType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDevicePosition","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDevicePosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraDevice"},{"kind":"text","text":"]"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Type Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(availableDevicesForType:andPosition:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDevices","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDeviceType","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDeviceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDevicePosition","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevicePosition","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDevicePosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"SBSDKCameraDevice","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraDevice"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the requested cameras: wide, ultra-wide, tele, etc."}]}]},{"name":"position","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The position of the requested cameras: front or back."}]}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A list of the supported available cameras of the current device for the given type and position."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Returns a list of all available and supported cameras of the device of the given type and position.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice\/availableDevices(for:position:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCameraDeviceType"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype","kind":"symbol","abstract":[{"text":"An enum to describe the different types of camera lenses\/devices.","type":"text"}],"title":"SBSDKCameraDeviceType","navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDevicePosition":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDevicePosition","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevicePosition","navigatorTitle":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradeviceposition","abstract":[{"text":"An enum to describe the physical position of a camera device.","type":"text"}],"title":"SBSDKCameraDevicePosition"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDevice":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice","type":"topic","title":"SBSDKCameraDevice","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDevice","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The camera device to be used with a "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevice","kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraDevice","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraSession":{"abstract":[{"text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the","type":"text"},{"text":" ","type":"text"},{"text":"camera device and the preview layer. Provides functionality to capture still images.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraSession","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcamerasession","title":"SBSDKCameraSession","role":"symbol","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDevice/availableDevices(for:position:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevice\/availableDevices(for:position:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableDevices"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDeviceType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDeviceType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCameraDevicePosition","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDevicePosition"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"SBSDKCameraDevice","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCameraDevice"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevice\/availabledevices(for:position:)","abstract":[{"type":"text","text":"Returns a list of all available and supported cameras of the device of the given type and position."}],"role":"symbol","title":"availableDevices(for:position:)","navigatorTitle":[{"kind":"identifier","text":"availableDevicesForType:andPosition:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"availableDevicesForType:andPosition:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"availableDevicesForType:andPosition:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKCameraDevice *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"availableDevicesForType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDeviceType","kind":"typeIdentifier","text":"SBSDKCameraDeviceType","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"andPosition:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDevicePosition","kind":"typeIdentifier","text":"SBSDKCameraDevicePosition","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDevicePosition"},{"kind":"text","text":") "},{"kind":"internalParam","text":"position"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"type","content":[{"inlineContent":[{"text":"The type of the requested cameras: wide, ultra-wide, tele, etc.","type":"text"}],"type":"paragraph"}]},{"name":"position","content":[{"type":"paragraph","inlineContent":[{"text":"The position of the requested cameras: front or back.","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"A list of the supported available cameras of the current device for the given type and position.","type":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/title","value":"SBSDKCameraDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/fragments","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCameraDeviceType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevicePosition\/title","value":"SBSDKCameraDevicePosition"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevicePosition\/fragments","value":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevicePosition\/navigatorTitle","value":[{"text":"SBSDKCameraDevicePosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/title","value":"SBSDKCameraDevice"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDevice"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice\/navigatorTitle","value":[{"text":"SBSDKCameraDevice","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"text":"SBSDKCameraSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice~1availableDevices(for:position:)\/title","value":"availableDevicesForType:andPosition:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDevice~1availableDevices(for:position:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"availableDevicesForType:andPosition:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}