{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/barcodeItemConfiguration","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeItemConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"barcodeItemConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration"}],"navigatorTitle":[{"text":"barcodeItemConfiguration","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration(py)barcodeItemConfiguration","title":"barcodeItemConfiguration","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Configuration of the barcode info box displayed in the camera preview."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeitemconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeitemconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","title":"SBSDKUI2BarcodeItemConfiguration","abstract":[{"type":"text","text":"Configuration of the barcode info box displayed in the camera preview."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration/barcodeItemConfiguration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeItemConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/barcodeItemConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the barcode info box displayed in the camera preview."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeitemconfiguration","role":"symbol","navigatorTitle":[{"text":"barcodeItemConfiguration","kind":"identifier"}],"title":"barcodeItemConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"title":"SBSDKUI2ArOverlayGeneralConfiguration","abstract":[{"type":"text","text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"barcodeItemConfiguration","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"barcodeItemConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration","text":"SBSDKUI2BarcodeItemConfiguration"},{"kind":"text","text":" * "},{"text":"barcodeItemConfiguration","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"SBSDKUI2BarcodeItemConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}]},{"value":"barcodeItemConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1barcodeItemConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"barcodeItemConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1barcodeItemConfiguration\/fragments"},{"op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"op":"replace"}]}]}