{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration(py)barcodeItemInfoPosition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"barcodeItemInfoPosition","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarcodeItemInfoPosition","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","title":"barcodeItemInfoPosition","navigatorTitle":[{"text":"barcodeItemInfoPosition","kind":"identifier"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Where to display the barcode info box in the camera preview."},{"type":"text","text":" "},{"type":"text","text":"Default is BELOW"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeiteminfoposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeiteminfoposition"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"barcodeItemInfoPosition","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarcodeItemInfoPosition","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/barcodeItemInfoPosition"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration/barcodeItemInfoPosition":{"navigatorTitle":[{"kind":"identifier","text":"barcodeItemInfoPosition"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeItemInfoPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition","text":"SBSDKUI2BarcodeItemInfoPosition"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/barcodeiteminfoposition","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/barcodeItemInfoPosition","kind":"symbol","abstract":[{"text":"Where to display the barcode info box in the camera preview.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is BELOW"}],"title":"barcodeItemInfoPosition"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemInfoPosition":{"kind":"symbol","role":"symbol","title":"SBSDKUI2BarcodeItemInfoPosition","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeiteminfoposition","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}],"abstract":[{"type":"text","text":"Where to display the barcode info box in the camera preview."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","navigatorTitle":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"kind":"symbol","role":"symbol","title":"SBSDKUI2ArOverlayGeneralConfiguration","abstract":[{"text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"barcodeItemInfoPosition","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"barcodeItemInfoPosition"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemInfoPosition","kind":"typeIdentifier","text":"SBSDKUI2BarcodeItemInfoPosition","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodeItemInfoPosition"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeItemInfoPosition"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"barcodeItemInfoPosition","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1barcodeItemInfoPosition\/title"},{"value":[{"kind":"identifier","text":"barcodeItemInfoPosition"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1barcodeItemInfoPosition\/fragments"},{"value":"SBSDKUI2BarcodeItemInfoPosition","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemInfoPosition\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title","value":"SBSDKUI2ArOverlayGeneralConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"op":"replace"}]}]}