{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/visible"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/visible"]}],"abstract":[{"type":"text","text":"Control the visibility of the user guidance."},{"type":"text","text":" "},{"text":"Default is false","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/visible"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"visible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]}],"metadata":{"title":"visible","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration(py)visible","symbolKind":"property","navigatorTitle":[{"text":"visible","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration/visible":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Control the visibility of the user guidance."},{"type":"text","text":" "},{"text":"Default is false","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration\/visible","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"visible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"visible","navigatorTitle":[{"text":"visible","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration\/visible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayGeneralConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"title":"SBSDKUI2ArOverlayGeneralConfiguration","abstract":[{"type":"text","text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaygeneralconfiguration","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"visible"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"visible"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"visible","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"visible","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1visible\/title"},{"op":"replace","value":[{"kind":"identifier","text":"visible"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration~1visible\/fragments"},{"op":"replace","value":"SBSDKUI2ArOverlayGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}