{"abstract":[{"text":"The drawing style of the finder view.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/style"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView","text":"SBSDKFinderView","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKFinderView"},{"kind":"text","text":"."},{"preciseIdentifier":"s:24ScanbotBarcodeScannerSDK15SBSDKFinderViewC5StyleO","text":"Style","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/Style-swift.enum","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Defaults to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/Style-swift.enum\/stroke","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/style"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/style"]}],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"style","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKFinderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKFinderView"},{"kind":"text","text":"."},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:24ScanbotBarcodeScannerSDK15SBSDKFinderViewC5StyleO"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBaseScannerViewFinderConfiguration(py)style","navigatorTitle":[{"text":"style","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration":{"abstract":[{"type":"text","text":"The view finder configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"Sometimes it is necessary to limit a live video frame detection or recognition to a certain rectangular area with"},{"text":" ","type":"text"},{"text":"a specific aspect ratio: the region or rectangle of interest. This is where a view finder comes in.","type":"text"},{"text":" ","type":"text"},{"text":"It crops the video frame to that region of interest before passing it to any scanner. Usually","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the performance of scanners gain a benefit from it because less pixels must be processed."},{"text":" ","type":"text"},{"type":"text","text":"Additionally, to guide the user, the view finder visualizes the region of interest by drawing a rectangle around"},{"type":"text","text":" "},{"type":"text","text":"on the user interface."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"title":"SBSDKBaseScannerViewFinderConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"title":"SBSDKFinderView","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderView"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderView"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView/Style-swift.enum/stroke":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"stroke","kind":"identifier"}],"title":"SBSDKFinderView.Style.stroke","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/Style-swift.enum\/stroke","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview\/style-swift.enum\/stroke","abstract":[{"text":"The full line around the finder view.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderViewStyle":{"abstract":[{"text":"The enum that defines the drawing styles of the finder view.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderViewStyle","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderviewstyle","type":"topic","title":"SBSDKFinderViewStyle","kind":"symbol","fragments":[{"text":"SBSDKFinderViewStyle","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFinderView/Style-swift.enum":{"kind":"symbol","abstract":[{"text":"The enum that defines the drawing styles of the finder view.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderView\/Style-swift.enum","title":"SBSDKFinderView.Style","navigatorTitle":[{"text":"Style","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfinderview\/style-swift.enum","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBaseScannerViewFinderConfiguration/style":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBaseScannerViewFinderConfiguration\/style","navigatorTitle":[{"kind":"identifier","text":"style"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:24ScanbotBarcodeScannerSDK15SBSDKFinderViewC5StyleO","text":"Style"}],"kind":"symbol","title":"style","abstract":[{"type":"text","text":"The drawing style of the finder view."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbasescannerviewfinderconfiguration\/style","role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"style","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"style"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKFinderViewStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFinderViewStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFinderViewStyle"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/title","value":"SBSDKBaseScannerViewFinderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerViewFinderConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration\/navigatorTitle"},{"value":"SBSDKFinderView","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/title"},{"value":[{"text":"SBSDKFinderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFinderView\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1style\/title","value":"style","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBaseScannerViewFinderConfiguration~1style\/fragments","value":[{"kind":"identifier","text":"style"}]}]}]}