{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/usacheckaccountnumberfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/usacheckaccountnumberfieldnormalizedname"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelConstants(cpy)usaCheckAccountNumberFieldNormalizedName","navigatorTitle":[{"text":"usaCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"roleHeading":"Type Property","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usaCheckAccountNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"usaCheckAccountNumberFieldNormalizedName","symbolKind":"property","modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants\/usaCheckAccountNumberFieldNormalizedName","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"usaCheckAccountNumberFieldNormalizedName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Normalized full name of the “AccountNumber” field type in document type “USACheck”.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelConstants":{"role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants","title":"SBSDKCheckDocumentModelConstants","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentModelConstants"}],"navigatorTitle":[{"text":"SBSDKCheckDocumentModelConstants","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelConstants/usaCheckAccountNumberFieldNormalizedName":{"abstract":[{"text":"Normalized full name of the “AccountNumber” field type in document type “USACheck”.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelconstants\/usacheckaccountnumberfieldnormalizedname","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelConstants\/usaCheckAccountNumberFieldNormalizedName","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"usaCheckAccountNumberFieldNormalizedName"}],"title":"usaCheckAccountNumberFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usaCheckAccountNumberFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"usaCheckAccountNumberFieldNormalizedName","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"usaCheckAccountNumberFieldNormalizedName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"usaCheckAccountNumberFieldNormalizedName","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/title","op":"replace","value":"SBSDKCheckDocumentModelConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckDocumentModelConstants"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKCheckDocumentModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants~1usaCheckAccountNumberFieldNormalizedName\/title","value":"usaCheckAccountNumberFieldNormalizedName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelConstants~1usaCheckAccountNumberFieldNormalizedName\/fragments","value":[{"text":"usaCheckAccountNumberFieldNormalizedName","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}