{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptionFreeText"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplansubheadingprescriptionfieldtype\/prescriptionfreetext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplansubheadingprescriptionfieldtype\/prescriptionfreetext"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType\/prescriptionFreeText","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Prescription free text"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptionFreeText"}],"title":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType.prescriptionFreeText","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType@SBSDKUI2MedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType":{"role":"symbol","title":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType"}],"abstract":[{"type":"text","text":"Medical Plan Subheading Prescription Field Type."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplansubheadingprescriptionfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType/prescriptionFreeText":{"role":"symbol","title":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType.prescriptionFreeText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"prescriptionFreeText"}],"abstract":[{"type":"text","text":"Prescription free text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType\/prescriptionFreeText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplansubheadingprescriptionfieldtype\/prescriptionfreetext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType\/title","value":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType~1prescriptionFreeText\/title","value":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanSubheadingPrescriptionFieldType~1prescriptionFreeText\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanSubheadingPrescriptionFieldTypePrescriptionFreeText"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}