{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition\/disabled","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Don’t display any barcode info."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition"]]},"metadata":{"title":"SBSDKUI2BarcodeItemInfoPosition.disabled","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BarcodeItemInfoPosition@SBSDKUI2BarcodeItemInfoPositionDisabled","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionDisabled"}],"role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeiteminfoposition\/disabled"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeiteminfoposition\/disabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemInfoPosition/disabled":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeiteminfoposition\/disabled","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"disabled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition\/disabled","title":"SBSDKUI2BarcodeItemInfoPosition.disabled","type":"topic","abstract":[{"type":"text","text":"Don’t display any barcode info."}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeItemInfoPositionDisabled","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemInfoPosition":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemInfoPosition","title":"SBSDKUI2BarcodeItemInfoPosition","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Where to display the barcode info box in the camera preview."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeiteminfoposition","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPosition"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2BarcodeItemInfoPositionDisabled"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionDisabled"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKUI2BarcodeItemInfoPositionDisabled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemInfoPosition~1disabled\/title","value":"SBSDKUI2BarcodeItemInfoPositionDisabled"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemInfoPositionDisabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemInfoPosition~1disabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemInfoPosition\/title","value":"SBSDKUI2BarcodeItemInfoPosition"},{"value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemInfoPosition\/fragments"},{"value":[{"text":"SBSDKUI2BarcodeItemInfoPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemInfoPosition\/navigatorTitle"}]}]}