{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"notifyPropertiesChange","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerZoomConfiguration(im)notifyPropertiesChange","title":"notifyPropertiesChange()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyPropertiesChange"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration\/notifyPropertiesChange()"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration"]]},"abstract":[{"text":"Notifies that properties have changed by incrementing the update counter.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/notifypropertieschange()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/notifypropertieschange()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerZoomConfiguration/notifyPropertiesChange()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyPropertiesChange"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration\/notifyPropertiesChange()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration\/notifypropertieschange()","abstract":[{"type":"text","text":"Notifies that properties have changed by incrementing the update counter."}],"title":"notifyPropertiesChange()","navigatorTitle":[{"kind":"identifier","text":"notifyPropertiesChange"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerZoomConfiguration":{"navigatorTitle":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The zoom configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses allow the user to zoom the camera."},{"type":"text","text":" "},{"type":"text","text":"This class lets you customize the zooming user experience."}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerzoomconfiguration","title":"SBSDKBaseScannerZoomConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerZoomConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"notifyPropertiesChange","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"notifyPropertiesChange"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration~1notifyPropertiesChange()\/title","value":"notifyPropertiesChange","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration~1notifyPropertiesChange()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"notifyPropertiesChange","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/title","value":"SBSDKBaseScannerZoomConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/fragments","value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerZoomConfiguration\/navigatorTitle","value":[{"text":"SBSDKBaseScannerZoomConfiguration","kind":"identifier"}],"op":"replace"}]}]}