{"metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.confirmed","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"confirmed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/confirmed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/confirmed"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"confirmed","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/confirmed","interfaceLanguage":"swift"},"abstract":[{"text":"Field is valid and confirmed across multiple frames.","type":"text"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus":{"type":"topic","kind":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus","role":"symbol","abstract":[{"text":"Health insurance card field validation status.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus/confirmed":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/confirmed","abstract":[{"text":"Field is valid and confirmed across multiple frames.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldvalidationstatus\/confirmed","kind":"symbol","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus.confirmed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"confirmed","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus\/navigatorTitle","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1confirmed\/title","op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatus~1confirmed\/fragments","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldValidationStatusConfirmed","kind":"identifier"}]}]}]}