{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconstyle\/initwithvisible:color:"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconStyle\/initWithVisible:color:","interfaceLanguage":"occ"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithVisible:color:"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2IconStyle(im)initWithVisible:color:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithVisible:color:","kind":"identifier"}],"role":"symbol","symbolKind":"method","title":"initWithVisible:color:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"visible"},{"kind":"text","text":" "},{"kind":"identifier","text":"color:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"color"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"abstract":[],"type":"topic","title":"SBSDKUI2Color"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconStyle/initWithVisible:color:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconstyle\/initwithvisible:color:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithVisible:color:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisible:color:"}],"title":"initWithVisible:color:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconStyle\/initWithVisible:color:","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IconStyle":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"title":"SBSDKUI2IconStyle","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2iconstyle","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IconStyle","abstract":[{"type":"text","text":"Configuration of the icon appearance."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle"},{"value":"SBSDKUI2IconStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/title"},{"value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/fragments"},{"value":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IconStyle\/navigatorTitle"}]}]}