{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultLicenseFailureHandler()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbot\/defaultlicensefailurehandler()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/scanbot\/defaultlicensefailurehandler()"]}],"abstract":[{"type":"text","text":"The default license failure handler."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultLicenseFailureHandler"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKLicenseFailureHandler","preciseIdentifier":"s:10ScanbotSDK26SBSDKLicenseFailureHandlera","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseFailureHandler"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The default license failure handler.","type":"text"}]}]}],"metadata":{"roleHeading":"Type Method","title":"defaultLicenseFailureHandler()","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultLicenseFailureHandler"},{"kind":"text","text":"() -> "},{"text":"SBSDKLicenseFailureHandler","preciseIdentifier":"s:10ScanbotSDK26SBSDKLicenseFailureHandlera","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"defaultLicenseFailureHandler","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)Scanbot(cm)defaultLicenseFailureHandler","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/defaultLicenseFailureHandler()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultLicenseFailureHandler()","navigatorTitle":[{"text":"defaultLicenseFailureHandler","kind":"identifier"}],"abstract":[{"text":"The default license failure handler.","type":"text"}],"url":"\/documentation\/scanbotsdk\/scanbot\/defaultlicensefailurehandler()","kind":"symbol","title":"defaultLicenseFailureHandler()","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:10ScanbotSDK26SBSDKLicenseFailureHandlera","text":"SBSDKLicenseFailureHandler","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot","navigatorTitle":[{"text":"Scanbot","kind":"identifier"}],"abstract":[{"type":"text","text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration."}],"url":"\/documentation\/scanbotsdk\/scanbot","kind":"symbol","title":"Scanbot","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Scanbot","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseFailureHandler":{"abstract":[{"type":"text","text":"Typealias for license failure handling closure."}],"url":"\/documentation\/scanbotsdk\/sbsdklicensefailurehandler","title":"SBSDKLicenseFailureHandler","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseFailureHandler","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKLicenseFailureHandler"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseFailureHandler"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"defaultLicenseFailureHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#$@M@ScanbotSDK@E@SBSDKLicenseStatus#$@M@ScanbotSDK@E@SBSDKFeature#*$objc(cs)NSString)","text":"void (^)(enum SBSDKLicenseStatus, enum SBSDKFeature, NSString *)"},{"text":") ","kind":"text"},{"text":"defaultLicenseFailureHandler","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"defaultLicenseFailureHandler","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultLicenseFailureHandler()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultLicenseFailureHandler()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"defaultLicenseFailureHandler","kind":"identifier"}]},{"value":"Scanbot","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/fragments","value":[{"kind":"identifier","text":"Scanbot"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}