{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicenseLoggingEnabled(_:)"},"metadata":{"symbolKind":"method","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLicenseLoggingEnabled"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotSDK@objc(cs)Scanbot(cm)setLicenseLoggingEnabled:","role":"symbol","title":"setLicenseLoggingEnabled(_:)","navigatorTitle":[{"kind":"identifier","text":"setLicenseLoggingEnabled:"}],"modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLicenseLoggingEnabled"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"enabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"type":"text","text":", if Scanbot SDK should log the license, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}]}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"By default license logging is on.","type":"text"}]}]}],"abstract":[{"text":"Enables or disables the Scanbot SDK license logging.","type":"text"},{"type":"text","text":" "},{"text":"If enabled Scanbot SDK logs information about the license to the console.","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/scanbot\/setlicenseloggingenabled(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/scanbot\/setlicenseloggingenabled(_:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Scanbot","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/scanbot","abstract":[{"text":"Main class of Scanbot SDK. Lets you install the license and allows basic configuration.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Scanbot","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot","role":"symbol","type":"topic","title":"Scanbot"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/setLicenseLoggingEnabled(_:)":{"abstract":[{"type":"text","text":"Enables or disables the Scanbot SDK license logging."},{"type":"text","text":" "},{"type":"text","text":"If enabled Scanbot SDK logs information about the license to the console."}],"kind":"symbol","title":"setLicenseLoggingEnabled(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setLicenseLoggingEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLicenseLoggingEnabled:"}],"url":"\/documentation\/scanbotsdk\/scanbot\/setlicenseloggingenabled(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/setLicenseLoggingEnabled(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"setLicenseLoggingEnabled:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setLicenseLoggingEnabled:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setLicenseLoggingEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"enabled"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"True"},{"type":"text","text":", if Scanbot SDK should log the license, "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"name":"enabled"}],"kind":"parameters"}},{"value":"Scanbot","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/fragments","value":[{"text":"Scanbot","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot\/navigatorTitle","value":[{"text":"Scanbot","kind":"identifier"}]},{"value":"setLicenseLoggingEnabled:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLicenseLoggingEnabled(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLicenseLoggingEnabled:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1setLicenseLoggingEnabled(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}