{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat"]]},"abstract":[{"type":"text","text":"Shows the barcode value only."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat\/code","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat\/code"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat\/code"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeDialogFormat@SBSDKBarcodeDialogFormatCode","symbolKind":"case","roleHeading":"Case","title":"SBSDKBarcodeDialogFormat.code","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKBarcodeDialogFormatCode","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDialogFormat/code":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat\/code","title":"SBSDKBarcodeDialogFormat.code","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat\/code","abstract":[{"type":"text","text":"Shows the barcode value only."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDialogFormatCode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDialogFormat":{"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeDialogFormat","kind":"identifier"}],"title":"SBSDKBarcodeDialogFormat","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDialogFormat"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDialogFormat","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedialogformat","abstract":[{"type":"text","text":"The barcode dialog text format."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeDialogFormatCode"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDialogFormatCode"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKBarcodeDialogFormatCode","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat~1code\/title","value":"SBSDKBarcodeDialogFormatCode","op":"replace"},{"value":[{"text":"SBSDKBarcodeDialogFormatCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat~1code\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat\/title","op":"replace","value":"SBSDKBarcodeDialogFormat"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDialogFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat\/fragments"},{"value":[{"text":"SBSDKBarcodeDialogFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDialogFormat\/navigatorTitle","op":"replace"}]}]}