{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration"]]},"metadata":{"roleHeading":"Instance Property","title":"titleSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"titleSelected","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}],"navigatorTitle":[{"kind":"identifier","text":"titleSelected"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration(py)titleSelected","modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration\/titleSelected"},"abstract":[{"type":"text","text":"Configuration of the text displaying a barcode’s value in the info box when the barcode has been selected."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleSelected"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration\/titleselected"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration\/titleselected"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemConfiguration/titleSelected":{"abstract":[{"text":"Configuration of the text displaying a barcode’s value in the info box when the barcode has been selected.","type":"text"}],"title":"titleSelected","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration\/titleselected","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleSelected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"titleSelected","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration\/titleSelected","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"title":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration","title":"SBSDKUI2BarcodeItemConfiguration","abstract":[{"text":"Configuration of the barcode info box displayed in the camera preview.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"titleSelected","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"titleSelected"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" * ","kind":"text"},{"text":"titleSelected","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration~1titleSelected\/title","value":"titleSelected","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration~1titleSelected\/fragments","value":[{"text":"titleSelected","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/title","op":"replace","value":"SBSDKUI2BarcodeItemConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}