{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagefit\/fillin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagefit\/fillin"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/fillIn","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"SBSDKPageFitFillIn","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKPageFit.fillIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillIn"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKPageFit@SBSDKPageFitFillIn","roleHeading":"Case"},"abstract":[{"text":"Fill page with image. Will crop the image if the aspect ratio","type":"text"},{"text":" ","type":"text"},{"text":"of the image and the page don’t match. Preserves image aspect ratio.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit/fillIn":{"kind":"symbol","abstract":[{"text":"Fill page with image. Will crop the image if the aspect ratio","type":"text"},{"text":" ","type":"text"},{"text":"of the image and the page don’t match. Preserves image aspect ratio.","type":"text"}],"title":"SBSDKPageFit.fillIn","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit\/fillIn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPageFitFillIn","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagefit\/fillin","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageFit":{"abstract":[{"type":"text","text":"Page fit."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageFit","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPageFit","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageFit","title":"SBSDKPageFit","url":"\/documentation\/scanbotsdk\/sbsdkpagefit","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKPageFitFillIn","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKPageFitFillIn"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKPageFitFillIn"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKPageFitFillIn","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit~1fillIn\/title"},{"value":[{"kind":"identifier","text":"SBSDKPageFitFillIn"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit~1fillIn\/fragments"},{"value":"SBSDKPageFit","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/title"},{"value":[{"kind":"identifier","text":"SBSDKPageFit"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/fragments"},{"value":[{"text":"SBSDKPageFit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageFit\/navigatorTitle"}]}]}