{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/minimumnumberofrequiredframeswithequalscanningresult"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Minimum number of accumulated frames that have an equal result in order for the result to be considered"},{"type":"text","text":" "},{"type":"text","text":"verified."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"Default is 2","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"minimumNumberOfRequiredFramesWithEqualScanningResult","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAccumulatedResultsVerifierConfiguration(py)minimumNumberOfRequiredFramesWithEqualScanningResult","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration":{"role":"symbol","navigatorTitle":[{"text":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKAccumulatedResultsVerifierConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration","title":"SBSDKAccumulatedResultsVerifierConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration","type":"topic","abstract":[{"type":"text","text":"Configure the frame accumulation process."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration/minimumNumberOfRequiredFramesWithEqualScanningResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration\/minimumNumberOfRequiredFramesWithEqualScanningResult","url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/minimumnumberofrequiredframeswithequalscanningresult","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Minimum number of accumulated frames that have an equal result in order for the result to be considered"},{"text":" ","type":"text"},{"type":"text","text":"verified."}],"title":"minimumNumberOfRequiredFramesWithEqualScanningResult","navigatorTitle":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"minimumNumberOfRequiredFramesWithEqualScanningResult","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SBSDKAccumulatedResultsVerifierConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/title","value":"minimumNumberOfRequiredFramesWithEqualScanningResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration~1minimumNumberOfRequiredFramesWithEqualScanningResult\/fragments","value":[{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualScanningResult"}]}]}]}