{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/requirednumberofequalaccumulatedresults"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/requirednumberofequalaccumulatedresults"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This sets the first part of the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/requiredNumberOfEqualAccumulatedResults"},{"type":"text","text":" of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/maxNumberOfAccumulatedResults"},{"type":"text","text":" selector,"},{"type":"text","text":" "},{"type":"text","text":"e.g. 2 of 4 results must be equal."},{"type":"text","text":" "},{"type":"text","text":"To get fewer false positive results, make the selector more strict by selecting a higher value, e.g. 3 of 4 or even 4 of 4."},{"type":"text","text":" "},{"type":"text","text":"Setting a value higher than "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/maxNumberOfAccumulatedResults"},{"type":"text","text":" will throw an exception."},{"type":"text","text":" "},{"type":"text","text":"Values less-than-or-equal to 0, will effectively turn off the result accumulation."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to 2."}]}],"kind":"content"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"requiredNumberOfEqualAccumulatedResults","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMachineReadableZoneRecognizer(py)requiredNumberOfEqualAccumulatedResults"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/requiredNumberOfEqualAccumulatedResults","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizer/maxNumberOfAccumulatedResults":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The maximum number of results to be accumulated when live-recognizing machine-readable zones on sample buffers."}],"navigatorTitle":[{"kind":"identifier","text":"maxNumberOfAccumulatedResults"}],"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/maxnumberofaccumulatedresults","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxNumberOfAccumulatedResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/maxNumberOfAccumulatedResults","title":"maxNumberOfAccumulatedResults"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizer":{"url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer","kind":"symbol","title":"SBSDKMachineReadableZoneRecognizer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizer"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMachineReadableZoneRecognizer"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer","abstract":[{"type":"text","text":"A class to recognize machine-readable zones in a "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"CMSampleBuffer","type":"codeVoice"},{"type":"text","text":"."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMachineReadableZoneRecognizer/requiredNumberOfEqualAccumulatedResults":{"title":"requiredNumberOfEqualAccumulatedResults","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmachinereadablezonerecognizer\/requirednumberofequalaccumulatedresults","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMachineReadableZoneRecognizer\/requiredNumberOfEqualAccumulatedResults","navigatorTitle":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"abstract":[{"text":"The minimum number of equal results in the accumulator when live-recognizing machine-readable zones on sample buffers.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"requiredNumberOfEqualAccumulatedResults","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredNumberOfEqualAccumulatedResults"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"maxNumberOfAccumulatedResults","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1maxNumberOfAccumulatedResults\/title","op":"replace"},{"value":[{"text":"maxNumberOfAccumulatedResults","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1maxNumberOfAccumulatedResults\/fragments","op":"replace"},{"value":"SBSDKMachineReadableZoneRecognizer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer\/title","op":"replace"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer\/fragments","op":"replace"},{"value":[{"text":"SBSDKMachineReadableZoneRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer\/navigatorTitle","op":"replace"},{"value":"requiredNumberOfEqualAccumulatedResults","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1requiredNumberOfEqualAccumulatedResults\/title","op":"replace"},{"value":[{"text":"requiredNumberOfEqualAccumulatedResults","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMachineReadableZoneRecognizer~1requiredNumberOfEqualAccumulatedResults\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}