{"metadata":{"role":"symbol","platforms":[],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerUIConfiguration(py)cameraOverlayColor","title":"cameraOverlayColor","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraOverlayColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"cameraOverlayColor","kind":"identifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/cameraoverlaycolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/cameraoverlaycolor"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/cameraOverlayColor","interfaceLanguage":"swift"},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cameraOverlayColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Background color of the scanner overlay.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerUIConfiguration":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscanneruiconfiguration","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"abstract":[{"text":"The configuration for user interface of the RTU-UI batch barcode scanner.","type":"text"}],"type":"topic","title":"SBSDKUIBarcodesBatchScannerUIConfiguration","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/cameraOverlayColor":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cameraOverlayColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/cameraOverlayColor","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/cameraoverlaycolor","type":"topic","title":"cameraOverlayColor","deprecated":true,"abstract":[{"text":"Background color of the scanner overlay.","type":"text"}],"navigatorTitle":[{"text":"cameraOverlayColor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"cameraOverlayColor","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cameraOverlayColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cameraOverlayColor"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/title","value":"SBSDKUIBarcodesBatchScannerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1cameraOverlayColor\/title","value":"cameraOverlayColor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1cameraOverlayColor\/fragments","op":"replace","value":[{"text":"cameraOverlayColor","kind":"identifier"}]}]}]}