{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsManager"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"subscriber"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","kind":"typeIdentifier","text":"SBSDKAnalyticsSubscriber","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsSubscriber"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsmanager\/subscribe(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsmanager\/subscribe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsManager\/subscribe(_:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscribe","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"subscribe:","kind":"identifier"}],"roleHeading":"Instance Method","title":"subscribe(_:)","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsManager(im)subscribe:","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"sections":[],"abstract":[{"type":"text","text":"Subscribes a subscriber to receive analytics events."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsSubscriber":{"title":"SBSDKAnalyticsSubscriber","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsSubscriber","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticssubscriber","kind":"symbol","abstract":[{"text":"The subscriber that is being tracked.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsManager/subscribe(_:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsManager\/subscribe(_:)","navigatorTitle":[{"text":"subscribe:","kind":"identifier"}],"title":"subscribe(_:)","type":"topic","abstract":[{"text":"Subscribes a subscriber to receive analytics events.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscribe","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsmanager\/subscribe(_:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsManager":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"title":"SBSDKAnalyticsManager","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsmanager","abstract":[{"type":"codeVoice","code":"SBSDKAnalyticsManager"},{"type":"text","text":" is a singleton class that manages analytics events within the Scanbot SDK."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsManager","navigatorTitle":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"subscribe:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscribe:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"subscribe:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"id<SBSDKAnalyticsSubscriber>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"subscriber"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKAnalyticsSubscriber","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsSubscriber\/title","op":"replace"},{"value":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsSubscriber\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsSubscriber\/navigatorTitle","op":"replace"},{"value":"subscribe:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager~1subscribe(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"subscribe:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager~1subscribe(_:)\/fragments","op":"replace"},{"value":"SBSDKAnalyticsManager","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager\/title","op":"replace"},{"value":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAnalyticsManager"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager\/navigatorTitle","op":"replace"}]}]}