{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageImageSource\/imported"},"sections":[],"abstract":[{"text":"The image originates from the photo\/media gallery.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imported"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"imported","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"SBSDKPageImageSource.imported","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKPageImageSource@SBSDKPageImageSourceImported","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageImageSourceImported"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpageimagesource\/imported"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpageimagesource\/imported"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageImageSource"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPageImageSource":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpageimagesource","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKPageImageSource","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageImageSource","abstract":[{"type":"text","text":"The source of an image."}],"title":"SBSDKPageImageSource","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageImageSource"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPageImageSource/imported":{"abstract":[{"text":"The image originates from the photo\/media gallery.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpageimagesource\/imported","title":"SBSDKPageImageSource.imported","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPageImageSource\/imported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imported","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageImageSourceImported"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPageImageSourceImported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKPageImageSourceImported"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKPageImageSourceImported","kind":"identifier"}]}]},"op":"replace"},{"value":"SBSDKPageImageSource","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageImageSource\/title"},{"op":"replace","value":[{"text":"SBSDKPageImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageImageSource\/fragments"},{"value":[{"text":"SBSDKPageImageSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageImageSource\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageImageSource~1imported\/title","value":"SBSDKPageImageSourceImported","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPageImageSourceImported"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPageImageSource~1imported\/fragments","op":"replace"}]}]}