{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/init(keyGenerator:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/init(keygenerator:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/init(keygenerator:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyGenerator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingKeyGenerator","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyGenerator"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"keyGenerator","content":[{"inlineContent":[{"text":"The key generator used to create new encryption keys.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"text":"Designated initializer.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithKeyGenerator:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKVolatileKeyProvider(im)initWithKeyGenerator:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyGenerator","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","text":"SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(keyGenerator:)","modules":[{"name":"ScanbotSDK"}],"symbolKind":"init"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider":{"role":"symbol","navigatorTitle":[{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVolatileKeyProvider","kind":"identifier"}],"title":"SBSDKVolatileKeyProvider","url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider","abstract":[{"type":"text","text":"A volatile key provider that generates and stores keys in memory."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVolatileKeyProvider/init(keyGenerator:)":{"type":"topic","title":"init(keyGenerator:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVolatileKeyProvider\/init(keyGenerator:)","url":"\/documentation\/scanbotsdk\/sbsdkvolatilekeyprovider\/init(keygenerator:)","role":"symbol","navigatorTitle":[{"text":"initWithKeyGenerator:","kind":"identifier"}],"abstract":[{"text":"Designated initializer.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyGenerator","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","text":"SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCryptingKeyGenerator":{"abstract":[{"type":"text","text":"Protocol for generating encryption keys."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCryptingKeyGenerator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"title":"SBSDKStorageCryptingKeyGenerator","navigatorTitle":[{"text":"SBSDKStorageCryptingKeyGenerator","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecryptingkeygenerator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithKeyGenerator:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithKeyGenerator:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithKeyGenerator:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingKeyGenerator","kind":"typeIdentifier","text":"id<SBSDKStorageCryptingKeyGenerator>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"keyGenerator"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"keyGenerator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key generator used to create new encryption keys."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKVolatileKeyProvider","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVolatileKeyProvider"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider\/navigatorTitle"},{"op":"replace","value":"initWithKeyGenerator:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1init(keyGenerator:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyGenerator:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVolatileKeyProvider~1init(keyGenerator:)\/fragments"},{"op":"replace","value":"SBSDKStorageCryptingKeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyGenerator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyGenerator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCryptingKeyGenerator"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCryptingKeyGenerator\/navigatorTitle"}]}]}