{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"API Collection","role":"collectionGroup","title":"UIScrollViewDelegate Implementations"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/scrollViewDidEndZooming(_:with:atScale:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/scrollViewDidZoom(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/viewForZooming(in:)"],"anchor":"Instance-Methods"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkzoomingimagescrollview\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkzoomingimagescrollview\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKZoomingImageScrollView/scrollViewDidEndZooming(_:with:atScale:)":{"navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}],"kind":"symbol","type":"topic","title":"scrollViewDidEndZooming(_:with:atScale:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/scrollViewDidEndZooming(_:with:atScale:)","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkzoomingimagescrollview\/scrollviewdidendzooming(_:with:atscale:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidEndZooming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"atScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKZoomingImageScrollView/viewForZooming(in:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/viewForZooming(in:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkzoomingimagescrollview\/viewforzooming(in:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForZooming"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"kind":"symbol","title":"viewForZooming(in:)","navigatorTitle":[{"kind":"identifier","text":"viewForZoomingInScrollView:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKZoomingImageScrollView":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkzoomingimagescrollview","type":"topic","title":"SBSDKZoomingImageScrollView","abstract":[{"text":"A scrollable and zoomable ","type":"text"},{"code":"UIScrollView","type":"codeVoice"},{"text":" subclass that displays images and an overlay view.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKZoomingImageScrollView/scrollViewDidZoom(_:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/scrollViewDidZoom(_:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkzoomingimagescrollview\/scrollviewdidzoom(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollViewDidZoom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"kind":"symbol","title":"scrollViewDidZoom(_:)","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidZoom:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/scrollViewDidEndZooming(_:with:atScale:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/scrollViewDidZoom(_:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKZoomingImageScrollView\/viewForZooming(in:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"scrollViewDidEndZooming:withView:atScale:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView~1scrollViewDidEndZooming(_:with:atScale:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidEndZooming:withView:atScale:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView~1scrollViewDidEndZooming(_:with:atScale:)\/fragments","op":"replace"},{"value":"viewForZoomingInScrollView:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView~1viewForZooming(in:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewForZoomingInScrollView:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView~1viewForZooming(in:)\/fragments","op":"replace"},{"value":"SBSDKZoomingImageScrollView","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView\/title","op":"replace"},{"value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView\/fragments","op":"replace"},{"value":[{"text":"SBSDKZoomingImageScrollView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView\/navigatorTitle","op":"replace"},{"value":"scrollViewDidZoom:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView~1scrollViewDidZoom(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollViewDidZoom:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKZoomingImageScrollView~1scrollViewDidZoom(_:)\/fragments","op":"replace"}]}]}