{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration\/finderLineWidth","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderLineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/finderlinewidth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/finderlinewidth"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"finderLineWidth","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerUIConfiguration(py)finderLineWidth","symbolKind":"property","title":"finderLineWidth","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderLineWidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Width of finder frame border.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerUIConfiguration/finderLineWidth":{"type":"topic","role":"symbol","kind":"symbol","title":"finderLineWidth","abstract":[{"type":"text","text":"Width of finder frame border."}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/finderlinewidth","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration\/finderLineWidth","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderLineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"text":"finderLineWidth","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerUIConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration"}],"kind":"symbol","title":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for user interface of the detector RTU-UI screen for Health Insurance Card scanner."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"finderLineWidth","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"finderLineWidth","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":" "},{"text":"finderLineWidth","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration~1finderLineWidth\/title","value":"finderLineWidth","op":"replace"},{"op":"replace","value":[{"text":"finderLineWidth","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration~1finderLineWidth\/fragments"},{"value":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}