{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration\/orientationLockMode"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/orientationlockmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/orientationlockmode"]}],"kind":"symbol","abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerUIConfiguration(py)orientationLockMode","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationLockMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKOrientationLock","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"}],"title":"orientationLockMode","navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","text":"SBSDKOrientationLock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOrientationLock":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkorientationlock","abstract":[{"text":"This enum describes the available orientation lock modes for the user interface.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKOrientationLock","kind":"identifier"}],"title":"SBSDKOrientationLock","navigatorTitle":[{"text":"SBSDKOrientationLock","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerUIConfiguration/orientationLockMode":{"navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"}],"kind":"symbol","title":"orientationLockMode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration\/orientationLockMode","abstract":[{"text":"Allowed orientations for automatic interface rotations.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/orientationlockmode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerUIConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration"}],"kind":"symbol","title":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for user interface of the detector RTU-UI screen for Health Insurance Card scanner."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"orientationLockMode","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"orientationLockMode"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKOrientationLock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientationLockMode"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/title","value":"SBSDKOrientationLock"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/fragments","value":[{"text":"SBSDKOrientationLock","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/navigatorTitle"},{"op":"replace","value":"orientationLockMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration~1orientationLockMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration~1orientationLockMode\/fragments","value":[{"text":"orientationLockMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration\/title","value":"SBSDKUIHealthInsuranceCardScannerUIConfiguration"},{"value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","kind":"identifier"}],"op":"replace"}]}]}