{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topBarButtonsColor"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topBarButtonsColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"topBarButtonsColor","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardScannerUIConfiguration(py)topBarButtonsColor","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration\/topBarButtonsColor"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Foreground color of the cancel button and when flash button is on."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarButtonsColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/topbarbuttonscolor"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/topbarbuttonscolor"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerUIConfiguration/topBarButtonsColor":{"kind":"symbol","title":"topBarButtonsColor","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration\/topBarButtonsColor","abstract":[{"type":"text","text":"Foreground color of the cancel button and when flash button is on."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"topBarButtonsColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"topBarButtonsColor"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration\/topbarbuttonscolor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardScannerUIConfiguration":{"abstract":[{"type":"text","text":"Configuration for user interface of the detector RTU-UI screen for Health Insurance Card scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","kind":"identifier"}],"title":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardscanneruiconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardScannerUIConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"topBarButtonsColor"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"topBarButtonsColor"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topBarButtonsColor"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"topBarButtonsColor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration~1topBarButtonsColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration~1topBarButtonsColor\/fragments","value":[{"kind":"identifier","text":"topBarButtonsColor"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration\/title","value":"SBSDKUIHealthInsuranceCardScannerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardScannerUIConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIHealthInsuranceCardScannerUIConfiguration","kind":"identifier"}]}]}]}