{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration(im)initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}],"title":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTopBarTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumQuality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQuality","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQuality","text":"SBSDKDocumentQuality"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"minimumQuality"},{"kind":"text","text":" "},{"kind":"identifier","text":"acknowledgementMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2AcknowledgementMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementMode","text":"SBSDKUI2AcknowledgementMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"acknowledgementMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"badImageHint:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2IconUserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration","text":"SBSDKUI2IconUserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"badImageHint"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomBar:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementBottomBar","text":"SBSDKUI2AcknowledgementBottomBar"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bottomBar"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration\/initwithtopbartitle:minimumquality:acknowledgementmode:badimagehint:backgroundcolor:bottombar:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementScreenConfiguration/initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:":{"navigatorTitle":[{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","kind":"identifier"}],"kind":"symbol","title":"initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration\/initwithtopbartitle:minimumquality:acknowledgementmode:badimagehint:backgroundcolor:bottombar:","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/initWithTopBarTitle:minimumQuality:acknowledgementMode:badImageHint:backgroundColor:bottomBar:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementScreenConfiguration":{"title":"SBSDKUI2AcknowledgementScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementScreenConfiguration","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementscreenconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementScreenConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the acknowledgement screen."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"title":"SBSDKUI2StyledText","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2IconUserGuidanceConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"title":"SBSDKUI2IconUserGuidanceConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IconUserGuidanceConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the hint (containing an icon) guiding users through the scanning process."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2IconUserGuidanceConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2iconuserguidanceconfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","title":"SBSDKUI2Color","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQuality":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentquality","kind":"symbol","title":"SBSDKDocumentQuality","abstract":[{"text":"Result of document quality analysis.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQuality","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQuality","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementBottomBar":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"title":"SBSDKUI2AcknowledgementBottomBar","role":"symbol","abstract":[{"type":"text","text":"Configuration of the bottom bar for the acknowledgement screen."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementBottomBar","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementbottombar"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2AcknowledgementMode":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"title":"SBSDKUI2AcknowledgementMode","abstract":[{"text":"Determines, after each page is snapped, whether the acknowledgment screen should be displayed or not.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2AcknowledgementMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2acknowledgementmode","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2AcknowledgementScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2IconUserGuidanceConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2IconUserGuidanceConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2IconUserGuidanceConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle"},{"value":"SBSDKDocumentQuality","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQuality\/title"},{"value":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQuality\/fragments"},{"value":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQuality\/navigatorTitle"},{"value":"SBSDKUI2AcknowledgementBottomBar","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/title"},{"value":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/fragments"},{"value":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementBottomBar\/navigatorTitle"},{"value":"SBSDKUI2AcknowledgementMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementMode\/title"},{"value":[{"text":"SBSDKUI2AcknowledgementMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2AcknowledgementMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}