{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collapsedSheet","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2SheetModeCollapsedSheet","kind":"identifier"}],"title":"SBSDKUI2SheetMode.collapsedSheet","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2SheetMode@SBSDKUI2SheetModeCollapsedSheet","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case"},"abstract":[{"text":"Result sheet is visible and collapsed and can be expanded by dragging it up.","type":"text"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode\/collapsedSheet"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheetmode\/collapsedsheet"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2sheetmode\/collapsedsheet"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collapsedSheet","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode","url":"\/documentation\/scanbotsdk\/sbsdkui2sheetmode","title":"SBSDKUI2SheetMode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SheetMode"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the barcode result sheet’s default visibility state."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2SheetMode/collapsedSheet":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2SheetModeCollapsedSheet","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2SheetMode\/collapsedSheet","type":"topic","abstract":[{"type":"text","text":"Result sheet is visible and collapsed and can be expanded by dragging it up."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2sheetmode\/collapsedsheet","title":"SBSDKUI2SheetMode.collapsedSheet","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collapsedSheet","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2SheetModeCollapsedSheet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SheetModeCollapsedSheet"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKUI2SheetModeCollapsedSheet","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/title","value":"SBSDKUI2SheetMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SheetMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode\/navigatorTitle","value":[{"text":"SBSDKUI2SheetMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode~1collapsedSheet\/title","value":"SBSDKUI2SheetModeCollapsedSheet"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2SheetMode~1collapsedSheet\/fragments","value":[{"text":"SBSDKUI2SheetModeCollapsedSheet","kind":"identifier"}]}]}]}