{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType","text":"SBSDKBarcodeType"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodetypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodetypes"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodeTypes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"List of accepted barcode types."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"barcodeTypes"}],"role":"symbol","title":"barcodeTypes","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType"},{"kind":"text","text":"]"}],"symbolKind":"property","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(py)barcodeTypes","extendedModule":"ScanbotSDK","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeType":{"role":"symbol","title":"SBSDKBarcodeType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeType"}],"abstract":[{"type":"text","text":"Class that represents a barcode type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/barcodeTypes":{"role":"symbol","title":"barcodeTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeType"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"List of accepted barcode types."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodeTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"barcodeTypes"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodetypes"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"role":"symbol","title":"SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"barcodeTypes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"barcodeTypes"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBSDKBarcodeType *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"barcodeTypes"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeType\/title","value":"SBSDKBarcodeType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeType\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodeTypes\/title","value":"barcodeTypes"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodeTypes\/fragments","value":[{"kind":"identifier","text":"barcodeTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}