{"abstract":[{"type":"text","text":"List of accepted barcode symbologies."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodeFormats"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodeformats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodeformats"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeFormats"},{"kind":"text","text":": ["},{"text":"SBSDKUI2BarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeFormats"},{"kind":"text","text":": ["},{"text":"SBSDKUI2BarcodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeFormats"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(py)barcodeFormats","title":"barcodeFormats","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/barcodeFormats":{"navigatorTitle":[{"text":"barcodeFormats","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/barcodeformats","abstract":[{"type":"text","text":"List of accepted barcode symbologies."}],"role":"symbol","title":"barcodeFormats","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeFormats"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/barcodeFormats"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration of the scanning behavior.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"title":"SBSDKUI2BarcodeRecognizerConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat":{"title":"SBSDKUI2BarcodeFormat","abstract":[{"type":"text","text":"Barcode symbology used."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"barcodeFormats","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"barcodeFormats"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKUI2BarcodeFormat *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"barcodeFormats"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"barcodeFormats","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodeFormats\/title"},{"value":[{"kind":"identifier","text":"barcodeFormats"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1barcodeFormats\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments"},{"value":"SBSDKUI2BarcodeFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/fragments","value":[{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"op":"replace"}]}]}