{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"acceptedDocumentFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat","text":"SBSDKUI2BarcodeDocumentFormat"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"barcodesExtensionFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter","text":"SBSDKUI2BarcodesExtensionFilter"},{"kind":"text","text":" = SBSDKUI2BarcodesExtensionFilter.noFilter, "},{"kind":"externalParam","text":"barcodesRegexFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"\", "},{"kind":"externalParam","text":"minimumTextLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 0, "},{"kind":"externalParam","text":"maximumTextLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 0, "},{"kind":"externalParam","text":"minimum1DBarcodesQuietZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 10, "},{"kind":"externalParam","text":"stripCheckDigits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"barcodeFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","text":"SBSDKUI2BarcodeFormat"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"kind":"text","text":" = SBSDKUI2MSIPlesseyChecksumAlgorithm\n                    .mod10, "},{"kind":"externalParam","text":"codeDensity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CodeDensity","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CodeDensity","text":"SBSDKUI2CodeDensity"},{"kind":"text","text":" = SBSDKUI2CodeDensity.low, "},{"kind":"externalParam","text":"gs1Handling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling","text":"SBSDKUI2Gs1Handling"},{"kind":"text","text":" = SBSDKUI2Gs1Handling.parse)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:barcodeformats:msiplesseychecksumalgorithm:codedensity:gs1handling:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:barcodeformats:msiplesseychecksumalgorithm:codedensity:gs1handling:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"acceptedDocumentFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"barcodesExtensionFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodesRegexFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumTextLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maximumTextLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimum1DBarcodesQuietZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stripCheckDigits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"codeDensity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CodeDensity","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CodeDensity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gs1Handling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Gs1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling"},{"kind":"text","text":")"}],"title":"init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(im)initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat":{"role":"symbol","title":"SBSDKUI2BarcodeFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"abstract":[{"type":"text","text":"Barcode symbology used."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"role":"symbol","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"abstract":[{"type":"text","text":"Type of MSI plessey checksum algorithm used."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeDocumentFormat":{"role":"symbol","title":"SBSDKUI2BarcodeDocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeDocumentFormat"}],"abstract":[{"type":"text","text":"Type of barcode document format used."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeDocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeDocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodedocumentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CodeDensity":{"role":"symbol","title":"SBSDKUI2CodeDensity","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CodeDensity"}],"abstract":[{"type":"text","text":"Expected quantity of QR codes in an image."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CodeDensity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CodeDensity"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2codedensity"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:)":{"role":"symbol","title":"init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"acceptedDocumentFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"barcodesExtensionFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodesRegexFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumTextLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maximumTextLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimum1DBarcodesQuietZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stripCheckDigits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"codeDensity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2CodeDensity","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CodeDensity"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gs1Handling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Gs1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:barcodeformats:msiplesseychecksumalgorithm:codedensity:gs1handling:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling":{"role":"symbol","title":"SBSDKUI2Gs1Handling","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"role":"symbol","title":"SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodesExtensionFilter":{"role":"symbol","title":"SBSDKUI2BarcodesExtensionFilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"abstract":[{"type":"text","text":"Filter for extended EAN and UPC barcodes."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAcceptedDocumentFormats:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2BarcodeDocumentFormat *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acceptedDocumentFormats"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodesExtensionFilter:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter","text":"SBSDKUI2BarcodesExtensionFilter"},{"kind":"text","text":") "},{"kind":"internalParam","text":"barcodesExtensionFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodesRegexFilter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodesRegexFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTextLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maximumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DBarcodesQuietZone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimum1DBarcodesQuietZone"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripCheckDigits:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"stripCheckDigits"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormats:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2BarcodeFormat *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcodeFormats"},{"kind":"text","text":" "},{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"kind":"text","text":") "},{"kind":"internalParam","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeDensity:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CodeDensity","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2CodeDensity","text":"SBSDKUI2CodeDensity"},{"kind":"text","text":") "},{"kind":"internalParam","text":"codeDensity"},{"kind":"text","text":" "},{"kind":"identifier","text":"gs1Handling:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling","text":"SBSDKUI2Gs1Handling"},{"kind":"text","text":") "},{"kind":"internalParam","text":"gs1Handling"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/title","value":"SBSDKUI2BarcodeFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title","value":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeDocumentFormat\/title","value":"SBSDKUI2BarcodeDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeDocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeDocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CodeDensity\/title","value":"SBSDKUI2CodeDensity"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CodeDensity\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CodeDensity"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:)\/title","value":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:barcodeFormats:msiPlesseyChecksumAlgorithm:codeDensity:gs1Handling:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/title","value":"SBSDKUI2Gs1Handling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/title","value":"SBSDKUI2BarcodesExtensionFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodesExtensionFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}