{"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiplesseychecksumalgorithm:austra-872c0"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiplesseychecksumalgorithm:austra-872c0"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(im)initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"acceptedDocumentFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat","text":"SBSDKUI2BarcodeDocumentFormat"},{"kind":"text","text":"], "},{"text":"barcodesExtensionFilter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodesRegexFilter"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minimumTextLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"maximumTextLength","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minimum1DBarcodesQuietZone"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"stripCheckDigits","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"useIATA2OF5Checksum","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"useCode11Checksum"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"barcodeFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"msiPlesseyChecksumAlgorithm"},{"kind":"text","text":": "},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"australiaPostCustomerFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","text":"SBSDKUI2AustraliaPostCustomerFormat"},{"text":", ","kind":"text"},{"text":"gs1Handling","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling","text":"SBSDKUI2Gs1Handling"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","symbolKind":"init"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"acceptedDocumentFormats"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat","text":"SBSDKUI2BarcodeDocumentFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeDocumentFormat"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"barcodesExtensionFilter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter","text":"SBSDKUI2BarcodesExtensionFilter"},{"text":" = SBSDKUI2BarcodesExtensionFilter.noFilter, ","kind":"text"},{"text":"barcodesRegexFilter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"\", ","kind":"text"},{"text":"minimumTextLength","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 0, ","kind":"text"},{"text":"maximumTextLength","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 0, ","kind":"text"},{"text":"minimum1DBarcodesQuietZone","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":" = 10, "},{"text":"stripCheckDigits","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"useIATA2OF5Checksum","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"useCode11Checksum"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"barcodeFormats"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"msiPlesseyChecksumAlgorithm"},{"text":": ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"kind":"text","text":" = SBSDKUI2MSIPlesseyChecksumAlgorithm\n                    .mod10, "},{"kind":"externalParam","text":"australiaPostCustomerFormat"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","text":"SBSDKUI2AustraliaPostCustomerFormat"},{"kind":"text","text":" = SBSDKUI2AustraliaPostCustomerFormat\n                    .alphaNumeric, "},{"kind":"externalParam","text":"gs1Handling"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Gs1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling"},{"text":" = SBSDKUI2Gs1Handling.parse)","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the scanning behavior."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"title":"SBSDKUI2BarcodeRecognizerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodesExtensionFilter":{"abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"title":"SBSDKUI2BarcodesExtensionFilter","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodesextensionfilter","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MSIPlesseyChecksumAlgorithm":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","type":"topic","title":"SBSDKUI2MSIPlesseyChecksumAlgorithm","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2msiplesseychecksumalgorithm","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"abstract":[{"text":"Type of MSI plessey checksum algorithm used.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Gs1Handling":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","url":"\/documentation\/scanbotsdk\/sbsdkui2gs1handling","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"title":"SBSDKUI2Gs1Handling","abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:"}],"kind":"symbol","abstract":[],"type":"topic","title":"init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)","url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/init(accepteddocumentformats:barcodesextensionfilter:barcodesregexfilter:minimumtextlength:maximumtextlength:minimum1dbarcodesquietzone:stripcheckdigits:useiata2of5checksum:usecode11checksum:barcodeformats:msiplesseychecksumalgorithm:austra-872c0","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"acceptedDocumentFormats","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeDocumentFormat","text":"SBSDKUI2BarcodeDocumentFormat","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"barcodesExtensionFilter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter","text":"SBSDKUI2BarcodesExtensionFilter"},{"kind":"text","text":", "},{"text":"barcodesRegexFilter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"minimumTextLength"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maximumTextLength"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"minimum1DBarcodesQuietZone","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"stripCheckDigits","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"useIATA2OF5Checksum","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useCode11Checksum"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"barcodeFormats","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeFormat","kind":"typeIdentifier","text":"SBSDKUI2BarcodeFormat"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"msiPlesseyChecksumAlgorithm"},{"text":": ","kind":"text"},{"text":"SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"australiaPostCustomerFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","text":"SBSDKUI2AustraliaPostCustomerFormat"},{"text":", ","kind":"text"},{"text":"gs1Handling","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling","text":"SBSDKUI2Gs1Handling","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeFormat":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeformat","role":"symbol","abstract":[{"type":"text","text":"Barcode symbology used."}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}],"type":"topic","title":"SBSDKUI2BarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeFormat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeDocumentFormat":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeDocumentFormat","abstract":[{"type":"text","text":"Type of barcode document format used."}],"title":"SBSDKUI2BarcodeDocumentFormat","navigatorTitle":[{"text":"SBSDKUI2BarcodeDocumentFormat","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodedocumentformat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeDocumentFormat"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AustraliaPostCustomerFormat":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}],"title":"SBSDKUI2AustraliaPostCustomerFormat","navigatorTitle":[{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AustraliaPostCustomerFormat","abstract":[{"text":"The customer format used in AUSTRALIA_POST codes. Only relevant for format codes 59 and 62.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2australiapostcustomerformat","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAcceptedDocumentFormats:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKUI2BarcodeDocumentFormat *>"},{"text":" *) ","kind":"text"},{"text":"acceptedDocumentFormats","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodesExtensionFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodesExtensionFilter","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2BarcodesExtensionFilter","kind":"typeIdentifier","text":"SBSDKUI2BarcodesExtensionFilter"},{"kind":"text","text":") "},{"kind":"internalParam","text":"barcodesExtensionFilter"},{"text":" ","kind":"text"},{"text":"barcodesRegexFilter:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"barcodesRegexFilter","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumTextLength:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumTextLength","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maximumTextLength:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"maximumTextLength","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimum1DBarcodesQuietZone:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"minimum1DBarcodesQuietZone","kind":"internalParam"},{"kind":"text","text":" "},{"text":"stripCheckDigits:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"stripCheckDigits","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useIATA2OF5Checksum:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"useIATA2OF5Checksum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useCode11Checksum:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"useCode11Checksum"},{"text":" ","kind":"text"},{"text":"barcodeFormats:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2BarcodeFormat *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcodeFormats"},{"kind":"text","text":" "},{"text":"msiPlesseyChecksumAlgorithm:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2MSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"msiPlesseyChecksumAlgorithm"},{"text":" ","kind":"text"},{"text":"australiaPostCustomerFormat:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2AustraliaPostCustomerFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AustraliaPostCustomerFormat","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2AustraliaPostCustomerFormat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"australiaPostCustomerFormat"},{"kind":"text","text":" "},{"text":"gs1Handling:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Gs1Handling","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2Gs1Handling","kind":"typeIdentifier","text":"SBSDKUI2Gs1Handling"},{"text":") ","kind":"text"},{"text":"gs1Handling","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeRecognizerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/title","op":"replace","value":"SBSDKUI2BarcodesExtensionFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodesExtensionFilter\/fragments","value":[{"text":"SBSDKUI2BarcodesExtensionFilter","kind":"identifier"}]},{"value":"SBSDKUI2MSIPlesseyChecksumAlgorithm","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MSIPlesseyChecksumAlgorithm\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MSIPlesseyChecksumAlgorithm"}],"op":"replace"},{"op":"replace","value":"SBSDKUI2Gs1Handling","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/title"},{"value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Gs1Handling\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)\/title","value":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1init(acceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAcceptedDocumentFormats:barcodesExtensionFilter:barcodesRegexFilter:minimumTextLength:maximumTextLength:minimum1DBarcodesQuietZone:stripCheckDigits:useIATA2OF5Checksum:useCode11Checksum:barcodeFormats:msiPlesseyChecksumAlgorithm:australiaPostCustomerFormat:gs1Handling:","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2BarcodeFormat","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeFormat\/fragments","op":"replace","value":[{"text":"SBSDKUI2BarcodeFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeDocumentFormat\/title","op":"replace","value":"SBSDKUI2BarcodeDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeDocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeDocumentFormat"}]},{"value":"SBSDKUI2AustraliaPostCustomerFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AustraliaPostCustomerFormat\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AustraliaPostCustomerFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AustraliaPostCustomerFormat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}