{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration"]]},"metadata":{"title":"minimum1DBarcodesQuietZone","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DBarcodesQuietZone"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"minimum1DBarcodesQuietZone"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeRecognizerConfiguration(py)minimum1DBarcodesQuietZone"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimum1DBarcodesQuietZone"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/minimum1dbarcodesquietzone"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/minimum1dbarcodesquietzone"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimum1DBarcodesQuietZone","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Optional minimum required quiet zone on the barcode. Measured in modules (the smallest bar size on a barcode).","type":"text"},{"text":" ","type":"text"},{"text":"The default is 10. NOTE - This feature works on ITF barcodes only.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is 10"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration/minimum1DBarcodesQuietZone":{"title":"minimum1DBarcodesQuietZone","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Optional minimum required quiet zone on the barcode. Measured in modules (the smallest bar size on a barcode)."},{"text":" ","type":"text"},{"text":"The default is 10. NOTE - This feature works on ITF barcodes only.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is 10"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration\/minimum1dbarcodesquietzone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minimum1DBarcodesQuietZone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration\/minimum1DBarcodesQuietZone","navigatorTitle":[{"kind":"identifier","text":"minimum1DBarcodesQuietZone"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeRecognizerConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcoderecognizerconfiguration","abstract":[{"text":"Configuration of the scanning behavior.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeRecognizerConfiguration","title":"SBSDKUI2BarcodeRecognizerConfiguration","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"minimum1DBarcodesQuietZone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"minimum1DBarcodesQuietZone","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"minimum1DBarcodesQuietZone","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1minimum1DBarcodesQuietZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration~1minimum1DBarcodesQuietZone\/fragments","value":[{"text":"minimum1DBarcodesQuietZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/title","value":"SBSDKUI2BarcodeRecognizerConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeRecognizerConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}