{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype\/illegalstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype\/illegalstate"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/illegalState","interfaceLanguage":"swift"},"abstract":[{"text":"The SDK is in an illegal or inconsistent state for the requested operation.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"illegalState"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeIllegalState"}],"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKErrorType@SBSDKErrorTypeIllegalState","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"illegalState"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKErrorType.illegalState"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/illegalState":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKErrorTypeIllegalState","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"illegalState","kind":"identifier"}],"title":"SBSDKErrorType.illegalState","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/illegalstate","abstract":[{"text":"The SDK is in an illegal or inconsistent state for the requested operation.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/illegalState"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype","kind":"symbol","title":"SBSDKErrorType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType","abstract":[{"text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK.","type":"text"},{"text":" ","type":"text"},{"text":"Each case corresponds to a specific error code.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKErrorTypeIllegalState","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKErrorTypeIllegalState"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"SBSDKErrorTypeIllegalState","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKErrorTypeIllegalState","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1illegalState\/title","op":"replace"},{"value":[{"text":"SBSDKErrorTypeIllegalState","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1illegalState\/fragments","op":"replace"},{"value":"SBSDKErrorType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/title","op":"replace"},{"value":[{"text":"SBSDKErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKErrorType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/navigatorTitle","op":"replace"}]}]}