{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nullPointer","kind":"identifier"}],"title":"SBSDKErrorType.nullPointer","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorTypeNullPointer"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKErrorType@SBSDKErrorTypeNullPointer","role":"symbol"},"abstract":[{"type":"text","text":"A null pointer was encountered where a valid reference was expected."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/nullPointer","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nullPointer"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype\/nullpointer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkerrortype\/nullpointer"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType/nullPointer":{"kind":"symbol","abstract":[{"type":"text","text":"A null pointer was encountered where a valid reference was expected."}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype\/nullpointer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType\/nullPointer","title":"SBSDKErrorType.nullPointer","role":"symbol","navigatorTitle":[{"text":"SBSDKErrorTypeNullPointer","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nullPointer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKErrorType":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKErrorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKErrorType"}],"url":"\/documentation\/scanbotsdk\/sbsdkerrortype","kind":"symbol","title":"SBSDKErrorType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKErrorType","abstract":[{"text":"An Objective-C compatible enum representing the types of errors that can occur within the Scanbot SDK.","type":"text"},{"text":" ","type":"text"},{"text":"Each case corresponds to a specific error code.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKErrorTypeNullPointer"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorTypeNullPointer"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKErrorTypeNullPointer"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1nullPointer\/title","op":"replace","value":"SBSDKErrorTypeNullPointer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType~1nullPointer\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorTypeNullPointer"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/title","op":"replace","value":"SBSDKErrorType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKErrorType"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKErrorType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}