{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController\/enableCameraTextConfiguration"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerViewController(py)enableCameraTextConfiguration","fragments":[{"kind":"identifier","text":"enableCameraTextConfiguration"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","title":"enableCameraTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"enableCameraTextConfiguration"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","text":"SBSDKUIEnableCameraTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"enableCameraTextConfiguration"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller\/enablecameratextconfiguration"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewController":{"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController","type":"topic","abstract":[{"text":"A view controller for camera-based detection of health insurance cards.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller","kind":"symbol","title":"SBSDKUIHealthInsuranceCardRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewController/enableCameraTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController\/enableCameraTextConfiguration","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"enableCameraTextConfiguration"}],"title":"enableCameraTextConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller\/enablecameratextconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration for the textual contents of camera based view controllers."}],"title":"SBSDKUIEnableCameraTextConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/title","value":"SBSDKUIHealthInsuranceCardRecognizerViewController"},{"value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title","value":"SBSDKUIEnableCameraTextConfiguration"},{"value":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}]}]}]}