{"kind":"symbol","sections":[],"metadata":{"platforms":[],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedAngleScore"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","navigatorTitle":[{"text":"acceptedAngleScore","kind":"identifier"}],"title":"acceptedAngleScore","symbolKind":"property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerBehaviorConfiguration(py)acceptedAngleScore","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"acceptedAngleScore","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to 75. Set lower values to accept more perspective distortion."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Lower values result in more blurred document images."}]}],"name":"Important","style":"important","type":"aside"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedAngleScore","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedanglescore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedanglescore"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The minimum score in percent (0 - 100) of the perspective distortion to accept a scanned document.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/acceptedAngleScore":{"navigatorTitle":[{"text":"acceptedAngleScore","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptedAngleScore","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The minimum score in percent (0 - 100) of the perspective distortion to accept a scanned document."}],"deprecated":true,"title":"acceptedAngleScore","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedAngleScore","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedanglescore","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}],"deprecated":true,"title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"acceptedAngleScore","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"acceptedAngleScore","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"acceptedAngleScore","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedAngleScore\/title","value":"acceptedAngleScore","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedAngleScore\/fragments","value":[{"kind":"identifier","text":"acceptedAngleScore"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}