{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"localization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration\/localization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration\/localization"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration\/localization"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2BarcodeTextLocalization","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerScreenConfiguration(py)localization","navigatorTitle":[{"kind":"identifier","text":"localization"}],"title":"localization","role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Configuration of the all strings for barcode scanner.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerScreenConfiguration/localization":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration\/localization","type":"topic","abstract":[{"text":"Configuration of the all strings for barcode scanner.","type":"text"}],"navigatorTitle":[{"text":"localization","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"localization","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2BarcodeTextLocalization","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"localization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration\/localization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeTextLocalization":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodetextlocalization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"navigatorTitle":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}],"title":"SBSDKUI2BarcodeTextLocalization"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerScreenConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerScreenConfiguration"}],"title":"SBSDKUI2BarcodeScannerScreenConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerScreenConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration","role":"symbol","abstract":[{"text":"Configuration of the barcode scanner screen.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"localization"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"localization","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUI2BarcodeTextLocalization","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeTextLocalization","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeTextLocalization"},{"text":" * ","kind":"text"},{"text":"localization","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"localization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration~1localization\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration~1localization\/fragments","value":[{"text":"localization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/title","value":"SBSDKUI2BarcodeTextLocalization","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/title","value":"SBSDKUI2BarcodeScannerScreenConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/navigatorTitle"}]}]}