{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderCorneredStyle\/fromJsonWithJson:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Type Method","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FinderCorneredStyle(cm)fromJsonWithJson:","title":"fromJsonWithJson:","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderCorneredStyle","text":"SBSDKUI2FinderCorneredStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FinderCorneredStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderCorneredStyle"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findercorneredstyle\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FinderCorneredStyle/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderCorneredStyle\/fromJsonWithJson:","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findercorneredstyle\/fromjsonwithjson:","type":"topic","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:","role":"symbol","abstract":[],"fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FinderCorneredStyle":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2FinderCorneredStyle"}],"navigatorTitle":[{"text":"SBSDKUI2FinderCorneredStyle","kind":"identifier"}],"abstract":[{"text":"A variant of the viewfinder displaying only the four corners of the scanning area.","type":"text"}],"title":"SBSDKUI2FinderCorneredStyle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FinderCorneredStyle","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findercorneredstyle","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderCorneredStyle\/title","value":"SBSDKUI2FinderCorneredStyle","op":"replace"},{"value":[{"text":"SBSDKUI2FinderCorneredStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderCorneredStyle\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2FinderCorneredStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FinderCorneredStyle\/navigatorTitle"}]}]}