{"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2MultipleScanningMode(im)initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","role":"symbol","navigatorTitle":[{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleScanningMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCountingRepeatDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"countingRepeatDelay"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowEmptySubmission:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowEmptySubmission"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleBarcodesScanningMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MultipleBarcodesScanningMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheet:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sheet","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sheetContent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2SheetContent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sheetContent","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountEditDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ManualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manualCountEditDialog","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeInfoMapping:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeInfoMapping","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcodeInfoMapping","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"arOverlay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"arOverlay","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplescanningmode\/initwithcountingrepeatdelay:allowemptysubmission:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleScanningMode\/initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleScanningMode":{"abstract":[{"text":"Configuration of the mode for scanning multiple barcodes.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleScanningMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplescanningmode","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"title":"SBSDKUI2MultipleScanningMode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeInfoMapping":{"role":"symbol","title":"SBSDKUI2BarcodeInfoMapping","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeinfomapping","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"abstract":[{"type":"text","text":"Configuration of the barcode data mapping."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeInfoMapping"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeInfoMapping"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayGeneralConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlaygeneralconfiguration","abstract":[{"type":"text","text":"Configuration of the AR overlay displayed on top of barcodes in the camera preview."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayGeneralConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"type":"topic","title":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the mode used for scanning multiple barcodes."}],"kind":"symbol","title":"SBSDKUI2MultipleBarcodesScanningMode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode","navigatorTitle":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetContent":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"role":"symbol","abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"title":"SBSDKUI2SheetContent","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.0","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sheet":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"title":"SBSDKUI2Sheet","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","abstract":[{"text":"Configuration of the preview mode for scanning multiple barcodes.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Sheet"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ManualCountEditDialog":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","kind":"symbol","title":"SBSDKUI2ManualCountEditDialog","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"abstract":[{"text":"Configuration of the dialog to manually edit the barcode count.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2manualcounteditdialog","navigatorTitle":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleScanningMode/initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleScanningMode\/initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplescanningmode\/initwithcountingrepeatdelay:allowemptysubmission:mode:sheet:sheetcontent:manualcounteditdialog:barcodeinfomapping:aroverlay:","abstract":[],"kind":"symbol","title":"initWithCountingRepeatDelay:allowEmptySubmission:mode:sheet:sheetContent:manualCountEditDialog:barcodeInfoMapping:arOverlay:","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2MultipleScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleScanningMode\/title","op":"replace"},{"value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleScanningMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleScanningMode\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2BarcodeInfoMapping","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeInfoMapping\/title","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeInfoMapping\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeInfoMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeInfoMapping\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2ArOverlayGeneralConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayGeneralConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayGeneralConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2MultipleBarcodesScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2SheetContent","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2SheetContent"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2Sheet","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/navigatorTitle","op":"replace"},{"value":"SBSDKUI2ManualCountEditDialog","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/title","op":"replace"},{"value":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/navigatorTitle","op":"replace"}]}]}