{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions\/cropRect","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions\/croprect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions\/croprect"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"cropRect","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPathImageLoadOptions(py)cropRect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"cropRect","kind":"identifier"}]},"sections":[],"abstract":[{"text":"If the rect is not empty, the image will be cropped to this rect before processing.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cropRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathImageLoadOptions/cropRect":{"abstract":[{"type":"text","text":"If the rect is not empty, the image will be cropped to this rect before processing."}],"url":"\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions\/croprect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"kind":"symbol","role":"symbol","title":"cropRect","navigatorTitle":[{"kind":"identifier","text":"cropRect"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions\/cropRect","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPathImageLoadOptions":{"title":"SBSDKPathImageLoadOptions","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpathimageloadoptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPathImageLoadOptions","abstract":[{"type":"text","text":"Options for loading image from path."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cropRect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cropRect"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"cropRect"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions~1cropRect\/title","value":"cropRect"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions~1cropRect\/fragments","value":[{"kind":"identifier","text":"cropRect"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/title","value":"SBSDKPathImageLoadOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPathImageLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}]}]}]}