{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentOcrResult\/encode(to:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentOcrResult"]]},"metadata":{"symbolKind":"method","role":"symbol","externalID":"s:24ScanbotBarcodeScannerSDK29SBSDKGenericDocumentOcrResultC6encode2toys7Encoder_p_tKF","title":"encode(to:)","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7EncoderP","text":"Encoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentocrresult\/encode(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"encoder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP","text":"Encoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Encodable.encode(to:)"},{"type":"text","text":"."}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentOcrResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentOcrResult"}],"abstract":[{"type":"text","text":"A generic documents fields result of OCR text recognition."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentocrresult","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentOcrResult","title":"SBSDKGenericDocumentOcrResult","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentOcrResult"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentOcrResult/encode(to:)":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentocrresult\/encode(to:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentOcrResult\/encode(to:)","title":"encode(to:)","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKGenericDocumentOcrResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentOcrResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentOcrResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentOcrResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentOcrResult\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentOcrResult","kind":"identifier"}]}]}]}