{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"permanentViewFinderConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2PermanentViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/permanentviewfinderconfiguration()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/permanentviewfinderconfiguration()"]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"permanentViewFinderConfiguration"}],"title":"permanentViewFinderConfiguration()","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BaseViewFinderConfiguration(cm)permanentViewFinderConfiguration","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"permanentViewFinderConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration","text":"SBSDKUI2PermanentViewFinderConfiguration"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/permanentViewFinderConfiguration()"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PermanentViewFinderConfiguration":{"title":"SBSDKUI2PermanentViewFinderConfiguration","navigatorTitle":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of the scanning interface’s viewfinder, which is always visible to guide the user."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2permanentviewfinderconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration":{"abstract":[{"type":"text","text":"Base configuration of the scanning interface’s viewfinder, serving as guidance to the user."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration","kind":"symbol","title":"SBSDKUI2BaseViewFinderConfiguration","navigatorTitle":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BaseViewFinderConfiguration/permanentViewFinderConfiguration()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BaseViewFinderConfiguration\/permanentViewFinderConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"permanentViewFinderConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2PermanentViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration"}],"title":"permanentViewFinderConfiguration()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2baseviewfinderconfiguration\/permanentviewfinderconfiguration()","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"permanentViewFinderConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"permanentViewFinderConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"permanentViewFinderConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PermanentViewFinderConfiguration","text":"SBSDKUI2PermanentViewFinderConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PermanentViewFinderConfiguration"},{"text":" *) ","kind":"text"},{"text":"permanentViewFinderConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2PermanentViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2PermanentViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2PermanentViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PermanentViewFinderConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2BaseViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKUI2BaseViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BaseViewFinderConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration\/navigatorTitle"},{"op":"replace","value":"permanentViewFinderConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1permanentViewFinderConfiguration()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"permanentViewFinderConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BaseViewFinderConfiguration~1permanentViewFinderConfiguration()\/fragments"}]}]}