{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller\/sbsdkhealthinsurancecardrecognizerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller\/sbsdkhealthinsurancecardrecognizerviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"API Collection","role":"collectionGroup","title":"SBSDKHealthInsuranceCardRecognizerViewControllerDelegate Implementations"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController\/SBSDKHealthInsuranceCardRecognizerViewControllerDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController"]]},"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController\/healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewController/healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)":{"type":"topic","title":"healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"healthInsuranceCardRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardRecognizerViewController"},{"text":", ","kind":"text"},{"text":"didScanHealthInsuranceCard","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:","kind":"identifier"}],"abstract":[{"text":"Informs the delegate that a health insurance card has been scanned.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller\/healthinsurancecardrecognizerviewcontroller(_:didscanhealthinsurancecard:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController\/healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewController":{"title":"SBSDKUIHealthInsuranceCardRecognizerViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"}],"abstract":[{"text":"A view controller for camera-based detection of health insurance cards.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController","deprecated":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController\/healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)"],"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController~1healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)\/title","value":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController~1healthInsuranceCardRecognizerViewController(_:didScanHealthInsuranceCard:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"healthInsuranceCardRecognizerViewController:didScanHealthInsuranceCard:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/title","value":"SBSDKUIHealthInsuranceCardRecognizerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/navigatorTitle","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}