{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCameraDeviceType@SBSDKCameraDeviceTypeSimulated","title":"SBSDKCameraDeviceType.simulated","symbolKind":"case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulated"}],"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKCameraDeviceTypeSimulated","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/simulated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/simulated"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A simulated camera that can simulate a video stream by looping a video or a single image."},{"type":"text","text":" "},{"type":"text","text":"Also used on iPhone\/iPad simulators without providing a video stream."}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/simulated"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simulated","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType","type":"topic","title":"SBSDKCameraDeviceType","kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An enum to describe the different types of camera lenses\/devices."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCameraDeviceType","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCameraDeviceType/simulated":{"abstract":[{"text":"A simulated camera that can simulate a video stream by looping a video or a single image.","type":"text"},{"text":" ","type":"text"},{"text":"Also used on iPhone\/iPad simulators without providing a video stream.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCameraDeviceType\/simulated","navigatorTitle":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeSimulated"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulated"}],"title":"SBSDKCameraDeviceType.simulated","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcameradevicetype\/simulated"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKCameraDeviceTypeSimulated"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKCameraDeviceTypeSimulated","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeSimulated"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/title","value":"SBSDKCameraDeviceType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/fragments","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType\/navigatorTitle","value":[{"text":"SBSDKCameraDeviceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1simulated\/title","value":"SBSDKCameraDeviceTypeSimulated"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCameraDeviceType~1simulated\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraDeviceTypeSimulated"}]}]}]}