{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVARawDocument","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Class","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentAAMVARawDocument","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARawDocument"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentAAMVARawDocument","kind":"identifier"}],"title":"SBSDKBarcodeDocumentAAMVARawDocument"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARawDocument\/requiredDocumentType"]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper"],"title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvarawdocument"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvarawdocument"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The raw document as was parsed from the barcode. The original field key names and field values as they appear in the barcode are left as-is. The mnemonic field keys from the AAMVA specification are not replaced with human-readable names. No field value normalization, like ISO 8601 date reformatting, etc., is done."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARawDocument"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVARawDocument":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentAAMVARawDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentAAMVARawDocument","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARawDocument","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvarawdocument","kind":"symbol","title":"SBSDKBarcodeDocumentAAMVARawDocument","role":"symbol","abstract":[{"text":"The raw document as was parsed from the barcode. The original field key names and field values as they appear in the barcode are left as-is. The mnemonic field keys from the AAMVA specification are not replaced with human-readable names. No field value normalization, like ISO 8601 date reformatting, etc., is done.","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVARawDocument/requiredDocumentType":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARawDocument\/requiredDocumentType","title":"requiredDocumentType","kind":"symbol","abstract":[{"type":"text","text":"The name of the wrapped document type."}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvarawdocument\/requireddocumenttype","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocumentWrapper":{"abstract":[{"type":"text","text":"Base class for strongly-typed "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument"},{"type":"text","text":" wrappers."}],"kind":"symbol","title":"SBSDKGenericDocumentWrapper","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocumentwrapper","navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGenericDocument":{"abstract":[{"type":"text","text":"Represents a generic document with fields and sub-documents used for document recognition."}],"kind":"symbol","title":"SBSDKGenericDocument","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocument","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgenericdocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentAAMVARawDocument/initWithGenericDocument:":{"title":"initWithGenericDocument:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARawDocument\/initWithGenericDocument:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentaamvarawdocument\/initwithgenericdocument:","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithGenericDocument:"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKBarcodeDocumentAAMVARawDocument","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeDocumentAAMVARawDocument","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentAAMVARawDocument","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARawDocument\/requiredDocumentType"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentAAMVARawDocument\/initWithGenericDocument:"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentAAMVARawDocument","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGenericDocumentWrapper","text":"SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKGenericDocumentWrapper"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARawDocument\/title","op":"replace","value":"SBSDKBarcodeDocumentAAMVARawDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARawDocument\/fragments","value":[{"text":"SBSDKBarcodeDocumentAAMVARawDocument","kind":"identifier"}]},{"value":"requiredDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARawDocument~1requiredDocumentType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentAAMVARawDocument~1requiredDocumentType\/fragments","value":[{"text":"requiredDocumentType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentWrapper\/title","value":"SBSDKGenericDocumentWrapper","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocumentWrapper\/fragments","value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGenericDocument\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}