{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKPolygonEdgeOrientation","symbolKind":"enum","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Enumeration","title":"SBSDKPolygonEdgeOrientation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/horizontal","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/undefined","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/vertical"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/rawrepresentable-implementations","abstract":[],"kind":"article"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/init(rawValue:)","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation/undefined":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/undefined","title":"SBSDKPolygonEdgeOrientation.undefined","abstract":[{"text":"The edge is oriented 45° from x- and y-axis.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/undefined","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientationUndefined","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 6.2.0"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation/Equatable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation/vertical":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vertical"}],"title":"SBSDKPolygonEdgeOrientation.vertical","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/vertical","navigatorTitle":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientationVertical"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/vertical","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The edge is oriented vertically."}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation":{"type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"title":"SBSDKPolygonEdgeOrientation","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation","navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPolygonEdgeOrientation/horizontal":{"kind":"symbol","type":"topic","abstract":[{"text":"The edge is oriented horizontally.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"title":"SBSDKPolygonEdgeOrientation.horizontal","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/horizontal","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpolygonedgeorientation\/horizontal","navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientationHorizontal","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKPolygonEdgeOrientation","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientation"}]},{"op":"replace","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/horizontal","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/undefined","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPolygonEdgeOrientation\/vertical"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1undefined\/title","op":"replace","value":"SBSDKPolygonEdgeOrientationUndefined"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1undefined\/fragments","value":[{"text":"SBSDKPolygonEdgeOrientationUndefined","kind":"identifier"}],"op":"replace"},{"value":"SBSDKPolygonEdgeOrientationVertical","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1vertical\/title"},{"value":[{"kind":"identifier","text":"SBSDKPolygonEdgeOrientationVertical"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1vertical\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation\/title","value":"SBSDKPolygonEdgeOrientation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation\/fragments","value":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}]},{"value":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation\/navigatorTitle","op":"replace"},{"value":"SBSDKPolygonEdgeOrientationHorizontal","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1horizontal\/title"},{"op":"replace","value":[{"text":"SBSDKPolygonEdgeOrientationHorizontal","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPolygonEdgeOrientation~1horizontal\/fragments"}]}]}