{"metadata":{"role":"symbol","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","roleHeading":"Enumeration","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKBarcodeMSIPlesseyChecksumAlgorithm"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm"]}],"abstract":[{"type":"text","text":"The checksum algorithm for MSI-Plessey type barcodes."}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1010","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110IBM","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110NCR","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11IBM","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11NCR","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/none"],"generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/init(rawValue:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/init(rawvalue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod1010":{"role":"symbol","abstract":[{"type":"text","text":"Mod1010."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod1010"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1010","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod1010","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1010","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1010","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod1110IBM":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mod1110IBM","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110IBM","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1110ibm","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110IBM","type":"topic","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod1110IBM","abstract":[{"type":"text","text":"Mod1110IBM."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod10":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10"}],"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod10","abstract":[{"type":"text","text":"Mod10."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod10","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod10","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod1110NCR":{"abstract":[{"text":"Mod1110NCR.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod1110ncr","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod1110NCR"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR"}],"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod1110NCR","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110NCR","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod11NCR":{"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod11NCR","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ncr","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11NCR","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Mod11NCR."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mod11NCR"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/Equatable-Implementations","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/equatable-implementations","kind":"article","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"symbol","abstract":[{"text":"The checksum algorithm for MSI-Plessey type barcodes.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/mod11IBM":{"type":"topic","title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.mod11IBM","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/mod11ibm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11IBM","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mod11IBM","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","kind":"identifier"}],"abstract":[{"type":"text","text":"Mod11IBM."}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeMSIPlesseyChecksumAlgorithm/none":{"title":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm.none","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmNone"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodemsiplesseychecksumalgorithm\/none","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/none","role":"symbol","type":"topic","abstract":[{"type":"text","text":"None."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm"}]},{"value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod10","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1010","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110IBM","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod1110NCR","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11IBM","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/mod11NCR","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/none"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1010","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1010\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1010\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1010"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110IBM\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110IBM"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110IBM\/fragments","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110IBM","kind":"identifier"}]},{"value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod10\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod10","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod10\/fragments"},{"value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110NCR\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod1110NCR","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod1110NCR\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11NCR\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11NCR\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11NCR"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/title","value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","op":"replace"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm\/navigatorTitle"},{"value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11IBM\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1mod11IBM\/fragments","value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmMod11IBM","kind":"identifier"}]},{"value":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmNone","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1none\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeMSIPlesseyChecksumAlgorithmNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeMSIPlesseyChecksumAlgorithm~1none\/fragments"}]}]}