{"kind":"symbol","sections":[],"abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature","title":"SBSDKFeature","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKFeature"}]},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/EHICRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/IDCardRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/MRZRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/NFCScanning","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/OCR","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/PDFCreation","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/barcodeDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/checkRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/cloudUpload","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/creditCardRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/dataIntelligence","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/driverLicenseRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/edgeDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/edgeDetectionUI","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/imageProcessing","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/invoiceDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/licensePlateScanning","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/medicalCertRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/multipleObjectsDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/payformDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/textLineRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/textOrientationDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/w2Detection"],"anchor":"Enumeration-Cases"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFeature"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"role":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/init(rawValue:)","abstract":[],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/MRZRecognition":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/mrzrecognition","title":"SBSDKFeature.MRZRecognition","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"MRZRecognition","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/MRZRecognition","navigatorTitle":[{"text":"SBSDKFeatureMRZRecognition","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Machine-readable-zone detection is enabled in the licence.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/creditCardRecognition":{"abstract":[{"text":"Credit card recognition is enabled in the licence. Currently unused.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKFeatureCreditCardRecognition","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/creditCardRecognition","role":"symbol","title":"SBSDKFeature.creditCardRecognition","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"creditCardRecognition"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/creditcardrecognition","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/payformDetection":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/payformDetection","title":"SBSDKFeature.payformDetection","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payformDetection","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKFeaturePayformDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"Payform detection is enabled in the license. Currently unused."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/payformdetection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/w2Detection":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/w2Detection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"w2Detection"}],"type":"topic","title":"SBSDKFeature.w2Detection","navigatorTitle":[{"text":"SBSDKFeatureW2Detection","kind":"identifier"}],"abstract":[{"type":"text","text":"W2 document detection is enabled in the licence. Currently unused."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/w2detection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/medicalCertRecognition":{"type":"topic","title":"SBSDKFeature.medicalCertRecognition","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"medicalCertRecognition","kind":"identifier"}],"abstract":[{"text":"Medical certificate recognition is enabled in the licence.","type":"text"}],"navigatorTitle":[{"text":"SBSDKFeatureMedicalCertRecognition","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/medicalCertRecognition","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/medicalcertrecognition","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/edgeDetection":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/edgedetection","navigatorTitle":[{"text":"SBSDKFeatureEdgeDetection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/edgeDetection","title":"SBSDKFeature.edgeDetection","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"edgeDetection","kind":"identifier"}],"type":"topic","abstract":[{"text":"Document detection is enabled in the license.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/barcodeDetection":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/barcodedetection","abstract":[{"text":"Barcode detection is enabled in the licence.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/barcodeDetection","navigatorTitle":[{"text":"SBSDKFeatureBarcodeDetection","kind":"identifier"}],"title":"SBSDKFeature.barcodeDetection","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeDetection"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/SBSDKFeatureNone":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/sbsdkfeaturenone","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/SBSDKFeatureNone","title":"SBSDKFeatureNone","role":"symbol","fragments":[{"text":"SBSDKFeatureNone","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Driver license recognition is enabled in the licence."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/cloudUpload":{"type":"topic","abstract":[{"type":"text","text":"Cloud upload is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/cloudUpload","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/cloudupload","navigatorTitle":[{"text":"SBSDKFeatureCloudUpload","kind":"identifier"}],"title":"SBSDKFeature.cloudUpload","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cloudUpload","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/invoiceDetection":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invoiceDetection","kind":"identifier"}],"title":"SBSDKFeature.invoiceDetection","kind":"symbol","abstract":[{"type":"text","text":"Invoice recognition is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/invoiceDetection","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/invoicedetection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureInvoiceDetection"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/checkRecognition":{"type":"topic","abstract":[{"type":"text","text":"Check recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/checkRecognition","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/checkrecognition","navigatorTitle":[{"text":"SBSDKFeatureCheckRecognition","kind":"identifier"}],"title":"SBSDKFeature.checkRecognition","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkRecognition","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/textLineRecognition":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textLineRecognition","kind":"identifier"}],"title":"SBSDKFeature.textLineRecognition","kind":"symbol","abstract":[{"type":"text","text":"Text line recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/textLineRecognition","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/textlinerecognition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureTextLineRecognition"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/licensePlateScanning":{"type":"topic","abstract":[{"type":"text","text":"License plate scanning is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/licensePlateScanning","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/licenseplatescanning","navigatorTitle":[{"text":"SBSDKFeatureLicensePlateScanning","kind":"identifier"}],"title":"SBSDKFeature.licensePlateScanning","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licensePlateScanning","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/imageProcessing":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageProcessing","kind":"identifier"}],"title":"SBSDKFeature.imageProcessing","kind":"symbol","abstract":[{"type":"text","text":"Image processing is enabled in the license."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/imageProcessing","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/imageprocessing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureImageProcessing"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/IDCardRecognition":{"type":"topic","abstract":[{"type":"text","text":"ID card and passport recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/IDCardRecognition","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/idcardrecognition","navigatorTitle":[{"text":"SBSDKFeatureIDCardRecognition","kind":"identifier"}],"title":"SBSDKFeature.IDCardRecognition","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDCardRecognition","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}],"title":"SBSDKFeature","kind":"symbol","abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeature"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/multipleObjectsDetection":{"type":"topic","abstract":[{"type":"text","text":"Multiple objects detection is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/multipleObjectsDetection","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/multipleobjectsdetection","navigatorTitle":[{"text":"SBSDKFeatureMultipleObjectsDetection","kind":"identifier"}],"title":"SBSDKFeature.multipleObjectsDetection","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multipleObjectsDetection","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/rawrepresentable-implementations","role":"collectionGroup"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/driverLicenseRecognition":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"driverLicenseRecognition","kind":"identifier"}],"title":"SBSDKFeature.driverLicenseRecognition","kind":"symbol","abstract":[{"type":"text","text":"Driver license recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/driverLicenseRecognition","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/driverlicenserecognition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureDriverLicenseRecognition"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/NFCScanning":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NFCScanning","kind":"identifier"}],"title":"SBSDKFeature.NFCScanning","kind":"symbol","abstract":[{"type":"text","text":"NFC scanning is enabled in the license. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/NFCScanning","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/nfcscanning","role":"symbol","navigatorTitle":[{"text":"SBSDKFeatureNFCScanning","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/Equatable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/Equatable-Implementations","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/edgeDetectionUI":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"edgeDetectionUI","kind":"identifier"}],"title":"SBSDKFeature.edgeDetectionUI","kind":"symbol","abstract":[{"text":"Document detection user interface is enabled in the license.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/edgeDetectionUI","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/edgedetectionui","role":"symbol","navigatorTitle":[{"text":"SBSDKFeatureEdgeDetectionUI","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/textOrientationDetection":{"type":"topic","abstract":[{"type":"text","text":"Text layout recognition is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/textOrientationDetection","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/textorientationdetection","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureTextOrientationDetection"}],"title":"SBSDKFeature.textOrientationDetection","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textOrientationDetection","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/PDFCreation":{"type":"topic","abstract":[{"type":"text","text":"PDF creation is enabled in the licence."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/PDFCreation","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/pdfcreation","navigatorTitle":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}],"title":"SBSDKFeature.PDFCreation","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PDFCreation"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/OCR":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OCR","kind":"identifier"}],"title":"SBSDKFeature.OCR","kind":"symbol","abstract":[{"type":"text","text":"Optical character recognition is enabled in the license."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/OCR","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/ocr","role":"symbol","navigatorTitle":[{"text":"SBSDKFeatureOCR","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/dataIntelligence":{"type":"topic","abstract":[{"type":"text","text":"Data intelligence is enabled in the licence. Currently unused."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/dataIntelligence","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/dataintelligence","navigatorTitle":[{"text":"SBSDKFeatureDataIntelligence","kind":"identifier"}],"title":"SBSDKFeature.dataIntelligence","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dataIntelligence","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/EHICRecognition":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"EHICRecognition","kind":"identifier"}],"title":"SBSDKFeature.EHICRecognition","kind":"symbol","abstract":[{"text":"European health insurance card recognition is enabled in the licence.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/EHICRecognition","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/ehicrecognition","role":"symbol","navigatorTitle":[{"text":"SBSDKFeatureEHICRecognition","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKFeature"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"text":"SBSDKFeature","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKFeature","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/EHICRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/IDCardRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/MRZRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/NFCScanning","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/OCR","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/PDFCreation","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/SBSDKFeatureNone","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/barcodeDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/checkRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/cloudUpload","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/creditCardRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/dataIntelligence","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/driverLicenseRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/edgeDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/edgeDetectionUI","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/imageProcessing","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/invoiceDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/licensePlateScanning","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/medicalCertRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/multipleObjectsDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/payformDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/textLineRecognition","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/textOrientationDetection","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/w2Detection"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFeature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1MRZRecognition\/title","op":"replace","value":"SBSDKFeatureMRZRecognition"},{"op":"replace","value":[{"text":"SBSDKFeatureMRZRecognition","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1MRZRecognition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1creditCardRecognition\/title","value":"SBSDKFeatureCreditCardRecognition"},{"value":[{"text":"SBSDKFeatureCreditCardRecognition","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1creditCardRecognition\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1payformDetection\/title","value":"SBSDKFeaturePayformDetection","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1payformDetection\/fragments","value":[{"text":"SBSDKFeaturePayformDetection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1w2Detection\/title","value":"SBSDKFeatureW2Detection","op":"replace"},{"op":"replace","value":[{"text":"SBSDKFeatureW2Detection","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1w2Detection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1medicalCertRecognition\/title","value":"SBSDKFeatureMedicalCertRecognition"},{"value":[{"kind":"identifier","text":"SBSDKFeatureMedicalCertRecognition"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1medicalCertRecognition\/fragments"},{"value":"SBSDKFeatureEdgeDetection","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1edgeDetection\/title"},{"value":[{"text":"SBSDKFeatureEdgeDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1edgeDetection\/fragments"},{"value":"SBSDKFeatureBarcodeDetection","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1barcodeDetection\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1barcodeDetection\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureBarcodeDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1cloudUpload\/title","value":"SBSDKFeatureCloudUpload"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1cloudUpload\/fragments","value":[{"text":"SBSDKFeatureCloudUpload","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1invoiceDetection\/title","op":"replace","value":"SBSDKFeatureInvoiceDetection"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1invoiceDetection\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFeatureInvoiceDetection"}]},{"op":"replace","value":"SBSDKFeatureCheckRecognition","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1checkRecognition\/title"},{"value":[{"kind":"identifier","text":"SBSDKFeatureCheckRecognition"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1checkRecognition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1textLineRecognition\/title","value":"SBSDKFeatureTextLineRecognition"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1textLineRecognition\/fragments","value":[{"text":"SBSDKFeatureTextLineRecognition","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1licensePlateScanning\/title","value":"SBSDKFeatureLicensePlateScanning"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1licensePlateScanning\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFeatureLicensePlateScanning"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1imageProcessing\/title","value":"SBSDKFeatureImageProcessing"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1imageProcessing\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFeatureImageProcessing"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1IDCardRecognition\/title","op":"replace","value":"SBSDKFeatureIDCardRecognition"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1IDCardRecognition\/fragments","value":[{"text":"SBSDKFeatureIDCardRecognition","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/title","value":"SBSDKFeature"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/fragments","value":[{"text":"SBSDKFeature","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1multipleObjectsDetection\/title","op":"replace","value":"SBSDKFeatureMultipleObjectsDetection"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1multipleObjectsDetection\/fragments","value":[{"text":"SBSDKFeatureMultipleObjectsDetection","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKFeatureDriverLicenseRecognition","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1driverLicenseRecognition\/title"},{"value":[{"text":"SBSDKFeatureDriverLicenseRecognition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1driverLicenseRecognition\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1NFCScanning\/title","op":"replace","value":"SBSDKFeatureNFCScanning"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1NFCScanning\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFeatureNFCScanning"}]},{"value":"SBSDKFeatureEdgeDetectionUI","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1edgeDetectionUI\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKFeatureEdgeDetectionUI"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1edgeDetectionUI\/fragments"},{"op":"replace","value":"SBSDKFeatureTextOrientationDetection","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1textOrientationDetection\/title"},{"value":[{"kind":"identifier","text":"SBSDKFeatureTextOrientationDetection"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1textOrientationDetection\/fragments"},{"op":"replace","value":"SBSDKFeaturePDFCreation","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1PDFCreation\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1PDFCreation\/fragments","value":[{"text":"SBSDKFeaturePDFCreation","kind":"identifier"}],"op":"replace"},{"value":"SBSDKFeatureOCR","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1OCR\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1OCR\/fragments","op":"replace","value":[{"text":"SBSDKFeatureOCR","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1dataIntelligence\/title","op":"replace","value":"SBSDKFeatureDataIntelligence"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1dataIntelligence\/fragments","value":[{"text":"SBSDKFeatureDataIntelligence","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1EHICRecognition\/title","value":"SBSDKFeatureEHICRecognition","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1EHICRecognition\/fragments","value":[{"kind":"identifier","text":"SBSDKFeatureEHICRecognition"}],"op":"replace"}]}]}