{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerUIConfiguration","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"class","platforms":[],"role":"symbol","title":"SBSDKUIBarcodesBatchScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"The configuration for user interface of the RTU-UI batch barcode scanner.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}],"type":"paragraph"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/barcodesCountTextColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/cameraOverlayColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsActionColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsBackgroundColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsPrimaryColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderAspectRatio","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderLineColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderLineWidth","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderTextHintColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/isCancelButtonHidden","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/isFlashButtonHidden","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/orientationLockMode","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarBackgroundColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarButtonsColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarButtonsInactiveColor"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/detailsActionColor":{"title":"detailsActionColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"detailsActionColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Foreground color of the top bar buttons on the details screen."}],"navigatorTitle":[{"kind":"identifier","text":"detailsActionColor"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsActionColor","kind":"symbol","type":"topic","role":"symbol","deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsactioncolor"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/topBarButtonsInactiveColor":{"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarButtonsInactiveColor","title":"topBarButtonsInactiveColor","navigatorTitle":[{"text":"topBarButtonsInactiveColor","kind":"identifier"}],"abstract":[{"text":"Foreground color of the flash button when flash is off.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/topbarbuttonsinactivecolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarButtonsInactiveColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/orientationLockMode":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/orientationLockMode","deprecated":true,"type":"topic","navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOrientationLock","kind":"typeIdentifier","text":"SBSDKOrientationLock"}],"abstract":[{"text":"Allowed orientations for automatic interface rotations.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/orientationlockmode","title":"orientationLockMode","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/finderAspectRatio":{"abstract":[{"type":"text","text":"Aspect ratio of finder frame (width \\ height), which is used to build actual finder frame."}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/finderaspectratio","deprecated":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderAspectRatio"},{"kind":"text","text":": "},{"text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAspectRatio"}],"title":"finderAspectRatio","navigatorTitle":[{"text":"finderAspectRatio","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderAspectRatio","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/finderLineColor":{"navigatorTitle":[{"kind":"identifier","text":"finderLineColor"}],"deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/finderlinecolor","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderLineColor","title":"finderLineColor","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Foreground color of the detection overlay."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderLineColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/finderTextHintColor":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/findertexthintcolor","kind":"symbol","navigatorTitle":[{"text":"finderTextHintColor","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderTextHintColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderTextHintColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"title":"finderTextHintColor","role":"symbol","abstract":[{"type":"text","text":"Foreground color of the description label."}],"type":"topic","deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The configuration for user interface of the RTU-UI batch barcode scanner."}],"deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration","title":"SBSDKUIBarcodesBatchScannerUIConfiguration","type":"topic","navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/init":{"abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/init","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/init","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/topBarBackgroundColor":{"title":"topBarBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"text":"Background color of the top bar.","type":"text"}],"navigatorTitle":[{"text":"topBarBackgroundColor","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarBackgroundColor","kind":"symbol","type":"topic","role":"symbol","deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/topbarbackgroundcolor"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/finderLineWidth":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/finderlinewidth","role":"symbol","kind":"symbol","title":"finderLineWidth","abstract":[{"text":"Width of finder frame border.","type":"text"}],"navigatorTitle":[{"text":"finderLineWidth","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finderLineWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderLineWidth"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/isCancelButtonHidden":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/iscancelbuttonhidden","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isCancelButtonHidden"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/isCancelButtonHidden","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isCancelButtonHidden","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isCancelButtonHidden","role":"symbol","abstract":[{"type":"text","text":"Whether the cancel button is hidden or not."}],"type":"topic","deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/isFlashButtonHidden":{"navigatorTitle":[{"kind":"identifier","text":"isFlashButtonHidden"}],"deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/isflashbuttonhidden","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/isFlashButtonHidden","title":"isFlashButtonHidden","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Whether the flash button is hidden or not."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFlashButtonHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/cameraOverlayColor":{"title":"cameraOverlayColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cameraOverlayColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Background color of the detection overlay.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/cameraOverlayColor","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/cameraoverlaycolor","role":"symbol","navigatorTitle":[{"text":"cameraOverlayColor","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/detailsPrimaryColor":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsprimarycolor","kind":"symbol","title":"detailsPrimaryColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"detailsPrimaryColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"deprecated":true,"abstract":[{"text":"Text color in the details barcodes list. Also affects image background, separator and progress spinner.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsPrimaryColor","type":"topic","navigatorTitle":[{"text":"detailsPrimaryColor","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/topBarButtonsColor":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarButtonsColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"topBarButtonsColor","kind":"symbol","abstract":[{"text":"Foreground color of the top bar buttons on the scanning screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarButtonsColor","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/topbarbuttonscolor","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"topBarButtonsColor","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/barcodesCountTextColor":{"navigatorTitle":[{"kind":"identifier","text":"barcodesCountTextColor"}],"deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/barcodescounttextcolor","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/barcodesCountTextColor","title":"barcodesCountTextColor","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Text color of the barcodes count label."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodesCountTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject","title":"NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/detailsBackgroundColor":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"detailsBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"detailsBackgroundColor"}],"type":"topic","title":"detailsBackgroundColor","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/detailsbackgroundcolor","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsBackgroundColor","abstract":[{"text":"Background color of the details screen.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[]},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUIBarcodesBatchScannerUIConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}],"op":"replace"},{"value":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/barcodesCountTextColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/cameraOverlayColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsActionColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsBackgroundColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/detailsPrimaryColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderAspectRatio","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderLineColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderLineWidth","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/finderTextHintColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/isCancelButtonHidden","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/isFlashButtonHidden","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/orientationLockMode","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarBackgroundColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarButtonsColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/topBarButtonsInactiveColor"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/init"],"anchor":"Instance-Methods"}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"detailsActionColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsActionColor\/title"},{"value":[{"kind":"identifier","text":"detailsActionColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsActionColor\/fragments","op":"replace"},{"value":"topBarButtonsInactiveColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1topBarButtonsInactiveColor\/title"},{"op":"replace","value":[{"text":"topBarButtonsInactiveColor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1topBarButtonsInactiveColor\/fragments"},{"value":"orientationLockMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1orientationLockMode\/title"},{"value":[{"text":"orientationLockMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1orientationLockMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderAspectRatio\/title","value":"finderAspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderAspectRatio\/fragments","op":"replace","value":[{"text":"finderAspectRatio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderLineColor\/title","op":"replace","value":"finderLineColor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderLineColor\/fragments","value":[{"text":"finderLineColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderTextHintColor\/title","op":"replace","value":"finderTextHintColor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderTextHintColor\/fragments","value":[{"text":"finderTextHintColor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/title","value":"SBSDKUIBarcodesBatchScannerUIConfiguration"},{"value":[{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1topBarBackgroundColor\/title","value":"topBarBackgroundColor"},{"op":"replace","value":[{"kind":"identifier","text":"topBarBackgroundColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1topBarBackgroundColor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderLineWidth\/title","value":"finderLineWidth","op":"replace"},{"value":[{"text":"finderLineWidth","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1finderLineWidth\/fragments","op":"replace"},{"value":"isCancelButtonHidden","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1isCancelButtonHidden\/title"},{"op":"replace","value":[{"text":"isCancelButtonHidden","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1isCancelButtonHidden\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1isFlashButtonHidden\/title","value":"isFlashButtonHidden","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1isFlashButtonHidden\/fragments","op":"replace","value":[{"text":"isFlashButtonHidden","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1cameraOverlayColor\/title","value":"cameraOverlayColor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1cameraOverlayColor\/fragments","value":[{"text":"cameraOverlayColor","kind":"identifier"}],"op":"replace"},{"value":"detailsPrimaryColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsPrimaryColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsPrimaryColor\/fragments","value":[{"kind":"identifier","text":"detailsPrimaryColor"}],"op":"replace"},{"op":"replace","value":"topBarButtonsColor","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1topBarButtonsColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1topBarButtonsColor\/fragments","op":"replace","value":[{"text":"topBarButtonsColor","kind":"identifier"}]},{"value":"barcodesCountTextColor","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1barcodesCountTextColor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1barcodesCountTextColor\/fragments","value":[{"kind":"identifier","text":"barcodesCountTextColor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsBackgroundColor\/title","value":"detailsBackgroundColor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1detailsBackgroundColor\/fragments","value":[{"text":"detailsBackgroundColor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}