{"abstract":[{"type":"text","text":"A "},{"code":"UIView","type":"codeVoice"},{"text":" that conforms to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoView"},{"kind":"text","text":" = ("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKTrackedBarcodeInfoViewable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable","kind":"typeIdentifier","text":"SBSDKTrackedBarcodeInfoViewable"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoView","interfaceLanguage":"swift"},"metadata":{"symbolKind":"typealias","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoView"}],"externalID":"s:24ScanbotBarcodeScannerSDK012SBSDKTrackedB8InfoViewa","title":"SBSDKTrackedBarcodeInfoView","roleHeading":"Type Alias","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"SBSDKTrackedBarcodeInfoView","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoview"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKTrackedBarcodeInfoViewable":{"abstract":[{"text":"A protocol that defines the methods and properties required for a custom tracking view to be displayed over detected barcodes using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The custom view must conform to this protocol in order to be used as an overlay on top of the detected barcodes.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoviewable","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"title":"SBSDKTrackedBarcodeInfoViewable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKTrackedBarcodeInfoView":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktrackedbarcodeinfoview","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A "},{"code":"UIView","type":"codeVoice"},{"type":"text","text":" that conforms to the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoViewable"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKTrackedBarcodeInfoView","title":"SBSDKTrackedBarcodeInfoView","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoView"}],"navigatorTitle":[{"text":"SBSDKTrackedBarcodeInfoView","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayConfiguration":{"role":"symbol","abstract":[{"text":"A class that represents the configuration options for a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"This overlay is used to visualize the detected barcodes on the screen."},{"type":"text","text":" "},{"type":"text","text":"The class provides various customization options for the appearance and behavior of the overlay."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlayconfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayConfiguration","kind":"identifier"}],"title":"SBSDKBarcodeTrackingOverlayConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKTrackedBarcodeInfoViewable","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable\/title"},{"value":[{"kind":"identifier","text":"SBSDKTrackedBarcodeInfoViewable"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKTrackedBarcodeInfoViewable\/fragments","op":"replace"},{"value":"SBSDKBarcodeTrackingOverlayConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayConfiguration\/fragments","op":"replace"}]}]}