{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"title":"SBSDKBarcodeScanAndCountViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeScanAndCountViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"roleHeading":"Protocol","symbolKind":"protocol","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:didDetectBarcodes:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:filterResults:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:overlayForBarcode:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:polygonStyleForBarcode:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCountControllerDidStartScanning(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"sections":[],"abstract":[{"text":"A delegate protocol to handle the barcode results from ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","isActive":true},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCountControllerDidStartScanning(_:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCountControllerDidStartScanning(_:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcountcontrollerdidstartscanning(_:)","kind":"symbol","title":"barcodeScanAndCountControllerDidStartScanning(_:)","required":true,"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"barcodeScanAndCountControllerDidStartScanning","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"text":")","kind":"text"}],"abstract":[{"text":"Informs the delegate when it starts scanning.","type":"text"}],"navigatorTitle":[{"text":"barcodeScanAndCountControllerDidStartScanning:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:polygonStyleForBarcode:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:polygonStyleForBarcode:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:polygonstyleforbarcode:)","title":"barcodeScanAndCount(_:polygonStyleForBarcode:)","role":"symbol","kind":"symbol","abstract":[{"text":"Asks the delegate to provide a custom barcode overlay polygon style for the given barcode.","type":"text"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeScanAndCount","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygonStyleForBarcode"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult"},{"kind":"text","text":") -> "},{"text":"SBSDKScanAndCountPolygonStyle","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKScanAndCountPolygonStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"barcodeScanAndCountController:polygonStyleForBarcode:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:overlayForBarcode:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:overlayForBarcode:)","abstract":[{"text":"Asks the delegate to provide the overlay view for a given code.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeScanAndCount","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeScanAndCountViewController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"kind":"text","text":", "},{"text":"overlayForBarcode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:overlayforbarcode:)","kind":"symbol","title":"barcodeScanAndCount(_:overlayForBarcode:)","navigatorTitle":[{"text":"barcodeScanAndCountController:overlayForBarcode:","kind":"identifier"}],"type":"topic","required":true,"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"role":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."},{"type":"text","text":" "},{"text":"Screen also shows snap, scan more and reset buttons.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"text":" ","type":"text"},{"text":"The snap button resets the scanning when tapped again.","type":"text"},{"text":" ","type":"text"},{"text":"Instead it is installing itself as a child view controller onto a given parent view controller.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","title":"SBSDKBarcodeScanAndCountViewController","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:didDetectBarcodes:)":{"type":"topic","required":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:didDetectBarcodes:)","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:diddetectbarcodes:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeScanAndCount","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier","text":"SBSDKBarcodeScanAndCountViewController"},{"kind":"text","text":", "},{"text":"didDetectBarcodes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"kind":"symbol","title":"barcodeScanAndCount(_:didDetectBarcodes:)","abstract":[{"type":"text","text":"Informs the delegate that the receiver has detected some barcodes."}],"navigatorTitle":[{"text":"barcodeScanAndCountController:didDetectBarcodes:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"title":"SBSDKBarcodeScanAndCountViewControllerDelegate","abstract":[{"text":"A delegate protocol to handle the barcode results from ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewController","isActive":true},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanAndCountViewControllerDelegate/barcodeScanAndCount(_:filterResults:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:filterResults:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanandcountviewcontrollerdelegate\/barcodescanandcount(_:filterresults:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeScanAndCount","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanAndCountViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"filterResults"},{"kind":"text","text":": ["},{"text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"barcodeScanAndCountController:filterResults:","kind":"identifier"}],"abstract":[{"type":"text","text":"Asks the delegate to filter the detected barcodes."}],"type":"topic","title":"barcodeScanAndCount(_:filterResults:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeScanAndCountViewControllerDelegate","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:didDetectBarcodes:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:filterResults:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:overlayForBarcode:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCount(_:polygonStyleForBarcode:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanAndCountViewControllerDelegate\/barcodeScanAndCountControllerDidStartScanning(_:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCountControllerDidStartScanning(_:)\/title","value":"barcodeScanAndCountControllerDidStartScanning:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"barcodeScanAndCountControllerDidStartScanning:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCountControllerDidStartScanning(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:polygonStyleForBarcode:)\/title","value":"barcodeScanAndCountController:polygonStyleForBarcode:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScanAndCountController:polygonStyleForBarcode:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:polygonStyleForBarcode:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:overlayForBarcode:)\/title","value":"barcodeScanAndCountController:overlayForBarcode:"},{"value":[{"kind":"text","text":"- "},{"text":"barcodeScanAndCountController:overlayForBarcode:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:overlayForBarcode:)\/fragments","op":"replace"},{"value":"SBSDKBarcodeScanAndCountViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/fragments"},{"value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle"},{"value":"barcodeScanAndCountController:didDetectBarcodes:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:didDetectBarcodes:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:didDetectBarcodes:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"barcodeScanAndCountController:didDetectBarcodes:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/title","value":"SBSDKBarcodeScanAndCountViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewControllerDelegate"}]},{"value":[{"text":"SBSDKBarcodeScanAndCountViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:filterResults:)\/title","op":"replace","value":"barcodeScanAndCountController:filterResults:"},{"value":[{"text":"- ","kind":"text"},{"text":"barcodeScanAndCountController:filterResults:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanAndCountViewControllerDelegate~1barcodeScanAndCount(_:filterResults:)\/fragments"}]}]}