{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/detected","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/idle","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/scanning"],"anchor":"Enumeration-Cases","generated":true},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/RawRepresentable-Implementations"]}],"metadata":{"title":"SBSDKScannerStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKScannerStatus"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"enum","navigatorTitle":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKScannerStatus","roleHeading":"Enumeration"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"This enum describes the possible scanning states of any scanner."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKScannerStatus","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus/detected":{"kind":"symbol","title":"SBSDKScannerStatus.detected","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/detected","navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatusDetected"}],"abstract":[{"type":"text","text":"The scanner has detected something."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detected","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/detected","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus/init(rawValue:)":{"abstract":[],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/Equatable-Implementations","kind":"article","abstract":[],"role":"collectionGroup","title":"Equatable Implementations","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"kind":"article","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus/idle":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/idle","abstract":[{"type":"text","text":"The scanner is paused or has not yet been started."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/idle","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatusIdle"}],"type":"topic","title":"SBSDKScannerStatus.idle"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus/scanning":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus\/scanning","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/scanning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanning"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatusScanning"}],"title":"SBSDKScannerStatus.scanning","abstract":[{"type":"text","text":"The scanner is active."}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKScannerStatus":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"role":"symbol","title":"SBSDKScannerStatus","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKScannerStatus"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkscannerstatus","abstract":[{"type":"text","text":"This enum describes the possible scanning states of any scanner."}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","value":"SBSDKScannerStatus","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"SBSDKScannerStatus","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKScannerStatus"}],"op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/detected","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/idle","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKScannerStatus\/scanning"],"anchor":"Enumeration-Cases","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKScannerStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus~1detected\/title","value":"SBSDKScannerStatusDetected","op":"replace"},{"value":[{"text":"SBSDKScannerStatusDetected","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus~1detected\/fragments","op":"replace"},{"value":"SBSDKScannerStatusIdle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus~1idle\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus~1idle\/fragments","value":[{"text":"SBSDKScannerStatusIdle","kind":"identifier"}]},{"value":"SBSDKScannerStatusScanning","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus~1scanning\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus~1scanning\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKScannerStatusScanning"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus\/title","value":"SBSDKScannerStatus"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus\/fragments","value":[{"kind":"identifier","text":"SBSDKScannerStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKScannerStatus\/navigatorTitle","value":[{"text":"SBSDKScannerStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}