{"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/init()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/arOverlay","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeImageVisible","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeInfoMapping","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeSubtitle","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeTitle","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/cancelButton","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/confirmationSheetEnabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/dividerColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/modalOverlayColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/sheetColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/submitButton"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/toJson()"]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeUseCase"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(SBSDKUI2SingleScanningMode) "},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Configuration of the single barcode scanning mode."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode","interfaceLanguage":"swift"},"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SingleScanningMode","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"title":"SBSDKUI2SingleScanningMode","role":"symbol"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/cancelButton":{"navigatorTitle":[{"kind":"identifier","text":"cancelButton"}],"role":"symbol","title":"cancelButton","abstract":[{"text":"Appearance of the cancel button on the confirmation sheet.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/cancelButton","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelButton","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/cancelbutton","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/dividerColor":{"navigatorTitle":[{"kind":"identifier","text":"dividerColor"}],"role":"symbol","abstract":[{"type":"text","text":"Color of the divider and separator lines in the confirmation sheet."},{"type":"text","text":" "},{"text":"Default is “?sbColorOutline”","type":"text"}],"title":"dividerColor","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/dividerColor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dividerColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/dividercolor","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeUseCase":{"navigatorTitle":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeusecase","abstract":[{"text":"Configuration of the barcode scanner screen’s behavior.","type":"text"}],"type":"topic","title":"SBSDKUI2BarcodeUseCase","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeUseCase"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/confirmationSheetEnabled":{"navigatorTitle":[{"kind":"identifier","text":"confirmationSheetEnabled"}],"role":"symbol","abstract":[{"type":"text","text":"If enabled, the confirmation sheet will be shown after the barcode has been scanned."},{"text":" ","type":"text"},{"text":"Default is false","type":"text"}],"title":"confirmationSheetEnabled","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/confirmationSheetEnabled","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationSheetEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/confirmationsheetenabled","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/barcodeImageVisible":{"navigatorTitle":[{"kind":"identifier","text":"barcodeImageVisible"}],"role":"symbol","title":"barcodeImageVisible","abstract":[{"type":"text","text":"If enabled, the barcode image will be shown on the confirmation sheet."},{"type":"text","text":" "},{"text":"Default is true","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeImageVisible","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeImageVisible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/barcodeimagevisible","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/barcodeInfoMapping":{"navigatorTitle":[{"kind":"identifier","text":"barcodeInfoMapping"}],"role":"symbol","abstract":[{"type":"text","text":"Appearance of the barcode info mapping."}],"title":"barcodeInfoMapping","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeInfoMapping","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeInfoMapping","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/barcodeinfomapping","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/barcodeTitle":{"navigatorTitle":[{"kind":"identifier","text":"barcodeTitle"}],"role":"symbol","abstract":[{"text":"Appearance of the barcode title (the barcode’s value) on the confirmation sheet.","type":"text"}],"title":"barcodeTitle","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeTitle","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/barcodetitle","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","title":"init()","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/init()","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/init()","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/sheetColor":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/sheetColor","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/sheetcolor","navigatorTitle":[{"kind":"identifier","text":"sheetColor"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sheetColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}],"title":"sheetColor","abstract":[{"text":"Color of the confirmation sheet’s background.","type":"text"},{"type":"text","text":" "},{"text":"Default is “?sbColorSurface”","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/barcodeSubtitle":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeSubtitle","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/barcodesubtitle","navigatorTitle":[{"text":"barcodeSubtitle","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"barcodeSubtitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"}],"title":"barcodeSubtitle","abstract":[{"text":"Appearance of the barcode subtitle (the barcode’s symbology) on the confirmation sheet.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/toJson()":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/toJson()","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/tojson()","navigatorTitle":[{"text":"toJson","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toJson","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"toJson()","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/arOverlay":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/arOverlay","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/aroverlay","navigatorTitle":[{"text":"arOverlay","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"arOverlay","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration"}],"title":"arOverlay","abstract":[{"text":"Configuration of the AR overlay.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/isEqual:":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"abstract":[],"title":"isEqual:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/isequal:"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/init(confirmationsheetenabled:barcodeimagevisible:sheetcolor:dividercolor:modaloverlaycolor:barcodetitle:barcodesubtitle:submitbutton:cancelbutton:barcodeinfomapping:aroverlay:)","navigatorTitle":[{"text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"confirmationSheetEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"barcodeImageVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"sheetColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dividerColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"modalOverlayColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"barcodeTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeSubtitle"},{"text":": ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"submitButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":", "},{"text":"cancelButton","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeInfoMapping"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeInfoMapping","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeInfoMapping"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"arOverlay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayGeneralConfiguration","text":"SBSDKUI2ArOverlayGeneralConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/submitButton":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/submitButton","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/submitbutton","navigatorTitle":[{"text":"submitButton","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"submitButton"},{"text":": ","kind":"text"},{"text":"SBSDKUI2ButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration"}],"title":"submitButton","abstract":[{"type":"text","text":"Appearance of the confirm button on the confirmation sheet."}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the single barcode scanning mode."}],"title":"SBSDKUI2SingleScanningMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/modalOverlayColor":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/modalOverlayColor","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/modaloverlaycolor","navigatorTitle":[{"text":"modalOverlayColor","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"modalOverlayColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"title":"modalOverlayColor","abstract":[{"type":"text","text":"Background color of the overlay surrounding the confirmation sheet."},{"text":" ","type":"text"},{"text":"Default is “?sbColorModalOverlay”","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/init(from:)":{"title":"init(from:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/init(from:)","abstract":[],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SingleScanningMode/hash":{"fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2singlescanningmode\/hash","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/hash","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2SingleScanningMode"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/arOverlay","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeImageVisible","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeInfoMapping","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeSubtitle","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/barcodeTitle","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/cancelButton","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/confirmationSheetEnabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/dividerColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/hash","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/modalOverlayColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/sheetColor","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/submitButton"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/init()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/isEqual:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SingleScanningMode\/toJson()"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeUseCase"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUI2SingleScanningMode","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeUseCase","text":"SBSDKUI2BarcodeUseCase","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeUseCase"}],"languages":["occ"]}]}},{"op":"replace","value":"cancelButton","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1cancelButton\/title"},{"value":[{"kind":"identifier","text":"cancelButton"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1cancelButton\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1dividerColor\/title","value":"dividerColor"},{"op":"replace","value":[{"kind":"identifier","text":"dividerColor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1dividerColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeUseCase\/title","value":"SBSDKUI2BarcodeUseCase"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeUseCase\/fragments"},{"value":"confirmationSheetEnabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1confirmationSheetEnabled\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1confirmationSheetEnabled\/fragments","value":[{"text":"confirmationSheetEnabled","kind":"identifier"}],"op":"replace"},{"value":"barcodeImageVisible","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1barcodeImageVisible\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1barcodeImageVisible\/fragments","op":"replace","value":[{"kind":"identifier","text":"barcodeImageVisible"}]},{"value":"barcodeInfoMapping","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1barcodeInfoMapping\/title","op":"replace"},{"value":[{"text":"barcodeInfoMapping","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1barcodeInfoMapping\/fragments"},{"value":"barcodeTitle","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1barcodeTitle\/title","op":"replace"},{"value":[{"text":"barcodeTitle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1barcodeTitle\/fragments"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1sheetColor\/title","op":"replace","value":"sheetColor"},{"value":[{"kind":"identifier","text":"sheetColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1sheetColor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1barcodeSubtitle\/title","op":"replace","value":"barcodeSubtitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1barcodeSubtitle\/fragments","value":[{"text":"barcodeSubtitle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1toJson()\/title","value":"toJson"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1toJson()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJson"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1arOverlay\/title","value":"arOverlay"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1arOverlay\/fragments","value":[{"kind":"identifier","text":"arOverlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)\/title","value":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithConfirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1init(confirmationSheetEnabled:barcodeImageVisible:sheetColor:dividerColor:modalOverlayColor:barcodeTitle:barcodeSubtitle:submitButton:cancelButton:barcodeInfoMapping:arOverlay:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1submitButton\/title","op":"replace","value":"submitButton"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1submitButton\/fragments","op":"replace","value":[{"text":"submitButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode\/title","value":"SBSDKUI2SingleScanningMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2SingleScanningMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1modalOverlayColor\/title","value":"modalOverlayColor","op":"replace"},{"value":[{"kind":"identifier","text":"modalOverlayColor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SingleScanningMode~1modalOverlayColor\/fragments"}]}]}