{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Medical Plan Patient Field Type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"}],"title":"SBSDKUI2MedicalPlanPatientFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanPatientFieldType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/allergiesAndIntolerances","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/birthDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/breastFeeding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/creatinineValue","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/firstName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/gender","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/height","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/lastName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/patientFreeText","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/patientId","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/preName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/pregnant","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/suffix","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/title","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/unknown","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/weight"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/title":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.title","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"}],"abstract":[{"type":"text","text":"Title"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/title","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeTitle"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/title"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/pregnant":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.pregnant","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pregnant"}],"abstract":[{"type":"text","text":"Pregnant"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/pregnant","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypePregnant"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/pregnant"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/patientFreeText":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.patientFreeText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"patientFreeText"}],"abstract":[{"type":"text","text":"Patient Free Text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/patientFreeText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypePatientFreeText"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/patientfreetext"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/creatinineValue":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.creatinineValue","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"creatinineValue"}],"abstract":[{"type":"text","text":"Creatinine Value"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/creatinineValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeCreatinineValue"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/creatininevalue"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/birthDate":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.birthDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"}],"abstract":[{"type":"text","text":"Birth Date"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/birthDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeBirthDate"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/birthdate"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/gender":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.gender","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gender"}],"abstract":[{"type":"text","text":"Gender"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/gender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeGender"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/gender"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/unknown":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeUnknown"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/unknown"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/preName":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.preName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preName"}],"abstract":[{"type":"text","text":"Pre Name"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/preName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypePreName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/prename"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/lastName":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.lastName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"abstract":[{"type":"text","text":"Last Name"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/lastName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeLastName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/lastname"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/breastFeeding":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.breastFeeding","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"breastFeeding"}],"abstract":[{"type":"text","text":"Breast Feeding"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/breastFeeding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeBreastFeeding"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/breastfeeding"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/suffix":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.suffix","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"suffix"}],"abstract":[{"type":"text","text":"Suffix"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/suffix","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeSuffix"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/suffix"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/height":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.height","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"}],"abstract":[{"type":"text","text":"Height"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/height","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeHeight"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/height"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/firstName":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.firstName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"abstract":[{"type":"text","text":"First Name"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/firstName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeFirstName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/firstname"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/allergiesAndIntolerances":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.allergiesAndIntolerances","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allergiesAndIntolerances"}],"abstract":[{"type":"text","text":"Allergies And Intolerances"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/allergiesAndIntolerances","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeAllergiesAndIntolerances"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/allergiesandintolerances"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/weight":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.weight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"weight"}],"abstract":[{"type":"text","text":"Weight"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/weight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeWeight"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/weight"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"}],"abstract":[{"type":"text","text":"Medical Plan Patient Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanPatientFieldType/patientId":{"role":"symbol","title":"SBSDKUI2MedicalPlanPatientFieldType.patientId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"patientId"}],"abstract":[{"type":"text","text":"Patient Id"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/patientId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypePatientId"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanpatientfieldtype\/patientid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalPlanPatientFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/allergiesAndIntolerances","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/birthDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/breastFeeding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/creatinineValue","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/firstName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/gender","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/height","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/lastName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/patientFreeText","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/patientId","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/preName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/pregnant","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/suffix","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/title","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/unknown","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanPatientFieldType\/weight"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1title\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1title\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1pregnant\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypePregnant"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1pregnant\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypePregnant"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1patientFreeText\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypePatientFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1patientFreeText\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypePatientFreeText"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1creatinineValue\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeCreatinineValue"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1creatinineValue\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeCreatinineValue"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1birthDate\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeBirthDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1birthDate\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeBirthDate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1gender\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeGender"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1gender\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeGender"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1unknown\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1unknown\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1preName\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypePreName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1preName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypePreName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1lastName\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeLastName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1lastName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeLastName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1breastFeeding\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeBreastFeeding"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1breastFeeding\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeBreastFeeding"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1suffix\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeSuffix"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1suffix\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeSuffix"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1height\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeHeight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1height\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1firstName\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1firstName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeFirstName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1allergiesAndIntolerances\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeAllergiesAndIntolerances"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1allergiesAndIntolerances\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeAllergiesAndIntolerances"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1weight\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypeWeight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1weight\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypeWeight"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType\/title","value":"SBSDKUI2MedicalPlanPatientFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1patientId\/title","value":"SBSDKUI2MedicalPlanPatientFieldTypePatientId"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanPatientFieldType~1patientId\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanPatientFieldTypePatientId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}