{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/init()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/init(from:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/init(sbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:)"],"anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorModalOverlay","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorNegative","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnPrimary","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSecondary","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSurface","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSurfaceVariant","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOutline","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPositive","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPrimary","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPrimaryDisabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSecondary","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSecondaryDisabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurface","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurfaceHigh","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurfaceLow","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorWarning"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/toJson()"],"generated":true,"anchor":"Instance-Methods"}],"metadata":{"roleHeading":"Class","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Palette","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Palette","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2Palette","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"symbolKind":"class"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"abstract":[{"text":"Value palette describing the colors of the scanner screens.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2Palette) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Palette","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorOutline":{"title":"sbColorOutline","kind":"symbol","navigatorTitle":[{"text":"sbColorOutline","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcoloroutline","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sbColorOutline","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOutline","type":"topic","abstract":[{"type":"text","text":"Color used for outlines."},{"type":"text","text":" "},{"type":"text","text":"Default is “#EFEFEF”"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"type":"topic","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/hash","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/hash","title":"hash"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/fromJsonWithJson:":{"title":"fromJsonWithJson:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/fromjsonwithjson:","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/fromJsonWithJson:","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/isEqual:":{"title":"isEqual:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/isequal:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/isEqual:","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorSurfaceLow":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbColorSurfaceLow","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"type":"topic","abstract":[{"type":"text","text":"Transparent color with a low alpha value used for certain surfaces."},{"type":"text","text":" "},{"type":"text","text":"Default is “#00000026”"}],"navigatorTitle":[{"text":"sbColorSurfaceLow","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorsurfacelow","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurfaceLow","title":"sbColorSurfaceLow"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorSecondaryDisabled":{"title":"sbColorSecondaryDisabled","kind":"symbol","navigatorTitle":[{"text":"sbColorSecondaryDisabled","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorsecondarydisabled","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbColorSecondaryDisabled"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSecondaryDisabled","type":"topic","abstract":[{"text":"Secondary color used for disabled elements.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “#F5F5F5”"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorPrimary":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sbColorPrimary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"type":"topic","abstract":[{"type":"text","text":"Primary color used for enabled elements."},{"type":"text","text":" "},{"text":"Default is “#C8193C”","type":"text"}],"navigatorTitle":[{"text":"sbColorPrimary","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorprimary","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPrimary","title":"sbColorPrimary"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorModalOverlay":{"title":"sbColorModalOverlay","kind":"symbol","navigatorTitle":[{"text":"sbColorModalOverlay","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolormodaloverlay","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbColorModalOverlay"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorModalOverlay","type":"topic","abstract":[{"text":"Transparent color with a very high alpha value used to fill certain overlays.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “#000000A3”"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorSecondary":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sbColorSecondary"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sbColorSecondary","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"kind":"symbol","title":"sbColorSecondary","abstract":[{"text":"Secondary color used for enabled elements.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “#FFEDEE”"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSecondary","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorsecondary"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorPositive":{"title":"sbColorPositive","kind":"symbol","navigatorTitle":[{"text":"sbColorPositive","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorpositive","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbColorPositive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPositive","type":"topic","abstract":[{"text":"Color used to convey a positive meaning.","type":"text"},{"type":"text","text":" "},{"text":"Default is “#4EFFB4”","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorWarning":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbColorWarning"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Color used to convey warnings.","type":"text"},{"type":"text","text":" "},{"text":"Default is “#FFCE5C”","type":"text"}],"navigatorTitle":[{"text":"sbColorWarning","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorwarning","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorWarning","title":"sbColorWarning"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/init(from:)":{"title":"init(from:)","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/init(from:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/init(from:)","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/init(sbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"sbColorPrimary","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"sbColorPrimaryDisabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"text":"sbColorNegative","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sbColorPositive"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sbColorWarning"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sbColorSecondary"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sbColorSecondaryDisabled"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"sbColorOnPrimary","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"sbColorOnSecondary","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"sbColorSurface","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sbColorOutline"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sbColorOnSurfaceVariant"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"sbColorOnSurface","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sbColorSurfaceLow"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sbColorSurfaceHigh"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sbColorModalOverlay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/init(sbcolorprimary:sbcolorprimarydisabled:sbcolornegative:sbcolorpositive:sbcolorwarning:sbcolorsecondary:sbcolorsecondarydisabled:sbcoloronprimary:sbcoloronsecondary:sbcolorsurface:sbcoloroutline:sbcoloronsurfacevariant:sbcoloronsurface:s-8zcpt","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/init(sbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:)","title":"init(sbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Node":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2node","title":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Node","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Abstract class for all the configurations.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorNegative":{"title":"sbColorNegative","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sbColorNegative"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolornegative","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbColorNegative"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorNegative","type":"topic","abstract":[{"text":"Color used to convey a negative meaning.","type":"text"},{"type":"text","text":" "},{"text":"Default is “#FF3737”","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorOnPrimary":{"title":"sbColorOnPrimary","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sbColorOnPrimary"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcoloronprimary","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sbColorOnPrimary"},{"kind":"text","text":": "},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnPrimary","type":"topic","abstract":[{"text":"Color used for displaying elements on top of the primary color.","type":"text"},{"type":"text","text":" "},{"text":"Default is “#FFFFFF”","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorOnSurface":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcoloronsurface","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSurface","role":"symbol","navigatorTitle":[{"text":"sbColorOnSurface","kind":"identifier"}],"abstract":[{"type":"text","text":"Color used on top of surfaces."},{"text":" ","type":"text"},{"text":"Default is “#000000”","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbColorOnSurface","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"}],"title":"sbColorOnSurface"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorOnSurfaceVariant":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbColorOnSurfaceVariant"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"type":"topic","abstract":[{"text":"Alternative color used on top of surfaces.","type":"text"},{"type":"text","text":" "},{"text":"Default is “#707070”","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sbColorOnSurfaceVariant"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcoloronsurfacevariant","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSurfaceVariant","title":"sbColorOnSurfaceVariant"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/toJson()":{"title":"toJson()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"toJson"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/tojson()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJson"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/toJson()","type":"topic","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Palette","kind":"identifier"}],"title":"SBSDKUI2Palette"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorOnSecondary":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sbColorOnSecondary","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"}],"type":"topic","abstract":[{"text":"Color used for displaying elements on top of the secondary color.","type":"text"},{"type":"text","text":" "},{"text":"Default is “#C8193C”","type":"text"}],"navigatorTitle":[{"text":"sbColorOnSecondary","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcoloronsecondary","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSecondary","title":"sbColorOnSecondary"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorSurfaceHigh":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbColorSurfaceHigh"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"type":"topic","abstract":[{"text":"Transparent color with a high alpha value used for certain surfaces.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is “#0000007A”"}],"navigatorTitle":[{"kind":"identifier","text":"sbColorSurfaceHigh"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorsurfacehigh","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurfaceHigh","title":"sbColorSurfaceHigh"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorPrimaryDisabled":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sbColorPrimaryDisabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"}],"kind":"symbol","type":"topic","title":"sbColorPrimaryDisabled","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorprimarydisabled","abstract":[{"text":"Primary color used for disabled elements.","type":"text"},{"text":" ","type":"text"},{"text":"Default is “#F5F5F5”","type":"text"}],"navigatorTitle":[{"text":"sbColorPrimaryDisabled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPrimaryDisabled"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/init()":{"title":"init()","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/init()","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/sbColorSurface":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbColorSurface","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"}],"type":"topic","abstract":[{"type":"text","text":"Color used for surfaces."},{"text":" ","type":"text"},{"text":"Default is “#FFFFFF”","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sbColorSurface"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/sbcolorsurface","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurface","title":"sbColorSurface"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"SBSDKUI2Palette","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/hash","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorModalOverlay","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorNegative","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnPrimary","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSecondary","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSurface","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOnSurfaceVariant","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorOutline","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPositive","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPrimary","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorPrimaryDisabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSecondary","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSecondaryDisabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurface","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurfaceHigh","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorSurfaceLow","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/sbColorWarning"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/init()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/init(sbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/isEqual:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/toJson()"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/fromJsonWithJson:"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SBSDKUI2Palette","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SBSDKUI2Node","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Node"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOutline\/title","value":"sbColorOutline"},{"op":"replace","value":[{"text":"sbColorOutline","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOutline\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSurfaceLow\/title","op":"replace","value":"sbColorSurfaceLow"},{"value":[{"kind":"identifier","text":"sbColorSurfaceLow"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSurfaceLow\/fragments","op":"replace"},{"value":"sbColorSecondaryDisabled","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSecondaryDisabled\/title"},{"value":[{"text":"sbColorSecondaryDisabled","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSecondaryDisabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorPrimary\/title","value":"sbColorPrimary","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorPrimary\/fragments","value":[{"text":"sbColorPrimary","kind":"identifier"}]},{"value":"sbColorModalOverlay","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorModalOverlay\/title"},{"value":[{"text":"sbColorModalOverlay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorModalOverlay\/fragments"},{"op":"replace","value":"sbColorSecondary","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSecondary\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSecondary\/fragments","value":[{"kind":"identifier","text":"sbColorSecondary"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorPositive\/title","value":"sbColorPositive","op":"replace"},{"value":[{"kind":"identifier","text":"sbColorPositive"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorPositive\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorWarning\/title","value":"sbColorWarning","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorWarning\/fragments","value":[{"kind":"identifier","text":"sbColorWarning"}]},{"op":"replace","value":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1init(sbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1init(sbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSbColorPrimary:sbColorPrimaryDisabled:sbColorNegative:sbColorPositive:sbColorWarning:sbColorSecondary:sbColorSecondaryDisabled:sbColorOnPrimary:sbColorOnSecondary:sbColorSurface:sbColorOutline:sbColorOnSurfaceVariant:sbColorOnSurface:sbColorSurfaceLow:sbColorSurfaceHigh:sbColorModalOverlay:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/title","op":"replace","value":"SBSDKUI2Node"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/fragments","op":"replace","value":[{"text":"SBSDKUI2Node","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"value":"sbColorNegative","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorNegative\/title"},{"value":[{"kind":"identifier","text":"sbColorNegative"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorNegative\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOnPrimary\/title","value":"sbColorOnPrimary"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOnPrimary\/fragments","value":[{"kind":"identifier","text":"sbColorOnPrimary"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOnSurface\/title","value":"sbColorOnSurface","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOnSurface\/fragments","value":[{"text":"sbColorOnSurface","kind":"identifier"}]},{"value":"sbColorOnSurfaceVariant","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOnSurfaceVariant\/title","op":"replace"},{"value":[{"text":"sbColorOnSurfaceVariant","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOnSurfaceVariant\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1toJson()\/title","value":"toJson","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"toJson","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1toJson()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/title","value":"SBSDKUI2Palette"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/fragments","value":[{"text":"SBSDKUI2Palette","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2Palette"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOnSecondary\/title","value":"sbColorOnSecondary"},{"op":"replace","value":[{"kind":"identifier","text":"sbColorOnSecondary"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorOnSecondary\/fragments"},{"value":"sbColorSurfaceHigh","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSurfaceHigh\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSurfaceHigh\/fragments","value":[{"kind":"identifier","text":"sbColorSurfaceHigh"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorPrimaryDisabled\/title","value":"sbColorPrimaryDisabled","op":"replace"},{"value":[{"kind":"identifier","text":"sbColorPrimaryDisabled"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorPrimaryDisabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSurface\/title","value":"sbColorSurface"},{"value":[{"text":"sbColorSurface","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette~1sbColorSurface\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}