{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Configuration for the popup menu items."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/init()"],"generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/accessibilityDescription","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/icon","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/title"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2PopupMenuItem) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PopupMenuItem"}],"symbolKind":"class","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2PopupMenuItem","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","title":"SBSDKUI2PopupMenuItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2PopupMenuItem"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/accessibilityDescription":{"kind":"symbol","type":"topic","abstract":[{"text":"The text to be read when the button is selected through accessibility mode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/accessibilityDescription","title":"accessibilityDescription","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/accessibilitydescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"accessibilityDescription","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Node":{"kind":"symbol","abstract":[{"type":"text","text":"Abstract class for all the configurations."}],"navigatorTitle":[{"text":"SBSDKUI2Node","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2node","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node","title":"SBSDKUI2Node","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Node"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/title":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/title","navigatorTitle":[{"text":"title","kind":"identifier"}],"title":"title","role":"symbol","abstract":[{"type":"text","text":"The text to be displayed on the button."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/title","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/toJson(configuration:)":{"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/tojson(configuration:)","kind":"symbol","title":"toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/toJson(configuration:)","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/isEqual:":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/isEqual:","title":"isEqual:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/isequal:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/copyWithZone:":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/copyWithZone:","title":"copyWithZone:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/copywithzone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/fromjsonwithjson:","kind":"symbol","title":"fromJsonWithJson:","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/fromJsonWithJson:","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/hash":{"kind":"symbol","title":"hash","abstract":[],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/hash","fragments":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/hash","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/icon":{"navigatorTitle":[{"text":"icon","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icon"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2IconStyle","text":"SBSDKUI2IconStyle","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/icon","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the icon appearance."}],"title":"icon","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/icon","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/initWithTitle:accessibilityDescription:icon:":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTitle:accessibilityDescription:icon:"}],"title":"initWithTitle:accessibilityDescription:icon:","abstract":[],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/initwithtitle:accessibilitydescription:icon:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTitle:accessibilityDescription:icon:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/initWithTitle:accessibilityDescription:icon:","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem/init()":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","abstract":[],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/init()","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2PopupMenuItem":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration for the popup menu items."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2popupmenuitem","title":"SBSDKUI2PopupMenuItem"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2PopupMenuItem"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/accessibilityDescription","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/hash","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/icon","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/title"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/copyWithZone:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/init()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/initWithTitle:accessibilityDescription:icon:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/isEqual:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/toJson(configuration:)"],"generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2PopupMenuItem\/fromJsonWithJson:"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCopying"],"title":"Conforms To"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"},{"kind":"text","text":" : "},{"text":"SBSDKUI2Node","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Node","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Node"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1accessibilityDescription\/title","value":"accessibilityDescription"},{"value":[{"text":"accessibilityDescription","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1accessibilityDescription\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/title","value":"SBSDKUI2Node"},{"value":[{"kind":"identifier","text":"SBSDKUI2Node"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Node\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Node"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1title\/title","value":"title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1title\/fragments","op":"replace","value":[{"text":"title","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:"},{"value":[{"kind":"text","text":"- "},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1toJson(configuration:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1icon\/title","op":"replace","value":"icon"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1icon\/fragments","value":[{"text":"icon","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"value":"SBSDKUI2PopupMenuItem","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem\/title"},{"value":[{"text":"SBSDKUI2PopupMenuItem","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2PopupMenuItem\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2PopupMenuItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}