{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKGS1Handling","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGS1Handling","kind":"identifier"}],"title":"SBSDKGS1Handling"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeFull","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeStructure","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/parse","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/validateFull","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/validateStructure"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/init(rawValue:)"],"title":"Initializers","generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"GS1 message handling options."},{"type":"text","text":" "},{"text":"The GS1 standard defines a a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"type":"text","text":" "},{"type":"text","text":"barcode types."},{"text":" ","type":"text"},{"type":"text","text":"https:\/\/ref.gs1.org\/standards\/genspecs\/"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKGS1Handling) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"GS1 messages have two representations or formats: a human-readable format and a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"machine-readable format. The human-readable format uses parentheses to wrap the keys in each"},{"type":"text","text":" "},{"text":"pair. For example, the string “(01)012345678901(37)02(3922)00278” contains three AI keys:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"01, 37, and 3922. The corresponding values are 012345678901, 02, and 00278."}],"type":"paragraph"},{"inlineContent":[{"text":"The machine-readable format uses the special ASCII \\x1D character to terminate key-value","type":"text"},{"type":"text","text":" "},{"text":"pairs in the string in cases where the given key implies that the value is variable-length.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The equivalent machine-readable string for the above example is"},{"type":"text","text":" "},{"text":"“010123456789013702\\x1D392200278”.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In the above example, the 01 AI key is fixed-length, so the \\x1D character is not necessary."},{"text":" ","type":"text"},{"text":"The 37 AI keys is variable-length, so the \\x1D character is necessary after the value in the","type":"text"},{"type":"text","text":" "},{"text":"pair. The 3922 AI key is also variable-length, but it is the last pair in the message, so","type":"text"},{"text":" ","type":"text"},{"text":"the \\x1D character is not necessary at the end.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The character \\x1D is UNPRINTABLE - this means that if you try to print or otherwise","type":"text"},{"type":"text","text":" "},{"text":"visualize a GS1 message containing the \\x1D character, you may see a number of different","type":"text"},{"type":"text","text":" "},{"text":"results, depending on how the system handles unprintable characters. You may see a question","type":"text"},{"type":"text","text":" "},{"type":"text","text":"mark, a box, an escape sequence, a space or nothing at all."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/Equatable-Implementations","role":"collectionGroup","kind":"article"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/decodeStructure":{"kind":"symbol","abstract":[{"text":"Same as VALIDATE_STRUCTURE. Additionally, GS1 strings are converted to the human-readable format,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"instead (with parentheses used to wrap AI keys, e.g. “(01)123456789”). The \\x1D character is"},{"type":"text","text":" "},{"text":"never used in this representation.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeStructure"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeStructure","title":"SBSDKGS1Handling.decodeStructure","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeStructure"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decodestructure","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/init(rawValue:)":{"kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/init(rawvalue:)","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/decodeFull":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeFull"}],"title":"SBSDKGS1Handling.decodeFull","type":"topic","abstract":[{"type":"text","text":"Combines the validations of VALIDATE_FULL and the human-readable output format of DECODE_STRUCTURE."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/decodefull","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeFull","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeFull"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/validateStructure":{"kind":"symbol","abstract":[{"type":"text","text":"Same as PARSE. Additionally, messages containing unknown AI keys, or containing values"},{"type":"text","text":" "},{"text":"that don’t fulfill the length, character set or regex requirements for known keys, are rejected.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validateStructure"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/validateStructure","title":"SBSDKGS1Handling.validateStructure","navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1HandlingValidateStructure"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/validatestructure","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/RawRepresentable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/rawrepresentable-implementations","role":"collectionGroup"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/validateFull":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateFull"}],"title":"SBSDKGS1Handling.validateFull","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/validatefull","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/validateFull","abstract":[{"text":"Includes all validations from VALIDATE_STRUCTURE. Additionally, GS1 messages which have missing or incompatible","type":"text"},{"type":"text","text":" "},{"type":"text","text":"combinations of AI keys are rejected. Additionally, values are checked against a list of known linting rules,"},{"text":" ","type":"text"},{"text":"e.g. checksums are calculated and verified, dates are checked for validity, etc. Results that fail any of the","type":"text"},{"type":"text","text":" "},{"text":"linter rules are rejected. The complete set of linter rules from the GS1 Syntax Dictionary are implemented.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKGS1HandlingValidateFull","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling/parse":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"parse","kind":"identifier"}],"title":"SBSDKGS1Handling.parse","type":"topic","abstract":[{"type":"text","text":"This is the default. GS1 messages are converted to the machine-readable format per"},{"text":" ","type":"text"},{"text":"the GS1 spec (the special FNC1 character is converted to ASCII \\x1D).","type":"text"},{"type":"text","text":" "},{"text":"The implied 01 AI key is prepended to DataBar results.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"No validation is performed."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling\/parse","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/parse","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKGS1Handling":{"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGS1Handling","kind":"identifier"}],"title":"SBSDKGS1Handling","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkgs1handling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling","abstract":[{"text":"GS1 message handling options.","type":"text"},{"text":" ","type":"text"},{"text":"The GS1 standard defines a a key-value format for business-centric data that can be encoded into many 1D and 2D","type":"text"},{"type":"text","text":" "},{"text":"barcode types.","type":"text"},{"text":" ","type":"text"},{"text":"https:\/\/ref.gs1.org\/standards\/genspecs\/","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"SBSDKGS1Handling","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeFull","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/decodeStructure","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/parse","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/validateFull","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKGS1Handling\/validateStructure"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKGS1Handling","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decodeStructure\/title","op":"replace","value":"SBSDKGS1HandlingDecodeStructure"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decodeStructure\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGS1HandlingDecodeStructure"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decodeFull\/title","value":"SBSDKGS1HandlingDecodeFull"},{"op":"replace","value":[{"text":"SBSDKGS1HandlingDecodeFull","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1decodeFull\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1validateStructure\/title","value":"SBSDKGS1HandlingValidateStructure","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1validateStructure\/fragments","value":[{"text":"SBSDKGS1HandlingValidateStructure","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1validateFull\/title","value":"SBSDKGS1HandlingValidateFull"},{"value":[{"text":"SBSDKGS1HandlingValidateFull","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1validateFull\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1parse\/title","value":"SBSDKGS1HandlingParse","op":"replace"},{"value":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling~1parse\/fragments","op":"replace"},{"value":"SBSDKGS1Handling","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/title","op":"replace"},{"value":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKGS1Handling\/navigatorTitle","op":"replace"}]}]}