{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemMapper\/mapBarcodeItem(item:onResult:onError:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemmapper"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemmapper"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemMapper"},"metadata":{"roleHeading":"Protocol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUI2BarcodeItemMapper","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKUI2BarcodeItemMapper","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"Maps a barcode’s data to the data of the corresponding product."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemMapper":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemmapper","abstract":[{"type":"text","text":"Maps a barcode’s data to the data of the corresponding product."}],"title":"SBSDKUI2BarcodeItemMapper","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemMapper","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeItemMapper/mapBarcodeItem(item:onResult:onError:)":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodeitemmapper\/mapbarcodeitem(item:onresult:onerror:)","abstract":[{"text":"Function that maps a barcode’s data to the data of the corresponding product.","type":"text"}],"title":"mapBarcodeItem(item:onResult:onError:)","required":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemMapper\/mapBarcodeItem(item:onResult:onError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapBarcodeItem"},{"text":"(","kind":"text"},{"text":"item","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeItem","kind":"typeIdentifier","text":"SBSDKUI2BarcodeItem"},{"kind":"text","text":", "},{"text":"onResult","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeMappedData","text":"SBSDKUI2BarcodeMappedData","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"text":"onError","kind":"externalParam"},{"kind":"text","text":": () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mapBarcodeItemWithItem:onResult:onError:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2BarcodeItemMapper"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeItemMapper\/mapBarcodeItem(item:onResult:onError:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeItemMapper","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SBSDKUI2BarcodeItemMapper","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemMapper\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemMapper"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemMapper\/fragments","op":"replace"},{"value":"mapBarcodeItemWithItem:onResult:onError:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemMapper~1mapBarcodeItem(item:onResult:onError:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeItemMapper~1mapBarcodeItem(item:onResult:onError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"mapBarcodeItemWithItem:onResult:onError:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}