{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Medical Plan Standard Subheading Field Type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"title":"SBSDKUI2MedicalPlanStandardSubheadingFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MedicalPlanStandardSubheadingFieldType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/keyWords","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/subheadingFreeText"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingFieldType":{"role":"symbol","title":"SBSDKUI2MedicalPlanStandardSubheadingFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"abstract":[{"type":"text","text":"Medical Plan Standard Subheading Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingFieldType/keyWords":{"role":"symbol","title":"SBSDKUI2MedicalPlanStandardSubheadingFieldType.keyWords","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyWords"}],"abstract":[{"type":"text","text":"Key words"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/keyWords","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldTypeKeyWords"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype\/keywords"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingFieldType/subheadingFreeText":{"role":"symbol","title":"SBSDKUI2MedicalPlanStandardSubheadingFieldType.subheadingFreeText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subheadingFreeText"}],"abstract":[{"type":"text","text":"Subheading free text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/subheadingFreeText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype\/subheadingfreetext"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MedicalPlanStandardSubheadingFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2medicalplanstandardsubheadingfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/keyWords","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MedicalPlanStandardSubheadingFieldType\/subheadingFreeText"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingFieldType\/title","value":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingFieldType~1keyWords\/title","value":"SBSDKUI2MedicalPlanStandardSubheadingFieldTypeKeyWords"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingFieldType~1keyWords\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldTypeKeyWords"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingFieldType~1subheadingFreeText\/title","value":"SBSDKUI2MedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MedicalPlanStandardSubheadingFieldType~1subheadingFreeText\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanStandardSubheadingFieldTypeSubheadingFreeText"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}