{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Typealias for license failure handling closure.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseFailureHandler"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdklicensefailurehandler"]}],"kind":"symbol","metadata":{"title":"SBSDKLicenseFailureHandler","externalID":"s:24ScanbotBarcodeScannerSDK26SBSDKLicenseFailureHandlera","navigatorTitle":[{"text":"SBSDKLicenseFailureHandler","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseFailureHandler"}],"roleHeading":"Type Alias"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseFailureHandler"},{"kind":"text","text":" = ("},{"text":"SBSDKLicenseStatus","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKLicenseStatus"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature","text":"SBSDKFeature","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> ()"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature","title":"SBSDKFeature","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}],"type":"topic","abstract":[{"text":"The features that are activated in the ScanbotSDK license.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseFailureHandler":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseFailureHandler","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensefailurehandler","abstract":[{"text":"Typealias for license failure handling closure.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseFailureHandler","kind":"identifier"}],"title":"SBSDKLicenseFailureHandler","navigatorTitle":[{"text":"SBSDKLicenseFailureHandler","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKLicenseStatus":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdklicensestatus","title":"SBSDKLicenseStatus","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKLicenseStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"kind":"symbol","abstract":[{"text":"The status of the ScanbotSDK license.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKFeature","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKFeature"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/navigatorTitle","op":"replace","value":[{"text":"SBSDKFeature","kind":"identifier"}]},{"op":"replace","value":"SBSDKLicenseStatus","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKLicenseStatus\/navigatorTitle","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"op":"replace"}]}]}