{"metadata":{"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"roleHeading":"Protocol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIBarcodesBatchScannerViewControllerDelegate","title":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","role":"symbol","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"platforms":[],"symbolKind":"protocol"},"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}],"type":"paragraph"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate"},"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewControllerDelegate"],"title":"Inherits From","kind":"relationships"}],"sections":[],"abstract":[{"text":"Delegate protocol for ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"kind":"symbol","topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewController(_:didFinishWith:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewControllerDidCancel(_:)"],"title":"Instance Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIViewControllerDelegate","text":"SBSDKUIViewControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewControllerDelegate"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"symbol","abstract":[{"type":"text","text":"Delegate protocol for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewControllerDelegate":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewControllerDelegate","title":"SBSDKUIViewControllerDelegate","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontrollerdelegate","abstract":[{"text":"The general delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController"},{"type":"text","text":"-based classes."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewControllerDelegate/barcodesBatchScannerViewControllerDidCancel(_:)":{"navigatorTitle":[{"text":"barcodesBatchScannerViewControllerDidCancel:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Informs the delegate that the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController"},{"text":" has been cancelled and dismissed.","type":"text"}],"required":true,"kind":"symbol","title":"barcodesBatchScannerViewControllerDidCancel(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodesBatchScannerViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewControllerDidCancel(_:)","deprecated":true,"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate\/barcodesbatchscannerviewcontrollerdidcancel(_:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"title":"SBSDKUIBarcodesBatchScannerViewController","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to detect barcodes batches."}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewControllerDelegate/barcodesBatchScannerViewController(_:didFinishWith:)":{"title":"barcodesBatchScannerViewController(_:didFinishWith:)","deprecated":true,"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewController(_:didFinishWith:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"barcodesBatchScannerViewController:didFinishWithResults:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontrollerdelegate\/barcodesbatchscannerviewcontroller(_:didfinishwith:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodesBatchScannerViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController","text":"SBSDKUIBarcodesBatchScannerViewController"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeMappedResult","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeMappedResult"},{"text":"])","kind":"text"}],"abstract":[{"text":"Informs the delegate that one or more barcodes have been detected and the view controller has dismissed.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewController":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"title":"SBSDKUIViewController","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}],"abstract":[{"text":"An abstract base class for RTU-UI view controllers.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.1.0","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewController(_:didFinishWith:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewControllerDelegate\/barcodesBatchScannerViewControllerDidCancel(_:)"],"title":"Instance Methods","generated":true}],"op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewControllerDelegate"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"SBSDKUIViewControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIViewControllerDelegate"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewControllerDelegate\/title","op":"replace","value":"SBSDKUIViewControllerDelegate"},{"value":[{"kind":"identifier","text":"SBSDKUIViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewControllerDelegate\/fragments","op":"replace"},{"value":[{"text":"SBSDKUIViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewControllerDelegate\/navigatorTitle"},{"value":"barcodesBatchScannerViewControllerDidCancel:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate~1barcodesBatchScannerViewControllerDidCancel(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate~1barcodesBatchScannerViewControllerDidCancel(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodesBatchScannerViewControllerDidCancel:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/title","value":"SBSDKUIBarcodesBatchScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}]},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate~1barcodesBatchScannerViewController(_:didFinishWith:)\/title","value":"barcodesBatchScannerViewController:didFinishWithResults:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewControllerDelegate~1barcodesBatchScannerViewController(_:didFinishWith:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodesBatchScannerViewController:didFinishWithResults:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/title","op":"replace","value":"SBSDKUIViewController"},{"op":"replace","value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/navigatorTitle","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}