{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"title":"SBSDKUIBarcodesBatchScannerViewController","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController","platforms":[],"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"roleHeading":"Class"},"abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan barcodes batches."}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/dataMapper","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/delegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/isScanningEnabled"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/freezeCamera()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/unfreezeCamera()"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/present(on:configuration:delegate:)"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCoding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8CopyableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8SendableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearanceContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIContentContainer","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusEnvironment","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIScrollViewDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIStateRestoring","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITableViewDataSource","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITableViewDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITraitEnvironment","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIUserActivityRestoring","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIViewControllerTransitioningDelegate"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController","interfaceLanguage":"swift"},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeScannerController:filterBarcodes:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerController:filterBarcodes:","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"barcodeScannerController:filterBarcodes:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:filterBarcodes:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontroller:filterbarcodes:","title":"barcodeScannerController:filterBarcodes:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/didHideEnableCameraView":{"abstract":[],"title":"didHideEnableCameraView","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/didHideEnableCameraView","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"didHideEnableCameraView","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/didhideenablecameraview","navigatorTitle":[{"kind":"identifier","text":"didHideEnableCameraView"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/animationControllerForPresentedController:presentingController:sourceController:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"animationControllerForPresentedController:presentingController:sourceController:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/animationControllerForPresentedController:presentingController:sourceController:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/animationcontrollerforpresentedcontroller:presentingcontroller:sourcecontroller:","title":"animationControllerForPresentedController:presentingController:sourceController:","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"animationControllerForPresentedController:presentingController:sourceController:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/tableView:heightForRowAtIndexPath:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/tableView:heightForRowAtIndexPath:","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"tableView:heightForRowAtIndexPath:","kind":"identifier"}],"title":"tableView:heightForRowAtIndexPath:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/tableview:heightforrowatindexpath:","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForRowAtIndexPath:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewControllerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"kind":"symbol","type":"topic","abstract":[{"text":"The delegate protocol of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","isActive":true,"type":"reference"},{"text":" that provides methods for","type":"text"},{"text":" ","type":"text"},{"text":"enabling\/disabling scanning and managing scanned barcodes.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"title":"SBSDKBarcodeScannerViewControllerDelegate"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/freezeCamera()":{"type":"topic","deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"freezeCamera"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/freezecamera()","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/freezeCamera()","role":"symbol","title":"freezeCamera()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeCamera"},{"kind":"text","text":"()"}],"abstract":[{"text":"Freezes the cameras preview layer by stopping the camera session.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/interactionControllerForDismissal:":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/interactioncontrollerfordismissal:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interactionControllerForDismissal:"}],"title":"interactionControllerForDismissal:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interactionControllerForDismissal:"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/interactionControllerForDismissal:","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeTrackingOverlay:textStyleFor:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodetrackingoverlay:textstylefor:","kind":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"barcodeTrackingOverlay:textStyleFor:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:textStyleFor:","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:textStyleFor:"}],"title":"barcodeTrackingOverlay:textStyleFor:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/delegate":{"deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/delegate","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/delegate","abstract":[{"type":"text","text":"The receivers delegate."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIBarcodesBatchScannerViewControllerDelegate","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIViewControllerTransitioningDelegate":{"type":"unresolvable","title":"UIViewControllerTransitioningDelegate","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeScannerController:didScanBarcodes:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScannerController:didScanBarcodes:"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontroller:didscanbarcodes:","title":"barcodeScannerController:didScanBarcodes:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerController:didScanBarcodes:","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"barcodeScannerController:didScanBarcodes:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/initWithCoder:":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/initwithcoder:","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/initWithCoder:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeTrackingOverlay:didTapOnBarcode:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:didTapOnBarcode:","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:didTapOnBarcode:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodetrackingoverlay:didtaponbarcode:","title":"barcodeTrackingOverlay:didTapOnBarcode:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/tableView:numberOfRowsInSection:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/tableView:numberOfRowsInSection:","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/tableview:numberofrowsinsection:","title":"tableView:numberOfRowsInSection:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/supportedInterfaceOrientations":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/supportedInterfaceOrientations","title":"supportedInterfaceOrientations","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"supportedInterfaceOrientations"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/supportedinterfaceorientations"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UITableViewDataSource","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITableViewDataSource"},"doc://net.doo.ScanbotBarcodeScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}],"title":"SBSDKUIViewController","navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuiviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/enableCameraUIConfiguration":{"fragments":[{"text":"enableCameraUIConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/enablecamerauiconfiguration","type":"topic","role":"symbol","title":"enableCameraUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/enableCameraUIConfiguration","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UITableViewDelegate":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITableViewDelegate","title":"UITableViewDelegate","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/updateFlashButton":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/updateflashbutton","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"updateFlashButton","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/updateFlashButton","navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}],"title":"updateFlashButton","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIFocusEnvironment"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/present(on:configuration:delegate:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerConfiguration","text":"SBSDKUIBarcodesBatchScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIBarcodesBatchScannerViewControllerDelegate","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController","text":"SBSDKUIBarcodesBatchScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:delegate:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/present(on:configuration:delegate:)","abstract":[{"text":"Creates a new instance of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController"},{"type":"text","text":" and presents it modally."}],"role":"symbol","deprecated":true,"title":"present(on:configuration:delegate:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/present(on:configuration:delegate:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayControllerDelegate":{"abstract":[{"text":"The delegation protocol for the barcode tracking overlay controller.","type":"text"}],"title":"SBSDKBarcodeTrackingOverlayControllerDelegate","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/viewDidLoad":{"abstract":[],"title":"viewDidLoad","type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/viewdidload","fragments":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/viewDidLoad"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/animationControllerForDismissedController:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/animationcontrollerfordismissedcontroller:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"animationControllerForDismissedController:","kind":"identifier"}],"navigatorTitle":[{"text":"animationControllerForDismissedController:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"animationControllerForDismissedController:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/animationControllerForDismissedController:"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIContentContainer":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"type":"topic","abstract":[{"text":"A highly customizable camera-based view controller to scan barcodes batches.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController","title":"SBSDKUIBarcodesBatchScannerViewController","deprecated":true},"doc://net.doo.ScanbotBarcodeScannerSDK/s8CopyableP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/tableView:cellForRowAtIndexPath:":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/tableview:cellforrowatindexpath:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"title":"tableView:cellForRowAtIndexPath:","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/tableView:cellForRowAtIndexPath:","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeTrackingOverlay:didChangeSelectedBarcodes:":{"title":"barcodeTrackingOverlay:didChangeSelectedBarcodes:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:didChangeSelectedBarcodes:","abstract":[],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodetrackingoverlay:didchangeselectedbarcodes:","fragments":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:didChangeSelectedBarcodes:","kind":"identifier"}],"navigatorTitle":[{"text":"barcodeTrackingOverlay:didChangeSelectedBarcodes:","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/containerForEnableCameraView":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/containerForEnableCameraView","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"containerForEnableCameraView"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/containerforenablecameraview","title":"containerForEnableCameraView"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode scanner.","type":"text"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"kind":"symbol","title":"SBSDKBarcodeScannerViewController"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/enableCameraTextConfiguration":{"role":"symbol","type":"topic","title":"enableCameraTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/enableCameraTextConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/enablecameratextconfiguration","abstract":[],"fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeScannerControllerShouldScanBarcodes:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodescannercontrollershouldscanbarcodes:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeScannerControllerShouldScanBarcodes:"}],"title":"barcodeScannerControllerShouldScanBarcodes:","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"barcodeScannerControllerShouldScanBarcodes:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerControllerShouldScanBarcodes:","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/interactionControllerForPresentation:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/interactionControllerForPresentation:","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interactionControllerForPresentation:"}],"navigatorTitle":[{"kind":"identifier","text":"interactionControllerForPresentation:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/interactioncontrollerforpresentation:","title":"interactionControllerForPresentation:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUICameraViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICameraViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIViewController","isActive":true},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController","navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"title":"SBSDKUICameraViewController","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuicameraviewcontroller","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/dataMapper":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dataMapper","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIBarcodesBatchScannerMapping","text":"SBSDKUIBarcodesBatchScannerMapping"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/dataMapper","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/datamapper","title":"dataMapper","kind":"symbol","abstract":[{"type":"text","text":"The mapper object, that conforms to the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerMapping","isActive":true},{"type":"text","text":" protocol. Used to get additional info for barcodes."},{"text":" ","type":"text"},{"type":"text","text":"Does not hold strong reference to the object. Can be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"dataMapper"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/willShowEnableCameraView":{"navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/willshowenablecameraview","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/willShowEnableCameraView","title":"willShowEnableCameraView","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowEnableCameraView"}],"abstract":[],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/unfreezeCamera()":{"navigatorTitle":[{"kind":"identifier","text":"unfreezeCamera"}],"title":"unfreezeCamera()","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/unfreezeCamera()","abstract":[{"type":"text","text":"Unfreezes the previously frozen cameras preview layer by restarting the camera session."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unfreezeCamera"},{"text":"()","kind":"text"}],"deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/unfreezecamera()","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/isScanningEnabled":{"navigatorTitle":[{"text":"isScanningEnabled","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/isscanningenabled","abstract":[{"type":"text","text":"Enables or disables the barcode scanning."}],"title":"isScanningEnabled","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/isScanningEnabled","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isScanningEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerMapping":{"deprecated":true,"navigatorTitle":[{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannermapping","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerMapping","type":"topic","title":"SBSDKUIBarcodesBatchScannerMapping","kind":"symbol","role":"symbol","abstract":[{"text":"Protocol for the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController"},{"text":" barcode results mapping.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/barcodeTrackingOverlay:polygonStyleFor:":{"fragments":[{"kind":"text","text":"- "},{"text":"barcodeTrackingOverlay:polygonStyleFor:","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:polygonStyleFor:"}],"title":"barcodeTrackingOverlay:polygonStyleFor:","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:polygonStyleFor:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/barcodetrackingoverlay:polygonstylefor:"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSExtensionRequestHandling"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/updateLayout":{"navigatorTitle":[{"text":"updateLayout","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/updateLayout","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/updatelayout","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"updateLayout","kind":"identifier"}],"title":"updateLayout"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIStateRestoring"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/create(configuration:delegate:)":{"abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/create(configuration:delegate:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKUIBarcodesBatchScannerViewControllerDelegate","text":"SBSDKUIBarcodesBatchScannerViewControllerDelegate"},{"kind":"text","text":"?) -> "},{"text":"SBSDKUIBarcodesBatchScannerViewController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodesBatchScannerViewController","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createNewWithConfiguration:delegate:","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/create(configuration:delegate:)","title":"create(configuration:delegate:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodesBatchScannerViewController/viewWillAppear:":{"abstract":[],"title":"viewWillAppear:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodesbatchscannerviewcontroller\/viewwillappear:","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/viewWillAppear:","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIScrollViewDelegate":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s8SendableP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKUIBarcodesBatchScannerViewController","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerViewController"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/containerForEnableCameraView","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/dataMapper","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/delegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/enableCameraTextConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/enableCameraUIConfiguration","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/isScanningEnabled","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/supportedInterfaceOrientations"]},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/animationControllerForDismissedController:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/animationControllerForPresentedController:presentingController:sourceController:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerController:didScanBarcodes:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerController:filterBarcodes:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeScannerControllerShouldScanBarcodes:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:didChangeSelectedBarcodes:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:didTapOnBarcode:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:polygonStyleFor:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/barcodeTrackingOverlay:textStyleFor:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/didHideEnableCameraView","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/freezeCamera()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/initWithCoder:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/interactionControllerForDismissal:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/interactionControllerForPresentation:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/tableView:cellForRowAtIndexPath:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/tableView:heightForRowAtIndexPath:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/tableView:numberOfRowsInSection:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/unfreezeCamera()","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/updateFlashButton","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/updateLayout","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/viewDidLoad","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/viewWillAppear:","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/willShowEnableCameraView"],"anchor":"Instance-Methods","generated":true},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/create(configuration:delegate:)","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodesBatchScannerViewController\/present(on:configuration:delegate:)"]}]},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewControllerDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITableViewDataSource","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UITableViewDelegate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/objc(pl)UIViewControllerTransitioningDelegate"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUICameraViewController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUICameraViewController","kind":"typeIdentifier","text":"SBSDKUICameraViewController"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title","op":"replace","value":"SBSDKBarcodeScannerViewControllerDelegate"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments"},{"value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewControllerDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1freezeCamera()\/title","op":"replace","value":"freezeCamera"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"freezeCamera"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1freezeCamera()\/fragments","op":"replace"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1delegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController","op":"replace"},{"value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/fragments"},{"value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1present(on:configuration:delegate:)\/title","value":"presentOn:configuration:delegate:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"presentOn:configuration:delegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1present(on:configuration:delegate:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/title","value":"SBSDKBarcodeTrackingOverlayControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/fragments","value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}]},{"op":"replace","value":"SBSDKUIBarcodesBatchScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/fragments","value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SBSDKUIBarcodesBatchScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController\/navigatorTitle"},{"op":"replace","value":"SBSDKBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title"},{"value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/title","value":"SBSDKUICameraViewController","op":"replace"},{"value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUICameraViewController\/navigatorTitle","value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}]},{"op":"replace","value":"dataMapper","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1dataMapper\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1dataMapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"dataMapper"}]},{"value":"unfreezeCamera","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1unfreezeCamera()\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1unfreezeCamera()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"unfreezeCamera","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1isScanningEnabled\/title","value":"isScanningEnabled"},{"op":"replace","value":[{"kind":"identifier","text":"isScanningEnabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1isScanningEnabled\/fragments"},{"value":"SBSDKUIBarcodesBatchScannerMapping","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerMapping\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerMapping\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodesBatchScannerMapping","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerMapping"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerMapping\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1create(configuration:delegate:)\/title","value":"createNewWithConfiguration:delegate:"},{"value":[{"kind":"text","text":"+ "},{"text":"createNewWithConfiguration:delegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodesBatchScannerViewController~1create(configuration:delegate:)\/fragments"}]}]}