{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"ID Card PDF417 Document Field Type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"}],"title":"SBSDKUI2IDCardPDF417DocumentFieldType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2IDCardPDF417DocumentFieldType","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/birthDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/dateExpired","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/dateIssued","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/documentCode","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/firstName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/lastName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/optional1","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/equatable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/dateIssued":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType.dateIssued","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateIssued"}],"abstract":[{"type":"text","text":"Date Issued"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/dateIssued","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeDateIssued"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/dateissued"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/optional1":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType.optional1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optional1"}],"abstract":[{"type":"text","text":"Optional 1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/optional1","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeOptional1"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/optional1"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/documentCode":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType.documentCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentCode"}],"abstract":[{"type":"text","text":"Document Code"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/documentCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeDocumentCode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/documentcode"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/unknown":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeUnknown"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/unknown"},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/firstName":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType.firstName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstName"}],"abstract":[{"type":"text","text":"First Name"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/firstName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeFirstName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/firstname"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/lastName":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType.lastName","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"}],"abstract":[{"type":"text","text":"Last Name"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/lastName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeLastName"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/lastname"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/init(rawvalue:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"}],"abstract":[{"type":"text","text":"ID Card PDF417 Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/dateExpired":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType.dateExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateExpired"}],"abstract":[{"type":"text","text":"Date Expired"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/dateExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeDateExpired"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/dateexpired"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2IDCardPDF417DocumentFieldType/birthDate":{"role":"symbol","title":"SBSDKUI2IDCardPDF417DocumentFieldType.birthDate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"}],"abstract":[{"type":"text","text":"Birth Date"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/birthDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeBirthDate"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2idcardpdf417documentfieldtype\/birthdate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/birthDate","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/dateExpired","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/dateIssued","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/documentCode","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/firstName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/lastName","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/optional1","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2IDCardPDF417DocumentFieldType\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1dateIssued\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldTypeDateIssued"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1dateIssued\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeDateIssued"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1optional1\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldTypeOptional1"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1optional1\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeOptional1"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1documentCode\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldTypeDocumentCode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1documentCode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeDocumentCode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1unknown\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1unknown\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1firstName\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldTypeFirstName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1firstName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeFirstName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1lastName\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldTypeLastName"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1lastName\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeLastName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1dateExpired\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldTypeDateExpired"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1dateExpired\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeDateExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1birthDate\/title","value":"SBSDKUI2IDCardPDF417DocumentFieldTypeBirthDate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2IDCardPDF417DocumentFieldType~1birthDate\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2IDCardPDF417DocumentFieldTypeBirthDate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}