{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"case","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoOrientation@SBSDKVideoOrientationLandscapeRight","navigatorTitle":[{"text":"SBSDKVideoOrientationLandscapeRight","kind":"identifier"}],"title":"SBSDKVideoOrientation.landscapeRight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"landscapeRight","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscapeRight","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/landscapeRight"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/landscaperight"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/landscaperight"]}],"abstract":[{"type":"text","text":"Landscape right orientation."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation/landscapeRight":{"title":"SBSDKVideoOrientation.landscapeRight","abstract":[{"text":"Landscape right orientation.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation\/landscaperight","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeRight"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation\/landscapeRight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeRight"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoOrientation":{"title":"SBSDKVideoOrientation","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoOrientation","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An enum describing the orientation of a video frame."}],"navigatorTitle":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoOrientation","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideoorientation","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVideoOrientationLandscapeRight"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKVideoOrientationLandscapeRight","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeRight"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1landscapeRight\/title","value":"SBSDKVideoOrientationLandscapeRight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation~1landscapeRight\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeRight"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/title","value":"SBSDKVideoOrientation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoOrientation\/navigatorTitle","value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}]}]}]}