{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"form1BCustom"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType\/form1BCustom","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1bcustom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1bcustom"]}],"metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"form1BCustom"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateFormTypeForm1BCustom","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateFormType@SBSDKMedicalCertificateFormTypeForm1BCustom","symbolKind":"case","title":"SBSDKMedicalCertificateFormType.form1BCustom"},"abstract":[{"type":"text","text":"Form 1B custom."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateFormType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType","title":"SBSDKMedicalCertificateFormType","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype","abstract":[{"type":"text","text":"Type of the medical certificate form."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateFormType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateFormType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateFormType/form1BCustom":{"type":"topic","abstract":[{"type":"text","text":"Form 1B custom."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"form1BCustom"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormTypeForm1BCustom"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificateformtype\/form1bcustom","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateFormType\/form1BCustom","title":"SBSDKMedicalCertificateFormType.form1BCustom","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKMedicalCertificateFormTypeForm1BCustom","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormTypeForm1BCustom"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateFormTypeForm1BCustom"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/title","value":"SBSDKMedicalCertificateFormType"},{"value":[{"text":"SBSDKMedicalCertificateFormType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKMedicalCertificateFormType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType~1form1BCustom\/title","value":"SBSDKMedicalCertificateFormTypeForm1BCustom","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateFormType~1form1BCustom\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateFormTypeForm1BCustom","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}