{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:filterbarcodes:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:filterbarcodes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeScannerController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController","text":"SBSDKBarcodeScannerViewController"},{"text":", ","kind":"text"},{"text":"filterBarcodes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","text":"SBSDKBarcodeItem"},{"text":"]) -> [","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"text":"]","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"barcodeScannerController(_:filterBarcodes:)","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeScannerViewControllerDelegate(im)barcodeScannerController:filterBarcodes:","navigatorTitle":[{"text":"barcodeScannerController:filterBarcodes:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(barcodeScannerController:filterBarcodes:) "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"barcodeScannerController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController","text":"SBSDKBarcodeScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filterBarcodes"},{"text":" ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","kind":"typeIdentifier","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"text":"]) -> [","kind":"text"},{"text":"SBSDKBarcodeItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calling "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"text":"Array of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"},{"text":" containing the scanned barcodes.","type":"text"}],"type":"paragraph"}],"name":"codes"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The filtered array of barcodes to be delivered to the post-processing."}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional."}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:filterBarcodes:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asks the delegate to filter the scanned barcodes."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate","abstract":[{"text":"The delegate protocol of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","type":"reference","isActive":true},{"type":"text","text":" that provides methods for"},{"type":"text","text":" "},{"type":"text","text":"enabling\/disabling scanning and managing scanned barcodes."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate","title":"SBSDKBarcodeScannerViewControllerDelegate","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","abstract":[{"type":"text","text":"The result of barcode scanning."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","title":"SBSDKBarcodeScannerResult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","title":"SBSDKBarcodeItem","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeItem"}],"abstract":[{"type":"text","text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are"},{"text":" ","type":"text"},{"type":"text","text":"considered separate barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewControllerDelegate/barcodeScannerController(_:filterBarcodes:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:filterBarcodes:"}],"title":"barcodeScannerController(_:filterBarcodes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"barcodeScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"text":", ","kind":"text"},{"text":"filterBarcodes","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"kind":"text","text":"]) -> ["},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier","text":"SBSDKBarcodeItem"},{"kind":"text","text":"]"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontrollerdelegate\/barcodescannercontroller(_:filterbarcodes:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewControllerDelegate\/barcodeScannerController(_:filterBarcodes:)","type":"topic","abstract":[{"type":"text","text":"Asks the delegate to filter the scanned barcodes."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"title":"SBSDKBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"barcodeScannerController:filterBarcodes:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"barcodeScannerController:filterBarcodes:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeItem *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"barcodeScannerController:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","kind":"typeIdentifier","text":"SBSDKBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"text":"filterBarcodes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeItem *>"},{"text":" *) ","kind":"text"},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The calling "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"controller"},{"name":"codes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","type":"reference","isActive":true},{"type":"text","text":" containing the scanned barcodes."}]}]}]}},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The filtered array of barcodes to be delivered to the post-processing."}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/title","value":"SBSDKBarcodeScannerViewControllerDelegate"},{"value":[{"text":"SBSDKBarcodeScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title","op":"replace","value":"SBSDKBarcodeScannerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments","value":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem"},{"op":"replace","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"op":"replace"},{"value":"barcodeScannerController:filterBarcodes:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:filterBarcodes:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewControllerDelegate~1barcodeScannerController(_:filterBarcodes:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"barcodeScannerController:filterBarcodes:","kind":"identifier"}]},{"value":"SBSDKBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}