{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encryptionmode:cryptingprovider:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encryptionmode:cryptingprovider:)"]}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKIndexedImageStorage(im)initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:","navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation"},{"text":"?, ","kind":"text"},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"text":"encryptionMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode"},{"text":", ","kind":"text"},{"text":"cryptingProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)","symbolKind":"init","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","text":"SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"? = SBSDKStorageLocation(), ","kind":"text"},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","text":"SBSDKImageFileFormat","kind":"typeIdentifier"},{"text":" = .JPEG, ","kind":"text"},{"text":"encryptionMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode","text":"SBSDKEncryptionMode","kind":"typeIdentifier"},{"text":" = .disabled, ","kind":"text"},{"text":"cryptingProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"storageLocation","content":[{"inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}],"type":"paragraph"}]},{"name":"fileFormat","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file format that should be used to store the images."}]}]},{"name":"encryptionMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encryption mode for the stored images. Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/disabled"},{"type":"text","text":"."}]}]},{"name":"cryptingProvider","content":[{"inlineContent":[{"type":"text","text":"If non-nil, overrides the default image encryption provider."}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","isActive":true},{"type":"text","text":" at the given storage location with given image file format."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingProvider":{"title":"SBSDKStorageCryptingProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","abstract":[{"type":"text","text":"Protocol for providing a storage crypting object."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingprovider"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode/disabled":{"type":"topic","abstract":[{"type":"text","text":"Encryption is not used when loading or saving images. Trying to load an encrypted image will fail."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode\/disabled","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"title":"SBSDKEncryptionMode.disabled","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFileFormat":{"type":"topic","title":"SBSDKImageFileFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageFileFormat","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Enumeration of supported image file types."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefileformat"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageLocation":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragelocation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","title":"SBSDKStorageLocation","type":"topic","abstract":[{"text":"Descriptor and helper class for describing and creating a directory on the file system.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageLocation"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage":{"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage","kind":"symbol","title":"SBSDKIndexedImageStorage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncryptionMode":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncryptionMode"}],"abstract":[{"type":"text","text":"Encryption\/Decryption mode to be used when an image is loaded\/saved."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencryptionmode","type":"topic","title":"SBSDKEncryptionMode","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage/init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)":{"abstract":[{"text":"Initializes a new ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","isActive":true,"type":"reference"},{"text":" at the given storage location with given image file format.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/init(storagelocation:fileformat:encryptionmode:cryptingprovider:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation"},{"text":"?, ","kind":"text"},{"text":"fileFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageFileFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"},{"text":", ","kind":"text"},{"text":"encryptionMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode"},{"text":", ","kind":"text"},{"text":"cryptingProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)","type":"topic","title":"init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStorageLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation"},{"text":" *) ","kind":"text"},{"text":"storageLocation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fileFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFileFormat","text":"SBSDKImageFileFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFileFormat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fileFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptionMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier","text":"SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"encryptionMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"cryptingProvider:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier","text":"id<SBSDKStorageCryptingProvider>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cryptingProvider"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"storageLocation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}]}]},{"name":"fileFormat","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file format that should be used to store the images."}]}]},{"name":"encryptionMode","content":[{"type":"paragraph","inlineContent":[{"text":"The encryption mode for the stored images. Defaults to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncryptionMode\/disabled"},{"text":".","type":"text"}]}]},{"name":"cryptingProvider","content":[{"inlineContent":[{"type":"text","text":"If non-nil, overrides the default image encryption provider."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/title","op":"replace","value":"SBSDKStorageCryptingProvider"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/fragments","op":"replace","value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/navigatorTitle","op":"replace","value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1disabled\/title","op":"replace","value":"SBSDKEncryptionModeDisabled"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode~1disabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKEncryptionModeDisabled"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/title","op":"replace","value":"SBSDKImageFileFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/fragments","op":"replace","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFileFormat\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageFileFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/title","op":"replace","value":"SBSDKStorageLocation"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/fragments","op":"replace","value":[{"text":"SBSDKStorageLocation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/title","op":"replace","value":"SBSDKIndexedImageStorage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/fragments","op":"replace","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/title","op":"replace","value":"SBSDKEncryptionMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncryptionMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEncryptionMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)\/title","op":"replace","value":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1init(storageLocation:fileFormat:encryptionMode:cryptingProvider:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:fileFormat:encryptionMode:cryptingProvider:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}