{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/moveimage(from:to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/moveimage(from:to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Moves the image at the source index to the destination index.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKIndexedImageStorage(im)moveImageFromIndex:toIndex:","navigatorTitle":[{"text":"moveImageFromIndex:toIndex:","kind":"identifier"}],"symbolKind":"method","title":"moveImage(from:to:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":"(moveImageFromIndex:toIndex:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sourceIndex","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"destinationIndex","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The valid current index of the image to be moved."}]}],"name":"sourceIndex"},{"content":[{"inlineContent":[{"text":"The valid new index of the image to be moved.","type":"text"}],"type":"paragraph"}],"name":"destinationIndex"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":", if the operation was successfull, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage"]]},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage":{"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage","kind":"symbol","title":"SBSDKIndexedImageStorage","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKIndexedImageStorage/moveImage(from:to:)":{"kind":"symbol","abstract":[{"text":"Moves the image at the source index to the destination index.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkindexedimagestorage\/moveimage(from:to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"moveImage(from:to:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"moveImageFromIndex:toIndex:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"moveImageFromIndex:toIndex:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveImageFromIndex:toIndex:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"moveImageFromIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sourceIndex"},{"kind":"text","text":" "},{"kind":"identifier","text":"toIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"destinationIndex"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The valid current index of the image to be moved."}]}],"name":"sourceIndex"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The valid new index of the image to be moved.","type":"text"}]}],"name":"destinationIndex"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":", if the operation was successfull, "},{"type":"codeVoice","code":"false"},{"type":"text","text":" otherwise."}]}]},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"SBSDKIndexedImageStorage","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage\/navigatorTitle"},{"op":"replace","value":"moveImageFromIndex:toIndex:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1moveImage(from:to:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveImageFromIndex:toIndex:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKIndexedImageStorage~1moveImage(from:to:)\/fragments"}]}]}