{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/initWithAuthor:creator:title:subject:keywords:","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfattributes\/initwithauthor:creator:title:subject:keywords:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAuthor:creator:title:subject:keywords:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"initWithAuthor:creator:title:subject:keywords:","navigatorTitle":[{"kind":"identifier","text":"initWithAuthor:creator:title:subject:keywords:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes(im)initWithAuthor:creator:title:subject:keywords:","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithAuthor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"author","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"creator:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"creator","kind":"internalParam"},{"kind":"text","text":" "},{"text":"title:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"subject:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"subject"},{"kind":"text","text":" "},{"text":"keywords:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"keywords"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKPDFAttributes","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFAttributes"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes","abstract":[{"text":"PDF attributes.","type":"text"}],"title":"SBSDKPDFAttributes","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes/initWithAuthor:creator:title:subject:keywords:":{"type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"initWithAuthor:creator:title:subject:keywords:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithAuthor:creator:title:subject:keywords:","kind":"identifier"}],"title":"initWithAuthor:creator:title:subject:keywords:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes\/initwithauthor:creator:title:subject:keywords:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes\/initWithAuthor:creator:title:subject:keywords:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKPDFAttributes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}]}]}]}