{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRegexFilter:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"regexFilter"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumSizeScore:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumSizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAdditionalQuietZone:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"addAdditionalQuietZone"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum1DQuietZoneSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimum1DQuietZoneSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumNumberOfRequiredFramesWithEqualRecognitionResult"},{"kind":"text","text":" "},{"kind":"identifier","text":"oneDConfirmationMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKOneDConfirmationMode","kind":"typeIdentifier","text":"SBSDKOneDConfirmationMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"oneDConfirmationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripCheckDigits:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"stripCheckDigits"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumTextLength:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minimumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTextLength:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maximumTextLength"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableOneDBlurScanner:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enableOneDBlurScanner"},{"kind":"text","text":" "},{"kind":"identifier","text":"checksumAlgorithms:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKMSIPlesseyChecksumAlgorithm *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"checksumAlgorithms"},{"kind":"text","text":";"}]}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatMSIPlesseyConfiguration(im)initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:onedconfirmationmode:stripcheckdigits:minimumtextlength:maximumtextlength:enableonedblurscanner:check-7wfke"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:","kind":"identifier"}],"kind":"symbol","title":"initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/initwithregexfilter:minimumsizescore:addadditionalquietzone:minimum1dquietzonesize:minimumnumberofrequiredframeswithequalrecognitionresult:onedconfirmationmode:stripcheckdigits:minimumtextlength:maximumtextlength:enableonedblurscanner:check-7wfke","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/initWithRegexFilter:minimumSizeScore:addAdditionalQuietZone:minimum1DQuietZoneSize:minimumNumberOfRequiredFramesWithEqualRecognitionResult:oneDConfirmationMode:stripCheckDigits:minimumTextLength:maximumTextLength:enableOneDBlurScanner:checksumAlgorithms:","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"MSI Plessey barcode configuration. Add to scanner configuration to scan MSI Plessey barcodes."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration","title":"SBSDKBarcodeFormatMSIPlesseyConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKOneDConfirmationMode":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkonedconfirmationmode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKOneDConfirmationMode","role":"symbol","title":"SBSDKOneDConfirmationMode","abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."},{"type":"text","text":" "},{"type":"text","text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey)."},{"text":" ","type":"text"},{"text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result.","type":"text"},{"text":" ","type":"text"},{"text":"However, this stronger condition can lead to missed barcodes (lower recall).","type":"text"},{"text":" ","type":"text"},{"text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeFormatMSIPlesseyConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKOneDConfirmationMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/title","op":"replace"},{"value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKOneDConfirmationMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}