{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/new","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Type Method","role":"symbol","title":"new","symbolKind":"method","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"navigatorTitle":[{"text":"new","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatMSIPlesseyConfiguration(cm)new","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/new"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"new","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration","title":"SBSDKBarcodeFormatMSIPlesseyConfiguration","abstract":[{"type":"text","text":"MSI Plessey barcode configuration. Add to scanner configuration to scan MSI Plessey barcodes."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatMSIPlesseyConfiguration/new":{"title":"new","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatmsiplesseyconfiguration\/new","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"new","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatMSIPlesseyConfiguration\/new","fragments":[{"text":"+ ","kind":"text"},{"text":"new","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKBarcodeFormatMSIPlesseyConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeFormatMSIPlesseyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatMSIPlesseyConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}