{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"resetButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Defaults to “Resets document’s edges”.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/resetbuttonaccessibilityhint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/resetbuttonaccessibilityhint"]}],"metadata":{"title":"resetButtonAccessibilityHint","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"resetButtonAccessibilityHint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"resetButtonAccessibilityHint"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration(py)resetButtonAccessibilityHint","symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/resetButtonAccessibilityHint","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration"]]},"abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the reset button."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration/resetButtonAccessibilityHint":{"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration\/resetbuttonaccessibilityhint","type":"topic","abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the reset button."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration\/resetButtonAccessibilityHint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetButtonAccessibilityHint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"resetButtonAccessibilityHint","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"resetButtonAccessibilityHint"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenAccessibilityConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenaccessibilityconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"title":"SBSDKUICroppingScreenAccessibilityConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenAccessibilityConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"resetButtonAccessibilityHint","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"resetButtonAccessibilityHint","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"resetButtonAccessibilityHint"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1resetButtonAccessibilityHint\/title","value":"resetButtonAccessibilityHint","op":"replace"},{"value":[{"text":"resetButtonAccessibilityHint","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration~1resetButtonAccessibilityHint\/fragments","op":"replace"},{"value":"SBSDKUICroppingScreenAccessibilityConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/fragments"}]}]}