{"abstract":[{"type":"text","text":"Synchronously converts the scanned document to a multipage-TIFF file and saves it to the specified URL."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-7evl8"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-7evl8"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(generateFromScannedDocument:toFile:error:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scannedDocument"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier","text":"SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"? = nil) "},{"kind":"keyword","text":"throws"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scanned document to convert to a TIFF file."}]}],"name":"scannedDocument"},{"content":[{"inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"the default TIFF location of the scanned document will be used."}],"type":"paragraph"}],"name":"fileURL"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","isActive":true,"type":"reference"},{"type":"text","text":" in case of an error."}]}],"style":"note","name":"Throws"}]}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"generateFromScannedDocument:toFile:error:","kind":"identifier"}],"symbolKind":"method","title":"generate(from:to:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGenerator(im)generateFromScannedDocument:toFile:error:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-7evl8","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/defaultCryptingProvider":{"type":"topic","title":"defaultCryptingProvider","abstract":[{"type":"text","text":"The SDK-wide encryption provider for storing image data to disk. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption used."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultCryptingProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/scanbot\/defaultcryptingprovider","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultCryptingProvider"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator/generate(from:to:)-7evl8":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"generate(from:to:)","abstract":[{"text":"Synchronously converts the scanned document to a multipage-TIFF file and saves it to the specified URL.","type":"text"}],"navigatorTitle":[{"text":"generateFromScannedDocument:toFile:error:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator\/generate(from:to:)-7evl8","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/generate(from:to:)-7evl8","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScannedDocument"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"kind":"symbol","abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"type":"topic","title":"SBSDKScannedDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKError":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKError"}],"title":"SBSDKError","url":"\/documentation\/scanbotsdk\/sbsdkerror","abstract":[{"type":"text","text":"Represents errors that can occur within the Scanbot SDK."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKError"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","type":"reference"},{"text":" is set, the generated TIFF files will be encrypted using the specified crypting provider.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"title":"SBSDKTIFFGenerator","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"generateFromScannedDocument:toFile:error:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"generateFromScannedDocument:toFile:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"generateFromScannedDocument:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","text":"SBSDKScannedDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"scannedDocument"},{"kind":"text","text":" "},{"kind":"identifier","text":"toFile:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fileURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"scannedDocument","content":[{"type":"paragraph","inlineContent":[{"text":"The scanned document to convert to a TIFF file.","type":"text"}]}]},{"name":"fileURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The file URL to save the TIFF file at. If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"the default TIFF location of the scanned document will be used."}]}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the method succeeded, otherwise "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}]}],"kind":"content"},"op":"add","path":"\/primaryContentSections\/2"},{"value":"defaultCryptingProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/title"},{"value":[{"kind":"identifier","text":"defaultCryptingProvider"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/fragments"},{"value":"generateFromScannedDocument:toFile:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1generate(from:to:)-7evl8\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"generateFromScannedDocument:toFile:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1generate(from:to:)-7evl8\/fragments"},{"value":"SBSDKScannedDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title"},{"value":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments"},{"value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle"},{"value":"SBSDKTIFFGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/title"},{"value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/navigatorTitle"}]}]}