{"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"saveAndReturnError:"}],"role":"symbol","title":"save()","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFMetadataEditor(im)saveAndReturnError:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"save","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFMetadataEditor"]]},"abstract":[{"text":"Tries to apply the changes in the metadata by saving it at the original URL.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFMetadataEditor\/save()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"save"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfmetadataeditor\/save()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfmetadataeditor\/save()"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFMetadataEditor/save()":{"title":"save()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfmetadataeditor\/save()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"save","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Tries to apply the changes in the metadata by saving it at the original URL.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFMetadataEditor\/save()","navigatorTitle":[{"text":"saveAndReturnError:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFMetadataEditor":{"abstract":[{"text":"A class to edit the metadata dictionary of a PDF.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKPDFMetadataEditor","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFMetadataEditor","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFMetadataEditor"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfmetadataeditor","title":"SBSDKPDFMetadataEditor"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"saveAndReturnError:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"saveAndReturnError:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"saveAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFMetadataEditor~1save()\/title","value":"saveAndReturnError:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"saveAndReturnError:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFMetadataEditor~1save()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFMetadataEditor\/title","value":"SBSDKPDFMetadataEditor"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFMetadataEditor\/fragments","value":[{"text":"SBSDKPDFMetadataEditor","kind":"identifier"}]}]}]}