{"metadata":{"platforms":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"uiConfiguration"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"uiConfiguration","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerConfiguration(py)uiConfiguration"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The user interface sub-configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uiConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration","kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2BarcodeScannerViewController instead."}],"type":"paragraph"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerconfiguration\/uiconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerconfiguration\/uiconfiguration"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration\/uiConfiguration"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerConfiguration/uiConfiguration":{"abstract":[{"text":"The user interface sub-configuration.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uiConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration","text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"typeIdentifier"}],"title":"uiConfiguration","navigatorTitle":[{"text":"uiConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerconfiguration\/uiconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration\/uiConfiguration","deprecated":true,"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerUIConfiguration":{"deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescanneruiconfiguration","abstract":[{"type":"text","text":"The configuration for user interface of the RTU-UI barcode scanner."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration","title":"SBSDKUIBarcodeScannerUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeScannerUIConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerConfiguration":{"deprecated":true,"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerConfiguration","kind":"identifier"}],"title":"SBSDKUIBarcodeScannerConfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerConfiguration","abstract":[{"text":"This class describes the look and feel, as well as the textual contents of the RTU-UI barcode scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"uiConfiguration","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"uiConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIBarcodeScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerUIConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerUIConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"uiConfiguration"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"uiConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration~1uiConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration~1uiConfiguration\/fragments","value":[{"text":"uiConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/title","value":"SBSDKUIBarcodeScannerUIConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerUIConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration\/title","op":"replace","value":"SBSDKUIBarcodeScannerConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerConfiguration\/fragments","value":[{"text":"SBSDKUIBarcodeScannerConfiguration","kind":"identifier"}],"op":"replace"}]}]}