{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/cumulativeTextSizeHistogram","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Cumulative histogram where every entry is equal to the number of symbols with text size equal or lower than N percent, where N is the index of the entry in the array."}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cumulativeTextSizeHistogram","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property","title":"cumulativeTextSizeHistogram","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult(py)cumulativeTextSizeHistogram","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cumulativeTextSizeHistogram","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"cumulativeTextSizeHistogram","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/cumulativetextsizehistogram"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/cumulativetextsizehistogram"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult/cumulativeTextSizeHistogram":{"kind":"symbol","abstract":[{"type":"text","text":"Cumulative histogram where every entry is equal to the number of symbols with text size equal or lower than N percent, where N is the index of the entry in the array."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/cumulativeTextSizeHistogram","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/cumulativetextsizehistogram","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cumulativeTextSizeHistogram","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"cumulativeTextSizeHistogram","kind":"identifier"}],"role":"symbol","title":"cumulativeTextSizeHistogram"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"title":"SBSDKDocumentQualityAnalyzerResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult","abstract":[{"type":"text","text":"Result of document quality analysis. It can be used to determine, e.g., if a document is good enough to be used for OCR processing."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cumulativeTextSizeHistogram"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cumulativeTextSizeHistogram"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cumulativeTextSizeHistogram"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult~1cumulativeTextSizeHistogram\/title","op":"replace","value":"cumulativeTextSizeHistogram"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult~1cumulativeTextSizeHistogram\/fragments","op":"replace","value":[{"text":"cumulativeTextSizeHistogram","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/title","op":"replace","value":"SBSDKDocumentQualityAnalyzerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/fragments","op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}