{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/cumulativeContrastHistogram"},"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"cumulativeContrastHistogram","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cumulativeContrastHistogram","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"cumulativeContrastHistogram","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult(py)cumulativeContrastHistogram","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/cumulativecontrasthistogram"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/cumulativecontrasthistogram"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Cumulative histogram where every entry is equal to the number of symbols with contrast equal or lower than N percent, where N is the index of the entry in the array.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cumulativeContrastHistogram","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"title":"SBSDKDocumentQualityAnalyzerResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult","abstract":[{"type":"text","text":"Result of document quality analysis. It can be used to determine, e.g., if a document is good enough to be used for OCR processing."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult/cumulativeContrastHistogram":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/cumulativecontrasthistogram","abstract":[{"type":"text","text":"Cumulative histogram where every entry is equal to the number of symbols with contrast equal or lower than N percent, where N is the index of the entry in the array."}],"title":"cumulativeContrastHistogram","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/cumulativeContrastHistogram","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cumulativeContrastHistogram","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"cumulativeContrastHistogram","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cumulativeContrastHistogram"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cumulativeContrastHistogram","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"cumulativeContrastHistogram","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/title","value":"SBSDKDocumentQualityAnalyzerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/fragments","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult~1cumulativeContrastHistogram\/title","value":"cumulativeContrastHistogram"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult~1cumulativeContrastHistogram\/fragments","value":[{"kind":"identifier","text":"cumulativeContrastHistogram"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}