{"metadata":{"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult(im)isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","title":"isEqual:","roleHeading":"Instance Method"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/isEqual:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult\/isEqual:","abstract":[],"title":"isEqual:","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult\/isequal:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentQualityAnalyzerResult":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentqualityanalyzerresult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"title":"SBSDKDocumentQualityAnalyzerResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentQualityAnalyzerResult","abstract":[{"type":"text","text":"Result of document quality analysis. It can be used to determine, e.g., if a document is good enough to be used for OCR processing."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/title","value":"SBSDKDocumentQualityAnalyzerResult","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/fragments","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentQualityAnalyzerResult\/navigatorTitle","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"op":"replace"}]}]}