{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/accessibilityconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/accessibilityconfiguration"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/accessibilityConfiguration","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"accessibilityConfiguration"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenTextConfiguration(py)accessibilityConfiguration","title":"accessibilityConfiguration"},"abstract":[{"text":"A configuration with accessibility texts settings.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration/accessibilityConfiguration":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityConfiguration"},{"text":": ","kind":"text"},{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration"},{"text":"?","kind":"text"}],"title":"accessibilityConfiguration","kind":"symbol","abstract":[{"text":"A configuration with accessibility texts settings.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration\/accessibilityConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration\/accessibilityconfiguration","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenAccessibilityConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenaccessibilityconfiguration","role":"symbol","title":"SBSDKUICroppingScreenAccessibilityConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUICroppingScreenAccessibilityConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenTextConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenTextConfiguration"}],"kind":"symbol","title":"SBSDKUICroppingScreenTextConfiguration","type":"topic","abstract":[{"text":"Configuration for the textual content of the page cropping screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenTextConfiguration","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreentextconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"accessibilityConfiguration","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"accessibilityConfiguration"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenAccessibilityConfiguration","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenAccessibilityConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accessibilityConfiguration"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1accessibilityConfiguration\/title","op":"replace","value":"accessibilityConfiguration"},{"value":[{"kind":"identifier","text":"accessibilityConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration~1accessibilityConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/title","value":"SBSDKUICroppingScreenAccessibilityConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUICroppingScreenAccessibilityConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenAccessibilityConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration\/title","value":"SBSDKUICroppingScreenTextConfiguration"},{"op":"replace","value":[{"text":"SBSDKUICroppingScreenTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenTextConfiguration\/fragments"}]}]}