{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/spain"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/spain"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/spain","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType(cpy)spain","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"spain","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"role":"symbol","symbolKind":"property","roleHeading":"Type Property","title":"spain","navigatorTitle":[{"kind":"identifier","text":"spain"}]},"sections":[],"abstract":[{"text":"The country named Spain.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"spain"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType":{"abstract":[{"type":"text","text":"The country types to be used with the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","isActive":true},{"type":"text","text":"."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","title":"SBSDKHealthInsuranceCardCountryType","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardCountryType/spain":{"title":"spain","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"spain","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardcountrytype\/spain","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType\/spain","abstract":[{"type":"text","text":"The country named Spain."}],"role":"symbol","navigatorTitle":[{"text":"spain","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKHealthInsuranceCardRecognizerParameters":{"abstract":[{"text":"The health insurance card recognizer configuration.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardRecognizerParameters","title":"SBSDKHealthInsuranceCardRecognizerParameters","url":"\/documentation\/scanbotsdk\/sbsdkhealthinsurancecardrecognizerparameters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"spain","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"spain"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKHealthInsuranceCardCountryType","kind":"typeIdentifier","text":"SBSDKHealthInsuranceCardCountryType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKHealthInsuranceCardCountryType"},{"kind":"text","text":" * "},{"text":"spain","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKHealthInsuranceCardCountryType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/fragments","value":[{"kind":"identifier","text":"SBSDKHealthInsuranceCardCountryType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType\/navigatorTitle","value":[{"text":"SBSDKHealthInsuranceCardCountryType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1spain\/title","value":"spain","op":"replace"},{"value":[{"text":"spain","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardCountryType~1spain\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/title","value":"SBSDKHealthInsuranceCardRecognizerParameters","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/fragments","value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}]},{"value":[{"text":"SBSDKHealthInsuranceCardRecognizerParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKHealthInsuranceCardRecognizerParameters\/navigatorTitle","op":"replace"}]}]}