{"metadata":{"required":true,"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKCameraSessionObserving(im)cameraSession:didChangeZoom:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"cameraSession:didChangeZoom:","kind":"identifier"}],"title":"cameraSession(_:didChangeZoom:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession","text":"SBSDKCameraSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didChangeZoom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didChangeZoom:)","interfaceLanguage":"swift"},"abstract":[{"text":"Informs the observer that the zoom value has changed.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraSession"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"text":": ","kind":"text"},{"text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didChangeZoom","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"zoomValue","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"session: The camera session that changed the zoom."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"zoomValue: The new zoom value of the camera session.","type":"text"}],"type":"paragraph"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasessionobserving\/camerasession(_:didchangezoom:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasessionobserving\/camerasession(_:didchangezoom:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSessionObserving"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSession":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasession","abstract":[{"type":"text","text":"An easy-to-use wrapper around the AVFoundations video capture session. Sets up and configures the"},{"type":"text","text":" "},{"type":"text","text":"camera device and the preview layer. Provides functionality to capture still images."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCameraSession","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","title":"SBSDKCameraSession","kind":"symbol","navigatorTitle":[{"text":"SBSDKCameraSession","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSessionObserving":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSessionObserving","title":"SBSDKCameraSessionObserving","abstract":[{"text":"A multicast-observer protocol that informs its observers about state changes of a camera session.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasessionobserving","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SBSDKCameraSessionObserving","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKCameraSessionObserving","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCameraSessionObserving/cameraSession(_:didChangeZoom:)":{"title":"cameraSession(_:didChangeZoom:)","abstract":[{"text":"Informs the observer that the zoom value has changed.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSessionObserving\/cameraSession(_:didChangeZoom:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcamerasessionobserving\/camerasession(_:didchangezoom:)","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraSession"},{"text":"(","kind":"text"},{"text":"SBSDKCameraSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeZoom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cameraSession:didChangeZoom:"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cameraSession:didChangeZoom:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cameraSession:didChangeZoom:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"cameraSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKCameraSession","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCameraSession","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCameraSession","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"text":" ","kind":"text"},{"text":"didChangeZoom:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"zoomValue"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/title","value":"SBSDKCameraSession","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/fragments","value":[{"kind":"identifier","text":"SBSDKCameraSession"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSession\/navigatorTitle","value":[{"text":"SBSDKCameraSession","kind":"identifier"}],"op":"replace"},{"value":"SBSDKCameraSessionObserving","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSessionObserving\/title"},{"value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSessionObserving\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSessionObserving\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKCameraSessionObserving"}]},{"value":"cameraSession:didChangeZoom:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didChangeZoom:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCameraSessionObserving~1cameraSession(_:didChangeZoom:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"cameraSession:didChangeZoom:","kind":"identifier"}]}]}]}