{"metadata":{"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enableOneDBlurScanner"}],"roleHeading":"Instance Property","role":"symbol","title":"enableOneDBlurScanner","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode93Configuration(py)enableOneDBlurScanner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableOneDBlurScanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode93Configuration\/enableOneDBlurScanner","interfaceLanguage":"swift"},"abstract":[{"text":"If true, the scanner will try extra-hard to scan barcodes with heavy blur or that are otherwise damaged.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode93Configuration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableOneDBlurScanner"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Default is true","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode93configuration\/enableonedblurscanner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode93configuration\/enableonedblurscanner"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode93Configuration/enableOneDBlurScanner":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode93configuration\/enableonedblurscanner","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode93Configuration\/enableOneDBlurScanner","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableOneDBlurScanner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"enableOneDBlurScanner","kind":"identifier"}],"title":"enableOneDBlurScanner","kind":"symbol","abstract":[{"type":"text","text":"If true, the scanner will try extra-hard to scan barcodes with heavy blur or that are otherwise damaged."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCode93Configuration":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcode93configuration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCode93Configuration","role":"symbol","title":"SBSDKBarcodeFormatCode93Configuration","navigatorTitle":[{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Code 93 barcode configuration. Add to scanner configuration to scan Code 93 barcodes."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"enableOneDBlurScanner","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"enableOneDBlurScanner"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"enableOneDBlurScanner","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration~1enableOneDBlurScanner\/title","value":"enableOneDBlurScanner","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration~1enableOneDBlurScanner\/fragments","value":[{"text":"enableOneDBlurScanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration\/title","value":"SBSDKBarcodeFormatCode93Configuration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration\/fragments","value":[{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCode93Configuration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCode93Configuration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}