{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2manualcounteditdialog\/copywithzone:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"kind":"text","text":" *) "},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"copyWithZone:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog(im)copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog\/copyWithZone:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ManualCountEditDialog/copyWithZone:":{"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2manualcounteditdialog\/copywithzone:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog\/copyWithZone:","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ManualCountEditDialog":{"kind":"symbol","type":"topic","title":"SBSDKUI2ManualCountEditDialog","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2manualcounteditdialog","abstract":[{"type":"text","text":"Configuration of the dialog to manually edit the barcode count."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/title","value":"SBSDKUI2ManualCountEditDialog","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ManualCountEditDialog"}]},{"value":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}