{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"title":"copyWithZone:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataMatrixConfiguration(im)copyWithZone:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatamatrixconfiguration\/copywithzone:"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataMatrixConfiguration\/copyWithZone:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataMatrixConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataMatrixConfiguration/copyWithZone:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataMatrixConfiguration\/copyWithZone:","kind":"symbol","type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatamatrixconfiguration\/copywithzone:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatDataMatrixConfiguration":{"navigatorTitle":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatdatamatrixconfiguration","abstract":[{"type":"text","text":"DataMatrix configuration. Add to scanner configuration to scan DataMatrix and DataMatrix rectangular extensions"},{"text":" ","type":"text"},{"text":"(DMRE) codes.","type":"text"}],"title":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatDataMatrixConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeFormatDataMatrixConfiguration"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeFormatDataMatrixConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatDataMatrixConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatDataMatrixConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatDataMatrixConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}