{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/parse"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/parse"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling\/parse","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingParse","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2Gs1Handling@SBSDKUI2Gs1HandlingParse","title":"SBSDKUI2Gs1Handling.parse","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parse","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","roleHeading":"Case"},"abstract":[{"text":"GS1 messages are converted to the machine-readable format per the GS1 spec (the special FNC1 character is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"converted to ASCII \\x1D). The implied 01 AI key is prepended to DataBar results. No validation is performed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"parse"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Gs1Handling/parse":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"GS1 messages are converted to the machine-readable format per the GS1 spec (the special FNC1 character is"},{"type":"text","text":" "},{"text":"converted to ASCII \\x1D). The implied 01 AI key is prepended to DataBar results. No validation is performed.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"parse","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2Gs1HandlingParse","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling\/parse","role":"symbol","title":"SBSDKUI2Gs1Handling.parse","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling\/parse"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Gs1Handling":{"title":"SBSDKUI2Gs1Handling","abstract":[{"type":"text","text":"GS1_COMPOSITE barcode type handling"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Gs1Handling","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2gs1handling","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SBSDKUI2Gs1HandlingParse","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKUI2Gs1HandlingParse","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingParse"}],"languages":["occ"]}]}},{"op":"replace","value":"SBSDKUI2Gs1HandlingParse","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling~1parse\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling~1parse\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Gs1HandlingParse"}]},{"value":"SBSDKUI2Gs1Handling","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/fragments","value":[{"text":"SBSDKUI2Gs1Handling","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Gs1Handling\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Gs1Handling"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}