{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshot\/initwithimagerefprofiles:totalmemoryconsumption:"]}],"metadata":{"navigatorTitle":[{"text":"initWithImageRefProfiles:totalMemoryConsumption:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithImageRefProfiles:totalMemoryConsumption:","kind":"identifier"}],"title":"initWithImageRefProfiles:totalMemoryConsumption:","symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot(im)initWithImageRefProfiles:totalMemoryConsumption:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot\/initWithImageRefProfiles:totalMemoryConsumption:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImageRefProfiles:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKImageRefProfile *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageRefProfiles","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"totalMemoryConsumption:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@int64_t","text":"int64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"totalMemoryConsumption","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.1.4","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefPoolSnapshot/initWithImageRefProfiles:totalMemoryConsumption:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshot\/initwithimagerefprofiles:totalmemoryconsumption:","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot\/initWithImageRefProfiles:totalMemoryConsumption:","navigatorTitle":[{"text":"initWithImageRefProfiles:totalMemoryConsumption:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithImageRefProfiles:totalMemoryConsumption:","kind":"identifier"}],"type":"topic","title":"initWithImageRefProfiles:totalMemoryConsumption:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefPoolSnapshot":{"title":"SBSDKImageRefPoolSnapshot","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshot","abstract":[{"text":"Snapshot of all alive ImageRefs.","type":"text"}],"navigatorTitle":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshot","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshot\/title","value":"SBSDKImageRefPoolSnapshot"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshot\/fragments","value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshot\/navigatorTitle","value":[{"text":"SBSDKImageRefPoolSnapshot","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}