{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardExpiryDateFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardExpiryDateFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCreditCardDocumentModelConstants(cpy)creditCardExpiryDateFieldName","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Type Property","title":"creditCardExpiryDateFieldName","navigatorTitle":[{"text":"creditCardExpiryDateFieldName","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Name of the “ExpiryDate” field type in document type “CreditCard”."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardexpirydatefieldname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardexpirydatefieldname"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardExpiryDateFieldName","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants/creditCardExpiryDateFieldName":{"type":"topic","abstract":[{"type":"text","text":"Name of the “ExpiryDate” field type in document type “CreditCard”."}],"title":"creditCardExpiryDateFieldName","navigatorTitle":[{"text":"creditCardExpiryDateFieldName","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants\/creditcardexpirydatefieldname","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardExpiryDateFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants\/creditCardExpiryDateFieldName","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCreditCardDocumentModelConstants":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCreditCardDocumentModelConstants","abstract":[],"type":"topic","title":"SBSDKCreditCardDocumentModelConstants","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCreditCardDocumentModelConstants"}],"url":"\/documentation\/scanbotsdk\/sbsdkcreditcarddocumentmodelconstants","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCreditCardDocumentModelConstants"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"creditCardExpiryDateFieldName","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"creditCardExpiryDateFieldName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"creditCardExpiryDateFieldName"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardExpiryDateFieldName\/title","op":"replace","value":"creditCardExpiryDateFieldName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants~1creditCardExpiryDateFieldName\/fragments","op":"replace","value":[{"kind":"identifier","text":"creditCardExpiryDateFieldName"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/title","op":"replace","value":"SBSDKCreditCardDocumentModelConstants"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/fragments","op":"replace","value":[{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCreditCardDocumentModelConstants\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCreditCardDocumentModelConstants","kind":"identifier"}]}]}]}