{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/copyWithZone:","interfaceLanguage":"occ"},"metadata":{"title":"copyWithZone:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration(im)copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/copywithzone:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/copyWithZone:":{"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration":{"title":"SBSDKUI2ArOverlayPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/title","value":"SBSDKUI2ArOverlayPolygonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/fragments","value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}]}]}]}