{"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","role":"symbol","title":"initWithVisible:deselected:selected:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ArOverlayPolygonConfiguration(im)initWithVisible:deselected:selected:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisible:deselected:selected:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithVisible:deselected:selected:"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/initWithVisible:deselected:selected:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"visible"},{"kind":"text","text":" "},{"kind":"identifier","text":"deselected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deselected"},{"kind":"text","text":" "},{"kind":"identifier","text":"selected:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"selected"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/initwithvisible:deselected:selected:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration/initWithVisible:deselected:selected:":{"kind":"symbol","abstract":[],"role":"symbol","title":"initWithVisible:deselected:selected:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVisible:deselected:selected:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisible:deselected:selected:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration\/initwithvisible:deselected:selected:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration\/initWithVisible:deselected:selected:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ArOverlayPolygonConfiguration":{"title":"SBSDKUI2ArOverlayPolygonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ArOverlayPolygonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the overlay polygon displayed on top of a barcode in the camera preview."}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2aroverlaypolygonconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PolygonStyle":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the polygon appearance."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2polygonstyle","title":"SBSDKUI2PolygonStyle"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/title","value":"SBSDKUI2ArOverlayPolygonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/fragments","value":[{"text":"SBSDKUI2ArOverlayPolygonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ArOverlayPolygonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayPolygonConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/title","op":"replace","value":"SBSDKUI2PolygonStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/fragments","op":"replace","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}