{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parsedSuccessful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1DocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2GS1DocumentField","text":"SBSDKUI2GS1DocumentField"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1documentformat\/init(parsedsuccessful:fields:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2gs1documentformat\/init(parsedsuccessful:fields:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1DocumentFormat\/init(parsedSuccessful:fields:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Designated initializer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parsedSuccessful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2GS1DocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2GS1DocumentField"},{"kind":"text","text":"])"}],"title":"init(parsedSuccessful:fields:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2GS1DocumentFormat(im)initWithParsedSuccessful:fields:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithParsedSuccessful:fields:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1DocumentFormat"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2GS1DocumentFormat":{"role":"symbol","title":"SBSDKUI2GS1DocumentFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2GS1DocumentFormat"}],"abstract":[{"type":"text","text":"GS1 Document Format"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1DocumentFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2GS1DocumentFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1documentformat"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2GS1DocumentFormat/init(parsedSuccessful:fields:)":{"role":"symbol","title":"init(parsedSuccessful:fields:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parsedSuccessful"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKUI2GS1DocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2GS1DocumentField"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Designated initializer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1DocumentFormat\/init(parsedSuccessful:fields:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParsedSuccessful:fields:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1documentformat\/init(parsedsuccessful:fields:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.4"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2GS1DocumentField":{"role":"symbol","title":"SBSDKUI2GS1DocumentField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2GS1DocumentField"}],"abstract":[{"type":"text","text":"GS1 Document Field"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2GS1DocumentField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2GS1DocumentField"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2gs1documentfield"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithParsedSuccessful:fields:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParsedSuccessful:fields:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParsedSuccessful:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"parsedSuccessful"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBSDKUI2GS1DocumentField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fields"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1DocumentFormat\/title","value":"SBSDKUI2GS1DocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1DocumentFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2GS1DocumentFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1DocumentFormat~1init(parsedSuccessful:fields:)\/title","value":"initWithParsedSuccessful:fields:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1DocumentFormat~1init(parsedSuccessful:fields:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParsedSuccessful:fields:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1DocumentField\/title","value":"SBSDKUI2GS1DocumentField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2GS1DocumentField\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2GS1DocumentField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}