{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration"]]},"sections":[],"abstract":[{"text":"An array of accepted check types.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/acceptedCheckStandards"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedCheckStandards"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelRootType","kind":"typeIdentifier","text":"SBSDKCheckDocumentModelRootType"},{"kind":"text","text":"]"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"By default all check types are allowed."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerBehaviorConfiguration(py)acceptedCheckStandards","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedCheckStandards"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType","text":"SBSDKCheckDocumentModelRootType"},{"kind":"text","text":"]"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"acceptedCheckStandards","kind":"identifier"}],"symbolKind":"property","title":"acceptedCheckStandards"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration\/acceptedcheckstandards"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration\/acceptedcheckstandards"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerBehaviorConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICheckScannerBehaviorConfiguration"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration","abstract":[{"text":"Configuration for the behavior of the RTU-UI check scanner.","type":"text"}],"title":"SBSDKUICheckScannerBehaviorConfiguration","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerBehaviorConfiguration/acceptedCheckStandards":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerBehaviorConfiguration\/acceptedCheckStandards","type":"topic","abstract":[{"type":"text","text":"An array of accepted check types."}],"url":"\/documentation\/scanbotsdk\/sbsdkuicheckscannerbehaviorconfiguration\/acceptedcheckstandards","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"acceptedCheckStandards","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKCheckDocumentModelRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckDocumentModelRootType"},{"kind":"text","text":"]"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"acceptedCheckStandards"}],"title":"acceptedCheckStandards"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentModelRootType":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKCheckDocumentModelRootType","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckDocumentModelRootType"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentmodelroottype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentModelRootType","title":"SBSDKCheckDocumentModelRootType","abstract":[{"type":"text","text":"Root document type."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"acceptedCheckStandards","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"acceptedCheckStandards"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKCheckDocumentModelRootType *>"},{"kind":"text","text":" * "},{"text":"acceptedCheckStandards","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUICheckScannerBehaviorConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUICheckScannerBehaviorConfiguration"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUICheckScannerBehaviorConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1acceptedCheckStandards\/title","op":"replace","value":"acceptedCheckStandards"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerBehaviorConfiguration~1acceptedCheckStandards\/fragments","value":[{"text":"acceptedCheckStandards","kind":"identifier"}],"op":"replace"},{"value":"SBSDKCheckDocumentModelRootType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/fragments","op":"replace","value":[{"text":"SBSDKCheckDocumentModelRootType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentModelRootType\/navigatorTitle","value":[{"text":"SBSDKCheckDocumentModelRootType","kind":"identifier"}]}]}]}