{"abstract":[{"type":"text","text":"The check scanner paused the detection and scanning."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerstate\/paused"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerstate\/paused"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState\/paused"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paused"}]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paused","kind":"identifier"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKCheckScannerState@SBSDKCheckScannerStatePaused","title":"SBSDKCheckScannerState.paused","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerStatePaused"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerState/paused":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState\/paused","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerstate\/paused","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerStatePaused"}],"title":"SBSDKCheckScannerState.paused","type":"topic","abstract":[{"text":"The check scanner paused the detection and scanning.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerState":{"title":"SBSDKCheckScannerState","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerstate","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKCheckScannerState","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKCheckScannerState","kind":"identifier"}],"abstract":[{"type":"text","text":"The live scanning state of the check scanner."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKCheckScannerStatePaused"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKCheckScannerStatePaused","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKCheckScannerStatePaused","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState~1paused\/title","value":"SBSDKCheckScannerStatePaused","op":"replace"},{"op":"replace","value":[{"text":"SBSDKCheckScannerStatePaused","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState~1paused\/fragments"},{"value":"SBSDKCheckScannerState","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/fragments","op":"replace","value":[{"text":"SBSDKCheckScannerState","kind":"identifier"}]},{"value":[{"text":"SBSDKCheckScannerState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerState\/navigatorTitle"}]}]}