{"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode39configuration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode39Configuration"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormatCode39Configuration(py)hash","role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode39Configuration\/hash"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode39Configuration":{"abstract":[{"type":"text","text":"Code 39 barcode and derivatives configuration. Add to scanner configuration to scan Code 39, Code 32 (Italian"},{"type":"text","text":" "},{"type":"text","text":"Pharmacode), PZN7 and PZN8 (Pharmazentralnummer) barcodes."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeFormatCode39Configuration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode39Configuration","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode39configuration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormatCode39Configuration/hash":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormatCode39Configuration\/hash","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformatcode39configuration\/hash","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode39Configuration\/title","value":"SBSDKBarcodeFormatCode39Configuration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode39Configuration\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCode39Configuration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormatCode39Configuration\/navigatorTitle"}]}]}