{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/didfinish"]}],"metadata":{"symbolKind":"method","title":"didFinish","navigatorTitle":[{"kind":"identifier","text":"didFinish"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"didFinish","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController(im)didFinish"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didFinish"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/didFinish"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController/didFinish":{"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/didfinish","title":"didFinish","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didFinish"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/didFinish","fragments":[{"kind":"text","text":"- "},{"text":"didFinish","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes.","type":"text"}],"role":"symbol","deprecated":true,"title":"SBSDKUIBarcodeScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKUIBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]},{"value":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}