{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithCoder:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"symbolKind":"method","title":"initWithCoder:","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingViewController(im)initWithCoder:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller\/initwithcoder:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController\/initWithCoder:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController/initWithCoder:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController\/initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller\/initwithcoder:","role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingViewController":{"navigatorTitle":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable view controller to edit a pages polygon or the page’s orientation.","type":"text"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuicroppingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingViewController","title":"SBSDKUICroppingViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUICroppingViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/fragments","value":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICroppingViewController","kind":"identifier"}]}]}]}