{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/fullHD","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Select a full HD (1920x1080) video resolution.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fullHD","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/fullhd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/fullhd"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionFullHD","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionFullHD","title":"SBSDKVideoFrameResolution.fullHD","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fullHD","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution","kind":"symbol","title":"SBSDKVideoFrameResolution","abstract":[{"type":"text","text":"An enum describing the resolution of a video or camera stream."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKVideoFrameResolution","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution/fullHD":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/fullhd","kind":"symbol","title":"SBSDKVideoFrameResolution.fullHD","abstract":[{"text":"Select a full HD (1920x1080) video resolution.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/fullHD","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionFullHD","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullHD"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKVideoFrameResolutionFullHD","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKVideoFrameResolution","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1fullHD\/title","value":"SBSDKVideoFrameResolutionFullHD"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionFullHD"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1fullHD\/fragments"}]}]}