{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputKeyMaterial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"salt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The input key material used to create the pseudo random key used during the extraction phase.","type":"text"}],"type":"paragraph"}],"name":"inputKeyMaterial"},{"content":[{"inlineContent":[{"text":"The info data block that may be used during the expansion phase. Optional. Default is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"info"},{"content":[{"inlineContent":[{"type":"text","text":"The salt data block that may be used during  the extraction phase. Optional. Default is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"salt"}],"kind":"parameters"}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inputKeyMaterial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"salt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithInputKeyMaterial:info:salt:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Initializer","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKHKDFKeyGenerator(im)initWithInputKeyMaterial:info:salt:","symbolKind":"init","title":"init(inputKeyMaterial:info:salt:)","platforms":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS"},{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkhkdfkeygenerator\/init(inputkeymaterial:info:salt:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkhkdfkeygenerator\/init(inputkeymaterial:info:salt:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKHKDFKeyGenerator\/init(inputKeyMaterial:info:salt:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKHKDFKeyGenerator"]]},"abstract":[{"text":"Designated initializer.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKHKDFKeyGenerator/init(inputKeyMaterial:info:salt:)":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkhkdfkeygenerator\/init(inputkeymaterial:info:salt:)","title":"init(inputKeyMaterial:info:salt:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inputKeyMaterial","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"salt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Designated initializer."}],"navigatorTitle":[{"text":"initWithInputKeyMaterial:info:salt:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKHKDFKeyGenerator\/init(inputKeyMaterial:info:salt:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKHKDFKeyGenerator":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKHKDFKeyGenerator","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"title":"SBSDKHKDFKeyGenerator","kind":"symbol","abstract":[{"type":"text","text":"A key generator that uses the HMAC based HKDF algorithm to generate a new encryption key. SHA512 is used as the hash function."},{"type":"text","text":" "},{"type":"text","text":"The key generation consists of two phases: extraction and expansion."},{"type":"text","text":" "},{"type":"text","text":"During the extraction a pseudo random key is generated from the input key material and an optional salt."},{"type":"text","text":" "},{"type":"text","text":"The expansion phase uses the pseudo random key and the info data block to derive the final key."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkhkdfkeygenerator"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithInputKeyMaterial:info:salt:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithInputKeyMaterial:info:salt:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithInputKeyMaterial:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"inputKeyMaterial","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"info:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"salt:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"salt","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The input key material used to create the pseudo random key used during the extraction phase.","type":"text"}]}],"name":"inputKeyMaterial"},{"content":[{"inlineContent":[{"text":"The info data block that may be used during the expansion phase. Optional. Default is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"info"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The salt data block that may be used during  the extraction phase. Optional. Default is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"salt"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKHKDFKeyGenerator~1init(inputKeyMaterial:info:salt:)\/title","op":"replace","value":"initWithInputKeyMaterial:info:salt:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKHKDFKeyGenerator~1init(inputKeyMaterial:info:salt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithInputKeyMaterial:info:salt:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKHKDFKeyGenerator\/title","value":"SBSDKHKDFKeyGenerator","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKHKDFKeyGenerator\/fragments","value":[{"kind":"identifier","text":"SBSDKHKDFKeyGenerator"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKHKDFKeyGenerator\/navigatorTitle","value":[{"text":"SBSDKHKDFKeyGenerator","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}