{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/hash","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"symbolKind":"property","title":"hash","fragments":[{"kind":"identifier","text":"hash"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration(py)hash","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"identifier"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","abstract":[{"type":"text","text":"Configuration for the European health insurance card (EHIC) recognizer."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/hash","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognizerconfiguration\/hash","type":"topic","abstract":[],"title":"hash","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognizerConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}