{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagestoring\/addimage(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagestoring\/addimage(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","title":"addImage(from:)","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addImageFromURL:"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring(im)addImageFromURL:","required":true,"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring\/addImage(from:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(addImageFromURL:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"url","content":[{"inlineContent":[{"text":"The file ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" of the image to be added.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"type":"text","text":", if the operation was successful, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Adds an image from a file into the storage."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}],"type":"topic","role":"symbol","title":"SBSDKImageStoring","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageStoring","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring/addImage(from:)":{"navigatorTitle":[{"text":"addImageFromURL:","kind":"identifier"}],"abstract":[{"text":"Adds an image from a file into the storage.","type":"text"}],"title":"addImage(from:)","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring\/addimage(from:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring\/addImage(from:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"addImageFromURL:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"addImageFromURL:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"addImageFromURL:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The file ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" of the image to be added.","type":"text"}]}],"name":"url"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"","type":"text"},{"code":"True","type":"codeVoice"},{"text":", if the operation was successful, ","type":"text"},{"code":"False","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"SBSDKImageStoring","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageStoring","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/navigatorTitle","op":"replace"},{"value":"addImageFromURL:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring~1addImage(from:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addImageFromURL:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring~1addImage(from:)\/fragments","op":"replace"}]}]}