{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions\/format"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions\/format"]}],"abstract":[{"type":"text","text":"Image format."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEncodingFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncodingFormat"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is JPEG","type":"text"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions\/format"},"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEncodingFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncodingFormat"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKEncodeImageOptions(py)format","navigatorTitle":[{"text":"format","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","title":"format"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","abstract":[{"text":"Version: 8.0.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodingFormat":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKEncodingFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Image Encoding Format."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncodingFormat","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodingformat","title":"SBSDKEncodingFormat","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodeImageOptions":{"abstract":[{"text":"Options for encoding image.","type":"text"}],"navigatorTitle":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions","title":"SBSDKEncodeImageOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodeImageOptions/format":{"type":"topic","title":"format","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions\/format","abstract":[{"type":"text","text":"Image format."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions\/format","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncodingFormat","text":"SBSDKEncodingFormat"}],"navigatorTitle":[{"kind":"identifier","text":"format"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"format"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"format","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKEncodingFormat","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKEncodingFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodingFormat"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/title","value":"SBSDKEncodingFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/fragments","value":[{"text":"SBSDKEncodingFormat","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKEncodingFormat"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodingFormat\/navigatorTitle","op":"replace"},{"value":"SBSDKEncodeImageOptions","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/fragments","op":"replace"},{"value":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/navigatorTitle","op":"replace"},{"value":"format","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions~1format\/title","op":"replace"},{"value":[{"kind":"identifier","text":"format"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions~1format\/fragments","op":"replace"}]}]}