{"metadata":{"roleHeading":"Case","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateCheckBoxType@SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes","title":"SBSDKMedicalCertificateCheckBoxType.entitlementToContinuedPaymentYes","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"entitlementToContinuedPaymentYes","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/entitlementtocontinuedpaymentyes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/entitlementtocontinuedpaymentyes"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"entitlementToContinuedPaymentYes","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentYes"},"abstract":[{"type":"text","text":"(Form 21a) Entitlement to continued payment yes (Anspruch auf Entgeltfortzahlung) checkbox."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Type of the checkbox."}],"title":"SBSDKMedicalCertificateCheckBoxType","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKMedicalCertificateCheckBoxType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateCheckBoxType/entitlementToContinuedPaymentYes":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateCheckBoxType\/entitlementToContinuedPaymentYes","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatecheckboxtype\/entitlementtocontinuedpaymentyes","abstract":[{"type":"text","text":"(Form 21a) Entitlement to continued payment yes (Anspruch auf Entgeltfortzahlung) checkbox."}],"kind":"symbol","title":"SBSDKMedicalCertificateCheckBoxType.entitlementToContinuedPaymentYes","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entitlementToContinuedPaymentYes","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/title","op":"replace","value":"SBSDKMedicalCertificateCheckBoxType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateCheckBoxType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1entitlementToContinuedPaymentYes\/title","value":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateCheckBoxTypeEntitlementToContinuedPaymentYes","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateCheckBoxType~1entitlementToContinuedPaymentYes\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}