{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate(im)documentScannerViewController:polygonFillColorForStatus:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"kind":"text","text":"("},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"text":"polygonFillColorFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"role":"symbol","title":"documentScannerViewController(_:polygonFillColorFor:)","navigatorTitle":[{"text":"documentScannerViewController:polygonFillColorForStatus:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate"]]},"abstract":[{"text":"Optional.","type":"text"},{"type":"text","text":" "},{"text":"Asks the delegate for the fill color of the polygon that surrounds the detected polygon on the screen, depending on the document detection status.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:polygonFillColorFor:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:polygonfillcolorfor:)"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:polygonfillcolorfor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(documentScannerViewController:polygonFillColorForStatus:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygonFillColorFor","kind":"externalParam"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]}]},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The document scanner controller that called this function."}],"type":"paragraph"}]},{"name":"status","content":[{"inlineContent":[{"type":"text","text":"The status of the current document detection."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The fill color for the displayed polygon."}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 5.0.2","type":"text"}],"role":"collection","type":"topic","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"role":"symbol","title":"SBSDKDocumentScannerViewControllerDelegate","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate","abstract":[{"type":"text","text":"The delegate protocol of "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"title":"SBSDKDocumentScannerViewController","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document detector.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewControllerDelegate/documentScannerViewController(_:polygonFillColorFor:)":{"role":"symbol","title":"documentScannerViewController(_:polygonFillColorFor:)","kind":"symbol","navigatorTitle":[{"text":"documentScannerViewController:polygonFillColorForStatus:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:polygonfillcolorfor:)","abstract":[{"text":"Optional.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Asks the delegate for the fill color of the polygon that surrounds the detected polygon on the screen, depending on the document detection status."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:polygonFillColorFor:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"polygonFillColorFor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"documentScannerViewController:polygonFillColorForStatus:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"documentScannerViewController:polygonFillColorForStatus:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"text":"documentScannerViewController:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"polygonFillColorForStatus:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/title","value":"SBSDKDocumentScannerViewControllerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title","value":"SBSDKDocumentScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"op":"replace"},{"value":"documentScannerViewController:polygonFillColorForStatus:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:polygonFillColorFor:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:polygonFillColorFor:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:polygonFillColorForStatus:","kind":"identifier"}]}]}]}