{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKDocumentScannerViewControllerDelegate(im)documentScannerViewController:shouldAutoSnapImageWithForDetectionResult:","required":true,"title":"documentScannerViewController(_:shouldAutoSnapImageWithForDetectionResult:)","navigatorTitle":[{"text":"documentScannerViewController:shouldAutoSnapImageWithForDetectionResult:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentScannerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldAutoSnapImageWithForDetectionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"text":"SBSDKDocumentScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"},{"text":", ","kind":"text"},{"text":"shouldAutoSnapImageWithForDetectionResult","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"result"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The document scanner controller that called this function.","type":"text"}]}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"text":"The result of the document detection on the previous video frame.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"True","type":"codeVoice"},{"type":"text","text":", if you want to schedule automatic snapping, "},{"type":"codeVoice","code":"False"},{"text":" otherwise.","type":"text"}]}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"It’s not called if "},{"type":"codeVoice","code":"autoSnappingMode"},{"text":" is set to SBSDKAutosnappingModeDisabled or SBSDKAutosnappingModeDisabledWithGuidance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:shouldautosnapimagewithfordetectionresult:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:shouldautosnapimagewithfordetectionresult:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:shouldAutoSnapImageWithForDetectionResult:)","interfaceLanguage":"swift"},"abstract":[{"text":"Optional.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Asks the delegate whether it should automatically snap an image when a document was detected on the video frame."}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewController":{"title":"SBSDKDocumentScannerViewController","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontroller","type":"topic","abstract":[{"type":"text","text":"A UIViewController subclass to show a camera screen and run a user guiding document detector."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewControllerDelegate/documentScannerViewController(_:shouldAutoSnapImageWithForDetectionResult:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentScannerViewController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","kind":"typeIdentifier","text":"SBSDKDocumentScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldAutoSnapImageWithForDetectionResult"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate\/documentScannerViewController(_:shouldAutoSnapImageWithForDetectionResult:)","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate\/documentscannerviewcontroller(_:shouldautosnapimagewithfordetectionresult:)","required":true,"title":"documentScannerViewController(_:shouldAutoSnapImageWithForDetectionResult:)","navigatorTitle":[{"kind":"identifier","text":"documentScannerViewController:shouldAutoSnapImageWithForDetectionResult:"}],"abstract":[{"type":"text","text":"Optional."},{"type":"text","text":" "},{"type":"text","text":"Asks the delegate whether it should automatically snap an image when a document was detected on the video frame."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectorResult":{"navigatorTitle":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}],"title":"SBSDKDocumentDetectorResult","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectorresult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult","abstract":[{"type":"text","text":"This class represents the result of a document detection"},{"text":" ","type":"text"},{"text":"on an image.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerViewControllerDelegate":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewControllerDelegate","abstract":[{"type":"text","text":"The delegate protocol of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"},{"type":"text","text":"."}],"kind":"symbol","title":"SBSDKDocumentScannerViewControllerDelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerViewControllerDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"documentScannerViewController:shouldAutoSnapImageWithForDetectionResult:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"documentScannerViewController:shouldAutoSnapImageWithForDetectionResult:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"documentScannerViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerViewController","text":"SBSDKDocumentScannerViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"shouldAutoSnapImageWithForDetectionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectorResult","kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectorResult"},{"kind":"text","text":" *) "},{"text":"result","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewController\/fragments","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"op":"replace","value":"documentScannerViewController:shouldAutoSnapImageWithForDetectionResult:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:shouldAutoSnapImageWithForDetectionResult:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate~1documentScannerViewController(_:shouldAutoSnapImageWithForDetectionResult:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentScannerViewController:shouldAutoSnapImageWithForDetectionResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/title","value":"SBSDKDocumentDetectorResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectorResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/title","value":"SBSDKDocumentScannerViewControllerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}