{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration\/topbarbuttonscolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration\/topbarbuttonscolor"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration"]]},"abstract":[{"type":"text","text":"Foreground color of the top bar buttons (Done, Cancel)."}],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"topBarButtonsColor","kind":"identifier"}],"roleHeading":"Instance Property","title":"topBarButtonsColor","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration(py)topBarButtonsColor","role":"symbol","platforms":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topBarButtonsColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topBarButtonsColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2CroppingViewController instead.","type":"text"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration\/topBarButtonsColor","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenUIConfiguration/topBarButtonsColor":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarButtonsColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"topBarButtonsColor","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration\/topbarbuttonscolor","title":"topBarButtonsColor","abstract":[{"type":"text","text":"Foreground color of the top bar buttons (Done, Cancel)."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration\/topBarButtonsColor","deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingScreenUIConfiguration":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for user interface of the page cropping screen."}],"title":"SBSDKUICroppingScreenUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingScreenUIConfiguration","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingscreenuiconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"topBarButtonsColor","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"topBarButtonsColor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"topBarButtonsColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"topBarButtonsColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration~1topBarButtonsColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration~1topBarButtonsColor\/fragments","value":[{"text":"topBarButtonsColor","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKUICroppingScreenUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration\/fragments","value":[{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingScreenUIConfiguration\/navigatorTitle"}]}]}