{"abstract":[{"text":"The style of the dialog\/alert in case of error.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDialogStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/errordialogstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/errordialogstyle"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICheckScannerUIConfiguration(py)errorDialogStyle","title":"errorDialogStyle","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDialogStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle","text":"SBSDKUIDialogStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"errorDialogStyle"}],"roleHeading":"Instance Property","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration\/errorDialogStyle"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerUIConfiguration":{"navigatorTitle":[{"text":"SBSDKUICheckScannerUIConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUICheckScannerUIConfiguration","kind":"identifier"}],"title":"SBSDKUICheckScannerUIConfiguration","abstract":[{"text":"Configuration for the user interface of the RTU-UI check scanner.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICheckScannerUIConfiguration/errorDialogStyle":{"abstract":[{"type":"text","text":"The style of the dialog\/alert in case of error."}],"title":"errorDialogStyle","role":"symbol","navigatorTitle":[{"text":"errorDialogStyle","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDialogStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle","text":"SBSDKUIDialogStyle","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICheckScannerUIConfiguration\/errorDialogStyle","url":"\/documentation\/scanbotsdk\/sbsdkuicheckscanneruiconfiguration\/errordialogstyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDialogStyle":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidialogstyle","abstract":[{"text":"The general style for a dialog in ScanbotSDK. Used to customize certain result dialogs in SBSDKUI components.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIDialogStyle","kind":"identifier"}],"title":"SBSDKUIDialogStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIDialogStyle","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"errorDialogStyle"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"errorDialogStyle","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIDialogStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDialogStyle","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDialogStyle"},{"kind":"text","text":" * "},{"text":"errorDialogStyle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"SBSDKUICheckScannerUIConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/title"},{"value":[{"text":"SBSDKUICheckScannerUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUICheckScannerUIConfiguration","kind":"identifier"}]},{"op":"replace","value":"errorDialogStyle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration~1errorDialogStyle\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICheckScannerUIConfiguration~1errorDialogStyle\/fragments","op":"replace","value":[{"text":"errorDialogStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogStyle\/title","value":"SBSDKUIDialogStyle"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDialogStyle"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogStyle\/fragments"},{"value":[{"text":"SBSDKUIDialogStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDialogStyle\/navigatorTitle","op":"replace"}]}]}