{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/acceptedcheckstandards"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/acceptedcheckstandards"]}],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration(py)acceptedCheckStandards","navigatorTitle":[{"text":"acceptedCheckStandards","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedCheckStandards","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKCheckStandard","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard"},{"text":"]","kind":"text"}],"title":"acceptedCheckStandards"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/acceptedCheckStandards"},"kind":"symbol","abstract":[{"type":"text","text":"Accepted check standards. Optional, by default - all checks are accepted."},{"type":"text","text":" "},{"type":"text","text":"With an empty list no filter is applied and all checks are accepted."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedCheckStandards","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","text":"SBSDKCheckStandard","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration","kind":"symbol","title":"SBSDKCheckScannerConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the check scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration/acceptedCheckStandards":{"navigatorTitle":[{"kind":"identifier","text":"acceptedCheckStandards"}],"title":"acceptedCheckStandards","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/acceptedCheckStandards","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/acceptedcheckstandards","abstract":[{"text":"Accepted check standards. Optional, by default - all checks are accepted.","type":"text"},{"text":" ","type":"text"},{"text":"With an empty list no filter is applied and all checks are accepted.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedCheckStandards","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckStandard","text":"SBSDKCheckStandard"},{"kind":"text","text":"]"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckStandard":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Supported check standards."}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckstandard","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckStandard","navigatorTitle":[{"text":"SBSDKCheckStandard","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCheckStandard","kind":"identifier"}],"title":"SBSDKCheckStandard"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"acceptedCheckStandards"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"acceptedCheckStandards","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKCheckStandard *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"acceptedCheckStandards","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKCheckScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/title"},{"value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/navigatorTitle"},{"value":"acceptedCheckStandards","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration~1acceptedCheckStandards\/title"},{"value":[{"text":"acceptedCheckStandards","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration~1acceptedCheckStandards\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/title","value":"SBSDKCheckStandard","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/fragments","value":[{"text":"SBSDKCheckStandard","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckStandard\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckStandard"}],"op":"replace"}]}]}