{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/initWithDocumentDetectionMode:acceptedCheckStandards:"},"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithDocumentDetectionMode:acceptedCheckStandards:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"initWithDocumentDetectionMode:acceptedCheckStandards:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration(im)initWithDocumentDetectionMode:acceptedCheckStandards:","role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDocumentDetectionMode:acceptedCheckStandards:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocumentDetectionMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode","text":"SBSDKCheckDocumentDetectionMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"documentDetectionMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedCheckStandards:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKCheckStandard *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"acceptedCheckStandards"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/initwithdocumentdetectionmode:acceptedcheckstandards:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration","kind":"symbol","title":"SBSDKCheckScannerConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the check scanner."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration/initWithDocumentDetectionMode:acceptedCheckStandards:":{"title":"initWithDocumentDetectionMode:acceptedCheckStandards:","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/initwithdocumentdetectionmode:acceptedcheckstandards:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDocumentDetectionMode:acceptedCheckStandards:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/initWithDocumentDetectionMode:acceptedCheckStandards:","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithDocumentDetectionMode:acceptedCheckStandards:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode","title":"SBSDKCheckDocumentDetectionMode","type":"topic","abstract":[{"type":"text","text":"Check document detection and extraction mode."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/title","value":"SBSDKCheckScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/title","value":"SBSDKCheckDocumentDetectionMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/fragments","value":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/navigatorTitle","value":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}