{"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","title":"multipleScanningMode()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"multipleScanningMode","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2MultipleScanningMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeUseCase(cm)multipleScanningMode","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"multipleScanningMode"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multipleScanningMode","kind":"identifier"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode","text":"SBSDKUI2MultipleScanningMode","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase\/multipleScanningMode()"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeusecase\/multiplescanningmode()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeusecase\/multiplescanningmode()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeUseCase":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the barcode scanner screen’s behavior."}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeusecase","title":"SBSDKUI2BarcodeUseCase"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MultipleScanningMode":{"navigatorTitle":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2multiplescanningmode","title":"SBSDKUI2MultipleScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration of the mode for scanning multiple barcodes."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeUseCase/multipleScanningMode()":{"title":"multipleScanningMode()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeUseCase\/multipleScanningMode()","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeusecase\/multiplescanningmode()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"multipleScanningMode","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode","text":"SBSDKUI2MultipleScanningMode","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"multipleScanningMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"multipleScanningMode","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"multipleScanningMode","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MultipleScanningMode","kind":"typeIdentifier","text":"SBSDKUI2MultipleScanningMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MultipleScanningMode"},{"text":" *) ","kind":"text"},{"text":"multipleScanningMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"SBSDKUI2BarcodeUseCase","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/fragments","value":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarcodeUseCase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/title","value":"SBSDKUI2MultipleScanningMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/fragments","value":[{"text":"SBSDKUI2MultipleScanningMode","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2MultipleScanningMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MultipleScanningMode\/navigatorTitle"},{"value":"multipleScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase~1multipleScanningMode()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeUseCase~1multipleScanningMode()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"multipleScanningMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}