{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroImage\/checkIntroDefaultImage()"},"metadata":{"symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkIntroDefaultImage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckIntroDefaultImage","text":"SBSDKUI2CheckIntroDefaultImage"}],"modules":[{"name":"ScanbotSDK"}],"title":"checkIntroDefaultImage()","navigatorTitle":[{"kind":"identifier","text":"checkIntroDefaultImage"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerIntroImage(cm)checkIntroDefaultImage"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkIntroDefaultImage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroDefaultImage","text":"SBSDKUI2CheckIntroDefaultImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckIntroDefaultImage"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroimage\/checkintrodefaultimage()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroimage\/checkintrodefaultimage()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroImage"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckIntroDefaultImage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroDefaultImage","role":"symbol","abstract":[{"text":"No image for the introduction screen.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckIntroDefaultImage"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckIntroDefaultImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkintrodefaultimage","title":"SBSDKUI2CheckIntroDefaultImage","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerIntroImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CheckScannerIntroImage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerIntroImage"}],"type":"topic","abstract":[{"type":"text","text":"The image for the introduction screen of a check scanner screen."}],"kind":"symbol","role":"symbol","title":"SBSDKUI2CheckScannerIntroImage","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroimage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerIntroImage/checkIntroDefaultImage()":{"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerintroimage\/checkintrodefaultimage()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"checkIntroDefaultImage"}],"title":"checkIntroDefaultImage()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkIntroDefaultImage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2CheckIntroDefaultImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckIntroDefaultImage"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerIntroImage\/checkIntroDefaultImage()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"checkIntroDefaultImage","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"checkIntroDefaultImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2CheckIntroDefaultImage","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroDefaultImage","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckIntroDefaultImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"checkIntroDefaultImage","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2CheckIntroDefaultImage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroDefaultImage\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2CheckIntroDefaultImage"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroDefaultImage\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroDefaultImage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CheckIntroDefaultImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroImage\/title","value":"SBSDKUI2CheckScannerIntroImage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroImage\/fragments","value":[{"text":"SBSDKUI2CheckScannerIntroImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroImage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CheckScannerIntroImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroImage~1checkIntroDefaultImage()\/title","value":"checkIntroDefaultImage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerIntroImage~1checkIntroDefaultImage()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkIntroDefaultImage"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}