{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerCancelButtonItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageEditingViewController","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"He calling SBSDKImageEditingViewController."}],"type":"paragraph"}],"name":"editingViewController"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The "},{"code":"UIBarButtonItem","type":"codeVoice"},{"type":"text","text":" for cancelling the editing."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Asks the delegate for a "},{"type":"codeVoice","code":"UIBarButtonItem"},{"type":"text","text":" to cancel the actual editing."}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollercancelbuttonitem(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollercancelbuttonitem(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKImageEditingViewControllerDelegate(im)imageEditingViewControllerCancelButtonItem:","role":"symbol","title":"imageEditingViewControllerCancelButtonItem(_:)","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem"},{"kind":"text","text":"?"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"abstract":[{"type":"text","text":"A delegate protocol to inform an object about changes in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController"},{"type":"text","text":"."}],"title":"SBSDKImageEditingViewControllerDelegate","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewControllerDelegate/imageEditingViewControllerCancelButtonItem(_:)":{"navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem:"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontrollerdelegate\/imageeditingviewcontrollercancelbuttonitem(_:)","abstract":[{"text":"Asks the delegate for a ","type":"text"},{"type":"codeVoice","code":"UIBarButtonItem"},{"text":" to cancel the actual editing.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewControllerDelegate\/imageEditingViewControllerCancelButtonItem(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerCancelButtonItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem"},{"kind":"text","text":"?"}],"title":"imageEditingViewControllerCancelButtonItem(_:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageEditingViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"title":"SBSDKImageEditingViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimageeditingviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" subclass to show and edit an image."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"imageEditingViewControllerCancelButtonItem:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerCancelButtonItem:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIBarButtonItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"text":" *) ","kind":"text"},{"text":"imageEditingViewControllerCancelButtonItem:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageEditingViewController","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageEditingViewController"},{"text":" *) ","kind":"text"},{"text":"editingViewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"He calling SBSDKImageEditingViewController."}]}],"name":"editingViewController"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"UIBarButtonItem","type":"codeVoice"},{"text":" for cancelling the editing.","type":"text"}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"SBSDKImageEditingViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/title"},{"value":[{"text":"SBSDKImageEditingViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageEditingViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate\/navigatorTitle"},{"value":"imageEditingViewControllerCancelButtonItem:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerCancelButtonItem(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"imageEditingViewControllerCancelButtonItem:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewControllerDelegate~1imageEditingViewControllerCancelButtonItem(_:)\/fragments"},{"value":"SBSDKImageEditingViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKImageEditingViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageEditingViewController\/navigatorTitle"}]}]}