{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedSizeScore"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Defaults to 80.0."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Lower values result in low resolution document images."}]}],"name":"Warning","style":"warning","type":"aside"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/acceptedsizescore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/acceptedsizescore"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/acceptedSizeScore"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerViewController(py)acceptedSizeScore","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedSizeScore"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"acceptedSizeScore","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"acceptedSizeScore"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController"]]},"abstract":[{"text":"The minimum size in percent (0 - 100) of the screen size to accept a detected document.","type":"text"},{"type":"text","text":" "},{"text":"It is sufficient that height or width match the score.","type":"text"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}],"abstract":[{"text":"A UIViewController subclass to show a camera screen and run a user guiding document detector.","type":"text"}],"type":"topic","title":"SBSDKDocumentScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerViewController/acceptedSizeScore":{"title":"acceptedSizeScore","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerviewcontroller\/acceptedsizescore","kind":"symbol","abstract":[{"text":"The minimum size in percent (0 - 100) of the screen size to accept a detected document.","type":"text"},{"type":"text","text":" "},{"text":"It is sufficient that height or width match the score.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptedSizeScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"text":"acceptedSizeScore","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerViewController\/acceptedSizeScore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"acceptedSizeScore","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"acceptedSizeScore"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedSizeScore"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/title","op":"replace","value":"SBSDKDocumentScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController\/navigatorTitle","value":[{"text":"SBSDKDocumentScannerViewController","kind":"identifier"}]},{"value":"acceptedSizeScore","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1acceptedSizeScore\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerViewController~1acceptedSizeScore\/fragments","op":"replace","value":[{"text":"acceptedSizeScore","kind":"identifier"}]}]}]}