{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings(im)isEqual:","title":"isEqual:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/isequal:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/isEqual:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/isEqual:":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","title":"isEqual:","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/isEqual:","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerOutputSettings","abstract":[{"text":"Configuration of the output settings.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/title","value":"SBSDKUI2DocumentScannerOutputSettings"},{"value":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}