{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:numericvalue:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:numericvalue:)"]}],"metadata":{"roleHeading":"Initializer","title":"init(fieldName:fieldTag:numericValue:)","role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"fieldTag","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numericValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFImageWriterUserDefinedField(im)initWithFieldName:fieldTag:numericValue:","navigatorTitle":[{"text":"initWithFieldName:fieldTag:numericValue:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fieldName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fieldTag"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numericValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The name of the field."}],"type":"paragraph"}],"name":"fieldName"},{"name":"fieldTag","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tag of the field."}]}]},{"name":"numericValue","content":[{"inlineContent":[{"text":"The numeric value of the field.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"text":"Creates a new user-defined TIFF field with a numeric-type value.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField\/init(fieldName:fieldTag:numericValue:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedField":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield","title":"SBSDKTIFFImageWriterUserDefinedField","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedField"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedField"}],"role":"symbol","abstract":[{"text":"A class used to describe a user-defined TIFF field.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedField/init(fieldName:fieldTag:numericValue:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedField\/init(fieldName:fieldTag:numericValue:)","title":"init(fieldName:fieldTag:numericValue:)","abstract":[{"type":"text","text":"Creates a new user-defined TIFF field with a numeric-type value."}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfield\/init(fieldname:fieldtag:numericvalue:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"fieldName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"fieldTag","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"numericValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithFieldName:fieldTag:numericValue:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithFieldName:fieldTag:numericValue:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldName:fieldTag:numericValue:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithFieldName:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"fieldName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fieldTag:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"fieldTag","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"numericValue:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"numericValue"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The name of the field."}],"type":"paragraph"}],"name":"fieldName"},{"content":[{"inlineContent":[{"type":"text","text":"The tag of the field."}],"type":"paragraph"}],"name":"fieldTag"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The numeric value of the field."}]}],"name":"numericValue"}],"kind":"parameters"}},{"op":"replace","value":"SBSDKTIFFImageWriterUserDefinedField","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField\/title"},{"op":"replace","value":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField\/fragments"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField\/navigatorTitle"},{"value":"initWithFieldName:fieldTag:numericValue:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField~1init(fieldName:fieldTag:numericValue:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFieldName:fieldTag:numericValue:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedField~1init(fieldName:fieldTag:numericValue:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}