{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Normalized full name of the “PhysicalDescriptionSex” field type in document type “AAMVA.DLID”.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvadlidPhysicalDescriptionSexFieldNormalizedName","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"aamvadlidPhysicalDescriptionSexFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvadlidphysicaldescriptionsexfieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvadlidphysicaldescriptionsexfieldnormalizedname"]}],"metadata":{"navigatorTitle":[{"text":"aamvadlidPhysicalDescriptionSexFieldNormalizedName","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"aamvadlidPhysicalDescriptionSexFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvadlidPhysicalDescriptionSexFieldNormalizedName","roleHeading":"Type Property","title":"aamvadlidPhysicalDescriptionSexFieldNormalizedName","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants/aamvadlidPhysicalDescriptionSexFieldNormalizedName":{"navigatorTitle":[{"kind":"identifier","text":"aamvadlidPhysicalDescriptionSexFieldNormalizedName"}],"kind":"symbol","abstract":[{"type":"text","text":"Normalized full name of the “PhysicalDescriptionSex” field type in document type “AAMVA.DLID”."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvadlidphysicaldescriptionsexfieldnormalizedname","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvadlidPhysicalDescriptionSexFieldNormalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvadlidPhysicalDescriptionSexFieldNormalizedName","title":"aamvadlidPhysicalDescriptionSexFieldNormalizedName","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants","title":"SBSDKBarcodeDocumentConstants"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","value":"aamvadlidPhysicalDescriptionSexFieldNormalizedName","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"aamvadlidPhysicalDescriptionSexFieldNormalizedName"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aamvadlidPhysicalDescriptionSexFieldNormalizedName"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"aamvadlidPhysicalDescriptionSexFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvadlidPhysicalDescriptionSexFieldNormalizedName\/title"},{"op":"replace","value":[{"text":"aamvadlidPhysicalDescriptionSexFieldNormalizedName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvadlidPhysicalDescriptionSexFieldNormalizedName\/fragments"},{"value":"SBSDKBarcodeDocumentConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]}]}]}