{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","role":"symbol","title":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"Normalized full name of the “InspectionFormOrStickerNumberPrevious” field type in document type “AAMVA.VehicleSafetyInspectionData”."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvavehiclesafetyinspectiondatainspectionformorstickernumberpreviousfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvavehiclesafetyinspectiondatainspectionformorstickernumberpreviousfieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants/aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvavehiclesafetyinspectiondatainspectionformorstickernumberpreviousfieldnormalizedname","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","abstract":[{"type":"text","text":"Normalized full name of the “InspectionFormOrStickerNumberPrevious” field type in document type “AAMVA.VehicleSafetyInspectionData”."}],"title":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"role":"symbol","type":"topic","title":"SBSDKBarcodeDocumentConstants","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName"},{"text":";","kind":"text"}]}]}},{"value":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName\/title","op":"replace"},{"value":[{"text":"aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleSafetyInspectionDataInspectionFormOrStickerNumberPreviousFieldNormalizedName\/fragments"},{"value":"SBSDKBarcodeDocumentConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}