{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Normalized full name of the “BaseJurisdictionRegisteredWeight” field type in document type “AAMVA.RegistrantAndVehicleData”."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvaregistrantandvehicledatabasejurisdictionregisteredweightfieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvaregistrantandvehicledatabasejurisdictionregisteredweightfieldnormalizedname"]}],"metadata":{"symbolKind":"property","roleHeading":"Type Property","title":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","navigatorTitle":[{"kind":"identifier","text":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants/aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName":{"title":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","kind":"identifier"}],"abstract":[{"type":"text","text":"Normalized full name of the “BaseJurisdictionRegisteredWeight” field type in document type “AAMVA.RegistrantAndVehicleData”."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvaregistrantandvehicledatabasejurisdictionregisteredweightfieldnormalizedname","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants","title":"SBSDKBarcodeDocumentConstants"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName\/title","value":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName\/fragments","value":[{"kind":"identifier","text":"aamvaRegistrantAndVehicleDataBaseJurisdictionRegisteredWeightFieldNormalizedName"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/title","op":"replace","value":"SBSDKBarcodeDocumentConstants"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/fragments","value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}]}]}]}