{"metadata":{"roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","title":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)aamvaVehicleDataNumberOfAxlesFieldNormalizedName"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleDataNumberOfAxlesFieldNormalizedName","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Normalized full name of the “NumberOfAxles” field type in document type “AAMVA.VehicleData”.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvavehicledatanumberofaxlesfieldnormalizedname"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvavehicledatanumberofaxlesfieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"]]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"title":"SBSDKBarcodeDocumentConstants","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants/aamvaVehicleDataNumberOfAxlesFieldNormalizedName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/aamvaVehicleDataNumberOfAxlesFieldNormalizedName","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/aamvavehicledatanumberofaxlesfieldnormalizedname","kind":"symbol","title":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName","type":"topic","role":"symbol","abstract":[{"text":"Normalized full name of the “NumberOfAxles” field type in document type “AAMVA.VehicleData”.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeDocumentConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleDataNumberOfAxlesFieldNormalizedName\/title","value":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1aamvaVehicleDataNumberOfAxlesFieldNormalizedName\/fragments","op":"replace","value":[{"kind":"identifier","text":"aamvaVehicleDataNumberOfAxlesFieldNormalizedName"}]}]}]}