{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Normalized full name of the “SourceOfBoardingPassIssuance” field type in document type “BoardingPass.Leg”.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/boardingpasslegsourceofboardingpassissuancefieldnormalizedname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/boardingpasslegsourceofboardingpassissuancefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","navigatorTitle":[{"text":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","kind":"identifier"}],"roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants/boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","title":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName"}],"abstract":[{"text":"Normalized full name of the “SourceOfBoardingPassIssuance” field type in document type “BoardingPass.Leg”.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/boardingpasslegsourceofboardingpassissuancefieldnormalizedname","kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"role":"symbol","type":"topic","title":"SBSDKBarcodeDocumentConstants","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName\/fragments","value":[{"text":"boardingPassLegSourceOfBoardingPassIssuanceFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"value":"SBSDKBarcodeDocumentConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"op":"replace"}]}]}