{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName","navigatorTitle":[{"kind":"identifier","text":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName"}],"modules":[{"name":"ScanbotSDK"}],"title":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Type Property"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Normalized full name of the “GeneralNotes” field type in document type “DEMedicalPlan.Subheading.Medicine”."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/demedicalplansubheadingmedicinegeneralnotesfieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/demedicalplansubheadingmedicinegeneralnotesfieldnormalizedname"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants","role":"symbol","abstract":[],"title":"SBSDKBarcodeDocumentConstants","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants/deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName","abstract":[{"type":"text","text":"Normalized full name of the “GeneralNotes” field type in document type “DEMedicalPlan.Subheading.Medicine”."}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/demedicalplansubheadingmedicinegeneralnotesfieldnormalizedname","title":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/title","op":"replace","value":"SBSDKBarcodeDocumentConstants"},{"value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName\/title","op":"replace","value":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName"},{"value":[{"text":"deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1deMedicalPlanSubheadingMedicineGeneralNotesFieldNormalizedName\/fragments","op":"replace"}]}]}