{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants"]]},"kind":"symbol","abstract":[{"text":"Normalized full name of the “PayeeAddressType” field type in document type “SwissQR”.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/swissqrpayeeaddresstypefieldnormalizedname"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/swissqrpayeeaddresstypefieldnormalizedname"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"swissQRPayeeAddressTypeFieldNormalizedName","roleHeading":"Type Property","navigatorTitle":[{"text":"swissQRPayeeAddressTypeFieldNormalizedName","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"swissQRPayeeAddressTypeFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentConstants(cpy)swissQRPayeeAddressTypeFieldNormalizedName","symbolKind":"property"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/swissQRPayeeAddressTypeFieldNormalizedName","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"swissQRPayeeAddressTypeFieldNormalizedName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants/swissQRPayeeAddressTypeFieldNormalizedName":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants\/swissqrpayeeaddresstypefieldnormalizedname","title":"swissQRPayeeAddressTypeFieldNormalizedName","type":"topic","abstract":[{"text":"Normalized full name of the “PayeeAddressType” field type in document type “SwissQR”.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants\/swissQRPayeeAddressTypeFieldNormalizedName","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"swissQRPayeeAddressTypeFieldNormalizedName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"swissQRPayeeAddressTypeFieldNormalizedName","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentConstants":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentConstants","title":"SBSDKBarcodeDocumentConstants","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentconstants","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"swissQRPayeeAddressTypeFieldNormalizedName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"swissQRPayeeAddressTypeFieldNormalizedName","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"swissQRPayeeAddressTypeFieldNormalizedName"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"swissQRPayeeAddressTypeFieldNormalizedName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1swissQRPayeeAddressTypeFieldNormalizedName\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants~1swissQRPayeeAddressTypeFieldNormalizedName\/fragments","op":"replace","value":[{"kind":"identifier","text":"swissQRPayeeAddressTypeFieldNormalizedName"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/title","value":"SBSDKBarcodeDocumentConstants"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/fragments"},{"value":[{"text":"SBSDKBarcodeDocumentConstants","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentConstants\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}