{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUICroppingViewControllerDelegate","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUICroppingViewControllerDelegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"delegate","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICroppingViewController(py)delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUICroppingViewControllerDelegate","text":"SBSDKUICroppingViewControllerDelegate"},{"kind":"text","text":"?"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController\/delegate"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The receiver’s delegate"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingViewController/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontroller\/delegate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController\/delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"SBSDKUICroppingViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUICroppingViewControllerDelegate"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The receiver’s delegate"}],"title":"delegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingViewControllerDelegate":{"abstract":[{"text":"Delegate protocol for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"SBSDKUICroppingViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontrollerdelegate","type":"topic","role":"symbol","kind":"symbol","title":"SBSDKUICroppingViewControllerDelegate"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICroppingViewController":{"title":"SBSDKUICroppingViewController","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICroppingViewController","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicroppingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICroppingViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}],"kind":"symbol","abstract":[{"type":"text","text":"A highly customizable view controller to edit a pages polygon or the page’s orientation."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"delegate","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<SBSDKUICroppingViewControllerDelegate>","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKUICroppingViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"delegate","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController~1delegate\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"value":"SBSDKUICroppingViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"SBSDKUICroppingViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewControllerDelegate\/fragments"},{"value":"SBSDKUICroppingViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICroppingViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICroppingViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}