{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerviewcontroller\/present(on:configuration:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerviewcontroller\/present(on:configuration:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Creates a new instance of "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","type":"reference"},{"text":" and presents it modally.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController\/present(on:configuration:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":"(presentOn:configuration:completion:) ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"presenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration","text":"SBSDKUI2MRZScannerScreenConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerUIResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerUIResult","text":"SBSDKUI2MRZScannerUIResult"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerViewController","text":"SBSDKUI2MRZScannerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"presenter","content":[{"type":"paragraph","inlineContent":[{"text":"The view controller the new instance should be presented on.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The configuration object for the MRZ scanner screen."}],"type":"paragraph"}],"name":"configuration"},{"content":[{"inlineContent":[{"text":"The completion closure that is called when the MRZ scanner has finished.","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","isActive":true},{"text":".","type":"text"}]}],"kind":"content"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerViewController(cm)presentOn:configuration:completion:","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenConfiguration"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerUIResult","text":"SBSDKUI2MRZScannerUIResult"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"SBSDKUI2MRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerViewController"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"presentOn:configuration:completion:"}],"symbolKind":"method","title":"present(on:configuration:completion:)","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Type Method"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan MRZ (Machine-readable zones) of various documents.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerviewcontroller","title":"SBSDKUI2MRZScannerViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","navigatorTitle":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration","abstract":[{"type":"text","text":"Configuration of the screen for detecting MRZ (Machine-readable zones) of various documents."}],"type":"topic","title":"SBSDKUI2MRZScannerScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerViewController/present(on:configuration:completion:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","isActive":true},{"text":" and presents it modally.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenConfiguration"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerUIResult","kind":"typeIdentifier","text":"SBSDKUI2MRZScannerUIResult"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerViewController","text":"SBSDKUI2MRZScannerViewController"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController\/present(on:configuration:completion:)","navigatorTitle":[{"text":"presentOn:configuration:completion:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerviewcontroller\/present(on:configuration:completion:)","title":"present(on:configuration:completion:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerUIResult":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerUIResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerUIResult","abstract":[{"type":"text","text":"Configuration of the MRZ RTU UI result."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscanneruiresult","title":"SBSDKUI2MRZScannerUIResult","navigatorTitle":[{"text":"SBSDKUI2MRZScannerUIResult","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"presentOn:configuration:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"presentOn:configuration:completion:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerViewController","text":"SBSDKUI2MRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"presentOn:"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"presenter","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration","text":"SBSDKUI2MRZScannerScreenConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerUIResult","text":"SBSDKUI2MRZScannerUIResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerUIResult"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"presenter","content":[{"inlineContent":[{"text":"The view controller the new instance should be presented on.","type":"text"}],"type":"paragraph"}]},{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration object for the MRZ scanner screen."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The completion closure that is called when the MRZ scanner has finished.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}]}]}},{"op":"replace","value":"SBSDKUI2MRZScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2MRZScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/title","value":"SBSDKUI2MRZScannerScreenConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/fragments","value":[{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController~1present(on:configuration:completion:)\/title","value":"presentOn:configuration:completion:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerViewController~1present(on:configuration:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"presentOn:configuration:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerUIResult\/title","op":"replace","value":"SBSDKUI2MRZScannerUIResult"},{"value":[{"text":"SBSDKUI2MRZScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerUIResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerUIResult\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerUIResult"}],"op":"replace"}]}]}