{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/viewdidlayoutsubviews"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController\/viewDidLayoutSubviews"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"roleHeading":"Instance Method","title":"viewDidLayoutSubviews","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraViewController(im)viewDidLayoutSubviews","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController/viewDidLayoutSubviews":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"title":"viewDidLayoutSubviews","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/viewdidlayoutsubviews","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController\/viewDidLayoutSubviews","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"title":"SBSDKUIViewController","url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIViewController"}],"type":"topic","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","abstract":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","type":"reference","isActive":true},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"title":"SBSDKUICameraViewController","navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICameraViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","value":"SBSDKUIViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/title","value":"SBSDKUICameraViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}