{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"noDocumentFound","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"?cameraUserGuidanceNoDocumentFound\", "},{"text":"badAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"?cameraUserGuidanceBadAspectRatio\", "},{"kind":"externalParam","text":"badAngles"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" = \"?cameraUserGuidanceBadAngles\", "},{"kind":"externalParam","text":"textHintOffCenter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"?cameraUserGuidanceTextHintOffCenter\", ","kind":"text"},{"text":"tooSmall","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" = \"?cameraUserGuidanceTooSmall\", ","kind":"text"},{"text":"tooNoisy","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"?cameraUserGuidanceTooNoisy\", ","kind":"text"},{"text":"tooDark","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" = \"?cameraUserGuidanceTooDark\", ","kind":"text"},{"text":"energySaveMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" = \"?cameraUserGuidanceEnergySaveMode\", "},{"text":"readyToCapture","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"?cameraUserGuidanceReadyToCapture\", ","kind":"text"},{"text":"capturing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" = \"?cameraUserGuidanceReadyToCapture\", ","kind":"text"},{"text":"captureManual","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"?cameraUserGuidanceReadyToCaptureManual\")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceStates(im)initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","symbolKind":"init","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"noDocumentFound"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"badAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"badAngles"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"textHintOffCenter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tooSmall","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tooNoisy","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tooDark"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"energySaveMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"readyToCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"capturing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"captureManual"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","kind":"identifier"}],"roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/init(nodocumentfound:badaspectratio:badangles:texthintoffcenter:toosmall:toonoisy:toodark:energysavemode:readytocapture:capturing:capturemanual:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/init(nodocumentfound:badaspectratio:badangles:texthintoffcenter:toosmall:toonoisy:toodark:energysavemode:readytocapture:capturing:capturemanual:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates/init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)":{"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"noDocumentFound","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"badAspectRatio"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"badAngles"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textHintOffCenter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"tooSmall","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"tooNoisy","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"tooDark","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"energySaveMode"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"readyToCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"capturing"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"captureManual","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates\/init(nodocumentfound:badaspectratio:badangles:texthintoffcenter:toosmall:toonoisy:toodark:energysavemode:readytocapture:capturing:capturemanual:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates\/init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)","title":"init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)","role":"symbol","navigatorTitle":[{"text":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceStates":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidancestates","type":"topic","abstract":[{"text":"Configure the titles of the user guidance hints for different states.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceStates","title":"SBSDKUI2UserGuidanceStates"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"initWithNoDocumentFound:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"noDocumentFound"},{"text":" ","kind":"text"},{"text":"badAspectRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"badAspectRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"badAngles:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"badAngles"},{"text":" ","kind":"text"},{"text":"textHintOffCenter:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"textHintOffCenter","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooSmall:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"tooSmall","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tooNoisy:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tooNoisy"},{"kind":"text","text":" "},{"text":"tooDark:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"tooDark","kind":"internalParam"},{"kind":"text","text":" "},{"text":"energySaveMode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"energySaveMode"},{"text":" ","kind":"text"},{"text":"readyToCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"readyToCapture"},{"text":" ","kind":"text"},{"text":"capturing:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"capturing","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureManual:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"captureManual","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates~1init(noDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithNoDocumentFound:badAspectRatio:badAngles:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2UserGuidanceStates","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/fragments","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceStates\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}]}]}]}