{"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","roleHeading":"Instance Method","title":"initWithValue:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUserFieldDoubleValue(im)initWithValue:","navigatorTitle":[{"kind":"identifier","text":"initWithValue:"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfielddoublevalue\/initwithvalue:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldDoubleValue\/initWithValue:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldDoubleValue"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"value","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUserFieldDoubleValue":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfielddoublevalue","title":"SBSDKUserFieldDoubleValue","abstract":[{"type":"text","text":"Double value (TIFF_DOUBLE)."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldDoubleValue","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUserFieldDoubleValue"}],"navigatorTitle":[{"text":"SBSDKUserFieldDoubleValue","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUserFieldDoubleValue/initWithValue:":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuserfielddoublevalue\/initwithvalue:","kind":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"initWithValue:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"title":"initWithValue:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUserFieldDoubleValue\/initWithValue:","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUserFieldDoubleValue","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldDoubleValue\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldDoubleValue\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUserFieldDoubleValue"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUserFieldDoubleValue\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUserFieldDoubleValue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}