{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI\/defaultImageStoreEncrypter"},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)ScanbotUI(cpy)defaultImageStoreEncrypter","title":"defaultImageStoreEncrypter","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"defaultImageStoreEncrypter"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImageStoreEncrypter"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Type Property"},"variants":[{"paths":["\/documentation\/scanbotsdk\/scanbotui\/defaultimagestoreencrypter"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/scanbotui\/defaultimagestoreencrypter"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The SBSDKUI-component-wide encrypter for storing image data to disk. Defaults to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImageStoreEncrypter"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" no encryption is used at all."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can use the built-in encrypter "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter"},{"type":"text","text":" to encrypt your sensitive image data"},{"type":"text","text":" "},{"text":"using AES128 or AES256 before storing it to disk.","type":"text"},{"type":"text","text":" "},{"text":"When using encryption you still can access the unencrypted images in the image storage.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Of course, encrypted storages cannot be read without the proper encrypter being set here."},{"text":" ","type":"text"},{"type":"text","text":"You are responsible for migrating image storages."}],"type":"paragraph"},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you wish to use the ScanbotSDK RTU-UI-wide encryption setup your encrypter before using any of the ScanbotSDK RTU-UI API."}]}],"type":"aside","name":"Important"},{"inlineContent":[{"type":"text","text":"A good place to configure it, is your "},{"code":"AppDelegate","type":"codeVoice"},{"type":"text","text":"’s entry point, right where the license is set."},{"text":" ","type":"text"},{"text":"Once ScanbotSDK RTU-UI API is used the storages are created and any change to the default encrypter is of no effect.","type":"text"}],"type":"paragraph"},{"style":"note","content":[{"inlineContent":[{"type":"text","text":"For standard components, prefixed with SBSDK (without UI) the default encrypter has no effect, since there is"},{"text":" ","type":"text"},{"text":"no image storage by default. You can, of course, create instances of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage","type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","type":"reference","isActive":true},{"type":"text","text":" and initialize them with an encrypter of your choice."}],"type":"paragraph"}],"name":"Note","type":"aside"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStorageCrypting"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"role":"symbol","title":"SBSDKStorageCrypting"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKKeyedImageStorage":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKKeyedImageStorage","abstract":[{"text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class.","type":"text"},{"type":"text","text":" "},{"text":"Manages images in a dictionary-like fashion.","type":"text"}],"title":"SBSDKKeyedImageStorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"url":"\/documentation\/scanbotsdk\/sbsdkkeyedimagestorage","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKKeyedImageStorage"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAESEncrypter":{"title":"SBSDKAESEncrypter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKAESEncrypter","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkaesencrypter","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAESEncrypter","type":"topic","abstract":[{"text":"ScanbotSDK’s default data encrypter. Provides AES128 and AES 256 encryption to your data.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All data is encrypted and decrypted with the same key."},{"type":"text","text":" "},{"type":"text","text":"The context being passed to the encrypt\/decrypt methods is ignored."}],"navigatorTitle":[{"text":"SBSDKAESEncrypter","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotUI/defaultImageStoreEncrypter":{"kind":"symbol","abstract":[{"type":"text","text":"The SBSDKUI-component-wide encrypter for storing image data to disk. Defaults to "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/scanbotui\/defaultimagestoreencrypter","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultImageStoreEncrypter","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"defaultImageStoreEncrypter","kind":"identifier"}],"title":"defaultImageStoreEncrypter","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI\/defaultImageStoreEncrypter"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage":{"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"abstract":[{"text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}],"kind":"symbol","title":"SBSDKIndexedImageStorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/ScanbotUI":{"abstract":[{"text":"Helper class to configure the properties of the ScanbotSDK RTU-UI (SBSDKUI) components.","type":"text"}],"title":"ScanbotUI","url":"\/documentation\/scanbotsdk\/scanbotui","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/ScanbotUI","role":"symbol","navigatorTitle":[{"text":"ScanbotUI","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanbotUI"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"defaultImageStoreEncrypter","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultImageStoreEncrypter"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SBSDKStorageCrypting>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting"},{"text":" ","kind":"text"},{"text":"defaultImageStoreEncrypter","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKStorageCrypting","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/title","value":"SBSDKKeyedImageStorage","op":"replace"},{"value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKKeyedImageStorage\/navigatorTitle","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]},{"value":"SBSDKAESEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAESEncrypter"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/fragments"},{"op":"replace","value":[{"text":"SBSDKAESEncrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAESEncrypter\/navigatorTitle"},{"op":"replace","value":"defaultImageStoreEncrypter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI~1defaultImageStoreEncrypter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI~1defaultImageStoreEncrypter\/fragments","value":[{"kind":"identifier","text":"defaultImageStoreEncrypter"}],"op":"replace"},{"value":"SBSDKIndexedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/title"},{"op":"replace","value":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/navigatorTitle","op":"replace"},{"value":"ScanbotUI","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ScanbotUI"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI\/fragments"},{"value":[{"kind":"identifier","text":"ScanbotUI"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1ScanbotUI\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}