{"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKOCRElement(im)copyWithZone:","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRElement\/copyWithZone:"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkocrelement\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRElement"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRElement":{"kind":"symbol","type":"topic","title":"SBSDKOCRElement","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRElement","role":"symbol","abstract":[{"text":"Base class for units of text, e.g. glyphs, words, lines, blocks, pages.","type":"text"}],"navigatorTitle":[{"text":"SBSDKOCRElement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKOCRElement","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkocrelement"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCRElement/copyWithZone:":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCRElement\/copyWithZone:","title":"copyWithZone:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkocrelement\/copywithzone:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRElement\/title","value":"SBSDKOCRElement"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRElement\/fragments","value":[{"kind":"identifier","text":"SBSDKOCRElement"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCRElement\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKOCRElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}