{"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreviewImageURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentPage(py)documentPreviewImageURL","title":"documentPreviewImageURL","roleHeading":"Instance Property","navigatorTitle":[{"text":"documentPreviewImageURL","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"abstract":[{"text":"The ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" of the document image including applied rotations,","type":"text"},{"text":" ","type":"text"},{"text":"filter and polygon in a resolution matching the devices screen.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreviewImageURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Key-Value Observable.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageURL","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimageurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimageurl"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPage"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPage"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage","title":"SBSDKDocumentPage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage/documentPreviewImageURL":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage\/documentpreviewimageurl","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPreviewImageURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage\/documentPreviewImageURL","navigatorTitle":[{"text":"documentPreviewImageURL","kind":"identifier"}],"title":"documentPreviewImageURL","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"URL","type":"codeVoice"},{"text":" of the document image including applied rotations,","type":"text"},{"text":" ","type":"text"},{"text":"filter and polygon in a resolution matching the devices screen.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"documentPreviewImageURL","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentPreviewImageURL"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentPreviewImageURL"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title","value":"SBSDKDocumentPage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImageURL\/title","value":"documentPreviewImageURL","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage~1documentPreviewImageURL\/fragments","value":[{"kind":"identifier","text":"documentPreviewImageURL"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}