{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization\/accessibilitydescriptioncamerapermissionclosebutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization\/accessibilitydescriptioncamerapermissionclosebutton"]}],"metadata":{"title":"accessibilityDescriptionCameraPermissionCloseButton","roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2BarcodeTextLocalization(py)accessibilityDescriptionCameraPermissionCloseButton","symbolKind":"property"},"abstract":[{"text":"The accessibility hint for the ‘close’ button of the camera permission dialog.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"Default is “Close screen without granting permission”","type":"text"}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeTextLocalization":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"title":"SBSDKUI2BarcodeTextLocalization","navigatorTitle":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the all strings for barcode scanner."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BarcodeTextLocalization/accessibilityDescriptionCameraPermissionCloseButton":{"role":"symbol","navigatorTitle":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BarcodeTextLocalization\/accessibilityDescriptionCameraPermissionCloseButton","abstract":[{"type":"text","text":"The accessibility hint for the ‘close’ button of the camera permission dialog."}],"type":"topic","title":"accessibilityDescriptionCameraPermissionCloseButton","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2barcodetextlocalization\/accessibilitydescriptioncamerapermissionclosebutton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"accessibilityDescriptionCameraPermissionCloseButton","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2BarcodeTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2BarcodeTextLocalization"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/fragments"},{"value":[{"text":"SBSDKUI2BarcodeTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization\/navigatorTitle"},{"value":"accessibilityDescriptionCameraPermissionCloseButton","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/title"},{"value":[{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BarcodeTextLocalization~1accessibilityDescriptionCameraPermissionCloseButton\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}