{"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(image:ignoreOrientation:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(sampleBuffer:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(sampleBuffer:orientation:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/image","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/imageData"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"metadata":{"roleHeading":"Class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerFrame","role":"symbol","symbolKind":"class","title":"SBSDKBaseScannerFrame","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"identifier"}]},"abstract":[{"text":"A wrapper class for video frames.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame/init(image:ignoreOrientation:)":{"kind":"symbol","title":"init(image:ignoreOrientation:)","role":"symbol","abstract":[{"type":"text","text":"Initializes a frame from an image."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe\/init(image:ignoreorientation:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(image:ignoreOrientation:)","navigatorTitle":[{"text":"initWithImage:ignoreOrientation:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignoreOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame","type":"topic","title":"SBSDKBaseScannerFrame","role":"symbol","abstract":[{"type":"text","text":"A wrapper class for video frames."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe","navigatorTitle":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame/init(sampleBuffer:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(sampleBuffer:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":")","kind":"text"}],"title":"init(sampleBuffer:)","role":"symbol","navigatorTitle":[{"text":"initWithSampleBuffer:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initializes a frame from a sample buffer as it is typically aquired from the camera."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe\/init(samplebuffer:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame/imageData":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/imageData","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"imageData","role":"symbol","navigatorTitle":[{"text":"imageData","kind":"identifier"}],"abstract":[{"type":"text","text":"The JPEG-data representation of the receiver."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe\/imagedata"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame/image":{"type":"topic","navigatorTitle":[{"text":"image","kind":"identifier"}],"title":"image","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/image","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":"representation of the receiver."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe\/image","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerFrame/init(sampleBuffer:orientation:)":{"navigatorTitle":[{"text":"initWithSampleBuffer:orientation:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initializes a frame from a sample buffer as it is typically aquired from the camera and rotates it according to the given orientation."}],"type":"topic","title":"init(sampleBuffer:orientation:)","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerframe\/init(samplebuffer:orientation:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(sampleBuffer:orientation:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKBaseScannerFrame","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/image","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/imageData"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(image:ignoreOrientation:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(sampleBuffer:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerFrame\/init(sampleBuffer:orientation:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerFrame"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithImage:ignoreOrientation:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1init(image:ignoreOrientation:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1init(image:ignoreOrientation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImage:ignoreOrientation:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/title","value":"SBSDKBaseScannerFrame"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/fragments","value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1init(sampleBuffer:)\/title","value":"initWithSampleBuffer:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1init(sampleBuffer:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSampleBuffer:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1imageData\/title","value":"imageData"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1imageData\/fragments","value":[{"text":"imageData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1image\/title","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1image\/fragments","value":[{"text":"image","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1init(sampleBuffer:orientation:)\/title","value":"initWithSampleBuffer:orientation:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerFrame~1init(sampleBuffer:orientation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSampleBuffer:orientation:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}