{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The device did not register significant motion for this period."}]}]},{"content":[{"inlineContent":[{"text":"No positive scanner results have been registered during this period.","type":"text"},{"text":" ","type":"text"},{"text":"Once in energy save mode the device can only return to performance mode if it is moved significantly or a positive","type":"text"},{"text":" ","type":"text"},{"text":"detection\/scanning result was registered.","type":"text"}],"type":"paragraph"}]}],"type":"orderedList"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"metadata":{"title":"SBSDKBaseScannerEnergyConfiguration","roleHeading":"Class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]},"kind":"symbol","abstract":[{"type":"text","text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"type":"text","text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"type":"text","text":" "},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"type":"text","text":" "},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"text":"well as in energy saving mode.","type":"text"},{"text":" ","type":"text"},{"text":"In performance mode the scanners will be fed with a higher, configurable rate of","type":"text"},{"text":" ","type":"text"},{"text":"video frames per second.","type":"text"},{"text":" ","type":"text"},{"text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate","type":"text"},{"text":" ","type":"text"},{"text":"of scans will be reduced to a lower (configurable) rate.","type":"text"},{"text":" ","type":"text"},{"text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode.","type":"text"},{"text":" ","type":"text"},{"text":"Inactivity here means that both of the following conditions are met:","type":"text"}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/detectionRate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/inactivityTimeout","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/isEnergySavingEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/motionSensitivity"]},{"anchor":"Type-Properties","title":"Type Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/defaultConfiguration"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/energySaveDetectionRate":{"navigatorTitle":[{"kind":"identifier","text":"energySaveDetectionRate"}],"title":"energySaveDetectionRate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveDetectionRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/energysavedetectionrate","abstract":[{"type":"text","text":"The rate of detections\/recognitions per second in energy save mode."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 1, meaning that 1 frame per second is detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"When the video frame rate is 30, 29 frames will be skipped, 1 frame is detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,"},{"type":"text","text":" "},{"type":"text","text":"the actual detection rate is limited by the video frame rate."},{"type":"text","text":" "},{"type":"text","text":"Note: Usually you set a much lower value here as for the detectionRate property to save energy."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/init","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/isEnergySavingEnabled":{"abstract":[{"text":"Set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":", if automatic energy saving should be enabled. With automatic energy saving enabled the","type":"text"},{"text":" ","type":"text"},{"text":"base scanner view controller will, after a certain time of inactivity, enter the energy save mode by lowering the","type":"text"},{"text":" ","type":"text"},{"text":"detection\/scanning rate.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/isEnergySavingEnabled","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/isenergysavingenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEnergySavingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"isEnergySavingEnabled","navigatorTitle":[{"text":"isEnergySavingEnabled","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/motionSensitivity":{"navigatorTitle":[{"kind":"identifier","text":"motionSensitivity"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/motionsensitivity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"motionSensitivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"abstract":[{"text":"The sensitivity to device motion. The lower the value the less motion of the device is required to prevent the scanner from entering energy save mode.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to 4.0","type":"text"}],"title":"motionSensitivity","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/motionSensitivity"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/detectionRate":{"title":"detectionRate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/detectionRate","type":"topic","role":"symbol","navigatorTitle":[{"text":"detectionRate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/detectionrate","abstract":[{"type":"text","text":"The rate of detections\/recognitions per second in normal performance mode."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 20, meaning that 20 frames per second are detected\/recognized, equally distributed over one second."},{"type":"text","text":" "},{"type":"text","text":"When the video frame rate is 30, 10 frames will be skipped and 20 frames will be detected\/recognized."},{"type":"text","text":" "},{"type":"text","text":"Note: if you set the detection rate greater to or equal to the video frame rate, no frames will be skipped,"},{"type":"text","text":" "},{"type":"text","text":"the actual detection rate is limited by the video frame rate."}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"title":"SBSDKBaseScannerEnergyConfiguration","abstract":[{"type":"text","text":"The energy management configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses."},{"type":"text","text":" "},{"type":"text","text":"‘SBSDKBaseScannerViewController’ and subclasses sport a customizable energy management system."},{"type":"text","text":" "},{"type":"text","text":"Since scanners running on a live video feed can put a lot of load onto the CPU and\/or GPU"},{"type":"text","text":" "},{"type":"text","text":"of the device, causing the battery to drain quickly and running the device hot, you can customize the energy"},{"type":"text","text":" "},{"type":"text","text":"consumption using this class by configuring the rate of detections\/recognitions per second in performance mode as"},{"type":"text","text":" "},{"type":"text","text":"well as in energy saving mode."},{"text":" ","type":"text"},{"text":"In performance mode the scanners will be fed with a higher, configurable rate of","type":"text"},{"text":" ","type":"text"},{"text":"video frames per second.","type":"text"},{"text":" ","type":"text"},{"text":"After a certain, configurable period of inactivity the energy save mode will be engaged and the rate","type":"text"},{"text":" ","type":"text"},{"text":"of scans will be reduced to a lower (configurable) rate.","type":"text"},{"text":" ","type":"text"},{"text":"You can also configure the time of inactivity before the automatic mode switches from performance to energy save mode.","type":"text"},{"text":" ","type":"text"},{"text":"Inactivity here means that both of the following conditions are met:","type":"text"}],"navigatorTitle":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/inactivityTimeout":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"inactivityTimeout","kind":"identifier"}],"abstract":[{"type":"text","text":"The amount of time in seconds of no activity in performance mode before the energy save mode will be engaged."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 4 seconds."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/inactivityTimeout","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/inactivitytimeout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inactivityTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"inactivityTimeout"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerEnergyConfiguration/defaultConfiguration":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultConfiguration"}],"abstract":[{"text":"This is the default configuration with the properties initialized as mentioned in their description.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/defaultConfiguration","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerenergyconfiguration\/defaultconfiguration","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerEnergyConfiguration","text":"SBSDKBaseScannerEnergyConfiguration"}],"title":"defaultConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBaseScannerEnergyConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/detectionRate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/energySaveDetectionRate","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/inactivityTimeout","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/isEnergySavingEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/motionSensitivity"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/init"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerEnergyConfiguration\/defaultConfiguration"],"anchor":"Type-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerEnergyConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1energySaveDetectionRate\/title","value":"energySaveDetectionRate"},{"value":[{"kind":"identifier","text":"energySaveDetectionRate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1energySaveDetectionRate\/fragments","op":"replace"},{"value":"isEnergySavingEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1isEnergySavingEnabled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isEnergySavingEnabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1isEnergySavingEnabled\/fragments","op":"replace"},{"value":"motionSensitivity","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1motionSensitivity\/title","op":"replace"},{"value":[{"kind":"identifier","text":"motionSensitivity"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1motionSensitivity\/fragments","op":"replace"},{"value":"detectionRate","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1detectionRate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"detectionRate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1detectionRate\/fragments","op":"replace"},{"value":"SBSDKBaseScannerEnergyConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKBaseScannerEnergyConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration\/navigatorTitle","op":"replace"},{"value":"inactivityTimeout","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1inactivityTimeout\/title","op":"replace"},{"value":[{"kind":"identifier","text":"inactivityTimeout"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1inactivityTimeout\/fragments","op":"replace"},{"value":"defaultConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1defaultConfiguration\/title","op":"replace"},{"value":[{"text":"defaultConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerEnergyConfiguration~1defaultConfiguration\/fragments","op":"replace"}]}]}