{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKImageRefProfiler) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"ImageRefs are reference-counted. If references aren’t correctly released for whatever reason, the image memory will"},{"type":"text","text":" "},{"type":"text","text":"leak. Leaking memory over time may cause out-of-memory crashes and must be avoided. The profiler can return basic"},{"type":"text","text":" "},{"type":"text","text":"and detailed information about all currently alive ImageRefs, that can be useful to track leaking ImageRefs or to"},{"type":"text","text":" "},{"type":"text","text":"confirm that there are no leaks."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"topicSections":[{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/enableDetailedProfiling()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/makeSnapshot()"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}],"title":"SBSDKImageRefProfiler","role":"symbol","symbolKind":"class","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefProfiler","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Class"},"kind":"symbol","abstract":[{"type":"text","text":"ImageRef memory profiler."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfiler/makeSnapshot()":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"makeSnapshot","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/makeSnapshot()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"}],"title":"makeSnapshot()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler\/makesnapshot()","kind":"symbol","abstract":[{"type":"text","text":"Returns a snapshot of all alive ImageRefs. The snapshot contains a list of ImageRefs with information such as"},{"type":"text","text":" "},{"type":"text","text":"in-memory size. If detailed profiling is enabled (by calling enableDetailedProfiling beforehand), the profile"},{"type":"text","text":" "},{"type":"text","text":"will contain additional information such as the source from which each ImageRef has been created."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfiler/diff(firstSnapshot:secondSnapshot:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler\/diff(firstsnapshot:secondsnapshot:)","abstract":[{"type":"text","text":"Computes difference between two snapshots. To confirm that a particular operation doesn’t leak, take a snapshot"},{"type":"text","text":" "},{"type":"text","text":"before and after the operation, and check that the diff doesn’t contain any unexpected new ImageRefs."}],"title":"diff(firstSnapshot:secondSnapshot:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","role":"symbol","navigatorTitle":[{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diff","kind":"identifier"},{"text":"(","kind":"text"},{"text":"firstSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secondSnapshot","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshot","text":"SBSDKImageRefPoolSnapshot","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff","text":"SBSDKImageRefPoolSnapshotsDiff","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfiler/init":{"title":"init","kind":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler\/init","abstract":[]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfiler/enableDetailedProfiling()":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler\/enabledetailedprofiling()","title":"enableDetailedProfiling()","role":"symbol","abstract":[{"type":"text","text":"After the function is called, ImageRefs will store additional information, such as source from which they were"},{"type":"text","text":" "},{"type":"text","text":"created. This information may be important when trying to understand a profile. This function must be called"},{"type":"text","text":" "},{"type":"text","text":"BEFORE the first ImageRef is created, otherwise details may be lost."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/enableDetailedProfiling()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableDetailedProfiling","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"enableDetailedProfiling","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefProfiler":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageRefProfiler","role":"symbol","abstract":[{"type":"text","text":"ImageRef memory profiler."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefprofiler","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKImageRefProfiler","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/init"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/diff(firstSnapshot:secondSnapshot:)","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/enableDetailedProfiling()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefProfiler\/makeSnapshot()"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKImageRefProfiler"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"makeSnapshot","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler~1makeSnapshot()\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler~1makeSnapshot()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"makeSnapshot","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/title","value":"diffWithFirstSnapshot:secondSnapshot:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler~1diff(firstSnapshot:secondSnapshot:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"diffWithFirstSnapshot:secondSnapshot:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler~1enableDetailedProfiling()\/title","value":"enableDetailedProfiling"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler~1enableDetailedProfiling()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"enableDetailedProfiling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler\/title","value":"SBSDKImageRefProfiler"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRefProfiler"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefProfiler\/navigatorTitle","value":[{"text":"SBSDKImageRefProfiler","kind":"identifier"}]}]}]}