{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"symbolKind":"enum","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKLicenseStatus","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"roleHeading":"Enumeration","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"title":"SBSDKLicenseStatus"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus"},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/appIDMismatch","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/corrupted","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/expired","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/notSet","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/okay","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/trial","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/wrongOS"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"],"type":"conformsTo"}],"abstract":[{"text":"The status of the ScanbotSDK license.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/notSet":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/notSet","role":"symbol","title":"SBSDKLicenseStatus.notSet","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/notset","abstract":[{"text":"No license has been installed. The trial mode ended.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusNotSet"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSet"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/init(rawValue:)":{"abstract":[],"kind":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/init(rawValue:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/init(rawvalue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/RawRepresentable-Implementations","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/appIDMismatch":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/appIDMismatch","abstract":[{"text":"Invalid license. The license is not valid for this application.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"appIDMismatch","kind":"identifier"}],"kind":"symbol","title":"SBSDKLicenseStatus.appIDMismatch","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/appidmismatch","navigatorTitle":[{"text":"SBSDKLicenseStatusAppIDMismatch","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/okay":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/okay","type":"topic","kind":"symbol","title":"SBSDKLicenseStatus.okay","abstract":[{"type":"text","text":"The license is valid."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okay"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusOkay"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/okay"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/Equatable-Implementations","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/equatable-implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/expired":{"abstract":[{"type":"text","text":"Invalid license. The license has expired."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/expired","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/expired","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expired"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusExpired"}],"title":"SBSDKLicenseStatus.expired","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"title":"SBSDKLicenseStatus","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus","abstract":[{"text":"The status of the ScanbotSDK license.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/wrongOS":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusWrongOS"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/wrongOS","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongOS"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/wrongos","role":"symbol","type":"topic","title":"SBSDKLicenseStatus.wrongOS","abstract":[{"text":"Invalid license. The license is not valid for this operating system.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/trial":{"title":"SBSDKLicenseStatus.trial","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trial"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusTrial"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/trial","type":"topic","abstract":[{"type":"text","text":"No license has been installed. The trial mode is active."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/trial","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLicenseStatus/corrupted":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusCorrupted"}],"title":"SBSDKLicenseStatus.corrupted","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/corrupted","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklicensestatus\/corrupted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"corrupted"}],"abstract":[{"type":"text","text":"Invalid license. License contains corrupted data."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKLicenseStatus","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/appIDMismatch","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/corrupted","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/expired","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/notSet","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/okay","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/trial","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLicenseStatus\/wrongOS"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKLicenseStatusNotSet","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1notSet\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusNotSet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1notSet\/fragments","op":"replace"},{"value":"SBSDKLicenseStatusAppIDMismatch","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1appIDMismatch\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusAppIDMismatch"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1appIDMismatch\/fragments","op":"replace"},{"value":"SBSDKLicenseStatusOkay","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1okay\/title","op":"replace"},{"value":[{"text":"SBSDKLicenseStatusOkay","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1okay\/fragments","op":"replace"},{"value":"SBSDKLicenseStatusExpired","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1expired\/title","op":"replace"},{"value":[{"text":"SBSDKLicenseStatusExpired","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1expired\/fragments","op":"replace"},{"value":"SBSDKLicenseStatus","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/title","op":"replace"},{"value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus\/navigatorTitle","op":"replace"},{"value":"SBSDKLicenseStatusWrongOS","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1wrongOS\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusWrongOS"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1wrongOS\/fragments","op":"replace"},{"value":"SBSDKLicenseStatusTrial","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1trial\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusTrial"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1trial\/fragments","op":"replace"},{"value":"SBSDKLicenseStatusCorrupted","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1corrupted\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusCorrupted"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLicenseStatus~1corrupted\/fragments","op":"replace"}]}]}