{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores\/initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","kind":"identifier"}],"title":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionScores(im)initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTotalScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"totalScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"distanceScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"distanceScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"angleScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"angleScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sizeScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatioScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"aspectRatioScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineCoverageScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"lineCoverageScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"widthScore"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightScore:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"heightScore"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionscores\/initwithtotalscore:distancescore:anglescore:sizescore:aspectratioscore:linecoveragescore:widthscore:heightscore:"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionScores/initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores\/initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionscores\/initwithtotalscore:distancescore:anglescore:sizescore:aspectratioscore:linecoveragescore:widthscore:heightscore:","navigatorTitle":[{"kind":"identifier","text":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:"}],"title":"initWithTotalScore:distanceScore:angleScore:sizeScore:aspectRatioScore:lineCoverageScore:widthScore:heightScore:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionScores":{"title":"SBSDKDocumentDetectionScores","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionscores","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"abstract":[{"type":"text","text":"The total and partial scores for the detected document contour."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionScores"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKDocumentDetectionScores","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/title"},{"value":[{"text":"SBSDKDocumentDetectionScores","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionScores"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionScores\/navigatorTitle"}]}]}