{"metadata":{"symbolKind":"property","title":"checkDigitDocumentNumber","navigatorTitle":[{"text":"checkDigitDocumentNumber","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigitDocumentNumber"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMRZ(py)checkDigitDocumentNumber","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz\/checkdigitdocumentnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz\/checkdigitdocumentnumber"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkDigitDocumentNumber","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Check digit document number"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ\/checkDigitDocumentNumber"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMRZ/checkDigitDocumentNumber":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ\/checkDigitDocumentNumber","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz\/checkdigitdocumentnumber","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigitDocumentNumber"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"type":"topic","title":"checkDigitDocumentNumber","navigatorTitle":[{"kind":"identifier","text":"checkDigitDocumentNumber"}],"abstract":[{"type":"text","text":"Check digit document number"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelMRZ":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelmrz","title":"SBSDKDocumentsModelMRZ","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelMRZ","kind":"symbol","abstract":[{"text":"MRZ part of the document","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelMRZ"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentField":{"title":"SBSDKGenericDocumentField","abstract":[{"text":"Generic document field.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfield","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"checkDigitDocumentNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"checkDigitDocumentNumber","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKGenericDocumentField","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"checkDigitDocumentNumber"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ~1checkDigitDocumentNumber\/title","value":"checkDigitDocumentNumber","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ~1checkDigitDocumentNumber\/fragments","value":[{"text":"checkDigitDocumentNumber","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKDocumentsModelMRZ","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/fragments","value":[{"text":"SBSDKDocumentsModelMRZ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelMRZ\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentsModelMRZ"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/title","op":"replace","value":"SBSDKGenericDocumentField"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentField"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentField\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentField","kind":"identifier"}]}]}]}