{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback"]]},"sections":[],"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback(cm)fromJsonWithJson:","title":"fromJsonWithJson:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback\/fromJsonWithJson:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback","text":"SBSDKUI2CaptureFeedback","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CaptureFeedback"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2capturefeedback\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CaptureFeedback":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback","title":"SBSDKUI2CaptureFeedback","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"abstract":[{"text":"Configuration of the feedback shown after snapping a page.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2capturefeedback"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CaptureFeedback/fromJsonWithJson:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CaptureFeedback\/fromJsonWithJson:","title":"fromJsonWithJson:","kind":"symbol","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2capturefeedback\/fromjsonwithjson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2CaptureFeedback","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CaptureFeedback","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CaptureFeedback"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CaptureFeedback\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}