{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/refreshoneachframe"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/refreshoneachframe"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKSimulatedCameraMockData(py)refreshOnEachFrame","title":"refreshOnEachFrame","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"refreshOnEachFrame","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshOnEachFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSimulatedCameraMockData":{"url":"\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata","abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData","role":"symbol","title":"SBSDKSimulatedCameraMockData"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKSimulatedCameraMockData/refreshOnEachFrame":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"refreshOnEachFrame","kind":"identifier"}],"abstract":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshOnEachFrame","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","title":"refreshOnEachFrame","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKSimulatedCameraMockData\/refreshOnEachFrame","url":"\/documentation\/scanbotsdk\/sbsdksimulatedcameramockdata\/refreshoneachframe"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"refreshOnEachFrame","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"refreshOnEachFrame","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshOnEachFrame"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKSimulatedCameraMockData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/title"},{"value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/fragments"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle"},{"value":"refreshOnEachFrame","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData~1refreshOnEachFrame\/title"},{"value":[{"text":"refreshOnEachFrame","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKSimulatedCameraMockData~1refreshOnEachFrame\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}