{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddisplaystate\/initwithvalue:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState\/initWithValue:"},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"title":"initWithValue:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentFieldDisplayState(im)initWithValue:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayStateValue","text":"SBSDKGenericDocumentFieldDisplayStateValue","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKGenericDocumentFieldDisplayStateValue"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDisplayStateValue":{"abstract":[],"fragments":[{"text":"SBSDKGenericDocumentFieldDisplayStateValue","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayStateValue","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddisplaystatevalue","role":"symbol","type":"topic","title":"SBSDKGenericDocumentFieldDisplayStateValue"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDisplayState/initWithValue:":{"navigatorTitle":[{"kind":"identifier","text":"initWithValue:"}],"title":"initWithValue:","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddisplaystate\/initwithvalue:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState\/initWithValue:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentFieldDisplayState":{"title":"SBSDKGenericDocumentFieldDisplayState","abstract":[{"text":"The generic document fields display status. Whether a field is shown or hidden in the user interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentFieldDisplayState","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentfielddisplaystate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/title","op":"replace","value":"SBSDKGenericDocumentFieldDisplayState"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentFieldDisplayState\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocumentFieldDisplayState","kind":"identifier"}]}]}]}