{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithDocumentDetectionMode:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCheckDocumentDetectionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCheckDocumentDetectionMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"documentDetectionMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerConfiguration(im)initWithDocumentDetectionMode:","fragments":[{"kind":"text","text":"- "},{"text":"initWithDocumentDetectionMode:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocumentDetectionMode:"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"initWithDocumentDetectionMode:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/initwithdocumentdetectionmode:"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/initWithDocumentDetectionMode:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration/initWithDocumentDetectionMode:":{"kind":"symbol","title":"initWithDocumentDetectionMode:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration\/initWithDocumentDetectionMode:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDocumentDetectionMode:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocumentDetectionMode:"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration\/initwithdocumentdetectionmode:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerConfiguration":{"abstract":[{"text":"Configuration of the check scanner.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}],"type":"topic","navigatorTitle":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"title":"SBSDKCheckScannerConfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckDocumentDetectionMode":{"type":"topic","navigatorTitle":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckdocumentdetectionmode","abstract":[{"type":"text","text":"Check document detection and extraction mode."}],"title":"SBSDKCheckDocumentDetectionMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckDocumentDetectionMode","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/title","value":"SBSDKCheckScannerConfiguration"},{"value":[{"text":"SBSDKCheckScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCheckScannerConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/title","value":"SBSDKCheckDocumentDetectionMode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKCheckDocumentDetectionMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckDocumentDetectionMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckDocumentDetectionMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}