{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"_NSZone","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/copywithzone:"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/copyWithZone:"},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFConfiguration(im)copyWithZone:","symbolKind":"method","title":"copyWithZone:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration","abstract":[{"type":"text","text":"The parameters "},{"type":"codeVoice","code":"pageSize"},{"type":"text","text":", "},{"type":"codeVoice","code":"pageFit"},{"text":", ","type":"text"},{"type":"codeVoice","code":"dpi"},{"type":"text","text":" and "},{"code":"resamplingMethod","type":"codeVoice"},{"text":" interact in a complex way","type":"text"},{"type":"text","text":" "},{"text":"when adding bitmap images (JPEG, PNG, or raw) to the PDF.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"There are three cases to consider:"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration","kind":"symbol","title":"SBSDKPDFConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFConfiguration/copyWithZone:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfconfiguration\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFConfiguration\/copyWithZone:","role":"symbol","kind":"symbol","abstract":[],"title":"copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKPDFConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKPDFConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFConfiguration\/navigatorTitle","value":[{"text":"SBSDKPDFConfiguration","kind":"identifier"}],"op":"replace"}]}]}