{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration\/minNumberOfRequiredFramesWithEqualRecognitionResult","interfaceLanguage":"swift"},"abstract":[{"text":"The minimum equal results in accumulated video frames to count as valid.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration"]]},"kind":"symbol","sections":[],"metadata":{"title":"minNumberOfRequiredFramesWithEqualRecognitionResult","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration(py)minNumberOfRequiredFramesWithEqualRecognitionResult","navigatorTitle":[{"text":"minNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/minnumberofrequiredframeswithequalrecognitionresult"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/minnumberofrequiredframeswithequalrecognitionresult"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerBehaviorConfiguration/minNumberOfRequiredFramesWithEqualRecognitionResult":{"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/minnumberofrequiredframeswithequalrecognitionresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration\/minNumberOfRequiredFramesWithEqualRecognitionResult","abstract":[{"type":"text","text":"The minimum equal results in accumulated video frames to count as valid."}],"role":"symbol","kind":"symbol","title":"minNumberOfRequiredFramesWithEqualRecognitionResult","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"navigatorTitle":[{"text":"minNumberOfRequiredFramesWithEqualRecognitionResult","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerBehaviorConfiguration":{"abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI license plate scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUILicensePlateScannerBehaviorConfiguration"}],"title":"SBSDKUILicensePlateScannerBehaviorConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerBehaviorConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"minNumberOfRequiredFramesWithEqualRecognitionResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"minNumberOfRequiredFramesWithEqualRecognitionResult"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minNumberOfRequiredFramesWithEqualRecognitionResult"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"minNumberOfRequiredFramesWithEqualRecognitionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration~1minNumberOfRequiredFramesWithEqualRecognitionResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"minNumberOfRequiredFramesWithEqualRecognitionResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration~1minNumberOfRequiredFramesWithEqualRecognitionResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/title","op":"replace","value":"SBSDKUILicensePlateScannerBehaviorConfiguration"},{"value":[{"text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}