{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration\/scanStrategy","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The strategy being used to find a license plate in an image."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanStrategy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy","text":"SBSDKLicensePlateScannerStrategy","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy","kind":"typeIdentifier"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/scanstrategy"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/scanstrategy"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanStrategy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKLicensePlateScannerStrategy","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration(py)scanStrategy","navigatorTitle":[{"kind":"identifier","text":"scanStrategy"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"title":"scanStrategy"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerBehaviorConfiguration":{"abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI license plate scanner."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUILicensePlateScannerBehaviorConfiguration"}],"title":"SBSDKUILicensePlateScannerBehaviorConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerBehaviorConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerBehaviorConfiguration/scanStrategy":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanStrategy"},{"kind":"text","text":": "},{"text":"SBSDKLicensePlateScannerStrategy","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration\/scanStrategy","abstract":[{"type":"text","text":"The strategy being used to find a license plate in an image."}],"title":"scanStrategy","role":"symbol","navigatorTitle":[{"text":"scanStrategy","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/scanstrategy"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicensePlateScannerStrategy":{"abstract":[{"type":"text","text":"The strategy being used to scan a license plate. *\/"}],"type":"topic","title":"SBSDKLicensePlateScannerStrategy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicensePlateScannerStrategy"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicensePlateScannerStrategy"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicenseplatescannerstrategy"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"scanStrategy","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"scanStrategy","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicensePlateScannerStrategy","text":"SBSDKLicensePlateScannerStrategy","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKLicensePlateScannerStrategy"},{"kind":"text","text":" "},{"text":"scanStrategy","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/title","value":"SBSDKUILicensePlateScannerBehaviorConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration~1scanStrategy\/title","value":"scanStrategy"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration~1scanStrategy\/fragments","value":[{"text":"scanStrategy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/title","value":"SBSDKLicensePlateScannerStrategy"},{"value":[{"text":"SBSDKLicensePlateScannerStrategy","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicensePlateScannerStrategy\/fragments","op":"replace"}]}]}