{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/playBleepSound()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/playbleepsound()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/playbleepsound()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"playBleepSound()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"playBleepSound"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playBleepSound","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerViewController(im)playBleepSound"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playBleepSound"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Plays standard bleep sound.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController/playBleepSound()":{"type":"topic","title":"playBleepSound()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController\/playBleepSound()","abstract":[{"text":"Plays standard bleep sound.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playBleepSound","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller\/playbleepsound()","navigatorTitle":[{"kind":"identifier","text":"playBleepSound"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"abstract":[{"type":"text","text":"A highly customizable camera view controller that delivers a basic camera functionality along with video"},{"type":"text","text":" "},{"text":"frame extraction and preprocessing, orientation correction and still image capturing.","type":"text"}],"role":"symbol","title":"SBSDKBaseScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerViewController","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbasescannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"playBleepSound"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playBleepSound","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"playBleepSound"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"playBleepSound","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController~1playBleepSound()\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playBleepSound","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController~1playBleepSound()\/fragments"},{"value":"SBSDKBaseScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/title"},{"value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}]}]}]}