{"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"verticalLines","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verticalLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt","text":"SBSDKLineSegmentInt"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"verticalLines"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionResult(py)verticalLines"},"abstract":[{"text":"All detected vertical lines in image space.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/verticalLines"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verticalLines","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKLineSegmentInt","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentInt","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt"},{"text":"]","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/verticallines"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/verticallines"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult/verticalLines":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult\/verticalLines","kind":"symbol","type":"topic","abstract":[{"text":"All detected vertical lines in image space.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"verticalLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLineSegmentInt","text":"SBSDKLineSegmentInt"},{"kind":"text","text":"]"}],"title":"verticalLines","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult\/verticallines","navigatorTitle":[{"kind":"identifier","text":"verticalLines"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLineSegmentInt":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklinesegmentint","title":"SBSDKLineSegmentInt","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLineSegmentInt","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLineSegmentInt"}],"abstract":[{"type":"text","text":"Represents a line segment in 2D space."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLineSegmentInt"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionResult":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionResult","role":"symbol","kind":"symbol","title":"SBSDKDocumentDetectionResult","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"abstract":[{"text":"Result of the document contour detection.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"verticalLines","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"verticalLines","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKLineSegmentInt *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"verticalLines","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"verticalLines","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult~1verticalLines\/title"},{"op":"replace","value":[{"kind":"identifier","text":"verticalLines"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult~1verticalLines\/fragments"},{"op":"replace","value":"SBSDKLineSegmentInt","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegmentInt"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLineSegmentInt"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLineSegmentInt\/navigatorTitle"},{"op":"replace","value":"SBSDKDocumentDetectionResult","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/title"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDetectionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}