{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2receiptsintroimage\/init"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReceiptsIntroImage"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReceiptsIntroImage\/init","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReceiptsIntroImage(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","title":"init","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReceiptsIntroImage/init":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReceiptsIntroImage\/init","url":"\/documentation\/scanbotsdk\/sbsdkui2receiptsintroimage\/init","type":"topic","abstract":[],"title":"init","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReceiptsIntroImage":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReceiptsIntroImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReceiptsIntroImage","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2ReceiptsIntroImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The image for the introduction screen with a receipt template."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2receiptsintroimage","title":"SBSDKUI2ReceiptsIntroImage"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReceiptsIntroImage\/title","op":"replace","value":"SBSDKUI2ReceiptsIntroImage"},{"value":[{"text":"SBSDKUI2ReceiptsIntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReceiptsIntroImage\/fragments"},{"value":[{"text":"SBSDKUI2ReceiptsIntroImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReceiptsIntroImage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}