{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TopBarConfiguration(im)init","role":"symbol","title":"init()","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration\/init()"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration\/init()","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarConfiguration/init()":{"type":"topic","title":"init()","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration\/init()","url":"\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TopBarConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TopBarConfiguration","kind":"symbol","title":"SBSDKUI2TopBarConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2topbarconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the top bar’s appearance."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/title","value":"SBSDKUI2TopBarConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TopBarConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}