{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter"]]},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCustomBinarizationFilter(py)hash","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","title":"hash"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter\/hash","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcustombinarizationfilter\/hash"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCustomBinarizationFilter":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter","title":"SBSDKCustomBinarizationFilter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcustombinarizationfilter","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCustomBinarizationFilter/hash":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter\/hash","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcustombinarizationfilter\/hash","type":"topic","kind":"symbol","title":"hash","fragments":[{"kind":"identifier","text":"hash"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter\/title","value":"SBSDKCustomBinarizationFilter","op":"replace"},{"value":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter\/fragments","op":"replace"},{"value":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter\/navigatorTitle","op":"replace"}]}]}