{"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithPreset:outputMode:denoise:radius:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(preset:outputMode:denoise:radius:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBinarizationFilterPreset","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarizationFilterPreset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"outputMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode","text":"SBSDKOutputMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"denoise","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCustomBinarizationFilter(im)initWithPreset:outputMode:denoise:radius:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"init"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"preset","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset","kind":"typeIdentifier","text":"SBSDKBinarizationFilterPreset","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarizationFilterPreset"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"outputMode"},{"text":": ","kind":"text"},{"text":"SBSDKOutputMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode"},{"text":", ","kind":"text"},{"text":"denoise","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcustombinarizationfilter\/init(preset:outputmode:denoise:radius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkcustombinarizationfilter\/init(preset:outputmode:denoise:radius:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter\/init(preset:outputMode:denoise:radius:)"},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKOutputMode":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKOutputMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOutputMode"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkoutputmode","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode","title":"SBSDKOutputMode","type":"topic","abstract":[{"text":"Output mode of binarization filter.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCustomBinarizationFilter":{"title":"SBSDKCustomBinarizationFilter","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcustombinarizationfilter","type":"topic","abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCustomBinarizationFilter/init(preset:outputMode:denoise:radius:)":{"role":"symbol","navigatorTitle":[{"text":"initWithPreset:outputMode:denoise:radius:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcustombinarizationfilter\/init(preset:outputmode:denoise:radius:)","title":"init(preset:outputMode:denoise:radius:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"preset"},{"kind":"text","text":": "},{"text":"SBSDKBinarizationFilterPreset","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarizationFilterPreset"},{"text":", ","kind":"text"},{"text":"outputMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKOutputMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"denoise","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter\/init(preset:outputMode:denoise:radius:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBinarizationFilterPreset":{"abstract":[{"text":"Preset of parameters for custom binarization filter.","type":"text"}],"kind":"symbol","title":"SBSDKBinarizationFilterPreset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbinarizationfilterpreset","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBinarizationFilterPreset"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 5.0.0"}],"title":"ScanbotDocumentScannerSDK","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithPreset:outputMode:denoise:radius:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPreset:outputMode:denoise:radius:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPreset:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBinarizationFilterPreset","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKBinarizationFilterPreset","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBinarizationFilterPreset"},{"text":") ","kind":"text"},{"text":"preset","kind":"internalParam"},{"kind":"text","text":" "},{"text":"outputMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKOutputMode","text":"SBSDKOutputMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKOutputMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"outputMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"denoise:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"denoise"},{"text":" ","kind":"text"},{"text":"radius:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"radius"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode\/title","value":"SBSDKOutputMode"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKOutputMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKOutputMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter\/title","value":"SBSDKCustomBinarizationFilter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter~1init(preset:outputMode:denoise:radius:)\/title","op":"replace","value":"initWithPreset:outputMode:denoise:radius:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithPreset:outputMode:denoise:radius:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter~1init(preset:outputMode:denoise:radius:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/title","value":"SBSDKBinarizationFilterPreset","op":"replace"},{"value":[{"text":"SBSDKBinarizationFilterPreset","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBinarizationFilterPreset\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}