{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance\/visibility"},"kind":"symbol","metadata":{"title":"visibility","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"visibility","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2UserGuidanceVisibility","text":"SBSDKUI2UserGuidanceVisibility"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerUserGuidance(py)visibility","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"visibility"}],"symbolKind":"property","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"abstract":[{"type":"text","text":"Determines when the user guidance hints should be visible."},{"type":"text","text":" "},{"type":"text","text":"Default is ENABLED"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visibility"},{"kind":"text","text":": "},{"text":"SBSDKUI2UserGuidanceVisibility","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2UserGuidanceVisibility","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance\/visibility"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance\/visibility"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance"]]},"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerUserGuidance/visibility":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance\/visibility","role":"symbol","type":"topic","title":"visibility","abstract":[{"text":"Determines when the user guidance hints should be visible.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is ENABLED"}],"navigatorTitle":[{"text":"visibility","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance\/visibility","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibility"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2UserGuidanceVisibility","text":"SBSDKUI2UserGuidanceVisibility","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceVisibility":{"navigatorTitle":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancevisibility","type":"topic","title":"SBSDKUI2UserGuidanceVisibility","abstract":[{"type":"text","text":"Determines the visibility mode for the document capturing user guidance labels."}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerUserGuidance":{"title":"SBSDKUI2DocumentScannerUserGuidance","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscanneruserguidance","role":"symbol","abstract":[{"text":"Configuration of the hints guiding users through the scanning process.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerUserGuidance","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"visibility","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"visibility","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceVisibility","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2UserGuidanceVisibility","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceVisibility"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibility"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance~1visibility\/title","value":"visibility"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance~1visibility\/fragments","value":[{"text":"visibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/title","value":"SBSDKUI2UserGuidanceVisibility"},{"op":"replace","value":[{"text":"SBSDKUI2UserGuidanceVisibility","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceVisibility"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceVisibility\/navigatorTitle"},{"value":"SBSDKUI2DocumentScannerUserGuidance","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerUserGuidance"}]},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerUserGuidance","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerUserGuidance\/navigatorTitle"}]}]}