{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/formats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/formats"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormat","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration\/formats"},"sections":[],"abstract":[{"text":"List of four-state barcode formats to scan.","type":"text"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formats","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"SBSDKBarcodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat"},{"text":">","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonFourStateConfiguration(py)formats","role":"symbol","navigatorTitle":[{"text":"formats","kind":"identifier"}],"title":"formats","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration/formats":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/formats","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"formats"}],"title":"formats","abstract":[{"text":"List of four-state barcode formats to scan.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat"},{"kind":"text","text":">"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration\/formats"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormat":{"title":"SBSDKBarcodeFormat","abstract":[{"type":"text","text":"Enumerates barcode formats."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformat","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration":{"kind":"symbol","type":"topic","title":"SBSDKBarcodeFormatCommonFourStateConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}],"abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple four-state barcode formats with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple four-state codes."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"formats","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"formats"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<SBSDKBarcodeFormat *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"formats","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration~1formats\/title","value":"formats"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration~1formats\/fragments","value":[{"text":"formats","kind":"identifier"}]},{"value":"SBSDKBarcodeFormat","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/title"},{"value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/fragments"},{"value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/navigatorTitle"},{"value":"SBSDKBarcodeFormatCommonFourStateConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}]}]}]}