{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonFourStateConfiguration"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"title":"fromJsonWithJson:","role":"symbol","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonFourStateConfiguration(cm)fromJsonWithJson:","roleHeading":"Type Method","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration\/fromJsonWithJson:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration":{"kind":"symbol","type":"topic","title":"SBSDKBarcodeFormatCommonFourStateConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}],"abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple four-state barcode formats with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple four-state codes."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration/fromJsonWithJson:":{"abstract":[],"kind":"symbol","type":"topic","title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/fromjsonwithjson:","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration\/fromJsonWithJson:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatCommonFourStateConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}