{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton\/initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2roundbutton\/initwithvisible:accessibilitydescription:backgroundcolor:foregroundcolor:activebackgroundcolor:activeforegroundcolor:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithVisible:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"visible"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescription:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"accessibilityDescription","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"backgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"foregroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Color","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"foregroundColor"},{"text":" ","kind":"text"},{"text":"activeBackgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"activeBackgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activeForegroundColor:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"activeForegroundColor","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton"]]},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:"}],"role":"symbol","title":"initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2RoundButton(im)initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2RoundButton/initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2roundbutton\/initwithvisible:accessibilitydescription:backgroundcolor:foregroundcolor:activebackgroundcolor:activeforegroundcolor:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton\/initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:"}],"title":"initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:","navigatorTitle":[{"kind":"identifier","text":"initWithVisible:accessibilityDescription:backgroundColor:foregroundColor:activeBackgroundColor:activeForegroundColor:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","title":"SBSDKUI2Color","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2RoundButton":{"role":"symbol","type":"topic","title":"SBSDKUI2RoundButton","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2roundbutton","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2RoundButton","navigatorTitle":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"abstract":[{"text":"Configuration of the round button.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2RoundButton","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2RoundButton","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2RoundButton\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2RoundButton\/fragments","op":"replace","value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2RoundButton\/navigatorTitle","value":[{"text":"SBSDKUI2RoundButton","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}