{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGenerator\/init(parameters:useEncryptionIfAvailable:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgenerator\/init(parameters:useencryptionifavailable:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgenerator\/init(parameters:useencryptionifavailable:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters","text":"SBSDKTIFFGeneratorParameters","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"useEncryptionIfAvailable","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}]},{"parameters":[{"name":"parameters","content":[{"inlineContent":[{"text":"The parameters to be used when generating TIFF images.","type":"text"}],"type":"paragraph"}]},{"name":"useEncryptionIfAvailable","content":[{"inlineContent":[{"text":"If ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" and a crypting provider is set in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/defaultCryptingProvider","type":"reference"},{"text":", the generated TIFF images will be encrypted.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithParameters:useEncryptionIfAvailable:error:"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGenerator(im)initWithParameters:useEncryptionIfAvailable:error:","title":"init(parameters:useEncryptionIfAvailable:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters"},{"text":", ","kind":"text"},{"text":"useEncryptionIfAvailable","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Initializer","symbolKind":"init"},"abstract":[{"type":"text","text":"Initializes a new TIFF image generator with the specified parameters and encrypter."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGenerator"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGenerator/init(parameters:useEncryptionIfAvailable:)":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGenerator\/init(parameters:useEncryptionIfAvailable:)","navigatorTitle":[{"kind":"identifier","text":"initWithParameters:useEncryptionIfAvailable:error:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgenerator\/init(parameters:useencryptionifavailable:)","role":"symbol","title":"init(parameters:useEncryptionIfAvailable:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters","text":"SBSDKTIFFGeneratorParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useEncryptionIfAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Initializes a new TIFF image generator with the specified parameters and encrypter."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGenerator":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgenerator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGenerator","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"abstract":[{"type":"text","text":"A class that converts images to (multipage) TIFF images."},{"type":"text","text":" "},{"type":"text","text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/defaultCryptingProvider","isActive":true},{"type":"text","text":" is set, the generated TIFF files will be encrypted using the specified crypting provider."}],"title":"SBSDKTIFFGenerator"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/Scanbot/defaultCryptingProvider":{"abstract":[{"type":"text","text":"The SDK-wide encryption provider for storing image data to disk. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption used."}],"kind":"symbol","navigatorTitle":[{"text":"defaultCryptingProvider","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/scanbot\/defaultcryptingprovider","title":"defaultCryptingProvider","type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/defaultCryptingProvider","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultCryptingProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFGeneratorParameters":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"TIFF generator parameters."}],"title":"SBSDKTIFFGeneratorParameters","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffgeneratorparameters","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithParameters:useEncryptionIfAvailable:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParameters:useEncryptionIfAvailable:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFGeneratorParameters","text":"SBSDKTIFFGeneratorParameters","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKTIFFGeneratorParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":" "},{"kind":"identifier","text":"useEncryptionIfAvailable:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"useEncryptionIfAvailable"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"parameters","content":[{"inlineContent":[{"text":"The parameters to be used when generating TIFF images.","type":"text"}],"type":"paragraph"}]},{"name":"useEncryptionIfAvailable","content":[{"inlineContent":[{"text":"If ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" and a crypting provider is set in ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/Scanbot\/defaultCryptingProvider","isActive":true,"type":"reference"},{"text":", the generated TIFF images will be encrypted.","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGenerator~1init(parameters:useEncryptionIfAvailable:)\/title","op":"replace","value":"initWithParameters:useEncryptionIfAvailable:error:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGenerator~1init(parameters:useEncryptionIfAvailable:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithParameters:useEncryptionIfAvailable:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGenerator\/title","op":"replace","value":"SBSDKTIFFGenerator"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGenerator\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGenerator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1defaultCryptingProvider\/title","op":"replace","value":"defaultCryptingProvider"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1Scanbot~1defaultCryptingProvider\/fragments","op":"replace","value":[{"text":"defaultCryptingProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/title","op":"replace","value":"SBSDKTIFFGeneratorParameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle","op":"replace","value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}