{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"kind":"text","text":" *) "},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"]]},"metadata":{"title":"copyWithZone:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKIndexedImageStorage(im)copyWithZone:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/copyWithZone:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/copyWithZone:":{"title":"copyWithZone:","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/copywithzone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class."},{"type":"text","text":" "},{"text":"Manages images in an array-like fashion.","type":"text"}],"navigatorTitle":[{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"title":"SBSDKIndexedImageStorage","url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKIndexedImageStorage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}