{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/moveimage(from:to:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/moveimage(from:to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)"},"abstract":[{"type":"text","text":"Moves the image at the source index to the destination index."}],"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moveImage"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"moveImage(from:to:)","navigatorTitle":[{"kind":"identifier","text":"moveImageFromIndex:toIndex:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKIndexedImageStorage(im)moveImageFromIndex:toIndex:","symbolKind":"method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(moveImageFromIndex:toIndex:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"moveImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceIndex"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":" ","kind":"text"},{"text":"destinationIndex","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]},{"parameters":[{"name":"sourceIndex","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The valid current index of the image to be moved."}]}]},{"name":"destinationIndex","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The valid new index of the image to be moved."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"code":"True","type":"codeVoice"},{"text":", if the operation was successfull, ","type":"text"},{"code":"False","type":"codeVoice"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKIndexedImageStorage","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A simple thread-safe multiple-reader-single-writer index based disk image cache class."},{"text":" ","type":"text"},{"text":"Manages images in an array-like fashion.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage","navigatorTitle":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage","title":"SBSDKIndexedImageStorage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKIndexedImageStorage/moveImage(from:to:)":{"role":"symbol","title":"moveImage(from:to:)","abstract":[{"type":"text","text":"Moves the image at the source index to the destination index."}],"url":"\/documentation\/scanbotsdk\/sbsdkindexedimagestorage\/moveimage(from:to:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKIndexedImageStorage\/moveImage(from:to:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"moveImageFromIndex:toIndex:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"moveImageFromIndex:toIndex:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"moveImageFromIndex:toIndex:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"moveImageFromIndex:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"sourceIndex","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"destinationIndex","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/title","value":"SBSDKIndexedImageStorage"},{"value":[{"kind":"identifier","text":"SBSDKIndexedImageStorage"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage\/fragments","op":"replace"},{"value":"moveImageFromIndex:toIndex:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1moveImage(from:to:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKIndexedImageStorage~1moveImage(from:to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveImageFromIndex:toIndex:"}]}]}]}