{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkstructuredappendinfo\/initwithcount:index:id:"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo\/initWithCount:index:id:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCount:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"count","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"index:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"index"},{"kind":"text","text":" "},{"kind":"identifier","text":"id:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"id"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"initWithCount:index:id:","kind":"identifier"}],"title":"initWithCount:index:id:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCount:index:id:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKStructuredAppendInfo(im)initWithCount:index:id:","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStructuredAppendInfo/initWithCount:index:id:":{"kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo\/initWithCount:index:id:","title":"initWithCount:index:id:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCount:index:id:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCount:index:id:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstructuredappendinfo\/initwithcount:index:id:"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStructuredAppendInfo":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStructuredAppendInfo","abstract":[{"type":"text","text":"The structured append mode can be used to split a message across multiple barcodes."}],"kind":"symbol","title":"SBSDKStructuredAppendInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstructuredappendinfo","navigatorTitle":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKStructuredAppendInfo","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}