{"abstract":[{"text":"The text being displayed on the user-guidance label, when a document was scanned, but the documents area is too small compared to the image area.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintTooSmall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintTooSmall"},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerStatusTextConfiguration(py)textHintTooSmall","title":"textHintTooSmall","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintTooSmall","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"textHintTooSmall","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthinttoosmall"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthinttoosmall"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerStatusTextConfiguration/textHintTooSmall":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintTooSmall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintTooSmall","navigatorTitle":[{"kind":"identifier","text":"textHintTooSmall"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when a document was scanned, but the documents area is too small compared to the image area."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration\/texthinttoosmall","title":"textHintTooSmall"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerStatusTextConfiguration":{"title":"SBSDKDocumentScannerStatusTextConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerStatusTextConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerstatustextconfiguration","type":"topic","abstract":[{"text":"Wraps the texts being displayed as the detection status.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"textHintTooSmall","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"textHintTooSmall","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"textHintTooSmall","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"textHintTooSmall","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintTooSmall\/title"},{"value":[{"text":"textHintTooSmall","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintTooSmall\/fragments"},{"value":"SBSDKDocumentScannerStatusTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/title"},{"value":[{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerStatusTextConfiguration\/navigatorTitle"}]}]}