{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancestates\/capturing"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancestates\/capturing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates\/capturing"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"The user guidance text displayed when the document is being captured and user needs to hold the device still.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is “?cameraUserGuidanceReadyToCapture”"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capturing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceStates(py)capturing","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"capturing","kind":"identifier"}],"title":"capturing","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"capturing"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","url":"\/documentation\/scanbotdocumentscannersdk","abstract":[{"type":"text","text":"Version: 6.2.0"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceStates":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"abstract":[{"type":"text","text":"Configure the titles of the user guidance hints for different states."}],"title":"SBSDKUI2UserGuidanceStates","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancestates","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceStates/capturing":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"capturing","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates\/capturing","title":"capturing","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"capturing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"The user guidance text displayed when the document is being captured and user needs to hold the device still."},{"type":"text","text":" "},{"text":"Default is “?cameraUserGuidanceReadyToCapture”","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancestates\/capturing"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"capturing","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"capturing","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"capturing","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2UserGuidanceStates","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/fragments","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates~1capturing\/title","value":"capturing","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates~1capturing\/fragments","value":[{"text":"capturing","kind":"identifier"}]}]}]}