{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/bottomBar","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"bottomBar"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementScreenConfiguration(py)bottomBar","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomBar","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar"}],"title":"bottomBar","symbolKind":"property","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomBar","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","text":"SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration"]]},"abstract":[{"type":"text","text":"Configuration of the bottom bar for the acknowledgement screen."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration\/bottombar"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration\/bottombar"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementScreenConfiguration/bottomBar":{"navigatorTitle":[{"kind":"identifier","text":"bottomBar"}],"abstract":[{"text":"Configuration of the bottom bar for the acknowledgement screen.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration\/bottombar","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomBar"},{"text":": ","kind":"text"},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar"}],"title":"bottomBar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration\/bottomBar","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementBottomBar":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","navigatorTitle":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}],"title":"SBSDKUI2AcknowledgementBottomBar","abstract":[{"type":"text","text":"Configuration of the bottom bar for the acknowledgement screen."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementbottombar","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2AcknowledgementScreenConfiguration":{"navigatorTitle":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementScreenConfiguration","title":"SBSDKUI2AcknowledgementScreenConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the acknowledgement screen.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2acknowledgementscreenconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"bottomBar","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"bottomBar","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"SBSDKUI2AcknowledgementBottomBar","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2AcknowledgementBottomBar","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2AcknowledgementBottomBar","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"bottomBar","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration~1bottomBar\/title","value":"bottomBar"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration~1bottomBar\/fragments","op":"replace","value":[{"text":"bottomBar","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/title","value":"SBSDKUI2AcknowledgementBottomBar"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/fragments","value":[{"text":"SBSDKUI2AcknowledgementBottomBar","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2AcknowledgementBottomBar"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementBottomBar\/navigatorTitle"},{"value":"SBSDKUI2AcknowledgementScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUI2AcknowledgementScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2AcknowledgementScreenConfiguration\/navigatorTitle","op":"replace"}]}]}