{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration"]]},"abstract":[{"type":"text","text":"Defines if the top and bottom buttons are swapped."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTopAndBottomButtonsSwapped","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Defaults to "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration\/isTopAndBottomButtonsSwapped"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration\/istopandbottombuttonsswapped"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration\/istopandbottombuttonsswapped"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SBSDKUI2CroppingViewController instead."}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"isTopAndBottomButtonsSwapped","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"platforms":[],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTopAndBottomButtonsSwapped","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","title":"isTopAndBottomButtonsSwapped","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICroppingScreenUIConfiguration(py)isTopAndBottomButtonsSwapped","symbolKind":"property"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenUIConfiguration":{"role":"symbol","deprecated":true,"abstract":[{"text":"Configuration for user interface of the page cropping screen.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"title":"SBSDKUICroppingScreenUIConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICroppingScreenUIConfiguration/isTopAndBottomButtonsSwapped":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICroppingScreenUIConfiguration\/isTopAndBottomButtonsSwapped","title":"isTopAndBottomButtonsSwapped","abstract":[{"text":"Defines if the top and bottom buttons are swapped.","type":"text"}],"deprecated":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTopAndBottomButtonsSwapped","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuicroppingscreenuiconfiguration\/istopandbottombuttonsswapped","navigatorTitle":[{"text":"isTopAndBottomButtonsSwapped","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isTopAndBottomButtonsSwapped","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"isTopAndBottomButtonsSwapped"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isTopAndBottomButtonsSwapped","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUICroppingScreenUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUICroppingScreenUIConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration\/fragments","op":"replace"},{"value":[{"text":"SBSDKUICroppingScreenUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration\/navigatorTitle","op":"replace"},{"value":"isTopAndBottomButtonsSwapped","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration~1isTopAndBottomButtonsSwapped\/title","op":"replace"},{"value":[{"text":"isTopAndBottomButtonsSwapped","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICroppingScreenUIConfiguration~1isTopAndBottomButtonsSwapped\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}