{"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"sections":[],"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/auto","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/live","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/singleShot"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKProcessingMode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProcessingMode"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKProcessingMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingMode","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"role":"symbol","title":"SBSDKProcessingMode","symbolKind":"enum"},"abstract":[{"type":"text","text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it."},{"type":"text","text":" "},{"type":"text","text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results."},{"type":"text","text":" "},{"type":"text","text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode/init(rawValue:)":{"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(rawValue:)","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode/live":{"title":"SBSDKProcessingMode.live","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/live","abstract":[{"type":"text","text":"In live mode input images are expected to come from a video source like a camera."},{"type":"text","text":" "},{"type":"text","text":"Scanners in live mode typically spend little time on each image and are able to quickly analyze multiple images and combine the individual image results into a final result."},{"type":"text","text":" "},{"type":"text","text":"Individual results from a particular image may be less accurate than running the scanner in single-shot mode on that frame, but after aggregating a few images of the same subject, the final result becomes much more accurate."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingModeLive"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/live","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"live"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/RawRepresentable-Implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se"},"doc://net.doo.ScanbotBarcodeScannerSDK/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode/auto":{"title":"SBSDKProcessingMode.auto","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/auto","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/auto","abstract":[{"text":"The scanner chooses live or single-shot mode based on the source of the image. An image constructed with RawImageLoadOptions.liveSource equal to true will be processed in live mode, otherwise it will be processed in single-shot mode.","type":"text"},{"text":" ","type":"text"},{"text":"On Android liveSource is automatically set to true if the ImageRef is created from Nv21 image data.","type":"text"},{"text":" ","type":"text"},{"text":"On iOS liveSource is automatically set to true if the ImageRef is created from a CMSampleBuffer.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKProcessingModeAuto","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/Equatable-Implementations","kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/equatable-implementations","title":"Equatable Implementations","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode/singleShot":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKProcessingModeSingleShot"}],"kind":"symbol","title":"SBSDKProcessingMode.singleShot","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode\/singleshot","abstract":[{"text":"In single-shot the scanner tries to extract the maximum amount of information possible from each input image. The scanner typically spends much longer on analyzing the image to ensure that all available information has been extracted.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/singleShot","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"singleShot"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKProcessingMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode","role":"symbol","title":"SBSDKProcessingMode","kind":"symbol","abstract":[{"type":"text","text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it."},{"type":"text","text":" "},{"type":"text","text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results."},{"type":"text","text":" "},{"type":"text","text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkprocessingmode","navigatorTitle":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKProcessingMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/auto","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/live","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKProcessingMode\/singleShot"],"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode~1live\/title","value":"SBSDKProcessingModeLive"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode~1live\/fragments","value":[{"text":"SBSDKProcessingModeLive","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode~1auto\/title","value":"SBSDKProcessingModeAuto"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode~1auto\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingModeAuto"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode~1singleShot\/title","value":"SBSDKProcessingModeSingleShot"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode~1singleShot\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingModeSingleShot"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/title","value":"SBSDKProcessingMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/fragments","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKProcessingMode\/navigatorTitle","value":[{"text":"SBSDKProcessingMode","kind":"identifier"}]}]}]}