{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"title":"SBSDKUI2MultipleBarcodesScanningMode","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2MultipleBarcodesScanningMode","roleHeading":"Enumeration","symbolKind":"enum","role":"symbol"},"abstract":[{"type":"text","text":"Configuration of the mode used for scanning multiple barcodes."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/counting","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/unique"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY"],"title":"Conforms To"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKUI2MultipleBarcodesScanningMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode\/equatable-implementations","type":"topic","abstract":[]},"doc://net.doo.ScanbotBarcodeScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode","title":"SBSDKUI2MultipleBarcodesScanningMode","type":"topic","role":"symbol","abstract":[{"text":"Configuration of the mode used for scanning multiple barcodes.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode/unique":{"type":"topic","kind":"symbol","title":"SBSDKUI2MultipleBarcodesScanningMode.unique","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/unique","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode\/unique","navigatorTitle":[{"text":"SBSDKUI2MultipleBarcodesScanningModeUnique","kind":"identifier"}],"abstract":[{"type":"text","text":"Only scan barcodes with unique values. Subsequent barcodes with the same values will be ignored."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unique"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotBarcodeScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotBarcodeScannerSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotBarcodeScannerSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/s12CaseIterableP","type":"unresolvable","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode/init(rawValue:)":{"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/init(rawValue:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode\/init(rawvalue:)","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode/counting":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode\/counting","title":"SBSDKUI2MultipleBarcodesScanningMode.counting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"counting"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/counting","abstract":[{"type":"text","text":"Scan barcodes even if they have the same value and count the number of repeated barcodes."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningModeCounting"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2MultipleBarcodesScanningMode/RawRepresentable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/RawRepresentable-Implementations","abstract":[],"type":"topic","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2multiplebarcodesscanningmode\/rawrepresentable-implementations"},"doc://net.doo.ScanbotBarcodeScannerSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MultipleBarcodesScanningMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/counting","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2MultipleBarcodesScanningMode\/unique"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKUI2MultipleBarcodesScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/fragments"},{"value":[{"text":"SBSDKUI2MultipleBarcodesScanningMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode\/navigatorTitle"},{"value":"SBSDKUI2MultipleBarcodesScanningModeUnique","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode~1unique\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningModeUnique"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode~1unique\/fragments"},{"value":"SBSDKUI2MultipleBarcodesScanningModeCounting","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode~1counting\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MultipleBarcodesScanningModeCounting"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2MultipleBarcodesScanningMode~1counting\/fragments"}]}]}