{"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/toJson(configuration:)"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/brightnessFilter()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/colorDocumentFilter()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/contrastFilter()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/customBinarizationFilter()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/grayscaleFilter()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/legacyFilter()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/scanbotBinarizationFilter()","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/whiteBlackPointFilter()"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBrightnessFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKContrastFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLegacyFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKWhiteBlackPointFilter"],"type":"inheritedBy"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKParametricFilter) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter","symbolKind":"class","title":"SBSDKParametricFilter"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Base class for all parametric filters."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/customBinarizationFilter()":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/customBinarizationFilter()","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/custombinarizationfilter()","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customBinarizationFilter"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKCustomBinarizationFilter","kind":"typeIdentifier","text":"SBSDKCustomBinarizationFilter"}],"title":"customBinarizationFilter()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/hash":{"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/hash","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/hash","title":"hash"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/fromJsonWithJson:":{"fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/fromjsonwithjson:","navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/fromJsonWithJson:","abstract":[],"role":"symbol","title":"fromJsonWithJson:","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKColorDocumentFilter":{"title":"SBSDKColorDocumentFilter","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcolordocumentfilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter","abstract":[{"type":"text","text":"Color document filter. This filter is a good starting point for most use cases."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKContrastFilter":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcontrastfilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContrastFilter","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKContrastFilter","kind":"identifier"}],"abstract":[{"text":"Contrast adjustment filter.","type":"text"}],"title":"SBSDKContrastFilter","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKContrastFilter","role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/legacyFilter()":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacyFilter"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKLegacyFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKLegacyFilter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/legacyFilter()","kind":"symbol","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/legacyfilter()","title":"legacyFilter()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/isEqual:":{"abstract":[],"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/isEqual:","kind":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/isequal:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/brightnessFilter()":{"title":"brightnessFilter()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/brightnessFilter()","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/brightnessfilter()","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessFilter"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBrightnessFilter","text":"SBSDKBrightnessFilter"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKGrayscaleFilter":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter","abstract":[{"text":"Converts color images to grayscale and applies autocontrast.","type":"text"}],"navigatorTitle":[{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"role":"symbol","title":"SBSDKGrayscaleFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGrayscaleFilter","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkgrayscalefilter","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/colorDocumentFilter()":{"title":"colorDocumentFilter()","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/colordocumentfilter()","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/colorDocumentFilter()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorDocumentFilter","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKColorDocumentFilter","text":"SBSDKColorDocumentFilter","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKCustomBinarizationFilter":{"kind":"symbol","abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkcustombinarizationfilter","navigatorTitle":[{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCustomBinarizationFilter","kind":"identifier"}],"title":"SBSDKCustomBinarizationFilter","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKLegacyFilter":{"navigatorTitle":[{"text":"SBSDKLegacyFilter","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLegacyFilter","kind":"identifier"}],"title":"SBSDKLegacyFilter","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdklegacyfilter","type":"topic","abstract":[{"type":"text","text":"Deprecated image filters."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLegacyFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/contrastFilter()":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contrastFilter","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKContrastFilter","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKContrastFilter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/contrastFilter()","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/contrastfilter()","title":"contrastFilter()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/grayscaleFilter()":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/grayscalefilter()","type":"topic","role":"symbol","title":"grayscaleFilter()","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/grayscaleFilter()","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"grayscaleFilter"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKGrayscaleFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKGrayscaleFilter"}]},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/toJson(configuration:)":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/tojson(configuration:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/toJson(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}],"type":"topic","title":"toJson(configuration:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKWhiteBlackPointFilter":{"title":"SBSDKWhiteBlackPointFilter","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKWhiteBlackPointFilter","role":"symbol","abstract":[{"type":"text","text":"Maps image value channel so that all the pixels darker than the black point are set to 0,"},{"type":"text","text":" "},{"type":"text","text":"all the pixels brighter than the white point are set to 255, and the pixels in between"},{"type":"text","text":" "},{"type":"text","text":"are linearly scaled."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkwhiteblackpointfilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/whiteBlackPointFilter()":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/whiteblackpointfilter()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"whiteBlackPointFilter","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKWhiteBlackPointFilter","text":"SBSDKWhiteBlackPointFilter","kind":"typeIdentifier"}],"type":"topic","title":"whiteBlackPointFilter()","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/whiteBlackPointFilter()","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotDocumentScannerSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBrightnessFilter":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbrightnessfilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBrightnessFilter"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBrightnessFilter","kind":"identifier"}],"type":"topic","title":"SBSDKBrightnessFilter","abstract":[{"type":"text","text":"Brightness adjustment filter."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBrightnessFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/copyWithZone:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/copywithzone:","role":"symbol","abstract":[],"title":"copyWithZone:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/copyWithZone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/scanbotBinarizationFilter()":{"title":"scanbotBinarizationFilter()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanbotBinarizationFilter"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKScanbotBinarizationFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKScanbotBinarizationFilter"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/scanbotBinarizationFilter()","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/scanbotbinarizationfilter()","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"role":"symbol","kind":"symbol","abstract":[{"text":"Base class for all parametric filters.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKParametricFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","title":"SBSDKParametricFilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKScanbotBinarizationFilter":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter","title":"SBSDKScanbotBinarizationFilter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkscanbotbinarizationfilter","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Automatic binarization filter. This filter is a good starting point for most use cases."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKParametricFilter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/hash"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/copyWithZone:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/isEqual:","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/toJson(configuration:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/fromJsonWithJson:"],"anchor":"Type-Methods","title":"Type Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBrightnessFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKColorDocumentFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKContrastFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKCustomBinarizationFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKGrayscaleFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKLegacyFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKScanbotBinarizationFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKWhiteBlackPointFilter"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSCopying"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/title","op":"replace","value":"SBSDKColorDocumentFilter"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/fragments","value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKColorDocumentFilter\/navigatorTitle","value":[{"text":"SBSDKColorDocumentFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKContrastFilter\/title","value":"SBSDKContrastFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKContrastFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKContrastFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKContrastFilter\/navigatorTitle","value":[{"text":"SBSDKContrastFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/title","value":"SBSDKGrayscaleFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKGrayscaleFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGrayscaleFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter\/title","value":"SBSDKCustomBinarizationFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKCustomBinarizationFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCustomBinarizationFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLegacyFilter\/title","value":"SBSDKLegacyFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLegacyFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKLegacyFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKLegacyFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKLegacyFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter~1toJson(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKWhiteBlackPointFilter\/title","value":"SBSDKWhiteBlackPointFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKWhiteBlackPointFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKWhiteBlackPointFilter\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKWhiteBlackPointFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBrightnessFilter\/title","value":"SBSDKBrightnessFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBrightnessFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKBrightnessFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBrightnessFilter\/navigatorTitle","value":[{"text":"SBSDKBrightnessFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/navigatorTitle","value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/title","value":"SBSDKScanbotBinarizationFilter","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKScanbotBinarizationFilter"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKScanbotBinarizationFilter\/navigatorTitle","value":[{"text":"SBSDKScanbotBinarizationFilter","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}