{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"},"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIFinderDocumentScannerBehaviorConfiguration","role":"symbol","roleHeading":"Class","symbolKind":"class","title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"platforms":[]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration"]}],"kind":"symbol","sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedAngleScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedBrightnessThreshold","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedSizeScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/autoSnappingDelay","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/autoSnappingSensitivity","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/cameraPreviewMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultPageFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/engineMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/forceUserGuidance","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/ignoreOrientationMismatch","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/imageScale","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isAutoSnappingEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isFlashEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/lockDocumentAspectRatioToFinder","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/photoQualityPrioritization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/stopsCameraSessionWhenDisappeared"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Configuration for the behavior of the document scanning screen."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use SBSDKUI2DocumentScannerViewController instead."}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/autoSnappingSensitivity":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingSensitivity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoSnappingSensitivity"}],"deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/autosnappingsensitivity","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/autoSnappingSensitivity","kind":"symbol","title":"autoSnappingSensitivity","abstract":[{"type":"text","text":"The sensitivity of auto-snapping."}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/acceptedSizeScore":{"abstract":[{"type":"text","text":"The minimum size in percent (0 - 100) of the screen size to accept a scanned document."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedSizeScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedsizescore","title":"acceptedSizeScore","navigatorTitle":[{"kind":"identifier","text":"acceptedSizeScore"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedSizeScore","deprecated":true,"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/acceptedBrightnessThreshold":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedbrightnessthreshold","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"The brightness threshold to accept a scanned document in the range of 0 (very dark) to 255 (very bright)."},{"type":"text","text":" "},{"type":"text","text":"If  the average brightness value of the scanners input image is below this value, the status of the detection will be set to"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/errorTooDark"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedBrightnessThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"acceptedBrightnessThreshold","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptedBrightnessThreshold"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedBrightnessThreshold"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/autoSnappingDelay":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoSnappingDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/autoSnappingDelay","deprecated":true,"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/autosnappingdelay","abstract":[{"text":"The minimum delay in seconds between two consecutive automatic image captures.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"autoSnappingDelay"}],"title":"autoSnappingDelay"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/ignoreOrientationMismatch":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/ignoreOrientationMismatch","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/ignoreorientationmismatch","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreOrientationMismatch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"deprecated":true,"title":"ignoreOrientationMismatch","kind":"symbol","abstract":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", ignores the orientation mismatch warning.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ignoreOrientationMismatch"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration","deprecated":true,"type":"topic","abstract":[{"text":"Configuration for the behavior of the document scanning screen.","type":"text"}],"role":"symbol","title":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/defaultParametricPageFilter":{"title":"defaultParametricPageFilter","navigatorTitle":[{"kind":"identifier","text":"defaultParametricPageFilter"}],"kind":"symbol","role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter","abstract":[{"text":"The default parametric filters for new documents pages.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultparametricpagefilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultParametricPageFilter"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBSDKParametricFilter","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter"},{"kind":"text","text":"]?"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/isFlashEnabled":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/isflashenabled","role":"symbol","abstract":[{"text":"Whether flash is toggled on or off.","type":"text"}],"type":"topic","title":"isFlashEnabled","navigatorTitle":[{"kind":"identifier","text":"isFlashEnabled"}],"kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFlashEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isFlashEnabled"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/defaultPageFilter":{"abstract":[{"text":"The default image filter type for new documents pages.","type":"text"}],"kind":"symbol","title":"defaultPageFilter","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultPageFilter"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultPageFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageFilterType","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFilterType"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultPageFilter","deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/defaultpagefilter"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/documentImageSizeLimit":{"title":"documentImageSizeLimit","deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/documentimagesizelimit","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentImageSizeLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/documentImageSizeLimit","navigatorTitle":[{"kind":"identifier","text":"documentImageSizeLimit"}],"abstract":[{"text":"Limits the maximum size of the document image. If width or height are zero, this property is effectively ignored.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/cameraPreviewMode":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/cameraPreviewMode","title":"cameraPreviewMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/camerapreviewmode","navigatorTitle":[{"kind":"identifier","text":"cameraPreviewMode"}],"deprecated":true,"abstract":[{"text":"The video layers content mode.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKVideoContentMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoContentMode"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionStatus/errorTooDark":{"title":"SBSDKDocumentDetectionStatus.errorTooDark","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorTooDark"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionstatus\/errortoodark","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionStatus\/errorTooDark","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectionStatusErrorTooDark"}],"type":"topic","abstract":[{"text":"No document was detected, likely because the input image is too dark.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/acceptedAngleScore":{"role":"symbol","type":"topic","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"acceptedAngleScore"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedAngleScore","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/acceptedanglescore","abstract":[{"text":"The minimum score in percent (0 - 100) of the perspective distortion to accept a scanned document.","type":"text"}],"title":"acceptedAngleScore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedAngleScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/photoQualityPrioritization":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoQualityPrioritization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKCapturePhotoQualityPrioritization"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/photoqualityprioritization","title":"photoQualityPrioritization","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/photoQualityPrioritization","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"photoQualityPrioritization"}],"deprecated":true,"abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/lockDocumentAspectRatioToFinder":{"kind":"symbol","abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", allows only scanning of documents with the aspect ratio that the finder has set.","type":"text"}],"type":"topic","title":"lockDocumentAspectRatioToFinder","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/lockdocumentaspectratiotofinder","deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lockDocumentAspectRatioToFinder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"lockDocumentAspectRatioToFinder"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/lockDocumentAspectRatioToFinder"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/stopsCameraSessionWhenDisappeared":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/stopscamerasessionwhendisappeared","title":"stopsCameraSessionWhenDisappeared","kind":"symbol","role":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", the default, the camera session will be stopped entirely, when the receiver disappears and restarts when the receiver reappears.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/stopsCameraSessionWhenDisappeared","navigatorTitle":[{"kind":"identifier","text":"stopsCameraSessionWhenDisappeared"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/isAutoSnappingEnabled":{"type":"topic","abstract":[{"text":"Whether auto-snapping is enabled or not.","type":"text"}],"title":"isAutoSnappingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutoSnappingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isAutoSnappingEnabled"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/isautosnappingenabled","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isAutoSnappingEnabled","role":"symbol","deprecated":true},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/engineMode":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"engineMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentScannerEngineMode","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentScannerEngineMode"}],"title":"engineMode","deprecated":true,"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/enginemode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"engineMode"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/engineMode","abstract":[{"text":"The mode of the document scanner to be used for document outline detection.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/forceUserGuidance":{"navigatorTitle":[{"kind":"identifier","text":"forceUserGuidance"}],"title":"forceUserGuidance","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/forceUserGuidance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceUserGuidance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"deprecated":true,"type":"topic","abstract":[{"text":"Whether user guidance is enabled while auto-snapping is disabled.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/forceuserguidance","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/imageScale":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageScale"}],"abstract":[{"type":"text","text":"The scaling factor for captured images. Values are clamped to the range 0.0 - 1.0."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/imagescale","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageScale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"type":"topic","title":"imageScale","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/imageScale"},"doc://net.doo.ScanbotDocumentScannerSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIFinderDocumentScannerBehaviorConfiguration/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/init","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuifinderdocumentscannerbehaviorconfiguration\/init","abstract":[],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedAngleScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedBrightnessThreshold","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/acceptedSizeScore","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/autoSnappingDelay","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/autoSnappingSensitivity","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/cameraPreviewMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultPageFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/defaultParametricPageFilter","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/documentImageSizeLimit","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/engineMode","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/forceUserGuidance","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/ignoreOrientationMismatch","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/imageScale","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isAutoSnappingEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/isFlashEnabled","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/lockDocumentAspectRatioToFinder","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/photoQualityPrioritization","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/stopsCameraSessionWhenDisappeared"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIFinderDocumentScannerBehaviorConfiguration\/init"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1autoSnappingSensitivity\/title","value":"autoSnappingSensitivity"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1autoSnappingSensitivity\/fragments","value":[{"text":"autoSnappingSensitivity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedSizeScore\/title","value":"acceptedSizeScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedSizeScore\/fragments","value":[{"kind":"identifier","text":"acceptedSizeScore"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedBrightnessThreshold\/title","value":"acceptedBrightnessThreshold"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedBrightnessThreshold\/fragments","value":[{"kind":"identifier","text":"acceptedBrightnessThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1autoSnappingDelay\/title","value":"autoSnappingDelay"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1autoSnappingDelay\/fragments","value":[{"text":"autoSnappingDelay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1ignoreOrientationMismatch\/title","value":"ignoreOrientationMismatch"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1ignoreOrientationMismatch\/fragments","value":[{"kind":"identifier","text":"ignoreOrientationMismatch"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/title","value":"SBSDKUIFinderDocumentScannerBehaviorConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIFinderDocumentScannerBehaviorConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultParametricPageFilter\/title","value":"defaultParametricPageFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultParametricPageFilter\/fragments","value":[{"kind":"identifier","text":"defaultParametricPageFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1isFlashEnabled\/title","value":"isFlashEnabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1isFlashEnabled\/fragments","value":[{"text":"isFlashEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultPageFilter\/title","value":"defaultPageFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1defaultPageFilter\/fragments","value":[{"kind":"identifier","text":"defaultPageFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1documentImageSizeLimit\/title","value":"documentImageSizeLimit"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1documentImageSizeLimit\/fragments","value":[{"kind":"identifier","text":"documentImageSizeLimit"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1cameraPreviewMode\/title","value":"cameraPreviewMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1cameraPreviewMode\/fragments","value":[{"text":"cameraPreviewMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1errorTooDark\/title","value":"SBSDKDocumentDetectionStatusErrorTooDark"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionStatus~1errorTooDark\/fragments","value":[{"text":"SBSDKDocumentDetectionStatusErrorTooDark","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedAngleScore\/title","value":"acceptedAngleScore"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1acceptedAngleScore\/fragments","value":[{"text":"acceptedAngleScore","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1photoQualityPrioritization\/title","value":"photoQualityPrioritization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1photoQualityPrioritization\/fragments","value":[{"kind":"identifier","text":"photoQualityPrioritization"}],"op":"replace"},{"op":"replace","value":"lockDocumentAspectRatioToFinder","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1lockDocumentAspectRatioToFinder\/title"},{"op":"replace","value":[{"text":"lockDocumentAspectRatioToFinder","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1lockDocumentAspectRatioToFinder\/fragments"},{"op":"replace","value":"stopsCameraSessionWhenDisappeared","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1stopsCameraSessionWhenDisappeared\/title"},{"op":"replace","value":[{"text":"stopsCameraSessionWhenDisappeared","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1stopsCameraSessionWhenDisappeared\/fragments"},{"op":"replace","value":"isAutoSnappingEnabled","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1isAutoSnappingEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isAutoSnappingEnabled"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1isAutoSnappingEnabled\/fragments"},{"op":"replace","value":"engineMode","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1engineMode\/title"},{"op":"replace","value":[{"text":"engineMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1engineMode\/fragments"},{"op":"replace","value":"forceUserGuidance","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1forceUserGuidance\/title"},{"op":"replace","value":[{"kind":"identifier","text":"forceUserGuidance"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1forceUserGuidance\/fragments"},{"op":"replace","value":"imageScale","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1imageScale\/title"},{"op":"replace","value":[{"text":"imageScale","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIFinderDocumentScannerBehaviorConfiguration~1imageScale\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}