{"sections":[],"abstract":[{"type":"text","text":"Enumeration of image type classifiers."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/document","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/documentUnfiltered","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/original"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/Equatable-Implementations","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType"},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentPageFileType","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"SBSDKDocumentPageFileType","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKDocumentPageFileType","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SY"},"doc://net.doo.ScanbotDocumentScannerSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SH"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType/documentUnfiltered":{"abstract":[{"text":"The image only contains the cropped and perspective-corrected document portion of the original camera image.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentUnfiltered","kind":"identifier"}],"kind":"symbol","title":"SBSDKDocumentPageFileType.documentUnfiltered","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/documentUnfiltered","navigatorTitle":[{"text":"SBSDKDocumentPageFileTypeDocumentUnfiltered","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/documentunfiltered"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType/RawRepresentable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType/init(rawValue:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/init(rawValue:)","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"title":"init(rawValue:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType","title":"SBSDKDocumentPageFileType","navigatorTitle":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"abstract":[{"text":"Enumeration of image type classifiers.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType/document":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/document","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentPageFileTypeDocument"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/document","kind":"symbol","role":"symbol","abstract":[{"text":"The image contains the cropped, perspective-corrected and filtered document portion of the original camera image.","type":"text"}],"title":"SBSDKDocumentPageFileType.document","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType/original":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/original","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/original","navigatorTitle":[{"text":"SBSDKDocumentPageFileTypeOriginal","kind":"identifier"}],"abstract":[{"type":"text","text":"The image is the uncropped full image that was captured from the camera."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"original","kind":"identifier"}],"title":"SBSDKDocumentPageFileType.original"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentPageFileType/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentpagefiletype\/equatable-implementations","kind":"article"},"doc://net.doo.ScanbotDocumentScannerSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentPageFileType","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/document","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/documentUnfiltered","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentPageFileType\/original"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentPageFileType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentPageFileTypeDocumentUnfiltered","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType~1documentUnfiltered\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileTypeDocumentUnfiltered"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType~1documentUnfiltered\/fragments"},{"value":"SBSDKDocumentPageFileType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/title"},{"value":[{"text":"SBSDKDocumentPageFileType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileType"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType\/navigatorTitle"},{"value":"SBSDKDocumentPageFileTypeDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType~1document\/title"},{"value":[{"text":"SBSDKDocumentPageFileTypeDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType~1document\/fragments"},{"value":"SBSDKDocumentPageFileTypeOriginal","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType~1original\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentPageFileTypeOriginal"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentPageFileType~1original\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}