{"metadata":{"navigatorTitle":[{"text":"finderView:didChangeRect:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKFinderViewDelegate(im)finderView:didChangeRect:","title":"finderView(_:didChangeRect:)","role":"symbol","required":true},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate, that the finder view has changed its finder rectangle."},{"type":"text","text":" "},{"type":"text","text":"Optional."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","text":"SBSDKFinderView","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"},{"text":", ","kind":"text"},{"text":"didChangeRect","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The finder view that changed its finder viewport rectangle. Can be ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", if it has been removed.","type":"text"}]}],"name":"view"},{"content":[{"inlineContent":[{"text":"The new rectangle of the finder viewport.","type":"text"}],"type":"paragraph"}],"name":"rect"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate\/finderview(_:didchangerect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate\/finderview(_:didchangerect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","title":"SBSDKFinderView","abstract":[{"text":"A ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfinderview"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewDelegate/finderView(_:didChangeRect:)":{"navigatorTitle":[{"text":"finderView:didChangeRect:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate\/finderView(_:didChangeRect:)","abstract":[{"type":"text","text":"Informs the delegate, that the finder view has changed its finder rectangle."},{"type":"text","text":" "},{"type":"text","text":"Optional."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKFinderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView"},{"text":", ","kind":"text"},{"text":"didChangeRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate\/finderview(_:didchangerect:)","kind":"symbol","title":"finderView(_:didChangeRect:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderViewDelegate":{"title":"SBSDKFinderViewDelegate","url":"\/documentation\/scanbotsdk\/sbsdkfinderviewdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderViewDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKFinderViewDelegate"}],"abstract":[{"type":"text","text":"The delegate protocol for the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView"},{"type":"text","text":" class."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"finderView:didChangeRect:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"finderView:didChangeRect:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"finderView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFinderView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","text":"SBSDKFinderView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didChangeRect:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"view","content":[{"inlineContent":[{"text":"The finder view that changed its finder viewport rectangle. Can be ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", if it has been removed.","type":"text"}],"type":"paragraph"}]},{"name":"rect","content":[{"inlineContent":[{"type":"text","text":"The new rectangle of the finder viewport."}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","op":"replace","value":"SBSDKFinderView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","op":"replace","value":[{"text":"SBSDKFinderView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate~1finderView(_:didChangeRect:)\/title","op":"replace","value":"finderView:didChangeRect:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate~1finderView(_:didChangeRect:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"finderView:didChangeRect:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/title","op":"replace","value":"SBSDKFinderViewDelegate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKFinderViewDelegate"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderViewDelegate\/navigatorTitle","op":"replace","value":[{"text":"SBSDKFinderViewDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}