{"metadata":{"navigatorTitle":[{"text":"finderPreferredHeight","kind":"identifier"}],"title":"finderPreferredHeight","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderPreferredHeight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerUIConfiguration(py)finderPreferredHeight","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration"]]},"sections":[],"abstract":[{"text":"The preferred height of the view finder.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"finderPreferredHeight","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration\/finderpreferredheight"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration\/finderpreferredheight"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration\/finderPreferredHeight","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerUIConfiguration/finderPreferredHeight":{"abstract":[{"type":"text","text":"The preferred height of the view finder."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"finderPreferredHeight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"finderPreferredHeight"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration\/finderPreferredHeight","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration\/finderpreferredheight","title":"finderPreferredHeight"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerUIConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerUIConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the user interface look and feel of the RTU-UI license plate scanner."}],"kind":"symbol","type":"topic","title":"SBSDKUILicensePlateScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescanneruiconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUILicensePlateScannerUIConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"finderPreferredHeight","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"finderPreferredHeight"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"text":" ","kind":"text"},{"text":"finderPreferredHeight","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration~1finderPreferredHeight\/title","value":"finderPreferredHeight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration~1finderPreferredHeight\/fragments","value":[{"text":"finderPreferredHeight","kind":"identifier"}]},{"value":"SBSDKUILicensePlateScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUILicensePlateScannerUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerUIConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerUIConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}