{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanStandardSubheadingFieldType","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfield\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfield\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingField\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The field type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanStandardSubheadingFieldType"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMedicalPlanStandardSubheadingField(py)type","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingField"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingFieldType":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"abstract":[{"type":"text","text":"The german medical plan document subheading information description field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingField":{"role":"symbol","title":"SBSDKMedicalPlanStandardSubheadingField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingField"}],"abstract":[{"type":"text","text":"The german medical plan document subheading information description field."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingField"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfield"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalPlanStandardSubheadingField/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanStandardSubheadingFieldType"}],"abstract":[{"type":"text","text":"The field type."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingField\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalplanstandardsubheadingfield\/type"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalPlanStandardSubheadingFieldType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKMedicalPlanStandardSubheadingFieldType","text":"SBSDKMedicalPlanStandardSubheadingFieldType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingFieldType\/title","value":"SBSDKMedicalPlanStandardSubheadingFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingField\/title","value":"SBSDKMedicalPlanStandardSubheadingField"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingField\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalPlanStandardSubheadingField"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingField~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalPlanStandardSubheadingField~1type\/fragments","value":[{"kind":"identifier","text":"type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}