{"kind":"article","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode\/!=(_:_:)"],"anchor":"Operators","title":"Operators"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkonedconfirmationmode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"ScanbotSDK"}],"roleHeading":"API Collection"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOneDConfirmationMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKOneDConfirmationMode"}],"title":"SBSDKOneDConfirmationMode","abstract":[{"type":"text","text":"Allows to select the balance between result accuracy (precision) and missed barcodes (recall) for linear barcodes."},{"type":"text","text":" "},{"type":"text","text":"Some barcode types are naturally prone to false positives (e.g. MSI Plessey)."},{"type":"text","text":" "},{"type":"text","text":"For those barcode types false positives can be drastically reduced (precision can be increased) by requiring that multiple scan-lines in the input scan to the same result."},{"type":"text","text":" "},{"type":"text","text":"However, this stronger condition can lead to missed barcodes (lower recall)."},{"type":"text","text":" "},{"type":"text","text":"Confirmation is avoided for barcode types, which are by design resistant to false positives, (e.g. Code128) to maximize recall."}],"url":"\/documentation\/scanbotsdk\/sbsdkonedconfirmationmode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOneDConfirmationMode/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOneDConfirmationMode\/!=(_:_:)","url":"\/documentation\/scanbotsdk\/sbsdkonedconfirmationmode\/!=(_:_:)","type":"topic","kind":"symbol","role":"symbol","title":"!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKOneDConfirmationMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/title"},{"value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/fragments"},{"value":[{"text":"SBSDKOneDConfirmationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOneDConfirmationMode\/navigatorTitle"}]}]}