{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"capturedImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"? = nil, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"label","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The label to describe the mock data."}]}]},{"name":"imageURL","content":[{"inlineContent":[{"type":"text","text":"A web or file URL to an image file to be used to feed the video stream of simulated camera device."}],"type":"paragraph"}]},{"name":"capturedImageURL","content":[{"type":"paragraph","inlineContent":[{"text":"A web or file URL to an image to be used on simulated camera devices when capturing a still image. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the current frame of the ","type":"text"},{"code":"imageURL","type":"codeVoice"},{"text":" is returned when capturing a still image.","type":"text"}]}]},{"name":"refreshOnEachFrame","content":[{"inlineContent":[{"type":"text","text":"If set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame."}],"type":"paragraph"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)"},"abstract":[{"text":"Initializes mock data for a simulated camera device from URLs.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData"]]},"metadata":{"title":"init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"capturedImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSimulatedCameraMockData(im)initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","navigatorTitle":[{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:"}],"kind":"symbol","abstract":[{"type":"text","text":"Initializes mock data for a simulated camera device from URLs."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData\/init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","title":"init(label:imageURL:capturedImageURL:refreshOnEachFrame:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"capturedImageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"refreshOnEachFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata\/init(label:imageurl:capturedimageurl:refreshoneachframe:)","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSimulatedCameraMockData":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSimulatedCameraMockData","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksimulatedcameramockdata","navigatorTitle":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"role":"symbol","title":"SBSDKSimulatedCameraMockData","type":"topic","abstract":[{"text":"A class to describe the mocking data that is fed to a simulated camera device.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithLabel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"label","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"imageURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"imageURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"capturedImageURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"capturedImageURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshOnEachFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"refreshOnEachFrame"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The label to describe the mock data."}]}],"name":"label"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A web or file URL to an image file to be used to feed the video stream of simulated camera device."}]}],"name":"imageURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A web or file URL to an image to be used on simulated camera devices when capturing a still image. If ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the current frame of the ","type":"text"},{"code":"imageURL","type":"codeVoice"},{"text":" is returned when capturing a still image.","type":"text"}]}],"name":"capturedImageURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" the image is reloaded\/downloaded after each frame. Otherwise the image is loaded only once and reused per frame.","type":"text"}]}],"name":"refreshOnEachFrame"}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/title","op":"replace","value":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLabel:imageURL:capturedImageURL:refreshOnEachFrame:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData~1init(label:imageURL:capturedImageURL:refreshOnEachFrame:)\/fragments"},{"value":"SBSDKSimulatedCameraMockData","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/title"},{"value":[{"text":"SBSDKSimulatedCameraMockData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKSimulatedCameraMockData"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSimulatedCameraMockData\/navigatorTitle"}]}]}