{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/none"},"metadata":{"title":"SBSDKImageFilterType.none","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKImageFilterType@SBSDKImageFilterTypeNone","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Case","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeNone"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"inlineContent":[{"text":"Please consider using the new class-based SBSDKParametricFilters.","type":"text"}],"type":"paragraph"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"]]},"abstract":[{"text":"Passthrough filter. Does not alter the image.","type":"text"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType/none":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype\/none","abstract":[{"type":"text","text":"Passthrough filter. Does not alter the image."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageFilterTypeNone"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType\/none","deprecated":true,"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKImageFilterType.none"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageFilterType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageFilterType","kind":"identifier"}],"title":"SBSDKImageFilterType","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagefiltertype","deprecated":true,"navigatorTitle":[{"text":"SBSDKImageFilterType","kind":"identifier"}],"abstract":[{"type":"text","text":"The ScanbotSDK image filter types."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageFilterType"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKImageFilterTypeNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKImageFilterTypeNone","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"SBSDKImageFilterTypeNone","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1none\/title","op":"replace","value":"SBSDKImageFilterTypeNone"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageFilterTypeNone"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/title","op":"replace","value":"SBSDKImageFilterType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/fragments","op":"replace","value":[{"text":"SBSDKImageFilterType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageFilterType\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageFilterType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}