{"kind":"symbol","sections":[],"abstract":[{"text":"EuropeanDriverLicenseFront document type.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/europeandriverlicensefront"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/europeandriverlicensefront"]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType(cpy)europeanDriverLicenseFront","navigatorTitle":[{"text":"europeanDriverLicenseFront","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Type Property","title":"europeanDriverLicenseFront","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanDriverLicenseFront","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/europeanDriverLicenseFront","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanDriverLicenseFront","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelRootType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype","navigatorTitle":[{"text":"SBSDKDocumentsModelRootType","kind":"identifier"}],"title":"SBSDKDocumentsModelRootType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelRootType","kind":"identifier"}],"abstract":[{"type":"text","text":"Root document type."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType/europeanDriverLicenseFront":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"europeanDriverLicenseFront"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","kind":"typeIdentifier","text":"SBSDKDocumentsModelRootType"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/europeandriverlicensefront","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"europeanDriverLicenseFront"}],"abstract":[{"type":"text","text":"EuropeanDriverLicenseFront document type."}],"type":"topic","title":"europeanDriverLicenseFront","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/europeanDriverLicenseFront"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"europeanDriverLicenseFront","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"europeanDriverLicenseFront","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType","text":"SBSDKDocumentsModelRootType"},{"kind":"text","text":" * "},{"kind":"identifier","text":"europeanDriverLicenseFront"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKDocumentsModelRootType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/title","op":"replace"},{"value":[{"text":"SBSDKDocumentsModelRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/fragments","op":"replace"},{"value":[{"text":"SBSDKDocumentsModelRootType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType\/navigatorTitle","op":"replace"},{"value":"europeanDriverLicenseFront","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1europeanDriverLicenseFront\/title","op":"replace"},{"value":[{"text":"europeanDriverLicenseFront","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1europeanDriverLicenseFront\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}