{"abstract":[{"type":"text","text":"Converts a "},{"type":"codeVoice","code":"CVPixelBufferRef"},{"type":"text","text":" to "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage"]]},"metadata":{"extendedModule":"UIKit","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sbsdk_image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKVideoOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"relatedModules":["UIKit"],"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@CM@ScanbotSDK@@objc(cs)UIImage(cm)sbsdk_imageFromPixelBuffer:orientation:","roleHeading":"Type Method","title":"sbsdk_image(from:orientation:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_image(from:orientation:)-6o11h"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_image(from:orientation:)-6o11h"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(sbsdk_imageFromPixelBuffer:orientation:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pixelBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","text":"SBSDKVideoOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The pixel buffer to convert."}]}],"name":"pixelBuffer"},{"content":[{"inlineContent":[{"text":"The orientation the pixel buffer has. So the final image can be unrotated.","type":"text"}],"type":"paragraph"}],"name":"orientation"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"He converted, unrotated image or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", if the operation failed.","type":"text"}]}],"kind":"content"}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage":{"title":"UIImage","abstract":[{"text":"An ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" class extension to perform basic image processing operations.","type":"text"},{"text":" ","type":"text"},{"text":"Direct usage is not recommended for large images.","type":"text"},{"text":" ","type":"text"},{"text":"queues and proper memory management.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage","navigatorTitle":[{"kind":"identifier","text":"UIImage"}],"url":"\/documentation\/scanbotsdk\/uikit\/uiimage","kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit/UIImage/sbsdk_image(from:orientation:)-6o11h":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit\/UIImage\/sbsdk_image(from:orientation:)-6o11h","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sbsdk_image"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKVideoOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Converts a "},{"code":"CVPixelBufferRef","type":"codeVoice"},{"type":"text","text":" to "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":"."}],"title":"sbsdk_image(from:orientation:)","url":"\/documentation\/scanbotsdk\/uikit\/uiimage\/sbsdk_image(from:orientation:)-6o11h"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"title":"SBSDKVideoOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"abstract":[{"text":"An enum describing the orientation of a video frame.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/UIKit":{"title":"UIKit","kind":"symbol","url":"\/documentation\/scanbotsdk\/uikit","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/UIKit","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"SBSDKVideoOrientation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/title"},{"value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}