{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates\/initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"title":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2UserGuidanceStates(im)initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancestates\/initwithnodocumentfound:badaspectratio:badangles:orientationmismatch:texthintoffcenter:toosmall:toonoisy:toodark:energysavemode:readytocapture:capturing:capturemanual:"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNoDocumentFound:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"noDocumentFound"},{"kind":"text","text":" "},{"kind":"identifier","text":"badAspectRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"badAspectRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"badAngles:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"badAngles"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientationMismatch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"orientationMismatch"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintOffCenter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textHintOffCenter"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooSmall:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tooSmall"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooNoisy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tooNoisy"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooDark:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tooDark"},{"kind":"text","text":" "},{"kind":"identifier","text":"energySaveMode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"energySaveMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"readyToCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"readyToCapture"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"capturing"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureManual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"captureManual"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceStates/initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancestates\/initwithnodocumentfound:badaspectratio:badangles:orientationmismatch:texthintoffcenter:toosmall:toonoisy:toodark:energysavemode:readytocapture:capturing:capturemanual:","role":"symbol","title":"initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates\/initWithNoDocumentFound:badAspectRatio:badAngles:orientationMismatch:textHintOffCenter:tooSmall:tooNoisy:tooDark:energySaveMode:readyToCapture:capturing:captureManual:","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2UserGuidanceStates":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2userguidancestates","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2UserGuidanceStates","abstract":[{"type":"text","text":"Configure the titles of the user guidance hints for different states."}],"title":"SBSDKUI2UserGuidanceStates"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/title","value":"SBSDKUI2UserGuidanceStates"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceStates"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2UserGuidanceStates\/navigatorTitle","value":[{"text":"SBSDKUI2UserGuidanceStates","kind":"identifier"}]}]}]}