{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/hidden"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/hidden"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode\/hidden","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarModeHidden"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKUI2TopBarMode@SBSDKUI2TopBarModeHidden","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hidden","kind":"identifier"}],"title":"SBSDKUI2TopBarMode.hidden","role":"symbol"},"abstract":[{"type":"text","text":"Hide the top bar completely."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TopBarMode":{"abstract":[{"type":"text","text":"The visual mode used for the top bar."}],"kind":"symbol","type":"topic","title":"SBSDKUI2TopBarMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarMode"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarMode"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2TopBarMode/hidden":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2topbarmode\/hidden","abstract":[{"text":"Hide the top bar completely.","type":"text"}],"kind":"symbol","title":"SBSDKUI2TopBarMode.hidden","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2TopBarMode\/hidden","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hidden"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarModeHidden"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUI2TopBarModeHidden","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKUI2TopBarModeHidden","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SBSDKUI2TopBarModeHidden"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2TopBarMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2TopBarMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/fragments"},{"value":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode\/navigatorTitle"},{"value":"SBSDKUI2TopBarModeHidden","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode~1hidden\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TopBarModeHidden"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2TopBarMode~1hidden\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}