{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/hash","interfaceLanguage":"occ"},"sections":[],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKParametricFilter(py)hash","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","title":"hash"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter/hash":{"kind":"symbol","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter\/hash","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter\/hash","role":"symbol","title":"hash"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKParametricFilter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKParametricFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"Base class for all parametric filters."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKParametricFilter","type":"topic","role":"symbol","title":"SBSDKParametricFilter","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkparametricfilter","kind":"symbol","navigatorTitle":[{"text":"SBSDKParametricFilter","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/title","value":"SBSDKParametricFilter","op":"replace"},{"value":[{"text":"SBSDKParametricFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKParametricFilter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKParametricFilter\/navigatorTitle"}]}]}