{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/initwithcameratopbarcancelbuttontitle:cameratopbartitle:cameratopguidance:camerauserguidancestart:camerauserguidancenodocumentfound:camerauserguidancebadaspectratio:camerauserguidanceorientationmismatch:camerauserguidancebadangles:camerause-3zazc"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraTopBarCancelButtonTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraTopBarCancelButtonTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraTopBarTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraTopBarTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraTopGuidance:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraTopGuidance","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceStart:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceStart","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceNoDocumentFound:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceNoDocumentFound","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceBadAspectRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceBadAspectRatio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceOrientationMismatch:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceOrientationMismatch","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceBadAngles:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceBadAngles","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceTooNoisy:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceTooNoisy","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceTextHintOffCenter:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceTextHintOffCenter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceTooSmall:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceTooSmall","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceTooDark:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceTooDark","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceEnergySaveMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceEnergySaveMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceReadyToCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceReadyToCapture","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraUserGuidanceReadyToCaptureManual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraUserGuidanceReadyToCaptureManual","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraImportButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraImportButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraTorchOnButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraTorchOnButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraTorchOffButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraTorchOffButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraAutoSnapButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraAutoSnapButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraManualSnapButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraManualSnapButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraPreviewButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraBadgedPreviewButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraBadgedPreviewButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroDoneButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroDoneButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroItem1:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroItem1","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroItem2:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroItem2","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroItem3:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroItem3","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraIntroItem4:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraIntroItem4","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraProgressOverlayTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraProgressOverlayTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraCancelAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraCancelAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraCancelAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraCancelAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraCancelNoButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraCancelNoButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraCancelYesButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraCancelYesButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraLimitReachedAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraLimitReachedAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraLimitReachedAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraLimitReachedAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraLimitReachedOkButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cameraLimitReachedOkButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acknowledgementScreenBadDocumentHint:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"acknowledgementScreenBadDocumentHint","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acknowledgementRetakeButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"acknowledgementRetakeButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acknowledgementAcceptButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"acknowledgementAcceptButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewTopBarBackButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewTopBarBackButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenPageCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenPageCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenAddButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenAddButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenRetakeButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenRetakeButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenCropButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenCropButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenRotateButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenRotateButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenDeleteButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenDeleteButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenSubmitButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenSubmitButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenDeleteAllButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenDeleteAllButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewScreenReorderPagesButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewScreenReorderPagesButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"zoomOverlayCancelButtonText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"zoomOverlayCancelButtonText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeletePageAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeleteAllPagesAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeleteAllPagesAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeletePageAlertSubTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertSubTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeleteAllPagesAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeleteAllPagesAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeletePageAlertConfirmButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertConfirmButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeleteAllPagesAlertDeleteButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeleteAllPagesAlertDeleteButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeletePageAlertDeleteRetakeButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertDeleteRetakeButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeletePageAlertCancelButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeletePageAlertCancelButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reviewDeleteAllPagesAlertCancelButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reviewDeleteAllPagesAlertCancelButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acknowledgementTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"acknowledgementTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reorderPageTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reorderPageTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reorderPageGuidanceTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reorderPageGuidanceTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reorderPageText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reorderPageText","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reorderTopBarConfirmButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reorderTopBarConfirmButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reorderTopBarCancelButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"reorderTopBarCancelButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingTopBarConfirmButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"croppingTopBarConfirmButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingTopBarCancelButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"croppingTopBarCancelButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingDetectButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"croppingDetectButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingRotateButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"croppingRotateButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingResetButtonTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"croppingResetButtonTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"croppingScreenTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"croppingScreenTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraTopBarIntroButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraTopBarIntroButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraTopBarCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraTopBarCancelButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraImportButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraImportButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraTorchOnButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraTorchOnButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraTorchOffButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraTorchOffButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraShutterButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraShutterButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraAutoSnapButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraAutoSnapButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraManualSnapButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraManualSnapButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPreviewButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraPreviewButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraIntroDoneButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraIntroDoneButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionAcknowledgementRetakeButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionAcknowledgementRetakeButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionAcknowledgementAcceptButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionAcknowledgementAcceptButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarConfirmButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingTopBarConfirmButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingTopBarCancelButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingTopBarCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingDetectButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingDetectButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingRotateButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingRotateButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCroppingResetButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCroppingResetButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReorderTopBarConfirmButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReorderTopBarConfirmButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReorderTopBarCancelButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReorderTopBarCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewNextPageButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewNextPageButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewPreviousPageButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewPreviousPageButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewAddButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewAddButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewRetakeButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewRetakeButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewCropButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewCropButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewRotateButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewRotateButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewSubmitButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewSubmitButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewMoreButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewMoreButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteAllButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteAllButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewReorderPagesButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewReorderPagesButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionZoomOverlayCancelButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionZoomOverlayCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewZoomButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewZoomButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewTopBarBackButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewTopBarBackButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeletePageAlertConfirmButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeletePageAlertConfirmButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeletePageAlertCancelButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeletePageAlertCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraLimitReachedOkButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraLimitReachedOkButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraCancelYesButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraCancelYesButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraCancelNoButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraCancelNoButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraExplanation"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionCloseButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionCloseButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionEnableCameraButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraPermissionEnableCameraButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCameraPermissionCloseButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCameraPermissionCloseButton"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2DocumentScannerTextLocalization(im)initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization\/initwithcameratopbarcancelbuttontitle:cameratopbartitle:cameratopguidance:camerauserguidancestart:camerauserguidancenodocumentfound:camerauserguidancebadaspectratio:camerauserguidanceorientationmismatch:camerauserguidancebadangles:camerause-3zazc","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization\/initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","type":"topic","title":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCameraTopBarCancelButtonTitle:cameraTopBarTitle:cameraTopGuidance:cameraUserGuidanceStart:cameraUserGuidanceNoDocumentFound:cameraUserGuidanceBadAspectRatio:cameraUserGuidanceOrientationMismatch:cameraUserGuidanceBadAngles:cameraUserGuidanceTooNoisy:cameraUserGuidanceTextHintOffCenter:cameraUserGuidanceTooSmall:cameraUserGuidanceTooDark:cameraUserGuidanceEnergySaveMode:cameraUserGuidanceReadyToCapture:cameraUserGuidanceReadyToCaptureManual:cameraImportButtonTitle:cameraTorchOnButtonTitle:cameraTorchOffButtonTitle:cameraAutoSnapButtonTitle:cameraManualSnapButtonTitle:cameraPreviewButtonTitle:cameraBadgedPreviewButtonTitle:cameraIntroDoneButton:cameraIntroTitle:cameraIntroSubtitle:cameraIntroItem1:cameraIntroItem2:cameraIntroItem3:cameraIntroItem4:cameraProgressOverlayTitle:cameraCancelAlertTitle:cameraCancelAlertSubtitle:cameraCancelNoButtonTitle:cameraCancelYesButtonTitle:cameraLimitReachedAlertTitle:cameraLimitReachedAlertSubtitle:cameraLimitReachedOkButtonTitle:acknowledgementScreenBadDocumentHint:acknowledgementRetakeButtonTitle:acknowledgementAcceptButtonTitle:reviewScreenTitle:reviewTopBarBackButtonTitle:reviewScreenPageCount:reviewScreenAddButtonTitle:reviewScreenRetakeButtonTitle:reviewScreenCropButtonTitle:reviewScreenRotateButtonTitle:reviewScreenDeleteButtonTitle:reviewScreenSubmitButtonTitle:reviewScreenDeleteAllButtonTitle:reviewScreenReorderPagesButtonTitle:zoomOverlayCancelButtonText:reviewDeletePageAlertTitle:reviewDeleteAllPagesAlertTitle:reviewDeletePageAlertSubTitle:reviewDeleteAllPagesAlertSubtitle:reviewDeletePageAlertConfirmButtonTitle:reviewDeleteAllPagesAlertDeleteButtonTitle:reviewDeletePageAlertDeleteRetakeButtonTitle:reviewDeletePageAlertCancelButtonTitle:reviewDeleteAllPagesAlertCancelButtonTitle:acknowledgementTitle:reorderPageTitle:reorderPageGuidanceTitle:reorderPageText:reorderTopBarConfirmButtonTitle:reorderTopBarCancelButtonTitle:croppingTopBarConfirmButtonTitle:croppingTopBarCancelButtonTitle:croppingDetectButtonTitle:croppingRotateButtonTitle:croppingResetButtonTitle:croppingScreenTitle:accessibilityDescriptionCameraTopBarIntroButton:accessibilityDescriptionCameraTopBarCancelButton:accessibilityDescriptionCameraImportButton:accessibilityDescriptionCameraTorchOnButton:accessibilityDescriptionCameraTorchOffButton:accessibilityDescriptionCameraShutterButton:accessibilityDescriptionCameraAutoSnapButton:accessibilityDescriptionCameraManualSnapButton:accessibilityDescriptionCameraPreviewButton:accessibilityDescriptionCameraIntroDoneButton:accessibilityDescriptionAcknowledgementRetakeButton:accessibilityDescriptionAcknowledgementAcceptButton:accessibilityDescriptionCroppingTopBarConfirmButton:accessibilityDescriptionCroppingTopBarCancelButton:accessibilityDescriptionCroppingDetectButton:accessibilityDescriptionCroppingRotateButton:accessibilityDescriptionCroppingResetButton:accessibilityDescriptionReorderTopBarConfirmButton:accessibilityDescriptionReorderTopBarCancelButton:accessibilityDescriptionReviewNextPageButton:accessibilityDescriptionReviewPreviousPageButton:accessibilityDescriptionReviewAddButton:accessibilityDescriptionReviewRetakeButton:accessibilityDescriptionReviewCropButton:accessibilityDescriptionReviewRotateButton:accessibilityDescriptionReviewDeleteButton:accessibilityDescriptionReviewSubmitButton:accessibilityDescriptionReviewMoreButton:accessibilityDescriptionReviewDeleteAllButton:accessibilityDescriptionReviewReorderPagesButton:accessibilityDescriptionZoomOverlayCancelButton:accessibilityDescriptionReviewZoomButton:accessibilityDescriptionReviewTopBarBackButton:accessibilityDescriptionReviewDeletePageAlertConfirmButton:accessibilityDescriptionReviewDeleteAllPagesAlertDeleteButton:accessibilityDescriptionReviewDeletePageAlertDeleteRetakeButton:accessibilityDescriptionReviewDeletePageAlertCancelButton:accessibilityDescriptionReviewDeleteAllPagesAlertCancelButton:accessibilityDescriptionCameraLimitReachedOkButton:accessibilityDescriptionCameraCancelYesButton:accessibilityDescriptionCameraCancelNoButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerTextLocalization":{"abstract":[{"text":"Configuration of all the strings for the standalone cropping screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerTextLocalization","title":"SBSDKUI2DocumentScannerTextLocalization","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannertextlocalization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerTextLocalization","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/title","value":"SBSDKUI2DocumentScannerTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerTextLocalization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}