{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"title":"copyWithZone:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2IconStyle(im)copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2iconstyle\/copywithzone:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle\/copyWithZone:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconStyle/copyWithZone:":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle\/copyWithZone:","title":"copyWithZone:","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconstyle\/copywithzone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2IconStyle":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2IconStyle","title":"SBSDKUI2IconStyle","type":"topic","abstract":[{"type":"text","text":"Configuration of the icon appearance."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2iconstyle","navigatorTitle":[{"text":"SBSDKUI2IconStyle","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2IconStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2IconStyle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2IconStyle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}