{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerStep\/aspectRatio","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"aspectRatio"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"aspectRatio","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerStep(py)aspectRatio","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier"}],"symbolKind":"property","platforms":[]},"kind":"symbol","abstract":[{"type":"text","text":"The aspect ratio for the workflow steps region of interest and, equally, for the finder view."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2TextPatternScannerViewController instead.","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerStep"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Defaults to 5:1.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerstep\/aspectratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerstep\/aspectratio"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerStep":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerStep","title":"SBSDKUITextPatternScannerStep","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerStep","kind":"identifier"}],"deprecated":true,"navigatorTitle":[{"text":"SBSDKUITextPatternScannerStep","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerstep","type":"topic","abstract":[{"text":"Defines a single workflow step of ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController","isActive":true},{"text":" flow.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController","kind":"symbol","abstract":[{"text":"A highly customizable camera-based view controller to scan and validate a small rectangular text area in realtime.","type":"text"}],"title":"SBSDKUITextPatternScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller","role":"symbol","navigatorTitle":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerStep/aspectRatio":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio"}],"navigatorTitle":[{"kind":"identifier","text":"aspectRatio"}],"kind":"symbol","abstract":[{"type":"text","text":"The aspect ratio for the workflow steps region of interest and, equally, for the finder view."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerStep\/aspectRatio","role":"symbol","deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerstep\/aspectratio","title":"aspectRatio"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatio":{"abstract":[{"text":"Aspect ratio is the ratio of the width to the height of an image or screen.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkaspectratio","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"identifier"}],"title":"SBSDKAspectRatio"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"aspectRatio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"aspectRatio","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aspectRatio"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKUITextPatternScannerStep","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerStep"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUITextPatternScannerStep","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/title","op":"replace","value":"SBSDKUITextPatternScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep~1aspectRatio\/title","op":"replace","value":"aspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerStep~1aspectRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"aspectRatio"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/title","op":"replace","value":"SBSDKAspectRatio"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/navigatorTitle","op":"replace","value":[{"text":"SBSDKAspectRatio","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}