{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isScanningEnabled"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/isscanningenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/isScanningEnabled","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","roleHeading":"Instance Property","title":"isScanningEnabled","fragments":[{"kind":"identifier","text":"isScanningEnabled"}],"navigatorTitle":[{"kind":"identifier","text":"isScanningEnabled"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerViewController(py)isScanningEnabled","symbolKind":"property"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"title":"SBSDKBarcodeScannerViewController","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode scanner."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerViewController/isScanningEnabled":{"title":"isScanningEnabled","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"isScanningEnabled","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerViewController\/isScanningEnabled","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerviewcontroller\/isscanningenabled"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/title","value":"SBSDKBarcodeScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}