{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardIMPP\/requiredDocumentType","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelVCardIMPP(py)requiredDocumentType","title":"requiredDocumentType","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardIMPP"]]},"abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardimpp\/requireddocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardimpp\/requireddocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardIMPP":{"type":"topic","kind":"symbol","title":"SBSDKBarcodeDocumentModelVCardIMPP","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeDocumentModelVCardIMPP","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardIMPP","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardimpp","abstract":[{"type":"text","text":"IMPP"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeDocumentModelVCardIMPP","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelVCardIMPP/requiredDocumentType":{"navigatorTitle":[{"kind":"identifier","text":"requiredDocumentType"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelvcardimpp\/requireddocumenttype","title":"requiredDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelVCardIMPP\/requiredDocumentType","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"requiredDocumentType","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"requiredDocumentType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"requiredDocumentType"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBarcodeDocumentModelVCardIMPP","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardIMPP\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardIMPP"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardIMPP\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelVCardIMPP"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardIMPP\/navigatorTitle"},{"op":"replace","value":"requiredDocumentType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardIMPP~1requiredDocumentType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"requiredDocumentType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelVCardIMPP~1requiredDocumentType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}