{"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZFinderLayoutPreset(cm)twoLineMrzFinderLayoutPreset","navigatorTitle":[{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset"}],"modules":[{"name":"ScanbotSDK"}],"title":"twoLineMrzFinderLayoutPreset()","roleHeading":"Type Method","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/twoLineMrzFinderLayoutPreset()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/twolinemrzfinderlayoutpreset()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/twolinemrzfinderlayoutpreset()"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"twoLineMrzFinderLayoutPreset","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TwoLineMRZFinderLayoutPreset":{"navigatorTitle":[{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2twolinemrzfinderlayoutpreset","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset","title":"SBSDKUI2TwoLineMRZFinderLayoutPreset","abstract":[{"type":"text","text":"A ready-to-use preset 2-line text to be displayed."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset/twoLineMrzFinderLayoutPreset()":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"typeIdentifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset\/twoLineMrzFinderLayoutPreset()","navigatorTitle":[{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset\/twolinemrzfinderlayoutpreset()","title":"twoLineMrzFinderLayoutPreset()","kind":"symbol","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZFinderLayoutPreset":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"title":"SBSDKUI2MRZFinderLayoutPreset","abstract":[{"type":"text","text":"Source of the text for the MRZ finder example overlay."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZFinderLayoutPreset","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzfinderlayoutpreset"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"twoLineMrzFinderLayoutPreset"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKUI2TwoLineMRZFinderLayoutPreset","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TwoLineMRZFinderLayoutPreset","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TwoLineMRZFinderLayoutPreset"},{"text":" *) ","kind":"text"},{"text":"twoLineMrzFinderLayoutPreset","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/title","op":"replace","value":"SBSDKUI2TwoLineMRZFinderLayoutPreset"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}]},{"value":[{"kind":"identifier","text":"SBSDKUI2TwoLineMRZFinderLayoutPreset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TwoLineMRZFinderLayoutPreset\/navigatorTitle"},{"value":"twoLineMrzFinderLayoutPreset","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1twoLineMrzFinderLayoutPreset()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"twoLineMrzFinderLayoutPreset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset~1twoLineMrzFinderLayoutPreset()\/fragments"},{"value":"SBSDKUI2MRZFinderLayoutPreset","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2MRZFinderLayoutPreset"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZFinderLayoutPreset\/navigatorTitle"}]}]}