{"abstract":[{"text":"Recognized barcode items.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult\/items"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"items","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem","text":"SBSDKUI2BarcodeItem"},{"text":"]","kind":"text"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"items"},{"kind":"text","text":": ["},{"text":"SBSDKUI2BarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerResult(py)items","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"items"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"items"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerresult\/items"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerresult\/items"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItem":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitem","abstract":[{"type":"text","text":"Data about the scanned barcode."}],"role":"symbol","kind":"symbol","title":"SBSDKUI2BarcodeItem","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItem","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItem"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerResult/items":{"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerresult\/items","abstract":[{"type":"text","text":"Recognized barcode items."}],"title":"items","kind":"symbol","navigatorTitle":[{"text":"items","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult\/items","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"items","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKUI2BarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItem"},{"kind":"text","text":"]"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerResult":{"abstract":[{"text":"Results of the barcode scan.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerresult","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerResult","kind":"identifier"}],"title":"SBSDKUI2BarcodeScannerResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2BarcodeScannerResult","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"items"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"items","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKUI2BarcodeItem *>"},{"text":" * ","kind":"text"},{"text":"items","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/title","value":"SBSDKUI2BarcodeItem"},{"value":[{"text":"SBSDKUI2BarcodeItem","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2BarcodeItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItem\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult~1items\/title","value":"items","op":"replace"},{"value":[{"kind":"identifier","text":"items"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult~1items\/fragments","op":"replace"},{"value":"SBSDKUI2BarcodeScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerResult\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerResult","kind":"identifier"}]}]}]}