{"abstract":[{"text":"Document date.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/documentdate"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/documentdate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/documentDate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType"]]},"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDate"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMedicalCertificateRecognizerDateResultType.documentDate","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerDateResultType@SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"documentDate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType/documentDate":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"documentDate","kind":"identifier"}],"abstract":[{"text":"Document date.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKMedicalCertificateRecognizerDateResultType.documentDate","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype\/documentdate","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType\/documentDate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerDateResultType":{"type":"topic","kind":"symbol","title":"SBSDKMedicalCertificateRecognizerDateResultType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerdateresulttype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerDateResultType","abstract":[{"text":"Type classifiers for dates recognized on medical certificates.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1documentDate\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultTypeDocumentDate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType~1documentDate\/fragments","op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerDateResultType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerDateResultType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerDateResultType\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateRecognizerDateResultType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}