{"abstract":[{"type":"text","text":"Quality parameter is for jpeg only and is in range 0 to 100. If -1, then settings from hibernation are used."},{"text":" ","type":"text"},{"type":"text","text":"In case when the Image Ref was created with a lazy load mode and originally has the same format as the requested"},{"text":" ","type":"text"},{"text":"to save,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"then setting quality to -1 leads to simply copying from source to destination,"},{"type":"text","text":" "},{"text":"which is time efficient and prevents quality loss caused by jpeg encoding\/decoding.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"property","title":"quality","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKEncodeImageOptions(py)quality","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"quality"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions\/quality"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quality"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is -1"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions\/quality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions\/quality"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodeImageOptions/quality":{"title":"quality","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions\/quality","navigatorTitle":[{"kind":"identifier","text":"quality"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[{"type":"text","text":"Quality parameter is for jpeg only and is in range 0 to 100. If -1, then settings from hibernation are used."},{"text":" ","type":"text"},{"text":"In case when the Image Ref was created with a lazy load mode and originally has the same format as the requested","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to save,"},{"text":" ","type":"text"},{"type":"text","text":"then setting quality to -1 leads to simply copying from source to destination,"},{"text":" ","type":"text"},{"type":"text","text":"which is time efficient and prevents quality loss caused by jpeg encoding\/decoding."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions\/quality"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodeImageOptions":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"abstract":[{"type":"text","text":"Options for encoding image."}],"navigatorTitle":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions","title":"SBSDKEncodeImageOptions","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"quality"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"quality","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"quality","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions~1quality\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions~1quality\/fragments","value":[{"kind":"identifier","text":"quality"}]},{"value":"SBSDKEncodeImageOptions","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/title","op":"replace"},{"value":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}