{"sections":[],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshotsdiff\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKImageRefPoolSnapshotsDiff(im)isEqual:","title":"isEqual:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff\/isEqual:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 8.0.0","type":"text"}],"title":"ScanbotDocumentScannerSDK","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefPoolSnapshotsDiff":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshotsdiff","role":"symbol","abstract":[{"text":"difference between two snapshots.","type":"text"}],"title":"SBSDKImageRefPoolSnapshotsDiff","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKImageRefPoolSnapshotsDiff/isEqual:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKImageRefPoolSnapshotsDiff\/isEqual:","abstract":[],"title":"isEqual:","role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkimagerefpoolsnapshotsdiff\/isequal:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/title","value":"SBSDKImageRefPoolSnapshotsDiff","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/fragments","value":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKImageRefPoolSnapshotsDiff\/navigatorTitle","value":[{"text":"SBSDKImageRefPoolSnapshotsDiff","kind":"identifier"}],"op":"replace"}]}]}