{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/childneedscarefrom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/childneedscarefrom"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"childNeedsCareFrom"}]}]}],"abstract":[{"type":"text","text":"(Form 21a) Child needs care from (Das genannte Kind bedarf\/bedurfte vom) date."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/childNeedsCareFrom","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType"]]},"metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"childNeedsCareFrom"}],"symbolKind":"case","title":"SBSDKMedicalCertificateDateRecordType.childNeedsCareFrom","navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareFrom","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateDateRecordType@SBSDKMedicalCertificateDateRecordTypeChildNeedsCareFrom"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype","title":"SBSDKMedicalCertificateDateRecordType","type":"topic","navigatorTitle":[{"text":"SBSDKMedicalCertificateDateRecordType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of a date record."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateDateRecordType/childNeedsCareFrom":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificatedaterecordtype\/childneedscarefrom","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareFrom"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"childNeedsCareFrom"}],"title":"SBSDKMedicalCertificateDateRecordType.childNeedsCareFrom","type":"topic","role":"symbol","abstract":[{"type":"text","text":"(Form 21a) Child needs care from (Das genannte Kind bedarf\/bedurfte vom) date."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateDateRecordType\/childNeedsCareFrom"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareFrom","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareFrom"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareFrom","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/title","value":"SBSDKMedicalCertificateDateRecordType","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/fragments","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateDateRecordType"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1childNeedsCareFrom\/title","value":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareFrom","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateDateRecordType~1childNeedsCareFrom\/fragments","value":[{"text":"SBSDKMedicalCertificateDateRecordTypeChildNeedsCareFrom","kind":"identifier"}],"op":"replace"}]}]}