{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/hash","interfaceLanguage":"occ"},"metadata":{"fragments":[{"kind":"identifier","text":"hash"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","title":"hash","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRefCountedObjectProfile(py)hash","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/hash"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile","type":"topic","abstract":[{"type":"text","text":"Profile info of a reference-counted stored object."}],"navigatorTitle":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile","title":"SBSDKRefCountedObjectProfile"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile/hash":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/hash","type":"topic","abstract":[],"fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/hash","title":"hash"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKRefCountedObjectProfile","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/title"},{"value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/fragments"},{"value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle"}]}]}