{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/isequal:"]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/isEqual:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRefCountedObjectProfile(im)isEqual:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","title":"isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile/isEqual:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/isequal:","role":"symbol","title":"isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile","type":"topic","abstract":[{"type":"text","text":"Profile info of a reference-counted stored object."}],"navigatorTitle":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile","title":"SBSDKRefCountedObjectProfile"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKRefCountedObjectProfile","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/title"},{"value":[{"kind":"identifier","text":"SBSDKRefCountedObjectProfile"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKRefCountedObjectProfile"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle"}]}]}