{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaDLIDAliasSuffixNameFieldName"},"kind":"symbol","abstract":[{"text":"Name of the “AliasSuffixName” field type in document type “AAMVA.DLID”.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/aamvadlidaliassuffixnamefieldname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/aamvadlidaliassuffixnamefieldname"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"]]},"metadata":{"title":"aamvaDLIDAliasSuffixNameFieldName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aamvaDLIDAliasSuffixNameFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"aamvaDLIDAliasSuffixNameFieldName","kind":"identifier"}],"roleHeading":"Type Property","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)aamvaDLIDAliasSuffixNameFieldName","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaDLIDAliasSuffixNameFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants/aamvaDLIDAliasSuffixNameFieldName":{"title":"aamvaDLIDAliasSuffixNameFieldName","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/aamvadlidaliassuffixnamefieldname","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aamvaDLIDAliasSuffixNameFieldName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"aamvaDLIDAliasSuffixNameFieldName","kind":"identifier"}],"abstract":[{"text":"Name of the “AliasSuffixName” field type in document type “AAMVA.DLID”.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/aamvaDLIDAliasSuffixNameFieldName"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"title":"SBSDKBarcodeDocumentModelConstants","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"aamvaDLIDAliasSuffixNameFieldName","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"aamvaDLIDAliasSuffixNameFieldName"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aamvaDLIDAliasSuffixNameFieldName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"aamvaDLIDAliasSuffixNameFieldName","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaDLIDAliasSuffixNameFieldName\/title","op":"replace"},{"value":[{"text":"aamvaDLIDAliasSuffixNameFieldName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1aamvaDLIDAliasSuffixNameFieldName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}]},{"value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}