{"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)deMedicalPlanPatientWeightFieldNormalizedName","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deMedicalPlanPatientWeightFieldNormalizedName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","title":"deMedicalPlanPatientWeightFieldNormalizedName","navigatorTitle":[{"kind":"identifier","text":"deMedicalPlanPatientWeightFieldNormalizedName"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"]]},"abstract":[{"type":"text","text":"Normalized full name of the “Weight” field type in document type “DEMedicalPlan.Patient”."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/demedicalplanpatientweightfieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/demedicalplanpatientweightfieldnormalizedname"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/deMedicalPlanPatientWeightFieldNormalizedName"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"deMedicalPlanPatientWeightFieldNormalizedName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"title":"SBSDKBarcodeDocumentModelConstants","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants/deMedicalPlanPatientWeightFieldNormalizedName":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/deMedicalPlanPatientWeightFieldNormalizedName","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"deMedicalPlanPatientWeightFieldNormalizedName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"deMedicalPlanPatientWeightFieldNormalizedName","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/demedicalplanpatientweightfieldnormalizedname","abstract":[{"text":"Normalized full name of the “Weight” field type in document type “DEMedicalPlan.Patient”.","type":"text"}],"title":"deMedicalPlanPatientWeightFieldNormalizedName"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"deMedicalPlanPatientWeightFieldNormalizedName"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"deMedicalPlanPatientWeightFieldNormalizedName"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"deMedicalPlanPatientWeightFieldNormalizedName","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKBarcodeDocumentModelConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1deMedicalPlanPatientWeightFieldNormalizedName\/title","value":"deMedicalPlanPatientWeightFieldNormalizedName","op":"replace"},{"value":[{"text":"deMedicalPlanPatientWeightFieldNormalizedName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1deMedicalPlanPatientWeightFieldNormalizedName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}