{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"idCardPDF417OptionalFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"idCardPDF417OptionalFieldNormalizedName","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)idCardPDF417OptionalFieldNormalizedName","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardPDF417OptionalFieldNormalizedName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"idCardPDF417OptionalFieldNormalizedName"}],"role":"symbol","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/idcardpdf417optionalfieldnormalizedname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/idcardpdf417optionalfieldnormalizedname"]}],"abstract":[{"type":"text","text":"Normalized full name of the “Optional” field type in document type “IDCardPDF417”."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/idCardPDF417OptionalFieldNormalizedName"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"title":"SBSDKBarcodeDocumentModelConstants","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentModelConstants/idCardPDF417OptionalFieldNormalizedName":{"title":"idCardPDF417OptionalFieldNormalizedName","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"idCardPDF417OptionalFieldNormalizedName"}],"abstract":[{"type":"text","text":"Normalized full name of the “Optional” field type in document type “IDCardPDF417”."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"idCardPDF417OptionalFieldNormalizedName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentModelConstants\/idCardPDF417OptionalFieldNormalizedName","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentmodelconstants\/idcardpdf417optionalfieldnormalizedname","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"idCardPDF417OptionalFieldNormalizedName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"idCardPDF417OptionalFieldNormalizedName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"idCardPDF417OptionalFieldNormalizedName","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/title","value":"SBSDKBarcodeDocumentModelConstants"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}]},{"op":"replace","value":[{"text":"SBSDKBarcodeDocumentModelConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1idCardPDF417OptionalFieldNormalizedName\/title","value":"idCardPDF417OptionalFieldNormalizedName"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentModelConstants~1idCardPDF417OptionalFieldNormalizedName\/fragments","value":[{"text":"idCardPDF417OptionalFieldNormalizedName","kind":"identifier"}],"op":"replace"}]}]}