{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dosageFreeText"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalplanmedicinefieldtype\/dosagefreetext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2medicalplanmedicinefieldtype\/dosagefreetext"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanMedicineFieldType\/dosageFreeText","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Dosage free text"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dosageFreeText"}],"title":"SBSDKUI2MedicalPlanMedicineFieldType.dosageFreeText","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKUI2MedicalPlanMedicineFieldType@SBSDKUI2MedicalPlanMedicineFieldTypeDosageFreeText","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeDosageFreeText"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanMedicineFieldType"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanMedicineFieldType":{"role":"symbol","title":"SBSDKUI2MedicalPlanMedicineFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldType"}],"abstract":[{"type":"text","text":"Medical Plan Medicine Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanMedicineFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplanmedicinefieldtype"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MedicalPlanMedicineFieldType/dosageFreeText":{"role":"symbol","title":"SBSDKUI2MedicalPlanMedicineFieldType.dosageFreeText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dosageFreeText"}],"abstract":[{"type":"text","text":"Dosage free text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MedicalPlanMedicineFieldType\/dosageFreeText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeDosageFreeText"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2medicalplanmedicinefieldtype\/dosagefreetext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2MedicalPlanMedicineFieldTypeDosageFreeText"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeDosageFreeText"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeDosageFreeText"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanMedicineFieldType\/title","value":"SBSDKUI2MedicalPlanMedicineFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanMedicineFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanMedicineFieldType~1dosageFreeText\/title","value":"SBSDKUI2MedicalPlanMedicineFieldTypeDosageFreeText"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MedicalPlanMedicineFieldType~1dosageFreeText\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MedicalPlanMedicineFieldTypeDosageFreeText"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}