{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/isCancelButtonHidden","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"isCancelButtonHidden","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodesBatchScannerUIConfiguration(py)isCancelButtonHidden","platforms":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCancelButtonHidden"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"isCancelButtonHidden","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Whether the cancel button is hidden or not."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use SBSDKUI2BarcodeScannerViewController instead.","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/iscancelbuttonhidden"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/iscancelbuttonhidden"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCancelButtonHidden","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerUIConfiguration/isCancelButtonHidden":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCancelButtonHidden"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration\/isCancelButtonHidden","abstract":[{"type":"text","text":"Whether the cancel button is hidden or not."}],"title":"isCancelButtonHidden","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isCancelButtonHidden"}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscanneruiconfiguration\/iscancelbuttonhidden","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodesBatchScannerUIConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodesBatchScannerUIConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}],"kind":"symbol","deprecated":true,"type":"topic","abstract":[{"type":"text","text":"The configuration for user interface of the RTU-UI batch barcode scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodesbatchscanneruiconfiguration","title":"SBSDKUIBarcodesBatchScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodesBatchScannerUIConfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"isCancelButtonHidden","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isCancelButtonHidden"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCancelButtonHidden"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"isCancelButtonHidden","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1isCancelButtonHidden\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration~1isCancelButtonHidden\/fragments","value":[{"text":"isCancelButtonHidden","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUIBarcodesBatchScannerUIConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodesBatchScannerUIConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIBarcodesBatchScannerUIConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}