{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(generateFromImageStorage:indexSet:output:progress:error:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageStorage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageStoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexSet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"text":": ","kind":"text"},{"text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"},{"text":"? = nil) ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The image store to take the images from.","type":"text"}]}],"name":"imageStorage"},{"content":[{"inlineContent":[{"text":"The indices of images in the image store the PDF should be generated from. Pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if all images must be used.","type":"text"}],"type":"paragraph"}],"name":"indexSet"},{"content":[{"inlineContent":[{"text":"The output file URL.","type":"text"}],"type":"paragraph"}],"name":"output"},{"content":[{"inlineContent":[{"type":"text","text":"An optional "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","type":"reference","isActive":true},{"type":"text","text":" object that can be observed."}],"type":"paragraph"}],"name":"progress"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Each page is made up of one image.","type":"text"}]}]}],"abstract":[{"text":"Synchronously generates the PDF file from the images at the specified indices from the image storage","type":"text"},{"text":" ","type":"text"},{"text":"with the given page size, and saves the PDF to the specified URL.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:indexset:output:progress:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:indexset:output:progress:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:progress:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"generate(from:indexSet:output:progress:)","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFGenerator(im)generateFromImageStorage:indexSet:output:progress:error:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKImageStoring","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"text":", ","kind":"text"},{"text":"indexSet","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":"?, ","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"generateFromImageStorage:indexSet:output:progress:error:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"kind":"symbol","type":"topic","title":"SBSDKProgress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","role":"symbol","abstract":[],"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkprogress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFGenerator","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator","navigatorTitle":[{"text":"SBSDKPDFGenerator","kind":"identifier"}],"abstract":[{"text":"A class to generate an ordered collection of images with or without performing HOCR.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator","title":"SBSDKPDFGenerator","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFGenerator/generate(from:indexSet:output:progress:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"indexSet","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"output","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","navigatorTitle":[{"text":"generateFromImageStorage:indexSet:output:progress:error:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Synchronously generates the PDF file from the images at the specified indices from the image storage"},{"type":"text","text":" "},{"type":"text","text":"with the given page size, and saves the PDF to the specified URL."}],"title":"generate(from:indexSet:output:progress:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFGenerator\/generate(from:indexSet:output:progress:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfgenerator\/generate(from:indexset:output:progress:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"role":"symbol","kind":"symbol","type":"topic","title":"SBSDKImageStoring","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageStoring"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","abstract":[{"text":"Protocol for an order-aware (array like) image storage.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageStoring"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"generateFromImageStorage:indexSet:output:progress:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"generateFromImageStorage:indexSet:output:progress:error:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"generateFromImageStorage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SBSDKImageStoring>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"text":") ","kind":"text"},{"text":"imageStorage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"indexSet:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSIndexSet","preciseIdentifier":"c:objc(cs)NSIndexSet"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexSet"},{"kind":"text","text":" "},{"kind":"identifier","text":"output:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"output"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"progress"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"imageStorage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image store to take the images from."}]}]},{"name":"indexSet","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The indices of images in the image store the PDF should be generated from. Pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if all images must be used."}]}]},{"name":"output","content":[{"inlineContent":[{"text":"The output file URL.","type":"text"}],"type":"paragraph"}]},{"name":"progress","content":[{"type":"paragraph","inlineContent":[{"text":"An optional ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","isActive":true,"type":"reference"},{"text":" object that can be observed.","type":"text"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" for this parameter.","type":"text"}]}]}]}},{"path":"\/primaryContentSections\/2","op":"add","value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the method succeeded, otherwise "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title","op":"replace","value":"SBSDKProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments","op":"replace","value":[{"text":"SBSDKProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKProgress"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/title","op":"replace","value":"SBSDKPDFGenerator"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFGenerator"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPDFGenerator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:indexSet:output:progress:)\/title","op":"replace","value":"generateFromImageStorage:indexSet:output:progress:error:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFGenerator~1generate(from:indexSet:output:progress:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateFromImageStorage:indexSet:output:progress:error:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","op":"replace","value":"SBSDKImageStoring"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments","op":"replace","value":[{"text":"SBSDKImageStoring","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageStoring","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}