{"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/fieldDetails","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/overallIsInvalid"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/toJson(configuration:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"abstract":[{"text":"Report of the field validation verification.","type":"text"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"SBSDKInvalidDataVerificationReport","navigatorTitle":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKInvalidDataVerificationReport"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(SBSDKInvalidDataVerificationReport) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/isEqual:":{"fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/isEqual:","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/copyWithZone:":{"title":"copyWithZone:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/copywithzone:","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/fieldDetails":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/fieldDetails","navigatorTitle":[{"kind":"identifier","text":"fieldDetails"}],"abstract":[{"text":"List of reports for each field that was verified.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/fielddetails","title":"fieldDetails","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fieldDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SBSDKFieldInvalidDataVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKFieldInvalidDataVerificationReport"},{"kind":"text","text":">"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"abstract":[],"title":"hash","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/hash","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/hash"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/initWithOverallIsInvalid:fieldDetails:":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/initWithOverallIsInvalid:fieldDetails:","type":"topic","title":"initWithOverallIsInvalid:fieldDetails:","url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/initwithoverallisinvalid:fielddetails:","role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithOverallIsInvalid:fieldDetails:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithOverallIsInvalid:fieldDetails:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/tojson(configuration:)","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","title":"toJson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/toJson(configuration:)","navigatorTitle":[{"text":"toJsonWithConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/overallIsInvalid":{"url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/overallisinvalid","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/overallIsInvalid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"overallIsInvalid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Overall status of the document verification. Corresponds to the most severe status of all fields, i.e. if at least one field is invalid, the overall status is invalid."}],"title":"overallIsInvalid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"overallIsInvalid"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport/fromJsonWithJson:":{"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/fromJsonWithJson:","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport\/fromjsonwithjson:","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"type":"topic","abstract":[],"title":"fromJsonWithJson:","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKInvalidDataVerificationReport":{"abstract":[{"type":"text","text":"Report of the field validation verification."}],"navigatorTitle":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SBSDKInvalidDataVerificationReport","url":"\/documentation\/scanbotsdk\/sbsdkinvaliddataverificationreport","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport","type":"topic"},"doc://net.doo.ScanbotSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKInvalidDataVerificationReport"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/fieldDetails","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/overallIsInvalid"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/initWithOverallIsInvalid:fieldDetails:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/toJson(configuration:)"],"generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKInvalidDataVerificationReport\/fromJsonWithJson:"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKInvalidDataVerificationReport"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport~1fieldDetails\/title","value":"fieldDetails"},{"value":[{"text":"fieldDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport~1fieldDetails\/fragments"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport~1toJson(configuration:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport~1toJson(configuration:)\/fragments"},{"value":"overallIsInvalid","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport~1overallIsInvalid\/title"},{"value":[{"text":"overallIsInvalid","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport~1overallIsInvalid\/fragments"},{"value":"SBSDKInvalidDataVerificationReport","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/title"},{"value":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/fragments"},{"value":[{"text":"SBSDKInvalidDataVerificationReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKInvalidDataVerificationReport\/navigatorTitle"}]}]}