{"abstract":[{"type":"text","text":"The delegation protocol for the barcode tracking overlay controller."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"title":"SBSDKBarcodeTrackingOverlayControllerDelegate","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKBarcodeTrackingOverlayControllerDelegate","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Protocol"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:customViewFor:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:didCreateCustomView:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:didTapOnBarcode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:overrideTextFor:proposedString:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:shouldHighlight:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:highlighted:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:didTapOnBarcode:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:didtaponbarcode:)","navigatorTitle":[{"text":"barcodeTrackingOverlay:didTapOnBarcode:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when a barcode is being tapped on."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didTapOnBarcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"barcodeTrackingOverlay(_:didTapOnBarcode:)","kind":"symbol","required":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:didTapOnBarcode:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"title":"SBSDKBarcodeTrackingOverlayControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate","type":"topic","role":"symbol","abstract":[{"text":"The delegation protocol for the barcode tracking overlay controller.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:shouldHighlight:)":{"title":"barcodeTrackingOverlay(_:shouldHighlight:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"text":", ","kind":"text"},{"text":"shouldHighlight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks the delegate to provide if the barcode tracking overlay should highlight a barcode."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:shouldhighlight:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:shouldHighlight:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"barcodeTrackingOverlay:shouldHighlight:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:customViewFor:)":{"kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTrackingOverlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customViewFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:customviewfor:)","title":"barcodeTrackingOverlay(_:customViewFor:)","navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:customViewFor:"}],"type":"topic","abstract":[{"text":"Asks the delegate to create a custom tracking view for the given barcode,","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:customViewFor:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:overrideTextFor:proposedString:)":{"kind":"symbol","role":"symbol","title":"barcodeTrackingOverlay(_:overrideTextFor:proposedString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeTrackingOverlay"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"overrideTextFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proposedString"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:overridetextfor:proposedstring:)","navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:overrideTextFor:proposedString:"}],"abstract":[{"text":"Asks the delegate to override the text that is displayed for a barcode.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:overrideTextFor:proposedString:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:textstylefor:proposedstyle:)","navigatorTitle":[{"text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:","kind":"identifier"}],"abstract":[{"text":"Asks the delegate to provide a custom style for a tracked barcodes info view. Is called when drawing the","type":"text"},{"text":" ","type":"text"},{"text":"info view for the tracked barcode.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textStyleFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proposedStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle","kind":"typeIdentifier"}],"title":"barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)","kind":"symbol","required":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:polygonstylefor:proposedstyle:)","navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:"}],"abstract":[{"type":"text","text":"Asks the delegate to provide a custom style for a tracked barcodes polygon. Is called when drawing the polygon"},{"type":"text","text":" "},{"type":"text","text":"view for the tracked barcode."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"polygonStyleFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"proposedStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKBarcodeTrackedViewPolygonStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewPolygonStyle","kind":"typeIdentifier"}],"title":"barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)","kind":"symbol","required":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:didCreateCustomView:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCreateCustomView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"barcodeTrackingOverlay(_:didCreateCustomView:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:didCreateCustomView:)","kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate that a custom tracked barcode view has been generated."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:didcreatecustomview:)","required":true,"role":"symbol","navigatorTitle":[{"text":"barcodeTrackingOverlay:didCreateCustomView:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:highlighted:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:updatecustomview:for:barcodeframe:highlighted:)","navigatorTitle":[{"text":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:highlighted:","kind":"identifier"}],"abstract":[{"text":"Informs the delegate to update the custom tracking view for the given barcode.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"updateCustomView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeItem","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"highlighted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:highlighted:)","kind":"symbol","required":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:highlighted:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodeTrackingOverlayControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:customViewFor:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:didCreateCustomView:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:didTapOnBarcode:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:overrideTextFor:proposedString:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:shouldHighlight:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:highlighted:)"],"anchor":"Instance-Methods"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:didTapOnBarcode:)\/title","value":"barcodeTrackingOverlay:didTapOnBarcode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:didTapOnBarcode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeTrackingOverlay:didTapOnBarcode:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/title","value":"SBSDKBarcodeTrackingOverlayControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/fragments","value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:shouldHighlight:)\/title","value":"barcodeTrackingOverlay:shouldHighlight:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:shouldHighlight:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:shouldHighlight:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:customViewFor:)\/title","value":"barcodeTrackingOverlay:customViewFor:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:customViewFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeTrackingOverlay:customViewFor:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:overrideTextFor:proposedString:)\/title","value":"barcodeTrackingOverlay:overrideTextFor:proposedString:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:overrideTextFor:proposedString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeTrackingOverlay:overrideTextFor:proposedString:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)\/title","value":"barcodeTrackingOverlay:textStyleFor:proposedStyle:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:textStyleFor:proposedStyle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:textStyleFor:proposedStyle:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)\/title","value":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:polygonStyleFor:proposedStyle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:polygonStyleFor:proposedStyle:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:didCreateCustomView:)\/title","value":"barcodeTrackingOverlay:didCreateCustomView:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:didCreateCustomView:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:didCreateCustomView:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:highlighted:)\/title","value":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:highlighted:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:highlighted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:highlighted:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}