{"metadata":{"roleHeading":"Class","title":"SBSDKPartiallyVisibleDocumentConfiguration","symbolKind":"class","modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"navigatorTitle":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration"},"sections":[],"abstract":[{"text":"Configuration for handling partially visible documents.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/init()"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/accumulationDuration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/allowPartiallyVisibleDocuments","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/minimumBrightness","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/retentionTime"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/toJson(configuration:)"],"generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKPartiallyVisibleDocumentConfiguration) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/isEqual:":{"url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/isequal:","role":"symbol","kind":"symbol","title":"isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/isEqual:","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/minimumBrightness":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/minimumBrightness","abstract":[{"type":"text","text":"Minimum brightness of a partially visible potential document. Increasing this value can reduce the number"},{"type":"text","text":" "},{"type":"text","text":"of spurious detections."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumBrightness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","title":"minimumBrightness","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/minimumbrightness","navigatorTitle":[{"kind":"identifier","text":"minimumBrightness"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/hash":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/hash","fragments":[{"text":"hash","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/hash","title":"hash"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/toJson(configuration:)":{"type":"topic","title":"toJson(configuration:)","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/tojson(configuration:)","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/toJson(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Returns a JSON string representation format."}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/copywithzone:","title":"copyWithZone:","role":"symbol"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/accumulationDuration":{"type":"topic","navigatorTitle":[{"text":"accumulationDuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Duration in milliseconds over which the document has to be detected as partially visible. If on any frame the"},{"type":"text","text":" "},{"type":"text","text":"document is not detected as partially visible, or detected as having a completely different Displacement, the"},{"type":"text","text":" "},{"text":"accumulation will be reset. During the accumulation, the document scanner will return a status of","type":"text"},{"text":" ","type":"text"},{"text":"ERROR_NOTHING_DETECTED instead of one of the partially visible statuses. Set to 0 to disable this behavior.","type":"text"}],"title":"accumulationDuration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accumulationDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/accumulationDuration","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/accumulationduration","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:":{"title":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/initwithallowpartiallyvisibledocuments:accumulationduration:retentiontime:minimumbrightness:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/init()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/init()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/allowPartiallyVisibleDocuments":{"abstract":[{"type":"text","text":"If true, the document scanner will return a status of ERROR_PARTIALLY_VISIBLE or ERROR_PARTIALLY_VISIBLE_TOO_CLOSE"},{"type":"text","text":" "},{"type":"text","text":"if a document-like shape is detected, but not all four corners of the document are visible."},{"type":"text","text":" "},{"text":"If false, a status of ERROR_NOTHING_DETECTED will be returned instead.","type":"text"}],"title":"allowPartiallyVisibleDocuments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPartiallyVisibleDocuments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/allowpartiallyvisibledocuments","navigatorTitle":[{"kind":"identifier","text":"allowPartiallyVisibleDocuments"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/allowPartiallyVisibleDocuments","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/fromJsonWithJson:":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/fromjsonwithjson:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"navigatorTitle":[{"text":"fromJsonWithJson:","kind":"identifier"}],"abstract":[],"title":"fromJsonWithJson:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration/retentionTime":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration\/retentiontime","title":"retentionTime","type":"topic","abstract":[{"text":"Time in milliseconds during which the detection status ERROR_NOTHING_DETECTED is changed to","type":"text"},{"text":" ","type":"text"},{"text":"ERROR_PARTIALLY_VISIBLE_TOO_CLOSE if no document was detected following the detection of a partially visible","type":"text"},{"text":" ","type":"text"},{"text":"document. Set to 0 to disable this behavior.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retentionTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/retentionTime","navigatorTitle":[{"kind":"identifier","text":"retentionTime"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"navigatorTitle":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for handling partially visible documents.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration","title":"SBSDKPartiallyVisibleDocumentConfiguration"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPartiallyVisibleDocumentConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/accumulationDuration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/allowPartiallyVisibleDocuments","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/minimumBrightness","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/retentionTime"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/init()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/toJson(configuration:)"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/fromJsonWithJson:"],"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1minimumBrightness\/title","op":"replace","value":"minimumBrightness"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1minimumBrightness\/fragments","op":"replace","value":[{"kind":"identifier","text":"minimumBrightness"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1toJson(configuration:)\/title","op":"replace","value":"toJsonWithConfiguration:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1toJson(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1accumulationDuration\/title","op":"replace","value":"accumulationDuration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1accumulationDuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"accumulationDuration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1allowPartiallyVisibleDocuments\/title","op":"replace","value":"allowPartiallyVisibleDocuments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1allowPartiallyVisibleDocuments\/fragments","op":"replace","value":[{"kind":"identifier","text":"allowPartiallyVisibleDocuments"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1retentionTime\/title","op":"replace","value":"retentionTime"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1retentionTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"retentionTime"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title","op":"replace","value":"SBSDKPartiallyVisibleDocumentConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}