{"sections":[],"metadata":{"title":"SBSDKBarcodeScannerEngineMode","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeScannerEngineMode","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum","roleHeading":"Enumeration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode"},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/legacy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGen","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenFarDistance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenLowPower","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenLowPowerFarDistance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenMaxDistance"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/RawRepresentable-Implementations"],"generated":true}],"abstract":[{"text":"The engine mode for barcode scanning.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKBarcodeScannerEngineMode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/nextGenMaxDistance":{"title":"SBSDKBarcodeScannerEngineMode.nextGenMaxDistance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenMaxDistance","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Similar to NEXT_GEN_FAR_DISTANCE, but optimized for scanning from far distances on very high power devices."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenmaxdistance","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextGenMaxDistance"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeNextGenMaxDistance"}]},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/legacy":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/legacy","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeLegacy","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"legacy","kind":"identifier"}],"abstract":[{"text":"Legacy mode. Very fast, significantly less accurate. Doesn’t support all barcode types.","type":"text"}],"title":"SBSDKBarcodeScannerEngineMode.legacy","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/legacy"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/nextGenLowPowerFarDistance":{"type":"topic","kind":"symbol","title":"SBSDKBarcodeScannerEngineMode.nextGenLowPowerFarDistance","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextGenLowPowerFarDistance","kind":"identifier"}],"abstract":[{"text":"Similar to NEXT_GEN_LOW_POWER, but optimized for scanning from far distances.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenlowpowerfardistance","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenLowPowerFarDistance"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/init(rawValue:)":{"type":"topic","kind":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/init(rawvalue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/Equatable-Implementations":{"kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","role":"collectionGroup","abstract":[]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/nextGenFarDistance":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextGenFarDistance","kind":"identifier"}],"title":"SBSDKBarcodeScannerEngineMode.nextGenFarDistance","abstract":[{"text":"Similar to NEXT_GEN, but optimized for scanning from far distances.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeNextGenFarDistance","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenfardistance","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenFarDistance"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/nextGen":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGen","abstract":[{"text":"Main engine mode for high-power devices. Supports all barcodes types.","type":"text"}],"title":"SBSDKBarcodeScannerEngineMode.nextGen","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextGen","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgen","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeNextGen","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/RawRepresentable-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/RawRepresentable-Implementations","kind":"article","type":"topic","abstract":[],"title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode","role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"abstract":[{"type":"text","text":"The engine mode for barcode scanning."}],"title":"SBSDKBarcodeScannerEngineMode","type":"topic"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerEngineMode/nextGenLowPower":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerenginemode\/nextgenlowpower","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenLowPower","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A faster version of the main engine mode, for use with low-power devices."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextGenLowPower","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerEngineModeNextGenLowPower","kind":"identifier"}],"title":"SBSDKBarcodeScannerEngineMode.nextGenLowPower"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKBarcodeScannerEngineMode","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/legacy","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGen","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenFarDistance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenLowPower","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenLowPowerFarDistance","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerEngineMode\/nextGenMaxDistance"],"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerEngineMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKBarcodeScannerEngineModeNextGenMaxDistance","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenMaxDistance\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeNextGenMaxDistance"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenMaxDistance\/fragments"},{"op":"replace","value":"SBSDKBarcodeScannerEngineModeLegacy","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1legacy\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerEngineModeLegacy","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1legacy\/fragments"},{"op":"replace","value":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenLowPowerFarDistance\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerEngineModeNextGenLowPowerFarDistance","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenLowPowerFarDistance\/fragments"},{"op":"replace","value":"SBSDKBarcodeScannerEngineModeNextGenFarDistance","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenFarDistance\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineModeNextGenFarDistance"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenFarDistance\/fragments"},{"op":"replace","value":"SBSDKBarcodeScannerEngineModeNextGen","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGen\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerEngineModeNextGen","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGen\/fragments"},{"op":"replace","value":"SBSDKBarcodeScannerEngineMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode\/navigatorTitle"},{"op":"replace","value":"SBSDKBarcodeScannerEngineModeNextGenLowPower","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenLowPower\/title"},{"op":"replace","value":[{"text":"SBSDKBarcodeScannerEngineModeNextGenLowPower","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerEngineMode~1nextGenLowPower\/fragments"}]}]}