{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKBarcodeAccumulationMethod) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod"]}],"kind":"symbol","abstract":[{"type":"text","text":"The method how to display barcodes from previous frames."}],"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodeAccumulationMethod","symbolKind":"enum","navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKBarcodeAccumulationMethod"},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/interpolateByCamera","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/lastVisible"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/RawRepresentable-Implementations"],"generated":true}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo"}],"references":{"doc://net.doo.ScanbotSDK/SQ":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod/interpolateByCamera":{"navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/interpolatebycamera","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/interpolateByCamera","title":"SBSDKBarcodeAccumulationMethod.interpolateByCamera","kind":"symbol","abstract":[{"type":"text","text":"The quad of barcode is interpolated by the camera movement. This option is recommended when the camera is moving, but the scanned object is not."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"interpolateByCamera","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/SY":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod/init(rawValue:)":{"kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/init(rawvalue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/init(rawValue:)","role":"symbol","title":"init(rawValue:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod/lastVisible":{"kind":"symbol","title":"SBSDKBarcodeAccumulationMethod.lastVisible","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastVisible","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/lastVisible","abstract":[{"type":"text","text":"The quad of a barcode is simply given as the last quad when it was detected."}],"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethodLastVisible","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/lastvisible"},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod/Equatable-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/Equatable-Implementations","type":"topic","kind":"article","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/equatable-implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod\/rawrepresentable-implementations"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeAccumulationMethod":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeaccumulationmethod","title":"SBSDKBarcodeAccumulationMethod","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod","abstract":[{"text":"The method how to display barcodes from previous frames.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/Se":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable","title":"Swift.Decodable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeAccumulationMethod"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/interpolateByCamera","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeAccumulationMethod\/lastVisible"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod~1interpolateByCamera\/title","value":"SBSDKBarcodeAccumulationMethodInterpolateByCamera"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod~1interpolateByCamera\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethodInterpolateByCamera"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod~1lastVisible\/title","value":"SBSDKBarcodeAccumulationMethodLastVisible"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod~1lastVisible\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethodLastVisible"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/title","value":"SBSDKBarcodeAccumulationMethod"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeAccumulationMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeAccumulationMethod\/navigatorTitle","value":[{"text":"SBSDKBarcodeAccumulationMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}