{"metadata":{"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKAnalyticsSubscriber","roleHeading":"Protocol","role":"symbol","title":"SBSDKAnalyticsSubscriber","navigatorTitle":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"The subscriber that is being tracked.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKAnalyticsSubscriber) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticssubscriber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkanalyticssubscriber"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber\/logEvent(event:)"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsSubscriber/logEvent(event:)":{"url":"\/documentation\/scanbotsdk\/sbsdkanalyticssubscriber\/logevent(event:)","abstract":[{"type":"text","text":"Log an event."}],"role":"symbol","required":true,"title":"logEvent(event:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAnalyticsEvent","text":"SBSDKAnalyticsEvent"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logEventWithEvent:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber\/logEvent(event:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAnalyticsSubscriber":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber","kind":"symbol","role":"symbol","abstract":[{"text":"The subscriber that is being tracked.","type":"text"}],"title":"SBSDKAnalyticsSubscriber","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"url":"\/documentation\/scanbotsdk\/sbsdkanalyticssubscriber"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKAnalyticsSubscriber","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAnalyticsSubscriber\/logEvent(event:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"logEventWithEvent:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber~1logEvent(event:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logEventWithEvent:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber~1logEvent(event:)\/fragments"},{"op":"replace","value":"SBSDKAnalyticsSubscriber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/fragments"},{"op":"replace","value":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAnalyticsSubscriber\/navigatorTitle"}]}]}