{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"title":"SBSDKBarcodeFormatConfigurationBase","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatConfigurationBase","modules":[{"name":"ScanbotSDK"}],"symbolKind":"class","roleHeading":"Class","role":"symbol"},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/addAdditionalQuietZone","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/minimumSizeScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/regexFilter"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/toJson(configuration:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatAustraliaPostConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatAztecConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCodabarConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode11Configuration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode128Configuration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode2Of5Configuration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode39Configuration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode93Configuration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonFourStateConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonOneDConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonTwoDConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarExpandedConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarLimitedConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataMatrixConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatGs1CompositeConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatItfConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatJapanPostConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMaxiCodeConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMicroPdf417Configuration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMsiPlesseyConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPdf417Configuration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPharmaCodeConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPharmaCodeTwoTrackConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatQrCodeConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalMailConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalTntPostConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUpcEanConfiguration()","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUspsIntelligentMailConfiguration()"],"generated":true,"title":"Type Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKBarcodeFormatConfigurationBase) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Base class for all barcode configurations.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonTwoDConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCommonTwoDConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommontwodconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonTwoDConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration","title":"SBSDKBarcodeFormatCommonTwoDConfiguration","type":"topic","abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple 2D codes with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple 2D codes."}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}],"title":"SBSDKBarcodeFormatCommonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration","abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple barcode formats with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple barcodes."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatJapanPostConfiguration()":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatJapanPostConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatJapanPostConfiguration","text":"SBSDKBarcodeFormatJapanPostConfiguration","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatjapanpostconfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatJapanPostConfiguration()","abstract":[],"type":"topic","title":"barcodeFormatJapanPostConfiguration()","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatTwoDConfigurationBase":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase","abstract":[{"type":"text","text":"Base class for all 2D barcode configurations."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformattwodconfigurationbase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}],"role":"symbol","title":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatPharmaCodeConfiguration()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatpharmacodeconfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatPharmaCodeConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeConfiguration","text":"SBSDKBarcodeFormatPharmaCodeConfiguration","kind":"typeIdentifier"}],"title":"barcodeFormatPharmaCodeConfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPharmaCodeConfiguration()","kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/minimumSizeScore":{"title":"minimumSizeScore","abstract":[{"text":"Minimum acceptable value of a result BarcodeItem’s sizeScore (between 0 and 1).","type":"text"},{"text":" ","type":"text"},{"text":"Barcodes with a sizeScore less than this value will not be scanned.","type":"text"},{"text":" ","type":"text"},{"text":"When set to 0, barcodes are returned no matter what their size is.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/minimumSizeScore","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/minimumsizescore","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumSizeScore","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"minimumSizeScore"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase":{"navigatorTitle":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"abstract":[{"type":"text","text":"Base class for all barcode configurations."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase","title":"SBSDKBarcodeFormatConfigurationBase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatOneDConfigurationBase":{"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"title":"SBSDKBarcodeFormatOneDConfigurationBase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","kind":"symbol","abstract":[{"type":"text","text":"Base class for all linear (1D) barcode configurations."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatonedconfigurationbase","type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatAztecConfiguration()":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatAztecConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatAztecConfiguration","text":"SBSDKBarcodeFormatAztecConfiguration","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatAztecConfiguration()","title":"barcodeFormatAztecConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformataztecconfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatRoyalMailConfiguration()":{"abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatRoyalMailConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatRoyalMailConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatRoyalMailConfiguration","kind":"typeIdentifier"}],"title":"barcodeFormatRoyalMailConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatroyalmailconfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalMailConfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatUpcEanConfiguration()":{"abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatUpcEanConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatUpcEanConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatUpcEanConfiguration","kind":"typeIdentifier"}],"title":"barcodeFormatUpcEanConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatupceanconfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUpcEanConfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatGS1CompositeConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","abstract":[{"text":"GS1 Composite configuration. Add to scanner configuration to scan GS1 Composite barcodes.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatgs1compositeconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"title":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatMicroPdf417Configuration()":{"title":"barcodeFormatMicroPdf417Configuration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMicroPdf417Configuration()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatmicropdf417configuration()","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatMicroPdf417Configuration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatMicroPDF417Configuration","text":"SBSDKBarcodeFormatMicroPDF417Configuration","kind":"typeIdentifier"}],"abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","title":"Swift.Decodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/isEqual:":{"type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/isequal:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/isEqual:","title":"isEqual:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/addAdditionalQuietZone":{"role":"symbol","navigatorTitle":[{"text":"addAdditionalQuietZone","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/addAdditionalQuietZone","abstract":[{"type":"text","text":"If true, we process the barcode scanning with an artificial quiet zone that we add to the input image."},{"type":"text","text":" "},{"type":"text","text":"This flag should be used to scan sharp crops of a barcode in single-shot mode."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/addadditionalquietzone","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAdditionalQuietZone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"addAdditionalQuietZone"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatMsiPlesseyConfiguration()":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatmsiplesseyconfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMsiPlesseyConfiguration()","title":"barcodeFormatMsiPlesseyConfiguration()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatMsiPlesseyConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatMSIPlesseyConfiguration","text":"SBSDKBarcodeFormatMSIPlesseyConfiguration"}],"abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/SH":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatPharmaCodeTwoTrackConfiguration()":{"title":"barcodeFormatPharmaCodeTwoTrackConfiguration()","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatpharmacodetwotrackconfiguration()","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatPharmaCodeTwoTrackConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration","text":"SBSDKBarcodeFormatPharmaCodeTwoTrackConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPharmaCodeTwoTrackConfiguration()"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode2Of5Configuration()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode2Of5Configuration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatCode2Of5Configuration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode2Of5Configuration","text":"SBSDKBarcodeFormatCode2Of5Configuration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode2of5configuration()","title":"barcodeFormatCode2Of5Configuration()","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataBarExpandedConfiguration()":{"title":"barcodeFormatDataBarExpandedConfiguration()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarExpandedConfiguration()","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatDataBarExpandedConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatDataBarExpandedConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataBarExpandedConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatabarexpandedconfiguration()"},"doc://net.doo.ScanbotSDK/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode93Configuration()":{"title":"barcodeFormatCode93Configuration()","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatCode93Configuration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatCode93Configuration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode93Configuration"}],"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode93Configuration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode93configuration()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataBarConfiguration()":{"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatabarconfiguration()","title":"barcodeFormatDataBarConfiguration()","abstract":[],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatDataBarConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataBarConfiguration","text":"SBSDKBarcodeFormatDataBarConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase":{"type":"topic","title":"SBSDKBarcodeFormatFourStateConfigurationBase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase","abstract":[{"text":"Base class for all four-state barcode configurations.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatAustraliaPostConfiguration()":{"role":"symbol","title":"barcodeFormatAustraliaPostConfiguration()","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformataustraliapostconfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatAustraliaPostConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatAustraliaPostConfiguration","text":"SBSDKBarcodeFormatAustraliaPostConfiguration"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatAustraliaPostConfiguration()","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","type":"topic","title":"SBSDKBarcodeFormatCommonFourStateConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration","role":"symbol","abstract":[{"text":"Convenience configuration for enabling the scanning of multiple four-state barcode formats with a common configuration.","type":"text"},{"text":" ","type":"text"},{"text":"Add to scanner configuration to enable and configure the scanning of multiple four-state codes.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode11Configuration()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode11Configuration()","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatCode11Configuration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode11Configuration","text":"SBSDKBarcodeFormatCode11Configuration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode11configuration()","type":"topic","title":"barcodeFormatCode11Configuration()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatGs1CompositeConfiguration()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatGs1CompositeConfiguration()","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatGs1CompositeConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatGS1CompositeConfiguration","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"title":"barcodeFormatGs1CompositeConfiguration()","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatgs1compositeconfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatMaxiCodeConfiguration()":{"role":"symbol","title":"barcodeFormatMaxiCodeConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatMaxiCodeConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatMaxiCodeConfiguration","text":"SBSDKBarcodeFormatMaxiCodeConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatmaxicodeconfiguration()","kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatMaxiCodeConfiguration()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatItfConfiguration()":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatItfConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatITFConfiguration","text":"SBSDKBarcodeFormatITFConfiguration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatItfConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatitfconfiguration()","title":"barcodeFormatItfConfiguration()","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode39Configuration()":{"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCode39Configuration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatCode39Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode39Configuration"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode39configuration()","title":"barcodeFormatCode39Configuration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode39Configuration()","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataMatrixConfiguration()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataMatrixConfiguration()","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatamatrixconfiguration()","role":"symbol","title":"barcodeFormatDataMatrixConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatDataMatrixConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataMatrixConfiguration","text":"SBSDKBarcodeFormatDataMatrixConfiguration"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatQrCodeConfiguration()":{"kind":"symbol","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatqrcodeconfiguration()","title":"barcodeFormatQrCodeConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatQrCodeConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatQRCodeConfiguration","text":"SBSDKBarcodeFormatQRCodeConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatQrCodeConfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/fromJsonWithJson:":{"abstract":[],"kind":"symbol","role":"symbol","title":"fromJsonWithJson:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/fromjsonwithjson:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/fromJsonWithJson:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatPdf417Configuration()":{"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatpdf417configuration()","type":"topic","title":"barcodeFormatPdf417Configuration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatPdf417Configuration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatPdf417Configuration"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPDF417Configuration","kind":"typeIdentifier","text":"SBSDKBarcodeFormatPDF417Configuration"}]},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatRoyalTntPostConfiguration()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatroyaltntpostconfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatRoyalTntPostConfiguration()","type":"topic","title":"barcodeFormatRoyalTntPostConfiguration()","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatRoyalTntPostConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatRoyalTNTPostConfiguration","text":"SBSDKBarcodeFormatRoyalTNTPostConfiguration","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/hash":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/hash","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/hash","type":"topic","title":"hash","role":"symbol","fragments":[{"kind":"identifier","text":"hash"}],"abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCommonConfiguration()":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonConfiguration()","title":"barcodeFormatCommonConfiguration()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCommonConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonConfiguration","text":"SBSDKBarcodeFormatCommonConfiguration","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcommonconfiguration()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/toJson(configuration:)":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/tojson(configuration:)","type":"topic","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/toJson(configuration:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"toJson(configuration:)","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonOneDConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommononedconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"symbol","abstract":[{"text":"Convenience configuration for enabling the scanning of multiple linear (1D) barcode formats with a common configuration.","type":"text"},{"text":" ","type":"text"},{"text":"Add to scanner configuration to enable and configure the scanning of multiple linear (1D) barcode formats.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCodabarConfiguration()":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcodabarconfiguration()","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCodabarConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatCodabarConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCodabarConfiguration"}],"title":"barcodeFormatCodabarConfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCodabarConfiguration()","type":"topic","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/regexFilter":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"regexFilter","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/regexFilter","abstract":[{"type":"text","text":"Regular expression filter for barcode text. If the barcode text does not match the regular expression, it will not be scanned. The default is an empty string (setting is turned off)."}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/regexfilter","title":"regexFilter","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"regexFilter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/objc(cs)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://net.doo.ScanbotSDK/SE":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCommonFourStateConfiguration()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonFourStateConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcommonfourstateconfiguration()","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCommonFourStateConfiguration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonFourStateConfiguration"}],"kind":"symbol","title":"barcodeFormatCommonFourStateConfiguration()"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCode128Configuration()":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeFormatCode128Configuration","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SBSDKBarcodeFormatCode128Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCode128Configuration"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCode128Configuration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcode128configuration()","abstract":[],"title":"barcodeFormatCode128Configuration()","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatUspsIntelligentMailConfiguration()":{"title":"barcodeFormatUspsIntelligentMailConfiguration()","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatUspsIntelligentMailConfiguration()","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatuspsintelligentmailconfiguration()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatUspsIntelligentMailConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatUSPSIntelligentMailConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatUSPSIntelligentMailConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCommonOneDConfiguration()":{"title":"barcodeFormatCommonOneDConfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatCommonOneDConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatCommonOneDConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonOneDConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcommononedconfiguration()","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonOneDConfiguration()","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/copyWithZone:":{"abstract":[],"title":"copyWithZone:","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/copywithzone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatDataBarLimitedConfiguration()":{"title":"barcodeFormatDataBarLimitedConfiguration()","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatdatabarlimitedconfiguration()","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatDataBarLimitedConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatDataBarLimitedConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatDataBarLimitedConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatDataBarLimitedConfiguration()","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatConfigurationBase/barcodeFormatCommonTwoDConfiguration()":{"kind":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatconfigurationbase\/barcodeformatcommontwodconfiguration()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeFormatCommonTwoDConfiguration"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SBSDKBarcodeFormatCommonTwoDConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonTwoDConfiguration"}],"title":"barcodeFormatCommonTwoDConfiguration()","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/barcodeFormatCommonTwoDConfiguration()","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKBarcodeFormatConfigurationBase"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/addAdditionalQuietZone","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/hash","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/minimumSizeScore","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/regexFilter"],"generated":true},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/copyWithZone:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/isEqual:","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/toJson(configuration:)"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatConfigurationBase\/fromJsonWithJson:"],"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(cs)NSObject"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonOneDConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonTwoDConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatGS1CompositeConfiguration","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatTwoDConfigurationBase"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSCopying"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatCommonTwoDConfiguration"},{"value":[{"text":"SBSDKBarcodeFormatCommonTwoDConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonTwoDConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonTwoDConfiguration\/navigatorTitle"},{"value":"SBSDKBarcodeFormatCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/fragments"},{"value":[{"text":"SBSDKBarcodeFormatCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonConfiguration\/navigatorTitle"},{"value":"SBSDKBarcodeFormatTwoDConfigurationBase","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatTwoDConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/fragments"},{"value":[{"text":"SBSDKBarcodeFormatTwoDConfigurationBase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatTwoDConfigurationBase\/navigatorTitle"},{"value":"minimumSizeScore","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase~1minimumSizeScore\/title"},{"value":[{"text":"minimumSizeScore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase~1minimumSizeScore\/fragments"},{"value":"SBSDKBarcodeFormatConfigurationBase","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/fragments"},{"value":[{"text":"SBSDKBarcodeFormatConfigurationBase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase\/navigatorTitle"},{"value":"SBSDKBarcodeFormatOneDConfigurationBase","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/fragments"},{"value":[{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/navigatorTitle"},{"value":"SBSDKBarcodeFormatGS1CompositeConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/title"},{"value":[{"text":"SBSDKBarcodeFormatGS1CompositeConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatGS1CompositeConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatGS1CompositeConfiguration\/navigatorTitle"},{"value":"addAdditionalQuietZone","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase~1addAdditionalQuietZone\/title"},{"value":[{"kind":"identifier","text":"addAdditionalQuietZone"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase~1addAdditionalQuietZone\/fragments"},{"value":"SBSDKBarcodeFormatFourStateConfigurationBase","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/title"},{"value":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/navigatorTitle"},{"value":"SBSDKBarcodeFormatCommonFourStateConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/navigatorTitle"},{"value":"toJsonWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase~1toJson(configuration:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase~1toJson(configuration:)\/fragments"},{"value":"SBSDKBarcodeFormatCommonOneDConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/fragments","value":[{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonOneDConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatCommonOneDConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase~1regexFilter\/title","value":"regexFilter"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatConfigurationBase~1regexFilter\/fragments","value":[{"kind":"identifier","text":"regexFilter"}]}]}]}