{"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureAppIdMismatch","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureCorrupted","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureExpired","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureInactive","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureNotSet","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureServer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureVersion","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureWrongOs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/okay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/okayExpiringSoon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/trial"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/RawRepresentable-Implementations"]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"]}],"metadata":{"title":"SBSDKLicenseStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"role":"symbol","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"roleHeading":"Enumeration","externalID":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(SBSDKLicenseStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Status of the license plate scanner."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/okay":{"abstract":[{"type":"text","text":"License is valid and accepted."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okay"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusOkay"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/okay","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/okay","title":"SBSDKLicenseStatus.okay"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureNotSet":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureNotSet"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureNotSet","abstract":[{"text":"No license set. On platforms that support trial mode, it means that the SDK’s trial mode is over.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failurenotset","title":"SBSDKLicenseStatus.failureNotSet","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureNotSet"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureServer":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureServer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failureserver","role":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatusFailureServer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureServer","title":"SBSDKLicenseStatus.failureServer","abstract":[{"text":"No license active. The online license check failed.","type":"text"}]},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se"},"doc://net.doo.ScanbotSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Status of the license plate scanner.","type":"text"}],"navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"title":"SBSDKLicenseStatus","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureExpired":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureExpired","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKLicenseStatusFailureExpired","kind":"identifier"}],"abstract":[{"text":"No license active. The set license is valid but it has expired.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureExpired","title":"SBSDKLicenseStatus.failureExpired","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failureexpired"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/Equatable-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/equatable-implementations","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/okayExpiringSoon":{"abstract":[{"type":"text","text":"License is valid but will expire soon. Make sure to update your license before it expires to ensure uninterrupted function."}],"role":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatusOkayExpiringSoon","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/okayExpiringSoon","title":"SBSDKLicenseStatus.okayExpiringSoon","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"okayExpiringSoon"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/okayexpiringsoon"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureInactive":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureInactive","navigatorTitle":[{"text":"SBSDKLicenseStatusFailureInactive","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureInactive","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"No license active. The set license is not yet active."}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failureinactive","type":"topic","kind":"symbol","title":"SBSDKLicenseStatus.failureInactive"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureCorrupted":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureCorrupted","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureCorrupted","navigatorTitle":[{"text":"SBSDKLicenseStatusFailureCorrupted","kind":"identifier"}],"role":"symbol","type":"topic","title":"SBSDKLicenseStatus.failureCorrupted","kind":"symbol","abstract":[{"text":"No license active. The set license was unreadable or has an invalid format.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failurecorrupted"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureAppIdMismatch":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureAppIdMismatch","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatusFailureAppIdMismatch","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failureappidmismatch","title":"SBSDKLicenseStatus.failureAppIdMismatch","abstract":[{"type":"text","text":"No license active. The set license does not cover the current app’s bundle identifier."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureAppIdMismatch","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureWrongOs":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureWrongOs","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureWrongOs"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureWrongOs"}],"abstract":[{"text":"No license active. The set license does not cover the current operating system.","type":"text"}],"title":"SBSDKLicenseStatus.failureWrongOs","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failurewrongos","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/init(rawValue:)","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/init(rawvalue:)","abstract":[],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/trial":{"kind":"symbol","abstract":[{"text":"No license set yet. The SDK is in trial mode.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SBSDKLicenseStatusTrial","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trial","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/trial","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/trial","title":"SBSDKLicenseStatus.trial"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureVersion":{"type":"topic","abstract":[{"type":"text","text":"No license active. The set license does not cover the current SDK version."}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failureversion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureVersion"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureVersion","kind":"symbol","title":"SBSDKLicenseStatus.failureVersion","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureVersion"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKLicenseStatus","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureAppIdMismatch","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureCorrupted","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureExpired","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureInactive","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureNotSet","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureServer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureVersion","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureWrongOs","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/okay","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/okayExpiringSoon","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/trial"],"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKLicenseStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SBSDKLicenseStatusOkay","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1okay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusOkay"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1okay\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusFailureNotSet","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureNotSet\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureNotSet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureNotSet\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusFailureServer","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureServer\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseStatusFailureServer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureServer\/fragments"},{"op":"replace","value":"SBSDKLicenseStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/navigatorTitle"},{"op":"replace","value":"SBSDKLicenseStatusFailureExpired","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureExpired\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureExpired"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureExpired\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusOkayExpiringSoon","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1okayExpiringSoon\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusOkayExpiringSoon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1okayExpiringSoon\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusFailureInactive","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureInactive\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseStatusFailureInactive","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureInactive\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusFailureCorrupted","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureCorrupted\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureCorrupted"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureCorrupted\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusFailureAppIdMismatch","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureAppIdMismatch\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseStatusFailureAppIdMismatch","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureAppIdMismatch\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusFailureWrongOs","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureWrongOs\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseStatusFailureWrongOs","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureWrongOs\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusTrial","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1trial\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKLicenseStatusTrial"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1trial\/fragments"},{"op":"replace","value":"SBSDKLicenseStatusFailureVersion","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureVersion\/title"},{"op":"replace","value":[{"text":"SBSDKLicenseStatusFailureVersion","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureVersion\/fragments"}]}]}