{"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/issuingAuthority","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/metadata","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/nationality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/photo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/validFrom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/validUntil"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelCnPermanentResidentCardFront","kind":"identifier"}],"roleHeading":"Class","title":"SBSDKDocumentsModelCnPermanentResidentCardFront","navigatorTitle":[{"text":"SBSDKDocumentsModelCnPermanentResidentCardFront","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelCnPermanentResidentCardFront","modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"CnPermanentResidentCardFront"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelCnPermanentResidentCardFront","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://net.doo.ScanbotSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://net.doo.ScanbotSDK/objc(pl)NSObject":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/birthDate":{"kind":"symbol","abstract":[{"type":"text","text":"Date of Birth"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/birthdate","navigatorTitle":[{"kind":"identifier","text":"birthDate"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"birthDate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/birthDate","title":"birthDate","type":"topic"},"doc://net.doo.ScanbotSDK/s7CVarArgP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/metadata":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/metadata","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/metadata","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"title":"metadata","abstract":[{"text":"The child document of type “Metadata”.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKDocumentsModelMetadata","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelMetadata"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"abstract":[{"text":"Generic document.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","title":"SBSDKGenericDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/validUntil":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/validUntil","kind":"symbol","navigatorTitle":[{"text":"validUntil","kind":"identifier"}],"type":"topic","title":"validUntil","abstract":[{"text":"End date of the validity of the card","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/validuntil","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validUntil","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","title":"Swift.Hashable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/photo":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"photo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/photo","title":"photo","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/photo","abstract":[{"text":"Photo","type":"text"}],"navigatorTitle":[{"text":"photo","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentWrapper":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentwrapper","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"abstract":[{"type":"text","text":"Base class for strongly-typed "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"type":"text","text":" wrappers."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","title":"SBSDKGenericDocumentWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/issuingAuthority":{"abstract":[{"type":"text","text":"Authority issuing the card"}],"navigatorTitle":[{"text":"issuingAuthority","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/issuingauthority","title":"issuingAuthority","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingAuthority","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/issuingAuthority"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/validFrom":{"abstract":[{"text":"Start date of the validity of the card","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"validFrom","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/validFrom","type":"topic","title":"validFrom","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/validfrom","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validFrom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/initWithGenericDocument:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/initWithGenericDocument:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGenericDocument:"}],"type":"topic","title":"initWithGenericDocument:","navigatorTitle":[{"kind":"identifier","text":"initWithGenericDocument:"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/initwithgenericdocument:","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelCnPermanentResidentCardFront"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront","title":"SBSDKDocumentsModelCnPermanentResidentCardFront","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelCnPermanentResidentCardFront"}],"abstract":[{"text":"CnPermanentResidentCardFront","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/requiredDocumentType":{"abstract":[{"text":"The name of the wrapped document type.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"requiredDocumentType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/requireddocumenttype","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"requiredDocumentType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/requiredDocumentType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/nationality":{"title":"nationality","navigatorTitle":[{"text":"nationality","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Nationality","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nationality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/nationality","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/nationality"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/gender":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/gender","navigatorTitle":[{"kind":"identifier","text":"gender"}],"abstract":[{"type":"text","text":"Gender"}],"kind":"symbol","title":"gender","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/gender","type":"topic"},"doc://net.doo.ScanbotSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/givenNames":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/givennames","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/givenNames","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenNames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"givenNames","type":"topic","navigatorTitle":[{"kind":"identifier","text":"givenNames"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Given Names","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelCnPermanentResidentCardFront/id":{"abstract":[{"text":"Identity Document Number","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/id","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentField","kind":"typeIdentifier","text":"SBSDKGenericDocumentField"},{"kind":"text","text":"?"}],"title":"id","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"id"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelcnpermanentresidentcardfront\/id"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKDocumentsModelCnPermanentResidentCardFront","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKDocumentsModelCnPermanentResidentCardFront","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKDocumentsModelCnPermanentResidentCardFront","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/birthDate","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/gender","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/givenNames","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/id","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/issuingAuthority","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/metadata","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/nationality","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/photo","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/requiredDocumentType","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/validFrom","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/validUntil"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelCnPermanentResidentCardFront\/initWithGenericDocument:"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelCnPermanentResidentCardFront"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentWrapper","kind":"typeIdentifier","text":"SBSDKGenericDocumentWrapper","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentWrapper"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"birthDate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1birthDate\/title"},{"value":[{"text":"birthDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1birthDate\/fragments"},{"value":"metadata","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1metadata\/title"},{"value":[{"text":"metadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1metadata\/fragments"},{"value":"SBSDKGenericDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title"},{"value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle"},{"value":"validUntil","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1validUntil\/title"},{"value":[{"text":"validUntil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1validUntil\/fragments"},{"value":"photo","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1photo\/title"},{"value":[{"text":"photo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1photo\/fragments"},{"value":"SBSDKGenericDocumentWrapper","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/title"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentWrapper"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/fragments"},{"value":[{"text":"SBSDKGenericDocumentWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentWrapper\/navigatorTitle"},{"value":"issuingAuthority","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1issuingAuthority\/title"},{"value":[{"text":"issuingAuthority","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1issuingAuthority\/fragments"},{"value":"validFrom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1validFrom\/title"},{"value":[{"kind":"identifier","text":"validFrom"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1validFrom\/fragments"},{"value":"SBSDKDocumentsModelCnPermanentResidentCardFront","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelCnPermanentResidentCardFront"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront\/fragments"},{"value":[{"text":"SBSDKDocumentsModelCnPermanentResidentCardFront","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront\/navigatorTitle"},{"value":"requiredDocumentType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1requiredDocumentType\/title"},{"value":[{"text":"requiredDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1requiredDocumentType\/fragments"},{"value":"nationality","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1nationality\/title"},{"value":[{"kind":"identifier","text":"nationality"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1nationality\/fragments"},{"value":"gender","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1gender\/title"},{"value":[{"text":"gender","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1gender\/fragments"},{"value":"givenNames","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1givenNames\/title"},{"value":[{"kind":"identifier","text":"givenNames"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1givenNames\/fragments"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1id\/title"},{"value":[{"text":"id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelCnPermanentResidentCardFront~1id\/fragments"}]}]}