{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Image serialization mode. Applicable only when serializeImages is true."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/buffer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/reference"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/Equatable-Implementations","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","doc:\/\/net.doo.ScanbotSDK\/Se","doc:\/\/net.doo.ScanbotSDK\/SE","doc:\/\/net.doo.ScanbotSDK\/SQ","doc:\/\/net.doo.ScanbotSDK\/SH","doc:\/\/net.doo.ScanbotSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimageserializationmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimageserializationmode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(SBSDKImageSerializationMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKImageSerializationMode","title":"SBSDKImageSerializationMode","modules":[{"name":"ScanbotSDK"}],"symbolKind":"enum"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSerializationMode/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkimageserializationmode\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic","kind":"article","title":"RawRepresentable Implementations"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSerializationMode/reference":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reference"}],"role":"symbol","title":"SBSDKImageSerializationMode.reference","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimageserializationmode\/reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/reference","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationModeReference"}],"abstract":[{"text":"Images are serialized as references to native resources.","type":"text"}]},"doc://net.doo.ScanbotSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SY","title":"Swift.RawRepresentable"},"doc://net.doo.ScanbotSDK/s12CaseIterableP":{"title":"Swift.CaseIterable","identifier":"doc:\/\/net.doo.ScanbotSDK\/s12CaseIterableP","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSerializationMode":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode","title":"SBSDKImageSerializationMode","url":"\/documentation\/scanbotsdk\/sbsdkimageserializationmode","abstract":[{"type":"text","text":"Image serialization mode. Applicable only when serializeImages is true."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageSerializationMode"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSerializationMode/Equatable-Implementations":{"kind":"article","url":"\/documentation\/scanbotsdk\/sbsdkimageserializationmode\/equatable-implementations","abstract":[],"title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/Equatable-Implementations","role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SE","type":"unresolvable"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSerializationMode/buffer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/buffer","role":"symbol","type":"topic","abstract":[{"text":"Images are serialized as base64 encoded buffers.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageserializationmode\/buffer","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buffer","kind":"identifier"}],"title":"SBSDKImageSerializationMode.buffer","kind":"symbol","navigatorTitle":[{"text":"SBSDKImageSerializationModeBuffer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSerializationMode/init(rawValue:)":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimageserializationmode\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/net.doo.ScanbotSDK\/Se","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SH","type":"unresolvable"},"doc://net.doo.ScanbotSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/net.doo.ScanbotSDK\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKImageSerializationMode","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/buffer","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSerializationMode\/reference"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageSerializationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKImageSerializationModeReference","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode~1reference\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode~1reference\/fragments","value":[{"kind":"identifier","text":"SBSDKImageSerializationModeReference"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode\/title","value":"SBSDKImageSerializationMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode\/fragments","value":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode\/navigatorTitle","value":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode~1buffer\/title","value":"SBSDKImageSerializationModeBuffer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSerializationMode~1buffer\/fragments","value":[{"kind":"identifier","text":"SBSDKImageSerializationModeBuffer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}