{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKBarcodeFormatOneDConfigurationBase","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatOneDConfigurationBase","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"title":"fromJsonWithJson:","roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatOneDConfigurationBase(cm)fromJsonWithJson:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatonedconfigurationbase\/fromjsonwithjson:"]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase\/fromJsonWithJson:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatOneDConfigurationBase":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase","kind":"symbol","title":"SBSDKBarcodeFormatOneDConfigurationBase","abstract":[{"type":"text","text":"Base class for all linear (1D) barcode configurations."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatonedconfigurationbase","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatOneDConfigurationBase/fromJsonWithJson:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatOneDConfigurationBase\/fromJsonWithJson:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatonedconfigurationbase\/fromjsonwithjson:","title":"fromJsonWithJson:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/title","value":"SBSDKBarcodeFormatOneDConfigurationBase","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatOneDConfigurationBase\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatOneDConfigurationBase"}],"op":"replace"}]}]}