{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAnalysisMode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier","text":"SBSDKUI2DocumentAnalysisMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2DocumentAnalysisMode"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Default is UNFILTERED_DOCUMENT","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"documentAnalysisMode","navigatorTitle":[{"text":"documentAnalysisMode","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAnalysisMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier","text":"SBSDKUI2DocumentAnalysisMode"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentScannerOutputSettings(py)documentAnalysisMode"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/documentanalysismode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/documentanalysismode"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode"},"abstract":[{"type":"text","text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings/documentAnalysisMode":{"navigatorTitle":[{"text":"documentAnalysisMode","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAnalysisMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2DocumentAnalysisMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2DocumentAnalysisMode","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image."}],"title":"documentAnalysisMode","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings\/documentanalysismode","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings\/documentAnalysisMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentAnalysisMode":{"abstract":[{"text":"Determines if the quality analysis for the acknowledgement mode will run on the filtered or the unfiltered image.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"type":"topic","title":"SBSDKUI2DocumentAnalysisMode","url":"\/documentation\/scanbotsdk\/sbsdkui2documentanalysismode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentAnalysisMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerOutputSettings":{"title":"SBSDKUI2DocumentScannerOutputSettings","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerOutputSettings","abstract":[{"type":"text","text":"Configuration of the output settings."}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscanneroutputsettings"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"documentAnalysisMode","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"documentAnalysisMode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentAnalysisMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKUI2DocumentAnalysisMode","text":"SBSDKUI2DocumentAnalysisMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAnalysisMode"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"documentAnalysisMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentAnalysisMode\/title"},{"value":[{"text":"documentAnalysisMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings~1documentAnalysisMode\/fragments"},{"value":"SBSDKUI2DocumentAnalysisMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentAnalysisMode\/title","op":"replace"},{"value":[{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentAnalysisMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentAnalysisMode\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentAnalysisMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/title","value":"SBSDKUI2DocumentScannerOutputSettings"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerOutputSettings"}]},{"op":"replace","value":[{"text":"SBSDKUI2DocumentScannerOutputSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerOutputSettings\/navigatorTitle"}]}]}