{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/init(pagesize:pagefitmode:pageorientation:dpi:resample:jpegquality:ocrconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/init(pagesize:pagefitmode:pageorientation:dpi:resample:jpegquality:ocrconfiguration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions(im)initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:","navigatorTitle":[{"text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:","kind":"identifier"}],"symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"pageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageFitMode"},{"kind":"text","text":": "},{"text":"SBSDKPDFRendererPageFitMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"pageOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation"},{"text":", ","kind":"text"},{"text":"dpi","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resample"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"jpegQuality","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ocrConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:)","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pageSize"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","text":"SBSDKPDFRendererPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"pageFitMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","text":"SBSDKPDFRendererPageFitMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageOrientation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation","kind":"typeIdentifier","text":"SBSDKPDFRendererPageOrientation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dpi"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resample"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"jpegQuality","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ocrConfiguration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier","text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The page size for each PDF page.","type":"text"}],"type":"paragraph"}],"name":"pageSize"},{"name":"pageOrientation","content":[{"type":"paragraph","inlineContent":[{"text":"The page orientation for each PDF page.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the OCR engine for the HOCR processing. Set to "},{"type":"codeVoice","code":"nil"},{"text":" if you do not want to perform HOCR.","type":"text"}]}],"name":"ocrConfiguration"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Designated initializer.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}],"abstract":[{"text":"An enum describing the mode of how images are fitted into a PDF page.","type":"text"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"type":"topic","title":"SBSDKPDFRendererPageFitMode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOpticalCharacterRecognizerConfiguration":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","title":"SBSDKOpticalCharacterRecognizerConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOpticalCharacterRecognizerConfiguration"}],"abstract":[{"text":"A class describing the configuration of the optical character recognizer (OCR).","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkopticalcharacterrecognizerconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize","abstract":[{"text":"Specifies the desired page size (media box size) for PDF rendering operations.","type":"text"}],"title":"SBSDKPDFRendererPageSize"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"abstract":[{"type":"text","text":"A class to describe the options being passed to PDF rendering API."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","kind":"symbol","title":"SBSDKPDFRendererOptions","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageOrientation":{"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpageorientation","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"abstract":[{"text":"An enum describing the orientation of the pages when rendering a PDF document.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageOrientation"}],"title":"SBSDKPDFRendererPageOrientation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:)":{"abstract":[{"type":"text","text":"Designated initializer."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/init(pagesize:pagefitmode:pageorientation:dpi:resample:jpegquality:ocrconfiguration:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize","text":"SBSDKPDFRendererPageSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageFitMode"},{"kind":"text","text":": "},{"text":"SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageOrientation"},{"kind":"text","text":": "},{"text":"SBSDKPDFRendererPageOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dpi"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":", "},{"text":"resample","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"jpegQuality","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"ocrConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration"},{"kind":"text","text":"?)"}],"kind":"symbol","navigatorTitle":[{"text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:)","title":"init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPageSize:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","kind":"typeIdentifier","text":"SBSDKPDFRendererPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"pageSize"},{"text":" ","kind":"text"},{"text":"pageFitMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","text":"SBSDKPDFRendererPageFitMode"},{"kind":"text","text":") "},{"text":"pageFitMode","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageOrientation:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageOrientation","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageOrientation","kind":"typeIdentifier","text":"SBSDKPDFRendererPageOrientation"},{"kind":"text","text":") "},{"text":"pageOrientation","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dpi:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"dpi","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"resample:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"resample"},{"kind":"text","text":" "},{"text":"jpegQuality:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"jpegQuality"},{"kind":"text","text":" "},{"text":"ocrConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOpticalCharacterRecognizerConfiguration","text":"SBSDKOpticalCharacterRecognizerConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKOpticalCharacterRecognizerConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"ocrConfiguration","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/title","value":"SBSDKPDFRendererPageFitMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}],"op":"replace"},{"value":"SBSDKOpticalCharacterRecognizerConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKOpticalCharacterRecognizerConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOpticalCharacterRecognizerConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/title","value":"SBSDKPDFRendererPageSize","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/fragments","op":"replace","value":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}]},{"value":"SBSDKPDFRendererOptions","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments"},{"value":"SBSDKPDFRendererPageOrientation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageOrientation\/fragments","op":"replace","value":[{"text":"SBSDKPDFRendererPageOrientation","kind":"identifier"}]},{"op":"replace","value":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1init(pageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPageSize:pageFitMode:pageOrientation:dpi:resample:jpegQuality:ocrConfiguration:","kind":"identifier"}]}]}]}