{"metadata":{"navigatorTitle":[{"text":"pageSize","kind":"identifier"}],"title":"pageSize","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions(py)pageSize","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize"},{"kind":"text","text":": "},{"text":"SBSDKPDFRendererPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagesize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagesize"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize","text":"SBSDKPDFRendererPageSize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","type":"reference","isActive":true},{"type":"text","text":"."}]},{"name":"Warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Has no effect, if the ocrConfiguration is set to use the legacy OCR engine."}]}],"style":"warning"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions"]]},"sections":[],"abstract":[{"text":"The physical size of the page. If ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","type":"reference","isActive":true},{"type":"text","text":", the page size will be set as the image size at given"},{"type":"text","text":" "},{"text":"dpi.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize","title":"SBSDKPDFRendererPageSize","role":"symbol","abstract":[{"text":"Specifies the desired page size (media box size) for PDF rendering operations.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/custom":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"title":"SBSDKPDFRendererPageSize.custom","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeCustom"}],"kind":"symbol","abstract":[{"text":"Each page is as large as its image at 72 dpi.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/custom","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"title":"SBSDKPDFRendererOptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"kind":"symbol","abstract":[{"type":"text","text":"A class to describe the options being passed to PDF rendering API."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pageSize":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKPDFRendererPageSize","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"}],"title":"pageSize","navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"kind":"symbol","abstract":[{"type":"text","text":"The physical size of the page. If "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","isActive":true,"type":"reference"},{"text":", the page size will be set as the image size at given","type":"text"},{"type":"text","text":" "},{"text":"dpi.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagesize","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"pageSize","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"pageSize","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKPDFRendererPageSize","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKPDFRendererPageSize","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize\/fragments","value":[{"text":"SBSDKPDFRendererPageSize","kind":"identifier"}],"op":"replace"},{"value":"SBSDKPDFRendererPageSizeCustom","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1custom\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageSizeCustom"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1custom\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title","value":"SBSDKPDFRendererOptions"},{"value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageSize\/title","value":"pageSize"},{"value":[{"text":"pageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageSize\/fragments","op":"replace"}]}]}