{"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagefitmode"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagefitmode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageFitMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","text":"SBSDKPDFRendererPageFitMode","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions(py)pageFitMode","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"pageFitMode","kind":"identifier"}],"title":"pageFitMode"},"abstract":[{"text":"How to fit the image into the page. Only used if ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","type":"reference"},{"type":"text","text":" is not "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The image can either be stretched to fill the page,","type":"text"},{"type":"text","text":" "},{"text":"in one of three ways, or centered on the page without stretching.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pageFitMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fitIn"},{"type":"text","text":"."}]},{"style":"warning","name":"Warning","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Has no effect, if the ocrConfiguration is set to use the legacy OCR engine."}],"type":"paragraph"}]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/fitIn":{"title":"SBSDKPDFRendererPageFitMode.fitIn","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/fitin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fitIn","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeFitIn"}],"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/fitIn"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","abstract":[{"text":"A class to describe the options being passed to PDF rendering API.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKPDFRendererOptions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pageSize":{"navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagesize","abstract":[{"text":"The physical size of the page. If ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","isActive":true,"type":"reference"},{"text":", the page size will be set as the image size at given","type":"text"},{"type":"text","text":" "},{"type":"text","text":"dpi."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageSize"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","title":"pageSize","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pageFitMode":{"title":"pageFitMode","navigatorTitle":[{"text":"pageFitMode","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagefitmode","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pageFitMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","text":"SBSDKPDFRendererPageFitMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","abstract":[{"text":"How to fit the image into the page. Only used if ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","type":"reference","isActive":true},{"type":"text","text":" is not "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","type":"reference","isActive":true},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The image can either be stretched to fill the page,"},{"text":" ","type":"text"},{"text":"in one of three ways, or centered on the page without stretching.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode":{"abstract":[{"type":"text","text":"An enum describing the mode of how images are fitted into a PDF page."}],"title":"SBSDKPDFRendererPageFitMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKPDFRendererPageFitMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/custom":{"navigatorTitle":[{"text":"SBSDKPDFRendererPageSizeCustom","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/custom","abstract":[{"text":"Each page is as large as its image at 72 dpi.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","title":"SBSDKPDFRendererPageSize.custom","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"pageFitMode","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"pageFitMode"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode","text":"SBSDKPDFRendererPageFitMode","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"pageFitMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1fitIn\/title","op":"replace","value":"SBSDKPDFRendererPageFitModeFitIn"},{"value":[{"text":"SBSDKPDFRendererPageFitModeFitIn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1fitIn\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title","value":"SBSDKPDFRendererOptions"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageSize\/title","value":"pageSize","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageSize\/fragments","op":"replace","value":[{"text":"pageSize","kind":"identifier"}]},{"value":"pageFitMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageFitMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageFitMode\/fragments","op":"replace","value":[{"text":"pageFitMode","kind":"identifier"}]},{"value":"SBSDKPDFRendererPageFitMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitMode"}]},{"value":"SBSDKPDFRendererPageSizeCustom","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1custom\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1custom\/fragments","value":[{"text":"SBSDKPDFRendererPageSizeCustom","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}