{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The PDF metadata attributes like title, author, creator, keywords etc.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdfAttributes"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","text":"SBSDKPDFAttributes","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]},{"style":"warning","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Has no effect, if the ocrConfiguration is set to use the legacy OCR engine."}]}],"type":"aside"}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pdfattributes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pdfattributes"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pdfAttributes"},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pdfAttributes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPDFAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes"},{"kind":"text","text":"?"}],"modules":[{"name":"ScanbotSDK"}],"title":"pdfAttributes","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions(py)pdfAttributes","navigatorTitle":[{"text":"pdfAttributes","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pdfAttributes":{"type":"topic","abstract":[{"type":"text","text":"The PDF metadata attributes like title, author, creator, keywords etc."}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pdfattributes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pdfAttributes","title":"pdfAttributes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pdfAttributes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes","text":"SBSDKPDFAttributes"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"pdfAttributes"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"abstract":[{"type":"text","text":"A class to describe the options being passed to PDF rendering API."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","title":"SBSDKPDFRendererOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFAttributes":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKPDFAttributes","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Represents the metadata attributes of PDF files, e.g. author, creator, title etc.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfattributes","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFAttributes"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","title":"SBSDKPDFAttributes"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"pdfAttributes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"pdfAttributes","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"SBSDKPDFAttributes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFAttributes","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFAttributes"},{"text":" * ","kind":"text"},{"text":"pdfAttributes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pdfAttributes\/title","value":"pdfAttributes"},{"value":[{"text":"pdfAttributes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pdfAttributes\/fragments"},{"value":"SBSDKPDFRendererOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments","op":"replace","value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/navigatorTitle","value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}]},{"value":"SBSDKPDFAttributes","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFAttributes"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFAttributes\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPDFAttributes","kind":"identifier"}]}]}]}