{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/resample"},"abstract":[{"text":"If set to ","type":"text"},{"code":"True","type":"codeVoice"},{"text":" downscales the images to match the ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","isActive":true},{"text":" setting before adding it to the PDF if","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the calculated image DPI after stretching is greater than "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","isActive":true},{"text":". This slows down the PDF generation but results in smaller PDFs.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"resample","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"False"},{"type":"text","text":" the images will not be scaled before rendering them to the PDF. Faster, but usually results in larger PDFs."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"code":"False","type":"codeVoice"},{"type":"text","text":"."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Has no effect, if the ocrConfiguration is set to use the legacy OCR engine."}]}],"name":"Warning","style":"warning","type":"aside"}]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions(py)resample","title":"resample","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resample","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"resample","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/resample"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/resample"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pageFitMode":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pageFitMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageFitMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageFitMode","kind":"typeIdentifier"}],"abstract":[{"text":"How to fit the image into the page. Only used if ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize"},{"text":" is not ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","isActive":true},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The image can either be stretched to fill the page,"},{"type":"text","text":" "},{"text":"in one of three ways, or centered on the page without stretching.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagefitmode","navigatorTitle":[{"text":"pageFitMode","kind":"identifier"}],"kind":"symbol","type":"topic","title":"pageFitMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageFitMode/none":{"navigatorTitle":[{"text":"SBSDKPDFRendererPageFitModeNone","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagefitmode\/none","title":"SBSDKPDFRendererPageFitMode.none","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererPageSize/custom":{"title":"SBSDKPDFRendererPageSize.custom","navigatorTitle":[{"text":"SBSDKPDFRendererPageSizeCustom","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Each page is as large as its image at 72 dpi."}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendererpagesize\/custom","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"custom"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/pageSize":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/pagesize","abstract":[{"type":"text","text":"The physical size of the page. If "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom"},{"type":"text","text":", the page size will be set as the image size at given"},{"text":" ","type":"text"},{"text":"dpi.","type":"text"}],"type":"topic","title":"pageSize","navigatorTitle":[{"kind":"identifier","text":"pageSize"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererPageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPDFRendererPageSize"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"abstract":[{"type":"text","text":"A class to describe the options being passed to PDF rendering API."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","title":"SBSDKPDFRendererOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/dpi":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/dpi","navigatorTitle":[{"kind":"identifier","text":"dpi"}],"abstract":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","isActive":true},{"text":" parameter has two different meanings depending on the value of ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","isActive":true,"type":"reference"},{"text":" and","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode","isActive":true},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageSize","isActive":true},{"type":"text","text":" is set to "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageSize\/custom","isActive":true},{"text":"or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/pageFitMode"},{"text":" is set to ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererPageFitMode\/none","isActive":true},{"type":"text","text":","},{"text":" ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","isActive":true,"type":"reference"},{"type":"text","text":" is the conversion ratio used to convert from units of pixels to physical inches when adding images to the PDF."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","title":"dpi","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dpi"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions/resample":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions\/resample","navigatorTitle":[{"text":"resample","kind":"identifier"}],"abstract":[{"text":"If set to ","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":" downscales the images to match the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi","isActive":true},{"text":" setting before adding it to the PDF if","type":"text"},{"text":" ","type":"text"},{"text":"the calculated image DPI after stretching is greater than ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/dpi"},{"type":"text","text":". This slows down the PDF generation but results in smaller PDFs."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions\/resample","title":"resample","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resample"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"resample","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"resample","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"resample","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageFitMode\/title","value":"pageFitMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageFitMode\/fragments","value":[{"text":"pageFitMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SBSDKPDFRendererPageFitModeNone","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1none\/title"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererPageFitModeNone"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageFitMode~1none\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1custom\/title","value":"SBSDKPDFRendererPageSizeCustom"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererPageSize~1custom\/fragments","value":[{"text":"SBSDKPDFRendererPageSizeCustom","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageSize\/title","value":"pageSize"},{"value":[{"text":"pageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1pageSize\/fragments"},{"value":"SBSDKPDFRendererOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/navigatorTitle","value":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"op":"replace"},{"value":"dpi","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1dpi\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1dpi\/fragments","op":"replace","value":[{"text":"dpi","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1resample\/title","value":"resample","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions~1resample\/fragments","op":"replace","value":[{"kind":"identifier","text":"resample"}]}]}]}