{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/isEqual:"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPathImageLoadOptions(im)isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","title":"isEqual:"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/isequal:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions","navigatorTitle":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"abstract":[{"text":"Options for loading image from path.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions","role":"symbol","title":"SBSDKPathImageLoadOptions"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","title":"ScanbotDocumentScannerSDK","role":"collection","abstract":[{"type":"text","text":"Version: 7.1.2"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPathImageLoadOptions/isEqual:":{"title":"isEqual:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPathImageLoadOptions\/isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpathimageloadoptions\/isequal:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/title","value":"SBSDKPathImageLoadOptions"},{"value":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPathImageLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}]}]}]}