{"metadata":{"navigatorTitle":[{"text":"initWithFormats:extractedDocumentFormats:","kind":"identifier"}],"title":"init(formats:extractedDocumentFormats:)","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"formats"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"extractedDocumentFormats","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKBarcodeDocumentFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentFormat"},{"text":"])","kind":"text"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScanner(im)initWithFormats:extractedDocumentFormats:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/init(formats:extractedDocumentFormats:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithFormats:extractedDocumentFormats:) ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"formats"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormat"},{"text":"], ","kind":"text"},{"text":"extractedDocumentFormats","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKBarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentFormat","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentFormat","kind":"typeIdentifier"},{"kind":"text","text":"] = [])"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/init(formats:extracteddocumentformats:)"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/init(formats:extracteddocumentformats:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner"]]},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeDocumentFormat":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodedocumentformat","title":"SBSDKBarcodeDocumentFormat","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeDocumentFormat","role":"symbol","abstract":[{"text":"Type of barcode document format used.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner":{"role":"symbol","title":"SBSDKBarcodeScanner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScanner"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner","navigatorTitle":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}],"type":"topic","abstract":[{"text":"A class to scan most types of barcodes and QR codes, data matrices etc. on various image sources.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScanner/init(formats:extractedDocumentFormats:)":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScanner\/init(formats:extractedDocumentFormats:)","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescanner\/init(formats:extracteddocumentformats:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFormats:extractedDocumentFormats:"}],"abstract":[],"title":"init(formats:extractedDocumentFormats:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"formats"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat"},{"kind":"text","text":"], "},{"text":"extractedDocumentFormats","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKBarcodeDocumentFormat","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeDocumentFormat","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeFormat":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeFormat","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"kind":"symbol","title":"SBSDKBarcodeFormat","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodeformat","abstract":[{"type":"text","text":"Enumerates barcode formats."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormat","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithFormats:extractedDocumentFormats:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFormats:extractedDocumentFormats:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFormats:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKBarcodeFormat *>"},{"text":" *) ","kind":"text"},{"text":"formats","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"extractedDocumentFormats:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKBarcodeDocumentFormat *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"extractedDocumentFormats"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentFormat\/title","value":"SBSDKBarcodeDocumentFormat"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentFormat\/fragments","value":[{"text":"SBSDKBarcodeDocumentFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeDocumentFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentFormat"}],"op":"replace"},{"value":"SBSDKBarcodeScanner","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/fragments","value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner\/navigatorTitle","value":[{"text":"SBSDKBarcodeScanner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1init(formats:extractedDocumentFormats:)\/title","value":"initWithFormats:extractedDocumentFormats:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFormats:extractedDocumentFormats:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScanner~1init(formats:extractedDocumentFormats:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormat\/title","value":"SBSDKBarcodeFormat","op":"replace"},{"value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeFormat\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"op":"replace"}]}]}