{"abstract":[{"text":"90 degrees counterclockwise rotation.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotationCounterclockwise90"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"counterclockwise90"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageRotation@SBSDKImageRotationCounterclockwise90","symbolKind":"case","role":"symbol","roleHeading":"Case","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"SBSDKImageRotation.counterclockwise90"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"counterclockwise90"}]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation\/counterclockwise90"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerotation\/counterclockwise90"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerotation\/counterclockwise90"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRotation/counterclockwise90":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerotation\/counterclockwise90","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation\/counterclockwise90","type":"topic","title":"SBSDKImageRotation.counterclockwise90","abstract":[{"type":"text","text":"90 degrees counterclockwise rotation."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"counterclockwise90"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageRotationCounterclockwise90"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageRotation":{"type":"topic","abstract":[{"type":"text","text":"Image rotation."}],"title":"SBSDKImageRotation","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimagerotation","navigatorTitle":[{"text":"SBSDKImageRotation","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRotation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageRotation","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKImageRotationCounterclockwise90","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKImageRotationCounterclockwise90","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKImageRotationCounterclockwise90","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation~1counterclockwise90\/title","value":"SBSDKImageRotationCounterclockwise90","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation~1counterclockwise90\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRotationCounterclockwise90"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/title","value":"SBSDKImageRotation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/fragments","value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageRotation\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKImageRotation"}],"op":"replace"}]}]}