{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError"]]},"metadata":{"roleHeading":"Instance Method","title":"copyWithZone:","symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKDeviceDeregistrationError(im)copyWithZone:","modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError\/copyWithZone:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceDeregistrationError/copyWithZone:":{"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror\/copywithzone:","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError\/copyWithZone:","type":"topic","title":"copyWithZone:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceDeregistrationError":{"abstract":[{"text":"Description of error that occurred during device deregistration.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror","title":"SBSDKDeviceDeregistrationError","navigatorTitle":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError"}},"variantOverrides":[{"patch":[{"value":"SBSDKDeviceDeregistrationError","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/title"},{"value":[{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/fragments"},{"value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}