{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError\/initWithDeviceId:errorMessage:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDeviceId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"deviceId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"errorMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"errorMessage","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","title":"initWithDeviceId:errorMessage:","navigatorTitle":[{"text":"initWithDeviceId:errorMessage:","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDeviceId:errorMessage:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKDeviceDeregistrationError(im)initWithDeviceId:errorMessage:","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror\/initwithdeviceid:errormessage:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceDeregistrationError/initWithDeviceId:errorMessage:":{"title":"initWithDeviceId:errorMessage:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror\/initwithdeviceid:errormessage:","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError\/initWithDeviceId:errorMessage:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDeviceId:errorMessage:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDeviceId:errorMessage:"}],"abstract":[],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceDeregistrationError":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror","role":"symbol","abstract":[{"type":"text","text":"Description of error that occurred during device deregistration."}],"title":"SBSDKDeviceDeregistrationError","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/title","value":"SBSDKDeviceDeregistrationError"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/fragments","value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/navigatorTitle","value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}]}]}]}