{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError\/toJson(configuration:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":" = SBSDKToJSONConfiguration()) -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKDeviceDeregistrationError(im)toJsonWithConfiguration:","roleHeading":"Instance Method","title":"toJson(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror\/tojson(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror\/tojson(configuration:)"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKToJSONConfiguration":{"title":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdktojsonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration used to serialize an object to json."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceDeregistrationError":{"abstract":[{"text":"Description of error that occurred during device deregistration.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror","title":"SBSDKDeviceDeregistrationError","navigatorTitle":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKDeviceDeregistrationError/toJson(configuration:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}],"title":"toJson(configuration:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKDeviceDeregistrationError\/toJson(configuration:)","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkdevicederegistrationerror\/tojson(configuration:)","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKToJSONConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKToJSONConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKToJSONConfiguration\/navigatorTitle","op":"replace"},{"value":"SBSDKDeviceDeregistrationError","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDeviceDeregistrationError"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/fragments","op":"replace"},{"value":[{"text":"SBSDKDeviceDeregistrationError","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError\/navigatorTitle","op":"replace"},{"value":"toJsonWithConfiguration:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError~1toJson(configuration:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKDeviceDeregistrationError~1toJson(configuration:)\/fragments","op":"replace"}]}]}