{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/sbsdkimageeditingviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewController(_:didDetectPolygon:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidFail(_:with:)"],"generated":true,"anchor":"Instance-Methods"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/SBSDKImageEditingViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"collectionGroup","title":"SBSDKImageEditingViewControllerDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"ScanbotSDK"}]},"kind":"article","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/imageEditingViewControllerDidFail(_:with:)":{"title":"imageEditingViewControllerDidFail(_:with:)","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidfail(_:with:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidFail(_:with:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEditingViewControllerDidFail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageEditingViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Informs the delegate that the image editing view controller failed with an error."}],"navigatorTitle":[{"text":"imageEditingViewControllerDidFail:with:","kind":"identifier"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/imageEditingViewControllerDidChangePolygon(_:)":{"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontrollerdidchangepolygon(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controllers polygon was changed by user interaction."}],"title":"imageEditingViewControllerDidChangePolygon(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController":{"navigatorTitle":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}],"title":"SBSDKUI2CroppingViewController","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController","role":"symbol","kind":"symbol","abstract":[{"text":"A highly customizable view controller to edit the page polygon or the page orientation.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingViewController/imageEditingViewController(_:didDetectPolygon:)":{"title":"imageEditingViewController(_:didDetectPolygon:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewController(_:didDetectPolygon:)","abstract":[{"type":"text","text":"Informs the delegate that the image editing view controller detected a polygon."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageEditingViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageEditingViewController","text":"SBSDKImageEditingViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectPolygon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon","text":"SBSDKPolygon"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingviewcontroller\/imageeditingviewcontroller(_:diddetectpolygon:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageEditingViewController:didDetectPolygon:"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewController(_:didDetectPolygon:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidChangePolygon(_:)","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingViewController\/imageEditingViewControllerDidFail(_:with:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidFail(_:with:)\/title","op":"replace","value":"imageEditingViewControllerDidFail:with:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidFail(_:with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerDidFail:with:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidChangePolygon(_:)\/title","op":"replace","value":"imageEditingViewControllerDidChangePolygon:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1imageEditingViewControllerDidChangePolygon(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewControllerDidChangePolygon:"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/title","op":"replace","value":"SBSDKUI2CroppingViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/fragments","op":"replace","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CroppingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1imageEditingViewController(_:didDetectPolygon:)\/title","op":"replace","value":"imageEditingViewController:didDetectPolygon:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingViewController~1imageEditingViewController(_:didDetectPolygon:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageEditingViewController:didDetectPolygon:"}]}]}]}