{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBoardingPassIssuanceJulian"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2boardingpassdocumentfieldtype\/dateofboardingpassissuancejulian"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2boardingpassdocumentfieldtype\/dateofboardingpassissuancejulian"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BoardingPassDocumentFieldType\/dateOfBoardingPassIssuanceJulian","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Date of boarding pass issuance in Julian format"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBoardingPassIssuanceJulian"}],"title":"SBSDKUI2BoardingPassDocumentFieldType.dateOfBoardingPassIssuanceJulian","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BoardingPassDocumentFieldType@SBSDKUI2BoardingPassDocumentFieldTypeDateOfBoardingPassIssuanceJulian","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeDateOfBoardingPassIssuanceJulian"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"Boarding Pass Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2boardingpassdocumentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BoardingPassDocumentFieldType/dateOfBoardingPassIssuanceJulian":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType.dateOfBoardingPassIssuanceJulian","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBoardingPassIssuanceJulian"}],"abstract":[{"type":"text","text":"Date of boarding pass issuance in Julian format"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BoardingPassDocumentFieldType\/dateOfBoardingPassIssuanceJulian","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeDateOfBoardingPassIssuanceJulian"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2boardingpassdocumentfieldtype\/dateofboardingpassissuancejulian"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeDateOfBoardingPassIssuanceJulian"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeDateOfBoardingPassIssuanceJulian"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeDateOfBoardingPassIssuanceJulian"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BoardingPassDocumentFieldType\/title","value":"SBSDKUI2BoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BoardingPassDocumentFieldType~1dateOfBoardingPassIssuanceJulian\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeDateOfBoardingPassIssuanceJulian"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BoardingPassDocumentFieldType~1dateOfBoardingPassIssuanceJulian\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeDateOfBoardingPassIssuanceJulian"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}