{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forIndividualAirlineUse"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2boardingpassdocumentfieldtype\/forindividualairlineuse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2boardingpassdocumentfieldtype\/forindividualairlineuse"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BoardingPassDocumentFieldType\/forIndividualAirlineUse","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For individual airline use"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forIndividualAirlineUse"}],"title":"SBSDKUI2BoardingPassDocumentFieldType.forIndividualAirlineUse","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2BoardingPassDocumentFieldType@SBSDKUI2BoardingPassDocumentFieldTypeForIndividualAirlineUse","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeForIndividualAirlineUse"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BoardingPassDocumentFieldType"]]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","title":"ScanbotBarcodeScannerSDK","abstract":[{"type":"text","text":"Version: 5.0.2"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BoardingPassDocumentFieldType":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"abstract":[{"type":"text","text":"Boarding Pass Document Field Type"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BoardingPassDocumentFieldType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2boardingpassdocumentfieldtype"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2BoardingPassDocumentFieldType/forIndividualAirlineUse":{"role":"symbol","title":"SBSDKUI2BoardingPassDocumentFieldType.forIndividualAirlineUse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forIndividualAirlineUse"}],"abstract":[{"type":"text","text":"For individual airline use"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2BoardingPassDocumentFieldType\/forIndividualAirlineUse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeForIndividualAirlineUse"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2boardingpassdocumentfieldtype\/forindividualairlineuse"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeForIndividualAirlineUse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeForIndividualAirlineUse"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeForIndividualAirlineUse"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BoardingPassDocumentFieldType\/title","value":"SBSDKUI2BoardingPassDocumentFieldType"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BoardingPassDocumentFieldType\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldType"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BoardingPassDocumentFieldType~1forIndividualAirlineUse\/title","value":"SBSDKUI2BoardingPassDocumentFieldTypeForIndividualAirlineUse"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2BoardingPassDocumentFieldType~1forIndividualAirlineUse\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BoardingPassDocumentFieldTypeForIndividualAirlineUse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}