{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2reviewbottombarconfiguration\/addbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2reviewbottombarconfiguration\/addbutton"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration\/addButton"},"abstract":[{"text":"Configuration of the ‘add’ button, located in the bottom bar.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addButton","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"addButton","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReviewBottomBarConfiguration(py)addButton","symbolKind":"property","title":"addButton","roleHeading":"Instance Property"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewBottomBarConfiguration/addButton":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration\/addButton","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration"}],"navigatorTitle":[{"text":"addButton","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration of the ‘add’ button, located in the bottom bar.","type":"text"}],"type":"topic","title":"addButton","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2reviewbottombarconfiguration\/addbutton"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReviewBottomBarConfiguration":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2reviewbottombarconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReviewBottomBarConfiguration","abstract":[{"type":"text","text":"Configuration of the bottom bar for the review screen."}],"title":"SBSDKUI2ReviewBottomBarConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration","title":"SBSDKUI2BarButtonConfiguration","abstract":[{"type":"text","text":"Configuration of the button located on a bar."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barbuttonconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"addButton","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"addButton","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarButtonConfiguration","kind":"typeIdentifier","text":"SBSDKUI2BarButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarButtonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"addButton"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration~1addButton\/title","value":"addButton","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration~1addButton\/fragments","value":[{"kind":"identifier","text":"addButton"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration\/title","value":"SBSDKUI2ReviewBottomBarConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration\/fragments","value":[{"text":"SBSDKUI2ReviewBottomBarConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReviewBottomBarConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ReviewBottomBarConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/title","value":"SBSDKUI2BarButtonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2BarButtonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarButtonConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2BarButtonConfiguration","kind":"identifier"}],"op":"replace"}]}]}