{"metadata":{"symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"streamingCryptCompleteWithError:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"streamingCryptCompleteWithError:","navigatorTitle":[{"text":"streamingCryptCompleteWithError:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKAESGCMEncrypter(im)streamingCryptCompleteWithError:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"streamingCryptCompleteWithError:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter\/streamingCryptCompleteWithError:"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter\/streamingcryptcompletewitherror:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESGCMEncrypter/streamingCryptCompleteWithError:":{"navigatorTitle":[{"text":"streamingCryptCompleteWithError:","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter\/streamingcryptcompletewitherror:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter\/streamingCryptCompleteWithError:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"streamingCryptCompleteWithError:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"streamingCryptCompleteWithError:","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKAESGCMEncrypter":{"abstract":[{"type":"text","text":"A data encrypter implementing the AES128-GCM and AES256-GCM standards, with a configurable encryption key provider."},{"type":"text","text":" "},{"text":"Supports encryption and decryption of single data blocks as well as streaming data.","type":"text"}],"title":"SBSDKAESGCMEncrypter","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"navigatorTitle":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKAESGCMEncrypter","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkaesgcmencrypter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKAESGCMEncrypter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/fragments","value":[{"text":"SBSDKAESGCMEncrypter","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKAESGCMEncrypter"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKAESGCMEncrypter\/navigatorTitle"}]}]}