{"metadata":{"role":"symbol","roleHeading":"Type Property","externalID":"s:10ScanbotSDK28SBSDKTIFFGeneratorParametersC07defaultD15ForBinaryImagesACvpZ","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultParametersForBinaryImages","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKTIFFGeneratorParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters"}],"title":"defaultParametersForBinaryImages","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"extendedModule":"ScanbotSDK"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultParametersForBinaryImages","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters","kind":"typeIdentifier","text":"SBSDKTIFFGeneratorParameters"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/defaultparametersforbinaryimages"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"The default parameters for TIFF generating with binarization.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultParametersForBinaryImages","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters/defaultParametersForBinaryImages":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultParametersForBinaryImages"},{"text":": ","kind":"text"},{"text":"SBSDKTIFFGeneratorParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters\/defaultparametersforbinaryimages","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters\/defaultParametersForBinaryImages","abstract":[{"text":"The default parameters for TIFF generating with binarization.","type":"text"}],"title":"defaultParametersForBinaryImages","role":"symbol","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","abstract":[{"text":"TIFF generator parameters.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","type":"topic","title":"SBSDKTIFFGeneratorParameters","navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKTIFFGeneratorParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments"},{"value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle","op":"replace"}]}]}