{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer"]]},"metadata":{"title":"initWithLayer:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLayer:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygonLayer(im)initWithLayer:","navigatorTitle":[{"kind":"identifier","text":"initWithLayer:"}],"roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithLayer:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"layer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer\/initWithLayer:"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygonlayer\/initwithlayer:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonLayer/initWithLayer:":{"role":"symbol","title":"initWithLayer:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLayer:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer\/initWithLayer:","navigatorTitle":[{"kind":"identifier","text":"initWithLayer:"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygonlayer\/initwithlayer:","type":"topic","abstract":[],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonLayer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonLayer","url":"\/documentation\/scanbotsdk\/sbsdkpolygonlayer","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygonLayer","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"CAShapeLayer","type":"codeVoice"},{"text":" subclass that is used to draw bezier paths with fluid animation.","type":"text"}],"kind":"symbol","title":"SBSDKPolygonLayer","navigatorTitle":[{"text":"SBSDKPolygonLayer","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"SBSDKPolygonLayer","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer\/title"},{"value":[{"text":"SBSDKPolygonLayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer\/fragments"},{"value":[{"text":"SBSDKPolygonLayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonLayer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}