{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzScannerController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","kind":"typeIdentifier","text":"SBSDKMRZScannerViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didScanMRZ"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKMRZScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerResult"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calling "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","type":"reference","isActive":true},{"type":"text","text":"."}]}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"text":"The scanned machine-readable zone result.","type":"text"}]}]}]}],"metadata":{"title":"mrzScannerController(_:didScanMRZ:)","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController"},{"text":", ","kind":"text"},{"text":"didScanMRZ","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMRZScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKMRZScannerViewControllerDelegate(im)mrzScannerController:didScanMRZ:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"mrzScannerController:didScanMRZ:"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontroller(_:didscanmrz:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontroller(_:didscanmrz:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerController(_:didScanMRZ:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Informs the delegate that the scanner has scanned a machine-readable zone."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate","role":"symbol","navigatorTitle":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegation protocol for the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"type":"text","text":" class."}],"title":"SBSDKMRZScannerViewControllerDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerResult":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKMRZScannerResult","kind":"identifier"}],"title":"SBSDKMRZScannerResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMRZScannerResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerResult","type":"topic","abstract":[{"text":"Container for result of MRZ scanning attempt.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerresult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewControllerDelegate/mrzScannerController(_:didScanMRZ:)":{"navigatorTitle":[{"text":"mrzScannerController:didScanMRZ:","kind":"identifier"}],"abstract":[{"text":"Informs the delegate that the scanner has scanned a machine-readable zone.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontrollerdelegate\/mrzscannercontroller(_:didscanmrz:)","title":"mrzScannerController(_:didScanMRZ:)","required":true,"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewControllerDelegate\/mrzScannerController(_:didScanMRZ:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzScannerController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController"},{"text":", ","kind":"text"},{"text":"didScanMRZ","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKMRZScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMRZScannerViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkmrzscannerviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"abstract":[{"text":"Classic UI view controller that can be used to scan machine-readable zones.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMRZScannerViewController"}],"type":"topic","title":"SBSDKMRZScannerViewController","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"mrzScannerController:didScanMRZ:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mrzScannerController:didScanMRZ:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"mrzScannerController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didScanMRZ:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKMRZScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKMRZScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The calling "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMRZScannerViewController","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scanned machine-readable zone result."}]}],"name":"result"}],"kind":"parameters"}},{"value":"SBSDKMRZScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKMRZScannerViewControllerDelegate"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/fragments","op":"replace"},{"value":[{"text":"SBSDKMRZScannerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerResult\/title","value":"SBSDKMRZScannerResult"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerResult\/fragments","value":[{"text":"SBSDKMRZScannerResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerResult\/navigatorTitle","value":[{"text":"SBSDKMRZScannerResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerController(_:didScanMRZ:)\/title","value":"mrzScannerController:didScanMRZ:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewControllerDelegate~1mrzScannerController(_:didScanMRZ:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mrzScannerController:didScanMRZ:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/title","value":"SBSDKMRZScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/fragments","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMRZScannerViewController\/navigatorTitle","value":[{"text":"SBSDKMRZScannerViewController","kind":"identifier"}]}]}]}