{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/!=(_:_:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/!=(_:_:)","interfaceLanguage":"swift"},"metadata":{"title":"!=(_:_:)","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@ScanbotSDK@E@SBSDKAustraliaPostCustomerFormat","role":"symbol","roleHeading":"Operator","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"op","modules":[{"relatedModules":["Swift"],"name":"ScanbotSDK"}],"extendedModule":"Swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/Equatable-Implementations"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/equatable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/Equatable-Implementations","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat/numeric":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatNumeric"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/numeric","title":"SBSDKAustraliaPostCustomerFormat.numeric","abstract":[{"type":"text","text":"The numeric format."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numeric"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/numeric"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat/alphanumeric":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/alphanumeric","abstract":[{"text":"The alphanumeric format.","type":"text"}],"title":"SBSDKAustraliaPostCustomerFormat.alphanumeric","navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatAlphanumeric"}],"url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/alphanumeric","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alphanumeric"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat/!=(_:_:)":{"title":"!=(_:_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/!=(_:_:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAustraliaPostCustomerFormat":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat","abstract":[{"text":"The format of the australia post code. Can be ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/numeric","isActive":true},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAustraliaPostCustomerFormat\/alphanumeric"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Only relevant for format codes 59 and 62."}],"title":"SBSDKAustraliaPostCustomerFormat","navigatorTitle":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"url":"\/documentation\/scanbotsdk\/sbsdkaustraliapostcustomerformat","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1numeric\/title","value":"SBSDKAustraliaPostCustomerFormatNumeric","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1numeric\/fragments","value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatNumeric"}],"op":"replace"},{"op":"replace","value":"SBSDKAustraliaPostCustomerFormatAlphanumeric","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1alphanumeric\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat~1alphanumeric\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormatAlphanumeric"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/title","value":"SBSDKAustraliaPostCustomerFormat"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/fragments","value":[{"text":"SBSDKAustraliaPostCustomerFormat","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKAustraliaPostCustomerFormat"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAustraliaPostCustomerFormat\/navigatorTitle"}]}]}