{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration\/initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:"}],"roleHeading":"Instance Method","title":"initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKResultAccumulationConfiguration(im)initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfirmationMethod:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKConfirmationMethod","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKConfirmationMethod","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod"},{"kind":"text","text":") "},{"kind":"internalParam","text":"confirmationMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfirmations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minConfirmations"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidenceForStableField:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minConfidenceForStableField"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoClearThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"autoClearThreshold"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration\/initwithconfirmationmethod:minconfirmations:minconfidenceforstablefield:autoclearthreshold:"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration","navigatorTitle":[{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for how to accumulate results.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKResultAccumulationConfiguration","kind":"identifier"}],"title":"SBSDKResultAccumulationConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKResultAccumulationConfiguration/initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:":{"navigatorTitle":[{"text":"initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKResultAccumulationConfiguration\/initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkresultaccumulationconfiguration\/initwithconfirmationmethod:minconfirmations:minconfidenceforstablefield:autoclearthreshold:","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:","kind":"identifier"}],"title":"initWithConfirmationMethod:minConfirmations:minConfidenceForStableField:autoClearThreshold:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKConfirmationMethod":{"role":"symbol","kind":"symbol","title":"SBSDKConfirmationMethod","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKConfirmationMethod"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKConfirmationMethod","url":"\/documentation\/scanbotsdk\/sbsdkconfirmationmethod","abstract":[{"type":"text","text":"Method used to confirm a result."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/title","value":"SBSDKResultAccumulationConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKResultAccumulationConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKResultAccumulationConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/title","value":"SBSDKConfirmationMethod"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/fragments","value":[{"text":"SBSDKConfirmationMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKConfirmationMethod\/navigatorTitle","value":[{"text":"SBSDKConfirmationMethod","kind":"identifier"}]}]}]}