{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration\/badge"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"badge","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"badge","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration(py)badge","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"badge"},{"text":": ","kind":"text"},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badge"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration","kind":"typeIdentifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration\/badge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration\/badge"]}],"abstract":[{"type":"text","text":"Configuration of the round badge on find and pick ar layer."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayFindAndPickConfiguration":{"abstract":[{"text":"Configuration of the AR overlay.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2ArOverlayFindAndPickConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickBadgeConfiguration":{"abstract":[{"type":"text","text":"Configuration of the round badge on find and pick ar layer."}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickbadgeconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2FindAndPickBadgeConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayFindAndPickConfiguration/badge":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"badge","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration","text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"typeIdentifier"}],"abstract":[{"text":"Configuration of the round badge on find and pick ar layer.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration\/badge","title":"badge","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration\/badge","type":"topic","navigatorTitle":[{"text":"badge","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"badge","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"badge"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"SBSDKUI2FindAndPickBadgeConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickBadgeConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickBadgeConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"badge"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/title","op":"replace","value":"SBSDKUI2ArOverlayFindAndPickConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/fragments","value":[{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/title","value":"SBSDKUI2FindAndPickBadgeConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickBadgeConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickBadgeConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2FindAndPickBadgeConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration~1badge\/title","value":"badge"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration~1badge\/fragments","op":"replace","value":[{"kind":"identifier","text":"badge"}]}]}]}