{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerBehaviorConfiguration(py)maximumNumberOfAccumulatedFrames","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"maximumNumberOfAccumulatedFrames"},"abstract":[{"type":"text","text":"The maximum number of accumulated video frames before the current recognition result is returned."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration\/maximumNumberOfAccumulatedFrames","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerBehaviorConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"identifier"}],"title":"SBSDKUILicensePlateScannerBehaviorConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUILicensePlateScannerBehaviorConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration","abstract":[{"type":"text","text":"Configuration for the behavior of the RTU-UI license plate scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerBehaviorConfiguration/maximumNumberOfAccumulatedFrames":{"role":"symbol","abstract":[{"text":"The maximum number of accumulated video frames before the current recognition result is returned.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannerbehaviorconfiguration\/maximumnumberofaccumulatedframes","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerBehaviorConfiguration\/maximumNumberOfAccumulatedFrames","kind":"symbol","type":"topic","title":"maximumNumberOfAccumulatedFrames","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"maximumNumberOfAccumulatedFrames","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUILicensePlateScannerBehaviorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerBehaviorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerBehaviorConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration\/navigatorTitle","op":"replace"},{"value":"maximumNumberOfAccumulatedFrames","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration~1maximumNumberOfAccumulatedFrames\/title","op":"replace"},{"value":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerBehaviorConfiguration~1maximumNumberOfAccumulatedFrames\/fragments","op":"replace"}]}]}