{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration\/hash"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration\/hash"]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatPharmaCodeConfiguration(py)hash","navigatorTitle":[{"kind":"identifier","text":"hash"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeConfiguration":{"title":"SBSDKBarcodeFormatPharmaCodeConfiguration","type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration","navigatorTitle":[{"text":"SBSDKBarcodeFormatPharmaCodeConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"PharmaCode barcode configuration. Add to scanner configuration to scan linear (1D) Laetus Pharmacode barcodes. Two-track PharmaCode scanning is configured separately through the PharmaCodeTwoTrackConfig class."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatPharmaCodeConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatPharmaCodeConfiguration/hash":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatPharmaCodeConfiguration\/hash","type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatpharmacodeconfiguration\/hash","role":"symbol","title":"hash","fragments":[{"kind":"identifier","text":"hash"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatPharmaCodeConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatPharmaCodeConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatPharmaCodeConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}