{"sections":[],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorConfiguration(im)init","title":"init","modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorConfiguration\/init","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorconfiguration\/init"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorConfiguration":{"navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorConfiguration","kind":"identifier"}],"abstract":[{"text":"This class describes the look and feel, the behavior and the textual contents of the RTU-UI document data extractor screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorConfiguration","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorconfiguration","title":"SBSDKUIDocumentDataExtractorConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorConfiguration","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorConfiguration/init":{"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractorconfiguration\/init","role":"symbol","abstract":[],"title":"init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorConfiguration\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"SBSDKUIDocumentDataExtractorConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIDocumentDataExtractorConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}