{"abstract":[{"type":"text","text":"Document issue date field."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issueDate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType","text":"SBSDKCommonFieldType","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType\/issueDate","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType"]]},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"title":"issueDate","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType(cpy)issueDate","roleHeading":"Type Property","navigatorTitle":[{"text":"issueDate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"issueDate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType","text":"SBSDKCommonFieldType"}],"role":"symbol","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcommonfieldtype\/issuedate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkcommonfieldtype\/issuedate"]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCommonFieldType/issueDate":{"role":"symbol","title":"issueDate","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"issueDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType","text":"SBSDKCommonFieldType","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcommonfieldtype\/issuedate","abstract":[{"type":"text","text":"Document issue date field."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType\/issueDate","kind":"symbol","type":"topic","navigatorTitle":[{"text":"issueDate","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKCommonFieldType":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkcommonfieldtype","abstract":[{"text":"Common field types.","type":"text"}],"title":"SBSDKCommonFieldType","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCommonFieldType","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKCommonFieldType","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"issueDate","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"issueDate"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKCommonFieldType","kind":"typeIdentifier","text":"SBSDKCommonFieldType","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKCommonFieldType"},{"kind":"text","text":" * "},{"kind":"identifier","text":"issueDate"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType~1issueDate\/title","value":"issueDate"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType~1issueDate\/fragments","op":"replace","value":[{"text":"issueDate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType\/title","value":"SBSDKCommonFieldType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType\/fragments","value":[{"text":"SBSDKCommonFieldType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKCommonFieldType\/navigatorTitle","value":[{"text":"SBSDKCommonFieldType","kind":"identifier"}]}]}]}