{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideocontentmode\/fillin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkvideocontentmode\/fillin"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"type":"text","text":" "},{"type":"text","text":"No visible borders. Video may be cropped to the visible screen area."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoContentMode\/fillIn","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","title":"SBSDKVideoContentMode.fillIn","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fillIn","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKVideoContentMode@SBSDKVideoContentModeFillIn","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKVideoContentModeFillIn","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoContentMode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoContentMode/fillIn":{"navigatorTitle":[{"text":"SBSDKVideoContentModeFillIn","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideocontentmode\/fillin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillIn","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoContentMode\/fillIn","title":"SBSDKVideoContentMode.fillIn","abstract":[{"type":"text","text":"The video layers content is filled into the video layer."},{"type":"text","text":" "},{"type":"text","text":"No visible borders. Video may be cropped to the visible screen area."}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKVideoContentMode":{"title":"SBSDKVideoContentMode","type":"topic","abstract":[{"text":"Enumeration of video preview content mode.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKVideoContentMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoContentMode"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKVideoContentMode","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkvideocontentmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKVideoContentModeFillIn"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoContentMode~1fillIn\/title","value":"SBSDKVideoContentModeFillIn"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoContentMode~1fillIn\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoContentModeFillIn"}]},{"value":"SBSDKVideoContentMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoContentMode\/title"},{"value":[{"text":"SBSDKVideoContentMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoContentMode\/fragments"},{"value":[{"text":"SBSDKVideoContentMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKVideoContentMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}