{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding\/end"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"end"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRangeEncoding(py)end","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"end"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"end","navigatorTitle":[{"kind":"identifier","text":"end"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding"]]},"abstract":[{"text":"End index of the range (inclusive).","type":"text"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkrangeencoding\/end"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkrangeencoding\/end"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRangeEncoding/end":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"end","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"End index of the range (inclusive)."}],"kind":"symbol","title":"end","url":"\/documentation\/scanbotsdk\/sbsdkrangeencoding\/end","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding\/end","type":"topic","navigatorTitle":[{"text":"end","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRangeEncoding":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKRangeEncoding"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRangeEncoding","title":"SBSDKRangeEncoding","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrangeencoding","navigatorTitle":[{"kind":"identifier","text":"SBSDKRangeEncoding"}],"abstract":[{"text":"A character encoding for a given range of bytes.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"end","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"end","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"text":"end","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding~1end\/title","op":"replace","value":"end"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding~1end\/fragments","value":[{"text":"end","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/title","value":"SBSDKRangeEncoding","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/fragments","value":[{"text":"SBSDKRangeEncoding","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKRangeEncoding"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRangeEncoding\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}