{"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicameraviewcontroller\/willshowenablecameraview()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuicameraviewcontroller\/willshowenablecameraview()"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraViewController\/willShowEnableCameraView()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willShowEnableCameraView"},{"text":"()","kind":"text"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Override to perform custom actions before appearing of the enable-camera-view."},{"type":"text","text":" "},{"type":"text","text":"For example: show the container or hide some buttons."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraViewController"]]},"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","title":"willShowEnableCameraView()","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"willShowEnableCameraView","kind":"identifier"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUICameraViewController(im)willShowEnableCameraView","navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}]},"abstract":[{"type":"text","text":"A method for subclassing."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICameraViewController":{"navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController","isActive":true},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKUICameraViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUICameraViewController","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicameraviewcontroller","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraViewController"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIViewController":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIViewController","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuiviewcontroller","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIViewController","kind":"identifier"}],"title":"SBSDKUIViewController","navigatorTitle":[{"text":"SBSDKUIViewController","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUICameraViewController/willShowEnableCameraView()":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willShowEnableCameraView"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"A method for subclassing."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUICameraViewController\/willShowEnableCameraView()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"willShowEnableCameraView"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuicameraviewcontroller\/willshowenablecameraview()","title":"willShowEnableCameraView()"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"willShowEnableCameraView"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willShowEnableCameraView"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"willShowEnableCameraView"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKUICameraViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraViewController\/fragments","value":[{"text":"SBSDKUICameraViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},{"value":"SBSDKUIViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController\/title"},{"op":"replace","value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController\/fragments"},{"value":[{"text":"SBSDKUIViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIViewController\/navigatorTitle"},{"op":"replace","value":"willShowEnableCameraView","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraViewController~1willShowEnableCameraView()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"willShowEnableCameraView","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUICameraViewController~1willShowEnableCameraView()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}