{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatFourStateConfigurationBase(im)copyWithZone:","title":"copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase\/copywithzone:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/copyWithZone:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase":{"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase","title":"SBSDKBarcodeFormatFourStateConfigurationBase","abstract":[{"text":"Base class for all four-state barcode configurations.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatFourStateConfigurationBase/copyWithZone:":{"title":"copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatfourstateconfigurationbase\/copywithzone:","kind":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatFourStateConfigurationBase\/copyWithZone:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/title","op":"replace","value":"SBSDKBarcodeFormatFourStateConfigurationBase"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatFourStateConfigurationBase"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatFourStateConfigurationBase\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBarcodeFormatFourStateConfigurationBase","kind":"identifier"}]}]}]}