{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration\/flashbuttoninactivecolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration\/flashbuttoninactivecolor"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"]]},"abstract":[{"type":"text","text":"Foreground color of the flash button when flash is off."}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flashButtonInactiveColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","symbolKind":"property","title":"flashButtonInactiveColor","navigatorTitle":[{"kind":"identifier","text":"flashButtonInactiveColor"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerUIConfiguration(py)flashButtonInactiveColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"flashButtonInactiveColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/flashButtonInactiveColor","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration":{"kind":"symbol","role":"symbol","title":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"}],"abstract":[{"type":"text","text":"Configuration for user interface of the detector RTU-UI screen for Health Insurance Card scanner."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration/flashButtonInactiveColor":{"kind":"symbol","title":"flashButtonInactiveColor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/flashButtonInactiveColor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flashButtonInactiveColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"flashButtonInactiveColor","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration\/flashbuttoninactivecolor","abstract":[{"text":"Foreground color of the flash button when flash is off.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"flashButtonInactiveColor","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"flashButtonInactiveColor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"flashButtonInactiveColor"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/title"},{"value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","kind":"identifier"}]},{"value":"flashButtonInactiveColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration~1flashButtonInactiveColor\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration~1flashButtonInactiveColor\/fragments","value":[{"kind":"identifier","text":"flashButtonInactiveColor"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}