{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions\/decrypter"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decrypter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Custom decrypter to use when loading the image if the encryptionMode implies encryption must be used.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions\/decrypter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions\/decrypter"]}],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPathImageLoadOptions(py)decrypter","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"text":"decrypter","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decrypter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","title":"decrypter"},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathImageLoadOptions/decrypter":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions\/decrypter","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions\/decrypter","kind":"symbol","role":"symbol","title":"decrypter","abstract":[{"text":"Custom decrypter to use when loading the image if the encryptionMode implies encryption must be used.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"decrypter"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPathImageLoadOptions":{"title":"SBSDKPathImageLoadOptions","kind":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpathimageloadoptions","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPathImageLoadOptions","abstract":[{"text":"Options for loading image from path.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPathImageLoadOptions","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKStorageCryptingProvider":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkstoragecryptingprovider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"type":"topic","title":"SBSDKStorageCryptingProvider","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKStorageCryptingProvider","abstract":[{"type":"text","text":"Protocol for providing a storage crypting object."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","type":"topic","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"decrypter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"decrypter"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"id<SBSDKStorageCryptingProvider>"},{"kind":"text","text":" "},{"kind":"identifier","text":"decrypter"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"decrypter","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions~1decrypter\/title","op":"replace"},{"value":[{"text":"decrypter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions~1decrypter\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/title","value":"SBSDKPathImageLoadOptions","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/fragments","value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPathImageLoadOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPathImageLoadOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingProvider\/title","value":"SBSDKStorageCryptingProvider","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingProvider\/fragments","value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKStorageCryptingProvider\/navigatorTitle","value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}