{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/europeanHealthInsuranceCardIssuerNameFieldName","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"europeanHealthInsuranceCardIssuerNameFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"europeanHealthInsuranceCardIssuerNameFieldName","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)europeanHealthInsuranceCardIssuerNameFieldName","navigatorTitle":[{"kind":"identifier","text":"europeanHealthInsuranceCardIssuerNameFieldName"}],"title":"europeanHealthInsuranceCardIssuerNameFieldName","role":"symbol","symbolKind":"property","roleHeading":"Type Property"},"abstract":[{"type":"text","text":"Name of the “IssuerName” field type in document type “EuropeanHealthInsuranceCard”."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeanhealthinsurancecardissuernamefieldname"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeanhealthinsurancecardissuernamefieldname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/europeanHealthInsuranceCardIssuerNameFieldName":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/europeanhealthinsurancecardissuernamefieldname","abstract":[{"type":"text","text":"Name of the “IssuerName” field type in document type “EuropeanHealthInsuranceCard”."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"europeanHealthInsuranceCardIssuerNameFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/europeanHealthInsuranceCardIssuerNameFieldName","title":"europeanHealthInsuranceCardIssuerNameFieldName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"europeanHealthInsuranceCardIssuerNameFieldName"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"role":"symbol","title":"SBSDKDocumentsModelConstants"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"europeanHealthInsuranceCardIssuerNameFieldName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"europeanHealthInsuranceCardIssuerNameFieldName"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"europeanHealthInsuranceCardIssuerNameFieldName","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1europeanHealthInsuranceCardIssuerNameFieldName\/title","value":"europeanHealthInsuranceCardIssuerNameFieldName"},{"value":[{"kind":"identifier","text":"europeanHealthInsuranceCardIssuerNameFieldName"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1europeanHealthInsuranceCardIssuerNameFieldName\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title","op":"replace","value":"SBSDKDocumentsModelConstants"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}]},{"value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle"}]}]}