{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatupceanconfiguration\/stripcheckdigits"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatupceanconfiguration\/stripcheckdigits"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","abstract":[{"text":"If true, the check digits are stripped from the result.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration"]]},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatUpcEanConfiguration(py)stripCheckDigits","role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Instance Property","title":"stripCheckDigits","navigatorTitle":[{"kind":"identifier","text":"stripCheckDigits"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stripCheckDigits","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/stripCheckDigits"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stripCheckDigits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is false"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatUpcEanConfiguration/stripCheckDigits":{"title":"stripCheckDigits","navigatorTitle":[{"kind":"identifier","text":"stripCheckDigits"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"stripCheckDigits","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatupceanconfiguration\/stripcheckdigits","type":"topic","abstract":[{"type":"text","text":"If true, the check digits are stripped from the result."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration\/stripCheckDigits","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatUpcEanConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatUpcEanConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}],"kind":"symbol","title":"SBSDKBarcodeFormatUpcEanConfiguration","abstract":[{"type":"text","text":"UPC\/EAN barcode configuration. Add to scanner configuration to scan EAN-8, EAN-13, UPC-E and UPC-A barcodes."}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatupceanconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"stripCheckDigits"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"stripCheckDigits"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"stripCheckDigits","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"stripCheckDigits","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1stripCheckDigits\/title"},{"value":[{"text":"stripCheckDigits","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration~1stripCheckDigits\/fragments","op":"replace"},{"value":"SBSDKBarcodeFormatUpcEanConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatUpcEanConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatUpcEanConfiguration\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormatUpcEanConfiguration","kind":"identifier"}],"op":"replace"}]}]}