{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode\/legacy"},"metadata":{"roleHeading":"Case","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKDocumentScannerEngineMode@SBSDKDocumentScannerEngineModeLegacy","title":"SBSDKDocumentScannerEngineMode.legacy","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"legacy","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineModeLegacy"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerenginemode\/legacy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerenginemode\/legacy"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"legacy"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Use the legacy edge-based document scanner."}],"sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerEngineMode/legacy":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode\/legacy","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"legacy","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerenginemode\/legacy","title":"SBSDKDocumentScannerEngineMode.legacy","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentScannerEngineModeLegacy","kind":"identifier"}],"abstract":[{"type":"text","text":"Use the legacy edge-based document scanner."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerEngineMode":{"navigatorTitle":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerEngineMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"title":"SBSDKDocumentScannerEngineMode","abstract":[{"type":"text","text":"Engines for document scanning."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerenginemode","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKDocumentScannerEngineModeLegacy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SBSDKDocumentScannerEngineModeLegacy","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineModeLegacy"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SBSDKDocumentScannerEngineModeLegacy","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode~1legacy\/title"},{"value":[{"text":"SBSDKDocumentScannerEngineModeLegacy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode~1legacy\/fragments"},{"value":"SBSDKDocumentScannerEngineMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode\/fragments"},{"value":[{"text":"SBSDKDocumentScannerEngineMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerEngineMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}