{"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog(im)copyWithZone:","role":"symbol","title":"copyWithZone:","roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanbotalertdialog\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_NSZone","preciseIdentifier":"c:@S@_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog\/copyWithZone:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanbotAlertDialog/copyWithZone:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanbotalertdialog\/copywithzone:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog\/copyWithZone:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","role":"symbol","title":"copyWithZone:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanbotAlertDialog":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanbotalertdialog","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the standard alert dialog."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog","navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"role":"symbol","title":"SBSDKUI2ScanbotAlertDialog","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2ScanbotAlertDialog","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","op":"replace"}]}]}