{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerTextConfiguration\/confirmationDialogConfirmButtonTitle","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationDialogConfirmButtonTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerTextConfiguration"]]},"abstract":[{"text":"The title of the confirmation dialog confirm button.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannertextconfiguration\/confirmationdialogconfirmbuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannertextconfiguration\/confirmationdialogconfirmbuttontitle"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerTextConfiguration(py)confirmationDialogConfirmButtonTitle","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"confirmationDialogConfirmButtonTitle"}],"title":"confirmationDialogConfirmButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmationDialogConfirmButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerTextConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUILicensePlateScannerTextConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUILicensePlateScannerTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannertextconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerTextConfiguration","abstract":[{"type":"text","text":"Configuration for the textual contents of the RTU-UI license plate scanner."}],"role":"symbol","title":"SBSDKUILicensePlateScannerTextConfiguration","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerTextConfiguration/confirmationDialogConfirmButtonTitle":{"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerTextConfiguration\/confirmationDialogConfirmButtonTitle","kind":"symbol","abstract":[{"type":"text","text":"The title of the confirmation dialog confirm button."}],"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannertextconfiguration\/confirmationdialogconfirmbuttontitle","navigatorTitle":[{"text":"confirmationDialogConfirmButtonTitle","kind":"identifier"}],"title":"confirmationDialogConfirmButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationDialogConfirmButtonTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"confirmationDialogConfirmButtonTitle","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"confirmationDialogConfirmButtonTitle","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"confirmationDialogConfirmButtonTitle","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration\/title","value":"SBSDKUILicensePlateScannerTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUILicensePlateScannerTextConfiguration","kind":"identifier"}]},{"value":"confirmationDialogConfirmButtonTitle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration~1confirmationDialogConfirmButtonTitle\/title"},{"op":"replace","value":[{"text":"confirmationDialogConfirmButtonTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration~1confirmationDialogConfirmButtonTitle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}