{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationDialogMessage"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannertextconfiguration\/confirmationdialogmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannertextconfiguration\/confirmationdialogmessage"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerTextConfiguration"]]},"sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","roleHeading":"Instance Property","title":"confirmationDialogMessage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationDialogMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"confirmationDialogMessage","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUILicensePlateScannerTextConfiguration(py)confirmationDialogMessage"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerTextConfiguration\/confirmationDialogMessage"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The message text of the confirmation dialog.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerTextConfiguration/confirmationDialogMessage":{"navigatorTitle":[{"text":"confirmationDialogMessage","kind":"identifier"}],"title":"confirmationDialogMessage","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationDialogMessage"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerTextConfiguration\/confirmationDialogMessage","abstract":[{"type":"text","text":"The message text of the confirmation dialog."}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannertextconfiguration\/confirmationdialogmessage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUILicensePlateScannerTextConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdkuilicenseplatescannertextconfiguration","title":"SBSDKUILicensePlateScannerTextConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUILicensePlateScannerTextConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUILicensePlateScannerTextConfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration for the textual contents of the RTU-UI license plate scanner."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUILicensePlateScannerTextConfiguration"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"confirmationDialogMessage"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"confirmationDialogMessage","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"confirmationDialogMessage","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration~1confirmationDialogMessage\/title","value":"confirmationDialogMessage","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration~1confirmationDialogMessage\/fragments","value":[{"kind":"identifier","text":"confirmationDialogMessage"}],"op":"replace"},{"value":"SBSDKUILicensePlateScannerTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration\/fragments","value":[{"text":"SBSDKUILicensePlateScannerTextConfiguration","kind":"identifier"}]},{"value":[{"text":"SBSDKUILicensePlateScannerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUILicensePlateScannerTextConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}