{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/confidencevalue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/confidencevalue"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration\/confidenceValue","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The string that shows average confidence value of scanned card. Use %li as number formatting symbol."}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","title":"confidenceValue","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerTextConfiguration(py)confidenceValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confidenceValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"confidenceValue"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confidenceValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration/confidenceValue":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/confidencevalue","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration\/confidenceValue","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"confidenceValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"confidenceValue","abstract":[{"type":"text","text":"The string that shows average confidence value of scanned card. Use %li as number formatting symbol."}],"kind":"symbol","navigatorTitle":[{"text":"confidenceValue","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration":{"title":"SBSDKUIGenericDocumentRecognizerTextConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"abstract":[{"text":"The configuration for the textual contents of the RTU-UI generic document recognizer screen.","type":"text"}],"navigatorTitle":[{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"confidenceValue","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"confidenceValue","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"confidenceValue","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"confidenceValue","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration~1confidenceValue\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration~1confidenceValue\/fragments","value":[{"text":"confidenceValue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/title","op":"replace","value":"SBSDKUIGenericDocumentRecognizerTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}