{"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","title":"emptyValueTitle","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emptyValueTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIGenericDocumentRecognizerTextConfiguration(py)emptyValueTitle","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"emptyValueTitle"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emptyValueTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/emptyvaluetitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/emptyvaluetitle"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The string being displayed for empty values.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration\/emptyValueTitle"},"sections":[],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration","title":"SBSDKUIGenericDocumentRecognizerTextConfiguration","abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI generic document recognizer screen."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIGenericDocumentRecognizerTextConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIGenericDocumentRecognizerTextConfiguration/emptyValueTitle":{"url":"\/documentation\/scanbotsdk\/sbsdkuigenericdocumentrecognizertextconfiguration\/emptyvaluetitle","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIGenericDocumentRecognizerTextConfiguration\/emptyValueTitle","type":"topic","abstract":[{"type":"text","text":"The string being displayed for empty values."}],"title":"emptyValueTitle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"emptyValueTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"emptyValueTitle","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"emptyValueTitle","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"emptyValueTitle","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"emptyValueTitle"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/title","value":"SBSDKUIGenericDocumentRecognizerTextConfiguration"},{"op":"replace","value":[{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/fragments"},{"value":[{"text":"SBSDKUIGenericDocumentRecognizerTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration\/navigatorTitle"},{"value":"emptyValueTitle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration~1emptyValueTitle\/title","op":"replace"},{"op":"replace","value":[{"text":"emptyValueTitle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIGenericDocumentRecognizerTextConfiguration~1emptyValueTitle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}