{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController\/initWithCoder:"},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController(im)initWithCoder:","roleHeading":"Instance Method","title":"initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController/initWithCoder:":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller\/initwithcoder:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController\/initWithCoder:","title":"initWithCoder:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"navigatorTitle":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller","title":"SBSDKTextPatternScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the text pattern scanner."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKTextPatternScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle"}]}]}