{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController"]]},"sections":[],"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUICameraViewController(im)willShowEnableCameraView","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"roleHeading":"Instance Method","title":"willShowEnableCameraView()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willShowEnableCameraView","kind":"identifier"},{"text":"()","kind":"text"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController\/willShowEnableCameraView()","interfaceLanguage":"swift"},"abstract":[{"text":"A method for subclassing.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willShowEnableCameraView","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Override to perform custom actions before appearing of the enable-camera-view.","type":"text"},{"text":" ","type":"text"},{"text":"For example: show the container or hide some buttons.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/willshowenablecameraview()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/willshowenablecameraview()"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIViewController":{"url":"\/documentation\/scanbotsdk\/sbsdkuiviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIViewController","kind":"identifier"}],"title":"SBSDKUIViewController","abstract":[{"type":"text","text":"An abstract base class for RTU-UI view controllers."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController/willShowEnableCameraView()":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController\/willShowEnableCameraView()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willShowEnableCameraView","kind":"identifier"},{"text":"()","kind":"text"}],"title":"willShowEnableCameraView()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"willShowEnableCameraView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller\/willshowenablecameraview()","abstract":[{"type":"text","text":"A method for subclassing."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUICameraViewController":{"navigatorTitle":[{"text":"SBSDKUICameraViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUICameraViewController","type":"topic","abstract":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIViewController","isActive":true,"type":"reference"},{"text":" subclass which adds support for enabled and disabled camera permission.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUICameraViewController","kind":"identifier"}],"title":"SBSDKUICameraViewController","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuicameraviewcontroller"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"willShowEnableCameraView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"willShowEnableCameraView","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"willShowEnableCameraView"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/title","op":"replace","value":"SBSDKUIViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIViewController\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController~1willShowEnableCameraView()\/title","op":"replace","value":"willShowEnableCameraView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController~1willShowEnableCameraView()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"willShowEnableCameraView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/title","op":"replace","value":"SBSDKUICameraViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUICameraViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUICameraViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}