{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PolygonStyle\/strokeColor","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"strokeColor","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"strokeColor","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2PolygonStyle(py)strokeColor","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"strokeColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2polygonstyle\/strokecolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2polygonstyle\/strokecolor"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The color of the polygon outline."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strokeColor"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Default is “#FFFFFFFF”"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PolygonStyle"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2Color":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"title":"SBSDKUI2Color","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2color","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PolygonStyle":{"navigatorTitle":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PolygonStyle","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2polygonstyle","abstract":[{"text":"Configuration of the polygon appearance.","type":"text"}],"title":"SBSDKUI2PolygonStyle","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2PolygonStyle/strokeColor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strokeColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"}],"title":"strokeColor","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2polygonstyle\/strokecolor","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2PolygonStyle\/strokeColor","navigatorTitle":[{"kind":"identifier","text":"strokeColor"}],"abstract":[{"type":"text","text":"The color of the polygon outline."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"strokeColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"strokeColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" * ","kind":"text"},{"text":"strokeColor","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUI2Color","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/title"},{"value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2Color\/navigatorTitle"},{"value":"SBSDKUI2PolygonStyle","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PolygonStyle\/title"},{"value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PolygonStyle\/fragments"},{"value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PolygonStyle\/navigatorTitle"},{"value":"strokeColor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PolygonStyle~1strokeColor\/title"},{"value":[{"text":"strokeColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2PolygonStyle~1strokeColor\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}