{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters\/acceptedaspectratioscore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters\/acceptedaspectratioscore"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"acceptedAspectRatioScore","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerParameters(py)acceptedAspectRatioScore","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedAspectRatioScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"acceptedAspectRatioScore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptedAspectRatioScore","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Default is 85"}],"type":"paragraph"}]}],"abstract":[{"text":"The minimum score in percent (0 - 100) that the aspect ratio of the document","type":"text"},{"text":" ","type":"text"},{"text":"must match one of the required aspect ratios (if any) to accept a detected document.","type":"text"},{"text":" ","type":"text"},{"text":"If acceptedAspectRatioScore is more than 0, then the document is only accepted if the aspect ratio","type":"text"},{"text":" ","type":"text"},{"text":"matches one of the given aspect ratios (if any), otherwise OK_BUT_BAD_ASPECT_RATIO is returned.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters\/acceptedAspectRatioScore"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters":{"type":"topic","title":"SBSDKDocumentScannerParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"abstract":[{"text":"Parameters for the document scanner.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters/acceptedAspectRatioScore":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters\/acceptedAspectRatioScore","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters\/acceptedaspectratioscore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptedAspectRatioScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"acceptedAspectRatioScore","abstract":[{"text":"The minimum score in percent (0 - 100) that the aspect ratio of the document","type":"text"},{"text":" ","type":"text"},{"text":"must match one of the required aspect ratios (if any) to accept a detected document.","type":"text"},{"text":" ","type":"text"},{"text":"If acceptedAspectRatioScore is more than 0, then the document is only accepted if the aspect ratio","type":"text"},{"text":" ","type":"text"},{"text":"matches one of the given aspect ratios (if any), otherwise OK_BUT_BAD_ASPECT_RATIO is returned.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"acceptedAspectRatioScore"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"acceptedAspectRatioScore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"acceptedAspectRatioScore"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"acceptedAspectRatioScore","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/title","op":"replace","value":"SBSDKDocumentScannerParameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/navigatorTitle","op":"replace","value":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters~1acceptedAspectRatioScore\/title","op":"replace","value":"acceptedAspectRatioScore"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters~1acceptedAspectRatioScore\/fragments","op":"replace","value":[{"text":"acceptedAspectRatioScore","kind":"identifier"}]}]}]}