{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanAssistanceOverlay\/copyWithZone:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanAssistanceOverlay"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanassistanceoverlay\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"title":"copyWithZone:","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay(im)copyWithZone:"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanAssistanceOverlay":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanAssistanceOverlay","title":"SBSDKUI2ScanAssistanceOverlay","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration of the scan assistance overlay."}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanassistanceoverlay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanAssistanceOverlay/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanAssistanceOverlay\/copyWithZone:","type":"topic","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanassistanceoverlay\/copywithzone:","kind":"symbol","title":"copyWithZone:","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2ScanAssistanceOverlay","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanAssistanceOverlay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanAssistanceOverlay\/fragments","op":"replace"},{"value":[{"text":"SBSDKUI2ScanAssistanceOverlay","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanAssistanceOverlay\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}