{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Property","title":"hash","symbolKind":"property","fragments":[{"kind":"identifier","text":"hash"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanAssistanceOverlay(py)hash"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanAssistanceOverlay"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanAssistanceOverlay\/hash","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanassistanceoverlay\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanAssistanceOverlay":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanassistanceoverlay","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanAssistanceOverlay","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"abstract":[{"text":"Configuration of the scan assistance overlay.","type":"text"}],"title":"SBSDKUI2ScanAssistanceOverlay","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanAssistanceOverlay/hash":{"fragments":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanAssistanceOverlay\/hash","role":"symbol","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanassistanceoverlay\/hash","abstract":[],"kind":"symbol","title":"hash"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanAssistanceOverlay\/title","value":"SBSDKUI2ScanAssistanceOverlay","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanAssistanceOverlay\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanAssistanceOverlay\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanAssistanceOverlay"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}