{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintEnergySavingActive"},"abstract":[{"type":"text","text":"The text being displayed on the user-guidance label, when the scanners energy saver is activated."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerStatusTextConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintenergysavingactive"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintenergysavingactive"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentScannerStatusTextConfiguration(py)textHintEnergySavingActive","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textHintEnergySavingActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"textHintEnergySavingActive","role":"symbol","navigatorTitle":[{"text":"textHintEnergySavingActive","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintEnergySavingActive"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerStatusTextConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerStatusTextConfiguration","kind":"symbol","abstract":[{"text":"Wraps the texts being displayed as the detection status.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerstatustextconfiguration","navigatorTitle":[{"text":"SBSDKDocumentScannerStatusTextConfiguration","kind":"identifier"}],"type":"topic","title":"SBSDKDocumentScannerStatusTextConfiguration","role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 8.0.4","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentScannerStatusTextConfiguration/textHintEnergySavingActive":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textHintEnergySavingActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentscannerstatustextconfiguration\/texthintenergysavingactive","navigatorTitle":[{"kind":"identifier","text":"textHintEnergySavingActive"}],"title":"textHintEnergySavingActive","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentScannerStatusTextConfiguration\/textHintEnergySavingActive","kind":"symbol","abstract":[{"text":"The text being displayed on the user-guidance label, when the scanners energy saver is activated.","type":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"textHintEnergySavingActive"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"textHintEnergySavingActive"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"textHintEnergySavingActive","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration\/title","value":"SBSDKDocumentScannerStatusTextConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerStatusTextConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintEnergySavingActive\/title","value":"textHintEnergySavingActive"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentScannerStatusTextConfiguration~1textHintEnergySavingActive\/fragments","value":[{"text":"textHintEnergySavingActive","kind":"identifier"}]}]}]}