{"metadata":{"roleHeading":"Type Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeDocumentModelConstants(cpy)sepaRemittanceFieldName","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","title":"sepaRemittanceFieldName","navigatorTitle":[{"kind":"identifier","text":"sepaRemittanceFieldName"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sepaRemittanceFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sepaRemittanceFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/separemittancefieldname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/separemittancefieldname"]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/sepaRemittanceFieldName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Name of the “Remittance” field type in document type “SEPA”."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants/sepaRemittanceFieldName":{"title":"sepaRemittanceFieldName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sepaRemittanceFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"sepaRemittanceFieldName","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants\/separemittancefieldname","abstract":[{"type":"text","text":"Name of the “Remittance” field type in document type “SEPA”."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants\/sepaRemittanceFieldName","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeDocumentModelConstants":{"abstract":[],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodedocumentmodelconstants","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"title":"SBSDKBarcodeDocumentModelConstants","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeDocumentModelConstants","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sepaRemittanceFieldName","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"sepaRemittanceFieldName"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sepaRemittanceFieldName"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"sepaRemittanceFieldName","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1sepaRemittanceFieldName\/title"},{"op":"replace","value":[{"text":"sepaRemittanceFieldName","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants~1sepaRemittanceFieldName\/fragments"},{"op":"replace","value":"SBSDKBarcodeDocumentModelConstants","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeDocumentModelConstants"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeDocumentModelConstants\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}