{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEncryptionMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkkeyedimagestorage\/encryptionmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkkeyedimagestorage\/encryptionmode"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKKeyedImageStorage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKKeyedImageStorage\/encryptionMode"},"abstract":[{"text":"The encryption mode for the stored images. Defaults to ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode\/disabled","type":"reference"},{"text":".","type":"text"}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKKeyedImageStorage(py)encryptionMode","roleHeading":"Instance Property","title":"encryptionMode","navigatorTitle":[{"text":"encryptionMode","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKKeyedImageStorage/encryptionMode":{"kind":"symbol","abstract":[{"type":"text","text":"The encryption mode for the stored images. Defaults to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode\/disabled"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"encryptionMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKKeyedImageStorage\/encryptionMode","title":"encryptionMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkkeyedimagestorage\/encryptionmode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKEncryptionMode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncryptionMode","kind":"typeIdentifier"}],"type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKKeyedImageStorage":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkkeyedimagestorage","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKKeyedImageStorage","navigatorTitle":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"title":"SBSDKKeyedImageStorage","abstract":[{"text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Manages images in a dictionary-like fashion."}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncryptionMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKEncryptionMode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncryptionMode"}],"title":"SBSDKEncryptionMode","role":"symbol","kind":"symbol","abstract":[{"text":"Encryption\/Decryption mode to be used when an image is loaded\/saved.","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncryptionMode/disabled":{"abstract":[{"type":"text","text":"Encryption is not used when loading or saving images. Trying to load an encrypted image will fail."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode\/disabled","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencryptionmode\/disabled","title":"SBSDKEncryptionMode.disabled","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKEncryptionModeDisabled","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"encryptionMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"encryptionMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKEncryptionMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncryptionMode","text":"SBSDKEncryptionMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"encryptionMode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage~1encryptionMode\/title","value":"encryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage~1encryptionMode\/fragments","value":[{"text":"encryptionMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage\/title","value":"SBSDKKeyedImageStorage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKKeyedImageStorage\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/title","value":"SBSDKEncryptionMode"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/fragments","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKEncryptionMode"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode~1disabled\/title","value":"SBSDKEncryptionModeDisabled"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncryptionMode~1disabled\/fragments","value":[{"text":"SBSDKEncryptionModeDisabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}