{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration\/accumulationTimeout","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"accumulationTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is 3000","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration\/accumulationtimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration\/accumulationtimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accumulationTimeout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"accumulationTimeout","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accumulationTimeout"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckScannerScreenConfiguration(py)accumulationTimeout"},"abstract":[{"type":"text","text":"Timeout for the accumulation state. If the accumulation state is active longer than this value, the alert will"},{"type":"text","text":" "},{"type":"text","text":"be presented."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration","kind":"symbol","title":"SBSDKUI2CheckScannerScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CheckScannerScreenConfiguration"}],"type":"topic","abstract":[{"text":"Configuration of the screen for detecting check data.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckScannerScreenConfiguration/accumulationTimeout":{"abstract":[{"text":"Timeout for the accumulation state. If the accumulation state is active longer than this value, the alert will","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"be presented."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckScannerScreenConfiguration\/accumulationTimeout","title":"accumulationTimeout","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"accumulationTimeout","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkscannerscreenconfiguration\/accumulationtimeout","navigatorTitle":[{"text":"accumulationTimeout","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"accumulationTimeout","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"accumulationTimeout","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"accumulationTimeout","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/title","value":"SBSDKUI2CheckScannerScreenConfiguration"},{"value":[{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2CheckScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration~1accumulationTimeout\/title","value":"accumulationTimeout"},{"op":"replace","value":[{"kind":"identifier","text":"accumulationTimeout"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckScannerScreenConfiguration~1accumulationTimeout\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}