{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorUIResult"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorUIResult\/copyWithZone:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"text":";","kind":"text"}]}]}],"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","title":"copyWithZone:","symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorUIResult(im)copyWithZone:"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractoruiresult\/copywithzone:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorUIResult/copyWithZone:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorUIResult\/copyWithZone:","title":"copyWithZone:","fragments":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractoruiresult\/copywithzone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorUIResult":{"kind":"symbol","title":"SBSDKUI2DocumentDataExtractorUIResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorUIResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorUIResult"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorUIResult","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the generic text scanner RTU UI result."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractoruiresult"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2DocumentDataExtractorUIResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorUIResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorUIResult\/fragments","op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorUIResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorUIResult\/navigatorTitle","value":[{"text":"SBSDKUI2DocumentDataExtractorUIResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}