{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroCustomImage\/initWithUri:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroCustomImage"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"initWithUri:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CheckIntroCustomImage(im)initWithUri:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithUri:","kind":"identifier"}],"title":"initWithUri:"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithUri:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"uri","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2checkintrocustomimage\/initwithuri:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckIntroCustomImage":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A custom image for the introduction screen."}],"url":"\/documentation\/scanbotsdk\/sbsdkui2checkintrocustomimage","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroCustomImage","title":"SBSDKUI2CheckIntroCustomImage","navigatorTitle":[{"text":"SBSDKUI2CheckIntroCustomImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CheckIntroCustomImage","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CheckIntroCustomImage/initWithUri:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithUri:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CheckIntroCustomImage\/initWithUri:","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithUri:","kind":"identifier"}],"title":"initWithUri:","url":"\/documentation\/scanbotsdk\/sbsdkui2checkintrocustomimage\/initwithuri:","role":"symbol","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroCustomImage\/title","op":"replace","value":"SBSDKUI2CheckIntroCustomImage"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroCustomImage\/fragments","op":"replace","value":[{"text":"SBSDKUI2CheckIntroCustomImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CheckIntroCustomImage\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CheckIntroCustomImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}