{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"platforms":[],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerAccessibilityConfiguration(py)cancelButtonAccessibilityHint","role":"symbol","title":"cancelButtonAccessibilityHint","navigatorTitle":[{"kind":"identifier","text":"cancelButtonAccessibilityHint"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelButtonAccessibilityHint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to “Dismisses the screen”."}]}],"kind":"content"}],"abstract":[{"text":"Text, that is used as an accessibility hint for the cancel button.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityHint","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/cancelbuttonaccessibilityhint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/cancelbuttonaccessibilityhint"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"inlineContent":[{"text":"Use SBSDKUI2DocumentScannerViewController instead.","type":"text"}],"type":"paragraph"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerAccessibilityConfiguration":{"abstract":[],"navigatorTitle":[{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration","title":"SBSDKUIDocumentScannerAccessibilityConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerAccessibilityConfiguration/cancelButtonAccessibilityHint":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cancelButtonAccessibilityHint","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/cancelbuttonaccessibilityhint","abstract":[{"text":"Text, that is used as an accessibility hint for the cancel button.","type":"text"}],"role":"symbol","title":"cancelButtonAccessibilityHint","navigatorTitle":[{"text":"cancelButtonAccessibilityHint","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/cancelButtonAccessibilityHint","deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"cancelButtonAccessibilityHint"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"cancelButtonAccessibilityHint","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"cancelButtonAccessibilityHint"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/title","value":"SBSDKUIDocumentScannerAccessibilityConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerAccessibilityConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUIDocumentScannerAccessibilityConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1cancelButtonAccessibilityHint\/title","op":"replace","value":"cancelButtonAccessibilityHint"},{"op":"replace","value":[{"kind":"identifier","text":"cancelButtonAccessibilityHint"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1cancelButtonAccessibilityHint\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}