{"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/flashButtonAccessibilityHint","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"flashButtonAccessibilityHint","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"flashButtonAccessibilityHint","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"flashButtonAccessibilityHint","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIDocumentScannerAccessibilityConfiguration(py)flashButtonAccessibilityHint","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/flashbuttonaccessibilityhint"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/flashbuttonaccessibilityhint"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flashButtonAccessibilityHint"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to “Turns the flashlight on or off”."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the flash button."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 5.2.1"}],"type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerAccessibilityConfiguration/flashButtonAccessibilityHint":{"abstract":[{"type":"text","text":"Text, that is used as an accessibility hint for the flash button."}],"title":"flashButtonAccessibilityHint","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration\/flashbuttonaccessibilityhint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flashButtonAccessibilityHint"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration\/flashButtonAccessibilityHint","type":"topic","navigatorTitle":[{"text":"flashButtonAccessibilityHint","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIDocumentScannerAccessibilityConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIDocumentScannerAccessibilityConfiguration","navigatorTitle":[{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuidocumentscanneraccessibilityconfiguration","type":"topic","role":"symbol","abstract":[],"title":"SBSDKUIDocumentScannerAccessibilityConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"flashButtonAccessibilityHint","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"flashButtonAccessibilityHint"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"flashButtonAccessibilityHint","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1flashButtonAccessibilityHint\/title","value":"flashButtonAccessibilityHint"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration~1flashButtonAccessibilityHint\/fragments","value":[{"kind":"identifier","text":"flashButtonAccessibilityHint"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/title","op":"replace","value":"SBSDKUIDocumentScannerAccessibilityConfiguration"},{"op":"replace","value":[{"text":"SBSDKUIDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIDocumentScannerAccessibilityConfiguration\/fragments"}]}]}