{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/cnEntryAndExitPermitBackMacaoValidUntilFieldName"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cnEntryAndExitPermitBackMacaoValidUntilFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"abstract":[{"text":"Name of the “MacaoValidUntil” field type in document type “CnEntryAndExitPermitBack”.","type":"text"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cnEntryAndExitPermitBackMacaoValidUntilFieldName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelConstants(cpy)cnEntryAndExitPermitBackMacaoValidUntilFieldName","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cnEntryAndExitPermitBackMacaoValidUntilFieldName"}],"roleHeading":"Type Property","title":"cnEntryAndExitPermitBackMacaoValidUntilFieldName","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitbackmacaovaliduntilfieldname"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitbackmacaovaliduntilfieldname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants":{"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"title":"SBSDKDocumentsModelConstants","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelConstants/cnEntryAndExitPermitBackMacaoValidUntilFieldName":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelConstants\/cnEntryAndExitPermitBackMacaoValidUntilFieldName","title":"cnEntryAndExitPermitBackMacaoValidUntilFieldName","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cnEntryAndExitPermitBackMacaoValidUntilFieldName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Name of the “MacaoValidUntil” field type in document type “CnEntryAndExitPermitBack”."}],"navigatorTitle":[{"text":"cnEntryAndExitPermitBackMacaoValidUntilFieldName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelconstants\/cnentryandexitpermitbackmacaovaliduntilfieldname"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cnEntryAndExitPermitBackMacaoValidUntilFieldName","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"cnEntryAndExitPermitBackMacaoValidUntilFieldName"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cnEntryAndExitPermitBackMacaoValidUntilFieldName"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentsModelConstants","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/title"},{"value":[{"text":"SBSDKDocumentsModelConstants","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentsModelConstants"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants\/navigatorTitle"},{"value":"cnEntryAndExitPermitBackMacaoValidUntilFieldName","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1cnEntryAndExitPermitBackMacaoValidUntilFieldName\/title"},{"value":[{"text":"cnEntryAndExitPermitBackMacaoValidUntilFieldName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelConstants~1cnEntryAndExitPermitBackMacaoValidUntilFieldName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}