{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithOptions:) "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions","text":"SBSDKPDFRendererOptions"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The PDF rendering options."}]}],"name":"options"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Creates a new instance of the PDF renderer and configures it according to the specified configuration.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Designated initializer."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/init(options:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/init(options:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/init(options:)"]}],"metadata":{"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRenderer(im)initWithOptions:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKPDFRendererOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions"},{"text":")","kind":"text"}],"title":"init(options:)","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"initWithOptions:","kind":"identifier"}],"symbolKind":"init"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/init(options:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithOptions:"}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/init(options:)","abstract":[{"type":"text","text":"Designated initializer."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions","text":"SBSDKPDFRendererOptions"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/init(options:)","title":"init(options:)","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRendererOptions":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFRendererOptions","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrendereroptions","abstract":[{"text":"A class to describe the options being passed to PDF rendering API.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"SBSDKPDFRendererOptions"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer":{"title":"SBSDKPDFRenderer","kind":"symbol","navigatorTitle":[{"text":"SBSDKPDFRenderer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRenderer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer","role":"symbol","type":"topic","abstract":[{"text":"A class to render an ordered collection of images with or without performing HOCR.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithOptions:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOptions:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithOptions:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRendererOptions","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRendererOptions","text":"SBSDKPDFRendererOptions","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1init(options:)\/title","value":"initWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1init(options:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOptions:","kind":"identifier"}]},{"value":"SBSDKPDFRendererOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/title"},{"value":[{"kind":"identifier","text":"SBSDKPDFRendererOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRendererOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/title","value":"SBSDKPDFRenderer"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/fragments"}]}]}