{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"renderDocumentAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"document"},{"kind":"text","text":": "},{"text":"SBSDKDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document to be rendered to the PDF."}]}],"name":"document"},{"name":"output","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The output file URL."}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The URL the PDF file has been written to or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation failed."}],"type":"paragraph"}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderdocumentasync(_:output:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderdocumentasync(_:output:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocumentAsync(_:output:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Asynchronously renders the document into a PDF file and saves it to the specified URL."},{"type":"text","text":" "},{"type":"text","text":"Each page is made up of one image."}],"metadata":{"symbolKind":"method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRenderer(im)renderDocumentAsync:output:completionHandler:","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderDocumentAsync"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"?"}],"title":"renderDocumentAsync(_:output:)","navigatorTitle":[{"text":"renderDocumentAsync:output:completionHandler:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderDocumentAsync(_:output:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderDocumentAsync"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument","kind":"typeIdentifier","text":"SBSDKDocument"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderDocumentAsync(_:output:)","type":"topic","title":"renderDocumentAsync(_:output:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderdocumentasync(_:output:)","kind":"symbol","abstract":[{"type":"text","text":"Asynchronously renders the document into a PDF file and saves it to the specified URL."},{"type":"text","text":" "},{"text":"Each page is made up of one image.","type":"text"}],"navigatorTitle":[{"text":"renderDocumentAsync:output:completionHandler:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer","kind":"symbol","navigatorTitle":[{"text":"SBSDKPDFRenderer","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRenderer","kind":"identifier"}],"title":"SBSDKPDFRenderer","abstract":[{"text":"A class to render an ordered collection of images with or without performing HOCR.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocument":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocument"}],"abstract":[{"type":"text","text":"A thread-safe, mutable container for scanned pages of type "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","isActive":true},{"type":"text","text":"."}],"title":"SBSDKDocument"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentPage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentPage"}],"title":"SBSDKDocumentPage","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"abstract":[{"type":"text","text":"This class represents a scanned documents page."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentPage","url":"\/documentation\/scanbotsdk\/sbsdkdocumentpage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"renderDocumentAsync:output:completionHandler:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"renderDocumentAsync:output:completionHandler:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"renderDocumentAsync:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocument","text":"SBSDKDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"kind":"text","text":" "},{"text":"output:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"output"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"document","content":[{"inlineContent":[{"type":"text","text":"The document to be rendered to the PDF."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The output file URL.","type":"text"}],"type":"paragraph"}],"name":"output"}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","value":null,"op":"replace"},{"op":"replace","value":"renderDocumentAsync:output:completionHandler:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderDocumentAsync(_:output:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderDocumentAsync(_:output:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"renderDocumentAsync:output:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/title","value":"SBSDKPDFRenderer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/title","op":"replace","value":"SBSDKDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/fragments","value":[{"text":"SBSDKDocument","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocument\/navigatorTitle"},{"value":"SBSDKDocumentPage","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/fragments","op":"replace","value":[{"text":"SBSDKDocumentPage","kind":"identifier"}]},{"value":[{"text":"SBSDKDocumentPage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentPage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}