{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorage(_:indexSet:output:progress:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"renderImageStorage:indexSet:output:progress:error:"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRenderer(im)renderImageStorage:indexSet:output:progress:error:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"renderImageStorage(_:indexSet:output:progress:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"renderImageStorage","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"indexSet","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"symbolKind":"method"},"sections":[],"abstract":[{"type":"text","text":"Synchronously renders the images at the specified indices from the image storage into a PDF file"},{"text":" ","type":"text"},{"text":"with the given page size, and saves the PDF to the specified URL.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renderImageStorage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"imageStorage"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"indexSet","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"kind":"text","text":"? = nil) "},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The image store to take the images from."}],"type":"paragraph"}],"name":"imageStorage"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The indices of images in the image store you want to render into the PDF. Pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if all images must be rendered."}]}],"name":"indexSet"},{"name":"output","content":[{"type":"paragraph","inlineContent":[{"text":"The output file URL.","type":"text"}]}]},{"name":"progress","content":[{"inlineContent":[{"type":"text","text":"An optional "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","isActive":true,"type":"reference"},{"text":" object that can be observed.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Each page is made up of one image."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorage(_:indexset:output:progress:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorage(_:indexset:output:progress:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderImageStorage(_:indexSet:output:progress:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorage(_:indexSet:output:progress:)","navigatorTitle":[{"text":"renderImageStorage:indexSet:output:progress:error:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorage(_:indexset:output:progress:)","abstract":[{"type":"text","text":"Synchronously renders the images at the specified indices from the image storage into a PDF file"},{"text":" ","type":"text"},{"type":"text","text":"with the given page size, and saves the PDF to the specified URL."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderImageStorage","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","kind":"typeIdentifier","text":"SBSDKImageStoring"},{"text":", ","kind":"text"},{"text":"indexSet","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"renderImageStorage(_:indexSet:output:progress:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"url":"\/documentation\/scanbotsdk\/sbsdkprogress","abstract":[],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKProgress","kind":"identifier"}],"kind":"symbol","title":"SBSDKProgress"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageStoring"}],"navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"title":"SBSDKImageStoring","abstract":[{"text":"Protocol for an order-aware (array like) image storage.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer","abstract":[{"type":"text","text":"A class to render an ordered collection of images with or without performing HOCR."}],"kind":"symbol","title":"SBSDKPDFRenderer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRenderer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","type":"topic","abstract":[{"type":"text","text":"Version: 6.0.0"}],"url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"renderImageStorage:indexSet:output:progress:error:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"renderImageStorage:indexSet:output:progress:error:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"renderImageStorage:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"id<SBSDKImageStoring>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"imageStorage"},{"kind":"text","text":" "},{"text":"indexSet:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexSet","kind":"typeIdentifier","text":"NSIndexSet"},{"text":" *) ","kind":"text"},{"text":"indexSet","kind":"internalParam"},{"kind":"text","text":" "},{"text":"output:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"text":"output","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress:"},{"kind":"text","text":"("},{"text":"SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"},{"text":" *) ","kind":"text"},{"text":"progress","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"renderImageStorage:indexSet:output:progress:error:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorage(_:indexSet:output:progress:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"renderImageStorage:indexSet:output:progress:error:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorage(_:indexSet:output:progress:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title","value":"SBSDKProgress"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments","value":[{"kind":"identifier","text":"SBSDKProgress"}],"op":"replace"},{"value":"SBSDKImageStoring","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments","value":[{"text":"SBSDKImageStoring","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/title","op":"replace","value":"SBSDKPDFRenderer"},{"value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}