{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderscanneddocument(_:output:progress:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderscanneddocument(_:output:progress:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocument(_:output:progress:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderScannedDocument"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"document"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKScannedDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","kind":"typeIdentifier"},{"text":"? = nil) ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"document","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document to be rendered to the PDF."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The output file URL. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"the default PDF location of the scanned document will be used."}],"type":"paragraph"}],"name":"output"},{"name":"progress","content":[{"inlineContent":[{"type":"text","text":"An optional "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"},{"text":" object that can be observed.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Each page is made up of one image."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderScannedDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"renderScannedDocument:output:progress:error:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRenderer(im)renderScannedDocument:output:progress:error:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","title":"renderScannedDocument(_:output:progress:)","role":"symbol","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Synchronously renders the scanned document into a PDF file"},{"type":"text","text":" "},{"text":"with the given page size, and saves the PDF to the specified URL.","type":"text"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderScannedDocument(_:output:progress:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderScannedDocument(_:output:progress:)","kind":"symbol","abstract":[{"type":"text","text":"Synchronously renders the scanned document into a PDF file"},{"text":" ","type":"text"},{"text":"with the given page size, and saves the PDF to the specified URL.","type":"text"}],"role":"symbol","title":"renderScannedDocument(_:output:progress:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderScannedDocument","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"kind":"text","text":", "},{"text":"output","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderscanneddocument(_:output:progress:)","navigatorTitle":[{"text":"renderScannedDocument:output:progress:error:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer","title":"SBSDKPDFRenderer","url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer","abstract":[{"type":"text","text":"A class to render an ordered collection of images with or without performing HOCR."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRenderer","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRenderer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProgress":{"navigatorTitle":[{"text":"SBSDKProgress","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkprogress","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProgress","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","title":"SBSDKProgress"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKScannedDocument","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages.","type":"text"}],"title":"SBSDKScannedDocument","navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"renderScannedDocument:output:progress:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"renderScannedDocument:output:progress:error:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"renderScannedDocument:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"output:"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"output","kind":"internalParam"},{"kind":"text","text":" "},{"text":"progress:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress","text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKProgress"},{"text":" *) ","kind":"text"},{"text":"progress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"document","content":[{"type":"paragraph","inlineContent":[{"text":"The document to be rendered to the PDF.","type":"text"}]}]},{"name":"output","content":[{"inlineContent":[{"type":"text","text":"The output file URL. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"the default PDF location of the scanned document will be used."}],"type":"paragraph"}]},{"name":"progress","content":[{"inlineContent":[{"text":"An optional ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProgress"},{"text":" object that can be observed.","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the method succeeded, otherwise "},{"code":"NO","type":"codeVoice"},{"text":".","type":"text"}]}],"kind":"content"},"op":"add"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderScannedDocument(_:output:progress:)\/title","value":"renderScannedDocument:output:progress:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderScannedDocument(_:output:progress:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"renderScannedDocument:output:progress:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/title","value":"SBSDKPDFRenderer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/fragments","value":[{"text":"SBSDKPDFRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/title","value":"SBSDKProgress","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/fragments","value":[{"text":"SBSDKProgress","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKProgress"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProgress\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title","value":"SBSDKScannedDocument"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle","op":"replace","value":[{"text":"SBSDKScannedDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}