{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"renderImageStorageAsync","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"imageStorage"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","kind":"typeIdentifier","text":"SBSDKImageStoring"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexSet"},{"text":": ","kind":"text"},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"? = nil, "},{"text":"output","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"imageStorage","content":[{"inlineContent":[{"type":"text","text":"The image store to take the images from."}],"type":"paragraph"}]},{"name":"indexSet","content":[{"inlineContent":[{"type":"text","text":"The indices of images in the image store you want to render into the PDF. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if all images must be rendered."}],"type":"paragraph"}]},{"name":"output","content":[{"inlineContent":[{"text":"The output file URL.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the PDF file has been written to or "},{"code":"nil","type":"codeVoice"},{"text":" if the operation failed.","type":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Swift language it is used with structured concurrency (async\/await)."}]}]}],"abstract":[{"type":"text","text":"Asynchronously renders the images at the specified indices from the image storage into a PDF file and saves it to the specified URL."},{"type":"text","text":" "},{"text":"Each page is made up of one image.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorageasync(_:indexset:output:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorageasync(_:indexset:output:)"]}],"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"renderImageStorageAsync(_:indexSet:output:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderImageStorageAsync","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexSet"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRenderer(im)renderImageStorageAsync:indexSet:output:completionHandler:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"renderImageStorageAsync:indexSet:output:completionHandler:"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorageAsync(_:indexSet:output:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer","title":"SBSDKPDFRenderer","url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer","abstract":[{"type":"text","text":"A class to render an ordered collection of images with or without performing HOCR."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRenderer","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKPDFRenderer","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagestoring","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageStoring"}],"navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"kind":"symbol","title":"SBSDKImageStoring"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderImageStorageAsync(_:indexSet:output:)":{"navigatorTitle":[{"text":"renderImageStorageAsync:indexSet:output:completionHandler:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorageAsync(_:indexSet:output:)","title":"renderImageStorageAsync(_:indexSet:output:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"renderImageStorageAsync"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"SBSDKImageStoring","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexSet"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier","text":"IndexSet"},{"kind":"text","text":"?, "},{"text":"output","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Asynchronously renders the images at the specified indices from the image storage into a PDF file and saves it to the specified URL."},{"text":" ","type":"text"},{"type":"text","text":"Each page is made up of one image."}],"role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorageasync(_:indexset:output:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"renderImageStorageAsync:indexSet:output:completionHandler:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"renderImageStorageAsync:indexSet:output:completionHandler:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"renderImageStorageAsync:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<SBSDKImageStoring>","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKImageStoring"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"imageStorage"},{"text":" ","kind":"text"},{"text":"indexSet:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSIndexSet","preciseIdentifier":"c:objc(cs)NSIndexSet"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexSet"},{"kind":"text","text":" "},{"text":"output:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"text":"output","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"imageStorage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image store to take the images from."}]}]},{"name":"indexSet","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The indices of images in the image store you want to render into the PDF. Pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if all images must be rendered."}]}]},{"name":"output","content":[{"inlineContent":[{"type":"text","text":"The output file URL."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"value":null,"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/title","value":"SBSDKPDFRenderer"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/fragments","value":[{"text":"SBSDKPDFRenderer","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","op":"replace","value":"SBSDKImageStoring"},{"value":[{"kind":"identifier","text":"SBSDKImageStoring"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/navigatorTitle","value":[{"text":"SBSDKImageStoring","kind":"identifier"}]},{"op":"replace","value":"renderImageStorageAsync:indexSet:output:completionHandler:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorageAsync(_:indexSet:output:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"renderImageStorageAsync:indexSet:output:completionHandler:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorageAsync(_:indexSet:output:)\/fragments","op":"replace"}]}]}