{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"renderImageStorageAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"imageStorage","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","text":"SBSDKImageStoring"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexSet"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier","text":"IndexSet"},{"text":"? = nil, ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"imageStorage","content":[{"type":"paragraph","inlineContent":[{"text":"The image store to take the images from.","type":"text"}]}]},{"name":"indexSet","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The indices of images in the image store you want to render into the PDF. Pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if all images must be rendered."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt the PDF file. Pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if encryption is not required."}]}],"name":"encrypter"},{"content":[{"inlineContent":[{"type":"text","text":"The output file URL."}],"type":"paragraph"}],"name":"output"}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The URL the PDF file has been written to or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation failed."}]}],"kind":"content"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer"]]},"metadata":{"title":"renderImageStorageAsync(_:indexSet:encrypter:output:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"renderImageStorageAsync","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","kind":"typeIdentifier","text":"SBSDKImageStoring"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexSet"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":"?, ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"output"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"renderImageStorageAsync:indexSet:encrypter:output:completionHandler:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFRenderer(im)renderImageStorageAsync:indexSet:encrypter:output:completionHandler:","symbolKind":"method"},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorageAsync(_:indexSet:encrypter:output:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorageasync(_:indexset:encrypter:output:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorageasync(_:indexset:encrypter:output:)"]}],"abstract":[{"type":"text","text":"Asynchronously renders the images at the specified indices from the image storage into a PDF file and saves it to the specified URL."},{"text":" ","type":"text"},{"type":"text","text":"Each page is made up of one image."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCrypting"}],"navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}],"kind":"symbol","title":"SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer":{"navigatorTitle":[{"text":"SBSDKPDFRenderer","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPDFRenderer","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"SBSDKPDFRenderer","abstract":[{"type":"text","text":"A class to render an ordered collection of images with or without performing HOCR."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFRenderer/renderImageStorageAsync(_:indexSet:encrypter:output:)":{"title":"renderImageStorageAsync(_:indexSet:encrypter:output:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"renderImageStorageAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKImageStoring","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKImageStoring","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexSet"},{"kind":"text","text":": "},{"text":"IndexSet","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV"},{"text":"?, ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"output"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"renderImageStorageAsync:indexSet:encrypter:output:completionHandler:","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfrenderer\/renderimagestorageasync(_:indexset:encrypter:output:)","abstract":[{"type":"text","text":"Asynchronously renders the images at the specified indices from the image storage into a PDF file and saves it to the specified URL."},{"type":"text","text":" "},{"text":"Each page is made up of one image.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFRenderer\/renderImageStorageAsync(_:indexSet:encrypter:output:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageStoring":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageStoring","type":"topic","navigatorTitle":[{"text":"SBSDKImageStoring","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol for an order-aware (array like) image storage."}],"role":"symbol","title":"SBSDKImageStoring","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageStoring","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagestoring"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"renderImageStorageAsync:indexSet:encrypter:output:completionHandler:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"renderImageStorageAsync:indexSet:encrypter:output:completionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"renderImageStorageAsync:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKImageStoring","text":"id<SBSDKImageStoring>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"imageStorage"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexSet:"},{"text":"(","kind":"text"},{"text":"NSIndexSet","preciseIdentifier":"c:objc(cs)NSIndexSet","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexSet","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"encrypter:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"encrypter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"output:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"output","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title","value":"SBSDKStorageCrypting"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/title","value":"SBSDKPDFRenderer"},{"value":[{"kind":"identifier","text":"SBSDKPDFRenderer"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorageAsync(_:indexSet:encrypter:output:)\/title","value":"renderImageStorageAsync:indexSet:encrypter:output:completionHandler:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFRenderer~1renderImageStorageAsync(_:indexSet:encrypter:output:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"renderImageStorageAsync:indexSet:encrypter:output:completionHandler:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/title","value":"SBSDKImageStoring"},{"value":[{"text":"SBSDKImageStoring","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageStoring\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}