{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior\/ignore","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignore"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehaviorIgnore","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKUpcEanExtensionBehavior.ignore","externalID":"c:@M@ScanbotSDK@E@SBSDKUpcEanExtensionBehavior@SBSDKUpcEanExtensionBehaviorIgnore","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignore"}],"roleHeading":"Case","symbolKind":"case"},"sections":[],"abstract":[{"type":"text","text":"Always ignore the extension."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/ignore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/ignore"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior","title":"SBSDKUpcEanExtensionBehavior","role":"symbol","abstract":[{"text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior/ignore":{"role":"symbol","type":"topic","title":"SBSDKUpcEanExtensionBehavior.ignore","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior\/ignore","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorIgnore"}],"abstract":[{"text":"Always ignore the extension.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignore"}],"url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/ignore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKUpcEanExtensionBehaviorIgnore","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorIgnore"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorIgnore"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKUpcEanExtensionBehavior","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/title"},{"value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/fragments"},{"value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle"},{"value":"SBSDKUpcEanExtensionBehaviorIgnore","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior~1ignore\/title"},{"value":[{"text":"SBSDKUpcEanExtensionBehaviorIgnore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior~1ignore\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}