{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/tesseract"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemode\/tesseract"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkocrenginemode\/tesseract"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tesseract","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"SBSDKOCREngineModeTesseract","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScanbotSDK"}],"title":"SBSDKOCREngineMode.tesseract","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKOCREngineMode@SBSDKOCREngineModeTesseract"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode/tesseract":{"abstract":[{"type":"text","text":"The legacy OCR mode using Tesseract. Slower, more error prone, but it supports more languages."}],"url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode\/tesseract","role":"symbol","type":"topic","title":"SBSDKOCREngineMode.tesseract","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tesseract"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode\/tesseract","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineModeTesseract"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOCREngineMode":{"abstract":[{"text":"An enum describing the modes of the optical character recognition engine.","type":"text"}],"kind":"symbol","type":"topic","title":"SBSDKOCREngineMode","url":"\/documentation\/scanbotsdk\/sbsdkocrenginemode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKOCREngineMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOCREngineMode"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOCREngineMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKOCREngineModeTesseract"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKOCREngineModeTesseract","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKOCREngineModeTesseract"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1tesseract\/title","op":"replace","value":"SBSDKOCREngineModeTesseract"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode~1tesseract\/fragments","op":"replace","value":[{"text":"SBSDKOCREngineModeTesseract","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/title","op":"replace","value":"SBSDKOCREngineMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/fragments","op":"replace","value":[{"text":"SBSDKOCREngineMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOCREngineMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKOCREngineMode","kind":"identifier"}]}]}]}