{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEngineMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode","kind":"typeIdentifier","text":"SBSDKDocumentScannerEngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKDocumentScannerEngineMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"engineMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"processingMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","kind":"typeIdentifier","text":"SBSDKProcessingMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKProcessingMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"processingMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"parameters:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters","kind":"typeIdentifier","text":"SBSDKDocumentScannerParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parameters"},{"kind":"text","text":" "},{"kind":"identifier","text":"partiallyVisibleDocumentConfiguration:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration","kind":"typeIdentifier","text":"SBSDKPartiallyVisibleDocumentConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"partiallyVisibleDocumentConfiguration"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerconfiguration\/initwithenginemode:processingmode:parameters:partiallyvisibledocumentconfiguration:"]}],"kind":"symbol","metadata":{"title":"initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","navigatorTitle":[{"text":"initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerConfiguration(im)initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerConfiguration\/initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerConfiguration/initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","kind":"identifier"}],"title":"initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerconfiguration\/initwithenginemode:processingmode:parameters:partiallyvisibledocumentconfiguration:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerConfiguration\/initWithEngineMode:processingMode:parameters:partiallyVisibleDocumentConfiguration:","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKProcessingMode":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKProcessingMode","abstract":[{"text":"Scanners typically can produce better results from a single image if they are allowed to spend a longer time analyzing it.","type":"text"},{"text":" ","type":"text"},{"text":"On the other hand, scanners can produce even better results if they can analyze multiple images of the same subject and cross-check and combine the results.","type":"text"},{"text":" ","type":"text"},{"text":"The processing mode tells the scanner whether to optimize for single or multiple images of a subject.","type":"text"}],"kind":"symbol","type":"topic","title":"SBSDKProcessingMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKProcessingMode","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkprocessingmode","navigatorTitle":[{"text":"SBSDKProcessingMode","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters","type":"topic","title":"SBSDKDocumentScannerParameters","abstract":[{"text":"Parameters for the document scanner.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"abstract":[{"type":"text","text":"Configuration for handling partially visible documents."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPartiallyVisibleDocumentConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"title":"SBSDKPartiallyVisibleDocumentConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkpartiallyvisibledocumentconfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerConfiguration":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerConfiguration","title":"SBSDKDocumentScannerConfiguration","abstract":[{"text":"Configuration for the document scanner.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerconfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerEngineMode":{"title":"SBSDKDocumentScannerEngineMode","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerenginemode","abstract":[{"type":"text","text":"Engines for document scanning."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerEngineMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentScannerEngineMode"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineMode"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/title","value":"SBSDKProcessingMode","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/fragments","value":[{"text":"SBSDKProcessingMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKProcessingMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKProcessingMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/title","value":"SBSDKDocumentScannerParameters","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/fragments","value":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"op":"replace"},{"value":"SBSDKPartiallyVisibleDocumentConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title"},{"value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle"},{"value":"SBSDKDocumentScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerConfiguration\/fragments"},{"value":[{"text":"SBSDKDocumentScannerConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerConfiguration\/navigatorTitle"},{"value":"SBSDKDocumentScannerEngineMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerEngineMode"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerEngineMode\/navigatorTitle"}]}]}