{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(textLineRecognizerViewController:didValidateResult:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textLineRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didValidate"},{"kind":"text","text":" "},{"text":"result","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKGenericTextLineRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","isActive":true},{"text":" that has recognized and validated the text line(s).","type":"text"}]}]},{"name":"result","content":[{"inlineContent":[{"type":"text","text":"The result of the recognition."}],"type":"paragraph"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate\/textlinerecognizerviewcontroller(_:didvalidate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate\/textlinerecognizerviewcontroller(_:didvalidate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate\/textLineRecognizerViewController(_:didValidate:)"},"abstract":[{"text":"Informs the delegate that text line(s) has been recognized and validated and passes the result.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textLineRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController"},{"kind":"text","text":", "},{"text":"didValidate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","text":"SBSDKGenericTextLineRecognizerResult"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","title":"textLineRecognizerViewController(_:didValidate:)","navigatorTitle":[{"kind":"identifier","text":"textLineRecognizerViewController:didValidateResult:"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKGenericTextLineRecognizerViewControllerDelegate(im)textLineRecognizerViewController:didValidateResult:","required":true,"symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewControllerDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate","abstract":[{"type":"text","text":"The delegation protocol for "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","type":"reference"},{"type":"text","text":"."}],"type":"topic","title":"SBSDKGenericTextLineRecognizerViewControllerDelegate","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate","role":"symbol","navigatorTitle":[{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewControllerDelegate/textLineRecognizerViewController(_:didValidate:)":{"abstract":[{"text":"Informs the delegate that text line(s) has been recognized and validated and passes the result.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewControllerDelegate\/textLineRecognizerViewController(_:didValidate:)","title":"textLineRecognizerViewController(_:didValidate:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textLineRecognizerViewController"},{"text":"(","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didValidate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","text":"SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"textLineRecognizerViewController:didValidateResult:","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontrollerdelegate\/textlinerecognizerviewcontroller(_:didvalidate:)","required":true,"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}],"abstract":[{"text":"A ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":" subclass to show a camera screen with the text line recognizer.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController","type":"topic","title":"SBSDKGenericTextLineRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerViewController"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericTextLineRecognizerResult":{"abstract":[{"type":"text","text":"A class describing the result of the generic text line recognizer."}],"type":"topic","title":"SBSDKGenericTextLineRecognizerResult","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenerictextlinerecognizerresult","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResult"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 5.2.1","type":"text"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"textLineRecognizerViewController:didValidateResult:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textLineRecognizerViewController:didValidateResult:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textLineRecognizerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericTextLineRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didValidateResult:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKGenericTextLineRecognizerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericTextLineRecognizerResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericTextLineRecognizerResult"},{"kind":"text","text":" *) "},{"text":"result","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate\/title","op":"replace","value":"SBSDKGenericTextLineRecognizerViewControllerDelegate"},{"op":"replace","value":[{"text":"SBSDKGenericTextLineRecognizerViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate~1textLineRecognizerViewController(_:didValidate:)\/title","value":"textLineRecognizerViewController:didValidateResult:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewControllerDelegate~1textLineRecognizerViewController(_:didValidate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textLineRecognizerViewController:didValidateResult:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/title","value":"SBSDKGenericTextLineRecognizerViewController"},{"value":[{"text":"SBSDKGenericTextLineRecognizerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult\/title","value":"SBSDKGenericTextLineRecognizerResult"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericTextLineRecognizerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericTextLineRecognizerResult"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}