{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgs1handling\/parse"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgs1handling\/parse"]}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parse"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKGS1Handling@SBSDKGS1HandlingParse","role":"symbol","navigatorTitle":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"SBSDKGS1Handling.parse","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"parse","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"This is the default. GS1 messages are converted to the machine-readable format per","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the GS1 spec (the special FNC1 character is converted to ASCII \\x1D)."},{"text":" ","type":"text"},{"text":"The implied 01 AI key is prepended to DataBar results.","type":"text"},{"type":"text","text":" "},{"text":"No validation is performed.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/parse","interfaceLanguage":"swift"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling/parse":{"url":"\/documentation\/scanbotsdk\/sbsdkgs1handling\/parse","title":"SBSDKGS1Handling.parse","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling\/parse","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parse"}],"abstract":[{"text":"This is the default. GS1 messages are converted to the machine-readable format per","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the GS1 spec (the special FNC1 character is converted to ASCII \\x1D)."},{"text":" ","type":"text"},{"text":"The implied 01 AI key is prepended to DataBar results.","type":"text"},{"text":" ","type":"text"},{"text":"No validation is performed.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGS1Handling":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKGS1Handling","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgs1handling","abstract":[{"type":"text","text":"GS1 message handling options. The GS1 standard defines a"},{"text":" ","type":"text"},{"type":"text","text":"a key-value format for business-centric data"},{"type":"text","text":" "},{"type":"text","text":"that can be encoded into many 1D and 2D barcode types."},{"type":"text","text":" "},{"text":"https:\/\/ref.gs1.org\/standards\/genspecs\/","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGS1Handling","title":"SBSDKGS1Handling","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGS1Handling"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SBSDKGS1HandlingParse","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKGS1HandlingParse"}],"platforms":["iOS"]}]}},{"value":"SBSDKGS1HandlingParse","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1parse\/title","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGS1HandlingParse","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling~1parse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/title","value":"SBSDKGS1Handling"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/fragments","value":[{"kind":"identifier","text":"SBSDKGS1Handling"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGS1Handling\/navigatorTitle","value":[{"text":"SBSDKGS1Handling","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}