{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm\/hash"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm(py)hash","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"hash"}],"title":"hash"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/hash","interfaceLanguage":"occ"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm":{"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm","title":"SBSDKMSIPlesseyChecksumAlgorithm","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}],"abstract":[{"text":"Checksum algorithm for MSI_PLESSEY.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMSIPlesseyChecksumAlgorithm/hash":{"type":"topic","title":"hash","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmsiplesseychecksumalgorithm\/hash","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/hash","fragments":[{"kind":"identifier","text":"hash"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/title","op":"replace","value":"SBSDKMSIPlesseyChecksumAlgorithm"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/fragments","op":"replace","value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}]}]}]}