{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorGuidanceStates(im)isEqual:","modules":[{"name":"ScanbotSDK"}],"title":"isEqual:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/isEqual:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/isequal:"]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates":{"navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorGuidanceStates","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates","title":"SBSDKUI2DocumentDataExtractorGuidanceStates","kind":"symbol","abstract":[{"text":"Configure the captions of the user guidance hints for different scanning states.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorGuidanceStates","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorGuidanceStates/isEqual:":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorguidancestates\/isequal:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorGuidanceStates\/isEqual:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic","title":"isEqual:","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2DocumentDataExtractorGuidanceStates","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/title"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorGuidanceStates","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2DocumentDataExtractorGuidanceStates","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorGuidanceStates\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}