{"kind":"symbol","abstract":[{"type":"text","text":"Initializes a new TIFF image generator with the specified parameters and encrypter."}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters","text":"SBSDKTIFFGeneratorParameters","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"useEncryptionIfAvailable","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"initWithParameters:useEncryptionIfAvailable:error:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGenerator(im)initWithParameters:useEncryptionIfAvailable:error:","role":"symbol","roleHeading":"Initializer","title":"init(parameters:useEncryptionIfAvailable:)","symbolKind":"init","modules":[{"name":"ScanbotSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","kind":"typeIdentifier","text":"SBSDKTIFFGeneratorParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useEncryptionIfAvailable"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"},{"parameters":[{"name":"parameters","content":[{"inlineContent":[{"text":"The parameters to be used when generating TIFF images.","type":"text"}],"type":"paragraph"}]},{"name":"useEncryptionIfAvailable","content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" and a crypting provider is set in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider"},{"text":", the generated TIFF images will be encrypted.","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/init(parameters:useEncryptionIfAvailable:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/init(parameters:useencryptionifavailable:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffgenerator\/init(parameters:useencryptionifavailable:)"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/Scanbot/defaultCryptingProvider":{"navigatorTitle":[{"text":"defaultCryptingProvider","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultCryptingProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/scanbotsdk\/scanbot\/defaultcryptingprovider","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","title":"defaultCryptingProvider","role":"symbol","type":"topic","abstract":[{"text":"The SDK-wide encryption provider for storing image data to disk. Defaults to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", no encryption used.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator/init(parameters:useEncryptionIfAvailable:)":{"url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator\/init(parameters:useencryptionifavailable:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator\/init(parameters:useEncryptionIfAvailable:)","abstract":[{"text":"Initializes a new TIFF image generator with the specified parameters and encrypter.","type":"text"}],"type":"topic","kind":"symbol","title":"init(parameters:useEncryptionIfAvailable:)","navigatorTitle":[{"kind":"identifier","text":"initWithParameters:useEncryptionIfAvailable:error:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKTIFFGeneratorParameters","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useEncryptionIfAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGeneratorParameters":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"type":"topic","abstract":[{"type":"text","text":"TIFF generator parameters."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"title":"SBSDKTIFFGeneratorParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffgeneratorparameters","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFGenerator":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGenerator","title":"SBSDKTIFFGenerator","navigatorTitle":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"abstract":[{"text":"A class that converts images to (multipage) TIFF images.","type":"text"},{"text":" ","type":"text"},{"text":"You can specify the TIFF parameters such as compression algorithm, binarization, metadata etc.","type":"text"},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider"},{"type":"text","text":" is set, the generated TIFF files will be encrypted using the specified crypting provider."}],"url":"\/documentation\/scanbotsdk\/sbsdktiffgenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithParameters:useEncryptionIfAvailable:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParameters:useEncryptionIfAvailable:error:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFGeneratorParameters","text":"SBSDKTIFFGeneratorParameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFGeneratorParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"useEncryptionIfAvailable:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"useEncryptionIfAvailable","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"parameters","content":[{"inlineContent":[{"type":"text","text":"The parameters to be used when generating TIFF images."}],"type":"paragraph"}]},{"name":"useEncryptionIfAvailable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":" and a crypting provider is set in "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/Scanbot\/defaultCryptingProvider","type":"reference","isActive":true},{"type":"text","text":", the generated TIFF images will be encrypted."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"defaultCryptingProvider","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/title"},{"value":[{"kind":"identifier","text":"defaultCryptingProvider"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1Scanbot~1defaultCryptingProvider\/fragments"},{"value":"initWithParameters:useEncryptionIfAvailable:error:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1init(parameters:useEncryptionIfAvailable:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParameters:useEncryptionIfAvailable:error:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator~1init(parameters:useEncryptionIfAvailable:)\/fragments"},{"value":"SBSDKTIFFGeneratorParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/title"},{"value":[{"kind":"identifier","text":"SBSDKTIFFGeneratorParameters"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/fragments"},{"value":[{"text":"SBSDKTIFFGeneratorParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGeneratorParameters\/navigatorTitle"},{"value":"SBSDKTIFFGenerator","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/title"},{"value":[{"text":"SBSDKTIFFGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTIFFGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFGenerator\/navigatorTitle"}]}]}