{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","text":"SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"updateCustomView"},{"kind":"text","text":" "},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeScannerResult","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"selected","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The barcode tracking overlay controller that the tracking view belongs to."}],"type":"paragraph"}]},{"name":"view","content":[{"inlineContent":[{"text":"The custom tracking view.","type":"text"}],"type":"paragraph"}]},{"name":"barcode","content":[{"type":"paragraph","inlineContent":[{"text":"The barcode that is represented by the custom tracking view.","type":"text"}]}]},{"name":"barcodeFrame","content":[{"type":"paragraph","inlineContent":[{"text":"The bounding rectangle of the barcode in view coordinates.","type":"text"}]}]},{"name":"selected","content":[{"type":"paragraph","inlineContent":[{"text":"Whether the barcode is selected or not.","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:updatecustomview:for:barcodeframe:selected:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:updatecustomview:for:barcodeframe:selected:)"]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:selected:"}],"symbolKind":"method","required":true,"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKBarcodeTrackingOverlayControllerDelegate(im)barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:selected:","role":"symbol","title":"barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:selected:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"barcodeTrackingOverlay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController"},{"kind":"text","text":", "},{"text":"updateCustomView","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"barcodeFrame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"selected"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:selected:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Informs the delegate to update the custom tracking view for the given barcode."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 5.2.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayControllerDelegate":{"title":"SBSDKBarcodeTrackingOverlayControllerDelegate","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate","role":"symbol","abstract":[{"text":"The delegation protocol for the barcode tracking overlay controller.","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayControllerDelegate"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayController":{"role":"symbol","abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing detected barcodes."},{"type":"text","text":" "},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The overlay can be used to highlight and select barcodes based on user input."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontroller","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"title":"SBSDKBarcodeTrackingOverlayController"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeScannerResult":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodescannerresult","kind":"symbol","title":"SBSDKBarcodeScannerResult","abstract":[{"text":"This class encapsulates the result of a barcode detection.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerResult","navigatorTitle":[{"text":"SBSDKBarcodeScannerResult","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKBarcodeTrackingOverlayControllerDelegate/barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:selected:)":{"title":"barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:selected:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayControllerDelegate\/barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:selected:)","required":true,"abstract":[{"text":"Informs the delegate to update the custom tracking view for the given barcode.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkbarcodetrackingoverlaycontrollerdelegate\/barcodetrackingoverlay(_:updatecustomview:for:barcodeframe:selected:)","navigatorTitle":[{"text":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:selected:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barcodeTrackingOverlay"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","text":"SBSDKBarcodeTrackingOverlayController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"updateCustomView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barcodeFrame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"selected","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:selected:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:selected:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"barcodeTrackingOverlay:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKBarcodeTrackingOverlayController","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateCustomView:"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" *) ","kind":"text"},{"text":"view","kind":"internalParam"},{"kind":"text","text":" "},{"text":"for:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKBarcodeScannerResult","kind":"typeIdentifier","text":"SBSDKBarcodeScannerResult","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKBarcodeScannerResult"},{"text":" *) ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeFrame:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"barcodeFrame"},{"text":" ","kind":"text"},{"text":"selected:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"selected","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/title","op":"replace","value":"SBSDKBarcodeTrackingOverlayControllerDelegate"},{"value":[{"text":"SBSDKBarcodeTrackingOverlayControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate\/fragments"},{"value":"SBSDKBarcodeTrackingOverlayController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayController\/fragments","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerResult\/title","value":"SBSDKBarcodeScannerResult","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeScannerResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:selected:)\/title","value":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:selected:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKBarcodeTrackingOverlayControllerDelegate~1barcodeTrackingOverlay(_:updateCustomView:for:barcodeFrame:selected:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"barcodeTrackingOverlay:updateCustomView:for:barcodeFrame:selected:","kind":"identifier"}]}]}]}