{"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractor(im)extractFromImage:useLiveMode:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"extractFromImage:useLiveMode:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"extract","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"text":"useLiveMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","text":"SBSDKDocumentDataExtractionResult"},{"text":"?","kind":"text"}],"title":"extract(from:useLiveMode:)"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/extract(from:uselivemode:)-6cmve"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/extract(from:uselivemode:)-6cmve"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(extractFromImage:useLiveMode:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"extract","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"text":"useLiveMode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false) -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","text":"SBSDKDocumentDataExtractionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to extract from."}]}],"name":"image"},{"name":"useLiveMode","content":[{"inlineContent":[{"type":"text","text":"Whether you want to run in live mode or single shot mode."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"The extraction result."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor\/extract(from:useLiveMode:)-6cmve","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor"]]},"abstract":[{"type":"text","text":"Extracts generic documents data on a "},{"type":"codeVoice","code":"UIImage"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractionResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","kind":"symbol","abstract":[{"text":"Contains the result of running the generic document extractor.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractionresult","title":"SBSDKDocumentDataExtractionResult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor/extract(from:useLiveMode:)-6cmve":{"title":"extract(from:useLiveMode:)","role":"symbol","navigatorTitle":[{"text":"extractFromImage:useLiveMode:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Extracts generic documents data on a ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor\/extract(from:useLiveMode:)-6cmve","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/extract(from:uselivemode:)-6cmve","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extract","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"useLiveMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"SBSDKDocumentDataExtractionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor":{"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor","role":"symbol","abstract":[{"text":"A class to extract generic documents data on various image sources.","type":"text"},{"type":"text","text":" "},{"text":"Extracts the sub-documents, field names and field values from many types of documents e.g. German passports, ID cards, driver’s licenses.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"title":"SBSDKDocumentDataExtractor","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"extractFromImage:useLiveMode:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"extractFromImage:useLiveMode:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractionResult","text":"SBSDKDocumentDataExtractionResult"},{"kind":"text","text":" *) "},{"text":"extractFromImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLiveMode:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"useLiveMode","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The image to extract from."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Whether you want to run in live mode or single shot mode."}],"type":"paragraph"}],"name":"useLiveMode"}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The extraction result.","type":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/title","value":"SBSDKDocumentDataExtractionResult"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractionResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractionResult\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractionResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor~1extract(from:useLiveMode:)-6cmve\/title","op":"replace","value":"extractFromImage:useLiveMode:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor~1extract(from:useLiveMode:)-6cmve\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extractFromImage:useLiveMode:"}]},{"op":"replace","value":"SBSDKDocumentDataExtractor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}]}]}]}