{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/resetdocumentaccumulation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/resetdocumentaccumulation()"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor\/resetDocumentAccumulation()"},"kind":"symbol","metadata":{"title":"resetDocumentAccumulation()","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetDocumentAccumulation","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"resetDocumentAccumulation","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractor(im)resetDocumentAccumulation","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Resets the recognized-documents-accumulator for live detection.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetDocumentAccumulation","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"title":"SBSDKDocumentDataExtractor","abstract":[{"type":"text","text":"A class to extract generic documents data on various image sources."},{"type":"text","text":" "},{"type":"text","text":"Extracts the sub-documents, field names and field values from many types of documents e.g. German passports, ID cards, driver’s licenses."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor/resetDocumentAccumulation()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetDocumentAccumulation","kind":"identifier"},{"text":"()","kind":"text"}],"title":"resetDocumentAccumulation()","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Resets the recognized-documents-accumulator for live detection."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor\/resetDocumentAccumulation()","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/resetdocumentaccumulation()","role":"symbol","navigatorTitle":[{"text":"resetDocumentAccumulation","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"resetDocumentAccumulation","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetDocumentAccumulation"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"resetDocumentAccumulation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentDataExtractor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/navigatorTitle"},{"op":"replace","value":"resetDocumentAccumulation","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor~1resetDocumentAccumulation()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetDocumentAccumulation"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor~1resetDocumentAccumulation()\/fragments"}]}]}