{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration\/initwithimagevisible:titleselected:subtitleselected:titledeselected:subtitledeselected:backgroundselected:backgrounddeselected:"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration\/initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeItemConfiguration(im)initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImageVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"imageVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"titleSelected:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"titleSelected","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"subtitleSelected:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"subtitleSelected","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"titleDeselected:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"titleDeselected","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"subtitleDeselected:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText"},{"text":" *) ","kind":"text"},{"text":"subtitleDeselected","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundSelected:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle"},{"text":" *) ","kind":"text"},{"text":"backgroundSelected","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundDeselected:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","text":"SBSDKUI2PolygonStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2PolygonStyle"},{"text":" *) ","kind":"text"},{"text":"backgroundDeselected","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2PolygonStyle":{"type":"topic","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2PolygonStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2polygonstyle","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the polygon appearance."}],"title":"SBSDKUI2PolygonStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2PolygonStyle"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration","title":"SBSDKUI2BarcodeItemConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}],"role":"symbol","abstract":[{"text":"Configuration of the barcode info box displayed in the camera preview.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeItemConfiguration/initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeItemConfiguration\/initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodeitemconfiguration\/initwithimagevisible:titleselected:subtitleselected:titledeselected:subtitledeselected:backgroundselected:backgrounddeselected:","title":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithImageVisible:titleSelected:subtitleSelected:titleDeselected:subtitleDeselected:backgroundSelected:backgroundDeselected:","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"title":"SBSDKUI2StyledText","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"type":"topic","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/title","op":"replace","value":"SBSDKUI2PolygonStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/fragments","op":"replace","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2PolygonStyle\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2PolygonStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/title","op":"replace","value":"SBSDKUI2BarcodeItemConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeItemConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeItemConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2BarcodeItemConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title","op":"replace","value":"SBSDKUI2StyledText"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments","op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]}]}]}