{"metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight\/!=(_:_:)"],"anchor":"Operators","title":"Operators","generated":true}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight\/Equatable-Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CollapsedVisibleHeight":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}],"title":"SBSDKUI2CollapsedVisibleHeight","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight","abstract":[{"type":"text","text":"Configuration of the barcodes result sheet’s height while collapsed."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CollapsedVisibleHeight/!=(_:_:)":{"title":"!=(_:_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CollapsedVisibleHeight\/!=(_:_:)","url":"\/documentation\/scanbotsdk\/sbsdkui2collapsedvisibleheight\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/title","value":"SBSDKUI2CollapsedVisibleHeight"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CollapsedVisibleHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CollapsedVisibleHeight\/navigatorTitle","value":[{"text":"SBSDKUI2CollapsedVisibleHeight","kind":"identifier"}]}]}]}