{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule\/Equatable-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule"]]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameramodule\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","topicSections":[{"anchor":"Operators","generated":true,"title":"Operators","identifiers":["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule\/!=(_:_:)"]}],"metadata":{"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraModule/!=(_:_:)":{"title":"!=(_:_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule\/!=(_:_:)","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameramodule\/!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2CameraModule":{"kind":"symbol","abstract":[{"type":"text","text":"Determines which camera module to use on start-up."}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2CameraModule","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"title":"SBSDKUI2CameraModule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2cameramodule"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2CameraModule","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/title"},{"op":"replace","value":[{"text":"SBSDKUI2CameraModule","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CameraModule"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2CameraModule\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}