{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsmanager\/unsubscribe(_:)"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsmanager\/unsubscribe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"subscriber"},{"text":": ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAnalyticsSubscriber"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsManager\/unsubscribe(_:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsManager"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKAnalyticsSubscriber","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAnalyticsSubscriber"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","title":"unsubscribe(_:)","navigatorTitle":[{"kind":"identifier","text":"unsubscribe:"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKAnalyticsManager(im)unsubscribe:","role":"symbol"},"abstract":[{"type":"text","text":"Unsubscribes a subscriber from receiving analytics events."}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsManager/unsubscribe(_:)":{"navigatorTitle":[{"text":"unsubscribe:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"SBSDKAnalyticsSubscriber","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"unsubscribe(_:)","abstract":[{"type":"text","text":"Unsubscribes a subscriber from receiving analytics events."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsManager\/unsubscribe(_:)","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsmanager\/unsubscribe(_:)","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"text":"Version: 7.1.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsSubscriber":{"type":"topic","abstract":[{"type":"text","text":"The subscriber that is being tracked."}],"title":"SBSDKAnalyticsSubscriber","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticssubscriber","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsSubscriber"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKAnalyticsManager":{"role":"symbol","kind":"symbol","abstract":[{"type":"codeVoice","code":"SBSDKAnalyticsManager"},{"text":" is a singleton class that manages analytics events within the Scanbot SDK.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKAnalyticsManager"}],"title":"SBSDKAnalyticsManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAnalyticsManager"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkanalyticsmanager","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKAnalyticsManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"unsubscribe:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unsubscribe:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"unsubscribe:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotBarcodeScannerSDK@objc(pl)SBSDKAnalyticsSubscriber","text":"id<SBSDKAnalyticsSubscriber>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"subscriber"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"unsubscribe:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager~1unsubscribe(_:)\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager~1unsubscribe(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"unsubscribe:","kind":"identifier"}],"op":"replace"},{"value":"SBSDKAnalyticsSubscriber","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsSubscriber\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsSubscriber\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKAnalyticsSubscriber"}]},{"value":[{"text":"SBSDKAnalyticsSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsSubscriber\/navigatorTitle","op":"replace"},{"op":"replace","value":"SBSDKAnalyticsManager","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager\/fragments","value":[{"text":"SBSDKAnalyticsManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKAnalyticsManager\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAnalyticsManager"}]}]}]}