{"sections":[],"metadata":{"modules":[{"name":"ScanbotDocumentScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"applicationStateDidChangeHandler"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationStateDidChangeHandler"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKApplicationState","kind":"typeIdentifier","text":"SBSDKApplicationState"},{"kind":"text","text":") -> ())?"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKBaseScannerViewController(py)applicationStateDidChangeHandler","title":"applicationStateDidChangeHandler"},"kind":"symbol","abstract":[{"type":"text","text":"A block being called when the application status was changed. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/applicationStateDidChangeHandler"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationStateDidChangeHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"SBSDKApplicationState","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKApplicationState","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKApplicationState"},{"kind":"text","text":") -> ())?"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/applicationstatedidchangehandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/applicationstatedidchangehandler"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKApplicationState":{"title":"SBSDKApplicationState","navigatorTitle":[{"text":"SBSDKApplicationState","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkapplicationstate","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKApplicationState","kind":"symbol","type":"topic","abstract":[{"text":"An enum describing the current state of the app.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKApplicationState","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController/applicationStateDidChangeHandler":{"abstract":[{"type":"text","text":"A block being called when the application status was changed. Defaults to "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationStateDidChangeHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"SBSDKApplicationState","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKApplicationState"},{"kind":"text","text":") -> ())?"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller\/applicationstatedidchangehandler","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController\/applicationStateDidChangeHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"applicationStateDidChangeHandler"}],"title":"applicationStateDidChangeHandler"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKBaseScannerViewController":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerViewController"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKBaseScannerViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkbasescannerviewcontroller","kind":"symbol","title":"SBSDKBaseScannerViewController","abstract":[{"text":"A highly customizable camera view controller that delivers a basic camera functionality along with video","type":"text"},{"text":" ","type":"text"},{"text":"frame extraction and preprocessing, orientation correction and still image capturing.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerViewController"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"applicationStateDidChangeHandler"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"applicationStateDidChangeHandler"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":"applicationStateDidChangeHandler","kind":"identifier"},{"text":")(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKApplicationState","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKApplicationState","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKApplicationState"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKApplicationState\/title","op":"replace","value":"SBSDKApplicationState"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKApplicationState\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKApplicationState"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKApplicationState\/navigatorTitle","value":[{"text":"SBSDKApplicationState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1applicationStateDidChangeHandler\/title","value":"applicationStateDidChangeHandler"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController~1applicationStateDidChangeHandler\/fragments","value":[{"text":"applicationStateDidChangeHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/title","value":"SBSDKBaseScannerViewController"},{"value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/fragments"},{"value":[{"text":"SBSDKBaseScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKBaseScannerViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}