{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage"]]},"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:cryptingprovider:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:cryptingprovider:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"? = SBSDKStorageLocation(), ","kind":"text"},{"text":"cryptingProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}]}],"name":"storageLocation"},{"content":[{"inlineContent":[{"type":"text","text":"If non-nil, overrides the default image encryption provider."}],"type":"paragraph"}],"name":"cryptingProvider"}],"kind":"parameters"}],"metadata":{"title":"init(storageLocation:cryptingProvider:)","symbolKind":"init","navigatorTitle":[{"text":"initWithStorageLocation:cryptingProvider:","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKKeyedImageStorage(im)initWithStorageLocation:cryptingProvider:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"storageLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cryptingProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"SBSDKStorageCryptingProvider","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","role":"symbol"},"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:cryptingProvider:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"SBSDKKeyedImageStorage"},{"type":"text","text":" at the given storage location."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageLocation":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Descriptor and helper class for describing and creating a directory on the file system."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragelocation","navigatorTitle":[{"text":"SBSDKStorageLocation","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageLocation","kind":"identifier"}],"title":"SBSDKStorageLocation"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage","role":"symbol","abstract":[{"text":"A simple thread-safe multiple-reader-single-writer key-value fashioned disk image cache class.","type":"text"},{"text":" ","type":"text"},{"text":"Manages images in a dictionary-like fashion.","type":"text"}],"title":"SBSDKKeyedImageStorage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKKeyedImageStorage"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKKeyedImageStorage/init(storageLocation:cryptingProvider:)":{"abstract":[{"text":"Initializes a new ","type":"text"},{"code":"SBSDKKeyedImageStorage","type":"codeVoice"},{"type":"text","text":" at the given storage location."}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKKeyedImageStorage\/init(storageLocation:cryptingProvider:)","role":"symbol","type":"topic","title":"init(storageLocation:cryptingProvider:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"storageLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cryptingProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCryptingProvider","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStorageLocation:cryptingProvider:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkkeyedimagestorage\/init(storagelocation:cryptingprovider:)","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCryptingProvider":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCryptingProvider","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecryptingprovider","role":"symbol","abstract":[{"type":"text","text":"Protocol for providing a storage crypting object."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}],"title":"SBSDKStorageCryptingProvider"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithStorageLocation:cryptingProvider:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithStorageLocation:cryptingProvider:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithStorageLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageLocation","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKStorageLocation","text":"SBSDKStorageLocation","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"storageLocation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cryptingProvider:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCryptingProvider","text":"id<SBSDKStorageCryptingProvider>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cryptingProvider","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"storageLocation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The storage location at which the new storage should reside."}]}]},{"name":"cryptingProvider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If non-nil, overrides the default image encryption provider."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/title","value":"SBSDKStorageLocation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageLocation\/navigatorTitle","value":[{"text":"SBSDKStorageLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/title","value":"SBSDKKeyedImageStorage"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/fragments","value":[{"kind":"identifier","text":"SBSDKKeyedImageStorage"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage\/navigatorTitle","value":[{"text":"SBSDKKeyedImageStorage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:cryptingProvider:)\/title","value":"initWithStorageLocation:cryptingProvider:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKKeyedImageStorage~1init(storageLocation:cryptingProvider:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStorageLocation:cryptingProvider:"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/title","value":"SBSDKStorageCryptingProvider"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/fragments","value":[{"text":"SBSDKStorageCryptingProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCryptingProvider\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKStorageCryptingProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}