{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText\/hash","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText"]]},"metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText(py)hash","title":"hash","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"identifier","text":"hash"}],"symbolKind":"property","role":"symbol"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText/hash":{"type":"topic","fragments":[{"text":"hash","kind":"identifier"}],"title":"hash","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext\/hash","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText\/hash","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.3"}],"title":"ScanbotBarcodeScannerSDK","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText":{"role":"symbol","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}