{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/barcodetrackingoverlay:textstylefor:"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle","text":"SBSDKBarcodeTrackedViewTextStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackedViewTextStyle"},{"text":" *) ","kind":"text"},{"text":"barcodeTrackingOverlay:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeTrackingOverlayController","kind":"typeIdentifier","text":"SBSDKBarcodeTrackingOverlayController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"textStyleFor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerResult","text":"SBSDKBarcodeScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcode"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:textStyleFor:","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"barcodeTrackingOverlay:textStyleFor:","kind":"identifier"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController(im)barcodeTrackingOverlay:textStyleFor:","role":"symbol","title":"barcodeTrackingOverlay:textStyleFor:","navigatorTitle":[{"kind":"identifier","text":"barcodeTrackingOverlay:textStyleFor:"}],"modules":[{"name":"ScanbotSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController/barcodeTrackingOverlay:textStyleFor:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"barcodeTrackingOverlay:textStyleFor:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"title":"barcodeTrackingOverlay:textStyleFor:","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/barcodetrackingoverlay:textstylefor:","navigatorTitle":[{"text":"barcodeTrackingOverlay:textStyleFor:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/barcodeTrackingOverlay:textStyleFor:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackingOverlayController":{"abstract":[{"type":"text","text":"A class that represents an overlay used for visualizing detected barcodes."},{"type":"text","text":" "},{"text":"It provides a customizable user interface for displaying barcodes and supports interaction with them.","type":"text"},{"text":" ","type":"text"},{"text":"The overlay can be used to highlight and select barcodes based on user input.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackingoverlaycontroller","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController","title":"SBSDKBarcodeTrackingOverlayController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeTrackedViewTextStyle":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodetrackedviewtextstyle","abstract":[{"type":"text","text":"A class that represents the style and kind of the text rendered below a barcode in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackingOverlayController"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeTrackedViewTextStyle","title":"SBSDKBarcodeTrackedViewTextStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerResult":{"title":"SBSDKBarcodeScannerResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerResult","kind":"symbol","abstract":[{"type":"text","text":"This class encapsulates the result of a barcode detection."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"kind":"symbol","title":"SBSDKUIBarcodeScannerViewController","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","deprecated":true}},"variantOverrides":[{"patch":[{"value":"SBSDKBarcodeTrackingOverlayController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackingOverlayController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackingOverlayController\/navigatorTitle","value":[{"text":"SBSDKBarcodeTrackingOverlayController","kind":"identifier"}]},{"op":"replace","value":"SBSDKBarcodeTrackedViewTextStyle","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/title"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeTrackedViewTextStyle"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/fragments"},{"value":[{"text":"SBSDKBarcodeTrackedViewTextStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeTrackedViewTextStyle\/navigatorTitle","op":"replace"},{"value":"SBSDKBarcodeScannerResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerResult"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title","value":"SBSDKUIBarcodeScannerViewController"},{"value":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}