{"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController(im)barcodeScannerController:didDetectBarcodes:","title":"barcodeScannerController:didDetectBarcodes:","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"barcodeScannerController:didDetectBarcodes:"}],"navigatorTitle":[{"text":"barcodeScannerController:didDetectBarcodes:","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/barcodeScannerController:didDetectBarcodes:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"barcodeScannerController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScannerViewController","text":"SBSDKBarcodeScannerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDetectBarcodes:"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKBarcodeScannerResult *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"codes","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/barcodescannercontroller:diddetectbarcodes:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController/barcodeScannerController:didDetectBarcodes:":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/barcodeScannerController:didDetectBarcodes:","title":"barcodeScannerController:didDetectBarcodes:","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/barcodescannercontroller:diddetectbarcodes:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"barcodeScannerController:didDetectBarcodes:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"barcodeScannerController:didDetectBarcodes:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"kind":"symbol","title":"SBSDKUIBarcodeScannerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"type":"topic","role":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScannerViewController":{"title":"SBSDKBarcodeScannerViewController","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodescannerviewcontroller","type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"text":" subclass to show a camera screen with the barcode detector.","type":"text"}],"navigatorTitle":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScannerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title","op":"replace","value":"SBSDKUIBarcodeScannerViewController"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"op":"replace"},{"op":"replace","value":"SBSDKBarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScannerViewController\/navigatorTitle","value":[{"text":"SBSDKBarcodeScannerViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}