{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/enablecameratextconfiguration"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/enableCameraTextConfiguration","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIEnableCameraTextConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration","text":"SBSDKUIEnableCameraTextConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"enableCameraTextConfiguration"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController(py)enableCameraTextConfiguration","fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"title":"enableCameraTextConfiguration","role":"symbol","modules":[{"name":"ScanbotSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","role":"collection","title":"ScanbotSDK","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","deprecated":true,"title":"SBSDKUIBarcodeScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIEnableCameraTextConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}],"abstract":[{"type":"text","text":"Configuration for the textual contents of camera based view controllers."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIEnableCameraTextConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuienablecameratextconfiguration","kind":"symbol","title":"SBSDKUIEnableCameraTextConfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIEnableCameraTextConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController/enableCameraTextConfiguration":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"enableCameraTextConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/enableCameraTextConfiguration","title":"enableCameraTextConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/enablecameratextconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title","value":"SBSDKUIBarcodeScannerViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]},{"value":"SBSDKUIEnableCameraTextConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIEnableCameraTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIEnableCameraTextConfiguration"}]}]}]}