{"metadata":{"title":"updateFlashButton","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateFlashButton"}],"navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeScannerViewController(im)updateFlashButton","symbolKind":"method"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/updateFlashButton"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/updateflashbutton"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"updateFlashButton","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIBarcodeScannerViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"kind":"symbol","title":"SBSDKUIBarcodeScannerViewController","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to detect QR and barcodes.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeScannerViewController/updateFlashButton":{"fragments":[{"text":"- ","kind":"text"},{"text":"updateFlashButton","kind":"identifier"}],"kind":"symbol","title":"updateFlashButton","role":"symbol","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodescannerviewcontroller\/updateflashbutton","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeScannerViewController\/updateFlashButton","navigatorTitle":[{"text":"updateFlashButton","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"SBSDKUIBarcodeScannerViewController","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}]},{"value":[{"kind":"identifier","text":"SBSDKUIBarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeScannerViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}