{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageOrigin\/bottomLeft"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageOrigin"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageOrigin","text":"SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageOrigin"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageorigin\/bottomleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimageorigin\/bottomleft"]}],"abstract":[{"type":"text","text":"Origin is at the bottom left corner of the image."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"bottomLeft","symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageOrigin(cpy)bottomLeft","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageOrigin"}],"roleHeading":"Type Property","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"bottomLeft"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageOrigin/bottomLeft":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageOrigin\/bottomLeft","title":"bottomLeft","url":"\/documentation\/scanbotsdk\/sbsdkimageorigin\/bottomleft","navigatorTitle":[{"kind":"identifier","text":"bottomLeft"}],"abstract":[{"text":"Origin is at the bottom left corner of the image.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageOrigin","text":"SBSDKImageOrigin"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageOrigin":{"type":"topic","abstract":[{"type":"text","text":"Location of the image origin in the image coordinate system."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageOrigin"}],"title":"SBSDKImageOrigin","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageOrigin"}],"url":"\/documentation\/scanbotsdk\/sbsdkimageorigin","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageOrigin"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"bottomLeft","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"bottomLeft","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKImageOrigin","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageOrigin","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageOrigin"},{"text":" * ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageOrigin~1bottomLeft\/title","op":"replace","value":"bottomLeft"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageOrigin~1bottomLeft\/fragments","op":"replace","value":[{"text":"bottomLeft","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageOrigin\/title","op":"replace","value":"SBSDKImageOrigin"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageOrigin\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageOrigin"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageOrigin\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageOrigin","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}