{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration\/sound","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration of the scan confirmation sound."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sound","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound","text":"SBSDKUI2Sound","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/sound"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/sound"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"sound"}],"symbolKind":"property","title":"sound","role":"symbol","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2MRZScannerScreenConfiguration(py)sound","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sound","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Sound","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound","kind":"typeIdentifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.2"}],"kind":"symbol","type":"topic","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Sound":{"url":"\/documentation\/scanbotsdk\/sbsdkui2sound","navigatorTitle":[{"text":"SBSDKUI2Sound","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","abstract":[{"text":"Configuration for the sound.","type":"text"}],"title":"SBSDKUI2Sound","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Sound","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration/sound":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration\/sound","abstract":[{"type":"text","text":"Configuration of the scan confirmation sound."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sound","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Sound","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration\/sound","navigatorTitle":[{"text":"sound","kind":"identifier"}],"title":"sound","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2MRZScannerScreenConfiguration":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2mrzscannerscreenconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2MRZScannerScreenConfiguration","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"identifier"}],"title":"SBSDKUI2MRZScannerScreenConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2MRZScannerScreenConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration of the screen for detecting MRZ (Machine-readable zones) of various documents.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sound","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"sound"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SBSDKUI2Sound","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Sound","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Sound"},{"text":" * ","kind":"text"},{"text":"sound","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/title","value":"SBSDKUI2Sound"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/fragments","value":[{"text":"SBSDKUI2Sound","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Sound\/navigatorTitle","value":[{"text":"SBSDKUI2Sound","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration~1sound\/title","value":"sound"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration~1sound\/fragments","value":[{"text":"sound","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/title","value":"SBSDKUI2MRZScannerScreenConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2MRZScannerScreenConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2MRZScannerScreenConfiguration"}]}]}]}