{"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractor(im)verifyDocumentWithDocumentParts:error:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentParts"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","kind":"typeIdentifier","text":"SBSDKGenericDocument"},{"kind":"text","text":">) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentVerificationReport","kind":"typeIdentifier","text":"SBSDKDocumentVerificationReport"}],"title":"verifyDocument(documentParts:)","navigatorTitle":[{"kind":"identifier","text":"verifyDocumentWithDocumentParts:error:"}]},"abstract":[{"type":"text","text":"Verify whether the extracted document has signs of forgery or tampering."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor\/verifyDocument(documentParts:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentParts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"},{"kind":"text","text":">) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentVerificationReport","kind":"typeIdentifier","text":"SBSDKDocumentVerificationReport"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The document parts to verify. For example, the front and back of an ID card.","type":"text"}]}],"name":"documentParts"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The verification report.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"name":"Throws","style":"note","type":"aside","content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","type":"reference"},{"text":" in case of an error.","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/verifydocument(documentparts:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/verifydocument(documentparts:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"abstract":[{"text":"Generic document.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","title":"SBSDKGenericDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor","kind":"symbol","title":"SBSDKDocumentDataExtractor","abstract":[{"type":"text","text":"API for extracting data from documents."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentVerificationReport":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentVerificationReport"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentVerificationReport"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentverificationreport","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport","abstract":[{"type":"text","text":"Report of the document verification."}],"title":"SBSDKDocumentVerificationReport","type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKError":{"abstract":[{"type":"text","text":"Represents errors that can occur within the Scanbot SDK."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKError","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkerror","title":"SBSDKError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SBSDKError","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKError","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor/verifyDocument(documentParts:)":{"role":"symbol","title":"verifyDocument(documentParts:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor\/verifydocument(documentparts:)","type":"topic","abstract":[{"type":"text","text":"Verify whether the extracted document has signs of forgery or tampering."}],"kind":"symbol","navigatorTitle":[{"text":"verifyDocumentWithDocumentParts:error:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor\/verifyDocument(documentParts:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentParts","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","kind":"typeIdentifier"},{"text":">) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentVerificationReport","text":"SBSDKDocumentVerificationReport","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"verifyDocumentWithDocumentParts:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"verifyDocumentWithDocumentParts:error:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentVerificationReport","text":"SBSDKDocumentVerificationReport","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentVerificationReport","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"verifyDocumentWithDocumentParts:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKGenericDocument *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentParts","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The document parts to verify. For example, the front and back of an ID card."}]}],"name":"documentParts"},{"content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for this parameter.","type":"text"}]}],"name":"error"}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The verification report.","type":"text"},{"text":" On failure, this method returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/title","value":"SBSDKDocumentDataExtractor","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/fragments","value":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/title","value":"SBSDKDocumentVerificationReport","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/fragments","value":[{"text":"SBSDKDocumentVerificationReport","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentVerificationReport\/navigatorTitle","value":[{"text":"SBSDKDocumentVerificationReport","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor~1verifyDocument(documentParts:)\/title","value":"verifyDocumentWithDocumentParts:error:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor~1verifyDocument(documentParts:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"verifyDocumentWithDocumentParts:error:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}