{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerScreenConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerScreenConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"SBSDKUI2BarcodeScannerUIResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerUIResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ())","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration to define look and feel of the new scanner view."}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"The completion handler to be called when the scanning is finished, providing the result or an error.","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/init(configuration:completion:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/init(configuration:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"init(configuration:completion:)","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerScreenConfiguration","text":"SBSDKUI2BarcodeScannerScreenConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerUIResult","text":"SBSDKUI2BarcodeScannerUIResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ())","kind":"text"}],"role":"symbol","externalID":"s:10ScanbotSDK26SBSDKUI2BarcodeScannerViewV13configuration10completionAcA0cdE19ScreenConfigurationC_yAA0cdE8UIResultCSg_s5Error_pSgtctcfc","modules":[{"name":"ScanbotSDK"}]},"sections":[],"abstract":[{"type":"text","text":"Creates a new instance of "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","isActive":true},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerScreenConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerScreenConfiguration"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerscreenconfiguration","kind":"symbol","title":"SBSDKUI2BarcodeScannerScreenConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2BarcodeScannerScreenConfiguration"}],"abstract":[{"text":"Configuration of the barcode scanner screen.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerScreenConfiguration","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerViewController":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController","title":"SBSDKUI2BarcodeScannerViewController","kind":"symbol","abstract":[{"text":"A highly customizable camera-based RTU-UI view controller to scan QR and barcodes.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView/init(configuration:completion:)":{"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView\/init(configuration:completion:)","url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview\/init(configuration:completion:)","abstract":[{"type":"text","text":"Creates a new instance of "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","type":"reference","isActive":true},{"type":"text","text":"."}],"title":"init(configuration:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerScreenConfiguration"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BarcodeScannerUIResult"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ())","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerView":{"navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescannerview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerView","kind":"symbol","role":"symbol","title":"SBSDKUI2BarcodeScannerView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerView","kind":"identifier"}],"abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerViewController"},{"type":"text","text":"."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BarcodeScannerUIResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BarcodeScannerUIResult","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Results of the barcode scan."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"title":"SBSDKUI2BarcodeScannerUIResult","navigatorTitle":[{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2barcodescanneruiresult","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SBSDKUI2BarcodeScannerScreenConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerScreenConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerScreenConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerScreenConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2BarcodeScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BarcodeScannerViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerViewController\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2BarcodeScannerUIResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/title"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2BarcodeScannerUIResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BarcodeScannerUIResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}