{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureNotSet"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureNotSet"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"No license set. On platforms that support trial mode, it means that the SDK’s trial mode is over."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/failurenotset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdklicensestatus\/failurenotset"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureNotSet"}],"roleHeading":"Case","title":"SBSDKLicenseStatus.failureNotSet","role":"symbol","symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKLicenseStatus@SBSDKLicenseStatusFailureNotSet","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"SBSDKLicenseStatusFailureNotSet","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus","role":"symbol","title":"SBSDKLicenseStatus","kind":"symbol","navigatorTitle":[{"text":"SBSDKLicenseStatus","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus","abstract":[{"type":"text","text":"Status of the license plate scanner."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKLicenseStatus"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLicenseStatus/failureNotSet":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureNotSet"}],"abstract":[{"text":"No license set. On platforms that support trial mode, it means that the SDK’s trial mode is over.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdklicensestatus\/failurenotset","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLicenseStatus\/failureNotSet","title":"SBSDKLicenseStatus.failureNotSet","navigatorTitle":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureNotSet"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKLicenseStatusFailureNotSet","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureNotSet"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKLicenseStatusFailureNotSet","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKLicenseStatus","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatus"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus\/navigatorTitle","op":"replace"},{"value":"SBSDKLicenseStatusFailureNotSet","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureNotSet\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKLicenseStatusFailureNotSet"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLicenseStatus~1failureNotSet\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}