{"metadata":{"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"ignoreOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"init(image:ignoreOrientation:)","navigatorTitle":[{"kind":"identifier","text":"initWithImage:ignoreOrientation:"}],"symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerFrame(im)initWithImage:ignoreOrientation:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame\/init(image:ignoreOrientation:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignoreOrientation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" to initialize the frame with."}]}]},{"name":"ignoreOrientation","content":[{"inlineContent":[{"type":"text","text":"If set to "},{"type":"codeVoice","code":"True"},{"text":", the orientation of the images metadata is ignored. Set to ‘False’ to rotate the image data according to its metadata.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame"]]},"abstract":[{"type":"text","text":"Initializes a frame from an image."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerframe\/init(image:ignoreorientation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannerframe\/init(image:ignoreorientation:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerFrame/init(image:ignoreOrientation:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":", "},{"text":"ignoreOrientation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initializes a frame from an image."}],"title":"init(image:ignoreOrientation:)","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame\/init(image:ignoreOrientation:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImage:ignoreOrientation:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerframe\/init(image:ignoreorientation:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerFrame":{"url":"\/documentation\/scanbotsdk\/sbsdkbasescannerframe","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerFrame","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerFrame"}],"abstract":[{"text":"A wrapper class for video frames.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"kind":"symbol","title":"SBSDKBaseScannerFrame"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithImage:ignoreOrientation:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImage:ignoreOrientation:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreOrientation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"ignoreOrientation","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame~1init(image:ignoreOrientation:)\/title","value":"initWithImage:ignoreOrientation:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame~1init(image:ignoreOrientation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImage:ignoreOrientation:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/title","value":"SBSDKBaseScannerFrame"},{"value":[{"text":"SBSDKBaseScannerFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerFrame\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}