{"kind":"symbol","abstract":[{"text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL.","type":"text"}],"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageURLsAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]","kind":"text"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFPagesExtractor(im)imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:","kind":"identifier"}],"title":"imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurlsasync(from:scaling:compression:encrypter:outputdirectory:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurlsasync(from:scaling:compression:encrypter:outputdirectory:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLsAsync"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"text":"pdfURL","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"encrypter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The URL of the PDF file."}],"type":"paragraph"}],"name":"pdfURL"},{"name":"scaling","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher."}]}]},{"name":"compression","content":[{"type":"paragraph","inlineContent":[{"text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used.","type":"text"}]}]},{"name":"encrypter","content":[{"inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"code":"nil","type":"codeVoice"},{"type":"text","text":", no encryption is used."}],"type":"paragraph"}]},{"name":"outputDirectory","content":[{"type":"paragraph","inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The created array of image file URLs."}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"In Swift language it is used with structured concurrency (async\/await).","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor":{"title":"SBSDKPDFPagesExtractor","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"abstract":[{"text":"Class used to extract pages from a PDF file and returns them in various ways.","type":"text"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStorageCrypting":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStorageCrypting","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKStorageCrypting"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkstoragecrypting","navigatorTitle":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"title":"SBSDKStorageCrypting","abstract":[{"type":"text","text":"Protocol for implementing encryption and decryption of (streamed) data."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageURLsAsync"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"scaling","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"compression","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"outputDirectory","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"]","kind":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurlsasync(from:scaling:compression:encrypter:outputdirectory:)","navigatorTitle":[{"text":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:","kind":"identifier"}],"title":"imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)","abstract":[{"type":"text","text":"Asynchronously extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"imageURLsAsyncFrom:"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"pdfURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scaling:"},{"kind":"text","text":"("},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scaling"},{"kind":"text","text":" "},{"text":"compression:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"compression"},{"kind":"text","text":" "},{"text":"encrypter:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>"},{"kind":"text","text":") "},{"text":"encrypter","kind":"internalParam"},{"kind":"text","text":" "},{"text":"outputDirectory:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"outputDirectory"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSURL *>"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SBSDKPDFPagesExtractor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/fragments","value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}]},{"value":"SBSDKStorageCrypting","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStorageCrypting\/fragments","value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)\/title","value":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLsAsync(from:scaling:compression:encrypter:outputDirectory:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageURLsAsyncFrom:scaling:compression:encrypter:outputDirectory:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}