{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/images(from:scaling:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(imagesFromPDF:scaling:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"images","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"pdfURL","kind":"internalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"scaling","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The URL of the PDF file.","type":"text"}]}],"name":"pdfURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher.","type":"text"}]}],"name":"scaling"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An array of ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" with extracted pages. The array will be empty if something is wrong.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor"]]},"sections":[],"abstract":[{"text":"Extracts pages from PDF and converts them to an array of ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/images(from:scaling:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/images(from:scaling:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFPagesExtractor(im)imagesFromPDF:scaling:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"imagesFromPDF:scaling:","kind":"identifier"}],"title":"images(from:scaling:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"images","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"]"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/images(from:scaling:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/images(from:scaling:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"images"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> [","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"imagesFromPDF:scaling:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Extracts pages from PDF and converts them to an array of ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":". Nothing is written to disk during this operation. Runs in the same thread, as it is called from.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/images(from:scaling:)","title":"images(from:scaling:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor","abstract":[{"text":"Class used to extract pages from a PDF file and returns them in various ways.","type":"text"}],"type":"topic","kind":"symbol","title":"SBSDKPDFPagesExtractor","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"imagesFromPDF:scaling:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"imagesFromPDF:scaling:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray<UIImage *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"imagesFromPDF:"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"pdfURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scaling:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"text":"scaling","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"imagesFromPDF:scaling:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1images(from:scaling:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1images(from:scaling:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagesFromPDF:scaling:"}]},{"value":"SBSDKPDFPagesExtractor","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/fragments"}]}]}