{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurls(from:compression:outputdirectory:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurls(from:compression:outputdirectory:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","title":"imageURLs(from:compression:outputDirectory:)","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageURLs","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"text":"compression","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":") -> [","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPDFPagesExtractor(im)imageURLsFromPDF:compression:outputDirectory:","navigatorTitle":[{"text":"imageURLsFromPDF:compression:outputDirectory:","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:compression:outputDirectory:)","interfaceLanguage":"swift"},"abstract":[{"text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"No encryption is used here. Media box scale value is 2."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(imageURLsFromPDF:compression:outputDirectory:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"pdfURL","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL of the PDF file."}]}]},{"name":"compression","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}]}]},{"content":[{"inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}],"type":"paragraph"}],"name":"outputDirectory"}]},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of URLs with extracted pages as JPEG files. The array will be empty if something is wrong."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor"]]},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor/imageURLs(from:compression:outputDirectory:)":{"navigatorTitle":[{"text":"imageURLsFromPDF:compression:outputDirectory:","kind":"identifier"}],"abstract":[{"type":"text","text":"Extracts pages from a PDF, converts them to JPEGs and writes them to a specified URL. Runs in the same thread that it is called from."},{"type":"text","text":" "},{"type":"text","text":"No encryption is used here. Media box scale value is 2."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"imageURLs","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"outputDirectory"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor\/imageURLs(from:compression:outputDirectory:)","url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor\/imageurls(from:compression:outputdirectory:)","title":"imageURLs(from:compression:outputDirectory:)","kind":"symbol","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPDFPagesExtractor":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPDFPagesExtractor","navigatorTitle":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpdfpagesextractor","role":"symbol","kind":"symbol","title":"SBSDKPDFPagesExtractor","abstract":[{"text":"Class used to extract pages from a PDF file and returns them in various ways.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"imageURLsFromPDF:compression:outputDirectory:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"imageURLsFromPDF:compression:outputDirectory:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURL *>"},{"kind":"text","text":" *) "},{"text":"imageURLsFromPDF:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":" "},{"text":"compression:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"compression"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputDirectory:"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"text":"outputDirectory","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The URL of the PDF file.","type":"text"}],"type":"paragraph"}],"name":"pdfURL"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}]}],"name":"compression"},{"name":"outputDirectory","content":[{"inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"An array of URLs with extracted pages as JPEG files. The array will be empty if something is wrong.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"imageURLsFromPDF:compression:outputDirectory:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:compression:outputDirectory:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"imageURLsFromPDF:compression:outputDirectory:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor~1imageURLs(from:compression:outputDirectory:)\/fragments"},{"value":"SBSDKPDFPagesExtractor","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/title"},{"op":"replace","value":[{"text":"SBSDKPDFPagesExtractor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPDFPagesExtractor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPDFPagesExtractor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}