{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewControllerShouldScan(_:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontrollershouldscan(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontrollershouldscan(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Asks the delegate if the check scanner should scan the next video frame. Optional.","type":"text"}],"metadata":{"title":"checkScannerViewControllerShouldScan(_:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"checkScannerViewControllerShouldScan:"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKCheckScannerViewControllerDelegate(im)checkScannerViewControllerShouldScan:","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkScannerViewControllerShouldScan","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKCheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkScannerViewControllerShouldScan"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKCheckScannerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}]},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The calling ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return True to run the scanning on the next video frame, False otherwise. Can be used to pause the detection."}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate/checkScannerViewControllerShouldScan(_:)":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate\/checkScannerViewControllerShouldScan(_:)","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate\/checkscannerviewcontrollershouldscan(_:)","role":"symbol","abstract":[{"text":"Asks the delegate if the check scanner should scan the next video frame. Optional.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"checkScannerViewControllerShouldScan:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkScannerViewControllerShouldScan"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController","text":"SBSDKCheckScannerViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"checkScannerViewControllerShouldScan(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCheckScannerViewController"}],"abstract":[{"type":"text","text":"Classic UI view controller that can be used to scan bank checks."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontroller","type":"topic","title":"SBSDKCheckScannerViewController","navigatorTitle":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCheckScannerViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegation protocol for the "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","isActive":true,"type":"reference"},{"type":"text","text":" class."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewControllerDelegate","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkcheckscannerviewcontrollerdelegate","type":"topic","title":"SBSDKCheckScannerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"checkScannerViewControllerShouldScan:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"checkScannerViewControllerShouldScan:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"checkScannerViewControllerShouldScan:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","text":"SBSDKCheckScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKCheckScannerViewController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The calling "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCheckScannerViewController","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return True to run the scanning on the next video frame, False otherwise. Can be used to pause the detection."}]}],"kind":"content"}},{"value":"checkScannerViewControllerShouldScan:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewControllerShouldScan(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate~1checkScannerViewControllerShouldScan(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"checkScannerViewControllerShouldScan:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/title","op":"replace","value":"SBSDKCheckScannerViewController"},{"value":[{"kind":"identifier","text":"SBSDKCheckScannerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKCheckScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewController\/navigatorTitle"},{"value":"SBSDKCheckScannerViewControllerDelegate","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/fragments","value":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}]},{"value":[{"text":"SBSDKCheckScannerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCheckScannerViewControllerDelegate\/navigatorTitle"}]}]}