{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate\/documentrecognizerviewcontroller(_:didrecognize:on:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate\/documentrecognizerviewcontroller(_:didrecognize:on:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/documentRecognizerViewController(_:didRecognize:on:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Informs the delegate that a document has been recognized successfully."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(documentRecognizerViewController:didRecognizeResult:onImage:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRecognize","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"result"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKGenericDocumentRecognitionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"on"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController"},{"type":"text","text":" instance that recognized the document."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The recognition result.","type":"text"}]}],"name":"result"},{"content":[{"inlineContent":[{"type":"text","text":"The original image where the document has been recognized on."}],"type":"paragraph"}],"name":"image"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentRecognizerViewController"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController"},{"kind":"text","text":", "},{"text":"didRecognize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKGenericDocumentRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":")","kind":"text"}],"title":"documentRecognizerViewController(_:didRecognize:on:)","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKGenericDocumentRecognizerViewControllerDelegate(im)documentRecognizerViewController:didRecognizeResult:onImage:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"documentRecognizerViewController:didRecognizeResult:onImage:"}],"role":"symbol","roleHeading":"Instance Method"},"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizer":{"title":"SBSDKGenericDocumentRecognizer","abstract":[{"type":"text","text":"A class to recognize and detect the data fields from specific documents,"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizer"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognitionResult":{"abstract":[{"type":"text","text":"The recognition result of the "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizer","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult","type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognitionResult","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognitionresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocumentRecognitionResult"}],"kind":"symbol","title":"SBSDKGenericDocumentRecognitionResult","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController":{"title":"SBSDKGenericDocumentRecognizerViewController","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to recognize documents, e.g. German passports, ID cards and driver’s licenses on video frames."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewControllerDelegate/documentRecognizerViewController(_:didRecognize:on:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentRecognizerViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController","text":"SBSDKGenericDocumentRecognizerViewController"},{"kind":"text","text":", "},{"text":"didRecognize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKGenericDocumentRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"documentRecognizerViewController(_:didRecognize:on:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/documentRecognizerViewController(_:didRecognize:on:)","navigatorTitle":[{"text":"documentRecognizerViewController:didRecognizeResult:onImage:","kind":"identifier"}],"abstract":[{"type":"text","text":"Informs the delegate that a document has been recognized successfully."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate\/documentrecognizerviewcontroller(_:didrecognize:on:)","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewControllerDelegate":{"abstract":[{"text":"The delegate protocol for the ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","type":"reference","isActive":true},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewControllerDelegate"}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate","role":"symbol","type":"topic","title":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"documentRecognizerViewController:didRecognizeResult:onImage:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentRecognizerViewController:didRecognizeResult:onImage:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentRecognizerViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","text":"SBSDKGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":" ","kind":"text"},{"text":"didRecognizeResult:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocumentRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognitionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognitionResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"onImage:"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"image"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/title","op":"replace","value":"SBSDKGenericDocumentRecognizer"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentRecognizer","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizer\/fragments"},{"value":"SBSDKGenericDocumentRecognitionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognitionResult\/fragments","op":"replace","value":[{"text":"SBSDKGenericDocumentRecognitionResult","kind":"identifier"}]},{"op":"replace","value":"SBSDKGenericDocumentRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate~1documentRecognizerViewController(_:didRecognize:on:)\/title","value":"documentRecognizerViewController:didRecognizeResult:onImage:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate~1documentRecognizerViewController(_:didRecognize:on:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentRecognizerViewController:didRecognizeResult:onImage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate\/title","value":"SBSDKGenericDocumentRecognizerViewControllerDelegate","op":"replace"},{"value":[{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}