{"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"genericDocumentRecognizerViewControllerShouldRecognize","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController","kind":"typeIdentifier","text":"SBSDKGenericDocumentRecognizerViewController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"ScanbotSDK"}],"title":"genericDocumentRecognizerViewControllerShouldRecognize(_:)","navigatorTitle":[{"text":"genericDocumentRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKGenericDocumentRecognizerViewControllerDelegate(im)genericDocumentRecognizerViewControllerShouldRecognize:"},"abstract":[{"text":"Asks the delegate if the generic document recognizer should scan the next video frame.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericDocumentRecognizerViewControllerShouldRecognize"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController","text":"SBSDKGenericDocumentRecognizerViewController"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The generic document recognizer view controller that will receive the video frame."}]}],"name":"viewController"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":" to run the recognition on the next video frame, "},{"code":"False","type":"codeVoice"},{"type":"text","text":" otherwise. Can be used to pause the detection."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Optional.","type":"text"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/genericDocumentRecognizerViewControllerShouldRecognize(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate\/genericdocumentrecognizerviewcontrollershouldrecognize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate\/genericdocumentrecognizerviewcontrollershouldrecognize(_:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewControllerDelegate/genericDocumentRecognizerViewControllerShouldRecognize(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"genericDocumentRecognizerViewControllerShouldRecognize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","title":"genericDocumentRecognizerViewControllerShouldRecognize(_:)","navigatorTitle":[{"text":"genericDocumentRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"abstract":[{"type":"text","text":"Asks the delegate if the generic document recognizer should scan the next video frame."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate\/genericdocumentrecognizerviewcontrollershouldrecognize(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate\/genericDocumentRecognizerViewControllerShouldRecognize(_:)"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewControllerDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SBSDKGenericDocumentRecognizerViewControllerDelegate","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The delegate protocol for the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontrollerdelegate","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewControllerDelegate"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerViewController","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SBSDKGenericDocumentRecognizerViewController","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewController"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to recognize documents, e.g. German passports, ID cards and driver’s licenses on video frames."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerviewcontroller","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"genericDocumentRecognizerViewControllerShouldRecognize:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"genericDocumentRecognizerViewControllerShouldRecognize:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"genericDocumentRecognizerViewControllerShouldRecognize:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerViewController","text":"SBSDKGenericDocumentRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"genericDocumentRecognizerViewControllerShouldRecognize:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate~1genericDocumentRecognizerViewControllerShouldRecognize(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"genericDocumentRecognizerViewControllerShouldRecognize:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate~1genericDocumentRecognizerViewControllerShouldRecognize(_:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate\/title","op":"replace","value":"SBSDKGenericDocumentRecognizerViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewControllerDelegate\/fragments","value":[{"text":"SBSDKGenericDocumentRecognizerViewControllerDelegate","kind":"identifier"}]},{"value":"SBSDKGenericDocumentRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKGenericDocumentRecognizerViewController"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}