{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog\/title"},"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog(py)title","navigatorTitle":[{"kind":"identifier","text":"title"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Property","title":"title","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","text":"SBSDKUI2StyledText","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanbotalertdialog\/title"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanbotalertdialog\/title"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog"]]},"abstract":[{"type":"text","text":"Title displayed above the message."}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2StyledText":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2StyledText"}],"navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2styledtext","kind":"symbol","type":"topic","abstract":[{"text":"Configuration of the text field appearance.","type":"text"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanbotAlertDialog/title":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanbotalertdialog\/title","kind":"symbol","title":"title","abstract":[{"text":"Title displayed above the message.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"title"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog\/title"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2ScanbotAlertDialog":{"type":"topic","title":"SBSDKUI2ScanbotAlertDialog","navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration of the the standard alert dialog.","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2scanbotalertdialog","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2ScanbotAlertDialog","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","role":"collection","abstract":[{"text":"Version: 6.1.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"title"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUI2StyledText","kind":"typeIdentifier","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" * "},{"kind":"identifier","text":"title"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKUI2StyledText","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/title"},{"op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2StyledText\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}]},{"value":"title","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog~1title\/title"},{"value":[{"kind":"identifier","text":"title"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog~1title\/fragments"},{"value":"SBSDKUI2ScanbotAlertDialog","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog\/fragments","value":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}]}]}]}