{"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionAuto","kind":"identifier"}],"title":"SBSDKVideoFrameResolution.auto","symbolKind":"case","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVideoFrameResolution@SBSDKVideoFrameResolutionAuto","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"auto"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/auto"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/auto"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution"]]},"abstract":[{"type":"text","text":"Select the video resolution automatically based on device specifics."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution/auto":{"url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution\/auto","navigatorTitle":[{"text":"SBSDKVideoFrameResolutionAuto","kind":"identifier"}],"title":"SBSDKVideoFrameResolution.auto","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auto","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution\/auto","abstract":[{"type":"text","text":"Select the video resolution automatically based on device specifics."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoFrameResolution":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoFrameResolution","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"url":"\/documentation\/scanbotsdk\/sbsdkvideoframeresolution","role":"symbol","type":"topic","kind":"symbol","title":"SBSDKVideoFrameResolution","abstract":[{"text":"An enum describing the resolution of a video or camera stream.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKVideoFrameResolutionAuto"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionAuto"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionAuto"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1auto\/title","op":"replace","value":"SBSDKVideoFrameResolutionAuto"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution~1auto\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolutionAuto"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/title","value":"SBSDKVideoFrameResolution","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/fragments","value":[{"text":"SBSDKVideoFrameResolution","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoFrameResolution\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKVideoFrameResolution"}],"op":"replace"}]}]}