{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noFilter"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterNoFilter"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noFilter"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodesExtensionFilter@SBSDKBarcodesExtensionFilterNoFilter","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","title":"SBSDKBarcodesExtensionFilter.noFilter","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/noFilter"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"EAN and UPC barcoded with or without extensions will be returned."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/nofilter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/nofilter"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter/noFilter":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/nofilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/noFilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterNoFilter"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFilter"}],"kind":"symbol","role":"symbol","title":"SBSDKBarcodesExtensionFilter.noFilter","abstract":[{"text":"EAN and UPC barcoded with or without extensions will be returned.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SBSDKBarcodesExtensionFilter","abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKBarcodesExtensionFilterNoFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterNoFilter"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKBarcodesExtensionFilterNoFilter","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"SBSDKBarcodesExtensionFilterNoFilter","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1noFilter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1noFilter\/fragments","value":[{"text":"SBSDKBarcodesExtensionFilterNoFilter","kind":"identifier"}]},{"op":"replace","value":"SBSDKBarcodesExtensionFilter","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"}]}]}]}