{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterOnlyWithExtensions"}],"roleHeading":"Case","role":"symbol","title":"SBSDKBarcodesExtensionFilter.onlyWithExtensions","externalID":"c:@M@ScanbotSDK@E@SBSDKBarcodesExtensionFilter@SBSDKBarcodesExtensionFilterOnlyWithExtensions","modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"onlyWithExtensions","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/onlywithextensions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/onlywithextensions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/onlyWithExtensions"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter"]]},"abstract":[{"text":"Only EAN and UPC barcoded with extensions will be returned.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlyWithExtensions"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter/onlyWithExtensions":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter\/onlyWithExtensions","type":"topic","title":"SBSDKBarcodesExtensionFilter.onlyWithExtensions","url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter\/onlywithextensions","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"onlyWithExtensions","kind":"identifier"}],"abstract":[{"text":"Only EAN and UPC barcoded with extensions will be returned.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterOnlyWithExtensions"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodesExtensionFilter":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodesExtensionFilter"}],"navigatorTitle":[{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"abstract":[{"text":"Filter for extended EAN and UPC barcodes.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodesextensionfilter","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodesExtensionFilter","kind":"symbol","title":"SBSDKBarcodesExtensionFilter","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKBarcodesExtensionFilterOnlyWithExtensions","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodesExtensionFilterOnlyWithExtensions"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SBSDKBarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1onlyWithExtensions\/title","op":"replace","value":"SBSDKBarcodesExtensionFilterOnlyWithExtensions"},{"value":[{"text":"SBSDKBarcodesExtensionFilterOnlyWithExtensions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter~1onlyWithExtensions\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter\/title","op":"replace","value":"SBSDKBarcodesExtensionFilter"},{"value":[{"text":"SBSDKBarcodesExtensionFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodesExtensionFilter\/fragments","op":"replace"}]}]}