{"kind":"symbol","sections":[],"metadata":{"title":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:"}],"symbolKind":"method","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKRefCountedObjectProfile(im)initWithUniqueId:timestampCreated:strongReferences:serializedReferences:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRefCountedObjectProfile\/initWithUniqueId:timestampCreated:strongReferences:serializedReferences:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithUniqueId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"uniqueId"},{"text":" ","kind":"text"},{"text":"timestampCreated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int64_t","preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"timestampCreated"},{"kind":"text","text":" "},{"kind":"identifier","text":"strongReferences:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"strongReferences","kind":"internalParam"},{"kind":"text","text":" "},{"text":"serializedReferences:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"serializedReferences","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRefCountedObjectProfile"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkrefcountedobjectprofile\/initwithuniqueid:timestampcreated:strongreferences:serializedreferences:"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKRefCountedObjectProfile/initWithUniqueId:timestampCreated:strongReferences:serializedReferences:":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkrefcountedobjectprofile\/initwithuniqueid:timestampcreated:strongreferences:serializedreferences:","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRefCountedObjectProfile\/initWithUniqueId:timestampCreated:strongReferences:serializedReferences:","abstract":[],"title":"initWithUniqueId:timestampCreated:strongReferences:serializedReferences:"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKRefCountedObjectProfile":{"abstract":[{"text":"Profile info of a reference-counted stored object.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKRefCountedObjectProfile","navigatorTitle":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkrefcountedobjectprofile","title":"SBSDKRefCountedObjectProfile","role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 7.1.1"}],"url":"\/documentation\/scanbotdocumentscannersdk"}},"variantOverrides":[{"patch":[{"value":"SBSDKRefCountedObjectProfile","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRefCountedObjectProfile\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRefCountedObjectProfile\/fragments","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}