{"deprecationSummary":[{"inlineContent":[{"text":"Please consider using SBSDKUIDocumentDataExtractorViewControllerDelegate.","type":"text"}],"type":"paragraph"}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate\/healthInsuranceCardDetectionViewController(_:didDetectCard:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate"]]},"sections":[],"abstract":[{"type":"text","text":"Informs the delegate that a health insurance card has been detected."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontrollerdelegate\/healthinsurancecarddetectionviewcontroller(_:diddetectcard:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontrollerdelegate\/healthinsurancecarddetectionviewcontroller(_:diddetectcard:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"healthInsuranceCardDetectionViewController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController"},{"text":", ","kind":"text"},{"text":"didDetectCard","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"card","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection view controller that detected the health insurance card."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The detected health insurance card.","type":"text"}]}],"name":"card"}],"kind":"parameters"}],"metadata":{"roleHeading":"Instance Method","required":true,"symbolKind":"method","title":"healthInsuranceCardDetectionViewController(_:didDetectCard:)","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(pl)SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate(im)healthInsuranceCardDetectionViewController:didDetectCard:","navigatorTitle":[{"text":"healthInsuranceCardDetectionViewController:didDetectCard:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"healthInsuranceCardDetectionViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerViewController"},{"text":", ","kind":"text"},{"text":"didDetectCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":[]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResult":{"url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresult","type":"topic","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"symbol","role":"symbol","abstract":[{"text":"The result of the health insurance card recognition.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"identifier"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate","title":"SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate","type":"topic","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontrollerdelegate","abstract":[{"type":"text","text":"Delegate protocol for "},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController","type":"reference"},{"text":".","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate/healthInsuranceCardDetectionViewController(_:didDetectCard:)":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"healthInsuranceCardDetectionViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerViewController"},{"text":", ","kind":"text"},{"text":"didDetectCard","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontrollerdelegate\/healthinsurancecarddetectionviewcontroller(_:diddetectcard:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate\/healthInsuranceCardDetectionViewController(_:didDetectCard:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"healthInsuranceCardDetectionViewController:didDetectCard:"}],"required":true,"abstract":[{"text":"Informs the delegate that a health insurance card has been detected.","type":"text"}],"title":"healthInsuranceCardDetectionViewController(_:didDetectCard:)","deprecated":true},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerViewController":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController","title":"SBSDKUIHealthInsuranceCardRecognizerViewController","type":"topic","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizerviewcontroller","abstract":[{"text":"A view controller for camera-based detection of health insurance cards.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"healthInsuranceCardDetectionViewController:didDetectCard:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"healthInsuranceCardDetectionViewController:didDetectCard:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"healthInsuranceCardDetectionViewController:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerViewController","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerViewController","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"text":"didDetectCard:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKEuropeanHealthInsuranceCardRecognitionResult","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"card"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection view controller that detected the health insurance card."}]}],"name":"viewController"},{"content":[{"inlineContent":[{"type":"text","text":"The detected health insurance card."}],"type":"paragraph"}],"name":"card"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/fragments","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResult\/navigatorTitle"},{"value":"SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate\/fragments","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate~1healthInsuranceCardDetectionViewController(_:didDetectCard:)\/title","value":"healthInsuranceCardDetectionViewController:didDetectCard:"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewControllerDelegate~1healthInsuranceCardDetectionViewController(_:didDetectCard:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"healthInsuranceCardDetectionViewController:didDetectCard:","kind":"identifier"}]},{"op":"replace","value":"SBSDKUIHealthInsuranceCardRecognizerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/fragments","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerViewController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}