{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2findercorneredstyle\/initwithstrokecolor:strokewidth:cornerradius:"]}],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2FinderCorneredStyle(im)initWithStrokeColor:strokeWidth:cornerRadius:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrokeColor:strokeWidth:cornerRadius:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStrokeColor:strokeWidth:cornerRadius:"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","title":"initWithStrokeColor:strokeWidth:cornerRadius:"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderCorneredStyle\/initWithStrokeColor:strokeWidth:cornerRadius:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStrokeColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"strokeColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"strokeWidth:"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"strokeWidth","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cornerRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderCorneredStyle"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color","url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FinderCorneredStyle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2FinderCorneredStyle"}],"abstract":[{"text":"A variant of the viewfinder displaying only the four corners of the scanning area.","type":"text"}],"title":"SBSDKUI2FinderCorneredStyle","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2findercorneredstyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2FinderCorneredStyle"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderCorneredStyle"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2FinderCorneredStyle/initWithStrokeColor:strokeWidth:cornerRadius:":{"type":"topic","role":"symbol","title":"initWithStrokeColor:strokeWidth:cornerRadius:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStrokeColor:strokeWidth:cornerRadius:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2FinderCorneredStyle\/initWithStrokeColor:strokeWidth:cornerRadius:","navigatorTitle":[{"kind":"identifier","text":"initWithStrokeColor:strokeWidth:cornerRadius:"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2findercorneredstyle\/initwithstrokecolor:strokewidth:cornerradius:","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","op":"replace","value":"SBSDKUI2Color"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderCorneredStyle\/title","op":"replace","value":"SBSDKUI2FinderCorneredStyle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderCorneredStyle\/fragments","op":"replace","value":[{"text":"SBSDKUI2FinderCorneredStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2FinderCorneredStyle\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2FinderCorneredStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}