{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engineMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeEngineMode","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeEngineMode"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode\/nextGen"},{"type":"text","text":"."}]}],"kind":"content"}],"metadata":{"symbolKind":"property","title":"engineMode","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeScanAndCountViewController(py)engineMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"engineMode"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"engineMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeEngineMode","kind":"typeIdentifier","text":"SBSDKBarcodeEngineMode"}],"modules":[{"name":"ScanbotSDK"}]},"abstract":[{"type":"text","text":"The barcode detector engine mode."}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/engineMode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/enginemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/enginemode"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController/engineMode":{"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller\/enginemode","navigatorTitle":[{"text":"engineMode","kind":"identifier"}],"title":"engineMode","abstract":[{"type":"text","text":"The barcode detector engine mode."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engineMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKBarcodeEngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeEngineMode","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController\/engineMode"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeScanAndCountViewController":{"kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the barcode detector."},{"type":"text","text":" "},{"type":"text","text":"Screen also shows snap, scan more and reset buttons."},{"type":"text","text":" "},{"type":"text","text":"The snap button starts the scanning when tapped."},{"type":"text","text":" "},{"type":"text","text":"The snap button resets the scanning when tapped again."},{"type":"text","text":" "},{"type":"text","text":"Instead it is installing itself as a child view controller onto a given parent view controller."}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeScanAndCountViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodescanandcountviewcontroller","role":"symbol","title":"SBSDKBarcodeScanAndCountViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeEngineMode/nextGen":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode\/nextGen","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeenginemode\/nextgen","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Next generation engine mode based on machine learning."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextGen"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeEngineModeNextGen"}],"title":"SBSDKBarcodeEngineMode.nextGen","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeEngineMode":{"role":"symbol","abstract":[{"type":"text","text":"The engine mode of the barcode recognizer."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeenginemode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBarcodeEngineMode"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeEngineMode"}],"title":"SBSDKBarcodeEngineMode","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"engineMode","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"engineMode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeEngineMode","kind":"typeIdentifier","text":"SBSDKBarcodeEngineMode","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKBarcodeEngineMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"engineMode"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"engineMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController~1engineMode\/title","op":"replace"},{"value":[{"text":"engineMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController~1engineMode\/fragments","op":"replace"},{"value":"SBSDKBarcodeScanAndCountViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeScanAndCountViewController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/fragments","op":"replace"},{"value":[{"text":"SBSDKBarcodeScanAndCountViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeScanAndCountViewController\/navigatorTitle","op":"replace"},{"value":"SBSDKBarcodeEngineModeNextGen","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode~1nextGen\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeEngineModeNextGen"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode~1nextGen\/fragments","op":"replace"},{"value":"SBSDKBarcodeEngineMode","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode\/title","op":"replace"},{"value":[{"text":"SBSDKBarcodeEngineMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKBarcodeEngineMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeEngineMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}