{"metadata":{"title":"background","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle","text":"SBSDKUI2BackgroundStyle","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"background","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CreditCardScanGuidanceConfiguration(py)background"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/background"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"background"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","kind":"typeIdentifier","text":"SBSDKUI2BackgroundStyle","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/background"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/background"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration"]]},"abstract":[{"text":"Configure the background style for the user guidance hints.","type":"text"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2BackgroundStyle":{"navigatorTitle":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration of the background appearance for buttons and hints.","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}],"title":"SBSDKUI2BackgroundStyle","url":"\/documentation\/scanbotsdk\/sbsdkui2backgroundstyle","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration":{"abstract":[{"type":"text","text":"Configuration of the hints guiding users through the credit card scanning process."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}],"type":"topic","title":"SBSDKUI2CreditCardScanGuidanceConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CreditCardScanGuidanceConfiguration/background":{"abstract":[{"text":"Configure the background style for the user guidance hints.","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2creditcardscanguidanceconfiguration\/background","title":"background","navigatorTitle":[{"text":"background","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CreditCardScanGuidanceConfiguration\/background","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKUI2BackgroundStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"background"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"background"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2BackgroundStyle","text":"SBSDKUI2BackgroundStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2BackgroundStyle"},{"text":" * ","kind":"text"},{"text":"background","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/title","value":"SBSDKUI2BackgroundStyle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/fragments","value":[{"text":"SBSDKUI2BackgroundStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2BackgroundStyle\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2BackgroundStyle"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/title","op":"replace","value":"SBSDKUI2CreditCardScanGuidanceConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CreditCardScanGuidanceConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2CreditCardScanGuidanceConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1background\/title","op":"replace","value":"background"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CreditCardScanGuidanceConfiguration~1background\/fragments","op":"replace","value":[{"kind":"identifier","text":"background"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}