{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedPointA:pointB:pointC:pointD:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"One of the designated initializer methods."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizedpointa:pointb:pointc:pointd:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizedpointa:pointb:pointc:pointd:)"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithNormalizedPointA:pointB:pointC:pointD:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"normalizedPointA","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"a","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"pointB","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"b","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"pointC","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"c","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"pointD","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"d","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The first point of the polygon in unit coordinates."}]}],"name":"a"},{"content":[{"inlineContent":[{"text":"The second point of the polygon in unit coordinates.","type":"text"}],"type":"paragraph"}],"name":"b"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The third point of the polygon in unit coordinates.","type":"text"}]}],"name":"c"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The fourth point of the polygon in unit coordinates.","type":"text"}]}],"name":"d"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon(im)initWithNormalizedPointA:pointB:pointC:pointD:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"normalizedPointA","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"pointB","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"pointC","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"text":"pointD","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":")","kind":"text"}],"title":"init(normalizedPointA:pointB:pointC:pointD:)","roleHeading":"Initializer","modules":[{"name":"ScanbotSDK"}],"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithNormalizedPointA:pointB:pointC:pointD:","kind":"identifier"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"type":"topic","role":"symbol","abstract":[{"text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","title":"SBSDKPolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPolygon","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/init(normalizedPointA:pointB:pointC:pointD:)":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/init(normalizedPointA:pointB:pointC:pointD:)","kind":"symbol","abstract":[{"type":"text","text":"One of the designated initializer methods."}],"title":"init(normalizedPointA:pointB:pointC:pointD:)","navigatorTitle":[{"kind":"identifier","text":"initWithNormalizedPointA:pointB:pointC:pointD:"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"normalizedPointA"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pointB"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pointC"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pointD"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":")"}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/init(normalizedpointa:pointb:pointc:pointd:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithNormalizedPointA:pointB:pointC:pointD:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNormalizedPointA:pointB:pointC:pointD:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithNormalizedPointA:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") ","kind":"text"},{"text":"a","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pointB:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") ","kind":"text"},{"text":"b","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pointC:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") ","kind":"text"},{"text":"c","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pointD:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"d"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The first point of the polygon in unit coordinates.","type":"text"}],"type":"paragraph"}],"name":"a"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The second point of the polygon in unit coordinates."}]}],"name":"b"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The third point of the polygon in unit coordinates."}]}],"name":"c"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The fourth point of the polygon in unit coordinates."}]}],"name":"d"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon","op":"replace"},{"op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKPolygon"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle"},{"op":"replace","value":"initWithNormalizedPointA:pointB:pointC:pointD:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedPointA:pointB:pointC:pointD:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNormalizedPointA:pointB:pointC:pointD:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1init(normalizedPointA:pointB:pointC:pointD:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}