{"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKPolygon(im)normalizedPointWithIndex:","navigatorTitle":[{"text":"normalizedPointWithIndex:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normalizedPoint"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"}],"modules":[{"name":"ScanbotSDK"}],"title":"normalizedPoint(with:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedPoint(with:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon"]]},"abstract":[{"text":"Returns the normalized point at the given index.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(normalizedPointWithIndex:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"normalizedPoint","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"index","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"}]}]},{"kind":"parameters","parameters":[{"name":"index","content":[{"inlineContent":[{"type":"text","text":"The index of the point in the receiver. Must be in range {0-3}."}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The normalized point."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/normalizedpoint(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpolygon\/normalizedpoint(with:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon/normalizedPoint(with:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedPoint"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"role":"symbol","navigatorTitle":[{"text":"normalizedPointWithIndex:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon\/normalizedPoint(with:)","title":"normalizedPoint(with:)","abstract":[{"type":"text","text":"Returns the normalized point at the given index."}],"url":"\/documentation\/scanbotsdk\/sbsdkpolygon\/normalizedpoint(with:)","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygon":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkpolygon","navigatorTitle":[{"text":"SBSDKPolygon","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This class represents a 4-polygon, a polygon with 4 edges. The polygons points are stored in a normalized unit coordinate system from {0, 0} to {1, 1}."}],"title":"SBSDKPolygon","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygon","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPolygon","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"normalizedPointWithIndex:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"normalizedPointWithIndex:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":") ","kind":"text"},{"text":"normalizedPointWithIndex:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"index","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The index of the point in the receiver. Must be in range {0-3}."}],"type":"paragraph"}],"name":"index"}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The normalized point.","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"value":"normalizedPointWithIndex:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedPoint(with:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon~1normalizedPoint(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"normalizedPointWithIndex:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/title","value":"SBSDKPolygon","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/fragments","value":[{"text":"SBSDKPolygon","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygon\/navigatorTitle","op":"replace","value":[{"text":"SBSDKPolygon","kind":"identifier"}]}]}]}