{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithGenericDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesd\/initwithgenericdocument:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD(im)initWithGenericDocument:","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"title":"initWithGenericDocument:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD\/initWithGenericDocument:"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD":{"navigatorTitle":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD","kind":"identifier"}],"abstract":[{"text":"EuropeanDriverLicenseBack.Categories.D","type":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD","role":"symbol","type":"topic","title":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesd"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD/initWithGenericDocument:":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithGenericDocument:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithGenericDocument:","kind":"identifier"}],"role":"symbol","title":"initWithGenericDocument:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD\/initWithGenericDocument:","url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodeleuropeandriverlicensebackcategoriesd\/initwithgenericdocument:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"title":"SBSDKGenericDocument","abstract":[{"type":"text","text":"Generic document."}],"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKGenericDocument"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD\/title","value":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD\/navigatorTitle","value":[{"text":"SBSDKDocumentsModelEuropeanDriverLicenseBackCategoriesD","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKGenericDocument"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}