{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"An optional handler that will be called when the zooming ends. The current zoom scale is passed as a parameter."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/didEndZoomHandler"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/didendzoomhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/didendzoomhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didEndZoomHandler","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ())?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView"]]},"metadata":{"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKZoomingImageScrollView(py)didEndZoomHandler","title":"didEndZoomHandler","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didEndZoomHandler"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEndZoomHandler"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> ())?"}]},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView":{"role":"symbol","title":"SBSDKZoomingImageScrollView","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView","kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"abstract":[{"type":"text","text":"A scrollable and zoomable "},{"type":"codeVoice","code":"UIScrollView"},{"type":"text","text":" subclass that displays images and an overlay view."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKZoomingImageScrollView/didEndZoomHandler":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkzoomingimagescrollview\/didendzoomhandler","title":"didEndZoomHandler","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didEndZoomHandler"}],"abstract":[{"text":"An optional handler that will be called when the zooming ends. The current zoom scale is passed as a parameter.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEndZoomHandler"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> ())?"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKZoomingImageScrollView\/didEndZoomHandler"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"didEndZoomHandler"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"didEndZoomHandler"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"kind":"identifier","text":"didEndZoomHandler"},{"kind":"text","text":")("},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/title","op":"replace","value":"SBSDKZoomingImageScrollView"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}]},{"value":[{"kind":"identifier","text":"SBSDKZoomingImageScrollView"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView\/navigatorTitle"},{"value":"didEndZoomHandler","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1didEndZoomHandler\/title"},{"value":[{"text":"didEndZoomHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKZoomingImageScrollView~1didEndZoomHandler\/fragments"}]}]}