{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm"},{"text":"]","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"}],"role":"symbol","title":"msiPlesseyChecksumAlgorithm","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUIBarcodeAdditionalParameters(py)msiPlesseyChecksumAlgorithm"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeAdditionalParameters"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm","text":"SBSDKMSIPlesseyChecksumAlgorithm"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/mod10","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodeadditionalparameters\/msiplesseychecksumalgorithm"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodeadditionalparameters\/msiplesseychecksumalgorithm"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeAdditionalParameters\/msiPlesseyChecksumAlgorithm","interfaceLanguage":"swift"},"abstract":[{"text":"The checksum algorithms for MSI Plessey barcodes.","type":"text"}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMSIPlesseyChecksumAlgorithm":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm","title":"SBSDKMSIPlesseyChecksumAlgorithm","abstract":[{"type":"text","text":"Checksum algorithm for MSI_PLESSEY."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeAdditionalParameters":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeAdditionalParameters","abstract":[{"text":"A class that contains additional parameters for barcodes scanning and filtering.","type":"text"}],"title":"SBSDKUIBarcodeAdditionalParameters","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodeadditionalparameters","kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUIBarcodeAdditionalParameters/msiPlesseyChecksumAlgorithm":{"kind":"symbol","abstract":[{"type":"text","text":"The checksum algorithms for MSI Plessey barcodes."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUIBarcodeAdditionalParameters\/msiPlesseyChecksumAlgorithm","title":"msiPlesseyChecksumAlgorithm","navigatorTitle":[{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkuibarcodeadditionalparameters\/msiplesseychecksumalgorithm","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKMSIPlesseyChecksumAlgorithm/mod10":{"title":"mod10","abstract":[{"type":"text","text":"Modulo 10."}],"navigatorTitle":[{"text":"mod10","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkmsiplesseychecksumalgorithm\/mod10","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKMSIPlesseyChecksumAlgorithm\/mod10","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mod10"},{"text":": ","kind":"text"},{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKMSIPlesseyChecksumAlgorithm"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"msiPlesseyChecksumAlgorithm","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"msiPlesseyChecksumAlgorithm","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKMSIPlesseyChecksumAlgorithm *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKMSIPlesseyChecksumAlgorithm","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/title"},{"value":[{"kind":"identifier","text":"SBSDKMSIPlesseyChecksumAlgorithm"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm\/navigatorTitle","value":[{"text":"SBSDKMSIPlesseyChecksumAlgorithm","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeAdditionalParameters\/title","op":"replace","value":"SBSDKUIBarcodeAdditionalParameters"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeAdditionalParameters\/fragments","value":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeAdditionalParameters\/navigatorTitle","value":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeAdditionalParameters~1msiPlesseyChecksumAlgorithm\/title","value":"msiPlesseyChecksumAlgorithm","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUIBarcodeAdditionalParameters~1msiPlesseyChecksumAlgorithm\/fragments","value":[{"kind":"identifier","text":"msiPlesseyChecksumAlgorithm"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1mod10\/title","op":"replace","value":"mod10"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKMSIPlesseyChecksumAlgorithm~1mod10\/fragments","op":"replace","value":[{"kind":"identifier","text":"mod10"}]}]}]}