{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions\/init()"]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions\/init()","interfaceLanguage":"swift"},"metadata":{"title":"init()","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKEncodeImageOptions(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodeImageOptions/init()":{"title":"init()","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions\/init()","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions\/init()"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","type":"topic","title":"ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.1.2","type":"text"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKEncodeImageOptions":{"role":"symbol","navigatorTitle":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkencodeimageoptions","title":"SBSDKEncodeImageOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"abstract":[{"type":"text","text":"Options for encoding image."}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKEncodeImageOptions","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/title","value":"SBSDKEncodeImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/fragments","value":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKEncodeImageOptions\/navigatorTitle","op":"replace","value":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}