{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration\/init"]}],"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIHealthInsuranceCardRecognizerUIConfiguration(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/init"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration/init":{"title":"init","kind":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration\/init","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/init","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration":{"title":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkuihealthinsurancecardrecognizeruiconfiguration","abstract":[{"type":"text","text":"Configuration for user interface of the detector RTU-UI screen for Health Insurance Card scanner."}],"navigatorTitle":[{"text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/title","op":"replace","value":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIHealthInsuranceCardRecognizerUIConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKUIHealthInsuranceCardRecognizerUIConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}