{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Adds a date validation config for a single field. Existing date validators for the specified field will be overwritten."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/adddatevalidatorconfiguration(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/adddatevalidatorconfiguration(_:)"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/addDateValidatorConfiguration(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationBuilder(im)addDateValidatorConfiguration:","title":"addDateValidatorConfiguration(_:)","symbolKind":"method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"addDateValidatorConfiguration:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDateValidatorConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDateValidatorConfiguration"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"typeIdentifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The date validation configuration to be used to validate the field specified in the configuration."}]}]}],"kind":"parameters"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/addDateValidatorConfiguration(_:)":{"kind":"symbol","abstract":[{"text":"Adds a date validation config for a single field. Existing date validators for the specified field will be overwritten.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addDateValidatorConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/adddatevalidatorconfiguration(_:)","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/addDateValidatorConfiguration(_:)","title":"addDateValidatorConfiguration(_:)","navigatorTitle":[{"text":"addDateValidatorConfiguration:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocumentRecognizerDateValidationConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration","abstract":[{"type":"text","text":"Date validation configuration."},{"text":" ","type":"text"},{"type":"text","text":"This configuration element does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"text":"Add to recognizer configuration to require date validation checks for specific document types.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkgenericdocumentrecognizerdatevalidationconfiguration","title":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder":{"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A builder class to help with assembling the configuration for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationBuilder"}],"title":"SBSDKDocumentDataExtractorConfigurationBuilder","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"title":"SBSDKDocumentDataExtractor","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A class to extract generic documents data on various image sources."},{"type":"text","text":" "},{"text":"Extracts the sub-documents, field names and field values from many types of documents e.g. German passports, ID cards, driver’s licenses.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"addDateValidatorConfiguration:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addDateValidatorConfiguration:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"addDateValidatorConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocumentRecognizerDateValidationConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"typeIdentifier","text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The date validation configuration to be used to validate the field specified in the configuration."}],"type":"paragraph"}],"name":"config"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"addDateValidatorConfiguration:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1addDateValidatorConfiguration(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addDateValidatorConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1addDateValidatorConfiguration(_:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/title","value":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","op":"replace"},{"op":"replace","value":[{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocumentRecognizerDateValidationConfiguration\/navigatorTitle","value":[{"text":"SBSDKGenericDocumentRecognizerDateValidationConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/title","value":"SBSDKDocumentDataExtractorConfigurationBuilder"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/fragments","value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/navigatorTitle","value":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/title","value":"SBSDKDocumentDataExtractor"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}