{"abstract":[{"text":"Lets you fine-tune the recognition of machine-readable-zone-based documents. Setting this property will automatically add the document type ","type":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/mrz","isActive":true,"type":"reference"},{"type":"text","text":" to the accepted document types."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorConfigurationBuilder(im)setMachineReadableZoneConfiguration:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMachineReadableZoneConfiguration"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"setMachineReadableZoneConfiguration:","kind":"identifier"}],"role":"symbol","symbolKind":"method","title":"setMachineReadableZoneConfiguration(_:)","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMachineReadableZoneConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"text":"The machine-readable-zone-based generic document recognizer configuration.","type":"text"}]}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setmachinereadablezoneconfiguration(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setmachinereadablezoneconfiguration(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setMachineReadableZoneConfiguration(_:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder/setMachineReadableZoneConfiguration(_:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder\/setMachineReadableZoneConfiguration(_:)","navigatorTitle":[{"text":"setMachineReadableZoneConfiguration:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Lets you fine-tune the recognition of machine-readable-zone-based documents. Setting this property will automatically add the document type ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/mrz"},{"type":"text","text":" to the accepted document types."}],"type":"topic","title":"setMachineReadableZoneConfiguration(_:)","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder\/setmachinereadablezoneconfiguration(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMachineReadableZoneConfiguration"},{"kind":"text","text":"("},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration"},{"text":")","kind":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorConfigurationBuilder":{"navigatorTitle":[{"text":"SBSDKDocumentDataExtractorConfigurationBuilder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A builder class to help with assembling the configuration for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor"},{"type":"text","text":"."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractorconfigurationbuilder","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationBuilder"}],"title":"SBSDKDocumentDataExtractorConfigurationBuilder","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorConfigurationBuilder"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractorMRZFallbackConfiguration":{"title":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractormrzfallbackconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"symbol","abstract":[{"type":"text","text":"MRZ fallback configuration element."},{"type":"text","text":" "},{"type":"text","text":"This configuration element does not enable the scanning of any document types by itself."},{"type":"text","text":" "},{"type":"text","text":"Add to extractor configuration to enable recognizing the MRZ only, specifically for documents that are otherwise not"},{"text":" ","type":"text"},{"type":"text","text":"supported."},{"type":"text","text":" "},{"type":"text","text":"Note that this may enable scanning of documents that were not enabled through the accepted document types."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentsModelRootType/mrz":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"mrz","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentsModelRootType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentsModelRootType"}],"kind":"symbol","abstract":[{"text":"MRZ document type.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentsmodelroottype\/mrz","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentsModelRootType\/mrz","type":"topic","navigatorTitle":[{"text":"mrz","kind":"identifier"}],"title":"mrz"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDataExtractor":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"title":"SBSDKDocumentDataExtractor","url":"\/documentation\/scanbotsdk\/sbsdkdocumentdataextractor","kind":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractor","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A class to extract generic documents data on various image sources."},{"type":"text","text":" "},{"text":"Extracts the sub-documents, field names and field values from many types of documents e.g. German passports, ID cards, driver’s licenses.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setMachineReadableZoneConfiguration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"setMachineReadableZoneConfiguration:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setMachineReadableZoneConfiguration:"},{"text":"(","kind":"text"},{"text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDataExtractorMRZFallbackConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDataExtractorMRZFallbackConfiguration"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The machine-readable-zone-based generic document recognizer configuration.","type":"text"}]}],"name":"config"}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setMachineReadableZoneConfiguration(_:)\/title","value":"setMachineReadableZoneConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder~1setMachineReadableZoneConfiguration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMachineReadableZoneConfiguration:"}],"op":"replace"},{"value":"SBSDKDocumentDataExtractorConfigurationBuilder","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationBuilder"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorConfigurationBuilder\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorConfigurationBuilder"}],"op":"replace"},{"value":"SBSDKDocumentDataExtractorMRZFallbackConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}]},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractorMRZFallbackConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractorMRZFallbackConfiguration\/navigatorTitle"},{"value":"mrz","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1mrz\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentsModelRootType~1mrz\/fragments","value":[{"text":"mrz","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/title","value":"SBSDKDocumentDataExtractor"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDataExtractor"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentDataExtractor","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDataExtractor\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}