{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"s:7SwiftUI4ViewPAAE36accessibilityShowsLargeContentViewerQryF::SYNTHESIZED::s:25ScanbotDocumentScannerSDK08SBSDKUI2bC4ViewV","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityShowsLargeContentViewer","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"15.0","beta":false,"name":"iOS"},{"deprecated":false,"unavailable":false,"introducedAt":"15.0","beta":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"introducedAt":"15.0","beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"introducedAt":"12.0","beta":false,"name":"macOS"},{"deprecated":false,"unavailable":false,"introducedAt":"15.0","beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false,"name":"watchOS"}],"title":"accessibilityShowsLargeContentViewer()","role":"symbol","roleHeading":"Instance Method","extendedModule":"SwiftUICore","modules":[{"relatedModules":["SwiftUICore"],"name":"ScanbotDocumentScannerSDK"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityShowsLargeContentViewer","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":"\n","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerview\/accessibilityshowslargecontentviewer()"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView\/accessibilityShowsLargeContentViewer()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.accessibilityShowsLargeContentViewer()"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"]]},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerView/View-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerview\/view-implementations","title":"View Implementations","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerView/accessibilityShowsLargeContentViewer()":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerview\/accessibilityshowslargecontentviewer()","type":"topic","abstract":[],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView\/accessibilityShowsLargeContentViewer()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityShowsLargeContentViewer"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"}],"kind":"symbol","title":"accessibilityShowsLargeContentViewer()"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerController":{"role":"symbol","title":"SBSDKUI2DocumentScannerController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannercontroller","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI controller to scan documents."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUI2DocumentScannerView":{"abstract":[{"text":"The SwiftUI wrapper for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerController","type":"reference"},{"text":".","type":"text"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkui2documentscannerview","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUI2DocumentScannerView","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerView","kind":"identifier"}],"title":"SBSDKUI2DocumentScannerView","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/title","value":"SBSDKUI2DocumentScannerController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUI2DocumentScannerController\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"op":"replace"}]}]}