{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode\/init(scanningcompletedcolor:scanningpartiallycolor:scanningnotscannedcolor:allowpartialscan:expectedbarcodes:countingrepeatdelay:sheet:sheetcontent:manualcounteditdialog:aroverlay:partialscannedalertdialogenabled:partialscannedalertdialog:c-8ofi3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode\/init(scanningcompletedcolor:scanningpartiallycolor:scanningnotscannedcolor:allowpartialscan:expectedbarcodes:countingrepeatdelay:sheet:sheetcontent:manualcounteditdialog:aroverlay:partialscannedalertdialogenabled:partialscannedalertdialog:c-8ofi3"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2FindAndPickScanningMode(im)initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","navigatorTitle":[{"kind":"identifier","text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:"}],"title":"init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"scanningCompletedColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"scanningPartiallyColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scanningNotScannedColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"allowPartialScan","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"expectedBarcodes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SBSDKUI2ExpectedBarcode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ExpectedBarcode"},{"kind":"text","text":"], "},{"text":"countingRepeatDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sheet","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet","text":"SBSDKUI2Sheet","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sheetContent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent","kind":"typeIdentifier","text":"SBSDKUI2SheetContent"},{"kind":"text","text":", "},{"text":"manualCountEditDialog","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog"},{"text":", ","kind":"text"},{"text":"arOverlay","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration","text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"partialScannedAlertDialogEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"partialScannedAlertDialog","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"confirmationAlertDialogEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"confirmationAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog"},{"text":")","kind":"text"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scanningCompletedColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" = SBSDKUI2Color(colorString: \"?sbColorPositive\", isArgb: false), ","kind":"text"},{"text":"scanningPartiallyColor","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorWarning\", isArgb: false), "},{"text":"scanningNotScannedColor","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"kind":"text","text":" = SBSDKUI2Color(colorString: \"?sbColorOutline\", isArgb: false), "},{"text":"allowPartialScan","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"expectedBarcodes","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ExpectedBarcode","text":"SBSDKUI2ExpectedBarcode","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ExpectedBarcode"},{"kind":"text","text":"] = [], "},{"text":"countingRepeatDelay","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":" = 1000, ","kind":"text"},{"kind":"externalParam","text":"sheet"},{"kind":"text","text":": "},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet"},{"text":" = SBSDKUI2Sheet(mode: SBSDKUI2SheetMode.collapsedSheet,\n                                                     collapsedVisibleHeight: SBSDKUI2CollapsedVisibleHeight.small,\n                                                     listButton: SBSDKUI2BadgedButton(badgeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                          isArgb: false),\n                                                                                      badgeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                          isArgb: false),\n                                                                                      visible: true,\n                                                                                      backgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                     isArgb: false),\n                                                                                      foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                     isArgb: false),\n                                                                                      activeBackgroundColor: SBSDKUI2Color(colorString: \"?sbColorSurfaceHigh\",\n                                                                                                                           isArgb: false),\n                                                                                      activeForegroundColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                           isArgb: false))), ","kind":"text"},{"kind":"externalParam","text":"sheetContent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent","kind":"typeIdentifier"},{"text":" = SBSDKUI2SheetContent(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\", isArgb: false),\n                                         dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                     isArgb: false),\n                                         manualCountChangeEnabled: true,\n                                         manualCountOutlineColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                isArgb: false),\n                                         manualCountChangeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                               isArgb: false),\n                                         title: SBSDKUI2StyledText(visible: true,\n                                                                   text: \"?findAndPickSheetTitle\",\n                                                                   color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                        isArgb: false),\n                                                                   useShadow: false),\n                                         clearAllButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                     text: \"?sheetResetButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                    isArgb: false),\n                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 1.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                              isArgb: false),\n                                                                                                                         useShadow: false)),\n                                         barcodeItemTitle: SBSDKUI2StyledText(text: \"BARCODE_TITLE\",\n                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                   isArgb: false)),\n                                         barcodeItemSubtitle: SBSDKUI2StyledText(text: \"?findAndPickSheetBarcodeItemSubtitle\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                      isArgb: false)),\n                                         barcodeItemImageVisible: true,\n                                         submitButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                   text: \"?sheetSubmitButton\",\n                                                                                   background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                isArgb: false),\n                                                                                                                       strokeWidth: 1.0),\n                                                                                   foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                       color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                            isArgb: false),\n                                                                                                                       useShadow: false)),\n                                         startScanningButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                          text: \"?sheetStartScanningButton\",\n                                                                                          background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                              fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                       isArgb: false),\n                                                                                                                              strokeWidth: 1.0),\n                                                                                          foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                   isArgb: false),\n                                                                                                                              useShadow: false)),\n                                         placeholderTitle: SBSDKUI2StyledText(text: \"?sheetPlaceholderTitle\",\n                                                                              color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                   isArgb: false)),\n                                         placeholderSubtitle: SBSDKUI2StyledText(text: \"?sheetPlaceholderSubtitle\",\n                                                                                 color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                      isArgb: false)),\n                                         placeholderIconBackground: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                                  isArgb: false),\n                                         placeholderIcon: SBSDKUI2IconStyle(visible: true,\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                 isArgb: false)),\n                                         swipeToDelete: SBSDKUI2SwipeToDelete(enabled: false,\n                                                                              backgroundColor: SBSDKUI2Color(colorString: \"?sbColorNegative\",\n                                                                                                             isArgb: false),\n                                                                              iconColor: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                       isArgb: false))), ","kind":"text"},{"text":"manualCountEditDialog","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog"},{"kind":"text","text":" = SBSDKUI2ManualCountEditDialog(sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                            isArgb: false),\n                                                  dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                              isArgb: false),\n                                                  modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                   isArgb: false),\n                                                  title: SBSDKUI2StyledText(text: \"?manualCountEditDialogTitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                 isArgb: false)),\n                                                  info: SBSDKUI2StyledText(text: \"?manualCountEditDialogInfo\",\n                                                                           color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                isArgb: false)),\n                                                  updateButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?manualCountEditDialogUpdateButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 1.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                  cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                            text: \"?manualCountEditDialogCancelButton\",\n                                                                                            background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                           isArgb: false),\n                                                                                                                                fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                         isArgb: false),\n                                                                                                                                strokeWidth: 1.0),\n                                                                                            foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                                color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                     isArgb: false),\n                                                                                                                                useShadow: false)),\n                                                  clearTextButton: SBSDKUI2IconStyle(visible: true,\n                                                                                     color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                          isArgb: false))), "},{"text":"arOverlay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration"},{"kind":"text","text":" = SBSDKUI2ArOverlayFindAndPickConfiguration(visible: true,\n                                                              automaticSelectionEnabled: true,\n                                                              polygon: SBSDKUI2FindAndPickArOverlayPolygonConfiguration(partiallyScanned: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorWarning\",\n                                                                                                                                                                                          isArgb: false),\n                                                                                                                                                               fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                               strokeWidth: 3.0,\n                                                                                                                                                               cornerRadius: 5.0),\n                                                                                                                        rejected: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                  isArgb: false),\n                                                                                                                                                       fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                isArgb: false),\n                                                                                                                                                       strokeWidth: 3.0,\n                                                                                                                                                       cornerRadius: 5.0),\n                                                                                                                        completed: SBSDKUI2PolygonStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                   isArgb: false),\n                                                                                                                                                        fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                                                 isArgb: false),\n                                                                                                                                                        strokeWidth: 3.0,\n                                                                                                                                                        cornerRadius: 5.0)),\n                                                              badge: SBSDKUI2FindAndPickBadgeConfiguration(partiallyScanned: SBSDKUI2BadgeStyle(visible: true,\n                                                                                                                                                background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#000000FF\",\n                                                                                                                                                                                                               isArgb: false),\n                                                                                                                                                                                    fillColor: SBSDKUI2Color(colorString: \"?sbColorWarning\",\n                                                                                                                                                                                                             isArgb: false),\n                                                                                                                                                                                    strokeWidth: 0.0),\n                                                                                                                                                foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                               isArgb: false)),\n                                                                                                           rejected: SBSDKUI2BadgeStyle(visible: true,\n                                                                                                                                        background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#000000FF\",\n                                                                                                                                                                                                       isArgb: false),\n                                                                                                                                                                            fillColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                                                                                                                                                     isArgb: false),\n                                                                                                                                                                            strokeWidth: 0.0),\n                                                                                                                                        foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                       isArgb: false)),\n                                                                                                           completed: SBSDKUI2BadgeStyle(visible: true,\n                                                                                                                                         background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#000000FF\",\n                                                                                                                                                                                                        isArgb: false),\n                                                                                                                                                                             fillColor: SBSDKUI2Color(colorString: \"?sbColorPositive\",\n                                                                                                                                                                                                      isArgb: false),\n                                                                                                                                                                             strokeWidth: 0.0),\n                                                                                                                                         foregroundColor: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                                                                                                        isArgb: false)))), "},{"text":"partialScannedAlertDialogEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"partialScannedAlertDialog"},{"kind":"text","text":": "},{"text":"SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":" = SBSDKUI2ScanbotAlertDialog(title: SBSDKUI2StyledText(text: \"?findAndPickPartialAlertTitle\",\n                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                              isArgb: false)),\n                                               subtitle: SBSDKUI2StyledText(text: \"?findAndPickPartialAlertSubtitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                 isArgb: false)),\n                                               sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                         isArgb: false),\n                                               modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                isArgb: false),\n                                               dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                           isArgb: false),\n                                               okButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                     text: \"?findAndPickPartialAlertSubmitButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                    isArgb: false),\n                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 1.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                              isArgb: false),\n                                                                                                                         useShadow: false)),\n                                               cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                         text: \"?findAndPickPartialAlertCancelButton\",\n                                                                                         background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                        isArgb: false),\n                                                                                                                             fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                             strokeWidth: 1.0),\n                                                                                         foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                             color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                             useShadow: false))), "},{"text":"confirmationAlertDialogEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"confirmationAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","text":"SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":" = SBSDKUI2ScanbotAlertDialog(title: SBSDKUI2StyledText(text: \"?findAndPickCompleteAlertTitle\",\n                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnSurface\",\n                                                                                              isArgb: false)),\n                                               subtitle: SBSDKUI2StyledText(text: \"?findAndPickCompleteAlertSubtitle\",\n                                                                            color: SBSDKUI2Color(colorString: \"?sbColorOnSurfaceVariant\",\n                                                                                                 isArgb: false)),\n                                               sheetColor: SBSDKUI2Color(colorString: \"?sbColorSurface\",\n                                                                         isArgb: false),\n                                               modalOverlayColor: SBSDKUI2Color(colorString: \"?sbColorModalOverlay\",\n                                                                                isArgb: false),\n                                               dividerColor: SBSDKUI2Color(colorString: \"?sbColorOutline\",\n                                                                           isArgb: false),\n                                               okButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                     text: \"?findAndPickCompleteAlertSubmitButton\",\n                                                                                     background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                    isArgb: false),\n                                                                                                                         fillColor: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                         strokeWidth: 1.0),\n                                                                                     foreground: SBSDKUI2ForegroundStyle(iconVisible: true,\n                                                                                                                         color: SBSDKUI2Color(colorString: \"?sbColorOnPrimary\",\n                                                                                                                                              isArgb: false),\n                                                                                                                         useShadow: false)),\n                                               cancelButton: SBSDKUI2ButtonConfiguration(visible: true,\n                                                                                         text: \"?findAndPickCompleteAlertCancelButton\",\n                                                                                         background: SBSDKUI2BackgroundStyle(strokeColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                        isArgb: false),\n                                                                                                                             fillColor: SBSDKUI2Color(colorString: \"#00000000\",\n                                                                                                                                                      isArgb: false),\n                                                                                                                             strokeWidth: 1.0),\n                                                                                         foreground: SBSDKUI2ForegroundStyle(iconVisible: false,\n                                                                                                                             color: SBSDKUI2Color(colorString: \"?sbColorPrimary\",\n                                                                                                                                                  isArgb: false),\n                                                                                                                             useShadow: false))))"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode\/init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"title":"SBSDKUI2Color","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","type":"topic","abstract":[],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ExpectedBarcode":{"kind":"symbol","type":"topic","title":"SBSDKUI2ExpectedBarcode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ExpectedBarcode"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2expectedbarcode","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ExpectedBarcode","abstract":[{"type":"text","text":"Configuration of the barcode to find and scan."}],"navigatorTitle":[{"text":"SBSDKUI2ExpectedBarcode","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Sheet":{"abstract":[{"type":"text","text":"Configuration of the preview mode for scanning multiple barcodes."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheet","title":"SBSDKUI2Sheet","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Sheet"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2Sheet","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ArOverlayFindAndPickConfiguration":{"title":"SBSDKUI2ArOverlayFindAndPickConfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2aroverlayfindandpickconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the AR overlay."}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ManualCountEditDialog":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2manualcounteditdialog","type":"topic","abstract":[{"type":"text","text":"Configuration of the dialog to manually edit the barcode count."}],"role":"symbol","title":"SBSDKUI2ManualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","navigatorTitle":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2SheetContent":{"abstract":[{"text":"Configuration of the list containing the barcodes that have already been scanned.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SBSDKUI2SheetContent","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2sheetcontent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","abstract":[{"type":"text","text":"Version: 6.1.0"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","kind":"symbol","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ScanbotAlertDialog":{"abstract":[{"type":"text","text":"Configuration of the the standard alert dialog."}],"title":"SBSDKUI2ScanbotAlertDialog","role":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2scanbotalertdialog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","navigatorTitle":[{"text":"SBSDKUI2ScanbotAlertDialog","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickScanningMode/init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode\/init(scanningcompletedcolor:scanningpartiallycolor:scanningnotscannedcolor:allowpartialscan:expectedbarcodes:countingrepeatdelay:sheet:sheetcontent:manualcounteditdialog:aroverlay:partialscannedalertdialogenabled:partialscannedalertdialog:c-8ofi3","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"scanningCompletedColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanningPartiallyColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scanningNotScannedColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","kind":"typeIdentifier","text":"SBSDKUI2Color"},{"text":", ","kind":"text"},{"text":"allowPartialScan","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expectedBarcodes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SBSDKUI2ExpectedBarcode","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ExpectedBarcode"},{"kind":"text","text":"], "},{"text":"countingRepeatDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sheet"},{"text":": ","kind":"text"},{"text":"SBSDKUI2Sheet","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet"},{"text":", ","kind":"text"},{"text":"sheetContent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent","text":"SBSDKUI2SheetContent"},{"kind":"text","text":", "},{"text":"manualCountEditDialog","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKUI2ManualCountEditDialog","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"},{"kind":"text","text":", "},{"text":"partialScannedAlertDialogEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"partialScannedAlertDialog"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"confirmationAlertDialogEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"confirmationAlertDialog","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode\/init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)","type":"topic","abstract":[],"title":"init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2FindAndPickScanningMode":{"type":"topic","title":"SBSDKUI2FindAndPickScanningMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2FindAndPickScanningMode","abstract":[{"type":"text","text":"Configuration of the Find and Pick barcode scanning mode."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2findandpickscanningmode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithScanningCompletedColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"text":"scanningCompletedColor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"scanningPartiallyColor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"scanningPartiallyColor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scanningNotScannedColor:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"text":"scanningNotScannedColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowPartialScan:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"allowPartialScan","kind":"internalParam"},{"kind":"text","text":" "},{"text":"expectedBarcodes:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<SBSDKUI2ExpectedBarcode *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expectedBarcodes"},{"kind":"text","text":" "},{"kind":"identifier","text":"countingRepeatDelay:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"countingRepeatDelay"},{"kind":"text","text":" "},{"text":"sheet:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKUI2Sheet","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Sheet","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Sheet","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sheet"},{"kind":"text","text":" "},{"kind":"identifier","text":"sheetContent:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2SheetContent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2SheetContent","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2SheetContent"},{"text":" *) ","kind":"text"},{"text":"sheetContent","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"manualCountEditDialog:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ManualCountEditDialog","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ManualCountEditDialog","text":"SBSDKUI2ManualCountEditDialog","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manualCountEditDialog","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"arOverlay:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ArOverlayFindAndPickConfiguration"},{"text":" *) ","kind":"text"},{"text":"arOverlay","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"partialScannedAlertDialogEnabled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"partialScannedAlertDialogEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"partialScannedAlertDialog:"},{"text":"(","kind":"text"},{"text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"partialScannedAlertDialog"},{"kind":"text","text":" "},{"text":"confirmationAlertDialogEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"confirmationAlertDialogEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationAlertDialog:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ScanbotAlertDialog","text":"SBSDKUI2ScanbotAlertDialog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ScanbotAlertDialog"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"confirmationAlertDialog"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Color"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2ExpectedBarcode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ExpectedBarcode\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ExpectedBarcode\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2ExpectedBarcode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ExpectedBarcode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ExpectedBarcode"}],"op":"replace"},{"value":"SBSDKUI2Sheet","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2Sheet"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Sheet\/navigatorTitle","value":[{"text":"SBSDKUI2Sheet","kind":"identifier"}]},{"op":"replace","value":"SBSDKUI2ArOverlayFindAndPickConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/title"},{"value":[{"text":"SBSDKUI2ArOverlayFindAndPickConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2ArOverlayFindAndPickConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ArOverlayFindAndPickConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/title","op":"replace","value":"SBSDKUI2ManualCountEditDialog"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/fragments","value":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ManualCountEditDialog\/navigatorTitle","value":[{"text":"SBSDKUI2ManualCountEditDialog","kind":"identifier"}],"op":"replace"},{"value":"SBSDKUI2SheetContent","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/title"},{"value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2SheetContent\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUI2SheetContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/title","op":"replace","value":"SBSDKUI2ScanbotAlertDialog"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ScanbotAlertDialog\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2ScanbotAlertDialog"}],"op":"replace"},{"value":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode~1init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithScanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode~1init(scanningCompletedColor:scanningPartiallyColor:scanningNotScannedColor:allowPartialScan:expectedBarcodes:countingRepeatDelay:sheet:sheetContent:manualCountEditDialog:arOverlay:partialScannedAlertDialogEnabled:partialScannedAlertDialog:confirmationAlertDialogEnabled:confirmationAlertDialog:)\/fragments"},{"op":"replace","value":"SBSDKUI2FindAndPickScanningMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/title"},{"op":"replace","value":[{"text":"SBSDKUI2FindAndPickScanningMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2FindAndPickScanningMode\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2FindAndPickScanningMode"}],"op":"replace"}]}]}