{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator"]]},"abstract":[{"type":"text","text":"Designated initializer."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"password","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"salt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"iterations","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"password","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The password to be used when generating the encryption key."}]}]},{"name":"salt","content":[{"type":"paragraph","inlineContent":[{"text":"The salt to be used when generating the encryption key.","type":"text"}]}]},{"name":"iterations","content":[{"inlineContent":[{"type":"text","text":"The number of iterations to be used when generating the encryption key."}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"title":"init(password:salt:iterations:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"salt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"iterations"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKPBKDF2KeyGenerator(im)initWithPassword:salt:iterations:","navigatorTitle":[{"kind":"identifier","text":"initWithPassword:salt:iterations:"}]},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator\/init(password:salt:iterations:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator\/init(password:salt:iterations:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator\/init(password:salt:iterations:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPBKDF2KeyGenerator/init(password:salt:iterations:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"password","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"salt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"iterations","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Designated initializer."}],"type":"topic","title":"init(password:salt:iterations:)","navigatorTitle":[{"text":"initWithPassword:salt:iterations:","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator\/init(password:salt:iterations:)","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator\/init(password:salt:iterations:)","role":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKPBKDF2KeyGenerator":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkpbkdf2keygenerator","title":"SBSDKPBKDF2KeyGenerator","navigatorTitle":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKPBKDF2KeyGenerator","abstract":[{"type":"text","text":"A key generator that uses the PBKDF2 algorithm to derive a key from a password and a salt."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/en.wikipedia.org\/wiki\/PBKDF2 for more information."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithPassword:salt:iterations:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPassword:salt:iterations:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPassword:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"password"},{"kind":"text","text":" "},{"kind":"identifier","text":"salt:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"salt","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"iterations:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"iterations","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"password","content":[{"type":"paragraph","inlineContent":[{"text":"The password to be used when generating the encryption key.","type":"text"}]}]},{"name":"salt","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The salt to be used when generating the encryption key."}]}]},{"name":"iterations","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of iterations to be used when generating the encryption key."}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"initWithPassword:salt:iterations:","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator~1init(password:salt:iterations:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPassword:salt:iterations:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator~1init(password:salt:iterations:)\/fragments","op":"replace"},{"value":"SBSDKPBKDF2KeyGenerator","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/title","op":"replace"},{"value":[{"text":"SBSDKPBKDF2KeyGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKPBKDF2KeyGenerator"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKPBKDF2KeyGenerator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}