{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The explanation text of the camera permission dialog.","type":"text"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization(py)cameraPermissionEnableCameraExplanation","navigatorTitle":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}],"role":"symbol","title":"cameraPermissionEnableCameraExplanation","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property"},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/camerapermissionenablecameraexplanation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/camerapermissionenablecameraexplanation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraExplanation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is “Please allow the usage of the camera to start the scanning process.”"}]}]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/cameraPermissionEnableCameraExplanation":{"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/camerapermissionenablecameraexplanation","navigatorTitle":[{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"}],"role":"symbol","title":"cameraPermissionEnableCameraExplanation","abstract":[{"type":"text","text":"The explanation text of the camera permission dialog."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/cameraPermissionEnableCameraExplanation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the all strings for document data extractor screen."}],"title":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cameraPermissionEnableCameraExplanation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionEnableCameraExplanation\/title","value":"cameraPermissionEnableCameraExplanation"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization~1cameraPermissionEnableCameraExplanation\/fragments","value":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/title","value":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization"}]}]}]}