{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTopBarTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"topBarTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"topBarCancelButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarCancelButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"topUserGuidance:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topUserGuidance"},{"kind":"text","text":" "},{"kind":"identifier","text":"introScreenTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"introScreenTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"introScreenDoneButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"introScreenDoneButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"introScreenText:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"introScreenText"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionOverlaySuccessMessage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"completionOverlaySuccessMessage"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionOpenIntroScreenButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionOpenIntroScreenButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionIntroScreenDoneButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionIntroScreenDoneButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionCancelButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionCancelButton"},{"kind":"text","text":" "},{"text":"accessibilityDescriptionRetryButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionRetryButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCloseScannerButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCloseScannerButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorAlertRetryButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorAlertRetryButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorAlertCloseScannerButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorAlertCloseScannerButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorNoDocumentDetectedAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorNoDocumentDetectedAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorNoDocumentDetectedAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorNoDocumentDetectedAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorCantProcessDocumentAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorCantProcessDocumentAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorCantProcessDocumentAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorCantProcessDocumentAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorUnsupportedDocumentAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorUnsupportedDocumentAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorUnsupportedDocumentAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorUnsupportedDocumentAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorScanningTooLongAlertTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorScanningTooLongAlertTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentDataExtractorScanningTooLongAlertSubtitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentDataExtractorScanningTooLongAlertSubtitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionFlashButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionFlashButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionZoomButton:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"accessibilityDescriptionZoomButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityDescriptionFlipCameraButton:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"accessibilityDescriptionFlipCameraButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraPermissionEnableCameraTitle"},{"kind":"text","text":" "},{"text":"cameraPermissionEnableCameraExplanation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraPermissionCloseButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionEnableCameraButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"accessibilityDescriptionCameraPermissionCloseButton","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceNoDocumentFound:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentUserGuidanceNoDocumentFound","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceScanningProgress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentUserGuidanceScanningProgress","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceTooDark:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentUserGuidanceTooDark","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceTooSmall:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentUserGuidanceTooSmall","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"documentUserGuidanceBadPerspective:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"documentUserGuidanceBadPerspective","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:"}],"title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2DocumentDataExtractorScreenTextLocalization(im)initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintroscreendonebutton:access-9kl9b"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization/initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:":{"navigatorTitle":[{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization\/initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","title":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopBarTitle:topBarCancelButton:topUserGuidance:introScreenTitle:introScreenDoneButton:introScreenText:completionOverlaySuccessMessage:accessibilityDescriptionOpenIntroScreenButton:accessibilityDescriptionIntroScreenDoneButton:accessibilityDescriptionCancelButton:accessibilityDescriptionRetryButton:accessibilityDescriptionCloseScannerButton:documentDataExtractorAlertRetryButton:documentDataExtractorAlertCloseScannerButton:documentDataExtractorNoDocumentDetectedAlertTitle:documentDataExtractorNoDocumentDetectedAlertSubtitle:documentDataExtractorCantProcessDocumentAlertTitle:documentDataExtractorCantProcessDocumentAlertSubtitle:documentDataExtractorUnsupportedDocumentAlertTitle:documentDataExtractorUnsupportedDocumentAlertSubtitle:documentDataExtractorScanningTooLongAlertTitle:documentDataExtractorScanningTooLongAlertSubtitle:accessibilityDescriptionFlashButton:accessibilityDescriptionZoomButton:accessibilityDescriptionFlipCameraButton:cameraPermissionEnableCameraTitle:cameraPermissionEnableCameraExplanation:cameraPermissionEnableCameraButton:cameraPermissionCloseButton:accessibilityDescriptionCameraPermissionEnableCameraButton:accessibilityDescriptionCameraPermissionCloseButton:documentUserGuidanceNoDocumentFound:documentUserGuidanceScanningProgress:documentUserGuidanceTooDark:documentUserGuidanceTooSmall:documentUserGuidanceBadPerspective:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization\/initwithtopbartitle:topbarcancelbutton:topuserguidance:introscreentitle:introscreendonebutton:introscreentext:completionoverlaysuccessmessage:accessibilitydescriptionopenintroscreenbutton:accessibilitydescriptionintroscreendonebutton:access-9kl9b","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentDataExtractorScreenTextLocalization":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the all strings for document data extractor screen."}],"title":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentDataExtractorScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2documentdataextractorscreentextlocalization","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/title"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/fragments"},{"value":[{"text":"SBSDKUI2DocumentDataExtractorScreenTextLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentDataExtractorScreenTextLocalization\/navigatorTitle"}]}]}