{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2topbarconfiguration\/initwithtitle:mode:statusbarmode:backgroundcolor:cancelbutton:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2TopBarConfiguration(im)initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:","navigatorTitle":[{"text":"initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:","kind":"identifier"}],"title":"initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarConfiguration\/initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"title"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2TopBarMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarMode","kind":"typeIdentifier","text":"SBSDKUI2TopBarMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusBarMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKUI2StatusBarMode","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StatusBarMode","text":"SBSDKUI2StatusBarMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"statusBarMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","text":"SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cancelButton"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarConfiguration"]]},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2TopBarMode":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarMode"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2topbarmode","title":"SBSDKUI2TopBarMode","abstract":[{"text":"The visual mode used for the top bar.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarMode"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2TopBarConfiguration":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarConfiguration","title":"SBSDKUI2TopBarConfiguration","abstract":[{"text":"Configuration of the top bar’s appearance.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2topbarconfiguration"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2TopBarConfiguration/initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:":{"kind":"symbol","title":"initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2TopBarConfiguration\/initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2topbarconfiguration\/initwithtitle:mode:statusbarmode:backgroundcolor:cancelbutton:","role":"symbol","navigatorTitle":[{"text":"initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithTitle:mode:statusBarMode:backgroundColor:cancelButton:","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","title":"ScanbotBarcodeScannerSDK","type":"topic"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StyledText":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StyledText","title":"SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2styledtext","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Color":{"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2color","abstract":[],"title":"SBSDKUI2Color","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2Color"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Color","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2Color"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2StatusBarMode":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2StatusBarMode","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2statusbarmode","abstract":[{"text":"The visual mode used for the status bar icons.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"role":"symbol","type":"topic","title":"SBSDKUI2StatusBarMode","kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2ButtonConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2ButtonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2buttonconfiguration","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration of the button."}],"kind":"symbol","title":"SBSDKUI2ButtonConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2TopBarMode","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2TopBarMode\/title"},{"value":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2TopBarMode\/fragments"},{"value":[{"text":"SBSDKUI2TopBarMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2TopBarMode\/navigatorTitle"},{"value":"SBSDKUI2TopBarConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2TopBarConfiguration\/title"},{"value":[{"text":"SBSDKUI2TopBarConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2TopBarConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2TopBarConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2TopBarConfiguration\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2StyledText","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/title"},{"op":"replace","value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2Color","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Color\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2StatusBarMode","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StatusBarMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2StatusBarMode"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StatusBarMode\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2StatusBarMode","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2StatusBarMode\/navigatorTitle"},{"op":"replace","value":"SBSDKUI2ButtonConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"op":"replace","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle"}]}]}