{"abstract":[{"type":"text","text":"Returns a JSON string representation format."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"roleHeading":"Instance Method","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormatCommonFourStateConfiguration(im)toJsonWithConfiguration:","symbolKind":"method","role":"symbol","title":"toJson(configuration:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toJson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKToJSONConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":" = SBSDKToJSONConfiguration()) -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration\/toJson(configuration:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/tojson(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/tojson(configuration:)"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration/toJson(configuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJson"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration","kind":"typeIdentifier","text":"SBSDKToJSONConfiguration"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","title":"toJson(configuration:)","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration\/tojson(configuration:)","navigatorTitle":[{"kind":"identifier","text":"toJsonWithConfiguration:"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration\/toJson(configuration:)","abstract":[{"text":"Returns a JSON string representation format.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormatCommonFourStateConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformatcommonfourstateconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormatCommonFourStateConfiguration","abstract":[{"type":"text","text":"Convenience configuration for enabling the scanning of multiple four-state barcode formats with a common configuration."},{"type":"text","text":" "},{"type":"text","text":"Add to scanner configuration to enable and configure the scanning of multiple four-state codes."}],"title":"SBSDKBarcodeFormatCommonFourStateConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKToJSONConfiguration":{"navigatorTitle":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktojsonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","title":"SBSDKToJSONConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration used to serialize an object to json."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"toJsonWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SBSDKToJSONConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKToJSONConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKToJSONConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration~1toJson(configuration:)\/title","value":"toJsonWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration~1toJson(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJsonWithConfiguration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/title","op":"replace","value":"SBSDKBarcodeFormatCommonFourStateConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKBarcodeFormatCommonFourStateConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormatCommonFourStateConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKBarcodeFormatCommonFourStateConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/title","op":"replace","value":"SBSDKToJSONConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKToJSONConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKToJSONConfiguration","kind":"identifier"}]}]}]}