{"abstract":[{"text":"ImageRef was created from a platform image, e.g. Bitmap on Android, UIImage on iOS.","type":"text"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType\/platformImage","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ScanbotSDK@E@SBSDKImageSourceType@SBSDKImageSourceTypePlatformImage","title":"SBSDKImageSourceType.platformImage","roleHeading":"Case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"platformImage","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSourceTypePlatformImage"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkimagesourcetype\/platformimage"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagesourcetype\/platformimage"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"platformImage","kind":"identifier"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSourceType":{"abstract":[{"text":"The type of source which originated the underlying image.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkimagesourcetype","title":"SBSDKImageSourceType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKImageSourceType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSourceType/platformImage":{"abstract":[{"type":"text","text":"ImageRef was created from a platform image, e.g. Bitmap on Android, UIImage on iOS."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType\/platformImage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"platformImage"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagesourcetype\/platformimage","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSourceTypePlatformImage"}],"kind":"symbol","title":"SBSDKImageSourceType.platformImage"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SBSDKImageSourceTypePlatformImage","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKImageSourceTypePlatformImage"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SBSDKImageSourceTypePlatformImage","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/title","op":"replace","value":"SBSDKImageSourceType"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/fragments","value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/navigatorTitle","value":[{"text":"SBSDKImageSourceType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType~1platformImage\/title","op":"replace","value":"SBSDKImageSourceTypePlatformImage"},{"op":"replace","value":[{"text":"SBSDKImageSourceTypePlatformImage","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType~1platformImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}