{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The patient’s address 2.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"addressString2","kind":"identifier"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/addressstring2"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/addressstring2"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType"]]},"metadata":{"modules":[{"name":"ScanbotSDK"}],"title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType.addressString2","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addressString2"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerResultPatientFieldType@SBSDKMedicalCertificateRecognizerResultPatientFieldTypeAddressString2","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeAddressString2"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType\/addressString2","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientFieldType/addressString2":{"kind":"symbol","type":"topic","title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType.addressString2","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType\/addressString2","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/addressstring2","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"addressString2","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeAddressString2","kind":"identifier"}],"abstract":[{"type":"text","text":"The patient’s address 2."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientFieldType":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype","abstract":[{"text":"The various types of fields inside the patient information field of a medical certificate.","type":"text"}],"kind":"symbol","title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 5.2.2","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","type":"topic","title":"ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeAddressString2","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeAddressString2"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeAddressString2"}]}],"kind":"declarations"}},{"value":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeAddressString2","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType~1addressString2\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType~1addressString2\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeAddressString2","kind":"identifier"}],"op":"replace"},{"value":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/title"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/fragments"}]}]}