{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/doctornumber"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/doctornumber"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType\/doctorNumber"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"doctorNumber"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerResultPatientFieldType@SBSDKMedicalCertificateRecognizerResultPatientFieldTypeDoctorNumber","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"doctorNumber","kind":"identifier"}],"title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType.doctorNumber","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeDoctorNumber"}],"roleHeading":"Case"},"abstract":[{"type":"text","text":"The doctor’s number."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientFieldType/doctorNumber":{"title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType.doctorNumber","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/doctornumber","abstract":[{"type":"text","text":"The doctor’s number."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"doctorNumber","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeDoctorNumber"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType\/doctorNumber"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientFieldType":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType","title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","abstract":[{"text":"The various types of fields inside the patient information field of a medical certificate.","type":"text"}],"navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","abstract":[{"text":"Version: 6.2.0","type":"text"}],"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeDoctorNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeDoctorNumber","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeDoctorNumber","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeDoctorNumber","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType~1doctorNumber\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType~1doctorNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeDoctorNumber"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/title","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","op":"replace"},{"op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/navigatorTitle","value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}