{"kind":"symbol","metadata":{"title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType.undefined","externalID":"c:@M@ScanbotSDK@E@SBSDKMedicalCertificateRecognizerResultPatientFieldType@SBSDKMedicalCertificateRecognizerResultPatientFieldTypeUndefined","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeUndefined","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"undefined"}],"roleHeading":"Case"},"sections":[],"abstract":[{"type":"text","text":"An undefined field."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/undefined"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/undefined"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType\/undefined","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientFieldType/undefined":{"title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType.undefined","navigatorTitle":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeUndefined"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType\/undefined","abstract":[{"text":"An undefined field.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype\/undefined","type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKMedicalCertificateRecognizerResultPatientFieldType":{"role":"symbol","navigatorTitle":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkmedicalcertificaterecognizerresultpatientfieldtype","title":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKMedicalCertificateRecognizerResultPatientFieldType","abstract":[{"text":"The various types of fields inside the patient information field of a medical certificate.","type":"text"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"type":"topic","abstract":[{"text":"Version: 6.0.0","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","url":"\/documentation\/scanbotsdk","title":"ScanbotSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeUndefined"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeUndefined","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeUndefined"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType~1undefined\/title","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeUndefined","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType~1undefined\/fragments","op":"replace","value":[{"text":"SBSDKMedicalCertificateRecognizerResultPatientFieldTypeUndefined","kind":"identifier"}]},{"op":"replace","value":"SBSDKMedicalCertificateRecognizerResultPatientFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/title"},{"value":[{"kind":"identifier","text":"SBSDKMedicalCertificateRecognizerResultPatientFieldType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKMedicalCertificateRecognizerResultPatientFieldType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}