{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(setDisplayText:forDocumentType:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDisplayText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"displayText","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"forDocumentType","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"documentType"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"displayText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text displayed for the given document type."}]}]},{"name":"documentType","content":[{"inlineContent":[{"text":"The type of the document.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration\/setdisplaytext(_:fordocumenttype:)"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration\/setdisplaytext(_:fordocumenttype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"setDisplayText:forDocumentType:","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorTextConfiguration(im)setDisplayText:forDocumentType:","role":"symbol","title":"setDisplayText(_:forDocumentType:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDisplayText"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"forDocumentType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration\/setDisplayText(_:forDocumentType:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"A convenience method to set the text displayed for the given document type."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorTextConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration","title":"SBSDKUIDocumentDataExtractorTextConfiguration","abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI document data extractor screen."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorTextConfiguration/setDisplayText(_:forDocumentType:)":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration\/setdisplaytext(_:fordocumenttype:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDisplayText:forDocumentType:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDisplayText"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"forDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"setDisplayText(_:forDocumentType:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration\/setDisplayText(_:forDocumentType:)","abstract":[{"type":"text","text":"A convenience method to set the text displayed for the given document type."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setDisplayText:forDocumentType:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setDisplayText:forDocumentType:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setDisplayText:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"displayText"},{"kind":"text","text":" "},{"kind":"identifier","text":"forDocumentType:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentType"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"displayText","content":[{"inlineContent":[{"type":"text","text":"The text displayed for the given document type."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The type of the document."}],"type":"paragraph"}],"name":"documentType"}],"kind":"parameters"}},{"value":"SBSDKUIDocumentDataExtractorTextConfiguration","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/title","op":"replace"},{"value":[{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/navigatorTitle"},{"value":"setDisplayText:forDocumentType:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration~1setDisplayText(_:forDocumentType:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setDisplayText:forDocumentType:","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration~1setDisplayText(_:forDocumentType:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}