{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIDocumentDataExtractorTextConfiguration(py)viewResultsButtonTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewResultsButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"viewResultsButtonTitle","navigatorTitle":[{"kind":"identifier","text":"viewResultsButtonTitle"}]},"sections":[],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration\/viewresultsbuttontitle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration\/viewresultsbuttontitle"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewResultsButtonTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration\/viewResultsButtonTitle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The string being displayed on the view results button."}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorTextConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration","title":"SBSDKUIDocumentDataExtractorTextConfiguration","abstract":[{"type":"text","text":"The configuration for the textual contents of the RTU-UI document data extractor screen."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUIDocumentDataExtractorTextConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIDocumentDataExtractorTextConfiguration/viewResultsButtonTitle":{"type":"topic","navigatorTitle":[{"text":"viewResultsButtonTitle","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIDocumentDataExtractorTextConfiguration\/viewResultsButtonTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"viewResultsButtonTitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuidocumentdataextractortextconfiguration\/viewresultsbuttontitle","title":"viewResultsButtonTitle","abstract":[{"type":"text","text":"The string being displayed on the view results button."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"viewResultsButtonTitle","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"viewResultsButtonTitle"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"viewResultsButtonTitle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/title","value":"SBSDKUIDocumentDataExtractorTextConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorTextConfiguration"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUIDocumentDataExtractorTextConfiguration"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration~1viewResultsButtonTitle\/title","value":"viewResultsButtonTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIDocumentDataExtractorTextConfiguration~1viewResultsButtonTitle\/fragments","value":[{"kind":"identifier","text":"viewResultsButtonTitle"}]}]}]}