{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTopBarBackButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBSDKUI2ButtonConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarBackButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"topBarConfirmButton:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ButtonConfiguration","text":"SBSDKUI2ButtonConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topBarConfirmButton"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2Color","text":"SBSDKUI2Color","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"guidance:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2UserGuidanceConfiguration","text":"SBSDKUI2UserGuidanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"guidance"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageTextStyle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2StyledText","text":"SBSDKUI2StyledText","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageTextStyle"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:"},"metadata":{"navigatorTitle":[{"text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:"}],"modules":[{"name":"ScanbotSDK"}],"title":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2ReorderPagesScreenConfiguration(im)initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration\/initwithtopbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:guidance:pagetextstyle:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReorderPagesScreenConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration","url":"\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the screen for reordering the scanned pages."}],"title":"SBSDKUI2ReorderPagesScreenConfiguration","navigatorTitle":[{"text":"SBSDKUI2ReorderPagesScreenConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2StyledText":{"type":"topic","navigatorTitle":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2styledtext","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2StyledText","abstract":[{"type":"text","text":"Configuration of the text field appearance."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2StyledText","kind":"identifier"}],"title":"SBSDKUI2StyledText"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ReorderPagesScreenConfiguration/initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:":{"role":"symbol","kind":"symbol","title":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:"}],"abstract":[],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2reorderpagesscreenconfiguration\/initwithtopbarbackbutton:topbartitle:topbarconfirmbutton:backgroundcolor:guidance:pagetextstyle:","navigatorTitle":[{"kind":"identifier","text":"initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ReorderPagesScreenConfiguration\/initWithTopBarBackButton:topBarTitle:topBarConfirmButton:backgroundColor:guidance:pageTextStyle:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2ButtonConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2buttonconfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2ButtonConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"title":"SBSDKUI2ButtonConfiguration","abstract":[{"type":"text","text":"Configuration of the button."}],"type":"topic","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2UserGuidanceConfiguration":{"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkui2userguidanceconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2UserGuidanceConfiguration","abstract":[{"type":"text","text":"Configuration of the hint guiding users through the scanning process."}],"kind":"symbol","title":"SBSDKUI2UserGuidanceConfiguration","navigatorTitle":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2Color":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2color","title":"SBSDKUI2Color","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2Color","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2Color","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2Color"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","url":"\/documentation\/scanbotsdk"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2ReorderPagesScreenConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2ReorderPagesScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2ReorderPagesScreenConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ReorderPagesScreenConfiguration\/navigatorTitle"},{"value":"SBSDKUI2StyledText","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2StyledText"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/fragments"},{"value":[{"text":"SBSDKUI2StyledText","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2StyledText\/navigatorTitle"},{"value":"SBSDKUI2ButtonConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKUI2ButtonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2ButtonConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2ButtonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/title","value":"SBSDKUI2UserGuidanceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2UserGuidanceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2UserGuidanceConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2UserGuidanceConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/title","value":"SBSDKUI2Color","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/fragments","value":[{"text":"SBSDKUI2Color","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2Color\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Color"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}