{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkuienablecameraviewcontroller\/initwithnibname:bundle:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraViewController\/initWithNibName:bundle:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKUIEnableCameraViewController(im)initWithNibName:bundle:","title":"initWithNibName:bundle:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraViewController"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithNibName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"nibNameOrNil","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bundle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","text":"NSBundle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"nibBundleOrNil","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIEnableCameraViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUIEnableCameraViewController"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIEnableCameraViewController"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraViewController","abstract":[],"title":"SBSDKUIEnableCameraViewController","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuienablecameraviewcontroller"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKUIEnableCameraViewController/initWithNibName:bundle:":{"role":"symbol","type":"topic","title":"initWithNibName:bundle:","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkuienablecameraviewcontroller\/initwithnibname:bundle:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKUIEnableCameraViewController\/initWithNibName:bundle:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraViewController\/title","value":"SBSDKUIEnableCameraViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraViewController\/fragments","value":[{"text":"SBSDKUIEnableCameraViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKUIEnableCameraViewController\/navigatorTitle","value":[{"text":"SBSDKUIEnableCameraViewController","kind":"identifier"}],"op":"replace"}]}]}