{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","kind":"identifier"}],"title":"SBSDKTIFFImageWriterUserDefinedFieldType.string","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"string","kind":"identifier"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@E@SBSDKTIFFImageWriterUserDefinedFieldType@SBSDKTIFFImageWriterUserDefinedFieldTypeString","modules":[{"name":"ScanbotDocumentScannerSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedFieldType\/string"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedFieldType"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"A string based field type.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfieldtype\/string"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfieldtype\/string"]}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedFieldType/string":{"title":"SBSDKTIFFImageWriterUserDefinedFieldType.string","abstract":[{"type":"text","text":"A string based field type."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedFieldType\/string","type":"topic","role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfieldtype\/string","navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"string","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 6.2.0"}],"url":"\/documentation\/scanbotdocumentscannersdk","role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKTIFFImageWriterUserDefinedFieldType":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKTIFFImageWriterUserDefinedFieldType","kind":"symbol","title":"SBSDKTIFFImageWriterUserDefinedFieldType","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Custom TIFF field type."}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdktiffimagewriteruserdefinedfieldtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKTIFFImageWriterUserDefinedFieldTypeString"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SBSDKTIFFImageWriterUserDefinedFieldTypeString","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedFieldType~1string\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedFieldType~1string\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldTypeString"}],"op":"replace"},{"op":"replace","value":"SBSDKTIFFImageWriterUserDefinedFieldType","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/fragments","op":"replace","value":[{"text":"SBSDKTIFFImageWriterUserDefinedFieldType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterUserDefinedFieldType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKTIFFImageWriterUserDefinedFieldType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}