{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters\/aspectratios"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters\/aspectratios"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerParameters(py)aspectRatios","symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"title":"aspectRatios","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"aspectRatios","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"aspectRatios","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatios"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters"]]},"abstract":[{"type":"text","text":"The possible desired aspect ratios for the detected document."},{"type":"text","text":" "},{"type":"text","text":"A document matches if its aspect ratio matches any of the given aspect ratios."},{"type":"text","text":" "},{"type":"text","text":"If acceptedAspectRatioScore is more than 0, then the document is only accepted if the aspect ratio"},{"type":"text","text":" "},{"type":"text","text":"matches one of the given aspect ratios, otherwise OK_BUT_BAD_ASPECT_RATIO is returned."},{"type":"text","text":" "},{"type":"text","text":"If empty, no aspect ratio is preferred."}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters\/aspectRatios","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters/aspectRatios":{"navigatorTitle":[{"kind":"identifier","text":"aspectRatios"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters\/aspectratios","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters\/aspectRatios","title":"aspectRatios","abstract":[{"type":"text","text":"The possible desired aspect ratios for the detected document."},{"type":"text","text":" "},{"type":"text","text":"A document matches if its aspect ratio matches any of the given aspect ratios."},{"type":"text","text":" "},{"type":"text","text":"If acceptedAspectRatioScore is more than 0, then the document is only accepted if the aspect ratio"},{"type":"text","text":" "},{"type":"text","text":"matches one of the given aspect ratios, otherwise OK_BUT_BAD_ASPECT_RATIO is returned."},{"type":"text","text":" "},{"type":"text","text":"If empty, no aspect ratio is preferred."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectRatios"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","kind":"typeIdentifier","text":"SBSDKAspectRatio"},{"kind":"text","text":">"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatio":{"navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"title":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkaspectratio","abstract":[{"type":"text","text":"Aspect ratio is the ratio of the width to the height of an image or screen."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters":{"type":"topic","kind":"symbol","role":"symbol","title":"SBSDKDocumentScannerParameters","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"abstract":[{"text":"Parameters for the document scanner.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"aspectRatios","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"aspectRatios","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBSDKAspectRatio *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aspectRatios"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"aspectRatios","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters~1aspectRatios\/title","op":"replace"},{"value":[{"kind":"identifier","text":"aspectRatios"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters~1aspectRatios\/fragments","op":"replace"},{"value":"SBSDKAspectRatio","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/title"},{"value":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/navigatorTitle"},{"value":"SBSDKDocumentScannerParameters","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/title"},{"value":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/fragments"},{"value":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}