{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters"]]},"metadata":{"title":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:"}],"navigatorTitle":[{"text":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentScannerParameters(im)initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithAcceptedAngleScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"acceptedAngleScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acceptedSizeScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"acceptedSizeScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acceptedBrightnessThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"acceptedBrightnessThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"acceptedAspectRatioScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"acceptedAspectRatioScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"aspectRatios:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SBSDKAspectRatio *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"aspectRatios","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ignoreOrientationMismatch:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"ignoreOrientationMismatch","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters\/initwithacceptedanglescore:acceptedsizescore:acceptedbrightnessthreshold:acceptedaspectratioscore:aspectratios:ignoreorientationmismatch:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters\/initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters":{"type":"topic","kind":"symbol","role":"symbol","title":"SBSDKDocumentScannerParameters","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKDocumentScannerParameters","kind":"identifier"}],"abstract":[{"text":"Parameters for the document scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentScannerParameters/initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:":{"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentscannerparameters\/initwithacceptedanglescore:acceptedsizescore:acceptedbrightnessthreshold:acceptedaspectratioscore:aspectratios:ignoreorientationmismatch:","navigatorTitle":[{"text":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","kind":"identifier"}],"abstract":[],"title":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentScannerParameters\/initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAcceptedAngleScore:acceptedSizeScore:acceptedBrightnessThreshold:acceptedAspectRatioScore:aspectRatios:ignoreOrientationMismatch:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKDocumentScannerParameters","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKDocumentScannerParameters"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentScannerParameters\/navigatorTitle","op":"replace"}]}]}