{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/initwithallowpartiallyvisibledocuments:accumulationduration:retentiontime:minimumbrightness:"]}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration(im)initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","role":"symbol","title":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithAllowPartiallyVisibleDocuments:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowPartiallyVisibleDocuments","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"accumulationDuration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"accumulationDuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"retentionTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"retentionTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumBrightness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumBrightness","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"title":"SBSDKPartiallyVisibleDocumentConfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"abstract":[{"type":"text","text":"Configuration for handling partially visible documents."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}],"role":"symbol","type":"topic","title":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/initwithallowpartiallyvisibledocuments:accumulationduration:retentiontime:minimumbrightness:","abstract":[],"navigatorTitle":[{"text":"initWithAllowPartiallyVisibleDocuments:accumulationDuration:retentionTime:minimumBrightness:","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","title":"ScanbotDocumentScannerSDK","abstract":[{"type":"text","text":"Version: 8.0.3"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title","value":"SBSDKPartiallyVisibleDocumentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}],"op":"replace"}]}]}