{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Minimum brightness of a partially visible potential document. Increasing this value can reduce the number"},{"type":"text","text":" "},{"type":"text","text":"of spurious detections."}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumBrightness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPartiallyVisibleDocumentConfiguration(py)minimumBrightness","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"minimumBrightness","kind":"identifier"}],"title":"minimumBrightness","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumBrightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Default is 0"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/minimumbrightness"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/minimumbrightness"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/minimumBrightness"},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"abstract":[{"type":"text","text":"Configuration for handling partially visible documents."}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration","type":"topic","title":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"url":"\/documentation\/scanbotdocumentscannersdk","type":"topic","title":"ScanbotDocumentScannerSDK","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Version: 8.0.3"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPartiallyVisibleDocumentConfiguration/minimumBrightness":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumBrightness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPartiallyVisibleDocumentConfiguration\/minimumBrightness","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpartiallyvisibledocumentconfiguration\/minimumbrightness","title":"minimumBrightness","abstract":[{"type":"text","text":"Minimum brightness of a partially visible potential document. Increasing this value can reduce the number"},{"type":"text","text":" "},{"type":"text","text":"of spurious detections."}],"navigatorTitle":[{"text":"minimumBrightness","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"minimumBrightness"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"minimumBrightness"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"minimumBrightness","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/title","op":"replace","value":"SBSDKPartiallyVisibleDocumentConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/fragments","op":"replace","value":[{"text":"SBSDKPartiallyVisibleDocumentConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKPartiallyVisibleDocumentConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1minimumBrightness\/title","op":"replace","value":"minimumBrightness"},{"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPartiallyVisibleDocumentConfiguration~1minimumBrightness\/fragments","op":"replace","value":[{"text":"minimumBrightness","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}