{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeLeft"}],"symbolKind":"case","role":"symbol","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscapeLeft","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKVideoOrientation@SBSDKVideoOrientationLandscapeLeft","title":"SBSDKVideoOrientation.landscapeLeft","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoorientation\/landscapeleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkvideoorientation\/landscapeleft"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeLeft"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"landscapeLeft","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Landscape left orientation."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation/landscapeLeft":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"landscapeLeft"}],"title":"SBSDKVideoOrientation.landscapeLeft","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation\/landscapeLeft","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation\/landscapeleft","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeLeft"}],"abstract":[{"text":"Landscape left orientation.","type":"text"}],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKVideoOrientation":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkvideoorientation","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKVideoOrientation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKVideoOrientation"}],"title":"SBSDKVideoOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKVideoOrientation"}],"abstract":[{"text":"An enum describing the orientation of a video frame.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SBSDKVideoOrientationLandscapeLeft","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeLeft"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKVideoOrientationLandscapeLeft","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1landscapeLeft\/title","value":"SBSDKVideoOrientationLandscapeLeft","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation~1landscapeLeft\/fragments","value":[{"kind":"identifier","text":"SBSDKVideoOrientationLandscapeLeft"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/title","value":"SBSDKVideoOrientation","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/fragments","value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKVideoOrientation\/navigatorTitle","value":[{"text":"SBSDKVideoOrientation","kind":"identifier"}],"op":"replace"}]}]}