{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Creates a new document with the specified image size limit and returns it."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentImageSizeLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" = 0) -> "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument","kind":"typeIdentifier","text":"SBSDKScannedDocument"}]}]},{"kind":"parameters","parameters":[{"name":"documentImageSizeLimit","content":[{"inlineContent":[{"text":"The maximum image size for each pages document image. After creating the document image by applying rotation, cropping and filtering to each pages original image, this upper limit image size is applied to the document image. If the longer side of the pages document image exceeds this limit, the document image is scaled down proportionally to fit into the limit. Setting the limit to 0, effectively disables the size limit.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The newly created document.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/createdocument(documentimagesizelimit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkscanneddocument\/createdocument(documentimagesizelimit:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/createDocument(documentImageSizeLimit:)"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentImageSizeLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"extendedModule":"ScanbotSDK","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKScannedDocument(cm)createDocumentWithDocumentImageSizeLimit:","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"createDocumentWithDocumentImageSizeLimit:"}],"title":"createDocument(documentImageSizeLimit:)","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument":{"kind":"symbol","navigatorTitle":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"An automatically persisted, thread-safe and observable document-page model for a document with multiple scanned pages."}],"title":"SBSDKScannedDocument","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKScannedDocument/createDocument(documentImageSizeLimit:)":{"abstract":[{"text":"Creates a new document with the specified image size limit and returns it.","type":"text"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentImageSizeLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"SBSDKScannedDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument\/createDocument(documentImageSizeLimit:)","kind":"symbol","navigatorTitle":[{"text":"createDocumentWithDocumentImageSizeLimit:","kind":"identifier"}],"title":"createDocument(documentImageSizeLimit:)","url":"\/documentation\/scanbotsdk\/sbsdkscanneddocument\/createdocument(documentimagesizelimit:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createDocumentWithDocumentImageSizeLimit:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createDocumentWithDocumentImageSizeLimit:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKScannedDocument","kind":"typeIdentifier","text":"SBSDKScannedDocument","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKScannedDocument"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createDocumentWithDocumentImageSizeLimit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"documentImageSizeLimit"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum image size for each pages document image. After creating the document image by applying rotation, cropping and filtering to each pages original image, this upper limit image size is applied to the document image. If the longer side of the pages document image exceeds this limit, the document image is scaled down proportionally to fit into the limit. Setting the limit to 0, effectively disables the size limit."}]}],"name":"documentImageSizeLimit"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"The newly created document.","type":"text"}],"type":"paragraph"}]}},{"value":"SBSDKScannedDocument","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/title"},{"value":[{"kind":"identifier","text":"SBSDKScannedDocument"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/fragments"},{"value":[{"text":"SBSDKScannedDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument\/navigatorTitle"},{"value":"createDocumentWithDocumentImageSizeLimit:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1createDocument(documentImageSizeLimit:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createDocumentWithDocumentImageSizeLimit:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKScannedDocument~1createDocument(documentImageSizeLimit:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}