{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the general appearance for the cropping screen."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration\/appearance"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"appearance","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration","text":"SBSDKUI2CroppingAppearanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","navigatorTitle":[{"text":"appearance","kind":"identifier"}],"roleHeading":"Instance Property","title":"appearance","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingConfiguration(py)appearance","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"appearance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration","text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingconfiguration\/appearance"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingconfiguration\/appearance"]}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingConfiguration/appearance":{"kind":"symbol","title":"appearance","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration\/appearance","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingconfiguration\/appearance","abstract":[{"text":"Configuration of the general appearance for the cropping screen.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearance"},{"kind":"text","text":": "},{"text":"SBSDKUI2CroppingAppearanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"appearance"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingConfiguration":{"title":"SBSDKUI2CroppingConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the standalone cropping screen."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingConfiguration","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2CroppingConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingAppearanceConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"title":"SBSDKUI2CroppingAppearanceConfiguration","abstract":[{"text":"Configuration of the general appearance for the cropping screen.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingappearanceconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"appearance","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"appearance"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKUI2CroppingAppearanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"appearance"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"appearance","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingConfiguration~1appearance\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingConfiguration~1appearance\/fragments","value":[{"kind":"identifier","text":"appearance"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingConfiguration\/title","value":"SBSDKUI2CroppingConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUI2CroppingConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingConfiguration\/navigatorTitle","value":[{"text":"SBSDKUI2CroppingConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/title","value":"SBSDKUI2CroppingAppearanceConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}]}]}]}