{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/compression"]},{"paths":["\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/compression"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"text":"The compression algorithm to be used for the TIFF image.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"compression","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterCompressionOptions","text":"SBSDKTIFFImageWriterCompressionOptions","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"compression"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTIFFImageWriterParameters(py)compression","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"compression","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterCompressionOptions","text":"SBSDKTIFFImageWriterCompressionOptions","kind":"typeIdentifier"}],"title":"compression"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/compression","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 6.2.0","type":"text"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters":{"abstract":[{"type":"text","text":"Class used to define the parameters for the TIFF image writer."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters","title":"SBSDKTIFFImageWriterParameters","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterCompressionOptions":{"title":"SBSDKTIFFImageWriterCompressionOptions","abstract":[{"text":"The TIFF compression algorithms.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewritercompressionoptions","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTIFFImageWriterParameters/compression":{"title":"compression","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"compression"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compression","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterCompressionOptions","text":"SBSDKTIFFImageWriterCompressionOptions","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The compression algorithm to be used for the TIFF image."}],"type":"topic","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdktiffimagewriterparameters\/compression","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterParameters\/compression"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"compression"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"compression"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKTIFFImageWriterCompressionOptions","text":"SBSDKTIFFImageWriterCompressionOptions","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTIFFImageWriterCompressionOptions"},{"text":" ","kind":"text"},{"text":"compression","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/title","op":"replace","value":"SBSDKTIFFImageWriterParameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/fragments","value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters\/navigatorTitle","value":[{"text":"SBSDKTIFFImageWriterParameters","kind":"identifier"}],"op":"replace"},{"value":"SBSDKTIFFImageWriterCompressionOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/fragments","value":[{"text":"SBSDKTIFFImageWriterCompressionOptions","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SBSDKTIFFImageWriterCompressionOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterCompressionOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1compression\/title","value":"compression"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTIFFImageWriterParameters~1compression\/fragments","value":[{"kind":"identifier","text":"compression"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}