{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/fromJsonWithJson:"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Type Method","title":"fromJsonWithJson:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKRefCountedObjectProfile(cm)fromJsonWithJson:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromJsonWithJson:"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/fromjsonwithjson:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKRefCountedObjectProfile","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"json","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile/fromJsonWithJson:":{"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile\/fromjsonwithjson:","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile\/fromJsonWithJson:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fromJsonWithJson:"}],"type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"fromJsonWithJson:","kind":"identifier"}],"title":"fromJsonWithJson:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKRefCountedObjectProfile":{"url":"\/documentation\/scanbotsdk\/sbsdkrefcountedobjectprofile","type":"topic","title":"SBSDKRefCountedObjectProfile","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKRefCountedObjectProfile","abstract":[{"type":"text","text":"Profile info of a reference-counted stored object."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"text":"Version: 7.0.2","type":"text"}],"role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKRefCountedObjectProfile","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/title"},{"op":"replace","value":[{"text":"SBSDKRefCountedObjectProfile","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKRefCountedObjectProfile"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKRefCountedObjectProfile\/navigatorTitle"}]}]}