{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/hash"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@objc(cs)SBSDKUI2Palette(py)hash"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/hash"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette/hash":{"title":"hash","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette\/hash","abstract":[],"fragments":[{"kind":"identifier","text":"hash"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette\/hash"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKUI2Palette":{"title":"SBSDKUI2Palette","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKUI2Palette","abstract":[{"type":"text","text":"Value palette describing the colors of the scanner screens."}],"navigatorTitle":[{"text":"SBSDKUI2Palette","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKUI2Palette","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkui2palette"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}],"title":"ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUI2Palette","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKUI2Palette\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUI2Palette"}]}]}]}