{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeItem(im)initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","modules":[{"name":"ScanbotSDK"}],"role":"symbol","symbolKind":"method","title":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/initwithtext:rawbytes:rawbytesencodings:structuredappendinfo:format:quad:quadnormalized:extendedquad:extendedquadnormalized:isupsidedown:sourceimage:upceanextension:isgs1message:isgs1compositepart:databarstacksize:sizescore:extracteddocumen-7jnoz"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithText:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":" ","kind":"text"},{"text":"rawBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"rawBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawBytesEncodings:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SBSDKRangeEncoding *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rawBytesEncodings"},{"text":" ","kind":"text"},{"text":"structuredAppendInfo:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKStructuredAppendInfo","text":"SBSDKStructuredAppendInfo","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo"},{"kind":"text","text":" *) "},{"text":"structuredAppendInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"format:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","text":"SBSDKBarcodeFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKBarcodeFormat"},{"kind":"text","text":" *) "},{"text":"format","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"quad:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"quad","kind":"internalParam"},{"kind":"text","text":" "},{"text":"quadNormalized:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quadNormalized"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extendedQuad:"},{"text":"(","kind":"text"},{"text":"NSArray<NSValue *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"extendedQuad","kind":"internalParam"},{"kind":"text","text":" "},{"text":"extendedQuadNormalized:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>"},{"text":" *) ","kind":"text"},{"text":"extendedQuadNormalized","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isUpsideDown:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isUpsideDown","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceImage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKImageRef","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKImageRef"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sourceImage"},{"kind":"text","text":" "},{"text":"upcEanExtension:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"upcEanExtension","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isGS1Message:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isGS1Message","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isGS1CompositePart:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isGS1CompositePart","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dataBarStackSize:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"dataBarStackSize"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeScore:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"sizeScore","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"extractedDocument:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKGenericDocument","text":"SBSDKGenericDocument","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"extractedDocument","kind":"internalParam"},{"kind":"text","text":" "},{"text":"globalIndex:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"globalIndex"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKStructuredAppendInfo":{"url":"\/documentation\/scanbotsdk\/sbsdkstructuredappendinfo","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKStructuredAppendInfo","navigatorTitle":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}],"abstract":[{"text":"The structured append mode can be used to split a message across multiple barcodes.","type":"text"}],"kind":"symbol","role":"symbol","title":"SBSDKStructuredAppendInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","abstract":[{"type":"text","text":"Version: 7.1.1"}],"role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKGenericDocument":{"url":"\/documentation\/scanbotsdk\/sbsdkgenericdocument","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKGenericDocument","navigatorTitle":[{"text":"SBSDKGenericDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic document."}],"kind":"symbol","role":"symbol","title":"SBSDKGenericDocument","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SBSDKGenericDocument","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageRef":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageRef","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageRef","title":"SBSDKImageRef","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimageref","type":"topic","abstract":[{"type":"text","text":"Image ref class."}],"navigatorTitle":[{"text":"SBSDKImageRef","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeFormat":{"role":"symbol","navigatorTitle":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"type":"topic","title":"SBSDKBarcodeFormat","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkbarcodeformat","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeFormat","abstract":[{"type":"text","text":"Enumerates barcode formats."}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem":{"abstract":[{"type":"text","text":"A single barcode found in the input image. Barcodes with the same content but different locations in the image are"},{"text":" ","type":"text"},{"type":"text","text":"considered separate barcodes."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKBarcodeItem","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem","title":"SBSDKBarcodeItem","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBarcodeItem/initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:":{"role":"symbol","title":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBarcodeItem\/initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}],"url":"\/documentation\/scanbotsdk\/sbsdkbarcodeitem\/initwithtext:rawbytes:rawbytesencodings:structuredappendinfo:format:quad:quadnormalized:extendedquad:extendedquadnormalized:isupsidedown:sourceimage:upceanextension:isgs1message:isgs1compositepart:databarstacksize:sizescore:extracteddocumen-7jnoz","navigatorTitle":[{"kind":"identifier","text":"initWithText:rawBytes:rawBytesEncodings:structuredAppendInfo:format:quad:quadNormalized:extendedQuad:extendedQuadNormalized:isUpsideDown:sourceImage:upcEanExtension:isGS1Message:isGS1CompositePart:dataBarStackSize:sizeScore:extractedDocument:globalIndex:"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/title","value":"SBSDKStructuredAppendInfo","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/fragments","op":"replace","value":[{"text":"SBSDKStructuredAppendInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKStructuredAppendInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKStructuredAppendInfo"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/title","value":"SBSDKGenericDocument","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/fragments","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKGenericDocument\/navigatorTitle","op":"replace","value":[{"text":"SBSDKGenericDocument","kind":"identifier"}]},{"op":"replace","value":"SBSDKImageRef","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/title"},{"op":"replace","value":[{"text":"SBSDKImageRef","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKImageRef"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageRef\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/title","value":"SBSDKBarcodeFormat","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/fragments","value":[{"kind":"identifier","text":"SBSDKBarcodeFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeFormat\/navigatorTitle","value":[{"text":"SBSDKBarcodeFormat","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/title","value":"SBSDKBarcodeItem"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/fragments","value":[{"text":"SBSDKBarcodeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBarcodeItem\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBarcodeItem"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}