{"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkblock\/initwithtext:confidence:roi:lines:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithText:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"confidence"},{"kind":"text","text":" "},{"kind":"identifier","text":"roi:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSValue *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"roi"},{"kind":"text","text":" "},{"kind":"identifier","text":"lines:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<SBSDKLine *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lines"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:confidence:roi:lines:","kind":"identifier"}],"title":"initWithText:confidence:roi:lines:","navigatorTitle":[{"kind":"identifier","text":"initWithText:confidence:roi:lines:"}],"modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBlock(im)initWithText:confidence:roi:lines:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBlock"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBlock\/initWithText:confidence:roi:lines:","interfaceLanguage":"occ"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBlock/initWithText:confidence:roi:lines:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithText:confidence:roi:lines:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBlock\/initWithText:confidence:roi:lines:","abstract":[],"kind":"symbol","title":"initWithText:confidence:roi:lines:","url":"\/documentation\/scanbotsdk\/sbsdkblock\/initwithtext:confidence:roi:lines:","type":"topic","navigatorTitle":[{"text":"initWithText:confidence:roi:lines:","kind":"identifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBlock":{"type":"topic","abstract":[{"type":"text","text":"Represents a single block, e.g. a paragraph. A block is made up of lines."}],"kind":"symbol","title":"SBSDKBlock","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKBlock","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBlock","navigatorTitle":[{"text":"SBSDKBlock","kind":"identifier"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkblock"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBlock\/title","value":"SBSDKBlock","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBlock\/fragments","value":[{"text":"SBSDKBlock","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBlock\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKBlock"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}