{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkimagesource\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkimagesource\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource\/type"},"abstract":[{"text":"Source type from which the ImageRef was created.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKImageSourceType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageSourceType"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKImageSource(py)type","modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"type","symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType","text":"SBSDKImageSourceType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageSourceType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSource":{"abstract":[{"text":"Description of source from which the ImageRef was created.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKImageSource"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSource"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource","url":"\/documentation\/scanbotsdk\/sbsdkimagesource","title":"SBSDKImageSource"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSource/type":{"role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkimagesource\/type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageSourceType","text":"SBSDKImageSourceType"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSource\/type","abstract":[{"type":"text","text":"Source type from which the ImageRef was created."}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"title":"type"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKImageSourceType":{"role":"symbol","type":"topic","kind":"symbol","title":"SBSDKImageSourceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSourceType","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkimagesourcetype","navigatorTitle":[{"text":"SBSDKImageSourceType","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType","abstract":[{"type":"text","text":"The type of source which originated the underlying image."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"type","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"type"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKImageSourceType","text":"SBSDKImageSourceType","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKImageSourceType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKImageSource","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageSource"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/fragments","op":"replace"},{"value":[{"text":"SBSDKImageSource","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource\/navigatorTitle","op":"replace"},{"value":"type","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource~1type\/title","op":"replace"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSource~1type\/fragments","op":"replace"},{"value":"SBSDKImageSourceType","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKImageSourceType"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKImageSourceType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}