{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"copyWithZone:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSZone","text":"_NSZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2croppingappearanceconfiguration\/copywithzone:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration\/copyWithZone:"},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"copyWithZone:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2CroppingAppearanceConfiguration(im)copyWithZone:","symbolKind":"method"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingAppearanceConfiguration/copyWithZone:":{"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration\/copyWithZone:","url":"\/documentation\/scanbotsdk\/sbsdkui2croppingappearanceconfiguration\/copywithzone:","title":"copyWithZone:"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2CroppingAppearanceConfiguration":{"title":"SBSDKUI2CroppingAppearanceConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2CroppingAppearanceConfiguration","navigatorTitle":[{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2croppingappearanceconfiguration","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the general appearance for the cropping screen."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SBSDKUI2CroppingAppearanceConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/title"},{"value":[{"text":"SBSDKUI2CroppingAppearanceConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKUI2CroppingAppearanceConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2CroppingAppearanceConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}