{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeAreaPadding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"insets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EdgeInsets","preciseIdentifier":"s:7SwiftUI10EdgeInsetsV"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":"\n"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/safeAreaPadding(_:)-7r3qb"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"View.safeAreaPadding(_:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/View-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/safeareapadding(_:)-7r3qb"]}],"metadata":{"extendedModule":"SwiftUICore","role":"symbol","symbolKind":"method","externalID":"s:7SwiftUI4ViewPAAE15safeAreaPaddingyQrAA10EdgeInsetsVF::SYNTHESIZED::s:10ScanbotSDK27SBSDKUI2DocumentScannerViewV","title":"safeAreaPadding(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeAreaPadding"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7SwiftUI10EdgeInsetsV","kind":"typeIdentifier","text":"EdgeInsets"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"modules":[{"name":"ScanbotSDK","relatedModules":["SwiftUICore"]}],"platforms":[{"name":"iOS","introducedAt":"17.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"17.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"17.0","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","introducedAt":"17.0","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","introducedAt":"10.0","deprecated":false,"unavailable":false,"beta":false}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"text":"Version: 8.0.1","type":"text"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView/safeAreaPadding(_:)-7r3qb":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"safeAreaPadding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EdgeInsets","preciseIdentifier":"s:7SwiftUI10EdgeInsetsV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"type":"topic","abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/safeareapadding(_:)-7r3qb","role":"symbol","title":"safeAreaPadding(_:)","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/safeAreaPadding(_:)-7r3qb","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView/View-Implementations":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView\/View-Implementations","title":"View Implementations","role":"collectionGroup","url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview\/view-implementations","kind":"article","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerController":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerController","abstract":[{"type":"text","text":"A highly customizable camera-based RTU-UI controller to scan documents."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SBSDKUI2DocumentScannerController","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannercontroller","title":"SBSDKUI2DocumentScannerController","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2DocumentScannerView":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2DocumentScannerView"}],"url":"\/documentation\/scanbotsdk\/sbsdkui2documentscannerview","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerView","role":"symbol","title":"SBSDKUI2DocumentScannerView","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerView"}],"abstract":[{"type":"text","text":"The SwiftUI wrapper for "},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2DocumentScannerController","isActive":true},{"type":"text","text":"."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUI2DocumentScannerController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUI2DocumentScannerController"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2DocumentScannerController\/navigatorTitle"}]}]}