{"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"detectionResult","kind":"identifier"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCaptureInfo(py)detectionResult","modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionResult"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult"},{"kind":"text","text":"?"}],"title":"detectionResult","symbolKind":"property","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionResult"},{"text":": ","kind":"text"},{"text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"text":"? { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/detectionresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/detectionresult"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/detectionResult"},"kind":"symbol","abstract":[{"type":"text","text":"The document detector result of the captured image."}],"sections":[],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo/detectionResult":{"navigatorTitle":[{"text":"detectionResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The document detector result of the captured image."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/detectionresult","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionResult"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult","text":"SBSDKDocumentDetectorResult","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"detectionResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/detectionResult","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentDetectorResult":{"abstract":[{"type":"text","text":"This class represents the result of a document detection"},{"type":"text","text":" "},{"type":"text","text":"on an image."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentdetectorresult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"kind":"symbol","type":"topic","title":"SBSDKDocumentDetectorResult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKCaptureInfo"}],"url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo","title":"SBSDKCaptureInfo","navigatorTitle":[{"kind":"identifier","text":"SBSDKCaptureInfo"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo","kind":"symbol","abstract":[{"type":"text","text":"Helper class, that gathers the image, camera and detection metadata of a document scan."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"detectionResult","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detectionResult"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBSDKDocumentDetectorResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentDetectorResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentDetectorResult"},{"kind":"text","text":" * "},{"text":"detectionResult","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"detectionResult","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1detectionResult\/title"},{"value":[{"kind":"identifier","text":"detectionResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1detectionResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/title","value":"SBSDKDocumentDetectorResult"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKDocumentDetectorResult"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentDetectorResult\/navigatorTitle","value":[{"text":"SBSDKDocumentDetectorResult","kind":"identifier"}]},{"op":"replace","value":"SBSDKCaptureInfo","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/title"},{"op":"replace","value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKCaptureInfo"}]}]}]}