{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/lensCameraProperties"},"sections":[],"abstract":[{"type":"text","text":"The lens and camera properties of the camera system the image was captured with."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"lensCameraProperties","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/lenscameraproperties"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/lenscameraproperties"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"lensCameraProperties"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCaptureInfo(py)lensCameraProperties","title":"lensCameraProperties","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lensCameraProperties","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKLensCameraProperties","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo/lensCameraProperties":{"type":"topic","abstract":[{"type":"text","text":"The lens and camera properties of the camera system the image was captured with."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/lensCameraProperties","navigatorTitle":[{"text":"lensCameraProperties","kind":"identifier"}],"title":"lensCameraProperties","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/lenscameraproperties","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"lensCameraProperties","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 5.1.4"}],"url":"\/documentation\/scanbotsdk","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKLensCameraProperties":{"abstract":[{"text":"Encapsulates lens and camera properties. Can be used with polygonal image cropping to achieve a very accurate aspect ratio of the resulting image.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If created from image image metadata, uses a dictionary of some known devices to lookup the values."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKLensCameraProperties"}],"role":"symbol","type":"topic","title":"SBSDKLensCameraProperties","url":"\/documentation\/scanbotsdk\/sbsdklenscameraproperties","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SBSDKLensCameraProperties","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCaptureInfo","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCaptureInfo"}],"title":"SBSDKCaptureInfo","abstract":[{"text":"Helper class, that gathers the image, camera and detection metadata of a document scan.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"lensCameraProperties","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"lensCameraProperties"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKLensCameraProperties","text":"SBSDKLensCameraProperties","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKLensCameraProperties"},{"kind":"text","text":" * "},{"text":"lensCameraProperties","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"lensCameraProperties","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1lensCameraProperties\/title"},{"value":[{"text":"lensCameraProperties","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1lensCameraProperties\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/title","op":"replace","value":"SBSDKLensCameraProperties"},{"value":[{"kind":"identifier","text":"SBSDKLensCameraProperties"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKLensCameraProperties\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/title","value":"SBSDKCaptureInfo"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/fragments","value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}