{"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pageImageSource","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKPageImageSource","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageImageSource","kind":"typeIdentifier"}],"title":"pageImageSource","modules":[{"name":"ScanbotSDK"}],"symbolKind":"property","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKCaptureInfo(py)pageImageSource","role":"symbol","navigatorTitle":[{"text":"pageImageSource","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageImageSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKPageImageSource","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageImageSource"},{"text":" { get }","kind":"text"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/pageimagesource"]},{"paths":["\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/pageimagesource"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The source the image was received from."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/pageImageSource"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageImageSource":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKPageImageSource","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkpageimagesource","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageImageSource"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource","abstract":[{"text":"The source of an image.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","title":"SBSDKPageImageSource"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","abstract":[{"type":"text","text":"Version: 6.1.1"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo/pageImageSource":{"navigatorTitle":[{"text":"pageImageSource","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo\/pageImageSource","abstract":[{"text":"The source the image was received from.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageImageSource","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageImageSource","text":"SBSDKPageImageSource"}],"title":"pageImageSource","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo\/pageimagesource","role":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCaptureInfo":{"title":"SBSDKCaptureInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCaptureInfo","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKCaptureInfo"}],"role":"symbol","abstract":[{"text":"Helper class, that gathers the image, camera and detection metadata of a document scan.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCaptureInfo","url":"\/documentation\/scanbotsdk\/sbsdkcaptureinfo","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"pageImageSource","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"pageImageSource","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKPageImageSource","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageImageSource","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKPageImageSource","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageImageSource"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/title","value":"SBSDKPageImageSource","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageImageSource"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageImageSource\/navigatorTitle","value":[{"text":"SBSDKPageImageSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1pageImageSource\/title","op":"replace","value":"pageImageSource"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo~1pageImageSource\/fragments","value":[{"text":"pageImageSource","kind":"identifier"}]},{"value":"SBSDKCaptureInfo","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/title"},{"value":[{"kind":"identifier","text":"SBSDKCaptureInfo"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCaptureInfo\/navigatorTitle","value":[{"text":"SBSDKCaptureInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}