{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKAccumulatedResultsVerifierConfiguration(py)maximumNumberOfAccumulatedFrames","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"maximumNumberOfAccumulatedFrames","role":"symbol","modules":[{"name":"ScanbotSDK"}],"navigatorTitle":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"abstract":[{"text":"Maximum number of accumulated frames to inspect to verify a scan result.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/maximumnumberofaccumulatedframes"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration\/maximumNumberOfAccumulatedFrames","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Default is 3","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration"]]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration/maximumNumberOfAccumulatedFrames":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration\/maximumNumberOfAccumulatedFrames","role":"symbol","type":"topic","abstract":[{"text":"Maximum number of accumulated frames to inspect to verify a scan result.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration\/maximumnumberofaccumulatedframes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}],"title":"maximumNumberOfAccumulatedFrames","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAccumulatedResultsVerifierConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"abstract":[{"text":"Configure the frame accumulation process.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAccumulatedResultsVerifierConfiguration","navigatorTitle":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"title":"SBSDKAccumulatedResultsVerifierConfiguration","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkaccumulatedresultsverifierconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"maximumNumberOfAccumulatedFrames","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"maximumNumberOfAccumulatedFrames"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"maximumNumberOfAccumulatedFrames","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration~1maximumNumberOfAccumulatedFrames\/title","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration~1maximumNumberOfAccumulatedFrames\/fragments","op":"replace","value":[{"text":"maximumNumberOfAccumulatedFrames","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/title","value":"SBSDKAccumulatedResultsVerifierConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAccumulatedResultsVerifierConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAccumulatedResultsVerifierConfiguration"}],"op":"replace"}]}]}