{"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/creditcardscanning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/creditcardscanning"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","title":"SBSDKFeature.creditCardScanning","roleHeading":"Case","role":"symbol","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKFeature@SBSDKFeatureCreditCardScanning","navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureCreditCardScanning"}],"modules":[{"name":"ScanbotBarcodeScannerSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardScanning","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/creditCardScanning","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Credit card scanning is enabled in the license."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creditCardScanning","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature":{"abstract":[{"type":"text","text":"The features that are activated in the ScanbotSDK license."}],"navigatorTitle":[{"text":"SBSDKFeature","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature","kind":"symbol","role":"symbol","title":"SBSDKFeature","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFeature","kind":"identifier"}]},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"type":"topic","title":"ScanbotBarcodeScannerSDK","url":"\/documentation\/scanbotbarcodescannersdk","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","abstract":[{"text":"Version: 7.0.1","type":"text"}],"role":"collection"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKFeature/creditCardScanning":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKFeatureCreditCardScanning"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"creditCardScanning"}],"title":"SBSDKFeature.creditCardScanning","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkfeature\/creditcardscanning","abstract":[{"type":"text","text":"Credit card scanning is enabled in the license."}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKFeature\/creditCardScanning","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SBSDKFeatureCreditCardScanning","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SBSDKFeatureCreditCardScanning","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKFeatureCreditCardScanning","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SBSDKFeature","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKFeature"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/fragments","op":"replace"},{"value":[{"text":"SBSDKFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature\/navigatorTitle","op":"replace"},{"value":"SBSDKFeatureCreditCardScanning","path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1creditCardScanning\/title","op":"replace"},{"value":[{"text":"SBSDKFeatureCreditCardScanning","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKFeature~1creditCardScanning\/fragments","op":"replace"}]}]}