{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldTypeDateOfBirth","kind":"identifier"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType.dateOfBirth","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"case","externalID":"c:@M@ScanbotSDK@E@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType@SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldTypeDateOfBirth"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Date of birth."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldtype\/dateofbirth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldtype\/dateofbirth"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType\/dateOfBirth"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 7.0.0"}],"url":"\/documentation\/scanbotsdk","title":"ScanbotSDK","type":"topic","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType"}],"type":"topic","abstract":[{"text":"Health insurance card field type.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType","title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldtype","kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType/dateOfBirth":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldTypeDateOfBirth"}],"title":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType.dateOfBirth","role":"symbol","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkeuropeanhealthinsurancecardrecognitionresultfieldtype\/dateofbirth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType\/dateOfBirth","abstract":[{"type":"text","text":"Date of birth."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldTypeDateOfBirth","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldTypeDateOfBirth","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldTypeDateOfBirth"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType\/title"},{"value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType\/fragments"},{"op":"replace","value":[{"text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType\/navigatorTitle"},{"op":"replace","value":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldTypeDateOfBirth","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType~1dateOfBirth\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldTypeDateOfBirth"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKEuropeanHealthInsuranceCardRecognitionResultFieldType~1dateOfBirth\/fragments"}]}]}