{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize"]]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us5X7","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"us5X7","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"case","roleHeading":"Case","title":"SBSDKPageSize.us5X7","role":"symbol","externalID":"c:@M@ScanbotSDK@E@SBSDKPageSize@SBSDKPageSizeUs5X7","navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeUs5X7"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"us5X7"}],"modules":[{"name":"ScanbotSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/us5x7"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkpagesize\/us5x7"]}],"kind":"symbol","abstract":[{"type":"text","text":"5 x 7 (inches)           360 x 504 (pixels) at 72 DPI."}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize/us5X7":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSizeUs5X7"}],"title":"SBSDKPageSize.us5X7","type":"topic","abstract":[{"text":"5 x 7 (inches)           360 x 504 (pixels) at 72 DPI.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"us5X7"}],"role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpagesize\/us5x7","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize\/us5X7"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPageSize":{"title":"SBSDKPageSize","abstract":[{"type":"text","text":"Page size."}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKPageSize"}],"url":"\/documentation\/scanbotsdk\/sbsdkpagesize","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPageSize"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPageSize","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"text":"Version: 8.0.1","type":"text"}],"title":"ScanbotSDK","type":"topic","role":"collection","url":"\/documentation\/scanbotsdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKPageSizeUs5X7"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKPageSizeUs5X7"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SBSDKPageSizeUs5X7","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us5X7\/title","op":"replace","value":"SBSDKPageSizeUs5X7"},{"op":"replace","value":[{"text":"SBSDKPageSizeUs5X7","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize~1us5X7\/fragments"},{"op":"replace","value":"SBSDKPageSize","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/title"},{"op":"replace","value":[{"text":"SBSDKPageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/fragments"},{"op":"replace","value":[{"text":"SBSDKPageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPageSize\/navigatorTitle"}]}]}