{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerUIConfiguration\/finderAspectRatio"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerUIConfiguration"]]},"kind":"symbol","metadata":{"modules":[{"name":"ScanbotSDK"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerUIConfiguration(py)finderAspectRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"finderAspectRatio"},{"text":": ","kind":"text"},{"text":"SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio"}],"navigatorTitle":[{"kind":"identifier","text":"finderAspectRatio"}],"symbolKind":"property","title":"finderAspectRatio"},"abstract":[{"type":"text","text":"The aspect ratio of finder frame (width \\ height), which is used to build actual finder frame."}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscanneruiconfiguration\/finderaspectratio"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscanneruiconfiguration\/finderaspectratio"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"finderAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio"}]}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerUIConfiguration/finderAspectRatio":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"finderAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio"}],"navigatorTitle":[{"kind":"identifier","text":"finderAspectRatio"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerUIConfiguration\/finderAspectRatio","kind":"symbol","abstract":[{"text":"The aspect ratio of finder frame (width \\ height), which is used to build actual finder frame.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuivinscanneruiconfiguration\/finderaspectratio","title":"finderAspectRatio"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerUIConfiguration":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerUIConfiguration","navigatorTitle":[{"text":"SBSDKUIVINScannerUIConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuivinscanneruiconfiguration","title":"SBSDKUIVINScannerUIConfiguration","type":"topic","abstract":[{"type":"text","text":"The configuration for the user interface of the RTU-UI vehicle identification number scanner."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUIVINScannerUIConfiguration"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKAspectRatio":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","url":"\/documentation\/scanbotsdk\/sbsdkaspectratio","kind":"symbol","type":"topic","title":"SBSDKAspectRatio","navigatorTitle":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"abstract":[{"type":"text","text":"Aspect ratio is the ratio of the width to the height of an image or screen."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKAspectRatio"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"finderAspectRatio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"finderAspectRatio","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKAspectRatio","text":"SBSDKAspectRatio","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKAspectRatio","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"finderAspectRatio","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration~1finderAspectRatio\/title","value":"finderAspectRatio"},{"value":[{"text":"finderAspectRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration~1finderAspectRatio\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration\/title","op":"replace","value":"SBSDKUIVINScannerUIConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration\/fragments","value":[{"text":"SBSDKUIVINScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration\/navigatorTitle","value":[{"text":"SBSDKUIVINScannerUIConfiguration","kind":"identifier"}],"op":"replace"},{"value":"SBSDKAspectRatio","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/title","op":"replace"},{"value":[{"text":"SBSDKAspectRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKAspectRatio\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKAspectRatio"}],"op":"replace"}]}]}