{"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerUIConfiguration\/orientationLockMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerUIConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"orientationLockMode"}],"role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIVINScannerUIConfiguration(py)orientationLockMode","modules":[{"name":"ScanbotSDK"}],"title":"orientationLockMode","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock"}]},"abstract":[{"type":"text","text":"Allowed orientations for automatic interface rotations."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","text":"SBSDKOrientationLock","kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock"}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscanneruiconfiguration\/orientationlockmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuivinscanneruiconfiguration\/orientationlockmode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerUIConfiguration/orientationLockMode":{"navigatorTitle":[{"text":"orientationLockMode","kind":"identifier"}],"abstract":[{"text":"Allowed orientations for automatic interface rotations.","type":"text"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerUIConfiguration\/orientationLockMode","kind":"symbol","title":"orientationLockMode","url":"\/documentation\/scanbotsdk\/sbsdkuivinscanneruiconfiguration\/orientationlockmode","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"orientationLockMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","text":"SBSDKOrientationLock","kind":"typeIdentifier"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIVINScannerUIConfiguration":{"kind":"symbol","role":"symbol","title":"SBSDKUIVINScannerUIConfiguration","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIVINScannerUIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIVINScannerUIConfiguration"}],"navigatorTitle":[{"text":"SBSDKUIVINScannerUIConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuivinscanneruiconfiguration","abstract":[{"text":"The configuration for the user interface of the RTU-UI vehicle identification number scanner.","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","kind":"symbol","abstract":[{"text":"Version: 6.0.0","type":"text"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKOrientationLock":{"title":"SBSDKOrientationLock","url":"\/documentation\/scanbotsdk\/sbsdkorientationlock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKOrientationLock"}],"abstract":[{"type":"text","text":"This enum describes the available orientation lock modes for the user interface."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SBSDKOrientationLock","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"orientationLockMode"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"orientationLockMode"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SBSDKOrientationLock","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKOrientationLock","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKOrientationLock"},{"text":" ","kind":"text"},{"text":"orientationLockMode","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration~1orientationLockMode\/title","op":"replace","value":"orientationLockMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration~1orientationLockMode\/fragments","value":[{"kind":"identifier","text":"orientationLockMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration\/title","op":"replace","value":"SBSDKUIVINScannerUIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIVINScannerUIConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKUIVINScannerUIConfiguration"}]},{"value":"SBSDKOrientationLock","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKOrientationLock"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKOrientationLock\/fragments"}]}]}