{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@ScanbotSDK@E@SBSDKPolygonEdgeOrientation","modules":[{"name":"ScanbotSDK","relatedModules":["Swift"]}],"extendedModule":"Swift","symbolKind":"method","title":"hash(into:)"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdgeOrientation","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdgeOrientation\/RawRepresentable-Implementations"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkpolygonedgeorientation\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdgeOrientation\/hash(into:)","interfaceLanguage":"swift"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonEdgeOrientation/hash(into:)":{"url":"\/documentation\/scanbotsdk\/sbsdkpolygonedgeorientation\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"hash(into:)","kind":"symbol","type":"topic","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdgeOrientation\/hash(into:)","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 6.1.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonEdgeOrientation":{"kind":"symbol","abstract":[{"type":"text","text":"An enum describing the orientation of a polygon edge."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdgeOrientation","title":"SBSDKPolygonEdgeOrientation","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkpolygonedgeorientation","type":"topic","navigatorTitle":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPolygonEdgeOrientation"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKPolygonEdgeOrientation/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkpolygonedgeorientation\/rawrepresentable-implementations","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKPolygonEdgeOrientation\/RawRepresentable-Implementations","kind":"article","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonEdgeOrientation\/title","value":"SBSDKPolygonEdgeOrientation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonEdgeOrientation\/fragments","value":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}]},{"op":"replace","value":[{"text":"SBSDKPolygonEdgeOrientation","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKPolygonEdgeOrientation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}