{"abstract":[{"text":"Images are serialized as base64 encoded buffers.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSerializationMode\/buffer"},"variants":[{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimageserializationmode\/buffer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotbarcodescannersdk\/sbsdkimageserializationmode\/buffer"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"SBSDKImageSerializationMode.buffer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"buffer"}],"roleHeading":"Case","externalID":"c:@M@ScanbotBarcodeScannerSDK@E@SBSDKImageSerializationMode@SBSDKImageSerializationModeBuffer","modules":[{"name":"ScanbotBarcodeScannerSDK"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationModeBuffer"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buffer","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSerializationMode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageSerializationMode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSerializationMode","navigatorTitle":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}],"url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageserializationmode","title":"SBSDKImageSerializationMode","abstract":[{"text":"Image serialization mode. Applicable only when serializeImages is true.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK/SBSDKImageSerializationMode/buffer":{"kind":"symbol","url":"\/documentation\/scanbotbarcodescannersdk\/sbsdkimageserializationmode\/buffer","type":"topic","identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK\/SBSDKImageSerializationMode\/buffer","abstract":[{"type":"text","text":"Images are serialized as base64 encoded buffers."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"buffer"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKImageSerializationModeBuffer"}],"role":"symbol","title":"SBSDKImageSerializationMode.buffer"},"doc://net.doo.ScanbotBarcodeScannerSDK/documentation/ScanbotBarcodeScannerSDK":{"kind":"symbol","abstract":[{"type":"text","text":"Version: 8.0.1"}],"identifier":"doc:\/\/net.doo.ScanbotBarcodeScannerSDK\/documentation\/ScanbotBarcodeScannerSDK","role":"collection","url":"\/documentation\/scanbotbarcodescannersdk","type":"topic","title":"ScanbotBarcodeScannerSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKImageSerializationModeBuffer"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageSerializationModeBuffer"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SBSDKImageSerializationModeBuffer"}]}]}},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSerializationMode\/title","op":"replace","value":"SBSDKImageSerializationMode"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSerializationMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKImageSerializationMode"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSerializationMode\/navigatorTitle","op":"replace","value":[{"text":"SBSDKImageSerializationMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSerializationMode~1buffer\/title","op":"replace","value":"SBSDKImageSerializationModeBuffer"},{"path":"\/references\/doc:~1~1net.doo.ScanbotBarcodeScannerSDK~1documentation~1ScanbotBarcodeScannerSDK~1SBSDKImageSerializationMode~1buffer\/fragments","op":"replace","value":[{"text":"SBSDKImageSerializationModeBuffer","kind":"identifier"}]}]}]}