{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripCheckDigits","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}]}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/stripcheckdigits"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/stripcheckdigits"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters"]]},"metadata":{"title":"stripCheckDigits","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripCheckDigits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIBarcodeAdditionalParameters(py)stripCheckDigits","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stripCheckDigits"}],"modules":[{"name":"ScanbotSDK"}]},"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters\/stripCheckDigits","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"With this option enabled, the scanner removes checks digits for UPC, EAN and MSI Plessey codes.","type":"text"},{"text":" ","type":"text"},{"text":"Has no effect if both single and double digit MSI Plessey checksums are enabled.","type":"text"}],"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeAdditionalParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"A class that contains additional parameters for barcodes scanning and filtering."}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters","role":"symbol","title":"SBSDKUIBarcodeAdditionalParameters","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIBarcodeAdditionalParameters/stripCheckDigits":{"title":"stripCheckDigits","kind":"symbol","type":"topic","navigatorTitle":[{"text":"stripCheckDigits","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIBarcodeAdditionalParameters\/stripCheckDigits","abstract":[{"text":"With this option enabled, the scanner removes checks digits for UPC, EAN and MSI Plessey codes.","type":"text"},{"text":" ","type":"text"},{"text":"Has no effect if both single and double digit MSI Plessey checksums are enabled.","type":"text"}],"url":"\/documentation\/scanbotsdk\/sbsdkuibarcodeadditionalparameters\/stripcheckdigits","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripCheckDigits","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"stripCheckDigits"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"stripCheckDigits","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"stripCheckDigits","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/title","op":"replace","value":"SBSDKUIBarcodeAdditionalParameters"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/fragments","op":"replace","value":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters\/navigatorTitle","op":"replace","value":[{"text":"SBSDKUIBarcodeAdditionalParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters~1stripCheckDigits\/title","op":"replace","value":"stripCheckDigits"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIBarcodeAdditionalParameters~1stripCheckDigits\/fragments","op":"replace","value":[{"text":"stripCheckDigits","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}