{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions\/copyWithZone:"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/copywithzone:"]}],"metadata":{"title":"copyWithZone:","roleHeading":"Instance Method","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKSaveImageOptions(im)copyWithZone:","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"role":"symbol","symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSaveImageOptions/copyWithZone:":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions\/copyWithZone:","title":"copyWithZone:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions\/copywithzone:","abstract":[],"role":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKSaveImageOptions":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"role":"symbol","title":"SBSDKSaveImageOptions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKSaveImageOptions","abstract":[{"text":"Options for saving image to a path.","type":"text"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdksaveimageoptions","navigatorTitle":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}],"kind":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk","kind":"symbol","role":"collection","title":"ScanbotDocumentScannerSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/title","value":"SBSDKSaveImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/fragments","value":[{"text":"SBSDKSaveImageOptions","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKSaveImageOptions"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKSaveImageOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}