{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The explanation text of the camera permission dialog."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"Default is “Please allow the usage of the camera to start the scanning process.”"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization\/camerapermissionenablecameraexplanation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization\/camerapermissionenablecameraexplanation"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization"]]},"metadata":{"navigatorTitle":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUI2TextPatternScannerScreenTextLocalization(py)cameraPermissionEnableCameraExplanation","title":"cameraPermissionEnableCameraExplanation"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization\/cameraPermissionEnableCameraExplanation"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","kind":"symbol","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"text":"Version: 7.1.2","type":"text"}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenTextLocalization/cameraPermissionEnableCameraExplanation":{"navigatorTitle":[{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPermissionEnableCameraExplanation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The explanation text of the camera permission dialog."}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization\/cameraPermissionEnableCameraExplanation","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization\/camerapermissionenablecameraexplanation","kind":"symbol","title":"cameraPermissionEnableCameraExplanation"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUI2TextPatternScannerScreenTextLocalization":{"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUI2TextPatternScannerScreenTextLocalization","url":"\/documentation\/scanbotsdk\/sbsdkui2textpatternscannerscreentextlocalization","abstract":[{"text":"Configuration of the all strings for generic text scanner screen.","type":"text"}],"title":"SBSDKUI2TextPatternScannerScreenTextLocalization","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUI2TextPatternScannerScreenTextLocalization"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"cameraPermissionEnableCameraExplanation"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"cameraPermissionEnableCameraExplanation","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization~1cameraPermissionEnableCameraExplanation\/title"},{"value":[{"text":"cameraPermissionEnableCameraExplanation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization~1cameraPermissionEnableCameraExplanation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/title","value":"SBSDKUI2TextPatternScannerScreenTextLocalization"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/fragments","value":[{"text":"SBSDKUI2TextPatternScannerScreenTextLocalization","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUI2TextPatternScannerScreenTextLocalization\/navigatorTitle","value":[{"text":"SBSDKUI2TextPatternScannerScreenTextLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}