{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFImageExtractor\/extract(from:scaling:compression:encrypter:outputDirectory:completion:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Asynchronously extracts images from a PDF, converts them to JPEGs and writes them to a specified URL.","type":"text"},{"text":" ","type":"text"},{"text":"The array of URLs is passed within the completion handler.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfimageextractor\/extract(from:scaling:compression:encrypter:outputdirectory:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfimageextractor\/extract(from:scaling:compression:encrypter:outputdirectory:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKPDFImageExtractor(im)extractImageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","modules":[{"name":"ScanbotDocumentScannerSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"extractImageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"}],"symbolKind":"method","title":"extract(from:scaling:compression:encrypter:outputDirectory:completion:)","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFImageExtractor"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(extractImageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extract"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pdfURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"encrypter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"outputDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier","text":"SBSDKProgress"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The URL of the PDF file.","type":"text"}]}],"name":"pdfURL"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher."}]}],"name":"scaling"},{"content":[{"inlineContent":[{"text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used.","type":"text"}],"type":"paragraph"}],"name":"compression"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}]}],"name":"encrypter"},{"content":[{"inlineContent":[{"type":"text","text":"The output folder where images will be stored. If the folder does not exist, it will be created."}],"type":"paragraph"}],"name":"outputDirectory"},{"content":[{"inlineContent":[{"type":"text","text":"The completion handler that delivers the created array of image file URLs."}],"type":"paragraph"}],"name":"completion"}]},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"A progress object that can be used for cancellation and progress observing. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", an error occurred."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"abstract":[{"type":"text","text":"Version: 7.0.2"}],"role":"collection","title":"ScanbotDocumentScannerSDK","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFImageExtractor/extract(from:scaling:compression:encrypter:outputDirectory:completion:)":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFImageExtractor\/extract(from:scaling:compression:encrypter:outputDirectory:completion:)","abstract":[{"type":"text","text":"Asynchronously extracts images from a PDF, converts them to JPEGs and writes them to a specified URL."},{"type":"text","text":" "},{"type":"text","text":"The array of URLs is passed within the completion handler."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extract","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scaling","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"compression","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"encrypter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SBSDKStorageCrypting","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"outputDirectory","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"SBSDKProgress","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"extractImageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfimageextractor\/extract(from:scaling:compression:encrypter:outputdirectory:completion:)","title":"extract(from:scaling:compression:encrypter:outputDirectory:completion:)"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKPDFImageExtractor":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkpdfimageextractor","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKPDFImageExtractor","navigatorTitle":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"title":"SBSDKPDFImageExtractor","kind":"symbol","abstract":[{"text":"Class used to extract images from a PDF file and returns them in various ways.","type":"text"}],"role":"symbol"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKStorageCrypting":{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKStorageCrypting","title":"SBSDKStorageCrypting","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkstoragecrypting","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKStorageCrypting","kind":"identifier"}],"navigatorTitle":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"abstract":[{"text":"Protocol for implementing encryption and decryption of (streamed) data.","type":"text"}],"kind":"symbol","type":"topic"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKProgress":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","type":"topic","abstract":[],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkprogress","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKProgress"}],"title":"SBSDKProgress","navigatorTitle":[{"kind":"identifier","text":"SBSDKProgress"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"extractImageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"extractImageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKProgress","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKProgress","text":"SBSDKProgress"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"extractImageURLsFromPDF:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pdfURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaling:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scaling"},{"kind":"text","text":" "},{"kind":"identifier","text":"compression:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"compression"},{"kind":"text","text":" "},{"kind":"identifier","text":"encrypter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ScanbotDocumentScannerSDK@objc(pl)SBSDKStorageCrypting","text":"id<SBSDKStorageCrypting>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"encrypter"},{"kind":"text","text":" "},{"kind":"identifier","text":"outputDirectory:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"outputDirectory"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURL *>"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"pdfURL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL of the PDF file.","type":"text"}]}]},{"name":"scaling","content":[{"type":"paragraph","inlineContent":[{"text":"Scaling applied to the PDF media box frame while extracting. Affects the output image quality. In most cases the recommended value is 2 and higher.","type":"text"}]}]},{"name":"compression","content":[{"inlineContent":[{"type":"text","text":"Compression of the output image file. The range is from 0 to 1, where 1 - lossless conversion, 0 - maximum compression is used."}],"type":"paragraph"}]},{"name":"encrypter","content":[{"inlineContent":[{"type":"text","text":"The encrypter used to encrypt output image files. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", no encryption is used."}],"type":"paragraph"}]},{"name":"outputDirectory","content":[{"type":"paragraph","inlineContent":[{"text":"The output folder where images will be stored. If the folder does not exist, it will be created.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"The completion handler that delivers the created array of image file URLs.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A progress object that can be used for cancellation and progress observing. If "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", an error occurred."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"extractImageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor~1extract(from:scaling:compression:encrypter:outputDirectory:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extractImageURLsFromPDF:scaling:compression:encrypter:outputDirectory:completion:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor~1extract(from:scaling:compression:encrypter:outputDirectory:completion:)\/fragments","op":"replace"},{"value":"SBSDKPDFImageExtractor","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKPDFImageExtractor"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKPDFImageExtractor\/navigatorTitle","op":"replace"},{"value":"SBSDKStorageCrypting","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/title","op":"replace"},{"value":[{"text":"SBSDKStorageCrypting","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SBSDKStorageCrypting"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKStorageCrypting\/navigatorTitle","op":"replace"},{"value":"SBSDKProgress","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/title","op":"replace"},{"value":[{"text":"SBSDKProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/fragments","op":"replace"},{"value":[{"text":"SBSDKProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKProgress\/navigatorTitle","op":"replace"}]}]}