{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration"]]},"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration(im)initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:","navigatorTitle":[{"kind":"identifier","text":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:"}],"modules":[{"name":"ScanbotSDK"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:"}],"title":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithOcrResolutionLimit:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"ocrResolutionLimit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maximumNumberOfAccumulatedFrames","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minimumNumberOfRequiredFramesWithEqualScanningResult","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validator:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKContentValidator","text":"SBSDKContentValidator","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"validator","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/initwithocrresolutionlimit:maximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:validator:"]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration/initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:":{"navigatorTitle":[{"kind":"identifier","text":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:"}],"kind":"symbol","role":"symbol","title":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/initwithocrresolutionlimit:maximumnumberofaccumulatedframes:minimumnumberofrequiredframeswithequalscanningresult:validator:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/initWithOcrResolutionLimit:maximumNumberOfAccumulatedFrames:minimumNumberOfRequiredFramesWithEqualScanningResult:validator:","type":"topic","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration","abstract":[{"text":"Configuration for the text pattern scanner.","type":"text"}],"type":"topic","title":"SBSDKTextPatternScannerConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKContentValidator":{"kind":"symbol","type":"topic","title":"SBSDKContentValidator","abstract":[{"text":"Base class for content validators.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKContentValidator","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcontentvalidator","navigatorTitle":[{"text":"SBSDKContentValidator","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKContentValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/title","value":"SBSDKTextPatternScannerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/navigatorTitle","value":[{"text":"SBSDKTextPatternScannerConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/title","value":"SBSDKContentValidator"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/fragments","value":[{"kind":"identifier","text":"SBSDKContentValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKContentValidator\/navigatorTitle","value":[{"text":"SBSDKContentValidator","kind":"identifier"}]}]}]}