{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/isEqual:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/isequal:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"isEqual:","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerConfiguration(im)isEqual:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","modules":[{"name":"ScanbotSDK"}]},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration":{"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration","abstract":[{"text":"Configuration for the text pattern scanner.","type":"text"}],"type":"topic","title":"SBSDKTextPatternScannerConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","abstract":[{"type":"text","text":"Version: 7.1.3"}],"type":"topic","role":"collection","kind":"symbol","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerConfiguration/isEqual:":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"type":"topic","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerconfiguration\/isequal:","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerConfiguration\/isEqual:","title":"isEqual:"}},"variantOverrides":[{"patch":[{"value":"SBSDKTextPatternScannerConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/title"},{"value":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKTextPatternScannerConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}