{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentFound"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","text":"SBSDKDocumentQuality","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"orientation"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cumulativeQualityHistogram","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQualityAnalyzerResult(im)initWithDocumentFound:quality:orientation:cumulativeQualityHistogram:","role":"symbol","modules":[{"name":"ScanbotSDK"}],"title":"init(documentFound:quality:orientation:cumulativeQualityHistogram:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentFound"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"quality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SBSDKDocumentQuality","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality"},{"text":"?, ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"cumulativeQualityHistogram"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithDocumentFound:quality:orientation:cumulativeQualityHistogram:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult\/init(documentfound:quality:orientation:cumulativequalityhistogram:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult\/init(documentfound:quality:orientation:cumulativequalityhistogram:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult\/init(documentFound:quality:orientation:cumulativeQualityHistogram:)"},"kind":"symbol","references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerResult/init(documentFound:quality:orientation:cumulativeQualityHistogram:)":{"kind":"symbol","title":"init(documentFound:quality:orientation:cumulativeQualityHistogram:)","navigatorTitle":[{"text":"initWithDocumentFound:quality:orientation:cumulativeQualityHistogram:","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult\/init(documentFound:quality:orientation:cumulativeQualityHistogram:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","text":"SBSDKDocumentQuality","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"orientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"text":"cumulativeQualityHistogram","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"])"}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult\/init(documentfound:quality:orientation:cumulativequalityhistogram:)","type":"topic","abstract":[],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQualityAnalyzerResult":{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQualityAnalyzerResult","abstract":[{"type":"text","text":"Result of document quality analysis. It can be used to determine, e.g., if a document is good enough to be used for"},{"text":" ","type":"text"},{"type":"text","text":"OCR processing."}],"url":"\/documentation\/scanbotsdk\/sbsdkdocumentqualityanalyzerresult","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentQualityAnalyzerResult"}],"title":"SBSDKDocumentQualityAnalyzerResult","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"abstract":[{"type":"text","text":"Version: 7.1.0"}],"url":"\/documentation\/scanbotsdk","role":"collection","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","kind":"symbol","type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKDocumentQuality":{"abstract":[{"type":"text","text":"Result of document quality analysis."}],"type":"topic","navigatorTitle":[{"text":"SBSDKDocumentQuality","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality","role":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkdocumentquality","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentQuality","kind":"identifier"}],"title":"SBSDKDocumentQuality"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithDocumentFound:quality:orientation:cumulativeQualityHistogram:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDocumentFound:quality:orientation:cumulativeQualityHistogram:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDocumentFound:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"documentFound","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKDocumentQuality","kind":"typeIdentifier","text":"SBSDKDocumentQuality","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKDocumentQuality"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"quality"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"orientation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cumulativeQualityHistogram:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"cumulativeQualityHistogram","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult~1init(documentFound:quality:orientation:cumulativeQualityHistogram:)\/title","value":"initWithDocumentFound:quality:orientation:cumulativeQualityHistogram:"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult~1init(documentFound:quality:orientation:cumulativeQualityHistogram:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDocumentFound:quality:orientation:cumulativeQualityHistogram:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/title","value":"SBSDKDocumentQualityAnalyzerResult"},{"value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/fragments"},{"op":"replace","value":[{"text":"SBSDKDocumentQualityAnalyzerResult","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQualityAnalyzerResult\/navigatorTitle"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/title","op":"replace","value":"SBSDKDocumentQuality"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/fragments","value":[{"text":"SBSDKDocumentQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKDocumentQuality\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKDocumentQuality"}],"op":"replace"}]}]}