{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions\/hash"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions\/hash","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKEncodeImageOptions(py)hash","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ScanbotDocumentScannerSDK"}]},"kind":"symbol","sections":[],"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodeImageOptions/hash":{"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions\/hash","title":"hash","abstract":[],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions\/hash","kind":"symbol","role":"symbol","fragments":[{"text":"hash","kind":"identifier"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"type":"topic","abstract":[{"text":"Version: 8.0.1","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","title":"ScanbotDocumentScannerSDK","url":"\/documentation\/scanbotdocumentscannersdk"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKEncodeImageOptions":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Options for encoding image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkencodeimageoptions","title":"SBSDKEncodeImageOptions","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKEncodeImageOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKEncodeImageOptions"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKEncodeImageOptions","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/title"},{"value":[{"kind":"identifier","text":"SBSDKEncodeImageOptions"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/fragments"},{"value":[{"text":"SBSDKEncodeImageOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKEncodeImageOptions\/navigatorTitle"}]}]}