{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/SBSDKTextPatternScannerViewControllerDelegate-Implementations"]]},"abstract":[{"text":"Asks the delegate whether the next video frame should be scanned or not.","type":"text"}],"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/textpatternscannerviewcontrollershouldscan(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/textpatternscannerviewcontrollershouldscan(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textPatternScannerViewControllerShouldScan"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","isActive":true},{"type":"text","text":" that wants to scan the next video frame."}],"type":"paragraph"}],"name":"controller"}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"True"},{"type":"text","text":", if you want to scan the next video frame, "},{"type":"codeVoice","code":"False"},{"type":"text","text":" otherwise."}]}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Optional.","type":"text"},{"text":" ","type":"text"},{"text":"Use to skip frames or pause the scanner for a while.","type":"text"}]}],"kind":"content"}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","extendedModule":"ScanbotSDK","roleHeading":"Instance Method","title":"textPatternScannerViewControllerShouldScan(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textPatternScannerViewControllerShouldScan"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","navigatorTitle":[{"text":"textPatternScannerViewControllerShouldScan:","kind":"identifier"}],"externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerViewController(im)textPatternScannerViewControllerShouldScan:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewControllerShouldScan(_:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"title":"SBSDKTextPatternScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the text pattern scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController/textPatternScannerViewControllerShouldScan(_:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewControllerShouldScan(_:)","type":"topic","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/textpatternscannerviewcontrollershouldscan(_:)","title":"textPatternScannerViewControllerShouldScan(_:)","abstract":[{"text":"Asks the delegate whether the next video frame should be scanned or not.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textPatternScannerViewControllerShouldScan","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"textPatternScannerViewControllerShouldScan:"}]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController/SBSDKTextPatternScannerViewControllerDelegate-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/sbsdktextpatternscannerviewcontrollerdelegate-implementations","type":"topic","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/SBSDKTextPatternScannerViewControllerDelegate-Implementations","title":"SBSDKTextPatternScannerViewControllerDelegate Implementations","abstract":[],"role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan and validate a small rectangular text area in realtime."}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller","title":"SBSDKUITextPatternScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"textPatternScannerViewControllerShouldScan:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textPatternScannerViewControllerShouldScan:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"textPatternScannerViewControllerShouldScan:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"SBSDKTextPatternScannerViewController","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title"},{"value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments"},{"op":"replace","value":[{"text":"SBSDKTextPatternScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle"},{"value":"textPatternScannerViewControllerShouldScan:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController~1textPatternScannerViewControllerShouldScan(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"textPatternScannerViewControllerShouldScan:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController~1textPatternScannerViewControllerShouldScan(_:)\/fragments"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/title","value":"SBSDKUITextPatternScannerViewController","op":"replace"},{"value":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/navigatorTitle"}]}]}