{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textPatternScannerViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didValidate"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","kind":"typeIdentifier","text":"SBSDKTextPatternScannerResult","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"controller","content":[{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","type":"reference","isActive":true},{"type":"text","text":" that has scanned and validated the text pattern."}],"type":"paragraph"}]},{"name":"result","content":[{"inlineContent":[{"text":"The result of the scan.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/textpatternscannerviewcontroller(_:didvalidate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/textpatternscannerviewcontroller(_:didvalidate:)"]}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/SBSDKTextPatternScannerViewControllerDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Informs the delegate that text pattern has been scanned and validated and passes the result."}],"metadata":{"navigatorTitle":[{"text":"textLineScannerViewController:didValidateResult:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textPatternScannerViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"SBSDKTextPatternScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didValidate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SBSDKTextPatternScannerResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult"},{"kind":"text","text":")"}],"modules":[{"name":"ScanbotSDK"}],"title":"textPatternScannerViewController(_:didValidate:)","roleHeading":"Instance Method","role":"symbol","extendedModule":"ScanbotSDK","externalID":"c:@CM@ScanbotSDK@objc(cs)SBSDKUITextPatternScannerViewController(im)textLineScannerViewController:didValidateResult:","symbolKind":"method"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewController(_:didValidate:)"},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController/SBSDKTextPatternScannerViewControllerDelegate-Implementations":{"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/sbsdktextpatternscannerviewcontrollerdelegate-implementations","type":"topic","kind":"article","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/SBSDKTextPatternScannerViewControllerDelegate-Implementations","title":"SBSDKTextPatternScannerViewControllerDelegate Implementations","abstract":[],"role":"collectionGroup"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"kind":"symbol","type":"topic","role":"collection","title":"ScanbotSDK","url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.0.0"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A highly customizable camera-based view controller to scan and validate a small rectangular text area in realtime."}],"deprecated":true,"url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller","title":"SBSDKUITextPatternScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUITextPatternScannerViewController"}],"kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerViewController":{"title":"SBSDKTextPatternScannerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" subclass to show a camera screen with the text pattern scanner."}],"url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerviewcontroller"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUITextPatternScannerViewController/textPatternScannerViewController(_:didValidate:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textPatternScannerViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","text":"SBSDKTextPatternScannerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didValidate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","kind":"typeIdentifier","text":"SBSDKTextPatternScannerResult"},{"text":")","kind":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUITextPatternScannerViewController\/textPatternScannerViewController(_:didValidate:)","url":"\/documentation\/scanbotsdk\/sbsdkuitextpatternscannerviewcontroller\/textpatternscannerviewcontroller(_:didvalidate:)","type":"topic","title":"textPatternScannerViewController(_:didValidate:)","kind":"symbol","navigatorTitle":[{"text":"textLineScannerViewController:didValidateResult:","kind":"identifier"}],"abstract":[{"type":"text","text":"Informs the delegate that text pattern has been scanned and validated and passes the result."}],"role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKTextPatternScannerResult":{"navigatorTitle":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"kind":"symbol","title":"SBSDKTextPatternScannerResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKTextPatternScannerResult","kind":"identifier"}],"type":"topic","abstract":[{"text":"The result of the text line recognition.","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","url":"\/documentation\/scanbotsdk\/sbsdktextpatternscannerresult","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"textLineScannerViewController:didValidateResult:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textLineScannerViewController:didValidateResult:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"textLineScannerViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerViewController","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerViewController","kind":"typeIdentifier","text":"SBSDKTextPatternScannerViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":" ","kind":"text"},{"text":"didValidateResult:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@objc(cs)SBSDKTextPatternScannerResult","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKTextPatternScannerResult","text":"SBSDKTextPatternScannerResult"},{"kind":"text","text":" *) "},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/title","value":"SBSDKUITextPatternScannerViewController","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/fragments","value":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController\/navigatorTitle","value":[{"text":"SBSDKUITextPatternScannerViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/title","op":"replace","value":"SBSDKTextPatternScannerViewController"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/fragments","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerViewController"}]},{"op":"replace","value":"textLineScannerViewController:didValidateResult:","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController~1textPatternScannerViewController(_:didValidate:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textLineScannerViewController:didValidateResult:"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUITextPatternScannerViewController~1textPatternScannerViewController(_:didValidate:)\/fragments"},{"op":"replace","value":"SBSDKTextPatternScannerResult","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}]},{"value":[{"kind":"identifier","text":"SBSDKTextPatternScannerResult"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKTextPatternScannerResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}