{"metadata":{"symbolKind":"property","modules":[{"name":"ScanbotSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoQualityPrioritization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization","text":"SBSDKCapturePhotoQualityPrioritization"}],"externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKBaseScannerGeneralConfiguration(py)photoQualityPrioritization","title":"photoQualityPrioritization","navigatorTitle":[{"kind":"identifier","text":"photoQualityPrioritization"}],"role":"symbol","roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration"]]},"kind":"symbol","abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If you experience lots of blurry still images try to set this property to SBSDKCapturePhotoQualityPrioritization."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/photoQualityPrioritization"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/photoqualityprioritization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/photoqualityprioritization"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoQualityPrioritization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBSDKCapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration/photoQualityPrioritization":{"navigatorTitle":[{"text":"photoQualityPrioritization","kind":"identifier"}],"abstract":[{"text":"The prioritization of still image quality and capturing speed.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"If you experience lots of blurry still images try to set this property to SBSDKCapturePhotoQualityPrioritization.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"photoQualityPrioritization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"typeIdentifier","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration\/photoqualityprioritization","type":"topic","title":"photoQualityPrioritization","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration\/photoQualityPrioritization","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization/balanced":{"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization\/balanced","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"balanced","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization\/balanced","navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"type":"topic","title":"SBSDKCapturePhotoQualityPrioritization.balanced","abstract":[{"text":"Balances capturing speed and image quality equally. This is the default value.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKCapturePhotoQualityPrioritization":{"type":"topic","navigatorTitle":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"title":"SBSDKCapturePhotoQualityPrioritization","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization","abstract":[{"type":"text","text":"The prioritization of still image quality and capturing speed."}],"url":"\/documentation\/scanbotsdk\/sbsdkcapturephotoqualityprioritization","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKBaseScannerGeneralConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}],"url":"\/documentation\/scanbotsdk\/sbsdkbasescannergeneralconfiguration","kind":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKBaseScannerGeneralConfiguration","abstract":[{"text":"The general configuration object for a ‘SBSDKBaseScannerViewController’ and its subclasses.","type":"text"}],"title":"SBSDKBaseScannerGeneralConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"photoQualityPrioritization","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"photoQualityPrioritization","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBSDKCapturePhotoQualityPrioritization","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKCapturePhotoQualityPrioritization","preciseIdentifier":"c:@M@ScanbotSDK@E@SBSDKCapturePhotoQualityPrioritization"},{"kind":"text","text":" "},{"kind":"identifier","text":"photoQualityPrioritization"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1photoQualityPrioritization\/title","value":"photoQualityPrioritization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration~1photoQualityPrioritization\/fragments","value":[{"text":"photoQualityPrioritization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/title","value":"SBSDKCapturePhotoQualityPrioritizationBalanced","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization~1balanced\/fragments","value":[{"text":"SBSDKCapturePhotoQualityPrioritizationBalanced","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/title","value":"SBSDKCapturePhotoQualityPrioritization","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/fragments","op":"replace","value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKCapturePhotoQualityPrioritization\/navigatorTitle","op":"replace","value":[{"text":"SBSDKCapturePhotoQualityPrioritization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/title","op":"replace","value":"SBSDKBaseScannerGeneralConfiguration"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"SBSDKBaseScannerGeneralConfiguration"}]},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKBaseScannerGeneralConfiguration\/navigatorTitle","op":"replace","value":[{"text":"SBSDKBaseScannerGeneralConfiguration","kind":"identifier"}]}]}]}