{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration"]]},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/init"},"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"ScanbotSDK"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@ScanbotSDK@objc(cs)SBSDKUIFinderDocumentScannerAccessibilityConfiguration(im)init","title":"init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration/init":{"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/init","kind":"symbol","url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration\/init","abstract":[]},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUIFinderDocumentScannerAccessibilityConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"title":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","deprecated":true,"navigatorTitle":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"url":"\/documentation\/scanbotsdk\/sbsdkuifinderdocumentscanneraccessibilityconfiguration","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUIFinderDocumentScannerAccessibilityConfiguration","abstract":[{"type":"text","text":"Configuration for the accessibility labels and hints."}],"kind":"symbol","role":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"title":"ScanbotSDK","abstract":[{"text":"Version: 7.0.3","type":"text"}],"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/scanbotsdk","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/title"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/fragments","value":[{"text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUIFinderDocumentScannerAccessibilityConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"SBSDKUIFinderDocumentScannerAccessibilityConfiguration"}],"op":"replace"}]}]}