{"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/cornersAndCross","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ScanbotSDK"}],"role":"symbol","title":"SBSDKFinderView.Style.cornersAndCross","externalID":"s:10ScanbotSDK15SBSDKFinderViewC5StyleO15cornersAndCrossyA2EmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornersAndCross"}],"roleHeading":"Case","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum"]]},"abstract":[{"text":"Draw the corners and the cross in the center of the finder view.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/cornersandcross"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornersAndCross","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum":{"url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}],"role":"symbol","title":"SBSDKFinderView.Style","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum","abstract":[{"text":"The enum that defines the drawing styles of the finder view.","type":"text"}],"kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView":{"url":"\/documentation\/scanbotsdk\/sbsdkfinderview","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" subclass to display a view finder with colored background and transparent cutout with the given aspect ratio."}],"title":"SBSDKFinderView","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKFinderView","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SBSDKFinderView","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","kind":"symbol","abstract":[{"text":"Version: 8.0.4","type":"text"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","type":"topic","role":"collection","title":"ScanbotSDK"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKFinderView/Style-swift.enum/cornersAndCross":{"title":"SBSDKFinderView.Style.cornersAndCross","url":"\/documentation\/scanbotsdk\/sbsdkfinderview\/style-swift.enum\/cornersandcross","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKFinderView\/Style-swift.enum\/cornersAndCross","abstract":[{"type":"text","text":"Draw the corners and the cross in the center of the finder view."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornersAndCross","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/title","value":"SBSDKFinderView","op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/fragments","value":[{"kind":"identifier","text":"SBSDKFinderView"}],"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKFinderView\/navigatorTitle","value":[{"text":"SBSDKFinderView","kind":"identifier"}],"op":"replace"}]}]}