{"sections":[],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/copy(with:)"]},{"paths":["\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/copy(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/copy(with:)"},"abstract":[{"text":"Creates a deep copy of the ","type":"text"},{"type":"codeVoice","code":"SBSDKDocumentDetectionMetrics"},{"text":" instance.","type":"text"}],"metadata":{"externalID":"c:@M@ScanbotDocumentScannerSDK@objc(cs)SBSDKDocumentDetectionMetrics(im)copyWithZone:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","modules":[{"name":"ScanbotDocumentScannerSDK"}],"title":"copy(with:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK":{"title":"ScanbotDocumentScannerSDK","abstract":[{"text":"Version: 6.2.0","type":"text"}],"kind":"symbol","url":"\/documentation\/scanbotdocumentscannersdk","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK","type":"topic","role":"collection"},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetector":{"role":"symbol","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetector","title":"SBSDKDocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKDocumentDetector"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector","navigatorTitle":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"kind":"symbol","abstract":[{"type":"text","text":"A class to detect a document’s outline polygon in a UIImage or CMSampleBufferRef."}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics/copy(with:)":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"type":"topic","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics\/copy(with:)","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics\/copy(with:)","abstract":[{"type":"text","text":"Creates a deep copy of the "},{"type":"codeVoice","code":"SBSDKDocumentDetectionMetrics"},{"type":"text","text":" instance."}],"role":"symbol","title":"copy(with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}]},"doc://net.doo.ScanbotDocumentScannerSDK/documentation/ScanbotDocumentScannerSDK/SBSDKDocumentDetectionMetrics":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SBSDKDocumentDetectionMetrics","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetectionMetrics","url":"\/documentation\/scanbotdocumentscannersdk\/sbsdkdocumentdetectionmetrics","abstract":[{"text":"The metrics and additional properties returned by ","type":"text"},{"type":"reference","identifier":"doc:\/\/net.doo.ScanbotDocumentScannerSDK\/documentation\/ScanbotDocumentScannerSDK\/SBSDKDocumentDetector","isActive":true},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Can be used to make decisions on polygon acceptance, automatic capturing and user guidance.","type":"text"}],"title":"SBSDKDocumentDetectionMetrics","role":"symbol","navigatorTitle":[{"text":"SBSDKDocumentDetectionMetrics","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"copyWithZone:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"zone","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SBSDKDocumentDetector","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/title"},{"value":[{"text":"SBSDKDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/fragments"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetector\/navigatorTitle"},{"value":"copyWithZone:","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1copy(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics~1copy(with:)\/fragments"},{"value":"SBSDKDocumentDetectionMetrics","op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics\/title"},{"value":[{"kind":"identifier","text":"SBSDKDocumentDetectionMetrics"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics\/fragments"},{"value":[{"text":"SBSDKDocumentDetectionMetrics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotDocumentScannerSDK~1documentation~1ScanbotDocumentScannerSDK~1SBSDKDocumentDetectionMetrics\/navigatorTitle"}]}]}