{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior"]]},"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior\/init(rawValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"externalID":"s:10ScanbotSDK28SBSDKUpcEanExtensionBehaviorO8rawValueACSgSi_tcfc","modules":[{"name":"ScanbotSDK"}],"roleHeading":"Initializer","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init"},"variants":[{"paths":["\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior","title":"SBSDKUpcEanExtensionBehavior","url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior","kind":"symbol","abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior/init(rawValue:)":{"title":"init(rawValue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior\/init(rawValue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/init(rawvalue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SBSDKUpcEanExtensionBehavior","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle"}]}]}