{"hierarchy":{"paths":[["doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior"]]},"abstract":[{"type":"text","text":"Only barcodes with either a 2-digit or a 5-digit extension are accepted."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requireAny","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior\/requireAny","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/requireany"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/requireany"]}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requireAny","kind":"identifier"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorRequireAny"}],"externalID":"c:@M@ScanbotSDK@E@SBSDKUpcEanExtensionBehavior@SBSDKUpcEanExtensionBehaviorRequireAny","symbolKind":"case","title":"SBSDKUpcEanExtensionBehavior.requireAny","modules":[{"name":"ScanbotSDK"}]},"references":{"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehavior"}],"identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior","title":"SBSDKUpcEanExtensionBehavior","url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior","kind":"symbol","abstract":[{"type":"text","text":"Behavior when scanning UPC\/EAN barcodes with EAN-2 or EAN-5 extensions."}],"type":"topic"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK/SBSDKUpcEanExtensionBehavior/requireAny":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requireAny"}],"type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK\/SBSDKUpcEanExtensionBehavior\/requireAny","url":"\/documentation\/scanbotsdk\/sbsdkupceanextensionbehavior\/requireany","abstract":[{"text":"Only barcodes with either a 2-digit or a 5-digit extension are accepted.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SBSDKUpcEanExtensionBehaviorRequireAny"}],"title":"SBSDKUpcEanExtensionBehavior.requireAny","kind":"symbol"},"doc://net.doo.ScanbotSDK/documentation/ScanbotSDK":{"url":"\/documentation\/scanbotsdk","abstract":[{"type":"text","text":"Version: 7.1.4"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/net.doo.ScanbotSDK\/documentation\/ScanbotSDK","title":"ScanbotSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SBSDKUpcEanExtensionBehaviorRequireAny"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorRequireAny","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SBSDKUpcEanExtensionBehaviorRequireAny","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/title","value":"SBSDKUpcEanExtensionBehavior","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior\/navigatorTitle","value":[{"text":"SBSDKUpcEanExtensionBehavior","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior~1requireAny\/title","value":"SBSDKUpcEanExtensionBehaviorRequireAny"},{"op":"replace","path":"\/references\/doc:~1~1net.doo.ScanbotSDK~1documentation~1ScanbotSDK~1SBSDKUpcEanExtensionBehavior~1requireAny\/fragments","value":[{"text":"SBSDKUpcEanExtensionBehaviorRequireAny","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}